# Data merge and feature engineering

In [1]:
%pip install pyarrow

Requirement already satisfied: pyarrow in c:\users\uw11\appdata\local\programs\python\python313\lib\site-packages (23.0.1)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.3.1 -> 26.0.1
[notice] To update, run: C:\Users\Uw11\AppData\Local\Programs\Python\Python313\python.exe -m pip install --upgrade pip

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import string

import re
import nltk
from nltk.stem import WordNetLemmatizer
from nltk.corpus import stopwords
from sklearn.feature_extraction.text import TfidfVectorizer
from tqdm.notebook import tqdm
from tqdm import tqdm
import pymorphy3
from collections import Counter

import os
from pathlib import Path
import json

In [3]:
df_weather = pd.read_csv("../data/weather_processed.csv")
df_war_events = pd.read_csv("../data/war_events_processed.csv")
df_isw_matrix = pd.read_csv("../data/isw_processed_svd.csv")

In [4]:
pd.set_option('display.max_columns', None)

In [5]:
df_weather['datetime_hour'] = pd.to_datetime(df_weather['datetime_hour'], errors="coerce")
df_war_events['datetime_hour'] = pd.to_datetime(df_war_events['datetime_hour'], errors="coerce")

In [6]:
df_final = pd.merge(
    df_weather, 
    df_war_events[['datetime_hour', 'region_id', 'alarm_active', 'alarm_minutes_in_hour']], 
    on=['datetime_hour', 'region_id'], 
    how='left'
)
df_final.sample(20)

,datetime_hour,region_id,city_latitude,city_longitude,day_temp,day_dew,day_humidity,day_precip,day_precipprob,day_precipcover,day_snow,day_snowdepth,day_windgust,day_windspeed,day_winddir,day_pressure,day_cloudcover,day_solarradiation,day_solarenergy,day_uvindex,day_moonphase,hour_temp,hour_feelslike,hour_humidity,hour_precip,hour_precipprob,hour_snow,hour_windgust,hour_windspeed,hour_winddir,hour_pressure,hour_cloudcover,hour_solarradiation,hour_solarenergy,hour_uvindex,day_conditions_simple_Clear,day_conditions_simple_Cloudy,day_conditions_simple_Rain,day_conditions_simple_Snow,hour_conditions_simple_Clear,hour_conditions_simple_Cloudy,hour_conditions_simple_Rain,hour_conditions_simple_Snow,year,month,day_of_week,hour,city_name,city_timezone,day_datetime,day_sunrise,day_sunset,hour_datetime,region_key,alarm_active,alarm_minutes_in_hour
261180,2023-05-23 12:00:00,15,46.47250,30.73710,18.7,13.6,73.5,1.2,100.0,12.50,0.0,0.0,29.2,14.8,8.2,1012.1,45.8,242.2,21.1,8.0,0.12,21.1,21.1,65.56,0.0,0.0,0.0,26.3,3.6,100.0,1012.1,90.0,738.7,2.7,7.0,False,False,True,False,False,True,False,False,2023,5,1,12,Odesa,Europe/Kiev,2023-05-23,05:15:26,20:32:53,12:00:00,Одеська,0,0.000000
558772,2024-10-21 05:00:00,6,50.25360,28.66540,5.1,0.2,74.8,0.0,0.0,0.00,0.0,0.0,11.5,7.2,215.9,1034.0,22.3,0.0,0.0,0.0,0.63,-0.7,-0.7,99.27,0.0,0.0,0.0,5.0,3.2,263.7,1035.0,53.2,5.6,0.1,0.0,False,True,False,False,False,True,False,False,2024,10,0,5,Zhytomyr,Europe/Kiev,2024-10-21,07:37:51,18:01:13,05:00:00,Житомирська,1,13.633333
195306,2023-01-29 02:00:00,21,46.64010,32.61420,-1.5,-2.8,90.4,0.5,100.0,4.17,1.8,3.0,41.0,25.2,5.8,1014.8,98.5,26.0,2.2,1.0,0.25,-1.4,-6.5,97.10,0.0,0.0,0.2,29.2,16.9,12.5,1013.0,99.3,0.0,0.0,0.0,False,False,False,True,False,True,False,False,2023,1,6,2,Kherson,Europe/Kiev,2023-01-29,07:17:44,16:48:05,02:00:00,Херсонська,0,0.000000
499634,2024-07-10 13:00:00,4,48.47530,35.01600,29.4,14.0,42.1,0.0,0.0,0.00,0.0,0.0,32.4,18.0,63.4,1016.7,44.0,308.6,26.5,9.0,0.14,35.2,33.5,22.16,0.0,0.0,0.0,29.5,11.9,68.6,1017.0,40.1,852.1,3.1,9.0,False,True,False,False,False,True,False,False,2024,7,2,13,Dnipro,Europe/Kiev,2024-07-10,04:49:36,20:40:47,13:00:00,Дніпропетровська,0,0.000000
49441,2022-05-20 21:00:00,3,50.74690,25.32630,16.4,3.2,45.4,0.0,0.0,0.00,0.0,0.0,28.1,26.5,232.1,1021.0,64.4,255.8,22.3,7.0,0.64,22.1,22.1,40.19,0.0,0.0,0.0,11.2,13.6,256.0,1013.6,47.7,35.0,0.1,0.0,False,True,False,False,False,True,False,False,2022,5,4,21,Lutsk,Europe/Kiev,2022-05-20,05:23:28,21:07:56,21:00:00,Волинська,0,0.000000
232213,2023-04-03 05:00:00,16,49.58790,34.55170,7.4,5.8,89.4,8.0,100.0,8.33,0.0,0.0,32.0,19.4,71.5,1007.6,99.3,33.6,3.0,1.0,0.41,6.9,3.6,85.88,0.0,0.0,0.0,29.5,18.4,85.6,1006.0,100.0,0.0,0.0,0.0,False,False,True,False,False,True,False,False,2023,4,0,5,Poltava,Europe/Kiev,2023-04-03,06:15:33,19:15:49,05:00:00,Полтавська,0,0.000000
295691,2023-07-22 10:00:00,14,46.97340,31.98520,23.3,15.4,64.7,0.6,100.0,4.17,0.0,0.0,42.5,21.6,169.0,1014.0,42.2,212.3,18.3,7.0,0.15,24.7,24.7,52.03,0.0,0.0,0.0,32.8,16.6,149.0,1014.0,44.5,488.8,1.8,5.0,False,False,True,False,False,True,False,False,2023,7,5,10,Mykolaiv,Europe/Kiev,2023-07-22,05:19:14,20:37:14,10:00:00,Миколаївська,0,0.000000
59198,2022-06-06 19:00:00,17,50.61927,26.25131,18.3,11.5,68.9,0.0,0.0,0.00,0.0,0.0,15.5,8.3,101.8,1019.1,58.6,294.0,25.4,9.0,0.22,23.0,23.0,45.50,0.0,0.0,0.0,15.1,7.9,121.6,1017.0,59.6,249.0,0.9,2.0,False,True,False,False,False,True,False,False,2022,6,0,19,Rivne,Europe/Kiev,2022-06-06,05:04:55,21:22:59,19:00:00,Рівненська,0,0.000000
323784,2023-09-09 05:00:00,2,49.23360,28.44860,16.4,9.4,66.4,0.0,0.0,0.00,0.0,0.0,35.3,14.4,4.4,1020.8,42.3,202.2,17.4,7.0,0.81,10.8,10.8,84.54,0.0,0.0,0.0,13.3,9.4,323.2,1019.0,45.5,0.0,0.0,0.0,False,True,False,False,False,True,False,False,2023,9,5,5,Vinnytsia,Europe/Kiev,2023-09-09,06:33:12,19:33:16,05:00:00,Вінницька,0,0.000000
633098,2025-02-27 06:00:00,4,48.47530,35.01600,-4.1,-9.0,70.8,0.0,0.0,0.00,0.0,0.5,19.8,7.2,143.8,1029.6,3.8,151.4,13.1,5.0,0.98,-10.6,-14.5,89.43,0.0,0.0,0.0,10.4,6.5,134.5,1030.0,0.5,0.0,0.0,0.0,True,False,False,False,True,False,False,False,2025,2,3,6,Dnipro,Europe/Kiev,2025-02-27,06:25:15,17:20:51,06:00:00,Дніпропетровська,0,0.000000
443832,2024-04-04 16:00:00,2,49.23360,28.44860,11.1,2.6,56.5,0.0,0.0,0.00,0.0,0.0,36.0,16.2,283.4,1014.0,91.6,179.6,15.4,6.0,0.85,14.2,14.2,46.85,0.0,0.0,0.0,30.6,12.2,298.0,1015.0,96.8,499.8,1.8,5.0,False,True,False,False,False,True,False,False,2024,4,3,16,Vinnytsia,Europe/Kiev,2024-04-04,06:36:35,19:42:35,16:00:00,Вінницька,0,0.000000
334160,2023-09-27 05:00:00,10,50.45060,30.52430,16.8,11.9,75.9,0.0,0.0,0.00,0.0,0.0,22.7,9.0,32.8,1028.2,4.2,169.6,14.6,6.0,0.43,11.0,11.0,98.03,0.0,0.0,0.0,11.9,6.1,41.4,1029.0,4.8,0.0,0.0,0.0,True,False,False,False,True,False,False,False,2023,9,2,5,Kyiv,Europe/Kiev,2023-09-27,06:51:09,18:46:03,05:00:00,Київська,0,0.000000
1656,2022-02-26 21:00:00,2,49.23360,28.44860,2.5,-3.4,67.7,0.0,0.0,0.00,0.0,0.0,35.6,18.0,354.6,1025.8,74.4,103.7,9.2,3.0,0.84,1.2,1.2,63.32,0.0,0.0,0.0,11.2,4.7,351.3,1030.0,12.8,0.0,0.1,0.0,False,True,False,False,True,False,False,False,2022,2,5,21,Vinnytsia,Europe/Kiev,2022-02-26,06:54:55,17:44:08,21:00:00,Вінницька,1,18.400000
377199,2023-12-10 22:00:00,18,50.90800,34.79720,-4.2,-5.2,93.0,0.1,100.0,4.17,0.0,14.5,27.4,14.3,113.2,1022.3,99.3,18.8,1.6,1.0,0.92,-4.6,-9.8,93.42,0.0,0.0,0.0,22.7,13.7,127.5,1024.0,100.0,0.0,0.0,0.0,False,False,False,True,False,True,False,False,2023,12,6,22,Sumy,Europe/Kiev,2023-12-10,07:32:03,15:34:44,22:00:00,Сумська,0,0.000000
548896,2024-10-04 01:00:00,19,49.55270,25.58890,13.2,12.4,95.0,4.0,100.0,4.17,0.0,0.0,19.4,10.8,71.0,1010.8,98.2,19.4,1.8,1.0,0.05,11.8,11.8,94.84,0.0,0.0,0.0,14.8,8.3,41.4,1012.0,100.0,0.0,0.0,0.0,False,False,True,False,False,True,False,False,2024,10,4,1,Ternopil,Europe/Kiev,2024-10-04,07:22:26,18:49:17,01:00:00,Тернопільська,0,0.000000
98320,2022-08-13 17:00:00,19,49.55270,25.58890,19.4,17.9,90.8,38.0,100.0,8.33,0.0,0.0,30.6,14.4,40.9,1014.3,96.0,194.7,16.9,8.0,0.51,21.0,21.0,89.46,0.0,0.0,0.0,20.2,9.7,48.9,1013.0,100.0,350.0,1.3,4.0,False,False,True,False,False,True,False,False,2022,8,5,17,Ternopil,Europe/Kiev,2022-08-13,06:05:18,20:38:51,17:00:00,Тернопільська,0,0.000000
417958,2024-02-19 16:00:00,25,51.49370,31.29440,-2.0,-7.9,66.9,0.0,0.0,0.00,0.0,0.0,20.9,11.2,79.0,1030.1,62.0,107.1,9.3,4.0,0.32,0.1,-1.9,44.78,0.0,0.0,0.0,14.8,5.8,119.8,1029.0,100.0,169.3,0.6,2.0,False,True,False,False,False,True,False,False,2024,2,0,16,Chernihiv,Europe/Kiev,2024-02-19,07:02:09,17:16:09,16:00:00,Чернігівська,0,0.000000
16497,2022-03-24 15:00:00,11,48.50850,32.26560,7.0,-3.8,48.2,0.0,0.0,0.00,0.0,0.0,35.6,21.6,291.3,1018.1,11.4,207.4,17.9,7.0,0.72,15.4,15.4,35.74,0.0,0.0,0.0,31.0,17.6,314.3,1014.0,62.5,518.0,1.9,5.0,True,False,False,False,False,True,False,False,2022,3,3,15,Kropyvnytskyi,Europe/Kiev,2022-03-24,05:45:56,18:09:28,15:00:00,Кіровоградська,0,0.000000
102524,2022-08-21 00:00:00,23,49.44070,32.06370,22.7,17.0,71.5,0.0,0.0,0.00,0.0,0.0,30.6,16.6,91.2,1011.5,29.0,206.2,17.8,8.0,0.78,21.1,21.1,84.05,0.0,0.0,0.0,28.4,14.0,107.3,1012.0,32.5,0.0,0.1,0.0,False,True,False,False,False,True,False,False,2022,8,6,0,Cherkasy,Europe/Kiev,2022-08-21,05:51:15,19:57:40,00:00:00,Черкаська,0,0.000000
233392,2023-04-05 06:00:00,19,49.55270,25.58890,0.0,-3.3,79.6,5.0,100.0,8.33,1.6,2.9,41.0,25.2,345.1,1018.9,98.1,157.9,13.5,6.0,0.47,-2.1,-7.6,91.48,0.0,0.0,0.0,27.7,18.0,330.0,1019.3,100.0,0.0,0.0,0.0,False,False,False,True,False,True,False,False,2023,4,2,6,Ternopil,Europe/Kiev,2023-04-05,06:47:09,19:54:45,06:00:00,Тернопільська,0,0.000000

In [7]:
df_final = df_final.sort_values(['region_id', 'datetime_hour'])
df_final.head()

,datetime_hour,region_id,city_latitude,city_longitude,day_temp,day_dew,day_humidity,day_precip,day_precipprob,day_precipcover,day_snow,day_snowdepth,day_windgust,day_windspeed,day_winddir,day_pressure,day_cloudcover,day_solarradiation,day_solarenergy,day_uvindex,day_moonphase,hour_temp,hour_feelslike,hour_humidity,hour_precip,hour_precipprob,hour_snow,hour_windgust,hour_windspeed,hour_winddir,hour_pressure,hour_cloudcover,hour_solarradiation,hour_solarenergy,hour_uvindex,day_conditions_simple_Clear,day_conditions_simple_Cloudy,day_conditions_simple_Rain,day_conditions_simple_Snow,hour_conditions_simple_Clear,hour_conditions_simple_Cloudy,hour_conditions_simple_Rain,hour_conditions_simple_Snow,year,month,day_of_week,hour,city_name,city_timezone,day_datetime,day_sunrise,day_sunset,hour_datetime,region_key,alarm_active,alarm_minutes_in_hour
0,2022-02-24 00:00:00,2,49.2336,28.4486,2.8,-0.3,80.5,0.3,100.0,4.17,0.0,0.0,27.7,10.8,312.0,1023.4,82.5,60.4,5.4,3.0,0.77,2.1,-0.5,91.76,0.0,0.0,0.0,16.6,8.6,279.6,1021.0,91.1,0.0,0.1,0.0,False,False,False,True,False,True,False,False,2022,2,3,0,Vinnytsia,Europe/Kiev,2022-02-24,06:58:49,17:40:52,00:00:00,Вінницька,0,0.0
24,2022-02-24 01:00:00,2,49.2336,28.4486,2.8,-0.3,80.5,0.3,100.0,4.17,0.0,0.0,27.7,10.8,312.0,1023.4,82.5,60.4,5.4,3.0,0.77,2.1,-0.4,89.80,0.0,0.0,0.0,16.6,8.3,289.2,1021.0,97.9,0.0,0.1,0.0,False,False,False,True,False,True,False,False,2022,2,3,1,Vinnytsia,Europe/Kiev,2022-02-24,06:58:49,17:40:52,01:00:00,Вінницька,0,0.0
48,2022-02-24 02:00:00,2,49.2336,28.4486,2.8,-0.3,80.5,0.3,100.0,4.17,0.0,0.0,27.7,10.8,312.0,1023.4,82.5,60.4,5.4,3.0,0.77,2.0,-0.3,90.44,0.0,0.0,0.0,27.7,7.6,287.6,1021.0,98.2,0.0,0.1,0.0,False,False,False,True,False,True,False,False,2022,2,3,2,Vinnytsia,Europe/Kiev,2022-02-24,06:58:49,17:40:52,02:00:00,Вінницька,0,0.0
72,2022-02-24 03:00:00,2,49.2336,28.4486,2.8,-0.3,80.5,0.3,100.0,4.17,0.0,0.0,27.7,10.8,312.0,1023.4,82.5,60.4,5.4,3.0,0.77,1.9,-0.3,91.75,0.0,0.0,0.0,15.1,7.2,288.9,1021.0,98.8,0.0,0.1,0.0,False,False,False,True,False,True,False,False,2022,2,3,3,Vinnytsia,Europe/Kiev,2022-02-24,06:58:49,17:40:52,03:00:00,Вінницька,0,0.0
96,2022-02-24 04:00:00,2,49.2336,28.4486,2.8,-0.3,80.5,0.3,100.0,4.17,0.0,0.0,27.7,10.8,312.0,1023.4,82.5,60.4,5.4,3.0,0.77,1.8,-0.2,92.40,0.0,0.0,0.0,13.7,6.5,290.4,1021.0,100.0,0.0,0.1,0.0,False,False,False,True,False,True,False,False,2022,2,3,4,Vinnytsia,Europe/Kiev,2022-02-24,06:58:49,17:40:52,04:00:00,Вінницька,0,0.0

In [8]:
df_final.info()

<class 'pandas.DataFrame'>
Index: 634680 entries, 0 to 634679
Data columns (total 56 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   datetime_hour                  634680 non-null  datetime64[us]
 1   region_id                      634680 non-null  int64
 2   city_latitude                  634680 non-null  float64
 3   city_longitude                 634680 non-null  float64
 4   day_temp                       634680 non-null  float64
 5   day_dew                        634680 non-null  float64
 6   day_humidity                   634680 non-null  float64
 7   day_precip                     634680 non-null  float64
 8   day_precipprob                 634680 non-null  float64
 9   day_precipcover                634680 non-null  float64
 10  day_snow                       634680 non-null  float64
 11  day_snowdepth                  634680 non-null  float64
 12  day_windgust                   634680 non-null  float64
 13  day_windspeed                  634680 non-null  float64
 14  day_winddir                    634680 non-null  float64
 15  day_pressure                   634680 non-null  float64
 16  day_cloudcover                 634680 non-null  float64
 17  day_solarradiation             634680 non-null  float64
 18  day_solarenergy                634680 non-null  float64
 19  day_uvindex                    634680 non-null  float64
 20  day_moonphase                  634680 non-null  float64
 21  hour_temp                      634680 non-null  float64
 22  hour_feelslike                 634680 non-null  float64
 23  hour_humidity                  634680 non-null  float64
 24  hour_precip                    634680 non-null  float64
 25  hour_precipprob                634680 non-null  float64
 26  hour_snow                      634680 non-null  float64
 27  hour_windgust                  634680 non-null  float64
 28  hour_windspeed                 634680 non-null  float64
 29  hour_winddir                   634680 non-null  float64
 30  hour_pressure                  634680 non-null  float64
 31  hour_cloudcover                634680 non-null  float64
 32  hour_solarradiation            634680 non-null  float64
 33  hour_solarenergy               634680 non-null  float64
 34  hour_uvindex                   634680 non-null  float64
 35  day_conditions_simple_Clear    634680 non-null  bool
 36  day_conditions_simple_Cloudy   634680 non-null  bool
 37  day_conditions_simple_Rain     634680 non-null  bool
 38  day_conditions_simple_Snow     634680 non-null  bool
 39  hour_conditions_simple_Clear   634680 non-null  bool
 40  hour_conditions_simple_Cloudy  634680 non-null  bool
 41  hour_conditions_simple_Rain    634680 non-null  bool
 42  hour_conditions_simple_Snow    634680 non-null  bool
 43  year                           634680 non-null  int64
 44  month                          634680 non-null  int64
 45  day_of_week                    634680 non-null  int64
 46  hour                           634680 non-null  int64
 47  city_name                      634680 non-null  str
 48  city_timezone                  634680 non-null  str
 49  day_datetime                   634680 non-null  str
 50  day_sunrise                    634680 non-null  str
 51  day_sunset                     634680 non-null  str
 52  hour_datetime                  634680 non-null  str
 53  region_key                     634680 non-null  str
 54  alarm_active                   634680 non-null  int64
 55  alarm_minutes_in_hour          634680 non-null  float64
dtypes: bool(8), datetime64[us](1), float64(34), int64(6), str(7)
memory usage: 287.3 MB

In [9]:
df_final = df_final.sort_values(["region_id", "datetime_hour"])

df_final["alarm_lag_1"] = df_final.groupby("region_id")["alarm_active"].shift(1)
df_final["alarm_lag_3"] = df_final.groupby("region_id")["alarm_active"].shift(3)
df_final["alarm_lag_6"] = df_final.groupby("region_id")["alarm_active"].shift(6)
df_final["alarm_lag_12"] = df_final.groupby("region_id")["alarm_active"].shift(12)
#df_final['alarm_minutes_lag1'] = (df_final.groupby('region_id')['alarm_minutes_in_hour'].shift(1).fillna(0))
#df_final['alarm_minutes_lag3'] = (df_final.groupby('region_id')['alarm_minutes_in_hour'].shift(3).fillna(0))

lag_cols = ["alarm_lag_1","alarm_lag_3","alarm_lag_6","alarm_lag_12"]
df_final[lag_cols] = df_final[lag_cols].fillna(0)

df_final['alarms_in_last_24h'] = (df_final.groupby('region_id')['alarm_active'].transform(lambda x: x.shift(1).rolling(24, min_periods=1).sum()))

df_final['is_weekend'] = df_final['day_of_week'].isin([5, 6]).astype(int)
df_final['is_night'] = ((df_final['hour'] >= 23) | (df_final['hour'] <= 6)).astype(int)

hourly_total = df_final.groupby('datetime_hour')['alarm_active'].sum().shift(1)
df_final['total_active_alarms_lag1'] = df_final['datetime_hour'].map(hourly_total)

df_final.sample(10)

,datetime_hour,region_id,city_latitude,city_longitude,day_temp,day_dew,day_humidity,day_precip,day_precipprob,day_precipcover,day_snow,day_snowdepth,day_windgust,day_windspeed,day_winddir,day_pressure,day_cloudcover,day_solarradiation,day_solarenergy,day_uvindex,day_moonphase,hour_temp,hour_feelslike,hour_humidity,hour_precip,hour_precipprob,hour_snow,hour_windgust,hour_windspeed,hour_winddir,hour_pressure,hour_cloudcover,hour_solarradiation,hour_solarenergy,hour_uvindex,day_conditions_simple_Clear,day_conditions_simple_Cloudy,day_conditions_simple_Rain,day_conditions_simple_Snow,hour_conditions_simple_Clear,hour_conditions_simple_Cloudy,hour_conditions_simple_Rain,hour_conditions_simple_Snow,year,month,day_of_week,hour,city_name,city_timezone,day_datetime,day_sunrise,day_sunset,hour_datetime,region_key,alarm_active,alarm_minutes_in_hour,alarm_lag_1,alarm_lag_3,alarm_lag_6,alarm_lag_12,alarms_in_last_24h,is_weekend,is_night,total_active_alarms_lag1
5106,2022-03-04 20:00:00,21,46.64010,32.61420,2.7,0.0,83.5,0.1,100.0,4.17,0.0,0.0,37.8,24.8,293.4,1011.1,80.4,92.4,6.6,3.0,0.04,2.0,-1.7,89.14,0.0,0.0,0.0,30.6,13.3,267.8,1012.0,78.9,5.6,0.1,0.0,False,False,False,True,False,True,False,False,2022,3,4,20,Kherson,Europe/Kiev,2022-03-04,06:23:55,17:39:26,20:00:00,Херсонська,0,0.000000,0.0,0.0,0.0,0.0,0.0,0,0,3.0
359600,2023-11-10 09:00:00,10,50.45060,30.52430,6.2,3.1,82.2,0.0,0.0,0.00,0.0,0.0,42.5,21.2,169.2,1018.7,62.8,69.7,5.9,3.0,0.90,1.7,-2.6,94.42,0.0,0.0,0.0,28.8,16.2,162.9,1021.0,97.8,118.2,0.4,1.0,False,True,False,False,False,True,False,False,2023,11,4,9,Kyiv,Europe/Kiev,2023-11-10,07:03:11,16:19:46,09:00:00,Київська,0,0.000000,0.0,0.0,1.0,0.0,3.0,0,0,0.0
607778,2025-01-14 07:00:00,4,48.47530,35.01600,-1.6,-4.9,78.7,0.0,0.0,0.00,0.0,0.0,30.6,18.0,271.4,1031.8,82.1,32.6,2.9,2.0,0.50,-2.5,-6.3,81.69,0.0,0.0,0.0,19.8,9.7,288.1,1033.0,93.7,0.0,0.0,0.0,False,True,False,False,False,True,False,False,2025,1,1,7,Dnipro,Europe/Kiev,2025-01-14,07:27:22,16:11:12,07:00:00,Дніпропетровська,0,0.000000,1.0,1.0,1.0,1.0,13.0,0,0,4.0
505928,2024-07-21 11:00:00,10,50.45060,30.52430,23.3,14.9,62.6,0.0,0.0,0.00,0.0,0.0,16.6,6.5,193.9,1010.4,86.5,214.0,18.6,6.0,0.50,27.9,27.7,42.24,0.0,0.0,0.0,16.2,5.0,213.1,1011.0,96.0,618.9,2.2,6.0,False,True,False,False,False,True,False,False,2024,7,6,11,Kyiv,Europe/Kiev,2024-07-21,05:11:06,20:56:56,11:00:00,Київська,0,0.000000,0.0,0.0,0.0,0.0,4.0,1,0,3.0
202426,2023-02-10 11:00:00,13,49.84440,24.02540,-4.3,-9.0,70.6,0.0,0.0,0.00,0.0,9.4,34.6,21.6,251.5,1035.7,63.0,103.8,8.9,4.0,0.66,-3.1,-8.2,62.27,0.0,0.0,0.0,32.8,14.4,260.0,1036.0,30.0,312.3,1.1,3.0,False,True,False,False,False,True,False,False,2023,2,4,11,Lviv,Europe/Kiev,2023-02-10,07:43:35,17:33:25,11:00:00,Львівська,1,58.983333,1.0,1.0,0.0,0.0,3.0,0,0,24.0
616408,2025-01-29 06:00:00,19,49.55270,25.58890,7.1,3.4,79.3,0.4,100.0,4.17,0.0,0.0,41.0,18.4,197.8,1012.6,48.7,61.1,5.3,3.0,0.00,4.0,0.7,94.52,0.0,0.0,0.0,19.4,13.7,171.1,1009.0,98.1,0.0,0.0,0.0,False,False,True,False,False,True,False,False,2025,1,2,6,Ternopil,Europe/Kiev,2025-01-29,07:53:51,17:08:26,06:00:00,Тернопільська,0,0.000000,0.0,0.0,0.0,0.0,1.0,0,1,8.0
375805,2023-12-08 12:00:00,16,49.58790,34.55170,-2.4,-3.7,91.3,7.0,100.0,8.33,5.8,4.6,42.5,24.5,95.0,1023.9,100.0,10.2,0.9,0.0,0.85,-2.4,-8.1,93.53,0.0,0.0,0.2,36.4,18.7,85.7,1024.0,100.0,48.9,0.2,0.0,False,False,False,True,False,True,False,False,2023,12,4,12,Poltava,Europe/Kiev,2023-12-08,07:24:51,15:42:05,12:00:00,Полтавська,0,0.000000,0.0,0.0,1.0,0.0,11.0,0,0,1.0
171616,2022-12-18 23:00:00,19,49.55270,25.58890,-5.9,-7.9,86.1,0.2,100.0,8.33,0.0,5.5,45.0,27.4,306.6,1034.5,97.1,55.0,4.9,3.0,0.81,-8.1,-13.2,88.24,0.0,0.0,0.0,18.4,10.4,326.9,1042.0,100.0,0.0,0.1,0.0,False,False,False,True,False,True,False,False,2022,12,6,23,Ternopil,Europe/Kiev,2022-12-18,08:09:43,16:18:41,23:00:00,Тернопільська,0,0.000000,0.0,0.0,0.0,0.0,0.0,1,1,0.0
30101,2022-04-17 07:00:00,7,48.62636,22.28514,5.0,-4.0,53.5,0.0,0.0,0.00,0.0,2.5,47.2,22.5,14.0,1024.5,34.8,262.5,22.6,8.0,0.53,0.3,-2.9,73.65,0.0,0.0,0.0,13.3,10.0,349.0,1025.9,10.0,3.0,0.0,0.0,False,True,False,False,True,False,False,False,2022,4,6,7,Uzhgorod,Europe/Uzhgorod,2022-04-17,06:36:53,20:25:02,07:00:00,Закарпатська,0,0.000000,1.0,0.0,0.0,0.0,4.0,1,0,22.0
631443,2025-02-24 09:00:00,5,48.00200,37.81450,-6.1,-9.1,80.0,1.5,100.0,45.83,1.0,5.1,39.2,19.1,330.1,1023.0,77.8,85.5,7.3,4.0,0.88,-7.0,-13.4,83.64,0.1,100.0,0.1,36.7,16.6,345.2,1024.0,100.0,164.4,0.6,2.0,False,False,False,True,False,False,False,True,2025,2,0,9,Donetsk,Europe/Kiev,2025-02-24,06:19:08,17:05:34,09:00:00,Донецька,0,0.000000,0.0,0.0,0.0,0.0,7.0,0,0,1.0

In [10]:
neighbouring_regions = {
    1: [21],
    2: [6, 10, 11, 15, 22, 23, 24],
    3: [13, 17],
    4: [5, 8, 11, 14, 16, 20, 21],
    5: [4, 8, 12, 20],
    6: [2, 10, 17, 22],
    7: [9, 13],
    8: [4, 5, 21],
    9: [7, 13, 19, 24],
    10: [2, 6, 16, 23, 25],
    11: [2, 4, 14, 15, 16, 23],
    12: [5, 20],
    13: [3, 7, 9, 17, 19],
    14: [4, 11, 15, 21],
    15: [2, 11, 14],
    16: [4, 10, 11, 18, 20, 23, 25],
    17: [3, 6, 13, 19, 22],
    18: [16, 20, 25],
    19: [9, 13, 17, 22, 24],
    20: [4, 5, 12, 16, 18],
    21: [1, 4, 8, 14],
    22: [2, 6, 17, 19, 24],
    23: [2, 10, 11, 16],
    24: [2, 9, 19, 22],
    25: [10, 16, 18], 
    26: [10]
}

alarms_matrix = df_final.pivot_table(
    index='datetime_hour',
    columns='region_id',
    values='alarm_active',
    fill_value=0
)

neighbour_alarm_matrix = pd.DataFrame(index=alarms_matrix.index)

for region, neighbours in neighbouring_regions.items():
    valid_neighbours = [n for n in neighbours if n in alarms_matrix.columns]
    
    if valid_neighbours:
        neighbour_alarm_matrix[region] = alarms_matrix[valid_neighbours].sum(axis=1)
    else:
        neighbour_alarm_matrix[region] = 0

neighbour_alarm_matrix = neighbour_alarm_matrix.shift(1)

neighbour_alarm_long = (neighbour_alarm_matrix.stack().reset_index())

neighbour_alarm_long.columns = ['datetime_hour','region_id','neighbour_alarms']

df_final = df_final.merge(neighbour_alarm_long,on=['datetime_hour', 'region_id'], how='left')

In [11]:
def hours_since_last_alarm(series):
    shifted = series.shift(1).fillna(0)
    result = []
    count = 0
    for val in shifted:
        if val == 1:
            count = 0
        else:
            count += 1
        result.append(count)
    return pd.Series(result, index=series.index)

df_final['hours_since_last_alarm'] = (df_final.groupby('region_id')['alarm_active'].transform(hours_since_last_alarm))

In [12]:
df_final.sample(20)

,datetime_hour,region_id,city_latitude,city_longitude,day_temp,day_dew,day_humidity,day_precip,day_precipprob,day_precipcover,day_snow,day_snowdepth,day_windgust,day_windspeed,day_winddir,day_pressure,day_cloudcover,day_solarradiation,day_solarenergy,day_uvindex,day_moonphase,hour_temp,hour_feelslike,hour_humidity,hour_precip,hour_precipprob,hour_snow,hour_windgust,hour_windspeed,hour_winddir,hour_pressure,hour_cloudcover,hour_solarradiation,hour_solarenergy,hour_uvindex,day_conditions_simple_Clear,day_conditions_simple_Cloudy,day_conditions_simple_Rain,day_conditions_simple_Snow,hour_conditions_simple_Clear,hour_conditions_simple_Cloudy,hour_conditions_simple_Rain,hour_conditions_simple_Snow,year,month,day_of_week,hour,city_name,city_timezone,day_datetime,day_sunrise,day_sunset,hour_datetime,region_key,alarm_active,alarm_minutes_in_hour,alarm_lag_1,alarm_lag_3,alarm_lag_6,alarm_lag_12,alarms_in_last_24h,is_weekend,is_night,total_active_alarms_lag1,neighbour_alarms,hours_since_last_alarm
155353,2024-10-14 19:00:00,7,48.6264,22.2851,7.5,3.0,75.5,0.000,0.0,0.00,0.0,0.0,24.8,9.0,239.3,1018.8,39.4,92.9,8.1,4.0,0.39,8.9,8.0,63.78,0.0,0.0,0.0,12.2,6.8,211.0,1019.6,36.0,15.1,0.1,0.0,False,True,False,False,False,True,False,False,2024,10,0,19,Uzhgorod,Europe/Uzhgorod,2024-10-14,07:49:53,18:42:56,19:00:00,Закарпатська,0,0.000000,0.0,0.0,0.0,0.0,0.0,0,0,0.0,0.0,67
227148,2023-12-05 14:00:00,10,50.4506,30.5243,-4.1,-6.1,86.2,0.100,100.0,4.17,0.1,7.2,25.9,14.0,172.2,1025.4,93.0,36.5,3.1,2.0,0.75,-2.3,-5.2,76.90,0.0,0.0,0.0,17.6,7.2,130.0,1025.5,100.0,121.2,0.4,1.0,False,False,False,True,False,True,False,False,2023,12,1,14,Kyiv,Europe/Kiev,2023-12-05,07:41:17,15:55:16,14:00:00,Київська,0,0.000000,0.0,0.0,0.0,0.0,0.0,0,0,3.0,0.0,38
278430,2023-09-29 14:00:00,13,49.8444,24.0254,16.1,10.1,72.0,0.000,0.0,0.00,0.0,0.0,24.8,11.5,167.6,1023.2,3.3,168.5,14.6,6.0,0.50,24.9,24.9,38.48,0.0,0.0,0.0,24.5,11.2,172.7,1023.0,0.0,585.7,2.1,6.0,True,False,False,False,True,False,False,False,2023,9,4,14,Lviv,Europe/Kiev,2023-09-29,07:20:06,19:07:46,14:00:00,Львівська,0,0.000000,0.0,0.0,0.0,0.0,0.0,0,0,4.0,0.0,66
383867,2023-09-15 07:00:00,17,50.6193,26.2513,15.9,12.5,81.5,0.790,100.0,4.17,0.0,0.0,32.8,16.6,354.2,1021.4,84.2,66.3,5.7,2.0,0.00,14.9,14.9,93.13,0.0,0.0,0.0,26.6,13.0,333.6,1020.0,100.0,0.1,0.0,0.0,False,False,True,False,False,True,False,False,2023,9,4,7,Rivne,Europe/Kiev,2023-09-15,06:49:45,19:30:02,07:00:00,Рівненська,1,35.833333,1.0,0.0,0.0,0.0,1.0,0,0,8.0,3.0,0
559846,2022-08-30 14:00:00,24,48.2924,25.9355,20.0,17.5,86.2,0.351,100.0,4.17,0.0,0.0,19.9,10.8,317.4,1018.6,89.3,147.8,12.8,5.0,0.09,21.9,21.9,74.57,0.0,0.0,0.0,16.4,9.4,321.0,1019.4,95.8,253.0,0.9,3.0,False,False,True,False,False,True,False,False,2022,8,1,14,Chernivtsi,Europe/Kiev,2022-08-30,06:30:43,20:02:15,14:00:00,Чернівецька,0,0.000000,0.0,0.0,0.0,0.0,0.0,0,0,1.0,0.0,42
552445,2024-11-01 04:00:00,23,49.4407,32.0637,10.4,6.0,74.4,0.000,0.0,0.00,0.0,0.0,50.8,25.9,262.6,1012.9,76.3,31.2,2.7,1.0,0.00,8.4,5.6,79.72,0.0,0.0,0.0,30.2,17.6,247.3,1016.0,100.0,0.0,0.0,0.0,False,True,False,False,False,True,False,False,2024,11,4,4,Cherkasy,Europe/Kiev,2024-11-01,06:40:33,16:29:26,04:00:00,Черкаська,1,17.366667,0.0,1.0,0.0,0.0,7.0,0,1,8.0,2.0,2
493387,2024-02-18 03:00:00,21,46.6401,32.6142,0.8,0.1,95.1,0.100,100.0,4.17,0.0,0.0,30.2,15.5,288.4,1027.6,92.5,48.4,4.3,2.0,0.29,-0.7,-0.7,91.58,0.0,0.0,0.0,2.5,2.5,251.8,1028.0,94.6,0.0,0.0,0.0,False,False,True,False,False,True,False,False,2024,2,6,3,Kherson,Europe/Kiev,2024-02-18,06:49:40,17:18:07,03:00:00,Херсонська,0,0.000000,0.0,0.0,0.0,1.0,4.0,1,1,5.0,2.0,6
179095,2024-06-24 04:00:00,8,47.8289,35.1626,23.5,16.1,64.6,0.000,0.0,0.00,0.0,0.0,34.2,22.3,320.1,1010.0,49.7,296.9,25.6,8.0,0.58,21.8,21.8,81.53,0.0,0.0,0.0,31.7,18.4,333.7,1010.0,12.9,0.0,0.0,0.0,False,True,False,False,True,False,False,False,2024,6,0,4,Zaporozhye,Europe/Zaporozhye,2024-06-24,04:41:35,20:42:13,04:00:00,Запорізька,0,0.000000,0.0,0.0,1.0,0.0,7.0,0,1,7.0,1.0,1
394552,2024-12-03 13:00:00,17,50.6193,26.2513,0.8,-0.5,91.5,0.000,0.0,0.00,0.0,0.0,24.8,14.3,179.7,1021.8,94.8,25.9,2.3,1.0,0.08,1.4,-2.2,89.74,0.0,0.0,0.0,24.8,12.2,169.8,1021.0,100.0,125.4,0.5,1.0,False,True,False,False,False,True,False,False,2024,12,1,13,Rivne,Europe/Kiev,2024-12-03,07:57:35,16:12:09,13:00:00,Рівненська,0,0.000000,0.0,1.0,0.0,0.0,5.0,0,0,3.0,0.0,1
316193,2025-01-13 05:00:00,14,46.9734,31.9852,-0.5,-2.0,90.1,0.000,0.0,0.00,0.0,0.0,24.8,12.2,328.8,1029.3,59.5,57.5,5.0,3.0,0.48,-0.4,-0.4,100.00,0.0,0.0,0.0,11.5,0.0,293.2,1025.7,4.0,0.0,0.0,0.0,False,True,False,False,True,False,False,False,2025,1,0,5,Mykolaiv,Europe/Kiev,2025-01-13,07:34:35,16:27:29,05:00:00,Миколаївська,1,12.166667,1.0,1.0,1.0,1.0,13.0,0,1,5.0,1.0,0
66753,2023-09-24 17:00:00,4,48.4753,35.0160,20.5,8.3,48.2,0.000,0.0,0.00,0.0,0.0,32.8,21.6,100.9,1021.4,3.3,183.6,15.8,6.0,0.32,26.3,26.3,29.89,0.0,0.0,0.0,29.5,11.9,93.0,1021.0,0.0,262.2,0.9,3.0,True,False,False,False,True,False,False,False,2023,9,6,17,Dnipro,Europe/Kiev,2023-09-24,06:28:38,18:34:46,17:00:00,Дніпропетровська,1,9.900000,0.0,0.0,0.0,0.0,6.0,1,0,3.0,2.0,13
236626,2025-01-03 13:00:00,10,50.4506,30.5243,1.1,-1.8,81.2,1.800,100.0,8.33,0.0,0.0,35.6,19.1,275.9,1008.5,81.1,22.1,1.9,1.0,0.12,1.1,-2.4,83.39,0.0,0.0,0.0,25.9,11.5,308.1,1009.0,100.0,123.2,0.4,1.0,False,False,False,True,False,True,False,False,2025,1,4,13,Kyiv,Europe/Kiev,2025-01-03,07:58:21,16:06:56,13:00:00,Київська,1,38.500000,1.0,1.0,1.0,1.0,16.0,0,0,8.0,3.0,0
519161,2024-01-21 04:00:00,22,49.4168,26.9743,-2.0,-4.4,84.1,0.500,100.0,8.33,0.3,7.7,48.2,28.8,302.0,1031.4,89.5,32.9,3.0,2.0,0.35,-0.8,-7.1,87.60,0.0,0.0,0.0,46.4,25.6,289.4,1025.0,68.0,0.0,0.0,0.0,False,False,False,True,False,True,False,False,2024,1,6,4,Khmelnytskyi,Europe/Kiev,2024-01-21,07:57:55,16:49:08,04:00:00,Хмельницька,0,0.000000,0.0,0.0,0.0,0.0,1.0,1,1,10.0,0.0,15
534820,2022-10-28 17:00:00,23,49.4407,32.0637,10.4,7.4,82.2,0.000,0.0,0.00,0.0,0.0,18.0,10.1,275.2,1027.5,70.1,93.0,8.0,4.0,0.08,13.6,13.6,68.44,0.0,0.0,0.0,12.2,5.4,258.5,1027.0,92.1,75.0,0.3,1.0,False,True,False,False,False,True,False,False,2022,10,4,17,Cherkasy,Europe/Kiev,2022-10-28,07:33:11,17:37:10,17:00:00,Черкаська,0,0.000000,0.0,0.0,0.0,0.0,1.0,0,0,0.0,0.0,15
436139,2023-08-20 13:00:00,19,49.5527,25.5889,24.2,16.6,64.9,1.200,100.0,8.33,0.0,0.0,24.1,14.4,281.9,1019.2,38.7,237.0,20.5,7.0,0.14,30.9,30.8,40.41,0.0,0.0,0.0,15.5,7.2,234.5,1020.0,3.5,741.3,2.7,7.0,False,False,True,False,True,False,False,False,2023,8,6,13,Ternopil,Europe/Kiev,2023-08-20,06:15:08,20:26:12,13:00:00,Тернопільська,0,0.000000,0.0,0.0,0.0,0.0,0.0,1,0,2.0,0.0,31
427729,2022-09-04 02:00:00,19,49.5527,25.5889,14.5,9.4,72.9,0.100,100.0,4.17,0.0,0.0,24.8,13.0,105.0,1023.6,89.7,95.8,8.2,4.0,0.25,11.8,11.8,89.92,0.0,0.0,0.0,7.2,4.0,106.3,1023.0,98.9,0.0,0.1,0.0,False,False,True,False,False,True,False,False,2022,9,6,2,Ternopil,Europe/Kiev,2022-09-04,06:37:22,19:55:09,02:00:00,Тернопільська,0,0.000000,0.0,0.0,0.0,0.0,0.0,1,1,7.0,0.0,85
487227,2023-06-06 11:00:00,21,46.6401,32.6142,18.9,6.9,49.0,0.000,0.0,0.00,0.0,0.0,28.8,9.0,81.3,1022.3,38.2,296.4,25.5,9.0,0.58,21.7,21.7,39.95,0.0,0.0,0.0,19.8,7.2,35.0,1023.0,43.6,780.5,2.8,8.0,False,True,False,False,False,True,False,False,2023,6,1,11,Kherson,Europe/Kiev,2023-06-06,04:57:39,20:39:11,11:00:00,Херсонська,0,0.000000,0.0,0.0,1.0,0.0,5.0,0,0,2.0,1.0,5
13918,2023-09-27 00:00:00,2,49.2336,28.4486,18.4,12.2,71.4,0.000,0.0,0.00,0.0,0.0,25.9,10.1,55.2,1027.4,4.8,175.3,15.0,6.0,0.43,13.9,13.9,84.89,0.0,0.0,0.0,16.9,3.6,330.0,1028.9,0.0,0.0,0.0,0.0,True,False,False,False,True,False,False,False,2023,9,2,0,Vinnytsia,Europe/Kiev,2023-09-27,06:59:17,18:54:34,00:00:00,Вінницька,0,0.000000,0.0,0.0,0.0,0.0,4.0,0,1,2.0,0.0,4
48805,2024-09-12 19:00:00,3,50.7469,25.3263,17.2,16.2,94.3,1.053,100.0,8.33,0.0,0.0,19.4,10.1,13.7,1008.3,95.4,39.3,3.3,1.0,0.31,18.8,18.8,92.16,0.0,0.0,0.0,13.0,5.8,339.9,1008.0,89.4,33.7,0.1,0.0,False,False,True,False,False,True,False,False,2024,9,3,19,Lutsk,Europe/Kiev,2024-09-12,06:49:56,19:38:51,19:00:00,Волинська,0,0.000000,0.0,0.0,0.0,0.0,0.0,0,0,4.0,0.0,131
434048,2023-05-25 10:00:00,19,49.5527,25.5889,18.7,8.7,55.1,0.000,0.0,0.00,0.0,0.0,29.2,25.2,334.2,1017.5,39.5,271.0,23.2,8.0,0.18,21.7,21.7,47.95,0.0,0.0,0.0,22.0,8.6,324.4,1018.0,32.4,557.3,2.0,6.0,False,True,False,False,False,True,False,False,2023,5,3,10,Ternopil,Europe/Kiev,2023-05-25,05:22:04,21:07:52,10:00:00,Тернопільська,0,0.000000,0.0,0.0,1.0,0.0,5.0,0,0,0.0,0.0,4

In [13]:
df_isw_matrix.sample(10)

,date,isw_topic_0,isw_topic_1,isw_topic_2,isw_topic_3,isw_topic_4,isw_topic_5,isw_topic_6,isw_topic_7,isw_topic_8,isw_topic_9,isw_topic_10,isw_topic_11,isw_topic_12,isw_topic_13,isw_topic_14,isw_topic_15,isw_topic_16,isw_topic_17,isw_topic_18,isw_topic_19,isw_topic_20,isw_topic_21,isw_topic_22,isw_topic_23,isw_topic_24,isw_topic_25,isw_topic_26,isw_topic_27,isw_topic_28,isw_topic_29,isw_topic_30,isw_topic_31,isw_topic_32,isw_topic_33,isw_topic_34,isw_topic_35,isw_topic_36,isw_topic_37,isw_topic_38,isw_topic_39,isw_topic_40,isw_topic_41,isw_topic_42,isw_topic_43,isw_topic_44,isw_topic_45,isw_topic_46,isw_topic_47,isw_topic_48,isw_topic_49,isw_topic_50,isw_topic_51,isw_topic_52,isw_topic_53,isw_topic_54,isw_topic_55,isw_topic_56,isw_topic_57,isw_topic_58,isw_topic_59,isw_topic_60,isw_topic_61,isw_topic_62,isw_topic_63,isw_topic_64,isw_topic_65,isw_topic_66,isw_topic_67,isw_topic_68,isw_topic_69,isw_topic_70,isw_topic_71,isw_topic_72,isw_topic_73,isw_topic_74,isw_topic_75,isw_topic_76,isw_topic_77,isw_topic_78,isw_topic_79,isw_topic_80,isw_topic_81,isw_topic_82,isw_topic_83,isw_topic_84,isw_topic_85,isw_topic_86,isw_topic_87,isw_topic_88,isw_topic_89,isw_topic_90,isw_topic_91,isw_topic_92,isw_topic_93,isw_topic_94,isw_topic_95,isw_topic_96,isw_topic_97,isw_topic_98,isw_topic_99,isw_topic_100,isw_topic_101,isw_topic_102,isw_topic_103,isw_topic_104,isw_topic_105,isw_topic_106,isw_topic_107,isw_topic_108,isw_topic_109,isw_topic_110,isw_topic_111,isw_topic_112,isw_topic_113,isw_topic_114,isw_topic_115,isw_topic_116,isw_topic_117,isw_topic_118,isw_topic_119,isw_topic_120,isw_topic_121,isw_topic_122,isw_topic_123,isw_topic_124,isw_topic_125,isw_topic_126,isw_topic_127,isw_topic_128,isw_topic_129,isw_topic_130,isw_topic_131,isw_topic_132,isw_topic_133,isw_topic_134,isw_topic_135,isw_topic_136,isw_topic_137,isw_topic_138,isw_topic_139,isw_topic_140,isw_topic_141,isw_topic_142,isw_topic_143,isw_topic_144,isw_topic_145,isw_topic_146,isw_topic_147,isw_topic_148,isw_topic_149
136,2022-07-09,0.744766,-0.206271,0.208248,-0.001226,-0.063301,0.104104,0.071302,-0.101936,-0.002449,0.012457,-0.116096,-0.127555,0.052244,-0.033801,-0.017166,0.046522,-0.055906,0.009067,-0.068595,-0.031481,0.006475,-0.082863,-0.033245,-0.025740,0.054279,0.025302,-0.026230,-0.044486,0.005255,-0.001249,0.072920,0.013327,-0.009163,0.016965,0.018714,0.011645,0.025238,-0.023150,0.002279,0.042971,-0.021873,-0.013869,-0.056613,-0.041758,0.000967,0.042961,0.040352,-0.068175,-0.043832,-0.012052,-0.008501,0.005472,-0.029390,0.002899,0.057730,0.031018,0.011728,-0.030052,-0.006495,0.030576,-0.022661,-0.036235,0.063426,0.026370,0.025170,0.025443,-0.030314,0.004432,-0.028582,-0.042687,0.039736,0.027267,-0.005573,-0.014119,-0.029532,0.009991,-0.029268,0.013783,-0.043374,-0.006110,-0.027900,0.002715,0.007302,0.015827,0.001589,-0.018015,-0.001485,-0.053690,-0.007329,-0.047021,-0.005765,0.006623,0.007871,-0.007514,0.002737,0.005117,-0.016600,0.003849,-0.018555,-0.007650,0.011154,-0.003941,0.019259,0.008886,-0.045556,-0.017753,0.004719,-0.004430,0.013214,0.018799,0.009835,-0.034650,-0.002944,-0.010044,-0.004507,-0.058413,-0.008916,-0.002448,0.017348,-0.007322,-0.001819,0.048098,0.039007,0.017339,-0.045625,0.003107,-0.012315,0.051055,0.037209,0.028696,0.013277,-0.036274,0.013106,0.005894,-0.011250,0.010466,0.055308,-0.011417,-0.002946,-0.015453,-0.019784,0.023989,0.065556,-0.008810,0.020015,-0.014550,0.025466,-0.020187,-0.000549,0.014066
1327,2025-10-22,0.753436,0.270383,0.030635,-0.184268,-0.014613,-0.170559,-0.237476,-0.021032,-0.221238,-0.071660,-0.093766,-0.032702,-0.064511,-0.099170,-0.128805,0.022666,0.022785,-0.009746,0.021250,-0.028994,0.068013,0.000166,0.027887,-0.039335,0.021479,-0.052618,0.026810,0.002537,-0.045076,-0.055689,0.027172,0.009938,0.025040,0.006673,0.001364,-0.012282,-0.023637,-0.023138,0.023443,0.037326,-0.009204,-0.025638,0.013522,-0.021824,0.028498,0.007547,0.000842,-0.065556,-0.006029,0.009895,-0.015914,0.019658,0.013272,0.055888,-0.027435,0.000605,0.000214,0.031382,0.014341,-0.016947,0.007641,-0.040875,0.000135,0.003066,-0.009500,-0.013589,-0.028704,-0.015839,-0.002763,0.003295,-0.017227,0.032027,0.017956,-0.007649,-0.020337,-0.002091,-0.004468,-0.020446,0.030275,-0.005905,-0.015749,-0.004847,-0.003405,-0.000067,0.004391,-0.006861,-0.032375,0.041812,-0.013600,0.005321,0.024425,-0.029874,-0.007948,-0.005134,-0.007734,0.006812,-0.030961,-0.001389,0.023336,0.012619,0.033208,0.005568,0.000524,0.014702,-0.030675,0.002634,-0.014299,-0.011296,0.004225,0.004283,0.007182,-0.007528,-0.027089,0.017472,-0.001642,0.014832,-0.000681,-0.007767,0.029366,-0.021544,0.003407,0.024409,-0.010499,-0.019998,-0.014666,0.007990,-0.007591,-0.007025,-0.004744,-0.009948,0.004278,-0.023632,-0.006374,0.008330,-0.000786,-0.014863,-0.014469,0.027454,-0.005087,0.005019,0.016341,-0.006392,-0.006019,0.018022,0.009853,0.023437,-0.015428,-0.013651,-0.008748,-0.005344
1156,2025-05-04,0.815555,0.248556,0.045863,0.072507,-0.060817,0.004352,0.015697,0.003697,-0.040156,0.042093,0.019827,0.038633,-0.061533,0.026899,0.127012,0.146152,0.149722,0.194174,0.051847,0.017714,-0.061324,0.045431,-0.021638,-0.022547,0.017812,0.018382,-0.019998,0.010567,0.032775,0.003513,0.030536,0.051991,-0.026504,-0.030745,-0.027959,-0.041046,0.040546,0.034175,-0.014579,-0.034727,-0.006517,-0.003507,-0.019432,-0.029261,0.031231,0.021067,0.009478,0.032722,-0.015902,0.004822,0.029292,-0.049871,-0.017574,-0.006298,0.001607,0.011345,-0.018093,-0.010508,0.023289,-0.031617,0.014684,-0.022753,0.012097,-0.019402,-0.032253,-0.026862,0.001983,-0.037165,0.010628,-0.007890,-0.027018,-0.036479,0.007555,-0.016055,0.015272,0.005776,-0.001678,-0.034937,0.037527,0.008714,0.004564,-0.007379,0.051316,0.000272,-0.048161,-0.006350,-0.014363,0.013528,0.015005,0.015073,0.015274,-0.024655,0.012734,0.003853,-0.007410,0.030761,0.003326,-0.006989,-0.005041,0.021765,-0.007366,0.011588,0.026375,0.009718,-0.014245,-0.014807,0.013483,0.031944,-0.013528,-0.000823,-0.018841,-0.017591,-0.021073,-0.009495,-0.026050,-0.007201,0.003888,0.003870,0.009074,-0.006216,-0.023931,-0.021158,0.024889,0.030665,-0.014521,-0.012247,0.004095,0.000028,0.006126,0.013262,-0.006662,-0.011905,-0.006114,0.005183,-0.000530,-0.013734,0.001328,0.003608,0.000368,-0.000204,-0.000495,-0.002844,-0.019730,-0.001311,0.007882,0.022966,-0.003865,-0.018222,0.024112,-0.014081
572,2023-09-21,0.783815,-0.114161,-0.031162,-0.141684,-0.081833,0.022303,-0.057226,0.085854,0.027594,-0.045247,0.043069,0.025693,0.156281,0.236921,0.052217,-0.119228,0.008003,0.046626,0.059459,-0.018154,0.050553,-0.007240,-0.003142,-0.026583,0.007593,0.038245,0.008122,0.046658,-0.002905,-0.046732,0.008651,0.030306,-0.010767,0.007208,-0.039697,0.014712,0.010662,0.019092,0.074300,0.055313,-0.010303,0.017052,0.017580,0.008601,0.019723,-0.032572,-0.004406,-0.039875,-0.001743,0.006900,-0.028435,0.022776,-0.057274,0.094306,0.037600,-0.010617,-0.032047,-0.066292,-0.015581,-0.023891,-0.043839,0.035384,0.021141,-0.001983,-0.046657,-0.036613,0.002543,0.011215,0.044991,-0.031534,0.004789,0.009580,0.018641,-0.040668,0.000965,-0.037706,-0.036806,0.006929,-0.030460,0.008536,0.013584,0.004145,0.004028,-0.017281,-0.029055,-0.020038,0.014879,-0.022145,0.025419,-0.005632,0.027514,0.013358,-0.020933,-0.008967,-0.034260,-0.017471,-0.029914,-0.015555,0.015690,-0.021496,-0.047724,0.041953,0.024006,-0.013593,0.015420,-0.016325,0.014699,0.018345,0.027701,0.021540,0.049801,-0.020284,-0.022870,-0.018263,0.017812,-0.010450,-0.004565,0.007531,0.010332,-0.001238,0.012794,0.020535,-0.001028,-0.010046,-0.016309,-0.014235,0.033476,-0.009191,-0.006383,-0.000333,-0.001845,0.018606,-0.008907,-0.031510,0.025897,-0.024846,-0.031143,-0.004598,0.010984,-0.016312,-0.020619,-0.003891,-0.003923,0.007455,-0.016798,-0.009599,0.024777,0.011794,0.003174,-0.021644
210,2022-09-21,0.723607,-0.219475,0.046933,-0.091472,-0.000724,0.000583,-0.026150,0.032025,0.015121,-0.072997,-0.008295,0.040047,0.168305,0.063026,-0.110495,0.170554,-0.119205,0.018849,0.102452,0.056035,0.056040,0.098168,-0.050490,-0.016359,0.043049,-0.032994,-0.053331,0.031382,0.036646,0.055852,-0.022183,-0.056243,-0.079498,-0.024113,0.024593,-0.058452,0.001554,-0.005164,0.044378,-0.043386,-0.012807,-0.048674,-0.032387,0.088567,0.059792,-0.011246,-0.051046,0.012029,0.039030,-0.008798,0.015340,-0.024806,0.049190,0.045458,0.024275,-0.065935,0.069827,0.019457,-0.001274,0.028949,0.014188,-0.012595,0.056188,-0.015104,-0.005761,0.005480,0.034693,-0.009356,0.010491,-0.010624,0.048210,0.047238,-0.000253,-0.022873,0.002780,-0.062997,0.033975,-0.018238,0.007574,0.026298,-0.030565,0.028318,0.025705,0.027440,-0.043002,0.046223,-0.005826,0.050912,-0.028826,-0.015746,-0.020099,-0.029451,0.020840,0.023177,0.056556,0.004272,-0.010351,0.023599,0.018085,0.007372,-0.004787,-0.042216,-0.005838,-0.014847,-0.013648,-0.010697,-0.024131,0.001059,-0.001416,0.014243,-0.003339,-0.005274,-0.003891,-0.015893,0.008390,-0.008870,-0.008262,-0.028660,0.007146,-0.028135,-0.016043,-0.007966,-0.020912,0.007884,0.022679,-0.002506,-0.072405,-0.038150,0.004697,-0.006779,-0.035433,0.008473,0.020301,-0.038335,0.021953,-0.010696,0.016776,0.022699,0.004049,0.023837,0.007420,-0.029902,0.061073,0.030997,-0.056490,-0.000002,0.014936,-0.028749,-0.003036,0.006703
772,2024-04-11,0.734258,-0.026803,-0.149474,0.278725,-0.060320,-0.091920,-0.022570,-0.113078,-0.027469,-0.092562,0.196644,-0.080477,0.051961,0.000699,-0.136153,-0.085638,-0.066121,0.033940,-0.069606,0.082912,0.040287,-0.023854,0.007505,-0.030613,-0.007949,0.077503,0.013492,0.046115,0.053100,-0.018738,-0.021238,-0.023129,-0.044438,0.007278,-0.031223,-0.073336,-0.011645,0.034779,-0.049521,-0.010247,0.061883,-0.022336,-0.018213,-0.057153,0.005874,0.014682,-0.049424,0.001661,-0.005204,0.031344,0.014055,0.032249,-0.004333,-0.003715,-0.001054,-0.023555,-0.024588,-0.002476,-0.005970,0.027114,-0.021339,0.017025,0.017719,0.038324,-0.007265,-0.015417,0.021318,0.046019,0.010924,0.007348,0.006462,0.013245,-0.014348,-0.012526,-0.007061,0.008641,-0.011066,0.025437,-0.007996,-0.006315,-0.019885,0.010736,-0.007949,0.008085,-0.024262,-0.048266,-0.029201,0.014554,0.007154,0.031082,-0.046853,0.017330,0.009046,-0.029836,0.042075,0.009929,-0.026639,0.001268,0.038740,-0.020510,-0.008083,-0.024069,0.005624,-0.025782,0.048466,0.015847,-0.001761,-0.001724,-0.035592,-0.019656,-0.037912,-0.016783,-0.033128,0.020311,-0.017716,0.009481,0.007080,-0.015737,-0.019289,0.017326,-0.002702,0.006206,0.008603,-0.003985,-0.012567,-0.027588,0.038471,-0.027985,0.016629,0.011875,-0.033668,0.007623,0.008211,-0.038790,-0.003606,0.021220,-0.025721,0.010687,-0.009313,-0.042150,0.026682,0.010578,0.008973,-0.003824,-0.003578,-0.013076,0.008720,0.004287,-0.020234,0.001749
341,2023-02-02,0.789044,-0.212431,-0.072684,0.042118,0.079438,0.011000,-0.022928,0.076442,-0.039440,0.046509,-0.002262,0.025620,0.150061,-0.155178,0.076335,0.078017,-0.057443,-0.021674,-0.024962,-0.011481,-0.106195,0.030859,-0.027276,0.017383,-0.098454,-0.080395,0.012335,0.017844,-0.005938,0.020456,0.003884,0.018688,-0.034497,0.012216,-0.049738,-0.042982,-0.049084,0.002041,0.026762,-0.005763,0.034516,-0.008145,0.003321,0.006611,0.018405,0.025360,0.002877,-0.023262,0.024629,-0.000964,-0.016414,0.013847,0.013829,0.007696,0.017079,-0.014799,-0.006199,-0.013601,-0.020214,-0.017035,0.005303,-0.023985,0.019610,-0.023669,0.003906,-0.011544,0.008046,-0.014135,-0.046414,-0.073085,0.037868,-0.022050,-0.002550,0.008815,-0.003687,-0.011776,0.006610,0.007609,0.010645,0.025713,-0.025002,0.060566,0.030607,0.002531,0.029146,0.022287,0.009715,-0.024261,-0.008054,0.033578,0.010555,-0.004621,-0.023972,-0.022576,-0.033745,-0.008379,0.064933,-0.017426,-0.006923,0.004498,0.002989,-0.025034,0.008179,-0.034400,0.010383,0.033712,0.035125,-0.028415,0.005140,-0.011130,-0.007474,-0.003530,0.016626,-0.002102,-0.013110,0.006081,-0.020781,-0.012179,0.023948,0.029089,-0.025533,0.017384,-0.001312,0.003441,0.007912,-0.041185,-0.059686,-0.012309,0.011907,0.020453,0.017886,0.011183,0.014546,-0.024660,0.014190,-0.034790,0.024508,-0.021103,0.055814,-0.002830,0.012605,-0.012939,0.021714,-0.005426,-0.042678,0.023096,0.004483,-0.006954,0.003945,0.020913
1052,2025-01-20,0.747101,0.190214,-0.088181,0.057422,0.273140,0.233032,-0.133700,-0.181907,0.142015,-0.061921,-0.013482,-0.004909,-0.109665,0.084374,0.105636,0.024173,-0.053324,0.000765,0.026140,-0.052025,-0.015148,-0.016369,0.041351,-0.012579,0.028378,0.003489,-0.057199,0.019094,-0.027282,0.088450,-0.044932,0.032968,-0.027207,0.007757,0.025299,0.024076,-0.018083,-0.072540,0.010840,0.022653,0.026940,0.002088,0.012201,-0.022287,0.001230,-0.001281,-0.040551,0.005495,0.000700,0.012708,0.022178,-0.015282,0.008809,0.009409,-0.014357,-0.005395,-0.004300,0.012972,-0.009104,-0.005001,0.009269,-0.003640,0.019483,0.008366,-0.021283,-0.014078,-0.010325,-0.022138,0.007369,-0.032536,-0.014105,0.003874,-0.048319,0.024874,-0.003340,0.005186,-0.007333,-0.032288,-0.027184,-0.013489,0.029076,-0.033895,-0.000632,0.003925,0.000465,0.021204,-0.005553,-0.020943,-0.000827,-0.006435,0.003611,-0.039561,-0.011807,-0.022774,0.021766,-0.001329,0.012140,-0.000963,-0.001082,-0.027197,0.033090,-0.001562,0.009757,-0.013557,-0.000910,-0.018619,0.009751,0.000306,0.007069,-0.025652,-0.004837,0.001648,0.005590,0.003668,-0.011969,0.004811,0.006027,-0.004842,-0.021805,0.003345,0.046185,0.007254,-0.013249,-0.006683,0.012602,-0.003663,0.007086,0.004535,-0.011815,-0.016471,-0.005582,0.003129,0.021126,0.005552,-0.001793,0.015664,0.016161,0.025486,-0.023998,-0.003720,-0.007474,-0.005515,0.003592,0.026337,-0.009606,0.014378,-0.009573,-0.017873,0.000927,0.004115
866,2024-07-14,0.799954,0.080552,-0.097046,0.099487,-0.179725,0.114132,0.076513,-0.129827,0.001640,0.039766,-0.142325,-0.228095,0.063603,-0.007670,-0.025614,-0.026389,0.027930,-0.050246,-0.022687,0.056028,0.022139,0.099565,-0.059225,0.000317,-0.020985,-0.019852,0.022612,-0.031255,-0.046290,-0.087420,-0.013357,-0.024300,-0.027971,-0.000405,0.020962,-0.007299,-0.036492,-0.000298,0.021851,0.005579,0.012893,0.002233,0.006526,-0.007364,0.023939,0.042677,-0.006303,0.011455,-0.003801,0.020470,0.067888,-0.007366,0.018303,-0.035284,0.003178,-0.008952,0.014510,0.006895,0.024244,-0.001721,0.019564,-0.007169,-0.019028,-0.037116,-0.019101,-0.014860,0.007953,0.005109,0.003125,-0.008676,-0.004679,0.007546,-0.011503,-0.007324,0.017975,0.028072,0.010827,0.021401,0.013220,-0.011011,-0.006510,0.005976,0.017144,0.010415,0.000840,0.001869,-0.026848,-0.025727,0.042056,-0.000736,-0.024177,-0.000756,0.023240,0.020185,-0.000342,0.007655,-0.018610,0.004379,0.007449,-0.003878,0.001663,-0.018730,0.022070,0.025375,-0.016788,-0.001231,-0.023129,0.014265,0.021672,0.002825,-0.005745,0.016539,-0.005636,-0.001438,0.016111,-0.000293,-0.002023,-0.000690,-0.020939,-0.029656,-0.005241,0.021463,0.004436,-0.033159,0.000228,-0.019482,0.005017,-0.003224,-0.036493,-0.000995,0.013673,0.000643,0.014873,0.016263,-0.019224,0.022683,-0.044995,0.014411,-0.008971,0.012845,0.015466,0.007551,-0.001937,0.003404,0.012577,0.021554,-0.010044,-0.009029,-0.015468,-0.019322
128,2022-07-01,0.770190,-0.207073,0.210602,0.009958,-0.033388,0.076172,0.060842,-0.091510,-0.000633,-0.007869,-0.092924,-0.039493,0.045080,-0.033236,-0.038884,0.042395,-0.051961,0.023646,-0.089538,-0.048440,0.016655,-0.071592,-0.036646,-0.025197,0.034415,-0.007115,0.017861,0.026303,-0.012855,-0.010784,0.050268,0.045175,0.000314,0.002946,0.005224,-0.002523,0.038833,-0.014437,0.033078,-0.019810,-0.005478,-0.062953,-0.050257,0.011034,-0.019124,0.009720,0.014698,-0.035303,0.017257,0.050648,0.021329,-0.032856,-0.017963,0.013815,0.022497,0.054264,-0.023892,0.031136,0.019049,0.023704,0.007907,-0.069246,0.115537,-0.037549,-0.026826,-0.008662,-0.006036,0.035914,-0.045669,-0.003280,0.028402,0.017956,0.000836,0.027553,-0.026630,-0.009552,-0.068459,0.032390,-0.001978,0.005071,0.028107,-0.015857,0.008288,-0.041785,-0.053349,-0.010675,-0.013731,-0.015042,-0.020419,0.004913,-0.003633,-0.020364,-0.005152,-0.033350,0.029018,-0.008909,-0.024805,-0.022672,0.040876,-0.009749,-0.018252,0.001017,-0.013864,0.010632,0.028165,0.000006,-0.015907,-0.014987,0.004149,0.033653,-0.003650,0.003749,-0.013910,0.014556,0.013069,0.007817,0.013180,0.004390,-0.003407,0.039836,0.008271,-0.017052,-0.009144,-0.044428,0.007030,0.004348,0.009906,0.005663,0.006306,0.014248,-0.011579,-0.055908,-0.043088,0.003625,0.000756,-0.016684,0.019835,-0.005245,0.034295,0.003776,-0.011400,-0.002533,0.040652,-0.038559,-0.022580,-0.010898,0.027573,0.002481,-0.007099,-0.010993

In [14]:
#df_isw_matrix["date"] = pd.to_datetime(df_isw_matrix["date"]) + pd.Timedelta(days=1)    ТУТ ЗСУВ ІСВ НА + 1 ДЕНЬ
df_isw_matrix = df_isw_matrix.rename(columns={'date': 'day_datetime'})

In [15]:
df_final['day_datetime'] = pd.to_datetime(df_final['day_datetime']).dt.date
df_isw_matrix['day_datetime'] = pd.to_datetime(df_isw_matrix['day_datetime']).dt.date
df_isw_matrix.fillna(0, inplace=True)
df_isw_matrix.isna().sum()

day_datetime     0
isw_topic_0      0
isw_topic_1      0
isw_topic_2      0
isw_topic_3      0
                ..
isw_topic_145    0
isw_topic_146    0
isw_topic_147    0
isw_topic_148    0
isw_topic_149    0
Length: 151, dtype: int64

In [16]:
df_final = df_final.merge(df_isw_matrix, on="day_datetime", how="left")

In [17]:
df_final.head(10)

,datetime_hour,region_id,city_latitude,city_longitude,day_temp,day_dew,day_humidity,day_precip,day_precipprob,day_precipcover,day_snow,day_snowdepth,day_windgust,day_windspeed,day_winddir,day_pressure,day_cloudcover,day_solarradiation,day_solarenergy,day_uvindex,day_moonphase,hour_temp,hour_feelslike,hour_humidity,hour_precip,hour_precipprob,hour_snow,hour_windgust,hour_windspeed,hour_winddir,hour_pressure,hour_cloudcover,hour_solarradiation,hour_solarenergy,hour_uvindex,day_conditions_simple_Clear,day_conditions_simple_Cloudy,day_conditions_simple_Rain,day_conditions_simple_Snow,hour_conditions_simple_Clear,hour_conditions_simple_Cloudy,hour_conditions_simple_Rain,hour_conditions_simple_Snow,year,month,day_of_week,hour,city_name,city_timezone,day_datetime,day_sunrise,day_sunset,hour_datetime,region_key,alarm_active,alarm_minutes_in_hour,alarm_lag_1,alarm_lag_3,alarm_lag_6,alarm_lag_12,alarms_in_last_24h,is_weekend,is_night,total_active_alarms_lag1,neighbour_alarms,hours_since_last_alarm,isw_topic_0,isw_topic_1,isw_topic_2,isw_topic_3,isw_topic_4,isw_topic_5,isw_topic_6,isw_topic_7,isw_topic_8,isw_topic_9,isw_topic_10,isw_topic_11,isw_topic_12,isw_topic_13,isw_topic_14,isw_topic_15,isw_topic_16,isw_topic_17,isw_topic_18,isw_topic_19,isw_topic_20,isw_topic_21,isw_topic_22,isw_topic_23,isw_topic_24,isw_topic_25,isw_topic_26,isw_topic_27,isw_topic_28,isw_topic_29,isw_topic_30,isw_topic_31,isw_topic_32,isw_topic_33,isw_topic_34,isw_topic_35,isw_topic_36,isw_topic_37,isw_topic_38,isw_topic_39,isw_topic_40,isw_topic_41,isw_topic_42,isw_topic_43,isw_topic_44,isw_topic_45,isw_topic_46,isw_topic_47,isw_topic_48,isw_topic_49,isw_topic_50,isw_topic_51,isw_topic_52,isw_topic_53,isw_topic_54,isw_topic_55,isw_topic_56,isw_topic_57,isw_topic_58,isw_topic_59,isw_topic_60,isw_topic_61,isw_topic_62,isw_topic_63,isw_topic_64,isw_topic_65,isw_topic_66,isw_topic_67,isw_topic_68,isw_topic_69,isw_topic_70,isw_topic_71,isw_topic_72,isw_topic_73,isw_topic_74,isw_topic_75,isw_topic_76,isw_topic_77,isw_topic_78,isw_topic_79,isw_topic_80,isw_topic_81,isw_topic_82,isw_topic_83,isw_topic_84,isw_topic_85,isw_topic_86,isw_topic_87,isw_topic_88,isw_topic_89,isw_topic_90,isw_topic_91,isw_topic_92,isw_topic_93,isw_topic_94,isw_topic_95,isw_topic_96,isw_topic_97,isw_topic_98,isw_topic_99,isw_topic_100,isw_topic_101,isw_topic_102,isw_topic_103,isw_topic_104,isw_topic_105,isw_topic_106,isw_topic_107,isw_topic_108,isw_topic_109,isw_topic_110,isw_topic_111,isw_topic_112,isw_topic_113,isw_topic_114,isw_topic_115,isw_topic_116,isw_topic_117,isw_topic_118,isw_topic_119,isw_topic_120,isw_topic_121,isw_topic_122,isw_topic_123,isw_topic_124,isw_topic_125,isw_topic_126,isw_topic_127,isw_topic_128,isw_topic_129,isw_topic_130,isw_topic_131,isw_topic_132,isw_topic_133,isw_topic_134,isw_topic_135,isw_topic_136,isw_topic_137,isw_topic_138,isw_topic_139,isw_topic_140,isw_topic_141,isw_topic_142,isw_topic_143,isw_topic_144,isw_topic_145,isw_topic_146,isw_topic_147,isw_topic_148,isw_topic_149
0,2022-02-24 00:00:00,2,49.2336,28.4486,2.8,-0.3,80.5,0.3,100.0,4.17,0.0,0.0,27.7,10.8,312.0,1023.4,82.5,60.4,5.4,3.0,0.77,2.1,-0.5,91.76,0.0,0.0,0.0,16.6,8.6,279.6,1021.0,91.1,0.0,0.1,0.0,False,False,False,True,False,True,False,False,2022,2,3,0,Vinnytsia,Europe/Kiev,2022-02-24,06:58:49,17:40:52,00:00:00,Вінницька,0,0.0,0.0,0.0,0.0,0.0,NaN,0,1,NaN,NaN,1,0.648336,-0.079572,0.178041,0.061854,0.073453,-0.055809,-0.011311,0.047310,0.008354,0.006474,-0.047099,0.020496,0.050190,-0.038573,0.057228,-0.072471,0.045393,-0.116783,0.168249,0.167355,-0.025072,-0.073858,-0.097024,-0.146191,0.027983,0.082989,0.014423,0.058370,-0.033928,0.046265,0.006901,-0.049498,0.126117,-0.089039,-0.006767,-0.031686,-0.010346,0.025637,0.061278,0.162580,-0.028081,0.161291,-0.018217,-0.002657,0.038485,-0.000530,0.044413,0.107176,-0.050721,0.064279,-0.066677,0.016742,-0.050257,0.072549,-0.035201,-0.027279,0.017115,0.043631,0.024660,-0.025841,0.031320,-0.076959,-0.072986,-0.040465,0.003958,-0.022475,0.033208,-0.028056,-0.005499,-0.055998,-0.021882,-0.070462,0.018237,-0.031396,-0.074606,0.072951,0.039997,0.036423,-0.027152,-0.071900,0.026267,-0.046270,-0.017945,0.007933,-0.006203,-0.046099,0.032793,-0.069113,0.020403,0.030783,-0.003787,-0.000490,-0.022951,0.013498,0.009664,-0.007012,-0.016325,-0.005732,0.036069,-0.063906,0.033891,0.010560,-0.104517,-0.022069,0.054322,-0.005460,-0.029093,0.040991,-0.053018,-0.024017,0.050817,-0.003297,-0.020895,-0.053213,-0.028428,0.048231,-0.001221,0.001302,-0.044137,0.015528,-0.012792,-0.012009,-0.008211,0.031114,0.024982,0.003863,-0.032321,0.030920,-0.012845,0.070170,-0.004037,0.014003,0.005577,0.021611,-0.002889,0.034824,0.047164,0.050545,-0.017639,0.029014,-0.030378,-0.027056,0.011464,-0.039759,-0.043514,-0.025605,-0.022484,-0.036224,0.000566,0.005481
1,2022-02-24 00:00:00,2,49.2336,28.4486,2.8,-0.3,80.5,0.3,100.0,4.17,0.0,0.0,27.7,10.8,312.0,1023.4,82.5,60.4,5.4,3.0,0.77,2.1,-0.5,91.76,0.0,0.0,0.0,16.6,8.6,279.6,1021.0,91.1,0.0,0.1,0.0,False,False,False,True,False,True,False,False,2022,2,3,0,Vinnytsia,Europe/Kiev,2022-02-24,06:58:49,17:40:52,00:00:00,Вінницька,0,0.0,0.0,0.0,0.0,0.0,NaN,0,1,NaN,NaN,1,0.580161,-0.090608,-0.028388,0.146350,0.071072,-0.030284,-0.004583,0.087399,-0.038512,0.016613,-0.038599,0.049747,0.186305,-0.172198,-0.045515,0.050785,0.041889,-0.112849,0.193473,-0.010566,0.044308,-0.118300,0.007117,-0.135687,-0.009441,-0.039465,0.032843,0.080393,-0.035434,0.010352,-0.016680,-0.046252,0.085840,-0.123167,0.064510,-0.023735,-0.025637,-0.027863,0.032156,0.068641,0.027667,0.162729,0.039675,-0.016915,-0.008203,0.048024,0.073343,0.025782,-0.013935,-0.008775,-0.045265,0.008979,-0.100558,0.044074,0.018202,-0.037279,0.062349,0.008014,0.075917,-0.063409,0.015404,-0.091507,-0.079240,-0.033000,-0.019226,-0.103926,0.031514,0.043306,-0.012137,-0.010430,0.035901,-0.013437,-0.042046,-0.064986,0.002947,0.024326,0.085592,-0.008453,0.091087,-0.106852,0.038223,-0.061062,0.027905,0.056421,-0.030501,0.000050,0.051385,-0.087324,-0.024025,0.031626,-0.029461,0.015717,-0.047181,-0.005600,0.049867,0.084412,-0.055460,-0.036620,0.120475,-0.012080,0.006961,-0.079701,0.055655,0.004130,0.013250,0.002392,0.041937,0.028208,-0.037232,0.014886,-0.036905,0.000138,-0.018200,-0.010680,-0.067564,-0.001064,-0.044792,-0.014807,-0.031911,-0.023504,0.070783,0.027626,0.000418,0.043677,-0.030193,-0.034979,0.080093,0.035489,-0.004156,-0.008032,0.039826,-0.037380,0.011931,0.008267,0.000590,0.043862,0.023758,0.038714,0.066128,0.028168,-0.012153,0.005376,0.008085,-0.038933,0.003404,0.003281,-0.004149,-0.025392,0.010434,-0.017613
2,2022-02-24 01:00:00,2,49.2336,28.4486,2.8,-0.3,80.5,0.3,100.0,4.17,0.0,0.0,27.7,10.8,312.0,1023.4,82.5,60.4,5.4,3.0,0.77,2.1,-0.4,89.80,0.0,0.0,0.0,16.6,8.3,289.2,1021.0,97.9,0.0,0.1,0.0,False,False,False,True,False,True,False,False,2022,2,3,1,Vinnytsia,Europe/Kiev,2022-02-24,06:58:49,17:40:52,01:00:00,Вінницька,0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0.0,0.0,2,0.648336,-0.079572,0.178041,0.061854,0.073453,-0.055809,-0.011311,0.047310,0.008354,0.006474,-0.047099,0.020496,0.050190,-0.038573,0.057228,-0.072471,0.045393,-0.116783,0.168249,0.167355,-0.025072,-0.073858,-0.097024,-0.146191,0.027983,0.082989,0.014423,0.058370,-0.033928,0.046265,0.006901,-0.049498,0.126117,-0.089039,-0.006767,-0.031686,-0.010346,0.025637,0.061278,0.162580,-0.028081,0.161291,-0.018217,-0.002657,0.038485,-0.000530,0.044413,0.107176,-0.050721,0.064279,-0.066677,0.016742,-0.050257,0.072549,-0.035201,-0.027279,0.017115,0.043631,0.024660,-0.025841,0.031320,-0.076959,-0.072986,-0.040465,0.003958,-0.022475,0.033208,-0.028056,-0.005499,-0.055998,-0.021882,-0.070462,0.018237,-0.031396,-0.074606,0.072951,0.039997,0.036423,-0.027152,-0.071900,0.026267,-0.046270,-0.017945,0.007933,-0.006203,-0.046099,0.032793,-0.069113,0.020403,0.030783,-0.003787,-0.000490,-0.022951,0.013498,0.009664,-0.007012,-0.016325,-0.005732,0.036069,-0.063906,0.033891,0.010560,-0.104517,-0.022069,0.054322,-0.005460,-0.029093,0.040991,-0.053018,-0.024017,0.050817,-0.003297,-0.020895,-0.053213,-0.028428,0.048231,-0.001221,0.001302,-0.044137,0.015528,-0.012792,-0.012009,-0.008211,0.031114,0.024982,0.003863,-0.032321,0.030920,-0.012845,0.070170,-0.004037,0.014003,0.005577,0.021611,-0.002889,0.034824,0.047164,0.050545,-0.017639,0.029014,-0.030378,-0.027056,0.011464,-0.039759,-0.043514,-0.025605,-0.022484,-0.036224,0.000566,0.005481
3,2022-02-24 01:00:00,2,49.2336,28.4486,2.8,-0.3,80.5,0.3,100.0,4.17,0.0,0.0,27.7,10.8,312.0,1023.4,82.5,60.4,5.4,3.0,0.77,2.1,-0.4,89.80,0.0,0.0,0.0,16.6,8.3,289.2,1021.0,97.9,0.0,0.1,0.0,False,False,False,True,False,True,False,False,2022,2,3,1,Vinnytsia,Europe/Kiev,2022-02-24,06:58:49,17:40:52,01:00:00,Вінницька,0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0.0,0.0,2,0.580161,-0.090608,-0.028388,0.146350,0.071072,-0.030284,-0.004583,0.087399,-0.038512,0.016613,-0.038599,0.049747,0.186305,-0.172198,-0.045515,0.050785,0.041889,-0.112849,0.193473,-0.010566,0.044308,-0.118300,0.007117,-0.135687,-0.009441,-0.039465,0.032843,0.080393,-0.035434,0.010352,-0.016680,-0.046252,0.085840,-0.123167,0.064510,-0.023735,-0.025637,-0.027863,0.032156,0.068641,0.027667,0.162729,0.039675,-0.016915,-0.008203,0.048024,0.073343,0.025782,-0.013935,-0.008775,-0.045265,0.008979,-0.100558,0.044074,0.018202,-0.037279,0.062349,0.008014,0.075917,-0.063409,0.015404,-0.091507,-0.079240,-0.033000,-0.019226,-0.103926,0.031514,0.043306,-0.012137,-0.010430,0.035901,-0.013437,-0.042046,-0.064986,0.002947,0.024326,0.085592,-0.008453,0.091087,-0.106852,0.038223,-0.061062,0.027905,0.056421,-0.030501,0.000050,0.051385,-0.087324,-0.024025,0.031626,-0.029461,0.015717,-0.047181,-0.005600,0.049867,0.084412,-0.055460,-0.036620,0.120475,-0.012080,0.006961,-0.079701,0.055655,0.004130,0.013250,0.002392,0.041937,0.028208,-0.037232,0.014886,-0.036905,0.000138,-0.018200,-0.010680,-0.067564,-0.001064,-0.044792,-0.014807,-0.031911,-0.023504,0.070783,0.027626,0.000418,0.043677,-0.030193,-0.034979,0.080093,0.035489,-0.004156,-0.008032,0.039826,-0.037380,0.011931,0.008267,0.000590,0.043862,0.023758,0.038714,0.066128,0.028168,-0.012153,0.005376,0.008085,-0.038933,0.003404,0.003281,-0.004149,-0.025392,0.010434,-0.017613
4,2022-02-24 02:00:00,2,49.2336,28.4486,2.8,-0.3,80.5,0.3,100.0,4.17,0.0,0.0,27.7,10.8,312.0,1023.4,82.5,60.4,5.4,3.0,0.77,2.0,-0.3,90.44,0.0,0.0,0.0,27.7,7.6,287.6,1021.0,98.2,0.0,0.1,0.0,False,False,False,True,False,True,False,False,2022,2,3,2,Vinnytsia,Europe/Kiev,2022-02-24,06:58:49,17:40:52,02:00:00,Вінницька,0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0.0,0.0,3,0.648336,-0.079572,0.178041,0.061854,0.073453,-0.055809,-0.011311,0.047310,0.008354,0.006474,-0.047099,0.020496,0.050190,-0.038573,0.057228,-0.072471,0.045393,-0.116783,0.168249,0.167355,-0.025072,-0.073858,-0.097024,-0.146191,0.027983,0.082989,0.014423,0.058370,-0.033928,0.046265,0.006901,-0.049498,0.126117,-0.089039,-0.006767,-0.031686,-0.010346,0.025637,0.061278,0.162580,-0.028081,0.161291,-0.018217,-0.002657,0.038485,-0.000530,0.044413,0.107176,-0.050721,0.064279,-0.066677,0.016742,-0.050257,0.072549,-0.035201,-0.027279,0.017115,0.043631,0.024660,-0.025841,0.031320,-0.076959,-0.072986,-0.040465,0.003958,-0.022475,0.033208,-0.028056,-0.005499,-0.055998,-0.021882,-0.070462,0.018237,-0.031396,-0.074606,0.072951,0.039997,0.036423,-0.027152,-0.071900,0.026267,-0.046270,-0.017945,0.007933,-0.006203,-0.046099,0.032793,-0.069113,0.020403,0.030783,-0.003787,-0.000490,-0.022951,0.013498,0.009664,-0.007012,-0.016325,-0.005732,0.036069,-0.063906,0.033891,0.010560,-0.104517,-0.022069,0.054322,-0.005460,-0.029093,0.040991,-0.053018,-0.024017,0.050817,-0.003297,-0.020895,-0.053213,-0.028428,0.048231,-0.001221,0.001302,-0.044137,0.015528,-0.012792,-0.012009,-0.008211,0.031114,0.024982,0.003863,-0.032321,0.030920,-0.012845,0.070170,-0.004037,0.014003,0.005577,0.021611,-0.002889,0.034824,0.047164,0.050545,-0.017639,0.029014,-0.030378,-0.027056,0.011464,-0.039759,-0.043514,-0.025605,-0.022484,-0.036224,0.000566,0.005481
5,2022-02-24 02:00:00,2,49.2336,28.4486,2.8,-0.3,80.5,0.3,100.0,4.17,0.0,0.0,27.7,10.8,312.0,1023.4,82.5,60.4,5.4,3.0,0.77,2.0,-0.3,90.44,0.0,0.0,0.0,27.7,7.6,287.6,1021.0,98.2,0.0,0.1,0.0,False,False,False,True,False,True,False,False,2022,2,3,2,Vinnytsia,Europe/Kiev,2022-02-24,06:58:49,17:40:52,02:00:00,Вінницька,0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0.0,0.0,3,0.580161,-0.090608,-0.028388,0.146350,0.071072,-0.030284,-0.004583,0.087399,-0.038512,0.016613,-0.038599,0.049747,0.186305,-0.172198,-0.045515,0.050785,0.041889,-0.112849,0.193473,-0.010566,0.044308,-0.118300,0.007117,-0.135687,-0.009441,-0.039465,0.032843,0.080393,-0.035434,0.010352,-0.016680,-0.046252,0.085840,-0.123167,0.064510,-0.023735,-0.025637,-0.027863,0.032156,0.068641,0.027667,0.162729,0.039675,-0.016915,-0.008203,0.048024,0.073343,0.025782,-0.013935,-0.008775,-0.045265,0.008979,-0.100558,0.044074,0.018202,-0.037279,0.062349,0.008014,0.075917,-0.063409,0.015404,-0.091507,-0.079240,-0.033000,-0.019226,-0.103926,0.031514,0.043306,-0.012137,-0.010430,0.035901,-0.013437,-0.042046,-0.064986,0.002947,0.024326,0.085592,-0.008453,0.091087,-0.106852,0.038223,-0.061062,0.027905,0.056421,-0.030501,0.000050,0.051385,-0.087324,-0.024025,0.031626,-0.029461,0.015717,-0.047181,-0.005600,0.049867,0.084412,-0.055460,-0.036620,0.120475,-0.012080,0.006961,-0.079701,0.055655,0.004130,0.013250,0.002392,0.041937,0.028208,-0.037232,0.014886,-0.036905,0.000138,-0.018200,-0.010680,-0.067564,-0.001064,-0.044792,-0.014807,-0.031911,-0.023504,0.070783,0.027626,0.000418,0.043677,-0.030193,-0.034979,0.080093,0.035489,-0.004156,-0.008032,0.039826,-0.037380,0.011931,0.008267,0.000590,0.043862,0.023758,0.038714,0.066128,0.028168,-0.012153,0.005376,0.008085,-0.038933,0.003404,0.003281,-0.004149,-0.025392,0.010434,-0.017613
6,2022-02-24 03:00:00,2,49.2336,28.4486,2.8,-0.3,80.5,0.3,100.0,4.17,0.0,0.0,27.7,10.8,312.0,1023.4,82.5,60.4,5.4,3.0,0.77,1.9,-0.3,91.75,0.0,0.0,0.0,15.1,7.2,288.9,1021.0,98.8,0.0,0.1,0.0,False,False,False,True,False,True,False,False,2022,2,3,3,Vinnytsia,Europe/Kiev,2022-02-24,06:58:49,17:40:52,03:00:00,Вінницька,0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0.0,0.0,4,0.648336,-0.079572,0.178041,0.061854,0.073453,-0.055809,-0.011311,0.047310,0.008354,0.006474,-0.047099,0.020496,0.050190,-0.038573,0.057228,-0.072471,0.045393,-0.116783,0.168249,0.167355,-0.025072,-0.073858,-0.097024,-0.146191,0.027983,0.082989,0.014423,0.058370,-0.033928,0.046265,0.006901,-0.049498,0.126117,-0.089039,-0.006767,-0.031686,-0.010346,0.025637,0.061278,0.162580,-0.028081,0.161291,-0.018217,-0.002657,0.038485,-0.000530,0.044413,0.107176,-0.050721,0.064279,-0.066677,0.016742,-0.050257,0.072549,-0.035201,-0.027279,0.017115,0.043631,0.024660,-0.025841,0.031320,-0.076959,-0.072986,-0.040465,0.003958,-0.022475,0.033208,-0.028056,-0.005499,-0.055998,-0.021882,-0.070462,0.018237,-0.031396,-0.074606,0.072951,0.039997,0.036423,-0.027152,-0.071900,0.026267,-0.046270,-0.017945,0.007933,-0.006203,-0.046099,0.032793,-0.069113,0.020403,0.030783,-0.003787,-0.000490,-0.022951,0.013498,0.009664,-0.007012,-0.016325,-0.005732,0.036069,-0.063906,0.033891,0.010560,-0.104517,-0.022069,0.054322,-0.005460,-0.029093,0.040991,-0.053018,-0.024017,0.050817,-0.003297,-0.020895,-0.053213,-0.028428,0.048231,-0.001221,0.001302,-0.044137,0.015528,-0.012792,-0.012009,-0.008211,0.031114,0.024982,0.003863,-0.032321,0.030920,-0.012845,0.070170,-0.004037,0.014003,0.005577,0.021611,-0.002889,0.034824,0.047164,0.050545,-0.017639,0.029014,-0.030378,-0.027056,0.011464,-0.039759,-0.043514,-0.025605,-0.022484,-0.036224,0.000566,0.005481
7,2022-02-24 03:00:00,2,49.2336,28.4486,2.8,-0.3,80.5,0.3,100.0,4.17,0.0,0.0,27.7,10.8,312.0,1023.4,82.5,60.4,5.4,3.0,0.77,1.9,-0.3,91.75,0.0,0.0,0.0,15.1,7.2,288.9,1021.0,98.8,0.0,0.1,0.0,False,False,False,True,False,True,False,False,2022,2,3,3,Vinnytsia,Europe/Kiev,2022-02-24,06:58:49,17:40:52,03:00:00,Вінницька,0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0.0,0.0,4,0.580161,-0.090608,-0.028388,0.146350,0.071072,-0.030284,-0.004583,0.087399,-0.038512,0.016613,-0.038599,0.049747,0.186305,-0.172198,-0.045515,0.050785,0.041889,-0.112849,0.193473,-0.010566,0.044308,-0.118300,0.007117,-0.135687,-0.009441,-0.039465,0.032843,0.080393,-0.035434,0.010352,-0.016680,-0.046252,0.085840,-0.123167,0.064510,-0.023735,-0.025637,-0.027863,0.032156,0.068641,0.027667,0.162729,0.039675,-0.016915,-0.008203,0.048024,0.073343,0.025782,-0.013935,-0.008775,-0.045265,0.008979,-0.100558,0.044074,0.018202,-0.037279,0.062349,0.008014,0.075917,-0.063409,0.015404,-0.091507,-0.079240,-0.033000,-0.019226,-0.103926,0.031514,0.043306,-0.012137,-0.010430,0.035901,-0.013437,-0.042046,-0.064986,0.002947,0.024326,0.085592,-0.008453,0.091087,-0.106852,0.038223,-0.061062,0.027905,0.056421,-0.030501,0.000050,0.051385,-0.087324,-0.024025,0.031626,-0.029461,0.015717,-0.047181,-0.005600,0.049867,0.084412,-0.055460,-0.036620,0.120475,-0.012080,0.006961,-0.079701,0.055655,0.004130,0.013250,0.002392,0.041937,0.028208,-0.037232,0.014886,-0.036905,0.000138,-0.018200,-0.010680,-0.067564,-0.001064,-0.044792,-0.014807,-0.031911,-0.023504,0.070783,0.027626,0.000418,0.043677,-0.030193,-0.034979,0.080093,0.035489,-0.004156,-0.008032,0.039826,-0.037380,0.011931,0.008267,0.000590,0.043862,0.023758,0.038714,0.066128,0.028168,-0.012153,0.005376,0.008085,-0.038933,0.003404,0.003281,-0.004149,-0.025392,0.010434,-0.017613
8,2022-02-24 04:00:00,2,49.2336,28.4486,2.8,-0.3,80.5,0.3,100.0,4.17,0.0,0.0,27.7,10.8,312.0,1023.4,82.5,60.4,5.4,3.0,0.77,1.8,-0.2,92.40,0.0,0.0,0.0,13.7,6.5,290.4,1021.0,100.0,0.0,0.1,0.0,False,False,False,True,False,True,False,False,2022,2,3,4,Vinnytsia,Europe/Kiev,2022-02-24,06:58:49,17:40:52,04:00:00,Вінницька,0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0.0,0.0,5,0.648336,-0.079572,0.178041,0.061854,0.073453,-0.055809,-0.011311,0.047310,0.008354,0.006474,-0.047099,0.020496,0.050190,-0.038573,0.057228,-0.072471,0.045393,-0.116783,0.168249,0.167355,-0.025072,-0.073858,-0.097024,-0.146191,0.027983,0.082989,0.014423,0.058370,-0.033928,0.046265,0.006901,-0.049498,0.126117,-0.089039,-0.006767,-0.031686,-0.010346,0.025637,0.061278,0.162580,-0.028081,0.161291,-0.018217,-0.002657,0.038485,-0.000530,0.044413,0.107176,-0.050721,0.064279,-0.066677,0.016742,-0.050257,0.072549,-0.035201,-0.027279,0.017115,0.043631,0.024660,-0.025841,0.031320,-0.076959,-0.072986,-0.040465,0.003958,-0.022475,0.033208,-0.028056,-0.005499,-0.055998,-0.021882,-0.070462,0.018237,-0.031396,-0.074606,0.072951,0.039997,0.036423,-0.027152,-0.071900,0.026267,-0.046270,-0.017945,0.007933,-0.006203,-0.046099,0.032793,-0.069113,0.020403,0.030783,-0.003787,-0.000490,-0.022951,0.013498,0.009664,-0.007012,-0.016325,-0.005732,0.036069,-0.063906,0.033891,0.010560,-0.104517,-0.022069,0.054322,-0.005460,-0.029093,0.040991,-0.053018,-0.024017,0.050817,-0.003297,-0.020895,-0.053213,-0.028428,0.048231,-0.001221,0.001302,-0.044137,0.015528,-0.012792,-0.012009,-0.008211,0.031114,0.024982,0.003863,-0.032321,0.030920,-0.012845,0.070170,-0.004037,0.014003,0.005577,0.021611,-0.002889,0.034824,0.047164,0.050545,-0.017639,0.029014,-0.030378,-0.027056,0.011464,-0.039759,-0.043514,-0.025605,-0.022484,-0.036224,0.000566,0.005481

In [18]:
df_final.isna().sum()

datetime_hour        0
region_id            0
city_latitude        0
city_longitude       0
day_temp             0
                  ...
isw_topic_145     5760
isw_topic_146     5760
isw_topic_147     5760
isw_topic_148     5760
isw_topic_149     5760
Length: 216, dtype: int64

In [19]:
df_final.fillna(0, inplace=True)

,datetime_hour,region_id,city_latitude,city_longitude,day_temp,day_dew,day_humidity,day_precip,day_precipprob,day_precipcover,day_snow,day_snowdepth,day_windgust,day_windspeed,day_winddir,day_pressure,day_cloudcover,day_solarradiation,day_solarenergy,day_uvindex,day_moonphase,hour_temp,hour_feelslike,hour_humidity,hour_precip,hour_precipprob,hour_snow,hour_windgust,hour_windspeed,hour_winddir,hour_pressure,hour_cloudcover,hour_solarradiation,hour_solarenergy,hour_uvindex,day_conditions_simple_Clear,day_conditions_simple_Cloudy,day_conditions_simple_Rain,day_conditions_simple_Snow,hour_conditions_simple_Clear,hour_conditions_simple_Cloudy,hour_conditions_simple_Rain,hour_conditions_simple_Snow,year,month,day_of_week,hour,city_name,city_timezone,day_datetime,day_sunrise,day_sunset,hour_datetime,region_key,alarm_active,alarm_minutes_in_hour,alarm_lag_1,alarm_lag_3,alarm_lag_6,alarm_lag_12,alarms_in_last_24h,is_weekend,is_night,total_active_alarms_lag1,neighbour_alarms,hours_since_last_alarm,isw_topic_0,isw_topic_1,isw_topic_2,isw_topic_3,isw_topic_4,isw_topic_5,isw_topic_6,isw_topic_7,isw_topic_8,isw_topic_9,isw_topic_10,isw_topic_11,isw_topic_12,isw_topic_13,isw_topic_14,isw_topic_15,isw_topic_16,isw_topic_17,isw_topic_18,isw_topic_19,isw_topic_20,isw_topic_21,isw_topic_22,isw_topic_23,isw_topic_24,isw_topic_25,isw_topic_26,isw_topic_27,isw_topic_28,isw_topic_29,isw_topic_30,isw_topic_31,isw_topic_32,isw_topic_33,isw_topic_34,isw_topic_35,isw_topic_36,isw_topic_37,isw_topic_38,isw_topic_39,isw_topic_40,isw_topic_41,isw_topic_42,isw_topic_43,isw_topic_44,isw_topic_45,isw_topic_46,isw_topic_47,isw_topic_48,isw_topic_49,isw_topic_50,isw_topic_51,isw_topic_52,isw_topic_53,isw_topic_54,isw_topic_55,isw_topic_56,isw_topic_57,isw_topic_58,isw_topic_59,isw_topic_60,isw_topic_61,isw_topic_62,isw_topic_63,isw_topic_64,isw_topic_65,isw_topic_66,isw_topic_67,isw_topic_68,isw_topic_69,isw_topic_70,isw_topic_71,isw_topic_72,isw_topic_73,isw_topic_74,isw_topic_75,isw_topic_76,isw_topic_77,isw_topic_78,isw_topic_79,isw_topic_80,isw_topic_81,isw_topic_82,isw_topic_83,isw_topic_84,isw_topic_85,isw_topic_86,isw_topic_87,isw_topic_88,isw_topic_89,isw_topic_90,isw_topic_91,isw_topic_92,isw_topic_93,isw_topic_94,isw_topic_95,isw_topic_96,isw_topic_97,isw_topic_98,isw_topic_99,isw_topic_100,isw_topic_101,isw_topic_102,isw_topic_103,isw_topic_104,isw_topic_105,isw_topic_106,isw_topic_107,isw_topic_108,isw_topic_109,isw_topic_110,isw_topic_111,isw_topic_112,isw_topic_113,isw_topic_114,isw_topic_115,isw_topic_116,isw_topic_117,isw_topic_118,isw_topic_119,isw_topic_120,isw_topic_121,isw_topic_122,isw_topic_123,isw_topic_124,isw_topic_125,isw_topic_126,isw_topic_127,isw_topic_128,isw_topic_129,isw_topic_130,isw_topic_131,isw_topic_132,isw_topic_133,isw_topic_134,isw_topic_135,isw_topic_136,isw_topic_137,isw_topic_138,isw_topic_139,isw_topic_140,isw_topic_141,isw_topic_142,isw_topic_143,isw_topic_144,isw_topic_145,isw_topic_146,isw_topic_147,isw_topic_148,isw_topic_149
0,2022-02-24 00:00:00,2,49.2336,28.4486,2.8,-0.3,80.5,0.3,100.0,4.17,0.0,0.0,27.7,10.8,312.0,1023.4,82.5,60.4,5.4,3.0,0.77,2.1,-0.5,91.76,0.0,0.0,0.0,16.6,8.6,279.6,1021.0,91.1,0.0,0.1,0.0,False,False,False,True,False,True,False,False,2022,2,3,0,Vinnytsia,Europe/Kiev,2022-02-24,06:58:49,17:40:52,00:00:00,Вінницька,0,0.000000,0.0,0.0,0.0,0.0,0.0,0,1,0.0,0.0,1,0.648336,-0.079572,0.178041,0.061854,0.073453,-0.055809,-0.011311,0.047310,0.008354,0.006474,-0.047099,0.020496,0.050190,-0.038573,0.057228,-0.072471,0.045393,-0.116783,0.168249,0.167355,-0.025072,-0.073858,-0.097024,-0.146191,0.027983,0.082989,0.014423,0.058370,-0.033928,0.046265,0.006901,-0.049498,0.126117,-0.089039,-0.006767,-0.031686,-0.010346,0.025637,0.061278,0.162580,-0.028081,0.161291,-0.018217,-0.002657,0.038485,-0.000530,0.044413,0.107176,-0.050721,0.064279,-0.066677,0.016742,-0.050257,0.072549,-0.035201,-0.027279,0.017115,0.043631,0.024660,-0.025841,0.031320,-0.076959,-0.072986,-0.040465,0.003958,-0.022475,0.033208,-0.028056,-0.005499,-0.055998,-0.021882,-0.070462,0.018237,-0.031396,-0.074606,0.072951,0.039997,0.036423,-0.027152,-0.071900,0.026267,-0.046270,-0.017945,0.007933,-0.006203,-0.046099,0.032793,-0.069113,0.020403,0.030783,-0.003787,-0.000490,-0.022951,0.013498,0.009664,-0.007012,-0.016325,-0.005732,0.036069,-0.063906,0.033891,0.010560,-0.104517,-0.022069,0.054322,-0.005460,-0.029093,0.040991,-0.053018,-0.024017,0.050817,-0.003297,-0.020895,-0.053213,-0.028428,0.048231,-0.001221,0.001302,-0.044137,0.015528,-0.012792,-0.012009,-0.008211,0.031114,0.024982,0.003863,-0.032321,0.030920,-0.012845,0.070170,-0.004037,0.014003,0.005577,0.021611,-0.002889,0.034824,0.047164,0.050545,-0.017639,0.029014,-0.030378,-0.027056,0.011464,-0.039759,-0.043514,-0.025605,-0.022484,-0.036224,0.000566,0.005481
1,2022-02-24 00:00:00,2,49.2336,28.4486,2.8,-0.3,80.5,0.3,100.0,4.17,0.0,0.0,27.7,10.8,312.0,1023.4,82.5,60.4,5.4,3.0,0.77,2.1,-0.5,91.76,0.0,0.0,0.0,16.6,8.6,279.6,1021.0,91.1,0.0,0.1,0.0,False,False,False,True,False,True,False,False,2022,2,3,0,Vinnytsia,Europe/Kiev,2022-02-24,06:58:49,17:40:52,00:00:00,Вінницька,0,0.000000,0.0,0.0,0.0,0.0,0.0,0,1,0.0,0.0,1,0.580161,-0.090608,-0.028388,0.146350,0.071072,-0.030284,-0.004583,0.087399,-0.038512,0.016613,-0.038599,0.049747,0.186305,-0.172198,-0.045515,0.050785,0.041889,-0.112849,0.193473,-0.010566,0.044308,-0.118300,0.007117,-0.135687,-0.009441,-0.039465,0.032843,0.080393,-0.035434,0.010352,-0.016680,-0.046252,0.085840,-0.123167,0.064510,-0.023735,-0.025637,-0.027863,0.032156,0.068641,0.027667,0.162729,0.039675,-0.016915,-0.008203,0.048024,0.073343,0.025782,-0.013935,-0.008775,-0.045265,0.008979,-0.100558,0.044074,0.018202,-0.037279,0.062349,0.008014,0.075917,-0.063409,0.015404,-0.091507,-0.079240,-0.033000,-0.019226,-0.103926,0.031514,0.043306,-0.012137,-0.010430,0.035901,-0.013437,-0.042046,-0.064986,0.002947,0.024326,0.085592,-0.008453,0.091087,-0.106852,0.038223,-0.061062,0.027905,0.056421,-0.030501,0.000050,0.051385,-0.087324,-0.024025,0.031626,-0.029461,0.015717,-0.047181,-0.005600,0.049867,0.084412,-0.055460,-0.036620,0.120475,-0.012080,0.006961,-0.079701,0.055655,0.004130,0.013250,0.002392,0.041937,0.028208,-0.037232,0.014886,-0.036905,0.000138,-0.018200,-0.010680,-0.067564,-0.001064,-0.044792,-0.014807,-0.031911,-0.023504,0.070783,0.027626,0.000418,0.043677,-0.030193,-0.034979,0.080093,0.035489,-0.004156,-0.008032,0.039826,-0.037380,0.011931,0.008267,0.000590,0.043862,0.023758,0.038714,0.066128,0.028168,-0.012153,0.005376,0.008085,-0.038933,0.003404,0.003281,-0.004149,-0.025392,0.010434,-0.017613
2,2022-02-24 01:00:00,2,49.2336,28.4486,2.8,-0.3,80.5,0.3,100.0,4.17,0.0,0.0,27.7,10.8,312.0,1023.4,82.5,60.4,5.4,3.0,0.77,2.1,-0.4,89.80,0.0,0.0,0.0,16.6,8.3,289.2,1021.0,97.9,0.0,0.1,0.0,False,False,False,True,False,True,False,False,2022,2,3,1,Vinnytsia,Europe/Kiev,2022-02-24,06:58:49,17:40:52,01:00:00,Вінницька,0,0.000000,0.0,0.0,0.0,0.0,0.0,0,1,0.0,0.0,2,0.648336,-0.079572,0.178041,0.061854,0.073453,-0.055809,-0.011311,0.047310,0.008354,0.006474,-0.047099,0.020496,0.050190,-0.038573,0.057228,-0.072471,0.045393,-0.116783,0.168249,0.167355,-0.025072,-0.073858,-0.097024,-0.146191,0.027983,0.082989,0.014423,0.058370,-0.033928,0.046265,0.006901,-0.049498,0.126117,-0.089039,-0.006767,-0.031686,-0.010346,0.025637,0.061278,0.162580,-0.028081,0.161291,-0.018217,-0.002657,0.038485,-0.000530,0.044413,0.107176,-0.050721,0.064279,-0.066677,0.016742,-0.050257,0.072549,-0.035201,-0.027279,0.017115,0.043631,0.024660,-0.025841,0.031320,-0.076959,-0.072986,-0.040465,0.003958,-0.022475,0.033208,-0.028056,-0.005499,-0.055998,-0.021882,-0.070462,0.018237,-0.031396,-0.074606,0.072951,0.039997,0.036423,-0.027152,-0.071900,0.026267,-0.046270,-0.017945,0.007933,-0.006203,-0.046099,0.032793,-0.069113,0.020403,0.030783,-0.003787,-0.000490,-0.022951,0.013498,0.009664,-0.007012,-0.016325,-0.005732,0.036069,-0.063906,0.033891,0.010560,-0.104517,-0.022069,0.054322,-0.005460,-0.029093,0.040991,-0.053018,-0.024017,0.050817,-0.003297,-0.020895,-0.053213,-0.028428,0.048231,-0.001221,0.001302,-0.044137,0.015528,-0.012792,-0.012009,-0.008211,0.031114,0.024982,0.003863,-0.032321,0.030920,-0.012845,0.070170,-0.004037,0.014003,0.005577,0.021611,-0.002889,0.034824,0.047164,0.050545,-0.017639,0.029014,-0.030378,-0.027056,0.011464,-0.039759,-0.043514,-0.025605,-0.022484,-0.036224,0.000566,0.005481
3,2022-02-24 01:00:00,2,49.2336,28.4486,2.8,-0.3,80.5,0.3,100.0,4.17,0.0,0.0,27.7,10.8,312.0,1023.4,82.5,60.4,5.4,3.0,0.77,2.1,-0.4,89.80,0.0,0.0,0.0,16.6,8.3,289.2,1021.0,97.9,0.0,0.1,0.0,False,False,False,True,False,True,False,False,2022,2,3,1,Vinnytsia,Europe/Kiev,2022-02-24,06:58:49,17:40:52,01:00:00,Вінницька,0,0.000000,0.0,0.0,0.0,0.0,0.0,0,1,0.0,0.0,2,0.580161,-0.090608,-0.028388,0.146350,0.071072,-0.030284,-0.004583,0.087399,-0.038512,0.016613,-0.038599,0.049747,0.186305,-0.172198,-0.045515,0.050785,0.041889,-0.112849,0.193473,-0.010566,0.044308,-0.118300,0.007117,-0.135687,-0.009441,-0.039465,0.032843,0.080393,-0.035434,0.010352,-0.016680,-0.046252,0.085840,-0.123167,0.064510,-0.023735,-0.025637,-0.027863,0.032156,0.068641,0.027667,0.162729,0.039675,-0.016915,-0.008203,0.048024,0.073343,0.025782,-0.013935,-0.008775,-0.045265,0.008979,-0.100558,0.044074,0.018202,-0.037279,0.062349,0.008014,0.075917,-0.063409,0.015404,-0.091507,-0.079240,-0.033000,-0.019226,-0.103926,0.031514,0.043306,-0.012137,-0.010430,0.035901,-0.013437,-0.042046,-0.064986,0.002947,0.024326,0.085592,-0.008453,0.091087,-0.106852,0.038223,-0.061062,0.027905,0.056421,-0.030501,0.000050,0.051385,-0.087324,-0.024025,0.031626,-0.029461,0.015717,-0.047181,-0.005600,0.049867,0.084412,-0.055460,-0.036620,0.120475,-0.012080,0.006961,-0.079701,0.055655,0.004130,0.013250,0.002392,0.041937,0.028208,-0.037232,0.014886,-0.036905,0.000138,-0.018200,-0.010680,-0.067564,-0.001064,-0.044792,-0.014807,-0.031911,-0.023504,0.070783,0.027626,0.000418,0.043677,-0.030193,-0.034979,0.080093,0.035489,-0.004156,-0.008032,0.039826,-0.037380,0.011931,0.008267,0.000590,0.043862,0.023758,0.038714,0.066128,0.028168,-0.012153,0.005376,0.008085,-0.038933,0.003404,0.003281,-0.004149,-0.025392,0.010434,-0.017613
4,2022-02-24 02:00:00,2,49.2336,28.4486,2.8,-0.3,80.5,0.3,100.0,4.17,0.0,0.0,27.7,10.8,312.0,1023.4,82.5,60.4,5.4,3.0,0.77,2.0,-0.3,90.44,0.0,0.0,0.0,27.7,7.6,287.6,1021.0,98.2,0.0,0.1,0.0,False,False,False,True,False,True,False,False,2022,2,3,2,Vinnytsia,Europe/Kiev,2022-02-24,06:58:49,17:40:52,02:00:00,Вінницька,0,0.000000,0.0,0.0,0.0,0.0,0.0,0,1,0.0,0.0,3,0.648336,-0.079572,0.178041,0.061854,0.073453,-0.055809,-0.011311,0.047310,0.008354,0.006474,-0.047099,0.020496,0.050190,-0.038573,0.057228,-0.072471,0.045393,-0.116783,0.168249,0.167355,-0.025072,-0.073858,-0.097024,-0.146191,0.027983,0.082989,0.014423,0.058370,-0.033928,0.046265,0.006901,-0.049498,0.126117,-0.089039,-0.006767,-0.031686,-0.010346,0.025637,0.061278,0.162580,-0.028081,0.161291,-0.018217,-0.002657,0.038485,-0.000530,0.044413,0.107176,-0.050721,0.064279,-0.066677,0.016742,-0.050257,0.072549,-0.035201,-0.027279,0.017115,0.043631,0.024660,-0.025841,0.031320,-0.076959,-0.072986,-0.040465,0.003958,-0.022475,0.033208,-0.028056,-0.005499,-0.055998,-0.021882,-0.070462,0.018237,-0.031396,-0.074606,0.072951,0.039997,0.036423,-0.027152,-0.071900,0.026267,-0.046270,-0.017945,0.007933,-0.006203,-0.046099,0.032793,-0.069113,0.020403,0.030783,-0.003787,-0.000490,-0.022951,0.013498,0.009664,-0.007012,-0.016325,-0.005732,0.036069,-0.063906,0.033891,0.010560,-0.104517,-0.022069,0.054322,-0.005460,-0.029093,0.040991,-0.053018,-0.024017,0.050817,-0.003297,-0.020895,-0.053213,-0.028428,0.048231,-0.001221,0.001302,-0.044137,0.015528,-0.012792,-0.012009,-0.008211,0.031114,0.024982,0.003863,-0.032321,0.030920,-0.012845,0.070170,-0.004037,0.014003,0.005577,0.021611,-0.002889,0.034824,0.047164,0.050545,-0.017639,0.029014,-0.030378,-0.027056,0.011464,-0.039759,-0.043514,-0.025605,-0.022484,-0.036224,0.000566,0.005481
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
635251,2025-03-01 19:00:00,26,50.4506,30.5243,0.0,-2.6,82.9,0.7,100.0,8.33,1.3,1.0,34.6,15.5,178.1,1026.7,99.5,40.6,3.6,2.0,0.05,-0.1,-3.5,97.13,0.0,0.0,0.0,16.9,10.1,181.6,1027.0,95.6,0.0,0.0,0.0,False,False,False,True,False,True,False,False,2025,3,5,19,Kyiv,Europe/Kiev,2025-03-01,06:41:35,17:39:46,19:00:00,Київ,0,0.000000,0.0,0.0,0.0,0.0,5.0,1,0,11.0,0.0,15,0.741253,0.175928,-0.044270,0.236290,0.000096,-0.082156,-0.069547,0.169634,0.047371,0.108829,-0.111513,0.005588,0.009037,-0.035562,0.049145,0.077242,-0.085251,0.067886,0.052548,-0.120459,0.081966,-0.062164,0.022709,0.023532,-0.002714,0.000626,-0.026931,0.012943,-0.027664,-0.111107,-0.094103,-0.019189,-0.002106,0.023217,0.036788,-0.009149,-0.051459,-0.073844,-0.016720,-0.019477,-0.024286,0.075470,-0.053957,-0.052265,0.022580,-0.016046,-0.047243,0.005718,0.019756,-0.035501,0.025955,0.020804,-0.008431,0.005311,-0.038751,-0.010557,-0.009238,-0.005986,-0.035657,-0.003185,-0.030416,-0.013563,-0.026338,0.069073,-0.003216,0.021366,0.025951,-0.017980,0.006948,0.029034,0.069441,-0.043368,0.028677,0.035237,-0.023784,-0.005083,0.028958,0.012654,0.001550,-0.039223,0.020654,-0.040622,0.014536,0.002429,-0.013533,0.003547,-0.061560,0.020515,-0.017876,0.041345,-0.033319,-0.020192,0.035267,0.011339,-0.088522,0.022461,-0.047734,-0.034346,-0.011346,0.043122,0.001617,-0.023157,-0.018391,-0.006131,0.040270,0.030336,0.007110,0.024232,0.035189,-0.038329,0.020301,0.032434,0.007683,-0.010900,-0.008896,-0.019209,0.007017,0.040898,-0.031859,0.000779,-0.002852,0.028824,0.006013,0.010350,0.013379,-0.027336,-0.003269,0.008264,0.004228,0.022508,-0.012380,0.000627,0.017807,-0.013325,-0.006459,0.021368,-0.027278,-0.008352,0.001816,0.004596,0.019812,-0.012733,-0.001035,-0.001903,0.005062,-0.015576,0.028419,-0.012698,0.016105,-0.007801
635252,2025-03-01 20:00:00,26,50.4506,30.5243,0.0,-2.6,82.9,0.7,100.0,8.33,1.3,1.0,34.6,15.5,178.1,1026.7,99.5,40.6,3.6,2.0,0.05,-0.3,-0.3,92.96,0.4,100.0,0.0,17.6,0.0,189.9,1027.0,100.0,0.0,0.0,0.0,False,False,False,True,False,False,False,True,2025,3,5,20,Kyiv,Europe/Kiev,2025-03-01,06:41:35,17:39:46,20:00:00,Київ,0,0.000000,0.0,0.0,0.0,0.0,5.0,1,0,5.0,0.0,16,0.741253,0.175928,-0.044270,0.236290,0.000096,-0.082156,-0.069547,0.169634,0.047371,0.108829,-0.111513,0.005588,0.009037,-0.035562,0.049145,0.077242,-0.085251,0.067886,0.052548,-0.120459,0.081966,-0.062164,0.022709,0.023532,-0.002714,0.000626,-0.026931,0.012943,-0.027664,-0.111107,-0.094103,-0.019189,-0.002106,0.023217,0.036788,-0.009149,-0.051459,-0.073844,-0.016720,-0.019477,-0.024286,0.075470,-0.053957,-0.052265,0.022580,-0.016046,-0.047243,0.005718,0.019756,-0.035501,0.025955,0.020804,-0.008431,0.005311,-0.038751,-0.010557,-0.009238,-0.005986,-0.035657,-0.003185,-0.030416,-0.013563,-0.026338,0.069073,-0.003216,0.021366,0.025951,-0.017980,0.006948,0.029034,0.069441,-0.043368,0.028677,0.035237,-0.023784,-0.005083,0.028958,0.012654,0.001550,-0.039223,0.020654,-0.040622,0.014536,0.002429,-0.013533,0.003547,-0.061560,0.020515,-0.017876,0.041345,-0.033319,-0.020192,0.035267,0.011339,-0.088522,0.022461,-0.047734,-0.034346,-0.011346,0.043122,0.001617,-0.023157,-0.018391,-0.006131,0.040270,0.030336,0.007110,0.024232,0.035189,-0.038329,0.020301,0.032434,0.007683,-0.010900,-0.008896,-0.019209,0.007017,0.040898,-0.031859,0.000779,-0.002852,0.028824,0.006013,0.010350,0.013379,-0.027336,-0.003269,0.008264,0.004228,0.022508,-0.012380,0.000627,0.017807,-0.013325,-0.006459,0.021368,-0.027278,-0.008352,0.001816,0.004596,0.019812,-0.012733,-0.001035,-0.001903,0.005062,-0.015576,0.028419,-0.012698,0.016105,-0.007801
635253,2025-03-01 21:00:00,26,50.4506,30.5243,0.0,-2.6,82.9,0.7,100.0,8.33,1.3,1.0,34.6,15.5,178.1,1026.7,99.5,40.6,3.6,2.0,0.05,0.0,-3.2,96.43,0.0,0.0,0.0,18.4,9.4,198.3,1027.0,100.0,0.0,0.0,0.0,False,False,False,True,False,True,False,False,2025,3,5,21,Kyiv,Europe/Kiev,2025-03-01,06:41:35,17:39:46,21:00:00,Київ,0,0.000000,0.0,0.0,0.0,0.0,5.0,1,0,9.0,0.0,17,0.741253,0.175928,-0.044270,0.236290,0.000096,-0.082156,-0.069547,0.169634,0.047371,0.108829,-0.111513,0.005588,0.009037,-0.035562,0.049145,0.077242,-0.085251,0.067886,0.052548,-0.120459,0.081966,-0.062164,0.022709,0.023532,-0.002714,0.000626,-0.026931,0.012943,-0.027664,-0.111107,-0.094103,-0.019189,-0.002106,0.023217,0.036788,-0.009149,-0.051459,-0.073844,-0.016720,-0.019477,-0.024286,0.075470,-0.053957,-0.052265,0.022580,-0.016046,-0.047243,0.005718,0.019756,-0.035501,0.025955,0.020804,-0.008431,0.005311,-0.038751,-0.010557,-0.009238,-0.005986,-0.035657,-0.003185,-0.030416,-0.013563,-0.026338,0.069073,-0.003216,0.021366,0.025951,-0.017980,0.006948,0.029034,0.069441,-0.043368,0.028677,0.035237,-0.023784,-0.005083,0.028958,0.012654,0.001550,-0.039223,0.020654,-0.040622,0.014536,0.002429,-0.013533,0.003547,-0.061560,0.020515,-0.017876,0.041345,-0.033319,-0.020192,0.035267,0.011339,-0.088522,0.022461,-0.047734,-0.034346,-0.011346,0.043122,0.001617,-0.023157,-0.018391,-0.006131,0.040270,0.030336,0.007110,0.024232,0.035189,-0.038329,0.020301,0.032434,0.007683,-0.010900,-0.008896,-0.019209,0.007017,0.040898,-0.031859,0.000779,-0.002852,0.028824,0.006013,0.010350,0.013379,-0.027336,-0.003269,0.008264,0.004228,0.022508,-0.012380,0.000627,0.017807,-0.013325,-0.006459,0.021368,-0.027278,-0.008352,0.001816,0.004596,0.019812,-0.012733,-0.001035,-0.001903,0.005062,-0.015576,0.028419,-0.012698,0.016105,-0.007801
635254,2025-03-01 22:00:00,26,50.4506,30.5243,0.0,-2.6,82.9,0.7,100.0,8.33,1.3,1.0,34.6,15.5,178.1,1026.7,99.5,40.6,3.6,2.0,0.05,0.0,-2.9,97.84,0.0,0.0,0.0,16.6,8.3,199.9,1027.0,97.6,0.0,0.0,0.0,False,False,False,True,False,True,False,False,2025,3,5,22,Kyiv,Europe/Kiev,2025-03-01,06:41:35,17:39:46,22:00:00,Київ,1,7.833333,0.0,0.0,0.0,0.0,5.0,1,0,11.0,0.0,18,0.741253,0.175928,-0.044270,0.236290,0.000096,-0.082156,-0.069547,0.169634,0.047371,0.108829,-0.111513,0.005588,0.009037,-0.035562,0.049145,0.077242,-0.085251,0.067886,0.052548,-0.120459,0.081966,-0.062164,0.022709,0.023532,-0.002714,0.000626,-0.026931,0.012943,-0.027664,-0.111107,-0.094103,-0.019189,-0.002106,0.023217,0.036788,-0.009149,-0.051459,-0.073844,-0.016720,-0.019477,-0.024286,0.075470,-0.053957,-0.052265,0.022580,-0.016046,-0.047243,0.005718,0.019756,-0.035501,0.025955,0.020804,-0.008431,0.005311,-0.038751,-0.010557,-0.009238,-0.005986,-0.035657,-0.003185,-0.030416,-0.013563,-0.026338,0.069073,-0.003216,0.021366,0.025951,-0.017980,0.006948,0.029034,0.069441,-0.043368,0.028677,0.035237,-0.023784,-0.005083,0.028958,0.012654,0.001550,-0.039223,0.020654,-0.040622,0.014536,0.002429,-0.013533,0.003547,-0.061560,0.020515,-0.017876,0.041345,-0.033319,-0.020192,0.035267,0.011339,-0.088522,0.022461,-0.047734,-0.034346,-0.011346,0.043122,0.001617,-0.023157,-0.018391,-0.006131,0.040270,0.030336,0.007110,0.024232,0.035189,-0.038329,0.020301,0.032434,0.007683,-0.010900,-0.008896,-0.019209,0.007017,0.040898,-0.031859,0.000779,-0.002852,0.028824,0.006013,0.010350,0.013379,-0.027336,-0.003269,0.008264,0.004228,0.022508,-0.012380,0.000627,0.017807,-0.013325,-0.006459,0.021368,-0.027278,-0.008352,0.001816,0.004596,0.019812,-0.012733,-0.001035,-0.001903,0.005062,-0.015576,0.028419,-0.012698,0.016105,-0.007801

In [20]:
df_final.isna().sum()

datetime_hour     0
region_id         0
city_latitude     0
city_longitude    0
day_temp          0
                 ..
isw_topic_145     0
isw_topic_146     0
isw_topic_147     0
isw_topic_148     0
isw_topic_149     0
Length: 216, dtype: int64

### Feature engineering for isw topics

In [21]:
topic_cols = [c for c in df_final.columns if "isw_topic_" in c]
df_isw_abs = df_final[topic_cols].abs()

df_final['isw_total_intensity'] = df_isw_abs.sum(axis=1)
df_final['isw_topic_std'] = df_isw_abs.std(axis=1)
df_final['isw_topic_max'] = df_isw_abs.max(axis=1)
df_final['isw_topic_mean'] = df_isw_abs.mean(axis=1)

df_final['isw_velocity_24h'] = (
    df_final.groupby('region_id')['isw_total_intensity']
    .diff(24)
    .fillna(0)
)

df_final['isw_intensity_ema'] = (df_final.groupby('region_id')['isw_total_intensity'].transform(lambda x: x.shift(1).ewm(span=24).mean()))

df_final['isw_topic_entropy'] = -(df_isw_abs.div(df_isw_abs.sum(axis=1), axis=0) * np.log(df_isw_abs.div(df_isw_abs.sum(axis=1), axis=0) + 1e-9)).sum(axis=1)

isw_cols = ['isw_velocity_24h', 'isw_intensity_ema', 'isw_topic_entropy']
df_final[isw_cols] = df_final[isw_cols].fillna(0)

C:\Users\Uw11\AppData\Local\Temp\ipykernel_22436\1269306822.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_final['isw_total_intensity'] = df_isw_abs.sum(axis=1)
C:\Users\Uw11\AppData\Local\Temp\ipykernel_22436\1269306822.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_final['isw_topic_std'] = df_isw_abs.std(axis=1)
C:\Users\Uw11\AppData\Local\Temp\ipykernel_22436\1269306822.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_final['isw_topic_max'] = df_isw_abs.max(axis=1)
C:\Users\Uw11\AppData\Local\Temp\ipykernel_22436\1269306822.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_final['isw_topic_mean'] = df_isw_abs.mean(axis=1)
C:\Users\Uw11\AppData\Local\Temp\ipykernel_22436\1269306822.py:9: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_final['isw_velocity_24h'] = (
C:\Users\Uw11\AppData\Local\Temp\ipykernel_22436\1269306822.py:15: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_final['isw_intensity_ema'] = (df_final.groupby('region_id')['isw_total_intensity'].transform(lambda x: x.shift(1).ewm(span=24).mean()))
C:\Users\Uw11\AppData\Local\Temp\ipykernel_22436\1269306822.py:17: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_final['isw_topic_entropy'] = -(df_isw_abs.div(df_isw_abs.sum(axis=1), axis=0) * np.log(df_isw_abs.div(df_isw_abs.sum(axis=1), axis=0) + 1e-9)).sum(axis=1)

In [22]:
df_final.sample(10)

,datetime_hour,region_id,city_latitude,city_longitude,day_temp,day_dew,day_humidity,day_precip,day_precipprob,day_precipcover,day_snow,day_snowdepth,day_windgust,day_windspeed,day_winddir,day_pressure,day_cloudcover,day_solarradiation,day_solarenergy,day_uvindex,day_moonphase,hour_temp,hour_feelslike,hour_humidity,hour_precip,hour_precipprob,hour_snow,hour_windgust,hour_windspeed,hour_winddir,hour_pressure,hour_cloudcover,hour_solarradiation,hour_solarenergy,hour_uvindex,day_conditions_simple_Clear,day_conditions_simple_Cloudy,day_conditions_simple_Rain,day_conditions_simple_Snow,hour_conditions_simple_Clear,hour_conditions_simple_Cloudy,hour_conditions_simple_Rain,hour_conditions_simple_Snow,year,month,day_of_week,hour,city_name,city_timezone,day_datetime,day_sunrise,day_sunset,hour_datetime,region_key,alarm_active,alarm_minutes_in_hour,alarm_lag_1,alarm_lag_3,alarm_lag_6,alarm_lag_12,alarms_in_last_24h,is_weekend,is_night,total_active_alarms_lag1,neighbour_alarms,hours_since_last_alarm,isw_topic_0,isw_topic_1,isw_topic_2,isw_topic_3,isw_topic_4,isw_topic_5,isw_topic_6,isw_topic_7,isw_topic_8,isw_topic_9,isw_topic_10,isw_topic_11,isw_topic_12,isw_topic_13,isw_topic_14,isw_topic_15,isw_topic_16,isw_topic_17,isw_topic_18,isw_topic_19,isw_topic_20,isw_topic_21,isw_topic_22,isw_topic_23,isw_topic_24,isw_topic_25,isw_topic_26,isw_topic_27,isw_topic_28,isw_topic_29,isw_topic_30,isw_topic_31,isw_topic_32,isw_topic_33,isw_topic_34,isw_topic_35,isw_topic_36,isw_topic_37,isw_topic_38,isw_topic_39,isw_topic_40,isw_topic_41,isw_topic_42,isw_topic_43,isw_topic_44,isw_topic_45,isw_topic_46,isw_topic_47,isw_topic_48,isw_topic_49,isw_topic_50,isw_topic_51,isw_topic_52,isw_topic_53,isw_topic_54,isw_topic_55,isw_topic_56,isw_topic_57,isw_topic_58,isw_topic_59,isw_topic_60,isw_topic_61,isw_topic_62,isw_topic_63,isw_topic_64,isw_topic_65,isw_topic_66,isw_topic_67,isw_topic_68,isw_topic_69,isw_topic_70,isw_topic_71,isw_topic_72,isw_topic_73,isw_topic_74,isw_topic_75,isw_topic_76,isw_topic_77,isw_topic_78,isw_topic_79,isw_topic_80,isw_topic_81,isw_topic_82,isw_topic_83,isw_topic_84,isw_topic_85,isw_topic_86,isw_topic_87,isw_topic_88,isw_topic_89,isw_topic_90,isw_topic_91,isw_topic_92,isw_topic_93,isw_topic_94,isw_topic_95,isw_topic_96,isw_topic_97,isw_topic_98,isw_topic_99,isw_topic_100,isw_topic_101,isw_topic_102,isw_topic_103,isw_topic_104,isw_topic_105,isw_topic_106,isw_topic_107,isw_topic_108,isw_topic_109,isw_topic_110,isw_topic_111,isw_topic_112,isw_topic_113,isw_topic_114,isw_topic_115,isw_topic_116,isw_topic_117,isw_topic_118,isw_topic_119,isw_topic_120,isw_topic_121,isw_topic_122,isw_topic_123,isw_topic_124,isw_topic_125,isw_topic_126,isw_topic_127,isw_topic_128,isw_topic_129,isw_topic_130,isw_topic_131,isw_topic_132,isw_topic_133,isw_topic_134,isw_topic_135,isw_topic_136,isw_topic_137,isw_topic_138,isw_topic_139,isw_topic_140,isw_topic_141,isw_topic_142,isw_topic_143,isw_topic_144,isw_topic_145,isw_topic_146,isw_topic_147,isw_topic_148,isw_topic_149,isw_total_intensity,isw_topic_std,isw_topic_max,isw_topic_mean,isw_velocity_24h,isw_intensity_ema,isw_topic_entropy
480528,2022-08-12 07:00:00,21,46.6401,32.6142,26.3,18.1,63.2,0.300,100.0,12.50,0.0,0.0,38.9,23.4,27.5,1010.9,64.0,142.4,12.2,5.0,0.48,22.4,22.4,67.11,0.000,0.0,0.0,34.9,23.4,8.4,1011.0,52.8,42.0,0.2,0.0,False,False,True,False,False,True,False,False,2022,8,4,7,Kherson,Europe/Kiev,2022-08-12,05:43:26,20:04:59,07:00:00,Херсонська,0,0.00,1.0,1.0,0.0,1.0,6.0,0,0,2.0,0.0,0,0.725403,-0.215571,0.199881,-0.060110,-0.080390,0.108017,0.010103,0.068705,0.138381,-0.108192,0.040550,-0.003107,-0.038401,-0.144589,-0.101464,0.073721,-0.108335,0.003920,-0.053107,-0.016416,-0.046681,0.041288,0.063766,-0.126378,0.114511,-0.055293,-0.113651,-0.095839,-0.006889,-0.045769,0.040402,0.002332,-0.009140,-0.036420,-0.021008,-0.031235,-0.005009,0.005115,-0.007556,-0.051869,-0.037470,-0.005588,0.032289,-0.025059,0.043514,-0.000166,-0.022387,0.002547,0.037568,-0.019907,0.008909,0.026504,-0.003893,0.012528,-0.003047,-0.007264,0.007063,0.006724,-0.009708,-0.052112,0.009218,-0.018477,-0.053095,0.015725,-0.039436,-0.024053,0.041252,0.014062,0.011979,0.027430,0.014833,-0.027153,-0.000499,0.008611,0.014519,0.010768,0.017154,-0.037872,-0.039898,0.003866,0.041286,-0.001490,-0.007813,-0.052410,-0.004002,-0.000235,0.006971,0.040223,-0.006082,0.018611,-0.021946,-0.000507,-0.042428,-0.011618,-0.035544,0.027140,0.046084,-0.037376,0.005969,0.051515,-0.032156,0.040023,-0.011151,-0.009160,-0.004969,-0.002255,0.011498,-0.033269,0.025271,-0.025874,-0.002398,-0.005963,0.020827,0.051955,-0.003743,0.013217,0.030562,-0.018221,0.012833,0.003021,0.018449,0.002059,-0.017266,-0.001922,-0.021396,-0.007349,-0.006716,-0.025633,0.003680,-0.010067,0.010066,0.030529,0.000035,-0.026008,-0.004984,0.031594,-0.004635,0.013866,-0.028428,-0.032408,0.023208,-0.032910,-0.019887,-0.040707,0.011661,0.017116,-0.025410,-0.005592,0.019830,-0.005939,5.329626,0.067090,0.725403,0.035531,0.316389,5.158708,4.285510
555681,2025-02-23 00:00:00,23,49.4407,32.0637,-5.7,-11.5,66.2,0.000,0.0,0.00,0.0,2.1,29.5,13.3,316.5,1035.5,1.1,136.4,11.7,5.0,0.85,-10.5,-14.2,84.54,0.000,0.0,0.0,10.8,6.1,300.7,1039.0,22.3,0.0,0.0,0.0,True,False,False,False,False,True,False,False,2025,2,6,0,Cherkasy,Europe/Kiev,2025-02-23,06:46:07,17:24:55,00:00:00,Черкаська,0,0.00,0.0,0.0,0.0,0.0,0.0,1,1,14.0,4.0,30,0.739080,0.247724,-0.043086,0.138830,0.024555,-0.002617,-0.017325,0.082623,-0.022115,0.052564,-0.031116,0.074383,0.230140,-0.237575,0.193023,-0.008187,-0.093247,0.036863,0.066861,-0.045646,0.040642,-0.024977,0.064052,-0.034978,0.005372,0.024849,0.000702,0.022192,-0.011514,-0.063925,-0.010856,-0.008643,0.000204,0.029723,0.018552,-0.046773,-0.028047,-0.071489,-0.015004,-0.024364,0.001666,0.001949,-0.008869,-0.054910,0.014567,-0.044456,-0.055785,0.049867,0.016768,-0.036161,0.034033,-0.022069,-0.030488,0.034543,-0.053473,0.048893,0.010478,-0.009486,0.017205,0.030175,-0.045377,0.022786,-0.003239,-0.010344,0.010689,0.047722,0.012789,-0.030705,0.037431,0.009017,0.002723,-0.013908,0.019531,0.016908,-0.006576,-0.020335,-0.007864,0.038520,0.006824,-0.032970,0.026771,0.037905,-0.023497,-0.010710,-0.006540,0.018830,0.001758,0.005375,-0.027334,-0.008877,-0.019781,0.025199,0.043920,0.022719,0.008416,0.030797,0.032043,-0.006878,0.001310,-0.002167,-0.030355,0.028044,0.003276,-0.012548,-0.010312,-0.004811,-0.032956,0.000095,-0.000839,0.000296,-0.002966,-0.012593,-0.013110,0.000280,0.031926,0.014244,0.001770,-0.018493,0.027873,-0.002791,-0.016037,0.023440,0.018700,-0.012228,0.020013,0.001688,-0.001731,0.023140,0.025832,-0.017992,0.012522,0.014132,0.002750,-0.005015,0.012081,0.019673,-0.011605,0.003082,0.014381,-0.004098,-0.037257,0.022181,0.032558,0.016166,-0.008408,-0.015302,-0.001298,0.002618,-0.024886,-0.012209,4.949951,0.069915,0.739080,0.033000,0.467338,4.464804,4.196064
324849,2022-12-20 22:00:00,15,46.4725,30.7371,0.2,-2.3,83.6,0.000,0.0,0.00,0.0,0.0,23.8,11.5,215.4,1036.3,45.0,61.7,5.3,3.0,0.88,2.2,-0.6,77.65,0.000,0.0,0.0,18.0,9.4,225.3,1030.0,99.6,0.0,0.1,0.0,False,True,False,False,False,True,False,False,2022,12,1,22,Odesa,Europe/Kiev,2022-12-20,07:37:18,16:11:56,22:00:00,Одеська,0,0.00,0.0,0.0,0.0,0.0,0.0,0,0,0.0,0.0,80,0.788089,-0.233450,-0.118115,-0.077445,0.129846,-0.017925,0.156792,0.108672,-0.123481,-0.037707,0.004514,-0.016905,-0.072351,-0.006665,0.017024,0.112494,0.012099,-0.084160,0.006672,-0.044341,0.002844,-0.036078,-0.017820,0.031111,-0.014215,0.055445,0.022791,-0.051026,-0.040868,0.012569,0.026332,0.044780,-0.012804,0.041623,0.000059,-0.040836,-0.010233,0.042576,-0.001542,-0.034583,-0.020445,0.022309,-0.021840,-0.000911,0.019198,0.029130,-0.051996,-0.048347,0.029064,0.025151,0.017504,0.010393,-0.031589,0.010715,-0.015616,0.013592,-0.011583,-0.016590,0.026268,-0.033099,0.010004,-0.002384,-0.034130,0.032536,-0.012595,0.005870,0.023313,0.013027,0.006274,0.014174,-0.020696,0.011466,-0.027454,-0.043716,0.022066,0.010097,-0.004488,-0.021308,-0.002951,-0.027088,0.012655,0.007664,-0.014988,-0.001596,0.027818,-0.027104,-0.005938,0.014249,0.013090,-0.012112,-0.021626,-0.003351,0.024050,0.002767,-0.017051,-0.015713,-0.001333,0.038916,-0.024184,0.011689,-0.022006,0.003380,-0.051853,-0.033100,-0.011825,-0.034790,-0.035735,-0.006964,0.023023,0.017061,0.024556,-0.004626,0.016827,-0.015963,-0.007153,0.008590,0.026168,-0.003864,-0.024879,0.014688,-0.003709,-0.008299,-0.010679,0.003680,-0.018871,0.014517,0.041205,0.020326,-0.032253,-0.000311,-0.007522,-0.016271,-0.000421,0.009888,-0.005954,0.028739,0.023853,-0.023863,0.007392,-0.016557,0.001327,0.027517,-0.002774,0.024659,-0.007129,-0.003305,-0.030573,-0.018977,-0.007428,-0.008258,4.621062,0.069497,0.788089,0.030807,-0.140046,4.679729,4.217333
568298,2023-07-26 19:00:00,24,48.2924,25.9355,19.8,17.8,88.7,12.132,100.0,33.33,0.0,0.1,39.6,14.4,346.3,1003.2,76.9,110.2,9.4,4.0,0.25,19.3,19.3,95.26,0.424,100.0,0.0,21.6,7.8,338.0,1003.6,80.4,60.2,0.2,1.0,False,False,True,False,False,False,True,False,2023,7,2,19,Chernivtsi,Europe/Kiev,2023-07-26,05:43:19,21:01:36,19:00:00,Чернівецька,1,60.00,1.0,0.0,1.0,0.0,3.0,0,0,24.0,4.0,0,0.789355,-0.147469,-0.040814,-0.060577,-0.136550,0.122257,0.049391,-0.028274,-0.072607,0.114678,-0.075300,-0.188178,0.018128,0.043715,0.030283,-0.137499,0.016266,0.033889,0.090725,0.011275,0.074110,0.011227,-0.000483,-0.022039,-0.023353,-0.060664,0.009437,0.098875,-0.016041,0.000026,-0.017750,-0.000854,0.013135,0.010212,-0.032584,0.017607,-0.000715,-0.012152,0.016200,0.014523,-0.003170,-0.005309,0.002238,0.000646,-0.007727,0.035339,-0.027736,0.026938,0.005012,-0.061884,-0.084583,0.001840,-0.021368,0.019298,-0.034659,0.006760,0.012554,-0.056861,0.056622,0.013689,-0.007882,0.040534,0.008177,-0.009027,0.032590,-0.007494,-0.007170,-0.014069,0.008696,-0.010473,-0.000746,0.004834,0.005429,-0.019388,-0.003260,-0.053719,-0.031827,-0.002491,-0.051411,0.033383,-0.002065,0.009734,0.001256,0.002153,-0.001090,-0.015166,0.009047,0.009368,-0.017477,-0.016104,0.020513,0.013722,0.007793,0.000860,-0.020629,-0.022383,-0.021420,0.009774,-0.002901,0.021602,-0.005198,-0.008131,0.006540,0.012850,0.010119,-0.008055,0.035307,-0.020388,0.034953,0.014442,0.037331,0.026788,-0.007838,-0.022031,0.009422,0.001545,-0.035779,0.023244,0.054080,0.003175,-0.005649,0.021609,-0.007965,0.010471,-0.011647,-0.011763,0.019942,-0.026337,0.009130,0.008606,-0.007048,0.014640,-0.021723,-0.010484,0.005458,-0.002720,-0.019413,-0.020245,-0.047557,-0.033680,-0.003951,-0.032524,-0.038232,0.024062,-0.005205,-0.037805,0.022364,0.011552,-0.023808,-0.032711,4.646624,0.069539,0.789355,0.030977,-0.086209,4.665504,4.185140
69549,2024-01-16 05:00:00,4,48.4753,35.0160,0.7,-1.1,88.0,5.600,100.0,8.33,0.1,5.4,40.3,25.2,235.0,1002.0,70.4,29.1,2.4,2.0,0.17,2.4,-2.5,93.11,0.000,0.0,0.0,38.5,21.6,190.0,999.3,100.0,0.0,0.0,0.0,False,False,False,True,False,True,False,False,2024,1,1,5,Dnipro,Europe/Kiev,2024-01-16,07:26:31,16:12:56,05:00:00,Дніпропетровська,0,0.00,0.0,0.0,0.0,1.0,4.0,0,1,0.0,0.0,11,0.748870,-0.076549,-0.261006,0.115656,0.186186,0.139078,-0.065855,-0.105602,0.072809,-0.061649,-0.030500,0.007215,0.047141,-0.016776,-0.156951,0.029645,0.065743,0.007624,0.100708,-0.089491,0.025876,-0.057702,0.041974,-0.049735,-0.006087,0.009876,0.021926,0.005130,0.036308,0.034822,-0.007961,-0.054235,0.044553,-0.003321,-0.005684,0.022614,-0.032499,0.074281,-0.010410,-0.052657,-0.061340,-0.036652,-0.060480,0.017701,-0.003763,0.012284,-0.007747,-0.006958,-0.000485,0.019789,0.008599,0.005610,-0.013125,0.045521,0.016543,0.016515,-0.000193,-0.043345,-0.023866,-0.037680,0.000225,0.014592,-0.000357,-0.010027,-0.042235,-0.008369,0.001725,-0.011228,-0.017337,-0.025462,0.018094,0.018009,0.015756,-0.007305,0.031163,-0.059947,0.017329,0.009128,-0.014136,-0.035609,0.031029,-0.010789,0.003847,0.002750,-0.015847,0.014612,0.015917,-0.015130,-0.004879,-0.041584,-0.008070,-0.006079,-0.007500,-0.033246,-0.019906,0.008461,0.017023,0.020367,0.019901,-0.001082,-0.008188,0.010290,0.017308,-0.015976,0.015419,0.013237,-0.008075,-0.002289,-0.018977,0.002307,0.004418,-0.042488,-0.004952,0.004837,-0.002797,0.008916,0.007639,-0.021013,0.003434,-0.015890,0.000316,0.031129,-0.033910,0.005119,-0.020235,-0.035281,0.012056,-0.027032,0.028430,0.029994,-0.004781,0.006817,0.012239,0.016286,0.004163,0.039881,-0.016171,-0.013498,0.022933,-0.003311,-0.002694,0.014367,-0.007681,0.007945,-0.008038,-0.000596,0.013843,0.020955,0.015507,-0.014109,4.774715,0.068625,0.748870,0.031831,-0.236030,4.933557,4.191098
161571,2022-06-17 22:00:00,8,47.8289,35.1626,21.8,10.4,52.6,0.000,0.0,0.00,0.0,0.0,23.4,11.5,189.8,1016.5,40.8,318.6,27.1,9.0,0.59,21.9,21.9,53.37,0.000,0.0,0.0,6.5,2.9,177.9,1015.0,100.0,0.0,0.1,0.0,False,True,False,False,False,True,False,False,2022,6,4,22,Zaporozhye,Europe/Zaporozhye,2022-06-17,04:40:06,20:40:36,22:00:00,Запорізька,0,0.00,0.0,0.0,0.0,0.0,2.0,0,0,0.0,0.0,21,0.772837,-0.182582,0.318101,0.001946,-0.011932,0.046757,0.051233,-0.087034,-0.009162,-0.026359,-0.065060,0.145287,0.003665,-0.001864,-0.005350,-0.035117,-0.022651,0.022556,-0.058088,-0.048465,0.084358,-0.086480,-0.100064,0.006130,0.006049,0.052092,0.027516,-0.019124,-0.051647,0.028564,0.043454,-0.023179,-0.020311,-0.021258,0.005368,0.019757,0.038829,0.032150,-0.022324,-0.000247,-0.019799,-0.013703,0.034965,-0.047050,0.014630,0.002434,0.009304,-0.023431,0.006845,0.027456,0.036798,-0.006177,-0.006765,0.014355,0.003270,-0.015981,-0.012547,-0.038068,0.015643,-0.011630,-0.009426,0.029540,0.045469,0.002194,-0.022866,0.002199,-0.016278,-0.008870,-0.014632,-0.005833,0.020115,-0.017775,0.010502,-0.043690,0.010124,0.008115,0.048156,0.013455,-0.014017,-0.029971,0.015999,0.023210,0.017923,0.056050,0.035799,-0.015363,-0.014333,-0.022124,-0.016145,-0.010710,0.031028,0.006794,0.030383,0.010626,-0.003665,-0.003550,-0.017526,0.018708,-0.001827,-0.022056,0.026242,-0.021147,0.015350,0.014747,-0.016298,0.003298,0.016655,-0.021169,-0.029877,0.004982,0.004621,-0.010129,-0.001743,-0.000050,0.015878,0.013332,-0.006179,0.008787,-0.015017,0.001792,0.010566,0.027138,-0.016547,-0.006064,-0.006891,-0.025994,0.014028,0.023160,-0.000819,0.006297,-0.009588,0.020804,-0.005034,0.015761,0.004529,-0.017305,0.013445,-0.011232,0.009541,0.024744,0.004800,0.002352,0.059472,-0.033590,-0.020819,-0.029952,0.020576,0.000579,0.000898,0.000997,4.403659,0.070181,0.772837,0.029358,-0.349243,4.471470,4.145132
325133,2023-01-01 18:00:00,15,46.4725,30.7371,8.6,5.3,80.0,0.000,0.0,0.00,0.0,0.0,19.1,10.8,243.6,1027.3,21.9,58.5,5.2,3.0,0.29,9.7,9.2,81.01,0.000,0.0,0.0,10.4,5.4,242.5,1027.0,0.0,0.0,0.1,0.0,False,True,False,False,True,False,False,False,2023,1,6,18,Odesa,Europe/Kiev,2023-01-01,07:40:56,16:20:13,18:00:00,Одеська,0,0.00,0.0,0.0,0.0,0.0,4.0,1,0,1.0,0.0,16,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-4.934028,1.096401,-0.000000
299711,2023-02-14 09:00:00,14,46.9734,31.9852,3.3,0.3,81.1,0.600,100.0,8.33,0.0,0.0,47.9,28.8,311.1,1020.0,82.9,52.7,4.3,3.0,0.80,3.5,-1.0,83.69,0.000,0.0,0.0,37.4,21.2,291.3,1019.0,100.0,29.5,0.1,0.0,False,False,True,False,False,True,False,False,2023,2,1,9,Mykolaiv,Europe/Kiev,2023-02-14,06:58:55,17:14:19,09:00:00,Миколаївська,1,49.05,0.0,0.0,0.0,0.0,0.0,0,0,0.0,0.0,25,0.774265,-0.223627,-0.071615,-0.006433,0.073213,0.025692,-0.040837,0.087117,-0.076395,0.070597,0.011121,0.033493,0.121480,-0.151575,0.124589,0.073301,-0.051839,-0.045286,-0.033155,-0.002972,-0.064656,0.011545,0.019079,-0.009554,-0.095420,-0.021798,0.017507,0.012020,-0.010657,-0.030959,-0.048253,-0.011464,-0.004500,-0.002449,-0.008735,-0.008484,-0.056307,0.010869,-0.022218,0.010085,-0.012848,0.032851,0.038754,-0.001450,-0.000962,0.022680,-0.012581,-0.018219,0.049474,-0.019138,-0.021301,0.012242,0.009641,-0.007966,-0.013768,0.002578,0.013426,-0.020260,0.018114,-0.032752,0.012645,0.007333,0.027001,-0.020800,-0.025044,-0.045931,-0.047735,0.014305,0.006891,-0.016740,0.061722,-0.004493,0.021303,0.013964,0.011254,0.030378,0.019912,-0.023696,-0.036051,-0.034612,-0.006105,0.056036,0.012897,0.033168,0.029492,-0.020671,0.007641,-0.022821,-0.005630,0.048671,-0.002351,0.018643,-0.021439,0.031923,0.017735,0.017050,0.023043,-0.004404,0.025784,0.007251,-0.012391,0.017906,0.003038,0.027312,-0.011631,-0.014328,0.002365,-0.020750,0.011552,-0.006446,-0.010869,0.011591,-0.009686,0.027724,-0.033083,0.001603,-0.010240,0.005170,-0.009588,0.025334,-0.030350,-0.018679,0.026319,-0.039520,0.005518,0.032882,0.009998,0.021560,0.015017,0.069629,0.006456,0.015292,0.014544,-0.030301,-0.009537,-0.000681,-0.053746,-0.003133,0.001022,-0.017085,0.023998,-0.002510,0.014031,-0.022648,0.019677,-0.036993,0.036034,0.014006,0.005931,0.001164,4.701600,0.067762,0.774265,0.031344,0.032073,4.841756,4.268940
227716,2023-12-20 06:00:00,10,50.4506,30.5243,6.1,0.5,67.3,0.000,0.0,0.00,0.0,0.8,34.6,18.0,229.3,1007.8,68.9,35.0,3.0,2.0,0.26,4.8,1.2,69.54,0.000,0.0,0.0,32.0,16.9,240.6,1009.0,63.1,0.0,0.0,0.0,False,True,False,False,False,True,False,False,2023,12,2,6,Kyiv,Europe/Kiev,2023-12-20,07:55:18,15:55:24,06:00:00,Київська,0,0.00,0.0,0.0,1.0,0.0,5.0,0,1,0.0,0.0,3,0.782071,-0.091581,-0.203412,0.019480,0.089662,-0.056459,0.201185,0.053804,-0.033399,-0.119913,-0.047504,-0.028680,-0.019478,0.001129,-0.056378,-0.030675,0.051878,0.009500,-0.000296,-0.082391,-0.055297,0.020198,0.019325,0.011720,0.047237,0.012706,0.049123,-0.027211,0.053338,0.008414,0.029226,0.000646,0.031241,-0.006606,-0.028773,0.014966,-0.019291,-0.049545,-0.004315,0.016209,-0.017100,0.008041,-0.032222,-0.012258,0.027679,-0.049794,0.027352,0.018130,-0.007922,0.004167,0.013547,-0.019253,-0.022450,0.001742,-0.007801,-0.005379,0.017837,0.019102,-0.001598,-0.046889,-0.028857,0.015023,0.031770,0.027907,-0.004385,0.047113,0.013490,-0.007189,-0.071758,-0.005227,0.014839,-0.026412,0.004181,0.005320,0.034278,0.014177,0.019923,0.028576,-0.034643,0.039374,-0.005247,-0.001257,0.012860,0.000113,0.005765,-0.010240,0.006931,0.022914,-0.019555,0.011065,0.044294,0.024881,-0.009848,-0.013365,-0.008920,-0.007992,0.025492,0.022858,-0.044178,-0.015991,0.005023,-0.023830,-0.050839,-0.010300,-0.050101,0.012583,0.000465,-0.035810,0.000636,0.010378,-0.031468,0.006915,-0.010887,-0.015691,-0.002430,-0.046101,0.004637,0.039175,-0.010338,-0.023434,0.009821,-0.001328,-0.024749,0.010709,0.008241,0.015132,0.022893,0.030541,0.005394,-0.001944,-0.006838,-0.022447,-0.062846,-0.010787,-0.034806,0.007957,0.016702,0.003446,-0.026592,0.022577,-0.006900,-0.011001,0.010208,0.015931,0.002594,-0.014122,0.005511,0.018494,-0.017101,-0.023475,4.494863,0.068170,0.782071,0.029966,-0.286390,4.667833,4.225373

### TELEGRAM MERGE

In [23]:
df_tg_matrix = pd.read_csv("../data/telegram_processed_svd.csv")

In [24]:
df_tg_matrix.head()

,date,channel,tg_topic_0,tg_topic_1,tg_topic_2,tg_topic_3,tg_topic_4,tg_topic_5,tg_topic_6,tg_topic_7,tg_topic_8,tg_topic_9,tg_topic_10,tg_topic_11,tg_topic_12,tg_topic_13,tg_topic_14,tg_topic_15,tg_topic_16,tg_topic_17,tg_topic_18,tg_topic_19,tg_topic_20,tg_topic_21,tg_topic_22,tg_topic_23,tg_topic_24,tg_topic_25,tg_topic_26,tg_topic_27,tg_topic_28,tg_topic_29,tg_topic_30,tg_topic_31,tg_topic_32,tg_topic_33,tg_topic_34,tg_topic_35,tg_topic_36,tg_topic_37,tg_topic_38,tg_topic_39,tg_topic_40,tg_topic_41,tg_topic_42,tg_topic_43,tg_topic_44,tg_topic_45,tg_topic_46,tg_topic_47,tg_topic_48,tg_topic_49,tg_topic_50,tg_topic_51,tg_topic_52,tg_topic_53,tg_topic_54,tg_topic_55,tg_topic_56,tg_topic_57,tg_topic_58,tg_topic_59,tg_topic_60,tg_topic_61,tg_topic_62,tg_topic_63,tg_topic_64,tg_topic_65,tg_topic_66,tg_topic_67,tg_topic_68,tg_topic_69,tg_topic_70,tg_topic_71,tg_topic_72,tg_topic_73,tg_topic_74,tg_topic_75,tg_topic_76,tg_topic_77,tg_topic_78,tg_topic_79,tg_topic_80,tg_topic_81,tg_topic_82,tg_topic_83,tg_topic_84,tg_topic_85,tg_topic_86,tg_topic_87,tg_topic_88,tg_topic_89,tg_topic_90,tg_topic_91,tg_topic_92,tg_topic_93,tg_topic_94,tg_topic_95,tg_topic_96,tg_topic_97,tg_topic_98,tg_topic_99,tg_topic_100,tg_topic_101,tg_topic_102,tg_topic_103,tg_topic_104,tg_topic_105,tg_topic_106,tg_topic_107,tg_topic_108,tg_topic_109,tg_topic_110,tg_topic_111,tg_topic_112,tg_topic_113,tg_topic_114,tg_topic_115,tg_topic_116,tg_topic_117,tg_topic_118,tg_topic_119,tg_topic_120,tg_topic_121,tg_topic_122,tg_topic_123,tg_topic_124,tg_topic_125,tg_topic_126,tg_topic_127,tg_topic_128,tg_topic_129,tg_topic_130,tg_topic_131,tg_topic_132,tg_topic_133,tg_topic_134,tg_topic_135,tg_topic_136,tg_topic_137,tg_topic_138,tg_topic_139,tg_topic_140,tg_topic_141,tg_topic_142,tg_topic_143,tg_topic_144,tg_topic_145,tg_topic_146,tg_topic_147,tg_topic_148,tg_topic_149,tg_topic_150,tg_topic_151,tg_topic_152,tg_topic_153,tg_topic_154,tg_topic_155,tg_topic_156,tg_topic_157,tg_topic_158,tg_topic_159,tg_topic_160,tg_topic_161,tg_topic_162,tg_topic_163,tg_topic_164,tg_topic_165,tg_topic_166,tg_topic_167,tg_topic_168,tg_topic_169,tg_topic_170,tg_topic_171,tg_topic_172,tg_topic_173,tg_topic_174,tg_topic_175,tg_topic_176,tg_topic_177,tg_topic_178,tg_topic_179,tg_topic_180,tg_topic_181,tg_topic_182,tg_topic_183,tg_topic_184,tg_topic_185,tg_topic_186,tg_topic_187,tg_topic_188,tg_topic_189,tg_topic_190,tg_topic_191,tg_topic_192,tg_topic_193,tg_topic_194,tg_topic_195,tg_topic_196,tg_topic_197,tg_topic_198,tg_topic_199,tg_topic_200,tg_topic_201,tg_topic_202,tg_topic_203,tg_topic_204,tg_topic_205,tg_topic_206,tg_topic_207,tg_topic_208,tg_topic_209,tg_topic_210,tg_topic_211,tg_topic_212,tg_topic_213,tg_topic_214,tg_topic_215,tg_topic_216,tg_topic_217,tg_topic_218,tg_topic_219,tg_topic_220,tg_topic_221,tg_topic_222,tg_topic_223,tg_topic_224,tg_topic_225,tg_topic_226,tg_topic_227,tg_topic_228,tg_topic_229,tg_topic_230,tg_topic_231,tg_topic_232,tg_topic_233,tg_topic_234,tg_topic_235,tg_topic_236,tg_topic_237,tg_topic_238,tg_topic_239,tg_topic_240,tg_topic_241,tg_topic_242,tg_topic_243,tg_topic_244,tg_topic_245,tg_topic_246,tg_topic_247,tg_topic_248,tg_topic_249
0,2026-03-06 13:06:58,DeepStateUA,0.007121,0.000107,0.019843,0.000990,-0.011395,0.032670,-0.050983,0.061080,0.042624,-0.024341,-0.018764,0.023404,-0.017137,-0.358836,0.425288,0.017966,-0.107660,-0.032066,-0.045986,0.118212,0.091172,-0.248637,-0.001069,0.150763,0.030603,-0.074030,0.005803,0.005871,0.034871,0.017239,0.058098,0.029814,-0.010845,0.031486,-0.022705,0.005607,-0.006324,-0.010169,0.024500,-0.015581,-0.012708,0.005139,0.007857,0.016734,-0.040289,-0.019688,-0.026763,0.009381,-0.043500,-0.009525,-0.013075,-0.010473,-0.018150,0.005988,0.032611,0.000850,0.017872,0.020885,0.023899,-0.019290,-0.006676,-0.018478,-0.023263,-0.005497,-0.006460,0.026051,0.004991,0.019687,-0.022244,0.010929,0.007016,-0.067349,-0.035249,-0.005686,0.018747,0.039159,-0.053868,-0.078189,-0.074737,-0.082163,0.020498,0.084336,0.113470,-0.025871,-0.048314,0.096330,0.043779,0.029575,0.019820,0.002819,-0.007308,-0.005234,-0.053796,-0.005893,0.036483,-0.061232,-0.001463,0.048285,-0.017340,0.033961,0.039046,-0.045463,-0.035894,-0.033875,0.041559,-0.021964,-0.005454,-0.020615,0.006442,-0.016322,-0.010443,-0.015532,0.000981,0.002928,-0.010924,-0.004072,-0.007252,-0.020386,0.007354,0.022114,-0.000884,-0.019901,-0.009325,-0.043505,0.008556,-0.016976,0.004765,0.030853,0.012413,0.011307,0.017726,0.010620,-0.013777,-0.037939,-0.003764,0.015808,-0.027407,-0.033773,0.054684,-0.005455,0.077819,0.006894,-0.022642,-0.011036,0.007590,-0.011639,0.036640,-0.020276,0.016764,-0.000467,-0.007996,0.023813,-0.014151,-0.026548,-0.078007,0.014955,0.043507,-0.021709,0.013392,-0.008661,0.012712,0.037409,-0.032628,-0.021403,-0.030711,0.033490,-0.025720,0.008100,-0.011149,-0.002706,0.002765,0.017707,-0.010806,-0.012850,0.007063,0.021780,0.010662,-0.031776,0.011750,0.069730,0.029703,0.012839,-0.031854,0.001635,-0.002149,-0.045445,0.002481,0.021315,0.006077,-0.006012,0.006578,-0.036587,0.009373,-0.025445,-0.019477,-0.011097,0.014675,-0.016785,0.010995,0.002045,-0.004600,-0.008963,0.006641,-0.017489,0.003821,0.005926,0.000537,-0.002830,-0.035321,-0.004957,0.013548,0.015414,0.018981,0.017932,-0.002853,0.007882,0.026621,0.003335,-0.001598,0.011594,-0.016659,0.001508,-0.007204,0.002975,0.001589,0.012191,0.005661,0.006600,-0.027472,0.014275,-0.020139,-0.011419,0.015111,-0.008120,0.001883,-0.011402,0.006871,0.024781,0.019495,0.024153,0.017141,-0.013944,-0.027516,0.034612,-0.032061,-0.051141,-0.004707,-0.003985,-0.052194,-0.026334
1,2026-03-06 12:57:29,DeepStateUA,0.022770,-0.002163,0.041469,0.001527,-0.033584,0.077087,-0.078417,0.091534,0.014917,-0.016270,-0.019775,0.015028,-0.012900,-0.066689,0.049295,-0.031093,0.006109,-0.021357,-0.047947,0.025239,-0.010092,0.063969,0.026579,-0.002938,0.000962,-0.014692,-0.010761,0.001202,-0.015000,-0.005930,-0.010839,0.049023,-0.023754,0.030922,0.000492,-0.009320,-0.015764,0.024560,0.006807,-0.000411,-0.001480,-0.017302,-0.026282,0.007343,0.049168,-0.004316,0.029036,-0.034987,0.034368,-0.046229,-0.012751,0.048371,0.004354,-0.014649,0.034935,-0.016468,-0.013150,0.017354,-0.000886,0.004047,0.036549,-0.017461,0.009667,-0.007887,-0.027599,-0.016937,-0.037606,-0.009493,-0.002735,-0.006034,0.023060,0.028297,0.024781,0.010909,-0.000544,-0.016357,-0.003670,-0.016336,0.002609,0.013846,-0.005648,-0.012539,-0.007839,-0.041249,0.030814,-0.017629,-0.005069,-0.024100,-0.013485,0.010861,-0.015271,-0.006842,-0.013700,0.008861,-0.010810,0.022671,-0.034102,-0.016120,0.001828,0.003954,0.007680,-0.037762,-0.017967,0.016946,0.016302,-0.011406,0.021384,-0.001978,-0.005628,-0.080374,0.039484,0.015890,0.034496,-0.016936,0.004379,-0.005021,0.014321,-0.003484,-0.002882,-0.002483,-0.005047,0.017296,-0.003401,0.009433,-0.001665,0.018296,0.003151,-0.031688,0.003527,0.010405,-0.006932,-0.019232,-0.004084,-0.023476,-0.008857,-0.015648,0.053937,0.034130,-0.026430,0.018625,-0.050338,0.022854,-0.000992,0.001886,-0.013131,0.037482,0.025278,-0.008833,-0.009892,0.015771,-0.019763,-0.015569,-0.015169,0.040201,0.018226,0.018286,-0.011713,-0.000436,0.000451,0.012252,0.007596,-0.000338,0.004704,0.023604,-0.020461,0.016871,0.003246,-0.045373,0.004746,-0.036469,-0.025234,0.030737,-0.000797,0.015820,0.042129,0.010345,0.022695,0.005339,-0.001636,-0.018894,0.026074,-0.054026,-0.057851,0.004372,-0.020828,-0.034435,0.055865,0.016301,0.063019,0.010370,-0.004495,-0.030530,0.018833,-0.013644,0.002207,0.037501,-0.045908,-0.059514,-0.035367,-0.024918,-0.039085,0.035208,0.085963,0.009390,0.079267,0.013885,0.006535,-0.052116,-0.033637,0.008546,-0.019285,0.006149,0.002710,-0.056530,-0.022435,0.020384,-0.013988,-0.005111,-0.015295,-0.097911,-0.042214,0.020642,-0.042973,0.045024,0.005130,-0.022150,0.006530,0.054045,-0.042555,0.006345,-0.035607,-0.006021,0.000036,-0.033672,0.020923,-0.000556,-0.034840,0.034524,0.004798,0.001867,-0.019097,0.025730,0.000530,0.020332,-0.028041,0.001581,0.006948,-0.064965,0.022597,-0.017810
2,2026-03-06 08:32:47,DeepStateUA,0.009647,-0.001083,0.029820,0.004092,-0.021362,0.053647,-0.076998,0.085930,0.011210,-0.020903,-0.051377,0.013232,-0.021159,0.001682,0.049129,-0.010018,-0.014271,-0.012423,-0.010588,0.046603,0.026875,0.002452,0.003347,-0.018525,0.005328,-0.003516,0.003550,0.018054,0.002157,0.012886,0.034851,0.000381,-0.009230,-0.002467,0.002381,0.000435,0.000842,-0.004257,-0.003348,0.009321,-0.005701,-0.004301,-0.016552,-0.001785,0.016005,0.008306,0.000706,-0.004439,-0.004069,-0.017177,-0.017974,-0.000361,-0.033317,-0.032714,0.027864,-0.006006,0.000665,-0.001117,-0.020576,0.002026,0.001386,0.000074,0.000035,0.007953,0.005774,0.005407,-0.005473,0.009134,-0.010858,-0.014439,0.028165,-0.023096,0.014483,0.021402,-0.017701,0.035852,-0.021296,-0.016145,-0.007317,-0.016939,0.014848,-0.006705,-0.047833,-0.002701,0.006144,-0.016566,0.016766,0.017487,0.002922,-0.004175,0.003020,-0.032485,0.001179,0.015611,0.015266,0.023711,0.005134,-0.030744,-0.014357,0.024034,0.016933,-0.044400,0.005215,0.011766,-0.026130,-0.005996,0.011388,-0.012677,-0.016358,-0.020579,-0.003119,-0.003134,0.019595,-0.011791,0.015521,0.022933,0.013426,0.013833,-0.006377,0.006772,-0.023631,0.008806,0.003886,0.014650,-0.029616,0.047030,0.005467,-0.020456,0.018529,-0.009387,0.010160,0.010283,-0.016104,0.038236,-0.028747,0.030649,0.028343,0.020708,0.001123,-0.009186,-0.064016,0.007831,0.005442,0.008333,-0.002820,0.007245,0.037716,-0.034047,0.009513,0.002276,-0.009623,-0.009046,0.023603,-0.009777,-0.047725,0.011991,-0.016423,0.004245,0.039250,0.030454,-0.007661,-0.043307,-0.005340,-0.003352,0.004921,0.010619,0.011745,-0.029661,-0.016769,-0.004054,-0.019134,-0.010521,-0.016018,0.013938,0.061204,0.000223,-0.016080,-0.013129,0.011080,0.025287,0.030597,-0.001902,-0.032930,0.022210,0.024393,-0.023036,0.001308,-0.010151,0.002527,0.003083,0.002821,0.012997,0.008941,-0.011744,0.019257,-0.000326,0.025398,-0.044011,-0.021810,-0.040764,-0.011043,0.008865,-0.020367,-0.005459,0.002685,0.019290,0.025485,-0.019258,-0.011527,-0.015354,-0.003904,0.007485,0.039596,0.030817,-0.034836,0.029725,0.018850,0.009886,0.006251,-0.006886,-0.028339,-0.017251,-0.019577,-0.004734,-0.014053,-0.014076,-0.018760,-0.006640,0.002467,-0.014727,0.015968,-0.020566,-0.000171,-0.020244,0.003823,-0.020505,-0.006361,-0.011117,-0.002427,0.036069,0.025378,-0.003550,-0.043415,-0.007200,-0.009172,0.006124,-0.004550,0.020576,0.010544,0.012825
3,2026-03-05 16:46:58,DeepStateUA,0.006857,0.000279,0.019019,0.000875,-0.011544,0.032104,-0.049929,0.059696,0.042415,-0.023916,-0.020173,0.022363,-0.016425,-0.354007,0.422410,0.017232,-0.106286,-0.032499,-0.045502,0.118053,0.090722,-0.246774,-0.000077,0.150527,0.029981,-0.074173,0.006982,0.007685,0.035762,0.018338,0.059439,0.029451,-0.012747,0.032325,-0.024156,0.006144,-0.004921,-0.007047,0.024916,-0.013464,-0.012810,0.004618,0.006305,0.017777,-0.037226,-0.018749,-0.026076,0.008026,-0.040668,-0.008455,-0.012120,-0.009955,-0.018018,0.006661,0.032070,0.001406,0.015931,0.020066,0.022360,-0.017343,-0.007000,-0.017683,-0.021564,-0.005667,-0.004897,0.022713,0.002352,0.021026,-0.020492,0.010265,0.006341,-0.062306,-0.031869,-0.004833,0.019042,0.034739,-0.048355,-0.072654,-0.066847,-0.074661,0.019525,0.081765,0.106477,-0.025839,-0.046011,0.091824,0.043276,0.026990,0.018548,0.002251,-0.006682,-0.005199,-0.051075,-0.003017,0.029777,-0.054537,-0.002321,0.044861,-0.018019,0.033038,0.036190,-0.042962,-0.033109,-0.031216,0.040022,-0.016626,-0.004321,-0.022597,0.001446,-0.018905,-0.015046,-0.006992,0.004125,0.000550,-0.011207,-0.006348,-0.005325,-0.023457,0.009404,0.021777,-0.001560,-0.021654,-0.010065,-0.041095,0.009058,-0.016847,0.014130,0.030820,0.014433,0.011400,0.017331,0.012039,-0.011976,-0.037318,-0.000059,0.013755,-0.023928,-0.033049,0.051293,-0.004679,0.075124,0.004404,-0.023162,-0.009870,0.008475,-0.011321,0.038668,-0.021760,0.017180,-0.003656,-0.004497,0.024860,-0.010259,-0.023728,-0.073984,0.014863,0.037362,-0.023343,0.010636,-0.008617,0.012118,0.033946,-0.033242,-0.018743,-0.029519,0.034794,-0.025605,0.008930,-0.006082,-0.003809,-0.002692,0.017623,-0.010778,-0.010494,0.004241,0.018071,0.015268,-0.027505,0.007476,0.058355,0.024457,0.010803,-0.030662,-0.001728,-0.001191,-0.040228,0.003914,0.019603,0.006112,-0.006858,0.006677,-0.036682,0.007404,-0.025808,-0.014273,-0.007471,0.014518,-0.012831,0.005292,-0.002303,-0.003711,-0.008705,0.000811,-0.012632,0.003962,0.004388,0.000392,0.002013,-0.028686,-0.003865,0.011868,0.012458,0.016571,0.009521,-0.001085,0.007509,0.021553,0.002596,0.005686,0.003029,-0.016085,0.005070,-0.006296,0.000888,0.002830,0.014467,0.006547,0.000059,-0.020972,0.009385,-0.014722,-0.008414,0.016377,-0.008301,-0.000710,-0.008819,0.006663,0.012456,0.012080,0.020719,0.008728,-0.007502,-0.021433,0.028223,-0.025323,-0.045761,-0.001697,0.002329,-0.042282,-0.017344
4,2026-03-05 15:46:39,DeepStateUA,0.048850,-0.006687,0.076040,-0.003924,-0.027197,0.089562,-0.088811,0.109836,0.052317,-0.025058,0.032393,-0.004227,-0.005032,-0.173462,0.094957,0.012582,-0.022470,-0.000701,-0.014110,-0.004739,-0.012713,0.127035,0.018404,-0.023593,0.003993,0.039285,-0.018524,0.000346,-0.081926,-0.045456,-0.116434,-0.028074,-0.013547,0.024679,0.046939,-0.021634,0.023138,0.009856,-0.025864,-0.041176,-0.000832,-0.024707,0.013634,-0.022765,0.057346,0.020489,0.010217,-0.026627,0.022514,0.022439,0.035388,-0.021224,0.008281,-0.000369,-0.015992,0.012876,-0.018086,-0.005188,-0.021093,0.012907,-0.008576,-0.008820,0.030578,0.014680,0.017475,0.007797,0.004474,-0.006686,0.023422,0.017913,0.009466,-0.011255,-0.006200,0.008317,-0.038521,0.017131,0.046956,0.005528,0.071628,0.044144,-0.006390,0.009272,-0.010302,-0.023798,0.013099,0.004949,0.000502,-0.025377,0.000576,0.005652,0.013762,-0.033165,0.011959,0.032019,-0.010729,0.074746,-0.045156,-0.069856,0.017151,-0.028899,-0.001317,-0.020143,-0.001444,0.077727,0.008474,0.017218,0.063803,0.022661,-0.019578,-0.089309,0.043190,0.054776,0.003839,0.005619,0.042291,-0.040703,0.034216,-0.018434,0.026249,-0.012015,0.004663,0.009540,0.028979,0.022277,0.015843,0.026390,-0.030022,-0.019719,0.008557,-0.006588,-0.012466,-0.013107,0.000680,-0.040800,0.018810,-0.018852,0.015615,-0.026299,-0.013060,-0.022985,-0.019649,0.003882,0.019573,0.020302,-0.053045,-0.013295,-0.013323,0.043432,-0.020309,-0.004050,-0.017728,-0.008395,-0.063169,-0.008017,0.060143,-0.036649,-0.009351,-0.031419,-0.019356,0.002941,0.015680,0.058794,0.034299,0.025507,0.026522,-0.024327,0.001476,-0.008036,-0.008201,0.018152,0.016011,-0.009222,0.020974,0.008694,-0.047264,0.028262,-0.002851,0.009422,-0.012002,0.004519,-0.010160,-0.031831,-0.005528,0.038708,-0.014277,0.009808,0.004059,-0.009500,0.033000,-0.038357,-0.005480,0.016188,-0.012154,-0.003113,0.007213,-0.049557,0.001337,0.025862,0.002217,0.009792,-0.002905,0.012793,-0.039633,-0.014680,0.012541,-0.026685,-0.057037,-0.038288,-0.031196,-0.025930,0.009651,0.004537,0.035687,-0.013257,0.015052,-0.006502,0.018667,-0.013956,0.023991,0.033361,-0.000124,-0.000186,0.012095,0.023317,0.014021,-0.007477,-0.006606,-0.045891,0.004310,-0.008439,0.004574,-0.039585,0.004941,0.010379,-0.002950,-0.053005,0.008541,-0.002762,0.010718,0.035433,0.017978,0.027453,-0.019744,0.008659,0.023139,-0.009485,-0.030263,0.013689,-0.022727,0.006843

In [25]:
df_tg_matrix["datetime_hour"] = pd.to_datetime(df_tg_matrix["date"]).dt.floor("h")

C:\Users\Uw11\AppData\Local\Temp\ipykernel_22436\2851151304.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_tg_matrix["datetime_hour"] = pd.to_datetime(df_tg_matrix["date"]).dt.floor("h")

In [26]:
topic_cols = [c for c in df_tg_matrix.columns if "tg_topic_" in c]

tg_hourly = (
    df_tg_matrix.groupby("datetime_hour")[topic_cols]
    .mean()
    .sort_index()
    .reset_index()
)

C:\Users\Uw11\AppData\Local\Temp\ipykernel_22436\2188712141.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  .reset_index()

In [27]:
df_tg_matrix.head()

,date,channel,tg_topic_0,tg_topic_1,tg_topic_2,tg_topic_3,tg_topic_4,tg_topic_5,tg_topic_6,tg_topic_7,tg_topic_8,tg_topic_9,tg_topic_10,tg_topic_11,tg_topic_12,tg_topic_13,tg_topic_14,tg_topic_15,tg_topic_16,tg_topic_17,tg_topic_18,tg_topic_19,tg_topic_20,tg_topic_21,tg_topic_22,tg_topic_23,tg_topic_24,tg_topic_25,tg_topic_26,tg_topic_27,tg_topic_28,tg_topic_29,tg_topic_30,tg_topic_31,tg_topic_32,tg_topic_33,tg_topic_34,tg_topic_35,tg_topic_36,tg_topic_37,tg_topic_38,tg_topic_39,tg_topic_40,tg_topic_41,tg_topic_42,tg_topic_43,tg_topic_44,tg_topic_45,tg_topic_46,tg_topic_47,tg_topic_48,tg_topic_49,tg_topic_50,tg_topic_51,tg_topic_52,tg_topic_53,tg_topic_54,tg_topic_55,tg_topic_56,tg_topic_57,tg_topic_58,tg_topic_59,tg_topic_60,tg_topic_61,tg_topic_62,tg_topic_63,tg_topic_64,tg_topic_65,tg_topic_66,tg_topic_67,tg_topic_68,tg_topic_69,tg_topic_70,tg_topic_71,tg_topic_72,tg_topic_73,tg_topic_74,tg_topic_75,tg_topic_76,tg_topic_77,tg_topic_78,tg_topic_79,tg_topic_80,tg_topic_81,tg_topic_82,tg_topic_83,tg_topic_84,tg_topic_85,tg_topic_86,tg_topic_87,tg_topic_88,tg_topic_89,tg_topic_90,tg_topic_91,tg_topic_92,tg_topic_93,tg_topic_94,tg_topic_95,tg_topic_96,tg_topic_97,tg_topic_98,tg_topic_99,tg_topic_100,tg_topic_101,tg_topic_102,tg_topic_103,tg_topic_104,tg_topic_105,tg_topic_106,tg_topic_107,tg_topic_108,tg_topic_109,tg_topic_110,tg_topic_111,tg_topic_112,tg_topic_113,tg_topic_114,tg_topic_115,tg_topic_116,tg_topic_117,tg_topic_118,tg_topic_119,tg_topic_120,tg_topic_121,tg_topic_122,tg_topic_123,tg_topic_124,tg_topic_125,tg_topic_126,tg_topic_127,tg_topic_128,tg_topic_129,tg_topic_130,tg_topic_131,tg_topic_132,tg_topic_133,tg_topic_134,tg_topic_135,tg_topic_136,tg_topic_137,tg_topic_138,tg_topic_139,tg_topic_140,tg_topic_141,tg_topic_142,tg_topic_143,tg_topic_144,tg_topic_145,tg_topic_146,tg_topic_147,tg_topic_148,tg_topic_149,tg_topic_150,tg_topic_151,tg_topic_152,tg_topic_153,tg_topic_154,tg_topic_155,tg_topic_156,tg_topic_157,tg_topic_158,tg_topic_159,tg_topic_160,tg_topic_161,tg_topic_162,tg_topic_163,tg_topic_164,tg_topic_165,tg_topic_166,tg_topic_167,tg_topic_168,tg_topic_169,tg_topic_170,tg_topic_171,tg_topic_172,tg_topic_173,tg_topic_174,tg_topic_175,tg_topic_176,tg_topic_177,tg_topic_178,tg_topic_179,tg_topic_180,tg_topic_181,tg_topic_182,tg_topic_183,tg_topic_184,tg_topic_185,tg_topic_186,tg_topic_187,tg_topic_188,tg_topic_189,tg_topic_190,tg_topic_191,tg_topic_192,tg_topic_193,tg_topic_194,tg_topic_195,tg_topic_196,tg_topic_197,tg_topic_198,tg_topic_199,tg_topic_200,tg_topic_201,tg_topic_202,tg_topic_203,tg_topic_204,tg_topic_205,tg_topic_206,tg_topic_207,tg_topic_208,tg_topic_209,tg_topic_210,tg_topic_211,tg_topic_212,tg_topic_213,tg_topic_214,tg_topic_215,tg_topic_216,tg_topic_217,tg_topic_218,tg_topic_219,tg_topic_220,tg_topic_221,tg_topic_222,tg_topic_223,tg_topic_224,tg_topic_225,tg_topic_226,tg_topic_227,tg_topic_228,tg_topic_229,tg_topic_230,tg_topic_231,tg_topic_232,tg_topic_233,tg_topic_234,tg_topic_235,tg_topic_236,tg_topic_237,tg_topic_238,tg_topic_239,tg_topic_240,tg_topic_241,tg_topic_242,tg_topic_243,tg_topic_244,tg_topic_245,tg_topic_246,tg_topic_247,tg_topic_248,tg_topic_249,datetime_hour
0,2026-03-06 13:06:58,DeepStateUA,0.007121,0.000107,0.019843,0.000990,-0.011395,0.032670,-0.050983,0.061080,0.042624,-0.024341,-0.018764,0.023404,-0.017137,-0.358836,0.425288,0.017966,-0.107660,-0.032066,-0.045986,0.118212,0.091172,-0.248637,-0.001069,0.150763,0.030603,-0.074030,0.005803,0.005871,0.034871,0.017239,0.058098,0.029814,-0.010845,0.031486,-0.022705,0.005607,-0.006324,-0.010169,0.024500,-0.015581,-0.012708,0.005139,0.007857,0.016734,-0.040289,-0.019688,-0.026763,0.009381,-0.043500,-0.009525,-0.013075,-0.010473,-0.018150,0.005988,0.032611,0.000850,0.017872,0.020885,0.023899,-0.019290,-0.006676,-0.018478,-0.023263,-0.005497,-0.006460,0.026051,0.004991,0.019687,-0.022244,0.010929,0.007016,-0.067349,-0.035249,-0.005686,0.018747,0.039159,-0.053868,-0.078189,-0.074737,-0.082163,0.020498,0.084336,0.113470,-0.025871,-0.048314,0.096330,0.043779,0.029575,0.019820,0.002819,-0.007308,-0.005234,-0.053796,-0.005893,0.036483,-0.061232,-0.001463,0.048285,-0.017340,0.033961,0.039046,-0.045463,-0.035894,-0.033875,0.041559,-0.021964,-0.005454,-0.020615,0.006442,-0.016322,-0.010443,-0.015532,0.000981,0.002928,-0.010924,-0.004072,-0.007252,-0.020386,0.007354,0.022114,-0.000884,-0.019901,-0.009325,-0.043505,0.008556,-0.016976,0.004765,0.030853,0.012413,0.011307,0.017726,0.010620,-0.013777,-0.037939,-0.003764,0.015808,-0.027407,-0.033773,0.054684,-0.005455,0.077819,0.006894,-0.022642,-0.011036,0.007590,-0.011639,0.036640,-0.020276,0.016764,-0.000467,-0.007996,0.023813,-0.014151,-0.026548,-0.078007,0.014955,0.043507,-0.021709,0.013392,-0.008661,0.012712,0.037409,-0.032628,-0.021403,-0.030711,0.033490,-0.025720,0.008100,-0.011149,-0.002706,0.002765,0.017707,-0.010806,-0.012850,0.007063,0.021780,0.010662,-0.031776,0.011750,0.069730,0.029703,0.012839,-0.031854,0.001635,-0.002149,-0.045445,0.002481,0.021315,0.006077,-0.006012,0.006578,-0.036587,0.009373,-0.025445,-0.019477,-0.011097,0.014675,-0.016785,0.010995,0.002045,-0.004600,-0.008963,0.006641,-0.017489,0.003821,0.005926,0.000537,-0.002830,-0.035321,-0.004957,0.013548,0.015414,0.018981,0.017932,-0.002853,0.007882,0.026621,0.003335,-0.001598,0.011594,-0.016659,0.001508,-0.007204,0.002975,0.001589,0.012191,0.005661,0.006600,-0.027472,0.014275,-0.020139,-0.011419,0.015111,-0.008120,0.001883,-0.011402,0.006871,0.024781,0.019495,0.024153,0.017141,-0.013944,-0.027516,0.034612,-0.032061,-0.051141,-0.004707,-0.003985,-0.052194,-0.026334,2026-03-06 13:00:00
1,2026-03-06 12:57:29,DeepStateUA,0.022770,-0.002163,0.041469,0.001527,-0.033584,0.077087,-0.078417,0.091534,0.014917,-0.016270,-0.019775,0.015028,-0.012900,-0.066689,0.049295,-0.031093,0.006109,-0.021357,-0.047947,0.025239,-0.010092,0.063969,0.026579,-0.002938,0.000962,-0.014692,-0.010761,0.001202,-0.015000,-0.005930,-0.010839,0.049023,-0.023754,0.030922,0.000492,-0.009320,-0.015764,0.024560,0.006807,-0.000411,-0.001480,-0.017302,-0.026282,0.007343,0.049168,-0.004316,0.029036,-0.034987,0.034368,-0.046229,-0.012751,0.048371,0.004354,-0.014649,0.034935,-0.016468,-0.013150,0.017354,-0.000886,0.004047,0.036549,-0.017461,0.009667,-0.007887,-0.027599,-0.016937,-0.037606,-0.009493,-0.002735,-0.006034,0.023060,0.028297,0.024781,0.010909,-0.000544,-0.016357,-0.003670,-0.016336,0.002609,0.013846,-0.005648,-0.012539,-0.007839,-0.041249,0.030814,-0.017629,-0.005069,-0.024100,-0.013485,0.010861,-0.015271,-0.006842,-0.013700,0.008861,-0.010810,0.022671,-0.034102,-0.016120,0.001828,0.003954,0.007680,-0.037762,-0.017967,0.016946,0.016302,-0.011406,0.021384,-0.001978,-0.005628,-0.080374,0.039484,0.015890,0.034496,-0.016936,0.004379,-0.005021,0.014321,-0.003484,-0.002882,-0.002483,-0.005047,0.017296,-0.003401,0.009433,-0.001665,0.018296,0.003151,-0.031688,0.003527,0.010405,-0.006932,-0.019232,-0.004084,-0.023476,-0.008857,-0.015648,0.053937,0.034130,-0.026430,0.018625,-0.050338,0.022854,-0.000992,0.001886,-0.013131,0.037482,0.025278,-0.008833,-0.009892,0.015771,-0.019763,-0.015569,-0.015169,0.040201,0.018226,0.018286,-0.011713,-0.000436,0.000451,0.012252,0.007596,-0.000338,0.004704,0.023604,-0.020461,0.016871,0.003246,-0.045373,0.004746,-0.036469,-0.025234,0.030737,-0.000797,0.015820,0.042129,0.010345,0.022695,0.005339,-0.001636,-0.018894,0.026074,-0.054026,-0.057851,0.004372,-0.020828,-0.034435,0.055865,0.016301,0.063019,0.010370,-0.004495,-0.030530,0.018833,-0.013644,0.002207,0.037501,-0.045908,-0.059514,-0.035367,-0.024918,-0.039085,0.035208,0.085963,0.009390,0.079267,0.013885,0.006535,-0.052116,-0.033637,0.008546,-0.019285,0.006149,0.002710,-0.056530,-0.022435,0.020384,-0.013988,-0.005111,-0.015295,-0.097911,-0.042214,0.020642,-0.042973,0.045024,0.005130,-0.022150,0.006530,0.054045,-0.042555,0.006345,-0.035607,-0.006021,0.000036,-0.033672,0.020923,-0.000556,-0.034840,0.034524,0.004798,0.001867,-0.019097,0.025730,0.000530,0.020332,-0.028041,0.001581,0.006948,-0.064965,0.022597,-0.017810,2026-03-06 12:00:00
2,2026-03-06 08:32:47,DeepStateUA,0.009647,-0.001083,0.029820,0.004092,-0.021362,0.053647,-0.076998,0.085930,0.011210,-0.020903,-0.051377,0.013232,-0.021159,0.001682,0.049129,-0.010018,-0.014271,-0.012423,-0.010588,0.046603,0.026875,0.002452,0.003347,-0.018525,0.005328,-0.003516,0.003550,0.018054,0.002157,0.012886,0.034851,0.000381,-0.009230,-0.002467,0.002381,0.000435,0.000842,-0.004257,-0.003348,0.009321,-0.005701,-0.004301,-0.016552,-0.001785,0.016005,0.008306,0.000706,-0.004439,-0.004069,-0.017177,-0.017974,-0.000361,-0.033317,-0.032714,0.027864,-0.006006,0.000665,-0.001117,-0.020576,0.002026,0.001386,0.000074,0.000035,0.007953,0.005774,0.005407,-0.005473,0.009134,-0.010858,-0.014439,0.028165,-0.023096,0.014483,0.021402,-0.017701,0.035852,-0.021296,-0.016145,-0.007317,-0.016939,0.014848,-0.006705,-0.047833,-0.002701,0.006144,-0.016566,0.016766,0.017487,0.002922,-0.004175,0.003020,-0.032485,0.001179,0.015611,0.015266,0.023711,0.005134,-0.030744,-0.014357,0.024034,0.016933,-0.044400,0.005215,0.011766,-0.026130,-0.005996,0.011388,-0.012677,-0.016358,-0.020579,-0.003119,-0.003134,0.019595,-0.011791,0.015521,0.022933,0.013426,0.013833,-0.006377,0.006772,-0.023631,0.008806,0.003886,0.014650,-0.029616,0.047030,0.005467,-0.020456,0.018529,-0.009387,0.010160,0.010283,-0.016104,0.038236,-0.028747,0.030649,0.028343,0.020708,0.001123,-0.009186,-0.064016,0.007831,0.005442,0.008333,-0.002820,0.007245,0.037716,-0.034047,0.009513,0.002276,-0.009623,-0.009046,0.023603,-0.009777,-0.047725,0.011991,-0.016423,0.004245,0.039250,0.030454,-0.007661,-0.043307,-0.005340,-0.003352,0.004921,0.010619,0.011745,-0.029661,-0.016769,-0.004054,-0.019134,-0.010521,-0.016018,0.013938,0.061204,0.000223,-0.016080,-0.013129,0.011080,0.025287,0.030597,-0.001902,-0.032930,0.022210,0.024393,-0.023036,0.001308,-0.010151,0.002527,0.003083,0.002821,0.012997,0.008941,-0.011744,0.019257,-0.000326,0.025398,-0.044011,-0.021810,-0.040764,-0.011043,0.008865,-0.020367,-0.005459,0.002685,0.019290,0.025485,-0.019258,-0.011527,-0.015354,-0.003904,0.007485,0.039596,0.030817,-0.034836,0.029725,0.018850,0.009886,0.006251,-0.006886,-0.028339,-0.017251,-0.019577,-0.004734,-0.014053,-0.014076,-0.018760,-0.006640,0.002467,-0.014727,0.015968,-0.020566,-0.000171,-0.020244,0.003823,-0.020505,-0.006361,-0.011117,-0.002427,0.036069,0.025378,-0.003550,-0.043415,-0.007200,-0.009172,0.006124,-0.004550,0.020576,0.010544,0.012825,2026-03-06 08:00:00
3,2026-03-05 16:46:58,DeepStateUA,0.006857,0.000279,0.019019,0.000875,-0.011544,0.032104,-0.049929,0.059696,0.042415,-0.023916,-0.020173,0.022363,-0.016425,-0.354007,0.422410,0.017232,-0.106286,-0.032499,-0.045502,0.118053,0.090722,-0.246774,-0.000077,0.150527,0.029981,-0.074173,0.006982,0.007685,0.035762,0.018338,0.059439,0.029451,-0.012747,0.032325,-0.024156,0.006144,-0.004921,-0.007047,0.024916,-0.013464,-0.012810,0.004618,0.006305,0.017777,-0.037226,-0.018749,-0.026076,0.008026,-0.040668,-0.008455,-0.012120,-0.009955,-0.018018,0.006661,0.032070,0.001406,0.015931,0.020066,0.022360,-0.017343,-0.007000,-0.017683,-0.021564,-0.005667,-0.004897,0.022713,0.002352,0.021026,-0.020492,0.010265,0.006341,-0.062306,-0.031869,-0.004833,0.019042,0.034739,-0.048355,-0.072654,-0.066847,-0.074661,0.019525,0.081765,0.106477,-0.025839,-0.046011,0.091824,0.043276,0.026990,0.018548,0.002251,-0.006682,-0.005199,-0.051075,-0.003017,0.029777,-0.054537,-0.002321,0.044861,-0.018019,0.033038,0.036190,-0.042962,-0.033109,-0.031216,0.040022,-0.016626,-0.004321,-0.022597,0.001446,-0.018905,-0.015046,-0.006992,0.004125,0.000550,-0.011207,-0.006348,-0.005325,-0.023457,0.009404,0.021777,-0.001560,-0.021654,-0.010065,-0.041095,0.009058,-0.016847,0.014130,0.030820,0.014433,0.011400,0.017331,0.012039,-0.011976,-0.037318,-0.000059,0.013755,-0.023928,-0.033049,0.051293,-0.004679,0.075124,0.004404,-0.023162,-0.009870,0.008475,-0.011321,0.038668,-0.021760,0.017180,-0.003656,-0.004497,0.024860,-0.010259,-0.023728,-0.073984,0.014863,0.037362,-0.023343,0.010636,-0.008617,0.012118,0.033946,-0.033242,-0.018743,-0.029519,0.034794,-0.025605,0.008930,-0.006082,-0.003809,-0.002692,0.017623,-0.010778,-0.010494,0.004241,0.018071,0.015268,-0.027505,0.007476,0.058355,0.024457,0.010803,-0.030662,-0.001728,-0.001191,-0.040228,0.003914,0.019603,0.006112,-0.006858,0.006677,-0.036682,0.007404,-0.025808,-0.014273,-0.007471,0.014518,-0.012831,0.005292,-0.002303,-0.003711,-0.008705,0.000811,-0.012632,0.003962,0.004388,0.000392,0.002013,-0.028686,-0.003865,0.011868,0.012458,0.016571,0.009521,-0.001085,0.007509,0.021553,0.002596,0.005686,0.003029,-0.016085,0.005070,-0.006296,0.000888,0.002830,0.014467,0.006547,0.000059,-0.020972,0.009385,-0.014722,-0.008414,0.016377,-0.008301,-0.000710,-0.008819,0.006663,0.012456,0.012080,0.020719,0.008728,-0.007502,-0.021433,0.028223,-0.025323,-0.045761,-0.001697,0.002329,-0.042282,-0.017344,2026-03-05 16:00:00
4,2026-03-05 15:46:39,DeepStateUA,0.048850,-0.006687,0.076040,-0.003924,-0.027197,0.089562,-0.088811,0.109836,0.052317,-0.025058,0.032393,-0.004227,-0.005032,-0.173462,0.094957,0.012582,-0.022470,-0.000701,-0.014110,-0.004739,-0.012713,0.127035,0.018404,-0.023593,0.003993,0.039285,-0.018524,0.000346,-0.081926,-0.045456,-0.116434,-0.028074,-0.013547,0.024679,0.046939,-0.021634,0.023138,0.009856,-0.025864,-0.041176,-0.000832,-0.024707,0.013634,-0.022765,0.057346,0.020489,0.010217,-0.026627,0.022514,0.022439,0.035388,-0.021224,0.008281,-0.000369,-0.015992,0.012876,-0.018086,-0.005188,-0.021093,0.012907,-0.008576,-0.008820,0.030578,0.014680,0.017475,0.007797,0.004474,-0.006686,0.023422,0.017913,0.009466,-0.011255,-0.006200,0.008317,-0.038521,0.017131,0.046956,0.005528,0.071628,0.044144,-0.006390,0.009272,-0.010302,-0.023798,0.013099,0.004949,0.000502,-0.025377,0.000576,0.005652,0.013762,-0.033165,0.011959,0.032019,-0.010729,0.074746,-0.045156,-0.069856,0.017151,-0.028899,-0.001317,-0.020143,-0.001444,0.077727,0.008474,0.017218,0.063803,0.022661,-0.019578,-0.089309,0.043190,0.054776,0.003839,0.005619,0.042291,-0.040703,0.034216,-0.018434,0.026249,-0.012015,0.004663,0.009540,0.028979,0.022277,0.015843,0.026390,-0.030022,-0.019719,0.008557,-0.006588,-0.012466,-0.013107,0.000680,-0.040800,0.018810,-0.018852,0.015615,-0.026299,-0.013060,-0.022985,-0.019649,0.003882,0.019573,0.020302,-0.053045,-0.013295,-0.013323,0.043432,-0.020309,-0.004050,-0.017728,-0.008395,-0.063169,-0.008017,0.060143,-0.036649,-0.009351,-0.031419,-0.019356,0.002941,0.015680,0.058794,0.034299,0.025507,0.026522,-0.024327,0.001476,-0.008036,-0.008201,0.018152,0.016011,-0.009222,0.020974,0.008694,-0.047264,0.028262,-0.002851,0.009422,-0.012002,0.004519,-0.010160,-0.031831,-0.005528,0.038708,-0.014277,0.009808,0.004059,-0.009500,0.033000,-0.038357,-0.005480,0.016188,-0.012154,-0.003113,0.007213,-0.049557,0.001337,0.025862,0.002217,0.009792,-0.002905,0.012793,-0.039633,-0.014680,0.012541,-0.026685,-0.057037,-0.038288,-0.031196,-0.025930,0.009651,0.004537,0.035687,-0.013257,0.015052,-0.006502,0.018667,-0.013956,0.023991,0.033361,-0.000124,-0.000186,0.012095,0.023317,0.014021,-0.007477,-0.006606,-0.045891,0.004310,-0.008439,0.004574,-0.039585,0.004941,0.010379,-0.002950,-0.053005,0.008541,-0.002762,0.010718,0.035433,0.017978,0.027453,-0.019744,0.008659,0.023139,-0.009485,-0.030263,0.013689,-0.022727,0.006843,2026-03-05 15:00:00

In [28]:
#tg_hourly["datetime_hour"] = tg_hourly["datetime_hour"] + pd.Timedelta(hours=1)        ТУТ ЗСУВ ТГ НА 1 ГОДИНУ

In [29]:
df_final = df_final.merge(tg_hourly, on="datetime_hour", how="left")

In [30]:
df_final.sample(20)

,datetime_hour,region_id,city_latitude,city_longitude,day_temp,day_dew,day_humidity,day_precip,day_precipprob,day_precipcover,day_snow,day_snowdepth,day_windgust,day_windspeed,day_winddir,day_pressure,day_cloudcover,day_solarradiation,day_solarenergy,day_uvindex,day_moonphase,hour_temp,hour_feelslike,hour_humidity,hour_precip,hour_precipprob,hour_snow,hour_windgust,hour_windspeed,hour_winddir,hour_pressure,hour_cloudcover,hour_solarradiation,hour_solarenergy,hour_uvindex,day_conditions_simple_Clear,day_conditions_simple_Cloudy,day_conditions_simple_Rain,day_conditions_simple_Snow,hour_conditions_simple_Clear,hour_conditions_simple_Cloudy,hour_conditions_simple_Rain,hour_conditions_simple_Snow,year,month,day_of_week,hour,city_name,city_timezone,day_datetime,day_sunrise,day_sunset,hour_datetime,region_key,alarm_active,alarm_minutes_in_hour,alarm_lag_1,alarm_lag_3,alarm_lag_6,alarm_lag_12,alarms_in_last_24h,is_weekend,is_night,total_active_alarms_lag1,neighbour_alarms,hours_since_last_alarm,isw_topic_0,isw_topic_1,isw_topic_2,isw_topic_3,isw_topic_4,isw_topic_5,isw_topic_6,isw_topic_7,isw_topic_8,isw_topic_9,isw_topic_10,isw_topic_11,isw_topic_12,isw_topic_13,isw_topic_14,isw_topic_15,isw_topic_16,isw_topic_17,isw_topic_18,isw_topic_19,isw_topic_20,isw_topic_21,isw_topic_22,isw_topic_23,isw_topic_24,isw_topic_25,isw_topic_26,isw_topic_27,isw_topic_28,isw_topic_29,isw_topic_30,isw_topic_31,isw_topic_32,isw_topic_33,isw_topic_34,isw_topic_35,isw_topic_36,isw_topic_37,isw_topic_38,isw_topic_39,isw_topic_40,isw_topic_41,isw_topic_42,isw_topic_43,isw_topic_44,isw_topic_45,isw_topic_46,isw_topic_47,isw_topic_48,isw_topic_49,isw_topic_50,isw_topic_51,isw_topic_52,isw_topic_53,isw_topic_54,isw_topic_55,isw_topic_56,isw_topic_57,isw_topic_58,isw_topic_59,isw_topic_60,isw_topic_61,isw_topic_62,isw_topic_63,isw_topic_64,isw_topic_65,isw_topic_66,isw_topic_67,isw_topic_68,isw_topic_69,isw_topic_70,isw_topic_71,isw_topic_72,isw_topic_73,isw_topic_74,isw_topic_75,isw_topic_76,isw_topic_77,isw_topic_78,isw_topic_79,isw_topic_80,isw_topic_81,isw_topic_82,isw_topic_83,isw_topic_84,isw_topic_85,isw_topic_86,isw_topic_87,isw_topic_88,isw_topic_89,isw_topic_90,isw_topic_91,isw_topic_92,isw_topic_93,isw_topic_94,isw_topic_95,isw_topic_96,isw_topic_97,isw_topic_98,isw_topic_99,isw_topic_100,isw_topic_101,isw_topic_102,isw_topic_103,isw_topic_104,isw_topic_105,isw_topic_106,isw_topic_107,isw_topic_108,isw_topic_109,isw_topic_110,isw_topic_111,isw_topic_112,isw_topic_113,isw_topic_114,isw_topic_115,isw_topic_116,isw_topic_117,isw_topic_118,isw_topic_119,isw_topic_120,isw_topic_121,isw_topic_122,isw_topic_123,isw_topic_124,isw_topic_125,isw_topic_126,isw_topic_127,isw_topic_128,isw_topic_129,isw_topic_130,isw_topic_131,isw_topic_132,isw_topic_133,isw_topic_134,isw_topic_135,isw_topic_136,isw_topic_137,isw_topic_138,isw_topic_139,isw_topic_140,isw_topic_141,isw_topic_142,isw_topic_143,isw_topic_144,isw_topic_145,isw_topic_146,isw_topic_147,isw_topic_148,isw_topic_149,isw_total_intensity,isw_topic_std,isw_topic_max,isw_topic_mean,isw_velocity_24h,isw_intensity_ema,isw_topic_entropy,tg_topic_0,tg_topic_1,tg_topic_2,tg_topic_3,tg_topic_4,tg_topic_5,tg_topic_6,tg_topic_7,tg_topic_8,tg_topic_9,tg_topic_10,tg_topic_11,tg_topic_12,tg_topic_13,tg_topic_14,tg_topic_15,tg_topic_16,tg_topic_17,tg_topic_18,tg_topic_19,tg_topic_20,tg_topic_21,tg_topic_22,tg_topic_23,tg_topic_24,tg_topic_25,tg_topic_26,tg_topic_27,tg_topic_28,tg_topic_29,tg_topic_30,tg_topic_31,tg_topic_32,tg_topic_33,tg_topic_34,tg_topic_35,tg_topic_36,tg_topic_37,tg_topic_38,tg_topic_39,tg_topic_40,tg_topic_41,tg_topic_42,tg_topic_43,tg_topic_44,tg_topic_45,tg_topic_46,tg_topic_47,tg_topic_48,tg_topic_49,tg_topic_50,tg_topic_51,tg_topic_52,tg_topic_53,tg_topic_54,tg_topic_55,tg_topic_56,tg_topic_57,tg_topic_58,tg_topic_59,tg_topic_60,tg_topic_61,tg_topic_62,tg_topic_63,tg_topic_64,tg_topic_65,tg_topic_66,tg_topic_67,tg_topic_68,tg_topic_69,tg_topic_70,tg_topic_71,tg_topic_72,tg_topic_73,tg_topic_74,tg_topic_75,tg_topic_76,tg_topic_77,tg_topic_78,tg_topic_79,tg_topic_80,tg_topic_81,tg_topic_82,tg_topic_83,tg_topic_84,tg_topic_85,tg_topic_86,tg_topic_87,tg_topic_88,tg_topic_89,tg_topic_90,tg_topic_91,tg_topic_92,tg_topic_93,tg_topic_94,tg_topic_95,tg_topic_96,tg_topic_97,tg_topic_98,tg_topic_99,tg_topic_100,tg_topic_101,tg_topic_102,tg_topic_103,tg_topic_104,tg_topic_105,tg_topic_106,tg_topic_107,tg_topic_108,tg_topic_109,tg_topic_110,tg_topic_111,tg_topic_112,tg_topic_113,tg_topic_114,tg_topic_115,tg_topic_116,tg_topic_117,tg_topic_118,tg_topic_119,tg_topic_120,tg_topic_121,tg_topic_122,tg_topic_123,tg_topic_124,tg_topic_125,tg_topic_126,tg_topic_127,tg_topic_128,tg_topic_129,tg_topic_130,tg_topic_131,tg_topic_132,tg_topic_133,tg_topic_134,tg_topic_135,tg_topic_136,tg_topic_137,tg_topic_138,tg_topic_139,tg_topic_140,tg_topic_141,tg_topic_142,tg_topic_143,tg_topic_144,tg_topic_145,tg_topic_146,tg_topic_147,tg_topic_148,tg_topic_149,tg_topic_150,tg_topic_151,tg_topic_152,tg_topic_153,tg_topic_154,tg_topic_155,tg_topic_156,tg_topic_157,tg_topic_158,tg_topic_159,tg_topic_160,tg_topic_161,tg_topic_162,tg_topic_163,tg_topic_164,tg_topic_165,tg_topic_166,tg_topic_167,tg_topic_168,tg_topic_169,tg_topic_170,tg_topic_171,tg_topic_172,tg_topic_173,tg_topic_174,tg_topic_175,tg_topic_176,tg_topic_177,tg_topic_178,tg_topic_179,tg_topic_180,tg_topic_181,tg_topic_182,tg_topic_183,tg_topic_184,tg_topic_185,tg_topic_186,tg_topic_187,tg_topic_188,tg_topic_189,tg_topic_190,tg_topic_191,tg_topic_192,tg_topic_193,tg_topic_194,tg_topic_195,tg_topic_196,tg_topic_197,tg_topic_198,tg_topic_199,tg_topic_200,tg_topic_201,tg_topic_202,tg_topic_203,tg_topic_204,tg_topic_205,tg_topic_206,tg_topic_207,tg_topic_208,tg_topic_209,tg_topic_210,tg_topic_211,tg_topic_212,tg_topic_213,tg_topic_214,tg_topic_215,tg_topic_216,tg_topic_217,tg_topic_218,tg_topic_219,tg_topic_220,tg_topic_221,tg_topic_222,tg_topic_223,tg_topic_224,tg_topic_225,tg_topic_226,tg_topic_227,tg_topic_228,tg_topic_229,tg_topic_230,tg_topic_231,tg_topic_232,tg_topic_233,tg_topic_234,tg_topic_235,tg_topic_236,tg_topic_237,tg_topic_238,tg_topic_239,tg_topic_240,tg_topic_241,tg_topic_242,tg_topic_243,tg_topic_244,tg_topic_245,tg_topic_246,tg_topic_247,tg_topic_248,tg_topic_249
619364,2023-05-09 19:00:00,26,50.45060,30.52430,9.6,-2.9,43.5,0.100,100.0,4.17,0.0,0.0,39.2,18.4,39.7,1028.3,78.1,222.2,19.0,7.0,0.63,13.2,13.2,31.40,0.0,0.0,0.0,27.0,11.2,42.2,1026.0,85.8,177.7,0.6,2.0,False,False,True,False,False,True,False,False,2023,5,1,19,Kyiv,Europe/Kiev,2023-05-09,05:20:05,20:29:44,19:00:00,Київ,0,0.000000,0.0,0.0,0.0,0.0,3.0,0,0,1.0,0.0,12,0.655291,-0.243454,-0.115147,-0.015367,0.013546,0.070645,-0.027938,0.117800,-0.163106,0.141880,0.112024,0.031456,-0.085903,-0.008538,0.132460,0.148685,0.228492,-0.038755,-0.106856,0.065451,0.119254,0.018395,0.080277,-0.080309,0.074529,0.081670,0.025250,-0.085439,0.049002,0.035057,0.001196,-0.035543,-0.038983,0.079606,0.025782,0.002485,-0.007463,0.006557,0.076843,0.072642,0.047106,-0.047184,0.011543,0.022796,0.024872,0.006548,0.070984,0.040978,0.039967,-0.044242,0.043541,0.009018,-0.029640,0.005521,-0.047910,0.019631,-0.059923,-0.030760,-0.028036,0.037690,-0.020922,-0.014259,-0.025446,0.066496,-0.017957,-0.022271,0.018733,0.067750,0.028576,0.028454,0.037263,0.020553,-0.003868,-0.009521,-0.004506,-0.071522,-0.005648,0.000083,-0.004464,-0.017875,-0.040314,-0.057382,0.017040,-0.017589,-0.006662,-0.019779,-0.041064,-0.033399,0.053629,0.023968,-0.026460,0.019272,0.006401,0.010837,-0.010208,-0.010140,-0.015842,0.047724,-0.014374,-0.002029,-0.004775,-0.014558,-0.010807,-0.026030,0.039830,0.006155,0.026746,-0.003473,-0.026313,0.007851,0.011579,-0.012770,0.027930,-0.007317,-0.018687,-0.024427,0.010001,-0.013281,-0.000521,-0.015115,0.004080,-0.002774,-0.050842,-0.009142,-0.002928,-0.009052,0.028329,0.008240,0.014736,0.019216,0.005578,0.013672,-0.014124,0.005248,-0.023872,-0.007257,0.023430,0.019029,0.008539,0.008823,-0.001447,-0.013522,0.006273,0.013246,-0.000467,0.001843,0.011415,0.035190,-0.047890,0.025898,5.891515,0.064651,0.655291,0.039277,0.800231,5.750150,4.362983,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
467522,2024-02-24 07:00:00,20,50.00420,36.23580,1.0,-1.5,84.4,0.000,0.0,0.00,0.0,5.9,46.8,28.8,122.0,1029.3,91.3,108.4,9.4,4.0,0.50,-2.0,-7.5,100.00,0.0,0.0,0.0,32.4,18.0,120.0,1028.0,100.0,5.3,0.0,0.0,False,True,False,False,False,True,False,False,2024,2,5,7,Kharkiv,Europe/Kiev,2024-02-24,06:29:50,17:07:44,07:00:00,Харківська,0,0.000000,0.0,0.0,0.0,0.0,6.0,1,0,0.0,0.0,8,0.798980,-0.040089,-0.199298,0.143927,0.052118,-0.019796,-0.005087,0.014307,0.009153,-0.018403,-0.063141,0.026318,0.201105,-0.171390,-0.017760,-0.043249,0.037389,-0.017575,0.004895,-0.033754,-0.029204,-0.001432,-0.010787,-0.003618,-0.028165,0.099587,-0.031921,0.028903,0.031185,-0.026928,-0.002748,0.013503,0.052169,-0.005480,0.005491,-0.008847,-0.063870,0.030306,0.004394,-0.000432,-0.063397,-0.010085,-0.027880,0.007339,-0.015611,0.002138,-0.015521,0.038091,0.014352,-0.027481,0.039194,-0.009928,0.019931,-0.030609,-0.001403,0.009361,0.018964,-0.014977,0.006078,0.021943,0.014006,-0.038668,0.007982,0.025602,-0.023668,-0.031992,-0.026945,0.038901,0.050350,-0.003648,-0.044901,-0.011279,-0.016699,-0.006788,0.006654,-0.010192,0.002957,-0.053300,0.003959,0.013247,-0.020390,-0.003760,0.015202,-0.023273,0.002835,-0.003767,-0.014207,-0.008732,-0.023595,0.000643,-0.008530,-0.011154,0.002926,0.041821,0.022550,0.002584,-0.031944,-0.015123,-0.031597,0.026405,0.016359,-0.028342,-0.028111,-0.007097,0.056278,-0.013471,0.010915,0.019137,-0.011753,0.001365,0.029386,-0.049204,-0.005920,0.005444,0.020005,-0.000722,0.011330,-0.005909,0.013631,-0.001649,0.015511,0.031430,-0.014248,0.017314,0.025547,-0.008482,0.005419,-0.000396,0.046123,0.029816,0.014623,0.008525,-0.005210,0.003786,0.007693,-0.002850,0.013602,-0.011956,0.035065,-0.016917,0.021087,0.003346,-0.009309,-0.027303,-0.010620,0.015752,0.021189,-0.051037,0.008168,0.005921,4.358040,0.070324,0.798980,0.029054,-1.017794,4.874212,4.149304,0.109267,-0.033579,0.115138,0.061618,-0.059098,0.092764,-0.142260,-0.003018,0.080335,0.004094,0.066542,-0.027284,0.016698,-0.006974,0.013941,-0.003972,0.039263,-0.017057,-0.118188,-0.164422,-0.072862,0.182142,0.072013,0.190590,0.107414,-0.214677,0.103312,-0.063844,-0.038584,-0.005993,-0.009179,-0.054800,-0.048586,0.078227,-0.026782,-0.020858,-0.045048,0.048995,0.045919,-0.031642,-0.036779,-0.069063,-0.092131,-0.009986,0.010804,-0.071406,0.000205,-0.002260,-0.051723,-0.036552,0.013232,-0.008933,-0.018920,0.053753,0.002238,-0.021758,-0.034701,0.025682,0.018374,-0.043266,-0.018334,0.043918,0.014645,0.042489,0.014030,-0.020847,0.012735,-0.034860,0.021933,-0.003064,0.001925,-0.010492,0.026737,0.003709,-0.022948,0.006175,-0.008294,0.018406,-0.021935,0.000956,-0.007375,-0.009581,0.000830,0.022486,-0.031782,-0.018115,-0.001325,-0.018254,0.007918,-0.001390,0.036746,-0.026075,0.045500,0.005653,-0.010335,-0.022047,-0.006263,-0.010332,0.006466,0.009711,0.006309,0.003543,-0.021122,-0.006883,0.006075,0.001684,-0.020233,-0.002420,-0.004045,0.009555,-0.009305,0.010567,-0.019860,-0.029443,0.009642,0.012180,-0.009524,0.010142,-0.027290,0.013965,0.004312,-0.000405,-0.011176,-0.024202,0.008745,-0.016051,0.001208,0.007812,0.044287,-0.034558,0.001546,0.025493,-0.017215,-0.001274,0.012998,0.005338,0.011128,0.046960,-0.060092,0.016125,-0.042843,-0.007839,0.020031,0.028762,-0.001145,-0.006427,0.010869,-0.067390,0.031620,0.024049,-0.006607,0.009678,-0.044785,-0.002815,-0.005166,-0.016290,0.023317,-0.022936,0.018681,0.035799,-0.047179,-0.026669,-0.029637,-0.014291,0.041976,-0.045475,0.036402,0.035142,-0.014406,-0.030403,-0.015834,-0.008683,0.016100,-0.015841,-0.035011,-0.041291,-0.011791,-0.049765,0.048327,0.031813,0.027979,0.042756,0.036769,0.023851,0.016952,0.036867,-0.020608,0.031780,-0.007118,-0.064860,-0.002249,0.102190,-0.075318,-0.025527,0.003496,-0.031011,0.030619,0.050056,0.011428,0.038663,-0.018259,-0.008410,0.004512,-0.002954,-0.000566,-0.000198,-0.014859,-0.009562,-0.038988,-0.012390,-0.004747,-0.001121,0.013517,0.017844,0.018198,0.002213,0.014524,-0.053689,0.032885,0.003872,-0.057346,0.008940,0.001372,0.020328,-0.049100,0.021625,-0.000320,0.022740,0.021513,0.025109,-0.029730,-0.012392,0.022819,-0.028186,0.020886,0.028096,-0.007603,0.029775,-0.020600,-0.037733,0.034878,-0.029398,-0.038832,0.021876,-0.007527,-0.008825,-0.014449,0.009184,0.002965,-0.002035
1917,2022-05-13 22:00:00,2,49.23360,28.44860,17.7,9.8,61.9,0.100,100.0,4.17,0.0,0.0,30.2,13.3,271.2,1015.9,89.0,220.8,18.9,7.0,0.41,15.9,15.9,75.62,0.0,0.0,0.0,18.0,8.3,207.9,1014.0,100.0,0.0,0.1,0.0,False,False,True,False,False,True,False,False,2022,5,4,22,Vinnytsia,Europe/Kiev,2022-05-13,05:26:13,20:39:51,22:00:00,Вінницька,1,28.166667,1.0,0.0,0.0,0.0,7.0,0,0,13.0,4.0,0,0.700683,-0.200705,0.365434,0.069992,0.038297,-0.009511,0.020468,-0.082590,0.021742,-0.071330,-0.037783,0.039568,0.034713,-0.022675,0.038784,0.006714,0.150180,0.032872,-0.027803,-0.040835,0.060159,0.012408,0.002785,0.069609,-0.028706,0.021588,0.005607,0.005549,-0.027741,0.037620,-0.049678,-0.068158,0.022197,-0.030691,-0.045029,0.045354,0.047148,0.005703,0.012393,0.015411,0.009527,-0.034569,0.047021,-0.043900,0.024514,-0.002204,0.009079,-0.060000,-0.005654,0.003930,0.019348,0.013594,-0.003897,0.022201,0.057864,-0.000148,-0.007843,0.020249,0.036021,-0.000938,0.002553,-0.002182,0.056618,-0.044423,0.016136,-0.003189,0.014077,0.033061,0.019575,-0.003282,0.014353,-0.013102,0.010202,0.036930,-0.023032,0.009190,-0.001509,0.030781,0.005220,-0.009908,0.054915,0.032775,0.016815,0.023517,-0.006786,-0.004519,0.003459,0.002591,-0.046797,0.049397,-0.038250,0.025822,0.038765,0.018082,0.002374,-0.040456,-0.024073,0.044471,-0.012630,0.062938,-0.016606,-0.005690,0.017501,-0.026538,0.016185,-0.017146,0.045974,0.056800,-0.040105,0.049960,0.078816,0.077379,0.002247,-0.016656,0.008510,0.010284,-0.032465,0.068550,0.041871,0.017701,0.000017,-0.026449,0.005550,-0.017901,0.063438,-0.041695,-0.030699,0.052196,0.006328,0.027074,-0.042446,0.015617,-0.012244,0.030628,0.008148,-0.028266,-0.011550,0.012661,0.000233,0.022056,-0.021198,0.059262,-0.043501,-0.038684,-0.013841,0.024073,-0.021291,0.043691,-0.034294,0.002078,5.351564,0.066602,0.700683,0.035677,0.860765,5.229080,4.350874,0.028049,0.002414,0.040311,-0.006482,-0.054165,0.078576,-0.060875,0.054651,-0.042986,0.100609,-0.028128,0.007437,-0.015251,0.034331,0.032960,-0.019067,-0.010372,-0.019101,-0.003210,0.025038,0.040794,0.053204,-0.012976,-0.023924,-0.018188,0.017947,-0.005296,-0.000210,-0.011011,0.004701,-0.001264,0.017661,-0.001398,0.020889,-0.045257,0.004665,0.013334,0.002056,0.040935,-0.043284,0.006509,0.041210,0.039071,0.027625,-0.062294,-0.016350,0.018180,0.009884,0.030787,0.011331,0.022520,-0.004288,0.040683,0.003463,-0.039009,-0.032925,-0.015035,-0.001285,-0.028167,0.010464,-0.008701,0.016670,0.009832,0.006131,0.005956,0.010561,0.017960,0.000222,-0.004683,0.006307,-0.029810,-0.017205,0.002902,0.000731,0.004657,0.006522,-0.026835,-0.024265,0.007149,-0.006689,-0.004790,-0.005994,-0.019453,0.015975,-0.000674,-0.007339,0.011771,0.004899,-0.005153,-0.032606,0.002880,-0.001873,-0.001229,-0.006475,-0.000027,0.013253,0.015302,0.001001,-0.000981,-0.005365,-0.007607,-0.003173,-0.005716,-0.009137,0.008586,0.003716,0.006497,0.016222,-0.007528,0.007425,0.002654,-0.017389,-0.018447,-0.008536,0.006206,0.008342,-0.001885,0.008471,-0.015763,-0.004847,0.009101,-0.000486,-0.011056,0.026003,-0.011123,0.003045,0.011233,-0.000198,-0.006787,-0.002626,0.003232,0.002017,-0.003197,-0.007836,-0.003496,0.001103,0.011271,-0.007049,-0.004150,0.004967,-0.010513,-0.008254,-0.006811,-0.000496,0.001023,-0.002939,0.002333,-0.001547,0.003815,0.001890,0.003627,0.001531,-0.009053,-0.004965,-0.015126,0.007375,-0.002500,-0.001004,0.016283,0.010136,-0.005319,0.006445,-0.010332,-0.006529,0.001252,0.010501,0.003623,0.003237,-0.010385,-0.002362,-0.002687,-0.002294,-0.001414,-0.021272,-0.006310,-0.006802,-0.022461,-0.007547,0.009221,0.023231,0.015161,0.008573,0.001317,0.004713,-0.008453,-0.014297,0.003596,0.004745,-0.002468,-0.006056,-0.012801,0.009773,0.005609,-0.020793,0.016129,0.008613,0.009202,-0.009064,-0.005941,-0.000656,0.003071,0.002977,0.001564,0.002486,-0.006250,-0.013979,0.018135,0.018945,0.026526,0.005870,0.013330,-0.031352,0.000256,0.020998,-0.005175,0.005018,0.004224,-0.006621,-0.013349,0.017484,-0.003858,0.014134,0.019139,-0.000700,-0.004521,0.013995,-0.000146,-0.014365,0.018560,0.015237,-0.004639,0.014352,0.002034,0.009432,-0.000444,-0.003851,0.003861,-0.016693,-0.015381,0.001477,-0.009452,0.008741,0.003765,0.005865,0.013224,0.010722,-0.015804,-0.008926,0.019340,-0.014510

In [31]:
df_final.shape

(635256, 473)

In [32]:
df_final = df_final.sort_values(["datetime_hour"])

In [33]:
with pd.option_context('display.max_rows', None):
    print(df_final.isnull().sum())

datetime_hour                         0
region_id                             0
city_latitude                         0
city_longitude                        0
day_temp                              0
day_dew                               0
day_humidity                          0
day_precip                            0
day_precipprob                        0
day_precipcover                       0
day_snow                              0
day_snowdepth                         0
day_windgust                          0
day_windspeed                         0
day_winddir                           0
day_pressure                          0
day_cloudcover                        0
day_solarradiation                    0
day_solarenergy                       0
day_uvindex                           0
day_moonphase                         0
hour_temp                             0
hour_feelslike                        0
hour_humidity                         0
hour_precip                           0
hour_precipprob                       0
hour_snow                             0
hour_windgust                         0
hour_windspeed                        0
hour_winddir                          0
hour_pressure                         0
hour_cloudcover                       0
hour_solarradiation                   0
hour_solarenergy                      0
hour_uvindex                          0
day_conditions_simple_Clear           0
day_conditions_simple_Cloudy          0
day_conditions_simple_Rain            0
day_conditions_simple_Snow            0
hour_conditions_simple_Clear          0
hour_conditions_simple_Cloudy         0
hour_conditions_simple_Rain           0
hour_conditions_simple_Snow           0
year                                  0
month                                 0
day_of_week                           0
hour                                  0
city_name                             0
city_timezone                         0
day_datetime                          0
day_sunrise                           0
day_sunset                            0
hour_datetime                         0
region_key                            0
alarm_active                          0
alarm_minutes_in_hour                 0
alarm_lag_1                           0
alarm_lag_3                           0
alarm_lag_6                           0
alarm_lag_12                          0
alarms_in_last_24h                    0
is_weekend                            0
is_night                              0
total_active_alarms_lag1              0
neighbour_alarms                      0
hours_since_last_alarm                0
isw_topic_0                           0
isw_topic_1                           0
isw_topic_2                           0
isw_topic_3                           0
isw_topic_4                           0
isw_topic_5                           0
isw_topic_6                           0
isw_topic_7                           0
isw_topic_8                           0
isw_topic_9                           0
isw_topic_10                          0
isw_topic_11                          0
isw_topic_12                          0
isw_topic_13                          0
isw_topic_14                          0
isw_topic_15                          0
isw_topic_16                          0
isw_topic_17                          0
isw_topic_18                          0
isw_topic_19                          0
isw_topic_20                          0
isw_topic_21                          0
isw_topic_22                          0
isw_topic_23                          0
isw_topic_24                          0
isw_topic_25                          0
isw_topic_26                          0
isw_topic_27                          0
isw_topic_28                          0
isw_topic_29                          0
isw_topic_30                          0
isw_topic_31                          0
isw_topic_32                          0
isw_topic_33                          0
isw_topic_34                          0
isw_topic_35                          0
isw_topic_36                          0
isw_topic_37                          0
isw_topic_38                          0
isw_topic_39                          0
isw_topic_40                          0
isw_topic_41                          0
isw_topic_42                          0
isw_topic_43                          0
isw_topic_44                          0
isw_topic_45                          0
isw_topic_46                          0
isw_topic_47                          0
isw_topic_48                          0
isw_topic_49                          0
isw_topic_50                          0
isw_topic_51                          0
isw_topic_52                          0
isw_topic_53                          0
isw_topic_54                          0
isw_topic_55                          0
isw_topic_56                          0
isw_topic_57                          0
isw_topic_58                          0
isw_topic_59                          0
isw_topic_60                          0
isw_topic_61                          0
isw_topic_62                          0
isw_topic_63                          0
isw_topic_64                          0
isw_topic_65                          0
isw_topic_66                          0
isw_topic_67                          0
isw_topic_68                          0
isw_topic_69                          0
isw_topic_70                          0
isw_topic_71                          0
isw_topic_72                          0
isw_topic_73                          0
isw_topic_74                          0
isw_topic_75                          0
isw_topic_76                          0
isw_topic_77                          0
isw_topic_78                          0
isw_topic_79                          0
isw_topic_80                          0
isw_topic_81                          0
isw_topic_82                          0
isw_topic_83                          0
isw_topic_84                          0
isw_topic_85                          0
isw_topic_86                          0
isw_topic_87                          0
isw_topic_88                          0
isw_topic_89                          0
isw_topic_90                          0
isw_topic_91                          0
isw_topic_92                          0
isw_topic_93                          0
isw_topic_94                          0
isw_topic_95                          0
isw_topic_96                          0
isw_topic_97                          0
isw_topic_98                          0
isw_topic_99                          0
isw_topic_100                         0
isw_topic_101                         0
isw_topic_102                         0
isw_topic_103                         0
isw_topic_104                         0
isw_topic_105                         0
isw_topic_106                         0
isw_topic_107                         0
isw_topic_108                         0
isw_topic_109                         0
isw_topic_110                         0
isw_topic_111                         0
isw_topic_112                         0
isw_topic_113                         0
isw_topic_114                         0
isw_topic_115                         0
isw_topic_116                         0
isw_topic_117                         0
isw_topic_118                         0
isw_topic_119                         0
isw_topic_120                         0
isw_topic_121                         0
isw_topic_122                         0
isw_topic_123                         0
isw_topic_124                         0
isw_topic_125                         0
isw_topic_126                         0
isw_topic_127                         0
isw_topic_128                         0
isw_topic_129                         0
isw_topic_130                         0
isw_topic_131                         0
isw_topic_132                         0
isw_topic_133                         0
isw_topic_134                         0
isw_topic_135                         0
isw_topic_136                         0
isw_topic_137                         0
isw_topic_138                         0
isw_topic_139                         0
isw_topic_140                         0
isw_topic_141                         0
isw_topic_142                         0
isw_topic_143                         0
isw_topic_144                         0
isw_topic_145                         0
isw_topic_146                         0
isw_topic_147                         0
isw_topic_148                         0
isw_topic_149                         0
isw_total_intensity                   0
isw_topic_std                         0
isw_topic_max                         0
isw_topic_mean                        0
isw_velocity_24h                      0
isw_intensity_ema                     0
isw_topic_entropy                     0
tg_topic_0                       121728
tg_topic_1                       121728
tg_topic_2                       121728
tg_topic_3                       121728
tg_topic_4                       121728
tg_topic_5                       121728
tg_topic_6                       121728
tg_topic_7                       121728
tg_topic_8                       121728
tg_topic_9                       121728
tg_topic_10                      121728
tg_topic_11                      121728
tg_topic_12                      121728
tg_topic_13                      121728
tg_topic_14                      121728
tg_topic_15                      121728
tg_topic_16                      121728
tg_topic_17                      121728
tg_topic_18                      121728
tg_topic_19                      121728
tg_topic_20                      121728
tg_topic_21                      121728
tg_topic_22                      121728
tg_topic_23                      121728
tg_topic_24                      121728
tg_topic_25                      121728
tg_topic_26                      121728
tg_topic_27                      121728
tg_topic_28                      121728
tg_topic_29                      121728
tg_topic_30                      121728
tg_topic_31                      121728
tg_topic_32                      121728
tg_topic_33                      121728
tg_topic_34                      121728
tg_topic_35                      121728
tg_topic_36                      121728
tg_topic_37                      121728
tg_topic_38                      121728
tg_topic_39                      121728
tg_topic_40                      121728
tg_topic_41                      121728
tg_topic_42                      121728
tg_topic_43                      121728
tg_topic_44                      121728
tg_topic_45                      121728
tg_topic_46                      121728
tg_topic_47                      121728
tg_topic_48                      121728
tg_topic_49                      121728
tg_topic_50                      121728
tg_topic_51                      121728
tg_topic_52                      121728
tg_topic_53                      121728
tg_topic_54                      121728
tg_topic_55                      121728
tg_topic_56                      121728
tg_topic_57                      121728
tg_topic_58                      121728
tg_topic_59                      121728
tg_topic_60                      121728
tg_topic_61                      121728
tg_topic_62                      121728
tg_topic_63                      121728
tg_topic_64                      121728
tg_topic_65                      121728
tg_topic_66                      121728
tg_topic_67                      121728
tg_topic_68                      121728
tg_topic_69                      121728
tg_topic_70                      121728
tg_topic_71                      121728
tg_topic_72                      121728
tg_topic_73                      121728
tg_topic_74                      121728
tg_topic_75                      121728
tg_topic_76                      121728
tg_topic_77                      121728
tg_topic_78                      121728
tg_topic_79                      121728
tg_topic_80                      121728
tg_topic_81                      121728
tg_topic_82                      121728
tg_topic_83                      121728
tg_topic_84                      121728
tg_topic_85                      121728
tg_topic_86                      121728
tg_topic_87                      121728
tg_topic_88                      121728
tg_topic_89                      121728
tg_topic_90                      121728
tg_topic_91                      121728
tg_topic_92                      121728
tg_topic_93                      121728
tg_topic_94                      121728
tg_topic_95                      121728
tg_topic_96                      121728
tg_topic_97                      121728
tg_topic_98                      121728
tg_topic_99                      121728
tg_topic_100                     121728
tg_topic_101                     121728
tg_topic_102                     121728
tg_topic_103                     121728
tg_topic_104                     121728
tg_topic_105                     121728
tg_topic_106                     121728
tg_topic_107                     121728
tg_topic_108                     121728
tg_topic_109                     121728
tg_topic_110                     121728
tg_topic_111                     121728
tg_topic_112                     121728
tg_topic_113                     121728
tg_topic_114                     121728
tg_topic_115                     121728
tg_topic_116                     121728
tg_topic_117                     121728
tg_topic_118                     121728
tg_topic_119                     121728
tg_topic_120                     121728
tg_topic_121                     121728
tg_topic_122                     121728
tg_topic_123                     121728
tg_topic_124                     121728
tg_topic_125                     121728
tg_topic_126                     121728
tg_topic_127                     121728
tg_topic_128                     121728
tg_topic_129                     121728
tg_topic_130                     121728
tg_topic_131                     121728
tg_topic_132                     121728
tg_topic_133                     121728
tg_topic_134                     121728
tg_topic_135                     121728
tg_topic_136                     121728
tg_topic_137                     121728
tg_topic_138                     121728
tg_topic_139                     121728
tg_topic_140                     121728
tg_topic_141                     121728
tg_topic_142                     121728
tg_topic_143                     121728
tg_topic_144                     121728
tg_topic_145                     121728
tg_topic_146                     121728
tg_topic_147                     121728
tg_topic_148                     121728
tg_topic_149                     121728
tg_topic_150                     121728
tg_topic_151                     121728
tg_topic_152                     121728
tg_topic_153                     121728
tg_topic_154                     121728
tg_topic_155                     121728
tg_topic_156                     121728
tg_topic_157                     121728
tg_topic_158                     121728
tg_topic_159                     121728
tg_topic_160                     121728
tg_topic_161                     121728
tg_topic_162                     121728
tg_topic_163                     121728
tg_topic_164                     121728
tg_topic_165                     121728
tg_topic_166                     121728
tg_topic_167                     121728
tg_topic_168                     121728
tg_topic_169                     121728
tg_topic_170                     121728
tg_topic_171                     121728
tg_topic_172                     121728
tg_topic_173                     121728
tg_topic_174                     121728
tg_topic_175                     121728
tg_topic_176                     121728
tg_topic_177                     121728
tg_topic_178                     121728
tg_topic_179                     121728
tg_topic_180                     121728
tg_topic_181                     121728
tg_topic_182                     121728
tg_topic_183                     121728
tg_topic_184                     121728
tg_topic_185                     121728
tg_topic_186                     121728
tg_topic_187                     121728
tg_topic_188                     121728
tg_topic_189                     121728
tg_topic_190                     121728
tg_topic_191                     121728
tg_topic_192                     121728
tg_topic_193                     121728
tg_topic_194                     121728
tg_topic_195                     121728
tg_topic_196                     121728
tg_topic_197                     121728
tg_topic_198                     121728
tg_topic_199                     121728
tg_topic_200                     121728
tg_topic_201                     121728
tg_topic_202                     121728
tg_topic_203                     121728
tg_topic_204                     121728
tg_topic_205                     121728
tg_topic_206                     121728
tg_topic_207                     121728
tg_topic_208                     121728
tg_topic_209                     121728
tg_topic_210                     121728
tg_topic_211                     121728
tg_topic_212                     121728
tg_topic_213                     121728
tg_topic_214                     121728
tg_topic_215                     121728
tg_topic_216                     121728
tg_topic_217                     121728
tg_topic_218                     121728
tg_topic_219                     121728
tg_topic_220                     121728
tg_topic_221                     121728
tg_topic_222                     121728
tg_topic_223                     121728
tg_topic_224                     121728
tg_topic_225                     121728
tg_topic_226                     121728
tg_topic_227                     121728
tg_topic_228                     121728
tg_topic_229                     121728
tg_topic_230                     121728
tg_topic_231                     121728
tg_topic_232                     121728
tg_topic_233                     121728
tg_topic_234                     121728
tg_topic_235                     121728
tg_topic_236                     121728
tg_topic_237                     121728
tg_topic_238                     121728
tg_topic_239                     121728
tg_topic_240                     121728
tg_topic_241                     121728
tg_topic_242                     121728
tg_topic_243                     121728
tg_topic_244                     121728
tg_topic_245                     121728
tg_topic_246                     121728
tg_topic_247                     121728
tg_topic_248                     121728
tg_topic_249                     121728
dtype: int64

In [34]:
df_final = df_final.fillna(0)

In [35]:
tg_cols = [c for c in df_final.columns if 'tg_topic_' in c]
df_tg_abs = df_final[tg_cols].abs()

df_final['tg_total_intensity'] = df_tg_abs.sum(axis=1)
df_final['tg_topic_std'] = df_tg_abs.std(axis=1)
df_final['tg_topic_max'] = df_tg_abs.max(axis=1)
df_final['tg_topic_entropy'] = -(df_tg_abs.div(df_tg_abs.sum(axis=1), axis=0) * np.log(df_tg_abs.div(df_tg_abs.sum(axis=1), axis=0) + 1e-9)).sum(axis=1)

C:\Users\Uw11\AppData\Local\Temp\ipykernel_22436\409095542.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_final['tg_total_intensity'] = df_tg_abs.sum(axis=1)
C:\Users\Uw11\AppData\Local\Temp\ipykernel_22436\409095542.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_final['tg_topic_std'] = df_tg_abs.std(axis=1)
C:\Users\Uw11\AppData\Local\Temp\ipykernel_22436\409095542.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_final['tg_topic_max'] = df_tg_abs.max(axis=1)
C:\Users\Uw11\AppData\Local\Temp\ipykernel_22436\409095542.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_final['tg_topic_entropy'] = -(df_tg_abs.div(df_tg_abs.sum(axis=1), axis=0) * np.log(df_tg_abs.div(df_tg_abs.sum(axis=1), axis=0) + 1e-9)).sum(axis=1)

In [36]:
df_final['tg_velocity_3h'] = (df_final.groupby('region_id')['tg_total_intensity'].diff(3).fillna(0))
df_final['tg_intensity_ema_6h'] = (df_final.groupby('region_id')['tg_total_intensity'].transform(lambda x: x.ewm(span=6).mean()))
df_final['tg_intensity_zscore'] = (df_final.groupby('region_id')['tg_total_intensity'].transform(lambda x: (x - x.rolling(24, min_periods=1).mean()) / (x.rolling(24, min_periods=1).std() + 1e-9)))

C:\Users\Uw11\AppData\Local\Temp\ipykernel_22436\3857173777.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_final['tg_velocity_3h'] = (df_final.groupby('region_id')['tg_total_intensity'].diff(3).fillna(0))
C:\Users\Uw11\AppData\Local\Temp\ipykernel_22436\3857173777.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_final['tg_intensity_ema_6h'] = (df_final.groupby('region_id')['tg_total_intensity'].transform(lambda x: x.ewm(span=6).mean()))
C:\Users\Uw11\AppData\Local\Temp\ipykernel_22436\3857173777.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_final['tg_intensity_zscore'] = (df_final.groupby('region_id')['tg_total_intensity'].transform(lambda x: (x - x.rolling(24, min_periods=1).mean()) / (x.rolling(24, min_periods=1).std() + 1e-9)))

In [37]:
df_final.sample(20)

,datetime_hour,region_id,city_latitude,city_longitude,day_temp,day_dew,day_humidity,day_precip,day_precipprob,day_precipcover,day_snow,day_snowdepth,day_windgust,day_windspeed,day_winddir,day_pressure,day_cloudcover,day_solarradiation,day_solarenergy,day_uvindex,day_moonphase,hour_temp,hour_feelslike,hour_humidity,hour_precip,hour_precipprob,hour_snow,hour_windgust,hour_windspeed,hour_winddir,hour_pressure,hour_cloudcover,hour_solarradiation,hour_solarenergy,hour_uvindex,day_conditions_simple_Clear,day_conditions_simple_Cloudy,day_conditions_simple_Rain,day_conditions_simple_Snow,hour_conditions_simple_Clear,hour_conditions_simple_Cloudy,hour_conditions_simple_Rain,hour_conditions_simple_Snow,year,month,day_of_week,hour,city_name,city_timezone,day_datetime,day_sunrise,day_sunset,hour_datetime,region_key,alarm_active,alarm_minutes_in_hour,alarm_lag_1,alarm_lag_3,alarm_lag_6,alarm_lag_12,alarms_in_last_24h,is_weekend,is_night,total_active_alarms_lag1,neighbour_alarms,hours_since_last_alarm,isw_topic_0,isw_topic_1,isw_topic_2,isw_topic_3,isw_topic_4,isw_topic_5,isw_topic_6,isw_topic_7,isw_topic_8,isw_topic_9,isw_topic_10,isw_topic_11,isw_topic_12,isw_topic_13,isw_topic_14,isw_topic_15,isw_topic_16,isw_topic_17,isw_topic_18,isw_topic_19,isw_topic_20,isw_topic_21,isw_topic_22,isw_topic_23,isw_topic_24,isw_topic_25,isw_topic_26,isw_topic_27,isw_topic_28,isw_topic_29,isw_topic_30,isw_topic_31,isw_topic_32,isw_topic_33,isw_topic_34,isw_topic_35,isw_topic_36,isw_topic_37,isw_topic_38,isw_topic_39,isw_topic_40,isw_topic_41,isw_topic_42,isw_topic_43,isw_topic_44,isw_topic_45,isw_topic_46,isw_topic_47,isw_topic_48,isw_topic_49,isw_topic_50,isw_topic_51,isw_topic_52,isw_topic_53,isw_topic_54,isw_topic_55,isw_topic_56,isw_topic_57,isw_topic_58,isw_topic_59,isw_topic_60,isw_topic_61,isw_topic_62,isw_topic_63,isw_topic_64,isw_topic_65,isw_topic_66,isw_topic_67,isw_topic_68,isw_topic_69,isw_topic_70,isw_topic_71,isw_topic_72,isw_topic_73,isw_topic_74,isw_topic_75,isw_topic_76,isw_topic_77,isw_topic_78,isw_topic_79,isw_topic_80,isw_topic_81,isw_topic_82,isw_topic_83,isw_topic_84,isw_topic_85,isw_topic_86,isw_topic_87,isw_topic_88,isw_topic_89,isw_topic_90,isw_topic_91,isw_topic_92,isw_topic_93,isw_topic_94,isw_topic_95,isw_topic_96,isw_topic_97,isw_topic_98,isw_topic_99,isw_topic_100,isw_topic_101,isw_topic_102,isw_topic_103,isw_topic_104,isw_topic_105,isw_topic_106,isw_topic_107,isw_topic_108,isw_topic_109,isw_topic_110,isw_topic_111,isw_topic_112,isw_topic_113,isw_topic_114,isw_topic_115,isw_topic_116,isw_topic_117,isw_topic_118,isw_topic_119,isw_topic_120,isw_topic_121,isw_topic_122,isw_topic_123,isw_topic_124,isw_topic_125,isw_topic_126,isw_topic_127,isw_topic_128,isw_topic_129,isw_topic_130,isw_topic_131,isw_topic_132,isw_topic_133,isw_topic_134,isw_topic_135,isw_topic_136,isw_topic_137,isw_topic_138,isw_topic_139,isw_topic_140,isw_topic_141,isw_topic_142,isw_topic_143,isw_topic_144,isw_topic_145,isw_topic_146,isw_topic_147,isw_topic_148,isw_topic_149,isw_total_intensity,isw_topic_std,isw_topic_max,isw_topic_mean,isw_velocity_24h,isw_intensity_ema,isw_topic_entropy,tg_topic_0,tg_topic_1,tg_topic_2,tg_topic_3,tg_topic_4,tg_topic_5,tg_topic_6,tg_topic_7,tg_topic_8,tg_topic_9,tg_topic_10,tg_topic_11,tg_topic_12,tg_topic_13,tg_topic_14,tg_topic_15,tg_topic_16,tg_topic_17,tg_topic_18,tg_topic_19,tg_topic_20,tg_topic_21,tg_topic_22,tg_topic_23,tg_topic_24,tg_topic_25,tg_topic_26,tg_topic_27,tg_topic_28,tg_topic_29,tg_topic_30,tg_topic_31,tg_topic_32,tg_topic_33,tg_topic_34,tg_topic_35,tg_topic_36,tg_topic_37,tg_topic_38,tg_topic_39,tg_topic_40,tg_topic_41,tg_topic_42,tg_topic_43,tg_topic_44,tg_topic_45,tg_topic_46,tg_topic_47,tg_topic_48,tg_topic_49,tg_topic_50,tg_topic_51,tg_topic_52,tg_topic_53,tg_topic_54,tg_topic_55,tg_topic_56,tg_topic_57,tg_topic_58,tg_topic_59,tg_topic_60,tg_topic_61,tg_topic_62,tg_topic_63,tg_topic_64,tg_topic_65,tg_topic_66,tg_topic_67,tg_topic_68,tg_topic_69,tg_topic_70,tg_topic_71,tg_topic_72,tg_topic_73,tg_topic_74,tg_topic_75,tg_topic_76,tg_topic_77,tg_topic_78,tg_topic_79,tg_topic_80,tg_topic_81,tg_topic_82,tg_topic_83,tg_topic_84,tg_topic_85,tg_topic_86,tg_topic_87,tg_topic_88,tg_topic_89,tg_topic_90,tg_topic_91,tg_topic_92,tg_topic_93,tg_topic_94,tg_topic_95,tg_topic_96,tg_topic_97,tg_topic_98,tg_topic_99,tg_topic_100,tg_topic_101,tg_topic_102,tg_topic_103,tg_topic_104,tg_topic_105,tg_topic_106,tg_topic_107,tg_topic_108,tg_topic_109,tg_topic_110,tg_topic_111,tg_topic_112,tg_topic_113,tg_topic_114,tg_topic_115,tg_topic_116,tg_topic_117,tg_topic_118,tg_topic_119,tg_topic_120,tg_topic_121,tg_topic_122,tg_topic_123,tg_topic_124,tg_topic_125,tg_topic_126,tg_topic_127,tg_topic_128,tg_topic_129,tg_topic_130,tg_topic_131,tg_topic_132,tg_topic_133,tg_topic_134,tg_topic_135,tg_topic_136,tg_topic_137,tg_topic_138,tg_topic_139,tg_topic_140,tg_topic_141,tg_topic_142,tg_topic_143,tg_topic_144,tg_topic_145,tg_topic_146,tg_topic_147,tg_topic_148,tg_topic_149,tg_topic_150,tg_topic_151,tg_topic_152,tg_topic_153,tg_topic_154,tg_topic_155,tg_topic_156,tg_topic_157,tg_topic_158,tg_topic_159,tg_topic_160,tg_topic_161,tg_topic_162,tg_topic_163,tg_topic_164,tg_topic_165,tg_topic_166,tg_topic_167,tg_topic_168,tg_topic_169,tg_topic_170,tg_topic_171,tg_topic_172,tg_topic_173,tg_topic_174,tg_topic_175,tg_topic_176,tg_topic_177,tg_topic_178,tg_topic_179,tg_topic_180,tg_topic_181,tg_topic_182,tg_topic_183,tg_topic_184,tg_topic_185,tg_topic_186,tg_topic_187,tg_topic_188,tg_topic_189,tg_topic_190,tg_topic_191,tg_topic_192,tg_topic_193,tg_topic_194,tg_topic_195,tg_topic_196,tg_topic_197,tg_topic_198,tg_topic_199,tg_topic_200,tg_topic_201,tg_topic_202,tg_topic_203,tg_topic_204,tg_topic_205,tg_topic_206,tg_topic_207,tg_topic_208,tg_topic_209,tg_topic_210,tg_topic_211,tg_topic_212,tg_topic_213,tg_topic_214,tg_topic_215,tg_topic_216,tg_topic_217,tg_topic_218,tg_topic_219,tg_topic_220,tg_topic_221,tg_topic_222,tg_topic_223,tg_topic_224,tg_topic_225,tg_topic_226,tg_topic_227,tg_topic_228,tg_topic_229,tg_topic_230,tg_topic_231,tg_topic_232,tg_topic_233,tg_topic_234,tg_topic_235,tg_topic_236,tg_topic_237,tg_topic_238,tg_topic_239,tg_topic_240,tg_topic_241,tg_topic_242,tg_topic_243,tg_topic_244,tg_topic_245,tg_topic_246,tg_topic_247,tg_topic_248,tg_topic_249,tg_total_intensity,tg_topic_std,tg_topic_max,tg_topic_entropy,tg_velocity_3h,tg_intensity_ema_6h,tg_intensity_zscore
131396,2025-01-21 11:00:00,6,50.2536,28.6654,-1.2,-1.8,96.1,0.000,0.0,0.00,0.0,0.0,27.4,14.4,142.4,1024.4,91.6,47.6,4.2,2.0,0.75,-1.6,-4.4,96.38,0.000,0.0,0.0,27.4,7.2,160.0,1025.4,100.0,133.7,0.5,1.0,False,True,False,False,False,True,False,False,2025,1,1,11,Zhytomyr,Europe/Kiev,2025-01-21,07:53:29,16:40:30,11:00:00,Житомирська,0,0.000000,0.0,0.0,0.0,0.0,4.0,0,0,3.0,0.0,7,0.763287,0.172911,-0.099689,0.027639,0.223623,0.220953,-0.138169,-0.173520,0.159807,-0.066048,-0.016635,-0.010427,-0.117902,0.074584,0.145011,0.034793,-0.077017,-0.027378,0.014876,0.001288,-0.002273,-0.001414,0.014000,0.045528,0.040207,-0.013500,-0.041370,0.034668,0.024405,0.043561,0.000577,-0.004054,0.001068,0.009608,0.084209,-0.021081,0.010300,-0.018769,0.008021,0.000083,0.036525,-0.035199,0.030801,-0.046411,-0.023040,-0.017294,-0.010986,-0.016233,-0.015425,0.028609,0.012282,0.009200,0.011044,0.004423,-0.015677,-0.015718,0.003240,-0.014046,-0.003601,-0.016061,-0.003329,-0.041492,0.017036,0.026812,0.020799,-0.023741,-0.024834,0.036740,0.038638,-0.004225,-0.007803,-0.000393,0.001600,0.009915,-0.020248,-0.008692,-0.006170,-0.008415,-0.031270,-0.004774,-0.015287,0.043553,-0.025657,0.034976,-0.022845,0.007273,-0.023355,-0.011182,0.011988,-0.000991,0.013788,-0.024076,-0.038482,-0.014088,0.019733,-0.020567,0.004792,-0.001444,0.010005,-0.007649,0.012127,0.016855,-0.015082,-0.004442,0.002493,-0.018525,0.007099,-0.016304,-0.012630,-0.009339,-0.025248,0.012352,-0.002732,-0.024609,-0.015263,-0.011396,-0.006988,0.023886,0.007568,-0.019741,0.022730,-0.010540,-0.029506,0.019918,-0.033618,0.019965,0.014808,-0.007997,0.011469,0.008907,0.003695,0.019057,-0.021776,0.010229,-0.000241,-0.003670,0.023067,0.015388,-0.015061,0.004552,-0.003522,0.012515,-0.009345,-0.004987,0.004476,0.007346,0.008459,-0.008792,0.019019,0.003266,4.681330,0.071419,0.763287,0.031209,0.136602,4.636075,4.103623,0.210297,-0.275916,-0.081571,0.326446,-0.102227,-0.002155,-0.155630,-0.103641,0.034864,-0.015041,0.016488,0.018054,0.001628,-0.030804,-0.020769,0.006139,-0.005340,-0.043135,0.017383,-0.021582,-0.009112,0.015989,-0.070826,-0.023677,0.045447,-0.029738,-0.025898,0.036081,0.001321,0.013336,-0.032227,0.005455,0.006761,0.005060,0.002474,-0.016284,0.002473,0.005989,0.009532,0.002014,0.010881,0.015692,0.004114,-0.009888,-0.016973,-0.002193,0.004773,0.002220,0.009845,-0.006335,0.000472,0.007685,0.006740,-0.001429,0.000969,0.008812,0.028469,0.004039,-0.011786,-0.015121,0.011879,-0.012223,0.005380,-0.022145,0.004795,-0.012566,0.016439,-0.012458,0.030498,0.018668,0.034871,0.063212,-0.045922,0.095295,-0.007982,0.016666,-0.007959,-0.000690,0.004492,-0.047047,-0.004490,0.021994,0.019885,0.023264,0.008239,-0.043091,0.004319,0.001459,-0.040972,-0.001105,-0.012184,0.037038,-0.038365,-0.007545,-0.009246,-0.010066,-0.021608,-0.010878,0.001816,0.040454,-0.023617,-0.009831,0.007022,-0.011603,-0.001325,0.047569,0.021994,-0.018604,-0.007122,-0.007592,-0.006960,-0.002957,-0.004272,-0.009307,0.000502,0.017076,0.015845,-0.002391,-0.004425,0.006969,-0.000880,-0.008723,0.004573,-0.017440,0.021251,0.000509,0.031715,-0.002251,-0.003798,-0.001443,-0.011362,-0.011499,0.000978,0.003373,0.028789,-0.006505,-0.001143,0.006752,0.023992,0.000641,-0.017328,-0.028101,-0.024714,0.000013,-0.008622,-0.004296,-0.002822,0.041207,0.001176,0.011213,0.002796,0.000974,-0.020110,-0.008946,0.012385,0.018954,0.005399,-0.009592,-0.013802,-0.007675,-0.013570,-0.012587,-0.007164,0.027215,0.007445,0.002458,-0.000294,0.013117,-0.021970,0.021453,0.005699,0.018862,0.014608,0.032821,-0.004296,0.004073,-0.007820,-0.009303,0.013925,0.002964,0.008109,-0.005687,0.018658,0.004104,-0.008770,-0.008871,-0.002684,-0.000395,0.020460,0.006531,0.002580,0.004570,0.011201,-0.002065,-0.012996,-0.011396,-0.010485,0.010227,-0.009893,-0.006359,-0.025105,-0.002935,0.002126,-0.001306,0.000640,-0.007540,-0.013095,0.007728,-0.000689,-0.019105,-0.014049,0.004412,0.014980,-0.000332,-0.005618,0.004724,0.018849,-0.008373,0.001973,0.023314,0.032303,0.013042,0.006063,0.003756,0.022972,0.008315,0.012977,0.006566,0.001153,-0.006866,-0.010494,-0.007578,0.025353,-0.012945,-0.002240,0.000389,0.001395,-0.001085,-0.004015,0.013361,-0.004980,0.007057,-0.008135,-0.009895,0.008426,-0.002722,0.011144,-0.003243,-0.002148,0.019391,4.355756,0.033713,0.326446,4.743155,0.793070,4.366133,-0.262790
213134,2022-04-21 15:00:00,10,50.4506,30.5243,6.1,3.2,82.6,0.500,100.0,4.17,0.0,0.0,29.2,12.6,176.1,1010.2,92.1,47.1,4.1,2.0,0.66,6.7,4.5,82.32,0.000,0.0,0.0,28.1,10.8,150.0,1010.4,100.0,153.0,0.6,2.0,False,False,True,False,False,True,False,False,2022,4,3,15,Kyiv,Europe/Kiev,2022-04-21,05:52:23,20:01:59,15:00:00,Київська,0,0.000000,0.0,0.0,0.0,0.0,3.0,0,0,4.0,0.0,15,0.592519,-0.174689,0.347811,0.224748,0.061515,-0.099087,-0.010491,-0.092800,-0.049100,-0.088047,0.127506,-0.033828,0.001652,0.008318,0.034528,-0.072152,0.141507,-0.124814,0.104593,-0.115749,0.038042,0.047625,0.103797,0.103052,-0.068376,-0.029853,-0.161714,-0.116531,-0.021201,-0.013068,-0.061698,-0.012127,0.017916,0.027448,-0.030578,-0.016431,-0.016208,0.069385,0.011014,0.011479,-0.008524,-0.020405,-0.049782,0.001576,0.019055,0.002784,-0.007464,0.060052,0.022559,-0.008686,-0.027657,0.027259,0.004162,0.019453,0.019695,0.058298,0.043577,0.003568,0.023212,0.004011,0.053927,-0.048044,-0.031597,0.011051,-0.003339,0.001696,0.071191,0.061835,-0.003546,0.052662,0.022817,0.039964,0.023662,-0.012329,0.001120,-0.049354,0.004927,-0.061806,-0.015464,0.039394,0.021543,0.008626,0.059256,-0.029758,-0.009708,0.036709,0.022461,0.071838,0.074691,0.042886,-0.001275,-0.026622,0.011132,0.018549,-0.031148,-0.021628,0.075133,0.034042,-0.022785,0.018674,-0.003403,0.001627,0.024690,-0.003213,-0.031353,0.008429,-0.024998,-0.003925,0.021715,-0.012182,-0.011306,0.026792,-0.021350,0.012433,0.038457,0.013753,0.037322,0.000330,-0.046531,-0.010227,0.037192,0.035481,0.033157,-0.002495,-0.024629,0.021064,0.026455,0.034918,-0.000708,-0.001368,0.038546,0.014773,0.000994,-0.004021,0.049882,0.028823,0.028306,0.011058,0.002187,-0.006083,0.017509,-0.019684,0.010469,0.022138,0.037293,-0.068848,0.004278,-0.047774,0.017952,0.021319,6.186404,0.063680,0.592519,0.041243,0.386126,6.052858,4.392419,0.009970,0.001644,0.022875,-0.000670,-0.025539,0.037880,-0.044781,0.042762,-0.019061,0.032255,-0.036522,0.002426,-0.008981,0.013099,0.021855,-0.024993,-0.001741,-0.018192,-0.018715,0.020631,-0.005515,0.005474,-0.004768,-0.009241,-0.006307,0.005933,-0.002779,0.006035,0.006682,0.013626,0.016402,0.006091,-0.001107,-0.000085,-0.000149,0.002803,0.006536,-0.003224,-0.005184,0.008781,-0.001140,-0.000617,-0.006060,0.000188,0.006983,0.008747,0.004611,0.007173,0.006740,-0.003412,-0.011590,0.006162,0.005187,0.001852,0.005421,-0.005934,-0.001413,-0.003906,-0.003192,-0.003710,0.005488,0.004650,-0.003697,0.017775,-0.009670,-0.001106,0.004074,-0.015306,0.002391,-0.001746,0.000610,-0.003590,0.000883,-0.006360,-0.019485,0.007602,0.006955,0.005202,0.002147,-0.000638,-0.001919,0.001298,-0.002219,-0.000408,0.003075,-0.001803,0.000707,-0.009798,-0.000164,0.005608,0.001273,-0.007317,0.007715,0.007567,-0.000761,-0.002821,-0.001641,-0.003060,-0.007425,0.020087,0.005745,-0.008839,0.005121,-0.004582,-0.012588,-0.003166,-0.011501,-0.010169,-0.010674,0.006406,-0.000610,-0.005195,0.006951,0.001755,0.000570,-0.003919,0.003437,0.002142,-0.008377,0.007075,-0.004681,-0.003818,-0.002430,-0.004489,-0.007150,0.006297,0.004424,0.005388,0.000623,0.000102,0.006260,-0.000606,-0.003713,0.012645,0.000172,-0.000431,-0.002277,-0.000161,-0.002290,0.008291,-0.006096,-0.004425,-0.003509,-0.006335,0.014500,0.002334,0.004880,-0.006067,0.000027,0.003257,-0.001377,0.000909,-0.001115,0.010830,-0.003531,0.002322,0.003453,0.003870,0.004023,-0.002346,0.000512,0.001909,-0.017683,-0.006513,-0.024945,0.005104,-0.005134,-0.005674,-0.010867,0.004828,-0.003827,0.003289,0.000225,-0.008503,-0.007970,0.020981,0.020535,-0.011649,0.001533,-0.000223,0.009473,0.006228,-0.009370,0.008398,0.000041,0.007228,0.015103,-0.006389,0.005878,-0.000503,-0.015385,0.019524,-0.002112,0.004237,-0.020712,0.007206,-0.015051,-0.012931,-0.003299,0.007635,-0.003492,0.001111,0.005155,-0.009008,0.006399,-0.025040,-0.001966,-0.003854,0.011172,0.013797,-0.008886,-0.014078,-0.010305,-0.008856,0.008148,-0.001024,-0.009422,-0.005806,0.001924,-0.011674,0.010666,0.005785,-0.016786,-0.011101,-0.006487,0.002712,0.003159,-0.010197,-0.011187,-0.014523,-0.003212,0.010629,0.006800,-0.004334,0.004837,0.006563,-0.015063,-0.025668,-0.003166,0.005894,0.007433,-0.011784,-0.001943,0.002686,-0.016256,-0.005435,0.003482,-0.000672,-0.001421,0.004462,1.835739,0.007305,0.044781,5.120798,-0.761447,2.253185,-0.376375
538936,2023-03-28 06:00:00,23,49.4407,32.0637,7.3,4.8,85.1,15.300,100.0,79.17,0.0,0.0,57.2,28.8,138.9,997.4,99.8,33.4,2.7,1.0,0.21,8.6,5.7,78.10,0.100,100.0,0.0,29.9,18.7,117.5,999.0,99.2,0.0,0.0,0.0,False,False,False,True,False,False,True,False,2023,3,1,6,Cherkasy,Europe/Kiev,2023-03-28,06:38:24,19:16:25,06:00:00,Черкаська,0,0.000000,1.0,0.0,0.0,0.0,2.0,0,1,11.0,2.0,0,0.765453,-0.237281,-0.109835,0.077711,0.050554,-0.017267,-0.070388,0.185353,-0.014949,0.145103,-0.031672,-0.023214,-0.101003,0.059535,0.015585,0.089729,0.017269,-0.067222,-0.164084,-0.051120,-0.010170,0.017032,-0.013719,-0.038182,-0.024320,-0.026787,-0.041934,-0.060943,0.012300,-0.009922,-0.025959,-0.037280,-0.011959,-0.021337,-0.002243,0.026129,0.037778,0.016457,0.038149,-0.017597,-0.026638,-0.015014,-0.001701,-0.001993,0.037900,-0.016935,0.027202,0.000240,-0.007284,-0.009292,0.016836,-0.004677,0.018147,0.034675,-0.013261,-0.043766,0.022341,-0.011595,-0.044143,-0.003109,-0.002836,0.003127,-0.026548,0.000912,0.029698,-0.033065,-0.017944,0.005422,-0.028210,0.003262,-0.007272,0.009476,-0.013171,0.039379,0.024483,-0.038678,-0.060509,0.017122,-0.042450,-0.018463,0.000933,0.009548,0.019087,-0.018428,-0.004543,0.013959,-0.012231,-0.049509,0.052675,-0.023051,0.000404,-0.009282,-0.004037,0.015714,0.035397,0.037079,0.016749,0.010351,-0.011311,-0.032344,-0.021717,0.001310,-0.052556,-0.034486,-0.062399,0.003093,-0.045749,-0.005248,0.006180,0.004404,0.017709,-0.036457,-0.032570,0.008610,-0.014066,-0.016278,-0.014877,0.016353,0.028398,0.008894,-0.015248,0.005548,0.002520,-0.019115,0.010841,0.025879,0.020188,0.012069,-0.014300,-0.006834,0.003017,0.006520,0.039154,0.008569,0.041263,-0.026031,-0.021354,0.004523,0.014715,0.009924,-0.011781,-0.005136,0.027015,0.000867,-0.044251,-0.004607,-0.029557,0.026317,0.000504,-0.001213,4.830150,0.068743,0.765453,0.032201,-0.415224,5.233328,4.238899,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-0.000000,0.000000,1.276696,-1.201476

In [38]:
df_final.to_parquet("merged_dataset.parquet", index=False, engine="pyarrow")

# ТУТ БУДЕ EDA

## Weather, ISW, Telegram shift for further models trainings

In [39]:
df_to_train = df_final.copy()
df_to_train = df_to_train.sort_values(['region_id', 'datetime_hour'])

In [40]:
# delete unnessecary columns
columns_to_delete = ['city_latitude', 'city_longitude', 'day_temp', 'day_dew', 'day_humidity', 'day_precip', 'day_precipprob', 'day_precipcover', 
                     'day_snow', 'day_snowdepth', 'day_windgust', 'day_windspeed', 'day_winddir', 'day_pressure', 'day_cloudcover', 'day_solarradiation',
                     'day_solarenergy', 'day_uvindex', 'day_moonphase', 'day_conditions_simple_Clear', 'day_conditions_simple_Cloudy', 'day_conditions_simple_Rain',
                     'day_conditions_simple_Snow', 'year', 'month', 'hour', 'day_of_week', 'city_timezone', 'day_datetime', 'hour_datetime', 'region_key']
df_to_train = df_to_train.drop(columns=columns_to_delete)

In [41]:
isw_cols = [c for c in df_to_train.columns if 'isw_' in c]
df_to_train[isw_cols] = df_to_train.groupby('region_id')[isw_cols].shift(24).fillna(0)

In [42]:
df_to_train.head()

,datetime_hour,region_id,hour_temp,hour_feelslike,hour_humidity,hour_precip,hour_precipprob,hour_snow,hour_windgust,hour_windspeed,hour_winddir,hour_pressure,hour_cloudcover,hour_solarradiation,hour_solarenergy,hour_uvindex,hour_conditions_simple_Clear,hour_conditions_simple_Cloudy,hour_conditions_simple_Rain,hour_conditions_simple_Snow,city_name,day_sunrise,day_sunset,alarm_active,alarm_minutes_in_hour,alarm_lag_1,alarm_lag_3,alarm_lag_6,alarm_lag_12,alarms_in_last_24h,is_weekend,is_night,total_active_alarms_lag1,neighbour_alarms,hours_since_last_alarm,isw_topic_0,isw_topic_1,isw_topic_2,isw_topic_3,isw_topic_4,isw_topic_5,isw_topic_6,isw_topic_7,isw_topic_8,isw_topic_9,isw_topic_10,isw_topic_11,isw_topic_12,isw_topic_13,isw_topic_14,isw_topic_15,isw_topic_16,isw_topic_17,isw_topic_18,isw_topic_19,isw_topic_20,isw_topic_21,isw_topic_22,isw_topic_23,isw_topic_24,isw_topic_25,isw_topic_26,isw_topic_27,isw_topic_28,isw_topic_29,isw_topic_30,isw_topic_31,isw_topic_32,isw_topic_33,isw_topic_34,isw_topic_35,isw_topic_36,isw_topic_37,isw_topic_38,isw_topic_39,isw_topic_40,isw_topic_41,isw_topic_42,isw_topic_43,isw_topic_44,isw_topic_45,isw_topic_46,isw_topic_47,isw_topic_48,isw_topic_49,isw_topic_50,isw_topic_51,isw_topic_52,isw_topic_53,isw_topic_54,isw_topic_55,isw_topic_56,isw_topic_57,isw_topic_58,isw_topic_59,isw_topic_60,isw_topic_61,isw_topic_62,isw_topic_63,isw_topic_64,isw_topic_65,isw_topic_66,isw_topic_67,isw_topic_68,isw_topic_69,isw_topic_70,isw_topic_71,isw_topic_72,isw_topic_73,isw_topic_74,isw_topic_75,isw_topic_76,isw_topic_77,isw_topic_78,isw_topic_79,isw_topic_80,isw_topic_81,isw_topic_82,isw_topic_83,isw_topic_84,isw_topic_85,isw_topic_86,isw_topic_87,isw_topic_88,isw_topic_89,isw_topic_90,isw_topic_91,isw_topic_92,isw_topic_93,isw_topic_94,isw_topic_95,isw_topic_96,isw_topic_97,isw_topic_98,isw_topic_99,isw_topic_100,isw_topic_101,isw_topic_102,isw_topic_103,isw_topic_104,isw_topic_105,isw_topic_106,isw_topic_107,isw_topic_108,isw_topic_109,isw_topic_110,isw_topic_111,isw_topic_112,isw_topic_113,isw_topic_114,isw_topic_115,isw_topic_116,isw_topic_117,isw_topic_118,isw_topic_119,isw_topic_120,isw_topic_121,isw_topic_122,isw_topic_123,isw_topic_124,isw_topic_125,isw_topic_126,isw_topic_127,isw_topic_128,isw_topic_129,isw_topic_130,isw_topic_131,isw_topic_132,isw_topic_133,isw_topic_134,isw_topic_135,isw_topic_136,isw_topic_137,isw_topic_138,isw_topic_139,isw_topic_140,isw_topic_141,isw_topic_142,isw_topic_143,isw_topic_144,isw_topic_145,isw_topic_146,isw_topic_147,isw_topic_148,isw_topic_149,isw_total_intensity,isw_topic_std,isw_topic_max,isw_topic_mean,isw_velocity_24h,isw_intensity_ema,isw_topic_entropy,tg_topic_0,tg_topic_1,tg_topic_2,tg_topic_3,tg_topic_4,tg_topic_5,tg_topic_6,tg_topic_7,tg_topic_8,tg_topic_9,tg_topic_10,tg_topic_11,tg_topic_12,tg_topic_13,tg_topic_14,tg_topic_15,tg_topic_16,tg_topic_17,tg_topic_18,tg_topic_19,tg_topic_20,tg_topic_21,tg_topic_22,tg_topic_23,tg_topic_24,tg_topic_25,tg_topic_26,tg_topic_27,tg_topic_28,tg_topic_29,tg_topic_30,tg_topic_31,tg_topic_32,tg_topic_33,tg_topic_34,tg_topic_35,tg_topic_36,tg_topic_37,tg_topic_38,tg_topic_39,tg_topic_40,tg_topic_41,tg_topic_42,tg_topic_43,tg_topic_44,tg_topic_45,tg_topic_46,tg_topic_47,tg_topic_48,tg_topic_49,tg_topic_50,tg_topic_51,tg_topic_52,tg_topic_53,tg_topic_54,tg_topic_55,tg_topic_56,tg_topic_57,tg_topic_58,tg_topic_59,tg_topic_60,tg_topic_61,tg_topic_62,tg_topic_63,tg_topic_64,tg_topic_65,tg_topic_66,tg_topic_67,tg_topic_68,tg_topic_69,tg_topic_70,tg_topic_71,tg_topic_72,tg_topic_73,tg_topic_74,tg_topic_75,tg_topic_76,tg_topic_77,tg_topic_78,tg_topic_79,tg_topic_80,tg_topic_81,tg_topic_82,tg_topic_83,tg_topic_84,tg_topic_85,tg_topic_86,tg_topic_87,tg_topic_88,tg_topic_89,tg_topic_90,tg_topic_91,tg_topic_92,tg_topic_93,tg_topic_94,tg_topic_95,tg_topic_96,tg_topic_97,tg_topic_98,tg_topic_99,tg_topic_100,tg_topic_101,tg_topic_102,tg_topic_103,tg_topic_104,tg_topic_105,tg_topic_106,tg_topic_107,tg_topic_108,tg_topic_109,tg_topic_110,tg_topic_111,tg_topic_112,tg_topic_113,tg_topic_114,tg_topic_115,tg_topic_116,tg_topic_117,tg_topic_118,tg_topic_119,tg_topic_120,tg_topic_121,tg_topic_122,tg_topic_123,tg_topic_124,tg_topic_125,tg_topic_126,tg_topic_127,tg_topic_128,tg_topic_129,tg_topic_130,tg_topic_131,tg_topic_132,tg_topic_133,tg_topic_134,tg_topic_135,tg_topic_136,tg_topic_137,tg_topic_138,tg_topic_139,tg_topic_140,tg_topic_141,tg_topic_142,tg_topic_143,tg_topic_144,tg_topic_145,tg_topic_146,tg_topic_147,tg_topic_148,tg_topic_149,tg_topic_150,tg_topic_151,tg_topic_152,tg_topic_153,tg_topic_154,tg_topic_155,tg_topic_156,tg_topic_157,tg_topic_158,tg_topic_159,tg_topic_160,tg_topic_161,tg_topic_162,tg_topic_163,tg_topic_164,tg_topic_165,tg_topic_166,tg_topic_167,tg_topic_168,tg_topic_169,tg_topic_170,tg_topic_171,tg_topic_172,tg_topic_173,tg_topic_174,tg_topic_175,tg_topic_176,tg_topic_177,tg_topic_178,tg_topic_179,tg_topic_180,tg_topic_181,tg_topic_182,tg_topic_183,tg_topic_184,tg_topic_185,tg_topic_186,tg_topic_187,tg_topic_188,tg_topic_189,tg_topic_190,tg_topic_191,tg_topic_192,tg_topic_193,tg_topic_194,tg_topic_195,tg_topic_196,tg_topic_197,tg_topic_198,tg_topic_199,tg_topic_200,tg_topic_201,tg_topic_202,tg_topic_203,tg_topic_204,tg_topic_205,tg_topic_206,tg_topic_207,tg_topic_208,tg_topic_209,tg_topic_210,tg_topic_211,tg_topic_212,tg_topic_213,tg_topic_214,tg_topic_215,tg_topic_216,tg_topic_217,tg_topic_218,tg_topic_219,tg_topic_220,tg_topic_221,tg_topic_222,tg_topic_223,tg_topic_224,tg_topic_225,tg_topic_226,tg_topic_227,tg_topic_228,tg_topic_229,tg_topic_230,tg_topic_231,tg_topic_232,tg_topic_233,tg_topic_234,tg_topic_235,tg_topic_236,tg_topic_237,tg_topic_238,tg_topic_239,tg_topic_240,tg_topic_241,tg_topic_242,tg_topic_243,tg_topic_244,tg_topic_245,tg_topic_246,tg_topic_247,tg_topic_248,tg_topic_249,tg_total_intensity,tg_topic_std,tg_topic_max,tg_topic_entropy,tg_velocity_3h,tg_intensity_ema_6h,tg_intensity_zscore
0,2022-02-24 00:00:00,2,2.1,-0.5,91.76,0.0,0.0,0.0,16.6,8.6,279.6,1021.0,91.1,0.0,0.1,0.0,False,True,False,False,Vinnytsia,06:58:49,17:40:52,0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0.0,0.0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-0.0,0.0,0.0,NaN
1,2022-02-24 00:00:00,2,2.1,-0.5,91.76,0.0,0.0,0.0,16.6,8.6,279.6,1021.0,91.1,0.0,0.1,0.0,False,True,False,False,Vinnytsia,06:58:49,17:40:52,0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0.0,0.0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-0.0,0.0,0.0,0.0
3,2022-02-24 01:00:00,2,2.1,-0.4,89.80,0.0,0.0,0.0,16.6,8.3,289.2,1021.0,97.9,0.0,0.1,0.0,False,True,False,False,Vinnytsia,06:58:49,17:40:52,0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0.0,0.0,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-0.0,0.0,0.0,0.0
2,2022-02-24 01:00:00,2,2.1,-0.4,89.80,0.0,0.0,0.0,16.6,8.3,289.2,1021.0,97.9,0.0,0.1,0.0,False,True,False,False,Vinnytsia,06:58:49,17:40:52,0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0.0,0.0,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-0.0,0.0,0.0,0.0
5,2022-02-24 02:00:00,2,2.0,-0.3,90.44,0.0,0.0,0.0,27.7,7.6,287.6,1021.0,98.2,0.0,0.1,0.0,False,True,False,False,Vinnytsia,06:58:49,17:40:52,0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0.0,0.0,3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-0.0,0.0,0.0,0.0

In [43]:
tg_cols = [c for c in df_to_train.columns if 'tg_' in c]
df_to_train[tg_cols] = df_to_train.groupby('region_id')[tg_cols].shift(1).fillna(0)

In [44]:
hour_weather_cols = [c for c in df_to_train.columns if c.startswith('hour_')]
df_to_train[hour_weather_cols] = (df_to_train.groupby('region_id')[hour_weather_cols].shift(1).fillna(0))

In [46]:
df_to_train.isna().sum()

datetime_hour          0
region_id              0
hour_temp              0
hour_feelslike         0
hour_humidity          0
                      ..
tg_topic_max           0
tg_topic_entropy       0
tg_velocity_3h         0
tg_intensity_ema_6h    0
tg_intensity_zscore    0
Length: 449, dtype: int64

In [47]:
df_to_train['alarm_minutes_in_hour'] = (df_to_train.groupby('region_id')['alarm_minutes_in_hour'].shift(1).fillna(0))

In [48]:
df_to_train.head()

,datetime_hour,region_id,hour_temp,hour_feelslike,hour_humidity,hour_precip,hour_precipprob,hour_snow,hour_windgust,hour_windspeed,hour_winddir,hour_pressure,hour_cloudcover,hour_solarradiation,hour_solarenergy,hour_uvindex,hour_conditions_simple_Clear,hour_conditions_simple_Cloudy,hour_conditions_simple_Rain,hour_conditions_simple_Snow,city_name,day_sunrise,day_sunset,alarm_active,alarm_minutes_in_hour,alarm_lag_1,alarm_lag_3,alarm_lag_6,alarm_lag_12,alarms_in_last_24h,is_weekend,is_night,total_active_alarms_lag1,neighbour_alarms,hours_since_last_alarm,isw_topic_0,isw_topic_1,isw_topic_2,isw_topic_3,isw_topic_4,isw_topic_5,isw_topic_6,isw_topic_7,isw_topic_8,isw_topic_9,isw_topic_10,isw_topic_11,isw_topic_12,isw_topic_13,isw_topic_14,isw_topic_15,isw_topic_16,isw_topic_17,isw_topic_18,isw_topic_19,isw_topic_20,isw_topic_21,isw_topic_22,isw_topic_23,isw_topic_24,isw_topic_25,isw_topic_26,isw_topic_27,isw_topic_28,isw_topic_29,isw_topic_30,isw_topic_31,isw_topic_32,isw_topic_33,isw_topic_34,isw_topic_35,isw_topic_36,isw_topic_37,isw_topic_38,isw_topic_39,isw_topic_40,isw_topic_41,isw_topic_42,isw_topic_43,isw_topic_44,isw_topic_45,isw_topic_46,isw_topic_47,isw_topic_48,isw_topic_49,isw_topic_50,isw_topic_51,isw_topic_52,isw_topic_53,isw_topic_54,isw_topic_55,isw_topic_56,isw_topic_57,isw_topic_58,isw_topic_59,isw_topic_60,isw_topic_61,isw_topic_62,isw_topic_63,isw_topic_64,isw_topic_65,isw_topic_66,isw_topic_67,isw_topic_68,isw_topic_69,isw_topic_70,isw_topic_71,isw_topic_72,isw_topic_73,isw_topic_74,isw_topic_75,isw_topic_76,isw_topic_77,isw_topic_78,isw_topic_79,isw_topic_80,isw_topic_81,isw_topic_82,isw_topic_83,isw_topic_84,isw_topic_85,isw_topic_86,isw_topic_87,isw_topic_88,isw_topic_89,isw_topic_90,isw_topic_91,isw_topic_92,isw_topic_93,isw_topic_94,isw_topic_95,isw_topic_96,isw_topic_97,isw_topic_98,isw_topic_99,isw_topic_100,isw_topic_101,isw_topic_102,isw_topic_103,isw_topic_104,isw_topic_105,isw_topic_106,isw_topic_107,isw_topic_108,isw_topic_109,isw_topic_110,isw_topic_111,isw_topic_112,isw_topic_113,isw_topic_114,isw_topic_115,isw_topic_116,isw_topic_117,isw_topic_118,isw_topic_119,isw_topic_120,isw_topic_121,isw_topic_122,isw_topic_123,isw_topic_124,isw_topic_125,isw_topic_126,isw_topic_127,isw_topic_128,isw_topic_129,isw_topic_130,isw_topic_131,isw_topic_132,isw_topic_133,isw_topic_134,isw_topic_135,isw_topic_136,isw_topic_137,isw_topic_138,isw_topic_139,isw_topic_140,isw_topic_141,isw_topic_142,isw_topic_143,isw_topic_144,isw_topic_145,isw_topic_146,isw_topic_147,isw_topic_148,isw_topic_149,isw_total_intensity,isw_topic_std,isw_topic_max,isw_topic_mean,isw_velocity_24h,isw_intensity_ema,isw_topic_entropy,tg_topic_0,tg_topic_1,tg_topic_2,tg_topic_3,tg_topic_4,tg_topic_5,tg_topic_6,tg_topic_7,tg_topic_8,tg_topic_9,tg_topic_10,tg_topic_11,tg_topic_12,tg_topic_13,tg_topic_14,tg_topic_15,tg_topic_16,tg_topic_17,tg_topic_18,tg_topic_19,tg_topic_20,tg_topic_21,tg_topic_22,tg_topic_23,tg_topic_24,tg_topic_25,tg_topic_26,tg_topic_27,tg_topic_28,tg_topic_29,tg_topic_30,tg_topic_31,tg_topic_32,tg_topic_33,tg_topic_34,tg_topic_35,tg_topic_36,tg_topic_37,tg_topic_38,tg_topic_39,tg_topic_40,tg_topic_41,tg_topic_42,tg_topic_43,tg_topic_44,tg_topic_45,tg_topic_46,tg_topic_47,tg_topic_48,tg_topic_49,tg_topic_50,tg_topic_51,tg_topic_52,tg_topic_53,tg_topic_54,tg_topic_55,tg_topic_56,tg_topic_57,tg_topic_58,tg_topic_59,tg_topic_60,tg_topic_61,tg_topic_62,tg_topic_63,tg_topic_64,tg_topic_65,tg_topic_66,tg_topic_67,tg_topic_68,tg_topic_69,tg_topic_70,tg_topic_71,tg_topic_72,tg_topic_73,tg_topic_74,tg_topic_75,tg_topic_76,tg_topic_77,tg_topic_78,tg_topic_79,tg_topic_80,tg_topic_81,tg_topic_82,tg_topic_83,tg_topic_84,tg_topic_85,tg_topic_86,tg_topic_87,tg_topic_88,tg_topic_89,tg_topic_90,tg_topic_91,tg_topic_92,tg_topic_93,tg_topic_94,tg_topic_95,tg_topic_96,tg_topic_97,tg_topic_98,tg_topic_99,tg_topic_100,tg_topic_101,tg_topic_102,tg_topic_103,tg_topic_104,tg_topic_105,tg_topic_106,tg_topic_107,tg_topic_108,tg_topic_109,tg_topic_110,tg_topic_111,tg_topic_112,tg_topic_113,tg_topic_114,tg_topic_115,tg_topic_116,tg_topic_117,tg_topic_118,tg_topic_119,tg_topic_120,tg_topic_121,tg_topic_122,tg_topic_123,tg_topic_124,tg_topic_125,tg_topic_126,tg_topic_127,tg_topic_128,tg_topic_129,tg_topic_130,tg_topic_131,tg_topic_132,tg_topic_133,tg_topic_134,tg_topic_135,tg_topic_136,tg_topic_137,tg_topic_138,tg_topic_139,tg_topic_140,tg_topic_141,tg_topic_142,tg_topic_143,tg_topic_144,tg_topic_145,tg_topic_146,tg_topic_147,tg_topic_148,tg_topic_149,tg_topic_150,tg_topic_151,tg_topic_152,tg_topic_153,tg_topic_154,tg_topic_155,tg_topic_156,tg_topic_157,tg_topic_158,tg_topic_159,tg_topic_160,tg_topic_161,tg_topic_162,tg_topic_163,tg_topic_164,tg_topic_165,tg_topic_166,tg_topic_167,tg_topic_168,tg_topic_169,tg_topic_170,tg_topic_171,tg_topic_172,tg_topic_173,tg_topic_174,tg_topic_175,tg_topic_176,tg_topic_177,tg_topic_178,tg_topic_179,tg_topic_180,tg_topic_181,tg_topic_182,tg_topic_183,tg_topic_184,tg_topic_185,tg_topic_186,tg_topic_187,tg_topic_188,tg_topic_189,tg_topic_190,tg_topic_191,tg_topic_192,tg_topic_193,tg_topic_194,tg_topic_195,tg_topic_196,tg_topic_197,tg_topic_198,tg_topic_199,tg_topic_200,tg_topic_201,tg_topic_202,tg_topic_203,tg_topic_204,tg_topic_205,tg_topic_206,tg_topic_207,tg_topic_208,tg_topic_209,tg_topic_210,tg_topic_211,tg_topic_212,tg_topic_213,tg_topic_214,tg_topic_215,tg_topic_216,tg_topic_217,tg_topic_218,tg_topic_219,tg_topic_220,tg_topic_221,tg_topic_222,tg_topic_223,tg_topic_224,tg_topic_225,tg_topic_226,tg_topic_227,tg_topic_228,tg_topic_229,tg_topic_230,tg_topic_231,tg_topic_232,tg_topic_233,tg_topic_234,tg_topic_235,tg_topic_236,tg_topic_237,tg_topic_238,tg_topic_239,tg_topic_240,tg_topic_241,tg_topic_242,tg_topic_243,tg_topic_244,tg_topic_245,tg_topic_246,tg_topic_247,tg_topic_248,tg_topic_249,tg_total_intensity,tg_topic_std,tg_topic_max,tg_topic_entropy,tg_velocity_3h,tg_intensity_ema_6h,tg_intensity_zscore
0,2022-02-24 00:00:00,2,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0,0,Vinnytsia,06:58:49,17:40:52,0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0.0,0.0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2022-02-24 00:00:00,2,2.1,-0.5,91.76,0.0,0.0,0.0,16.6,8.6,279.6,1021.0,91.1,0.0,0.1,0.0,False,True,False,False,Vinnytsia,06:58:49,17:40:52,0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0.0,0.0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-0.0,0.0,0.0,0.0
3,2022-02-24 01:00:00,2,2.1,-0.5,91.76,0.0,0.0,0.0,16.6,8.6,279.6,1021.0,91.1,0.0,0.1,0.0,False,True,False,False,Vinnytsia,06:58:49,17:40:52,0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0.0,0.0,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-0.0,0.0,0.0,0.0
2,2022-02-24 01:00:00,2,2.1,-0.4,89.80,0.0,0.0,0.0,16.6,8.3,289.2,1021.0,97.9,0.0,0.1,0.0,False,True,False,False,Vinnytsia,06:58:49,17:40:52,0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0.0,0.0,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-0.0,0.0,0.0,0.0
5,2022-02-24 02:00:00,2,2.1,-0.4,89.80,0.0,0.0,0.0,16.6,8.3,289.2,1021.0,97.9,0.0,0.1,0.0,False,True,False,False,Vinnytsia,06:58:49,17:40:52,0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0.0,0.0,3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-0.0,0.0,0.0,0.0