# Data merge and feature engineering

In [1]:
%pip install pyarrow

Requirement already satisfied: pyarrow in c:\users\uw11\appdata\local\programs\python\python313\lib\site-packages (23.0.1)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.3.1 -> 26.0.1
[notice] To update, run: C:\Users\Uw11\AppData\Local\Programs\Python\Python313\python.exe -m pip install --upgrade pip

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import string

import re
import nltk
from nltk.stem import WordNetLemmatizer
from nltk.corpus import stopwords
from sklearn.feature_extraction.text import TfidfVectorizer
from tqdm.notebook import tqdm
from tqdm import tqdm
import pymorphy3
from collections import Counter

import os
from pathlib import Path
import json

In [3]:
df_weather = pd.read_csv("../data/weather_processed.csv")
df_war_events = pd.read_csv("../data/war_events_processed.csv")
df_isw_matrix = pd.read_csv("../data/isw_processed_svd.csv")

In [4]:
df_weather.shape

(844417, 40)

In [5]:
df_war_events.tail()

,datetime_hour,region_id,region_key,alarm_minutes_in_hour,alarm_active
924659,2026-03-16 23:00:00,22,Хмельницька,0.000000,0
924660,2026-03-16 23:00:00,23,Черкаська,0.000000,0
924661,2026-03-16 23:00:00,24,Чернівецька,0.000000,0
924662,2026-03-16 23:00:00,25,Чернігівська,60.000000,1
924663,2026-03-16 23:00:00,26,Київ,17.216667,1

In [6]:
df_isw_matrix.tail()

,date,isw_topic_0,isw_topic_1,isw_topic_2,isw_topic_3,isw_topic_4,isw_topic_5,isw_topic_6,isw_topic_7,isw_topic_8,...,isw_topic_140,isw_topic_141,isw_topic_142,isw_topic_143,isw_topic_144,isw_topic_145,isw_topic_146,isw_topic_147,isw_topic_148,isw_topic_149
1465,2026-03-12,0.765066,0.254433,0.143732,0.069641,0.144979,-0.166380,0.266070,0.093652,0.047666,...,0.003032,-0.000317,-0.006545,0.011102,0.010367,0.015426,0.005809,0.001704,0.004254,-0.000352
1466,2026-03-13,0.729641,0.246665,0.120514,0.087529,0.148420,-0.158200,0.260993,0.089181,0.039639,...,-0.012584,0.007533,-0.000076,0.013117,0.016895,0.017925,0.022592,0.012608,-0.006074,-0.001135
1467,2026-03-14,0.740226,0.232331,0.208518,0.021025,0.144145,-0.154209,0.256186,0.092777,0.051726,...,-0.016406,0.012282,0.011012,0.000315,0.009572,-0.011610,-0.003205,0.013381,0.005499,0.015785
1468,2026-03-15,0.749144,0.245996,0.145135,0.056091,0.141475,-0.163337,0.259697,0.090983,0.048221,...,-0.004930,0.008439,0.009397,0.014819,0.020686,0.001803,-0.000955,0.014018,-0.008022,0.013834
1469,2026-03-16,0.763329,0.257908,0.159290,0.046706,0.139619,-0.137105,0.237035,0.090248,0.034309,...,-0.024635,-0.002579,-0.007857,-0.023229,-0.002476,0.014476,0.010180,-0.003162,0.001239,0.020061

In [7]:
pd.set_option('display.max_columns', None)

In [8]:
df_weather['datetime_hour'] = pd.to_datetime(df_weather['datetime_hour'], errors="coerce")
df_war_events['datetime_hour'] = pd.to_datetime(df_war_events['datetime_hour'], errors="coerce")

In [9]:
df_final = pd.merge(
    df_weather, 
    df_war_events[['datetime_hour', 'region_id', 'alarm_active', 'alarm_minutes_in_hour']], 
    on=['datetime_hour', 'region_id'], 
    how='left'
)
df_final.sample(20)

,datetime_hour,region_id,day_tempmax,day_tempmin,day_temp,day_dew,day_humidity,day_precip,day_precipprob,day_precipcover,day_windgust,day_cloudcover,day_moonphase,hour_temp,hour_feelslike,hour_humidity,hour_dew,hour_precip,hour_precipprob,hour_snow,hour_snowdepth,hour_windgust,hour_windspeed,hour_winddir,hour_pressure,hour_cloudcover,hour_solarradiation,hour_solarenergy,hour_uvindex,hour_conditions_simple_Clear,hour_conditions_simple_Cloudy,hour_conditions_simple_Rain,hour_conditions_simple_Snow,day_of_week,hour,city_name,day_datetime,day_sunrise,day_sunset,region_key,alarm_active,alarm_minutes_in_hour
193727,2023-01-26 08:00:00,26,-1.3,-3.8,-2.3,-4.7,84.1,0.200,100.0,4.17,20.5,97.0,0.15,-3.3,-3.3,89.36,-4.8,0.0,0.0,0.0,1.0,7.9,0.0,172.6,1028.1,100.0,0.6,0.0,0.0,False,True,False,False,3,8,Kyiv,2023-01-26,07:41:36,16:39:46,Київ,1,60.000000
563645,2024-10-29 16:00:00,7,16.1,3.1,9.8,7.0,84.2,0.124,100.0,4.17,21.6,59.3,0.90,15.0,15.0,66.90,8.9,0.0,0.0,0.0,0.0,13.3,6.8,233.0,1025.1,54.7,133.3,0.5,1.0,False,True,False,False,1,16,Uzhgorod,2024-10-29,07:13:01,17:15:25,Закарпатська,0,0.000000
619345,2025-02-03 09:00:00,3,0.2,-3.4,-1.2,-4.1,81.1,0.596,100.0,4.17,38.5,82.6,0.17,-2.3,-6.8,88.11,-4.0,0.0,0.0,0.0,0.1,23.8,12.6,290.4,1025.0,57.7,31.3,0.1,0.0,False,True,False,False,0,9,Lutsk,2025-02-03,07:51:23,17:14:26,Волинська,0,0.000000
3979,2022-03-02 21:00:00,22,0.7,-1.6,-0.8,-2.2,90.1,0.600,100.0,4.17,29.2,98.4,0.97,-0.3,-3.1,95.02,-1.0,0.0,0.0,0.0,0.1,16.6,7.9,350.9,1019.0,93.8,0.0,0.1,0.0,False,True,False,False,2,21,Khmelnytskyi,2022-03-02,06:53:04,17:56:18,Хмельницька,1,27.750000
284518,2023-07-03 00:00:00,25,26.6,17.5,22.0,14.2,65.2,0.000,0.0,0.00,28.1,60.5,0.50,19.1,19.1,92.76,17.9,0.0,0.0,0.0,0.0,13.0,0.0,257.5,1005.6,60.0,0.0,0.0,0.0,False,True,False,False,0,0,Chernihiv,2023-07-03,04:43:14,21:14:31,Чернігівська,0,0.000000
804741,2026-01-04 02:00:00,26,-0.1,-5.6,-2.7,-6.9,73.9,0.900,100.0,16.67,34.6,45.7,0.53,-2.8,-6.9,73.93,-6.8,0.0,0.0,0.0,6.3,29.9,10.8,230.0,1009.5,75.0,0.0,0.0,0.0,False,True,False,False,6,2,Kyiv,2026-01-04,07:58:11,16:07:49,Київ,0,0.000000
9505,2022-03-12 12:00:00,3,3.9,-6.2,-1.2,-9.2,57.2,0.000,0.0,0.00,32.8,80.0,0.31,1.3,-3.1,47.31,-8.7,0.0,0.0,0.0,0.0,30.2,16.2,310.0,1033.0,88.6,281.0,1.0,3.0,False,True,False,False,5,12,Lutsk,2022-03-12,06:39:33,18:18:19,Волинська,0,0.000000
193137,2023-01-25 08:00:00,11,-1.4,-3.6,-2.0,-3.9,87.0,0.000,0.0,0.00,21.2,95.8,0.12,-1.4,-5.2,88.19,-3.1,0.0,0.0,0.0,0.6,12.6,10.8,10.0,1033.5,100.0,3.6,0.0,0.0,False,True,False,False,2,8,Kropyvnytskyi,2023-01-25,07:29:15,16:37:42,Кіровоградська,0,0.000000
54863,2022-05-30 06:00:00,26,18.6,13.3,15.6,12.2,80.9,3.500,100.0,8.33,43.6,93.7,0.98,13.4,13.4,83.71,10.7,0.0,0.0,0.0,0.0,24.8,3.6,140.0,1014.5,90.0,5.0,0.0,0.0,False,True,False,False,0,6,Kyiv,2022-05-30,04:53:27,20:58:09,Київ,0,0.000000
784586,2025-11-28 14:00:00,19,2.2,0.9,1.6,0.0,89.3,0.000,0.0,0.00,19.8,97.1,0.25,1.2,-1.1,94.40,0.4,0.0,0.0,0.0,0.0,16.6,7.2,70.0,1023.9,100.0,55.7,0.2,1.0,False,True,False,False,4,14,Ternopil,2025-11-28,07:48:43,16:22:21,Тернопільська,0,0.000000
508396,2024-07-25 18:00:00,6,22.5,17.2,19.9,15.9,78.2,2.000,100.0,4.17,26.6,89.1,0.64,21.4,21.4,73.18,16.4,0.0,0.0,0.0,0.0,21.2,3.6,350.0,1008.0,100.0,248.9,0.9,2.0,False,True,False,False,3,18,Zhytomyr,2024-07-25,05:24:35,20:58:27,Житомирська,0,0.000000
236289,2023-04-10 07:00:00,11,13.7,7.1,10.2,7.2,82.6,2.900,100.0,8.33,30.6,93.8,0.65,7.9,6.1,97.31,7.5,0.0,0.0,0.0,0.0,19.8,10.1,108.4,1021.0,100.0,8.5,0.0,0.0,False,True,False,False,0,7,Kropyvnytskyi,2023-04-10,06:11:29,19:34:13,Кіровоградська,0,0.000000
294771,2023-07-20 20:00:00,5,26.2,12.9,19.6,13.4,69.4,3.700,100.0,41.67,36.7,61.1,0.09,19.1,19.1,83.29,16.2,0.1,100.0,0.0,0.0,20.9,11.2,153.8,1010.0,67.7,22.6,0.1,0.0,False,False,True,False,3,20,Donetsk,2023-07-20,04:49:49,20:19:49,Донецька,1,60.000000
377499,2023-12-11 11:00:00,5,-0.5,-3.5,-2.0,-2.6,95.9,2.700,100.0,54.17,37.8,100.0,0.95,-1.9,-7.0,97.09,-2.3,0.3,100.0,0.0,0.6,35.3,15.8,124.1,1022.0,100.0,27.5,0.1,0.0,False,False,False,True,0,11,Donetsk,2023-12-11,07:08:08,15:35:26,Донецька,0,0.000000
710497,2025-07-17 09:00:00,13,22.6,11.1,17.2,13.2,79.0,1.800,100.0,29.17,21.2,78.9,0.73,17.4,17.4,81.49,14.2,0.0,0.0,0.0,0.0,11.9,3.6,190.0,1010.5,65.0,325.0,1.2,3.0,False,True,False,False,3,9,Lviv,2025-07-17,05:34:37,21:25:01,Львівська,0,0.000000
79990,2022-07-12 21:00:00,25,17.9,13.7,15.8,12.1,78.9,7.000,100.0,4.17,54.0,93.0,0.43,14.4,14.4,89.53,12.7,7.0,100.0,0.0,0.0,29.9,10.8,200.0,1011.1,80.0,26.0,0.1,0.0,False,False,True,False,1,21,Chernihiv,2022-07-12,04:51:46,21:08:36,Чернігівська,0,0.000000
147903,2022-11-07 19:00:00,18,4.3,0.1,2.1,-1.0,80.0,0.000,0.0,0.00,23.0,92.3,0.42,2.8,2.8,86.05,0.7,0.0,0.0,0.0,0.0,10.4,4.7,151.2,1025.0,77.1,0.0,0.1,0.0,False,True,False,False,0,19,Sumy,2022-11-07,06:42:46,16:05:32,Сумська,0,0.000000
830127,2026-02-19 02:00:00,20,1.0,-8.0,-3.1,-3.9,94.2,13.700,100.0,79.17,55.8,90.4,0.07,-2.0,-9.3,100.00,-2.0,1.8,100.0,0.0,5.1,46.4,32.5,110.0,999.0,100.0,0.0,0.0,0.0,False,False,False,True,3,2,Kharkiv,2026-02-19,06:38:32,17:00:09,Харківська,1,54.833333
742299,2025-09-13 00:00:00,4,22.3,11.1,16.8,4.3,46.8,0.000,0.0,0.00,38.5,11.2,0.70,16.2,16.2,54.81,7.1,0.0,0.0,0.0,0.0,27.7,15.1,84.4,1025.0,0.0,0.0,0.0,0.0,True,False,False,False,5,0,Dnipro,2025-09-13,06:13:58,18:56:53,Дніпропетровська,1,60.000000
235927,2023-04-09 16:00:00,9,12.9,-0.4,6.6,1.4,72.5,0.000,0.0,0.00,16.2,74.4,0.61,12.1,12.1,48.29,1.5,0.0,0.0,0.0,0.4,16.2,4.7,166.5,1023.0,99.3,490.2,1.8,5.0,False,True,False,False,6,16,Ivano-Frankivsk,2023-04-09,06:43:06,20:03:32,Івано-Франківська,0,0.000000

In [10]:
df_final = df_final.sort_values(['region_id', 'datetime_hour'])
df_final.head()

,datetime_hour,region_id,day_tempmax,day_tempmin,day_temp,day_dew,day_humidity,day_precip,day_precipprob,day_precipcover,day_windgust,day_cloudcover,day_moonphase,hour_temp,hour_feelslike,hour_humidity,hour_dew,hour_precip,hour_precipprob,hour_snow,hour_snowdepth,hour_windgust,hour_windspeed,hour_winddir,hour_pressure,hour_cloudcover,hour_solarradiation,hour_solarenergy,hour_uvindex,hour_conditions_simple_Clear,hour_conditions_simple_Cloudy,hour_conditions_simple_Rain,hour_conditions_simple_Snow,day_of_week,hour,city_name,day_datetime,day_sunrise,day_sunset,region_key,alarm_active,alarm_minutes_in_hour
0,2022-02-24 00:00:00,2,5.0,0.7,2.8,-0.3,80.5,0.3,100.0,4.17,27.7,82.5,0.77,2.1,-0.5,91.76,0.9,0.0,0.0,0.0,0.0,16.6,8.6,279.6,1021.0,91.1,0.0,0.1,0.0,False,True,False,False,3,0,Vinnytsia,2022-02-24,06:58:49,17:40:52,Вінницька,0,0.0
24,2022-02-24 01:00:00,2,5.0,0.7,2.8,-0.3,80.5,0.3,100.0,4.17,27.7,82.5,0.77,2.1,-0.4,89.80,0.6,0.0,0.0,0.0,0.0,16.6,8.3,289.2,1021.0,97.9,0.0,0.1,0.0,False,True,False,False,3,1,Vinnytsia,2022-02-24,06:58:49,17:40:52,Вінницька,0,0.0
48,2022-02-24 02:00:00,2,5.0,0.7,2.8,-0.3,80.5,0.3,100.0,4.17,27.7,82.5,0.77,2.0,-0.3,90.44,0.6,0.0,0.0,0.0,0.0,27.7,7.6,287.6,1021.0,98.2,0.0,0.1,0.0,False,True,False,False,3,2,Vinnytsia,2022-02-24,06:58:49,17:40:52,Вінницька,0,0.0
72,2022-02-24 03:00:00,2,5.0,0.7,2.8,-0.3,80.5,0.3,100.0,4.17,27.7,82.5,0.77,1.9,-0.3,91.75,0.7,0.0,0.0,0.0,0.0,15.1,7.2,288.9,1021.0,98.8,0.0,0.1,0.0,False,True,False,False,3,3,Vinnytsia,2022-02-24,06:58:49,17:40:52,Вінницька,0,0.0
96,2022-02-24 04:00:00,2,5.0,0.7,2.8,-0.3,80.5,0.3,100.0,4.17,27.7,82.5,0.77,1.8,-0.2,92.40,0.7,0.0,0.0,0.0,0.0,13.7,6.5,290.4,1021.0,100.0,0.0,0.1,0.0,False,True,False,False,3,4,Vinnytsia,2022-02-24,06:58:49,17:40:52,Вінницька,0,0.0

In [11]:
df_final.tail()

,datetime_hour,region_id,day_tempmax,day_tempmin,day_temp,day_dew,day_humidity,day_precip,day_precipprob,day_precipcover,day_windgust,day_cloudcover,day_moonphase,hour_temp,hour_feelslike,hour_humidity,hour_dew,hour_precip,hour_precipprob,hour_snow,hour_snowdepth,hour_windgust,hour_windspeed,hour_winddir,hour_pressure,hour_cloudcover,hour_solarradiation,hour_solarenergy,hour_uvindex,hour_conditions_simple_Clear,hour_conditions_simple_Cloudy,hour_conditions_simple_Rain,hour_conditions_simple_Snow,day_of_week,hour,city_name,day_datetime,day_sunrise,day_sunset,region_key,alarm_active,alarm_minutes_in_hour
844324,2026-03-16 19:00:00,26,11.1,0.1,5.6,-1.8,60.9,0.0,0.0,0.0,25.6,15.5,0.92,7.5,7.5,55.25,-0.9,0.0,0.0,0.0,0.0,10.4,3.6,80.0,1019.0,44.3,5.5,0.1,0.0,False,True,False,False,0,19,Kyiv,2026-03-16,06:09:51,18:04:17,Київ,0,0.000000
844347,2026-03-16 20:00:00,26,11.1,0.1,5.6,-1.8,60.9,0.0,0.0,0.0,25.6,15.5,0.92,6.9,6.9,59.27,-0.5,0.0,0.0,0.0,0.0,9.4,4.0,79.6,1021.0,59.3,5.5,0.1,0.0,False,True,False,False,0,20,Kyiv,2026-03-16,06:09:51,18:04:17,Київ,0,0.000000
844370,2026-03-16 21:00:00,26,11.1,0.1,5.6,-1.8,60.9,0.0,0.0,0.0,25.6,15.5,0.92,6.1,6.1,62.62,-0.5,0.0,0.0,0.0,0.0,10.1,3.6,88.3,1021.0,39.4,5.5,0.1,0.0,False,True,False,False,0,21,Kyiv,2026-03-16,06:09:51,18:04:17,Київ,0,0.000000
844393,2026-03-16 22:00:00,26,11.1,0.1,5.6,-1.8,60.9,0.0,0.0,0.0,25.6,15.5,0.92,5.3,5.3,65.23,-0.7,0.0,0.0,0.0,0.0,9.0,2.5,85.6,1021.0,19.4,5.5,0.1,0.0,True,False,False,False,0,22,Kyiv,2026-03-16,06:09:51,18:04:17,Київ,1,25.650000
844416,2026-03-16 23:00:00,26,11.1,0.1,5.6,-1.8,60.9,0.0,0.0,0.0,25.6,15.5,0.92,4.7,4.7,66.06,-1.1,0.0,0.0,0.0,0.0,5.8,2.2,63.2,1021.0,10.6,5.5,0.1,0.0,True,False,False,False,0,23,Kyiv,2026-03-16,06:09:51,18:04:17,Київ,1,17.216667

In [12]:
df_final.info()

<class 'pandas.DataFrame'>
Index: 844417 entries, 0 to 844416
Data columns (total 42 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   datetime_hour                  844417 non-null  datetime64[us]
 1   region_id                      844417 non-null  int64
 2   day_tempmax                    844417 non-null  float64
 3   day_tempmin                    844417 non-null  float64
 4   day_temp                       844417 non-null  float64
 5   day_dew                        844417 non-null  float64
 6   day_humidity                   844417 non-null  float64
 7   day_precip                     844417 non-null  float64
 8   day_precipprob                 844417 non-null  float64
 9   day_precipcover                844417 non-null  float64
 10  day_windgust                   844417 non-null  float64
 11  day_cloudcover                 844417 non-null  float64
 12  day_moonphase                  844417 non-null  float64
 13  hour_temp                      844417 non-null  float64
 14  hour_feelslike                 844417 non-null  float64
 15  hour_humidity                  844417 non-null  float64
 16  hour_dew                       844417 non-null  float64
 17  hour_precip                    844417 non-null  float64
 18  hour_precipprob                844417 non-null  float64
 19  hour_snow                      844417 non-null  float64
 20  hour_snowdepth                 844417 non-null  float64
 21  hour_windgust                  844417 non-null  float64
 22  hour_windspeed                 844417 non-null  float64
 23  hour_winddir                   844417 non-null  float64
 24  hour_pressure                  844417 non-null  float64
 25  hour_cloudcover                844417 non-null  float64
 26  hour_solarradiation            844417 non-null  float64
 27  hour_solarenergy               844417 non-null  float64
 28  hour_uvindex                   844417 non-null  float64
 29  hour_conditions_simple_Clear   844417 non-null  bool
 30  hour_conditions_simple_Cloudy  844417 non-null  bool
 31  hour_conditions_simple_Rain    844417 non-null  bool
 32  hour_conditions_simple_Snow    844417 non-null  bool
 33  day_of_week                    844417 non-null  int64
 34  hour                           844417 non-null  int64
 35  city_name                      844417 non-null  str
 36  day_datetime                   844417 non-null  str
 37  day_sunrise                    844417 non-null  str
 38  day_sunset                     844417 non-null  str
 39  region_key                     844417 non-null  str
 40  alarm_active                   844417 non-null  int64
 41  alarm_minutes_in_hour          844417 non-null  float64
dtypes: bool(4), datetime64[us](1), float64(28), int64(4), str(5)
memory usage: 298.8 MB

In [13]:
df_final = df_final.sort_values(["region_id", "datetime_hour"])

df_final["alarm_lag_1"] = df_final.groupby("region_id")["alarm_active"].shift(1)
df_final["alarm_lag_3"] = df_final.groupby("region_id")["alarm_active"].shift(3)
df_final["alarm_lag_6"] = df_final.groupby("region_id")["alarm_active"].shift(6)
df_final["alarm_lag_12"] = df_final.groupby("region_id")["alarm_active"].shift(12)
#df_final['alarm_minutes_lag1'] = (df_final.groupby('region_id')['alarm_minutes_in_hour'].shift(1).fillna(0))
#df_final['alarm_minutes_lag3'] = (df_final.groupby('region_id')['alarm_minutes_in_hour'].shift(3).fillna(0))

lag_cols = ["alarm_lag_1","alarm_lag_3","alarm_lag_6","alarm_lag_12"]
df_final[lag_cols] = df_final[lag_cols].fillna(0)

df_final['alarms_in_last_24h'] = (df_final.groupby('region_id')['alarm_active'].transform(lambda x: x.shift(1).rolling(24, min_periods=1).sum()))

df_final['is_weekend'] = df_final['day_of_week'].isin([5, 6]).astype(int)
df_final['is_night'] = ((df_final['hour'] >= 23) | (df_final['hour'] <= 6)).astype(int)

hourly_total = df_final.groupby('datetime_hour')['alarm_active'].sum().shift(1)
df_final['total_active_alarms_lag1'] = df_final['datetime_hour'].map(hourly_total)

df_final.sample(10)

,datetime_hour,region_id,day_tempmax,day_tempmin,day_temp,day_dew,day_humidity,day_precip,day_precipprob,day_precipcover,day_windgust,day_cloudcover,day_moonphase,hour_temp,hour_feelslike,hour_humidity,hour_dew,hour_precip,hour_precipprob,hour_snow,hour_snowdepth,hour_windgust,hour_windspeed,hour_winddir,hour_pressure,hour_cloudcover,hour_solarradiation,hour_solarenergy,hour_uvindex,hour_conditions_simple_Clear,hour_conditions_simple_Cloudy,hour_conditions_simple_Rain,hour_conditions_simple_Snow,day_of_week,hour,city_name,day_datetime,day_sunrise,day_sunset,region_key,alarm_active,alarm_minutes_in_hour,alarm_lag_1,alarm_lag_3,alarm_lag_6,alarm_lag_12,alarms_in_last_24h,is_weekend,is_night,total_active_alarms_lag1
2660,2022-02-28 14:00:00,23,3.0,-2.6,0.0,-5.0,69.2,0.000,0.0,0.00,45.4,73.2,0.90,3.0,-2.3,56.54,-4.8,0.0,0.0,0.0,0.0,37.4,27.0,18.5,1029.0,52.8,155.1,0.6,2.0,False,True,False,False,0,14,Cherkasy,2022-02-28,06:36:47,17:32:39,Черкаська,0,0.000000,1.0,0.0,1.0,1.0,14.0,0,0,6.0
566925,2024-11-04 08:00:00,24,8.5,-0.3,4.7,-1.0,67.9,0.000,0.0,0.00,57.6,63.9,0.10,6.7,3.6,42.27,-5.2,0.0,0.0,0.0,0.0,48.2,17.5,302.0,1022.0,98.7,20.1,0.1,0.0,False,True,False,False,0,8,Chernivtsi,2024-11-04,07:07:01,16:52:02,Чернівецька,0,0.000000,0.0,0.0,0.0,0.0,0.0,0,0,0.0
768669,2025-10-30 18:00:00,18,11.7,5.0,7.9,5.2,84.3,0.100,100.0,4.17,35.6,85.4,0.30,9.1,6.8,76.04,5.1,0.0,0.0,0.0,0.0,25.6,14.8,165.1,1018.0,100.0,0.0,0.0,0.0,False,True,False,False,3,18,Sumy,2025-10-30,06:29:28,16:18:46,Сумська,0,0.000000,1.0,1.0,1.0,1.0,24.0,0,0,5.0
259795,2023-05-21 02:00:00,22,21.2,9.7,15.6,5.2,52.5,0.000,0.0,0.00,38.2,24.4,0.06,11.7,11.7,70.43,6.5,0.0,0.0,0.0,0.0,22.0,11.2,54.3,1023.0,0.0,0.0,0.0,0.0,True,False,False,False,6,2,Khmelnytskyi,2023-05-21,05:21:27,20:56:48,Хмельницька,0,0.000000,0.0,0.0,0.0,0.0,1.0,1,1,1.0
28439,2022-04-14 09:00:00,26,13.9,4.4,8.5,-0.2,58.1,0.000,0.0,0.00,41.8,49.6,0.43,6.2,3.9,68.83,0.9,0.0,0.0,0.0,0.0,33.5,10.8,340.0,1020.1,100.0,310.0,1.1,3.0,False,True,False,False,3,9,Kyiv,2022-04-14,06:06:42,19:50:49,Київ,0,0.000000,0.0,0.0,0.0,0.0,1.0,0,0,2.0
524252,2024-08-22 06:00:00,23,32.9,19.5,26.2,16.5,58.7,0.800,100.0,12.50,34.2,73.8,0.59,19.8,19.8,85.51,17.3,0.0,0.0,0.0,0.0,8.6,6.5,65.4,1007.0,75.7,0.0,0.0,0.0,False,True,False,False,3,6,Cherkasy,2024-08-22,05:53:29,19:54:43,Черкаська,1,26.433333,1.0,0.0,0.0,0.0,9.0,0,1,8.0
111050,2022-09-04 20:00:00,4,16.5,10.9,13.4,7.4,68.1,6.727,100.0,4.17,44.3,72.5,0.25,14.1,14.1,55.79,5.4,0.0,0.0,0.0,0.0,29.2,7.9,9.8,1022.0,3.6,1.0,0.0,0.0,True,False,False,False,6,20,Dnipro,2022-09-04,06:01:02,19:16:08,Дніпропетровська,0,0.000000,1.0,0.0,0.0,0.0,6.0,1,0,4.0
824713,2026-02-09 07:00:00,10,-5.8,-16.3,-10.5,-13.8,77.0,0.000,0.0,0.00,28.4,74.2,0.75,-13.1,-20.2,82.84,-15.4,0.0,0.0,0.0,25.8,24.1,13.7,6.8,1021.0,90.7,0.0,0.0,0.0,False,True,False,False,0,7,Kyiv,2026-02-09,07:20:24,17:04:39,Київська,1,56.683333,1.0,1.0,1.0,0.0,11.0,0,0,10.0
412805,2024-02-10 18:00:00,7,12.3,6.6,9.2,7.1,87.1,7.674,100.0,45.83,36.7,90.8,0.00,9.8,8.2,82.27,6.9,0.0,0.0,0.0,0.0,31.3,11.2,182.0,999.9,86.0,12.3,0.0,0.0,False,True,False,False,5,18,Uzhgorod,2024-02-10,07:48:01,17:42:54,Закарпатська,0,0.000000,0.0,0.0,0.0,0.0,0.0,1,0,5.0
646784,2025-03-23 22:00:00,9,11.1,4.0,6.9,3.0,76.5,0.600,100.0,4.17,40.0,93.6,0.80,6.5,2.9,90.77,5.1,0.0,0.0,0.0,0.0,37.4,19.8,129.4,1016.0,90.8,0.0,0.0,0.0,False,True,False,False,6,22,Ivano-Frankivsk,2025-03-23,06:17:31,18:38:47,Івано-Франківська,0,0.000000,0.0,0.0,0.0,0.0,0.0,1,0,10.0

In [14]:
neighbouring_regions = {
    1: [21],
    2: [6, 10, 11, 15, 22, 23, 24],
    3: [13, 17],
    4: [5, 8, 11, 14, 16, 20, 21],
    5: [4, 8, 12, 20],
    6: [2, 10, 17, 22],
    7: [9, 13],
    8: [4, 5, 21],
    9: [7, 13, 19, 24],
    10: [2, 6, 16, 23, 25],
    11: [2, 4, 14, 15, 16, 23],
    12: [5, 20],
    13: [3, 7, 9, 17, 19],
    14: [4, 11, 15, 21],
    15: [2, 11, 14],
    16: [4, 10, 11, 18, 20, 23, 25],
    17: [3, 6, 13, 19, 22],
    18: [16, 20, 25],
    19: [9, 13, 17, 22, 24],
    20: [4, 5, 12, 16, 18],
    21: [1, 4, 8, 14],
    22: [2, 6, 17, 19, 24],
    23: [2, 10, 11, 16],
    24: [2, 9, 19, 22],
    25: [10, 16, 18], 
    26: [10]
}

alarms_matrix = df_final.pivot_table(
    index='datetime_hour',
    columns='region_id',
    values='alarm_active',
    fill_value=0
)

neighbour_alarm_matrix = pd.DataFrame(index=alarms_matrix.index)

for region, neighbours in neighbouring_regions.items():
    valid_neighbours = [n for n in neighbours if n in alarms_matrix.columns]
    
    if valid_neighbours:
        neighbour_alarm_matrix[region] = alarms_matrix[valid_neighbours].sum(axis=1)
    else:
        neighbour_alarm_matrix[region] = 0

neighbour_alarm_matrix = neighbour_alarm_matrix.shift(1)

neighbour_alarm_long = (neighbour_alarm_matrix.stack().reset_index())

neighbour_alarm_long.columns = ['datetime_hour','region_id','neighbour_alarms']

df_final = df_final.merge(neighbour_alarm_long,on=['datetime_hour', 'region_id'], how='left')

In [15]:
def hours_since_last_alarm_vectorized(series):
    shifted = series.shift(1).fillna(0)
    alarm_cumsum = shifted.cumsum()
    result = shifted.groupby(alarm_cumsum).cumcount()
    return result

df_final['hours_since_last_alarm'] = (df_final.groupby('region_id')['alarm_active'].transform(hours_since_last_alarm_vectorized))

In [16]:
df_final.sample(20)

,datetime_hour,region_id,day_tempmax,day_tempmin,day_temp,day_dew,day_humidity,day_precip,day_precipprob,day_precipcover,day_windgust,day_cloudcover,day_moonphase,hour_temp,hour_feelslike,hour_humidity,hour_dew,hour_precip,hour_precipprob,hour_snow,hour_snowdepth,hour_windgust,hour_windspeed,hour_winddir,hour_pressure,hour_cloudcover,hour_solarradiation,hour_solarenergy,hour_uvindex,hour_conditions_simple_Clear,hour_conditions_simple_Cloudy,hour_conditions_simple_Rain,hour_conditions_simple_Snow,day_of_week,hour,city_name,day_datetime,day_sunrise,day_sunset,region_key,alarm_active,alarm_minutes_in_hour,alarm_lag_1,alarm_lag_3,alarm_lag_6,alarm_lag_12,alarms_in_last_24h,is_weekend,is_night,total_active_alarms_lag1,neighbour_alarms,hours_since_last_alarm
522557,2026-01-01 16:00:00,17,-2.5,-16.3,-9.0,-11.4,83.5,0.000,0.0,0.00,42.5,50.0,0.43,-3.3,-8.6,84.74,-5.5,0.0,0.0,0.0,5.4,26.6,15.5,182.0,1008.0,100.0,32.6,0.1,0.0,False,True,False,False,3,16,Rivne,2026-01-01,08:16:31,16:20:52,Рівненська,0,0.000000,1.0,1.0,1.0,1.0,14.0,0,0,10.0,1.0,0
122321,2023-12-07 07:00:00,5,-0.8,-2.4,-1.8,-3.7,87.0,0.000,0.0,0.00,50.0,99.4,0.82,-2.3,-7.8,89.44,-3.8,0.0,0.0,0.0,0.4,37.8,17.6,89.0,1024.0,98.5,0.0,0.0,0.0,False,True,False,False,3,7,Donetsk,2023-12-07,07:04:03,15:35:54,Донецька,1,60.000000,1.0,0.0,0.0,0.0,10.0,0,0,1.0,0.0,0
395953,2023-09-24 22:00:00,14,30.9,12.9,21.8,12.6,61.1,0.000,0.0,0.00,28.1,1.3,0.32,22.3,22.3,51.75,11.9,0.0,0.0,0.0,0.0,21.6,11.5,98.9,1020.0,0.0,0.0,0.0,0.0,True,False,False,False,6,22,Mykolaiv,2023-09-24,06:40:50,18:46:52,Миколаївська,0,0.000000,0.0,1.0,0.0,0.0,4.0,1,0,3.0,1.0,1
350097,2022-07-23 01:00:00,13,32.6,16.3,25.6,15.5,56.6,0.000,0.0,0.00,23.0,48.1,0.80,22.8,22.8,58.72,14.3,0.0,0.0,0.0,0.0,9.4,4.0,132.8,1016.0,31.0,0.0,0.1,0.0,False,True,False,False,5,1,Lviv,2022-07-23,05:41:31,21:18:34,Львівська,0,0.000000,0.0,0.0,0.0,0.0,0.0,1,1,1.0,0.0,151
707379,2022-09-29 11:00:00,23,18.7,9.8,14.4,12.1,86.3,0.000,0.0,0.00,25.2,73.5,0.10,14.4,14.4,79.50,10.9,0.0,0.0,0.0,0.0,14.4,7.9,114.0,1010.0,91.4,356.0,1.3,4.0,False,True,False,False,3,11,Cherkasy,2022-09-29,06:48:09,18:35:15,Черкаська,0,0.000000,0.0,0.0,0.0,0.0,6.0,0,0,6.0,1.0,7
382398,2022-03-09 01:00:00,14,1.3,-1.7,-0.4,-4.6,74.8,0.000,0.0,0.00,38.9,67.9,0.21,-0.4,-0.4,93.64,-1.3,0.0,0.0,0.0,0.0,3.6,2.2,304.3,1014.0,58.0,0.0,0.1,0.0,False,True,False,False,2,1,Mykolaiv,2022-03-09,06:17:08,17:48:54,Миколаївська,0,0.000000,0.0,0.0,0.0,0.0,2.0,0,1,2.0,0.0,9
770283,2025-11-11 18:00:00,24,10.2,5.6,7.7,6.4,92.0,0.000,0.0,0.00,34.6,24.6,0.70,6.9,5.1,86.25,4.8,0.0,0.0,0.0,0.0,18.7,9.5,301.0,1017.0,0.0,0.0,0.0,0.0,True,False,False,False,1,18,Chernivtsi,2025-11-11,07:17:33,16:42:32,Чернівецька,0,0.000000,0.0,0.0,0.0,0.0,0.0,0,0,8.0,0.0,41
786835,2023-09-11 12:00:00,25,22.3,6.0,14.1,7.8,70.8,0.000,0.0,0.00,17.3,53.2,0.88,22.1,22.1,42.30,8.7,0.0,0.0,0.0,0.0,17.3,7.2,220.0,1021.8,100.0,354.4,1.3,4.0,False,True,False,False,0,12,Chernihiv,2023-09-11,06:22:36,19:19:38,Чернігівська,0,0.000000,0.0,0.0,0.0,1.0,2.0,0,0,4.0,1.0,11
715780,2023-09-14 13:00:00,23,25.2,14.9,19.7,14.0,70.8,3.300,100.0,37.50,26.6,58.3,0.98,25.2,25.2,54.92,15.5,0.0,0.0,0.0,0.0,24.8,12.2,159.5,1015.0,59.0,412.4,1.5,4.0,False,True,False,False,3,13,Cherkasy,2023-09-14,06:25:47,19:08:16,Черкаська,0,0.000000,0.0,0.0,0.0,0.0,0.0,0,0,3.0,0.0,24
63512,2025-05-03 16:00:00,3,25.1,11.7,17.8,8.4,56.1,1.552,100.0,8.33,51.5,56.1,0.19,24.1,24.1,43.44,10.9,0.0,0.0,0.0,0.0,46.1,20.9,272.1,1008.0,28.7,613.3,2.2,6.0,False,True,False,False,5,16,Lutsk,2025-05-03,05:49:10,20:43:07,Волинська,0,0.000000,0.0,0.0,0.0,0.0,0.0,1,0,3.0,0.0,75
823887,2023-11-12 12:00:00,26,8.6,6.5,7.4,6.3,92.6,19.000,100.0,8.33,52.9,100.0,0.97,6.9,3.5,88.92,5.2,0.0,0.0,0.0,0.0,39.2,19.4,278.9,993.0,100.0,36.1,0.1,0.0,False,True,False,False,6,12,Kyiv,2023-11-12,07:06:33,16:16:52,Київ,0,0.000000,0.0,0.0,0.0,0.0,4.0,1,0,1.0,0.0,20
404853,2024-09-29 19:00:00,14,27.2,12.9,20.2,12.8,65.0,0.000,0.0,0.00,26.3,29.1,0.88,24.7,24.7,45.37,12.1,0.0,0.0,0.0,0.0,11.5,6.8,70.9,1008.0,93.0,9.8,0.0,0.0,False,True,False,False,6,19,Mykolaiv,2024-09-29,06:48:30,18:35:19,Миколаївська,0,0.000000,0.0,1.0,0.0,0.0,7.0,1,0,0.0,0.0,2
514331,2025-01-23 21:00:00,17,4.7,-0.3,1.7,0.6,92.5,0.002,100.0,4.17,29.2,91.0,0.80,2.2,-1.8,93.10,1.2,0.0,0.0,0.0,0.0,28.8,15.5,170.7,1015.0,99.0,0.0,0.0,0.0,False,True,False,False,3,21,Rivne,2025-01-23,08:02:17,16:52:07,Рівненська,0,0.000000,0.0,0.0,0.0,0.0,0.0,0,0,0.0,0.0,39
617426,2024-08-27 00:00:00,20,31.5,17.0,24.8,10.6,42.4,0.000,0.0,0.00,41.4,43.5,0.77,24.3,24.3,40.10,9.9,0.0,0.0,0.0,0.0,24.1,3.8,89.0,1017.1,0.0,0.0,0.0,0.0,True,False,False,False,1,0,Kharkiv,2024-08-27,05:43:01,19:29:02,Харківська,1,23.250000,1.0,1.0,0.0,1.0,18.0,0,1,14.0,4.0,0
440037,2024-09-13 23:00:00,15,25.8,17.7,22.1,19.0,83.5,0.200,100.0,8.33,35.3,44.9,0.34,20.9,20.9,92.85,19.7,0.0,0.0,0.0,0.0,15.8,9.7,110.3,1009.0,49.9,0.0,0.0,0.0,False,True,False,False,4,23,Odesa,2024-09-13,06:32:44,19:12:13,Одеська,0,0.000000,0.0,0.0,0.0,0.0,3.0,0,1,11.0,1.0,19
370273,2024-11-09 19:00:00,13,3.7,0.9,2.2,0.3,87.2,0.000,0.0,0.00,34.2,97.8,0.25,3.2,-0.3,80.68,0.2,0.0,0.0,0.0,0.0,23.0,13.7,117.2,1033.0,87.0,0.0,0.0,0.0,False,True,False,False,5,19,Lviv,2024-11-09,07:26:58,16:47:57,Львівська,0,0.000000,0.0,0.0,0.0,0.0,2.0,1,0,7.0,1.0,15
609963,2023-10-21 00:00:00,20,14.2,5.0,9.0,8.4,95.6,3.400,100.0,8.33,41.0,97.5,0.23,13.8,13.8,92.59,12.7,0.0,0.0,0.0,0.0,31.3,3.7,328.0,1005.8,100.0,0.0,0.0,0.0,False,True,False,False,5,0,Kharkiv,2023-10-21,07:05:50,17:32:54,Харківська,0,0.000000,1.0,0.0,0.0,1.0,3.0,1,1,8.0,2.0,0
839801,2025-09-05 16:00:00,26,24.9,10.6,18.4,10.3,62.6,0.000,0.0,0.00,25.2,0.5,0.42,24.7,24.7,37.15,9.1,0.0,0.0,0.0,0.0,24.8,9.4,87.2,1020.0,0.0,532.3,1.9,5.0,True,False,False,False,4,16,Kyiv,2025-09-05,06:18:22,19:33:52,Київ,0,0.000000,0.0,0.0,0.0,0.0,0.0,0,0,3.0,0.0,24
291628,2024-01-01 13:00:00,10,3.9,-2.4,1.4,0.2,91.6,1.400,100.0,25.00,26.3,94.8,0.67,3.3,0.4,89.89,1.8,0.0,0.0,0.0,0.0,22.3,10.8,181.4,1010.0,99.2,85.1,0.3,1.0,False,True,False,False,0,13,Kyiv,2024-01-01,07:58:39,16:04:00,Київська,1,54.200000,1.0,0.0,0.0,0.0,9.0,0,0,24.0,5.0,0
92766,2024-08-13 17:00:00,4,26.0,13.8,20.2,8.8,50.8,0.000,0.0,0.00,43.2,42.6,0.29,24.9,24.9,32.26,7.2,0.0,0.0,0.0,0.0,43.2,22.0,316.0,1011.0,32.8,374.1,1.3,4.0,False,True,False,False,1,17,Dnipro,2024-08-13,05:31:12,19:57:27,Дніпропетровська,1,25.983333,1.0,1.0,1.0,0.0,13.0,0,0,6.0,4.0,0

In [17]:
df_isw_matrix.sample(10)

,date,isw_topic_0,isw_topic_1,isw_topic_2,isw_topic_3,isw_topic_4,isw_topic_5,isw_topic_6,isw_topic_7,isw_topic_8,isw_topic_9,isw_topic_10,isw_topic_11,isw_topic_12,isw_topic_13,isw_topic_14,isw_topic_15,isw_topic_16,isw_topic_17,isw_topic_18,isw_topic_19,isw_topic_20,isw_topic_21,isw_topic_22,isw_topic_23,isw_topic_24,isw_topic_25,isw_topic_26,isw_topic_27,isw_topic_28,isw_topic_29,isw_topic_30,isw_topic_31,isw_topic_32,isw_topic_33,isw_topic_34,isw_topic_35,isw_topic_36,isw_topic_37,isw_topic_38,isw_topic_39,isw_topic_40,isw_topic_41,isw_topic_42,isw_topic_43,isw_topic_44,isw_topic_45,isw_topic_46,isw_topic_47,isw_topic_48,isw_topic_49,isw_topic_50,isw_topic_51,isw_topic_52,isw_topic_53,isw_topic_54,isw_topic_55,isw_topic_56,isw_topic_57,isw_topic_58,isw_topic_59,isw_topic_60,isw_topic_61,isw_topic_62,isw_topic_63,isw_topic_64,isw_topic_65,isw_topic_66,isw_topic_67,isw_topic_68,isw_topic_69,isw_topic_70,isw_topic_71,isw_topic_72,isw_topic_73,isw_topic_74,isw_topic_75,isw_topic_76,isw_topic_77,isw_topic_78,isw_topic_79,isw_topic_80,isw_topic_81,isw_topic_82,isw_topic_83,isw_topic_84,isw_topic_85,isw_topic_86,isw_topic_87,isw_topic_88,isw_topic_89,isw_topic_90,isw_topic_91,isw_topic_92,isw_topic_93,isw_topic_94,isw_topic_95,isw_topic_96,isw_topic_97,isw_topic_98,isw_topic_99,isw_topic_100,isw_topic_101,isw_topic_102,isw_topic_103,isw_topic_104,isw_topic_105,isw_topic_106,isw_topic_107,isw_topic_108,isw_topic_109,isw_topic_110,isw_topic_111,isw_topic_112,isw_topic_113,isw_topic_114,isw_topic_115,isw_topic_116,isw_topic_117,isw_topic_118,isw_topic_119,isw_topic_120,isw_topic_121,isw_topic_122,isw_topic_123,isw_topic_124,isw_topic_125,isw_topic_126,isw_topic_127,isw_topic_128,isw_topic_129,isw_topic_130,isw_topic_131,isw_topic_132,isw_topic_133,isw_topic_134,isw_topic_135,isw_topic_136,isw_topic_137,isw_topic_138,isw_topic_139,isw_topic_140,isw_topic_141,isw_topic_142,isw_topic_143,isw_topic_144,isw_topic_145,isw_topic_146,isw_topic_147,isw_topic_148,isw_topic_149
1319,2025-10-14,0.747181,0.339812,0.088489,-0.172308,0.001162,-0.144459,0.036787,-0.190518,-0.066613,-0.187446,-0.060652,-0.040023,-0.060026,0.048086,-0.049673,0.004426,0.053710,-0.028178,0.049368,-0.043898,-0.026112,-0.033009,-0.050044,-0.049116,-0.028522,-0.028165,0.015673,-0.024033,-0.018556,0.003075,0.000400,0.042533,0.024088,-0.017701,-0.002570,-0.018683,-0.009724,-0.009970,0.014982,-0.023968,-0.006341,-0.010174,0.005962,-0.046694,0.016984,0.021192,0.036422,0.005376,0.004692,-0.030350,-0.023622,0.008982,0.004246,-0.037845,0.000723,0.010657,0.028145,-0.011919,-0.005896,0.022907,-0.002532,0.028253,-0.002245,0.007506,-0.001162,-0.031922,-0.013847,-0.021181,-0.001041,0.005175,0.007636,0.021677,-0.007297,-0.050674,0.010805,0.008795,-0.028649,-0.000103,-0.002102,0.006754,0.016535,0.061443,0.025110,-0.022785,-0.026930,0.050072,-0.040167,0.032171,-0.009523,0.001851,-0.016568,-0.028217,-0.003518,0.031212,-0.023429,-0.033124,0.008007,-0.012795,0.000577,-0.015566,-0.038264,0.014216,0.019691,-0.027953,0.025071,0.056825,-0.036398,-0.009105,0.015623,0.017508,-0.032763,-0.007155,-0.004493,0.002289,-0.031614,-0.010134,-0.001934,0.005332,-0.048980,0.027041,0.026666,-0.004402,-0.025716,0.006868,-0.021480,0.020490,-0.011712,-0.020468,-0.003296,-0.002507,-0.008206,-0.009635,-0.016837,0.019257,-0.003244,-0.023580,-0.030103,0.004129,-0.007157,0.012231,-0.005970,0.002459,-0.013747,0.030270,0.000095,-0.000582,0.002156,-0.028408,0.012387,0.007780
1313,2025-10-08,0.767828,0.325849,0.028183,-0.123379,0.000494,-0.128035,0.053573,-0.142132,-0.077720,-0.176235,-0.030848,-0.013960,-0.037276,0.070653,-0.088690,0.062491,0.088683,-0.049379,-0.013520,-0.072283,0.017928,0.013510,-0.041348,-0.013895,-0.005288,-0.042731,0.008358,0.022415,-0.031573,0.030920,-0.009761,0.051783,0.003983,0.014097,0.018619,0.025920,-0.003627,-0.008518,0.010372,-0.013575,-0.032885,-0.035461,0.003038,-0.000158,-0.019269,-0.007868,0.052707,-0.015863,-0.013360,0.007603,0.023876,-0.040234,0.025863,-0.024249,-0.013071,-0.058933,-0.026298,0.019348,0.000051,-0.016170,-0.025328,-0.031059,-0.025564,-0.020889,-0.004387,0.024201,-0.001436,0.031863,0.014465,-0.003483,0.001461,-0.023453,0.002481,-0.003888,0.009420,0.018114,-0.001800,-0.019408,0.028322,-0.019836,0.005012,-0.002229,-0.012432,-0.003551,-0.015440,0.030084,0.002233,0.029886,-0.029443,0.013735,-0.052740,-0.009818,0.018643,0.005312,0.014927,0.031609,-0.002755,0.015793,0.001459,0.008719,-0.000223,0.000526,-0.011008,-0.017731,-0.004699,-0.013685,-0.009705,0.042390,0.003525,0.000770,-0.016011,0.022196,-0.007738,-0.020237,-0.022736,-0.022305,-0.015584,-0.013996,0.006162,0.000729,0.012467,-0.029682,-0.006446,0.024747,-0.003814,0.035199,-0.038164,-0.009470,-0.006725,0.017269,-0.020624,-0.012829,-0.011397,0.006059,-0.001556,0.002075,0.006119,0.009697,0.026398,0.024757,-0.023481,0.046869,-0.005674,-0.007834,-0.035525,0.014221,0.013269,-0.050927,0.004681,-0.003007
661,2023-12-20,0.781312,-0.097103,-0.203659,0.025224,0.089286,-0.016635,-0.129667,0.167790,-0.112384,-0.019049,-0.076538,-0.031664,-0.020763,-0.006363,-0.058330,-0.020122,0.057448,0.006033,-0.011683,-0.088592,-0.028433,-0.024122,0.020605,0.026566,0.045782,0.016548,0.044204,-0.015056,0.061030,0.001309,0.029639,0.030355,-0.011272,-0.004686,-0.021637,-0.017092,0.031414,-0.034813,-0.008836,0.011688,0.024560,0.011609,0.029579,-0.002295,-0.004701,-0.065523,0.021463,0.006540,-0.001197,0.017476,-0.022752,0.017356,0.006175,-0.015757,0.008827,-0.002296,0.015442,0.020390,0.000528,0.015765,-0.048266,0.022315,-0.008990,-0.042528,-0.001952,-0.049263,0.030743,-0.002712,-0.068118,0.025000,-0.027376,-0.008287,0.014204,0.008524,-0.029109,0.010008,0.005447,0.032508,-0.009838,0.042860,0.028874,0.007029,-0.005168,-0.006778,-0.004736,0.007918,0.008403,0.025634,0.020396,0.016047,-0.001260,0.046958,-0.016681,-0.013170,-0.017741,-0.010846,-0.024662,-0.002727,0.035678,0.026225,0.015882,0.044491,-0.012032,-0.017754,-0.001535,0.052679,-0.039009,-0.033723,0.007047,0.024638,0.020491,0.011601,-0.004886,0.007603,-0.018622,-0.029952,-0.023660,0.049682,-0.012314,-0.002675,0.014616,-0.003085,-0.026839,-0.008130,0.019464,0.012071,0.022052,0.006871,0.030782,0.014435,-0.007271,0.020153,-0.056453,0.006545,0.035754,-0.021817,0.019590,0.008876,-0.011933,-0.010081,0.028330,0.012301,0.007549,-0.006677,0.018993,-0.010038,-0.005453,0.020455,-0.000036,-0.023275
1290,2025-09-15,0.779046,0.299672,0.055660,-0.114585,-0.033947,-0.017141,0.095018,-0.008479,-0.094676,-0.015628,0.063841,0.018197,0.208999,-0.201522,-0.014658,0.050874,0.081647,-0.070350,0.023726,-0.100215,-0.074578,0.017509,-0.024618,-0.011977,-0.008116,-0.002770,0.013654,-0.016998,-0.041368,0.012201,-0.005207,0.009439,0.008008,-0.018045,0.001428,0.038177,-0.002784,0.003239,0.018971,-0.016793,-0.035001,0.030134,0.036209,-0.006370,-0.029016,0.051226,0.045755,0.023687,0.008387,0.037973,0.008704,-0.008331,-0.015796,0.008606,-0.052730,-0.009985,0.011921,0.047889,-0.003226,-0.004922,0.011655,0.034924,-0.011145,0.052856,-0.037588,-0.005058,-0.013364,0.022827,-0.008970,0.018706,-0.014515,0.007119,-0.005977,-0.003597,-0.032740,-0.004358,-0.009208,-0.006318,-0.031994,-0.035248,-0.005695,0.022614,-0.018781,0.021602,0.025159,-0.016308,-0.005913,0.012886,-0.011298,0.030351,0.034746,-0.003725,-0.022551,0.000061,-0.013831,-0.006722,0.013660,0.005450,0.008549,0.035730,-0.018819,-0.026738,0.006474,-0.023563,-0.013009,0.020282,-0.004030,-0.001932,0.023262,-0.033642,0.005838,-0.011072,0.036235,0.005769,-0.009227,-0.007305,-0.012722,0.036975,-0.022310,0.016810,0.004770,-0.047982,-0.011830,-0.004353,-0.036227,-0.011816,0.003539,0.001758,0.001840,-0.017049,-0.006911,-0.001774,-0.014567,-0.025104,-0.004468,-0.012464,-0.027911,0.023584,-0.016185,0.011884,0.004601,0.019337,-0.019653,-0.044439,0.006594,0.012362,-0.009426,-0.002773,-0.000881,0.007974
290,2022-12-11,0.496594,-0.124496,-0.049575,0.016204,0.075892,-0.038473,-0.033960,0.050547,-0.007972,-0.027549,0.019165,0.006860,0.020748,0.035767,-0.008139,0.092709,0.048918,-0.151683,-0.060833,0.025619,-0.007402,0.071921,-0.100325,-0.062529,-0.107371,-0.185193,-0.012463,0.115500,-0.076534,-0.061750,0.079363,0.014965,0.039425,-0.292400,0.048359,-0.050481,-0.046308,0.054923,-0.041702,0.008407,-0.074698,0.255997,-0.078221,0.000794,0.022245,0.118151,0.003651,-0.076639,-0.017782,0.043176,0.033289,0.287390,-0.114046,-0.076746,-0.092648,0.164150,-0.073335,-0.007795,0.013763,0.014746,-0.027186,0.059779,-0.070565,-0.014552,0.091481,-0.028778,0.028565,0.109153,0.049148,-0.065645,0.024890,-0.038312,-0.043422,0.077915,0.027602,-0.069196,-0.003394,-0.016137,-0.005632,0.030704,0.079239,0.021695,-0.007507,0.046435,-0.089874,-0.034908,0.005963,0.005000,-0.020305,0.017667,-0.057163,0.012137,-0.024990,0.007581,-0.027245,-0.041880,-0.022372,0.047238,0.000028,-0.003823,0.017880,-0.033039,0.012382,0.062693,0.019309,0.028675,-0.023347,0.004870,-0.017649,0.008009,0.012745,0.008512,-0.010260,-0.012850,0.007955,-0.011296,-0.003338,-0.004611,-0.004901,-0.003905,-0.011711,-0.029229,0.020992,-0.017805,0.032743,-0.027398,0.020275,-0.034693,-0.021546,-0.046615,0.043651,-0.010323,-0.008944,-0.028850,-0.045420,0.013358,0.022941,-0.037081,-0.009763,-0.030795,0.006501,0.028270,0.004230,0.006227,0.018146,0.003029,0.014945,-0.003542,-0.018993,0.047205
342,2023-02-03,0.785299,-0.167700,-0.087675,0.000472,0.125787,0.049973,0.065868,0.009559,0.010312,-0.043514,0.043170,0.044302,0.151621,0.200695,0.122249,-0.011046,-0.088713,-0.002287,-0.018439,-0.062124,-0.094149,0.014184,0.017907,0.008391,-0.083023,-0.079126,0.016174,-0.015927,-0.044376,-0.023145,0.022540,0.036687,0.038123,0.035600,0.004910,-0.016714,-0.015684,0.047715,0.006195,0.020178,-0.009060,0.022312,-0.004581,-0.060048,0.031268,0.009557,0.024626,-0.010248,0.003032,0.015780,-0.012720,-0.027386,-0.000761,0.010526,-0.005180,-0.029241,-0.009266,-0.036032,-0.023236,0.019959,0.002599,-0.008967,0.029689,0.002295,0.009505,0.021071,-0.029577,0.002871,-0.017073,0.026785,-0.020443,0.018095,0.007016,0.029705,0.046027,0.004325,0.037428,-0.065072,0.008936,-0.003048,-0.016118,0.017128,-0.026379,-0.010417,-0.032203,-0.017534,-0.000787,-0.001419,-0.011555,-0.033318,0.011633,-0.007586,0.004690,-0.005193,-0.022107,0.016223,-0.061897,0.040125,-0.003758,-0.016102,0.000400,0.029190,-0.023964,0.030433,-0.014665,-0.009851,-0.005346,-0.039802,-0.006784,-0.017114,-0.041687,-0.011846,-0.009232,-0.020352,0.003698,-0.011782,0.012981,-0.012602,0.002848,0.024558,-0.064284,-0.007759,0.003518,0.024672,-0.048048,-0.032753,-0.008200,-0.033333,-0.031875,-0.023970,-0.002893,-0.009491,-0.013687,0.010068,0.023636,-0.018140,0.006190,0.021522,0.014999,0.023880,-0.020733,-0.037388,-0.002555,0.038154,0.040308,0.010702,-0.011003,-0.007320,0.009426,0.004166
1109,2025-03-18,0.764309,0.196367,0.032043,0.234124,0.010178,-0.172615,0.164173,0.070980,0.046703,0.055090,-0.053117,-0.001096,-0.101125,-0.058140,0.087161,0.124171,-0.120477,0.081621,-0.059248,-0.071443,0.118643,0.090481,0.052691,-0.012615,-0.001120,0.034191,-0.005832,-0.076801,-0.008770,0.006635,-0.065371,0.018140,-0.011485,0.022271,0.009361,-0.034916,0.057123,0.073874,-0.017353,0.036260,-0.017152,0.000431,-0.028289,0.001334,0.013311,0.014696,-0.003196,0.015062,0.008601,0.009128,0.034515,-0.012627,-0.018666,-0.029003,-0.010388,-0.004274,0.004070,0.022580,-0.013784,-0.005152,0.001865,0.042196,0.005312,-0.006699,0.023674,-0.019806,-0.016250,0.003471,-0.045070,-0.030737,0.027479,-0.000609,0.008064,-0.046911,0.001522,0.009636,-0.016726,0.007157,0.000646,0.001553,0.039035,-0.020754,-0.003359,0.005375,-0.028918,-0.039241,0.021330,-0.012444,0.017790,0.010272,-0.009350,0.009328,0.028885,0.010874,0.001899,-0.022866,0.015094,-0.000725,-0.001449,-0.010672,-0.002427,0.000244,-0.003026,0.013245,0.005138,-0.025096,-0.017792,-0.026005,-0.008054,0.013341,0.005365,0.009626,-0.000438,-0.010522,0.000406,0.027523,0.007342,-0.000517,0.010058,-0.014285,-0.004907,0.041199,0.015716,0.011801,0.004983,-0.000607,-0.032929,-0.012976,0.002253,0.000964,-0.019800,-0.013653,-0.005772,-0.004264,0.034534,-0.004800,0.014798,-0.007848,-0.031963,-0.005263,-0.002330,0.012812,-0.010814,-0.016650,0.008396,0.023486,0.019775,0.028837,0.000331,0.025319
572,2023-09-21,0.783512,-0.116468,-0.031240,-0.139651,-0.063580,-0.016151,0.097853,-0.001759,-0.077957,0.044610,0.034007,0.019639,0.173326,-0.225062,0.045026,-0.120311,0.016652,0.037251,-0.065572,-0.003214,0.051831,0.010560,-0.028717,-0.011831,0.008802,0.035044,-0.002162,0.049434,-0.004382,-0.048522,-0.001370,-0.001821,0.031841,0.013709,-0.046667,-0.010863,-0.003731,0.016525,-0.061992,0.061916,0.001825,0.006798,-0.009768,-0.009783,0.027656,-0.028353,-0.013101,-0.009231,-0.023043,-0.023723,0.043099,-0.025858,0.001716,-0.103318,-0.059695,-0.011136,-0.028902,-0.054131,-0.026478,-0.026372,-0.051577,0.040068,0.029553,-0.013235,-0.032714,0.039456,0.001600,0.006304,0.041937,0.020702,0.006698,0.008157,0.007340,-0.044228,-0.014321,-0.034930,-0.036942,-0.026137,-0.002733,0.030547,-0.004743,-0.006752,-0.005074,-0.018184,0.014635,0.030685,-0.021806,-0.022452,-0.021457,-0.012058,-0.000176,0.020595,-0.023884,-0.035512,-0.020431,-0.014515,0.012870,0.022357,-0.015401,0.009359,-0.053405,-0.026169,0.030065,0.024374,-0.007349,-0.009095,0.035221,0.005837,0.027625,-0.003391,-0.042285,-0.023863,-0.010524,-0.008161,-0.037235,-0.020434,0.005472,0.001636,0.005760,0.015338,0.004955,0.020200,0.001121,-0.000353,-0.012351,0.003863,0.017047,0.025596,-0.025045,0.019083,0.018244,0.010814,-0.010229,-0.039032,-0.024204,-0.004243,-0.028699,-0.018876,-0.015174,-0.006309,-0.000549,-0.027569,0.010258,0.004032,-0.000736,-0.030008,-0.012762,0.004136,0.016042,-0.007556
337,2023-01-29,0.461696,-0.165812,-0.023138,0.017452,0.037823,0.053804,-0.011817,-0.010627,0.055483,-0.037517,0.013889,0.017695,0.041020,0.023760,-0.074711,0.076064,-0.004656,-0.019149,-0.170283,0.173237,0.181308,-0.011706,-0.094369,-0.122774,-0.171511,-0.071417,-0.054913,0.126435,0.069764,-0.030496,-0.165145,-0.026491,0.013922,0.081260,-0.109414,0.004841,0.017180,-0.170180,0.094403,-0.094437,0.031444,-0.013173,-0.137872,-0.046113,-0.062185,0.015347,0.046353,0.083036,0.131960,-0.101961,-0.090204,0.079876,-0.136557,-0.046416,-0.035715,-0.027922,-0.036452,0.041732,0.016788,-0.015180,0.015545,-0.097355,0.005895,-0.134578,-0.089197,-0.066821,-0.091817,-0.051822,-0.050267,0.099041,0.088755,-0.026208,0.115704,0.004206,-0.042212,0.017532,0.010706,-0.081037,0.010452,0.007214,0.026072,0.094418,0.077583,0.086375,0.002055,-0.089158,-0.042489,0.009030,0.004236,-0.026421,0.046302,-0.016915,0.024615,-0.072674,-0.032066,0.036279,-0.004343,0.043661,-0.005498,-0.003791,-0.058176,0.032209,0.114130,-0.053439,-0.015346,-0.037260,-0.041918,-0.029454,-0.043531,-0.088944,0.026299,-0.011790,0.010335,-0.063999,0.029416,-0.001752,0.031341,-0.028919,-0.071394,-0.021079,0.033645,-0.056207,0.012209,-0.073637,0.051994,0.010773,-0.002220,-0.001661,0.017094,0.043182,0.004893,-0.023928,-0.006696,0.007914,0.011837,0.011824,0.000220,0.005773,-0.012004,0.011930,-0.012220,0.026163,-0.010538,-0.004636,-0.024861,0.011920,0.041106,0.034078,0.051273,-0.007160
701,2024-01-31,0.751695,-0.032079,-0.221527,0.121535,0.192166,0.197736,0.025447,-0.157159,0.042216,0.099984,-0.064944,-0.006328,0.008200,-0.018864,-0.126635,-0.048897,0.063078,0.037378,-0.040758,-0.034802,0.032699,-0.052592,-0.084170,-0.005854,-0.002217,0.020960,0.000495,-0.036693,0.019113,0.045645,0.032670,-0.013841,0.046116,-0.044556,0.020181,0.036499,0.044376,0.036171,0.013898,0.015041,0.060242,-0.019393,-0.042220,-0.007893,-0.017348,0.009188,-0.022396,-0.051683,0.039061,-0.000744,0.018815,-0.012507,0.071033,-0.036411,-0.027962,0.007088,0.008674,0.033158,-0.050876,-0.004463,0.010707,0.023214,0.010173,-0.012942,-0.020748,0.034706,0.010227,-0.014383,-0.031868,-0.007514,0.025305,0.004826,-0.021255,0.027920,-0.008871,-0.008524,-0.023036,0.028802,0.019236,0.005128,-0.011631,0.008549,-0.001060,0.001866,-0.014913,-0.028060,-0.002669,-0.009943,-0.019013,-0.049579,-0.023829,-0.034043,0.002867,0.020480,0.007209,0.026421,-0.015293,0.023543,-0.029211,0.003256,0.005011,0.017581,0.024069,-0.001897,-0.034384,-0.038191,-0.005488,-0.018265,-0.006088,-0.010270,-0.021282,-0.036262,-0.006891,0.007543,0.001209,0.001697,0.011887,0.020081,0.002912,0.015103,0.003325,-0.020473,0.011325,-0.025687,-0.018283,0.017290,-0.023132,-0.017191,-0.002133,-0.015338,-0.016975,0.021627,0.006883,-0.012676,0.000825,0.030156,0.007380,0.036264,0.010327,-0.004356,0.015161,-0.002471,-0.036648,0.013591,-0.017914,0.006934,-0.017449,-0.006854,-0.014723,-0.032813

In [18]:
df_isw_matrix.tail()

,date,isw_topic_0,isw_topic_1,isw_topic_2,isw_topic_3,isw_topic_4,isw_topic_5,isw_topic_6,isw_topic_7,isw_topic_8,isw_topic_9,isw_topic_10,isw_topic_11,isw_topic_12,isw_topic_13,isw_topic_14,isw_topic_15,isw_topic_16,isw_topic_17,isw_topic_18,isw_topic_19,isw_topic_20,isw_topic_21,isw_topic_22,isw_topic_23,isw_topic_24,isw_topic_25,isw_topic_26,isw_topic_27,isw_topic_28,isw_topic_29,isw_topic_30,isw_topic_31,isw_topic_32,isw_topic_33,isw_topic_34,isw_topic_35,isw_topic_36,isw_topic_37,isw_topic_38,isw_topic_39,isw_topic_40,isw_topic_41,isw_topic_42,isw_topic_43,isw_topic_44,isw_topic_45,isw_topic_46,isw_topic_47,isw_topic_48,isw_topic_49,isw_topic_50,isw_topic_51,isw_topic_52,isw_topic_53,isw_topic_54,isw_topic_55,isw_topic_56,isw_topic_57,isw_topic_58,isw_topic_59,isw_topic_60,isw_topic_61,isw_topic_62,isw_topic_63,isw_topic_64,isw_topic_65,isw_topic_66,isw_topic_67,isw_topic_68,isw_topic_69,isw_topic_70,isw_topic_71,isw_topic_72,isw_topic_73,isw_topic_74,isw_topic_75,isw_topic_76,isw_topic_77,isw_topic_78,isw_topic_79,isw_topic_80,isw_topic_81,isw_topic_82,isw_topic_83,isw_topic_84,isw_topic_85,isw_topic_86,isw_topic_87,isw_topic_88,isw_topic_89,isw_topic_90,isw_topic_91,isw_topic_92,isw_topic_93,isw_topic_94,isw_topic_95,isw_topic_96,isw_topic_97,isw_topic_98,isw_topic_99,isw_topic_100,isw_topic_101,isw_topic_102,isw_topic_103,isw_topic_104,isw_topic_105,isw_topic_106,isw_topic_107,isw_topic_108,isw_topic_109,isw_topic_110,isw_topic_111,isw_topic_112,isw_topic_113,isw_topic_114,isw_topic_115,isw_topic_116,isw_topic_117,isw_topic_118,isw_topic_119,isw_topic_120,isw_topic_121,isw_topic_122,isw_topic_123,isw_topic_124,isw_topic_125,isw_topic_126,isw_topic_127,isw_topic_128,isw_topic_129,isw_topic_130,isw_topic_131,isw_topic_132,isw_topic_133,isw_topic_134,isw_topic_135,isw_topic_136,isw_topic_137,isw_topic_138,isw_topic_139,isw_topic_140,isw_topic_141,isw_topic_142,isw_topic_143,isw_topic_144,isw_topic_145,isw_topic_146,isw_topic_147,isw_topic_148,isw_topic_149
1465,2026-03-12,0.765066,0.254433,0.143732,0.069641,0.144979,-0.166380,0.266070,0.093652,0.047666,-0.005971,-0.022839,-0.027493,-0.013284,-0.053438,-0.108671,-0.076737,-0.062514,0.074815,0.126928,0.060178,0.064468,-0.073082,0.090115,0.012502,0.025990,-0.021222,0.003271,-0.003000,-0.023399,-0.041246,0.046683,-0.045821,-0.006519,0.023476,-0.031907,0.036555,-0.055942,0.013408,-0.020848,-0.015601,0.019009,0.037012,-0.000524,0.024216,-0.033717,-0.012869,0.025066,-0.040495,0.038080,0.030960,-0.043235,0.010624,-0.045864,0.009136,-0.033719,-0.005913,0.001567,-0.006515,0.003483,-0.001836,0.013089,-0.016532,-0.003341,0.013519,0.019499,-0.024948,0.010420,-0.018005,-6.777517e-03,-0.005597,-0.002244,0.009911,-0.008649,-0.011712,-0.015743,0.015824,-0.031023,0.025343,0.017240,0.008802,-0.027629,0.014344,-0.026334,-0.011674,-0.016208,0.016379,-0.011220,0.001471,-0.013165,-0.009175,-0.037000,-0.000638,-0.014463,-0.014415,0.006220,-0.004982,-0.000845,0.003552,-0.007706,-0.013666,0.010243,0.035163,0.014926,0.002759,0.011273,0.004127,0.014570,0.011445,0.007651,-0.011859,-0.009574,-0.007425,-0.002650,0.011232,0.009197,0.015446,-0.010712,-0.009066,-0.003153,-0.016597,0.010077,-0.002519,0.011182,-0.018032,-0.004637,-0.013795,0.023275,-0.012627,0.011217,0.008873,0.001366,0.014713,-0.001550,0.011899,0.015634,-0.008881,-0.000234,-0.025042,0.017235,-0.029331,0.003032,-0.000317,-0.006545,0.011102,0.010367,0.015426,0.005809,0.001704,0.004254,-0.000352
1466,2026-03-13,0.729641,0.246665,0.120514,0.087529,0.148420,-0.158200,0.260993,0.089181,0.039639,-0.021073,-0.001887,-0.029413,-0.016107,-0.043593,-0.123176,-0.029581,-0.045643,0.043537,0.109786,0.033566,0.032703,-0.014846,0.109468,0.066838,0.009854,-0.021243,-0.052359,0.047748,0.004632,-0.003190,0.048814,-0.072675,-0.020785,0.014451,-0.033611,0.044921,-0.017667,0.014083,-0.021032,-0.034673,0.004057,-0.012496,-0.022244,0.010415,-0.087610,-0.050536,0.071161,-0.035159,0.020357,0.033910,-0.026163,0.015623,-0.024740,-0.048221,-0.013629,-0.007749,0.026537,-0.033438,-0.004903,-0.001772,-0.015259,-0.063615,0.002543,-0.015795,0.032226,0.039486,0.029629,-0.033245,5.735563e-02,-0.001929,-0.017911,-0.050696,0.012334,0.008475,0.028079,0.007730,0.006653,0.033079,0.014611,-0.010935,0.012907,0.015373,0.008094,-0.023676,-0.019180,0.005388,-0.039551,-0.011736,0.002517,-0.015101,-0.023918,0.019787,0.018860,0.003881,0.052820,0.005292,0.015243,0.001446,-0.017980,-0.015600,0.009542,0.044380,-0.013693,-0.024854,-0.010858,-0.000891,0.006801,0.013915,0.005699,0.020252,-0.014115,0.007407,-0.011878,0.034735,0.011590,0.038541,0.017691,-0.012455,-0.022507,0.018720,0.003547,0.005801,0.015886,-0.000822,-0.020761,-0.002023,0.019880,-0.007153,0.017742,-0.027086,0.021461,-0.005170,0.000746,0.028572,-0.027311,0.011458,-0.006779,-0.003069,-0.014207,-0.047222,-0.012584,0.007533,-0.000076,0.013117,0.016895,0.017925,0.022592,0.012608,-0.006074,-0.001135
1467,2026-03-14,0.740226,0.232331,0.208518,0.021025,0.144145,-0.154209,0.256186,0.092777,0.051726,-0.005725,-0.013879,-0.025149,-0.032867,-0.069501,-0.099152,-0.099795,-0.078270,0.079999,0.113603,0.119327,0.049764,0.041656,0.083825,0.060603,0.006557,0.012430,-0.066228,0.033271,0.045675,-0.031748,0.041589,-0.095009,0.027840,0.042680,-0.032275,0.031743,-0.016721,0.030039,-0.019099,-0.011599,0.000191,0.022450,-0.012355,-0.034929,-0.007488,-0.008135,0.007868,-0.023445,-0.018560,0.048053,-0.011507,0.014391,0.007953,0.011873,-0.045470,-0.017504,0.001884,0.012534,0.011285,0.021653,0.009957,0.024366,-0.031798,-0.019292,0.000382,0.006396,0.021577,-0.025737,9.061105e-07,0.010486,-0.037469,0.004699,-0.006401,0.016996,-0.016998,-0.015654,-0.005181,0.007265,0.030198,0.023315,-0.004894,0.038584,-0.003500,-0.003816,0.014502,-0.015149,-0.010671,0.006001,-0.028428,0.018451,-0.002899,0.020245,0.003184,-0.013559,-0.011121,-0.020892,0.009696,-0.014120,-0.020365,0.006367,-0.017329,0.029840,0.006786,0.003175,-0.004093,0.005934,0.001253,0.023695,-0.009669,0.015394,-0.006823,0.015723,0.005364,0.028300,-0.004967,-0.003691,-0.002849,-0.008868,-0.014896,-0.007394,0.006952,-0.016250,0.008620,-0.007639,-0.000601,-0.012518,0.016646,-0.026369,0.002488,-0.024104,0.007927,0.014045,0.010846,0.018713,0.016251,0.007173,0.022476,-0.011452,-0.024647,-0.020169,-0.016406,0.012282,0.011012,0.000315,0.009572,-0.011610,-0.003205,0.013381,0.005499,0.015785
1468,2026-03-15,0.749144,0.245996,0.145135,0.056091,0.141475,-0.163337,0.259697,0.090983,0.048221,-0.005217,-0.019421,-0.024872,-0.018505,-0.047248,-0.091553,-0.055898,-0.083335,0.076723,0.129019,0.069012,0.072393,-0.033603,0.132394,0.047246,-0.001602,-0.018387,-0.038122,0.013449,0.034706,-0.049498,0.028030,-0.061754,0.020901,0.002037,-0.018425,0.022542,0.006349,0.016398,-0.008605,-0.034312,0.000168,0.026462,-0.008616,-0.008559,-0.001933,-0.015261,0.026921,-0.018890,0.000459,0.055087,-0.016048,0.027054,-0.009409,-0.006331,-0.039898,-0.051844,-0.022189,0.014726,0.015680,0.021347,0.023737,0.012657,-0.036189,-0.038169,0.000437,0.014987,0.030693,-0.002424,-9.660964e-03,0.018359,-0.024763,0.007739,-0.017960,0.000886,-0.008640,0.002868,-0.012151,0.020232,0.015708,0.004798,-0.013763,0.037211,-0.001242,-0.017039,-0.010456,0.011229,-0.023484,-0.007557,-0.015945,0.024258,-0.032258,-0.002255,0.002474,0.004083,0.015089,-0.000955,0.003460,-0.023137,-0.021042,0.011825,0.010725,0.044844,0.007140,0.021535,-0.007189,0.006446,0.015530,0.006088,-0.014942,-0.001527,-0.010566,0.004584,-0.005626,0.009725,-0.007808,0.034352,-0.008642,0.005634,-0.001677,-0.008118,0.023041,0.007632,0.023629,-0.016659,-0.010477,-0.020944,-0.009529,-0.034602,-0.003200,-0.032905,0.012749,0.016693,-0.002752,0.022213,0.016778,0.008445,0.003624,0.018741,-0.017556,-0.013517,-0.004930,0.008439,0.009397,0.014819,0.020686,0.001803,-0.000955,0.014018,-0.008022,0.013834
1469,2026-03-16,0.763329,0.257908,0.159290,0.046706,0.139619,-0.137105,0.237035,0.090248,0.034309,-0.016405,-0.007182,-0.020786,-0.015444,-0.040635,-0.087929,-0.065333,-0.031703,0.065081,0.107947,0.095459,0.061175,-0.072911,0.100152,-0.004679,0.019504,-0.024268,-0.012686,-0.003419,0.009949,-0.016268,0.050409,-0.067728,-0.001722,0.007696,-0.052572,0.027906,-0.043968,0.009228,-0.022924,-0.026173,0.015389,0.049728,-0.011892,0.035544,-0.040425,-0.015477,0.027806,-0.048095,0.006576,0.033667,-0.053193,0.002926,-0.024577,0.018430,-0.025015,-0.002874,0.015761,-0.006361,0.015737,0.049314,-0.000153,-0.011353,-0.005248,0.027920,0.010209,-0.018895,0.028934,-0.009222,1.486564e-02,0.000560,-0.045952,-0.008980,-0.018907,0.001456,-0.022851,-0.006765,-0.044090,0.009906,0.031205,0.031027,-0.019364,0.001277,-0.009505,0.006802,-0.021599,0.006317,-0.014554,-0.030289,0.010772,-0.024763,-0.028286,0.003788,0.010264,-0.027466,-0.008981,-0.010880,-0.002958,-0.020453,-0.001468,0.024672,0.012768,0.021246,0.022114,-0.013893,0.022840,-0.006963,0.016022,0.015851,-0.012893,-0.005564,-0.005529,0.019039,0.039666,0.010222,0.007122,0.005330,-0.010213,-0.035756,-0.000821,0.003358,0.027891,-0.003919,-0.000622,-0.000815,0.005627,-0.000709,0.004590,-0.014279,0.013812,-0.016632,-0.001279,0.008312,0.016122,0.028116,-0.016800,-0.001338,-0.016748,0.006018,0.011268,-0.004087,-0.024635,-0.002579,-0.007857,-0.023229,-0.002476,0.014476,0.010180,-0.003162,0.001239,0.020061

In [19]:
#df_isw_matrix["date"] = pd.to_datetime(df_isw_matrix["date"]) + pd.Timedelta(days=1)    ТУТ ЗСУВ ІСВ НА + 1 ДЕНЬ
df_isw_matrix = df_isw_matrix.rename(columns={'date': 'day_datetime'})

In [20]:
df_final['day_datetime'] = pd.to_datetime(df_final['day_datetime']).dt.date
df_isw_matrix['day_datetime'] = pd.to_datetime(df_isw_matrix['day_datetime']).dt.date
df_isw_matrix.fillna(0, inplace=True)
df_isw_matrix.isna().sum()

day_datetime     0
isw_topic_0      0
isw_topic_1      0
isw_topic_2      0
isw_topic_3      0
                ..
isw_topic_145    0
isw_topic_146    0
isw_topic_147    0
isw_topic_148    0
isw_topic_149    0
Length: 151, dtype: int64

In [21]:
df_final = df_final.merge(df_isw_matrix, on="day_datetime", how="left")

In [22]:
df_final.head(10)

,datetime_hour,region_id,day_tempmax,day_tempmin,day_temp,day_dew,day_humidity,day_precip,day_precipprob,day_precipcover,day_windgust,day_cloudcover,day_moonphase,hour_temp,hour_feelslike,hour_humidity,hour_dew,hour_precip,hour_precipprob,hour_snow,hour_snowdepth,hour_windgust,hour_windspeed,hour_winddir,hour_pressure,hour_cloudcover,hour_solarradiation,hour_solarenergy,hour_uvindex,hour_conditions_simple_Clear,hour_conditions_simple_Cloudy,hour_conditions_simple_Rain,hour_conditions_simple_Snow,day_of_week,hour,city_name,day_datetime,day_sunrise,day_sunset,region_key,alarm_active,alarm_minutes_in_hour,alarm_lag_1,alarm_lag_3,alarm_lag_6,alarm_lag_12,alarms_in_last_24h,is_weekend,is_night,total_active_alarms_lag1,neighbour_alarms,hours_since_last_alarm,isw_topic_0,isw_topic_1,isw_topic_2,isw_topic_3,isw_topic_4,isw_topic_5,isw_topic_6,isw_topic_7,isw_topic_8,isw_topic_9,isw_topic_10,isw_topic_11,isw_topic_12,isw_topic_13,isw_topic_14,isw_topic_15,isw_topic_16,isw_topic_17,isw_topic_18,isw_topic_19,isw_topic_20,isw_topic_21,isw_topic_22,isw_topic_23,isw_topic_24,isw_topic_25,isw_topic_26,isw_topic_27,isw_topic_28,isw_topic_29,isw_topic_30,isw_topic_31,isw_topic_32,isw_topic_33,isw_topic_34,isw_topic_35,isw_topic_36,isw_topic_37,isw_topic_38,isw_topic_39,isw_topic_40,isw_topic_41,isw_topic_42,isw_topic_43,isw_topic_44,isw_topic_45,isw_topic_46,isw_topic_47,isw_topic_48,isw_topic_49,isw_topic_50,isw_topic_51,isw_topic_52,isw_topic_53,isw_topic_54,isw_topic_55,isw_topic_56,isw_topic_57,isw_topic_58,isw_topic_59,isw_topic_60,isw_topic_61,isw_topic_62,isw_topic_63,isw_topic_64,isw_topic_65,isw_topic_66,isw_topic_67,isw_topic_68,isw_topic_69,isw_topic_70,isw_topic_71,isw_topic_72,isw_topic_73,isw_topic_74,isw_topic_75,isw_topic_76,isw_topic_77,isw_topic_78,isw_topic_79,isw_topic_80,isw_topic_81,isw_topic_82,isw_topic_83,isw_topic_84,isw_topic_85,isw_topic_86,isw_topic_87,isw_topic_88,isw_topic_89,isw_topic_90,isw_topic_91,isw_topic_92,isw_topic_93,isw_topic_94,isw_topic_95,isw_topic_96,isw_topic_97,isw_topic_98,isw_topic_99,isw_topic_100,isw_topic_101,isw_topic_102,isw_topic_103,isw_topic_104,isw_topic_105,isw_topic_106,isw_topic_107,isw_topic_108,isw_topic_109,isw_topic_110,isw_topic_111,isw_topic_112,isw_topic_113,isw_topic_114,isw_topic_115,isw_topic_116,isw_topic_117,isw_topic_118,isw_topic_119,isw_topic_120,isw_topic_121,isw_topic_122,isw_topic_123,isw_topic_124,isw_topic_125,isw_topic_126,isw_topic_127,isw_topic_128,isw_topic_129,isw_topic_130,isw_topic_131,isw_topic_132,isw_topic_133,isw_topic_134,isw_topic_135,isw_topic_136,isw_topic_137,isw_topic_138,isw_topic_139,isw_topic_140,isw_topic_141,isw_topic_142,isw_topic_143,isw_topic_144,isw_topic_145,isw_topic_146,isw_topic_147,isw_topic_148,isw_topic_149
0,2022-02-24 00:00:00,2,5.0,0.7,2.8,-0.3,80.5,0.3,100.0,4.17,27.7,82.5,0.77,2.1,-0.5,91.76,0.9,0.0,0.0,0.0,0.0,16.6,8.6,279.6,1021.0,91.1,0.0,0.1,0.0,False,True,False,False,3,0,Vinnytsia,2022-02-24,06:58:49,17:40:52,Вінницька,0,0.0,0.0,0.0,0.0,0.0,NaN,0,1,NaN,NaN,0,0.648733,-0.078386,0.180873,0.059880,0.070008,-0.042071,-0.006712,0.006174,-0.014324,0.004678,-0.034546,0.026839,0.051262,0.052505,0.069154,-0.065115,0.063161,-0.13259,-0.148380,0.167924,-0.069896,0.082404,-0.099159,-0.135181,0.040913,0.067235,-0.000759,0.058867,-0.037716,0.038137,0.020267,0.064787,-0.092394,-0.073454,-0.044226,0.015863,-0.045746,0.052133,-0.060692,0.157277,0.045770,0.153091,0.048066,-0.040708,0.029668,-0.018682,0.045509,0.093437,-0.040995,0.078446,-0.038387,-0.054725,-0.011545,-0.097217,0.008896,-0.047726,0.027129,0.028893,0.040973,0.061139,0.005002,-0.081452,-0.032886,0.071956,0.016690,0.039795,0.046933,-0.017759,0.000617,0.055723,0.001567,-0.065267,0.039934,-0.036891,0.055054,0.077850,-0.027169,0.051738,-0.012014,0.012023,-0.088707,0.027350,0.043625,0.012068,-0.010631,0.054585,-0.036056,-0.057756,-0.029479,0.036439,0.021386,-0.003892,-0.004663,-0.036183,0.014969,-0.000180,0.036404,-0.045506,-0.041311,0.045422,0.034035,0.045637,0.034013,0.002362,-0.075796,-0.009571,-0.035545,0.01706,-0.050099,-0.046210,-0.016780,-0.013202,-0.037655,0.045839,-0.018973,-0.005701,0.049022,-0.020264,0.033857,-0.035811,-0.012768,-0.011943,0.003566,-0.014989,0.034077,-0.013549,-0.027016,-0.005318,0.020995,-0.065815,-0.025836,0.048361,0.013902,0.007758,0.035416,0.017354,0.051423,-0.047020,0.005248,-0.011767,0.013046,0.010118,-0.017252,-0.029334,-0.010031,-0.020943,0.039399,-0.023117,0.000179,-0.014684
1,2022-02-24 00:00:00,2,5.0,0.7,2.8,-0.3,80.5,0.3,100.0,4.17,27.7,82.5,0.77,2.1,-0.5,91.76,0.9,0.0,0.0,0.0,0.0,16.6,8.6,279.6,1021.0,91.1,0.0,0.1,0.0,False,True,False,False,3,0,Vinnytsia,2022-02-24,06:58:49,17:40:52,Вінницька,0,0.0,0.0,0.0,0.0,0.0,NaN,0,1,NaN,NaN,0,0.579583,-0.092636,-0.024936,0.148737,0.067631,-0.022840,0.013561,0.027065,-0.037442,-0.035436,-0.015363,0.057749,0.179283,0.195302,-0.021927,0.067237,0.055735,-0.13245,-0.180805,0.022177,0.047934,0.124387,-0.104893,-0.028056,0.011823,-0.057940,0.017698,0.082596,-0.039430,0.008824,-0.008312,0.038742,-0.071414,-0.115007,0.019256,0.055175,-0.023332,0.013635,-0.052078,0.057392,-0.001245,0.182019,-0.013404,-0.044537,-0.019262,0.026267,0.091475,0.006528,0.007382,0.012741,-0.047336,-0.031316,-0.037770,-0.111627,-0.030441,-0.024342,0.072859,0.009923,0.082156,0.049584,-0.039721,-0.070926,-0.020624,0.073648,-0.023476,0.107926,-0.008489,0.047896,-0.012193,0.026755,-0.051663,0.006328,-0.025392,-0.060057,0.006822,0.020465,0.045375,0.068948,0.047465,-0.096006,-0.113087,0.025337,0.021947,0.055621,0.041927,-0.002777,-0.018814,-0.077862,0.037441,0.042639,0.066090,-0.005926,0.022404,-0.031626,0.025406,0.100814,0.073405,-0.031779,-0.095086,-0.031135,-0.020002,-0.043989,-0.091820,0.029670,0.018828,-0.015173,0.030559,-0.02146,-0.044291,0.026559,0.023168,0.017386,-0.044963,0.032709,0.025639,-0.033002,0.017142,-0.031334,0.009681,0.013112,0.061303,0.037710,-0.031997,-0.053227,0.000885,-0.023360,0.063897,0.060482,0.016209,-0.004942,0.031317,-0.038357,-0.007171,0.027314,0.064252,0.036855,0.004244,-0.041335,0.063204,0.000008,-0.011816,0.006371,-0.015602,-0.023692,-0.022085,-0.009336,0.000669,-0.016102,0.022940,-0.018549
2,2022-02-24 01:00:00,2,5.0,0.7,2.8,-0.3,80.5,0.3,100.0,4.17,27.7,82.5,0.77,2.1,-0.4,89.80,0.6,0.0,0.0,0.0,0.0,16.6,8.3,289.2,1021.0,97.9,0.0,0.1,0.0,False,True,False,False,3,1,Vinnytsia,2022-02-24,06:58:49,17:40:52,Вінницька,0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0.0,0.0,1,0.648733,-0.078386,0.180873,0.059880,0.070008,-0.042071,-0.006712,0.006174,-0.014324,0.004678,-0.034546,0.026839,0.051262,0.052505,0.069154,-0.065115,0.063161,-0.13259,-0.148380,0.167924,-0.069896,0.082404,-0.099159,-0.135181,0.040913,0.067235,-0.000759,0.058867,-0.037716,0.038137,0.020267,0.064787,-0.092394,-0.073454,-0.044226,0.015863,-0.045746,0.052133,-0.060692,0.157277,0.045770,0.153091,0.048066,-0.040708,0.029668,-0.018682,0.045509,0.093437,-0.040995,0.078446,-0.038387,-0.054725,-0.011545,-0.097217,0.008896,-0.047726,0.027129,0.028893,0.040973,0.061139,0.005002,-0.081452,-0.032886,0.071956,0.016690,0.039795,0.046933,-0.017759,0.000617,0.055723,0.001567,-0.065267,0.039934,-0.036891,0.055054,0.077850,-0.027169,0.051738,-0.012014,0.012023,-0.088707,0.027350,0.043625,0.012068,-0.010631,0.054585,-0.036056,-0.057756,-0.029479,0.036439,0.021386,-0.003892,-0.004663,-0.036183,0.014969,-0.000180,0.036404,-0.045506,-0.041311,0.045422,0.034035,0.045637,0.034013,0.002362,-0.075796,-0.009571,-0.035545,0.01706,-0.050099,-0.046210,-0.016780,-0.013202,-0.037655,0.045839,-0.018973,-0.005701,0.049022,-0.020264,0.033857,-0.035811,-0.012768,-0.011943,0.003566,-0.014989,0.034077,-0.013549,-0.027016,-0.005318,0.020995,-0.065815,-0.025836,0.048361,0.013902,0.007758,0.035416,0.017354,0.051423,-0.047020,0.005248,-0.011767,0.013046,0.010118,-0.017252,-0.029334,-0.010031,-0.020943,0.039399,-0.023117,0.000179,-0.014684
3,2022-02-24 01:00:00,2,5.0,0.7,2.8,-0.3,80.5,0.3,100.0,4.17,27.7,82.5,0.77,2.1,-0.4,89.80,0.6,0.0,0.0,0.0,0.0,16.6,8.3,289.2,1021.0,97.9,0.0,0.1,0.0,False,True,False,False,3,1,Vinnytsia,2022-02-24,06:58:49,17:40:52,Вінницька,0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0.0,0.0,1,0.579583,-0.092636,-0.024936,0.148737,0.067631,-0.022840,0.013561,0.027065,-0.037442,-0.035436,-0.015363,0.057749,0.179283,0.195302,-0.021927,0.067237,0.055735,-0.13245,-0.180805,0.022177,0.047934,0.124387,-0.104893,-0.028056,0.011823,-0.057940,0.017698,0.082596,-0.039430,0.008824,-0.008312,0.038742,-0.071414,-0.115007,0.019256,0.055175,-0.023332,0.013635,-0.052078,0.057392,-0.001245,0.182019,-0.013404,-0.044537,-0.019262,0.026267,0.091475,0.006528,0.007382,0.012741,-0.047336,-0.031316,-0.037770,-0.111627,-0.030441,-0.024342,0.072859,0.009923,0.082156,0.049584,-0.039721,-0.070926,-0.020624,0.073648,-0.023476,0.107926,-0.008489,0.047896,-0.012193,0.026755,-0.051663,0.006328,-0.025392,-0.060057,0.006822,0.020465,0.045375,0.068948,0.047465,-0.096006,-0.113087,0.025337,0.021947,0.055621,0.041927,-0.002777,-0.018814,-0.077862,0.037441,0.042639,0.066090,-0.005926,0.022404,-0.031626,0.025406,0.100814,0.073405,-0.031779,-0.095086,-0.031135,-0.020002,-0.043989,-0.091820,0.029670,0.018828,-0.015173,0.030559,-0.02146,-0.044291,0.026559,0.023168,0.017386,-0.044963,0.032709,0.025639,-0.033002,0.017142,-0.031334,0.009681,0.013112,0.061303,0.037710,-0.031997,-0.053227,0.000885,-0.023360,0.063897,0.060482,0.016209,-0.004942,0.031317,-0.038357,-0.007171,0.027314,0.064252,0.036855,0.004244,-0.041335,0.063204,0.000008,-0.011816,0.006371,-0.015602,-0.023692,-0.022085,-0.009336,0.000669,-0.016102,0.022940,-0.018549
4,2022-02-24 02:00:00,2,5.0,0.7,2.8,-0.3,80.5,0.3,100.0,4.17,27.7,82.5,0.77,2.0,-0.3,90.44,0.6,0.0,0.0,0.0,0.0,27.7,7.6,287.6,1021.0,98.2,0.0,0.1,0.0,False,True,False,False,3,2,Vinnytsia,2022-02-24,06:58:49,17:40:52,Вінницька,0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0.0,0.0,2,0.648733,-0.078386,0.180873,0.059880,0.070008,-0.042071,-0.006712,0.006174,-0.014324,0.004678,-0.034546,0.026839,0.051262,0.052505,0.069154,-0.065115,0.063161,-0.13259,-0.148380,0.167924,-0.069896,0.082404,-0.099159,-0.135181,0.040913,0.067235,-0.000759,0.058867,-0.037716,0.038137,0.020267,0.064787,-0.092394,-0.073454,-0.044226,0.015863,-0.045746,0.052133,-0.060692,0.157277,0.045770,0.153091,0.048066,-0.040708,0.029668,-0.018682,0.045509,0.093437,-0.040995,0.078446,-0.038387,-0.054725,-0.011545,-0.097217,0.008896,-0.047726,0.027129,0.028893,0.040973,0.061139,0.005002,-0.081452,-0.032886,0.071956,0.016690,0.039795,0.046933,-0.017759,0.000617,0.055723,0.001567,-0.065267,0.039934,-0.036891,0.055054,0.077850,-0.027169,0.051738,-0.012014,0.012023,-0.088707,0.027350,0.043625,0.012068,-0.010631,0.054585,-0.036056,-0.057756,-0.029479,0.036439,0.021386,-0.003892,-0.004663,-0.036183,0.014969,-0.000180,0.036404,-0.045506,-0.041311,0.045422,0.034035,0.045637,0.034013,0.002362,-0.075796,-0.009571,-0.035545,0.01706,-0.050099,-0.046210,-0.016780,-0.013202,-0.037655,0.045839,-0.018973,-0.005701,0.049022,-0.020264,0.033857,-0.035811,-0.012768,-0.011943,0.003566,-0.014989,0.034077,-0.013549,-0.027016,-0.005318,0.020995,-0.065815,-0.025836,0.048361,0.013902,0.007758,0.035416,0.017354,0.051423,-0.047020,0.005248,-0.011767,0.013046,0.010118,-0.017252,-0.029334,-0.010031,-0.020943,0.039399,-0.023117,0.000179,-0.014684
5,2022-02-24 02:00:00,2,5.0,0.7,2.8,-0.3,80.5,0.3,100.0,4.17,27.7,82.5,0.77,2.0,-0.3,90.44,0.6,0.0,0.0,0.0,0.0,27.7,7.6,287.6,1021.0,98.2,0.0,0.1,0.0,False,True,False,False,3,2,Vinnytsia,2022-02-24,06:58:49,17:40:52,Вінницька,0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0.0,0.0,2,0.579583,-0.092636,-0.024936,0.148737,0.067631,-0.022840,0.013561,0.027065,-0.037442,-0.035436,-0.015363,0.057749,0.179283,0.195302,-0.021927,0.067237,0.055735,-0.13245,-0.180805,0.022177,0.047934,0.124387,-0.104893,-0.028056,0.011823,-0.057940,0.017698,0.082596,-0.039430,0.008824,-0.008312,0.038742,-0.071414,-0.115007,0.019256,0.055175,-0.023332,0.013635,-0.052078,0.057392,-0.001245,0.182019,-0.013404,-0.044537,-0.019262,0.026267,0.091475,0.006528,0.007382,0.012741,-0.047336,-0.031316,-0.037770,-0.111627,-0.030441,-0.024342,0.072859,0.009923,0.082156,0.049584,-0.039721,-0.070926,-0.020624,0.073648,-0.023476,0.107926,-0.008489,0.047896,-0.012193,0.026755,-0.051663,0.006328,-0.025392,-0.060057,0.006822,0.020465,0.045375,0.068948,0.047465,-0.096006,-0.113087,0.025337,0.021947,0.055621,0.041927,-0.002777,-0.018814,-0.077862,0.037441,0.042639,0.066090,-0.005926,0.022404,-0.031626,0.025406,0.100814,0.073405,-0.031779,-0.095086,-0.031135,-0.020002,-0.043989,-0.091820,0.029670,0.018828,-0.015173,0.030559,-0.02146,-0.044291,0.026559,0.023168,0.017386,-0.044963,0.032709,0.025639,-0.033002,0.017142,-0.031334,0.009681,0.013112,0.061303,0.037710,-0.031997,-0.053227,0.000885,-0.023360,0.063897,0.060482,0.016209,-0.004942,0.031317,-0.038357,-0.007171,0.027314,0.064252,0.036855,0.004244,-0.041335,0.063204,0.000008,-0.011816,0.006371,-0.015602,-0.023692,-0.022085,-0.009336,0.000669,-0.016102,0.022940,-0.018549
6,2022-02-24 03:00:00,2,5.0,0.7,2.8,-0.3,80.5,0.3,100.0,4.17,27.7,82.5,0.77,1.9,-0.3,91.75,0.7,0.0,0.0,0.0,0.0,15.1,7.2,288.9,1021.0,98.8,0.0,0.1,0.0,False,True,False,False,3,3,Vinnytsia,2022-02-24,06:58:49,17:40:52,Вінницька,0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0.0,0.0,3,0.648733,-0.078386,0.180873,0.059880,0.070008,-0.042071,-0.006712,0.006174,-0.014324,0.004678,-0.034546,0.026839,0.051262,0.052505,0.069154,-0.065115,0.063161,-0.13259,-0.148380,0.167924,-0.069896,0.082404,-0.099159,-0.135181,0.040913,0.067235,-0.000759,0.058867,-0.037716,0.038137,0.020267,0.064787,-0.092394,-0.073454,-0.044226,0.015863,-0.045746,0.052133,-0.060692,0.157277,0.045770,0.153091,0.048066,-0.040708,0.029668,-0.018682,0.045509,0.093437,-0.040995,0.078446,-0.038387,-0.054725,-0.011545,-0.097217,0.008896,-0.047726,0.027129,0.028893,0.040973,0.061139,0.005002,-0.081452,-0.032886,0.071956,0.016690,0.039795,0.046933,-0.017759,0.000617,0.055723,0.001567,-0.065267,0.039934,-0.036891,0.055054,0.077850,-0.027169,0.051738,-0.012014,0.012023,-0.088707,0.027350,0.043625,0.012068,-0.010631,0.054585,-0.036056,-0.057756,-0.029479,0.036439,0.021386,-0.003892,-0.004663,-0.036183,0.014969,-0.000180,0.036404,-0.045506,-0.041311,0.045422,0.034035,0.045637,0.034013,0.002362,-0.075796,-0.009571,-0.035545,0.01706,-0.050099,-0.046210,-0.016780,-0.013202,-0.037655,0.045839,-0.018973,-0.005701,0.049022,-0.020264,0.033857,-0.035811,-0.012768,-0.011943,0.003566,-0.014989,0.034077,-0.013549,-0.027016,-0.005318,0.020995,-0.065815,-0.025836,0.048361,0.013902,0.007758,0.035416,0.017354,0.051423,-0.047020,0.005248,-0.011767,0.013046,0.010118,-0.017252,-0.029334,-0.010031,-0.020943,0.039399,-0.023117,0.000179,-0.014684
7,2022-02-24 03:00:00,2,5.0,0.7,2.8,-0.3,80.5,0.3,100.0,4.17,27.7,82.5,0.77,1.9,-0.3,91.75,0.7,0.0,0.0,0.0,0.0,15.1,7.2,288.9,1021.0,98.8,0.0,0.1,0.0,False,True,False,False,3,3,Vinnytsia,2022-02-24,06:58:49,17:40:52,Вінницька,0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0.0,0.0,3,0.579583,-0.092636,-0.024936,0.148737,0.067631,-0.022840,0.013561,0.027065,-0.037442,-0.035436,-0.015363,0.057749,0.179283,0.195302,-0.021927,0.067237,0.055735,-0.13245,-0.180805,0.022177,0.047934,0.124387,-0.104893,-0.028056,0.011823,-0.057940,0.017698,0.082596,-0.039430,0.008824,-0.008312,0.038742,-0.071414,-0.115007,0.019256,0.055175,-0.023332,0.013635,-0.052078,0.057392,-0.001245,0.182019,-0.013404,-0.044537,-0.019262,0.026267,0.091475,0.006528,0.007382,0.012741,-0.047336,-0.031316,-0.037770,-0.111627,-0.030441,-0.024342,0.072859,0.009923,0.082156,0.049584,-0.039721,-0.070926,-0.020624,0.073648,-0.023476,0.107926,-0.008489,0.047896,-0.012193,0.026755,-0.051663,0.006328,-0.025392,-0.060057,0.006822,0.020465,0.045375,0.068948,0.047465,-0.096006,-0.113087,0.025337,0.021947,0.055621,0.041927,-0.002777,-0.018814,-0.077862,0.037441,0.042639,0.066090,-0.005926,0.022404,-0.031626,0.025406,0.100814,0.073405,-0.031779,-0.095086,-0.031135,-0.020002,-0.043989,-0.091820,0.029670,0.018828,-0.015173,0.030559,-0.02146,-0.044291,0.026559,0.023168,0.017386,-0.044963,0.032709,0.025639,-0.033002,0.017142,-0.031334,0.009681,0.013112,0.061303,0.037710,-0.031997,-0.053227,0.000885,-0.023360,0.063897,0.060482,0.016209,-0.004942,0.031317,-0.038357,-0.007171,0.027314,0.064252,0.036855,0.004244,-0.041335,0.063204,0.000008,-0.011816,0.006371,-0.015602,-0.023692,-0.022085,-0.009336,0.000669,-0.016102,0.022940,-0.018549
8,2022-02-24 04:00:00,2,5.0,0.7,2.8,-0.3,80.5,0.3,100.0,4.17,27.7,82.5,0.77,1.8,-0.2,92.40,0.7,0.0,0.0,0.0,0.0,13.7,6.5,290.4,1021.0,100.0,0.0,0.1,0.0,False,True,False,False,3,4,Vinnytsia,2022-02-24,06:58:49,17:40:52,Вінницька,0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0.0,0.0,4,0.648733,-0.078386,0.180873,0.059880,0.070008,-0.042071,-0.006712,0.006174,-0.014324,0.004678,-0.034546,0.026839,0.051262,0.052505,0.069154,-0.065115,0.063161,-0.13259,-0.148380,0.167924,-0.069896,0.082404,-0.099159,-0.135181,0.040913,0.067235,-0.000759,0.058867,-0.037716,0.038137,0.020267,0.064787,-0.092394,-0.073454,-0.044226,0.015863,-0.045746,0.052133,-0.060692,0.157277,0.045770,0.153091,0.048066,-0.040708,0.029668,-0.018682,0.045509,0.093437,-0.040995,0.078446,-0.038387,-0.054725,-0.011545,-0.097217,0.008896,-0.047726,0.027129,0.028893,0.040973,0.061139,0.005002,-0.081452,-0.032886,0.071956,0.016690,0.039795,0.046933,-0.017759,0.000617,0.055723,0.001567,-0.065267,0.039934,-0.036891,0.055054,0.077850,-0.027169,0.051738,-0.012014,0.012023,-0.088707,0.027350,0.043625,0.012068,-0.010631,0.054585,-0.036056,-0.057756,-0.029479,0.036439,0.021386,-0.003892,-0.004663,-0.036183,0.014969,-0.000180,0.036404,-0.045506,-0.041311,0.045422,0.034035,0.045637,0.034013,0.002362,-0.075796,-0.009571,-0.035545,0.01706,-0.050099,-0.046210,-0.016780,-0.013202,-0.037655,0.045839,-0.018973,-0.005701,0.049022,-0.020264,0.033857,-0.035811,-0.012768,-0.011943,0.003566,-0.014989,0.034077,-0.013549,-0.027016,-0.005318,0.020995,-0.065815,-0.025836,0.048361,0.013902,0.007758,0.035416,0.017354,0.051423,-0.047020,0.005248,-0.011767,0.013046,0.010118,-0.017252,-0.029334,-0.010031,-0.020943,0.039399,-0.023117,0.000179,-0.014684
9,2022-02-24 04:00:00,2,5.0,0.7,2.8,-0.3,80.5,0.3,100.0,4.17,27.7,82.5,0.77,1.8,-0.2,92.40,0.7,0.0,0.0,0.0,0.0,13.7,6.5,290.4,1021.0,100.0,0.0,0.1,0.0,False,True,False,False,3,4,Vinnytsia,2022-02-24,06:58:49,17:40:52,Вінницька,0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0.0,0.0,4,0.579583,-0.092636,-0.024936,0.148737,0.067631,-0.022840,0.013561,0.027065,-0.037442,-0.035436,-0.015363,0.057749,0.179283,0.195302,-0.021927,0.067237,0.055735,-0.13245,-0.180805,0.022177,0.047934,0.124387,-0.104893,-0.028056,0.011823,-0.057940,0.017698,0.082596,-0.039430,0.008824,-0.008312,0.038742,-0.071414,-0.115007,0.019256,0.055175,-0.023332,0.013635,-0.052078,0.057392,-0.001245,0.182019,-0.013404,-0.044537,-0.019262,0.026267,0.091475,0.006528,0.007382,0.012741,-0.047336,-0.031316,-0.037770,-0.111627,-0.030441,-0.024342,0.072859,0.009923,0.082156,0.049584,-0.039721,-0.070926,-0.020624,0.073648,-0.023476,0.107926,-0.008489,0.047896,-0.012193,0.026755,-0.051663,0.006328,-0.025392,-0.060057,0.006822,0.020465,0.045375,0.068948,0.047465,-0.096006,-0.113087,0.025337,0.021947,0.055621,0.041927,-0.002777,-0.018814,-0.077862,0.037441,0.042639,0.066090,-0.005926,0.022404,-0.031626,0.025406,0.100814,0.073405,-0.031779,-0.095086,-0.031135,-0.020002,-0.043989,-0.091820,0.029670,0.018828,-0.015173,0.030559,-0.02146,-0.044291,0.026559,0.023168,0.017386,-0.044963,0.032709,0.025639,-0.033002,0.017142,-0.031334,0.009681,0.013112,0.061303,0.037710,-0.031997,-0.053227,0.000885,-0.023360,0.063897,0.060482,0.016209,-0.004942,0.031317,-0.038357,-0.007171,0.027314,0.064252,0.036855,0.004244,-0.041335,0.063204,0.000008,-0.011816,0.006371,-0.015602,-0.023692,-0.022085,-0.009336,0.000669,-0.016102,0.022940,-0.018549

In [23]:
df_final.isna().sum()

datetime_hour       0
region_id           0
day_tempmax         0
day_tempmin         0
day_temp            0
                 ...
isw_topic_145    7416
isw_topic_146    7416
isw_topic_147    7416
isw_topic_148    7416
isw_topic_149    7416
Length: 202, dtype: int64

In [24]:
df_final.tail()

,datetime_hour,region_id,day_tempmax,day_tempmin,day_temp,day_dew,day_humidity,day_precip,day_precipprob,day_precipcover,day_windgust,day_cloudcover,day_moonphase,hour_temp,hour_feelslike,hour_humidity,hour_dew,hour_precip,hour_precipprob,hour_snow,hour_snowdepth,hour_windgust,hour_windspeed,hour_winddir,hour_pressure,hour_cloudcover,hour_solarradiation,hour_solarenergy,hour_uvindex,hour_conditions_simple_Clear,hour_conditions_simple_Cloudy,hour_conditions_simple_Rain,hour_conditions_simple_Snow,day_of_week,hour,city_name,day_datetime,day_sunrise,day_sunset,region_key,alarm_active,alarm_minutes_in_hour,alarm_lag_1,alarm_lag_3,alarm_lag_6,alarm_lag_12,alarms_in_last_24h,is_weekend,is_night,total_active_alarms_lag1,neighbour_alarms,hours_since_last_alarm,isw_topic_0,isw_topic_1,isw_topic_2,isw_topic_3,isw_topic_4,isw_topic_5,isw_topic_6,isw_topic_7,isw_topic_8,isw_topic_9,isw_topic_10,isw_topic_11,isw_topic_12,isw_topic_13,isw_topic_14,isw_topic_15,isw_topic_16,isw_topic_17,isw_topic_18,isw_topic_19,isw_topic_20,isw_topic_21,isw_topic_22,isw_topic_23,isw_topic_24,isw_topic_25,isw_topic_26,isw_topic_27,isw_topic_28,isw_topic_29,isw_topic_30,isw_topic_31,isw_topic_32,isw_topic_33,isw_topic_34,isw_topic_35,isw_topic_36,isw_topic_37,isw_topic_38,isw_topic_39,isw_topic_40,isw_topic_41,isw_topic_42,isw_topic_43,isw_topic_44,isw_topic_45,isw_topic_46,isw_topic_47,isw_topic_48,isw_topic_49,isw_topic_50,isw_topic_51,isw_topic_52,isw_topic_53,isw_topic_54,isw_topic_55,isw_topic_56,isw_topic_57,isw_topic_58,isw_topic_59,isw_topic_60,isw_topic_61,isw_topic_62,isw_topic_63,isw_topic_64,isw_topic_65,isw_topic_66,isw_topic_67,isw_topic_68,isw_topic_69,isw_topic_70,isw_topic_71,isw_topic_72,isw_topic_73,isw_topic_74,isw_topic_75,isw_topic_76,isw_topic_77,isw_topic_78,isw_topic_79,isw_topic_80,isw_topic_81,isw_topic_82,isw_topic_83,isw_topic_84,isw_topic_85,isw_topic_86,isw_topic_87,isw_topic_88,isw_topic_89,isw_topic_90,isw_topic_91,isw_topic_92,isw_topic_93,isw_topic_94,isw_topic_95,isw_topic_96,isw_topic_97,isw_topic_98,isw_topic_99,isw_topic_100,isw_topic_101,isw_topic_102,isw_topic_103,isw_topic_104,isw_topic_105,isw_topic_106,isw_topic_107,isw_topic_108,isw_topic_109,isw_topic_110,isw_topic_111,isw_topic_112,isw_topic_113,isw_topic_114,isw_topic_115,isw_topic_116,isw_topic_117,isw_topic_118,isw_topic_119,isw_topic_120,isw_topic_121,isw_topic_122,isw_topic_123,isw_topic_124,isw_topic_125,isw_topic_126,isw_topic_127,isw_topic_128,isw_topic_129,isw_topic_130,isw_topic_131,isw_topic_132,isw_topic_133,isw_topic_134,isw_topic_135,isw_topic_136,isw_topic_137,isw_topic_138,isw_topic_139,isw_topic_140,isw_topic_141,isw_topic_142,isw_topic_143,isw_topic_144,isw_topic_145,isw_topic_146,isw_topic_147,isw_topic_148,isw_topic_149
844988,2026-03-16 19:00:00,26,11.1,0.1,5.6,-1.8,60.9,0.0,0.0,0.0,25.6,15.5,0.92,7.5,7.5,55.25,-0.9,0.0,0.0,0.0,0.0,10.4,3.6,80.0,1019.0,44.3,5.5,0.1,0.0,False,True,False,False,0,19,Kyiv,2026-03-16,06:09:51,18:04:17,Київ,0,0.000000,0.0,0.0,0.0,0.0,3.0,0,0,8.0,1.0,7,0.763329,0.257908,0.15929,0.046706,0.139619,-0.137105,0.237035,0.090248,0.034309,-0.016405,-0.007182,-0.020786,-0.015444,-0.040635,-0.087929,-0.065333,-0.031703,0.065081,0.107947,0.095459,0.061175,-0.072911,0.100152,-0.004679,0.019504,-0.024268,-0.012686,-0.003419,0.009949,-0.016268,0.050409,-0.067728,-0.001722,0.007696,-0.052572,0.027906,-0.043968,0.009228,-0.022924,-0.026173,0.015389,0.049728,-0.011892,0.035544,-0.040425,-0.015477,0.027806,-0.048095,0.006576,0.033667,-0.053193,0.002926,-0.024577,0.01843,-0.025015,-0.002874,0.015761,-0.006361,0.015737,0.049314,-0.000153,-0.011353,-0.005248,0.02792,0.010209,-0.018895,0.028934,-0.009222,0.014866,0.00056,-0.045952,-0.00898,-0.018907,0.001456,-0.022851,-0.006765,-0.04409,0.009906,0.031205,0.031027,-0.019364,0.001277,-0.009505,0.006802,-0.021599,0.006317,-0.014554,-0.030289,0.010772,-0.024763,-0.028286,0.003788,0.010264,-0.027466,-0.008981,-0.01088,-0.002958,-0.020453,-0.001468,0.024672,0.012768,0.021246,0.022114,-0.013893,0.02284,-0.006963,0.016022,0.015851,-0.012893,-0.005564,-0.005529,0.019039,0.039666,0.010222,0.007122,0.00533,-0.010213,-0.035756,-0.000821,0.003358,0.027891,-0.003919,-0.000622,-0.000815,0.005627,-0.000709,0.00459,-0.014279,0.013812,-0.016632,-0.001279,0.008312,0.016122,0.028116,-0.0168,-0.001338,-0.016748,0.006018,0.011268,-0.004087,-0.024635,-0.002579,-0.007857,-0.023229,-0.002476,0.014476,0.01018,-0.003162,0.001239,0.020061
844989,2026-03-16 20:00:00,26,11.1,0.1,5.6,-1.8,60.9,0.0,0.0,0.0,25.6,15.5,0.92,6.9,6.9,59.27,-0.5,0.0,0.0,0.0,0.0,9.4,4.0,79.6,1021.0,59.3,5.5,0.1,0.0,False,True,False,False,0,20,Kyiv,2026-03-16,06:09:51,18:04:17,Київ,0,0.000000,0.0,0.0,0.0,1.0,3.0,0,0,11.0,1.0,8,0.763329,0.257908,0.15929,0.046706,0.139619,-0.137105,0.237035,0.090248,0.034309,-0.016405,-0.007182,-0.020786,-0.015444,-0.040635,-0.087929,-0.065333,-0.031703,0.065081,0.107947,0.095459,0.061175,-0.072911,0.100152,-0.004679,0.019504,-0.024268,-0.012686,-0.003419,0.009949,-0.016268,0.050409,-0.067728,-0.001722,0.007696,-0.052572,0.027906,-0.043968,0.009228,-0.022924,-0.026173,0.015389,0.049728,-0.011892,0.035544,-0.040425,-0.015477,0.027806,-0.048095,0.006576,0.033667,-0.053193,0.002926,-0.024577,0.01843,-0.025015,-0.002874,0.015761,-0.006361,0.015737,0.049314,-0.000153,-0.011353,-0.005248,0.02792,0.010209,-0.018895,0.028934,-0.009222,0.014866,0.00056,-0.045952,-0.00898,-0.018907,0.001456,-0.022851,-0.006765,-0.04409,0.009906,0.031205,0.031027,-0.019364,0.001277,-0.009505,0.006802,-0.021599,0.006317,-0.014554,-0.030289,0.010772,-0.024763,-0.028286,0.003788,0.010264,-0.027466,-0.008981,-0.01088,-0.002958,-0.020453,-0.001468,0.024672,0.012768,0.021246,0.022114,-0.013893,0.02284,-0.006963,0.016022,0.015851,-0.012893,-0.005564,-0.005529,0.019039,0.039666,0.010222,0.007122,0.00533,-0.010213,-0.035756,-0.000821,0.003358,0.027891,-0.003919,-0.000622,-0.000815,0.005627,-0.000709,0.00459,-0.014279,0.013812,-0.016632,-0.001279,0.008312,0.016122,0.028116,-0.0168,-0.001338,-0.016748,0.006018,0.011268,-0.004087,-0.024635,-0.002579,-0.007857,-0.023229,-0.002476,0.014476,0.01018,-0.003162,0.001239,0.020061
844990,2026-03-16 21:00:00,26,11.1,0.1,5.6,-1.8,60.9,0.0,0.0,0.0,25.6,15.5,0.92,6.1,6.1,62.62,-0.5,0.0,0.0,0.0,0.0,10.1,3.6,88.3,1021.0,39.4,5.5,0.1,0.0,False,True,False,False,0,21,Kyiv,2026-03-16,06:09:51,18:04:17,Київ,0,0.000000,0.0,0.0,0.0,1.0,3.0,0,0,8.0,0.0,9,0.763329,0.257908,0.15929,0.046706,0.139619,-0.137105,0.237035,0.090248,0.034309,-0.016405,-0.007182,-0.020786,-0.015444,-0.040635,-0.087929,-0.065333,-0.031703,0.065081,0.107947,0.095459,0.061175,-0.072911,0.100152,-0.004679,0.019504,-0.024268,-0.012686,-0.003419,0.009949,-0.016268,0.050409,-0.067728,-0.001722,0.007696,-0.052572,0.027906,-0.043968,0.009228,-0.022924,-0.026173,0.015389,0.049728,-0.011892,0.035544,-0.040425,-0.015477,0.027806,-0.048095,0.006576,0.033667,-0.053193,0.002926,-0.024577,0.01843,-0.025015,-0.002874,0.015761,-0.006361,0.015737,0.049314,-0.000153,-0.011353,-0.005248,0.02792,0.010209,-0.018895,0.028934,-0.009222,0.014866,0.00056,-0.045952,-0.00898,-0.018907,0.001456,-0.022851,-0.006765,-0.04409,0.009906,0.031205,0.031027,-0.019364,0.001277,-0.009505,0.006802,-0.021599,0.006317,-0.014554,-0.030289,0.010772,-0.024763,-0.028286,0.003788,0.010264,-0.027466,-0.008981,-0.01088,-0.002958,-0.020453,-0.001468,0.024672,0.012768,0.021246,0.022114,-0.013893,0.02284,-0.006963,0.016022,0.015851,-0.012893,-0.005564,-0.005529,0.019039,0.039666,0.010222,0.007122,0.00533,-0.010213,-0.035756,-0.000821,0.003358,0.027891,-0.003919,-0.000622,-0.000815,0.005627,-0.000709,0.00459,-0.014279,0.013812,-0.016632,-0.001279,0.008312,0.016122,0.028116,-0.0168,-0.001338,-0.016748,0.006018,0.011268,-0.004087,-0.024635,-0.002579,-0.007857,-0.023229,-0.002476,0.014476,0.01018,-0.003162,0.001239,0.020061
844991,2026-03-16 22:00:00,26,11.1,0.1,5.6,-1.8,60.9,0.0,0.0,0.0,25.6,15.5,0.92,5.3,5.3,65.23,-0.7,0.0,0.0,0.0,0.0,9.0,2.5,85.6,1021.0,19.4,5.5,0.1,0.0,True,False,False,False,0,22,Kyiv,2026-03-16,06:09:51,18:04:17,Київ,1,25.650000,0.0,0.0,0.0,0.0,3.0,0,0,9.0,0.0,10,0.763329,0.257908,0.15929,0.046706,0.139619,-0.137105,0.237035,0.090248,0.034309,-0.016405,-0.007182,-0.020786,-0.015444,-0.040635,-0.087929,-0.065333,-0.031703,0.065081,0.107947,0.095459,0.061175,-0.072911,0.100152,-0.004679,0.019504,-0.024268,-0.012686,-0.003419,0.009949,-0.016268,0.050409,-0.067728,-0.001722,0.007696,-0.052572,0.027906,-0.043968,0.009228,-0.022924,-0.026173,0.015389,0.049728,-0.011892,0.035544,-0.040425,-0.015477,0.027806,-0.048095,0.006576,0.033667,-0.053193,0.002926,-0.024577,0.01843,-0.025015,-0.002874,0.015761,-0.006361,0.015737,0.049314,-0.000153,-0.011353,-0.005248,0.02792,0.010209,-0.018895,0.028934,-0.009222,0.014866,0.00056,-0.045952,-0.00898,-0.018907,0.001456,-0.022851,-0.006765,-0.04409,0.009906,0.031205,0.031027,-0.019364,0.001277,-0.009505,0.006802,-0.021599,0.006317,-0.014554,-0.030289,0.010772,-0.024763,-0.028286,0.003788,0.010264,-0.027466,-0.008981,-0.01088,-0.002958,-0.020453,-0.001468,0.024672,0.012768,0.021246,0.022114,-0.013893,0.02284,-0.006963,0.016022,0.015851,-0.012893,-0.005564,-0.005529,0.019039,0.039666,0.010222,0.007122,0.00533,-0.010213,-0.035756,-0.000821,0.003358,0.027891,-0.003919,-0.000622,-0.000815,0.005627,-0.000709,0.00459,-0.014279,0.013812,-0.016632,-0.001279,0.008312,0.016122,0.028116,-0.0168,-0.001338,-0.016748,0.006018,0.011268,-0.004087,-0.024635,-0.002579,-0.007857,-0.023229,-0.002476,0.014476,0.01018,-0.003162,0.001239,0.020061
844992,2026-03-16 23:00:00,26,11.1,0.1,5.6,-1.8,60.9,0.0,0.0,0.0,25.6,15.5,0.92,4.7,4.7,66.06,-1.1,0.0,0.0,0.0,0.0,5.8,2.2,63.2,1021.0,10.6,5.5,0.1,0.0,True,False,False,False,0,23,Kyiv,2026-03-16,06:09:51,18:04:17,Київ,1,17.216667,1.0,0.0,0.0,1.0,4.0,0,1,10.0,1.0,0,0.763329,0.257908,0.15929,0.046706,0.139619,-0.137105,0.237035,0.090248,0.034309,-0.016405,-0.007182,-0.020786,-0.015444,-0.040635,-0.087929,-0.065333,-0.031703,0.065081,0.107947,0.095459,0.061175,-0.072911,0.100152,-0.004679,0.019504,-0.024268,-0.012686,-0.003419,0.009949,-0.016268,0.050409,-0.067728,-0.001722,0.007696,-0.052572,0.027906,-0.043968,0.009228,-0.022924,-0.026173,0.015389,0.049728,-0.011892,0.035544,-0.040425,-0.015477,0.027806,-0.048095,0.006576,0.033667,-0.053193,0.002926,-0.024577,0.01843,-0.025015,-0.002874,0.015761,-0.006361,0.015737,0.049314,-0.000153,-0.011353,-0.005248,0.02792,0.010209,-0.018895,0.028934,-0.009222,0.014866,0.00056,-0.045952,-0.00898,-0.018907,0.001456,-0.022851,-0.006765,-0.04409,0.009906,0.031205,0.031027,-0.019364,0.001277,-0.009505,0.006802,-0.021599,0.006317,-0.014554,-0.030289,0.010772,-0.024763,-0.028286,0.003788,0.010264,-0.027466,-0.008981,-0.01088,-0.002958,-0.020453,-0.001468,0.024672,0.012768,0.021246,0.022114,-0.013893,0.02284,-0.006963,0.016022,0.015851,-0.012893,-0.005564,-0.005529,0.019039,0.039666,0.010222,0.007122,0.00533,-0.010213,-0.035756,-0.000821,0.003358,0.027891,-0.003919,-0.000622,-0.000815,0.005627,-0.000709,0.00459,-0.014279,0.013812,-0.016632,-0.001279,0.008312,0.016122,0.028116,-0.0168,-0.001338,-0.016748,0.006018,0.011268,-0.004087,-0.024635,-0.002579,-0.007857,-0.023229,-0.002476,0.014476,0.01018,-0.003162,0.001239,0.020061

In [25]:
df_final.fillna(0, inplace=True)

,datetime_hour,region_id,day_tempmax,day_tempmin,day_temp,day_dew,day_humidity,day_precip,day_precipprob,day_precipcover,day_windgust,day_cloudcover,day_moonphase,hour_temp,hour_feelslike,hour_humidity,hour_dew,hour_precip,hour_precipprob,hour_snow,hour_snowdepth,hour_windgust,hour_windspeed,hour_winddir,hour_pressure,hour_cloudcover,hour_solarradiation,hour_solarenergy,hour_uvindex,hour_conditions_simple_Clear,hour_conditions_simple_Cloudy,hour_conditions_simple_Rain,hour_conditions_simple_Snow,day_of_week,hour,city_name,day_datetime,day_sunrise,day_sunset,region_key,alarm_active,alarm_minutes_in_hour,alarm_lag_1,alarm_lag_3,alarm_lag_6,alarm_lag_12,alarms_in_last_24h,is_weekend,is_night,total_active_alarms_lag1,neighbour_alarms,hours_since_last_alarm,isw_topic_0,isw_topic_1,isw_topic_2,isw_topic_3,isw_topic_4,isw_topic_5,isw_topic_6,isw_topic_7,isw_topic_8,isw_topic_9,isw_topic_10,isw_topic_11,isw_topic_12,isw_topic_13,isw_topic_14,isw_topic_15,isw_topic_16,isw_topic_17,isw_topic_18,isw_topic_19,isw_topic_20,isw_topic_21,isw_topic_22,isw_topic_23,isw_topic_24,isw_topic_25,isw_topic_26,isw_topic_27,isw_topic_28,isw_topic_29,isw_topic_30,isw_topic_31,isw_topic_32,isw_topic_33,isw_topic_34,isw_topic_35,isw_topic_36,isw_topic_37,isw_topic_38,isw_topic_39,isw_topic_40,isw_topic_41,isw_topic_42,isw_topic_43,isw_topic_44,isw_topic_45,isw_topic_46,isw_topic_47,isw_topic_48,isw_topic_49,isw_topic_50,isw_topic_51,isw_topic_52,isw_topic_53,isw_topic_54,isw_topic_55,isw_topic_56,isw_topic_57,isw_topic_58,isw_topic_59,isw_topic_60,isw_topic_61,isw_topic_62,isw_topic_63,isw_topic_64,isw_topic_65,isw_topic_66,isw_topic_67,isw_topic_68,isw_topic_69,isw_topic_70,isw_topic_71,isw_topic_72,isw_topic_73,isw_topic_74,isw_topic_75,isw_topic_76,isw_topic_77,isw_topic_78,isw_topic_79,isw_topic_80,isw_topic_81,isw_topic_82,isw_topic_83,isw_topic_84,isw_topic_85,isw_topic_86,isw_topic_87,isw_topic_88,isw_topic_89,isw_topic_90,isw_topic_91,isw_topic_92,isw_topic_93,isw_topic_94,isw_topic_95,isw_topic_96,isw_topic_97,isw_topic_98,isw_topic_99,isw_topic_100,isw_topic_101,isw_topic_102,isw_topic_103,isw_topic_104,isw_topic_105,isw_topic_106,isw_topic_107,isw_topic_108,isw_topic_109,isw_topic_110,isw_topic_111,isw_topic_112,isw_topic_113,isw_topic_114,isw_topic_115,isw_topic_116,isw_topic_117,isw_topic_118,isw_topic_119,isw_topic_120,isw_topic_121,isw_topic_122,isw_topic_123,isw_topic_124,isw_topic_125,isw_topic_126,isw_topic_127,isw_topic_128,isw_topic_129,isw_topic_130,isw_topic_131,isw_topic_132,isw_topic_133,isw_topic_134,isw_topic_135,isw_topic_136,isw_topic_137,isw_topic_138,isw_topic_139,isw_topic_140,isw_topic_141,isw_topic_142,isw_topic_143,isw_topic_144,isw_topic_145,isw_topic_146,isw_topic_147,isw_topic_148,isw_topic_149
0,2022-02-24 00:00:00,2,5.0,0.7,2.8,-0.3,80.5,0.3,100.0,4.17,27.7,82.5,0.77,2.1,-0.5,91.76,0.9,0.0,0.0,0.0,0.0,16.6,8.6,279.6,1021.0,91.1,0.0,0.1,0.0,False,True,False,False,3,0,Vinnytsia,2022-02-24,06:58:49,17:40:52,Вінницька,0,0.000000,0.0,0.0,0.0,0.0,0.0,0,1,0.0,0.0,0,0.648733,-0.078386,0.180873,0.059880,0.070008,-0.042071,-0.006712,0.006174,-0.014324,0.004678,-0.034546,0.026839,0.051262,0.052505,0.069154,-0.065115,0.063161,-0.132590,-0.148380,0.167924,-0.069896,0.082404,-0.099159,-0.135181,0.040913,0.067235,-0.000759,0.058867,-0.037716,0.038137,0.020267,0.064787,-0.092394,-0.073454,-0.044226,0.015863,-0.045746,0.052133,-0.060692,0.157277,0.045770,0.153091,0.048066,-0.040708,0.029668,-0.018682,0.045509,0.093437,-0.040995,0.078446,-0.038387,-0.054725,-0.011545,-0.097217,0.008896,-0.047726,0.027129,0.028893,0.040973,0.061139,0.005002,-0.081452,-0.032886,0.071956,0.016690,0.039795,0.046933,-0.017759,0.000617,0.055723,0.001567,-0.065267,0.039934,-0.036891,0.055054,0.077850,-0.027169,0.051738,-0.012014,0.012023,-0.088707,0.027350,0.043625,0.012068,-0.010631,0.054585,-0.036056,-0.057756,-0.029479,0.036439,0.021386,-0.003892,-0.004663,-0.036183,0.014969,-0.000180,0.036404,-0.045506,-0.041311,0.045422,0.034035,0.045637,0.034013,0.002362,-0.075796,-0.009571,-0.035545,0.017060,-0.050099,-0.046210,-0.016780,-0.013202,-0.037655,0.045839,-0.018973,-0.005701,0.049022,-0.020264,0.033857,-0.035811,-0.012768,-0.011943,0.003566,-0.014989,0.034077,-0.013549,-0.027016,-0.005318,0.020995,-0.065815,-0.025836,0.048361,0.013902,0.007758,0.035416,0.017354,0.051423,-0.047020,0.005248,-0.011767,0.013046,0.010118,-0.017252,-0.029334,-0.010031,-0.020943,0.039399,-0.023117,0.000179,-0.014684
1,2022-02-24 00:00:00,2,5.0,0.7,2.8,-0.3,80.5,0.3,100.0,4.17,27.7,82.5,0.77,2.1,-0.5,91.76,0.9,0.0,0.0,0.0,0.0,16.6,8.6,279.6,1021.0,91.1,0.0,0.1,0.0,False,True,False,False,3,0,Vinnytsia,2022-02-24,06:58:49,17:40:52,Вінницька,0,0.000000,0.0,0.0,0.0,0.0,0.0,0,1,0.0,0.0,0,0.579583,-0.092636,-0.024936,0.148737,0.067631,-0.022840,0.013561,0.027065,-0.037442,-0.035436,-0.015363,0.057749,0.179283,0.195302,-0.021927,0.067237,0.055735,-0.132450,-0.180805,0.022177,0.047934,0.124387,-0.104893,-0.028056,0.011823,-0.057940,0.017698,0.082596,-0.039430,0.008824,-0.008312,0.038742,-0.071414,-0.115007,0.019256,0.055175,-0.023332,0.013635,-0.052078,0.057392,-0.001245,0.182019,-0.013404,-0.044537,-0.019262,0.026267,0.091475,0.006528,0.007382,0.012741,-0.047336,-0.031316,-0.037770,-0.111627,-0.030441,-0.024342,0.072859,0.009923,0.082156,0.049584,-0.039721,-0.070926,-0.020624,0.073648,-0.023476,0.107926,-0.008489,0.047896,-0.012193,0.026755,-0.051663,0.006328,-0.025392,-0.060057,0.006822,0.020465,0.045375,0.068948,0.047465,-0.096006,-0.113087,0.025337,0.021947,0.055621,0.041927,-0.002777,-0.018814,-0.077862,0.037441,0.042639,0.066090,-0.005926,0.022404,-0.031626,0.025406,0.100814,0.073405,-0.031779,-0.095086,-0.031135,-0.020002,-0.043989,-0.091820,0.029670,0.018828,-0.015173,0.030559,-0.021460,-0.044291,0.026559,0.023168,0.017386,-0.044963,0.032709,0.025639,-0.033002,0.017142,-0.031334,0.009681,0.013112,0.061303,0.037710,-0.031997,-0.053227,0.000885,-0.023360,0.063897,0.060482,0.016209,-0.004942,0.031317,-0.038357,-0.007171,0.027314,0.064252,0.036855,0.004244,-0.041335,0.063204,0.000008,-0.011816,0.006371,-0.015602,-0.023692,-0.022085,-0.009336,0.000669,-0.016102,0.022940,-0.018549
2,2022-02-24 01:00:00,2,5.0,0.7,2.8,-0.3,80.5,0.3,100.0,4.17,27.7,82.5,0.77,2.1,-0.4,89.80,0.6,0.0,0.0,0.0,0.0,16.6,8.3,289.2,1021.0,97.9,0.0,0.1,0.0,False,True,False,False,3,1,Vinnytsia,2022-02-24,06:58:49,17:40:52,Вінницька,0,0.000000,0.0,0.0,0.0,0.0,0.0,0,1,0.0,0.0,1,0.648733,-0.078386,0.180873,0.059880,0.070008,-0.042071,-0.006712,0.006174,-0.014324,0.004678,-0.034546,0.026839,0.051262,0.052505,0.069154,-0.065115,0.063161,-0.132590,-0.148380,0.167924,-0.069896,0.082404,-0.099159,-0.135181,0.040913,0.067235,-0.000759,0.058867,-0.037716,0.038137,0.020267,0.064787,-0.092394,-0.073454,-0.044226,0.015863,-0.045746,0.052133,-0.060692,0.157277,0.045770,0.153091,0.048066,-0.040708,0.029668,-0.018682,0.045509,0.093437,-0.040995,0.078446,-0.038387,-0.054725,-0.011545,-0.097217,0.008896,-0.047726,0.027129,0.028893,0.040973,0.061139,0.005002,-0.081452,-0.032886,0.071956,0.016690,0.039795,0.046933,-0.017759,0.000617,0.055723,0.001567,-0.065267,0.039934,-0.036891,0.055054,0.077850,-0.027169,0.051738,-0.012014,0.012023,-0.088707,0.027350,0.043625,0.012068,-0.010631,0.054585,-0.036056,-0.057756,-0.029479,0.036439,0.021386,-0.003892,-0.004663,-0.036183,0.014969,-0.000180,0.036404,-0.045506,-0.041311,0.045422,0.034035,0.045637,0.034013,0.002362,-0.075796,-0.009571,-0.035545,0.017060,-0.050099,-0.046210,-0.016780,-0.013202,-0.037655,0.045839,-0.018973,-0.005701,0.049022,-0.020264,0.033857,-0.035811,-0.012768,-0.011943,0.003566,-0.014989,0.034077,-0.013549,-0.027016,-0.005318,0.020995,-0.065815,-0.025836,0.048361,0.013902,0.007758,0.035416,0.017354,0.051423,-0.047020,0.005248,-0.011767,0.013046,0.010118,-0.017252,-0.029334,-0.010031,-0.020943,0.039399,-0.023117,0.000179,-0.014684
3,2022-02-24 01:00:00,2,5.0,0.7,2.8,-0.3,80.5,0.3,100.0,4.17,27.7,82.5,0.77,2.1,-0.4,89.80,0.6,0.0,0.0,0.0,0.0,16.6,8.3,289.2,1021.0,97.9,0.0,0.1,0.0,False,True,False,False,3,1,Vinnytsia,2022-02-24,06:58:49,17:40:52,Вінницька,0,0.000000,0.0,0.0,0.0,0.0,0.0,0,1,0.0,0.0,1,0.579583,-0.092636,-0.024936,0.148737,0.067631,-0.022840,0.013561,0.027065,-0.037442,-0.035436,-0.015363,0.057749,0.179283,0.195302,-0.021927,0.067237,0.055735,-0.132450,-0.180805,0.022177,0.047934,0.124387,-0.104893,-0.028056,0.011823,-0.057940,0.017698,0.082596,-0.039430,0.008824,-0.008312,0.038742,-0.071414,-0.115007,0.019256,0.055175,-0.023332,0.013635,-0.052078,0.057392,-0.001245,0.182019,-0.013404,-0.044537,-0.019262,0.026267,0.091475,0.006528,0.007382,0.012741,-0.047336,-0.031316,-0.037770,-0.111627,-0.030441,-0.024342,0.072859,0.009923,0.082156,0.049584,-0.039721,-0.070926,-0.020624,0.073648,-0.023476,0.107926,-0.008489,0.047896,-0.012193,0.026755,-0.051663,0.006328,-0.025392,-0.060057,0.006822,0.020465,0.045375,0.068948,0.047465,-0.096006,-0.113087,0.025337,0.021947,0.055621,0.041927,-0.002777,-0.018814,-0.077862,0.037441,0.042639,0.066090,-0.005926,0.022404,-0.031626,0.025406,0.100814,0.073405,-0.031779,-0.095086,-0.031135,-0.020002,-0.043989,-0.091820,0.029670,0.018828,-0.015173,0.030559,-0.021460,-0.044291,0.026559,0.023168,0.017386,-0.044963,0.032709,0.025639,-0.033002,0.017142,-0.031334,0.009681,0.013112,0.061303,0.037710,-0.031997,-0.053227,0.000885,-0.023360,0.063897,0.060482,0.016209,-0.004942,0.031317,-0.038357,-0.007171,0.027314,0.064252,0.036855,0.004244,-0.041335,0.063204,0.000008,-0.011816,0.006371,-0.015602,-0.023692,-0.022085,-0.009336,0.000669,-0.016102,0.022940,-0.018549
4,2022-02-24 02:00:00,2,5.0,0.7,2.8,-0.3,80.5,0.3,100.0,4.17,27.7,82.5,0.77,2.0,-0.3,90.44,0.6,0.0,0.0,0.0,0.0,27.7,7.6,287.6,1021.0,98.2,0.0,0.1,0.0,False,True,False,False,3,2,Vinnytsia,2022-02-24,06:58:49,17:40:52,Вінницька,0,0.000000,0.0,0.0,0.0,0.0,0.0,0,1,0.0,0.0,2,0.648733,-0.078386,0.180873,0.059880,0.070008,-0.042071,-0.006712,0.006174,-0.014324,0.004678,-0.034546,0.026839,0.051262,0.052505,0.069154,-0.065115,0.063161,-0.132590,-0.148380,0.167924,-0.069896,0.082404,-0.099159,-0.135181,0.040913,0.067235,-0.000759,0.058867,-0.037716,0.038137,0.020267,0.064787,-0.092394,-0.073454,-0.044226,0.015863,-0.045746,0.052133,-0.060692,0.157277,0.045770,0.153091,0.048066,-0.040708,0.029668,-0.018682,0.045509,0.093437,-0.040995,0.078446,-0.038387,-0.054725,-0.011545,-0.097217,0.008896,-0.047726,0.027129,0.028893,0.040973,0.061139,0.005002,-0.081452,-0.032886,0.071956,0.016690,0.039795,0.046933,-0.017759,0.000617,0.055723,0.001567,-0.065267,0.039934,-0.036891,0.055054,0.077850,-0.027169,0.051738,-0.012014,0.012023,-0.088707,0.027350,0.043625,0.012068,-0.010631,0.054585,-0.036056,-0.057756,-0.029479,0.036439,0.021386,-0.003892,-0.004663,-0.036183,0.014969,-0.000180,0.036404,-0.045506,-0.041311,0.045422,0.034035,0.045637,0.034013,0.002362,-0.075796,-0.009571,-0.035545,0.017060,-0.050099,-0.046210,-0.016780,-0.013202,-0.037655,0.045839,-0.018973,-0.005701,0.049022,-0.020264,0.033857,-0.035811,-0.012768,-0.011943,0.003566,-0.014989,0.034077,-0.013549,-0.027016,-0.005318,0.020995,-0.065815,-0.025836,0.048361,0.013902,0.007758,0.035416,0.017354,0.051423,-0.047020,0.005248,-0.011767,0.013046,0.010118,-0.017252,-0.029334,-0.010031,-0.020943,0.039399,-0.023117,0.000179,-0.014684
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
844988,2026-03-16 19:00:00,26,11.1,0.1,5.6,-1.8,60.9,0.0,0.0,0.00,25.6,15.5,0.92,7.5,7.5,55.25,-0.9,0.0,0.0,0.0,0.0,10.4,3.6,80.0,1019.0,44.3,5.5,0.1,0.0,False,True,False,False,0,19,Kyiv,2026-03-16,06:09:51,18:04:17,Київ,0,0.000000,0.0,0.0,0.0,0.0,3.0,0,0,8.0,1.0,7,0.763329,0.257908,0.159290,0.046706,0.139619,-0.137105,0.237035,0.090248,0.034309,-0.016405,-0.007182,-0.020786,-0.015444,-0.040635,-0.087929,-0.065333,-0.031703,0.065081,0.107947,0.095459,0.061175,-0.072911,0.100152,-0.004679,0.019504,-0.024268,-0.012686,-0.003419,0.009949,-0.016268,0.050409,-0.067728,-0.001722,0.007696,-0.052572,0.027906,-0.043968,0.009228,-0.022924,-0.026173,0.015389,0.049728,-0.011892,0.035544,-0.040425,-0.015477,0.027806,-0.048095,0.006576,0.033667,-0.053193,0.002926,-0.024577,0.018430,-0.025015,-0.002874,0.015761,-0.006361,0.015737,0.049314,-0.000153,-0.011353,-0.005248,0.027920,0.010209,-0.018895,0.028934,-0.009222,0.014866,0.000560,-0.045952,-0.008980,-0.018907,0.001456,-0.022851,-0.006765,-0.044090,0.009906,0.031205,0.031027,-0.019364,0.001277,-0.009505,0.006802,-0.021599,0.006317,-0.014554,-0.030289,0.010772,-0.024763,-0.028286,0.003788,0.010264,-0.027466,-0.008981,-0.010880,-0.002958,-0.020453,-0.001468,0.024672,0.012768,0.021246,0.022114,-0.013893,0.022840,-0.006963,0.016022,0.015851,-0.012893,-0.005564,-0.005529,0.019039,0.039666,0.010222,0.007122,0.005330,-0.010213,-0.035756,-0.000821,0.003358,0.027891,-0.003919,-0.000622,-0.000815,0.005627,-0.000709,0.004590,-0.014279,0.013812,-0.016632,-0.001279,0.008312,0.016122,0.028116,-0.016800,-0.001338,-0.016748,0.006018,0.011268,-0.004087,-0.024635,-0.002579,-0.007857,-0.023229,-0.002476,0.014476,0.010180,-0.003162,0.001239,0.020061
844989,2026-03-16 20:00:00,26,11.1,0.1,5.6,-1.8,60.9,0.0,0.0,0.00,25.6,15.5,0.92,6.9,6.9,59.27,-0.5,0.0,0.0,0.0,0.0,9.4,4.0,79.6,1021.0,59.3,5.5,0.1,0.0,False,True,False,False,0,20,Kyiv,2026-03-16,06:09:51,18:04:17,Київ,0,0.000000,0.0,0.0,0.0,1.0,3.0,0,0,11.0,1.0,8,0.763329,0.257908,0.159290,0.046706,0.139619,-0.137105,0.237035,0.090248,0.034309,-0.016405,-0.007182,-0.020786,-0.015444,-0.040635,-0.087929,-0.065333,-0.031703,0.065081,0.107947,0.095459,0.061175,-0.072911,0.100152,-0.004679,0.019504,-0.024268,-0.012686,-0.003419,0.009949,-0.016268,0.050409,-0.067728,-0.001722,0.007696,-0.052572,0.027906,-0.043968,0.009228,-0.022924,-0.026173,0.015389,0.049728,-0.011892,0.035544,-0.040425,-0.015477,0.027806,-0.048095,0.006576,0.033667,-0.053193,0.002926,-0.024577,0.018430,-0.025015,-0.002874,0.015761,-0.006361,0.015737,0.049314,-0.000153,-0.011353,-0.005248,0.027920,0.010209,-0.018895,0.028934,-0.009222,0.014866,0.000560,-0.045952,-0.008980,-0.018907,0.001456,-0.022851,-0.006765,-0.044090,0.009906,0.031205,0.031027,-0.019364,0.001277,-0.009505,0.006802,-0.021599,0.006317,-0.014554,-0.030289,0.010772,-0.024763,-0.028286,0.003788,0.010264,-0.027466,-0.008981,-0.010880,-0.002958,-0.020453,-0.001468,0.024672,0.012768,0.021246,0.022114,-0.013893,0.022840,-0.006963,0.016022,0.015851,-0.012893,-0.005564,-0.005529,0.019039,0.039666,0.010222,0.007122,0.005330,-0.010213,-0.035756,-0.000821,0.003358,0.027891,-0.003919,-0.000622,-0.000815,0.005627,-0.000709,0.004590,-0.014279,0.013812,-0.016632,-0.001279,0.008312,0.016122,0.028116,-0.016800,-0.001338,-0.016748,0.006018,0.011268,-0.004087,-0.024635,-0.002579,-0.007857,-0.023229,-0.002476,0.014476,0.010180,-0.003162,0.001239,0.020061
844990,2026-03-16 21:00:00,26,11.1,0.1,5.6,-1.8,60.9,0.0,0.0,0.00,25.6,15.5,0.92,6.1,6.1,62.62,-0.5,0.0,0.0,0.0,0.0,10.1,3.6,88.3,1021.0,39.4,5.5,0.1,0.0,False,True,False,False,0,21,Kyiv,2026-03-16,06:09:51,18:04:17,Київ,0,0.000000,0.0,0.0,0.0,1.0,3.0,0,0,8.0,0.0,9,0.763329,0.257908,0.159290,0.046706,0.139619,-0.137105,0.237035,0.090248,0.034309,-0.016405,-0.007182,-0.020786,-0.015444,-0.040635,-0.087929,-0.065333,-0.031703,0.065081,0.107947,0.095459,0.061175,-0.072911,0.100152,-0.004679,0.019504,-0.024268,-0.012686,-0.003419,0.009949,-0.016268,0.050409,-0.067728,-0.001722,0.007696,-0.052572,0.027906,-0.043968,0.009228,-0.022924,-0.026173,0.015389,0.049728,-0.011892,0.035544,-0.040425,-0.015477,0.027806,-0.048095,0.006576,0.033667,-0.053193,0.002926,-0.024577,0.018430,-0.025015,-0.002874,0.015761,-0.006361,0.015737,0.049314,-0.000153,-0.011353,-0.005248,0.027920,0.010209,-0.018895,0.028934,-0.009222,0.014866,0.000560,-0.045952,-0.008980,-0.018907,0.001456,-0.022851,-0.006765,-0.044090,0.009906,0.031205,0.031027,-0.019364,0.001277,-0.009505,0.006802,-0.021599,0.006317,-0.014554,-0.030289,0.010772,-0.024763,-0.028286,0.003788,0.010264,-0.027466,-0.008981,-0.010880,-0.002958,-0.020453,-0.001468,0.024672,0.012768,0.021246,0.022114,-0.013893,0.022840,-0.006963,0.016022,0.015851,-0.012893,-0.005564,-0.005529,0.019039,0.039666,0.010222,0.007122,0.005330,-0.010213,-0.035756,-0.000821,0.003358,0.027891,-0.003919,-0.000622,-0.000815,0.005627,-0.000709,0.004590,-0.014279,0.013812,-0.016632,-0.001279,0.008312,0.016122,0.028116,-0.016800,-0.001338,-0.016748,0.006018,0.011268,-0.004087,-0.024635,-0.002579,-0.007857,-0.023229,-0.002476,0.014476,0.010180,-0.003162,0.001239,0.020061
844991,2026-03-16 22:00:00,26,11.1,0.1,5.6,-1.8,60.9,0.0,0.0,0.00,25.6,15.5,0.92,5.3,5.3,65.23,-0.7,0.0,0.0,0.0,0.0,9.0,2.5,85.6,1021.0,19.4,5.5,0.1,0.0,True,False,False,False,0,22,Kyiv,2026-03-16,06:09:51,18:04:17,Київ,1,25.650000,0.0,0.0,0.0,0.0,3.0,0,0,9.0,0.0,10,0.763329,0.257908,0.159290,0.046706,0.139619,-0.137105,0.237035,0.090248,0.034309,-0.016405,-0.007182,-0.020786,-0.015444,-0.040635,-0.087929,-0.065333,-0.031703,0.065081,0.107947,0.095459,0.061175,-0.072911,0.100152,-0.004679,0.019504,-0.024268,-0.012686,-0.003419,0.009949,-0.016268,0.050409,-0.067728,-0.001722,0.007696,-0.052572,0.027906,-0.043968,0.009228,-0.022924,-0.026173,0.015389,0.049728,-0.011892,0.035544,-0.040425,-0.015477,0.027806,-0.048095,0.006576,0.033667,-0.053193,0.002926,-0.024577,0.018430,-0.025015,-0.002874,0.015761,-0.006361,0.015737,0.049314,-0.000153,-0.011353,-0.005248,0.027920,0.010209,-0.018895,0.028934,-0.009222,0.014866,0.000560,-0.045952,-0.008980,-0.018907,0.001456,-0.022851,-0.006765,-0.044090,0.009906,0.031205,0.031027,-0.019364,0.001277,-0.009505,0.006802,-0.021599,0.006317,-0.014554,-0.030289,0.010772,-0.024763,-0.028286,0.003788,0.010264,-0.027466,-0.008981,-0.010880,-0.002958,-0.020453,-0.001468,0.024672,0.012768,0.021246,0.022114,-0.013893,0.022840,-0.006963,0.016022,0.015851,-0.012893,-0.005564,-0.005529,0.019039,0.039666,0.010222,0.007122,0.005330,-0.010213,-0.035756,-0.000821,0.003358,0.027891,-0.003919,-0.000622,-0.000815,0.005627,-0.000709,0.004590,-0.014279,0.013812,-0.016632,-0.001279,0.008312,0.016122,0.028116,-0.016800,-0.001338,-0.016748,0.006018,0.011268,-0.004087,-0.024635,-0.002579,-0.007857,-0.023229,-0.002476,0.014476,0.010180,-0.003162,0.001239,0.020061

In [26]:
df_final.isna().sum()

datetime_hour    0
region_id        0
day_tempmax      0
day_tempmin      0
day_temp         0
                ..
isw_topic_145    0
isw_topic_146    0
isw_topic_147    0
isw_topic_148    0
isw_topic_149    0
Length: 202, dtype: int64

### Feature engineering for isw topics

In [27]:
topic_cols = [c for c in df_final.columns if "isw_topic_" in c]
df_isw_abs = df_final[topic_cols].abs()

df_final['isw_total_intensity'] = df_isw_abs.sum(axis=1)
df_final['isw_topic_std'] = df_isw_abs.std(axis=1)
df_final['isw_topic_max'] = df_isw_abs.max(axis=1)
df_final['isw_topic_mean'] = df_isw_abs.mean(axis=1)

df_final['isw_velocity_24h'] = (
    df_final.groupby('region_id')['isw_total_intensity']
    .diff(24)
    .fillna(0)
)

df_final['isw_intensity_ema'] = (df_final.groupby('region_id')['isw_total_intensity'].transform(lambda x: x.shift(1).ewm(span=24).mean()))

df_final['isw_topic_entropy'] = -(df_isw_abs.div(df_isw_abs.sum(axis=1), axis=0) * np.log(df_isw_abs.div(df_isw_abs.sum(axis=1), axis=0) + 1e-9)).sum(axis=1)

isw_cols = ['isw_velocity_24h', 'isw_intensity_ema', 'isw_topic_entropy']
df_final[isw_cols] = df_final[isw_cols].fillna(0)

C:\Users\Uw11\AppData\Local\Temp\ipykernel_29284\1269306822.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_final['isw_total_intensity'] = df_isw_abs.sum(axis=1)
C:\Users\Uw11\AppData\Local\Temp\ipykernel_29284\1269306822.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_final['isw_topic_std'] = df_isw_abs.std(axis=1)
C:\Users\Uw11\AppData\Local\Temp\ipykernel_29284\1269306822.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_final['isw_topic_max'] = df_isw_abs.max(axis=1)
C:\Users\Uw11\AppData\Local\Temp\ipykernel_29284\1269306822.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_final['isw_topic_mean'] = df_isw_abs.mean(axis=1)
C:\Users\Uw11\AppData\Local\Temp\ipykernel_29284\1269306822.py:9: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_final['isw_velocity_24h'] = (
C:\Users\Uw11\AppData\Local\Temp\ipykernel_29284\1269306822.py:15: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_final['isw_intensity_ema'] = (df_final.groupby('region_id')['isw_total_intensity'].transform(lambda x: x.shift(1).ewm(span=24).mean()))
C:\Users\Uw11\AppData\Local\Temp\ipykernel_29284\1269306822.py:17: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_final['isw_topic_entropy'] = -(df_isw_abs.div(df_isw_abs.sum(axis=1), axis=0) * np.log(df_isw_abs.div(df_isw_abs.sum(axis=1), axis=0) + 1e-9)).sum(axis=1)

In [28]:
df_final.sample(10)

,datetime_hour,region_id,day_tempmax,day_tempmin,day_temp,day_dew,day_humidity,day_precip,day_precipprob,day_precipcover,day_windgust,day_cloudcover,day_moonphase,hour_temp,hour_feelslike,hour_humidity,hour_dew,hour_precip,hour_precipprob,hour_snow,hour_snowdepth,hour_windgust,hour_windspeed,hour_winddir,hour_pressure,hour_cloudcover,hour_solarradiation,hour_solarenergy,hour_uvindex,hour_conditions_simple_Clear,hour_conditions_simple_Cloudy,hour_conditions_simple_Rain,hour_conditions_simple_Snow,day_of_week,hour,city_name,day_datetime,day_sunrise,day_sunset,region_key,alarm_active,alarm_minutes_in_hour,alarm_lag_1,alarm_lag_3,alarm_lag_6,alarm_lag_12,alarms_in_last_24h,is_weekend,is_night,total_active_alarms_lag1,neighbour_alarms,hours_since_last_alarm,isw_topic_0,isw_topic_1,isw_topic_2,isw_topic_3,isw_topic_4,isw_topic_5,isw_topic_6,isw_topic_7,isw_topic_8,isw_topic_9,isw_topic_10,isw_topic_11,isw_topic_12,isw_topic_13,isw_topic_14,isw_topic_15,isw_topic_16,isw_topic_17,isw_topic_18,isw_topic_19,isw_topic_20,isw_topic_21,isw_topic_22,isw_topic_23,isw_topic_24,isw_topic_25,isw_topic_26,isw_topic_27,isw_topic_28,isw_topic_29,isw_topic_30,isw_topic_31,isw_topic_32,isw_topic_33,isw_topic_34,isw_topic_35,isw_topic_36,isw_topic_37,isw_topic_38,isw_topic_39,isw_topic_40,isw_topic_41,isw_topic_42,isw_topic_43,isw_topic_44,isw_topic_45,isw_topic_46,isw_topic_47,isw_topic_48,isw_topic_49,isw_topic_50,isw_topic_51,isw_topic_52,isw_topic_53,isw_topic_54,isw_topic_55,isw_topic_56,isw_topic_57,isw_topic_58,isw_topic_59,isw_topic_60,isw_topic_61,isw_topic_62,isw_topic_63,isw_topic_64,isw_topic_65,isw_topic_66,isw_topic_67,isw_topic_68,isw_topic_69,isw_topic_70,isw_topic_71,isw_topic_72,isw_topic_73,isw_topic_74,isw_topic_75,isw_topic_76,isw_topic_77,isw_topic_78,isw_topic_79,isw_topic_80,isw_topic_81,isw_topic_82,isw_topic_83,isw_topic_84,isw_topic_85,isw_topic_86,isw_topic_87,isw_topic_88,isw_topic_89,isw_topic_90,isw_topic_91,isw_topic_92,isw_topic_93,isw_topic_94,isw_topic_95,isw_topic_96,isw_topic_97,isw_topic_98,isw_topic_99,isw_topic_100,isw_topic_101,isw_topic_102,isw_topic_103,isw_topic_104,isw_topic_105,isw_topic_106,isw_topic_107,isw_topic_108,isw_topic_109,isw_topic_110,isw_topic_111,isw_topic_112,isw_topic_113,isw_topic_114,isw_topic_115,isw_topic_116,isw_topic_117,isw_topic_118,isw_topic_119,isw_topic_120,isw_topic_121,isw_topic_122,isw_topic_123,isw_topic_124,isw_topic_125,isw_topic_126,isw_topic_127,isw_topic_128,isw_topic_129,isw_topic_130,isw_topic_131,isw_topic_132,isw_topic_133,isw_topic_134,isw_topic_135,isw_topic_136,isw_topic_137,isw_topic_138,isw_topic_139,isw_topic_140,isw_topic_141,isw_topic_142,isw_topic_143,isw_topic_144,isw_topic_145,isw_topic_146,isw_topic_147,isw_topic_148,isw_topic_149,isw_total_intensity,isw_topic_std,isw_topic_max,isw_topic_mean,isw_velocity_24h,isw_intensity_ema,isw_topic_entropy
78032,2022-12-05 17:00:00,4,-3.4,-9.0,-6.8,-12.6,63.9,0.000,0.0,0.00,37.8,5.1,0.37,-4.7,-10.0,57.58,-11.8,0.0,0.0,0.0,0.0,34.2,14.0,81.5,1035.0,0.0,0.0,0.1,0.0,True,False,False,False,0,17,Dnipro,2022-12-05,07:15:10,15:45:38,Дніпропетровська,0,0.000000,1.0,1.0,0.0,0.0,9.0,0,0,24.0,7.0,0,0.602673,-0.107887,-0.062862,-0.046238,0.104967,0.009789,-0.122709,0.170461,-0.134839,-0.028030,-0.071228,-0.011209,0.010958,-0.000430,-0.104796,0.012517,-0.074765,0.035123,-0.051429,0.129223,0.022825,0.024960,-0.016663,0.103264,-0.038798,0.055985,-0.077021,0.133471,-0.028440,-0.111060,0.046021,0.081770,0.025553,0.103138,-0.033967,0.095586,-0.079968,-0.039622,-0.100816,0.075453,-0.019357,0.017407,-0.023932,-0.046530,0.079786,0.039166,0.044172,-0.007309,-0.033271,-0.003359,0.070337,-0.026430,0.110314,0.029114,-0.025437,0.010074,-0.093694,0.006347,0.013641,0.033421,-0.014271,-0.053559,0.030952,0.059691,0.056225,-0.020292,-0.016448,0.042065,-0.002877,-0.004276,0.094276,-0.010740,-0.001885,0.001512,0.038723,-0.005771,0.016822,0.001133,-0.096306,-0.069449,-0.046535,-0.082070,-0.042402,-0.049618,-0.004135,-0.021530,-0.004639,0.009675,-0.012555,-0.076988,-0.021044,0.012771,-0.036354,0.027832,0.000549,-0.022632,-0.061387,0.023634,0.054361,0.011683,0.044194,0.005400,-0.039764,0.057110,0.088141,-0.028537,-0.086019,-0.073780,-0.153780,-0.019406,0.039903,-0.053185,0.015757,-0.001651,0.050252,-0.034092,-0.037934,0.004906,-0.026547,-0.011919,0.064803,-0.035433,-0.074497,0.027918,0.000945,-0.030563,-0.019552,0.020234,-0.052639,0.058622,-0.024156,-0.029411,-0.037947,-0.036319,0.057676,-0.060345,-0.036866,-0.091165,-0.032450,0.039940,-0.049955,0.027263,-0.003282,0.043070,0.010262,0.031084,0.000267,-0.062257,0.058792,0.050779,7.220046,0.057516,0.602673,0.048134,2.146326,6.688778,4.591322
629519,2025-12-25 22:00:00,20,-4.4,-13.5,-8.4,-9.8,89.9,0.000,0.0,0.00,44.9,69.5,0.19,-5.0,-11.5,92.69,-6.0,0.0,0.0,0.0,0.0,36.0,19.8,265.0,1019.0,88.0,0.0,0.0,0.0,False,True,False,False,3,22,Kharkiv,2025-12-25,07:32:50,15:37:44,Харківська,0,0.000000,0.0,1.0,1.0,1.0,20.0,0,0,12.0,3.0,1,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-4.213112,0.677243,-0.000000
347583,2022-03-29 07:00:00,13,14.1,5.7,10.0,2.5,61.0,2.000,100.0,4.17,48.6,63.0,0.89,6.9,5.2,59.70,-0.4,0.0,0.0,0.0,0.0,19.8,8.6,222.9,1010.0,59.8,0.0,0.1,0.0,False,True,False,False,1,7,Lviv,2022-03-29,07:07:34,19:50:47,Львівська,0,0.000000,0.0,1.0,0.0,0.0,6.0,0,0,1.0,0.0,2,0.670155,-0.144163,0.304925,0.214902,0.107982,-0.150587,0.082331,0.019994,0.031941,0.066011,-0.105028,-0.014872,-0.052026,-0.037798,0.048868,-0.017414,0.097120,-0.147525,-0.068777,0.021485,-0.132478,-0.048849,0.042342,-0.009446,0.048535,0.001418,0.070298,0.049045,0.083169,0.025715,-0.083762,-0.009737,-0.018976,0.023320,-0.060368,-0.006402,0.055412,0.035811,-0.037790,-0.011275,0.005662,-0.080097,0.003981,-0.025288,-0.026972,0.001532,0.009305,-0.035019,-0.025359,-0.007275,0.023812,0.020749,0.022672,-0.008243,-0.053070,0.006352,-0.008455,-0.000988,0.036740,-0.018451,0.026656,0.004217,-0.058790,-0.030680,0.031969,-0.041604,-0.009489,0.011592,-0.001887,-0.018093,0.021219,0.028250,-0.043068,0.004121,-0.031147,0.037253,0.026318,-0.010777,-0.033341,0.036162,-0.027320,-0.044619,0.023874,-0.006031,0.006344,-0.013627,0.030072,-0.021583,0.025927,0.008268,-0.051901,-0.012509,-0.005601,0.019691,0.004211,-0.012892,-0.014210,0.011409,-0.004715,-0.019898,0.004636,0.030823,-0.003195,-0.003952,-0.048702,-0.007977,0.016795,0.030803,0.038393,0.008089,0.000008,0.016902,0.010460,0.041600,0.001878,-0.017863,-0.003435,0.024831,0.036807,0.012723,-0.026612,-0.042512,0.000618,0.015435,-0.012621,-0.003138,-0.016440,-0.053895,-0.015645,0.030266,-0.028077,-0.036286,-0.012499,-0.013811,0.029639,0.008982,0.012478,-0.013263,0.016452,-0.041656,-0.010290,-0.011584,0.007854,-0.016251,-0.001057,0.028630,-0.020156,0.007314,-0.029292,0.020035,5.492065,0.065334,0.670155,0.036614,0.037751,5.479531,4.337661
571187,2023-05-23 04:00:00,19,24.4,8.8,17.5,5.2,47.5,0.000,0.0,0.00,26.3,46.7,0.12,11.1,11.1,64.24,4.6,0.0,0.0,0.0,0.0,14.8,7.9,87.9,1016.0,80.6,0.0,0.0,0.0,False,True,False,False,1,4,Ternopil,2023-05-23,05:24:11,21:05:26,Тернопільська,0,0.000000,0.0,0.0,0.0,0.0,2.0,0,1,8.0,2.0,22,0.746421,-0.195735,-0.048062,-0.033640,-0.020344,0.018218,0.042146,0.019951,0.009762,-0.048436,0.068382,0.034782,-0.038997,-0.020168,0.106571,0.051774,0.113639,0.160880,0.056523,0.070222,-0.070845,-0.002079,-0.007753,0.008675,-0.027670,-0.100409,0.008405,-0.009885,-0.001810,0.045780,0.069604,-0.016717,-0.022691,-0.033163,0.069802,0.015474,0.025284,-0.011390,0.038632,0.023777,0.006586,0.004320,-0.011363,-0.026406,-0.040182,0.010547,-0.020791,0.035505,-0.062410,-0.042730,0.046370,0.073920,-0.028983,-0.048757,-0.050161,-0.043407,0.010944,0.042430,0.008021,-0.026817,0.050177,0.020652,0.017936,0.047465,0.011381,-0.018706,0.003350,-0.009760,0.001012,-0.024135,-0.032803,-0.008064,0.042011,0.011434,-0.079458,0.082321,0.000112,-0.003617,-0.018563,-0.015032,-0.027261,-0.005480,0.037452,-0.025138,-0.040523,-0.000119,-0.075463,0.066550,-0.007318,-0.018444,-0.024978,0.054811,0.060798,0.001208,-0.048951,-0.045549,-0.011291,0.051445,-0.077300,0.031256,-0.039427,-0.000100,-0.045096,0.047764,0.089645,-0.044715,0.037479,-0.044306,-0.001320,-0.019551,-0.006866,-0.033639,-0.046985,0.043180,-0.006493,-0.023266,0.036074,0.023753,0.058188,0.023327,0.030738,-0.014555,-0.005320,0.035683,0.035259,-0.007323,0.013046,0.065037,-0.022644,-0.040328,-0.049422,0.012883,0.001667,0.033091,0.003770,-0.003119,0.031415,0.037048,0.003171,0.019849,-0.005428,-0.008793,0.050133,-0.039215,-0.000322,0.010707,0.000932,0.001044,0.054796,0.004559,5.676945,0.065249,0.746421,0.037846,0.631024,5.249875,4.428244
839877,2025-08-15 20:00:00,26,24.9,11.6,19.2,11.2,62.6,0.000,0.0,0.00,32.4,13.5,0.72,18.4,18.4,71.24,13.1,0.0,0.0,0.0,0.0,15.1,6.5,33.8,1021.0,12.4,55.9,0.2,1.0,True,False,False,False,4,20,Kyiv,2025-08-15,05:46:29,20:17:21,Київ,0,0.000000,1.0,0.0,0.0,0.0,5.0,0,0,23.0,1.0,0,0.760936,0.299442,0.107173,-0.103762,-0.135814,0.061004,0.134343,0.063104,-0.146046,0.154845,0.118755,-0.010166,-0.129262,0.147643,-0.091382,0.020966,0.043082,-0.037384,-0.049553,-0.046479,-0.006215,-0.057173,-0.040803,-0.011825,-0.031329,0.033472,0.036600,0.005747,-0.078419,0.012106,0.004300,-0.039448,-0.016971,0.089121,0.058410,-0.013968,-0.029143,0.010269,-0.016102,0.027101,0.009580,0.021219,-0.034927,0.027993,-0.020327,0.020797,-0.023966,-0.023088,-0.027118,0.043493,0.023208,0.030441,-0.003092,0.009154,-0.015784,-0.000941,0.013145,-0.014943,-0.005528,0.049674,0.026420,0.003976,0.011711,-0.010054,0.013776,-0.007592,0.002450,-0.028548,-0.052501,-0.006914,0.015548,0.003664,0.005798,-0.020886,-0.019438,-0.007065,-0.018991,-0.011734,0.021507,0.021731,0.004673,0.006925,0.017074,0.023874,0.014774,0.014433,0.003034,0.006939,-0.038658,0.015399,-0.000971,-0.006229,-0.022062,-0.009142,-0.014626,0.020158,0.021701,0.027679,0.004972,-0.025091,0.031025,-0.002153,-0.012424,0.032112,0.022695,0.005147,0.002692,-0.007500,-0.006691,0.012837,0.031434,-0.005274,0.023769,-0.002451,0.007294,-0.035587,0.006703,-0.014133,0.006418,-0.033682,-0.011296,0.006932,-0.007066,-0.000161,0.027892,-0.003812,-0.010954,0.004907,0.011443,-0.022232,0.028381,0.005885,0.018246,0.006348,0.016076,-0.004974,0.038691,0.000633,-0.005116,0.004740,-0.016323,0.001772,-0.012761,-0.020961,0.019183,0.007835,-0.024078,0.032510,0.006294,0.012053,4.998374,0.071149,0.760936,0.033322,-0.586253,5.119729,4.185823
148614,2023-11-25 23:00:00,6,2.4,-2.5,-0.3,-2.4,85.8,0.000,0.0,0.00,33.5,54.5,0.43,-0.8,-0.8,90.90,-2.1,0.0,0.0,0.0,0.7,7.9,3.6,270.0,999.8,90.0,0.0,0.0,0.0,False,True,False,False,5,23,Zhytomyr,2023-11-25,07:34:06,16:09:58,Житомирська,0,0.000000,0.0,0.0,0.0,0.0,0.0,1,1,7.0,0.0,45,0.820916,-0.067633,-0.101505,-0.146293,0.012330,-0.122434,-0.086633,0.040159,0.191973,0.116064,0.086331,0.002781,0.014048,-0.005648,-0.054028,-0.083062,0.047283,0.060659,-0.114065,-0.040712,0.014790,0.054372,-0.002500,0.036088,0.008870,0.035215,-0.013806,-0.009386,0.048337,-0.039581,0.001245,-0.020144,-0.037185,0.013284,0.054144,0.049916,0.014748,-0.057355,-0.030574,0.012028,0.007783,0.013796,-0.027021,-0.032169,0.004028,0.006451,0.005923,0.005763,0.020650,-0.022108,-0.028354,-0.002547,-0.027785,0.003499,0.011391,0.013204,0.008091,-0.039205,0.033430,-0.022890,-0.016395,0.021310,0.035272,0.010036,0.033251,-0.027217,-0.006221,-0.039778,0.017974,-0.007434,-0.006481,0.002526,0.018897,0.001032,0.024890,-0.032471,0.010624,-0.046794,0.005390,0.002944,-0.004145,-0.023364,0.008018,0.006110,-0.007747,0.013948,0.007873,0.003940,0.003099,-0.002339,0.002180,0.031240,-0.029430,0.001843,0.005004,0.007796,0.024596,0.015928,-0.012961,-0.000266,0.002675,0.014444,-0.006521,-0.007651,-0.007053,-0.011560,-0.012529,0.022381,-0.003357,-0.023993,0.034142,0.006330,-0.000291,-0.014582,-0.006086,0.041238,-0.006036,-0.021057,-0.026986,-0.003887,0.005988,-0.001728,0.014695,-0.002197,-0.020764,0.003813,-0.008461,-0.017363,0.007131,-0.007391,-0.001840,-0.026054,-0.001023,0.027190,0.012867,0.000808,-0.017400,0.030702,0.035362,0.004356,-0.010146,0.000487,-0.003329,-0.026810,-0.003451,0.010398,0.010616,-0.006988,-0.002331,0.001135,4.278602,0.071316,0.820916,0.028524,-0.642842,4.288139,4.086749
747336,2023-03-09 12:00:00,24,15.7,5.4,10.3,3.9,65.7,0.042,100.0,4.17,50.4,81.6,0.57,13.8,13.8,54.32,4.7,0.0,0.0,0.0,0.0,46.8,19.6,190.0,998.9,90.0,259.1,0.9,3.0,False,True,False,False,3,12,Chernivtsi,2023-03-09,06:42:36,18:12:01,Чернівецька,1,0.233333,0.0,0.0,1.0,0.0,5.0,0,0,1.0,0.0,5,0.786978,-0.213185,-0.002488,0.097496,0.087241,-0.126082,0.191583,0.065111,0.040824,0.001196,0.011159,-0.015280,-0.060338,-0.052123,0.031858,0.025429,-0.035894,0.025934,0.114131,-0.033316,-0.051094,0.030445,-0.073502,-0.003560,-0.081642,-0.074662,-0.051407,-0.041892,-0.004373,-0.005990,-0.000827,-0.030604,0.049698,0.036687,-0.030781,0.023675,-0.002162,-0.031298,-0.011681,0.036998,-0.012630,-0.030341,-0.010425,-0.031818,0.035909,-0.022587,-0.042300,0.044408,-0.056904,0.041765,0.034480,-0.059326,0.029348,0.015158,0.006320,0.032501,0.001970,0.060600,0.032459,0.002999,-0.004835,-0.067024,-0.016539,0.003541,0.000444,0.038605,-0.017096,-0.014809,-0.024857,0.013360,-0.021402,0.037028,-0.046480,-0.029511,0.002220,-0.003186,-0.001502,-0.007972,-0.007827,0.014099,0.007393,0.001259,0.021076,0.000939,-0.016413,0.015323,0.012015,0.003633,-0.002842,0.014484,0.012243,0.004859,-0.022430,0.009151,-0.008285,0.005031,-0.068663,0.007523,-0.021593,0.012931,0.006347,-0.010421,-0.048851,-0.005929,0.033725,-0.018807,0.018059,0.032753,-0.037121,-0.018391,-0.009661,-0.020637,0.025106,-0.014245,-0.014750,0.002404,-0.002466,0.022387,-0.024939,0.015186,0.006995,-0.017932,0.058804,-0.023262,-0.000370,-0.015547,0.016495,0.005906,-0.015846,0.000572,0.008927,-0.001826,0.016383,-0.004251,0.006282,0.019616,0.009426,0.006644,-0.008837,-0.015864,0.049624,-0.027311,0.004629,0.017709,-0.023941,0.011863,0.033300,-0.006875,0.003496,0.006555,4.762571,0.069267,0.786978,0.031750,-0.072631,4.770030,4.228106
12006,2023-07-08 08:00:00,2,22.7,16.6,19.2,12.8,67.9,0.400,100.0,12.50,52.6,97.4,0.67,17.7,17.7,72.05,12.6,0.0,0.0,0.0,0.0,40.3,20.2,355.0,1017.0,99.7,178.2,0.6,2.0,False,True,False,False,5,8,Vinnytsia,2023-07-08,05:10:01,21:12:08,Вінницька,0,0.000000,0.0,0.0,0.0,0.0,1.0,1,0,0.0,0.0,10,0.746629,-0.236015,-0.090347,-0.067111,-0.104812,0.107030,0.121842,0.095351,0.098346,-0.151734,0.049769,-0.136595,-0.041657,-0.014032,0.062170,-0.040343,0.049531,-0.075589,-0.011715,0.025397,0.125375,-0.035665,-0.038708,0.054266,0.049525,0.010070,-0.018430,0.059837,-0.047190,-0.029096,-0.033010,0.051619,0.006655,-0.074200,-0.037531,0.001418,0.029000,0.016967,0.033846,-0.054011,0.004814,-0.019317,-0.016542,0.011136,-0.027296,0.014847,-0.063812,-0.040854,-0.004453,0.043986,-0.007701,-0.065400,0.045388,0.046748,-0.000670,0.060091,0.101982,-0.022744,0.039283,0.022675,0.040083,-0.066047,-0.015491,-0.035751,-0.027405,-0.042659,0.044455,-0.021565,-0.013472,0.000835,0.046004,0.009233,-0.013192,-0.044476,-0.029898,0.045439,-0.002432,0.014532,-0.011196,0.018424,0.012509,0.019465,-0.000281,-0.037236,0.007274,-0.027714,-0.027270,0.034264,-0.001021,0.056017,0.032399,0.015545,-0.008289,-0.004383,0.031783,-0.003397,0.025568,0.032987,-0.017566,0.029265,-0.000275,0.006624,-0.041850,0.027888,-0.033657,-0.044902,-0.007456,0.035866,-0.008965,-0.020030,0.005017,0.006777,0.023809,-0.003034,0.017887,-0.033637,-0.008235,-0.013652,-0.021416,-0.005284,-0.002550,-0.011079,-0.013963,0.013908,-0.030824,-0.007808,0.018457,0.001139,0.005442,0.010323,0.031476,0.001372,0.009863,-0.014782,0.019830,0.000317,-0.002492,-0.006638,0.010545,-0.033247,-0.001093,-0.008444,-0.007373,-0.015817,0.002471,0.011776,0.001794,-0.026335,0.015442,0.009767,5.471629,0.067308,0.746629,0.036478,0.929991,5.042036,4.341562
161118,2025-04-30 01:00:00,6,20.3,8.2,14.6,3.1,48.4,0.000,0.0,0.00,33.8,68.0,0.09,9.4,7.6,64.30,3.0,0.0,0.0,0.0,0.0,18.0,11.5,286.8,1017.0,80.8,0.0,0.0,0.0,False,True,False,False,2,1,Zhytomyr,2025-04-30,05:42:40,20:23:33,Житомирська,0,0.000000,0.0,0.0,0.0,0.0,0.0,0,1,1.0,0.0,34,0.769713,0.169668,-0.003655,0.250288,-0.084509,-0.059419,-0.125252,-0.096049,-0.079464,-0.077125,0.272574,-0.083866,-0.030033,-0.040261,-0.037121,0.047109,-0.142813,0.029197,-0.096238,-0.015886,0.051978,0.041384,-0.028043,-0.013894,0.040154,-0.031132,0.040827,0.028101,0.008841,-0.027995,0.019547,-0.048467,-0.031598,0.010892,-0.063513,0.006643,0.053398,-0.020101,0.031394,-0.013021,0.022069,-0.001180,0.018743,-0.025132,0.008131,0.000614,-0.013047,-0.000565,0.000651,-0.005835,0.004899,0.022562,0.020046,-0.011602,0.008880,0.037652,0.025579,-0.009497,-0.000009,0.013289,-0.011087,-0.000645,0.008818,0.058758,0.030467,0.020494,-0.019223,-0.016543,0.022744,-0.000463,0.009200,-0.035371,-0.000474,0.006052,0.015610,0.013259,-0.023109,0.011956,0.007113,-0.019420,0.009263,0.009447,-0.000878,-0.012058,-0.013764,0.007611,0.001163,-0.011266,-0.005011,-0.001776,-0.011362,-0.014287,0.003494,-0.002158,-0.002593,0.002302,-0.000028,-0.005425,-0.006294,-0.010566,0.011152,-0.013864,0.022060,-0.017424,-0.004497,-0.015385,0.012171,-0.040805,0.012770,-0.040976,-0.017290,-0.012805,-0.002503,-0.008895,0.012064,-0.006913,-0.011525,-0.014074,0.007050,0.000182,-0.007415,-0.020196,0.008178,0.029694,-0.009537,0.016418,0.017210,0.016242,0.031882,-0.024610,0.003122,-0.002167,0.013274,0.008499,0.002957,-0.006778,-0.014246,-0.008075,0.009320,0.011506,-0.006316,-0.008679,-0.001847,0.021195,0.007359,-0.001132,0.007604,-0.030126,0.024801,0.002518,4.490007,0.071787,0.769713,0.029933,-0.292860,4.810192,4.056705

### TELEGRAM MERGE

In [29]:
df_tg_matrix = pd.read_csv("../data/telegram_processed_svd.csv")

In [30]:
df_tg_matrix.head()

,date,channel,tg_topic_0,tg_topic_1,tg_topic_2,tg_topic_3,tg_topic_4,tg_topic_5,tg_topic_6,tg_topic_7,tg_topic_8,tg_topic_9,tg_topic_10,tg_topic_11,tg_topic_12,tg_topic_13,tg_topic_14,tg_topic_15,tg_topic_16,tg_topic_17,tg_topic_18,tg_topic_19,tg_topic_20,tg_topic_21,tg_topic_22,tg_topic_23,tg_topic_24,tg_topic_25,tg_topic_26,tg_topic_27,tg_topic_28,tg_topic_29,tg_topic_30,tg_topic_31,tg_topic_32,tg_topic_33,tg_topic_34,tg_topic_35,tg_topic_36,tg_topic_37,tg_topic_38,tg_topic_39,tg_topic_40,tg_topic_41,tg_topic_42,tg_topic_43,tg_topic_44,tg_topic_45,tg_topic_46,tg_topic_47,tg_topic_48,tg_topic_49,tg_topic_50,tg_topic_51,tg_topic_52,tg_topic_53,tg_topic_54,tg_topic_55,tg_topic_56,tg_topic_57,tg_topic_58,tg_topic_59,tg_topic_60,tg_topic_61,tg_topic_62,tg_topic_63,tg_topic_64,tg_topic_65,tg_topic_66,tg_topic_67,tg_topic_68,tg_topic_69,tg_topic_70,tg_topic_71,tg_topic_72,tg_topic_73,tg_topic_74,tg_topic_75,tg_topic_76,tg_topic_77,tg_topic_78,tg_topic_79,tg_topic_80,tg_topic_81,tg_topic_82,tg_topic_83,tg_topic_84,tg_topic_85,tg_topic_86,tg_topic_87,tg_topic_88,tg_topic_89,tg_topic_90,tg_topic_91,tg_topic_92,tg_topic_93,tg_topic_94,tg_topic_95,tg_topic_96,tg_topic_97,tg_topic_98,tg_topic_99,tg_topic_100,tg_topic_101,tg_topic_102,tg_topic_103,tg_topic_104,tg_topic_105,tg_topic_106,tg_topic_107,tg_topic_108,tg_topic_109,tg_topic_110,tg_topic_111,tg_topic_112,tg_topic_113,tg_topic_114,tg_topic_115,tg_topic_116,tg_topic_117,tg_topic_118,tg_topic_119,tg_topic_120,tg_topic_121,tg_topic_122,tg_topic_123,tg_topic_124,tg_topic_125,tg_topic_126,tg_topic_127,tg_topic_128,tg_topic_129,tg_topic_130,tg_topic_131,tg_topic_132,tg_topic_133,tg_topic_134,tg_topic_135,tg_topic_136,tg_topic_137,tg_topic_138,tg_topic_139,tg_topic_140,tg_topic_141,tg_topic_142,tg_topic_143,tg_topic_144,tg_topic_145,tg_topic_146,tg_topic_147,tg_topic_148,tg_topic_149,tg_topic_150,tg_topic_151,tg_topic_152,tg_topic_153,tg_topic_154,tg_topic_155,tg_topic_156,tg_topic_157,tg_topic_158,tg_topic_159,tg_topic_160,tg_topic_161,tg_topic_162,tg_topic_163,tg_topic_164,tg_topic_165,tg_topic_166,tg_topic_167,tg_topic_168,tg_topic_169,tg_topic_170,tg_topic_171,tg_topic_172,tg_topic_173,tg_topic_174,tg_topic_175,tg_topic_176,tg_topic_177,tg_topic_178,tg_topic_179,tg_topic_180,tg_topic_181,tg_topic_182,tg_topic_183,tg_topic_184,tg_topic_185,tg_topic_186,tg_topic_187,tg_topic_188,tg_topic_189,tg_topic_190,tg_topic_191,tg_topic_192,tg_topic_193,tg_topic_194,tg_topic_195,tg_topic_196,tg_topic_197,tg_topic_198,tg_topic_199,tg_topic_200,tg_topic_201,tg_topic_202,tg_topic_203,tg_topic_204,tg_topic_205,tg_topic_206,tg_topic_207,tg_topic_208,tg_topic_209,tg_topic_210,tg_topic_211,tg_topic_212,tg_topic_213,tg_topic_214,tg_topic_215,tg_topic_216,tg_topic_217,tg_topic_218,tg_topic_219,tg_topic_220,tg_topic_221,tg_topic_222,tg_topic_223,tg_topic_224,tg_topic_225,tg_topic_226,tg_topic_227,tg_topic_228,tg_topic_229,tg_topic_230,tg_topic_231,tg_topic_232,tg_topic_233,tg_topic_234,tg_topic_235,tg_topic_236,tg_topic_237,tg_topic_238,tg_topic_239,tg_topic_240,tg_topic_241,tg_topic_242,tg_topic_243,tg_topic_244,tg_topic_245,tg_topic_246,tg_topic_247,tg_topic_248,tg_topic_249
0,2026-03-17 01:31:21,kpszsu,0.138465,-0.060347,0.284671,0.035601,0.116456,-0.045463,-0.021404,0.031473,0.003471,0.014402,0.286607,0.194596,-0.210486,0.069280,-0.111417,0.052725,0.069214,0.119048,-0.077877,0.065132,-0.077492,-0.005224,-0.019193,0.070873,-0.107137,-0.076956,-0.067567,0.098249,0.002130,0.136716,0.044741,-0.024770,0.051995,-0.083287,0.067505,0.114771,0.033290,0.000556,0.255589,-0.002123,-0.049321,0.032166,-0.022657,-0.121028,0.038802,0.038982,0.039210,0.119676,0.006456,-0.083387,-0.005215,0.086310,-0.061551,-0.063818,0.027737,-0.027433,0.029990,-0.021397,-0.062931,-0.081544,-0.037276,0.086436,0.086050,0.001841,0.071080,-0.013168,0.000673,-0.012356,-0.001683,0.025808,-0.025291,-0.025418,0.053668,0.007258,-0.024991,0.030166,0.059870,-0.083016,-0.066038,-0.054990,0.013588,0.063259,0.006870,-0.141285,0.103932,-0.012589,0.006431,-0.088279,0.022473,-0.066362,-0.047590,0.045179,0.004218,0.030831,-0.054250,-0.029351,0.041396,-0.045288,-0.087615,0.052448,-0.075680,-0.030585,0.065225,-0.027470,-0.033416,-0.006350,0.041117,0.010669,-0.016878,0.017371,-0.010531,0.037712,-0.003122,-0.064614,0.000778,-0.058324,0.000732,0.063612,0.001426,-0.004630,0.022107,0.026890,-0.002877,-0.007457,0.022465,0.054594,-0.063663,-0.038484,-0.027482,0.005726,-0.019801,0.022768,0.002185,0.021476,0.023816,-0.002198,-0.035340,0.006767,0.014429,-0.017577,-0.019679,-0.018992,-0.035058,-0.009034,0.022018,0.018299,0.027707,0.000418,-0.036627,0.005189,0.005043,0.004999,-0.029362,0.046705,0.001302,0.023673,-0.038693,0.028319,-0.022432,0.010767,-0.015688,0.000376,0.052725,-0.007286,0.030421,0.022825,0.027643,-0.028867,0.051349,0.042974,0.017341,-0.023986,0.012823,0.021964,0.021618,0.016822,-0.027134,-0.038862,0.000389,-0.029627,-0.010725,0.043088,0.000004,0.015184,-0.005345,-0.029839,0.026691,0.038260,-0.005670,-0.000586,-0.027356,0.003945,-0.000152,0.024882,0.022157,-0.005061,-0.049974,0.029649,-0.024783,0.005134,0.058755,-0.003974,-0.014609,0.042866,0.001083,0.009632,-0.003357,-0.013045,0.019440,0.008442,0.081747,-0.028814,-0.013081,0.018299,-0.023976,0.001223,-0.038043,-0.022559,0.001781,-0.015626,-0.036170,-0.004866,0.024373,0.069734,-0.025656,-0.108018,-0.060561,0.033817,0.000072,0.025559,-0.039647,0.015612,0.020662,-0.027484,-0.009553,0.008035,-0.045313,0.026774,-0.046688,0.001197,0.032808,0.093800,-0.069880,0.004953,-0.050572,0.002973,0.033703,-0.030074,-0.039642,0.065714
1,2026-03-17 01:21:32,kpszsu,0.081445,-0.029977,0.247861,0.054075,0.095709,-0.057322,-0.032291,-0.002144,-0.061026,-0.000349,0.058877,0.020566,-0.084236,-0.020251,-0.084056,-0.072488,0.076767,0.252278,0.334362,0.091094,0.123831,0.097900,-0.149999,0.063629,0.032940,-0.029925,0.002428,0.052438,-0.024259,-0.000462,0.004025,-0.037703,0.012892,-0.012401,-0.044341,0.070714,0.030852,-0.022582,0.159383,0.041918,-0.003680,-0.027373,0.015890,-0.079918,0.046941,0.046236,0.036299,0.066485,-0.023775,-0.031196,0.009114,0.065309,-0.033780,-0.048204,-0.000066,0.029089,0.014088,-0.033346,-0.047687,-0.029563,0.013562,0.025532,0.021691,0.011945,0.034211,-0.036508,-0.000594,-0.004532,-0.007462,0.000012,0.003351,0.013241,0.041728,0.016402,-0.002984,0.030432,0.028853,-0.028717,-0.025719,-0.052691,0.001095,0.019845,-0.002567,-0.058738,0.034502,0.005373,0.026171,0.020127,0.022007,-0.020962,-0.027217,0.025405,-0.020779,0.014818,-0.026313,0.004178,0.019359,-0.021494,-0.027382,0.045601,-0.038545,-0.056272,0.040210,0.006677,-0.039778,0.030839,-0.014617,0.006912,-0.030934,-0.021980,0.007721,0.032819,-0.030178,-0.014516,-0.019618,-0.011318,0.014966,0.044775,-0.005767,0.018571,0.040382,0.043330,-0.026895,0.021511,0.015915,0.038290,-0.017584,0.004245,-0.017202,0.024369,-0.013239,-0.008324,0.028224,0.040272,-0.002205,0.009691,-0.032332,0.037062,0.017641,-0.006146,-0.020431,-0.014117,-0.007295,-0.001494,0.018983,-0.012901,0.011172,-0.005895,0.009558,-0.003325,0.015059,0.025263,-0.022237,0.060879,0.015981,0.017196,-0.002125,0.007762,0.001673,-0.022553,-0.006871,0.017024,0.021484,-0.046161,0.027117,0.051850,0.007578,-0.012628,0.019280,0.011891,0.008518,0.018874,-0.015337,0.036233,-0.023559,0.009720,0.012382,-0.034651,0.012400,-0.027353,-0.005547,0.019104,-0.047072,0.006491,-0.039092,-0.061500,-0.000121,0.007155,-0.005601,0.034050,-0.001088,0.014417,-0.009232,0.012555,-0.012744,0.046162,0.000906,0.039759,-0.007223,0.003844,0.050336,-0.013732,-0.002823,0.007491,-0.031241,0.038498,0.023349,0.011865,-0.012218,-0.008905,0.087717,-0.034785,0.029018,0.028218,0.032772,0.040696,-0.005858,0.030184,-0.052476,0.003957,-0.094581,0.056383,0.005090,-0.008526,-0.016663,-0.020389,-0.025368,0.009741,-0.006208,0.062136,0.017239,0.047100,0.063502,-0.069763,-0.008333,-0.100094,-0.103329,0.013100,0.026504,0.019163,0.022844,0.061741,-0.099778,-0.040678,-0.017302,0.050442,-0.032312,-0.019222,0.001714,-0.011180
2,2026-03-17 00:45:16,kpszsu,0.105084,-0.046298,0.205981,0.022232,0.084708,-0.026968,-0.018273,0.035228,0.011104,0.012668,0.256708,0.171674,-0.167075,0.049015,-0.141766,0.007056,0.058707,0.227561,0.175420,0.129212,0.051936,0.016562,-0.100967,0.107908,0.086987,-0.068439,0.003396,-0.118361,-0.037934,-0.028892,0.053700,-0.062491,0.016984,0.035380,-0.029684,0.070358,0.004297,0.058915,0.145860,-0.015504,-0.066756,0.038467,0.044416,-0.105012,-0.000332,0.016199,0.008431,0.033092,-0.025877,-0.019219,-0.019688,0.054911,-0.003414,-0.012124,0.017088,-0.025771,-0.003911,0.005257,-0.022092,-0.026852,0.007023,0.056990,0.060005,0.012899,0.027598,-0.025051,0.009237,0.001975,-0.003508,0.016622,-0.016613,-0.015368,0.027598,0.009586,-0.027132,0.031524,0.014735,-0.057399,-0.035300,-0.043781,0.025107,0.025224,0.012144,-0.080650,0.067541,-0.015216,-0.005507,-0.075218,0.010542,-0.043353,-0.012417,0.034512,-0.017629,0.040248,-0.037723,-0.012209,0.012921,-0.034023,-0.016157,0.041341,-0.044365,-0.042018,0.026374,-0.003383,-0.031019,0.024522,0.000008,0.013725,-0.034833,-0.033750,0.000645,0.027322,-0.027107,-0.028914,-0.025834,-0.014569,0.018640,0.034904,-0.006686,0.030703,0.047056,0.028257,-0.029696,0.019813,0.007009,0.003299,0.004024,0.037968,-0.007443,0.017785,0.002201,-0.028063,0.029215,0.001624,0.007756,0.006892,0.007746,-0.005293,0.007887,0.001488,-0.005918,-0.006704,0.011983,0.008847,0.030397,0.005884,-0.000754,-0.013624,-0.001285,-0.021799,0.006546,0.030952,-0.005749,0.046793,-0.020911,0.008099,-0.006064,-0.001224,0.001652,0.005072,-0.000833,0.005461,-0.002096,-0.046314,-0.026112,0.000856,-0.003517,-0.011551,0.011186,-0.004431,-0.010931,-0.002757,0.004268,-0.004567,-0.041279,-0.005649,0.015248,-0.015297,-0.002424,-0.018278,-0.012699,0.025262,-0.033443,-0.004119,-0.028482,-0.019176,0.005992,-0.002140,0.004348,0.008520,-0.011717,-0.005097,-0.006033,0.005057,-0.005517,0.024310,0.036965,-0.002765,0.017872,0.005523,0.007311,-0.000949,0.029967,0.002951,0.002448,0.030331,0.014670,0.002061,-0.022851,-0.025745,0.037327,-0.003633,0.019323,0.018550,0.020266,0.039182,0.020342,0.024751,-0.054518,0.005665,-0.061892,0.060482,0.006192,-0.020693,-0.006436,0.006757,0.017694,0.006223,-0.014864,0.017611,0.051557,0.029833,0.050085,-0.002730,-0.008607,-0.084603,-0.059504,-0.017975,0.054269,0.016123,-0.006270,-0.004745,-0.021264,-0.040773,0.023039,0.027518,-0.034993,0.000479,0.020928,-0.028859
3,2026-03-17 00:33:10,kpszsu,0.157535,-0.071472,0.326986,0.093080,0.102398,-0.106918,-0.002767,0.013840,-0.095454,-0.025148,0.126537,0.113714,-0.047401,0.021931,0.047574,0.173796,0.093499,-0.026190,-0.103364,0.002587,-0.036625,0.001888,-0.012957,0.348204,0.059674,-0.078542,-0.022091,0.087036,-0.004032,0.043401,-0.004430,0.045495,0.061583,-0.116436,-0.006978,0.073243,0.073548,-0.065315,0.164541,-0.034224,-0.124791,-0.137846,0.081421,-0.066593,-0.097558,-0.000447,-0.033104,0.008700,-0.126692,-0.003739,0.004673,0.052261,0.084910,0.006517,0.025257,0.064814,0.009505,-0.042701,-0.064888,0.006151,0.064699,-0.046971,-0.020759,-0.043696,-0.033699,-0.063607,-0.035293,0.129424,0.089013,-0.043548,-0.003238,-0.010730,0.037873,-0.001692,-0.026928,0.085015,-0.034597,-0.038893,-0.083847,-0.066816,0.005148,-0.047564,0.016877,-0.013450,0.003747,-0.047701,-0.009025,0.029263,0.135268,-0.040976,0.038661,-0.057250,-0.034475,0.119960,-0.017549,-0.024396,-0.034516,0.051513,0.017700,-0.036808,0.024788,0.016020,-0.001344,-0.000272,-0.005811,0.035357,0.010039,0.013435,-0.032259,0.017766,-0.042356,-0.020955,-0.019849,-0.018692,0.019065,-0.029051,-0.023030,0.029229,0.001599,-0.008910,0.039998,-0.028329,-0.016452,-0.001025,-0.002825,-0.052526,0.025843,0.011630,0.000089,0.049061,0.039794,-0.041036,-0.020850,-0.044902,-0.008521,-0.049821,0.130815,0.008565,0.003646,0.027318,0.035037,0.000728,-0.023164,0.031708,0.023820,0.024722,-0.023195,0.062995,-0.056316,-0.009654,-0.024351,0.023498,0.049273,-0.008360,-0.019477,-0.004215,-0.013292,-0.045806,0.013138,-0.138738,-0.017433,-0.040693,-0.037609,-0.043765,0.056655,-0.014737,-0.045464,0.020936,-0.021661,-0.019726,0.014913,0.049683,-0.046037,0.009127,0.048342,0.022217,0.002301,-0.030900,0.032640,0.002944,0.052944,-0.004791,0.054912,-0.005396,-0.005737,-0.015156,-0.044975,0.023627,0.022784,-0.036272,0.003612,-0.013702,-0.030584,-0.034615,-0.075749,-0.045365,0.058842,0.078412,-0.080768,-0.023364,0.091381,-0.054169,0.099914,0.033261,0.113589,0.014300,0.038528,0.015061,-0.036444,0.006221,0.015163,-0.059150,-0.006163,0.077840,0.027629,-0.045494,-0.011676,0.007961,0.006003,-0.021858,-0.002265,-0.002166,0.007077,0.013411,0.017994,-0.035065,0.019670,-0.004608,-0.006582,-0.022644,0.001066,-0.003627,0.019168,-0.010144,-0.011657,-0.018929,-0.002369,0.000273,0.026089,-0.009492,-0.002598,0.002334,-0.003293,-0.005758,0.003161,0.003687,-0.003392,-0.015742,0.024436,0.006963
4,2026-03-16 23:30:39,kpszsu,0.086284,-0.013447,0.206107,0.011940,0.060368,-0.059965,-0.001821,0.019170,-0.004458,-0.009648,0.225544,0.156530,-0.135636,0.055203,-0.098784,0.020448,0.017467,0.057409,-0.180284,0.078452,-0.150403,-0.082255,0.083102,0.028168,0.146435,0.058102,-0.041051,-0.054629,-0.001966,-0.077432,0.057427,0.001955,-0.096813,-0.050339,0.049807,0.033074,0.008641,0.064747,-0.015792,-0.010306,-0.003599,0.005837,-0.016538,0.033314,-0.094433,-0.089436,-0.007744,-0.018319,-0.001537,0.005980,-0.067055,-0.008179,-0.030991,0.012513,-0.028641,-0.036708,-0.013484,0.025631,-0.039420,-0.052131,-0.006948,0.013703,0.025137,0.005163,-0.000478,-0.018326,-0.013158,-0.035966,-0.021579,0.040714,0.004467,-0.043439,0.030601,0.006101,-0.038502,0.024962,-0.004806,-0.053136,-0.038796,-0.027540,0.012633,0.051862,0.030648,-0.046695,0.091882,-0.018502,-0.012556,-0.091033,-0.002592,-0.010190,0.007522,0.035732,-0.022504,0.059741,-0.013541,-0.004720,0.015781,-0.028124,0.028541,-0.046519,-0.008490,0.038174,0.045450,-0.060776,-0.024765,-0.104436,0.038963,0.001431,0.107465,0.030285,0.169420,0.082742,-0.060005,0.125142,0.124934,0.235560,-0.004497,0.298645,-0.045009,-0.158774,0.081241,0.040379,0.046264,-0.013366,0.084232,0.051756,0.063677,0.003895,-0.013856,0.059364,0.020009,-0.032260,0.031630,-0.045375,-0.021741,0.023400,-0.013403,0.033449,-0.001340,-0.006783,-0.018940,-0.004541,0.001201,-0.025616,0.009844,0.001418,-0.011174,0.013933,-0.028911,0.008501,-0.011928,-0.008648,0.004568,0.006973,-0.021269,0.006889,-0.013873,0.003899,0.004513,0.014755,-0.031048,-0.037680,-0.005877,-0.027442,0.010634,-0.030291,-0.029992,0.020678,0.027016,0.026559,-0.028472,-0.023276,0.005586,-0.016526,0.007086,-0.015285,0.017279,-0.001579,-0.025486,0.007684,-0.003522,-0.003363,0.015039,-0.008244,-0.024590,0.001974,0.006857,0.006517,0.006724,-0.006835,-0.014678,0.009219,-0.005719,-0.018043,0.019360,-0.007094,0.009129,-0.014171,0.035966,0.004124,-0.003560,0.001255,-0.005335,0.003899,0.001262,0.001385,0.001416,-0.009663,0.001845,0.012063,-0.021216,0.003721,-0.003337,0.006796,-0.002613,-0.005347,-0.005237,-0.005359,0.005972,-0.011846,0.002321,-0.016305,0.006143,0.006003,0.002693,-0.001045,-0.016132,0.003167,-0.013464,-0.013161,0.002457,0.007259,-0.007108,0.003937,-0.002485,-0.003352,-0.009933,-0.011002,0.000517,-0.006357,0.000333,0.018163,-0.014486,0.006608,-0.000406,0.008269,0.006597,-0.000130,0.009959,0.008867

In [31]:
df_tg_matrix["datetime_hour"] = pd.to_datetime(df_tg_matrix["date"]).dt.floor("h")

C:\Users\Uw11\AppData\Local\Temp\ipykernel_29284\2851151304.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_tg_matrix["datetime_hour"] = pd.to_datetime(df_tg_matrix["date"]).dt.floor("h")

In [32]:
topic_cols = [c for c in df_tg_matrix.columns if "tg_topic_" in c]

tg_hourly = (
    df_tg_matrix.groupby("datetime_hour")[topic_cols]
    .mean()
    .sort_index()
    .reset_index()
)

C:\Users\Uw11\AppData\Local\Temp\ipykernel_29284\2188712141.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  .reset_index()

In [33]:
df_tg_matrix.head()

,date,channel,tg_topic_0,tg_topic_1,tg_topic_2,tg_topic_3,tg_topic_4,tg_topic_5,tg_topic_6,tg_topic_7,tg_topic_8,tg_topic_9,tg_topic_10,tg_topic_11,tg_topic_12,tg_topic_13,tg_topic_14,tg_topic_15,tg_topic_16,tg_topic_17,tg_topic_18,tg_topic_19,tg_topic_20,tg_topic_21,tg_topic_22,tg_topic_23,tg_topic_24,tg_topic_25,tg_topic_26,tg_topic_27,tg_topic_28,tg_topic_29,tg_topic_30,tg_topic_31,tg_topic_32,tg_topic_33,tg_topic_34,tg_topic_35,tg_topic_36,tg_topic_37,tg_topic_38,tg_topic_39,tg_topic_40,tg_topic_41,tg_topic_42,tg_topic_43,tg_topic_44,tg_topic_45,tg_topic_46,tg_topic_47,tg_topic_48,tg_topic_49,tg_topic_50,tg_topic_51,tg_topic_52,tg_topic_53,tg_topic_54,tg_topic_55,tg_topic_56,tg_topic_57,tg_topic_58,tg_topic_59,tg_topic_60,tg_topic_61,tg_topic_62,tg_topic_63,tg_topic_64,tg_topic_65,tg_topic_66,tg_topic_67,tg_topic_68,tg_topic_69,tg_topic_70,tg_topic_71,tg_topic_72,tg_topic_73,tg_topic_74,tg_topic_75,tg_topic_76,tg_topic_77,tg_topic_78,tg_topic_79,tg_topic_80,tg_topic_81,tg_topic_82,tg_topic_83,tg_topic_84,tg_topic_85,tg_topic_86,tg_topic_87,tg_topic_88,tg_topic_89,tg_topic_90,tg_topic_91,tg_topic_92,tg_topic_93,tg_topic_94,tg_topic_95,tg_topic_96,tg_topic_97,tg_topic_98,tg_topic_99,tg_topic_100,tg_topic_101,tg_topic_102,tg_topic_103,tg_topic_104,tg_topic_105,tg_topic_106,tg_topic_107,tg_topic_108,tg_topic_109,tg_topic_110,tg_topic_111,tg_topic_112,tg_topic_113,tg_topic_114,tg_topic_115,tg_topic_116,tg_topic_117,tg_topic_118,tg_topic_119,tg_topic_120,tg_topic_121,tg_topic_122,tg_topic_123,tg_topic_124,tg_topic_125,tg_topic_126,tg_topic_127,tg_topic_128,tg_topic_129,tg_topic_130,tg_topic_131,tg_topic_132,tg_topic_133,tg_topic_134,tg_topic_135,tg_topic_136,tg_topic_137,tg_topic_138,tg_topic_139,tg_topic_140,tg_topic_141,tg_topic_142,tg_topic_143,tg_topic_144,tg_topic_145,tg_topic_146,tg_topic_147,tg_topic_148,tg_topic_149,tg_topic_150,tg_topic_151,tg_topic_152,tg_topic_153,tg_topic_154,tg_topic_155,tg_topic_156,tg_topic_157,tg_topic_158,tg_topic_159,tg_topic_160,tg_topic_161,tg_topic_162,tg_topic_163,tg_topic_164,tg_topic_165,tg_topic_166,tg_topic_167,tg_topic_168,tg_topic_169,tg_topic_170,tg_topic_171,tg_topic_172,tg_topic_173,tg_topic_174,tg_topic_175,tg_topic_176,tg_topic_177,tg_topic_178,tg_topic_179,tg_topic_180,tg_topic_181,tg_topic_182,tg_topic_183,tg_topic_184,tg_topic_185,tg_topic_186,tg_topic_187,tg_topic_188,tg_topic_189,tg_topic_190,tg_topic_191,tg_topic_192,tg_topic_193,tg_topic_194,tg_topic_195,tg_topic_196,tg_topic_197,tg_topic_198,tg_topic_199,tg_topic_200,tg_topic_201,tg_topic_202,tg_topic_203,tg_topic_204,tg_topic_205,tg_topic_206,tg_topic_207,tg_topic_208,tg_topic_209,tg_topic_210,tg_topic_211,tg_topic_212,tg_topic_213,tg_topic_214,tg_topic_215,tg_topic_216,tg_topic_217,tg_topic_218,tg_topic_219,tg_topic_220,tg_topic_221,tg_topic_222,tg_topic_223,tg_topic_224,tg_topic_225,tg_topic_226,tg_topic_227,tg_topic_228,tg_topic_229,tg_topic_230,tg_topic_231,tg_topic_232,tg_topic_233,tg_topic_234,tg_topic_235,tg_topic_236,tg_topic_237,tg_topic_238,tg_topic_239,tg_topic_240,tg_topic_241,tg_topic_242,tg_topic_243,tg_topic_244,tg_topic_245,tg_topic_246,tg_topic_247,tg_topic_248,tg_topic_249,datetime_hour
0,2026-03-17 01:31:21,kpszsu,0.138465,-0.060347,0.284671,0.035601,0.116456,-0.045463,-0.021404,0.031473,0.003471,0.014402,0.286607,0.194596,-0.210486,0.069280,-0.111417,0.052725,0.069214,0.119048,-0.077877,0.065132,-0.077492,-0.005224,-0.019193,0.070873,-0.107137,-0.076956,-0.067567,0.098249,0.002130,0.136716,0.044741,-0.024770,0.051995,-0.083287,0.067505,0.114771,0.033290,0.000556,0.255589,-0.002123,-0.049321,0.032166,-0.022657,-0.121028,0.038802,0.038982,0.039210,0.119676,0.006456,-0.083387,-0.005215,0.086310,-0.061551,-0.063818,0.027737,-0.027433,0.029990,-0.021397,-0.062931,-0.081544,-0.037276,0.086436,0.086050,0.001841,0.071080,-0.013168,0.000673,-0.012356,-0.001683,0.025808,-0.025291,-0.025418,0.053668,0.007258,-0.024991,0.030166,0.059870,-0.083016,-0.066038,-0.054990,0.013588,0.063259,0.006870,-0.141285,0.103932,-0.012589,0.006431,-0.088279,0.022473,-0.066362,-0.047590,0.045179,0.004218,0.030831,-0.054250,-0.029351,0.041396,-0.045288,-0.087615,0.052448,-0.075680,-0.030585,0.065225,-0.027470,-0.033416,-0.006350,0.041117,0.010669,-0.016878,0.017371,-0.010531,0.037712,-0.003122,-0.064614,0.000778,-0.058324,0.000732,0.063612,0.001426,-0.004630,0.022107,0.026890,-0.002877,-0.007457,0.022465,0.054594,-0.063663,-0.038484,-0.027482,0.005726,-0.019801,0.022768,0.002185,0.021476,0.023816,-0.002198,-0.035340,0.006767,0.014429,-0.017577,-0.019679,-0.018992,-0.035058,-0.009034,0.022018,0.018299,0.027707,0.000418,-0.036627,0.005189,0.005043,0.004999,-0.029362,0.046705,0.001302,0.023673,-0.038693,0.028319,-0.022432,0.010767,-0.015688,0.000376,0.052725,-0.007286,0.030421,0.022825,0.027643,-0.028867,0.051349,0.042974,0.017341,-0.023986,0.012823,0.021964,0.021618,0.016822,-0.027134,-0.038862,0.000389,-0.029627,-0.010725,0.043088,0.000004,0.015184,-0.005345,-0.029839,0.026691,0.038260,-0.005670,-0.000586,-0.027356,0.003945,-0.000152,0.024882,0.022157,-0.005061,-0.049974,0.029649,-0.024783,0.005134,0.058755,-0.003974,-0.014609,0.042866,0.001083,0.009632,-0.003357,-0.013045,0.019440,0.008442,0.081747,-0.028814,-0.013081,0.018299,-0.023976,0.001223,-0.038043,-0.022559,0.001781,-0.015626,-0.036170,-0.004866,0.024373,0.069734,-0.025656,-0.108018,-0.060561,0.033817,0.000072,0.025559,-0.039647,0.015612,0.020662,-0.027484,-0.009553,0.008035,-0.045313,0.026774,-0.046688,0.001197,0.032808,0.093800,-0.069880,0.004953,-0.050572,0.002973,0.033703,-0.030074,-0.039642,0.065714,2026-03-17 01:00:00
1,2026-03-17 01:21:32,kpszsu,0.081445,-0.029977,0.247861,0.054075,0.095709,-0.057322,-0.032291,-0.002144,-0.061026,-0.000349,0.058877,0.020566,-0.084236,-0.020251,-0.084056,-0.072488,0.076767,0.252278,0.334362,0.091094,0.123831,0.097900,-0.149999,0.063629,0.032940,-0.029925,0.002428,0.052438,-0.024259,-0.000462,0.004025,-0.037703,0.012892,-0.012401,-0.044341,0.070714,0.030852,-0.022582,0.159383,0.041918,-0.003680,-0.027373,0.015890,-0.079918,0.046941,0.046236,0.036299,0.066485,-0.023775,-0.031196,0.009114,0.065309,-0.033780,-0.048204,-0.000066,0.029089,0.014088,-0.033346,-0.047687,-0.029563,0.013562,0.025532,0.021691,0.011945,0.034211,-0.036508,-0.000594,-0.004532,-0.007462,0.000012,0.003351,0.013241,0.041728,0.016402,-0.002984,0.030432,0.028853,-0.028717,-0.025719,-0.052691,0.001095,0.019845,-0.002567,-0.058738,0.034502,0.005373,0.026171,0.020127,0.022007,-0.020962,-0.027217,0.025405,-0.020779,0.014818,-0.026313,0.004178,0.019359,-0.021494,-0.027382,0.045601,-0.038545,-0.056272,0.040210,0.006677,-0.039778,0.030839,-0.014617,0.006912,-0.030934,-0.021980,0.007721,0.032819,-0.030178,-0.014516,-0.019618,-0.011318,0.014966,0.044775,-0.005767,0.018571,0.040382,0.043330,-0.026895,0.021511,0.015915,0.038290,-0.017584,0.004245,-0.017202,0.024369,-0.013239,-0.008324,0.028224,0.040272,-0.002205,0.009691,-0.032332,0.037062,0.017641,-0.006146,-0.020431,-0.014117,-0.007295,-0.001494,0.018983,-0.012901,0.011172,-0.005895,0.009558,-0.003325,0.015059,0.025263,-0.022237,0.060879,0.015981,0.017196,-0.002125,0.007762,0.001673,-0.022553,-0.006871,0.017024,0.021484,-0.046161,0.027117,0.051850,0.007578,-0.012628,0.019280,0.011891,0.008518,0.018874,-0.015337,0.036233,-0.023559,0.009720,0.012382,-0.034651,0.012400,-0.027353,-0.005547,0.019104,-0.047072,0.006491,-0.039092,-0.061500,-0.000121,0.007155,-0.005601,0.034050,-0.001088,0.014417,-0.009232,0.012555,-0.012744,0.046162,0.000906,0.039759,-0.007223,0.003844,0.050336,-0.013732,-0.002823,0.007491,-0.031241,0.038498,0.023349,0.011865,-0.012218,-0.008905,0.087717,-0.034785,0.029018,0.028218,0.032772,0.040696,-0.005858,0.030184,-0.052476,0.003957,-0.094581,0.056383,0.005090,-0.008526,-0.016663,-0.020389,-0.025368,0.009741,-0.006208,0.062136,0.017239,0.047100,0.063502,-0.069763,-0.008333,-0.100094,-0.103329,0.013100,0.026504,0.019163,0.022844,0.061741,-0.099778,-0.040678,-0.017302,0.050442,-0.032312,-0.019222,0.001714,-0.011180,2026-03-17 01:00:00
2,2026-03-17 00:45:16,kpszsu,0.105084,-0.046298,0.205981,0.022232,0.084708,-0.026968,-0.018273,0.035228,0.011104,0.012668,0.256708,0.171674,-0.167075,0.049015,-0.141766,0.007056,0.058707,0.227561,0.175420,0.129212,0.051936,0.016562,-0.100967,0.107908,0.086987,-0.068439,0.003396,-0.118361,-0.037934,-0.028892,0.053700,-0.062491,0.016984,0.035380,-0.029684,0.070358,0.004297,0.058915,0.145860,-0.015504,-0.066756,0.038467,0.044416,-0.105012,-0.000332,0.016199,0.008431,0.033092,-0.025877,-0.019219,-0.019688,0.054911,-0.003414,-0.012124,0.017088,-0.025771,-0.003911,0.005257,-0.022092,-0.026852,0.007023,0.056990,0.060005,0.012899,0.027598,-0.025051,0.009237,0.001975,-0.003508,0.016622,-0.016613,-0.015368,0.027598,0.009586,-0.027132,0.031524,0.014735,-0.057399,-0.035300,-0.043781,0.025107,0.025224,0.012144,-0.080650,0.067541,-0.015216,-0.005507,-0.075218,0.010542,-0.043353,-0.012417,0.034512,-0.017629,0.040248,-0.037723,-0.012209,0.012921,-0.034023,-0.016157,0.041341,-0.044365,-0.042018,0.026374,-0.003383,-0.031019,0.024522,0.000008,0.013725,-0.034833,-0.033750,0.000645,0.027322,-0.027107,-0.028914,-0.025834,-0.014569,0.018640,0.034904,-0.006686,0.030703,0.047056,0.028257,-0.029696,0.019813,0.007009,0.003299,0.004024,0.037968,-0.007443,0.017785,0.002201,-0.028063,0.029215,0.001624,0.007756,0.006892,0.007746,-0.005293,0.007887,0.001488,-0.005918,-0.006704,0.011983,0.008847,0.030397,0.005884,-0.000754,-0.013624,-0.001285,-0.021799,0.006546,0.030952,-0.005749,0.046793,-0.020911,0.008099,-0.006064,-0.001224,0.001652,0.005072,-0.000833,0.005461,-0.002096,-0.046314,-0.026112,0.000856,-0.003517,-0.011551,0.011186,-0.004431,-0.010931,-0.002757,0.004268,-0.004567,-0.041279,-0.005649,0.015248,-0.015297,-0.002424,-0.018278,-0.012699,0.025262,-0.033443,-0.004119,-0.028482,-0.019176,0.005992,-0.002140,0.004348,0.008520,-0.011717,-0.005097,-0.006033,0.005057,-0.005517,0.024310,0.036965,-0.002765,0.017872,0.005523,0.007311,-0.000949,0.029967,0.002951,0.002448,0.030331,0.014670,0.002061,-0.022851,-0.025745,0.037327,-0.003633,0.019323,0.018550,0.020266,0.039182,0.020342,0.024751,-0.054518,0.005665,-0.061892,0.060482,0.006192,-0.020693,-0.006436,0.006757,0.017694,0.006223,-0.014864,0.017611,0.051557,0.029833,0.050085,-0.002730,-0.008607,-0.084603,-0.059504,-0.017975,0.054269,0.016123,-0.006270,-0.004745,-0.021264,-0.040773,0.023039,0.027518,-0.034993,0.000479,0.020928,-0.028859,2026-03-17 00:00:00
3,2026-03-17 00:33:10,kpszsu,0.157535,-0.071472,0.326986,0.093080,0.102398,-0.106918,-0.002767,0.013840,-0.095454,-0.025148,0.126537,0.113714,-0.047401,0.021931,0.047574,0.173796,0.093499,-0.026190,-0.103364,0.002587,-0.036625,0.001888,-0.012957,0.348204,0.059674,-0.078542,-0.022091,0.087036,-0.004032,0.043401,-0.004430,0.045495,0.061583,-0.116436,-0.006978,0.073243,0.073548,-0.065315,0.164541,-0.034224,-0.124791,-0.137846,0.081421,-0.066593,-0.097558,-0.000447,-0.033104,0.008700,-0.126692,-0.003739,0.004673,0.052261,0.084910,0.006517,0.025257,0.064814,0.009505,-0.042701,-0.064888,0.006151,0.064699,-0.046971,-0.020759,-0.043696,-0.033699,-0.063607,-0.035293,0.129424,0.089013,-0.043548,-0.003238,-0.010730,0.037873,-0.001692,-0.026928,0.085015,-0.034597,-0.038893,-0.083847,-0.066816,0.005148,-0.047564,0.016877,-0.013450,0.003747,-0.047701,-0.009025,0.029263,0.135268,-0.040976,0.038661,-0.057250,-0.034475,0.119960,-0.017549,-0.024396,-0.034516,0.051513,0.017700,-0.036808,0.024788,0.016020,-0.001344,-0.000272,-0.005811,0.035357,0.010039,0.013435,-0.032259,0.017766,-0.042356,-0.020955,-0.019849,-0.018692,0.019065,-0.029051,-0.023030,0.029229,0.001599,-0.008910,0.039998,-0.028329,-0.016452,-0.001025,-0.002825,-0.052526,0.025843,0.011630,0.000089,0.049061,0.039794,-0.041036,-0.020850,-0.044902,-0.008521,-0.049821,0.130815,0.008565,0.003646,0.027318,0.035037,0.000728,-0.023164,0.031708,0.023820,0.024722,-0.023195,0.062995,-0.056316,-0.009654,-0.024351,0.023498,0.049273,-0.008360,-0.019477,-0.004215,-0.013292,-0.045806,0.013138,-0.138738,-0.017433,-0.040693,-0.037609,-0.043765,0.056655,-0.014737,-0.045464,0.020936,-0.021661,-0.019726,0.014913,0.049683,-0.046037,0.009127,0.048342,0.022217,0.002301,-0.030900,0.032640,0.002944,0.052944,-0.004791,0.054912,-0.005396,-0.005737,-0.015156,-0.044975,0.023627,0.022784,-0.036272,0.003612,-0.013702,-0.030584,-0.034615,-0.075749,-0.045365,0.058842,0.078412,-0.080768,-0.023364,0.091381,-0.054169,0.099914,0.033261,0.113589,0.014300,0.038528,0.015061,-0.036444,0.006221,0.015163,-0.059150,-0.006163,0.077840,0.027629,-0.045494,-0.011676,0.007961,0.006003,-0.021858,-0.002265,-0.002166,0.007077,0.013411,0.017994,-0.035065,0.019670,-0.004608,-0.006582,-0.022644,0.001066,-0.003627,0.019168,-0.010144,-0.011657,-0.018929,-0.002369,0.000273,0.026089,-0.009492,-0.002598,0.002334,-0.003293,-0.005758,0.003161,0.003687,-0.003392,-0.015742,0.024436,0.006963,2026-03-17 00:00:00
4,2026-03-16 23:30:39,kpszsu,0.086284,-0.013447,0.206107,0.011940,0.060368,-0.059965,-0.001821,0.019170,-0.004458,-0.009648,0.225544,0.156530,-0.135636,0.055203,-0.098784,0.020448,0.017467,0.057409,-0.180284,0.078452,-0.150403,-0.082255,0.083102,0.028168,0.146435,0.058102,-0.041051,-0.054629,-0.001966,-0.077432,0.057427,0.001955,-0.096813,-0.050339,0.049807,0.033074,0.008641,0.064747,-0.015792,-0.010306,-0.003599,0.005837,-0.016538,0.033314,-0.094433,-0.089436,-0.007744,-0.018319,-0.001537,0.005980,-0.067055,-0.008179,-0.030991,0.012513,-0.028641,-0.036708,-0.013484,0.025631,-0.039420,-0.052131,-0.006948,0.013703,0.025137,0.005163,-0.000478,-0.018326,-0.013158,-0.035966,-0.021579,0.040714,0.004467,-0.043439,0.030601,0.006101,-0.038502,0.024962,-0.004806,-0.053136,-0.038796,-0.027540,0.012633,0.051862,0.030648,-0.046695,0.091882,-0.018502,-0.012556,-0.091033,-0.002592,-0.010190,0.007522,0.035732,-0.022504,0.059741,-0.013541,-0.004720,0.015781,-0.028124,0.028541,-0.046519,-0.008490,0.038174,0.045450,-0.060776,-0.024765,-0.104436,0.038963,0.001431,0.107465,0.030285,0.169420,0.082742,-0.060005,0.125142,0.124934,0.235560,-0.004497,0.298645,-0.045009,-0.158774,0.081241,0.040379,0.046264,-0.013366,0.084232,0.051756,0.063677,0.003895,-0.013856,0.059364,0.020009,-0.032260,0.031630,-0.045375,-0.021741,0.023400,-0.013403,0.033449,-0.001340,-0.006783,-0.018940,-0.004541,0.001201,-0.025616,0.009844,0.001418,-0.011174,0.013933,-0.028911,0.008501,-0.011928,-0.008648,0.004568,0.006973,-0.021269,0.006889,-0.013873,0.003899,0.004513,0.014755,-0.031048,-0.037680,-0.005877,-0.027442,0.010634,-0.030291,-0.029992,0.020678,0.027016,0.026559,-0.028472,-0.023276,0.005586,-0.016526,0.007086,-0.015285,0.017279,-0.001579,-0.025486,0.007684,-0.003522,-0.003363,0.015039,-0.008244,-0.024590,0.001974,0.006857,0.006517,0.006724,-0.006835,-0.014678,0.009219,-0.005719,-0.018043,0.019360,-0.007094,0.009129,-0.014171,0.035966,0.004124,-0.003560,0.001255,-0.005335,0.003899,0.001262,0.001385,0.001416,-0.009663,0.001845,0.012063,-0.021216,0.003721,-0.003337,0.006796,-0.002613,-0.005347,-0.005237,-0.005359,0.005972,-0.011846,0.002321,-0.016305,0.006143,0.006003,0.002693,-0.001045,-0.016132,0.003167,-0.013464,-0.013161,0.002457,0.007259,-0.007108,0.003937,-0.002485,-0.003352,-0.009933,-0.011002,0.000517,-0.006357,0.000333,0.018163,-0.014486,0.006608,-0.000406,0.008269,0.006597,-0.000130,0.009959,0.008867,2026-03-16 23:00:00

In [34]:
#tg_hourly["datetime_hour"] = tg_hourly["datetime_hour"] + pd.Timedelta(hours=1)        ТУТ ЗСУВ ТГ НА 1 ГОДИНУ

In [35]:
df_final = df_final.merge(tg_hourly, on="datetime_hour", how="left")

In [36]:
df_final.sample(20)

,datetime_hour,region_id,day_tempmax,day_tempmin,day_temp,day_dew,day_humidity,day_precip,day_precipprob,day_precipcover,day_windgust,day_cloudcover,day_moonphase,hour_temp,hour_feelslike,hour_humidity,hour_dew,hour_precip,hour_precipprob,hour_snow,hour_snowdepth,hour_windgust,hour_windspeed,hour_winddir,hour_pressure,hour_cloudcover,hour_solarradiation,hour_solarenergy,hour_uvindex,hour_conditions_simple_Clear,hour_conditions_simple_Cloudy,hour_conditions_simple_Rain,hour_conditions_simple_Snow,day_of_week,hour,city_name,day_datetime,day_sunrise,day_sunset,region_key,alarm_active,alarm_minutes_in_hour,alarm_lag_1,alarm_lag_3,alarm_lag_6,alarm_lag_12,alarms_in_last_24h,is_weekend,is_night,total_active_alarms_lag1,neighbour_alarms,hours_since_last_alarm,isw_topic_0,isw_topic_1,isw_topic_2,isw_topic_3,isw_topic_4,isw_topic_5,isw_topic_6,isw_topic_7,isw_topic_8,isw_topic_9,isw_topic_10,isw_topic_11,isw_topic_12,isw_topic_13,isw_topic_14,isw_topic_15,isw_topic_16,isw_topic_17,isw_topic_18,isw_topic_19,isw_topic_20,isw_topic_21,isw_topic_22,isw_topic_23,isw_topic_24,isw_topic_25,isw_topic_26,isw_topic_27,isw_topic_28,isw_topic_29,isw_topic_30,isw_topic_31,isw_topic_32,isw_topic_33,isw_topic_34,isw_topic_35,isw_topic_36,isw_topic_37,isw_topic_38,isw_topic_39,isw_topic_40,isw_topic_41,isw_topic_42,isw_topic_43,isw_topic_44,isw_topic_45,isw_topic_46,isw_topic_47,isw_topic_48,isw_topic_49,isw_topic_50,isw_topic_51,isw_topic_52,isw_topic_53,isw_topic_54,isw_topic_55,isw_topic_56,isw_topic_57,isw_topic_58,isw_topic_59,isw_topic_60,isw_topic_61,isw_topic_62,isw_topic_63,isw_topic_64,isw_topic_65,isw_topic_66,isw_topic_67,isw_topic_68,isw_topic_69,isw_topic_70,isw_topic_71,isw_topic_72,isw_topic_73,isw_topic_74,isw_topic_75,isw_topic_76,isw_topic_77,isw_topic_78,isw_topic_79,isw_topic_80,isw_topic_81,isw_topic_82,isw_topic_83,isw_topic_84,isw_topic_85,isw_topic_86,isw_topic_87,isw_topic_88,isw_topic_89,isw_topic_90,isw_topic_91,isw_topic_92,isw_topic_93,isw_topic_94,isw_topic_95,isw_topic_96,isw_topic_97,isw_topic_98,isw_topic_99,isw_topic_100,isw_topic_101,isw_topic_102,isw_topic_103,isw_topic_104,isw_topic_105,isw_topic_106,isw_topic_107,isw_topic_108,isw_topic_109,isw_topic_110,isw_topic_111,isw_topic_112,isw_topic_113,isw_topic_114,isw_topic_115,isw_topic_116,isw_topic_117,isw_topic_118,isw_topic_119,isw_topic_120,isw_topic_121,isw_topic_122,isw_topic_123,isw_topic_124,isw_topic_125,isw_topic_126,isw_topic_127,isw_topic_128,isw_topic_129,isw_topic_130,isw_topic_131,isw_topic_132,isw_topic_133,isw_topic_134,isw_topic_135,isw_topic_136,isw_topic_137,isw_topic_138,isw_topic_139,isw_topic_140,isw_topic_141,isw_topic_142,isw_topic_143,isw_topic_144,isw_topic_145,isw_topic_146,isw_topic_147,isw_topic_148,isw_topic_149,isw_total_intensity,isw_topic_std,isw_topic_max,isw_topic_mean,isw_velocity_24h,isw_intensity_ema,isw_topic_entropy,tg_topic_0,tg_topic_1,tg_topic_2,tg_topic_3,tg_topic_4,tg_topic_5,tg_topic_6,tg_topic_7,tg_topic_8,tg_topic_9,tg_topic_10,tg_topic_11,tg_topic_12,tg_topic_13,tg_topic_14,tg_topic_15,tg_topic_16,tg_topic_17,tg_topic_18,tg_topic_19,tg_topic_20,tg_topic_21,tg_topic_22,tg_topic_23,tg_topic_24,tg_topic_25,tg_topic_26,tg_topic_27,tg_topic_28,tg_topic_29,tg_topic_30,tg_topic_31,tg_topic_32,tg_topic_33,tg_topic_34,tg_topic_35,tg_topic_36,tg_topic_37,tg_topic_38,tg_topic_39,tg_topic_40,tg_topic_41,tg_topic_42,tg_topic_43,tg_topic_44,tg_topic_45,tg_topic_46,tg_topic_47,tg_topic_48,tg_topic_49,tg_topic_50,tg_topic_51,tg_topic_52,tg_topic_53,tg_topic_54,tg_topic_55,tg_topic_56,tg_topic_57,tg_topic_58,tg_topic_59,tg_topic_60,tg_topic_61,tg_topic_62,tg_topic_63,tg_topic_64,tg_topic_65,tg_topic_66,tg_topic_67,tg_topic_68,tg_topic_69,tg_topic_70,tg_topic_71,tg_topic_72,tg_topic_73,tg_topic_74,tg_topic_75,tg_topic_76,tg_topic_77,tg_topic_78,tg_topic_79,tg_topic_80,tg_topic_81,tg_topic_82,tg_topic_83,tg_topic_84,tg_topic_85,tg_topic_86,tg_topic_87,tg_topic_88,tg_topic_89,tg_topic_90,tg_topic_91,tg_topic_92,tg_topic_93,tg_topic_94,tg_topic_95,tg_topic_96,tg_topic_97,tg_topic_98,tg_topic_99,tg_topic_100,tg_topic_101,tg_topic_102,tg_topic_103,tg_topic_104,tg_topic_105,tg_topic_106,tg_topic_107,tg_topic_108,tg_topic_109,tg_topic_110,tg_topic_111,tg_topic_112,tg_topic_113,tg_topic_114,tg_topic_115,tg_topic_116,tg_topic_117,tg_topic_118,tg_topic_119,tg_topic_120,tg_topic_121,tg_topic_122,tg_topic_123,tg_topic_124,tg_topic_125,tg_topic_126,tg_topic_127,tg_topic_128,tg_topic_129,tg_topic_130,tg_topic_131,tg_topic_132,tg_topic_133,tg_topic_134,tg_topic_135,tg_topic_136,tg_topic_137,tg_topic_138,tg_topic_139,tg_topic_140,tg_topic_141,tg_topic_142,tg_topic_143,tg_topic_144,tg_topic_145,tg_topic_146,tg_topic_147,tg_topic_148,tg_topic_149,tg_topic_150,tg_topic_151,tg_topic_152,tg_topic_153,tg_topic_154,tg_topic_155,tg_topic_156,tg_topic_157,tg_topic_158,tg_topic_159,tg_topic_160,tg_topic_161,tg_topic_162,tg_topic_163,tg_topic_164,tg_topic_165,tg_topic_166,tg_topic_167,tg_topic_168,tg_topic_169,tg_topic_170,tg_topic_171,tg_topic_172,tg_topic_173,tg_topic_174,tg_topic_175,tg_topic_176,tg_topic_177,tg_topic_178,tg_topic_179,tg_topic_180,tg_topic_181,tg_topic_182,tg_topic_183,tg_topic_184,tg_topic_185,tg_topic_186,tg_topic_187,tg_topic_188,tg_topic_189,tg_topic_190,tg_topic_191,tg_topic_192,tg_topic_193,tg_topic_194,tg_topic_195,tg_topic_196,tg_topic_197,tg_topic_198,tg_topic_199,tg_topic_200,tg_topic_201,tg_topic_202,tg_topic_203,tg_topic_204,tg_topic_205,tg_topic_206,tg_topic_207,tg_topic_208,tg_topic_209,tg_topic_210,tg_topic_211,tg_topic_212,tg_topic_213,tg_topic_214,tg_topic_215,tg_topic_216,tg_topic_217,tg_topic_218,tg_topic_219,tg_topic_220,tg_topic_221,tg_topic_222,tg_topic_223,tg_topic_224,tg_topic_225,tg_topic_226,tg_topic_227,tg_topic_228,tg_topic_229,tg_topic_230,tg_topic_231,tg_topic_232,tg_topic_233,tg_topic_234,tg_topic_235,tg_topic_236,tg_topic_237,tg_topic_238,tg_topic_239,tg_topic_240,tg_topic_241,tg_topic_242,tg_topic_243,tg_topic_244,tg_topic_245,tg_topic_246,tg_topic_247,tg_topic_248,tg_topic_249
495889,2022-12-02 09:00:00,17,-2.3,-5.1,-3.5,-5.3,87.4,0.000,0.0,0.00,21.6,97.4,0.27,-4.5,-8.5,88.58,-6.1,0.0,0.0,0.0,2.0,17.6,9.4,78.1,1030.0,97.9,24.0,0.1,0.0,False,True,False,False,4,9,Rivne,2022-12-02,07:55:35,16:12:54,Рівненська,0,0.000000,0.0,0.0,0.0,0.0,2.0,0,0,0.0,0.0,17,0.815950,-0.180205,-0.015774,-0.048260,0.118890,-0.012299,-0.095065,0.125515,-0.081084,-0.033412,-0.029388,0.000923,0.022468,0.032553,-0.076443,0.086747,-0.065476,0.025995,-0.118839,0.088334,0.029250,0.042544,-0.018216,0.001260,-0.062363,-0.006034,-0.000167,-0.012534,-0.061868,-0.017368,-0.009515,-0.031152,-0.010873,-0.024890,-0.014971,0.004052,0.021307,-0.011973,-0.022671,0.022755,-0.006972,-0.062452,0.023572,0.009049,0.005574,0.035340,-0.020158,-0.019960,-0.023114,0.035755,0.050735,-0.019701,0.005067,0.019812,0.001215,0.049401,-0.016628,0.009487,0.034536,-0.019194,-0.023289,0.017525,-0.032851,0.022613,-0.012124,0.016344,-0.000370,5.480664e-03,-0.019582,0.023199,-0.008926,0.016847,-0.042280,-0.034781,0.018946,0.024795,0.003549,0.005008,0.010909,0.022694,-0.013618,-0.001625,-0.042738,0.018778,0.036052,-0.016520,-0.003708,-0.011550,0.014514,0.005848,-0.029299,0.034039,0.044430,-0.027656,0.017009,-0.024397,-0.026415,-0.073650,-0.000666,0.000471,0.020934,-0.004838,-0.016440,-0.003281,0.015780,0.027565,-0.013018,-0.006504,-0.006294,-0.010641,0.000651,0.023984,0.000616,-0.014029,0.028264,-0.017487,-0.003589,0.028480,0.006109,-0.027507,0.023955,0.003395,-0.001319,0.021107,-0.003837,0.019586,-0.007895,-0.001690,-0.014270,0.042747,-0.017159,-0.011998,0.000916,0.000368,-0.023512,-0.003104,-0.024876,0.013440,0.006410,-0.010329,0.021700,-0.006918,-0.011933,-0.025284,0.006007,-0.012300,0.001650,-0.022527,-0.016922,0.011950,4.437317,0.069926,0.815950,0.029582,-0.029751,4.467150,4.196942,0.009150,-0.002421,0.024107,0.008288,-0.012985,0.032174,-0.017187,0.083168,0.021393,-0.030792,-0.027214,0.003590,-0.004832,0.022446,-0.011631,-0.017182,0.016852,-0.028505,0.005236,-0.043653,-0.003895,0.003930,-0.036748,-0.012173,0.017072,0.017300,-0.030353,-0.027035,-0.002601,0.022207,0.007281,0.007225,-0.004688,-0.010953,-0.011395,0.003845,0.004761,-0.012605,-0.005359,-0.003918,-0.006562,0.002906,0.000285,0.004306,0.001999,-0.002847,-0.003916,-0.005479,-0.001436,-0.000867,-0.005517,0.003056,0.001066,-0.002571,0.004867,-0.001077,-0.004532,-0.005657,0.001010,0.009108,-0.011272,0.000585,-0.019969,0.001113,0.006064,-0.005147,-0.008375,-0.003496,0.003620,0.015315,-0.025361,-0.010143,-0.004491,-0.009421,0.008132,0.000770,0.001300,-0.003886,-0.001698,-0.007886,-0.003490,-0.001170,-0.003087,-0.013192,0.000741,-0.015662,-0.009112,-0.002911,0.006149,0.000923,-0.003838,0.005600,-0.009508,-0.000040,-0.007514,0.008746,0.001165,0.002811,-0.000961,-0.008913,-0.014817,0.006353,0.001031,0.012126,-0.000173,0.002132,-0.004480,0.020265,-0.008225,0.004577,0.013858,-0.011833,0.015486,-0.001410,0.017820,0.002967,0.007065,-0.006574,-0.006002,-0.000685,0.010608,0.001632,-0.001863,-0.009704,-0.001748,0.012256,-0.013676,0.019453,0.010714,-0.009623,-0.007216,0.008949,0.004973,-0.011879,-0.001664,0.013964,-0.010557,0.009498,-0.002786,0.014739,0.009975,-0.001359,-0.010473,0.011349,0.011071,0.008210,-0.007094,0.019050,0.009003,0.008701,0.021771,-0.005489,0.000032,0.008568,-0.012729,0.003842,0.008130,-0.002032,-0.019708,0.013707,0.012012,0.006046,-0.004902,-0.017061,-0.003620,0.010974,0.006700,0.001418,-0.026201,0.011984,0.008359,0.011465,-0.012049,-0.002799,0.003023,-0.001542,-0.001977,-0.005661,-0.005813,-0.001067,0.003740,-0.001023,0.007947,0.005898,0.001912,0.007335,-0.002375,0.003850,-0.005766,-0.000041,-0.006598,-0.002492,-0.005715,-0.000311,-0.002818,0.001130,-0.016821,-0.021069,-0.005871,0.004962,-0.001701,-0.017754,-0.003012,-0.018584,0.012516,-0.007841,0.022842,-0.001848,0.005305,0.006969,0.004975,0.031777,0.017532,0.009846,0.006593,0.004835,0.012495,-0.004722,0.016515,-0.005474,-0.013837,-0.001782,-0.023552,0.011852,-0.009616,-0.016071,-0.000153,0.010111,0.000654,0.002218,0.000808,0.000612,-0.003555,-0.012321,-0.017281,0.001486,0.009118,0.001128,0.003491,0.001064,0.009449,-0.004941,0.007297,0.011521,0.004476,0.011012,0.011739,-0.014879,-0.005948,0.002017
173365,2022-08-31 09:00:00,7,27.0,12.4,19.2,10.4,59.5,0.000,0.0,0.00,37.4,47.9,0.12,18.1,18.1,77.46,14.1,0.0,0.0,0.0,0.0,16.2,0.1,348.0,1017.5,30.2,209.0,0.8,2.0,False,True,False,False,2,9,Uzhgorod,2022-08-31,06:46:12,20:15:20,Закарпатська,0,0.000000,0.0,0.0,0.0,0.0,0.0,0,0,0.0,0.0,61,0.782098,-0.246752,0.153086,-0.103483,-0.051319,0.063238,0.036831,0.020989,-0.087397,0.125973,-0.000523,0.006678,-0.000366,0.089186,-0.104712,0.035248,-0.089148,0.091038,-0.013426,0.053161,0.024725,-0.043504,-0.041086,-0.014882,0.049415,-0.015518,-0.018356,0.035722,0.023631,0.024514,-0.053130,0.049531,-0.048637,0.043578,-0.046740,0.026778,-0.022020,-0.009384,0.022887,-0.077606,0.013711,0.061679,-0.063710,-0.029081,0.046874,-0.035425,0.023788,-0.005691,-0.003650,-0.012900,-0.038118,0.017977,-0.015444,-0.024211,0.027537,0.005423,-0.015492,0.001837,-0.006111,0.015166,-0.001461,-0.018909,0.024413,0.004262,-0.016936,-0.001404,0.020312,1.168085e-02,-0.034325,0.009560,0.015082,-0.005692,-0.008700,-0.008643,0.000025,-0.002309,-0.023872,-0.017945,0.029671,-0.030444,0.011308,0.016732,0.009413,0.016193,0.020239,-0.017780,0.000048,-0.016245,0.015990,-0.005479,-0.015881,0.046632,0.039160,-0.000702,-0.017110,-0.003292,-0.006061,-0.022033,0.005788,0.029599,-0.022130,0.022112,-0.033170,-0.044853,0.007415,-0.004284,0.003326,0.009354,0.004226,-0.014919,0.016527,-0.006582,0.054755,-0.024591,0.002726,0.033509,0.007190,-0.002882,-0.003118,-0.053895,0.005380,0.000786,-0.005591,-0.003954,0.000133,0.016784,0.023212,0.027077,0.003017,0.010180,-0.016554,-0.004811,0.007474,0.005285,0.005330,-0.013771,0.033217,0.000820,0.055039,0.017042,0.037398,0.016521,-0.020533,-0.023080,0.024324,0.001142,0.050559,0.000430,0.004211,-0.007294,4.723971,0.069265,0.782098,0.031493,-0.369490,4.891069,4.206467,0.030525,-0.010424,0.044570,0.000518,-0.004207,0.040825,-0.029457,0.131057,0.029879,-0.055396,0.174909,-0.156297,0.076931,0.038400,0.017789,0.012055,-0.017680,0.008042,-0.032454,-0.016868,0.023115,-0.010401,-0.043050,-0.034701,0.038369,-0.032167,0.015688,0.056370,0.001925,0.003060,-0.003501,-0.005612,0.010036,0.014398,-0.000247,0.001207,0.007003,0.002647,-0.024309,-0.014022,-0.003141,-0.004319,-0.007339,0.011757,0.002988,0.015284,0.003469,-0.014624,-0.011698,-0.022269,-0.019450,0.038106,0.028985,0.025161,-0.003981,0.032993,0.081319,-0.026358,0.025653,-0.083178,-0.023118,0.031402,-0.130914,0.133327,0.011202,-0.036631,0.040985,0.011335,0.013784,0.000504,-0.053705,-0.030059,-0.004691,0.006746,-0.052909,-0.044899,0.015593,-0.001342,-0.003682,-0.009109,-0.003942,-0.001201,-0.002796,-0.001603,0.002677,-0.002598,0.000187,-0.001110,-0.018098,-0.009014,0.005767,-0.006513,0.010918,0.005181,0.000620,-0.006025,0.011984,0.002781,0.011474,-0.007495,-0.016408,0.007343,-0.003171,0.006661,-0.014401,0.005574,-0.004952,0.011377,-0.018003,0.019020,0.031613,-0.003628,0.020809,-0.033258,0.016189,0.014654,0.003170,-0.005392,-0.017443,0.032306,0.011385,-0.000180,-0.025885,-0.035080,0.023358,-0.009793,0.013977,-0.011469,-0.013945,-0.006669,0.007613,-0.011205,-0.024127,0.005042,-0.007284,0.015868,-0.001844,-0.003318,0.000165,-0.004199,-0.001853,-0.005855,-0.007109,0.002351,-0.000960,0.003850,0.003491,-0.004303,-0.006112,-0.003875,0.000650,0.001280,-0.003532,-0.003365,-0.004493,-0.002887,-0.003045,-0.005667,0.000986,-0.002750,-0.014746,-0.002312,0.019649,0.008503,-0.007231,0.006116,0.004386,0.010875,0.004942,-0.002041,0.006267,0.010597,0.000280,0.010004,-0.004153,-0.000869,-0.010345,0.008206,-0.015727,0.001783,-0.000202,0.003191,0.007824,-0.001577,-0.005803,-0.008019,-0.000627,0.004488,0.001442,0.016561,-0.004528,0.002579,-0.006853,0.005577,0.011988,-0.003985,0.007738,0.017538,-0.011907,0.000197,0.007812,0.006806,-0.006035,0.000962,0.009681,-0.000526,-0.004491,-0.011392,-0.005243,-0.004456,-0.003945,-0.009199,-0.009075,-0.004797,0.004616,0.009405,0.029407,0.007903,-0.010074,0.022484,-0.011508,-0.005708,-0.015316,0.002412,0.011995,0.012688,-0.001809,-0.002337,0.003066,-0.010548,-0.001267,-0.002244,0.000191,-0.001199,-0.005705,0.006743,0.008452,-0.012742,0.011402,0.006041,-0.015072,0.024008,0.001690,-0.005320,-0.001204,-0.019315,-0.011046,0.007429,0.000589,0.004479
624930,2025-06-17 17:00:00,20,26.3,13.7,20.4,13.3,66.7,0.400,100.0,4.17,32.4,31.3,0.71,24.0,24.0,51.83,13.5,0.0,0.0,0.0,0.0,22.0,14.4,330.0,1010.0,0.0,236.6,0.9,2.0,True,False,False,False,1,17,Kharkiv,2025-06-17,04:25:22,20:46:57,Харківська,1,12.166667,1.0,0.0,1.0,1.0,15.0,0,0,3.0,1.0,0,0.759705,0.292549,0.074489,0.035142,-0.173023,0.075889,-0.016877,0.032656,0.102619,-0.128633,-0.006775,0.279896,-0.110410,-0.076520,-0.007797,-0.015823,-0.088817,-0.025046,-0.038926,-0.028337,-0.120548,-0.039972,-0.018855,0.035239,-0.040547,0.054720,-0.045824,0.004136,0.060590,0.002067,0.035087,-0.017825,0.006720,0.017739,-0.048048,0.013400,-0.002699,0.011469,0.004308,-0.007176,-0.006728,0.027747,0.029975,-0.016892,0.014090,0.024459,-0.042792,0.033228,-0.003218,-0.027104,0.019342,-0.010949,0.009152,-0.012782,-0.008981,-0.003728,-0.016578,0.017349,0.020415,0.011838,-0.009788,-0.004738,-0.015880,-0.027261,0.005230,0.021377,0.011193,3.061878e-02,-0.014870,-0.005678,0.016609,0.017568,-0.016993,0.009495,-0.015717,-0.007797,0.026706,-0.001724,-0.014928,-0.000135,0.008445,0.001815,0.003907,0.018404,0.003835,0.001445,0.017208,0.009688,-0.018694,0.005389,0.043573,0.007050,0.008336,0.014984,-0.016445,-0.009198,0.018840,0.015115,-0.005540,-0.005803,0.018829,0.023696,-0.029971,0.002658,-0.028904,-0.041945,-0.007905,0.030205,0.019117,0.013629,-0.012240,0.000659,-0.002798,-0.006747,-0.001944,-0.017002,0.017063,-0.017778,0.005528,0.003253,0.006504,-0.014211,-0.006298,0.008506,-0.022664,0.001139,0.003859,-0.014260,0.004434,-0.013548,0.026200,-0.004263,0.007004,0.017947,-0.003481,0.009617,0.003728,0.009548,0.009689,-0.014589,-0.000877,-0.013844,-0.008722,-0.015289,-0.001346,-0.013954,0.002650,0.000273,-0.002613,0.015654,4.400846,0.072066,0.759705,0.029339,-0.132652,4.427471,4.035635,0.190294,0.005819,-0.003348,0.011593,-0.124848,-0.068776,0.104915,0.055571,-0.022134,-0.046298,-0.007235,0.010266,-0.006226,-0.006594,0.010834,-0.013161,0.021712,-0.008549,0.020263,-0.040179,-0.004131,-0.054541,-0.036464,0.014832,-0.021360,0.015951,-0.048757,0.007486,0.028095,-0.004094,-0.007083,0.012185,0.004386,0.037273,-0.040861,-0.039901,0.030399,0.015891,0.014303,-0.039543,-0.035368,0.002775,0.019567,0.037351,0.010652,0.012231,0.011354,-0.004169,0.050580,0.005983,0.011788,0.019484,0.011716,0.001485,-0.008792,0.005642,-0.012243,0.004727,0.007974,0.005199,-0.007792,0.012584,-0.006114,0.014309,-0.009541,0.009719,-0.005909,-0.002356,0.004926,0.009757,0.011854,-0.003642,-0.010300,-0.003960,0.007180,0.001387,0.008370,0.014789,-0.001680,-0.008174,-0.000713,-0.005003,-0.004853,-0.000324,-0.016159,-0.018818,-0.008519,-0.009073,0.009139,0.020369,0.007600,0.014918,0.014410,-0.029948,-0.003547,-0.003622,-0.004204,-0.017357,0.007572,0.033409,0.011254,-0.005437,0.022996,-0.020120,0.000974,-0.000938,-0.005871,-0.023850,-0.004856,-0.007001,-0.010559,0.009259,0.047157,0.011343,0.004372,0.006039,0.031565,0.025395,0.003819,-0.003725,-0.008905,0.020929,0.001504,0.007098,-0.000517,-0.007430,-0.021211,0.000677,-0.010523,-0.007980,0.002812,-0.009878,-0.014002,-0.006988,0.007418,-0.004165,0.010353,-0.006267,0.004390,-0.006292,0.008659,0.001909,0.011645,0.008932,0.006222,0.017550,0.000283,-0.015035,-0.019323,-0.017933,0.000807,-0.005945,0.003098,0.007113,0.000402,-0.008502,-0.011102,-0.014274,0.026323,-0.033238,0.020454,0.013276,0.001098,0.021962,-0.032464,0.018353,0.015335,-0.012091,0.017033,0.017509,0.003845,-0.022547,-0.002190,-0.016801,0.011102,-0.001922,0.004387,-0.002595,0.016146,-0.010500,-0.003137,0.008189,0.012305,0.006585,-0.018779,-0.002761,-0.000872,0.005341,-0.010729,0.005253,-0.000823,0.003365,0.000811,0.000931,-0.015371,0.002852,-0.003041,-0.002769,0.005938,0.004470,-0.011385,0.002728,-0.001648,-0.010027,-0.014813,0.000865,0.000177,-0.000395,-0.006146,-0.010199,-0.010763,-0.011448,-0.007693,0.004789,-0.002516,-0.013467,0.009914,0.008217,0.003851,-0.005348,0.012250,-0.005918,0.001034,0.018496,0.010600,0.008529,-0.012197,0.006088,-0.006364,-0.006689,0.004748,0.011605,-0.000789,0.000922,0.014584,-0.001711,0.011090,0.004363,0.010375,0.002903,0.002693,0.001563,-0.003922,-0.001178,-0.003745,-0.003556,-0.004133,-0.010593,0.003441,0.009090

In [37]:
df_final.shape

(844993, 459)

In [38]:
df_final = df_final.sort_values(["datetime_hour"])

In [39]:
with pd.option_context('display.max_rows', None):
    print(df_final.isnull().sum())

datetime_hour                         0
region_id                             0
day_tempmax                           0
day_tempmin                           0
day_temp                              0
day_dew                               0
day_humidity                          0
day_precip                            0
day_precipprob                        0
day_precipcover                       0
day_windgust                          0
day_cloudcover                        0
day_moonphase                         0
hour_temp                             0
hour_feelslike                        0
hour_humidity                         0
hour_dew                              0
hour_precip                           0
hour_precipprob                       0
hour_snow                             0
hour_snowdepth                        0
hour_windgust                         0
hour_windspeed                        0
hour_winddir                          0
hour_pressure                         0
hour_cloudcover                       0
hour_solarradiation                   0
hour_solarenergy                      0
hour_uvindex                          0
hour_conditions_simple_Clear          0
hour_conditions_simple_Cloudy         0
hour_conditions_simple_Rain           0
hour_conditions_simple_Snow           0
day_of_week                           0
hour                                  0
city_name                             0
day_datetime                          0
day_sunrise                           0
day_sunset                            0
region_key                            0
alarm_active                          0
alarm_minutes_in_hour                 0
alarm_lag_1                           0
alarm_lag_3                           0
alarm_lag_6                           0
alarm_lag_12                          0
alarms_in_last_24h                    0
is_weekend                            0
is_night                              0
total_active_alarms_lag1              0
neighbour_alarms                      0
hours_since_last_alarm                0
isw_topic_0                           0
isw_topic_1                           0
isw_topic_2                           0
isw_topic_3                           0
isw_topic_4                           0
isw_topic_5                           0
isw_topic_6                           0
isw_topic_7                           0
isw_topic_8                           0
isw_topic_9                           0
isw_topic_10                          0
isw_topic_11                          0
isw_topic_12                          0
isw_topic_13                          0
isw_topic_14                          0
isw_topic_15                          0
isw_topic_16                          0
isw_topic_17                          0
isw_topic_18                          0
isw_topic_19                          0
isw_topic_20                          0
isw_topic_21                          0
isw_topic_22                          0
isw_topic_23                          0
isw_topic_24                          0
isw_topic_25                          0
isw_topic_26                          0
isw_topic_27                          0
isw_topic_28                          0
isw_topic_29                          0
isw_topic_30                          0
isw_topic_31                          0
isw_topic_32                          0
isw_topic_33                          0
isw_topic_34                          0
isw_topic_35                          0
isw_topic_36                          0
isw_topic_37                          0
isw_topic_38                          0
isw_topic_39                          0
isw_topic_40                          0
isw_topic_41                          0
isw_topic_42                          0
isw_topic_43                          0
isw_topic_44                          0
isw_topic_45                          0
isw_topic_46                          0
isw_topic_47                          0
isw_topic_48                          0
isw_topic_49                          0
isw_topic_50                          0
isw_topic_51                          0
isw_topic_52                          0
isw_topic_53                          0
isw_topic_54                          0
isw_topic_55                          0
isw_topic_56                          0
isw_topic_57                          0
isw_topic_58                          0
isw_topic_59                          0
isw_topic_60                          0
isw_topic_61                          0
isw_topic_62                          0
isw_topic_63                          0
isw_topic_64                          0
isw_topic_65                          0
isw_topic_66                          0
isw_topic_67                          0
isw_topic_68                          0
isw_topic_69                          0
isw_topic_70                          0
isw_topic_71                          0
isw_topic_72                          0
isw_topic_73                          0
isw_topic_74                          0
isw_topic_75                          0
isw_topic_76                          0
isw_topic_77                          0
isw_topic_78                          0
isw_topic_79                          0
isw_topic_80                          0
isw_topic_81                          0
isw_topic_82                          0
isw_topic_83                          0
isw_topic_84                          0
isw_topic_85                          0
isw_topic_86                          0
isw_topic_87                          0
isw_topic_88                          0
isw_topic_89                          0
isw_topic_90                          0
isw_topic_91                          0
isw_topic_92                          0
isw_topic_93                          0
isw_topic_94                          0
isw_topic_95                          0
isw_topic_96                          0
isw_topic_97                          0
isw_topic_98                          0
isw_topic_99                          0
isw_topic_100                         0
isw_topic_101                         0
isw_topic_102                         0
isw_topic_103                         0
isw_topic_104                         0
isw_topic_105                         0
isw_topic_106                         0
isw_topic_107                         0
isw_topic_108                         0
isw_topic_109                         0
isw_topic_110                         0
isw_topic_111                         0
isw_topic_112                         0
isw_topic_113                         0
isw_topic_114                         0
isw_topic_115                         0
isw_topic_116                         0
isw_topic_117                         0
isw_topic_118                         0
isw_topic_119                         0
isw_topic_120                         0
isw_topic_121                         0
isw_topic_122                         0
isw_topic_123                         0
isw_topic_124                         0
isw_topic_125                         0
isw_topic_126                         0
isw_topic_127                         0
isw_topic_128                         0
isw_topic_129                         0
isw_topic_130                         0
isw_topic_131                         0
isw_topic_132                         0
isw_topic_133                         0
isw_topic_134                         0
isw_topic_135                         0
isw_topic_136                         0
isw_topic_137                         0
isw_topic_138                         0
isw_topic_139                         0
isw_topic_140                         0
isw_topic_141                         0
isw_topic_142                         0
isw_topic_143                         0
isw_topic_144                         0
isw_topic_145                         0
isw_topic_146                         0
isw_topic_147                         0
isw_topic_148                         0
isw_topic_149                         0
isw_total_intensity                   0
isw_topic_std                         0
isw_topic_max                         0
isw_topic_mean                        0
isw_velocity_24h                      0
isw_intensity_ema                     0
isw_topic_entropy                     0
tg_topic_0                       137552
tg_topic_1                       137552
tg_topic_2                       137552
tg_topic_3                       137552
tg_topic_4                       137552
tg_topic_5                       137552
tg_topic_6                       137552
tg_topic_7                       137552
tg_topic_8                       137552
tg_topic_9                       137552
tg_topic_10                      137552
tg_topic_11                      137552
tg_topic_12                      137552
tg_topic_13                      137552
tg_topic_14                      137552
tg_topic_15                      137552
tg_topic_16                      137552
tg_topic_17                      137552
tg_topic_18                      137552
tg_topic_19                      137552
tg_topic_20                      137552
tg_topic_21                      137552
tg_topic_22                      137552
tg_topic_23                      137552
tg_topic_24                      137552
tg_topic_25                      137552
tg_topic_26                      137552
tg_topic_27                      137552
tg_topic_28                      137552
tg_topic_29                      137552
tg_topic_30                      137552
tg_topic_31                      137552
tg_topic_32                      137552
tg_topic_33                      137552
tg_topic_34                      137552
tg_topic_35                      137552
tg_topic_36                      137552
tg_topic_37                      137552
tg_topic_38                      137552
tg_topic_39                      137552
tg_topic_40                      137552
tg_topic_41                      137552
tg_topic_42                      137552
tg_topic_43                      137552
tg_topic_44                      137552
tg_topic_45                      137552
tg_topic_46                      137552
tg_topic_47                      137552
tg_topic_48                      137552
tg_topic_49                      137552
tg_topic_50                      137552
tg_topic_51                      137552
tg_topic_52                      137552
tg_topic_53                      137552
tg_topic_54                      137552
tg_topic_55                      137552
tg_topic_56                      137552
tg_topic_57                      137552
tg_topic_58                      137552
tg_topic_59                      137552
tg_topic_60                      137552
tg_topic_61                      137552
tg_topic_62                      137552
tg_topic_63                      137552
tg_topic_64                      137552
tg_topic_65                      137552
tg_topic_66                      137552
tg_topic_67                      137552
tg_topic_68                      137552
tg_topic_69                      137552
tg_topic_70                      137552
tg_topic_71                      137552
tg_topic_72                      137552
tg_topic_73                      137552
tg_topic_74                      137552
tg_topic_75                      137552
tg_topic_76                      137552
tg_topic_77                      137552
tg_topic_78                      137552
tg_topic_79                      137552
tg_topic_80                      137552
tg_topic_81                      137552
tg_topic_82                      137552
tg_topic_83                      137552
tg_topic_84                      137552
tg_topic_85                      137552
tg_topic_86                      137552
tg_topic_87                      137552
tg_topic_88                      137552
tg_topic_89                      137552
tg_topic_90                      137552
tg_topic_91                      137552
tg_topic_92                      137552
tg_topic_93                      137552
tg_topic_94                      137552
tg_topic_95                      137552
tg_topic_96                      137552
tg_topic_97                      137552
tg_topic_98                      137552
tg_topic_99                      137552
tg_topic_100                     137552
tg_topic_101                     137552
tg_topic_102                     137552
tg_topic_103                     137552
tg_topic_104                     137552
tg_topic_105                     137552
tg_topic_106                     137552
tg_topic_107                     137552
tg_topic_108                     137552
tg_topic_109                     137552
tg_topic_110                     137552
tg_topic_111                     137552
tg_topic_112                     137552
tg_topic_113                     137552
tg_topic_114                     137552
tg_topic_115                     137552
tg_topic_116                     137552
tg_topic_117                     137552
tg_topic_118                     137552
tg_topic_119                     137552
tg_topic_120                     137552
tg_topic_121                     137552
tg_topic_122                     137552
tg_topic_123                     137552
tg_topic_124                     137552
tg_topic_125                     137552
tg_topic_126                     137552
tg_topic_127                     137552
tg_topic_128                     137552
tg_topic_129                     137552
tg_topic_130                     137552
tg_topic_131                     137552
tg_topic_132                     137552
tg_topic_133                     137552
tg_topic_134                     137552
tg_topic_135                     137552
tg_topic_136                     137552
tg_topic_137                     137552
tg_topic_138                     137552
tg_topic_139                     137552
tg_topic_140                     137552
tg_topic_141                     137552
tg_topic_142                     137552
tg_topic_143                     137552
tg_topic_144                     137552
tg_topic_145                     137552
tg_topic_146                     137552
tg_topic_147                     137552
tg_topic_148                     137552
tg_topic_149                     137552
tg_topic_150                     137552
tg_topic_151                     137552
tg_topic_152                     137552
tg_topic_153                     137552
tg_topic_154                     137552
tg_topic_155                     137552
tg_topic_156                     137552
tg_topic_157                     137552
tg_topic_158                     137552
tg_topic_159                     137552
tg_topic_160                     137552
tg_topic_161                     137552
tg_topic_162                     137552
tg_topic_163                     137552
tg_topic_164                     137552
tg_topic_165                     137552
tg_topic_166                     137552
tg_topic_167                     137552
tg_topic_168                     137552
tg_topic_169                     137552
tg_topic_170                     137552
tg_topic_171                     137552
tg_topic_172                     137552
tg_topic_173                     137552
tg_topic_174                     137552
tg_topic_175                     137552
tg_topic_176                     137552
tg_topic_177                     137552
tg_topic_178                     137552
tg_topic_179                     137552
tg_topic_180                     137552
tg_topic_181                     137552
tg_topic_182                     137552
tg_topic_183                     137552
tg_topic_184                     137552
tg_topic_185                     137552
tg_topic_186                     137552
tg_topic_187                     137552
tg_topic_188                     137552
tg_topic_189                     137552
tg_topic_190                     137552
tg_topic_191                     137552
tg_topic_192                     137552
tg_topic_193                     137552
tg_topic_194                     137552
tg_topic_195                     137552
tg_topic_196                     137552
tg_topic_197                     137552
tg_topic_198                     137552
tg_topic_199                     137552
tg_topic_200                     137552
tg_topic_201                     137552
tg_topic_202                     137552
tg_topic_203                     137552
tg_topic_204                     137552
tg_topic_205                     137552
tg_topic_206                     137552
tg_topic_207                     137552
tg_topic_208                     137552
tg_topic_209                     137552
tg_topic_210                     137552
tg_topic_211                     137552
tg_topic_212                     137552
tg_topic_213                     137552
tg_topic_214                     137552
tg_topic_215                     137552
tg_topic_216                     137552
tg_topic_217                     137552
tg_topic_218                     137552
tg_topic_219                     137552
tg_topic_220                     137552
tg_topic_221                     137552
tg_topic_222                     137552
tg_topic_223                     137552
tg_topic_224                     137552
tg_topic_225                     137552
tg_topic_226                     137552
tg_topic_227                     137552
tg_topic_228                     137552
tg_topic_229                     137552
tg_topic_230                     137552
tg_topic_231                     137552
tg_topic_232                     137552
tg_topic_233                     137552
tg_topic_234                     137552
tg_topic_235                     137552
tg_topic_236                     137552
tg_topic_237                     137552
tg_topic_238                     137552
tg_topic_239                     137552
tg_topic_240                     137552
tg_topic_241                     137552
tg_topic_242                     137552
tg_topic_243                     137552
tg_topic_244                     137552
tg_topic_245                     137552
tg_topic_246                     137552
tg_topic_247                     137552
tg_topic_248                     137552
tg_topic_249                     137552
dtype: int64

In [40]:
df_final = df_final.fillna(0)

In [41]:
tg_cols = [c for c in df_final.columns if 'tg_topic_' in c]
df_tg_abs = df_final[tg_cols].abs()

df_final['tg_total_intensity'] = df_tg_abs.sum(axis=1)
df_final['tg_topic_std'] = df_tg_abs.std(axis=1)
df_final['tg_topic_max'] = df_tg_abs.max(axis=1)
df_final['tg_topic_entropy'] = -(df_tg_abs.div(df_tg_abs.sum(axis=1), axis=0) * np.log(df_tg_abs.div(df_tg_abs.sum(axis=1), axis=0) + 1e-9)).sum(axis=1)

C:\Users\Uw11\AppData\Local\Temp\ipykernel_29284\409095542.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_final['tg_total_intensity'] = df_tg_abs.sum(axis=1)
C:\Users\Uw11\AppData\Local\Temp\ipykernel_29284\409095542.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_final['tg_topic_std'] = df_tg_abs.std(axis=1)
C:\Users\Uw11\AppData\Local\Temp\ipykernel_29284\409095542.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_final['tg_topic_max'] = df_tg_abs.max(axis=1)
C:\Users\Uw11\AppData\Local\Temp\ipykernel_29284\409095542.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_final['tg_topic_entropy'] = -(df_tg_abs.div(df_tg_abs.sum(axis=1), axis=0) * np.log(df_tg_abs.div(df_tg_abs.sum(axis=1), axis=0) + 1e-9)).sum(axis=1)

In [42]:
df_final['tg_velocity_3h'] = (df_final.groupby('region_id')['tg_total_intensity'].diff(3).fillna(0))
df_final['tg_intensity_ema_6h'] = (df_final.groupby('region_id')['tg_total_intensity'].transform(lambda x: x.ewm(span=6).mean()))
df_final['tg_intensity_zscore'] = (df_final.groupby('region_id')['tg_total_intensity'].transform(lambda x: (x - x.rolling(24, min_periods=1).mean()) / (x.rolling(24, min_periods=1).std() + 1e-9)))

C:\Users\Uw11\AppData\Local\Temp\ipykernel_29284\3857173777.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_final['tg_velocity_3h'] = (df_final.groupby('region_id')['tg_total_intensity'].diff(3).fillna(0))
C:\Users\Uw11\AppData\Local\Temp\ipykernel_29284\3857173777.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_final['tg_intensity_ema_6h'] = (df_final.groupby('region_id')['tg_total_intensity'].transform(lambda x: x.ewm(span=6).mean()))
C:\Users\Uw11\AppData\Local\Temp\ipykernel_29284\3857173777.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_final['tg_intensity_zscore'] = (df_final.groupby('region_id')['tg_total_intensity'].transform(lambda x: (x - x.rolling(24, min_periods=1).mean()) / (x.rolling(24, min_periods=1).std() + 1e-9)))

In [43]:
df_final.sample(20)

,datetime_hour,region_id,day_tempmax,day_tempmin,day_temp,day_dew,day_humidity,day_precip,day_precipprob,day_precipcover,day_windgust,day_cloudcover,day_moonphase,hour_temp,hour_feelslike,hour_humidity,hour_dew,hour_precip,hour_precipprob,hour_snow,hour_snowdepth,hour_windgust,hour_windspeed,hour_winddir,hour_pressure,hour_cloudcover,hour_solarradiation,hour_solarenergy,hour_uvindex,hour_conditions_simple_Clear,hour_conditions_simple_Cloudy,hour_conditions_simple_Rain,hour_conditions_simple_Snow,day_of_week,hour,city_name,day_datetime,day_sunrise,day_sunset,region_key,alarm_active,alarm_minutes_in_hour,alarm_lag_1,alarm_lag_3,alarm_lag_6,alarm_lag_12,alarms_in_last_24h,is_weekend,is_night,total_active_alarms_lag1,neighbour_alarms,hours_since_last_alarm,isw_topic_0,isw_topic_1,isw_topic_2,isw_topic_3,isw_topic_4,isw_topic_5,isw_topic_6,isw_topic_7,isw_topic_8,isw_topic_9,isw_topic_10,isw_topic_11,isw_topic_12,isw_topic_13,isw_topic_14,isw_topic_15,isw_topic_16,isw_topic_17,isw_topic_18,isw_topic_19,isw_topic_20,isw_topic_21,isw_topic_22,isw_topic_23,isw_topic_24,isw_topic_25,isw_topic_26,isw_topic_27,isw_topic_28,isw_topic_29,isw_topic_30,isw_topic_31,isw_topic_32,isw_topic_33,isw_topic_34,isw_topic_35,isw_topic_36,isw_topic_37,isw_topic_38,isw_topic_39,isw_topic_40,isw_topic_41,isw_topic_42,isw_topic_43,isw_topic_44,isw_topic_45,isw_topic_46,isw_topic_47,isw_topic_48,isw_topic_49,isw_topic_50,isw_topic_51,isw_topic_52,isw_topic_53,isw_topic_54,isw_topic_55,isw_topic_56,isw_topic_57,isw_topic_58,isw_topic_59,isw_topic_60,isw_topic_61,isw_topic_62,isw_topic_63,isw_topic_64,isw_topic_65,isw_topic_66,isw_topic_67,isw_topic_68,isw_topic_69,isw_topic_70,isw_topic_71,isw_topic_72,isw_topic_73,isw_topic_74,isw_topic_75,isw_topic_76,isw_topic_77,isw_topic_78,isw_topic_79,isw_topic_80,isw_topic_81,isw_topic_82,isw_topic_83,isw_topic_84,isw_topic_85,isw_topic_86,isw_topic_87,isw_topic_88,isw_topic_89,isw_topic_90,isw_topic_91,isw_topic_92,isw_topic_93,isw_topic_94,isw_topic_95,isw_topic_96,isw_topic_97,isw_topic_98,isw_topic_99,isw_topic_100,isw_topic_101,isw_topic_102,isw_topic_103,isw_topic_104,isw_topic_105,isw_topic_106,isw_topic_107,isw_topic_108,isw_topic_109,isw_topic_110,isw_topic_111,isw_topic_112,isw_topic_113,isw_topic_114,isw_topic_115,isw_topic_116,isw_topic_117,isw_topic_118,isw_topic_119,isw_topic_120,isw_topic_121,isw_topic_122,isw_topic_123,isw_topic_124,isw_topic_125,isw_topic_126,isw_topic_127,isw_topic_128,isw_topic_129,isw_topic_130,isw_topic_131,isw_topic_132,isw_topic_133,isw_topic_134,isw_topic_135,isw_topic_136,isw_topic_137,isw_topic_138,isw_topic_139,isw_topic_140,isw_topic_141,isw_topic_142,isw_topic_143,isw_topic_144,isw_topic_145,isw_topic_146,isw_topic_147,isw_topic_148,isw_topic_149,isw_total_intensity,isw_topic_std,isw_topic_max,isw_topic_mean,isw_velocity_24h,isw_intensity_ema,isw_topic_entropy,tg_topic_0,tg_topic_1,tg_topic_2,tg_topic_3,tg_topic_4,tg_topic_5,tg_topic_6,tg_topic_7,tg_topic_8,tg_topic_9,tg_topic_10,tg_topic_11,tg_topic_12,tg_topic_13,tg_topic_14,tg_topic_15,tg_topic_16,tg_topic_17,tg_topic_18,tg_topic_19,tg_topic_20,tg_topic_21,tg_topic_22,tg_topic_23,tg_topic_24,tg_topic_25,tg_topic_26,tg_topic_27,tg_topic_28,tg_topic_29,tg_topic_30,tg_topic_31,tg_topic_32,tg_topic_33,tg_topic_34,tg_topic_35,tg_topic_36,tg_topic_37,tg_topic_38,tg_topic_39,tg_topic_40,tg_topic_41,tg_topic_42,tg_topic_43,tg_topic_44,tg_topic_45,tg_topic_46,tg_topic_47,tg_topic_48,tg_topic_49,tg_topic_50,tg_topic_51,tg_topic_52,tg_topic_53,tg_topic_54,tg_topic_55,tg_topic_56,tg_topic_57,tg_topic_58,tg_topic_59,tg_topic_60,tg_topic_61,tg_topic_62,tg_topic_63,tg_topic_64,tg_topic_65,tg_topic_66,tg_topic_67,tg_topic_68,tg_topic_69,tg_topic_70,tg_topic_71,tg_topic_72,tg_topic_73,tg_topic_74,tg_topic_75,tg_topic_76,tg_topic_77,tg_topic_78,tg_topic_79,tg_topic_80,tg_topic_81,tg_topic_82,tg_topic_83,tg_topic_84,tg_topic_85,tg_topic_86,tg_topic_87,tg_topic_88,tg_topic_89,tg_topic_90,tg_topic_91,tg_topic_92,tg_topic_93,tg_topic_94,tg_topic_95,tg_topic_96,tg_topic_97,tg_topic_98,tg_topic_99,tg_topic_100,tg_topic_101,tg_topic_102,tg_topic_103,tg_topic_104,tg_topic_105,tg_topic_106,tg_topic_107,tg_topic_108,tg_topic_109,tg_topic_110,tg_topic_111,tg_topic_112,tg_topic_113,tg_topic_114,tg_topic_115,tg_topic_116,tg_topic_117,tg_topic_118,tg_topic_119,tg_topic_120,tg_topic_121,tg_topic_122,tg_topic_123,tg_topic_124,tg_topic_125,tg_topic_126,tg_topic_127,tg_topic_128,tg_topic_129,tg_topic_130,tg_topic_131,tg_topic_132,tg_topic_133,tg_topic_134,tg_topic_135,tg_topic_136,tg_topic_137,tg_topic_138,tg_topic_139,tg_topic_140,tg_topic_141,tg_topic_142,tg_topic_143,tg_topic_144,tg_topic_145,tg_topic_146,tg_topic_147,tg_topic_148,tg_topic_149,tg_topic_150,tg_topic_151,tg_topic_152,tg_topic_153,tg_topic_154,tg_topic_155,tg_topic_156,tg_topic_157,tg_topic_158,tg_topic_159,tg_topic_160,tg_topic_161,tg_topic_162,tg_topic_163,tg_topic_164,tg_topic_165,tg_topic_166,tg_topic_167,tg_topic_168,tg_topic_169,tg_topic_170,tg_topic_171,tg_topic_172,tg_topic_173,tg_topic_174,tg_topic_175,tg_topic_176,tg_topic_177,tg_topic_178,tg_topic_179,tg_topic_180,tg_topic_181,tg_topic_182,tg_topic_183,tg_topic_184,tg_topic_185,tg_topic_186,tg_topic_187,tg_topic_188,tg_topic_189,tg_topic_190,tg_topic_191,tg_topic_192,tg_topic_193,tg_topic_194,tg_topic_195,tg_topic_196,tg_topic_197,tg_topic_198,tg_topic_199,tg_topic_200,tg_topic_201,tg_topic_202,tg_topic_203,tg_topic_204,tg_topic_205,tg_topic_206,tg_topic_207,tg_topic_208,tg_topic_209,tg_topic_210,tg_topic_211,tg_topic_212,tg_topic_213,tg_topic_214,tg_topic_215,tg_topic_216,tg_topic_217,tg_topic_218,tg_topic_219,tg_topic_220,tg_topic_221,tg_topic_222,tg_topic_223,tg_topic_224,tg_topic_225,tg_topic_226,tg_topic_227,tg_topic_228,tg_topic_229,tg_topic_230,tg_topic_231,tg_topic_232,tg_topic_233,tg_topic_234,tg_topic_235,tg_topic_236,tg_topic_237,tg_topic_238,tg_topic_239,tg_topic_240,tg_topic_241,tg_topic_242,tg_topic_243,tg_topic_244,tg_topic_245,tg_topic_246,tg_topic_247,tg_topic_248,tg_topic_249,tg_total_intensity,tg_topic_std,tg_topic_max,tg_topic_entropy,tg_velocity_3h,tg_intensity_ema_6h,tg_intensity_zscore
381420,2026-02-06 07:00:00,13,1.4,-0.5,0.4,-0.1,96.1,0.800,100.0,25.00,42.1,96.9,0.64,0.0,-5.1,96.43,-0.5,0.2,100.0,0.0,17.4,35.3,19.1,131.2,1000.0,100.0,0.0,0.0,0.0,False,False,False,True,4,7,Lviv,2026-02-06,07:49:42,17:27:02,Львівська,0,0.000000,0.0,0.0,0.0,0.0,3.0,0,0,12.0,0.0,13,0.788955,0.259868,0.143378,-0.039124,0.115617,0.014296,0.061277,0.052936,0.004134,-0.098755,0.070878,0.034278,0.152276,0.183833,0.085869,-0.097087,-0.013859,-0.017788,0.077662,0.029173,-0.020775,0.055931,0.082541,-0.052106,0.009727,0.009101,-0.035272,-0.021343,0.060476,0.015562,-0.034489,-0.023805,0.013694,-0.045838,-0.064249,-0.032347,0.007195,0.003908,0.003917,-0.003077,0.005971,0.019363,0.013170,0.052629,0.004859,0.015018,-0.016328,0.000163,-0.020447,-0.021635,0.017123,-0.008865,-0.015527,0.031741,0.009809,0.011429,0.003470,0.007543,-0.017447,-0.000070,0.013146,0.033947,0.001081,0.010870,-0.008757,-0.016948,0.004498,0.010606,-0.012516,0.011080,-0.009112,-0.014024,-0.001924,0.008308,-0.019824,-0.011199,-0.011440,0.007712,-0.003186,0.029830,0.007336,-0.011584,0.000249,0.020800,-0.003055,-0.010228,-0.003444,-0.006043,0.030238,-0.039967,0.039279,0.009667,0.013755,0.005227,-0.028208,0.018415,-0.005089,-0.016444,0.022308,0.025265,-0.001881,-0.001307,-0.023446,0.021253,0.002433,-0.026704,-0.000280,0.003829,0.001032,0.009155,0.017292,0.017569,0.012058,-0.021990,-0.010455,-0.009445,0.004214,-0.005764,0.020362,-0.028058,0.019520,-0.006645,-0.005128,0.010051,0.013514,0.016358,-0.000468,-0.008912,0.007223,0.002719,-0.002789,0.000389,0.002650,-0.007131,-0.009236,-0.006967,-0.007248,-0.003186,0.000458,-0.001860,-0.013510,0.008900,-0.018801,0.002035,-0.002543,0.007421,-0.004973,-0.011242,-0.000554,-0.022648,4.249223,0.071573,0.788955,0.028328,-0.764145,4.597980,4.013361,0.053837,-0.006822,0.225831,0.061305,0.064326,-0.068463,-0.015239,0.013552,-0.066863,-0.032600,-0.034346,-0.017632,-0.020049,0.087741,0.149105,-0.139089,0.054051,0.094246,0.097339,0.137427,-0.023646,0.008349,-0.035964,-0.026980,0.024953,0.048660,-0.026433,-0.053263,-0.015608,-0.052151,0.013098,-0.012107,-0.067156,-0.002904,-0.037685,-0.002153,0.012246,0.012870,-0.018638,0.000910,-0.003764,-0.043713,0.026215,0.013672,-0.035580,-0.021775,-0.008743,-0.022148,-0.017093,-0.011382,-0.008889,-0.005000,-0.004781,0.018530,-0.027831,0.010576,0.007918,0.014613,-0.060683,-0.034236,0.003254,-0.009055,-0.009567,-0.001642,-0.006353,0.001403,-0.006680,-0.014199,-0.007648,0.001006,0.025453,0.004685,0.040736,0.003988,0.007270,0.008510,-0.022759,0.029094,-0.059022,-0.019891,-0.013606,-0.068671,-0.018287,-0.028500,0.031968,0.011441,0.019337,0.023217,0.017866,0.006420,-0.005235,-0.031830,-0.012047,-0.006737,0.003991,-0.017612,0.013484,-0.007964,0.079672,0.036167,-0.029812,-0.030503,-0.006414,0.011684,-0.001230,0.022272,-0.021212,-0.009072,0.003388,0.010644,-0.025364,-0.008179,0.018743,0.014027,0.013993,-0.008686,-0.028285,-0.020974,0.001266,-0.011801,-0.018291,0.008515,-0.017048,-0.009316,0.006898,0.012826,0.028177,0.026010,0.004210,-0.007699,-0.010977,-0.004232,0.016133,0.000801,-0.029436,-0.005533,-0.023536,0.009665,-0.019900,0.002378,0.001521,0.011231,-0.002784,0.002718,0.018082,0.015023,0.017235,-0.016620,0.017258,-0.000102,0.002533,0.001025,0.002826,0.012830,0.007441,0.015535,-0.000906,-0.008008,0.021055,-0.004665,0.003276,0.022398,-0.004030,-0.014298,-0.033869,0.008287,-0.009611,-0.021320,-0.002644,-0.008851,0.009001,-0.002659,0.013736,0.006851,-0.005379,0.009257,0.005145,0.008667,0.007382,-0.004241,0.006266,0.027545,-0.019832,0.004406,0.021156,-0.018247,0.008829,-0.008361,0.004007,0.026178,-0.007592,-0.023982,0.011648,0.006212,0.008348,0.023115,0.016155,-0.003838,0.019161,0.013550,-0.007570,0.001864,-0.006890,-0.003432,-0.013198,0.023638,0.009885,-0.013160,0.002981,0.006622,0.015592,0.004864,0.000322,0.017417,0.022218,0.013153,0.007542,0.015404,-0.010968,0.007738,-0.001739,-0.000527,0.002676,-0.016798,0.011224,0.020031,-0.003736,-0.007118,0.000800,0.002511,0.014773,0.013842,0.011968,-0.031535,-0.008584,-0.018871,-0.021982,-0.010466,0.003234,0.004079,0.011763,0.010707,-0.017167,0.002819,-0.000220,0.014786,-0.013371,-0.002149,0.012818,-0.020908,4.804568,0.025227,0.225831,5.004939,-0.393472,5.148805,0.458011
357896,2023-06-02 01:00:00,13,23.7,9.7,17.0,9.9,65.3,0.700,100.0,12.50,39.6,44.1,0.44,12.0,12.0,89.34,10.3,0.0,0.0,0.0,0.0,11.9,7.2,220.1,1012.0,62.3,0.0,0.0,0.0,False,True,False,False,4,1,Lviv,2023-06-02,05:20:11,21:24:11,Львівська,0,0.000000,0.0,0.0,0.0,0.0,0.0,0,1,5.0,0.0,84,0.803940,-0.194828,-0.056027,-0.014410,-0.043265,0.048578,0.037674,0.041222,0.050862,-0.112013,0.040844,0.181037,-0.059578,-0.038595,0.002362,-0.024914,-0.011278,-0.042877,0.026663,0.018074,-0.050082,-0.009340,0.009051,-0.017963,-0.019765,-0.050394,-0.045417,0.018349,0.004420,-0.039332,0.029262,0.051096,-0.016041,0.021251,0.091710,0.000462,0.064768,0.031096,-0.016428,0.061987,0.013219,0.015762,0.001337,-0.014793,0.010611,0.006459,0.006191,-0.016345,0.007458,-0.003318,0.001898,0.013470,0.001524,0.053885,0.021049,-0.028916,0.020846,0.036818,-0.038671,0.004726,0.078083,0.041752,0.021193,0.011974,0.019278,-0.000738,0.005507,0.018877,0.017295,0.008362,-0.000021,0.008045,-0.010192,0.016631,-0.030079,-0.011457,-0.008932,0.011349,-0.022591,0.014885,-0.007230,0.021155,0.000014,-0.018316,-0.010266,-0.017495,-0.049609,-0.000580,0.020793,-0.011711,-0.031169,0.035696,0.012746,0.018762,0.037877,-0.016366,0.029088,0.046267,-0.032670,-0.001457,0.008782,0.003175,-0.029448,-0.004815,0.016282,-0.023416,0.020111,-0.019495,0.023878,-0.028878,0.031656,0.012015,-0.024947,-0.044943,-0.010398,-0.005100,0.040594,-0.002622,0.012275,0.020283,0.012314,-0.051568,0.006813,0.003711,-0.012918,0.010159,0.000998,-0.022734,0.056214,0.008207,0.001154,0.021318,-0.006007,0.021091,0.011564,0.002132,-0.000722,0.010803,-0.006454,0.007515,-0.004053,0.014875,0.020836,-0.017953,-0.008635,0.030630,-0.019827,0.012575,0.017770,0.025207,4.420930,0.069035,0.803940,0.029473,-1.024604,5.349586,4.221978,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-0.000000,-2.950780,3.050597,-1.349391
840978,2025-09-30 17:00:00,26,11.4,7.7,9.8,5.3,74.3,2.200,100.0,33.33,40.0,89.3,0.25,10.6,10.6,71.19,5.6,0.1,100.0,0.0,0.0,29.5,18.0,68.6,1026.0,99.2,63.4,0.2,1.0,False,False,True,False,1,17,Kyiv,2025-09-30,06:56:38,18:38:17,Київ,1,2.650000,0.0,0.0,0.0,0.0,2.0,0,0,8.0,1.0,21,0.740367,0.310084,0.066769,-0.141667,-0.031897,-0.023609,0.106650,-0.022451,-0.098198,-0.017158,0.064322,0.012381,0.245355,-0.218944,-0.058482,0.044796,0.083741,-0.039203,0.035157,-0.065757,-0.041697,0.027738,-0.034893,0.062371,-0.020396,0.023814,0.005674,0.006033,-0.023309,0.054171,0.004991,0.014485,0.073409,-0.022864,0.014760,0.013462,0.048035,-0.047459,0.017758,-0.039877,0.000622,0.035522,0.001540,-0.041676,-0.027041,-0.009030,-0.004734,0.049077,0.062357,0.044474,-0.039141,0.004645,-0.052649,-0.003632,-0.023417,0.012179,0.004865,-0.002199,0.014026,0.021181,0.015601,0.022507,-0.019711,0.053061,-0.017303,-0.013043,-0.021996,0.006910,-0.040269,0.004328,-0.008932,0.069932,0.018739,-0.004048,-0.023828,0.013684,-0.000401,-0.038687,-0.030143,-0.032595,0.010751,0.005288,-0.027848,-0.015942,0.005252,0.005074,-0.018263,-0.017644,0.006290,-0.013365,-0.010093,-0.017271,0.006573,0.040880,0.022003,0.003045,0.003972,-0.008911,-0.014895,0.020420,0.008445,-0.001329,0.021272,0.002499,0.000818,-0.020754,-0.001747,-0.027111,-0.002691,0.008987,-0.008155,0.025373,0.011515,-0.002040,-0.032344,0.019456,0.009877,-0.002036,-0.010833,0.005284,-0.001677,-0.005767,0.018445,-0.005815,-0.004578,0.007577,-0.010455,0.016084,0.007765,-0.022329,0.019260,-0.006464,-0.003346,0.031192,0.008999,-0.004938,-0.009522,-0.004223,0.010116,0.012387,-0.000736,0.006217,0.004714,0.006376,-0.014663,0.001498,-0.015853,0.009215,0.000589,0.000148,4.701205,0.070931,0.740367,0.031341,-0.301562,4.765812,4.111807,0.035232,-0.009056,0.115488,0.019535,0.029923,-0.003557,-0.019066,0.071554,-0.026645,-0.030056,-0.018641,0.024524,-0.018541,0.023011,-0.024631,-0.004349,0.012100,-0.055096,-0.014436,-0.026670,0.009488,-0.002957,-0.019977,0.014853,0.022873,0.000989,-0.045625,-0.044416,-0.012489,0.071798,-0.001955,-0.005559,-0.002664,-0.018043,0.017596,-0.001523,0.028859,-0.005397,0.005888,-0.007593,-0.014833,0.012071,0.012042,0.038914,-0.003756,-0.023529,0.005498,0.002083,-0.019058,0.002437,-0.014757,0.013145,0.014485,-0.006386,-0.018456,0.021401,0.005051,-0.014480,-0.013127,-0.006296,0.014072,0.000741,-0.041150,0.014837,-0.020847,0.026013,-0.018490,-0.011243,-0.024438,0.020307,-0.003426,0.019698,-0.011296,0.011920,0.050781,0.033326,-0.021091,0.024176,-0.015656,-0.007786,-0.000332,-0.027276,-0.001420,0.023490,-0.048877,-0.021348,-0.009059,0.005643,0.022878,0.034496,0.012530,-0.007248,-0.012243,0.000026,-0.011788,0.006860,0.011159,-0.021253,-0.018834,-0.012855,0.003635,0.013137,-0.029980,0.000587,-0.017773,0.035340,0.013722,-0.008272,0.003497,-0.005800,0.026912,0.018897,0.000468,-0.003591,-0.008768,-0.018246,-0.000133,-0.007078,0.007231,-0.016029,-0.005670,0.010397,0.023306,-0.004344,-0.018112,-0.020129,0.010141,0.019042,-0.008183,0.008503,-0.004898,-0.003369,0.018271,-0.020199,-0.003676,0.005730,0.012856,-0.004513,0.004782,-0.002289,-0.001443,0.007691,0.015459,-0.001550,0.007929,-0.001707,-0.015226,0.000311,0.017021,0.000928,-0.017248,0.005274,-0.015673,0.002701,0.008866,0.013888,0.002308,-0.010119,-0.002081,-0.019237,0.015924,-0.001578,-0.024411,0.018096,-0.002802,-0.012621,-0.019052,0.027192,-0.003844,-0.015831,0.025735,0.025343,0.000718,0.033205,0.014588,0.002797,0.000227,0.004004,-0.004553,0.002078,0.008291,0.008121,-0.001084,0.017686,0.013781,0.001089,0.013908,0.002057,0.000723,0.001289,-0.009047,0.005060,0.011388,0.008697,-0.002180,0.009285,0.023089,-0.003349,-0.005008,-0.009375,0.019789,-0.018905,-0.022005,-0.002649,-0.007764,0.006135,-0.002671,-0.005557,0.012365,0.004119,-0.030900,0.000386,0.000916,0.011566,0.005568,-0.005629,-0.015149,-0.003643,-0.013398,-0.025633,-0.002082,0.003206,0.000362,0.002252,-0.017584,-0.008464,-0.012982,0.007265,0.004378,-0.002183,0.000131,-0.013325,-0.016371,0.005997,-0.009082,-0.002740,-0.021412,-0.005009,-0.002493,0.007245,0.006006,0.001516,0.006086,-0.017584,0.007001,0.005768,0.014131,-0.002566,0.006129,-0.004016,3.338748,0.013263,0.115488,5.132908,0.574730,3.989308,-0.710338

# ТУТ БУДЕ EDA

## Weather, ISW, Telegram shift for further models trainings

In [44]:
df_to_train = df_final.copy()
df_to_train = df_to_train.sort_values(['region_id', 'datetime_hour'])

In [45]:
isw_cols = [c for c in df_to_train.columns if 'isw_' in c]
df_to_train[isw_cols] = df_to_train.groupby('region_id')[isw_cols].shift(24).fillna(0)

In [46]:
df_to_train.head()

,datetime_hour,region_id,day_tempmax,day_tempmin,day_temp,day_dew,day_humidity,day_precip,day_precipprob,day_precipcover,day_windgust,day_cloudcover,day_moonphase,hour_temp,hour_feelslike,hour_humidity,hour_dew,hour_precip,hour_precipprob,hour_snow,hour_snowdepth,hour_windgust,hour_windspeed,hour_winddir,hour_pressure,hour_cloudcover,hour_solarradiation,hour_solarenergy,hour_uvindex,hour_conditions_simple_Clear,hour_conditions_simple_Cloudy,hour_conditions_simple_Rain,hour_conditions_simple_Snow,day_of_week,hour,city_name,day_datetime,day_sunrise,day_sunset,region_key,alarm_active,alarm_minutes_in_hour,alarm_lag_1,alarm_lag_3,alarm_lag_6,alarm_lag_12,alarms_in_last_24h,is_weekend,is_night,total_active_alarms_lag1,neighbour_alarms,hours_since_last_alarm,isw_topic_0,isw_topic_1,isw_topic_2,isw_topic_3,isw_topic_4,isw_topic_5,isw_topic_6,isw_topic_7,isw_topic_8,isw_topic_9,isw_topic_10,isw_topic_11,isw_topic_12,isw_topic_13,isw_topic_14,isw_topic_15,isw_topic_16,isw_topic_17,isw_topic_18,isw_topic_19,isw_topic_20,isw_topic_21,isw_topic_22,isw_topic_23,isw_topic_24,isw_topic_25,isw_topic_26,isw_topic_27,isw_topic_28,isw_topic_29,isw_topic_30,isw_topic_31,isw_topic_32,isw_topic_33,isw_topic_34,isw_topic_35,isw_topic_36,isw_topic_37,isw_topic_38,isw_topic_39,isw_topic_40,isw_topic_41,isw_topic_42,isw_topic_43,isw_topic_44,isw_topic_45,isw_topic_46,isw_topic_47,isw_topic_48,isw_topic_49,isw_topic_50,isw_topic_51,isw_topic_52,isw_topic_53,isw_topic_54,isw_topic_55,isw_topic_56,isw_topic_57,isw_topic_58,isw_topic_59,isw_topic_60,isw_topic_61,isw_topic_62,isw_topic_63,isw_topic_64,isw_topic_65,isw_topic_66,isw_topic_67,isw_topic_68,isw_topic_69,isw_topic_70,isw_topic_71,isw_topic_72,isw_topic_73,isw_topic_74,isw_topic_75,isw_topic_76,isw_topic_77,isw_topic_78,isw_topic_79,isw_topic_80,isw_topic_81,isw_topic_82,isw_topic_83,isw_topic_84,isw_topic_85,isw_topic_86,isw_topic_87,isw_topic_88,isw_topic_89,isw_topic_90,isw_topic_91,isw_topic_92,isw_topic_93,isw_topic_94,isw_topic_95,isw_topic_96,isw_topic_97,isw_topic_98,isw_topic_99,isw_topic_100,isw_topic_101,isw_topic_102,isw_topic_103,isw_topic_104,isw_topic_105,isw_topic_106,isw_topic_107,isw_topic_108,isw_topic_109,isw_topic_110,isw_topic_111,isw_topic_112,isw_topic_113,isw_topic_114,isw_topic_115,isw_topic_116,isw_topic_117,isw_topic_118,isw_topic_119,isw_topic_120,isw_topic_121,isw_topic_122,isw_topic_123,isw_topic_124,isw_topic_125,isw_topic_126,isw_topic_127,isw_topic_128,isw_topic_129,isw_topic_130,isw_topic_131,isw_topic_132,isw_topic_133,isw_topic_134,isw_topic_135,isw_topic_136,isw_topic_137,isw_topic_138,isw_topic_139,isw_topic_140,isw_topic_141,isw_topic_142,isw_topic_143,isw_topic_144,isw_topic_145,isw_topic_146,isw_topic_147,isw_topic_148,isw_topic_149,isw_total_intensity,isw_topic_std,isw_topic_max,isw_topic_mean,isw_velocity_24h,isw_intensity_ema,isw_topic_entropy,tg_topic_0,tg_topic_1,tg_topic_2,tg_topic_3,tg_topic_4,tg_topic_5,tg_topic_6,tg_topic_7,tg_topic_8,tg_topic_9,tg_topic_10,tg_topic_11,tg_topic_12,tg_topic_13,tg_topic_14,tg_topic_15,tg_topic_16,tg_topic_17,tg_topic_18,tg_topic_19,tg_topic_20,tg_topic_21,tg_topic_22,tg_topic_23,tg_topic_24,tg_topic_25,tg_topic_26,tg_topic_27,tg_topic_28,tg_topic_29,tg_topic_30,tg_topic_31,tg_topic_32,tg_topic_33,tg_topic_34,tg_topic_35,tg_topic_36,tg_topic_37,tg_topic_38,tg_topic_39,tg_topic_40,tg_topic_41,tg_topic_42,tg_topic_43,tg_topic_44,tg_topic_45,tg_topic_46,tg_topic_47,tg_topic_48,tg_topic_49,tg_topic_50,tg_topic_51,tg_topic_52,tg_topic_53,tg_topic_54,tg_topic_55,tg_topic_56,tg_topic_57,tg_topic_58,tg_topic_59,tg_topic_60,tg_topic_61,tg_topic_62,tg_topic_63,tg_topic_64,tg_topic_65,tg_topic_66,tg_topic_67,tg_topic_68,tg_topic_69,tg_topic_70,tg_topic_71,tg_topic_72,tg_topic_73,tg_topic_74,tg_topic_75,tg_topic_76,tg_topic_77,tg_topic_78,tg_topic_79,tg_topic_80,tg_topic_81,tg_topic_82,tg_topic_83,tg_topic_84,tg_topic_85,tg_topic_86,tg_topic_87,tg_topic_88,tg_topic_89,tg_topic_90,tg_topic_91,tg_topic_92,tg_topic_93,tg_topic_94,tg_topic_95,tg_topic_96,tg_topic_97,tg_topic_98,tg_topic_99,tg_topic_100,tg_topic_101,tg_topic_102,tg_topic_103,tg_topic_104,tg_topic_105,tg_topic_106,tg_topic_107,tg_topic_108,tg_topic_109,tg_topic_110,tg_topic_111,tg_topic_112,tg_topic_113,tg_topic_114,tg_topic_115,tg_topic_116,tg_topic_117,tg_topic_118,tg_topic_119,tg_topic_120,tg_topic_121,tg_topic_122,tg_topic_123,tg_topic_124,tg_topic_125,tg_topic_126,tg_topic_127,tg_topic_128,tg_topic_129,tg_topic_130,tg_topic_131,tg_topic_132,tg_topic_133,tg_topic_134,tg_topic_135,tg_topic_136,tg_topic_137,tg_topic_138,tg_topic_139,tg_topic_140,tg_topic_141,tg_topic_142,tg_topic_143,tg_topic_144,tg_topic_145,tg_topic_146,tg_topic_147,tg_topic_148,tg_topic_149,tg_topic_150,tg_topic_151,tg_topic_152,tg_topic_153,tg_topic_154,tg_topic_155,tg_topic_156,tg_topic_157,tg_topic_158,tg_topic_159,tg_topic_160,tg_topic_161,tg_topic_162,tg_topic_163,tg_topic_164,tg_topic_165,tg_topic_166,tg_topic_167,tg_topic_168,tg_topic_169,tg_topic_170,tg_topic_171,tg_topic_172,tg_topic_173,tg_topic_174,tg_topic_175,tg_topic_176,tg_topic_177,tg_topic_178,tg_topic_179,tg_topic_180,tg_topic_181,tg_topic_182,tg_topic_183,tg_topic_184,tg_topic_185,tg_topic_186,tg_topic_187,tg_topic_188,tg_topic_189,tg_topic_190,tg_topic_191,tg_topic_192,tg_topic_193,tg_topic_194,tg_topic_195,tg_topic_196,tg_topic_197,tg_topic_198,tg_topic_199,tg_topic_200,tg_topic_201,tg_topic_202,tg_topic_203,tg_topic_204,tg_topic_205,tg_topic_206,tg_topic_207,tg_topic_208,tg_topic_209,tg_topic_210,tg_topic_211,tg_topic_212,tg_topic_213,tg_topic_214,tg_topic_215,tg_topic_216,tg_topic_217,tg_topic_218,tg_topic_219,tg_topic_220,tg_topic_221,tg_topic_222,tg_topic_223,tg_topic_224,tg_topic_225,tg_topic_226,tg_topic_227,tg_topic_228,tg_topic_229,tg_topic_230,tg_topic_231,tg_topic_232,tg_topic_233,tg_topic_234,tg_topic_235,tg_topic_236,tg_topic_237,tg_topic_238,tg_topic_239,tg_topic_240,tg_topic_241,tg_topic_242,tg_topic_243,tg_topic_244,tg_topic_245,tg_topic_246,tg_topic_247,tg_topic_248,tg_topic_249,tg_total_intensity,tg_topic_std,tg_topic_max,tg_topic_entropy,tg_velocity_3h,tg_intensity_ema_6h,tg_intensity_zscore
0,2022-02-24 00:00:00,2,5.0,0.7,2.8,-0.3,80.5,0.3,100.0,4.17,27.7,82.5,0.77,2.1,-0.5,91.76,0.9,0.0,0.0,0.0,0.0,16.6,8.6,279.6,1021.0,91.1,0.0,0.1,0.0,False,True,False,False,3,0,Vinnytsia,2022-02-24,06:58:49,17:40:52,Вінницька,0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-0.0,0.0,0.0,NaN
1,2022-02-24 00:00:00,2,5.0,0.7,2.8,-0.3,80.5,0.3,100.0,4.17,27.7,82.5,0.77,2.1,-0.5,91.76,0.9,0.0,0.0,0.0,0.0,16.6,8.6,279.6,1021.0,91.1,0.0,0.1,0.0,False,True,False,False,3,0,Vinnytsia,2022-02-24,06:58:49,17:40:52,Вінницька,0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-0.0,0.0,0.0,0.0
3,2022-02-24 01:00:00,2,5.0,0.7,2.8,-0.3,80.5,0.3,100.0,4.17,27.7,82.5,0.77,2.1,-0.4,89.80,0.6,0.0,0.0,0.0,0.0,16.6,8.3,289.2,1021.0,97.9,0.0,0.1,0.0,False,True,False,False,3,1,Vinnytsia,2022-02-24,06:58:49,17:40:52,Вінницька,0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0.0,0.0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-0.0,0.0,0.0,0.0
2,2022-02-24 01:00:00,2,5.0,0.7,2.8,-0.3,80.5,0.3,100.0,4.17,27.7,82.5,0.77,2.1,-0.4,89.80,0.6,0.0,0.0,0.0,0.0,16.6,8.3,289.2,1021.0,97.9,0.0,0.1,0.0,False,True,False,False,3,1,Vinnytsia,2022-02-24,06:58:49,17:40:52,Вінницька,0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0.0,0.0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-0.0,0.0,0.0,0.0
5,2022-02-24 02:00:00,2,5.0,0.7,2.8,-0.3,80.5,0.3,100.0,4.17,27.7,82.5,0.77,2.0,-0.3,90.44,0.6,0.0,0.0,0.0,0.0,27.7,7.6,287.6,1021.0,98.2,0.0,0.1,0.0,False,True,False,False,3,2,Vinnytsia,2022-02-24,06:58:49,17:40:52,Вінницька,0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0.0,0.0,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-0.0,0.0,0.0,0.0

In [47]:
tg_cols = [c for c in df_to_train.columns if 'tg_' in c]
df_to_train[tg_cols] = df_to_train.groupby('region_id')[tg_cols].shift(1).fillna(0)

In [48]:
df_to_train.head(5)

,datetime_hour,region_id,day_tempmax,day_tempmin,day_temp,day_dew,day_humidity,day_precip,day_precipprob,day_precipcover,day_windgust,day_cloudcover,day_moonphase,hour_temp,hour_feelslike,hour_humidity,hour_dew,hour_precip,hour_precipprob,hour_snow,hour_snowdepth,hour_windgust,hour_windspeed,hour_winddir,hour_pressure,hour_cloudcover,hour_solarradiation,hour_solarenergy,hour_uvindex,hour_conditions_simple_Clear,hour_conditions_simple_Cloudy,hour_conditions_simple_Rain,hour_conditions_simple_Snow,day_of_week,hour,city_name,day_datetime,day_sunrise,day_sunset,region_key,alarm_active,alarm_minutes_in_hour,alarm_lag_1,alarm_lag_3,alarm_lag_6,alarm_lag_12,alarms_in_last_24h,is_weekend,is_night,total_active_alarms_lag1,neighbour_alarms,hours_since_last_alarm,isw_topic_0,isw_topic_1,isw_topic_2,isw_topic_3,isw_topic_4,isw_topic_5,isw_topic_6,isw_topic_7,isw_topic_8,isw_topic_9,isw_topic_10,isw_topic_11,isw_topic_12,isw_topic_13,isw_topic_14,isw_topic_15,isw_topic_16,isw_topic_17,isw_topic_18,isw_topic_19,isw_topic_20,isw_topic_21,isw_topic_22,isw_topic_23,isw_topic_24,isw_topic_25,isw_topic_26,isw_topic_27,isw_topic_28,isw_topic_29,isw_topic_30,isw_topic_31,isw_topic_32,isw_topic_33,isw_topic_34,isw_topic_35,isw_topic_36,isw_topic_37,isw_topic_38,isw_topic_39,isw_topic_40,isw_topic_41,isw_topic_42,isw_topic_43,isw_topic_44,isw_topic_45,isw_topic_46,isw_topic_47,isw_topic_48,isw_topic_49,isw_topic_50,isw_topic_51,isw_topic_52,isw_topic_53,isw_topic_54,isw_topic_55,isw_topic_56,isw_topic_57,isw_topic_58,isw_topic_59,isw_topic_60,isw_topic_61,isw_topic_62,isw_topic_63,isw_topic_64,isw_topic_65,isw_topic_66,isw_topic_67,isw_topic_68,isw_topic_69,isw_topic_70,isw_topic_71,isw_topic_72,isw_topic_73,isw_topic_74,isw_topic_75,isw_topic_76,isw_topic_77,isw_topic_78,isw_topic_79,isw_topic_80,isw_topic_81,isw_topic_82,isw_topic_83,isw_topic_84,isw_topic_85,isw_topic_86,isw_topic_87,isw_topic_88,isw_topic_89,isw_topic_90,isw_topic_91,isw_topic_92,isw_topic_93,isw_topic_94,isw_topic_95,isw_topic_96,isw_topic_97,isw_topic_98,isw_topic_99,isw_topic_100,isw_topic_101,isw_topic_102,isw_topic_103,isw_topic_104,isw_topic_105,isw_topic_106,isw_topic_107,isw_topic_108,isw_topic_109,isw_topic_110,isw_topic_111,isw_topic_112,isw_topic_113,isw_topic_114,isw_topic_115,isw_topic_116,isw_topic_117,isw_topic_118,isw_topic_119,isw_topic_120,isw_topic_121,isw_topic_122,isw_topic_123,isw_topic_124,isw_topic_125,isw_topic_126,isw_topic_127,isw_topic_128,isw_topic_129,isw_topic_130,isw_topic_131,isw_topic_132,isw_topic_133,isw_topic_134,isw_topic_135,isw_topic_136,isw_topic_137,isw_topic_138,isw_topic_139,isw_topic_140,isw_topic_141,isw_topic_142,isw_topic_143,isw_topic_144,isw_topic_145,isw_topic_146,isw_topic_147,isw_topic_148,isw_topic_149,isw_total_intensity,isw_topic_std,isw_topic_max,isw_topic_mean,isw_velocity_24h,isw_intensity_ema,isw_topic_entropy,tg_topic_0,tg_topic_1,tg_topic_2,tg_topic_3,tg_topic_4,tg_topic_5,tg_topic_6,tg_topic_7,tg_topic_8,tg_topic_9,tg_topic_10,tg_topic_11,tg_topic_12,tg_topic_13,tg_topic_14,tg_topic_15,tg_topic_16,tg_topic_17,tg_topic_18,tg_topic_19,tg_topic_20,tg_topic_21,tg_topic_22,tg_topic_23,tg_topic_24,tg_topic_25,tg_topic_26,tg_topic_27,tg_topic_28,tg_topic_29,tg_topic_30,tg_topic_31,tg_topic_32,tg_topic_33,tg_topic_34,tg_topic_35,tg_topic_36,tg_topic_37,tg_topic_38,tg_topic_39,tg_topic_40,tg_topic_41,tg_topic_42,tg_topic_43,tg_topic_44,tg_topic_45,tg_topic_46,tg_topic_47,tg_topic_48,tg_topic_49,tg_topic_50,tg_topic_51,tg_topic_52,tg_topic_53,tg_topic_54,tg_topic_55,tg_topic_56,tg_topic_57,tg_topic_58,tg_topic_59,tg_topic_60,tg_topic_61,tg_topic_62,tg_topic_63,tg_topic_64,tg_topic_65,tg_topic_66,tg_topic_67,tg_topic_68,tg_topic_69,tg_topic_70,tg_topic_71,tg_topic_72,tg_topic_73,tg_topic_74,tg_topic_75,tg_topic_76,tg_topic_77,tg_topic_78,tg_topic_79,tg_topic_80,tg_topic_81,tg_topic_82,tg_topic_83,tg_topic_84,tg_topic_85,tg_topic_86,tg_topic_87,tg_topic_88,tg_topic_89,tg_topic_90,tg_topic_91,tg_topic_92,tg_topic_93,tg_topic_94,tg_topic_95,tg_topic_96,tg_topic_97,tg_topic_98,tg_topic_99,tg_topic_100,tg_topic_101,tg_topic_102,tg_topic_103,tg_topic_104,tg_topic_105,tg_topic_106,tg_topic_107,tg_topic_108,tg_topic_109,tg_topic_110,tg_topic_111,tg_topic_112,tg_topic_113,tg_topic_114,tg_topic_115,tg_topic_116,tg_topic_117,tg_topic_118,tg_topic_119,tg_topic_120,tg_topic_121,tg_topic_122,tg_topic_123,tg_topic_124,tg_topic_125,tg_topic_126,tg_topic_127,tg_topic_128,tg_topic_129,tg_topic_130,tg_topic_131,tg_topic_132,tg_topic_133,tg_topic_134,tg_topic_135,tg_topic_136,tg_topic_137,tg_topic_138,tg_topic_139,tg_topic_140,tg_topic_141,tg_topic_142,tg_topic_143,tg_topic_144,tg_topic_145,tg_topic_146,tg_topic_147,tg_topic_148,tg_topic_149,tg_topic_150,tg_topic_151,tg_topic_152,tg_topic_153,tg_topic_154,tg_topic_155,tg_topic_156,tg_topic_157,tg_topic_158,tg_topic_159,tg_topic_160,tg_topic_161,tg_topic_162,tg_topic_163,tg_topic_164,tg_topic_165,tg_topic_166,tg_topic_167,tg_topic_168,tg_topic_169,tg_topic_170,tg_topic_171,tg_topic_172,tg_topic_173,tg_topic_174,tg_topic_175,tg_topic_176,tg_topic_177,tg_topic_178,tg_topic_179,tg_topic_180,tg_topic_181,tg_topic_182,tg_topic_183,tg_topic_184,tg_topic_185,tg_topic_186,tg_topic_187,tg_topic_188,tg_topic_189,tg_topic_190,tg_topic_191,tg_topic_192,tg_topic_193,tg_topic_194,tg_topic_195,tg_topic_196,tg_topic_197,tg_topic_198,tg_topic_199,tg_topic_200,tg_topic_201,tg_topic_202,tg_topic_203,tg_topic_204,tg_topic_205,tg_topic_206,tg_topic_207,tg_topic_208,tg_topic_209,tg_topic_210,tg_topic_211,tg_topic_212,tg_topic_213,tg_topic_214,tg_topic_215,tg_topic_216,tg_topic_217,tg_topic_218,tg_topic_219,tg_topic_220,tg_topic_221,tg_topic_222,tg_topic_223,tg_topic_224,tg_topic_225,tg_topic_226,tg_topic_227,tg_topic_228,tg_topic_229,tg_topic_230,tg_topic_231,tg_topic_232,tg_topic_233,tg_topic_234,tg_topic_235,tg_topic_236,tg_topic_237,tg_topic_238,tg_topic_239,tg_topic_240,tg_topic_241,tg_topic_242,tg_topic_243,tg_topic_244,tg_topic_245,tg_topic_246,tg_topic_247,tg_topic_248,tg_topic_249,tg_total_intensity,tg_topic_std,tg_topic_max,tg_topic_entropy,tg_velocity_3h,tg_intensity_ema_6h,tg_intensity_zscore
0,2022-02-24 00:00:00,2,5.0,0.7,2.8,-0.3,80.5,0.3,100.0,4.17,27.7,82.5,0.77,2.1,-0.5,91.76,0.9,0.0,0.0,0.0,0.0,16.6,8.6,279.6,1021.0,91.1,0.0,0.1,0.0,False,True,False,False,3,0,Vinnytsia,2022-02-24,06:58:49,17:40:52,Вінницька,0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2022-02-24 00:00:00,2,5.0,0.7,2.8,-0.3,80.5,0.3,100.0,4.17,27.7,82.5,0.77,2.1,-0.5,91.76,0.9,0.0,0.0,0.0,0.0,16.6,8.6,279.6,1021.0,91.1,0.0,0.1,0.0,False,True,False,False,3,0,Vinnytsia,2022-02-24,06:58:49,17:40:52,Вінницька,0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-0.0,0.0,0.0,0.0
3,2022-02-24 01:00:00,2,5.0,0.7,2.8,-0.3,80.5,0.3,100.0,4.17,27.7,82.5,0.77,2.1,-0.4,89.80,0.6,0.0,0.0,0.0,0.0,16.6,8.3,289.2,1021.0,97.9,0.0,0.1,0.0,False,True,False,False,3,1,Vinnytsia,2022-02-24,06:58:49,17:40:52,Вінницька,0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0.0,0.0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-0.0,0.0,0.0,0.0
2,2022-02-24 01:00:00,2,5.0,0.7,2.8,-0.3,80.5,0.3,100.0,4.17,27.7,82.5,0.77,2.1,-0.4,89.80,0.6,0.0,0.0,0.0,0.0,16.6,8.3,289.2,1021.0,97.9,0.0,0.1,0.0,False,True,False,False,3,1,Vinnytsia,2022-02-24,06:58:49,17:40:52,Вінницька,0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0.0,0.0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-0.0,0.0,0.0,0.0
5,2022-02-24 02:00:00,2,5.0,0.7,2.8,-0.3,80.5,0.3,100.0,4.17,27.7,82.5,0.77,2.0,-0.3,90.44,0.6,0.0,0.0,0.0,0.0,27.7,7.6,287.6,1021.0,98.2,0.0,0.1,0.0,False,True,False,False,3,2,Vinnytsia,2022-02-24,06:58:49,17:40:52,Вінницька,0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0.0,0.0,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-0.0,0.0,0.0,0.0

In [49]:
hour_weather_cols = [c for c in df_to_train.columns if c.startswith('hour_')]
for col in hour_weather_cols:
    if df_to_train[col].dtype == bool:
        df_to_train[col] = df_to_train.groupby('region_id')[col].shift(1).fillna(False)
    else:
        df_to_train[col] = df_to_train.groupby('region_id')[col].shift(1).fillna(0)

In [50]:
day_weather_cols = [c for c in df_to_train.columns if (c.startswith('day_') and c not in ['day_datetime', 'day_sunrise', 'day_sunset', 'day_moonphase', 'day_of_week'])]
df_to_train[day_weather_cols] = df_to_train.groupby('region_id')[day_weather_cols].shift(24).fillna(0)

In [51]:
df_to_train.isna().sum()

datetime_hour          0
region_id              0
day_tempmax            0
day_tempmin            0
day_temp               0
                      ..
tg_topic_max           0
tg_topic_entropy       0
tg_velocity_3h         0
tg_intensity_ema_6h    0
tg_intensity_zscore    0
Length: 466, dtype: int64

In [52]:
df_to_train['alarm_minutes_in_hour'] = (df_to_train.groupby('region_id')['alarm_minutes_in_hour'].shift(1).fillna(0))

In [53]:
df_to_train.head()

,datetime_hour,region_id,day_tempmax,day_tempmin,day_temp,day_dew,day_humidity,day_precip,day_precipprob,day_precipcover,day_windgust,day_cloudcover,day_moonphase,hour_temp,hour_feelslike,hour_humidity,hour_dew,hour_precip,hour_precipprob,hour_snow,hour_snowdepth,hour_windgust,hour_windspeed,hour_winddir,hour_pressure,hour_cloudcover,hour_solarradiation,hour_solarenergy,hour_uvindex,hour_conditions_simple_Clear,hour_conditions_simple_Cloudy,hour_conditions_simple_Rain,hour_conditions_simple_Snow,day_of_week,hour,city_name,day_datetime,day_sunrise,day_sunset,region_key,alarm_active,alarm_minutes_in_hour,alarm_lag_1,alarm_lag_3,alarm_lag_6,alarm_lag_12,alarms_in_last_24h,is_weekend,is_night,total_active_alarms_lag1,neighbour_alarms,hours_since_last_alarm,isw_topic_0,isw_topic_1,isw_topic_2,isw_topic_3,isw_topic_4,isw_topic_5,isw_topic_6,isw_topic_7,isw_topic_8,isw_topic_9,isw_topic_10,isw_topic_11,isw_topic_12,isw_topic_13,isw_topic_14,isw_topic_15,isw_topic_16,isw_topic_17,isw_topic_18,isw_topic_19,isw_topic_20,isw_topic_21,isw_topic_22,isw_topic_23,isw_topic_24,isw_topic_25,isw_topic_26,isw_topic_27,isw_topic_28,isw_topic_29,isw_topic_30,isw_topic_31,isw_topic_32,isw_topic_33,isw_topic_34,isw_topic_35,isw_topic_36,isw_topic_37,isw_topic_38,isw_topic_39,isw_topic_40,isw_topic_41,isw_topic_42,isw_topic_43,isw_topic_44,isw_topic_45,isw_topic_46,isw_topic_47,isw_topic_48,isw_topic_49,isw_topic_50,isw_topic_51,isw_topic_52,isw_topic_53,isw_topic_54,isw_topic_55,isw_topic_56,isw_topic_57,isw_topic_58,isw_topic_59,isw_topic_60,isw_topic_61,isw_topic_62,isw_topic_63,isw_topic_64,isw_topic_65,isw_topic_66,isw_topic_67,isw_topic_68,isw_topic_69,isw_topic_70,isw_topic_71,isw_topic_72,isw_topic_73,isw_topic_74,isw_topic_75,isw_topic_76,isw_topic_77,isw_topic_78,isw_topic_79,isw_topic_80,isw_topic_81,isw_topic_82,isw_topic_83,isw_topic_84,isw_topic_85,isw_topic_86,isw_topic_87,isw_topic_88,isw_topic_89,isw_topic_90,isw_topic_91,isw_topic_92,isw_topic_93,isw_topic_94,isw_topic_95,isw_topic_96,isw_topic_97,isw_topic_98,isw_topic_99,isw_topic_100,isw_topic_101,isw_topic_102,isw_topic_103,isw_topic_104,isw_topic_105,isw_topic_106,isw_topic_107,isw_topic_108,isw_topic_109,isw_topic_110,isw_topic_111,isw_topic_112,isw_topic_113,isw_topic_114,isw_topic_115,isw_topic_116,isw_topic_117,isw_topic_118,isw_topic_119,isw_topic_120,isw_topic_121,isw_topic_122,isw_topic_123,isw_topic_124,isw_topic_125,isw_topic_126,isw_topic_127,isw_topic_128,isw_topic_129,isw_topic_130,isw_topic_131,isw_topic_132,isw_topic_133,isw_topic_134,isw_topic_135,isw_topic_136,isw_topic_137,isw_topic_138,isw_topic_139,isw_topic_140,isw_topic_141,isw_topic_142,isw_topic_143,isw_topic_144,isw_topic_145,isw_topic_146,isw_topic_147,isw_topic_148,isw_topic_149,isw_total_intensity,isw_topic_std,isw_topic_max,isw_topic_mean,isw_velocity_24h,isw_intensity_ema,isw_topic_entropy,tg_topic_0,tg_topic_1,tg_topic_2,tg_topic_3,tg_topic_4,tg_topic_5,tg_topic_6,tg_topic_7,tg_topic_8,tg_topic_9,tg_topic_10,tg_topic_11,tg_topic_12,tg_topic_13,tg_topic_14,tg_topic_15,tg_topic_16,tg_topic_17,tg_topic_18,tg_topic_19,tg_topic_20,tg_topic_21,tg_topic_22,tg_topic_23,tg_topic_24,tg_topic_25,tg_topic_26,tg_topic_27,tg_topic_28,tg_topic_29,tg_topic_30,tg_topic_31,tg_topic_32,tg_topic_33,tg_topic_34,tg_topic_35,tg_topic_36,tg_topic_37,tg_topic_38,tg_topic_39,tg_topic_40,tg_topic_41,tg_topic_42,tg_topic_43,tg_topic_44,tg_topic_45,tg_topic_46,tg_topic_47,tg_topic_48,tg_topic_49,tg_topic_50,tg_topic_51,tg_topic_52,tg_topic_53,tg_topic_54,tg_topic_55,tg_topic_56,tg_topic_57,tg_topic_58,tg_topic_59,tg_topic_60,tg_topic_61,tg_topic_62,tg_topic_63,tg_topic_64,tg_topic_65,tg_topic_66,tg_topic_67,tg_topic_68,tg_topic_69,tg_topic_70,tg_topic_71,tg_topic_72,tg_topic_73,tg_topic_74,tg_topic_75,tg_topic_76,tg_topic_77,tg_topic_78,tg_topic_79,tg_topic_80,tg_topic_81,tg_topic_82,tg_topic_83,tg_topic_84,tg_topic_85,tg_topic_86,tg_topic_87,tg_topic_88,tg_topic_89,tg_topic_90,tg_topic_91,tg_topic_92,tg_topic_93,tg_topic_94,tg_topic_95,tg_topic_96,tg_topic_97,tg_topic_98,tg_topic_99,tg_topic_100,tg_topic_101,tg_topic_102,tg_topic_103,tg_topic_104,tg_topic_105,tg_topic_106,tg_topic_107,tg_topic_108,tg_topic_109,tg_topic_110,tg_topic_111,tg_topic_112,tg_topic_113,tg_topic_114,tg_topic_115,tg_topic_116,tg_topic_117,tg_topic_118,tg_topic_119,tg_topic_120,tg_topic_121,tg_topic_122,tg_topic_123,tg_topic_124,tg_topic_125,tg_topic_126,tg_topic_127,tg_topic_128,tg_topic_129,tg_topic_130,tg_topic_131,tg_topic_132,tg_topic_133,tg_topic_134,tg_topic_135,tg_topic_136,tg_topic_137,tg_topic_138,tg_topic_139,tg_topic_140,tg_topic_141,tg_topic_142,tg_topic_143,tg_topic_144,tg_topic_145,tg_topic_146,tg_topic_147,tg_topic_148,tg_topic_149,tg_topic_150,tg_topic_151,tg_topic_152,tg_topic_153,tg_topic_154,tg_topic_155,tg_topic_156,tg_topic_157,tg_topic_158,tg_topic_159,tg_topic_160,tg_topic_161,tg_topic_162,tg_topic_163,tg_topic_164,tg_topic_165,tg_topic_166,tg_topic_167,tg_topic_168,tg_topic_169,tg_topic_170,tg_topic_171,tg_topic_172,tg_topic_173,tg_topic_174,tg_topic_175,tg_topic_176,tg_topic_177,tg_topic_178,tg_topic_179,tg_topic_180,tg_topic_181,tg_topic_182,tg_topic_183,tg_topic_184,tg_topic_185,tg_topic_186,tg_topic_187,tg_topic_188,tg_topic_189,tg_topic_190,tg_topic_191,tg_topic_192,tg_topic_193,tg_topic_194,tg_topic_195,tg_topic_196,tg_topic_197,tg_topic_198,tg_topic_199,tg_topic_200,tg_topic_201,tg_topic_202,tg_topic_203,tg_topic_204,tg_topic_205,tg_topic_206,tg_topic_207,tg_topic_208,tg_topic_209,tg_topic_210,tg_topic_211,tg_topic_212,tg_topic_213,tg_topic_214,tg_topic_215,tg_topic_216,tg_topic_217,tg_topic_218,tg_topic_219,tg_topic_220,tg_topic_221,tg_topic_222,tg_topic_223,tg_topic_224,tg_topic_225,tg_topic_226,tg_topic_227,tg_topic_228,tg_topic_229,tg_topic_230,tg_topic_231,tg_topic_232,tg_topic_233,tg_topic_234,tg_topic_235,tg_topic_236,tg_topic_237,tg_topic_238,tg_topic_239,tg_topic_240,tg_topic_241,tg_topic_242,tg_topic_243,tg_topic_244,tg_topic_245,tg_topic_246,tg_topic_247,tg_topic_248,tg_topic_249,tg_total_intensity,tg_topic_std,tg_topic_max,tg_topic_entropy,tg_velocity_3h,tg_intensity_ema_6h,tg_intensity_zscore
0,2022-02-24 00:00:00,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.77,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,False,False,False,False,3,0,Vinnytsia,2022-02-24,06:58:49,17:40:52,Вінницька,0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2022-02-24 00:00:00,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.77,2.1,-0.5,91.76,0.9,0.0,0.0,0.0,0.0,16.6,8.6,279.6,1021.0,91.1,0.0,0.1,0.0,False,True,False,False,3,0,Vinnytsia,2022-02-24,06:58:49,17:40:52,Вінницька,0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-0.0,0.0,0.0,0.0
3,2022-02-24 01:00:00,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.77,2.1,-0.5,91.76,0.9,0.0,0.0,0.0,0.0,16.6,8.6,279.6,1021.0,91.1,0.0,0.1,0.0,False,True,False,False,3,1,Vinnytsia,2022-02-24,06:58:49,17:40:52,Вінницька,0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0.0,0.0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-0.0,0.0,0.0,0.0
2,2022-02-24 01:00:00,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.77,2.1,-0.4,89.80,0.6,0.0,0.0,0.0,0.0,16.6,8.3,289.2,1021.0,97.9,0.0,0.1,0.0,False,True,False,False,3,1,Vinnytsia,2022-02-24,06:58:49,17:40:52,Вінницька,0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0.0,0.0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-0.0,0.0,0.0,0.0
5,2022-02-24 02:00:00,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.77,2.1,-0.4,89.80,0.6,0.0,0.0,0.0,0.0,16.6,8.3,289.2,1021.0,97.9,0.0,0.1,0.0,False,True,False,False,3,2,Vinnytsia,2022-02-24,06:58:49,17:40:52,Вінницька,0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0.0,0.0,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-0.0,0.0,0.0,0.0

In [55]:
print(f"Final dataset shape: {df_to_train.shape}")
print(f"Date range: {df_to_train['datetime_hour'].min()} → {df_to_train['datetime_hour'].max()}")
print(f"Regions: {df_to_train['region_id'].nunique()}")
print(f"Target balance: {df_to_train['alarm_active'].mean():.2%} positive")
print(f"NaN count: {df_to_train.isna().sum().sum()}")

Final dataset shape: (844993, 466)
Date range: 2022-02-24 00:00:00 → 2026-03-16 23:00:00
Regions: 24
Target balance: 20.64% positive
NaN count: 0

In [54]:
df_to_train.to_parquet("final_merged_dataset.parquet", index = False, engine = "pyarrow")