# Data merge and feature engineering

In [11]:
%pip install pyarrow

Requirement already satisfied: pyarrow in c:\users\uw11\appdata\local\programs\python\python313\lib\site-packages (23.0.1)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.3.1 -> 26.0.1
[notice] To update, run: C:\Users\Uw11\AppData\Local\Programs\Python\Python313\python.exe -m pip install --upgrade pip

In [12]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import string

import re
import nltk
from nltk.stem import WordNetLemmatizer
from nltk.corpus import stopwords
from sklearn.feature_extraction.text import TfidfVectorizer
from tqdm.notebook import tqdm
from tqdm import tqdm
import pymorphy3
from collections import Counter

import os
from pathlib import Path
import json

In [13]:
df_weather = pd.read_csv("../data/weather_processed.csv")
df_war_events = pd.read_csv("../data/war_events_processed.csv")
df_isw_matrix = pd.read_csv("../data/isw_processed_svd.csv")

In [69]:
df_weather.shape

(844417, 34)

In [33]:
df_war_events.tail()

,datetime_hour,region_id,region_key,alarm_minutes_in_hour,alarm_active
924659,2026-03-16 23:00:00,22,Хмельницька,0.000000,0
924660,2026-03-16 23:00:00,23,Черкаська,0.000000,0
924661,2026-03-16 23:00:00,24,Чернівецька,0.000000,0
924662,2026-03-16 23:00:00,25,Чернігівська,60.000000,1
924663,2026-03-16 23:00:00,26,Київ,17.216667,1

In [34]:
df_isw_matrix.tail()

,day_datetime,isw_topic_0,isw_topic_1,isw_topic_2,isw_topic_3,isw_topic_4,isw_topic_5,isw_topic_6,isw_topic_7,isw_topic_8,isw_topic_9,isw_topic_10,isw_topic_11,isw_topic_12,isw_topic_13,isw_topic_14,isw_topic_15,isw_topic_16,isw_topic_17,isw_topic_18,isw_topic_19,isw_topic_20,isw_topic_21,isw_topic_22,isw_topic_23,isw_topic_24,isw_topic_25,isw_topic_26,isw_topic_27,isw_topic_28,isw_topic_29,isw_topic_30,isw_topic_31,isw_topic_32,isw_topic_33,isw_topic_34,isw_topic_35,isw_topic_36,isw_topic_37,isw_topic_38,isw_topic_39,isw_topic_40,isw_topic_41,isw_topic_42,isw_topic_43,isw_topic_44,isw_topic_45,isw_topic_46,isw_topic_47,isw_topic_48,isw_topic_49,isw_topic_50,isw_topic_51,isw_topic_52,isw_topic_53,isw_topic_54,isw_topic_55,isw_topic_56,isw_topic_57,isw_topic_58,isw_topic_59,isw_topic_60,isw_topic_61,isw_topic_62,isw_topic_63,isw_topic_64,isw_topic_65,isw_topic_66,isw_topic_67,isw_topic_68,isw_topic_69,isw_topic_70,isw_topic_71,isw_topic_72,isw_topic_73,isw_topic_74,isw_topic_75,isw_topic_76,isw_topic_77,isw_topic_78,isw_topic_79,isw_topic_80,isw_topic_81,isw_topic_82,isw_topic_83,isw_topic_84,isw_topic_85,isw_topic_86,isw_topic_87,isw_topic_88,isw_topic_89,isw_topic_90,isw_topic_91,isw_topic_92,isw_topic_93,isw_topic_94,isw_topic_95,isw_topic_96,isw_topic_97,isw_topic_98,isw_topic_99,isw_topic_100,isw_topic_101,isw_topic_102,isw_topic_103,isw_topic_104,isw_topic_105,isw_topic_106,isw_topic_107,isw_topic_108,isw_topic_109,isw_topic_110,isw_topic_111,isw_topic_112,isw_topic_113,isw_topic_114,isw_topic_115,isw_topic_116,isw_topic_117,isw_topic_118,isw_topic_119,isw_topic_120,isw_topic_121,isw_topic_122,isw_topic_123,isw_topic_124,isw_topic_125,isw_topic_126,isw_topic_127,isw_topic_128,isw_topic_129,isw_topic_130,isw_topic_131,isw_topic_132,isw_topic_133,isw_topic_134,isw_topic_135,isw_topic_136,isw_topic_137,isw_topic_138,isw_topic_139,isw_topic_140,isw_topic_141,isw_topic_142,isw_topic_143,isw_topic_144,isw_topic_145,isw_topic_146,isw_topic_147,isw_topic_148,isw_topic_149
1450,2026-02-25,0.794526,0.278399,0.076717,-0.017046,0.130514,0.027260,-0.016811,0.133450,-0.089720,0.070505,-0.001508,0.029849,0.216945,-0.191913,0.039367,-0.081793,-0.028576,-0.015380,-0.037350,0.051588,0.033024,-0.001077,-0.032285,0.047213,0.026472,-0.034078,0.021475,-0.026009,0.012121,-0.001979,-0.006542,0.006595,0.003465,-0.026377,-0.018966,-0.012102,0.025430,0.011179,-0.000786,-0.006697,-0.002752,-0.014308,-0.027570,0.049736,-0.027920,-0.019518,-0.013256,-0.027406,0.001268,-0.024612,-0.021970,0.019933,0.004401,-0.070484,0.019840,-0.026222,-0.025895,-0.010331,-0.010895,0.025983,0.005557,-0.012166,-0.001707,0.026743,0.005436,-0.004494,0.005406,0.014124,-0.012217,-0.003826,0.004201,0.022561,-0.012841,0.007031,0.028518,0.016360,0.005313,-0.008868,-0.030852,-0.008994,0.020207,0.019844,0.009032,-0.003323,0.009689,0.006533,0.014164,-0.001182,0.023723,-0.045677,-0.010081,-0.001688,-0.036899,-0.017436,-0.003877,-0.015655,-0.010086,0.007955,0.020829,-0.018619,-0.003883,0.006805,-0.016228,0.003644,-0.008055,-0.002014,0.009305,0.016573,-0.006390,0.006504,-0.016563,-0.016203,-0.009431,-0.017402,0.011307,0.019392,0.036467,-0.002640,-0.006597,-0.020570,-0.027470,0.014320,0.009700,-0.004638,0.004841,0.004362,-0.000251,0.006573,-0.000536,0.006895,-0.002910,0.014939,-0.008813,0.014757,0.010208,0.016375,-0.001539,-0.000318,0.012399,-0.004559,-0.003080,-0.031158,-0.023643,0.000771,0.023196,0.010538,-0.017646,-0.024978,0.006705,0.014877
1451,2026-02-26,0.773297,0.254389,0.092057,-0.014604,0.112812,0.023849,-0.033479,0.117877,-0.090861,0.101495,-0.002202,0.049757,0.236446,-0.212107,0.065014,-0.087469,-0.021346,-0.007087,-0.051019,0.065923,-0.026802,-0.081054,0.017684,0.068441,0.035285,-0.012822,-0.033085,0.032736,0.058368,-0.021791,0.007965,-0.023264,-0.051200,-0.022218,-0.018411,0.018479,0.016588,0.042810,0.033631,-0.003018,0.031416,0.002899,0.028572,0.024571,-0.009660,-0.011085,0.016730,-0.023477,0.014187,0.014596,0.007376,0.003512,-0.019419,-0.039254,0.000321,-0.008324,-0.000609,0.035768,0.005611,0.024689,-0.025033,0.010551,-0.017602,-0.000136,0.029147,0.007510,0.025200,0.007497,-0.021728,0.006200,0.013765,0.010035,0.001681,-0.010644,0.043114,-0.002912,-0.018086,0.025465,-0.005174,0.025100,0.036609,-0.019776,0.010688,0.028595,0.016364,0.015607,-0.003120,0.017307,-0.035060,-0.022154,-0.018051,-0.003000,-0.021402,-0.009571,0.008718,0.005129,-0.008040,0.002516,-0.026669,0.001949,0.004743,-0.011800,-0.024480,-0.023320,-0.003796,-0.009007,-0.017904,-0.026674,-0.018766,0.035769,-0.013860,-0.013818,-0.000232,0.002075,0.021006,0.001301,0.027441,-0.004576,-0.014272,-0.009651,0.024408,-0.000447,-0.026677,0.011904,-0.009837,-0.020189,-0.006570,0.013163,-0.003054,0.001827,-0.018999,0.041701,0.012759,0.007803,0.004694,0.017596,0.021573,-0.034703,-0.003402,-0.011840,0.004163,0.014887,-0.013205,-0.020521,0.032542,-0.006460,0.015448,-0.005690,0.039212,-0.023284
1452,2026-02-27,0.767208,0.234002,0.103143,-0.042355,0.127271,0.029699,-0.034892,0.136108,-0.088537,0.099667,0.002902,0.035263,0.232336,-0.213571,0.097932,-0.108498,-0.043979,-0.021108,-0.081243,0.051927,-0.042521,-0.020504,-0.009283,0.116775,0.042463,-0.006809,-0.031898,-0.000175,0.042953,0.006410,0.011119,-0.001130,-0.025684,0.002698,-0.028808,0.013481,0.023630,0.030198,0.007385,-0.017087,-0.010424,-0.002109,0.010957,0.034349,-0.004790,0.004866,0.011436,-0.013798,0.010438,0.008862,-0.008323,-0.000104,-0.011001,-0.050343,0.025654,-0.012101,-0.006008,-0.013958,0.001366,-0.001211,0.027860,-0.009303,-0.009818,-0.001158,0.005358,-0.006622,0.006143,-0.000162,0.002885,0.014167,0.016078,-0.002715,-0.002086,-0.000489,0.036322,0.005840,-0.032095,0.016969,-0.021452,0.032977,0.025514,-0.001583,-0.021266,0.032611,0.001922,0.011470,-0.014972,0.008316,0.019652,-0.019713,-0.004137,-0.038651,-0.024679,0.010851,0.004742,-0.015255,-0.021407,0.019903,0.015430,0.002805,-0.017909,0.012397,-0.022470,-0.000060,-0.015609,0.005657,0.014859,-0.022110,-0.008530,0.010062,0.008348,-0.038417,0.031229,-0.012173,-0.006564,-0.007975,0.025447,0.012211,0.006266,0.009065,-0.010092,0.011431,0.013411,-0.004469,-0.006327,0.001288,-0.005563,-0.010272,-0.003699,0.019859,0.018272,0.013837,-0.029464,-0.004604,-0.000104,0.040395,0.010268,0.008611,-0.001799,-0.017073,0.000744,-0.023396,-0.021014,-0.019735,0.010289,0.007776,0.016875,0.010422,0.027153,-0.020628
1453,2026-02-28,0.715039,0.297372,0.093814,-0.038289,0.093199,0.040552,-0.039998,0.139265,-0.101488,0.108808,0.000700,0.072239,0.259687,-0.218456,0.094221,-0.123816,-0.078653,0.000671,-0.053714,0.064646,-0.008455,0.022445,0.019413,0.098310,0.062499,-0.044081,0.013405,-0.017511,0.050526,-0.034255,0.020261,0.005889,-0.087852,0.000400,-0.017509,0.039092,0.046045,0.038273,-0.020686,-0.006812,0.023759,-0.031305,0.013346,0.022084,-0.023304,-0.013261,0.014015,-0.010140,-0.000150,0.005831,-0.003117,-0.003679,-0.026364,-0.024542,-0.008506,-0.038928,-0.039922,-0.013738,0.026909,-0.005525,0.019318,-0.012756,-0.005082,0.037954,0.037824,-0.027325,0.029274,-0.027908,-0.005772,0.000255,0.008109,-0.029916,-0.018112,0.009354,0.010251,0.009010,-0.013248,0.014046,0.009828,0.035857,0.013298,-0.028462,-0.002755,0.045912,-0.000932,0.011370,0.042772,0.012033,0.018122,0.010848,-0.002105,-0.041907,0.075513,-0.007081,-0.017470,0.009671,-0.058093,0.003612,0.027410,-0.019759,0.038029,-0.006013,0.005976,-0.052463,-0.041349,0.028631,0.027669,-0.014342,-0.004460,-0.013544,0.036668,-0.021716,-0.001902,-0.003789,-0.000146,0.007417,0.023317,-0.004179,0.015168,-0.028888,-0.015205,-0.015067,-0.014256,0.012947,-0.023113,0.002457,0.010553,-0.017719,-0.011131,0.011102,0.000071,0.007232,0.005574,-0.013591,-0.007260,0.017491,-0.002228,0.016765,-0.034988,-0.011893,-0.023351,-0.018112,-0.014473,-0.000974,0.022032,0.000880,0.000159,-0.008722,0.015096,0.005460
1454,2026-03-01,0.708314,0.256758,0.114548,0.055863,0.089634,-0.068363,-0.103194,0.242655,0.002351,0.169372,-0.095588,-0.022101,0.024344,-0.001461,-0.040643,-0.076595,-0.082074,0.052514,-0.093886,0.020514,0.024782,-0.049448,0.025172,0.151741,0.043869,-0.026390,-0.026887,-0.010614,0.040992,-0.028492,-0.015131,-0.015092,-0.081331,-0.007005,0.005101,0.063775,0.015399,0.035141,0.001223,-0.050185,0.010160,0.007785,0.007790,0.011716,-0.037940,0.009536,0.039031,-0.003356,0.001701,0.009568,-0.006425,-0.007954,-0.055637,-0.006271,0.040976,-0.058804,-0.020485,-0.006845,-0.011040,-0.027138,0.022307,0.020306,-0.018795,0.052431,0.011207,-0.030009,0.042206,-0.051978,-0.019022,-0.013631,0.036606,-0.083654,-0.031017,0.013508,-0.001098,0.005599,0.024519,-0.022530,-0.007747,0.017907,0.037246,-0.049448,0.053199,0.041962,0.013377,0.022580,0.035295,0.011623,0.010105,-0.000453,-0.015768,-0.044444,0.067907,0.022418,-0.043248,-0.009985,-0.047332,-0.004319,0.037832,-0.001569,0.022845,-0.014701,-0.031970,-0.035740,0.008853,0.035253,-0.027612,0.010187,0.005981,-0.037596,0.038206,0.012857,0.022110,-0.018999,-0.029241,-0.020763,0.046269,0.013518,0.022606,-0.036986,0.006396,0.018948,-0.035638,0.005809,-0.017722,-0.034465,-0.015246,-0.017241,0.030346,-0.001263,-0.027071,0.009721,-0.003910,-0.017440,-0.008913,0.032905,-0.017430,0.005737,-0.018297,-0.028329,0.015226,-0.007925,0.008394,0.016786,0.018483,-0.021064,0.015966,0.006791,0.012315,0.039367

In [14]:
pd.set_option('display.max_columns', None)

In [15]:
df_weather['datetime_hour'] = pd.to_datetime(df_weather['datetime_hour'], errors="coerce")
df_war_events['datetime_hour'] = pd.to_datetime(df_war_events['datetime_hour'], errors="coerce")

In [16]:
df_final = pd.merge(
    df_weather, 
    df_war_events[['datetime_hour', 'region_id', 'alarm_active', 'alarm_minutes_in_hour']], 
    on=['datetime_hour', 'region_id'], 
    how='left'
)
df_final.sample(20)

,datetime_hour,region_id,day_dew,day_precip,day_precipprob,day_precipcover,day_moonphase,hour_temp,hour_feelslike,hour_humidity,hour_dew,hour_precip,hour_precipprob,hour_snow,hour_snowdepth,hour_windgust,hour_windspeed,hour_winddir,hour_pressure,hour_cloudcover,hour_solarradiation,hour_solarenergy,hour_uvindex,hour_conditions_simple_Clear,hour_conditions_simple_Cloudy,hour_conditions_simple_Rain,hour_conditions_simple_Snow,day_of_week,hour,city_name,day_datetime,day_sunrise,day_sunset,region_key,alarm_active,alarm_minutes_in_hour
651221,2025-04-01 00:00:00,7,4.8,0.006,100.0,4.17,0.10,9.6,8.7,70.59,4.5,0.0,0.0,0.0,0.0,25.6,7.3,10.0,1015.1,89.9,0.0,0.0,0.0,False,True,False,False,1,0,Uzhgorod,2025-04-01,07:08:33,20:01:49,Закарпатська,0,0.000000
315675,2023-08-26 03:00:00,5,11.6,0.000,0.0,0.00,0.34,13.5,13.5,90.05,11.9,0.0,0.0,0.0,0.0,10.4,4.7,34.4,1017.0,23.9,0.0,0.0,0.0,False,True,False,False,5,3,Donetsk,2023-08-26,05:37:50,19:22:39,Донецька,0,0.000000
726023,2025-08-14 12:00:00,14,9.9,0.000,0.0,0.00,0.68,29.7,29.2,38.80,14.2,0.0,0.0,0.0,0.0,23.0,14.4,50.0,1021.3,11.5,766.8,2.8,8.0,True,False,False,False,3,12,Mykolaiv,2025-08-14,05:48:06,20:04:35,Миколаївська,0,0.000000
7947,2022-03-09 19:00:00,5,-6.6,0.600,100.0,20.83,0.21,-1.0,-3.8,66.76,-6.4,0.0,0.0,0.1,1.7,15.1,7.6,33.4,1015.0,93.7,126.0,0.5,0.0,False,True,False,False,2,19,Donetsk,2022-03-09,05:54:28,17:24:58,Донецька,0,0.000000
423518,2024-02-29 08:00:00,17,4.6,0.000,0.0,0.00,0.66,5.8,5.8,85.90,3.7,0.0,0.0,0.0,0.0,13.7,3.6,181.0,1023.0,99.8,31.1,0.1,0.0,False,True,False,False,3,8,Rivne,2024-02-29,07:00:26,17:55:22,Рівненська,0,0.000000
74808,2022-07-03 22:00:00,2,13.2,2.500,100.0,20.83,0.13,22.0,22.0,67.89,15.8,0.0,0.0,0.0,0.0,9.4,4.7,67.9,1018.0,50.9,0.0,0.1,0.0,False,True,False,False,6,22,Vinnytsia,2022-07-03,05:06:17,21:14:20,Вінницька,0,0.000000
372197,2023-12-02 06:00:00,7,0.4,22.162,100.0,91.67,0.66,1.2,-2.5,92.66,0.2,0.0,0.0,0.0,3.8,14.8,12.9,360.0,1000.8,100.0,0.0,0.0,0.0,False,True,False,False,5,6,Uzhgorod,2023-12-02,08:02:50,16:37:14,Закарпатська,0,0.000000
18094,2022-03-27 10:00:00,25,-8.7,0.100,100.0,4.17,0.82,-0.3,-7.3,56.52,-7.9,0.0,0.0,0.0,0.0,64.4,33.5,332.0,1018.0,100.0,279.0,1.0,3.0,False,True,False,False,6,10,Chernihiv,2022-03-27,06:41:57,19:19:32,Чернігівська,0,0.000000
151586,2022-11-14 05:00:00,4,2.0,0.000,0.0,0.00,0.66,5.2,3.6,88.15,3.4,0.0,0.0,0.0,0.0,18.4,6.8,332.8,1025.0,9.4,0.0,0.1,0.0,True,False,False,False,0,5,Dnipro,2022-11-14,06:45:55,16:02:14,Дніпропетровська,0,0.000000
808069,2026-01-10 03:00:00,19,-12.9,0.000,0.0,0.00,0.75,-9.1,-15.2,85.39,-11.1,0.0,0.0,0.0,35.2,27.0,13.3,278.6,1001.0,81.9,0.0,0.0,0.0,False,True,False,False,5,3,Ternopil,2026-01-10,08:11:48,16:38:56,Тернопільська,0,0.000000
81540,2022-07-15 14:00:00,15,17.4,0.000,0.0,0.00,0.53,27.7,28.0,48.61,15.9,0.0,0.0,0.0,0.0,31.3,15.8,170.7,1013.0,0.0,872.0,3.1,9.0,True,False,False,False,4,14,Odesa,2022-07-15,05:19:06,20:46:30,Одеська,0,0.000000
622813,2025-02-09 09:00:00,16,-9.0,0.000,0.0,0.00,0.39,-7.9,-14.1,88.96,-9.4,0.0,0.0,0.0,1.4,28.4,14.4,58.9,1043.0,100.0,61.0,0.2,1.0,False,True,False,False,6,9,Poltava,2025-02-09,07:01:43,16:51:05,Полтавська,0,0.000000
687763,2025-06-06 04:00:00,26,17.1,1.300,100.0,8.33,0.34,20.1,20.1,75.81,15.7,0.0,0.0,0.0,0.0,24.1,13.3,207.7,1015.0,4.0,0.0,0.0,0.0,True,False,False,False,4,4,Kyiv,2025-06-06,04:48:34,21:05:18,Київ,1,52.850000
60113,2022-06-08 09:00:00,20,9.6,0.000,0.0,0.00,0.28,22.0,22.0,46.45,10.0,0.0,0.0,0.0,0.0,5.0,0.7,265.4,1015.0,56.3,545.0,2.0,5.0,False,True,False,False,2,9,Kharkiv,2022-06-08,04:27:07,20:41:34,Харківська,0,0.000000
652650,2025-04-03 14:00:00,10,5.1,1.000,100.0,4.17,0.17,14.7,14.7,51.47,4.8,0.0,0.0,0.0,0.0,37.1,14.8,16.6,1020.0,16.2,579.0,2.1,6.0,True,False,False,False,3,14,Kyiv,2025-04-03,06:29:40,19:33:42,Київська,1,23.900000
199772,2023-02-05 20:00:00,23,-4.3,1.700,100.0,50.00,0.50,-2.2,-7.1,84.87,-4.4,0.0,0.0,0.0,2.4,28.1,14.8,31.1,1026.0,94.9,0.0,0.0,0.0,False,True,False,False,6,20,Cherkasy,2023-02-05,07:18:26,16:53:44,Черкаська,0,0.000000
103285,2022-08-22 08:00:00,16,10.0,0.000,0.0,0.00,0.82,18.5,18.5,66.74,12.2,0.0,0.0,0.0,0.0,21.6,10.4,72.7,1013.0,48.3,221.0,0.8,2.0,False,True,False,False,0,8,Poltava,2022-08-22,05:42:25,19:46:05,Полтавська,0,0.000000
292444,2023-07-16 19:00:00,6,15.1,0.000,0.0,0.00,0.95,28.2,28.4,47.52,16.0,0.0,0.0,0.0,0.0,7.9,1.8,100.9,1016.0,39.1,225.3,0.8,2.0,False,True,False,False,6,19,Zhytomyr,2023-07-16,05:12:27,21:09:46,Житомирська,0,0.000000
427091,2024-03-06 13:00:00,14,-1.0,0.100,100.0,4.17,0.87,9.2,5.9,41.55,-3.2,0.0,0.0,0.0,0.0,42.5,24.5,34.7,1016.0,79.2,495.4,1.8,5.0,False,True,False,False,2,13,Mykolaiv,2024-03-06,06:21:57,17:45:20,Миколаївська,1,23.133333
75141,2022-07-04 11:00:00,24,16.3,0.000,0.0,0.00,0.16,26.6,26.6,60.03,18.2,0.0,0.0,0.0,0.0,12.7,5.8,13.0,1016.5,30.0,720.0,2.6,7.0,False,True,False,False,0,11,Chernivtsi,2022-07-04,05:21:25,21:19:40,Чернівецька,0,0.000000

In [17]:
df_final = df_final.sort_values(['region_id', 'datetime_hour'])
df_final.head()

,datetime_hour,region_id,day_dew,day_precip,day_precipprob,day_precipcover,day_moonphase,hour_temp,hour_feelslike,hour_humidity,hour_dew,hour_precip,hour_precipprob,hour_snow,hour_snowdepth,hour_windgust,hour_windspeed,hour_winddir,hour_pressure,hour_cloudcover,hour_solarradiation,hour_solarenergy,hour_uvindex,hour_conditions_simple_Clear,hour_conditions_simple_Cloudy,hour_conditions_simple_Rain,hour_conditions_simple_Snow,day_of_week,hour,city_name,day_datetime,day_sunrise,day_sunset,region_key,alarm_active,alarm_minutes_in_hour
0,2022-02-24 00:00:00,2,-0.3,0.3,100.0,4.17,0.77,2.1,-0.5,91.76,0.9,0.0,0.0,0.0,0.0,16.6,8.6,279.6,1021.0,91.1,0.0,0.1,0.0,False,True,False,False,3,0,Vinnytsia,2022-02-24,06:58:49,17:40:52,Вінницька,0,0.0
24,2022-02-24 01:00:00,2,-0.3,0.3,100.0,4.17,0.77,2.1,-0.4,89.80,0.6,0.0,0.0,0.0,0.0,16.6,8.3,289.2,1021.0,97.9,0.0,0.1,0.0,False,True,False,False,3,1,Vinnytsia,2022-02-24,06:58:49,17:40:52,Вінницька,0,0.0
48,2022-02-24 02:00:00,2,-0.3,0.3,100.0,4.17,0.77,2.0,-0.3,90.44,0.6,0.0,0.0,0.0,0.0,27.7,7.6,287.6,1021.0,98.2,0.0,0.1,0.0,False,True,False,False,3,2,Vinnytsia,2022-02-24,06:58:49,17:40:52,Вінницька,0,0.0
72,2022-02-24 03:00:00,2,-0.3,0.3,100.0,4.17,0.77,1.9,-0.3,91.75,0.7,0.0,0.0,0.0,0.0,15.1,7.2,288.9,1021.0,98.8,0.0,0.1,0.0,False,True,False,False,3,3,Vinnytsia,2022-02-24,06:58:49,17:40:52,Вінницька,0,0.0
96,2022-02-24 04:00:00,2,-0.3,0.3,100.0,4.17,0.77,1.8,-0.2,92.40,0.7,0.0,0.0,0.0,0.0,13.7,6.5,290.4,1021.0,100.0,0.0,0.1,0.0,False,True,False,False,3,4,Vinnytsia,2022-02-24,06:58:49,17:40:52,Вінницька,0,0.0

In [18]:
df_final.tail()

,datetime_hour,region_id,day_dew,day_precip,day_precipprob,day_precipcover,day_moonphase,hour_temp,hour_feelslike,hour_humidity,hour_dew,hour_precip,hour_precipprob,hour_snow,hour_snowdepth,hour_windgust,hour_windspeed,hour_winddir,hour_pressure,hour_cloudcover,hour_solarradiation,hour_solarenergy,hour_uvindex,hour_conditions_simple_Clear,hour_conditions_simple_Cloudy,hour_conditions_simple_Rain,hour_conditions_simple_Snow,day_of_week,hour,city_name,day_datetime,day_sunrise,day_sunset,region_key,alarm_active,alarm_minutes_in_hour
844324,2026-03-16 19:00:00,26,-1.8,0.0,0.0,0.0,0.92,7.5,7.5,55.25,-0.9,0.0,0.0,0.0,0.0,10.4,3.6,80.0,1019.0,44.3,5.5,0.1,0.0,False,True,False,False,0,19,Kyiv,2026-03-16,06:09:51,18:04:17,Київ,0,0.000000
844347,2026-03-16 20:00:00,26,-1.8,0.0,0.0,0.0,0.92,6.9,6.9,59.27,-0.5,0.0,0.0,0.0,0.0,9.4,4.0,79.6,1021.0,59.3,5.5,0.1,0.0,False,True,False,False,0,20,Kyiv,2026-03-16,06:09:51,18:04:17,Київ,0,0.000000
844370,2026-03-16 21:00:00,26,-1.8,0.0,0.0,0.0,0.92,6.1,6.1,62.62,-0.5,0.0,0.0,0.0,0.0,10.1,3.6,88.3,1021.0,39.4,5.5,0.1,0.0,False,True,False,False,0,21,Kyiv,2026-03-16,06:09:51,18:04:17,Київ,0,0.000000
844393,2026-03-16 22:00:00,26,-1.8,0.0,0.0,0.0,0.92,5.3,5.3,65.23,-0.7,0.0,0.0,0.0,0.0,9.0,2.5,85.6,1021.0,19.4,5.5,0.1,0.0,True,False,False,False,0,22,Kyiv,2026-03-16,06:09:51,18:04:17,Київ,1,25.650000
844416,2026-03-16 23:00:00,26,-1.8,0.0,0.0,0.0,0.92,4.7,4.7,66.06,-1.1,0.0,0.0,0.0,0.0,5.8,2.2,63.2,1021.0,10.6,5.5,0.1,0.0,True,False,False,False,0,23,Kyiv,2026-03-16,06:09:51,18:04:17,Київ,1,17.216667

In [19]:
df_final.info()

<class 'pandas.DataFrame'>
Index: 844417 entries, 0 to 844416
Data columns (total 36 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   datetime_hour                  844417 non-null  datetime64[us]
 1   region_id                      844417 non-null  int64
 2   day_dew                        844417 non-null  float64
 3   day_precip                     844417 non-null  float64
 4   day_precipprob                 844417 non-null  float64
 5   day_precipcover                844417 non-null  float64
 6   day_moonphase                  844417 non-null  float64
 7   hour_temp                      844417 non-null  float64
 8   hour_feelslike                 844417 non-null  float64
 9   hour_humidity                  844417 non-null  float64
 10  hour_dew                       844417 non-null  float64
 11  hour_precip                    844417 non-null  float64
 12  hour_precipprob                844417 non-null  float64
 13  hour_snow                      844417 non-null  float64
 14  hour_snowdepth                 844417 non-null  float64
 15  hour_windgust                  844417 non-null  float64
 16  hour_windspeed                 844417 non-null  float64
 17  hour_winddir                   844417 non-null  float64
 18  hour_pressure                  844417 non-null  float64
 19  hour_cloudcover                844417 non-null  float64
 20  hour_solarradiation            844417 non-null  float64
 21  hour_solarenergy               844417 non-null  float64
 22  hour_uvindex                   844417 non-null  float64
 23  hour_conditions_simple_Clear   844417 non-null  bool
 24  hour_conditions_simple_Cloudy  844417 non-null  bool
 25  hour_conditions_simple_Rain    844417 non-null  bool
 26  hour_conditions_simple_Snow    844417 non-null  bool
 27  day_of_week                    844417 non-null  int64
 28  hour                           844417 non-null  int64
 29  city_name                      844417 non-null  str
 30  day_datetime                   844417 non-null  str
 31  day_sunrise                    844417 non-null  str
 32  day_sunset                     844417 non-null  str
 33  region_key                     844417 non-null  str
 34  alarm_active                   844417 non-null  int64
 35  alarm_minutes_in_hour          844417 non-null  float64
dtypes: bool(4), datetime64[us](1), float64(22), int64(4), str(5)
memory usage: 260.1 MB

In [20]:
df_final = df_final.sort_values(["region_id", "datetime_hour"])

df_final["alarm_lag_1"] = df_final.groupby("region_id")["alarm_active"].shift(1)
df_final["alarm_lag_3"] = df_final.groupby("region_id")["alarm_active"].shift(3)
df_final["alarm_lag_6"] = df_final.groupby("region_id")["alarm_active"].shift(6)
df_final["alarm_lag_12"] = df_final.groupby("region_id")["alarm_active"].shift(12)
#df_final['alarm_minutes_lag1'] = (df_final.groupby('region_id')['alarm_minutes_in_hour'].shift(1).fillna(0))
#df_final['alarm_minutes_lag3'] = (df_final.groupby('region_id')['alarm_minutes_in_hour'].shift(3).fillna(0))

lag_cols = ["alarm_lag_1","alarm_lag_3","alarm_lag_6","alarm_lag_12"]
df_final[lag_cols] = df_final[lag_cols].fillna(0)

df_final['alarms_in_last_24h'] = (df_final.groupby('region_id')['alarm_active'].transform(lambda x: x.shift(1).rolling(24, min_periods=1).sum()))

df_final['is_weekend'] = df_final['day_of_week'].isin([5, 6]).astype(int)
df_final['is_night'] = ((df_final['hour'] >= 23) | (df_final['hour'] <= 6)).astype(int)

hourly_total = df_final.groupby('datetime_hour')['alarm_active'].sum().shift(1)
df_final['total_active_alarms_lag1'] = df_final['datetime_hour'].map(hourly_total)

df_final.sample(10)

,datetime_hour,region_id,day_dew,day_precip,day_precipprob,day_precipcover,day_moonphase,hour_temp,hour_feelslike,hour_humidity,hour_dew,hour_precip,hour_precipprob,hour_snow,hour_snowdepth,hour_windgust,hour_windspeed,hour_winddir,hour_pressure,hour_cloudcover,hour_solarradiation,hour_solarenergy,hour_uvindex,hour_conditions_simple_Clear,hour_conditions_simple_Cloudy,hour_conditions_simple_Rain,hour_conditions_simple_Snow,day_of_week,hour,city_name,day_datetime,day_sunrise,day_sunset,region_key,alarm_active,alarm_minutes_in_hour,alarm_lag_1,alarm_lag_3,alarm_lag_6,alarm_lag_12,alarms_in_last_24h,is_weekend,is_night,total_active_alarms_lag1
671434,2025-05-07 15:00:00,2,6.9,4.000,100.0,4.17,0.32,12.2,12.2,70.05,6.9,0.000,0.0,0.0,0.0,29.9,7.2,360.0,1013.6,87.5,184.2,0.7,2.0,False,True,False,False,2,15,Vinnytsia,2025-05-07,05:34:47,20:31:47,Вінницька,0,0.000000,0.0,1.0,1.0,0.0,8.0,0,0,2.0
552886,2024-10-10 23:00:00,25,11.1,0.000,0.0,0.00,0.25,13.8,13.8,85.44,11.4,0.000,0.0,0.0,0.0,25.2,14.4,140.7,1008.0,81.0,0.0,0.0,0.0,False,True,False,False,3,23,Chernihiv,2024-10-10,07:10:52,18:11:46,Чернігівська,0,0.000000,0.0,1.0,0.0,1.0,13.0,0,1,12.0
629071,2025-02-20 06:00:00,9,-8.7,0.100,100.0,4.17,0.75,-5.0,-9.1,86.52,-6.9,0.000,0.0,0.1,0.4,17.3,9.4,312.5,1035.0,92.0,0.0,0.0,0.0,False,True,False,False,3,6,Ivano-Frankivsk,2025-02-20,07:20:18,17:50:15,Івано-Франківська,1,19.583333,0.0,0.0,0.0,0.0,0.0,0,1,14.0
348413,2023-10-21 23:00:00,7,12.4,0.093,100.0,4.17,0.23,15.3,15.3,88.10,13.4,0.093,100.0,0.0,0.0,20.2,4.8,69.0,1008.2,82.3,0.0,0.0,0.0,False,False,True,False,5,23,Uzhgorod,2023-10-21,07:59:22,18:30:59,Закарпатська,0,0.000000,0.0,0.0,0.0,0.0,0.0,1,1,4.0
366569,2023-11-22 11:00:00,20,-11.2,0.300,100.0,4.17,0.32,-3.9,-7.1,62.66,-10.0,0.000,0.0,0.0,8.2,11.2,7.3,271.0,1020.8,90.0,274.6,1.0,3.0,False,True,False,False,2,11,Kharkiv,2023-11-22,06:58:16,15:43:29,Харківська,1,5.983333,0.0,1.0,0.0,1.0,12.0,0,0,0.0
73044,2022-06-30 20:00:00,15,18.1,17.000,100.0,4.17,0.03,25.5,25.5,70.31,19.7,0.000,0.0,0.0,0.0,14.4,5.4,108.1,1014.0,100.0,128.0,0.5,1.0,False,True,False,False,3,20,Odesa,2022-06-30,05:07:39,20:53:38,Одеська,0,0.000000,0.0,0.0,1.0,0.0,5.0,0,0,0.0
570757,2024-11-11 00:00:00,16,0.8,0.100,100.0,4.17,0.34,2.1,-0.6,87.87,0.3,0.000,0.0,0.0,0.0,16.2,9.0,34.5,1032.0,99.3,0.0,0.0,0.0,False,True,False,False,0,0,Poltava,2024-11-11,06:47:18,16:03:52,Полтавська,1,60.000000,1.0,1.0,0.0,0.0,14.0,0,1,7.0
70822,2022-06-26 23:00:00,25,13.5,0.000,0.0,0.00,0.89,21.7,21.7,64.01,14.6,0.000,0.0,0.0,0.0,12.6,6.8,57.5,1020.0,100.0,0.0,0.1,0.0,False,True,False,False,6,23,Chernihiv,2022-06-26,04:39:10,21:16:05,Чернігівська,0,0.000000,0.0,0.0,0.0,1.0,10.0,1,1,1.0
630722,2025-02-23 03:00:00,4,-11.9,0.000,0.0,0.00,0.85,-9.2,-15.6,78.81,-12.2,0.000,0.0,0.0,3.1,23.4,14.0,337.4,1035.0,13.6,0.0,0.0,0.0,True,False,False,False,6,3,Dnipro,2025-02-23,06:32:52,17:14:32,Дніпропетровська,1,36.466667,1.0,1.0,1.0,0.0,11.0,1,1,15.0
81565,2022-07-15 15:00:00,16,15.2,0.700,100.0,4.17,0.53,28.2,27.9,41.51,13.9,0.000,0.0,0.0,0.0,29.2,10.8,210.0,1011.5,80.0,733.0,2.6,7.0,False,True,False,False,4,15,Poltava,2022-07-15,04:51:01,20:43:57,Полтавська,0,0.000000,0.0,0.0,0.0,1.0,8.0,0,0,1.0

In [21]:
neighbouring_regions = {
    1: [21],
    2: [6, 10, 11, 15, 22, 23, 24],
    3: [13, 17],
    4: [5, 8, 11, 14, 16, 20, 21],
    5: [4, 8, 12, 20],
    6: [2, 10, 17, 22],
    7: [9, 13],
    8: [4, 5, 21],
    9: [7, 13, 19, 24],
    10: [2, 6, 16, 23, 25],
    11: [2, 4, 14, 15, 16, 23],
    12: [5, 20],
    13: [3, 7, 9, 17, 19],
    14: [4, 11, 15, 21],
    15: [2, 11, 14],
    16: [4, 10, 11, 18, 20, 23, 25],
    17: [3, 6, 13, 19, 22],
    18: [16, 20, 25],
    19: [9, 13, 17, 22, 24],
    20: [4, 5, 12, 16, 18],
    21: [1, 4, 8, 14],
    22: [2, 6, 17, 19, 24],
    23: [2, 10, 11, 16],
    24: [2, 9, 19, 22],
    25: [10, 16, 18], 
    26: [10]
}

alarms_matrix = df_final.pivot_table(
    index='datetime_hour',
    columns='region_id',
    values='alarm_active',
    fill_value=0
)

neighbour_alarm_matrix = pd.DataFrame(index=alarms_matrix.index)

for region, neighbours in neighbouring_regions.items():
    valid_neighbours = [n for n in neighbours if n in alarms_matrix.columns]
    
    if valid_neighbours:
        neighbour_alarm_matrix[region] = alarms_matrix[valid_neighbours].sum(axis=1)
    else:
        neighbour_alarm_matrix[region] = 0

neighbour_alarm_matrix = neighbour_alarm_matrix.shift(1)

neighbour_alarm_long = (neighbour_alarm_matrix.stack().reset_index())

neighbour_alarm_long.columns = ['datetime_hour','region_id','neighbour_alarms']

df_final = df_final.merge(neighbour_alarm_long,on=['datetime_hour', 'region_id'], how='left')

In [22]:
def hours_since_last_alarm(series):
    shifted = series.shift(1).fillna(0)
    result = []
    count = 0
    for val in shifted:
        if val == 1:
            count = 0
        else:
            count += 1
        result.append(count)
    return pd.Series(result, index=series.index)

df_final['hours_since_last_alarm'] = (df_final.groupby('region_id')['alarm_active'].transform(hours_since_last_alarm))

In [23]:
df_final.sample(20)

,datetime_hour,region_id,day_dew,day_precip,day_precipprob,day_precipcover,day_moonphase,hour_temp,hour_feelslike,hour_humidity,hour_dew,hour_precip,hour_precipprob,hour_snow,hour_snowdepth,hour_windgust,hour_windspeed,hour_winddir,hour_pressure,hour_cloudcover,hour_solarradiation,hour_solarenergy,hour_uvindex,hour_conditions_simple_Clear,hour_conditions_simple_Cloudy,hour_conditions_simple_Rain,hour_conditions_simple_Snow,day_of_week,hour,city_name,day_datetime,day_sunrise,day_sunset,region_key,alarm_active,alarm_minutes_in_hour,alarm_lag_1,alarm_lag_3,alarm_lag_6,alarm_lag_12,alarms_in_last_24h,is_weekend,is_night,total_active_alarms_lag1,neighbour_alarms,hours_since_last_alarm
235100,2025-08-31 23:00:00,8,14.8,0.000,0.0,0.00,0.25,24.7,24.7,65.90,17.9,0.00,0.0,0.0,0.0,24.8,15.5,176.8,1007.0,0.0,0.0,0.0,0.0,True,False,False,False,6,23,Zaporozhye,2025-08-31,05:56:15,19:22:13,Запорізька,1,60.000000,1.0,0.0,0.0,1.0,16.0,1,1,5.0,1.0,0
781620,2023-02-06 04:00:00,25,-6.5,0.100,100.0,4.17,0.52,-3.0,-8.3,82.87,-5.5,0.00,0.0,0.0,2.6,24.5,15.5,356.7,1032.0,97.0,0.0,0.0,0.0,False,True,False,False,0,4,Chernihiv,2023-02-06,07:25:43,16:52:48,Чернігівська,0,0.000000,0.0,0.0,0.0,0.0,2.0,0,1,0.0,0.0,18
7214,2022-12-21 15:00:00,2,-3.7,0.000,0.0,0.00,0.91,2.2,0.2,73.75,-2.0,0.00,0.0,0.0,0.1,14.4,6.8,175.5,1019.0,100.0,112.0,0.4,1.0,False,True,False,False,2,15,Vinnytsia,2022-12-21,07:58:38,16:09:54,Вінницька,1,8.183333,1.0,1.0,0.0,0.0,3.0,0,0,24.0,7.0,0
584594,2024-12-18 20:00:00,19,3.7,3.000,100.0,4.17,0.60,5.7,5.7,86.97,3.7,0.00,0.0,0.0,0.0,19.8,0.0,230.6,1019.4,80.0,0.0,0.0,0.0,False,True,False,False,2,20,Ternopil,2024-12-18,08:10:05,16:18:53,Тернопільська,0,0.000000,0.0,0.0,0.0,0.0,0.0,0,0,3.0,0.0,106
348979,2022-06-06 11:00:00,13,11.1,0.000,0.0,0.00,0.22,20.5,20.5,55.17,11.2,0.00,0.0,0.0,0.0,28.1,11.5,132.7,1020.0,61.3,697.0,2.5,7.0,False,True,False,False,0,11,Lviv,2022-06-06,05:17:38,21:28:03,Львівська,0,0.000000,0.0,0.0,0.0,0.0,0.0,0,0,8.0,0.0,27
362967,2024-01-10 08:00:00,13,-15.6,0.000,0.0,0.00,0.97,-17.1,-17.1,85.14,-19.0,0.00,0.0,0.0,6.0,15.8,0.0,279.1,1036.7,8.5,0.0,0.0,0.0,True,False,False,False,2,8,Lviv,2024-01-10,08:19:31,16:43:16,Львівська,1,50.216667,0.0,0.0,0.0,0.0,0.0,0,0,13.0,3.0,47
399736,2024-02-29 13:00:00,14,-0.5,0.000,0.0,0.00,0.66,9.5,9.5,56.18,1.2,0.00,0.0,0.0,0.0,16.6,4.0,132.9,1026.0,90.6,547.5,2.0,5.0,False,True,False,False,3,13,Mykolaiv,2024-02-29,06:33:16,17:36:35,Миколаївська,1,10.866667,0.0,0.0,0.0,0.0,4.0,0,0,4.0,1.0,13
610915,2023-11-29 16:00:00,20,0.2,17.000,100.0,8.33,0.57,1.0,-5.8,100.00,1.0,0.00,0.0,0.2,4.2,54.0,36.0,130.0,996.0,100.0,1.2,0.0,0.0,False,True,False,False,2,16,Kharkiv,2023-11-29,07:08:35,15:37:36,Харківська,0,0.000000,0.0,0.0,0.0,0.0,7.0,0,0,0.0,0.0,12
585510,2025-01-26 00:00:00,19,2.3,0.000,0.0,0.00,0.90,2.4,-0.7,100.00,2.4,0.00,0.0,0.0,0.0,21.6,10.8,154.1,1021.0,100.0,0.0,0.0,0.0,False,True,False,False,6,0,Ternopil,2025-01-26,07:57:39,17:03:28,Тернопільська,0,0.000000,0.0,0.0,0.0,0.0,0.0,1,1,12.0,0.0,41
561614,2022-05-06 06:00:00,19,-0.2,0.000,0.0,0.00,0.17,6.1,6.1,63.08,-0.4,0.00,0.0,0.0,0.0,13.3,0.0,138.4,1025.1,14.3,0.0,0.1,0.0,True,False,False,False,4,6,Ternopil,2022-05-06,05:47:13,20:42:22,Тернопільська,0,0.000000,0.0,0.0,0.0,0.0,4.0,0,1,4.0,0.0,8
91812,2024-07-04 23:00:00,4,12.4,0.000,0.0,0.00,0.94,23.6,23.6,70.39,17.9,0.00,0.0,0.0,0.0,11.2,6.1,296.8,1005.0,98.0,0.0,0.0,0.0,False,True,False,False,3,23,Dnipro,2024-07-04,04:44:39,20:44:00,Дніпропетровська,1,17.616667,0.0,0.0,0.0,1.0,10.0,0,1,5.0,3.0,6
163091,2025-07-26 06:00:00,6,17.7,0.500,100.0,8.33,0.05,18.2,18.2,95.09,17.4,0.00,0.0,0.0,0.0,5.8,0.0,639.0,1013.2,71.5,5.0,0.0,0.0,False,True,False,False,5,6,Zhytomyr,2025-07-26,05:25:37,20:57:26,Житомирська,0,0.000000,0.0,0.0,0.0,0.0,2.0,1,1,8.0,1.0,15
548040,2024-11-07 14:00:00,18,4.5,0.702,100.0,8.33,0.20,5.7,2.7,88.20,3.9,0.00,0.0,0.0,0.0,31.7,14.4,300.0,1029.0,100.0,73.4,0.3,1.0,False,True,False,False,3,14,Sumy,2024-11-07,06:43:41,16:04:43,Сумська,0,0.000000,0.0,1.0,1.0,1.0,20.0,0,0,1.0,0.0,1
498561,2023-04-07 18:00:00,17,3.0,0.994,100.0,4.17,0.54,7.4,5.4,70.48,2.4,0.00,0.0,0.0,0.2,25.6,10.8,140.0,1019.7,99.8,134.2,0.5,1.0,False,True,False,False,4,18,Rivne,2023-04-07,06:38:56,19:56:35,Рівненська,0,0.000000,0.0,0.0,0.0,0.0,0.0,0,0,1.0,0.0,75
838168,2025-06-29 15:00:00,26,13.6,0.100,100.0,4.17,0.13,20.2,20.2,71.57,14.9,0.00,0.0,0.0,0.0,42.5,10.8,280.0,1010.2,100.0,348.4,1.3,3.0,False,True,False,False,6,15,Kyiv,2025-06-29,04:49:35,21:13:10,Київ,0,0.000000,0.0,0.0,0.0,1.0,7.0,1,0,3.0,0.0,10
280578,2022-09-28 02:00:00,10,11.6,0.300,100.0,4.17,0.07,11.8,11.8,98.69,11.6,0.00,0.0,0.0,0.0,5.8,2.5,258.8,1003.0,99.3,0.0,0.1,0.0,False,True,False,False,2,2,Kyiv,2022-09-28,06:53:03,18:43:17,Київська,0,0.000000,0.0,0.0,0.0,0.0,0.0,0,1,3.0,0.0,35
831207,2024-09-12 13:00:00,26,16.3,17.000,100.0,8.33,0.31,27.4,27.8,50.11,16.1,0.00,0.0,0.0,0.0,47.5,16.9,114.3,1009.0,95.2,445.6,1.6,4.0,False,True,False,False,3,13,Kyiv,2024-09-12,06:29:21,19:17:52,Київ,0,0.000000,0.0,0.0,0.0,0.0,6.0,0,0,10.0,0.0,8
708238,2022-11-04 06:00:00,23,6.1,0.200,100.0,8.33,0.32,6.2,5.0,96.60,5.7,0.00,0.0,0.0,0.0,12.2,6.1,223.3,1017.0,96.8,0.0,0.1,0.0,False,True,False,False,4,6,Cherkasy,2022-11-04,06:44:34,16:25:22,Черкаська,0,0.000000,0.0,1.0,0.0,0.0,6.0,0,1,6.0,1.0,1
183174,2023-10-20 03:00:00,7,12.1,2.914,100.0,45.83,0.20,10.6,10.6,94.31,9.7,0.34,100.0,0.0,0.0,31.0,5.4,254.0,1000.3,96.0,0.0,0.0,0.0,False,False,True,False,4,3,Uzhgorod,2023-10-20,07:57:50,18:32:51,Закарпатська,0,0.000000,0.0,0.0,0.0,0.0,0.0,0,1,0.0,0.0,487
826223,2024-02-17 20:00:00,26,-0.4,0.100,100.0,4.17,0.26,1.2,-1.1,94.40,0.4,0.00,0.0,0.0,0.0,25.2,7.2,200.0,1025.1,100.0,0.0,0.0,0.0,False,True,False,False,5,20,Kyiv,2024-02-17,07:06:58,17:17:47,Київ,0,0.000000,0.0,0.0,0.0,0.0,1.0,1,0,9.0,0.0,7

In [24]:
df_isw_matrix.sample(10)

,date,isw_topic_0,isw_topic_1,isw_topic_2,isw_topic_3,isw_topic_4,isw_topic_5,isw_topic_6,isw_topic_7,isw_topic_8,isw_topic_9,isw_topic_10,isw_topic_11,isw_topic_12,isw_topic_13,isw_topic_14,isw_topic_15,isw_topic_16,isw_topic_17,isw_topic_18,isw_topic_19,isw_topic_20,isw_topic_21,isw_topic_22,isw_topic_23,isw_topic_24,isw_topic_25,isw_topic_26,isw_topic_27,isw_topic_28,isw_topic_29,isw_topic_30,isw_topic_31,isw_topic_32,isw_topic_33,isw_topic_34,isw_topic_35,isw_topic_36,isw_topic_37,isw_topic_38,isw_topic_39,isw_topic_40,isw_topic_41,isw_topic_42,isw_topic_43,isw_topic_44,isw_topic_45,isw_topic_46,isw_topic_47,isw_topic_48,isw_topic_49,isw_topic_50,isw_topic_51,isw_topic_52,isw_topic_53,isw_topic_54,isw_topic_55,isw_topic_56,isw_topic_57,isw_topic_58,isw_topic_59,isw_topic_60,isw_topic_61,isw_topic_62,isw_topic_63,isw_topic_64,isw_topic_65,isw_topic_66,isw_topic_67,isw_topic_68,isw_topic_69,isw_topic_70,isw_topic_71,isw_topic_72,isw_topic_73,isw_topic_74,isw_topic_75,isw_topic_76,isw_topic_77,isw_topic_78,isw_topic_79,isw_topic_80,isw_topic_81,isw_topic_82,isw_topic_83,isw_topic_84,isw_topic_85,isw_topic_86,isw_topic_87,isw_topic_88,isw_topic_89,isw_topic_90,isw_topic_91,isw_topic_92,isw_topic_93,isw_topic_94,isw_topic_95,isw_topic_96,isw_topic_97,isw_topic_98,isw_topic_99,isw_topic_100,isw_topic_101,isw_topic_102,isw_topic_103,isw_topic_104,isw_topic_105,isw_topic_106,isw_topic_107,isw_topic_108,isw_topic_109,isw_topic_110,isw_topic_111,isw_topic_112,isw_topic_113,isw_topic_114,isw_topic_115,isw_topic_116,isw_topic_117,isw_topic_118,isw_topic_119,isw_topic_120,isw_topic_121,isw_topic_122,isw_topic_123,isw_topic_124,isw_topic_125,isw_topic_126,isw_topic_127,isw_topic_128,isw_topic_129,isw_topic_130,isw_topic_131,isw_topic_132,isw_topic_133,isw_topic_134,isw_topic_135,isw_topic_136,isw_topic_137,isw_topic_138,isw_topic_139,isw_topic_140,isw_topic_141,isw_topic_142,isw_topic_143,isw_topic_144,isw_topic_145,isw_topic_146,isw_topic_147,isw_topic_148,isw_topic_149
575,2023-09-24,0.790050,-0.136141,0.019131,-0.165198,-0.047305,0.007962,-0.063581,0.080242,0.009071,-0.046490,0.039469,0.033295,0.155179,0.223246,0.068429,-0.085887,0.021341,0.041823,0.065208,0.003649,0.038336,0.027303,-0.109591,-0.014070,-0.016398,0.010042,-0.015257,-0.007831,-0.027794,0.013924,-0.010308,-0.006039,0.009242,0.015530,-0.038670,0.013095,-0.026556,0.017733,-0.008279,0.029124,-0.007625,0.030991,-0.011718,0.030206,-0.004725,-0.043405,-0.013866,-0.036863,-0.004565,0.017346,0.024288,0.001964,-0.017125,0.018723,0.009956,-0.008714,-0.006790,-0.053065,0.006683,-0.029119,0.004267,-0.005652,0.000528,0.020887,0.013472,0.051162,0.020877,-0.011886,0.025595,-0.061849,0.026148,0.016998,-0.035713,0.014083,-0.024563,0.037633,-0.020835,0.005519,-0.023980,-0.035664,0.015878,-0.014599,0.032550,0.022425,0.033564,0.011083,0.020455,-0.007790,-0.000020,-0.009774,-0.036911,-0.047396,-0.032949,-0.009683,-0.042611,0.002180,0.015359,-0.027570,0.005814,0.020127,-0.004326,-0.000988,0.007083,0.042176,-0.022176,0.007157,0.041651,0.018320,0.038056,0.032019,-0.021284,0.032283,-0.033734,-0.016115,0.036548,0.002318,-0.032854,0.012726,-0.029057,-0.004690,-0.002499,0.010582,-0.000463,0.001856,0.016354,0.009675,0.010523,-0.015037,0.003037,0.001309,-0.008433,0.003542,0.024139,0.005638,-0.000382,-0.005976,-0.000292,-0.017312,-0.024015,-0.001086,0.035635,-0.002946,-0.014342,0.003722,0.008628,-0.011754,0.027997,-0.019280,-0.018877,-0.011170
56,2022-04-20,0.620680,-0.172529,0.345004,0.226888,0.051193,-0.096838,-0.016490,-0.112101,-0.081036,-0.082493,0.196736,-0.049930,0.000839,0.007660,0.055525,-0.082571,0.096303,-0.062868,0.028160,-0.070337,-0.002592,0.040318,0.093280,0.050480,-0.031456,-0.033413,-0.077659,-0.067716,-0.016606,-0.017769,-0.006578,-0.036763,-0.035211,0.005416,-0.006933,-0.014326,-0.007392,0.007991,-0.021543,0.014500,0.033333,-0.037115,-0.000332,0.044117,0.015302,0.024073,0.009926,0.047272,-0.000352,-0.016995,-0.041864,0.018904,0.029753,-0.029651,-0.019270,0.060047,0.020191,-0.021356,-0.024396,0.026119,-0.017204,-0.022528,-0.038864,0.038473,-0.032296,0.016475,0.037625,0.027663,0.008884,-0.003504,-0.007961,-0.003823,0.033396,0.020117,0.006415,-0.047542,-0.000282,0.002377,0.014581,-0.007416,-0.029473,0.002782,0.075824,0.004621,-0.036727,0.021031,0.015054,0.067955,0.033180,-0.021801,0.026973,0.051186,-0.020833,0.008412,-0.037055,-0.032023,0.031433,-0.043129,0.016910,0.025561,0.024881,0.000919,0.010005,-0.030672,-0.012989,0.002962,0.023997,0.012811,0.000040,-0.011055,-0.027005,0.024049,-0.075744,-0.026131,0.031368,0.015917,0.028189,-0.040554,-0.020019,-0.012436,0.021315,-0.015359,-0.032148,0.013681,0.023198,-0.018907,-0.005867,0.036265,0.027203,0.057033,0.013406,-0.025267,0.039007,-0.022157,0.020450,-0.000649,-0.015423,0.028073,0.020540,-0.039855,0.065667,-0.025769,-0.007843,0.020129,-0.019266,-0.065971,0.044438,-0.042076,-0.026516,0.021177
1078,2025-02-15,0.790912,0.194049,-0.071717,0.088920,0.051529,0.022342,-0.009543,0.066373,0.001352,0.008846,-0.016224,0.051781,0.173806,-0.191716,0.161097,0.021189,-0.061923,0.012367,0.051225,-0.031071,0.071662,0.046577,0.011181,0.023036,0.008368,-0.008279,-0.002196,0.031694,-0.021427,-0.001932,0.042299,0.009545,0.070955,0.029774,0.072978,-0.051113,-0.004704,-0.079119,0.029024,-0.032731,0.034478,-0.032315,-0.015161,-0.050771,0.019889,-0.048852,-0.015737,-0.010548,-0.030595,-0.004216,0.008671,-0.011017,0.033851,0.031735,-0.054333,0.055230,-0.002165,-0.077993,-0.016649,0.006833,-0.024298,-0.037033,-0.018939,0.010606,0.020483,0.025938,-0.005233,-0.002751,0.008792,0.033861,0.006574,0.015781,0.022724,0.003184,0.022542,-0.000879,-0.041485,0.069197,-0.008541,-0.010301,0.021155,-0.006223,-0.034274,0.019033,0.001796,-0.009141,-0.018189,0.006716,-0.024515,0.000847,0.000852,0.046589,0.017788,0.040273,-0.018740,0.026721,0.016445,0.021763,0.017595,-0.009291,-0.011202,-0.001751,-0.049916,0.032313,-0.020241,0.003703,0.005740,0.015603,-0.003619,0.009270,0.007005,0.001901,0.040865,-0.027902,0.007915,0.010581,0.003809,-0.022675,-0.012633,0.004140,-0.032685,0.034702,0.018328,-0.010852,0.008358,-0.014392,0.001124,-0.004652,0.014188,-0.009446,0.046613,-0.007621,0.003635,0.010396,-0.001021,0.016484,0.010581,0.022176,-0.006094,0.006199,0.017079,-0.007936,0.015788,-0.009246,0.013595,0.006134,-0.022675,0.020008,0.001450,-0.014235
1279,2025-09-04,0.731015,0.364218,0.099905,-0.101814,-0.033776,0.025791,-0.058418,0.122845,-0.048009,-0.003198,0.054438,0.010268,0.153458,0.149134,-0.097135,-0.005981,0.043138,-0.006519,-0.003001,-0.029541,0.032882,0.088623,-0.004958,-0.086200,-0.005913,-0.013560,0.081923,-0.045165,-0.083739,-0.018094,-0.021269,-0.020609,0.004334,0.030367,0.005198,-0.024055,0.002680,-0.039669,-0.021033,-0.013556,0.015464,0.000858,-0.013025,-0.008300,-0.044901,-0.004467,-0.007001,-0.019462,-0.004335,0.028224,-0.001673,0.023927,-0.002375,-0.053829,0.046828,-0.017994,-0.011602,0.004477,0.020560,0.014083,0.058694,-0.004503,-0.019108,0.014213,-0.033178,-0.015409,0.012055,-0.013787,-0.005937,0.009772,0.004439,-0.012133,0.016024,0.023597,-0.012273,-0.012321,0.012651,0.009361,-0.025594,-0.033060,-0.005153,0.020250,-0.015936,-0.020659,-0.001949,-0.004914,-0.038105,-0.014970,0.019485,-0.005766,-0.021083,-0.004257,0.048100,-0.025737,0.073981,0.002488,0.033296,-0.043486,0.034479,-0.046442,-0.011715,-0.024260,-0.021062,0.014615,0.000395,-0.012415,-0.021227,-0.023935,-0.045596,0.017161,-0.002024,0.001365,0.030701,0.006068,0.063620,0.015276,0.009721,0.020693,-0.014826,-0.024511,0.001865,-0.016430,0.012656,0.025086,0.006732,-0.002690,0.022224,0.036655,0.032929,-0.024967,-0.010797,-0.003212,-0.081816,0.023560,-0.004765,-0.038405,-0.011371,-0.055234,0.001169,-0.012049,0.014404,-0.032870,-0.038117,0.015730,-0.010741,-0.016793,-0.035876,-0.012260,-0.024372,0.013317
326,2023-01-18,0.753861,-0.191788,-0.105814,-0.011380,0.268632,0.207352,-0.097987,-0.041178,0.005722,0.014024,0.022851,-0.000415,-0.067743,0.007186,-0.031807,0.133063,-0.013608,-0.072392,0.098358,-0.038261,-0.014183,-0.077555,-0.012574,0.005544,-0.022493,0.043736,0.052146,-0.089374,-0.059155,-0.002919,0.031252,0.064239,-0.015791,0.047654,-0.002486,-0.015907,0.034686,0.046328,-0.034956,-0.027434,0.033863,0.023130,-0.028458,-0.017590,0.078449,0.001919,0.025135,-0.036301,-0.022177,-0.044082,-0.002451,0.007480,-0.022508,0.000774,0.004599,-0.024955,0.018072,-0.020137,-0.011647,0.101846,-0.025327,-0.003088,-0.020889,0.002146,-0.016761,0.034490,0.031782,-0.011158,0.029256,-0.024558,-0.017413,-0.027429,-0.019098,-0.012431,0.004404,-0.015427,-0.042866,0.015414,0.003882,0.035415,-0.015191,-0.043637,0.050701,0.003904,-0.026440,-0.020422,0.039163,-0.020776,0.005334,-0.006784,0.030714,-0.022170,0.017198,-0.024787,0.010723,-0.012575,-0.018312,0.035255,0.002602,-0.000836,0.031629,0.007059,-0.018099,0.002231,0.024437,0.006997,0.017660,0.039503,0.007757,0.004117,-0.001945,0.004132,0.021901,-0.003983,-0.016778,0.002418,0.013407,0.002178,0.025463,0.016451,0.007612,0.007264,0.008108,-0.001520,0.020088,-0.028133,-0.031145,0.002234,0.003897,-0.008245,0.007406,0.013441,0.018471,-0.006946,0.014053,0.004951,-0.001219,0.014869,0.014653,0.017964,0.009520,-0.022894,0.009350,-0.000211,-0.023538,-0.015215,-0.015602,0.027734,0.004420,0.010753
701,2024-01-31,0.752020,-0.026881,-0.223853,0.113254,0.218223,0.175072,-0.117094,-0.120390,0.100354,-0.046378,-0.029812,-0.000030,0.013064,0.009547,-0.119531,-0.066968,0.052602,0.044728,0.028383,-0.038637,0.032335,0.059498,0.020613,-0.072694,-0.008897,0.028332,0.004172,-0.039486,0.013339,0.057904,0.014348,0.035531,-0.026716,-0.043583,0.040713,0.029727,-0.049554,0.016896,-0.018342,0.017066,-0.059996,-0.025141,0.035605,-0.009966,-0.017770,0.005269,-0.027740,-0.040881,0.050844,-0.008266,-0.016038,-0.062716,-0.005975,0.051505,0.025118,-0.005846,0.012225,0.026653,-0.048638,0.013156,0.000274,0.024670,0.014228,0.004532,-0.034011,-0.033715,0.000799,-0.019946,-0.025688,0.005347,-0.022869,0.034225,0.001152,0.026295,-0.000082,-0.015831,0.018756,0.017948,-0.001566,-0.002903,0.004904,-0.009864,0.006096,0.000887,0.016377,0.029852,-0.014788,0.002634,0.029153,-0.046340,-0.019506,-0.020749,0.022050,0.005176,-0.013289,0.033284,0.000936,-0.037960,0.001735,0.004151,-0.003958,0.016818,-0.033788,-0.001861,0.046610,0.004613,0.009688,-0.012802,-0.008285,-0.002817,0.031563,-0.029997,-0.002460,-0.000802,-0.008314,0.006711,0.012812,0.018358,0.010777,-0.011937,-0.002092,-0.015070,0.011127,0.015405,-0.027258,0.014886,-0.029667,0.001695,0.001887,0.016434,-0.015016,0.018437,0.005406,-0.012858,0.021076,0.021347,0.022514,-0.018582,-0.012634,0.012633,-0.002507,0.047260,-0.004403,-0.014986,0.015083,0.010377,-0.003914,0.007966,-0.036247,-0.014410
228,2022-10-09,0.497310,-0.157935,-0.109406,-0.018847,0.018440,-0.025347,-0.041832,0.029969,-0.104789,-0.018257,-0.020288,0.006512,-0.015154,-0.097324,-0.060601,0.213371,0.072769,-0.155236,0.120998,-0.036572,0.070536,0.015022,-0.144003,0.106631,0.142744,0.075425,-0.123078,0.063706,0.020322,0.018756,0.036680,0.065637,0.030908,0.071310,0.059582,0.001440,0.087003,0.134159,-0.110183,0.032337,0.007864,0.024529,0.055546,-0.070795,-0.103343,0.028984,0.000320,0.099041,-0.088427,-0.056901,0.006074,0.048789,-0.001485,-0.015020,0.002133,0.043090,-0.133531,-0.024216,0.006470,0.010660,-0.033559,-0.020785,-0.099931,-0.001095,-0.088788,-0.005785,-0.183825,-0.112116,-0.039931,0.075482,-0.026457,0.109154,-0.142874,0.120392,0.001453,-0.144828,0.138875,0.111282,0.000715,0.058797,0.032907,0.054869,-0.045733,-0.058774,0.009794,0.018688,0.057323,-0.050112,0.085083,0.066096,-0.040818,-0.023713,-0.040338,-0.022750,-0.021924,0.022322,-0.083088,0.013033,-0.053031,0.022901,0.050102,-0.002530,0.014357,0.006968,-0.018031,0.011868,-0.024952,-0.071517,-0.022205,0.013457,-0.003662,0.069123,-0.038522,-0.068533,0.026564,0.077623,-0.019258,0.031514,-0.027390,-0.026338,0.005791,0.013140,-0.017305,0.015422,0.036584,0.001619,-0.019695,-0.025982,-0.019080,-0.041152,-0.034626,-0.029523,-0.026554,-0.003813,-0.026240,0.067944,0.022250,-0.008923,0.021706,0.003390,-0.031410,-0.014775,0.001172,0.026616,-0.012282,-0.002694,0.000053,-0.033567,-0.023506,-0.039006
234,2022-10-15,0.784943,-0.214747,-0.023479,-0.174003,-0.003853,-0.095414,-0.142632,-0.058093,-0.094131,-0.071787,-0.071047,-0.014402,-0.027102,-0.058211,-0.021523,0.075233,-0.085836,0.032732,0.016191,0.070801,-0.038181,0.056328,0.037978,0.095070,-0.020727,0.030696,0.011442,0.040804,-0.036667,-0.012203,-0.005708,-0.011610,0.010216,-0.016060,-0.005211,0.013256,-0.018725,0.025058,0.019223,0.037974,0.009775,0.022543,-0.001346,-0.032278,-0.042696,0.014064,0.019158,0.001114,-0.028144,-0.043200,-0.010573,-0.024378,0.011754,-0.018181,-0.012499,-0.014536,0.003577,0.001258,0.005147,-0.014352,-0.003350,0.008260,0.031115,0.018423,0.003024,0.030065,0.001604,-0.054199,0.021237,0.006581,0.014223,0.000525,0.047882,0.006449,0.035828,-0.002278,0.007004,0.022533,0.009494,0.005164,-0.004522,-0.002697,-0.003012,0.012416,0.013934,-0.002278,0.021998,-0.020459,-0.022303,-0.010410,0.025274,0.014492,-0.006771,0.013481,0.028248,0.007756,-0.008623,-0.000300,0.040811,-0.004033,0.014803,0.049042,0.038555,-0.025173,-0.007668,0.028264,0.002704,0.010863,0.060768,-0.009666,0.011489,0.017108,0.034564,0.012357,0.054198,-0.025915,0.054619,-0.005109,0.005684,0.031893,0.014954,-0.026833,-0.009344,-0.010380,-0.032772,0.000489,0.019706,0.023845,0.017849,0.001376,-0.021725,-0.025583,-0.000393,0.054569,0.058867,-0.004708,0.025717,-0.013113,-0.014192,-0.019108,-0.010161,-0.021253,0.023840,0.006782,0.005417,-0.005132,-0.010716,-0.001578,-0.035738,-0.019645
964,2024-10-21,0.771546,0.102604,-0.061744,-0.100337,-0.078409,-0.192188,-0.193770,-0.145520,-0.033696,-0.152316,-0.139402,-0.006249,-0.080885,-0.059164,0.070442,0.011145,-0.035426,-0.043594,-0.052751,0.012265,0.016917,0.005747,0.095335,-0.055877,0.036115,-0.022475,0.011014,0.004284,-0.013789,0.108375,0.044403,0.097945,-0.051237,-0.004584,-0.045298,0.082646,0.020697,-0.040601,-0.010737,0.048900,-0.040070,0.036906,0.043455,-0.015741,0.005393,-0.023883,-0.033585,-0.007413,0.027328,0.008044,0.003996,-0.007929,-0.014418,-0.010951,-0.010777,-0.001228,0.042438,0.013082,-0.002687,0.035207,-0.012945,-0.000610,-0.071852,-0.011208,0.044863,0.025609,0.003628,0.002163,-0.050203,-0.010309,0.030935,0.014941,0.029478,0.015878,0.015942,-0.003861,0.012646,-0.031309,-0.035378,0.004992,-0.006270,0.006143,0.003614,0.006333,-0.045824,0.000231,0.011244,0.013945,-0.008092,-0.011826,0.017704,0.005189,-0.029006,-0.002979,0.021977,-0.012031,-0.028536,0.004852,0.036524,0.029261,0.017507,0.018483,0.010714,0.011067,0.030321,0.006588,-0.037552,-0.008002,-0.017004,-0.026796,-0.014326,0.037294,0.037289,-0.024273,-0.002509,0.017162,-0.012223,-0.005705,-0.025295,0.009723,0.011736,0.011049,0.030698,-0.036973,0.029407,0.010183,0.027003,0.002632,-0.021163,-0.000729,0.016661,0.005761,-0.014405,-0.006586,-0.006822,0.001951,-0.006457,0.001002,0.001377,-0.013205,0.009524,0.037800,-0.029303,-0.010634,0.026423,0.022896,0.009947,0.007932,-0.003936,0.000272
816,2024-05-25,0.851830,-0.001112,-0.011213,0.065816,-0.048097,-0.007053,0.014401,-0.051840,0.048826,-0.039747,-0.032842,0.038799,0.025811,-0.001836,0.024109,-0.001364,0.141687,0.061148,-0.020571,0.132438,0.030315,-0.043627,-0.055146,-0.014994,0.010074,-0.036006,-0.007490,-0.015006,-0.055606,0.001082,-0.020658,-0.034752,-0.047295,0.044568,-0.032272,0.093054,0.006343,-0.004578,0.009798,-0.044282,0.007785,0.049417,-0.049370,0.015683,0.022774,0.032635,0.003870,-0.022881,-0.032173,0.014663,0.023919,-0.044777,0.024615,0.049754,-0.006434,-0.008595,0.015117,0.055194,-0.056008,0.024339,-0.032394,0.011320,-0.000160,-0.057445,-0.046296,-0.003182,0.003647,-0.011906,-0.009876,-0.014889,0.011357,0.001591,-0.030540,0.047849,-0.024433,0.010215,0.007832,-0.013354,0.010693,-0.043542,0.008552,-0.004476,-0.027141,-0.012487,-0.001889,-0.004530,0.007738,-0.001330,-0.048138,-0.009334,0.033608,0.001085,0.019885,0.005397,-0.006524,0.003763,0.012148,-0.004630,-0.011327,0.009898,0.045142,0.033812,-0.002279,-0.035070,-0.007091,-0.020142,-0.041169,-0.024583,0.005355,-0.004532,0.001059,-0.024358,0.034210,0.011478,0.045571,-0.024156,-0.033612,-0.014831,0.003026,0.012559,-0.037288,0.029713,-0.012677,-0.007618,0.006916,0.003377,0.023804,0.025570,0.028638,0.021608,0.019745,-0.027596,0.010700,-0.007044,-0.008153,-0.005853,-0.013173,0.006679,0.007785,-0.019823,-0.010902,-0.019133,-0.031083,0.001741,0.016533,0.031837,0.011627,-0.035316,-0.011166,0.029368

In [30]:
df_isw_matrix.tail()

,day_datetime,isw_topic_0,isw_topic_1,isw_topic_2,isw_topic_3,isw_topic_4,isw_topic_5,isw_topic_6,isw_topic_7,isw_topic_8,isw_topic_9,isw_topic_10,isw_topic_11,isw_topic_12,isw_topic_13,isw_topic_14,isw_topic_15,isw_topic_16,isw_topic_17,isw_topic_18,isw_topic_19,isw_topic_20,isw_topic_21,isw_topic_22,isw_topic_23,isw_topic_24,isw_topic_25,isw_topic_26,isw_topic_27,isw_topic_28,isw_topic_29,isw_topic_30,isw_topic_31,isw_topic_32,isw_topic_33,isw_topic_34,isw_topic_35,isw_topic_36,isw_topic_37,isw_topic_38,isw_topic_39,isw_topic_40,isw_topic_41,isw_topic_42,isw_topic_43,isw_topic_44,isw_topic_45,isw_topic_46,isw_topic_47,isw_topic_48,isw_topic_49,isw_topic_50,isw_topic_51,isw_topic_52,isw_topic_53,isw_topic_54,isw_topic_55,isw_topic_56,isw_topic_57,isw_topic_58,isw_topic_59,isw_topic_60,isw_topic_61,isw_topic_62,isw_topic_63,isw_topic_64,isw_topic_65,isw_topic_66,isw_topic_67,isw_topic_68,isw_topic_69,isw_topic_70,isw_topic_71,isw_topic_72,isw_topic_73,isw_topic_74,isw_topic_75,isw_topic_76,isw_topic_77,isw_topic_78,isw_topic_79,isw_topic_80,isw_topic_81,isw_topic_82,isw_topic_83,isw_topic_84,isw_topic_85,isw_topic_86,isw_topic_87,isw_topic_88,isw_topic_89,isw_topic_90,isw_topic_91,isw_topic_92,isw_topic_93,isw_topic_94,isw_topic_95,isw_topic_96,isw_topic_97,isw_topic_98,isw_topic_99,isw_topic_100,isw_topic_101,isw_topic_102,isw_topic_103,isw_topic_104,isw_topic_105,isw_topic_106,isw_topic_107,isw_topic_108,isw_topic_109,isw_topic_110,isw_topic_111,isw_topic_112,isw_topic_113,isw_topic_114,isw_topic_115,isw_topic_116,isw_topic_117,isw_topic_118,isw_topic_119,isw_topic_120,isw_topic_121,isw_topic_122,isw_topic_123,isw_topic_124,isw_topic_125,isw_topic_126,isw_topic_127,isw_topic_128,isw_topic_129,isw_topic_130,isw_topic_131,isw_topic_132,isw_topic_133,isw_topic_134,isw_topic_135,isw_topic_136,isw_topic_137,isw_topic_138,isw_topic_139,isw_topic_140,isw_topic_141,isw_topic_142,isw_topic_143,isw_topic_144,isw_topic_145,isw_topic_146,isw_topic_147,isw_topic_148,isw_topic_149
1450,2026-02-25,0.794526,0.278399,0.076717,-0.017046,0.130514,0.027260,-0.016811,0.133450,-0.089720,0.070505,-0.001508,0.029849,0.216945,-0.191913,0.039367,-0.081793,-0.028576,-0.015380,-0.037350,0.051588,0.033024,-0.001077,-0.032285,0.047213,0.026472,-0.034078,0.021475,-0.026009,0.012121,-0.001979,-0.006542,0.006595,0.003465,-0.026377,-0.018966,-0.012102,0.025430,0.011179,-0.000786,-0.006697,-0.002752,-0.014308,-0.027570,0.049736,-0.027920,-0.019518,-0.013256,-0.027406,0.001268,-0.024612,-0.021970,0.019933,0.004401,-0.070484,0.019840,-0.026222,-0.025895,-0.010331,-0.010895,0.025983,0.005557,-0.012166,-0.001707,0.026743,0.005436,-0.004494,0.005406,0.014124,-0.012217,-0.003826,0.004201,0.022561,-0.012841,0.007031,0.028518,0.016360,0.005313,-0.008868,-0.030852,-0.008994,0.020207,0.019844,0.009032,-0.003323,0.009689,0.006533,0.014164,-0.001182,0.023723,-0.045677,-0.010081,-0.001688,-0.036899,-0.017436,-0.003877,-0.015655,-0.010086,0.007955,0.020829,-0.018619,-0.003883,0.006805,-0.016228,0.003644,-0.008055,-0.002014,0.009305,0.016573,-0.006390,0.006504,-0.016563,-0.016203,-0.009431,-0.017402,0.011307,0.019392,0.036467,-0.002640,-0.006597,-0.020570,-0.027470,0.014320,0.009700,-0.004638,0.004841,0.004362,-0.000251,0.006573,-0.000536,0.006895,-0.002910,0.014939,-0.008813,0.014757,0.010208,0.016375,-0.001539,-0.000318,0.012399,-0.004559,-0.003080,-0.031158,-0.023643,0.000771,0.023196,0.010538,-0.017646,-0.024978,0.006705,0.014877
1451,2026-02-26,0.773297,0.254389,0.092057,-0.014604,0.112812,0.023849,-0.033479,0.117877,-0.090861,0.101495,-0.002202,0.049757,0.236446,-0.212107,0.065014,-0.087469,-0.021346,-0.007087,-0.051019,0.065923,-0.026802,-0.081054,0.017684,0.068441,0.035285,-0.012822,-0.033085,0.032736,0.058368,-0.021791,0.007965,-0.023264,-0.051200,-0.022218,-0.018411,0.018479,0.016588,0.042810,0.033631,-0.003018,0.031416,0.002899,0.028572,0.024571,-0.009660,-0.011085,0.016730,-0.023477,0.014187,0.014596,0.007376,0.003512,-0.019419,-0.039254,0.000321,-0.008324,-0.000609,0.035768,0.005611,0.024689,-0.025033,0.010551,-0.017602,-0.000136,0.029147,0.007510,0.025200,0.007497,-0.021728,0.006200,0.013765,0.010035,0.001681,-0.010644,0.043114,-0.002912,-0.018086,0.025465,-0.005174,0.025100,0.036609,-0.019776,0.010688,0.028595,0.016364,0.015607,-0.003120,0.017307,-0.035060,-0.022154,-0.018051,-0.003000,-0.021402,-0.009571,0.008718,0.005129,-0.008040,0.002516,-0.026669,0.001949,0.004743,-0.011800,-0.024480,-0.023320,-0.003796,-0.009007,-0.017904,-0.026674,-0.018766,0.035769,-0.013860,-0.013818,-0.000232,0.002075,0.021006,0.001301,0.027441,-0.004576,-0.014272,-0.009651,0.024408,-0.000447,-0.026677,0.011904,-0.009837,-0.020189,-0.006570,0.013163,-0.003054,0.001827,-0.018999,0.041701,0.012759,0.007803,0.004694,0.017596,0.021573,-0.034703,-0.003402,-0.011840,0.004163,0.014887,-0.013205,-0.020521,0.032542,-0.006460,0.015448,-0.005690,0.039212,-0.023284
1452,2026-02-27,0.767208,0.234002,0.103143,-0.042355,0.127271,0.029699,-0.034892,0.136108,-0.088537,0.099667,0.002902,0.035263,0.232336,-0.213571,0.097932,-0.108498,-0.043979,-0.021108,-0.081243,0.051927,-0.042521,-0.020504,-0.009283,0.116775,0.042463,-0.006809,-0.031898,-0.000175,0.042953,0.006410,0.011119,-0.001130,-0.025684,0.002698,-0.028808,0.013481,0.023630,0.030198,0.007385,-0.017087,-0.010424,-0.002109,0.010957,0.034349,-0.004790,0.004866,0.011436,-0.013798,0.010438,0.008862,-0.008323,-0.000104,-0.011001,-0.050343,0.025654,-0.012101,-0.006008,-0.013958,0.001366,-0.001211,0.027860,-0.009303,-0.009818,-0.001158,0.005358,-0.006622,0.006143,-0.000162,0.002885,0.014167,0.016078,-0.002715,-0.002086,-0.000489,0.036322,0.005840,-0.032095,0.016969,-0.021452,0.032977,0.025514,-0.001583,-0.021266,0.032611,0.001922,0.011470,-0.014972,0.008316,0.019652,-0.019713,-0.004137,-0.038651,-0.024679,0.010851,0.004742,-0.015255,-0.021407,0.019903,0.015430,0.002805,-0.017909,0.012397,-0.022470,-0.000060,-0.015609,0.005657,0.014859,-0.022110,-0.008530,0.010062,0.008348,-0.038417,0.031229,-0.012173,-0.006564,-0.007975,0.025447,0.012211,0.006266,0.009065,-0.010092,0.011431,0.013411,-0.004469,-0.006327,0.001288,-0.005563,-0.010272,-0.003699,0.019859,0.018272,0.013837,-0.029464,-0.004604,-0.000104,0.040395,0.010268,0.008611,-0.001799,-0.017073,0.000744,-0.023396,-0.021014,-0.019735,0.010289,0.007776,0.016875,0.010422,0.027153,-0.020628
1453,2026-02-28,0.715039,0.297372,0.093814,-0.038289,0.093199,0.040552,-0.039998,0.139265,-0.101488,0.108808,0.000700,0.072239,0.259687,-0.218456,0.094221,-0.123816,-0.078653,0.000671,-0.053714,0.064646,-0.008455,0.022445,0.019413,0.098310,0.062499,-0.044081,0.013405,-0.017511,0.050526,-0.034255,0.020261,0.005889,-0.087852,0.000400,-0.017509,0.039092,0.046045,0.038273,-0.020686,-0.006812,0.023759,-0.031305,0.013346,0.022084,-0.023304,-0.013261,0.014015,-0.010140,-0.000150,0.005831,-0.003117,-0.003679,-0.026364,-0.024542,-0.008506,-0.038928,-0.039922,-0.013738,0.026909,-0.005525,0.019318,-0.012756,-0.005082,0.037954,0.037824,-0.027325,0.029274,-0.027908,-0.005772,0.000255,0.008109,-0.029916,-0.018112,0.009354,0.010251,0.009010,-0.013248,0.014046,0.009828,0.035857,0.013298,-0.028462,-0.002755,0.045912,-0.000932,0.011370,0.042772,0.012033,0.018122,0.010848,-0.002105,-0.041907,0.075513,-0.007081,-0.017470,0.009671,-0.058093,0.003612,0.027410,-0.019759,0.038029,-0.006013,0.005976,-0.052463,-0.041349,0.028631,0.027669,-0.014342,-0.004460,-0.013544,0.036668,-0.021716,-0.001902,-0.003789,-0.000146,0.007417,0.023317,-0.004179,0.015168,-0.028888,-0.015205,-0.015067,-0.014256,0.012947,-0.023113,0.002457,0.010553,-0.017719,-0.011131,0.011102,0.000071,0.007232,0.005574,-0.013591,-0.007260,0.017491,-0.002228,0.016765,-0.034988,-0.011893,-0.023351,-0.018112,-0.014473,-0.000974,0.022032,0.000880,0.000159,-0.008722,0.015096,0.005460
1454,2026-03-01,0.708314,0.256758,0.114548,0.055863,0.089634,-0.068363,-0.103194,0.242655,0.002351,0.169372,-0.095588,-0.022101,0.024344,-0.001461,-0.040643,-0.076595,-0.082074,0.052514,-0.093886,0.020514,0.024782,-0.049448,0.025172,0.151741,0.043869,-0.026390,-0.026887,-0.010614,0.040992,-0.028492,-0.015131,-0.015092,-0.081331,-0.007005,0.005101,0.063775,0.015399,0.035141,0.001223,-0.050185,0.010160,0.007785,0.007790,0.011716,-0.037940,0.009536,0.039031,-0.003356,0.001701,0.009568,-0.006425,-0.007954,-0.055637,-0.006271,0.040976,-0.058804,-0.020485,-0.006845,-0.011040,-0.027138,0.022307,0.020306,-0.018795,0.052431,0.011207,-0.030009,0.042206,-0.051978,-0.019022,-0.013631,0.036606,-0.083654,-0.031017,0.013508,-0.001098,0.005599,0.024519,-0.022530,-0.007747,0.017907,0.037246,-0.049448,0.053199,0.041962,0.013377,0.022580,0.035295,0.011623,0.010105,-0.000453,-0.015768,-0.044444,0.067907,0.022418,-0.043248,-0.009985,-0.047332,-0.004319,0.037832,-0.001569,0.022845,-0.014701,-0.031970,-0.035740,0.008853,0.035253,-0.027612,0.010187,0.005981,-0.037596,0.038206,0.012857,0.022110,-0.018999,-0.029241,-0.020763,0.046269,0.013518,0.022606,-0.036986,0.006396,0.018948,-0.035638,0.005809,-0.017722,-0.034465,-0.015246,-0.017241,0.030346,-0.001263,-0.027071,0.009721,-0.003910,-0.017440,-0.008913,0.032905,-0.017430,0.005737,-0.018297,-0.028329,0.015226,-0.007925,0.008394,0.016786,0.018483,-0.021064,0.015966,0.006791,0.012315,0.039367

In [25]:
#df_isw_matrix["date"] = pd.to_datetime(df_isw_matrix["date"]) + pd.Timedelta(days=1)    ТУТ ЗСУВ ІСВ НА + 1 ДЕНЬ
df_isw_matrix = df_isw_matrix.rename(columns={'date': 'day_datetime'})

In [26]:
df_final['day_datetime'] = pd.to_datetime(df_final['day_datetime']).dt.date
df_isw_matrix['day_datetime'] = pd.to_datetime(df_isw_matrix['day_datetime']).dt.date
df_isw_matrix.fillna(0, inplace=True)
df_isw_matrix.isna().sum()

day_datetime     0
isw_topic_0      0
isw_topic_1      0
isw_topic_2      0
isw_topic_3      0
                ..
isw_topic_145    0
isw_topic_146    0
isw_topic_147    0
isw_topic_148    0
isw_topic_149    0
Length: 151, dtype: int64

In [27]:
df_final = df_final.merge(df_isw_matrix, on="day_datetime", how="left")

In [28]:
df_final.head(10)

,datetime_hour,region_id,day_dew,day_precip,day_precipprob,day_precipcover,day_moonphase,hour_temp,hour_feelslike,hour_humidity,hour_dew,hour_precip,hour_precipprob,hour_snow,hour_snowdepth,hour_windgust,hour_windspeed,hour_winddir,hour_pressure,hour_cloudcover,hour_solarradiation,hour_solarenergy,hour_uvindex,hour_conditions_simple_Clear,hour_conditions_simple_Cloudy,hour_conditions_simple_Rain,hour_conditions_simple_Snow,day_of_week,hour,city_name,day_datetime,day_sunrise,day_sunset,region_key,alarm_active,alarm_minutes_in_hour,alarm_lag_1,alarm_lag_3,alarm_lag_6,alarm_lag_12,alarms_in_last_24h,is_weekend,is_night,total_active_alarms_lag1,neighbour_alarms,hours_since_last_alarm,isw_topic_0,isw_topic_1,isw_topic_2,isw_topic_3,isw_topic_4,isw_topic_5,isw_topic_6,isw_topic_7,isw_topic_8,isw_topic_9,isw_topic_10,isw_topic_11,isw_topic_12,isw_topic_13,isw_topic_14,isw_topic_15,isw_topic_16,isw_topic_17,isw_topic_18,isw_topic_19,isw_topic_20,isw_topic_21,isw_topic_22,isw_topic_23,isw_topic_24,isw_topic_25,isw_topic_26,isw_topic_27,isw_topic_28,isw_topic_29,isw_topic_30,isw_topic_31,isw_topic_32,isw_topic_33,isw_topic_34,isw_topic_35,isw_topic_36,isw_topic_37,isw_topic_38,isw_topic_39,isw_topic_40,isw_topic_41,isw_topic_42,isw_topic_43,isw_topic_44,isw_topic_45,isw_topic_46,isw_topic_47,isw_topic_48,isw_topic_49,isw_topic_50,isw_topic_51,isw_topic_52,isw_topic_53,isw_topic_54,isw_topic_55,isw_topic_56,isw_topic_57,isw_topic_58,isw_topic_59,isw_topic_60,isw_topic_61,isw_topic_62,isw_topic_63,isw_topic_64,isw_topic_65,isw_topic_66,isw_topic_67,isw_topic_68,isw_topic_69,isw_topic_70,isw_topic_71,isw_topic_72,isw_topic_73,isw_topic_74,isw_topic_75,isw_topic_76,isw_topic_77,isw_topic_78,isw_topic_79,isw_topic_80,isw_topic_81,isw_topic_82,isw_topic_83,isw_topic_84,isw_topic_85,isw_topic_86,isw_topic_87,isw_topic_88,isw_topic_89,isw_topic_90,isw_topic_91,isw_topic_92,isw_topic_93,isw_topic_94,isw_topic_95,isw_topic_96,isw_topic_97,isw_topic_98,isw_topic_99,isw_topic_100,isw_topic_101,isw_topic_102,isw_topic_103,isw_topic_104,isw_topic_105,isw_topic_106,isw_topic_107,isw_topic_108,isw_topic_109,isw_topic_110,isw_topic_111,isw_topic_112,isw_topic_113,isw_topic_114,isw_topic_115,isw_topic_116,isw_topic_117,isw_topic_118,isw_topic_119,isw_topic_120,isw_topic_121,isw_topic_122,isw_topic_123,isw_topic_124,isw_topic_125,isw_topic_126,isw_topic_127,isw_topic_128,isw_topic_129,isw_topic_130,isw_topic_131,isw_topic_132,isw_topic_133,isw_topic_134,isw_topic_135,isw_topic_136,isw_topic_137,isw_topic_138,isw_topic_139,isw_topic_140,isw_topic_141,isw_topic_142,isw_topic_143,isw_topic_144,isw_topic_145,isw_topic_146,isw_topic_147,isw_topic_148,isw_topic_149
0,2022-02-24 00:00:00,2,-0.3,0.3,100.0,4.17,0.77,2.1,-0.5,91.76,0.9,0.0,0.0,0.0,0.0,16.6,8.6,279.6,1021.0,91.1,0.0,0.1,0.0,False,True,False,False,3,0,Vinnytsia,2022-02-24,06:58:49,17:40:52,Вінницька,0,0.0,0.0,0.0,0.0,0.0,NaN,0,1,NaN,NaN,1,0.648336,-0.079572,0.178041,0.061854,0.073453,-0.055809,-0.011311,0.047310,0.008354,0.006474,-0.047099,0.020496,0.050190,-0.038573,0.057228,-0.072471,0.045393,-0.116783,0.168249,0.167355,-0.025072,-0.073858,-0.097024,-0.146191,0.027983,0.082989,0.014423,0.058370,-0.033928,0.046265,0.006901,-0.049498,0.126117,-0.089039,-0.006767,-0.031686,-0.010346,0.025637,0.061278,0.162580,-0.028081,0.161291,-0.018217,-0.002657,0.038485,-0.000530,0.044413,0.107176,-0.050721,0.064279,-0.066677,0.016742,-0.050257,0.072549,-0.035201,-0.027279,0.017115,0.043631,0.024660,-0.025841,0.031320,-0.076959,-0.072986,-0.040465,0.003958,-0.022475,0.033208,-0.028056,-0.005499,-0.055998,-0.021882,-0.070462,0.018237,-0.031396,-0.074606,0.072951,0.039997,0.036423,-0.027152,-0.071900,0.026267,-0.046270,-0.017945,0.007933,-0.006203,-0.046099,0.032793,-0.069113,0.020403,0.030783,-0.003787,-0.000490,-0.022951,0.013498,0.009664,-0.007012,-0.016325,-0.005732,0.036069,-0.063906,0.033891,0.010560,-0.104517,-0.022069,0.054322,-0.005460,-0.029093,0.040991,-0.053018,-0.024017,0.050817,-0.003297,-0.020895,-0.053213,-0.028428,0.048231,-0.001221,0.001302,-0.044137,0.015528,-0.012792,-0.012009,-0.008211,0.031114,0.024982,0.003863,-0.032321,0.030920,-0.012845,0.070170,-0.004037,0.014003,0.005577,0.021611,-0.002889,0.034824,0.047164,0.050545,-0.017639,0.029014,-0.030378,-0.027056,0.011464,-0.039759,-0.043514,-0.025605,-0.022484,-0.036224,0.000566,0.005481
1,2022-02-24 00:00:00,2,-0.3,0.3,100.0,4.17,0.77,2.1,-0.5,91.76,0.9,0.0,0.0,0.0,0.0,16.6,8.6,279.6,1021.0,91.1,0.0,0.1,0.0,False,True,False,False,3,0,Vinnytsia,2022-02-24,06:58:49,17:40:52,Вінницька,0,0.0,0.0,0.0,0.0,0.0,NaN,0,1,NaN,NaN,1,0.580161,-0.090608,-0.028388,0.146350,0.071072,-0.030284,-0.004583,0.087399,-0.038512,0.016613,-0.038599,0.049747,0.186305,-0.172198,-0.045515,0.050785,0.041889,-0.112849,0.193473,-0.010566,0.044308,-0.118300,0.007117,-0.135687,-0.009441,-0.039465,0.032843,0.080393,-0.035434,0.010352,-0.016680,-0.046252,0.085840,-0.123167,0.064510,-0.023735,-0.025637,-0.027863,0.032156,0.068641,0.027667,0.162729,0.039675,-0.016915,-0.008203,0.048024,0.073343,0.025782,-0.013935,-0.008775,-0.045265,0.008979,-0.100558,0.044074,0.018202,-0.037279,0.062349,0.008014,0.075917,-0.063409,0.015404,-0.091507,-0.079240,-0.033000,-0.019226,-0.103926,0.031514,0.043306,-0.012137,-0.010430,0.035901,-0.013437,-0.042046,-0.064986,0.002947,0.024326,0.085592,-0.008453,0.091087,-0.106852,0.038223,-0.061062,0.027905,0.056421,-0.030501,0.000050,0.051385,-0.087324,-0.024025,0.031626,-0.029461,0.015717,-0.047181,-0.005600,0.049867,0.084412,-0.055460,-0.036620,0.120475,-0.012080,0.006961,-0.079701,0.055655,0.004130,0.013250,0.002392,0.041937,0.028208,-0.037232,0.014886,-0.036905,0.000138,-0.018200,-0.010680,-0.067564,-0.001064,-0.044792,-0.014807,-0.031911,-0.023504,0.070783,0.027626,0.000418,0.043677,-0.030193,-0.034979,0.080093,0.035489,-0.004156,-0.008032,0.039826,-0.037380,0.011931,0.008267,0.000590,0.043862,0.023758,0.038714,0.066128,0.028168,-0.012153,0.005376,0.008085,-0.038933,0.003404,0.003281,-0.004149,-0.025392,0.010434,-0.017613
2,2022-02-24 01:00:00,2,-0.3,0.3,100.0,4.17,0.77,2.1,-0.4,89.80,0.6,0.0,0.0,0.0,0.0,16.6,8.3,289.2,1021.0,97.9,0.0,0.1,0.0,False,True,False,False,3,1,Vinnytsia,2022-02-24,06:58:49,17:40:52,Вінницька,0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0.0,0.0,2,0.648336,-0.079572,0.178041,0.061854,0.073453,-0.055809,-0.011311,0.047310,0.008354,0.006474,-0.047099,0.020496,0.050190,-0.038573,0.057228,-0.072471,0.045393,-0.116783,0.168249,0.167355,-0.025072,-0.073858,-0.097024,-0.146191,0.027983,0.082989,0.014423,0.058370,-0.033928,0.046265,0.006901,-0.049498,0.126117,-0.089039,-0.006767,-0.031686,-0.010346,0.025637,0.061278,0.162580,-0.028081,0.161291,-0.018217,-0.002657,0.038485,-0.000530,0.044413,0.107176,-0.050721,0.064279,-0.066677,0.016742,-0.050257,0.072549,-0.035201,-0.027279,0.017115,0.043631,0.024660,-0.025841,0.031320,-0.076959,-0.072986,-0.040465,0.003958,-0.022475,0.033208,-0.028056,-0.005499,-0.055998,-0.021882,-0.070462,0.018237,-0.031396,-0.074606,0.072951,0.039997,0.036423,-0.027152,-0.071900,0.026267,-0.046270,-0.017945,0.007933,-0.006203,-0.046099,0.032793,-0.069113,0.020403,0.030783,-0.003787,-0.000490,-0.022951,0.013498,0.009664,-0.007012,-0.016325,-0.005732,0.036069,-0.063906,0.033891,0.010560,-0.104517,-0.022069,0.054322,-0.005460,-0.029093,0.040991,-0.053018,-0.024017,0.050817,-0.003297,-0.020895,-0.053213,-0.028428,0.048231,-0.001221,0.001302,-0.044137,0.015528,-0.012792,-0.012009,-0.008211,0.031114,0.024982,0.003863,-0.032321,0.030920,-0.012845,0.070170,-0.004037,0.014003,0.005577,0.021611,-0.002889,0.034824,0.047164,0.050545,-0.017639,0.029014,-0.030378,-0.027056,0.011464,-0.039759,-0.043514,-0.025605,-0.022484,-0.036224,0.000566,0.005481
3,2022-02-24 01:00:00,2,-0.3,0.3,100.0,4.17,0.77,2.1,-0.4,89.80,0.6,0.0,0.0,0.0,0.0,16.6,8.3,289.2,1021.0,97.9,0.0,0.1,0.0,False,True,False,False,3,1,Vinnytsia,2022-02-24,06:58:49,17:40:52,Вінницька,0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0.0,0.0,2,0.580161,-0.090608,-0.028388,0.146350,0.071072,-0.030284,-0.004583,0.087399,-0.038512,0.016613,-0.038599,0.049747,0.186305,-0.172198,-0.045515,0.050785,0.041889,-0.112849,0.193473,-0.010566,0.044308,-0.118300,0.007117,-0.135687,-0.009441,-0.039465,0.032843,0.080393,-0.035434,0.010352,-0.016680,-0.046252,0.085840,-0.123167,0.064510,-0.023735,-0.025637,-0.027863,0.032156,0.068641,0.027667,0.162729,0.039675,-0.016915,-0.008203,0.048024,0.073343,0.025782,-0.013935,-0.008775,-0.045265,0.008979,-0.100558,0.044074,0.018202,-0.037279,0.062349,0.008014,0.075917,-0.063409,0.015404,-0.091507,-0.079240,-0.033000,-0.019226,-0.103926,0.031514,0.043306,-0.012137,-0.010430,0.035901,-0.013437,-0.042046,-0.064986,0.002947,0.024326,0.085592,-0.008453,0.091087,-0.106852,0.038223,-0.061062,0.027905,0.056421,-0.030501,0.000050,0.051385,-0.087324,-0.024025,0.031626,-0.029461,0.015717,-0.047181,-0.005600,0.049867,0.084412,-0.055460,-0.036620,0.120475,-0.012080,0.006961,-0.079701,0.055655,0.004130,0.013250,0.002392,0.041937,0.028208,-0.037232,0.014886,-0.036905,0.000138,-0.018200,-0.010680,-0.067564,-0.001064,-0.044792,-0.014807,-0.031911,-0.023504,0.070783,0.027626,0.000418,0.043677,-0.030193,-0.034979,0.080093,0.035489,-0.004156,-0.008032,0.039826,-0.037380,0.011931,0.008267,0.000590,0.043862,0.023758,0.038714,0.066128,0.028168,-0.012153,0.005376,0.008085,-0.038933,0.003404,0.003281,-0.004149,-0.025392,0.010434,-0.017613
4,2022-02-24 02:00:00,2,-0.3,0.3,100.0,4.17,0.77,2.0,-0.3,90.44,0.6,0.0,0.0,0.0,0.0,27.7,7.6,287.6,1021.0,98.2,0.0,0.1,0.0,False,True,False,False,3,2,Vinnytsia,2022-02-24,06:58:49,17:40:52,Вінницька,0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0.0,0.0,3,0.648336,-0.079572,0.178041,0.061854,0.073453,-0.055809,-0.011311,0.047310,0.008354,0.006474,-0.047099,0.020496,0.050190,-0.038573,0.057228,-0.072471,0.045393,-0.116783,0.168249,0.167355,-0.025072,-0.073858,-0.097024,-0.146191,0.027983,0.082989,0.014423,0.058370,-0.033928,0.046265,0.006901,-0.049498,0.126117,-0.089039,-0.006767,-0.031686,-0.010346,0.025637,0.061278,0.162580,-0.028081,0.161291,-0.018217,-0.002657,0.038485,-0.000530,0.044413,0.107176,-0.050721,0.064279,-0.066677,0.016742,-0.050257,0.072549,-0.035201,-0.027279,0.017115,0.043631,0.024660,-0.025841,0.031320,-0.076959,-0.072986,-0.040465,0.003958,-0.022475,0.033208,-0.028056,-0.005499,-0.055998,-0.021882,-0.070462,0.018237,-0.031396,-0.074606,0.072951,0.039997,0.036423,-0.027152,-0.071900,0.026267,-0.046270,-0.017945,0.007933,-0.006203,-0.046099,0.032793,-0.069113,0.020403,0.030783,-0.003787,-0.000490,-0.022951,0.013498,0.009664,-0.007012,-0.016325,-0.005732,0.036069,-0.063906,0.033891,0.010560,-0.104517,-0.022069,0.054322,-0.005460,-0.029093,0.040991,-0.053018,-0.024017,0.050817,-0.003297,-0.020895,-0.053213,-0.028428,0.048231,-0.001221,0.001302,-0.044137,0.015528,-0.012792,-0.012009,-0.008211,0.031114,0.024982,0.003863,-0.032321,0.030920,-0.012845,0.070170,-0.004037,0.014003,0.005577,0.021611,-0.002889,0.034824,0.047164,0.050545,-0.017639,0.029014,-0.030378,-0.027056,0.011464,-0.039759,-0.043514,-0.025605,-0.022484,-0.036224,0.000566,0.005481
5,2022-02-24 02:00:00,2,-0.3,0.3,100.0,4.17,0.77,2.0,-0.3,90.44,0.6,0.0,0.0,0.0,0.0,27.7,7.6,287.6,1021.0,98.2,0.0,0.1,0.0,False,True,False,False,3,2,Vinnytsia,2022-02-24,06:58:49,17:40:52,Вінницька,0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0.0,0.0,3,0.580161,-0.090608,-0.028388,0.146350,0.071072,-0.030284,-0.004583,0.087399,-0.038512,0.016613,-0.038599,0.049747,0.186305,-0.172198,-0.045515,0.050785,0.041889,-0.112849,0.193473,-0.010566,0.044308,-0.118300,0.007117,-0.135687,-0.009441,-0.039465,0.032843,0.080393,-0.035434,0.010352,-0.016680,-0.046252,0.085840,-0.123167,0.064510,-0.023735,-0.025637,-0.027863,0.032156,0.068641,0.027667,0.162729,0.039675,-0.016915,-0.008203,0.048024,0.073343,0.025782,-0.013935,-0.008775,-0.045265,0.008979,-0.100558,0.044074,0.018202,-0.037279,0.062349,0.008014,0.075917,-0.063409,0.015404,-0.091507,-0.079240,-0.033000,-0.019226,-0.103926,0.031514,0.043306,-0.012137,-0.010430,0.035901,-0.013437,-0.042046,-0.064986,0.002947,0.024326,0.085592,-0.008453,0.091087,-0.106852,0.038223,-0.061062,0.027905,0.056421,-0.030501,0.000050,0.051385,-0.087324,-0.024025,0.031626,-0.029461,0.015717,-0.047181,-0.005600,0.049867,0.084412,-0.055460,-0.036620,0.120475,-0.012080,0.006961,-0.079701,0.055655,0.004130,0.013250,0.002392,0.041937,0.028208,-0.037232,0.014886,-0.036905,0.000138,-0.018200,-0.010680,-0.067564,-0.001064,-0.044792,-0.014807,-0.031911,-0.023504,0.070783,0.027626,0.000418,0.043677,-0.030193,-0.034979,0.080093,0.035489,-0.004156,-0.008032,0.039826,-0.037380,0.011931,0.008267,0.000590,0.043862,0.023758,0.038714,0.066128,0.028168,-0.012153,0.005376,0.008085,-0.038933,0.003404,0.003281,-0.004149,-0.025392,0.010434,-0.017613
6,2022-02-24 03:00:00,2,-0.3,0.3,100.0,4.17,0.77,1.9,-0.3,91.75,0.7,0.0,0.0,0.0,0.0,15.1,7.2,288.9,1021.0,98.8,0.0,0.1,0.0,False,True,False,False,3,3,Vinnytsia,2022-02-24,06:58:49,17:40:52,Вінницька,0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0.0,0.0,4,0.648336,-0.079572,0.178041,0.061854,0.073453,-0.055809,-0.011311,0.047310,0.008354,0.006474,-0.047099,0.020496,0.050190,-0.038573,0.057228,-0.072471,0.045393,-0.116783,0.168249,0.167355,-0.025072,-0.073858,-0.097024,-0.146191,0.027983,0.082989,0.014423,0.058370,-0.033928,0.046265,0.006901,-0.049498,0.126117,-0.089039,-0.006767,-0.031686,-0.010346,0.025637,0.061278,0.162580,-0.028081,0.161291,-0.018217,-0.002657,0.038485,-0.000530,0.044413,0.107176,-0.050721,0.064279,-0.066677,0.016742,-0.050257,0.072549,-0.035201,-0.027279,0.017115,0.043631,0.024660,-0.025841,0.031320,-0.076959,-0.072986,-0.040465,0.003958,-0.022475,0.033208,-0.028056,-0.005499,-0.055998,-0.021882,-0.070462,0.018237,-0.031396,-0.074606,0.072951,0.039997,0.036423,-0.027152,-0.071900,0.026267,-0.046270,-0.017945,0.007933,-0.006203,-0.046099,0.032793,-0.069113,0.020403,0.030783,-0.003787,-0.000490,-0.022951,0.013498,0.009664,-0.007012,-0.016325,-0.005732,0.036069,-0.063906,0.033891,0.010560,-0.104517,-0.022069,0.054322,-0.005460,-0.029093,0.040991,-0.053018,-0.024017,0.050817,-0.003297,-0.020895,-0.053213,-0.028428,0.048231,-0.001221,0.001302,-0.044137,0.015528,-0.012792,-0.012009,-0.008211,0.031114,0.024982,0.003863,-0.032321,0.030920,-0.012845,0.070170,-0.004037,0.014003,0.005577,0.021611,-0.002889,0.034824,0.047164,0.050545,-0.017639,0.029014,-0.030378,-0.027056,0.011464,-0.039759,-0.043514,-0.025605,-0.022484,-0.036224,0.000566,0.005481
7,2022-02-24 03:00:00,2,-0.3,0.3,100.0,4.17,0.77,1.9,-0.3,91.75,0.7,0.0,0.0,0.0,0.0,15.1,7.2,288.9,1021.0,98.8,0.0,0.1,0.0,False,True,False,False,3,3,Vinnytsia,2022-02-24,06:58:49,17:40:52,Вінницька,0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0.0,0.0,4,0.580161,-0.090608,-0.028388,0.146350,0.071072,-0.030284,-0.004583,0.087399,-0.038512,0.016613,-0.038599,0.049747,0.186305,-0.172198,-0.045515,0.050785,0.041889,-0.112849,0.193473,-0.010566,0.044308,-0.118300,0.007117,-0.135687,-0.009441,-0.039465,0.032843,0.080393,-0.035434,0.010352,-0.016680,-0.046252,0.085840,-0.123167,0.064510,-0.023735,-0.025637,-0.027863,0.032156,0.068641,0.027667,0.162729,0.039675,-0.016915,-0.008203,0.048024,0.073343,0.025782,-0.013935,-0.008775,-0.045265,0.008979,-0.100558,0.044074,0.018202,-0.037279,0.062349,0.008014,0.075917,-0.063409,0.015404,-0.091507,-0.079240,-0.033000,-0.019226,-0.103926,0.031514,0.043306,-0.012137,-0.010430,0.035901,-0.013437,-0.042046,-0.064986,0.002947,0.024326,0.085592,-0.008453,0.091087,-0.106852,0.038223,-0.061062,0.027905,0.056421,-0.030501,0.000050,0.051385,-0.087324,-0.024025,0.031626,-0.029461,0.015717,-0.047181,-0.005600,0.049867,0.084412,-0.055460,-0.036620,0.120475,-0.012080,0.006961,-0.079701,0.055655,0.004130,0.013250,0.002392,0.041937,0.028208,-0.037232,0.014886,-0.036905,0.000138,-0.018200,-0.010680,-0.067564,-0.001064,-0.044792,-0.014807,-0.031911,-0.023504,0.070783,0.027626,0.000418,0.043677,-0.030193,-0.034979,0.080093,0.035489,-0.004156,-0.008032,0.039826,-0.037380,0.011931,0.008267,0.000590,0.043862,0.023758,0.038714,0.066128,0.028168,-0.012153,0.005376,0.008085,-0.038933,0.003404,0.003281,-0.004149,-0.025392,0.010434,-0.017613
8,2022-02-24 04:00:00,2,-0.3,0.3,100.0,4.17,0.77,1.8,-0.2,92.40,0.7,0.0,0.0,0.0,0.0,13.7,6.5,290.4,1021.0,100.0,0.0,0.1,0.0,False,True,False,False,3,4,Vinnytsia,2022-02-24,06:58:49,17:40:52,Вінницька,0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0.0,0.0,5,0.648336,-0.079572,0.178041,0.061854,0.073453,-0.055809,-0.011311,0.047310,0.008354,0.006474,-0.047099,0.020496,0.050190,-0.038573,0.057228,-0.072471,0.045393,-0.116783,0.168249,0.167355,-0.025072,-0.073858,-0.097024,-0.146191,0.027983,0.082989,0.014423,0.058370,-0.033928,0.046265,0.006901,-0.049498,0.126117,-0.089039,-0.006767,-0.031686,-0.010346,0.025637,0.061278,0.162580,-0.028081,0.161291,-0.018217,-0.002657,0.038485,-0.000530,0.044413,0.107176,-0.050721,0.064279,-0.066677,0.016742,-0.050257,0.072549,-0.035201,-0.027279,0.017115,0.043631,0.024660,-0.025841,0.031320,-0.076959,-0.072986,-0.040465,0.003958,-0.022475,0.033208,-0.028056,-0.005499,-0.055998,-0.021882,-0.070462,0.018237,-0.031396,-0.074606,0.072951,0.039997,0.036423,-0.027152,-0.071900,0.026267,-0.046270,-0.017945,0.007933,-0.006203,-0.046099,0.032793,-0.069113,0.020403,0.030783,-0.003787,-0.000490,-0.022951,0.013498,0.009664,-0.007012,-0.016325,-0.005732,0.036069,-0.063906,0.033891,0.010560,-0.104517,-0.022069,0.054322,-0.005460,-0.029093,0.040991,-0.053018,-0.024017,0.050817,-0.003297,-0.020895,-0.053213,-0.028428,0.048231,-0.001221,0.001302,-0.044137,0.015528,-0.012792,-0.012009,-0.008211,0.031114,0.024982,0.003863,-0.032321,0.030920,-0.012845,0.070170,-0.004037,0.014003,0.005577,0.021611,-0.002889,0.034824,0.047164,0.050545,-0.017639,0.029014,-0.030378,-0.027056,0.011464,-0.039759,-0.043514,-0.025605,-0.022484,-0.036224,0.000566,0.005481
9,2022-02-24 04:00:00,2,-0.3,0.3,100.0,4.17,0.77,1.8,-0.2,92.40,0.7,0.0,0.0,0.0,0.0,13.7,6.5,290.4,1021.0,100.0,0.0,0.1,0.0,False,True,False,False,3,4,Vinnytsia,2022-02-24,06:58:49,17:40:52,Вінницька,0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0.0,0.0,5,0.580161,-0.090608,-0.028388,0.146350,0.071072,-0.030284,-0.004583,0.087399,-0.038512,0.016613,-0.038599,0.049747,0.186305,-0.172198,-0.045515,0.050785,0.041889,-0.112849,0.193473,-0.010566,0.044308,-0.118300,0.007117,-0.135687,-0.009441,-0.039465,0.032843,0.080393,-0.035434,0.010352,-0.016680,-0.046252,0.085840,-0.123167,0.064510,-0.023735,-0.025637,-0.027863,0.032156,0.068641,0.027667,0.162729,0.039675,-0.016915,-0.008203,0.048024,0.073343,0.025782,-0.013935,-0.008775,-0.045265,0.008979,-0.100558,0.044074,0.018202,-0.037279,0.062349,0.008014,0.075917,-0.063409,0.015404,-0.091507,-0.079240,-0.033000,-0.019226,-0.103926,0.031514,0.043306,-0.012137,-0.010430,0.035901,-0.013437,-0.042046,-0.064986,0.002947,0.024326,0.085592,-0.008453,0.091087,-0.106852,0.038223,-0.061062,0.027905,0.056421,-0.030501,0.000050,0.051385,-0.087324,-0.024025,0.031626,-0.029461,0.015717,-0.047181,-0.005600,0.049867,0.084412,-0.055460,-0.036620,0.120475,-0.012080,0.006961,-0.079701,0.055655,0.004130,0.013250,0.002392,0.041937,0.028208,-0.037232,0.014886,-0.036905,0.000138,-0.018200,-0.010680,-0.067564,-0.001064,-0.044792,-0.014807,-0.031911,-0.023504,0.070783,0.027626,0.000418,0.043677,-0.030193,-0.034979,0.080093,0.035489,-0.004156,-0.008032,0.039826,-0.037380,0.011931,0.008267,0.000590,0.043862,0.023758,0.038714,0.066128,0.028168,-0.012153,0.005376,0.008085,-0.038933,0.003404,0.003281,-0.004149,-0.025392,0.010434,-0.017613

In [29]:
df_final.isna().sum()

datetime_hour         0
region_id             0
day_dew               0
day_precip            0
day_precipprob        0
                  ...
isw_topic_145     15696
isw_topic_146     15696
isw_topic_147     15696
isw_topic_148     15696
isw_topic_149     15696
Length: 196, dtype: int64

In [31]:
df_final.tail()

,datetime_hour,region_id,day_dew,day_precip,day_precipprob,day_precipcover,day_moonphase,hour_temp,hour_feelslike,hour_humidity,hour_dew,hour_precip,hour_precipprob,hour_snow,hour_snowdepth,hour_windgust,hour_windspeed,hour_winddir,hour_pressure,hour_cloudcover,hour_solarradiation,hour_solarenergy,hour_uvindex,hour_conditions_simple_Clear,hour_conditions_simple_Cloudy,hour_conditions_simple_Rain,hour_conditions_simple_Snow,day_of_week,hour,city_name,day_datetime,day_sunrise,day_sunset,region_key,alarm_active,alarm_minutes_in_hour,alarm_lag_1,alarm_lag_3,alarm_lag_6,alarm_lag_12,alarms_in_last_24h,is_weekend,is_night,total_active_alarms_lag1,neighbour_alarms,hours_since_last_alarm,isw_topic_0,isw_topic_1,isw_topic_2,isw_topic_3,isw_topic_4,isw_topic_5,isw_topic_6,isw_topic_7,isw_topic_8,isw_topic_9,isw_topic_10,isw_topic_11,isw_topic_12,isw_topic_13,isw_topic_14,isw_topic_15,isw_topic_16,isw_topic_17,isw_topic_18,isw_topic_19,isw_topic_20,isw_topic_21,isw_topic_22,isw_topic_23,isw_topic_24,isw_topic_25,isw_topic_26,isw_topic_27,isw_topic_28,isw_topic_29,isw_topic_30,isw_topic_31,isw_topic_32,isw_topic_33,isw_topic_34,isw_topic_35,isw_topic_36,isw_topic_37,isw_topic_38,isw_topic_39,isw_topic_40,isw_topic_41,isw_topic_42,isw_topic_43,isw_topic_44,isw_topic_45,isw_topic_46,isw_topic_47,isw_topic_48,isw_topic_49,isw_topic_50,isw_topic_51,isw_topic_52,isw_topic_53,isw_topic_54,isw_topic_55,isw_topic_56,isw_topic_57,isw_topic_58,isw_topic_59,isw_topic_60,isw_topic_61,isw_topic_62,isw_topic_63,isw_topic_64,isw_topic_65,isw_topic_66,isw_topic_67,isw_topic_68,isw_topic_69,isw_topic_70,isw_topic_71,isw_topic_72,isw_topic_73,isw_topic_74,isw_topic_75,isw_topic_76,isw_topic_77,isw_topic_78,isw_topic_79,isw_topic_80,isw_topic_81,isw_topic_82,isw_topic_83,isw_topic_84,isw_topic_85,isw_topic_86,isw_topic_87,isw_topic_88,isw_topic_89,isw_topic_90,isw_topic_91,isw_topic_92,isw_topic_93,isw_topic_94,isw_topic_95,isw_topic_96,isw_topic_97,isw_topic_98,isw_topic_99,isw_topic_100,isw_topic_101,isw_topic_102,isw_topic_103,isw_topic_104,isw_topic_105,isw_topic_106,isw_topic_107,isw_topic_108,isw_topic_109,isw_topic_110,isw_topic_111,isw_topic_112,isw_topic_113,isw_topic_114,isw_topic_115,isw_topic_116,isw_topic_117,isw_topic_118,isw_topic_119,isw_topic_120,isw_topic_121,isw_topic_122,isw_topic_123,isw_topic_124,isw_topic_125,isw_topic_126,isw_topic_127,isw_topic_128,isw_topic_129,isw_topic_130,isw_topic_131,isw_topic_132,isw_topic_133,isw_topic_134,isw_topic_135,isw_topic_136,isw_topic_137,isw_topic_138,isw_topic_139,isw_topic_140,isw_topic_141,isw_topic_142,isw_topic_143,isw_topic_144,isw_topic_145,isw_topic_146,isw_topic_147,isw_topic_148,isw_topic_149
844988,2026-03-16 19:00:00,26,-1.8,0.0,0.0,0.0,0.92,7.5,7.5,55.25,-0.9,0.0,0.0,0.0,0.0,10.4,3.6,80.0,1019.0,44.3,5.5,0.1,0.0,False,True,False,False,0,19,Kyiv,2026-03-16,06:09:51,18:04:17,Київ,0,0.000000,0.0,0.0,0.0,0.0,3.0,0,0,8.0,1.0,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
844989,2026-03-16 20:00:00,26,-1.8,0.0,0.0,0.0,0.92,6.9,6.9,59.27,-0.5,0.0,0.0,0.0,0.0,9.4,4.0,79.6,1021.0,59.3,5.5,0.1,0.0,False,True,False,False,0,20,Kyiv,2026-03-16,06:09:51,18:04:17,Київ,0,0.000000,0.0,0.0,0.0,1.0,3.0,0,0,11.0,1.0,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
844990,2026-03-16 21:00:00,26,-1.8,0.0,0.0,0.0,0.92,6.1,6.1,62.62,-0.5,0.0,0.0,0.0,0.0,10.1,3.6,88.3,1021.0,39.4,5.5,0.1,0.0,False,True,False,False,0,21,Kyiv,2026-03-16,06:09:51,18:04:17,Київ,0,0.000000,0.0,0.0,0.0,1.0,3.0,0,0,8.0,0.0,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
844991,2026-03-16 22:00:00,26,-1.8,0.0,0.0,0.0,0.92,5.3,5.3,65.23,-0.7,0.0,0.0,0.0,0.0,9.0,2.5,85.6,1021.0,19.4,5.5,0.1,0.0,True,False,False,False,0,22,Kyiv,2026-03-16,06:09:51,18:04:17,Київ,1,25.650000,0.0,0.0,0.0,0.0,3.0,0,0,9.0,0.0,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
844992,2026-03-16 23:00:00,26,-1.8,0.0,0.0,0.0,0.92,4.7,4.7,66.06,-1.1,0.0,0.0,0.0,0.0,5.8,2.2,63.2,1021.0,10.6,5.5,0.1,0.0,True,False,False,False,0,23,Kyiv,2026-03-16,06:09:51,18:04:17,Київ,1,17.216667,1.0,0.0,0.0,1.0,4.0,0,1,10.0,1.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [35]:
df_final.fillna(0, inplace=True)

,datetime_hour,region_id,day_dew,day_precip,day_precipprob,day_precipcover,day_moonphase,hour_temp,hour_feelslike,hour_humidity,hour_dew,hour_precip,hour_precipprob,hour_snow,hour_snowdepth,hour_windgust,hour_windspeed,hour_winddir,hour_pressure,hour_cloudcover,hour_solarradiation,hour_solarenergy,hour_uvindex,hour_conditions_simple_Clear,hour_conditions_simple_Cloudy,hour_conditions_simple_Rain,hour_conditions_simple_Snow,day_of_week,hour,city_name,day_datetime,day_sunrise,day_sunset,region_key,alarm_active,alarm_minutes_in_hour,alarm_lag_1,alarm_lag_3,alarm_lag_6,alarm_lag_12,alarms_in_last_24h,is_weekend,is_night,total_active_alarms_lag1,neighbour_alarms,hours_since_last_alarm,isw_topic_0,isw_topic_1,isw_topic_2,isw_topic_3,isw_topic_4,isw_topic_5,isw_topic_6,isw_topic_7,isw_topic_8,isw_topic_9,isw_topic_10,isw_topic_11,isw_topic_12,isw_topic_13,isw_topic_14,isw_topic_15,isw_topic_16,isw_topic_17,isw_topic_18,isw_topic_19,isw_topic_20,isw_topic_21,isw_topic_22,isw_topic_23,isw_topic_24,isw_topic_25,isw_topic_26,isw_topic_27,isw_topic_28,isw_topic_29,isw_topic_30,isw_topic_31,isw_topic_32,isw_topic_33,isw_topic_34,isw_topic_35,isw_topic_36,isw_topic_37,isw_topic_38,isw_topic_39,isw_topic_40,isw_topic_41,isw_topic_42,isw_topic_43,isw_topic_44,isw_topic_45,isw_topic_46,isw_topic_47,isw_topic_48,isw_topic_49,isw_topic_50,isw_topic_51,isw_topic_52,isw_topic_53,isw_topic_54,isw_topic_55,isw_topic_56,isw_topic_57,isw_topic_58,isw_topic_59,isw_topic_60,isw_topic_61,isw_topic_62,isw_topic_63,isw_topic_64,isw_topic_65,isw_topic_66,isw_topic_67,isw_topic_68,isw_topic_69,isw_topic_70,isw_topic_71,isw_topic_72,isw_topic_73,isw_topic_74,isw_topic_75,isw_topic_76,isw_topic_77,isw_topic_78,isw_topic_79,isw_topic_80,isw_topic_81,isw_topic_82,isw_topic_83,isw_topic_84,isw_topic_85,isw_topic_86,isw_topic_87,isw_topic_88,isw_topic_89,isw_topic_90,isw_topic_91,isw_topic_92,isw_topic_93,isw_topic_94,isw_topic_95,isw_topic_96,isw_topic_97,isw_topic_98,isw_topic_99,isw_topic_100,isw_topic_101,isw_topic_102,isw_topic_103,isw_topic_104,isw_topic_105,isw_topic_106,isw_topic_107,isw_topic_108,isw_topic_109,isw_topic_110,isw_topic_111,isw_topic_112,isw_topic_113,isw_topic_114,isw_topic_115,isw_topic_116,isw_topic_117,isw_topic_118,isw_topic_119,isw_topic_120,isw_topic_121,isw_topic_122,isw_topic_123,isw_topic_124,isw_topic_125,isw_topic_126,isw_topic_127,isw_topic_128,isw_topic_129,isw_topic_130,isw_topic_131,isw_topic_132,isw_topic_133,isw_topic_134,isw_topic_135,isw_topic_136,isw_topic_137,isw_topic_138,isw_topic_139,isw_topic_140,isw_topic_141,isw_topic_142,isw_topic_143,isw_topic_144,isw_topic_145,isw_topic_146,isw_topic_147,isw_topic_148,isw_topic_149
0,2022-02-24 00:00:00,2,-0.3,0.3,100.0,4.17,0.77,2.1,-0.5,91.76,0.9,0.0,0.0,0.0,0.0,16.6,8.6,279.6,1021.0,91.1,0.0,0.1,0.0,False,True,False,False,3,0,Vinnytsia,2022-02-24,06:58:49,17:40:52,Вінницька,0,0.000000,0.0,0.0,0.0,0.0,0.0,0,1,0.0,0.0,1,0.648336,-0.079572,0.178041,0.061854,0.073453,-0.055809,-0.011311,0.047310,0.008354,0.006474,-0.047099,0.020496,0.050190,-0.038573,0.057228,-0.072471,0.045393,-0.116783,0.168249,0.167355,-0.025072,-0.073858,-0.097024,-0.146191,0.027983,0.082989,0.014423,0.058370,-0.033928,0.046265,0.006901,-0.049498,0.126117,-0.089039,-0.006767,-0.031686,-0.010346,0.025637,0.061278,0.162580,-0.028081,0.161291,-0.018217,-0.002657,0.038485,-0.000530,0.044413,0.107176,-0.050721,0.064279,-0.066677,0.016742,-0.050257,0.072549,-0.035201,-0.027279,0.017115,0.043631,0.024660,-0.025841,0.031320,-0.076959,-0.072986,-0.040465,0.003958,-0.022475,0.033208,-0.028056,-0.005499,-0.055998,-0.021882,-0.070462,0.018237,-0.031396,-0.074606,0.072951,0.039997,0.036423,-0.027152,-0.071900,0.026267,-0.046270,-0.017945,0.007933,-0.006203,-0.046099,0.032793,-0.069113,0.020403,0.030783,-0.003787,-0.000490,-0.022951,0.013498,0.009664,-0.007012,-0.016325,-0.005732,0.036069,-0.063906,0.033891,0.010560,-0.104517,-0.022069,0.054322,-0.005460,-0.029093,0.040991,-0.053018,-0.024017,0.050817,-0.003297,-0.020895,-0.053213,-0.028428,0.048231,-0.001221,0.001302,-0.044137,0.015528,-0.012792,-0.012009,-0.008211,0.031114,0.024982,0.003863,-0.032321,0.030920,-0.012845,0.070170,-0.004037,0.014003,0.005577,0.021611,-0.002889,0.034824,0.047164,0.050545,-0.017639,0.029014,-0.030378,-0.027056,0.011464,-0.039759,-0.043514,-0.025605,-0.022484,-0.036224,0.000566,0.005481
1,2022-02-24 00:00:00,2,-0.3,0.3,100.0,4.17,0.77,2.1,-0.5,91.76,0.9,0.0,0.0,0.0,0.0,16.6,8.6,279.6,1021.0,91.1,0.0,0.1,0.0,False,True,False,False,3,0,Vinnytsia,2022-02-24,06:58:49,17:40:52,Вінницька,0,0.000000,0.0,0.0,0.0,0.0,0.0,0,1,0.0,0.0,1,0.580161,-0.090608,-0.028388,0.146350,0.071072,-0.030284,-0.004583,0.087399,-0.038512,0.016613,-0.038599,0.049747,0.186305,-0.172198,-0.045515,0.050785,0.041889,-0.112849,0.193473,-0.010566,0.044308,-0.118300,0.007117,-0.135687,-0.009441,-0.039465,0.032843,0.080393,-0.035434,0.010352,-0.016680,-0.046252,0.085840,-0.123167,0.064510,-0.023735,-0.025637,-0.027863,0.032156,0.068641,0.027667,0.162729,0.039675,-0.016915,-0.008203,0.048024,0.073343,0.025782,-0.013935,-0.008775,-0.045265,0.008979,-0.100558,0.044074,0.018202,-0.037279,0.062349,0.008014,0.075917,-0.063409,0.015404,-0.091507,-0.079240,-0.033000,-0.019226,-0.103926,0.031514,0.043306,-0.012137,-0.010430,0.035901,-0.013437,-0.042046,-0.064986,0.002947,0.024326,0.085592,-0.008453,0.091087,-0.106852,0.038223,-0.061062,0.027905,0.056421,-0.030501,0.000050,0.051385,-0.087324,-0.024025,0.031626,-0.029461,0.015717,-0.047181,-0.005600,0.049867,0.084412,-0.055460,-0.036620,0.120475,-0.012080,0.006961,-0.079701,0.055655,0.004130,0.013250,0.002392,0.041937,0.028208,-0.037232,0.014886,-0.036905,0.000138,-0.018200,-0.010680,-0.067564,-0.001064,-0.044792,-0.014807,-0.031911,-0.023504,0.070783,0.027626,0.000418,0.043677,-0.030193,-0.034979,0.080093,0.035489,-0.004156,-0.008032,0.039826,-0.037380,0.011931,0.008267,0.000590,0.043862,0.023758,0.038714,0.066128,0.028168,-0.012153,0.005376,0.008085,-0.038933,0.003404,0.003281,-0.004149,-0.025392,0.010434,-0.017613
2,2022-02-24 01:00:00,2,-0.3,0.3,100.0,4.17,0.77,2.1,-0.4,89.80,0.6,0.0,0.0,0.0,0.0,16.6,8.3,289.2,1021.0,97.9,0.0,0.1,0.0,False,True,False,False,3,1,Vinnytsia,2022-02-24,06:58:49,17:40:52,Вінницька,0,0.000000,0.0,0.0,0.0,0.0,0.0,0,1,0.0,0.0,2,0.648336,-0.079572,0.178041,0.061854,0.073453,-0.055809,-0.011311,0.047310,0.008354,0.006474,-0.047099,0.020496,0.050190,-0.038573,0.057228,-0.072471,0.045393,-0.116783,0.168249,0.167355,-0.025072,-0.073858,-0.097024,-0.146191,0.027983,0.082989,0.014423,0.058370,-0.033928,0.046265,0.006901,-0.049498,0.126117,-0.089039,-0.006767,-0.031686,-0.010346,0.025637,0.061278,0.162580,-0.028081,0.161291,-0.018217,-0.002657,0.038485,-0.000530,0.044413,0.107176,-0.050721,0.064279,-0.066677,0.016742,-0.050257,0.072549,-0.035201,-0.027279,0.017115,0.043631,0.024660,-0.025841,0.031320,-0.076959,-0.072986,-0.040465,0.003958,-0.022475,0.033208,-0.028056,-0.005499,-0.055998,-0.021882,-0.070462,0.018237,-0.031396,-0.074606,0.072951,0.039997,0.036423,-0.027152,-0.071900,0.026267,-0.046270,-0.017945,0.007933,-0.006203,-0.046099,0.032793,-0.069113,0.020403,0.030783,-0.003787,-0.000490,-0.022951,0.013498,0.009664,-0.007012,-0.016325,-0.005732,0.036069,-0.063906,0.033891,0.010560,-0.104517,-0.022069,0.054322,-0.005460,-0.029093,0.040991,-0.053018,-0.024017,0.050817,-0.003297,-0.020895,-0.053213,-0.028428,0.048231,-0.001221,0.001302,-0.044137,0.015528,-0.012792,-0.012009,-0.008211,0.031114,0.024982,0.003863,-0.032321,0.030920,-0.012845,0.070170,-0.004037,0.014003,0.005577,0.021611,-0.002889,0.034824,0.047164,0.050545,-0.017639,0.029014,-0.030378,-0.027056,0.011464,-0.039759,-0.043514,-0.025605,-0.022484,-0.036224,0.000566,0.005481
3,2022-02-24 01:00:00,2,-0.3,0.3,100.0,4.17,0.77,2.1,-0.4,89.80,0.6,0.0,0.0,0.0,0.0,16.6,8.3,289.2,1021.0,97.9,0.0,0.1,0.0,False,True,False,False,3,1,Vinnytsia,2022-02-24,06:58:49,17:40:52,Вінницька,0,0.000000,0.0,0.0,0.0,0.0,0.0,0,1,0.0,0.0,2,0.580161,-0.090608,-0.028388,0.146350,0.071072,-0.030284,-0.004583,0.087399,-0.038512,0.016613,-0.038599,0.049747,0.186305,-0.172198,-0.045515,0.050785,0.041889,-0.112849,0.193473,-0.010566,0.044308,-0.118300,0.007117,-0.135687,-0.009441,-0.039465,0.032843,0.080393,-0.035434,0.010352,-0.016680,-0.046252,0.085840,-0.123167,0.064510,-0.023735,-0.025637,-0.027863,0.032156,0.068641,0.027667,0.162729,0.039675,-0.016915,-0.008203,0.048024,0.073343,0.025782,-0.013935,-0.008775,-0.045265,0.008979,-0.100558,0.044074,0.018202,-0.037279,0.062349,0.008014,0.075917,-0.063409,0.015404,-0.091507,-0.079240,-0.033000,-0.019226,-0.103926,0.031514,0.043306,-0.012137,-0.010430,0.035901,-0.013437,-0.042046,-0.064986,0.002947,0.024326,0.085592,-0.008453,0.091087,-0.106852,0.038223,-0.061062,0.027905,0.056421,-0.030501,0.000050,0.051385,-0.087324,-0.024025,0.031626,-0.029461,0.015717,-0.047181,-0.005600,0.049867,0.084412,-0.055460,-0.036620,0.120475,-0.012080,0.006961,-0.079701,0.055655,0.004130,0.013250,0.002392,0.041937,0.028208,-0.037232,0.014886,-0.036905,0.000138,-0.018200,-0.010680,-0.067564,-0.001064,-0.044792,-0.014807,-0.031911,-0.023504,0.070783,0.027626,0.000418,0.043677,-0.030193,-0.034979,0.080093,0.035489,-0.004156,-0.008032,0.039826,-0.037380,0.011931,0.008267,0.000590,0.043862,0.023758,0.038714,0.066128,0.028168,-0.012153,0.005376,0.008085,-0.038933,0.003404,0.003281,-0.004149,-0.025392,0.010434,-0.017613
4,2022-02-24 02:00:00,2,-0.3,0.3,100.0,4.17,0.77,2.0,-0.3,90.44,0.6,0.0,0.0,0.0,0.0,27.7,7.6,287.6,1021.0,98.2,0.0,0.1,0.0,False,True,False,False,3,2,Vinnytsia,2022-02-24,06:58:49,17:40:52,Вінницька,0,0.000000,0.0,0.0,0.0,0.0,0.0,0,1,0.0,0.0,3,0.648336,-0.079572,0.178041,0.061854,0.073453,-0.055809,-0.011311,0.047310,0.008354,0.006474,-0.047099,0.020496,0.050190,-0.038573,0.057228,-0.072471,0.045393,-0.116783,0.168249,0.167355,-0.025072,-0.073858,-0.097024,-0.146191,0.027983,0.082989,0.014423,0.058370,-0.033928,0.046265,0.006901,-0.049498,0.126117,-0.089039,-0.006767,-0.031686,-0.010346,0.025637,0.061278,0.162580,-0.028081,0.161291,-0.018217,-0.002657,0.038485,-0.000530,0.044413,0.107176,-0.050721,0.064279,-0.066677,0.016742,-0.050257,0.072549,-0.035201,-0.027279,0.017115,0.043631,0.024660,-0.025841,0.031320,-0.076959,-0.072986,-0.040465,0.003958,-0.022475,0.033208,-0.028056,-0.005499,-0.055998,-0.021882,-0.070462,0.018237,-0.031396,-0.074606,0.072951,0.039997,0.036423,-0.027152,-0.071900,0.026267,-0.046270,-0.017945,0.007933,-0.006203,-0.046099,0.032793,-0.069113,0.020403,0.030783,-0.003787,-0.000490,-0.022951,0.013498,0.009664,-0.007012,-0.016325,-0.005732,0.036069,-0.063906,0.033891,0.010560,-0.104517,-0.022069,0.054322,-0.005460,-0.029093,0.040991,-0.053018,-0.024017,0.050817,-0.003297,-0.020895,-0.053213,-0.028428,0.048231,-0.001221,0.001302,-0.044137,0.015528,-0.012792,-0.012009,-0.008211,0.031114,0.024982,0.003863,-0.032321,0.030920,-0.012845,0.070170,-0.004037,0.014003,0.005577,0.021611,-0.002889,0.034824,0.047164,0.050545,-0.017639,0.029014,-0.030378,-0.027056,0.011464,-0.039759,-0.043514,-0.025605,-0.022484,-0.036224,0.000566,0.005481
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
844988,2026-03-16 19:00:00,26,-1.8,0.0,0.0,0.00,0.92,7.5,7.5,55.25,-0.9,0.0,0.0,0.0,0.0,10.4,3.6,80.0,1019.0,44.3,5.5,0.1,0.0,False,True,False,False,0,19,Kyiv,2026-03-16,06:09:51,18:04:17,Київ,0,0.000000,0.0,0.0,0.0,0.0,3.0,0,0,8.0,1.0,7,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
844989,2026-03-16 20:00:00,26,-1.8,0.0,0.0,0.00,0.92,6.9,6.9,59.27,-0.5,0.0,0.0,0.0,0.0,9.4,4.0,79.6,1021.0,59.3,5.5,0.1,0.0,False,True,False,False,0,20,Kyiv,2026-03-16,06:09:51,18:04:17,Київ,0,0.000000,0.0,0.0,0.0,1.0,3.0,0,0,11.0,1.0,8,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
844990,2026-03-16 21:00:00,26,-1.8,0.0,0.0,0.00,0.92,6.1,6.1,62.62,-0.5,0.0,0.0,0.0,0.0,10.1,3.6,88.3,1021.0,39.4,5.5,0.1,0.0,False,True,False,False,0,21,Kyiv,2026-03-16,06:09:51,18:04:17,Київ,0,0.000000,0.0,0.0,0.0,1.0,3.0,0,0,8.0,0.0,9,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
844991,2026-03-16 22:00:00,26,-1.8,0.0,0.0,0.00,0.92,5.3,5.3,65.23,-0.7,0.0,0.0,0.0,0.0,9.0,2.5,85.6,1021.0,19.4,5.5,0.1,0.0,True,False,False,False,0,22,Kyiv,2026-03-16,06:09:51,18:04:17,Київ,1,25.650000,0.0,0.0,0.0,0.0,3.0,0,0,9.0,0.0,10,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
844992,2026-03-16 23:00:00,26,-1.8,0.0,0.0,0.00,0.92,4.7,4.7,66.06,-1.1,0.0,0.0,0.0,0.0,5.8,2.2,63.2,1021.0,10.6,5.5,0.1,0.0,True,False,False,False,0,23,Kyiv,2026-03-16,06:09:51,18:04:17,Київ,1,17.216667,1.0,0.0,0.0,1.0,4.0,0,1,10.0,1.0,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

In [36]:
df_final.isna().sum()

datetime_hour     0
region_id         0
day_dew           0
day_precip        0
day_precipprob    0
                 ..
isw_topic_145     0
isw_topic_146     0
isw_topic_147     0
isw_topic_148     0
isw_topic_149     0
Length: 196, dtype: int64

### Feature engineering for isw topics

In [37]:
topic_cols = [c for c in df_final.columns if "isw_topic_" in c]
df_isw_abs = df_final[topic_cols].abs()

df_final['isw_total_intensity'] = df_isw_abs.sum(axis=1)
df_final['isw_topic_std'] = df_isw_abs.std(axis=1)
df_final['isw_topic_max'] = df_isw_abs.max(axis=1)
df_final['isw_topic_mean'] = df_isw_abs.mean(axis=1)

df_final['isw_velocity_24h'] = (
    df_final.groupby('region_id')['isw_total_intensity']
    .diff(24)
    .fillna(0)
)

df_final['isw_intensity_ema'] = (df_final.groupby('region_id')['isw_total_intensity'].transform(lambda x: x.shift(1).ewm(span=24).mean()))

df_final['isw_topic_entropy'] = -(df_isw_abs.div(df_isw_abs.sum(axis=1), axis=0) * np.log(df_isw_abs.div(df_isw_abs.sum(axis=1), axis=0) + 1e-9)).sum(axis=1)

isw_cols = ['isw_velocity_24h', 'isw_intensity_ema', 'isw_topic_entropy']
df_final[isw_cols] = df_final[isw_cols].fillna(0)

C:\Users\Uw11\AppData\Local\Temp\ipykernel_33600\1269306822.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_final['isw_total_intensity'] = df_isw_abs.sum(axis=1)
C:\Users\Uw11\AppData\Local\Temp\ipykernel_33600\1269306822.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_final['isw_topic_std'] = df_isw_abs.std(axis=1)
C:\Users\Uw11\AppData\Local\Temp\ipykernel_33600\1269306822.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_final['isw_topic_max'] = df_isw_abs.max(axis=1)
C:\Users\Uw11\AppData\Local\Temp\ipykernel_33600\1269306822.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_final['isw_topic_mean'] = df_isw_abs.mean(axis=1)
C:\Users\Uw11\AppData\Local\Temp\ipykernel_33600\1269306822.py:9: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_final['isw_velocity_24h'] = (
C:\Users\Uw11\AppData\Local\Temp\ipykernel_33600\1269306822.py:15: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_final['isw_intensity_ema'] = (df_final.groupby('region_id')['isw_total_intensity'].transform(lambda x: x.shift(1).ewm(span=24).mean()))
C:\Users\Uw11\AppData\Local\Temp\ipykernel_33600\1269306822.py:17: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_final['isw_topic_entropy'] = -(df_isw_abs.div(df_isw_abs.sum(axis=1), axis=0) * np.log(df_isw_abs.div(df_isw_abs.sum(axis=1), axis=0) + 1e-9)).sum(axis=1)

In [38]:
df_final.sample(10)

,datetime_hour,region_id,day_dew,day_precip,day_precipprob,day_precipcover,day_moonphase,hour_temp,hour_feelslike,hour_humidity,hour_dew,hour_precip,hour_precipprob,hour_snow,hour_snowdepth,hour_windgust,hour_windspeed,hour_winddir,hour_pressure,hour_cloudcover,hour_solarradiation,hour_solarenergy,hour_uvindex,hour_conditions_simple_Clear,hour_conditions_simple_Cloudy,hour_conditions_simple_Rain,hour_conditions_simple_Snow,day_of_week,hour,city_name,day_datetime,day_sunrise,day_sunset,region_key,alarm_active,alarm_minutes_in_hour,alarm_lag_1,alarm_lag_3,alarm_lag_6,alarm_lag_12,alarms_in_last_24h,is_weekend,is_night,total_active_alarms_lag1,neighbour_alarms,hours_since_last_alarm,isw_topic_0,isw_topic_1,isw_topic_2,isw_topic_3,isw_topic_4,isw_topic_5,isw_topic_6,isw_topic_7,isw_topic_8,isw_topic_9,isw_topic_10,isw_topic_11,isw_topic_12,isw_topic_13,isw_topic_14,isw_topic_15,isw_topic_16,isw_topic_17,isw_topic_18,isw_topic_19,isw_topic_20,isw_topic_21,isw_topic_22,isw_topic_23,isw_topic_24,isw_topic_25,isw_topic_26,isw_topic_27,isw_topic_28,isw_topic_29,isw_topic_30,isw_topic_31,isw_topic_32,isw_topic_33,isw_topic_34,isw_topic_35,isw_topic_36,isw_topic_37,isw_topic_38,isw_topic_39,isw_topic_40,isw_topic_41,isw_topic_42,isw_topic_43,isw_topic_44,isw_topic_45,isw_topic_46,isw_topic_47,isw_topic_48,isw_topic_49,isw_topic_50,isw_topic_51,isw_topic_52,isw_topic_53,isw_topic_54,isw_topic_55,isw_topic_56,isw_topic_57,isw_topic_58,isw_topic_59,isw_topic_60,isw_topic_61,isw_topic_62,isw_topic_63,isw_topic_64,isw_topic_65,isw_topic_66,isw_topic_67,isw_topic_68,isw_topic_69,isw_topic_70,isw_topic_71,isw_topic_72,isw_topic_73,isw_topic_74,isw_topic_75,isw_topic_76,isw_topic_77,isw_topic_78,isw_topic_79,isw_topic_80,isw_topic_81,isw_topic_82,isw_topic_83,isw_topic_84,isw_topic_85,isw_topic_86,isw_topic_87,isw_topic_88,isw_topic_89,isw_topic_90,isw_topic_91,isw_topic_92,isw_topic_93,isw_topic_94,isw_topic_95,isw_topic_96,isw_topic_97,isw_topic_98,isw_topic_99,isw_topic_100,isw_topic_101,isw_topic_102,isw_topic_103,isw_topic_104,isw_topic_105,isw_topic_106,isw_topic_107,isw_topic_108,isw_topic_109,isw_topic_110,isw_topic_111,isw_topic_112,isw_topic_113,isw_topic_114,isw_topic_115,isw_topic_116,isw_topic_117,isw_topic_118,isw_topic_119,isw_topic_120,isw_topic_121,isw_topic_122,isw_topic_123,isw_topic_124,isw_topic_125,isw_topic_126,isw_topic_127,isw_topic_128,isw_topic_129,isw_topic_130,isw_topic_131,isw_topic_132,isw_topic_133,isw_topic_134,isw_topic_135,isw_topic_136,isw_topic_137,isw_topic_138,isw_topic_139,isw_topic_140,isw_topic_141,isw_topic_142,isw_topic_143,isw_topic_144,isw_topic_145,isw_topic_146,isw_topic_147,isw_topic_148,isw_topic_149,isw_total_intensity,isw_topic_std,isw_topic_max,isw_topic_mean,isw_velocity_24h,isw_intensity_ema,isw_topic_entropy
717349,2023-10-28 22:00:00,23,8.5,2.600,100.0,20.83,0.50,12.0,12.0,69.05,6.5,0.0,0.0,0.0,0.0,38.2,18.7,275.7,1006.0,4.2,0.0,0.0,0.0,True,False,False,False,5,22,Cherkasy,2023-10-28,07:32:48,17:37:36,Черкаська,0,0.00,0.0,0.0,0.0,1.0,4.0,1,0,6.0,0.0,9,0.780125,-0.078214,-0.107154,-0.200354,-0.047502,-0.162899,-0.198176,-0.062243,-0.143992,-0.057412,-0.090597,-0.033255,-0.106709,-0.041674,0.032578,-0.130523,0.050504,0.053701,0.001499,-0.061491,-0.056953,0.008248,-0.054784,0.006040,0.045104,0.053447,-0.034620,-0.064085,0.038855,-0.047638,-0.001892,-0.048556,0.002408,-0.015156,0.016534,-0.004498,0.032239,-0.036042,0.025961,0.001280,0.059896,0.008775,0.026882,0.008909,0.034830,0.002943,-0.050798,0.011676,0.033403,0.043676,0.007134,-0.029772,0.018775,-0.016045,-0.005306,0.018814,0.032342,0.004165,0.027896,-0.035272,0.004270,-0.032764,0.018601,0.001412,0.006088,0.037498,-0.037997,-0.011988,0.015662,-0.004225,0.010505,-0.005078,0.001676,0.024582,0.044064,0.019680,-0.000681,0.028726,0.023436,0.002041,0.003866,-0.021816,0.014209,-0.013614,0.021637,-0.023041,-0.008005,0.004920,0.002885,-0.026602,0.007864,0.029133,-0.000101,0.002658,0.021538,0.027345,-0.003936,-0.006009,-0.008835,0.005523,0.002450,0.012787,0.006165,-0.030743,0.031132,0.033777,0.014151,-0.012238,0.020356,0.018971,-0.000032,0.031046,0.023342,-0.022854,-0.025774,-0.005745,0.012944,-0.003679,-0.007151,-0.026187,-0.018394,0.003975,0.017221,0.020076,-0.027048,0.028733,0.008870,0.020670,-0.029674,0.005411,-0.042289,-0.012913,-0.017654,-0.018263,0.009713,-0.000129,0.010238,-0.008485,0.030518,-0.015048,-0.014986,-0.020662,0.013156,0.024972,-0.008487,0.014767,0.008090,0.002849,0.021696,0.000518,4.913791,0.069817,0.780125,0.032759,0.188192,4.882179,4.226585
225181,2024-07-07 15:00:00,8,13.9,0.000,0.0,0.00,0.05,29.1,28.6,39.14,13.8,0.0,0.0,0.0,0.0,25.9,14.0,32.4,1016.0,3.3,813.0,2.9,8.0,True,False,False,False,6,15,Zaporozhye,2024-07-07,04:49:14,20:39:10,Запорізька,1,46.35,1.0,1.0,1.0,0.0,12.0,1,0,4.0,2.0,0,0.770007,0.086930,-0.029850,0.051252,-0.218287,0.142768,0.092372,-0.154565,0.012636,0.058775,-0.162422,-0.217104,0.036700,0.020123,0.023397,-0.077085,-0.017963,-0.057027,-0.033913,0.122626,0.023124,-0.011740,0.005931,0.056562,-0.004705,0.022403,-0.022423,-0.014863,0.000130,-0.039388,-0.025938,-0.017342,-0.053176,0.047552,0.023440,0.021804,-0.027125,0.001935,0.015062,0.010767,0.009386,-0.008213,0.037192,0.022668,0.051128,0.027824,0.012863,0.026706,-0.026520,0.028072,0.052804,-0.016928,-0.009324,0.000003,0.005072,-0.039894,0.011055,0.009016,0.008323,-0.020394,-0.003490,-0.008427,-0.010480,-0.048324,-0.004581,0.021595,0.011138,-0.010104,0.022494,-0.021609,-0.041807,-0.001962,-0.011483,0.022930,0.011320,0.008058,0.026742,-0.009352,0.019028,-0.036924,0.015263,0.008037,0.046431,-0.007240,-0.000743,0.016807,-0.039669,-0.016503,0.005483,-0.008560,-0.014220,-0.030135,0.003777,-0.001949,-0.030580,-0.007648,-0.011552,-0.022449,-0.000803,-0.026950,0.002773,0.039583,0.001525,-0.010736,-0.006594,-0.020414,-0.002996,0.013809,0.009609,-0.004352,0.002317,-0.010102,0.015824,-0.041053,0.009314,-0.024668,0.012756,-0.008255,0.009669,-0.009465,-0.008667,-0.019673,0.021237,-0.012705,-0.001146,0.007607,0.019860,0.033841,0.023002,-0.005722,-0.020690,0.014757,-0.033301,0.005915,-0.014379,0.002714,0.001342,0.001562,0.011399,0.009957,-0.032826,-0.012016,0.018420,0.014723,0.026897,0.019331,0.005619,0.013108,0.022536,-0.001451,4.613464,0.069903,0.770007,0.030756,0.183048,4.577434,4.163832
40448,2022-09-13 13:00:00,3,9.8,0.182,100.0,4.17,0.56,13.0,13.0,82.00,10.0,0.0,0.0,0.0,0.0,21.6,11.2,301.5,1012.0,99.1,243.0,0.9,2.0,False,True,False,False,1,13,Lutsk,2022-09-13,06:50:39,19:37:45,Волинська,0,0.00,0.0,0.0,0.0,0.0,0.0,0,0,0.0,0.0,40,0.722903,-0.242497,0.006866,-0.058876,-0.005859,0.020462,-0.013710,0.044653,0.001523,-0.058614,-0.001138,0.028278,0.158948,0.043674,-0.091599,0.169784,-0.077430,0.044255,0.070742,0.008073,0.037552,0.095419,-0.015051,0.084739,0.059726,-0.040706,0.049986,0.081680,0.076636,0.081218,-0.050189,-0.051504,0.005605,0.038043,0.018138,-0.030560,-0.014511,-0.038694,0.026750,-0.016792,-0.012843,0.094668,0.068754,0.083852,0.012579,0.031365,0.054277,-0.046638,-0.038550,-0.077310,-0.047039,0.028470,0.008283,0.015732,-0.065116,-0.043876,0.025481,-0.013147,0.069425,-0.003062,0.026914,-0.010857,0.029315,0.000243,0.010037,0.035321,-0.040373,0.029488,-0.012073,-0.011181,-0.026887,-0.025947,0.029903,-0.032162,-0.034801,-0.000972,0.019280,-0.000457,-0.014024,0.037198,0.066062,-0.026550,-0.022958,-0.031893,-0.007914,-0.007766,-0.018184,-0.013985,0.054407,0.014364,0.011743,0.022725,0.029817,0.012866,0.008719,-0.012421,-0.029555,-0.011617,-0.052710,-0.019072,-0.005050,0.024657,-0.016400,-0.009478,-0.022513,-0.043414,-0.039791,0.008600,0.017368,0.041652,-0.042685,-0.008109,-0.032694,0.027601,0.013515,-0.044626,-0.001311,-0.034528,-0.001336,-0.024008,-0.001609,0.007672,0.064633,-0.019922,-0.060614,-0.023218,-0.000550,0.000040,-0.034473,0.022722,0.018579,-0.047907,0.018170,-0.008841,-0.004816,0.053553,0.005552,-0.026080,-0.056662,-0.011467,-0.009479,0.002307,-0.029184,-0.007971,0.000798,0.001195,0.042772,-0.012609,-0.016983,-0.035468,5.631793,0.065106,0.722903,0.037545,0.272076,5.522274,4.407911
323213,2023-07-09 18:00:00,11,14.2,6.400,100.0,20.83,0.71,23.9,23.9,50.16,12.9,0.0,0.0,0.0,0.0,54.0,25.2,350.0,1011.3,80.0,369.8,1.3,4.0,False,True,False,False,6,18,Kropyvnytskyi,2023-07-09,04:58:53,20:53:01,Кіровоградська,0,0.00,0.0,0.0,0.0,0.0,0.0,1,0,0.0,0.0,35,0.757472,-0.190904,-0.082160,-0.070162,-0.102810,0.136103,0.041712,0.004644,-0.114075,0.140692,-0.016433,-0.164305,-0.017836,0.031354,0.058655,-0.062873,0.050603,-0.035414,0.037352,-0.036892,0.075257,0.046625,0.064085,0.040564,0.025597,-0.017306,-0.020494,0.002683,-0.057653,-0.026612,-0.001527,0.013844,0.071547,-0.030621,-0.071749,-0.003923,0.016190,-0.000206,-0.010635,-0.027366,-0.022992,-0.014417,0.014184,-0.052489,-0.047701,0.088052,-0.083790,0.022660,0.005732,0.026810,-0.087083,0.006606,0.060179,-0.036583,-0.015251,-0.013117,0.085451,-0.011840,0.064184,0.017505,0.013067,0.009990,0.042740,0.030060,-0.030688,0.037247,0.048850,-0.043123,0.002581,-0.015748,0.000019,-0.025607,0.002932,0.023739,0.032460,-0.015875,0.005147,0.028033,-0.012145,-0.029979,-0.009452,-0.026513,-0.002300,-0.035212,-0.019568,0.013668,0.015353,-0.007822,0.014023,-0.010921,-0.006090,-0.002799,-0.002939,0.031333,0.028499,0.024661,0.000768,0.003662,-0.001406,0.040073,0.016114,-0.042707,-0.003927,0.006006,-0.012160,-0.017162,0.016907,0.012209,0.009491,-0.000941,0.008530,0.018561,-0.022457,-0.002250,0.000078,-0.006901,-0.001810,-0.005324,-0.000659,0.009959,-0.000348,-0.019085,-0.026727,-0.007785,0.001857,0.000738,0.008176,0.018206,-0.015224,-0.012569,0.022845,-0.029467,-0.004890,-0.012953,-0.005271,0.007877,0.006801,-0.005262,-0.003677,0.005025,0.003936,-0.025944,0.028461,-0.007636,0.005120,0.031729,-0.005871,-0.049206,0.007773,0.036536,4.931804,0.067567,0.757472,0.032879,-0.381064,4.995859,4.239925
336221,2025-01-01 19:00:00,11,-0.5,0.000,0.0,0.00,0.05,2.2,-2.1,81.72,-0.6,0.0,0.0,0.0,0.0,26.3,16.9,237.2,1021.0,38.2,0.0,0.0,0.0,False,True,False,False,2,19,Kropyvnytskyi,2025-01-01,07:43:03,16:06:25,Кіровоградська,0,0.00,0.0,0.0,0.0,1.0,11.0,0,0,7.0,2.0,3,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-4.117675,0.858552,-0.000000
729951,2025-04-06 02:00:00,23,0.7,8.500,100.0,75.00,0.27,4.6,0.8,86.24,2.5,0.9,100.0,0.0,0.0,33.5,17.6,323.0,999.0,99.4,0.0,0.0,0.0,False,False,True,False,6,2,Cherkasy,2025-04-06,06:18:15,19:31:03,Черкаська,1,60.00,1.0,0.0,0.0,0.0,3.0,1,1,23.0,4.0,0,0.777720,0.161607,0.029870,0.192531,-0.038566,-0.108975,-0.014185,-0.074301,-0.061939,-0.013984,0.260092,-0.078917,-0.045949,0.054802,0.059874,-0.024610,-0.159488,0.067847,0.009993,0.031589,0.028731,-0.113231,0.007466,0.018314,0.009086,0.083034,-0.027464,0.056061,0.020892,-0.047364,0.004020,0.029858,0.021130,0.012823,0.000702,0.015391,-0.036214,0.045798,0.069465,0.035651,-0.013704,-0.020323,0.027819,0.025688,0.002247,0.003944,-0.004916,0.009662,0.024356,0.012497,-0.028462,0.034486,-0.004930,0.010378,0.025322,-0.033264,-0.029793,0.056911,-0.022976,0.010114,-0.026435,0.043537,0.001966,0.004107,-0.013619,-0.040352,-0.014151,0.032575,-0.027520,-0.022489,-0.047631,0.020551,0.000838,-0.012260,0.079537,-0.020946,-0.022825,-0.038697,-0.022375,0.044644,-0.023669,-0.019161,-0.017156,-0.001697,-0.014469,-0.017301,0.010840,-0.005014,-0.009154,0.012297,-0.015123,0.030280,0.030140,0.032687,-0.007207,-0.011951,0.005824,-0.006033,0.011083,-0.036399,-0.028195,0.002389,0.047249,0.016643,0.040442,-0.012124,0.032771,-0.014140,-0.002451,0.012877,0.007350,0.014878,-0.014087,0.006719,-0.019047,-0.012703,-0.013010,-0.014074,-0.014655,0.010268,-0.000579,-0.004499,0.003293,-0.009288,-0.009669,0.013161,0.005795,0.040901,-0.009857,0.005236,0.005820,-0.012122,-0.021123,-0.019586,-0.003851,-0.016021,0.011895,0.000021,0.004700,0.001910,-0.026911,-0.002506,-0.009214,0.004549,-0.013456,-0.001758,-0.011412,-0.016514,-0.008775,-0.013189,4.849557,0.070550,0.777720,0.032330,0.429555,4.468007,4.211184
574741,2023-10-18 06:00:00,19,0.6,0.000,0.0,0.00,0.13,3.4,3.4,89.90,1.9,0.0,0.0,0.0,0.0,10.4,0.0,191.4,1020.9,80.0,0.0,0.0,0.0,False,True,False,False,2,6,Ternopil,2023-10-18,07:42:56,18:22:03,Тернопільська,0,0.00,0.0,0.0,0.0,0.0,0.0,0,1,0.0,0.0,48,0.803842,-0.092826,-0.080547,-0.195590,-0.057188,-0.164259,-0.189873,-0.058845,-0.124935,-0.078645,-0.098286,-0.018502,-0.080562,-0.032881,0.015787,-0.122418,0.020459,0.079505,0.088377,-0.036824,-0.010601,-0.030777,-0.032769,0.010569,0.024168,-0.002573,0.008187,-0.030475,0.016844,0.001656,-0.038033,-0.020475,0.007769,0.010142,0.046212,-0.014109,0.002434,0.027978,0.014159,0.014236,0.013847,0.031870,0.018397,-0.008711,0.009452,0.005756,-0.005785,-0.021893,0.028230,0.001550,0.035236,-0.018829,0.001815,0.000493,-0.005402,-0.006335,-0.002853,-0.032913,0.012277,-0.010604,-0.005458,-0.005668,0.009910,-0.006451,-0.032158,-0.019795,0.022356,-0.030460,0.000200,0.011171,-0.006059,-0.002369,-0.003241,-0.020790,-0.004579,-0.023557,-0.010145,-0.028068,0.004200,-0.011961,0.000565,-0.022106,0.008037,-0.011263,-0.044406,0.003145,-0.002152,0.004814,-0.004453,-0.008080,-0.022912,-0.014020,0.005199,-0.007916,-0.007407,-0.001294,0.002103,0.006572,-0.006507,-0.015403,0.002814,0.011391,-0.005340,0.010016,0.014687,0.020054,-0.002844,0.008026,-0.012335,0.016296,0.020400,-0.012349,0.017750,-0.006373,-0.000118,0.031509,-0.004316,-0.015522,0.034336,0.010374,-0.000644,-0.022748,-0.004967,-0.007848,-0.008589,-0.006757,0.009350,0.013571,-0.016882,-0.022066,-0.007881,0.046155,-0.003102,-0.029107,-0.013656,0.012626,0.021656,0.013577,0.002615,0.030004,0.001304,-0.021830,-0.015126,-0.017356,0.009519,-0.023140,-0.004128,-0.002474,-0.048174,0.011236,4.238449,0.071453,0.803842,0.028256,-0.929171,4.729818,4.045281
788485,2023-10-27 06:00:00,25,9.6,4.000,100.0,4.17,0.45,10.9,10.9,96.73,10.4,0.0,0.0,0.0,0.0,26.6,14.4,220.0,997.0,100.0,0.0,0.0,0.0,False,True,False,False,4,6,Chernihiv,2023-10-27,07:38:45,17:37:56,Чернігівська,0,0.00,0.0,0.0,0.0,0.0,0.0,0,1,2.0,0.0,41,0.767071,-0.051937,-0.092930,-0.204765,-0.066695,-0.187556,-0.223545,-0.088682,-0.137743,-0.091674,-0.114780,-0.031111,-0.108891,-0.051090,0.038640,-0.152864,0.033053,0.102556,0.027696,-0.077863,-0.047455,-0.009647,-0.049739,-0.051338,0.016199,0.010100,-0.003921,-0.102851,0.042010,-0.038008,-0.022537,-0.020289,-0.032535,0.000548,0.028421,-0.020787,0.026282,-0.032686,-0.011707,-0.002475,0.020695,0.015169,0.018040,0.008908,0.003318,0.012005,-0.016323,0.015304,0.011620,-0.007629,0.018117,0.009049,0.016980,-0.016007,0.019147,0.006983,0.012819,0.013340,0.001121,0.017903,0.000552,-0.037041,-0.019572,0.017045,-0.007941,-0.039994,-0.005817,0.005170,-0.008925,0.025865,-0.024865,-0.003982,-0.029472,0.005474,-0.005730,-0.007050,-0.010036,-0.024136,0.014978,-0.015584,-0.014493,-0.030991,-0.001564,-0.009810,0.009071,-0.022305,-0.004563,0.017067,0.030289,-0.035627,-0.030772,0.002555,0.019529,0.017579,-0.001205,-0.023054,0.000911,0.015839,0.006872,0.017662,0.023235,0.022845,-0.006046,-0.027254,0.014561,0.010807,0.030355,-0.011291,-0.010199,0.001483,0.008237,-0.007073,0.004592,0.004997,0.001918,0.013058,0.021800,0.007556,0.007765,-0.002163,0.000082,0.015079,0.019737,0.005924,0.012385,-0.005823,-0.026231,0.003289,-0.002826,0.014165,0.001485,0.017475,0.009542,-0.000420,0.028303,-0.010757,0.012457,-0.012379,0.031780,0.020234,0.001992,0.006670,-0.026961,0.024286,-0.001900,-0.003577,0.027034,0.016747,-0.007399,-0.019282,4.725599,0.070782,0.767071,0.031504,0.059342,4.681921,4.131453
328061,2024-01-27 18:00:00,11,0.3,0.600,100.0,8.33,0.55,1.0,-2.3,97.86,0.7,0.0,0.0,0.0,1.8,17.3,10.4,336.0,1019.0,99.2,0.0,0.0,0.0,False,True,False,False,5,18,Kropyvnytskyi,2024-01-27,07:27:16,16:40:29,Кіровоградська,0,0.00,0.0,0.0,0.0,0.0,3.0,1,0,0.0,0.0,19,0.719599,0.015621,-0.260155,0.125581,0.202298,0.173226,-0.098213,-0.127423,0.082649,-0.047071,-0.027690,-0.009836,0.012103,-0.008987,-0.121700,-0.017373,0.090457,0.036364,-0.013458,-0.099843,-0.024240,0.108196,-0.026265,-0.073113,0.017215,0.007476,0.094907,-0.058139,0.020014,0.067579,0.008284,-0.006729,0.028160,-0.031793,0.010490,-0.076290,-0.022562,0.097058,-0.004264,-0.003184,-0.007900,-0.049723,-0.040711,-0.007479,-0.020300,0.066841,0.033526,0.002538,-0.016586,0.005278,0.028404,0.044127,-0.039494,0.003113,0.017237,-0.003495,-0.008164,0.012152,-0.012766,-0.066022,-0.049573,-0.014999,0.004219,0.040111,-0.021458,-0.003836,0.022044,0.035622,-0.002866,0.023276,-0.014963,0.017579,0.002080,-0.008052,0.021562,-0.040781,0.032523,0.029088,0.018280,-0.022483,0.001675,-0.015998,0.025350,0.021791,-0.017651,-0.021754,-0.008680,0.010087,0.006907,0.006491,-0.007421,-0.006448,0.022201,0.001369,-0.031376,-0.041537,0.019715,0.022004,0.028214,-0.012976,-0.010752,0.017185,-0.002009,-0.010185,-0.003410,0.001244,0.010764,-0.041479,-0.026972,-0.029138,0.001613,-0.021182,0.020570,0.035133,-0.017729,-0.022206,-0.008523,0.020579,0.001655,-0.001457,-0.017865,0.007278,0.019368,-0.018848,0.022576,0.027764,0.000068,0.012412,0.008455,0.014835,-0.014053,-0.013452,-0.009823,0.013956,-0.022106,0.054190,-0.012445,-0.019500,0.013746,0.022118,-0.039441,0.013249,-0.042428,-0.007292,0.034001,-0.005542,-0.015707,0.019757,0.036775,0.003895,5.183232,0.067571,0.719599,0.034555,0.310142,5.109690,4.269031

### TELEGRAM MERGE

In [39]:
df_tg_matrix = pd.read_csv("../data/telegram_processed_svd.csv")

In [40]:
df_tg_matrix.head()

,date,channel,tg_topic_0,tg_topic_1,tg_topic_2,tg_topic_3,tg_topic_4,tg_topic_5,tg_topic_6,tg_topic_7,tg_topic_8,tg_topic_9,tg_topic_10,tg_topic_11,tg_topic_12,tg_topic_13,tg_topic_14,tg_topic_15,tg_topic_16,tg_topic_17,tg_topic_18,tg_topic_19,tg_topic_20,tg_topic_21,tg_topic_22,tg_topic_23,tg_topic_24,tg_topic_25,tg_topic_26,tg_topic_27,tg_topic_28,tg_topic_29,tg_topic_30,tg_topic_31,tg_topic_32,tg_topic_33,tg_topic_34,tg_topic_35,tg_topic_36,tg_topic_37,tg_topic_38,tg_topic_39,tg_topic_40,tg_topic_41,tg_topic_42,tg_topic_43,tg_topic_44,tg_topic_45,tg_topic_46,tg_topic_47,tg_topic_48,tg_topic_49,tg_topic_50,tg_topic_51,tg_topic_52,tg_topic_53,tg_topic_54,tg_topic_55,tg_topic_56,tg_topic_57,tg_topic_58,tg_topic_59,tg_topic_60,tg_topic_61,tg_topic_62,tg_topic_63,tg_topic_64,tg_topic_65,tg_topic_66,tg_topic_67,tg_topic_68,tg_topic_69,tg_topic_70,tg_topic_71,tg_topic_72,tg_topic_73,tg_topic_74,tg_topic_75,tg_topic_76,tg_topic_77,tg_topic_78,tg_topic_79,tg_topic_80,tg_topic_81,tg_topic_82,tg_topic_83,tg_topic_84,tg_topic_85,tg_topic_86,tg_topic_87,tg_topic_88,tg_topic_89,tg_topic_90,tg_topic_91,tg_topic_92,tg_topic_93,tg_topic_94,tg_topic_95,tg_topic_96,tg_topic_97,tg_topic_98,tg_topic_99,tg_topic_100,tg_topic_101,tg_topic_102,tg_topic_103,tg_topic_104,tg_topic_105,tg_topic_106,tg_topic_107,tg_topic_108,tg_topic_109,tg_topic_110,tg_topic_111,tg_topic_112,tg_topic_113,tg_topic_114,tg_topic_115,tg_topic_116,tg_topic_117,tg_topic_118,tg_topic_119,tg_topic_120,tg_topic_121,tg_topic_122,tg_topic_123,tg_topic_124,tg_topic_125,tg_topic_126,tg_topic_127,tg_topic_128,tg_topic_129,tg_topic_130,tg_topic_131,tg_topic_132,tg_topic_133,tg_topic_134,tg_topic_135,tg_topic_136,tg_topic_137,tg_topic_138,tg_topic_139,tg_topic_140,tg_topic_141,tg_topic_142,tg_topic_143,tg_topic_144,tg_topic_145,tg_topic_146,tg_topic_147,tg_topic_148,tg_topic_149,tg_topic_150,tg_topic_151,tg_topic_152,tg_topic_153,tg_topic_154,tg_topic_155,tg_topic_156,tg_topic_157,tg_topic_158,tg_topic_159,tg_topic_160,tg_topic_161,tg_topic_162,tg_topic_163,tg_topic_164,tg_topic_165,tg_topic_166,tg_topic_167,tg_topic_168,tg_topic_169,tg_topic_170,tg_topic_171,tg_topic_172,tg_topic_173,tg_topic_174,tg_topic_175,tg_topic_176,tg_topic_177,tg_topic_178,tg_topic_179,tg_topic_180,tg_topic_181,tg_topic_182,tg_topic_183,tg_topic_184,tg_topic_185,tg_topic_186,tg_topic_187,tg_topic_188,tg_topic_189,tg_topic_190,tg_topic_191,tg_topic_192,tg_topic_193,tg_topic_194,tg_topic_195,tg_topic_196,tg_topic_197,tg_topic_198,tg_topic_199,tg_topic_200,tg_topic_201,tg_topic_202,tg_topic_203,tg_topic_204,tg_topic_205,tg_topic_206,tg_topic_207,tg_topic_208,tg_topic_209,tg_topic_210,tg_topic_211,tg_topic_212,tg_topic_213,tg_topic_214,tg_topic_215,tg_topic_216,tg_topic_217,tg_topic_218,tg_topic_219,tg_topic_220,tg_topic_221,tg_topic_222,tg_topic_223,tg_topic_224,tg_topic_225,tg_topic_226,tg_topic_227,tg_topic_228,tg_topic_229,tg_topic_230,tg_topic_231,tg_topic_232,tg_topic_233,tg_topic_234,tg_topic_235,tg_topic_236,tg_topic_237,tg_topic_238,tg_topic_239,tg_topic_240,tg_topic_241,tg_topic_242,tg_topic_243,tg_topic_244,tg_topic_245,tg_topic_246,tg_topic_247,tg_topic_248,tg_topic_249
0,2026-03-06 13:06:58,DeepStateUA,0.006988,0.000199,0.019066,0.000954,-0.008573,0.027555,-0.023391,0.082142,0.048557,-0.035440,-0.044857,0.023973,-0.010295,0.314186,0.441313,0.148148,-0.033453,0.013616,-0.015178,0.300137,-0.013802,0.024118,0.032728,-0.075552,-0.055436,0.056107,-0.114964,-0.062816,0.000904,0.040613,0.030641,-0.011243,-0.031934,-0.016560,-0.000001,-0.009350,-0.013027,0.023568,-0.014856,-0.013250,0.003955,0.006923,0.018694,-0.040851,-0.016602,-0.022611,0.020255,-0.044764,-0.014433,-0.000230,-0.005441,-0.015143,0.000333,0.033882,-0.001488,0.004348,0.028966,0.024959,-0.010554,-0.007216,-0.016782,-0.017824,-0.004213,-0.016672,-0.025594,0.012135,0.018105,-0.023220,0.009999,0.012852,-0.056985,-0.036515,-0.008792,-0.007234,-0.026848,-0.062293,0.085060,0.036042,-0.086716,-0.011956,-0.004898,0.141366,-0.055466,-0.088688,0.061815,0.057730,0.016840,-0.002449,0.000985,-0.015949,-0.059070,-0.003214,0.027277,-0.060307,-0.006571,0.040405,-0.027011,0.030307,0.029944,-0.074698,-0.003246,0.014907,0.033488,-0.037240,-0.000254,-0.023585,0.003416,-0.019977,-0.013568,-0.016645,-0.000286,0.008311,-0.014775,-0.005559,-0.015832,-0.004287,-0.005642,0.019342,0.001947,-0.019377,-0.004330,-0.017837,-0.021871,-0.024705,-0.017573,-0.001472,0.055299,-0.001903,-0.015556,0.010957,0.008829,0.013609,-0.038590,0.020824,-0.034754,0.032417,-0.015662,0.027220,0.082186,-0.008328,-0.017706,-0.003848,0.011998,-0.018755,0.032181,0.001489,-0.003755,0.006359,0.029443,0.043361,0.021388,-0.067447,-0.023474,-0.022019,0.022576,0.027941,-0.032890,-0.001851,-0.000252,0.033536,-0.027417,0.039129,-0.011637,-0.036006,-0.007872,0.002064,-0.007389,-0.011695,-0.019128,0.007078,0.013907,0.019934,0.014856,0.020196,-0.025725,0.013732,0.067211,-0.018237,-0.015207,-0.034795,-0.037587,-0.005869,-0.019109,-0.039292,0.006822,-0.001080,0.007132,-0.030108,-0.002523,0.020054,-0.002851,-0.020187,-0.032920,0.020520,-0.008675,-0.005489,0.004209,-0.023765,0.017471,0.002919,-0.007788,-0.011782,0.016704,0.016441,-0.021023,0.001152,-0.001316,-0.018605,-0.003998,-0.010896,0.008553,0.018630,0.011477,0.000386,0.000532,-0.002162,0.010066,-0.002241,0.032521,0.011660,-0.014818,0.011373,-0.015453,-0.008815,-0.010049,0.005701,-0.001860,-0.001877,0.032768,-0.012209,0.004888,0.020140,0.009989,0.017622,0.025116,-0.001460,-0.027003,-0.020394,0.029014,0.040200,-0.025010,-0.009210,0.002963,0.010881,-0.004524,-0.032907,-0.024614,0.001823,0.028596,0.021748
1,2026-03-06 12:57:29,DeepStateUA,0.022407,-0.001962,0.039639,0.001378,-0.027803,0.069328,-0.037689,0.126188,0.023940,-0.028037,-0.035619,0.015228,-0.008888,0.052549,0.052510,-0.028265,-0.017459,-0.048919,-0.000002,-0.004600,0.007378,-0.006131,0.044293,-0.004127,-0.012952,-0.023969,0.033698,0.023532,0.003563,-0.007249,0.049355,-0.024524,-0.027906,0.009351,-0.011559,-0.014335,0.024924,0.011433,-0.000501,0.001053,-0.016656,-0.025999,0.002606,0.049670,-0.012654,0.022713,-0.043216,0.038906,-0.038572,-0.015364,0.052192,0.007416,-0.017437,0.032346,-0.017844,-0.017607,0.016605,-0.004603,0.007639,0.034544,-0.015709,0.016759,0.003032,-0.022000,0.023525,-0.039551,-0.022953,-0.005678,-0.006245,0.026950,0.017354,0.035258,0.004186,-0.003158,0.000993,0.005015,-0.002274,0.005244,0.005333,-0.013808,0.000107,-0.012621,0.017583,-0.008419,-0.008566,-0.044011,-0.008986,0.009480,-0.019269,0.001166,-0.009918,-0.001627,-0.017014,0.029735,-0.029830,-0.013649,0.007678,-0.001438,0.001700,-0.031980,-0.018274,-0.026328,0.011910,-0.021965,0.018630,0.003590,0.005359,-0.087143,0.011642,0.029459,0.038763,-0.016025,0.000355,-0.003981,-0.005369,0.013387,-0.004440,-0.000836,-0.005716,0.014559,-0.008708,0.006655,0.006114,0.017460,-0.006043,-0.022052,-0.020510,0.003933,0.016616,-0.009529,-0.020628,-0.011706,-0.022555,-0.026535,0.056622,-0.025933,-0.008077,-0.000318,-0.052970,0.027302,-0.009042,-0.008970,-0.010959,0.035780,0.031761,-0.015721,0.000368,0.020273,0.011313,-0.016592,0.016288,0.032706,-0.024469,0.013322,-0.003262,0.004794,0.003132,0.006254,-0.008577,-0.001997,-0.014584,-0.015129,-0.026315,-0.022377,-0.006290,-0.042899,0.027561,-0.030112,0.048342,0.012373,-0.013031,0.012919,-0.051104,-0.008474,-0.021121,-0.041249,-0.010103,-0.014892,-0.020265,0.020357,-0.041117,0.055916,0.013355,-0.034619,-0.059931,-0.018448,0.033353,-0.059874,-0.008030,0.015561,-0.006351,0.022683,-0.030349,-0.035098,0.017985,-0.006712,0.033118,-0.085218,0.046445,0.054191,0.068605,-0.022177,0.008913,0.082670,-0.008593,0.008451,-0.028321,-0.026067,0.013130,0.004902,0.013437,0.033820,-0.007049,-0.060058,0.024515,0.009594,-0.081896,0.017468,-0.047242,0.005291,0.068628,0.007056,-0.025127,0.006486,0.030336,-0.050305,0.010195,0.011570,0.026577,0.037405,-0.009934,0.035270,-0.000135,-0.015283,0.000304,-0.033954,0.013224,0.033420,0.008937,0.017547,0.027843,-0.004694,0.021460,-0.012477,-0.023853,-0.001170,-0.009580,-0.020032,-0.016587,0.012829
2,2026-03-06 08:32:47,DeepStateUA,0.009207,-0.000980,0.027773,0.003815,-0.016143,0.044874,-0.036316,0.114618,0.018318,-0.029455,-0.061089,0.011554,-0.017066,-0.012750,0.046438,0.002240,-0.008364,-0.031490,-0.034225,0.021600,0.025354,0.012989,-0.016711,-0.005652,-0.000940,0.004435,-0.026056,-0.002133,0.009171,0.013860,0.001250,-0.008481,0.006147,0.007172,-0.001211,-0.000019,-0.002802,-0.003287,0.009267,-0.004910,-0.003997,-0.016448,-0.001282,0.016932,0.007769,0.000162,-0.003869,-0.003458,-0.021086,0.004215,0.005328,-0.027756,-0.038482,0.028505,-0.006878,0.003910,-0.003042,-0.018648,-0.003555,0.001712,-0.001450,0.004726,-0.007310,0.006116,-0.008207,-0.001980,0.006809,-0.008187,-0.011355,0.031342,-0.017843,0.019879,0.014570,-0.014654,-0.044019,-0.019220,0.017996,-0.000225,-0.022663,0.003560,0.024625,-0.033276,0.008231,0.028736,0.019367,0.013745,-0.002683,-0.001753,0.010490,-0.019671,0.008335,0.004611,0.007201,0.033003,0.006705,-0.031089,-0.000850,0.019676,0.014343,-0.033543,-0.040100,-0.016089,-0.021698,-0.000217,0.008069,-0.010423,-0.007300,-0.024042,0.005015,-0.006406,0.022364,-0.016317,0.022815,0.025304,0.020725,0.012295,0.002634,0.009039,-0.017906,0.009439,-0.010084,0.032144,-0.017489,0.045213,-0.007165,-0.024685,0.001219,0.017809,-0.023696,0.000947,0.011792,0.010850,0.036833,0.004700,0.030137,-0.036761,-0.015026,-0.015174,-0.058549,0.012580,0.007102,0.015909,0.002080,0.004369,0.045627,-0.003952,-0.022525,0.006335,0.010368,-0.001270,-0.010937,-0.049170,-0.023460,0.000338,-0.031371,0.016503,-0.012089,0.039702,-0.009027,-0.043528,0.016736,0.004246,-0.003805,-0.004715,-0.013558,-0.000750,0.030282,0.007177,0.011529,-0.004391,-0.020481,0.022266,-0.054567,0.033857,0.006121,0.005828,0.032057,-0.017976,-0.023840,-0.003578,-0.027381,-0.022436,0.012264,-0.019206,-0.003325,-0.006892,0.007634,-0.004763,0.008151,0.003102,-0.009821,0.023551,-0.010474,0.022000,0.026389,0.011537,-0.026863,-0.016042,-0.006907,0.005188,-0.013523,-0.046201,0.019915,0.007582,0.016845,0.007917,0.001214,-0.012764,0.026748,-0.017207,0.039371,0.025085,0.013642,0.004250,0.010080,0.001055,0.023545,0.001470,0.009214,0.022693,-0.005097,-0.001313,-0.020567,0.019687,0.029591,-0.018218,0.049065,0.001587,-0.006777,0.015120,-0.011917,0.010657,-0.026841,-0.027324,0.024679,0.047434,-0.033187,-0.008394,0.010494,-0.011802,0.010305,-0.002259,0.038323,-0.006857,0.000943,-0.010578,-0.007479,-0.013278,-0.020446,0.037237
3,2026-03-05 16:46:58,DeepStateUA,0.006730,0.000369,0.018262,0.000836,-0.008774,0.027116,-0.022959,0.080319,0.048234,-0.034813,-0.045849,0.022738,-0.009713,0.309644,0.438196,0.146174,-0.033863,0.013235,-0.015803,0.297928,-0.013456,0.024753,0.033258,-0.075049,-0.055813,0.057353,-0.116678,-0.062500,0.000718,0.040400,0.030313,-0.013032,-0.032609,-0.017691,0.000159,-0.008193,-0.009915,0.024541,-0.012840,-0.013136,0.003457,0.005493,0.019286,-0.037760,-0.016446,-0.022256,0.017909,-0.041597,-0.012891,-0.000280,-0.005204,-0.015119,0.001041,0.033324,-0.000904,0.003041,0.027553,0.023323,-0.009145,-0.007351,-0.016475,-0.016810,-0.003328,-0.014595,-0.022927,0.007267,0.018860,-0.021800,0.009130,0.012072,-0.053230,-0.032769,-0.008438,-0.006633,-0.022763,-0.056280,0.078936,0.032010,-0.078151,-0.009682,-0.002629,0.133985,-0.052904,-0.084579,0.060615,0.053592,0.015893,-0.001841,0.001716,-0.015658,-0.055644,-0.001325,0.021125,-0.053712,-0.006979,0.036450,-0.027121,0.029705,0.027946,-0.068235,-0.003609,0.013171,0.034101,-0.030720,0.000881,-0.026276,-0.001736,-0.020847,-0.019344,-0.009823,0.002972,0.006247,-0.014389,-0.006934,-0.018915,-0.002400,-0.005911,0.019148,0.001120,-0.020964,-0.004639,-0.017239,-0.020584,-0.024811,-0.010215,-0.007846,0.055711,0.000035,-0.014508,0.011382,0.009537,0.012127,-0.038330,0.021539,-0.031461,0.033549,-0.014398,0.025901,0.078348,-0.010072,-0.018390,-0.003523,0.012972,-0.017914,0.033514,0.002874,-0.005511,0.002857,0.026880,0.044138,0.018543,-0.066708,-0.023418,-0.020027,0.020840,0.023301,-0.032703,-0.002422,0.000113,0.030761,-0.028155,0.036588,-0.010908,-0.038256,-0.007882,0.000361,-0.009495,-0.011750,-0.012554,0.002863,0.013041,0.016275,0.012648,0.016132,-0.026770,0.009312,0.057960,-0.012964,-0.013864,-0.029401,-0.035812,-0.002513,-0.015276,-0.034533,0.005844,-0.001694,0.003622,-0.027561,-0.000588,0.021415,-0.004247,-0.015327,-0.027034,0.018165,-0.007450,-0.003131,0.001438,-0.021702,0.013110,0.002678,-0.007512,-0.012194,0.014093,0.013775,-0.015105,-0.000609,0.000011,-0.015561,-0.005320,-0.005557,0.005562,0.016873,0.006082,-0.002208,-0.004107,-0.002010,0.009410,0.002032,0.028864,0.015535,-0.011462,0.004802,-0.014629,-0.007260,-0.007657,0.005782,-0.000784,0.001769,0.025649,-0.014303,-0.004693,0.015168,0.010415,0.015075,0.013582,-0.003469,-0.020816,-0.016733,0.013027,0.029355,-0.027494,-0.010488,-0.002657,0.008813,-0.002380,-0.024928,-0.023059,-0.007300,0.018533,0.018425
4,2026-03-05 15:46:39,DeepStateUA,0.048474,-0.006318,0.074492,-0.003677,-0.020839,0.080790,-0.041054,0.150230,0.063555,-0.043204,0.008690,-0.000347,-0.003948,0.152312,0.096819,0.034472,0.000234,-0.012378,0.004079,-0.045798,0.024286,-0.038902,0.063380,0.019516,0.037086,-0.056330,0.129901,0.108324,0.016540,-0.052420,-0.029516,-0.016280,-0.026797,0.036448,-0.006656,0.032470,0.011474,-0.025498,-0.041208,-0.000548,-0.024440,0.013744,-0.021409,0.056265,0.019822,0.005498,-0.032493,0.020598,0.027337,-0.006096,-0.029304,0.002763,0.007005,-0.016472,0.016137,-0.007199,-0.014718,-0.025963,0.005799,-0.008611,-0.007486,0.027010,0.002104,0.023235,-0.010194,0.007028,-0.004511,0.023883,0.018102,0.006015,-0.000850,-0.009526,0.011164,-0.025278,-0.030647,0.056156,-0.012454,-0.049401,0.059024,0.015464,0.015910,-0.005285,0.008670,-0.014688,0.005626,-0.024439,0.010349,0.017736,0.019146,-0.013128,0.023786,0.014655,-0.019442,0.088970,-0.036350,-0.054979,0.038121,-0.035612,-0.005553,0.010942,-0.022885,-0.071533,0.018372,0.004381,0.052752,0.032290,-0.008342,-0.090515,0.018199,0.066380,0.004269,-0.020578,0.047784,-0.030463,-0.041661,0.037565,0.006622,-0.018215,0.002972,0.017010,0.019653,0.020813,0.021123,0.033048,-0.025844,0.007062,-0.015535,0.011495,0.000960,-0.016812,-0.013719,-0.005454,-0.041389,0.000160,0.017724,0.030464,0.017963,-0.032639,-0.013660,0.010936,0.013186,0.023178,-0.056093,-0.011590,-0.021671,-0.004475,0.038871,-0.004559,0.004582,-0.023562,0.044997,0.065422,0.043786,-0.010457,0.009059,-0.048286,-0.023518,-0.011432,0.017929,0.058257,-0.000254,-0.045754,0.007873,0.019382,-0.006915,0.010458,0.015239,0.017786,-0.008954,0.004618,-0.015154,-0.010725,0.049668,-0.007467,-0.000409,-0.003879,-0.019728,-0.004494,-0.017682,0.039583,-0.001462,-0.011101,-0.005771,0.005899,-0.035796,-0.009256,-0.026692,-0.033233,-0.010023,-0.030311,0.015309,0.018778,-0.000732,0.016525,-0.030803,-0.039326,-0.006236,0.025289,0.014652,-0.013699,-0.009412,-0.004784,-0.022144,0.004702,-0.048493,-0.028913,0.037935,-0.031141,0.006822,0.019647,-0.000942,0.014402,0.003771,0.022732,-0.046648,-0.018938,0.012592,0.022197,-0.009677,0.019232,-0.002493,0.022667,0.032174,-0.013280,0.011676,0.013809,0.032932,0.035071,-0.029565,-0.028411,0.020664,-0.013560,0.009666,0.013115,0.004648,0.048747,-0.018451,0.024594,-0.011803,-0.014144,-0.013906,-0.010699,0.031310,0.009072,-0.003523,-0.034698,-0.039809,0.018241,-0.014541,0.038226

In [41]:
df_tg_matrix["datetime_hour"] = pd.to_datetime(df_tg_matrix["date"]).dt.floor("h")

C:\Users\Uw11\AppData\Local\Temp\ipykernel_33600\2851151304.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_tg_matrix["datetime_hour"] = pd.to_datetime(df_tg_matrix["date"]).dt.floor("h")

In [42]:
topic_cols = [c for c in df_tg_matrix.columns if "tg_topic_" in c]

tg_hourly = (
    df_tg_matrix.groupby("datetime_hour")[topic_cols]
    .mean()
    .sort_index()
    .reset_index()
)

C:\Users\Uw11\AppData\Local\Temp\ipykernel_33600\2188712141.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  .reset_index()

In [43]:
df_tg_matrix.head()

,date,channel,tg_topic_0,tg_topic_1,tg_topic_2,tg_topic_3,tg_topic_4,tg_topic_5,tg_topic_6,tg_topic_7,tg_topic_8,tg_topic_9,tg_topic_10,tg_topic_11,tg_topic_12,tg_topic_13,tg_topic_14,tg_topic_15,tg_topic_16,tg_topic_17,tg_topic_18,tg_topic_19,tg_topic_20,tg_topic_21,tg_topic_22,tg_topic_23,tg_topic_24,tg_topic_25,tg_topic_26,tg_topic_27,tg_topic_28,tg_topic_29,tg_topic_30,tg_topic_31,tg_topic_32,tg_topic_33,tg_topic_34,tg_topic_35,tg_topic_36,tg_topic_37,tg_topic_38,tg_topic_39,tg_topic_40,tg_topic_41,tg_topic_42,tg_topic_43,tg_topic_44,tg_topic_45,tg_topic_46,tg_topic_47,tg_topic_48,tg_topic_49,tg_topic_50,tg_topic_51,tg_topic_52,tg_topic_53,tg_topic_54,tg_topic_55,tg_topic_56,tg_topic_57,tg_topic_58,tg_topic_59,tg_topic_60,tg_topic_61,tg_topic_62,tg_topic_63,tg_topic_64,tg_topic_65,tg_topic_66,tg_topic_67,tg_topic_68,tg_topic_69,tg_topic_70,tg_topic_71,tg_topic_72,tg_topic_73,tg_topic_74,tg_topic_75,tg_topic_76,tg_topic_77,tg_topic_78,tg_topic_79,tg_topic_80,tg_topic_81,tg_topic_82,tg_topic_83,tg_topic_84,tg_topic_85,tg_topic_86,tg_topic_87,tg_topic_88,tg_topic_89,tg_topic_90,tg_topic_91,tg_topic_92,tg_topic_93,tg_topic_94,tg_topic_95,tg_topic_96,tg_topic_97,tg_topic_98,tg_topic_99,tg_topic_100,tg_topic_101,tg_topic_102,tg_topic_103,tg_topic_104,tg_topic_105,tg_topic_106,tg_topic_107,tg_topic_108,tg_topic_109,tg_topic_110,tg_topic_111,tg_topic_112,tg_topic_113,tg_topic_114,tg_topic_115,tg_topic_116,tg_topic_117,tg_topic_118,tg_topic_119,tg_topic_120,tg_topic_121,tg_topic_122,tg_topic_123,tg_topic_124,tg_topic_125,tg_topic_126,tg_topic_127,tg_topic_128,tg_topic_129,tg_topic_130,tg_topic_131,tg_topic_132,tg_topic_133,tg_topic_134,tg_topic_135,tg_topic_136,tg_topic_137,tg_topic_138,tg_topic_139,tg_topic_140,tg_topic_141,tg_topic_142,tg_topic_143,tg_topic_144,tg_topic_145,tg_topic_146,tg_topic_147,tg_topic_148,tg_topic_149,tg_topic_150,tg_topic_151,tg_topic_152,tg_topic_153,tg_topic_154,tg_topic_155,tg_topic_156,tg_topic_157,tg_topic_158,tg_topic_159,tg_topic_160,tg_topic_161,tg_topic_162,tg_topic_163,tg_topic_164,tg_topic_165,tg_topic_166,tg_topic_167,tg_topic_168,tg_topic_169,tg_topic_170,tg_topic_171,tg_topic_172,tg_topic_173,tg_topic_174,tg_topic_175,tg_topic_176,tg_topic_177,tg_topic_178,tg_topic_179,tg_topic_180,tg_topic_181,tg_topic_182,tg_topic_183,tg_topic_184,tg_topic_185,tg_topic_186,tg_topic_187,tg_topic_188,tg_topic_189,tg_topic_190,tg_topic_191,tg_topic_192,tg_topic_193,tg_topic_194,tg_topic_195,tg_topic_196,tg_topic_197,tg_topic_198,tg_topic_199,tg_topic_200,tg_topic_201,tg_topic_202,tg_topic_203,tg_topic_204,tg_topic_205,tg_topic_206,tg_topic_207,tg_topic_208,tg_topic_209,tg_topic_210,tg_topic_211,tg_topic_212,tg_topic_213,tg_topic_214,tg_topic_215,tg_topic_216,tg_topic_217,tg_topic_218,tg_topic_219,tg_topic_220,tg_topic_221,tg_topic_222,tg_topic_223,tg_topic_224,tg_topic_225,tg_topic_226,tg_topic_227,tg_topic_228,tg_topic_229,tg_topic_230,tg_topic_231,tg_topic_232,tg_topic_233,tg_topic_234,tg_topic_235,tg_topic_236,tg_topic_237,tg_topic_238,tg_topic_239,tg_topic_240,tg_topic_241,tg_topic_242,tg_topic_243,tg_topic_244,tg_topic_245,tg_topic_246,tg_topic_247,tg_topic_248,tg_topic_249,datetime_hour
0,2026-03-06 13:06:58,DeepStateUA,0.006988,0.000199,0.019066,0.000954,-0.008573,0.027555,-0.023391,0.082142,0.048557,-0.035440,-0.044857,0.023973,-0.010295,0.314186,0.441313,0.148148,-0.033453,0.013616,-0.015178,0.300137,-0.013802,0.024118,0.032728,-0.075552,-0.055436,0.056107,-0.114964,-0.062816,0.000904,0.040613,0.030641,-0.011243,-0.031934,-0.016560,-0.000001,-0.009350,-0.013027,0.023568,-0.014856,-0.013250,0.003955,0.006923,0.018694,-0.040851,-0.016602,-0.022611,0.020255,-0.044764,-0.014433,-0.000230,-0.005441,-0.015143,0.000333,0.033882,-0.001488,0.004348,0.028966,0.024959,-0.010554,-0.007216,-0.016782,-0.017824,-0.004213,-0.016672,-0.025594,0.012135,0.018105,-0.023220,0.009999,0.012852,-0.056985,-0.036515,-0.008792,-0.007234,-0.026848,-0.062293,0.085060,0.036042,-0.086716,-0.011956,-0.004898,0.141366,-0.055466,-0.088688,0.061815,0.057730,0.016840,-0.002449,0.000985,-0.015949,-0.059070,-0.003214,0.027277,-0.060307,-0.006571,0.040405,-0.027011,0.030307,0.029944,-0.074698,-0.003246,0.014907,0.033488,-0.037240,-0.000254,-0.023585,0.003416,-0.019977,-0.013568,-0.016645,-0.000286,0.008311,-0.014775,-0.005559,-0.015832,-0.004287,-0.005642,0.019342,0.001947,-0.019377,-0.004330,-0.017837,-0.021871,-0.024705,-0.017573,-0.001472,0.055299,-0.001903,-0.015556,0.010957,0.008829,0.013609,-0.038590,0.020824,-0.034754,0.032417,-0.015662,0.027220,0.082186,-0.008328,-0.017706,-0.003848,0.011998,-0.018755,0.032181,0.001489,-0.003755,0.006359,0.029443,0.043361,0.021388,-0.067447,-0.023474,-0.022019,0.022576,0.027941,-0.032890,-0.001851,-0.000252,0.033536,-0.027417,0.039129,-0.011637,-0.036006,-0.007872,0.002064,-0.007389,-0.011695,-0.019128,0.007078,0.013907,0.019934,0.014856,0.020196,-0.025725,0.013732,0.067211,-0.018237,-0.015207,-0.034795,-0.037587,-0.005869,-0.019109,-0.039292,0.006822,-0.001080,0.007132,-0.030108,-0.002523,0.020054,-0.002851,-0.020187,-0.032920,0.020520,-0.008675,-0.005489,0.004209,-0.023765,0.017471,0.002919,-0.007788,-0.011782,0.016704,0.016441,-0.021023,0.001152,-0.001316,-0.018605,-0.003998,-0.010896,0.008553,0.018630,0.011477,0.000386,0.000532,-0.002162,0.010066,-0.002241,0.032521,0.011660,-0.014818,0.011373,-0.015453,-0.008815,-0.010049,0.005701,-0.001860,-0.001877,0.032768,-0.012209,0.004888,0.020140,0.009989,0.017622,0.025116,-0.001460,-0.027003,-0.020394,0.029014,0.040200,-0.025010,-0.009210,0.002963,0.010881,-0.004524,-0.032907,-0.024614,0.001823,0.028596,0.021748,2026-03-06 13:00:00
1,2026-03-06 12:57:29,DeepStateUA,0.022407,-0.001962,0.039639,0.001378,-0.027803,0.069328,-0.037689,0.126188,0.023940,-0.028037,-0.035619,0.015228,-0.008888,0.052549,0.052510,-0.028265,-0.017459,-0.048919,-0.000002,-0.004600,0.007378,-0.006131,0.044293,-0.004127,-0.012952,-0.023969,0.033698,0.023532,0.003563,-0.007249,0.049355,-0.024524,-0.027906,0.009351,-0.011559,-0.014335,0.024924,0.011433,-0.000501,0.001053,-0.016656,-0.025999,0.002606,0.049670,-0.012654,0.022713,-0.043216,0.038906,-0.038572,-0.015364,0.052192,0.007416,-0.017437,0.032346,-0.017844,-0.017607,0.016605,-0.004603,0.007639,0.034544,-0.015709,0.016759,0.003032,-0.022000,0.023525,-0.039551,-0.022953,-0.005678,-0.006245,0.026950,0.017354,0.035258,0.004186,-0.003158,0.000993,0.005015,-0.002274,0.005244,0.005333,-0.013808,0.000107,-0.012621,0.017583,-0.008419,-0.008566,-0.044011,-0.008986,0.009480,-0.019269,0.001166,-0.009918,-0.001627,-0.017014,0.029735,-0.029830,-0.013649,0.007678,-0.001438,0.001700,-0.031980,-0.018274,-0.026328,0.011910,-0.021965,0.018630,0.003590,0.005359,-0.087143,0.011642,0.029459,0.038763,-0.016025,0.000355,-0.003981,-0.005369,0.013387,-0.004440,-0.000836,-0.005716,0.014559,-0.008708,0.006655,0.006114,0.017460,-0.006043,-0.022052,-0.020510,0.003933,0.016616,-0.009529,-0.020628,-0.011706,-0.022555,-0.026535,0.056622,-0.025933,-0.008077,-0.000318,-0.052970,0.027302,-0.009042,-0.008970,-0.010959,0.035780,0.031761,-0.015721,0.000368,0.020273,0.011313,-0.016592,0.016288,0.032706,-0.024469,0.013322,-0.003262,0.004794,0.003132,0.006254,-0.008577,-0.001997,-0.014584,-0.015129,-0.026315,-0.022377,-0.006290,-0.042899,0.027561,-0.030112,0.048342,0.012373,-0.013031,0.012919,-0.051104,-0.008474,-0.021121,-0.041249,-0.010103,-0.014892,-0.020265,0.020357,-0.041117,0.055916,0.013355,-0.034619,-0.059931,-0.018448,0.033353,-0.059874,-0.008030,0.015561,-0.006351,0.022683,-0.030349,-0.035098,0.017985,-0.006712,0.033118,-0.085218,0.046445,0.054191,0.068605,-0.022177,0.008913,0.082670,-0.008593,0.008451,-0.028321,-0.026067,0.013130,0.004902,0.013437,0.033820,-0.007049,-0.060058,0.024515,0.009594,-0.081896,0.017468,-0.047242,0.005291,0.068628,0.007056,-0.025127,0.006486,0.030336,-0.050305,0.010195,0.011570,0.026577,0.037405,-0.009934,0.035270,-0.000135,-0.015283,0.000304,-0.033954,0.013224,0.033420,0.008937,0.017547,0.027843,-0.004694,0.021460,-0.012477,-0.023853,-0.001170,-0.009580,-0.020032,-0.016587,0.012829,2026-03-06 12:00:00
2,2026-03-06 08:32:47,DeepStateUA,0.009207,-0.000980,0.027773,0.003815,-0.016143,0.044874,-0.036316,0.114618,0.018318,-0.029455,-0.061089,0.011554,-0.017066,-0.012750,0.046438,0.002240,-0.008364,-0.031490,-0.034225,0.021600,0.025354,0.012989,-0.016711,-0.005652,-0.000940,0.004435,-0.026056,-0.002133,0.009171,0.013860,0.001250,-0.008481,0.006147,0.007172,-0.001211,-0.000019,-0.002802,-0.003287,0.009267,-0.004910,-0.003997,-0.016448,-0.001282,0.016932,0.007769,0.000162,-0.003869,-0.003458,-0.021086,0.004215,0.005328,-0.027756,-0.038482,0.028505,-0.006878,0.003910,-0.003042,-0.018648,-0.003555,0.001712,-0.001450,0.004726,-0.007310,0.006116,-0.008207,-0.001980,0.006809,-0.008187,-0.011355,0.031342,-0.017843,0.019879,0.014570,-0.014654,-0.044019,-0.019220,0.017996,-0.000225,-0.022663,0.003560,0.024625,-0.033276,0.008231,0.028736,0.019367,0.013745,-0.002683,-0.001753,0.010490,-0.019671,0.008335,0.004611,0.007201,0.033003,0.006705,-0.031089,-0.000850,0.019676,0.014343,-0.033543,-0.040100,-0.016089,-0.021698,-0.000217,0.008069,-0.010423,-0.007300,-0.024042,0.005015,-0.006406,0.022364,-0.016317,0.022815,0.025304,0.020725,0.012295,0.002634,0.009039,-0.017906,0.009439,-0.010084,0.032144,-0.017489,0.045213,-0.007165,-0.024685,0.001219,0.017809,-0.023696,0.000947,0.011792,0.010850,0.036833,0.004700,0.030137,-0.036761,-0.015026,-0.015174,-0.058549,0.012580,0.007102,0.015909,0.002080,0.004369,0.045627,-0.003952,-0.022525,0.006335,0.010368,-0.001270,-0.010937,-0.049170,-0.023460,0.000338,-0.031371,0.016503,-0.012089,0.039702,-0.009027,-0.043528,0.016736,0.004246,-0.003805,-0.004715,-0.013558,-0.000750,0.030282,0.007177,0.011529,-0.004391,-0.020481,0.022266,-0.054567,0.033857,0.006121,0.005828,0.032057,-0.017976,-0.023840,-0.003578,-0.027381,-0.022436,0.012264,-0.019206,-0.003325,-0.006892,0.007634,-0.004763,0.008151,0.003102,-0.009821,0.023551,-0.010474,0.022000,0.026389,0.011537,-0.026863,-0.016042,-0.006907,0.005188,-0.013523,-0.046201,0.019915,0.007582,0.016845,0.007917,0.001214,-0.012764,0.026748,-0.017207,0.039371,0.025085,0.013642,0.004250,0.010080,0.001055,0.023545,0.001470,0.009214,0.022693,-0.005097,-0.001313,-0.020567,0.019687,0.029591,-0.018218,0.049065,0.001587,-0.006777,0.015120,-0.011917,0.010657,-0.026841,-0.027324,0.024679,0.047434,-0.033187,-0.008394,0.010494,-0.011802,0.010305,-0.002259,0.038323,-0.006857,0.000943,-0.010578,-0.007479,-0.013278,-0.020446,0.037237,2026-03-06 08:00:00
3,2026-03-05 16:46:58,DeepStateUA,0.006730,0.000369,0.018262,0.000836,-0.008774,0.027116,-0.022959,0.080319,0.048234,-0.034813,-0.045849,0.022738,-0.009713,0.309644,0.438196,0.146174,-0.033863,0.013235,-0.015803,0.297928,-0.013456,0.024753,0.033258,-0.075049,-0.055813,0.057353,-0.116678,-0.062500,0.000718,0.040400,0.030313,-0.013032,-0.032609,-0.017691,0.000159,-0.008193,-0.009915,0.024541,-0.012840,-0.013136,0.003457,0.005493,0.019286,-0.037760,-0.016446,-0.022256,0.017909,-0.041597,-0.012891,-0.000280,-0.005204,-0.015119,0.001041,0.033324,-0.000904,0.003041,0.027553,0.023323,-0.009145,-0.007351,-0.016475,-0.016810,-0.003328,-0.014595,-0.022927,0.007267,0.018860,-0.021800,0.009130,0.012072,-0.053230,-0.032769,-0.008438,-0.006633,-0.022763,-0.056280,0.078936,0.032010,-0.078151,-0.009682,-0.002629,0.133985,-0.052904,-0.084579,0.060615,0.053592,0.015893,-0.001841,0.001716,-0.015658,-0.055644,-0.001325,0.021125,-0.053712,-0.006979,0.036450,-0.027121,0.029705,0.027946,-0.068235,-0.003609,0.013171,0.034101,-0.030720,0.000881,-0.026276,-0.001736,-0.020847,-0.019344,-0.009823,0.002972,0.006247,-0.014389,-0.006934,-0.018915,-0.002400,-0.005911,0.019148,0.001120,-0.020964,-0.004639,-0.017239,-0.020584,-0.024811,-0.010215,-0.007846,0.055711,0.000035,-0.014508,0.011382,0.009537,0.012127,-0.038330,0.021539,-0.031461,0.033549,-0.014398,0.025901,0.078348,-0.010072,-0.018390,-0.003523,0.012972,-0.017914,0.033514,0.002874,-0.005511,0.002857,0.026880,0.044138,0.018543,-0.066708,-0.023418,-0.020027,0.020840,0.023301,-0.032703,-0.002422,0.000113,0.030761,-0.028155,0.036588,-0.010908,-0.038256,-0.007882,0.000361,-0.009495,-0.011750,-0.012554,0.002863,0.013041,0.016275,0.012648,0.016132,-0.026770,0.009312,0.057960,-0.012964,-0.013864,-0.029401,-0.035812,-0.002513,-0.015276,-0.034533,0.005844,-0.001694,0.003622,-0.027561,-0.000588,0.021415,-0.004247,-0.015327,-0.027034,0.018165,-0.007450,-0.003131,0.001438,-0.021702,0.013110,0.002678,-0.007512,-0.012194,0.014093,0.013775,-0.015105,-0.000609,0.000011,-0.015561,-0.005320,-0.005557,0.005562,0.016873,0.006082,-0.002208,-0.004107,-0.002010,0.009410,0.002032,0.028864,0.015535,-0.011462,0.004802,-0.014629,-0.007260,-0.007657,0.005782,-0.000784,0.001769,0.025649,-0.014303,-0.004693,0.015168,0.010415,0.015075,0.013582,-0.003469,-0.020816,-0.016733,0.013027,0.029355,-0.027494,-0.010488,-0.002657,0.008813,-0.002380,-0.024928,-0.023059,-0.007300,0.018533,0.018425,2026-03-05 16:00:00
4,2026-03-05 15:46:39,DeepStateUA,0.048474,-0.006318,0.074492,-0.003677,-0.020839,0.080790,-0.041054,0.150230,0.063555,-0.043204,0.008690,-0.000347,-0.003948,0.152312,0.096819,0.034472,0.000234,-0.012378,0.004079,-0.045798,0.024286,-0.038902,0.063380,0.019516,0.037086,-0.056330,0.129901,0.108324,0.016540,-0.052420,-0.029516,-0.016280,-0.026797,0.036448,-0.006656,0.032470,0.011474,-0.025498,-0.041208,-0.000548,-0.024440,0.013744,-0.021409,0.056265,0.019822,0.005498,-0.032493,0.020598,0.027337,-0.006096,-0.029304,0.002763,0.007005,-0.016472,0.016137,-0.007199,-0.014718,-0.025963,0.005799,-0.008611,-0.007486,0.027010,0.002104,0.023235,-0.010194,0.007028,-0.004511,0.023883,0.018102,0.006015,-0.000850,-0.009526,0.011164,-0.025278,-0.030647,0.056156,-0.012454,-0.049401,0.059024,0.015464,0.015910,-0.005285,0.008670,-0.014688,0.005626,-0.024439,0.010349,0.017736,0.019146,-0.013128,0.023786,0.014655,-0.019442,0.088970,-0.036350,-0.054979,0.038121,-0.035612,-0.005553,0.010942,-0.022885,-0.071533,0.018372,0.004381,0.052752,0.032290,-0.008342,-0.090515,0.018199,0.066380,0.004269,-0.020578,0.047784,-0.030463,-0.041661,0.037565,0.006622,-0.018215,0.002972,0.017010,0.019653,0.020813,0.021123,0.033048,-0.025844,0.007062,-0.015535,0.011495,0.000960,-0.016812,-0.013719,-0.005454,-0.041389,0.000160,0.017724,0.030464,0.017963,-0.032639,-0.013660,0.010936,0.013186,0.023178,-0.056093,-0.011590,-0.021671,-0.004475,0.038871,-0.004559,0.004582,-0.023562,0.044997,0.065422,0.043786,-0.010457,0.009059,-0.048286,-0.023518,-0.011432,0.017929,0.058257,-0.000254,-0.045754,0.007873,0.019382,-0.006915,0.010458,0.015239,0.017786,-0.008954,0.004618,-0.015154,-0.010725,0.049668,-0.007467,-0.000409,-0.003879,-0.019728,-0.004494,-0.017682,0.039583,-0.001462,-0.011101,-0.005771,0.005899,-0.035796,-0.009256,-0.026692,-0.033233,-0.010023,-0.030311,0.015309,0.018778,-0.000732,0.016525,-0.030803,-0.039326,-0.006236,0.025289,0.014652,-0.013699,-0.009412,-0.004784,-0.022144,0.004702,-0.048493,-0.028913,0.037935,-0.031141,0.006822,0.019647,-0.000942,0.014402,0.003771,0.022732,-0.046648,-0.018938,0.012592,0.022197,-0.009677,0.019232,-0.002493,0.022667,0.032174,-0.013280,0.011676,0.013809,0.032932,0.035071,-0.029565,-0.028411,0.020664,-0.013560,0.009666,0.013115,0.004648,0.048747,-0.018451,0.024594,-0.011803,-0.014144,-0.013906,-0.010699,0.031310,0.009072,-0.003523,-0.034698,-0.039809,0.018241,-0.014541,0.038226,2026-03-05 15:00:00

In [44]:
#tg_hourly["datetime_hour"] = tg_hourly["datetime_hour"] + pd.Timedelta(hours=1)        ТУТ ЗСУВ ТГ НА 1 ГОДИНУ

In [45]:
df_final = df_final.merge(tg_hourly, on="datetime_hour", how="left")

In [46]:
df_final.sample(20)

,datetime_hour,region_id,day_dew,day_precip,day_precipprob,day_precipcover,day_moonphase,hour_temp,hour_feelslike,hour_humidity,hour_dew,hour_precip,hour_precipprob,hour_snow,hour_snowdepth,hour_windgust,hour_windspeed,hour_winddir,hour_pressure,hour_cloudcover,hour_solarradiation,hour_solarenergy,hour_uvindex,hour_conditions_simple_Clear,hour_conditions_simple_Cloudy,hour_conditions_simple_Rain,hour_conditions_simple_Snow,day_of_week,hour,city_name,day_datetime,day_sunrise,day_sunset,region_key,alarm_active,alarm_minutes_in_hour,alarm_lag_1,alarm_lag_3,alarm_lag_6,alarm_lag_12,alarms_in_last_24h,is_weekend,is_night,total_active_alarms_lag1,neighbour_alarms,hours_since_last_alarm,isw_topic_0,isw_topic_1,isw_topic_2,isw_topic_3,isw_topic_4,isw_topic_5,isw_topic_6,isw_topic_7,isw_topic_8,isw_topic_9,isw_topic_10,isw_topic_11,isw_topic_12,isw_topic_13,isw_topic_14,isw_topic_15,isw_topic_16,isw_topic_17,isw_topic_18,isw_topic_19,isw_topic_20,isw_topic_21,isw_topic_22,isw_topic_23,isw_topic_24,isw_topic_25,isw_topic_26,isw_topic_27,isw_topic_28,isw_topic_29,isw_topic_30,isw_topic_31,isw_topic_32,isw_topic_33,isw_topic_34,isw_topic_35,isw_topic_36,isw_topic_37,isw_topic_38,isw_topic_39,isw_topic_40,isw_topic_41,isw_topic_42,isw_topic_43,isw_topic_44,isw_topic_45,isw_topic_46,isw_topic_47,isw_topic_48,isw_topic_49,isw_topic_50,isw_topic_51,isw_topic_52,isw_topic_53,isw_topic_54,isw_topic_55,isw_topic_56,isw_topic_57,isw_topic_58,isw_topic_59,isw_topic_60,isw_topic_61,isw_topic_62,isw_topic_63,isw_topic_64,isw_topic_65,isw_topic_66,isw_topic_67,isw_topic_68,isw_topic_69,isw_topic_70,isw_topic_71,isw_topic_72,isw_topic_73,isw_topic_74,isw_topic_75,isw_topic_76,isw_topic_77,isw_topic_78,isw_topic_79,isw_topic_80,isw_topic_81,isw_topic_82,isw_topic_83,isw_topic_84,isw_topic_85,isw_topic_86,isw_topic_87,isw_topic_88,isw_topic_89,isw_topic_90,isw_topic_91,isw_topic_92,isw_topic_93,isw_topic_94,isw_topic_95,isw_topic_96,isw_topic_97,isw_topic_98,isw_topic_99,isw_topic_100,isw_topic_101,isw_topic_102,isw_topic_103,isw_topic_104,isw_topic_105,isw_topic_106,isw_topic_107,isw_topic_108,isw_topic_109,isw_topic_110,isw_topic_111,isw_topic_112,isw_topic_113,isw_topic_114,isw_topic_115,isw_topic_116,isw_topic_117,isw_topic_118,isw_topic_119,isw_topic_120,isw_topic_121,isw_topic_122,isw_topic_123,isw_topic_124,isw_topic_125,isw_topic_126,isw_topic_127,isw_topic_128,isw_topic_129,isw_topic_130,isw_topic_131,isw_topic_132,isw_topic_133,isw_topic_134,isw_topic_135,isw_topic_136,isw_topic_137,isw_topic_138,isw_topic_139,isw_topic_140,isw_topic_141,isw_topic_142,isw_topic_143,isw_topic_144,isw_topic_145,isw_topic_146,isw_topic_147,isw_topic_148,isw_topic_149,isw_total_intensity,isw_topic_std,isw_topic_max,isw_topic_mean,isw_velocity_24h,isw_intensity_ema,isw_topic_entropy,tg_topic_0,tg_topic_1,tg_topic_2,tg_topic_3,tg_topic_4,tg_topic_5,tg_topic_6,tg_topic_7,tg_topic_8,tg_topic_9,tg_topic_10,tg_topic_11,tg_topic_12,tg_topic_13,tg_topic_14,tg_topic_15,tg_topic_16,tg_topic_17,tg_topic_18,tg_topic_19,tg_topic_20,tg_topic_21,tg_topic_22,tg_topic_23,tg_topic_24,tg_topic_25,tg_topic_26,tg_topic_27,tg_topic_28,tg_topic_29,tg_topic_30,tg_topic_31,tg_topic_32,tg_topic_33,tg_topic_34,tg_topic_35,tg_topic_36,tg_topic_37,tg_topic_38,tg_topic_39,tg_topic_40,tg_topic_41,tg_topic_42,tg_topic_43,tg_topic_44,tg_topic_45,tg_topic_46,tg_topic_47,tg_topic_48,tg_topic_49,tg_topic_50,tg_topic_51,tg_topic_52,tg_topic_53,tg_topic_54,tg_topic_55,tg_topic_56,tg_topic_57,tg_topic_58,tg_topic_59,tg_topic_60,tg_topic_61,tg_topic_62,tg_topic_63,tg_topic_64,tg_topic_65,tg_topic_66,tg_topic_67,tg_topic_68,tg_topic_69,tg_topic_70,tg_topic_71,tg_topic_72,tg_topic_73,tg_topic_74,tg_topic_75,tg_topic_76,tg_topic_77,tg_topic_78,tg_topic_79,tg_topic_80,tg_topic_81,tg_topic_82,tg_topic_83,tg_topic_84,tg_topic_85,tg_topic_86,tg_topic_87,tg_topic_88,tg_topic_89,tg_topic_90,tg_topic_91,tg_topic_92,tg_topic_93,tg_topic_94,tg_topic_95,tg_topic_96,tg_topic_97,tg_topic_98,tg_topic_99,tg_topic_100,tg_topic_101,tg_topic_102,tg_topic_103,tg_topic_104,tg_topic_105,tg_topic_106,tg_topic_107,tg_topic_108,tg_topic_109,tg_topic_110,tg_topic_111,tg_topic_112,tg_topic_113,tg_topic_114,tg_topic_115,tg_topic_116,tg_topic_117,tg_topic_118,tg_topic_119,tg_topic_120,tg_topic_121,tg_topic_122,tg_topic_123,tg_topic_124,tg_topic_125,tg_topic_126,tg_topic_127,tg_topic_128,tg_topic_129,tg_topic_130,tg_topic_131,tg_topic_132,tg_topic_133,tg_topic_134,tg_topic_135,tg_topic_136,tg_topic_137,tg_topic_138,tg_topic_139,tg_topic_140,tg_topic_141,tg_topic_142,tg_topic_143,tg_topic_144,tg_topic_145,tg_topic_146,tg_topic_147,tg_topic_148,tg_topic_149,tg_topic_150,tg_topic_151,tg_topic_152,tg_topic_153,tg_topic_154,tg_topic_155,tg_topic_156,tg_topic_157,tg_topic_158,tg_topic_159,tg_topic_160,tg_topic_161,tg_topic_162,tg_topic_163,tg_topic_164,tg_topic_165,tg_topic_166,tg_topic_167,tg_topic_168,tg_topic_169,tg_topic_170,tg_topic_171,tg_topic_172,tg_topic_173,tg_topic_174,tg_topic_175,tg_topic_176,tg_topic_177,tg_topic_178,tg_topic_179,tg_topic_180,tg_topic_181,tg_topic_182,tg_topic_183,tg_topic_184,tg_topic_185,tg_topic_186,tg_topic_187,tg_topic_188,tg_topic_189,tg_topic_190,tg_topic_191,tg_topic_192,tg_topic_193,tg_topic_194,tg_topic_195,tg_topic_196,tg_topic_197,tg_topic_198,tg_topic_199,tg_topic_200,tg_topic_201,tg_topic_202,tg_topic_203,tg_topic_204,tg_topic_205,tg_topic_206,tg_topic_207,tg_topic_208,tg_topic_209,tg_topic_210,tg_topic_211,tg_topic_212,tg_topic_213,tg_topic_214,tg_topic_215,tg_topic_216,tg_topic_217,tg_topic_218,tg_topic_219,tg_topic_220,tg_topic_221,tg_topic_222,tg_topic_223,tg_topic_224,tg_topic_225,tg_topic_226,tg_topic_227,tg_topic_228,tg_topic_229,tg_topic_230,tg_topic_231,tg_topic_232,tg_topic_233,tg_topic_234,tg_topic_235,tg_topic_236,tg_topic_237,tg_topic_238,tg_topic_239,tg_topic_240,tg_topic_241,tg_topic_242,tg_topic_243,tg_topic_244,tg_topic_245,tg_topic_246,tg_topic_247,tg_topic_248,tg_topic_249
635313,2022-08-02 09:00:00,21,18.3,0.700,100.0,12.50,0.14,22.6,22.6,77.17,18.4,0.0,0.0,0.0,0.0,18.0,9.4,341.4,1009.0,47.6,422.0,1.5,4.0,False,True,False,False,1,9,Kherson,2022-08-02,05:30:58,20:19:58,Херсонська,0,0.000000,0.0,0.0,0.0,0.0,0.0,0,0,1.0,1.0,2624,0.765098,-0.211664,0.206794,-0.084964,-0.071043,0.090403,0.014706,0.045621,0.127624,-0.084899,0.019313,-0.027847,-0.019585,-0.117531,-0.067732,0.002815,-0.071670,0.063766,-0.039869,0.035406,-0.010556,-0.032295,0.021073,-0.110741,0.062610,0.029304,-0.072775,-0.049662,-0.018016,-0.005582,0.050119,-0.049990,0.005703,-0.003880,-0.029889,-0.004937,0.004510,-0.008183,0.030552,-0.020993,-0.047144,-0.004462,0.043947,0.011888,-0.035134,-0.005409,-0.014197,-0.004620,0.010263,-0.053913,-0.014444,-0.034615,0.001621,0.025344,0.018371,-0.010395,-0.009415,-0.016024,0.001769,-0.013183,-0.007272,-0.016664,-0.030499,0.028415,0.044464,-0.032330,0.002867,0.006761,-0.012777,0.017758,-0.050176,-0.042364,-0.023354,-0.012977,0.006412,0.022612,-0.031730,-0.001063,0.024130,-0.005897,-0.005539,0.028278,0.005691,-0.028008,-0.024904,0.035874,-0.016630,-0.033283,-0.038464,-0.008566,-0.014916,-0.032592,0.044522,-0.022454,0.022485,-0.003476,0.009493,0.013560,-0.018742,0.003046,-0.005632,-0.000585,-0.019392,0.000487,-0.016025,0.010245,0.053036,-0.024175,0.015778,-0.012800,-0.007003,0.029263,0.016531,0.016152,0.041749,0.011136,-0.013407,0.013852,-0.010217,-0.023282,-0.014504,0.033419,0.004752,0.047476,-0.017678,-0.054841,-0.003132,-0.039570,0.018405,0.000131,0.012872,-0.037743,0.021987,0.012129,-0.041352,0.012407,-0.003314,0.023413,-0.016399,0.031638,-0.017769,0.014210,-0.014490,0.025703,-0.000833,-0.006039,-0.002433,-0.024264,-0.013617,0.006879,4.911069,0.067880,0.765098,0.032740,0.259625,4.805956,4.282689,0.024329,-0.013366,0.038320,0.002207,0.004225,0.035188,-0.032709,0.119795,0.030817,-0.048151,0.244140,-0.177291,0.052228,0.001518,0.017612,-0.039276,-0.021694,-0.024370,-0.045258,-0.000612,0.023202,-0.001215,-0.037036,0.036867,0.017949,-0.012549,-0.005220,0.031542,0.006306,0.010375,0.000577,-0.005088,0.001728,0.005520,0.001369,0.006005,0.000352,0.002916,-0.018853,0.004136,0.001976,0.005461,-0.001102,-0.014191,0.004989,-0.000476,0.011806,-0.037806,-0.027100,0.001210,0.022236,0.019413,0.025791,0.053778,0.019647,0.036012,0.095251,-0.044833,0.045343,-0.106024,-0.058678,0.060403,-0.192593,0.147612,0.002339,-0.043376,0.024545,0.001779,-0.020790,-0.020893,0.054492,-0.008411,0.001756,-0.011551,0.068132,-0.044800,0.007458,-0.003602,-0.007793,0.005607,0.004622,0.015973,-0.012451,0.007059,0.024020,0.006584,0.008510,0.026391,0.023044,-0.020380,-0.029040,-0.000632,0.023807,0.026093,0.003351,-0.014339,0.000506,-0.017429,0.001203,0.001983,-0.001984,-0.002041,-0.006411,0.003734,0.004269,0.021535,0.009873,0.009141,-0.026816,0.034904,-0.030122,-0.004177,0.063243,-0.026463,0.015166,0.037375,-0.013071,0.008676,-0.035657,-0.029197,0.042837,-0.002694,-0.022458,-0.016000,-0.008265,-0.006851,0.010573,-0.010137,0.011510,0.009082,-0.004390,-0.002381,0.014654,-0.020104,-0.017181,0.008676,0.002697,0.003394,-0.003977,-0.006073,0.004268,0.000518,-0.009391,0.007328,0.008844,-0.004091,0.012008,0.015781,-0.000135,-0.005892,-0.008768,-0.009768,0.012094,-0.010192,-0.014797,-0.008571,0.001503,-0.000607,-0.015248,0.007954,-0.011330,-0.012170,0.000527,-0.012784,-0.009739,-0.009775,-0.008469,0.011981,0.017811,-0.001576,-0.006693,-0.001757,0.000879,0.009207,-0.006710,-0.001872,0.003405,0.004644,-0.001439,0.003093,-0.003012,0.004453,0.014064,0.009334,-0.006163,-0.006285,-0.002627,-0.004096,-0.002107,0.002167,0.002239,0.004548,0.006735,0.000874,0.010295,0.009573,0.001574,-0.009278,-0.005758,-0.005574,0.003985,0.000173,0.002104,0.004459,0.001979,-0.001055,0.003700,-0.003196,-0.002930,-0.007006,0.013268,-0.008350,-0.008929,0.007297,0.006073,0.005800,-0.003769,0.002676,0.006842,-0.001646,0.007041,-0.006851,-0.012282,-0.003471,0.001664,0.001792,0.008547,-0.010913,0.014096,-0.007082,0.003486,0.004152,-0.002045,-0.014217,0.000432,0.003662,-0.014914,-0.008082,-0.001467,0.016364,-0.000559,-0.008629,0.003828,-0.020051,-0.005624,0.006060,0.006414,0.007028,0.012648,-0.006064
376856,2025-07-31 03:00:00,13,12.1,0.600,100.0,8.33,0.21,11.1,11.1,97.38,10.7,0.0,0.0,0.0,0.0,14.8,0.0,639.0,1015.4,0.0,0.0,0.0,0.0,True,False,False,False,3,3,Lviv,2025-07-31,05:52:34,21:07:15,Львівська,0,0.000000,0.0,0.0,0.0,1.0,2.0,0,1,7.0,1.0,10,0.795360,0.260680,0.096849,0.043324,-0.137880,0.111904,0.056096,-0.046141,-0.072968,0.100286,-0.074760,-0.204026,0.018662,0.003826,-0.017532,0.057684,0.025368,-0.050498,0.017181,0.018719,-0.061884,-0.064310,0.001913,-0.013337,-0.064960,0.057929,-0.013544,0.021326,-0.022217,0.048688,-0.079074,-0.033538,0.000064,0.024128,-0.008438,-0.003019,0.000858,-0.014708,-0.009507,0.032726,0.003439,0.001503,-0.006998,0.035063,0.024985,-0.052044,-0.002231,-0.048781,-0.002842,0.043813,-0.030473,-0.006047,0.004531,-0.004265,-0.031810,-0.012296,-0.018731,-0.022591,-0.032258,0.010826,-0.044443,0.001762,0.009446,0.060253,0.061022,-0.011357,0.016396,0.028818,0.025913,0.036502,0.028436,-0.009270,0.000425,0.014562,-0.042089,-0.029103,0.008710,0.043444,0.005095,0.027226,0.000036,0.034181,-0.041161,-0.009025,0.032765,0.026087,0.039271,0.011112,-0.017199,-0.031742,-0.019350,0.006933,-0.051835,0.009147,0.037488,-0.012429,-0.018183,-0.011061,-0.012282,-0.007343,-0.034582,0.005197,-0.003450,0.026054,-0.005564,-0.005328,-0.005487,-0.031188,-0.021965,-0.034568,-0.005645,-0.031778,0.000683,-0.027582,0.005621,0.009583,0.030666,-0.003284,0.029402,-0.001976,0.036709,0.004145,-0.022634,-0.010790,0.015734,-0.010607,0.001103,0.006336,0.019534,0.007108,-0.006664,0.018512,-0.015206,0.002362,0.000740,0.028796,0.007904,0.016710,0.012645,-0.020414,-0.023605,-0.011923,-0.006222,0.006091,0.004294,0.018015,0.010026,-0.016510,0.028242,-0.008169,4.831698,0.071105,0.795360,0.032211,0.398529,4.470065,4.207105,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29394,2025-07-01 22:00:00,2,8.6,0.000,0.0,0.00,0.19,19.6,19.6,49.34,8.7,0.0,0.0,0.0,0.0,26.6,10.8,329.1,1016.0,41.3,0.4,0.0,0.0,False,True,False,False,1,22,Vinnytsia,2025-07-01,05:05:10,21:14:55,Вінницька,0,0.000000,0.0,0.0,0.0,0.0,0.0,0,0,5.0,0.0,64,0.809624,0.225131,0.084191,-0.006893,-0.176612,0.145466,0.100916,-0.084373,-0.098713,0.128630,-0.097080,-0.081244,-0.041779,0.047696,0.020082,-0.015923,-0.060089,-0.017758,0.019366,0.016494,-0.085797,0.040021,0.010289,0.034644,-0.058284,0.078301,-0.046130,0.005100,0.015955,0.033069,0.041680,-0.008191,0.001815,-0.014551,0.013424,0.014077,0.018212,0.010887,-0.005072,0.003983,-0.024742,0.022711,0.021263,0.024431,0.009875,-0.012160,-0.003466,-0.010884,0.009248,-0.018061,-0.004872,-0.026691,0.012473,0.019881,-0.009014,0.019357,0.012794,-0.025626,-0.008562,-0.005680,0.018198,0.011041,-0.003446,-0.002617,0.007947,0.018563,-0.013928,0.008480,0.006452,-0.013598,-0.001050,0.003218,-0.014907,0.031106,-0.010244,0.000713,0.002939,-0.009513,0.017264,-0.001292,-0.010698,-0.033502,0.007610,0.011791,0.005660,-0.005037,0.017162,0.011119,0.019283,-0.001833,0.000573,0.002931,-0.017059,-0.007358,0.008752,-0.004030,0.018804,0.013760,0.015078,0.004573,-0.008964,-0.004725,-0.016264,-0.008178,0.008108,0.007148,-0.009633,-0.002644,-0.018175,0.002835,0.003166,0.005603,0.002604,-0.008897,0.000239,-0.024287,-0.003698,-0.009320,0.005344,0.006129,-0.036535,-0.018400,0.002437,-0.008408,-0.022656,0.001128,-0.017141,-0.015852,0.016141,-0.009283,0.006704,-0.024265,-0.002166,0.009888,0.000416,-0.006455,0.028792,-0.014815,-0.006059,0.013516,0.027997,-0.004892,-0.006250,0.007721,0.002956,-0.003306,-0.000516,0.005209,-0.008115,-0.008993,4.025439,0.072032,0.809624,0.026836,-0.198570,4.072254,3.972005,0.079038,-0.048816,0.141937,0.093240,0.019210,-0.037964,0.030853,0.031703,-0.022897,-0.012059,0.008905,0.027942,-0.032303,-0.002184,-0.027823,-0.000319,-0.016309,-0.056777,0.084727,0.061525,0.049387,0.036894,-0.010555,0.045334,0.088426,0.025685,0.010865,-0.031438,-0.003590,-0.004581,0.003581,-0.021965,-0.003826,-0.004779,0.016901,0.004218,0.000397,0.005236,-0.035442,-0.024727,-0.019507,0.015493,-0.013674,-0.004770,0.009659,0.026319,-0.032930,-0.011489,0.001497,0.025923,0.004771,-0.010296,-0.009112,0.017375,0.038005,-0.016794,-0.017557,-0.025707,0.039531,0.045553,0.015837,0.012747,0.001242,0.019219,-0.002049,0.009073,0.036303,-0.001782,0.000860,0.011498,0.003125,0.023047,-0.035054,-0.016263,0.001929,0.033463,0.025434,-0.005405,-0.011267,0.003119,0.019519,0.016089,0.003211,0.041690,0.026768,-0.012107,-0.021464,0.005197,-0.010922,0.034521,0.000502,-0.006353,0.010129,-0.017597,-0.023241,0.009569,-0.007599,-0.018445,-0.006640,-0.013494,-0.002734,0.025640,-0.011023,0.005600,0.005560,-0.008062,-0.019127,0.000300,-0.017369,-0.034434,-0.000132,0.002460,-0.026862,-0.028478,0.020228,0.017913,0.018073,0.007634,-0.016019,0.004659,0.026888,-0.004400,-0.017518,0.005651,-0.014590,-0.010836,-0.007576,-0.007709,-0.019158,0.017200,-0.006278,-0.012341,0.001713,-0.014478,-0.010573,0.005311,0.014973,0.001707,-0.014575,0.008897,0.003375,-0.017911,-0.000080,0.036327,-0.006075,0.006085,-0.004692,0.008954,0.029375,-0.004457,0.019547,-0.011279,0.006251,0.003454,-0.032212,0.017777,0.011493,-0.011276,-0.010169,-0.013851,-0.023816,-0.013925,-0.036694,0.005330,-0.007433,-0.008457,-0.000684,0.016561,0.010149,-0.022539,-0.005222,0.021632,0.006720,0.010886,0.002118,-0.005897,-0.007228,-0.032865,-0.013011,-0.002513,-0.007259,-0.001340,-0.009086,0.004404,0.017826,-0.015448,-0.037157,-0.006755,0.029817,0.006781,-0.059909,-0.010686,0.010738,-0.001204,0.009850,-0.002403,0.007972,0.027883,0.017168,-0.019467,0.018089,-0.002851,-0.028730,0.002949,-0.034068,-0.035923,-0.009269,0.012248,0.012811,0.002077,0.013075,-0.001322,-0.010203,-0.009995,-0.011802,0.001714,0.026755,0.001022,-0.016745,0.015652,0.024327,-0.000707,-0.030622,0.004296,0.003512,-0.005662,-0.015057,0.001341,0.027675,-0.009538,-0.012910,0.011114,-0.015014,0.046107,0.018925,-0.006899,-0.006844,-0.007824,-0.022838,0.030587,-0.014093,0.000605,0.031612,0.020332,-0.001313,0.013397,-0.025063,0.009271,-0.049378,0.012951

In [47]:
df_final.shape

(844993, 453)

In [48]:
df_final = df_final.sort_values(["datetime_hour"])

In [49]:
with pd.option_context('display.max_rows', None):
    print(df_final.isnull().sum())

datetime_hour                         0
region_id                             0
day_dew                               0
day_precip                            0
day_precipprob                        0
day_precipcover                       0
day_moonphase                         0
hour_temp                             0
hour_feelslike                        0
hour_humidity                         0
hour_dew                              0
hour_precip                           0
hour_precipprob                       0
hour_snow                             0
hour_snowdepth                        0
hour_windgust                         0
hour_windspeed                        0
hour_winddir                          0
hour_pressure                         0
hour_cloudcover                       0
hour_solarradiation                   0
hour_solarenergy                      0
hour_uvindex                          0
hour_conditions_simple_Clear          0
hour_conditions_simple_Cloudy         0
hour_conditions_simple_Rain           0
hour_conditions_simple_Snow           0
day_of_week                           0
hour                                  0
city_name                             0
day_datetime                          0
day_sunrise                           0
day_sunset                            0
region_key                            0
alarm_active                          0
alarm_minutes_in_hour                 0
alarm_lag_1                           0
alarm_lag_3                           0
alarm_lag_6                           0
alarm_lag_12                          0
alarms_in_last_24h                    0
is_weekend                            0
is_night                              0
total_active_alarms_lag1              0
neighbour_alarms                      0
hours_since_last_alarm                0
isw_topic_0                           0
isw_topic_1                           0
isw_topic_2                           0
isw_topic_3                           0
isw_topic_4                           0
isw_topic_5                           0
isw_topic_6                           0
isw_topic_7                           0
isw_topic_8                           0
isw_topic_9                           0
isw_topic_10                          0
isw_topic_11                          0
isw_topic_12                          0
isw_topic_13                          0
isw_topic_14                          0
isw_topic_15                          0
isw_topic_16                          0
isw_topic_17                          0
isw_topic_18                          0
isw_topic_19                          0
isw_topic_20                          0
isw_topic_21                          0
isw_topic_22                          0
isw_topic_23                          0
isw_topic_24                          0
isw_topic_25                          0
isw_topic_26                          0
isw_topic_27                          0
isw_topic_28                          0
isw_topic_29                          0
isw_topic_30                          0
isw_topic_31                          0
isw_topic_32                          0
isw_topic_33                          0
isw_topic_34                          0
isw_topic_35                          0
isw_topic_36                          0
isw_topic_37                          0
isw_topic_38                          0
isw_topic_39                          0
isw_topic_40                          0
isw_topic_41                          0
isw_topic_42                          0
isw_topic_43                          0
isw_topic_44                          0
isw_topic_45                          0
isw_topic_46                          0
isw_topic_47                          0
isw_topic_48                          0
isw_topic_49                          0
isw_topic_50                          0
isw_topic_51                          0
isw_topic_52                          0
isw_topic_53                          0
isw_topic_54                          0
isw_topic_55                          0
isw_topic_56                          0
isw_topic_57                          0
isw_topic_58                          0
isw_topic_59                          0
isw_topic_60                          0
isw_topic_61                          0
isw_topic_62                          0
isw_topic_63                          0
isw_topic_64                          0
isw_topic_65                          0
isw_topic_66                          0
isw_topic_67                          0
isw_topic_68                          0
isw_topic_69                          0
isw_topic_70                          0
isw_topic_71                          0
isw_topic_72                          0
isw_topic_73                          0
isw_topic_74                          0
isw_topic_75                          0
isw_topic_76                          0
isw_topic_77                          0
isw_topic_78                          0
isw_topic_79                          0
isw_topic_80                          0
isw_topic_81                          0
isw_topic_82                          0
isw_topic_83                          0
isw_topic_84                          0
isw_topic_85                          0
isw_topic_86                          0
isw_topic_87                          0
isw_topic_88                          0
isw_topic_89                          0
isw_topic_90                          0
isw_topic_91                          0
isw_topic_92                          0
isw_topic_93                          0
isw_topic_94                          0
isw_topic_95                          0
isw_topic_96                          0
isw_topic_97                          0
isw_topic_98                          0
isw_topic_99                          0
isw_topic_100                         0
isw_topic_101                         0
isw_topic_102                         0
isw_topic_103                         0
isw_topic_104                         0
isw_topic_105                         0
isw_topic_106                         0
isw_topic_107                         0
isw_topic_108                         0
isw_topic_109                         0
isw_topic_110                         0
isw_topic_111                         0
isw_topic_112                         0
isw_topic_113                         0
isw_topic_114                         0
isw_topic_115                         0
isw_topic_116                         0
isw_topic_117                         0
isw_topic_118                         0
isw_topic_119                         0
isw_topic_120                         0
isw_topic_121                         0
isw_topic_122                         0
isw_topic_123                         0
isw_topic_124                         0
isw_topic_125                         0
isw_topic_126                         0
isw_topic_127                         0
isw_topic_128                         0
isw_topic_129                         0
isw_topic_130                         0
isw_topic_131                         0
isw_topic_132                         0
isw_topic_133                         0
isw_topic_134                         0
isw_topic_135                         0
isw_topic_136                         0
isw_topic_137                         0
isw_topic_138                         0
isw_topic_139                         0
isw_topic_140                         0
isw_topic_141                         0
isw_topic_142                         0
isw_topic_143                         0
isw_topic_144                         0
isw_topic_145                         0
isw_topic_146                         0
isw_topic_147                         0
isw_topic_148                         0
isw_topic_149                         0
isw_total_intensity                   0
isw_topic_std                         0
isw_topic_max                         0
isw_topic_mean                        0
isw_velocity_24h                      0
isw_intensity_ema                     0
isw_topic_entropy                     0
tg_topic_0                       142842
tg_topic_1                       142842
tg_topic_2                       142842
tg_topic_3                       142842
tg_topic_4                       142842
tg_topic_5                       142842
tg_topic_6                       142842
tg_topic_7                       142842
tg_topic_8                       142842
tg_topic_9                       142842
tg_topic_10                      142842
tg_topic_11                      142842
tg_topic_12                      142842
tg_topic_13                      142842
tg_topic_14                      142842
tg_topic_15                      142842
tg_topic_16                      142842
tg_topic_17                      142842
tg_topic_18                      142842
tg_topic_19                      142842
tg_topic_20                      142842
tg_topic_21                      142842
tg_topic_22                      142842
tg_topic_23                      142842
tg_topic_24                      142842
tg_topic_25                      142842
tg_topic_26                      142842
tg_topic_27                      142842
tg_topic_28                      142842
tg_topic_29                      142842
tg_topic_30                      142842
tg_topic_31                      142842
tg_topic_32                      142842
tg_topic_33                      142842
tg_topic_34                      142842
tg_topic_35                      142842
tg_topic_36                      142842
tg_topic_37                      142842
tg_topic_38                      142842
tg_topic_39                      142842
tg_topic_40                      142842
tg_topic_41                      142842
tg_topic_42                      142842
tg_topic_43                      142842
tg_topic_44                      142842
tg_topic_45                      142842
tg_topic_46                      142842
tg_topic_47                      142842
tg_topic_48                      142842
tg_topic_49                      142842
tg_topic_50                      142842
tg_topic_51                      142842
tg_topic_52                      142842
tg_topic_53                      142842
tg_topic_54                      142842
tg_topic_55                      142842
tg_topic_56                      142842
tg_topic_57                      142842
tg_topic_58                      142842
tg_topic_59                      142842
tg_topic_60                      142842
tg_topic_61                      142842
tg_topic_62                      142842
tg_topic_63                      142842
tg_topic_64                      142842
tg_topic_65                      142842
tg_topic_66                      142842
tg_topic_67                      142842
tg_topic_68                      142842
tg_topic_69                      142842
tg_topic_70                      142842
tg_topic_71                      142842
tg_topic_72                      142842
tg_topic_73                      142842
tg_topic_74                      142842
tg_topic_75                      142842
tg_topic_76                      142842
tg_topic_77                      142842
tg_topic_78                      142842
tg_topic_79                      142842
tg_topic_80                      142842
tg_topic_81                      142842
tg_topic_82                      142842
tg_topic_83                      142842
tg_topic_84                      142842
tg_topic_85                      142842
tg_topic_86                      142842
tg_topic_87                      142842
tg_topic_88                      142842
tg_topic_89                      142842
tg_topic_90                      142842
tg_topic_91                      142842
tg_topic_92                      142842
tg_topic_93                      142842
tg_topic_94                      142842
tg_topic_95                      142842
tg_topic_96                      142842
tg_topic_97                      142842
tg_topic_98                      142842
tg_topic_99                      142842
tg_topic_100                     142842
tg_topic_101                     142842
tg_topic_102                     142842
tg_topic_103                     142842
tg_topic_104                     142842
tg_topic_105                     142842
tg_topic_106                     142842
tg_topic_107                     142842
tg_topic_108                     142842
tg_topic_109                     142842
tg_topic_110                     142842
tg_topic_111                     142842
tg_topic_112                     142842
tg_topic_113                     142842
tg_topic_114                     142842
tg_topic_115                     142842
tg_topic_116                     142842
tg_topic_117                     142842
tg_topic_118                     142842
tg_topic_119                     142842
tg_topic_120                     142842
tg_topic_121                     142842
tg_topic_122                     142842
tg_topic_123                     142842
tg_topic_124                     142842
tg_topic_125                     142842
tg_topic_126                     142842
tg_topic_127                     142842
tg_topic_128                     142842
tg_topic_129                     142842
tg_topic_130                     142842
tg_topic_131                     142842
tg_topic_132                     142842
tg_topic_133                     142842
tg_topic_134                     142842
tg_topic_135                     142842
tg_topic_136                     142842
tg_topic_137                     142842
tg_topic_138                     142842
tg_topic_139                     142842
tg_topic_140                     142842
tg_topic_141                     142842
tg_topic_142                     142842
tg_topic_143                     142842
tg_topic_144                     142842
tg_topic_145                     142842
tg_topic_146                     142842
tg_topic_147                     142842
tg_topic_148                     142842
tg_topic_149                     142842
tg_topic_150                     142842
tg_topic_151                     142842
tg_topic_152                     142842
tg_topic_153                     142842
tg_topic_154                     142842
tg_topic_155                     142842
tg_topic_156                     142842
tg_topic_157                     142842
tg_topic_158                     142842
tg_topic_159                     142842
tg_topic_160                     142842
tg_topic_161                     142842
tg_topic_162                     142842
tg_topic_163                     142842
tg_topic_164                     142842
tg_topic_165                     142842
tg_topic_166                     142842
tg_topic_167                     142842
tg_topic_168                     142842
tg_topic_169                     142842
tg_topic_170                     142842
tg_topic_171                     142842
tg_topic_172                     142842
tg_topic_173                     142842
tg_topic_174                     142842
tg_topic_175                     142842
tg_topic_176                     142842
tg_topic_177                     142842
tg_topic_178                     142842
tg_topic_179                     142842
tg_topic_180                     142842
tg_topic_181                     142842
tg_topic_182                     142842
tg_topic_183                     142842
tg_topic_184                     142842
tg_topic_185                     142842
tg_topic_186                     142842
tg_topic_187                     142842
tg_topic_188                     142842
tg_topic_189                     142842
tg_topic_190                     142842
tg_topic_191                     142842
tg_topic_192                     142842
tg_topic_193                     142842
tg_topic_194                     142842
tg_topic_195                     142842
tg_topic_196                     142842
tg_topic_197                     142842
tg_topic_198                     142842
tg_topic_199                     142842
tg_topic_200                     142842
tg_topic_201                     142842
tg_topic_202                     142842
tg_topic_203                     142842
tg_topic_204                     142842
tg_topic_205                     142842
tg_topic_206                     142842
tg_topic_207                     142842
tg_topic_208                     142842
tg_topic_209                     142842
tg_topic_210                     142842
tg_topic_211                     142842
tg_topic_212                     142842
tg_topic_213                     142842
tg_topic_214                     142842
tg_topic_215                     142842
tg_topic_216                     142842
tg_topic_217                     142842
tg_topic_218                     142842
tg_topic_219                     142842
tg_topic_220                     142842
tg_topic_221                     142842
tg_topic_222                     142842
tg_topic_223                     142842
tg_topic_224                     142842
tg_topic_225                     142842
tg_topic_226                     142842
tg_topic_227                     142842
tg_topic_228                     142842
tg_topic_229                     142842
tg_topic_230                     142842
tg_topic_231                     142842
tg_topic_232                     142842
tg_topic_233                     142842
tg_topic_234                     142842
tg_topic_235                     142842
tg_topic_236                     142842
tg_topic_237                     142842
tg_topic_238                     142842
tg_topic_239                     142842
tg_topic_240                     142842
tg_topic_241                     142842
tg_topic_242                     142842
tg_topic_243                     142842
tg_topic_244                     142842
tg_topic_245                     142842
tg_topic_246                     142842
tg_topic_247                     142842
tg_topic_248                     142842
tg_topic_249                     142842
dtype: int64

In [50]:
df_final = df_final.fillna(0)

In [51]:
tg_cols = [c for c in df_final.columns if 'tg_topic_' in c]
df_tg_abs = df_final[tg_cols].abs()

df_final['tg_total_intensity'] = df_tg_abs.sum(axis=1)
df_final['tg_topic_std'] = df_tg_abs.std(axis=1)
df_final['tg_topic_max'] = df_tg_abs.max(axis=1)
df_final['tg_topic_entropy'] = -(df_tg_abs.div(df_tg_abs.sum(axis=1), axis=0) * np.log(df_tg_abs.div(df_tg_abs.sum(axis=1), axis=0) + 1e-9)).sum(axis=1)

C:\Users\Uw11\AppData\Local\Temp\ipykernel_33600\409095542.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_final['tg_total_intensity'] = df_tg_abs.sum(axis=1)
C:\Users\Uw11\AppData\Local\Temp\ipykernel_33600\409095542.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_final['tg_topic_std'] = df_tg_abs.std(axis=1)
C:\Users\Uw11\AppData\Local\Temp\ipykernel_33600\409095542.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_final['tg_topic_max'] = df_tg_abs.max(axis=1)
C:\Users\Uw11\AppData\Local\Temp\ipykernel_33600\409095542.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_final['tg_topic_entropy'] = -(df_tg_abs.div(df_tg_abs.sum(axis=1), axis=0) * np.log(df_tg_abs.div(df_tg_abs.sum(axis=1), axis=0) + 1e-9)).sum(axis=1)

In [52]:
df_final['tg_velocity_3h'] = (df_final.groupby('region_id')['tg_total_intensity'].diff(3).fillna(0))
df_final['tg_intensity_ema_6h'] = (df_final.groupby('region_id')['tg_total_intensity'].transform(lambda x: x.ewm(span=6).mean()))
df_final['tg_intensity_zscore'] = (df_final.groupby('region_id')['tg_total_intensity'].transform(lambda x: (x - x.rolling(24, min_periods=1).mean()) / (x.rolling(24, min_periods=1).std() + 1e-9)))

C:\Users\Uw11\AppData\Local\Temp\ipykernel_33600\3857173777.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_final['tg_velocity_3h'] = (df_final.groupby('region_id')['tg_total_intensity'].diff(3).fillna(0))
C:\Users\Uw11\AppData\Local\Temp\ipykernel_33600\3857173777.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_final['tg_intensity_ema_6h'] = (df_final.groupby('region_id')['tg_total_intensity'].transform(lambda x: x.ewm(span=6).mean()))
C:\Users\Uw11\AppData\Local\Temp\ipykernel_33600\3857173777.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_final['tg_intensity_zscore'] = (df_final.groupby('region_id')['tg_total_intensity'].transform(lambda x: (x - x.rolling(24, min_periods=1).mean()) / (x.rolling(24, min_periods=1).std() + 1e-9)))

In [53]:
df_final.sample(20)

,datetime_hour,region_id,day_dew,day_precip,day_precipprob,day_precipcover,day_moonphase,hour_temp,hour_feelslike,hour_humidity,hour_dew,hour_precip,hour_precipprob,hour_snow,hour_snowdepth,hour_windgust,hour_windspeed,hour_winddir,hour_pressure,hour_cloudcover,hour_solarradiation,hour_solarenergy,hour_uvindex,hour_conditions_simple_Clear,hour_conditions_simple_Cloudy,hour_conditions_simple_Rain,hour_conditions_simple_Snow,day_of_week,hour,city_name,day_datetime,day_sunrise,day_sunset,region_key,alarm_active,alarm_minutes_in_hour,alarm_lag_1,alarm_lag_3,alarm_lag_6,alarm_lag_12,alarms_in_last_24h,is_weekend,is_night,total_active_alarms_lag1,neighbour_alarms,hours_since_last_alarm,isw_topic_0,isw_topic_1,isw_topic_2,isw_topic_3,isw_topic_4,isw_topic_5,isw_topic_6,isw_topic_7,isw_topic_8,isw_topic_9,isw_topic_10,isw_topic_11,isw_topic_12,isw_topic_13,isw_topic_14,isw_topic_15,isw_topic_16,isw_topic_17,isw_topic_18,isw_topic_19,isw_topic_20,isw_topic_21,isw_topic_22,isw_topic_23,isw_topic_24,isw_topic_25,isw_topic_26,isw_topic_27,isw_topic_28,isw_topic_29,isw_topic_30,isw_topic_31,isw_topic_32,isw_topic_33,isw_topic_34,isw_topic_35,isw_topic_36,isw_topic_37,isw_topic_38,isw_topic_39,isw_topic_40,isw_topic_41,isw_topic_42,isw_topic_43,isw_topic_44,isw_topic_45,isw_topic_46,isw_topic_47,isw_topic_48,isw_topic_49,isw_topic_50,isw_topic_51,isw_topic_52,isw_topic_53,isw_topic_54,isw_topic_55,isw_topic_56,isw_topic_57,isw_topic_58,isw_topic_59,isw_topic_60,isw_topic_61,isw_topic_62,isw_topic_63,isw_topic_64,isw_topic_65,isw_topic_66,isw_topic_67,isw_topic_68,isw_topic_69,isw_topic_70,isw_topic_71,isw_topic_72,isw_topic_73,isw_topic_74,isw_topic_75,isw_topic_76,isw_topic_77,isw_topic_78,isw_topic_79,isw_topic_80,isw_topic_81,isw_topic_82,isw_topic_83,isw_topic_84,isw_topic_85,isw_topic_86,isw_topic_87,isw_topic_88,isw_topic_89,isw_topic_90,isw_topic_91,isw_topic_92,isw_topic_93,isw_topic_94,isw_topic_95,isw_topic_96,isw_topic_97,isw_topic_98,isw_topic_99,isw_topic_100,isw_topic_101,isw_topic_102,isw_topic_103,isw_topic_104,isw_topic_105,isw_topic_106,isw_topic_107,isw_topic_108,isw_topic_109,isw_topic_110,isw_topic_111,isw_topic_112,isw_topic_113,isw_topic_114,isw_topic_115,isw_topic_116,isw_topic_117,isw_topic_118,isw_topic_119,isw_topic_120,isw_topic_121,isw_topic_122,isw_topic_123,isw_topic_124,isw_topic_125,isw_topic_126,isw_topic_127,isw_topic_128,isw_topic_129,isw_topic_130,isw_topic_131,isw_topic_132,isw_topic_133,isw_topic_134,isw_topic_135,isw_topic_136,isw_topic_137,isw_topic_138,isw_topic_139,isw_topic_140,isw_topic_141,isw_topic_142,isw_topic_143,isw_topic_144,isw_topic_145,isw_topic_146,isw_topic_147,isw_topic_148,isw_topic_149,isw_total_intensity,isw_topic_std,isw_topic_max,isw_topic_mean,isw_velocity_24h,isw_intensity_ema,isw_topic_entropy,tg_topic_0,tg_topic_1,tg_topic_2,tg_topic_3,tg_topic_4,tg_topic_5,tg_topic_6,tg_topic_7,tg_topic_8,tg_topic_9,tg_topic_10,tg_topic_11,tg_topic_12,tg_topic_13,tg_topic_14,tg_topic_15,tg_topic_16,tg_topic_17,tg_topic_18,tg_topic_19,tg_topic_20,tg_topic_21,tg_topic_22,tg_topic_23,tg_topic_24,tg_topic_25,tg_topic_26,tg_topic_27,tg_topic_28,tg_topic_29,tg_topic_30,tg_topic_31,tg_topic_32,tg_topic_33,tg_topic_34,tg_topic_35,tg_topic_36,tg_topic_37,tg_topic_38,tg_topic_39,tg_topic_40,tg_topic_41,tg_topic_42,tg_topic_43,tg_topic_44,tg_topic_45,tg_topic_46,tg_topic_47,tg_topic_48,tg_topic_49,tg_topic_50,tg_topic_51,tg_topic_52,tg_topic_53,tg_topic_54,tg_topic_55,tg_topic_56,tg_topic_57,tg_topic_58,tg_topic_59,tg_topic_60,tg_topic_61,tg_topic_62,tg_topic_63,tg_topic_64,tg_topic_65,tg_topic_66,tg_topic_67,tg_topic_68,tg_topic_69,tg_topic_70,tg_topic_71,tg_topic_72,tg_topic_73,tg_topic_74,tg_topic_75,tg_topic_76,tg_topic_77,tg_topic_78,tg_topic_79,tg_topic_80,tg_topic_81,tg_topic_82,tg_topic_83,tg_topic_84,tg_topic_85,tg_topic_86,tg_topic_87,tg_topic_88,tg_topic_89,tg_topic_90,tg_topic_91,tg_topic_92,tg_topic_93,tg_topic_94,tg_topic_95,tg_topic_96,tg_topic_97,tg_topic_98,tg_topic_99,tg_topic_100,tg_topic_101,tg_topic_102,tg_topic_103,tg_topic_104,tg_topic_105,tg_topic_106,tg_topic_107,tg_topic_108,tg_topic_109,tg_topic_110,tg_topic_111,tg_topic_112,tg_topic_113,tg_topic_114,tg_topic_115,tg_topic_116,tg_topic_117,tg_topic_118,tg_topic_119,tg_topic_120,tg_topic_121,tg_topic_122,tg_topic_123,tg_topic_124,tg_topic_125,tg_topic_126,tg_topic_127,tg_topic_128,tg_topic_129,tg_topic_130,tg_topic_131,tg_topic_132,tg_topic_133,tg_topic_134,tg_topic_135,tg_topic_136,tg_topic_137,tg_topic_138,tg_topic_139,tg_topic_140,tg_topic_141,tg_topic_142,tg_topic_143,tg_topic_144,tg_topic_145,tg_topic_146,tg_topic_147,tg_topic_148,tg_topic_149,tg_topic_150,tg_topic_151,tg_topic_152,tg_topic_153,tg_topic_154,tg_topic_155,tg_topic_156,tg_topic_157,tg_topic_158,tg_topic_159,tg_topic_160,tg_topic_161,tg_topic_162,tg_topic_163,tg_topic_164,tg_topic_165,tg_topic_166,tg_topic_167,tg_topic_168,tg_topic_169,tg_topic_170,tg_topic_171,tg_topic_172,tg_topic_173,tg_topic_174,tg_topic_175,tg_topic_176,tg_topic_177,tg_topic_178,tg_topic_179,tg_topic_180,tg_topic_181,tg_topic_182,tg_topic_183,tg_topic_184,tg_topic_185,tg_topic_186,tg_topic_187,tg_topic_188,tg_topic_189,tg_topic_190,tg_topic_191,tg_topic_192,tg_topic_193,tg_topic_194,tg_topic_195,tg_topic_196,tg_topic_197,tg_topic_198,tg_topic_199,tg_topic_200,tg_topic_201,tg_topic_202,tg_topic_203,tg_topic_204,tg_topic_205,tg_topic_206,tg_topic_207,tg_topic_208,tg_topic_209,tg_topic_210,tg_topic_211,tg_topic_212,tg_topic_213,tg_topic_214,tg_topic_215,tg_topic_216,tg_topic_217,tg_topic_218,tg_topic_219,tg_topic_220,tg_topic_221,tg_topic_222,tg_topic_223,tg_topic_224,tg_topic_225,tg_topic_226,tg_topic_227,tg_topic_228,tg_topic_229,tg_topic_230,tg_topic_231,tg_topic_232,tg_topic_233,tg_topic_234,tg_topic_235,tg_topic_236,tg_topic_237,tg_topic_238,tg_topic_239,tg_topic_240,tg_topic_241,tg_topic_242,tg_topic_243,tg_topic_244,tg_topic_245,tg_topic_246,tg_topic_247,tg_topic_248,tg_topic_249,tg_total_intensity,tg_topic_std,tg_topic_max,tg_topic_entropy,tg_velocity_3h,tg_intensity_ema_6h,tg_intensity_zscore
431350,2023-09-04 23:00:00,15,12.5,0.000,0.0,0.00,0.64,21.4,21.4,51.85,11.1,0.0,0.0,0.0,0.0,42.8,24.8,22.8,1017.0,0.2,0.0,0.0,0.0,True,False,False,False,0,23,Odesa,2023-09-04,06:20:18,19:31:19,Одеська,0,0.000000,0.0,0.0,0.0,0.0,6.0,0,1,3.0,0.0,8,0.780670,-0.078170,-0.030306,-0.162756,-0.092640,0.025452,-0.065059,0.100287,0.018315,-0.045577,0.049183,0.042227,0.183135,0.289444,0.074117,-0.108274,0.027852,0.040781,0.055644,-0.080048,0.002886,-0.044268,-0.030450,-0.024332,-0.006321,-0.021062,-0.000300,0.014952,-0.031638,0.019155,-0.005753,0.009270,-0.029013,0.007991,-0.069218,0.007422,-0.009432,0.060469,0.028937,0.014445,-0.015825,-0.004976,-0.047273,0.019625,0.005374,-0.043383,-0.001495,-0.004813,-0.006741,-0.029831,0.007163,0.000556,-0.048582,0.048305,0.011767,0.049083,-0.011579,-0.009633,-0.005142,0.009893,0.012317,0.017934,-0.009864,0.002526,-0.009022,-0.016325,0.000955,0.021691,0.034680,-0.005044,-0.025494,0.019341,0.000579,0.007752,0.012337,0.055754,-0.018931,-0.002420,0.012780,-0.016208,0.004438,0.022549,0.017104,0.003768,0.034169,0.002933,-0.006916,0.004624,-0.003368,0.000644,0.033746,-0.007571,0.003144,-0.003815,-0.005556,0.023210,-0.014424,-0.014257,-0.016752,0.020946,-0.018200,0.020733,0.013294,-0.011855,0.017165,-0.020861,0.019725,-0.001475,-0.017934,-0.002899,-0.018588,0.014595,-0.033696,-0.045279,0.002820,-0.008127,-0.037222,0.009263,0.023112,0.002835,0.019399,0.026968,0.013400,-0.013409,-0.039957,-0.026571,0.000579,-0.049195,-0.004959,0.011276,0.017463,0.041061,-0.060335,0.003513,0.005729,-0.015497,0.010633,0.001816,0.013124,0.014713,0.001082,0.002903,-0.017846,0.029757,0.000384,-0.006450,-0.011227,0.030330,0.026378,-0.007789,4.577601,0.070780,0.780670,0.030517,0.184435,4.556958,4.141029,0.066398,0.076990,0.000006,0.040958,0.011562,0.102501,-0.010792,0.050666,-0.003092,-0.053769,-0.029656,-0.000115,-0.007500,-0.031227,0.007666,-0.022286,-0.013272,-0.046966,-0.014209,-0.003716,0.015259,-0.018471,0.009745,-0.004630,-0.002173,0.007622,-0.016190,-0.002323,-0.007412,0.003869,-0.004569,0.010232,-0.002858,0.029156,0.005176,0.041795,0.004148,-0.012716,-0.009634,-0.004381,0.003107,0.010029,-0.001189,0.008577,0.004340,-0.003293,-0.009948,-0.008290,0.002436,-0.001699,0.001698,-0.000502,0.012255,-0.014867,-0.004146,-0.002423,-0.006235,-0.002189,0.003042,0.008276,-0.013373,0.004465,-0.003210,0.005470,-0.004560,-0.005508,-0.004746,-0.007621,-0.001013,-0.002372,0.005189,-0.005658,0.005130,0.007529,0.003659,0.002569,-0.009606,0.003306,0.002072,0.001679,0.002536,-0.003235,0.002036,0.003532,-0.004425,0.013143,-0.007427,-0.004171,-0.000468,-0.000913,0.001933,-0.002325,0.000630,0.000581,6.379141e-03,0.006578,-0.002585,0.001304,0.000309,-0.003679,0.005114,0.000959,0.006436,-0.001623,0.002803,-0.002123,-0.005858,-0.006133,-0.002311,0.007461,-0.000805,0.002668,-0.001280,0.000017,-0.010527,-0.000093,0.003387,-0.006342,0.002187,0.011766,0.003520,-0.001063,0.011653,0.000762,-0.011055,-0.004149,-0.007150,-0.001393,0.002826,-0.000353,-0.000513,-0.000942,-0.008720,0.003468,0.003279,0.003641,0.003639,-0.002040,0.002732,-0.000433,-0.003323,0.001804,-0.005770,-0.001835,-0.002335,0.000823,0.003026,-0.001158,0.008056,0.006925,0.000996,0.009232,0.001435,0.000579,-0.006479,0.003151,-0.001989,0.014532,-0.022167,-0.007914,-0.002092,0.004466,0.004848,0.002090,0.001103,0.000242,0.002591,0.004103,-0.007558,-0.003729,0.001521,0.012131,-0.001522,0.002564,0.023272,0.019397,-0.006215,-0.004697,-0.002850,-0.001639,0.004864,-0.006087,-0.002197,-0.013788,0.004851,0.001668,0.002606,0.004054,0.003788,-0.000439,0.011203,0.016375,-0.001551,0.003961,0.003347,0.001230,-0.016974,0.002174,-0.003595,-0.000795,0.007811,-0.006879,0.008101,0.004178,0.006012,0.000477,-0.003477,0.003080,0.005034,0.006674,0.001389,-0.000301,-0.005110,0.004339,0.002103,-0.001982,0.015772,0.002886,-0.001976,0.009038,-0.007730,-0.001719,-0.017140,0.006772,0.012161,0.002219,0.020349,-0.008589,-0.002643,-0.008237,-0.001950,-0.005359,0.001246,0.005443,-0.015478,0.009527,0.001151,-0.003308,-0.008261,0.005451,0.007602,-0.007179,-0.005992,0.004449,-0.008162,0.002075,0.014467,-0.000986,0.008225,0.001816,1.854408,0.011508,0.102501,4.890471,-1.736255,2.945090,-1.381618
406273,2024-11-15 23:00:00,14,0.2,0.000,0.0,0.00,0.50,4.1,2.3,86.81,2.1,0.0,0.0,0.0,0.0,23.8,7.2,280.0,1019.1,100.0,0.0,0.0,0.0,False,True,False,False,4,23,Mykolaiv,2024-11-15,06:55:47,16:17:11,Миколаївська,1,60.000000,1.0,0.0,0.0,0.0,4.0,0,1,8.0,3.0,0,0.791371,0.136067,-0.050125,-0.090940,0.009791,-0.210883,0.125441,-0.211765,0.239236,0.168793,0.052587,0.021587,-0.010654,-0.002963,0.073039,0.043957,0.000608,-0.049307,-0.013122,-0.016723,0.050039,-0.025093,0.014843,-0.020563,0.014663,-0.010349,0.008200,0.013357,-0.005898,-0.001712,-0.052530,0.037593,0.011253,-0.013582,-0.015748,-0.023231,0.002914,0.037489,-0.009828,0.014626,-0.047918,-0.018142,0.014649,0.006605,0.006473,-0.029767,0.008214,-0.001165,-0.017059,0.032537,-0.027971,0.039424,-0.042916,-0.009016,0.013855,-0.023942,0.013314,-0.006255,0.019105,0.002035,-0.009155,0.008176,-0.001026,-0.005513,-0.026824,0.000352,-0.051066,0.025671,0.013987,0.022555,0.009333,0.042890,-0.001116,-0.028212,0.003706,-0.015001,-0.023660,0.022757,-0.001123,0.025039,0.001728,0.015307,0.018053,0.024167,0.009714,-0.012943,0.017648,0.001168,-0.015062,0.001629,-0.001970,0.004555,0.036054,0.025205,-0.005038,0.017426,0.021832,-0.019098,-0.032013,-0.008324,-0.007730,-0.040739,-0.017944,0.006813,-0.012607,0.026144,-0.004153,-0.012802,0.004154,0.000070,0.008228,-0.003853,0.002286,-0.004261,-0.002755,0.001414,0.015408,0.024186,-0.008764,-0.006171,-0.006886,-0.017053,-0.013831,0.004676,-0.006026,-0.016374,0.000096,-0.007926,-0.019797,-0.020719,0.013707,-0.005543,-0.001300,-0.000148,-0.006514,-0.019133,-0.021050,0.021078,-0.001980,0.007329,0.013577,-0.014521,-0.000623,-0.006653,0.010003,0.004017,-0.002497,-0.000141,-0.010808,-0.012717,4.206132,0.072735,0.791371,0.028041,-0.380962,4.257837,3.979233,0.067723,-0.014525,0.216246,0.058581,0.065805,-0.036703,-0.026605,0.029940,-0.039951,-0.009555,-0.027193,0.002508,-0.026613,-0.032594,0.007827,-0.007768,0.041424,-0.051922,0.008678,0.007975,-0.008277,0.017055,-0.049686,-0.003807,-0.077695,-0.035563,-0.028035,0.031773,0.010482,0.041173,-0.005763,-0.016595,0.018306,-0.052709,-0.029920,0.035856,0.021249,-0.043932,0.046176,0.011142,0.000092,0.024168,-0.071988,-0.019059,-0.011817,-0.010317,-0.024904,0.025017,-0.027695,-0.004565,-0.045314,0.008297,0.054899,-0.006050,0.024038,0.051635,0.038639,-0.047705,-0.010733,0.043750,0.011774,-0.001103,-0.022886,-0.037104,0.000641,-0.029584,0.015147,0.013945,0.015202,-0.005610,-0.017213,-0.007782,-0.033249,-0.008399,0.000099,0.017286,-0.018641,0.003765,-0.037295,-0.014763,0.042517,-0.002965,0.009413,-0.007034,0.006119,-0.016112,0.003420,-0.025598,0.003129,0.015964,-0.010830,0.005274,-0.011355,0.005980,2.505600e-07,-0.004149,-0.019453,0.019302,-0.015801,-0.001677,0.035899,0.027555,0.026468,-0.010311,-0.004491,0.020184,0.024506,-0.006442,0.001384,-0.007115,0.024704,-0.005839,0.038545,0.010041,0.010922,0.007269,0.005678,-0.007459,-0.026647,0.030831,-0.000832,-0.004788,-0.012505,0.006793,-0.004171,-0.008920,0.032079,-0.000364,0.055827,0.015780,0.020253,0.042745,-0.010881,-0.047654,-0.016893,-0.021781,0.017568,0.013050,0.035044,0.000687,0.006148,0.010788,0.010219,-0.008213,0.009298,-0.006518,-0.013990,0.010902,0.001467,0.004855,-0.014543,0.036818,0.021679,0.016390,-0.006121,0.003607,-0.000924,-0.006916,-0.013942,0.008718,0.003388,0.034858,-0.000745,-0.005412,-0.009166,0.007303,0.011212,0.002686,0.010258,-0.005402,0.001178,0.020955,0.005290,0.007556,0.021930,-0.012341,-0.018145,-0.017132,0.007461,-0.019142,-0.001284,-0.008633,-0.025900,0.011566,0.006591,0.009175,-0.002200,-0.007276,0.010326,-0.010096,0.005615,0.011752,0.021909,0.008578,0.006702,0.001649,0.013489,0.010670,0.003690,0.008296,0.005071,0.000112,0.003340,0.006338,-0.010791,0.010229,0.003679,0.023162,-0.001826,-0.002920,-0.008865,0.002958,-0.001296,-0.009202,0.002283,0.000080,0.003454,0.006679,-0.005501,0.004968,-0.014615,-0.003120,0.007182,0.001983,-0.004293,-0.007521,0.008506,-0.001216,-0.002824,-0.006372,-0.005580,0.001847,0.005472,0.006679,-0.001210,0.023544,-0.000518,0.000619,-0.006629,0.015261,-0.010613,-0.007033,-0.017763,-0.009825,0.010496,0.010022,0.001804,-0.008701,-0.011652,-0.010891,4.110056,0.019583,0.216246,5.057914,-1.013835,4.091311,0.193363
13403,2023-09-04 13:00:00,2,14.0,15.000,100.0,8.33,0.64,17.6,17.6,84.19,14.9,0.0,0.0,0.0,0.0,27.7,13.0,14.4,1023.0,100.0,143.8,0.5,1.0,False,True,False,False,0,13,Vinnytsia,2023-09-04,06:26:00,19:43:50,Вінницька,1,27.416667,0.0,0.0,0.0,0.0,1.0,0,0,3.0,0.0,9,0.780670,-0.078170,-0.030306,-0.162756,-0.092640,0.025452,-0.065059,0.100287,0.018315,-0.045577,0.049183,0.042227,0.183135,0.289444,0.074117,-0.108274,0.027852,0.040781,0.055644,-0.080048,0.002886,-0.044268,-0.030450,-0.024332,-0.006321,-0.021062,-0.000300,0.014952,-0.031638,0.019155,-0.005753,0.009270,-0.029013,0.007991,-0.069218,0.007422,-0.009432,0.060469,0.028937,0.014445,-0.015825,-0.004976,-0.047273,0.019625,0.005374,-0.043383,-0.001495,-0.004813,-0.006741,-0.029831,0.007163,0.000556,-0.048582,0.048305,0.011767,0.049083,-0.011579,-0.009633,-0.005142,0.009893,0.012317,0.017934,-0.009864,0.002526,-0.009022,-0.016325,0.000955,0.021691,0.034680,-0.005044,-0.025494,0.019341,0.000579,0.007752,0.012337,0.055754,-0.018931,-0.002420,0.012780,-0.016208,0.004438,0.022549,0.017104,0.003768,0.034169,0.002933,-0.006916,0.004624,-0.003368,0.000644,0.033746,-0.007571,0.003144,-0.003815,-0.005556,0.023210,-0.014424,-0.014257,-0.016752,0.020946,-0.018200,0.020733,0.013294,-0.011855,0.017165,-0.020861,0.019725,-0.001475,-0.017934,-0.002899,-0.018588,0.014595,-0.033696,-0.045279,0.002820,-0.008127,-0.037222,0.009263,0.023112,0.002835,0.019399,0.026968,0.013400,-0.013409,-0.039957,-0.026571,0.000579,-0.049195,-0.004959,0.011276,0.017463,0.041061,-0.060335,0.003513,0.005729,-0.015497,0.010633,0.001816,0.013124,0.014713,0.001082,0.002903,-0.017846,0.029757,0.000384,-0.006450,-0.011227,0.030330,0.026378,-0.007789,4.577601,0.070780,0.780670,0.030517,0.184435,4.530080,4.141029,0.026690,0.007117,0.036915,-0.008933,-0.061151,0.105788,-0.027858,0.055212,-0.045541,0.023465,-0.020428,0.025189,-0.023038,-0.045396,0.060157,-0.003598,-0.020055,0.006332,0.018524,-0.025866,-0.018204,-0.003062,-0.008705,0.016513,0.017245,-0.002001,-0.039775,-0.020341,0.006994,0.014030,-0.014561,0.002405,0.006607,-0.006733,0.003222,-0.008623,0.007777,-0.011942,-0.007786,-0.017566,-0.000437,-0.008692,0.003862,-0.058937,-0.030245,-0.043747,0.009451,0.066351,0.017592,-0.023418,-0.043830,-0.034762,-0.092116,0.097936,0.014986,0.008346,0.014880,0.032420,-0.013113,0.033038,-0.025787,-0.040280,-0.043543,0.030900,0.017677,0.046870,0.025031,0.006663,-0.022150,0.032485,-0.025563,-0.012167,0.005523,0.012736,0.004662,0.039079,-0.065309,0.000750,-0.002213,0.008379,-0.017930,0.029182,-0.010116,-0.047310,-0.026390,-0.041053,-0.000458,-0.002272,0.002145,0.045227,0.006676,-0.011377,-0.036436,0.030859,-3.067200e-02,-0.001527,0.005421,-0.022240,-0.019383,-0.013991,-0.005647,-0.019526,0.000007,-0.013556,0.032252,0.037121,-0.020868,-0.012173,0.014653,-0.014042,-0.036428,-0.008561,-0.007215,0.010769,0.004743,-0.008721,-0.016957,-0.001450,-0.008979,-0.026997,-0.020329,-0.016748,0.025226,-0.002752,-0.022470,0.014149,0.017950,-0.003590,-0.002374,0.006047,0.010033,-0.001669,-0.005547,-0.007151,-0.001178,0.023574,0.039760,0.005779,-0.038454,-0.032539,-0.013630,-0.030938,0.024502,0.014504,0.008709,-0.005692,0.007242,-0.025563,-0.000589,-0.013934,-0.004129,0.012918,-0.017384,0.003035,-0.008429,-0.003075,0.012042,0.003306,-0.005638,-0.007907,0.003202,0.007661,0.002653,0.005695,-0.006813,0.005995,-0.008853,-0.005662,0.002042,0.012324,-0.007752,-0.002726,-0.022561,-0.004321,-0.009729,0.007497,0.008140,-0.001570,0.004362,-0.003241,0.002844,0.019052,-0.005356,0.014333,-0.010539,-0.015157,-0.004055,-0.004085,-0.003048,-0.001241,0.005519,-0.006984,-0.002214,-0.001819,0.001219,-0.000799,-0.005429,-0.005342,0.003732,-0.005112,0.007343,-0.000790,0.013296,0.007751,-0.008599,-0.004239,-0.004244,-0.001087,0.002263,0.003611,0.001891,0.001808,-0.006766,-0.003874,-0.009483,0.007264,-0.013492,-0.008783,-0.018086,0.001954,-0.001103,0.011619,0.009061,-0.004510,0.011980,0.008866,0.016560,-0.002090,-0.017637,-0.004093,-0.005628,-0.001956,-0.002257,-0.003411,0.005936,0.020364,0.002844,-0.021288,-0.016539,0.012558,0.007097,0.016559,-0.001668,-0.000166,-0.014250,-0.005613,0.002695,0.021078,0.003807,0.003724,3.853343,0.016425,0.105788,5.077001,-0.588584,4.195735,-0.173878

# ТУТ БУДЕ EDA

## Weather, ISW, Telegram shift for further models trainings

In [54]:
df_to_train = df_final.copy()
df_to_train = df_to_train.sort_values(['region_id', 'datetime_hour'])

In [55]:
isw_cols = [c for c in df_to_train.columns if 'isw_' in c]
df_to_train[isw_cols] = df_to_train.groupby('region_id')[isw_cols].shift(24).fillna(0)

In [56]:
df_to_train.head()

,datetime_hour,region_id,day_dew,day_precip,day_precipprob,day_precipcover,day_moonphase,hour_temp,hour_feelslike,hour_humidity,hour_dew,hour_precip,hour_precipprob,hour_snow,hour_snowdepth,hour_windgust,hour_windspeed,hour_winddir,hour_pressure,hour_cloudcover,hour_solarradiation,hour_solarenergy,hour_uvindex,hour_conditions_simple_Clear,hour_conditions_simple_Cloudy,hour_conditions_simple_Rain,hour_conditions_simple_Snow,day_of_week,hour,city_name,day_datetime,day_sunrise,day_sunset,region_key,alarm_active,alarm_minutes_in_hour,alarm_lag_1,alarm_lag_3,alarm_lag_6,alarm_lag_12,alarms_in_last_24h,is_weekend,is_night,total_active_alarms_lag1,neighbour_alarms,hours_since_last_alarm,isw_topic_0,isw_topic_1,isw_topic_2,isw_topic_3,isw_topic_4,isw_topic_5,isw_topic_6,isw_topic_7,isw_topic_8,isw_topic_9,isw_topic_10,isw_topic_11,isw_topic_12,isw_topic_13,isw_topic_14,isw_topic_15,isw_topic_16,isw_topic_17,isw_topic_18,isw_topic_19,isw_topic_20,isw_topic_21,isw_topic_22,isw_topic_23,isw_topic_24,isw_topic_25,isw_topic_26,isw_topic_27,isw_topic_28,isw_topic_29,isw_topic_30,isw_topic_31,isw_topic_32,isw_topic_33,isw_topic_34,isw_topic_35,isw_topic_36,isw_topic_37,isw_topic_38,isw_topic_39,isw_topic_40,isw_topic_41,isw_topic_42,isw_topic_43,isw_topic_44,isw_topic_45,isw_topic_46,isw_topic_47,isw_topic_48,isw_topic_49,isw_topic_50,isw_topic_51,isw_topic_52,isw_topic_53,isw_topic_54,isw_topic_55,isw_topic_56,isw_topic_57,isw_topic_58,isw_topic_59,isw_topic_60,isw_topic_61,isw_topic_62,isw_topic_63,isw_topic_64,isw_topic_65,isw_topic_66,isw_topic_67,isw_topic_68,isw_topic_69,isw_topic_70,isw_topic_71,isw_topic_72,isw_topic_73,isw_topic_74,isw_topic_75,isw_topic_76,isw_topic_77,isw_topic_78,isw_topic_79,isw_topic_80,isw_topic_81,isw_topic_82,isw_topic_83,isw_topic_84,isw_topic_85,isw_topic_86,isw_topic_87,isw_topic_88,isw_topic_89,isw_topic_90,isw_topic_91,isw_topic_92,isw_topic_93,isw_topic_94,isw_topic_95,isw_topic_96,isw_topic_97,isw_topic_98,isw_topic_99,isw_topic_100,isw_topic_101,isw_topic_102,isw_topic_103,isw_topic_104,isw_topic_105,isw_topic_106,isw_topic_107,isw_topic_108,isw_topic_109,isw_topic_110,isw_topic_111,isw_topic_112,isw_topic_113,isw_topic_114,isw_topic_115,isw_topic_116,isw_topic_117,isw_topic_118,isw_topic_119,isw_topic_120,isw_topic_121,isw_topic_122,isw_topic_123,isw_topic_124,isw_topic_125,isw_topic_126,isw_topic_127,isw_topic_128,isw_topic_129,isw_topic_130,isw_topic_131,isw_topic_132,isw_topic_133,isw_topic_134,isw_topic_135,isw_topic_136,isw_topic_137,isw_topic_138,isw_topic_139,isw_topic_140,isw_topic_141,isw_topic_142,isw_topic_143,isw_topic_144,isw_topic_145,isw_topic_146,isw_topic_147,isw_topic_148,isw_topic_149,isw_total_intensity,isw_topic_std,isw_topic_max,isw_topic_mean,isw_velocity_24h,isw_intensity_ema,isw_topic_entropy,tg_topic_0,tg_topic_1,tg_topic_2,tg_topic_3,tg_topic_4,tg_topic_5,tg_topic_6,tg_topic_7,tg_topic_8,tg_topic_9,tg_topic_10,tg_topic_11,tg_topic_12,tg_topic_13,tg_topic_14,tg_topic_15,tg_topic_16,tg_topic_17,tg_topic_18,tg_topic_19,tg_topic_20,tg_topic_21,tg_topic_22,tg_topic_23,tg_topic_24,tg_topic_25,tg_topic_26,tg_topic_27,tg_topic_28,tg_topic_29,tg_topic_30,tg_topic_31,tg_topic_32,tg_topic_33,tg_topic_34,tg_topic_35,tg_topic_36,tg_topic_37,tg_topic_38,tg_topic_39,tg_topic_40,tg_topic_41,tg_topic_42,tg_topic_43,tg_topic_44,tg_topic_45,tg_topic_46,tg_topic_47,tg_topic_48,tg_topic_49,tg_topic_50,tg_topic_51,tg_topic_52,tg_topic_53,tg_topic_54,tg_topic_55,tg_topic_56,tg_topic_57,tg_topic_58,tg_topic_59,tg_topic_60,tg_topic_61,tg_topic_62,tg_topic_63,tg_topic_64,tg_topic_65,tg_topic_66,tg_topic_67,tg_topic_68,tg_topic_69,tg_topic_70,tg_topic_71,tg_topic_72,tg_topic_73,tg_topic_74,tg_topic_75,tg_topic_76,tg_topic_77,tg_topic_78,tg_topic_79,tg_topic_80,tg_topic_81,tg_topic_82,tg_topic_83,tg_topic_84,tg_topic_85,tg_topic_86,tg_topic_87,tg_topic_88,tg_topic_89,tg_topic_90,tg_topic_91,tg_topic_92,tg_topic_93,tg_topic_94,tg_topic_95,tg_topic_96,tg_topic_97,tg_topic_98,tg_topic_99,tg_topic_100,tg_topic_101,tg_topic_102,tg_topic_103,tg_topic_104,tg_topic_105,tg_topic_106,tg_topic_107,tg_topic_108,tg_topic_109,tg_topic_110,tg_topic_111,tg_topic_112,tg_topic_113,tg_topic_114,tg_topic_115,tg_topic_116,tg_topic_117,tg_topic_118,tg_topic_119,tg_topic_120,tg_topic_121,tg_topic_122,tg_topic_123,tg_topic_124,tg_topic_125,tg_topic_126,tg_topic_127,tg_topic_128,tg_topic_129,tg_topic_130,tg_topic_131,tg_topic_132,tg_topic_133,tg_topic_134,tg_topic_135,tg_topic_136,tg_topic_137,tg_topic_138,tg_topic_139,tg_topic_140,tg_topic_141,tg_topic_142,tg_topic_143,tg_topic_144,tg_topic_145,tg_topic_146,tg_topic_147,tg_topic_148,tg_topic_149,tg_topic_150,tg_topic_151,tg_topic_152,tg_topic_153,tg_topic_154,tg_topic_155,tg_topic_156,tg_topic_157,tg_topic_158,tg_topic_159,tg_topic_160,tg_topic_161,tg_topic_162,tg_topic_163,tg_topic_164,tg_topic_165,tg_topic_166,tg_topic_167,tg_topic_168,tg_topic_169,tg_topic_170,tg_topic_171,tg_topic_172,tg_topic_173,tg_topic_174,tg_topic_175,tg_topic_176,tg_topic_177,tg_topic_178,tg_topic_179,tg_topic_180,tg_topic_181,tg_topic_182,tg_topic_183,tg_topic_184,tg_topic_185,tg_topic_186,tg_topic_187,tg_topic_188,tg_topic_189,tg_topic_190,tg_topic_191,tg_topic_192,tg_topic_193,tg_topic_194,tg_topic_195,tg_topic_196,tg_topic_197,tg_topic_198,tg_topic_199,tg_topic_200,tg_topic_201,tg_topic_202,tg_topic_203,tg_topic_204,tg_topic_205,tg_topic_206,tg_topic_207,tg_topic_208,tg_topic_209,tg_topic_210,tg_topic_211,tg_topic_212,tg_topic_213,tg_topic_214,tg_topic_215,tg_topic_216,tg_topic_217,tg_topic_218,tg_topic_219,tg_topic_220,tg_topic_221,tg_topic_222,tg_topic_223,tg_topic_224,tg_topic_225,tg_topic_226,tg_topic_227,tg_topic_228,tg_topic_229,tg_topic_230,tg_topic_231,tg_topic_232,tg_topic_233,tg_topic_234,tg_topic_235,tg_topic_236,tg_topic_237,tg_topic_238,tg_topic_239,tg_topic_240,tg_topic_241,tg_topic_242,tg_topic_243,tg_topic_244,tg_topic_245,tg_topic_246,tg_topic_247,tg_topic_248,tg_topic_249,tg_total_intensity,tg_topic_std,tg_topic_max,tg_topic_entropy,tg_velocity_3h,tg_intensity_ema_6h,tg_intensity_zscore
0,2022-02-24 00:00:00,2,-0.3,0.3,100.0,4.17,0.77,2.1,-0.5,91.76,0.9,0.0,0.0,0.0,0.0,16.6,8.6,279.6,1021.0,91.1,0.0,0.1,0.0,False,True,False,False,3,0,Vinnytsia,2022-02-24,06:58:49,17:40:52,Вінницька,0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0.0,0.0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-0.0,0.0,0.0,NaN
1,2022-02-24 00:00:00,2,-0.3,0.3,100.0,4.17,0.77,2.1,-0.5,91.76,0.9,0.0,0.0,0.0,0.0,16.6,8.6,279.6,1021.0,91.1,0.0,0.1,0.0,False,True,False,False,3,0,Vinnytsia,2022-02-24,06:58:49,17:40:52,Вінницька,0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0.0,0.0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-0.0,0.0,0.0,0.0
3,2022-02-24 01:00:00,2,-0.3,0.3,100.0,4.17,0.77,2.1,-0.4,89.80,0.6,0.0,0.0,0.0,0.0,16.6,8.3,289.2,1021.0,97.9,0.0,0.1,0.0,False,True,False,False,3,1,Vinnytsia,2022-02-24,06:58:49,17:40:52,Вінницька,0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0.0,0.0,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-0.0,0.0,0.0,0.0
2,2022-02-24 01:00:00,2,-0.3,0.3,100.0,4.17,0.77,2.1,-0.4,89.80,0.6,0.0,0.0,0.0,0.0,16.6,8.3,289.2,1021.0,97.9,0.0,0.1,0.0,False,True,False,False,3,1,Vinnytsia,2022-02-24,06:58:49,17:40:52,Вінницька,0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0.0,0.0,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-0.0,0.0,0.0,0.0
5,2022-02-24 02:00:00,2,-0.3,0.3,100.0,4.17,0.77,2.0,-0.3,90.44,0.6,0.0,0.0,0.0,0.0,27.7,7.6,287.6,1021.0,98.2,0.0,0.1,0.0,False,True,False,False,3,2,Vinnytsia,2022-02-24,06:58:49,17:40:52,Вінницька,0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0.0,0.0,3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-0.0,0.0,0.0,0.0

In [57]:
tg_cols = [c for c in df_to_train.columns if 'tg_' in c]
df_to_train[tg_cols] = df_to_train.groupby('region_id')[tg_cols].shift(1).fillna(0)

In [58]:
df_to_train.head(5)

,datetime_hour,region_id,day_dew,day_precip,day_precipprob,day_precipcover,day_moonphase,hour_temp,hour_feelslike,hour_humidity,hour_dew,hour_precip,hour_precipprob,hour_snow,hour_snowdepth,hour_windgust,hour_windspeed,hour_winddir,hour_pressure,hour_cloudcover,hour_solarradiation,hour_solarenergy,hour_uvindex,hour_conditions_simple_Clear,hour_conditions_simple_Cloudy,hour_conditions_simple_Rain,hour_conditions_simple_Snow,day_of_week,hour,city_name,day_datetime,day_sunrise,day_sunset,region_key,alarm_active,alarm_minutes_in_hour,alarm_lag_1,alarm_lag_3,alarm_lag_6,alarm_lag_12,alarms_in_last_24h,is_weekend,is_night,total_active_alarms_lag1,neighbour_alarms,hours_since_last_alarm,isw_topic_0,isw_topic_1,isw_topic_2,isw_topic_3,isw_topic_4,isw_topic_5,isw_topic_6,isw_topic_7,isw_topic_8,isw_topic_9,isw_topic_10,isw_topic_11,isw_topic_12,isw_topic_13,isw_topic_14,isw_topic_15,isw_topic_16,isw_topic_17,isw_topic_18,isw_topic_19,isw_topic_20,isw_topic_21,isw_topic_22,isw_topic_23,isw_topic_24,isw_topic_25,isw_topic_26,isw_topic_27,isw_topic_28,isw_topic_29,isw_topic_30,isw_topic_31,isw_topic_32,isw_topic_33,isw_topic_34,isw_topic_35,isw_topic_36,isw_topic_37,isw_topic_38,isw_topic_39,isw_topic_40,isw_topic_41,isw_topic_42,isw_topic_43,isw_topic_44,isw_topic_45,isw_topic_46,isw_topic_47,isw_topic_48,isw_topic_49,isw_topic_50,isw_topic_51,isw_topic_52,isw_topic_53,isw_topic_54,isw_topic_55,isw_topic_56,isw_topic_57,isw_topic_58,isw_topic_59,isw_topic_60,isw_topic_61,isw_topic_62,isw_topic_63,isw_topic_64,isw_topic_65,isw_topic_66,isw_topic_67,isw_topic_68,isw_topic_69,isw_topic_70,isw_topic_71,isw_topic_72,isw_topic_73,isw_topic_74,isw_topic_75,isw_topic_76,isw_topic_77,isw_topic_78,isw_topic_79,isw_topic_80,isw_topic_81,isw_topic_82,isw_topic_83,isw_topic_84,isw_topic_85,isw_topic_86,isw_topic_87,isw_topic_88,isw_topic_89,isw_topic_90,isw_topic_91,isw_topic_92,isw_topic_93,isw_topic_94,isw_topic_95,isw_topic_96,isw_topic_97,isw_topic_98,isw_topic_99,isw_topic_100,isw_topic_101,isw_topic_102,isw_topic_103,isw_topic_104,isw_topic_105,isw_topic_106,isw_topic_107,isw_topic_108,isw_topic_109,isw_topic_110,isw_topic_111,isw_topic_112,isw_topic_113,isw_topic_114,isw_topic_115,isw_topic_116,isw_topic_117,isw_topic_118,isw_topic_119,isw_topic_120,isw_topic_121,isw_topic_122,isw_topic_123,isw_topic_124,isw_topic_125,isw_topic_126,isw_topic_127,isw_topic_128,isw_topic_129,isw_topic_130,isw_topic_131,isw_topic_132,isw_topic_133,isw_topic_134,isw_topic_135,isw_topic_136,isw_topic_137,isw_topic_138,isw_topic_139,isw_topic_140,isw_topic_141,isw_topic_142,isw_topic_143,isw_topic_144,isw_topic_145,isw_topic_146,isw_topic_147,isw_topic_148,isw_topic_149,isw_total_intensity,isw_topic_std,isw_topic_max,isw_topic_mean,isw_velocity_24h,isw_intensity_ema,isw_topic_entropy,tg_topic_0,tg_topic_1,tg_topic_2,tg_topic_3,tg_topic_4,tg_topic_5,tg_topic_6,tg_topic_7,tg_topic_8,tg_topic_9,tg_topic_10,tg_topic_11,tg_topic_12,tg_topic_13,tg_topic_14,tg_topic_15,tg_topic_16,tg_topic_17,tg_topic_18,tg_topic_19,tg_topic_20,tg_topic_21,tg_topic_22,tg_topic_23,tg_topic_24,tg_topic_25,tg_topic_26,tg_topic_27,tg_topic_28,tg_topic_29,tg_topic_30,tg_topic_31,tg_topic_32,tg_topic_33,tg_topic_34,tg_topic_35,tg_topic_36,tg_topic_37,tg_topic_38,tg_topic_39,tg_topic_40,tg_topic_41,tg_topic_42,tg_topic_43,tg_topic_44,tg_topic_45,tg_topic_46,tg_topic_47,tg_topic_48,tg_topic_49,tg_topic_50,tg_topic_51,tg_topic_52,tg_topic_53,tg_topic_54,tg_topic_55,tg_topic_56,tg_topic_57,tg_topic_58,tg_topic_59,tg_topic_60,tg_topic_61,tg_topic_62,tg_topic_63,tg_topic_64,tg_topic_65,tg_topic_66,tg_topic_67,tg_topic_68,tg_topic_69,tg_topic_70,tg_topic_71,tg_topic_72,tg_topic_73,tg_topic_74,tg_topic_75,tg_topic_76,tg_topic_77,tg_topic_78,tg_topic_79,tg_topic_80,tg_topic_81,tg_topic_82,tg_topic_83,tg_topic_84,tg_topic_85,tg_topic_86,tg_topic_87,tg_topic_88,tg_topic_89,tg_topic_90,tg_topic_91,tg_topic_92,tg_topic_93,tg_topic_94,tg_topic_95,tg_topic_96,tg_topic_97,tg_topic_98,tg_topic_99,tg_topic_100,tg_topic_101,tg_topic_102,tg_topic_103,tg_topic_104,tg_topic_105,tg_topic_106,tg_topic_107,tg_topic_108,tg_topic_109,tg_topic_110,tg_topic_111,tg_topic_112,tg_topic_113,tg_topic_114,tg_topic_115,tg_topic_116,tg_topic_117,tg_topic_118,tg_topic_119,tg_topic_120,tg_topic_121,tg_topic_122,tg_topic_123,tg_topic_124,tg_topic_125,tg_topic_126,tg_topic_127,tg_topic_128,tg_topic_129,tg_topic_130,tg_topic_131,tg_topic_132,tg_topic_133,tg_topic_134,tg_topic_135,tg_topic_136,tg_topic_137,tg_topic_138,tg_topic_139,tg_topic_140,tg_topic_141,tg_topic_142,tg_topic_143,tg_topic_144,tg_topic_145,tg_topic_146,tg_topic_147,tg_topic_148,tg_topic_149,tg_topic_150,tg_topic_151,tg_topic_152,tg_topic_153,tg_topic_154,tg_topic_155,tg_topic_156,tg_topic_157,tg_topic_158,tg_topic_159,tg_topic_160,tg_topic_161,tg_topic_162,tg_topic_163,tg_topic_164,tg_topic_165,tg_topic_166,tg_topic_167,tg_topic_168,tg_topic_169,tg_topic_170,tg_topic_171,tg_topic_172,tg_topic_173,tg_topic_174,tg_topic_175,tg_topic_176,tg_topic_177,tg_topic_178,tg_topic_179,tg_topic_180,tg_topic_181,tg_topic_182,tg_topic_183,tg_topic_184,tg_topic_185,tg_topic_186,tg_topic_187,tg_topic_188,tg_topic_189,tg_topic_190,tg_topic_191,tg_topic_192,tg_topic_193,tg_topic_194,tg_topic_195,tg_topic_196,tg_topic_197,tg_topic_198,tg_topic_199,tg_topic_200,tg_topic_201,tg_topic_202,tg_topic_203,tg_topic_204,tg_topic_205,tg_topic_206,tg_topic_207,tg_topic_208,tg_topic_209,tg_topic_210,tg_topic_211,tg_topic_212,tg_topic_213,tg_topic_214,tg_topic_215,tg_topic_216,tg_topic_217,tg_topic_218,tg_topic_219,tg_topic_220,tg_topic_221,tg_topic_222,tg_topic_223,tg_topic_224,tg_topic_225,tg_topic_226,tg_topic_227,tg_topic_228,tg_topic_229,tg_topic_230,tg_topic_231,tg_topic_232,tg_topic_233,tg_topic_234,tg_topic_235,tg_topic_236,tg_topic_237,tg_topic_238,tg_topic_239,tg_topic_240,tg_topic_241,tg_topic_242,tg_topic_243,tg_topic_244,tg_topic_245,tg_topic_246,tg_topic_247,tg_topic_248,tg_topic_249,tg_total_intensity,tg_topic_std,tg_topic_max,tg_topic_entropy,tg_velocity_3h,tg_intensity_ema_6h,tg_intensity_zscore
0,2022-02-24 00:00:00,2,-0.3,0.3,100.0,4.17,0.77,2.1,-0.5,91.76,0.9,0.0,0.0,0.0,0.0,16.6,8.6,279.6,1021.0,91.1,0.0,0.1,0.0,False,True,False,False,3,0,Vinnytsia,2022-02-24,06:58:49,17:40:52,Вінницька,0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0.0,0.0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2022-02-24 00:00:00,2,-0.3,0.3,100.0,4.17,0.77,2.1,-0.5,91.76,0.9,0.0,0.0,0.0,0.0,16.6,8.6,279.6,1021.0,91.1,0.0,0.1,0.0,False,True,False,False,3,0,Vinnytsia,2022-02-24,06:58:49,17:40:52,Вінницька,0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0.0,0.0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-0.0,0.0,0.0,0.0
3,2022-02-24 01:00:00,2,-0.3,0.3,100.0,4.17,0.77,2.1,-0.4,89.80,0.6,0.0,0.0,0.0,0.0,16.6,8.3,289.2,1021.0,97.9,0.0,0.1,0.0,False,True,False,False,3,1,Vinnytsia,2022-02-24,06:58:49,17:40:52,Вінницька,0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0.0,0.0,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-0.0,0.0,0.0,0.0
2,2022-02-24 01:00:00,2,-0.3,0.3,100.0,4.17,0.77,2.1,-0.4,89.80,0.6,0.0,0.0,0.0,0.0,16.6,8.3,289.2,1021.0,97.9,0.0,0.1,0.0,False,True,False,False,3,1,Vinnytsia,2022-02-24,06:58:49,17:40:52,Вінницька,0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0.0,0.0,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-0.0,0.0,0.0,0.0
5,2022-02-24 02:00:00,2,-0.3,0.3,100.0,4.17,0.77,2.0,-0.3,90.44,0.6,0.0,0.0,0.0,0.0,27.7,7.6,287.6,1021.0,98.2,0.0,0.1,0.0,False,True,False,False,3,2,Vinnytsia,2022-02-24,06:58:49,17:40:52,Вінницька,0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0.0,0.0,3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-0.0,0.0,0.0,0.0

In [59]:
hour_weather_cols = [c for c in df_to_train.columns if c.startswith('hour_')]
for col in hour_weather_cols:
    if df_to_train[col].dtype == bool:
        df_to_train[col] = df_to_train.groupby('region_id')[col].shift(1).fillna(False)
    else:
        df_to_train[col] = df_to_train.groupby('region_id')[col].shift(1).fillna(0)

In [63]:
day_weather_cols = [c for c in df_to_train.columns if (c.startswith('day_') and c not in ['day_datetime', 'day_sunrise', 'day_sunset', 'day_moonphase', 'day_of_week'])]
df_to_train[day_weather_cols] = df_to_train.groupby('region_id')[day_weather_cols].shift(24).fillna(0)

In [64]:
df_to_train.isna().sum()

datetime_hour          0
region_id              0
day_dew                0
day_precip             0
day_precipprob         0
                      ..
tg_topic_max           0
tg_topic_entropy       0
tg_velocity_3h         0
tg_intensity_ema_6h    0
tg_intensity_zscore    0
Length: 460, dtype: int64

In [65]:
df_to_train['alarm_minutes_in_hour'] = (df_to_train.groupby('region_id')['alarm_minutes_in_hour'].shift(1).fillna(0))

In [66]:
df_to_train.head()

,datetime_hour,region_id,day_dew,day_precip,day_precipprob,day_precipcover,day_moonphase,hour_temp,hour_feelslike,hour_humidity,hour_dew,hour_precip,hour_precipprob,hour_snow,hour_snowdepth,hour_windgust,hour_windspeed,hour_winddir,hour_pressure,hour_cloudcover,hour_solarradiation,hour_solarenergy,hour_uvindex,hour_conditions_simple_Clear,hour_conditions_simple_Cloudy,hour_conditions_simple_Rain,hour_conditions_simple_Snow,day_of_week,hour,city_name,day_datetime,day_sunrise,day_sunset,region_key,alarm_active,alarm_minutes_in_hour,alarm_lag_1,alarm_lag_3,alarm_lag_6,alarm_lag_12,alarms_in_last_24h,is_weekend,is_night,total_active_alarms_lag1,neighbour_alarms,hours_since_last_alarm,isw_topic_0,isw_topic_1,isw_topic_2,isw_topic_3,isw_topic_4,isw_topic_5,isw_topic_6,isw_topic_7,isw_topic_8,isw_topic_9,isw_topic_10,isw_topic_11,isw_topic_12,isw_topic_13,isw_topic_14,isw_topic_15,isw_topic_16,isw_topic_17,isw_topic_18,isw_topic_19,isw_topic_20,isw_topic_21,isw_topic_22,isw_topic_23,isw_topic_24,isw_topic_25,isw_topic_26,isw_topic_27,isw_topic_28,isw_topic_29,isw_topic_30,isw_topic_31,isw_topic_32,isw_topic_33,isw_topic_34,isw_topic_35,isw_topic_36,isw_topic_37,isw_topic_38,isw_topic_39,isw_topic_40,isw_topic_41,isw_topic_42,isw_topic_43,isw_topic_44,isw_topic_45,isw_topic_46,isw_topic_47,isw_topic_48,isw_topic_49,isw_topic_50,isw_topic_51,isw_topic_52,isw_topic_53,isw_topic_54,isw_topic_55,isw_topic_56,isw_topic_57,isw_topic_58,isw_topic_59,isw_topic_60,isw_topic_61,isw_topic_62,isw_topic_63,isw_topic_64,isw_topic_65,isw_topic_66,isw_topic_67,isw_topic_68,isw_topic_69,isw_topic_70,isw_topic_71,isw_topic_72,isw_topic_73,isw_topic_74,isw_topic_75,isw_topic_76,isw_topic_77,isw_topic_78,isw_topic_79,isw_topic_80,isw_topic_81,isw_topic_82,isw_topic_83,isw_topic_84,isw_topic_85,isw_topic_86,isw_topic_87,isw_topic_88,isw_topic_89,isw_topic_90,isw_topic_91,isw_topic_92,isw_topic_93,isw_topic_94,isw_topic_95,isw_topic_96,isw_topic_97,isw_topic_98,isw_topic_99,isw_topic_100,isw_topic_101,isw_topic_102,isw_topic_103,isw_topic_104,isw_topic_105,isw_topic_106,isw_topic_107,isw_topic_108,isw_topic_109,isw_topic_110,isw_topic_111,isw_topic_112,isw_topic_113,isw_topic_114,isw_topic_115,isw_topic_116,isw_topic_117,isw_topic_118,isw_topic_119,isw_topic_120,isw_topic_121,isw_topic_122,isw_topic_123,isw_topic_124,isw_topic_125,isw_topic_126,isw_topic_127,isw_topic_128,isw_topic_129,isw_topic_130,isw_topic_131,isw_topic_132,isw_topic_133,isw_topic_134,isw_topic_135,isw_topic_136,isw_topic_137,isw_topic_138,isw_topic_139,isw_topic_140,isw_topic_141,isw_topic_142,isw_topic_143,isw_topic_144,isw_topic_145,isw_topic_146,isw_topic_147,isw_topic_148,isw_topic_149,isw_total_intensity,isw_topic_std,isw_topic_max,isw_topic_mean,isw_velocity_24h,isw_intensity_ema,isw_topic_entropy,tg_topic_0,tg_topic_1,tg_topic_2,tg_topic_3,tg_topic_4,tg_topic_5,tg_topic_6,tg_topic_7,tg_topic_8,tg_topic_9,tg_topic_10,tg_topic_11,tg_topic_12,tg_topic_13,tg_topic_14,tg_topic_15,tg_topic_16,tg_topic_17,tg_topic_18,tg_topic_19,tg_topic_20,tg_topic_21,tg_topic_22,tg_topic_23,tg_topic_24,tg_topic_25,tg_topic_26,tg_topic_27,tg_topic_28,tg_topic_29,tg_topic_30,tg_topic_31,tg_topic_32,tg_topic_33,tg_topic_34,tg_topic_35,tg_topic_36,tg_topic_37,tg_topic_38,tg_topic_39,tg_topic_40,tg_topic_41,tg_topic_42,tg_topic_43,tg_topic_44,tg_topic_45,tg_topic_46,tg_topic_47,tg_topic_48,tg_topic_49,tg_topic_50,tg_topic_51,tg_topic_52,tg_topic_53,tg_topic_54,tg_topic_55,tg_topic_56,tg_topic_57,tg_topic_58,tg_topic_59,tg_topic_60,tg_topic_61,tg_topic_62,tg_topic_63,tg_topic_64,tg_topic_65,tg_topic_66,tg_topic_67,tg_topic_68,tg_topic_69,tg_topic_70,tg_topic_71,tg_topic_72,tg_topic_73,tg_topic_74,tg_topic_75,tg_topic_76,tg_topic_77,tg_topic_78,tg_topic_79,tg_topic_80,tg_topic_81,tg_topic_82,tg_topic_83,tg_topic_84,tg_topic_85,tg_topic_86,tg_topic_87,tg_topic_88,tg_topic_89,tg_topic_90,tg_topic_91,tg_topic_92,tg_topic_93,tg_topic_94,tg_topic_95,tg_topic_96,tg_topic_97,tg_topic_98,tg_topic_99,tg_topic_100,tg_topic_101,tg_topic_102,tg_topic_103,tg_topic_104,tg_topic_105,tg_topic_106,tg_topic_107,tg_topic_108,tg_topic_109,tg_topic_110,tg_topic_111,tg_topic_112,tg_topic_113,tg_topic_114,tg_topic_115,tg_topic_116,tg_topic_117,tg_topic_118,tg_topic_119,tg_topic_120,tg_topic_121,tg_topic_122,tg_topic_123,tg_topic_124,tg_topic_125,tg_topic_126,tg_topic_127,tg_topic_128,tg_topic_129,tg_topic_130,tg_topic_131,tg_topic_132,tg_topic_133,tg_topic_134,tg_topic_135,tg_topic_136,tg_topic_137,tg_topic_138,tg_topic_139,tg_topic_140,tg_topic_141,tg_topic_142,tg_topic_143,tg_topic_144,tg_topic_145,tg_topic_146,tg_topic_147,tg_topic_148,tg_topic_149,tg_topic_150,tg_topic_151,tg_topic_152,tg_topic_153,tg_topic_154,tg_topic_155,tg_topic_156,tg_topic_157,tg_topic_158,tg_topic_159,tg_topic_160,tg_topic_161,tg_topic_162,tg_topic_163,tg_topic_164,tg_topic_165,tg_topic_166,tg_topic_167,tg_topic_168,tg_topic_169,tg_topic_170,tg_topic_171,tg_topic_172,tg_topic_173,tg_topic_174,tg_topic_175,tg_topic_176,tg_topic_177,tg_topic_178,tg_topic_179,tg_topic_180,tg_topic_181,tg_topic_182,tg_topic_183,tg_topic_184,tg_topic_185,tg_topic_186,tg_topic_187,tg_topic_188,tg_topic_189,tg_topic_190,tg_topic_191,tg_topic_192,tg_topic_193,tg_topic_194,tg_topic_195,tg_topic_196,tg_topic_197,tg_topic_198,tg_topic_199,tg_topic_200,tg_topic_201,tg_topic_202,tg_topic_203,tg_topic_204,tg_topic_205,tg_topic_206,tg_topic_207,tg_topic_208,tg_topic_209,tg_topic_210,tg_topic_211,tg_topic_212,tg_topic_213,tg_topic_214,tg_topic_215,tg_topic_216,tg_topic_217,tg_topic_218,tg_topic_219,tg_topic_220,tg_topic_221,tg_topic_222,tg_topic_223,tg_topic_224,tg_topic_225,tg_topic_226,tg_topic_227,tg_topic_228,tg_topic_229,tg_topic_230,tg_topic_231,tg_topic_232,tg_topic_233,tg_topic_234,tg_topic_235,tg_topic_236,tg_topic_237,tg_topic_238,tg_topic_239,tg_topic_240,tg_topic_241,tg_topic_242,tg_topic_243,tg_topic_244,tg_topic_245,tg_topic_246,tg_topic_247,tg_topic_248,tg_topic_249,tg_total_intensity,tg_topic_std,tg_topic_max,tg_topic_entropy,tg_velocity_3h,tg_intensity_ema_6h,tg_intensity_zscore
0,2022-02-24 00:00:00,2,0.0,0.0,0.0,0.0,0.77,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,False,False,False,False,3,0,Vinnytsia,2022-02-24,06:58:49,17:40:52,Вінницька,0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0.0,0.0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2022-02-24 00:00:00,2,0.0,0.0,0.0,0.0,0.77,2.1,-0.5,91.76,0.9,0.0,0.0,0.0,0.0,16.6,8.6,279.6,1021.0,91.1,0.0,0.1,0.0,False,True,False,False,3,0,Vinnytsia,2022-02-24,06:58:49,17:40:52,Вінницька,0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0.0,0.0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-0.0,0.0,0.0,0.0
3,2022-02-24 01:00:00,2,0.0,0.0,0.0,0.0,0.77,2.1,-0.5,91.76,0.9,0.0,0.0,0.0,0.0,16.6,8.6,279.6,1021.0,91.1,0.0,0.1,0.0,False,True,False,False,3,1,Vinnytsia,2022-02-24,06:58:49,17:40:52,Вінницька,0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0.0,0.0,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-0.0,0.0,0.0,0.0
2,2022-02-24 01:00:00,2,0.0,0.0,0.0,0.0,0.77,2.1,-0.4,89.80,0.6,0.0,0.0,0.0,0.0,16.6,8.3,289.2,1021.0,97.9,0.0,0.1,0.0,False,True,False,False,3,1,Vinnytsia,2022-02-24,06:58:49,17:40:52,Вінницька,0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0.0,0.0,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-0.0,0.0,0.0,0.0
5,2022-02-24 02:00:00,2,0.0,0.0,0.0,0.0,0.77,2.1,-0.4,89.80,0.6,0.0,0.0,0.0,0.0,16.6,8.3,289.2,1021.0,97.9,0.0,0.1,0.0,False,True,False,False,3,2,Vinnytsia,2022-02-24,06:58:49,17:40:52,Вінницька,0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0.0,0.0,3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-0.0,0.0,0.0,0.0

In [67]:
df_to_train.to_parquet("final_merged_dataset.parquet", index = False, engine = "pyarrow")