# Data merge and feature engineering

In [1]:
%pip install pyarrow

Requirement already satisfied: pyarrow in c:\users\uw11\appdata\local\programs\python\python313\lib\site-packages (23.0.1)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.3.1 -> 26.0.1
[notice] To update, run: C:\Users\Uw11\AppData\Local\Programs\Python\Python313\python.exe -m pip install --upgrade pip

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import string

import re
import nltk
from nltk.stem import WordNetLemmatizer
from nltk.corpus import stopwords
from sklearn.feature_extraction.text import TfidfVectorizer
from tqdm.notebook import tqdm
from tqdm import tqdm
import pymorphy3
from collections import Counter

import os
from pathlib import Path
import json

In [3]:
df_weather = pd.read_csv("../data/weather_processed.csv")
df_war_events = pd.read_csv("../data/war_events_processed.csv")
df_isw_matrix = pd.read_csv("../data/isw_processed_svd.csv")

In [4]:
pd.set_option('display.max_columns', None)

In [5]:
df_weather['datetime_hour'] = pd.to_datetime(df_weather['datetime_hour'], errors="coerce")
df_war_events['datetime_hour'] = pd.to_datetime(df_war_events['datetime_hour'], errors="coerce")

In [6]:
df_final = pd.merge(
    df_weather, 
    df_war_events[['datetime_hour', 'region_id', 'alarm_active', 'alarm_minutes_in_hour']], 
    on=['datetime_hour', 'region_id'], 
    how='left'
)
df_final.sample(20)

,datetime_hour,region_id,city_latitude,city_longitude,day_temp,day_dew,day_humidity,day_precip,day_precipprob,day_precipcover,day_snow,day_snowdepth,day_windgust,day_windspeed,day_winddir,day_pressure,day_cloudcover,day_solarradiation,day_solarenergy,day_uvindex,day_moonphase,hour_temp,hour_feelslike,hour_humidity,hour_precip,hour_precipprob,hour_snow,hour_windgust,hour_windspeed,hour_winddir,hour_pressure,hour_cloudcover,hour_solarradiation,hour_solarenergy,hour_uvindex,day_conditions_simple_Clear,day_conditions_simple_Cloudy,day_conditions_simple_Rain,day_conditions_simple_Snow,hour_conditions_simple_Clear,hour_conditions_simple_Cloudy,hour_conditions_simple_Rain,hour_conditions_simple_Snow,year,month,day_of_week,hour,city_name,city_timezone,day_datetime,day_sunrise,day_sunset,hour_datetime,region_key,alarm_active,alarm_minutes_in_hour
456014,2024-04-25 19:00:00,17,50.61930,26.25130,9.2,5.5,80.0,0.043,100.0,4.17,0.0,0.0,36.7,24.9,245.2,1006.6,83.0,176.0,15.2,5.0,0.55,12.3,12.3,59.76,0.0,0.0,0.0,19.1,10.4,288.2,1008.0,100.0,100.2,0.4,1.0,False,False,True,False,False,True,False,False,2024,4,3,19,Rivne,Europe/Kiev,2024-04-25,06:00:12,20:26:44,19:00:00,Рівненська,0,0.000000
124512,2022-09-28 05:00:00,2,49.23360,28.44860,12.0,10.7,92.0,4.700,100.0,25.00,0.0,0.0,31.0,14.0,208.7,1002.2,73.2,58.4,4.9,3.0,0.07,9.4,9.4,99.33,0.0,0.0,0.0,5.0,2.5,137.1,1001.0,100.0,0.0,0.1,0.0,False,False,True,False,False,True,False,False,2022,9,2,5,Vinnytsia,Europe/Kiev,2022-09-28,07:01:05,18:51:54,05:00:00,Вінницька,0,0.000000
111353,2022-09-05 08:00:00,20,50.00420,36.23580,12.0,4.6,62.5,0.700,100.0,16.67,0.0,0.0,27.4,18.0,327.6,1021.0,67.0,146.8,12.7,6.0,0.29,11.0,11.0,71.27,0.0,0.0,0.0,6.5,7.2,20.0,1022.0,96.1,90.0,0.3,1.0,False,False,True,False,False,True,False,False,2022,9,0,8,Kharkiv,Europe/Kiev,2022-09-05,05:55:37,19:11:03,08:00:00,Харківська,0,0.000000
78740,2022-07-10 17:00:00,23,49.44070,32.06370,20.8,15.9,75.1,0.900,100.0,20.83,0.0,0.0,34.2,19.1,341.9,1007.5,68.2,253.5,21.9,7.0,0.36,24.3,24.3,59.45,0.1,100.0,0.0,29.9,15.1,355.0,1006.0,39.0,572.0,2.1,6.0,False,False,True,False,False,False,True,False,2022,7,6,17,Cherkasy,Europe/Kiev,2022-07-10,04:56:35,20:57:12,17:00:00,Черкаська,0,0.000000
50976,2022-05-23 13:00:00,2,49.23360,28.44860,11.5,7.4,76.7,2.400,100.0,33.33,0.0,0.0,32.8,15.8,341.7,1010.1,84.3,187.2,16.1,8.0,0.74,13.4,13.4,64.31,0.0,0.0,0.0,24.5,11.9,47.4,1010.0,99.9,811.0,2.9,8.0,False,False,True,False,False,True,False,False,2022,5,0,13,Vinnytsia,Europe/Kiev,2022-05-23,05:13:47,20:52:56,13:00:00,Вінницька,0,0.000000
415253,2024-02-15 00:00:00,7,48.62640,22.28510,2.1,-1.1,81.0,0.000,0.0,0.00,0.0,6.2,15.1,7.2,162.9,1025.4,40.3,104.0,8.9,4.0,0.19,-1.2,-1.2,91.13,0.0,0.0,0.0,9.4,3.7,123.0,1025.0,29.0,0.0,0.0,0.0,False,True,False,False,False,True,False,False,2024,2,3,0,Uzhgorod,Europe/Uzhgorod,2024-02-15,07:39:43,17:51:06,00:00:00,Закарпатська,0,0.000000
584918,2024-12-05 14:00:00,17,50.61930,26.25130,-0.8,-2.2,90.0,0.000,0.0,0.00,0.0,0.0,23.0,14.4,131.3,1028.8,99.2,15.8,1.4,1.0,0.15,-0.9,-4.5,87.54,0.0,0.0,0.0,19.1,10.8,150.0,1029.3,100.0,64.0,0.2,1.0,False,True,False,False,False,True,False,False,2024,12,3,14,Rivne,Europe/Kiev,2024-12-05,08:00:05,16:11:19,14:00:00,Рівненська,0,0.000000
624785,2025-02-12 19:00:00,20,50.00420,36.23580,-9.0,-11.6,82.3,0.000,0.0,0.00,0.0,2.4,20.9,10.8,353.1,1034.2,78.9,86.8,7.4,4.0,0.50,-7.0,-7.0,73.13,0.0,0.0,0.0,8.6,3.6,270.0,1031.0,92.2,0.0,0.0,0.0,False,True,False,False,False,True,False,False,2025,2,2,19,Kharkiv,Europe/Kiev,2025-02-12,06:50:53,16:48:30,19:00:00,Харківська,1,21.150000
52045,2022-05-25 09:00:00,16,49.58790,34.55170,16.7,3.3,43.5,0.000,0.0,0.00,0.0,0.0,30.2,12.2,287.7,1015.7,67.5,202.9,17.7,9.0,0.81,17.7,17.7,37.19,0.0,0.0,0.0,19.8,10.8,300.0,1015.9,10.0,526.0,1.9,5.0,False,True,False,False,True,False,False,False,2022,5,2,9,Poltava,Europe/Kiev,2022-05-25,04:45:51,20:32:24,09:00:00,Полтавська,1,24.500000
54360,2022-05-29 10:00:00,2,49.23360,28.44860,13.7,3.5,52.2,0.300,100.0,4.17,0.0,0.0,24.8,11.5,243.5,1014.2,64.0,324.3,27.9,9.0,0.95,14.1,14.1,51.31,0.0,0.0,0.0,24.4,11.0,298.8,1015.0,89.5,629.0,2.3,6.0,False,False,True,False,False,True,False,False,2022,5,6,10,Vinnytsia,Europe/Kiev,2022-05-29,05:08:06,20:59:49,10:00:00,Вінницька,0,0.000000
592300,2024-12-18 10:00:00,6,50.25360,28.66540,3.1,0.2,81.6,0.000,0.0,0.00,0.0,0.8,45.7,25.9,288.4,1018.4,66.4,38.0,3.3,2.0,0.60,3.5,-0.9,79.57,0.0,0.0,0.0,37.8,20.5,299.8,1019.0,43.2,89.9,0.3,1.0,False,True,False,False,False,True,False,False,2024,12,2,10,Zhytomyr,Europe/Kiev,2024-12-18,08:01:02,16:03:18,10:00:00,Житомирська,0,0.000000
192175,2023-01-23 16:00:00,9,48.92260,24.71470,2.8,2.1,95.6,0.000,0.0,0.00,0.0,0.6,33.1,16.2,106.6,1034.1,99.9,36.0,3.0,2.0,0.05,2.3,-1.6,87.89,0.0,0.0,0.0,28.8,14.8,112.9,1035.0,100.0,84.5,0.3,1.0,False,True,False,False,False,True,False,False,2023,1,0,16,Ivano-Frankivsk,Europe/Kiev,2023-01-23,08:02:56,17:03:25,16:00:00,Івано-Франківська,0,0.000000
65789,2022-06-18 06:00:00,7,48.62636,22.28514,19.1,8.9,55.1,0.035,100.0,4.17,0.0,0.0,19.4,7.9,314.4,1021.2,16.1,297.3,25.7,8.0,0.62,10.7,10.7,85.31,0.0,0.0,0.0,8.3,4.1,314.0,1022.7,1.4,5.0,0.0,0.0,False,False,True,False,True,False,False,False,2022,6,5,6,Uzhgorod,Europe/Uzhgorod,2022-06-18,05:27:58,21:36:11,06:00:00,Закарпатська,0,0.000000
344555,2023-10-15 06:00:00,14,46.97340,31.98520,15.1,12.2,84.5,0.000,0.0,0.00,0.0,0.0,37.4,19.4,186.1,1011.5,32.5,116.2,10.3,5.0,0.02,9.1,9.1,98.66,0.0,0.0,0.0,17.6,0.0,167.6,1013.9,88.4,0.0,0.0,0.0,False,True,False,False,False,True,False,False,2023,10,6,6,Mykolaiv,Europe/Kiev,2023-10-15,07:09:22,18:05:46,06:00:00,Миколаївська,0,0.000000
259612,2023-05-20 19:00:00,6,50.25360,28.66540,17.8,8.8,59.7,0.000,0.0,0.00,0.0,0.0,41.4,20.5,36.2,1024.2,26.1,311.2,26.9,8.0,0.02,22.3,22.3,34.51,0.0,0.0,0.0,37.1,16.6,39.9,1023.0,0.0,271.1,1.0,3.0,False,True,False,False,True,False,False,False,2023,5,5,19,Zhytomyr,Europe/Kiev,2023-05-20,05:12:29,20:52:10,19:00:00,Житомирська,0,0.000000
47262,2022-05-17 02:00:00,8,47.82890,35.16260,16.0,4.2,47.8,0.000,0.0,0.00,0.0,0.0,36.7,18.4,299.0,1014.1,79.6,280.8,24.1,9.0,0.54,12.9,12.9,67.36,0.0,0.0,0.0,8.6,5.0,251.4,1015.0,99.9,0.0,0.1,0.0,False,True,False,False,False,True,False,False,2022,5,1,2,Zaporozhye,Europe/Zaporozhye,2022-05-17,04:59:06,20:13:14,02:00:00,Запорізька,1,26.050000
61543,2022-06-10 21:00:00,9,48.92260,24.71470,20.7,14.0,67.3,1.400,100.0,16.67,0.0,0.0,45.4,22.0,314.6,1013.2,72.7,258.6,22.4,8.0,0.35,21.4,21.4,65.62,0.0,0.0,0.0,40.3,7.2,260.0,1014.3,80.0,25.0,0.1,0.0,False,False,True,False,False,True,False,False,2022,6,4,21,Ivano-Frankivsk,Europe/Kiev,2022-06-10,05:17:42,21:23:52,21:00:00,Івано-Франківська,0,0.000000
495651,2024-07-03 15:00:00,5,48.00200,37.81450,27.0,8.6,34.8,0.000,0.0,0.00,0.0,0.0,37.8,17.3,114.6,1005.6,0.1,334.5,28.7,9.0,0.91,34.6,32.4,18.33,0.0,0.0,0.0,37.8,16.6,120.8,1004.0,0.0,804.5,2.9,8.0,True,False,False,False,True,False,False,False,2024,7,2,15,Donetsk,Europe/Kiev,2024-07-03,04:34:52,20:31:04,15:00:00,Донецька,1,37.316667
38820,2022-05-02 10:00:00,15,46.47250,30.73710,13.4,6.5,64.2,0.000,0.0,0.00,0.0,0.0,20.5,14.4,110.2,1019.6,42.1,282.8,24.5,9.0,0.03,14.1,14.1,58.56,0.0,0.0,0.0,19.4,9.7,61.5,1020.0,0.0,600.0,2.2,6.0,False,True,False,False,True,False,False,False,2022,5,0,10,Odesa,Europe/Kiev,2022-05-02,05:41:40,20:07:21,10:00:00,Одеська,0,0.000000
528292,2024-08-29 07:00:00,6,50.25360,28.66540,24.8,14.0,54.3,0.000,0.0,0.00,0.0,0.0,34.9,16.9,55.9,1019.1,55.5,215.2,18.6,7.0,0.84,19.2,19.2,73.74,0.0,0.0,0.0,18.0,11.9,51.7,1020.0,78.4,12.9,0.0,0.0,False,True,False,False,False,True,False,False,2024,8,3,7,Zhytomyr,Europe/Kiev,2024-08-29,06:15:52,19:55:31,07:00:00,Житомирська,1,60.000000

In [7]:
df_final = df_final.sort_values(['region_id', 'datetime_hour'])
df_final.head()

,datetime_hour,region_id,city_latitude,city_longitude,day_temp,day_dew,day_humidity,day_precip,day_precipprob,day_precipcover,day_snow,day_snowdepth,day_windgust,day_windspeed,day_winddir,day_pressure,day_cloudcover,day_solarradiation,day_solarenergy,day_uvindex,day_moonphase,hour_temp,hour_feelslike,hour_humidity,hour_precip,hour_precipprob,hour_snow,hour_windgust,hour_windspeed,hour_winddir,hour_pressure,hour_cloudcover,hour_solarradiation,hour_solarenergy,hour_uvindex,day_conditions_simple_Clear,day_conditions_simple_Cloudy,day_conditions_simple_Rain,day_conditions_simple_Snow,hour_conditions_simple_Clear,hour_conditions_simple_Cloudy,hour_conditions_simple_Rain,hour_conditions_simple_Snow,year,month,day_of_week,hour,city_name,city_timezone,day_datetime,day_sunrise,day_sunset,hour_datetime,region_key,alarm_active,alarm_minutes_in_hour
0,2022-02-24 00:00:00,2,49.2336,28.4486,2.8,-0.3,80.5,0.3,100.0,4.17,0.0,0.0,27.7,10.8,312.0,1023.4,82.5,60.4,5.4,3.0,0.77,2.1,-0.5,91.76,0.0,0.0,0.0,16.6,8.6,279.6,1021.0,91.1,0.0,0.1,0.0,False,False,False,True,False,True,False,False,2022,2,3,0,Vinnytsia,Europe/Kiev,2022-02-24,06:58:49,17:40:52,00:00:00,Вінницька,0,0.0
24,2022-02-24 01:00:00,2,49.2336,28.4486,2.8,-0.3,80.5,0.3,100.0,4.17,0.0,0.0,27.7,10.8,312.0,1023.4,82.5,60.4,5.4,3.0,0.77,2.1,-0.4,89.80,0.0,0.0,0.0,16.6,8.3,289.2,1021.0,97.9,0.0,0.1,0.0,False,False,False,True,False,True,False,False,2022,2,3,1,Vinnytsia,Europe/Kiev,2022-02-24,06:58:49,17:40:52,01:00:00,Вінницька,0,0.0
48,2022-02-24 02:00:00,2,49.2336,28.4486,2.8,-0.3,80.5,0.3,100.0,4.17,0.0,0.0,27.7,10.8,312.0,1023.4,82.5,60.4,5.4,3.0,0.77,2.0,-0.3,90.44,0.0,0.0,0.0,27.7,7.6,287.6,1021.0,98.2,0.0,0.1,0.0,False,False,False,True,False,True,False,False,2022,2,3,2,Vinnytsia,Europe/Kiev,2022-02-24,06:58:49,17:40:52,02:00:00,Вінницька,0,0.0
72,2022-02-24 03:00:00,2,49.2336,28.4486,2.8,-0.3,80.5,0.3,100.0,4.17,0.0,0.0,27.7,10.8,312.0,1023.4,82.5,60.4,5.4,3.0,0.77,1.9,-0.3,91.75,0.0,0.0,0.0,15.1,7.2,288.9,1021.0,98.8,0.0,0.1,0.0,False,False,False,True,False,True,False,False,2022,2,3,3,Vinnytsia,Europe/Kiev,2022-02-24,06:58:49,17:40:52,03:00:00,Вінницька,0,0.0
96,2022-02-24 04:00:00,2,49.2336,28.4486,2.8,-0.3,80.5,0.3,100.0,4.17,0.0,0.0,27.7,10.8,312.0,1023.4,82.5,60.4,5.4,3.0,0.77,1.8,-0.2,92.40,0.0,0.0,0.0,13.7,6.5,290.4,1021.0,100.0,0.0,0.1,0.0,False,False,False,True,False,True,False,False,2022,2,3,4,Vinnytsia,Europe/Kiev,2022-02-24,06:58:49,17:40:52,04:00:00,Вінницька,0,0.0

In [8]:
df_final.info()

<class 'pandas.DataFrame'>
Index: 634680 entries, 0 to 634679
Data columns (total 56 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   datetime_hour                  634680 non-null  datetime64[us]
 1   region_id                      634680 non-null  int64
 2   city_latitude                  634680 non-null  float64
 3   city_longitude                 634680 non-null  float64
 4   day_temp                       634680 non-null  float64
 5   day_dew                        634680 non-null  float64
 6   day_humidity                   634680 non-null  float64
 7   day_precip                     634680 non-null  float64
 8   day_precipprob                 634680 non-null  float64
 9   day_precipcover                634680 non-null  float64
 10  day_snow                       634680 non-null  float64
 11  day_snowdepth                  634680 non-null  float64
 12  day_windgust                   634680 non-null  float64
 13  day_windspeed                  634680 non-null  float64
 14  day_winddir                    634680 non-null  float64
 15  day_pressure                   634680 non-null  float64
 16  day_cloudcover                 634680 non-null  float64
 17  day_solarradiation             634680 non-null  float64
 18  day_solarenergy                634680 non-null  float64
 19  day_uvindex                    634680 non-null  float64
 20  day_moonphase                  634680 non-null  float64
 21  hour_temp                      634680 non-null  float64
 22  hour_feelslike                 634680 non-null  float64
 23  hour_humidity                  634680 non-null  float64
 24  hour_precip                    634680 non-null  float64
 25  hour_precipprob                634680 non-null  float64
 26  hour_snow                      634680 non-null  float64
 27  hour_windgust                  634680 non-null  float64
 28  hour_windspeed                 634680 non-null  float64
 29  hour_winddir                   634680 non-null  float64
 30  hour_pressure                  634680 non-null  float64
 31  hour_cloudcover                634680 non-null  float64
 32  hour_solarradiation            634680 non-null  float64
 33  hour_solarenergy               634680 non-null  float64
 34  hour_uvindex                   634680 non-null  float64
 35  day_conditions_simple_Clear    634680 non-null  bool
 36  day_conditions_simple_Cloudy   634680 non-null  bool
 37  day_conditions_simple_Rain     634680 non-null  bool
 38  day_conditions_simple_Snow     634680 non-null  bool
 39  hour_conditions_simple_Clear   634680 non-null  bool
 40  hour_conditions_simple_Cloudy  634680 non-null  bool
 41  hour_conditions_simple_Rain    634680 non-null  bool
 42  hour_conditions_simple_Snow    634680 non-null  bool
 43  year                           634680 non-null  int64
 44  month                          634680 non-null  int64
 45  day_of_week                    634680 non-null  int64
 46  hour                           634680 non-null  int64
 47  city_name                      634680 non-null  str
 48  city_timezone                  634680 non-null  str
 49  day_datetime                   634680 non-null  str
 50  day_sunrise                    634680 non-null  str
 51  day_sunset                     634680 non-null  str
 52  hour_datetime                  634680 non-null  str
 53  region_key                     634680 non-null  str
 54  alarm_active                   634680 non-null  int64
 55  alarm_minutes_in_hour          634680 non-null  float64
dtypes: bool(8), datetime64[us](1), float64(34), int64(6), str(7)
memory usage: 287.3 MB

In [9]:
df_final = df_final.sort_values(["region_id", "datetime_hour"])

df_final["alarm_lag_1"] = df_final.groupby("region_id")["alarm_active"].shift(1)
df_final["alarm_lag_3"] = df_final.groupby("region_id")["alarm_active"].shift(3)
df_final["alarm_lag_6"] = df_final.groupby("region_id")["alarm_active"].shift(6)
df_final["alarm_lag_12"] = df_final.groupby("region_id")["alarm_active"].shift(12)
#df_final['alarm_minutes_lag1'] = (df_final.groupby('region_id')['alarm_minutes_in_hour'].shift(1).fillna(0))
#df_final['alarm_minutes_lag3'] = (df_final.groupby('region_id')['alarm_minutes_in_hour'].shift(3).fillna(0))

lag_cols = ["alarm_lag_1","alarm_lag_3","alarm_lag_6","alarm_lag_12"]
df_final[lag_cols] = df_final[lag_cols].fillna(0)

df_final['alarms_in_last_24h'] = (df_final.groupby('region_id')['alarm_active'].transform(lambda x: x.shift(1).rolling(24, min_periods=1).sum()))

df_final['is_weekend'] = df_final['day_of_week'].isin([5, 6]).astype(int)
df_final['is_night'] = ((df_final['hour'] >= 23) | (df_final['hour'] <= 6)).astype(int)

hourly_total = df_final.groupby('datetime_hour')['alarm_active'].sum().shift(1)
df_final['total_active_alarms_lag1'] = df_final['datetime_hour'].map(hourly_total)

df_final.sample(10)

,datetime_hour,region_id,city_latitude,city_longitude,day_temp,day_dew,day_humidity,day_precip,day_precipprob,day_precipcover,day_snow,day_snowdepth,day_windgust,day_windspeed,day_winddir,day_pressure,day_cloudcover,day_solarradiation,day_solarenergy,day_uvindex,day_moonphase,hour_temp,hour_feelslike,hour_humidity,hour_precip,hour_precipprob,hour_snow,hour_windgust,hour_windspeed,hour_winddir,hour_pressure,hour_cloudcover,hour_solarradiation,hour_solarenergy,hour_uvindex,day_conditions_simple_Clear,day_conditions_simple_Cloudy,day_conditions_simple_Rain,day_conditions_simple_Snow,hour_conditions_simple_Clear,hour_conditions_simple_Cloudy,hour_conditions_simple_Rain,hour_conditions_simple_Snow,year,month,day_of_week,hour,city_name,city_timezone,day_datetime,day_sunrise,day_sunset,hour_datetime,region_key,alarm_active,alarm_minutes_in_hour,alarm_lag_1,alarm_lag_3,alarm_lag_6,alarm_lag_12,alarms_in_last_24h,is_weekend,is_night,total_active_alarms_lag1
88332,2022-07-27 09:00:00,15,46.47250,30.73710,23.9,18.1,70.4,0.000,0.0,0.00,0.0,0.0,31.7,18.0,180.3,1010.9,28.6,318.8,27.5,9.0,0.94,23.9,23.9,69.13,0.0,0.0,0.0,6.1,3.6,110.0,1011.1,3.1,429.0,1.5,4.0,False,True,False,False,True,False,False,False,2022,7,2,9,Odesa,Europe/Kiev,2022-07-27,05:31:53,20:34:39,09:00:00,Одеська,0,0.0,0.0,0.0,0.0,0.0,2.0,0,0,1.0
410665,2024-02-07 01:00:00,3,50.74690,25.32630,6.6,2.5,76.2,4.592,100.0,4.17,0.0,0.0,72.0,42.4,257.5,998.2,99.2,42.7,3.8,2.0,0.92,7.9,3.8,67.72,0.0,0.0,0.0,56.5,30.2,252.0,1001.0,100.0,0.0,0.0,0.0,False,False,True,False,False,True,False,False,2024,2,2,1,Lutsk,Europe/Kiev,2024-02-07,07:46:10,17:20:12,01:00:00,Волинська,0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,8.0
35799,2022-04-27 04:00:00,18,50.90800,34.79720,12.4,6.5,69.4,0.000,0.0,0.00,0.0,0.0,36.0,17.8,295.4,1015.5,77.3,136.5,11.7,4.0,0.87,11.0,11.0,94.18,0.0,0.0,0.0,21.6,11.2,280.0,1013.0,91.5,0.0,0.1,0.0,False,True,False,False,False,True,False,False,2022,4,2,4,Sumy,Europe/Kiev,2022-04-27,05:22:25,19:55:39,04:00:00,Сумська,0,0.0,0.0,0.0,1.0,0.0,3.0,0,1,1.0
295813,2023-07-22 15:00:00,16,49.58790,34.55170,19.0,13.8,73.4,2.000,100.0,4.17,0.0,0.0,23.8,13.7,192.5,1014.8,71.7,158.4,13.7,5.0,0.15,23.4,23.4,52.03,0.0,0.0,0.0,17.3,6.8,192.9,1015.0,100.0,345.3,1.2,3.0,False,False,True,False,False,True,False,False,2023,7,5,15,Poltava,Europe/Kiev,2023-07-22,04:58:53,20:36:57,15:00:00,Полтавська,0,0.0,0.0,0.0,0.0,1.0,3.0,1,0,3.0
56105,2022-06-01 10:00:00,20,50.00420,36.23580,19.9,15.7,77.9,1.500,100.0,20.83,0.0,0.0,25.6,14.4,40.2,1017.5,86.4,310.5,26.7,9.0,0.05,21.0,21.0,73.11,0.0,0.0,0.0,22.7,3.6,20.0,1018.0,99.0,653.0,2.4,7.0,False,False,True,False,False,True,False,False,2022,6,2,10,Kharkiv,Europe/Kiev,2022-06-01,04:31:09,20:35:18,10:00:00,Харківська,0,0.0,0.0,1.0,0.0,0.0,7.0,0,0,0.0
240947,2023-04-18 09:00:00,14,46.97340,31.98520,13.3,7.1,67.3,0.000,0.0,0.00,0.0,0.0,34.2,18.0,79.8,1015.0,46.6,253.4,22.0,8.0,0.94,12.1,12.1,67.19,0.0,0.0,0.0,31.0,18.0,80.0,1016.0,80.0,350.0,1.3,4.0,False,True,False,False,False,True,False,False,2023,4,1,9,Mykolaiv,Europe/Kiev,2023-04-18,05:59:41,19:44:15,09:00:00,Миколаївська,0,0.0,0.0,0.0,1.0,0.0,3.0,0,0,5.0
321615,2023-09-05 10:00:00,18,50.90800,34.79720,18.5,12.5,69.9,0.974,100.0,4.17,0.0,0.0,39.6,18.7,20.4,1021.9,53.4,155.6,13.4,7.0,0.68,16.7,16.7,76.75,0.0,0.0,0.0,32.8,16.2,33.1,1023.0,5.1,409.9,1.5,4.0,False,False,True,False,True,False,False,False,2023,9,1,10,Sumy,Europe/Kiev,2023-09-05,05:59:50,19:18:30,10:00:00,Сумська,0,0.0,0.0,0.0,0.0,0.0,2.0,0,0,0.0
404374,2024-01-27 02:00:00,25,51.49370,31.29440,0.7,-0.2,94.0,0.200,100.0,4.17,0.0,9.4,21.6,14.4,335.5,1017.5,99.6,31.6,2.7,1.0,0.55,0.8,-2.8,96.45,0.0,0.0,0.0,18.0,11.5,318.1,1014.0,100.0,0.0,0.0,0.0,False,False,False,True,False,True,False,False,2024,1,5,2,Chernihiv,Europe/Kiev,2024-01-27,07:41:17,16:34:17,02:00:00,Чернігівська,0,0.0,0.0,0.0,0.0,1.0,2.0,1,1,0.0
5534,2022-03-05 14:00:00,17,50.61927,26.25131,-0.5,-4.4,75.3,0.000,0.0,0.00,0.0,1.0,24.5,14.3,358.5,1021.4,91.3,92.2,6.7,2.0,0.07,0.6,-3.6,63.24,0.0,0.0,0.0,17.6,14.3,20.0,1021.9,99.8,5.6,0.1,0.0,False,True,False,False,False,True,False,False,2022,3,5,14,Rivne,Europe/Kiev,2022-03-05,06:50:57,18:02:58,14:00:00,Рівненська,0,0.0,0.0,0.0,0.0,0.0,1.0,1,0,5.0
29044,2022-04-15 11:00:00,6,50.25360,28.66540,12.0,0.7,50.0,0.000,0.0,0.00,0.0,0.0,36.0,16.9,236.4,1017.0,70.5,210.7,18.3,7.0,0.46,15.0,15.0,36.94,0.0,0.0,0.0,23.8,12.2,204.1,1018.0,16.4,510.0,1.8,5.0,False,True,False,False,True,False,False,False,2022,4,4,11,Zhytomyr,Europe/Kiev,2022-04-15,06:12:24,19:59:29,11:00:00,Житомирська,1,9.8,0.0,0.0,1.0,1.0,12.0,0,0,5.0

In [10]:
neighbouring_regions = {
    1: [21],
    2: [6, 10, 11, 15, 22, 23, 24],
    3: [13, 17],
    4: [5, 8, 11, 14, 16, 20, 21],
    5: [4, 8, 12, 20],
    6: [2, 10, 17, 22],
    7: [9, 13],
    8: [4, 5, 21],
    9: [7, 13, 19, 24],
    10: [2, 6, 16, 23, 25],
    11: [2, 4, 14, 15, 16, 23],
    12: [5, 20],
    13: [3, 7, 9, 17, 19],
    14: [4, 11, 15, 21],
    15: [2, 11, 14],
    16: [4, 10, 11, 18, 20, 23, 25],
    17: [3, 6, 13, 19, 22],
    18: [16, 20, 25],
    19: [9, 13, 17, 22, 24],
    20: [4, 5, 12, 16, 18],
    21: [1, 4, 8, 14],
    22: [2, 6, 17, 19, 24],
    23: [2, 10, 11, 16],
    24: [2, 9, 19, 22],
    25: [10, 16, 18], 
    26: [10]
}

alarms_matrix = df_final.pivot_table(
    index='datetime_hour',
    columns='region_id',
    values='alarm_active',
    fill_value=0
)

neighbour_alarm_matrix = pd.DataFrame(index=alarms_matrix.index)

for region, neighbours in neighbouring_regions.items():
    valid_neighbours = [n for n in neighbours if n in alarms_matrix.columns]
    
    if valid_neighbours:
        neighbour_alarm_matrix[region] = alarms_matrix[valid_neighbours].sum(axis=1)
    else:
        neighbour_alarm_matrix[region] = 0

neighbour_alarm_matrix = neighbour_alarm_matrix.shift(1)

neighbour_alarm_long = (neighbour_alarm_matrix.stack().reset_index())

neighbour_alarm_long.columns = ['datetime_hour','region_id','neighbour_alarms']

df_final = df_final.merge(neighbour_alarm_long,on=['datetime_hour', 'region_id'], how='left')

In [11]:
def hours_since_last_alarm(series):
    shifted = series.shift(1).fillna(0)
    result = []
    count = 0
    for val in shifted:
        if val == 1:
            count = 0
        else:
            count += 1
        result.append(count)
    return pd.Series(result, index=series.index)

df_final['hours_since_last_alarm'] = (df_final.groupby('region_id')['alarm_active'].transform(hours_since_last_alarm))

In [12]:
df_final.sample(20)

,datetime_hour,region_id,city_latitude,city_longitude,day_temp,day_dew,day_humidity,day_precip,day_precipprob,day_precipcover,day_snow,day_snowdepth,day_windgust,day_windspeed,day_winddir,day_pressure,day_cloudcover,day_solarradiation,day_solarenergy,day_uvindex,day_moonphase,hour_temp,hour_feelslike,hour_humidity,hour_precip,hour_precipprob,hour_snow,hour_windgust,hour_windspeed,hour_winddir,hour_pressure,hour_cloudcover,hour_solarradiation,hour_solarenergy,hour_uvindex,day_conditions_simple_Clear,day_conditions_simple_Cloudy,day_conditions_simple_Rain,day_conditions_simple_Snow,hour_conditions_simple_Clear,hour_conditions_simple_Cloudy,hour_conditions_simple_Rain,hour_conditions_simple_Snow,year,month,day_of_week,hour,city_name,city_timezone,day_datetime,day_sunrise,day_sunset,hour_datetime,region_key,alarm_active,alarm_minutes_in_hour,alarm_lag_1,alarm_lag_3,alarm_lag_6,alarm_lag_12,alarms_in_last_24h,is_weekend,is_night,total_active_alarms_lag1,neighbour_alarms,hours_since_last_alarm
7471,2023-01-01 08:00:00,2,49.2336,28.4486,9.4,5.3,76.0,0.0,0.0,0.00,0.0,0.0,31.0,16.2,232.3,1024.0,63.9,41.5,3.7,2.0,0.29,6.7,6.7,84.07,0.0,0.0,0.0,18.7,3.6,250.0,1023.7,30.0,0.0,0.1,0.0,False,True,False,False,False,True,False,False,2023,1,6,8,Vinnytsia,Europe/Kiev,2023-01-01,08:01:26,16:18:03,08:00:00,Вінницька,0,0.000000,0.0,0.0,1.0,0.0,11.0,1,0,0.0,0.0,3
423947,2022-03-30 12:00:00,19,49.5527,25.5889,7.1,4.7,85.1,6.0,100.0,8.33,0.0,0.0,15.1,14.4,294.2,1006.1,98.2,20.6,1.8,1.0,0.92,6.7,4.5,89.53,0.0,0.0,0.0,12.2,10.8,250.0,1006.8,100.0,54.0,0.2,1.0,False,False,True,False,False,True,False,False,2022,3,2,12,Ternopil,Europe/Kiev,2022-03-30,06:59:23,19:45:52,12:00:00,Тернопільська,1,11.683333,1.0,0.0,0.0,1.0,10.0,0,0,8.0,1.0,0
449688,2022-03-01 03:00:00,20,50.0042,36.2358,0.2,-0.5,95.3,0.1,100.0,4.17,0.0,0.1,37.8,21.6,52.1,1026.3,100.0,85.4,6.1,3.0,0.94,0.0,-5.0,92.97,0.0,0.0,0.0,22.0,18.0,30.0,1026.0,100.0,0.0,0.1,0.0,False,False,False,True,False,True,False,False,2022,3,1,3,Kharkiv,Europe/Kiev,2022-03-01,06:18:47,17:16:55,03:00:00,Харківська,0,0.000000,0.0,0.0,0.0,1.0,6.0,0,1,1.0,0.0,3
319559,2022-05-27 12:00:00,15,46.4725,30.7371,19.3,12.4,66.1,0.0,0.0,0.00,0.0,0.0,28.8,15.1,219.3,1016.4,51.5,199.4,17.2,9.0,0.88,25.2,25.2,36.06,0.0,0.0,0.0,10.1,10.8,230.0,1017.4,60.0,867.0,3.1,9.0,False,True,False,False,False,True,False,False,2022,5,4,12,Odesa,Europe/Kiev,2022-05-27,05:11:44,20:37:20,12:00:00,Одеська,0,0.000000,0.0,1.0,0.0,0.0,6.0,0,0,11.0,0.0,2
169825,2023-06-03 21:00:00,8,47.8289,35.1626,19.2,13.8,72.2,0.0,0.0,0.00,0.0,0.0,45.7,27.7,294.9,1014.0,8.2,294.2,25.3,8.0,0.47,16.7,16.7,75.25,0.0,0.0,0.0,45.4,27.7,5.2,1016.0,22.0,3.9,0.0,0.0,True,False,False,False,False,True,False,False,2023,6,5,21,Zaporozhye,Europe/Zaporozhye,2023-06-03,04:43:59,20:31:31,21:00:00,Запорізька,1,60.000000,1.0,0.0,0.0,0.0,6.0,1,0,3.0,2.0,0
10985,2023-05-27 19:00:00,2,49.2336,28.4486,19.1,10.5,59.2,1.5,100.0,8.33,0.0,0.0,41.8,21.6,355.0,1016.7,39.5,260.5,22.6,8.0,0.25,21.5,21.5,46.63,0.0,0.0,0.0,31.3,17.6,3.6,1016.0,20.7,177.0,0.6,2.0,False,False,True,False,False,True,False,False,2023,5,5,19,Vinnytsia,Europe/Kiev,2023-05-27,05:10:04,20:57:22,19:00:00,Вінницька,0,0.000000,0.0,0.0,0.0,0.0,2.0,1,0,1.0,0.0,14
20717,2024-07-06 08:00:00,2,49.2336,28.4486,20.9,12.0,61.1,0.0,0.0,0.00,0.0,0.0,18.7,11.5,83.2,1018.1,22.2,305.6,26.5,8.0,0.00,19.8,19.8,63.18,0.0,0.0,0.0,8.6,1.4,145.6,1019.0,0.3,262.9,0.9,3.0,False,True,False,False,True,False,False,False,2024,7,5,8,Vinnytsia,Europe/Kiev,2024-07-06,05:08:59,21:12:49,08:00:00,Вінницька,0,0.000000,1.0,0.0,1.0,0.0,3.0,1,0,24.0,7.0,0
340038,2024-09-26 21:00:00,15,46.4725,30.7371,20.5,16.5,78.7,0.0,0.0,0.00,0.0,0.0,32.0,18.4,155.9,1017.5,62.2,163.0,14.2,6.0,0.78,20.4,20.4,79.32,0.0,0.0,0.0,18.4,10.8,200.0,1016.8,80.0,0.0,0.0,0.0,False,True,False,False,False,True,False,False,2024,9,3,21,Odesa,Europe/Kiev,2024-09-26,06:49:26,18:46:23,21:00:00,Одеська,1,39.566667,0.0,0.0,0.0,0.0,10.0,0,0,7.0,2.0,8
268899,2022-08-28 10:00:00,13,49.8444,24.0254,22.1,13.4,61.3,0.0,0.0,0.00,0.0,0.0,15.5,7.2,265.0,1012.8,46.7,227.4,19.6,7.0,0.02,21.6,21.6,64.82,0.0,0.0,0.0,5.8,1.4,176.3,1014.0,45.7,401.0,1.4,4.0,False,True,False,False,False,True,False,False,2022,8,6,10,Lviv,Europe/Kiev,2022-08-28,06:32:53,20:16:30,10:00:00,Львівська,0,0.000000,0.0,0.0,0.0,0.0,0.0,1,0,0.0,0.0,85
600564,2024-04-16 09:00:00,25,51.4937,31.2944,10.1,7.2,83.1,2.0,100.0,4.17,0.0,0.0,37.4,18.4,197.8,1002.8,96.3,138.6,12.0,6.0,0.25,8.9,8.9,90.31,0.0,0.0,0.0,16.2,3.6,160.0,1003.6,100.0,261.2,0.9,3.0,False,False,True,False,False,True,False,False,2024,4,1,9,Chernihiv,Europe/Kiev,2024-04-16,05:56:20,19:53:55,09:00:00,Чернігівська,1,16.783333,0.0,0.0,0.0,0.0,1.0,0,0,1.0,0.0,20
81722,2022-06-03 12:00:00,5,48.0020,37.8145,24.3,12.1,48.7,0.0,0.0,0.00,0.0,0.0,25.2,11.2,101.6,1017.3,5.9,338.1,29.4,9.0,0.11,28.8,28.0,35.40,0.0,0.0,0.0,23.4,10.4,110.6,1017.0,10.0,889.0,3.2,9.0,True,False,False,False,True,False,False,False,2022,6,4,12,Donetsk,Europe/Kiev,2022-06-03,04:32:30,20:21:51,12:00:00,Донецька,1,48.350000,1.0,1.0,1.0,0.0,13.0,0,0,1.0,0.0,0
444931,2024-08-20 22:00:00,19,49.5527,25.5889,23.6,18.8,76.2,0.4,100.0,4.17,0.0,0.0,20.5,14.4,343.6,1012.9,40.3,237.8,20.5,8.0,0.52,22.8,22.8,78.17,0.0,0.0,0.0,10.4,5.8,9.5,1013.0,47.6,0.0,0.0,0.0,False,False,True,False,False,True,False,False,2024,8,1,22,Ternopil,Europe/Kiev,2024-08-20,06:16:15,20:24:44,22:00:00,Тернопільська,0,0.000000,0.0,0.0,0.0,0.0,2.0,0,0,3.0,0.0,19
64277,2023-06-13 13:00:00,4,48.4753,35.0160,17.9,13.1,74.8,0.0,0.0,0.00,0.0,0.0,34.6,18.0,46.6,1012.2,92.6,208.1,17.8,7.0,0.83,22.9,22.9,60.28,0.0,0.0,0.0,32.8,16.9,51.6,1012.0,100.0,682.5,2.5,7.0,False,True,False,False,False,True,False,False,2023,6,1,13,Dnipro,Europe/Kiev,2023-06-13,04:37:59,20:42:14,13:00:00,Дніпропетровська,0,0.000000,0.0,0.0,1.0,1.0,7.0,0,0,2.0,2.0,4
552085,2024-10-17 04:00:00,23,49.4407,32.0637,6.9,3.5,80.3,0.5,100.0,20.83,0.0,0.0,43.6,22.7,7.7,1030.2,66.9,67.3,5.9,3.0,0.50,6.8,3.7,95.30,0.0,0.0,0.0,29.2,16.6,14.0,1029.0,51.5,0.0,0.0,0.0,False,False,True,False,False,True,False,False,2024,10,3,4,Cherkasy,Europe/Kiev,2024-10-17,07:16:28,17:56:51,04:00:00,Черкаська,0,0.000000,1.0,1.0,1.0,0.0,16.0,0,1,14.0,4.0,0
8772,2023-02-24 13:00:00,2,49.2336,28.4486,2.3,-1.1,79.0,0.0,0.0,0.00,0.0,0.2,48.6,23.4,188.8,1012.0,94.6,97.2,8.5,4.0,0.14,4.4,0.4,70.48,0.0,0.0,0.0,42.5,18.7,194.4,1011.0,98.7,404.6,1.5,4.0,False,True,False,False,False,True,False,False,2023,2,4,13,Vinnytsia,Europe/Kiev,2023-02-24,06:59:17,17:40:29,13:00:00,Вінницька,0,0.000000,0.0,0.0,0.0,0.0,0.0,0,0,0.0,0.0,50
60368,2023-01-01 15:00:00,4,48.4753,35.0160,5.6,4.1,89.9,0.0,0.0,0.00,0.0,0.0,43.6,25.2,225.4,1024.6,78.4,34.4,3.1,2.0,0.29,8.4,5.9,84.85,0.0,0.0,0.0,36.0,15.1,223.4,1024.0,79.8,98.0,0.4,1.0,False,True,False,False,False,True,False,False,2023,1,6,15,Dnipro,Europe/Kiev,2023-01-01,07:31:54,15:55:01,15:00:00,Дніпропетровська,1,1.533333,1.0,1.0,0.0,0.0,9.0,1,0,5.0,4.0,0
580383,2025-01-02 09:00:00,24,48.2924,25.9355,7.1,-2.4,51.5,0.0,0.0,0.00,0.0,0.0,52.9,28.3,228.0,1015.3,27.0,58.7,5.0,3.0,0.09,3.2,0.0,60.41,0.0,0.0,0.0,42.1,12.5,224.0,1018.0,0.0,23.7,0.1,0.0,False,True,False,False,True,False,False,False,2025,1,3,9,Chernivtsi,Europe/Kiev,2025-01-02,08:07:24,16:33:39,09:00:00,Чернівецька,0,0.000000,0.0,0.0,0.0,0.0,0.0,0,0,4.0,0.0,47
94754,2023-11-28 13:00:00,5,48.0020,37.8145,-0.9,-3.8,81.2,0.0,0.0,0.00,0.0,0.0,34.6,20.5,202.4,1013.1,46.0,62.2,5.3,3.0,0.53,2.1,-1.3,63.06,0.0,0.0,0.0,32.0,11.9,224.3,1014.0,2.1,240.7,0.9,2.0,False,True,False,False,True,False,False,False,2023,11,1,13,Donetsk,Europe/Kiev,2023-11-28,06:53:05,15:39:46,13:00:00,Донецька,1,17.133333,1.0,1.0,1.0,1.0,17.0,0,0,4.0,2.0,0
554958,2025-02-13 21:00:00,23,49.4407,32.0637,-5.4,-8.4,81.2,0.0,0.0,0.00,0.0,0.9,17.3,9.0,117.2,1027.1,43.7,95.2,8.3,4.0,0.53,-2.8,-6.0,71.69,0.0,0.0,0.0,15.1,7.9,155.1,1022.0,62.0,0.0,0.0,0.0,False,True,False,False,False,True,False,False,2025,2,3,21,Cherkasy,Europe/Kiev,2025-02-13,07:04:32,17:08:11,21:00:00,Черкаська,0,0.000000,1.0,1.0,0.0,0.0,3.0,0,0,7.0,1.0,0
476602,2022-03-20 16:00:00,21,46.6401,32.6142,1.1,-8.9,49.3,0.0,0.0,0.00,0.0,0.0,38.2,24.5,27.2,1038.3,1.9,234.9,20.3,6.0,0.58,6.7,2.7,31.14,0.0,0.0,0.0,38.2,24.5,29.2,1037.0,0.0,487.0,1.8,5.0,True,False,False,False,True,False,False,False,2022,3,6,16,Kherson,Europe/Kiev,2022-03-20,05:53:00,18:01:56,16:00:00,Херсонська,0,0.000000,0.0,0.0,0.0,0.0,0.0,1,0,0.0,0.0,460

In [13]:
df_isw_matrix.sample(10)

,date,isw_topic_0,isw_topic_1,isw_topic_2,isw_topic_3,isw_topic_4,isw_topic_5,isw_topic_6,isw_topic_7,isw_topic_8,isw_topic_9,isw_topic_10,isw_topic_11,isw_topic_12,isw_topic_13,isw_topic_14,isw_topic_15,isw_topic_16,isw_topic_17,isw_topic_18,isw_topic_19,isw_topic_20,isw_topic_21,isw_topic_22,isw_topic_23,isw_topic_24,isw_topic_25,isw_topic_26,isw_topic_27,isw_topic_28,isw_topic_29,isw_topic_30,isw_topic_31,isw_topic_32,isw_topic_33,isw_topic_34,isw_topic_35,isw_topic_36,isw_topic_37,isw_topic_38,isw_topic_39,isw_topic_40,isw_topic_41,isw_topic_42,isw_topic_43,isw_topic_44,isw_topic_45,isw_topic_46,isw_topic_47,isw_topic_48,isw_topic_49,isw_topic_50,isw_topic_51,isw_topic_52,isw_topic_53,isw_topic_54,isw_topic_55,isw_topic_56,isw_topic_57,isw_topic_58,isw_topic_59,isw_topic_60,isw_topic_61,isw_topic_62,isw_topic_63,isw_topic_64,isw_topic_65,isw_topic_66,isw_topic_67,isw_topic_68,isw_topic_69,isw_topic_70,isw_topic_71,isw_topic_72,isw_topic_73,isw_topic_74,isw_topic_75,isw_topic_76,isw_topic_77,isw_topic_78,isw_topic_79,isw_topic_80,isw_topic_81,isw_topic_82,isw_topic_83,isw_topic_84,isw_topic_85,isw_topic_86,isw_topic_87,isw_topic_88,isw_topic_89,isw_topic_90,isw_topic_91,isw_topic_92,isw_topic_93,isw_topic_94,isw_topic_95,isw_topic_96,isw_topic_97,isw_topic_98,isw_topic_99,isw_topic_100,isw_topic_101,isw_topic_102,isw_topic_103,isw_topic_104,isw_topic_105,isw_topic_106,isw_topic_107,isw_topic_108,isw_topic_109,isw_topic_110,isw_topic_111,isw_topic_112,isw_topic_113,isw_topic_114,isw_topic_115,isw_topic_116,isw_topic_117,isw_topic_118,isw_topic_119,isw_topic_120,isw_topic_121,isw_topic_122,isw_topic_123,isw_topic_124,isw_topic_125,isw_topic_126,isw_topic_127,isw_topic_128,isw_topic_129,isw_topic_130,isw_topic_131,isw_topic_132,isw_topic_133,isw_topic_134,isw_topic_135,isw_topic_136,isw_topic_137,isw_topic_138,isw_topic_139,isw_topic_140,isw_topic_141,isw_topic_142,isw_topic_143,isw_topic_144,isw_topic_145,isw_topic_146,isw_topic_147,isw_topic_148,isw_topic_149
385,2023-03-18,0.746146,-0.262940,-0.077112,0.067906,0.056723,-0.032690,-0.082964,0.218940,-0.022119,0.184051,-0.029375,-0.032423,-0.117405,0.068284,0.034770,0.068197,-0.029190,-0.045195,-0.140199,-0.028553,0.020024,-0.022164,0.076004,0.008336,-0.036340,0.011725,0.009525,-0.047756,-0.000788,0.022103,-0.018020,-0.022411,-0.028055,0.006905,-0.059768,-0.029051,0.016639,-0.013765,0.049691,-0.037661,-0.016299,0.005716,0.018410,-0.004191,-0.029760,-0.023390,-0.021077,0.043381,-0.004875,-0.011056,0.010581,-0.017413,0.031947,-0.017515,0.016393,-0.001937,-0.008261,-0.000783,0.042417,-0.016021,-0.020621,-0.063429,0.017583,-0.009843,-0.021510,0.020915,-0.001064,-0.006311,0.037060,-0.036272,0.005554,0.021939,0.037050,0.004396,0.013289,-0.021346,-0.010986,0.020422,0.004938,-0.002650,0.033925,-0.065277,0.006157,0.049536,0.012779,-0.043827,-0.009465,0.025517,-0.031771,0.012132,0.012420,0.016616,-0.023775,0.011864,0.017375,-0.042801,0.039929,-0.003278,0.029507,0.014338,0.039869,0.036952,-0.010706,-0.001807,-0.021647,0.042424,-0.023374,-0.003180,-0.010300,-0.048208,-0.007077,-0.025192,-0.012379,-0.020774,0.007765,-0.019609,0.001479,-0.007420,0.020509,0.022239,0.001502,0.024335,-0.013797,-0.002145,-0.007850,-0.032244,0.020398,-0.023295,-0.015587,-0.004402,-0.019111,0.023290,0.018462,-0.013060,0.006465,-0.024322,0.026880,0.012204,0.033529,0.007839,-0.036358,-0.009748,0.006098,0.006315,0.019021,0.000019,-0.025683,0.014366,-0.004773,0.004106
823,2024-06-01,0.823545,0.004163,-0.056029,0.098266,-0.116597,0.036854,0.050271,-0.109809,-0.002073,-0.003050,-0.053947,0.188031,-0.009668,0.017230,-0.034472,-0.049492,0.069187,0.038448,-0.035079,0.149175,0.000730,-0.075499,-0.013741,0.052531,-0.017473,0.013479,-0.023231,-0.017432,-0.009162,-0.049490,-0.061359,0.008060,-0.031632,0.033353,-0.005418,0.006200,-0.031049,-0.009330,0.028498,-0.027581,-0.003717,0.032437,-0.022590,0.006635,0.006668,0.036798,-0.001840,0.020923,0.002311,0.045210,0.000458,0.026479,0.014952,0.026845,0.027789,-0.044204,0.009157,0.010954,-0.008699,0.020929,-0.017238,0.009587,0.003863,0.004633,-0.041837,0.014182,-0.025453,-0.007281,-0.017634,0.010922,0.027150,0.020887,-0.005683,-0.021843,-0.012655,-0.010631,-0.007393,0.007311,0.000850,-0.022861,0.019166,0.017378,-0.001476,0.007524,0.009468,-0.051495,0.035232,0.030909,-0.018919,0.020806,-0.019368,0.027762,0.016776,0.001160,-0.013111,-0.010268,0.017787,-0.040023,-0.003114,0.024572,-0.013535,0.021321,0.047758,0.005674,0.001044,-0.023919,0.001765,-0.011044,-0.005109,0.022907,-0.024240,0.006067,0.019397,0.012861,-0.015126,0.007433,-0.003182,0.016611,0.014399,-0.028435,0.002746,0.010164,-0.036861,-0.000710,-0.009013,0.015396,-0.009862,0.013843,-0.017929,-0.006028,0.027273,-0.032449,0.014261,-0.000651,-0.003419,0.000936,0.011152,-0.020852,0.002122,-0.004702,-0.018281,-0.047138,0.001282,0.023914,0.003771,-0.008229,-0.033349,0.003678,0.006572,0.006687
941,2024-09-27,0.829803,0.047829,-0.019874,-0.007677,-0.071266,-0.015918,-0.035848,-0.001454,0.087732,-0.103539,-0.009843,0.037422,0.155549,0.176862,0.077317,0.034745,0.037467,-0.081488,-0.003873,0.041441,0.007118,-0.063486,-0.063760,-0.015576,-0.017344,-0.008646,-0.025732,-0.025554,0.005673,-0.058349,-0.062504,0.020579,0.001714,0.005478,-0.028132,0.011985,0.033480,0.002184,0.007650,0.012404,-0.018245,-0.012245,0.017462,0.028355,-0.005297,0.029243,0.012801,-0.015180,-0.006771,-0.016037,0.017863,-0.021173,0.000462,-0.034735,-0.009788,0.020993,0.012694,0.020511,-0.024162,-0.002205,-0.006013,0.018929,-0.000831,-0.022803,0.008813,-0.003034,-0.010433,-0.027122,-0.025361,0.015848,0.017158,0.006906,0.007807,-0.015794,-0.020282,-0.027121,-0.004082,0.015345,-0.018072,-0.029617,-0.009528,-0.032551,-0.024300,-0.024189,-0.009569,-0.044640,0.028087,0.032580,-0.013557,-0.025755,-0.005211,0.012261,-0.006621,0.017531,-0.030800,-0.025571,0.000613,0.009908,0.029032,0.011927,0.010465,-0.018221,-0.032143,0.012156,-0.049910,0.022775,-0.034192,0.012504,-0.017129,0.030031,0.043566,0.008804,0.010486,-0.001569,0.004578,-0.034056,0.003460,-0.013487,-0.012968,-0.002391,-0.024916,0.014913,0.021236,0.006278,-0.014009,-0.007292,-0.008194,-0.001991,0.007325,0.005442,-0.020114,0.021289,0.000493,0.004918,0.027177,-0.008942,-0.028020,0.033377,0.024322,0.006807,-0.006663,0.008475,-0.018010,0.022373,0.010377,0.001586,0.038983,0.023101,0.016031,0.017589
854,2024-07-02,0.817168,0.026394,-0.126731,0.111847,-0.171594,0.110820,0.095058,-0.135670,-0.011855,0.041942,-0.133512,-0.149027,0.034980,-0.008904,-0.023030,0.007606,0.031299,-0.067808,-0.002123,0.010952,-0.075756,-0.003157,-0.047846,0.071767,0.020039,-0.004203,0.016637,-0.010963,-0.041715,-0.028247,-0.036449,-0.011070,0.048626,0.010426,-0.037897,0.000049,-0.021033,-0.035214,0.040667,-0.002765,0.020884,-0.015626,0.029139,0.066581,-0.004781,0.002941,0.003295,0.010521,-0.038742,0.028136,0.030367,-0.019003,0.000960,-0.012650,0.011248,-0.015733,-0.025611,0.000117,0.006370,-0.008276,0.014305,-0.018609,-0.008237,-0.022117,0.013671,-0.010585,0.018677,-0.012214,0.001426,-0.012102,0.002615,0.006997,-0.021588,-0.028513,0.025598,-0.027889,0.002401,0.016911,0.009878,-0.007147,0.014848,0.000164,0.038684,0.014044,0.006762,0.021956,-0.009457,0.014443,0.033611,-0.009527,0.000776,-0.032660,0.007263,-0.021707,0.019074,0.006064,-0.004731,-0.014856,0.003214,-0.022960,-0.011225,0.010705,0.013627,0.033881,0.000421,-0.007068,-0.004791,-0.023199,-0.016573,-0.039469,0.009247,-0.023824,-0.018251,-0.016282,-0.008682,-0.020696,0.021699,0.029066,0.003667,0.004099,-0.014520,0.007116,-0.006633,-0.014109,-0.000465,0.006979,0.003657,0.018299,0.003615,0.010560,-0.014994,0.002936,0.011680,0.024045,-0.035034,0.019763,-0.037641,0.023282,0.006354,-0.002830,0.004464,0.021092,-0.014729,-0.010166,0.003775,-0.002188,-0.015132,0.031289,0.013760,-0.006609
424,2023-04-26,0.760990,-0.225905,-0.104488,0.116481,-0.012018,-0.057497,-0.024924,-0.025961,-0.138207,-0.002051,0.279070,-0.078939,-0.010210,0.011132,-0.016954,0.000776,-0.060727,0.022380,-0.039900,0.000849,-0.063725,-0.049151,0.001080,0.037431,-0.005076,-0.082883,0.052751,0.021912,0.017375,0.061205,-0.025003,-0.035645,0.032321,-0.010248,0.014731,0.009572,0.015558,-0.019772,0.011157,-0.006757,-0.036552,0.021586,0.019335,0.009076,-0.040664,0.022770,0.028205,-0.008726,-0.028308,-0.039452,0.004603,0.017119,0.010386,0.029580,-0.042078,-0.009379,-0.034657,-0.020420,0.059743,0.019381,-0.006083,-0.009649,0.025812,0.017718,-0.030810,0.040449,-0.051120,0.007322,-0.030602,-0.038649,-0.010134,-0.012811,0.011629,0.003092,0.017217,-0.066636,-0.006680,-0.000694,0.024801,0.014410,0.070448,-0.005565,-0.007348,-0.034194,-0.001971,-0.018643,-0.003105,0.031394,0.024241,0.019693,-0.025458,0.003271,0.001520,-0.010925,0.018490,-0.015794,0.024445,-0.010074,-0.010934,-0.019590,-0.002118,-0.036391,-0.021850,0.006216,0.002735,0.037863,-0.025299,0.018512,0.036122,0.021399,0.023463,0.014511,-0.014116,-0.020323,0.025429,0.013203,0.003802,-0.042715,0.011517,-0.002676,-0.004138,0.006399,0.013866,0.000099,-0.020784,-0.053560,-0.002985,0.012652,0.005302,0.026996,0.006637,0.036795,-0.012116,-0.019064,0.038100,-0.014066,-0.020673,-0.003409,0.024377,-0.000084,-0.004239,-0.001514,-0.010699,-0.007595,-0.009224,0.037658,-0.023034,0.034643,0.013862,-0.026368
358,2023-02-19,0.542521,-0.055382,-0.045201,0.022866,0.038109,0.008040,-0.038734,0.034093,-0.036035,0.023957,0.018012,0.008520,0.017668,-0.028617,0.084943,0.017040,0.047869,-0.118840,-0.048996,0.015044,-0.031789,0.255753,-0.238555,-0.110230,-0.107560,-0.125560,-0.020193,-0.015707,-0.003009,-0.120667,0.000536,-0.013920,-0.063880,-0.045650,-0.042091,0.076134,-0.026180,-0.050165,-0.007585,0.057333,0.119784,-0.014805,0.064026,-0.084359,0.131215,0.081207,0.153122,0.031256,0.031662,0.014670,-0.019156,-0.071161,-0.066312,0.108939,-0.043165,-0.019717,0.056834,0.015693,-0.031689,0.042450,-0.047023,0.040522,0.017720,0.006630,0.087583,-0.017459,-0.110616,-0.082827,-0.007806,-0.027061,-0.011828,0.103599,0.028723,0.092664,-0.057833,-0.010740,0.027635,0.013912,-0.123887,-0.049222,0.046077,0.042578,0.050542,-0.072922,0.011444,-0.055098,-0.037944,0.028334,-0.034901,-0.075263,0.049355,0.027228,0.001705,0.004934,-0.039624,-0.052063,-0.024093,0.042147,-0.016779,-0.016798,0.021996,-0.036273,0.059744,-0.009462,0.093799,-0.044215,-0.033811,0.030224,0.043806,-0.068524,-0.025806,0.015979,-0.000516,0.061154,-0.026052,0.015069,0.110760,-0.084112,-0.077338,0.015709,0.020069,-0.023789,-0.003381,0.048796,-0.052271,-0.076187,0.043604,0.029872,0.089081,0.003095,0.002552,-0.009486,-0.000076,0.016223,-0.071153,0.023205,0.050012,0.044371,0.051649,0.052446,-0.036771,-0.021826,-0.017113,-0.061502,0.015314,-0.030858,-0.020336,0.024326,0.006757,0.019541
1262,2025-08-18,0.714641,0.316367,0.096538,-0.060334,-0.122693,0.100101,-0.025291,0.178938,0.120904,-0.069261,0.124810,-0.019400,-0.107917,-0.155222,-0.108038,0.002912,0.030763,-0.015870,0.018169,-0.047959,0.006279,0.125019,-0.035491,-0.081117,-0.002988,-0.005548,0.094102,-0.053476,-0.135079,-0.037500,-0.033088,-0.041560,-0.009061,0.058866,0.004564,-0.051950,0.010597,-0.023547,0.009781,0.046407,-0.027475,0.000199,-0.009840,0.038060,-0.077106,-0.003241,-0.043709,-0.032102,0.017370,0.030568,0.003212,0.037945,-0.020738,-0.067116,0.025299,-0.002714,0.019385,-0.000991,0.003492,0.007027,0.078719,-0.018838,-0.015285,0.003616,-0.032743,-0.007281,-0.012380,-0.023969,-0.040188,0.019490,-0.018232,0.003330,0.008711,-0.027971,0.010337,-0.016677,0.000168,0.020484,-0.014433,-0.003676,0.010189,0.000446,-0.025968,0.033976,-0.015366,-0.011748,-0.023377,0.014969,0.054491,0.008616,-0.027307,0.025962,0.011973,-0.000726,0.020217,-0.002494,0.002186,-0.030938,0.046281,0.011118,-0.013545,-0.021150,0.026667,-0.012779,0.012483,-0.016817,-0.013002,0.011246,0.003741,-0.006488,-0.018852,-0.009532,0.032221,-0.017086,0.014179,0.004584,-0.016688,0.019717,-0.019252,-0.012156,-0.024408,0.016825,0.002273,0.037122,0.021670,0.010844,0.004463,0.000160,-0.006606,-0.004280,0.007295,0.001489,-0.029575,-0.013192,0.011871,-0.013506,0.012078,0.006710,0.005527,-0.033787,-0.010382,-0.007209,-0.016152,-0.000646,-0.054520,-0.019899,-0.029998,0.032719,0.004861,-0.009308
1449,2026-02-24,0.790909,0.175004,0.056538,0.015774,0.111459,0.016503,-0.010622,0.133078,-0.096456,0.065089,0.000639,0.049191,0.215138,-0.205500,-0.026223,0.010443,-0.004287,-0.041139,0.056358,0.022354,0.076345,-0.098489,-0.029972,0.045413,0.058113,-0.064372,-0.038841,0.011614,0.098275,0.002639,-0.014611,0.009466,-0.038100,-0.005787,-0.036454,0.012429,0.084320,0.043154,0.001183,0.008480,-0.024792,-0.028777,-0.030761,0.059748,0.001036,-0.006537,0.013215,-0.008129,0.015429,0.012667,-0.014543,-0.015506,0.018423,-0.051501,0.026918,-0.061121,-0.021404,0.000952,-0.001486,0.003724,0.005556,0.028743,-0.018479,0.035132,0.009563,0.019944,-0.002852,0.018820,0.020464,-0.039417,-0.000947,0.005956,-0.034780,0.038824,0.045983,-0.024789,-0.003409,0.009693,0.000114,-0.007735,0.010535,-0.024354,0.025634,-0.006304,-0.013210,-0.011710,-0.000990,-0.003081,0.017886,0.005214,-0.007204,-0.018167,0.029226,-0.007519,0.009044,-0.015584,-0.028272,0.019761,0.044382,-0.036897,-0.020324,0.001416,0.013631,-0.014541,0.001206,-0.014711,0.015525,-0.000975,0.012526,0.014932,-0.005852,-0.012494,0.004596,0.014538,0.013892,-0.024041,0.004211,-0.016809,-0.026918,-0.019407,-0.020120,0.005610,0.021952,0.006971,0.007299,0.009056,-0.018980,0.012274,0.003103,0.027405,0.006811,0.018073,-0.013649,0.013575,0.006982,-0.009675,0.028469,0.008834,0.000792,-0.019020,-0.011299,-0.008336,0.006496,-0.012131,-0.009898,-0.008510,-0.021048,0.006486,0.015315,0.002394
1306,2025-10-01,0.774006,0.243254,0.062306,-0.170094,-0.043213,-0.117998,-0.191521,0.011352,-0.122536,-0.083928,-0.036893,-0.010424,0.046339,0.047297,-0.083004,0.036794,0.022049,-0.025497,-0.046452,-0.008182,-0.040608,-0.018457,0.032859,-0.044950,-0.021137,0.014099,-0.026055,0.031933,-0.032730,-0.005931,-0.056278,0.023688,0.064012,-0.001360,0.033097,0.039189,0.012399,-0.018718,-0.008424,-0.033169,0.048800,-0.058410,-0.003753,0.003571,-0.017395,-0.018930,0.029634,0.030419,0.000470,0.113403,-0.011240,-0.015075,-0.060231,0.046385,-0.021175,0.034858,0.029257,-0.003791,-0.021950,0.024188,-0.040760,-0.029276,0.000137,-0.002588,0.006106,-0.025241,-0.006661,0.000721,0.075444,-0.017762,0.001581,-0.048276,-0.003177,0.000395,-0.031624,0.031802,0.053028,-0.005798,-0.005972,0.046366,-0.009103,0.001762,0.033688,0.015170,0.026958,0.015442,0.022097,0.017583,0.020079,0.003222,-0.035737,-0.011259,-0.004727,-0.002130,0.013658,-0.007894,-0.007825,-0.001520,0.000009,0.008598,0.003968,-0.015974,-0.026517,0.034879,-0.020867,0.005272,-0.034529,-0.008517,0.014607,-0.010914,-0.023001,-0.001484,-0.007868,0.019975,0.004123,-0.012077,-0.007251,-0.006536,0.020548,-0.003044,0.000718,-0.003322,0.003109,-0.049588,-0.001254,-0.018595,0.020916,-0.012111,-0.010877,-0.017135,-0.003268,0.019330,-0.000887,0.021795,0.028418,0.008332,-0.012029,-0.008353,0.006277,-0.021051,0.008370,0.031443,-0.001199,-0.013191,-0.002102,-0.021738,-0.007861,-0.001009,-0.006631,-0.028358
742,2024-03-12,0.771006,-0.058675,-0.169587,0.198907,0.000772,-0.093848,-0.057264,0.111716,0.099504,0.050589,-0.122796,-0.018896,0.012651,0.026105,-0.157758,-0.038243,0.002078,0.042938,-0.065391,-0.023506,0.030951,0.032394,0.025281,0.033876,-0.022799,0.000386,-0.030766,0.001905,-0.016852,0.008279,0.022035,-0.023898,0.032906,-0.070680,0.059909,0.049607,-0.007963,0.034037,-0.006167,-0.031504,-0.033616,-0.014857,-0.019122,0.015500,-0.025709,0.010523,0.034876,-0.008206,-0.050647,-0.041032,-0.019984,0.027440,-0.026612,0.037400,-0.035648,-0.003144,0.003892,-0.049543,0.121290,0.026386,0.051116,0.067847,0.000931,-0.008513,0.027634,0.005616,-0.067899,0.066156,-0.007342,-0.037822,0.013567,-0.039547,0.002023,-0.022912,-0.017720,0.009892,0.019161,0.013207,0.037890,0.039838,-0.010514,-0.012988,-0.010408,-0.022367,-0.017459,-0.027939,-0.042488,0.021948,0.051503,0.015691,0.006091,0.033213,-0.039125,0.019545,-0.006251,0.020913,0.010444,-0.005016,-0.006921,-0.027019,0.011630,-0.020075,-0.006756,-0.014786,0.016619,-0.008884,-0.021167,0.011715,-0.013178,0.009461,-0.000656,-0.017466,-0.030060,0.035794,-0.015796,-0.013711,0.010429,0.019682,0.009879,0.020422,-0.026809,0.002350,-0.003840,-0.054370,0.009522,0.011201,0.014122,0.038536,0.008256,-0.038828,-0.030040,0.033385,0.030183,-0.014591,0.027094,0.006506,0.027099,0.022295,-0.006718,0.007781,-0.011677,0.013786,-0.040996,-0.036679,-0.013618,0.013703,0.027807,0.008405,0.000511,-0.008446

In [14]:
#df_isw_matrix["date"] = pd.to_datetime(df_isw_matrix["date"]) + pd.Timedelta(days=1)    ТУТ ЗСУВ ІСВ НА + 1 ДЕНЬ
df_isw_matrix = df_isw_matrix.rename(columns={'date': 'day_datetime'})

In [15]:
df_final['day_datetime'] = pd.to_datetime(df_final['day_datetime']).dt.date
df_isw_matrix['day_datetime'] = pd.to_datetime(df_isw_matrix['day_datetime']).dt.date
df_isw_matrix.fillna(0, inplace=True)
df_isw_matrix.isna().sum()

day_datetime     0
isw_topic_0      0
isw_topic_1      0
isw_topic_2      0
isw_topic_3      0
                ..
isw_topic_145    0
isw_topic_146    0
isw_topic_147    0
isw_topic_148    0
isw_topic_149    0
Length: 151, dtype: int64

In [16]:
df_final = df_final.merge(df_isw_matrix, on="day_datetime", how="left")

In [17]:
df_final.head(10)

,datetime_hour,region_id,city_latitude,city_longitude,day_temp,day_dew,day_humidity,day_precip,day_precipprob,day_precipcover,day_snow,day_snowdepth,day_windgust,day_windspeed,day_winddir,day_pressure,day_cloudcover,day_solarradiation,day_solarenergy,day_uvindex,day_moonphase,hour_temp,hour_feelslike,hour_humidity,hour_precip,hour_precipprob,hour_snow,hour_windgust,hour_windspeed,hour_winddir,hour_pressure,hour_cloudcover,hour_solarradiation,hour_solarenergy,hour_uvindex,day_conditions_simple_Clear,day_conditions_simple_Cloudy,day_conditions_simple_Rain,day_conditions_simple_Snow,hour_conditions_simple_Clear,hour_conditions_simple_Cloudy,hour_conditions_simple_Rain,hour_conditions_simple_Snow,year,month,day_of_week,hour,city_name,city_timezone,day_datetime,day_sunrise,day_sunset,hour_datetime,region_key,alarm_active,alarm_minutes_in_hour,alarm_lag_1,alarm_lag_3,alarm_lag_6,alarm_lag_12,alarms_in_last_24h,is_weekend,is_night,total_active_alarms_lag1,neighbour_alarms,hours_since_last_alarm,isw_topic_0,isw_topic_1,isw_topic_2,isw_topic_3,isw_topic_4,isw_topic_5,isw_topic_6,isw_topic_7,isw_topic_8,isw_topic_9,isw_topic_10,isw_topic_11,isw_topic_12,isw_topic_13,isw_topic_14,isw_topic_15,isw_topic_16,isw_topic_17,isw_topic_18,isw_topic_19,isw_topic_20,isw_topic_21,isw_topic_22,isw_topic_23,isw_topic_24,isw_topic_25,isw_topic_26,isw_topic_27,isw_topic_28,isw_topic_29,isw_topic_30,isw_topic_31,isw_topic_32,isw_topic_33,isw_topic_34,isw_topic_35,isw_topic_36,isw_topic_37,isw_topic_38,isw_topic_39,isw_topic_40,isw_topic_41,isw_topic_42,isw_topic_43,isw_topic_44,isw_topic_45,isw_topic_46,isw_topic_47,isw_topic_48,isw_topic_49,isw_topic_50,isw_topic_51,isw_topic_52,isw_topic_53,isw_topic_54,isw_topic_55,isw_topic_56,isw_topic_57,isw_topic_58,isw_topic_59,isw_topic_60,isw_topic_61,isw_topic_62,isw_topic_63,isw_topic_64,isw_topic_65,isw_topic_66,isw_topic_67,isw_topic_68,isw_topic_69,isw_topic_70,isw_topic_71,isw_topic_72,isw_topic_73,isw_topic_74,isw_topic_75,isw_topic_76,isw_topic_77,isw_topic_78,isw_topic_79,isw_topic_80,isw_topic_81,isw_topic_82,isw_topic_83,isw_topic_84,isw_topic_85,isw_topic_86,isw_topic_87,isw_topic_88,isw_topic_89,isw_topic_90,isw_topic_91,isw_topic_92,isw_topic_93,isw_topic_94,isw_topic_95,isw_topic_96,isw_topic_97,isw_topic_98,isw_topic_99,isw_topic_100,isw_topic_101,isw_topic_102,isw_topic_103,isw_topic_104,isw_topic_105,isw_topic_106,isw_topic_107,isw_topic_108,isw_topic_109,isw_topic_110,isw_topic_111,isw_topic_112,isw_topic_113,isw_topic_114,isw_topic_115,isw_topic_116,isw_topic_117,isw_topic_118,isw_topic_119,isw_topic_120,isw_topic_121,isw_topic_122,isw_topic_123,isw_topic_124,isw_topic_125,isw_topic_126,isw_topic_127,isw_topic_128,isw_topic_129,isw_topic_130,isw_topic_131,isw_topic_132,isw_topic_133,isw_topic_134,isw_topic_135,isw_topic_136,isw_topic_137,isw_topic_138,isw_topic_139,isw_topic_140,isw_topic_141,isw_topic_142,isw_topic_143,isw_topic_144,isw_topic_145,isw_topic_146,isw_topic_147,isw_topic_148,isw_topic_149
0,2022-02-24 00:00:00,2,49.2336,28.4486,2.8,-0.3,80.5,0.3,100.0,4.17,0.0,0.0,27.7,10.8,312.0,1023.4,82.5,60.4,5.4,3.0,0.77,2.1,-0.5,91.76,0.0,0.0,0.0,16.6,8.6,279.6,1021.0,91.1,0.0,0.1,0.0,False,False,False,True,False,True,False,False,2022,2,3,0,Vinnytsia,Europe/Kiev,2022-02-24,06:58:49,17:40:52,00:00:00,Вінницька,0,0.0,0.0,0.0,0.0,0.0,NaN,0,1,NaN,NaN,1,0.648336,-0.079572,0.178041,0.061854,0.073453,-0.055809,-0.011311,0.047310,0.008354,0.006474,-0.047099,0.020496,0.050190,-0.038573,0.057228,-0.072471,0.045393,-0.116783,0.168249,0.167355,-0.025072,-0.073858,-0.097024,-0.146191,0.027983,0.082989,0.014423,0.058370,-0.033928,0.046265,0.006901,-0.049498,0.126117,-0.089039,-0.006767,-0.031686,-0.010346,0.025637,0.061278,0.162580,-0.028081,0.161291,-0.018217,-0.002657,0.038485,-0.000530,0.044413,0.107176,-0.050721,0.064279,-0.066677,0.016742,-0.050257,0.072549,-0.035201,-0.027279,0.017115,0.043631,0.024660,-0.025841,0.031320,-0.076959,-0.072986,-0.040465,0.003958,-0.022475,0.033208,-0.028056,-0.005499,-0.055998,-0.021882,-0.070462,0.018237,-0.031396,-0.074606,0.072951,0.039997,0.036423,-0.027152,-0.071900,0.026267,-0.046270,-0.017945,0.007933,-0.006203,-0.046099,0.032793,-0.069113,0.020403,0.030783,-0.003787,-0.000490,-0.022951,0.013498,0.009664,-0.007012,-0.016325,-0.005732,0.036069,-0.063906,0.033891,0.010560,-0.104517,-0.022069,0.054322,-0.005460,-0.029093,0.040991,-0.053018,-0.024017,0.050817,-0.003297,-0.020895,-0.053213,-0.028428,0.048231,-0.001221,0.001302,-0.044137,0.015528,-0.012792,-0.012009,-0.008211,0.031114,0.024982,0.003863,-0.032321,0.030920,-0.012845,0.070170,-0.004037,0.014003,0.005577,0.021611,-0.002889,0.034824,0.047164,0.050545,-0.017639,0.029014,-0.030378,-0.027056,0.011464,-0.039759,-0.043514,-0.025605,-0.022484,-0.036224,0.000566,0.005481
1,2022-02-24 00:00:00,2,49.2336,28.4486,2.8,-0.3,80.5,0.3,100.0,4.17,0.0,0.0,27.7,10.8,312.0,1023.4,82.5,60.4,5.4,3.0,0.77,2.1,-0.5,91.76,0.0,0.0,0.0,16.6,8.6,279.6,1021.0,91.1,0.0,0.1,0.0,False,False,False,True,False,True,False,False,2022,2,3,0,Vinnytsia,Europe/Kiev,2022-02-24,06:58:49,17:40:52,00:00:00,Вінницька,0,0.0,0.0,0.0,0.0,0.0,NaN,0,1,NaN,NaN,1,0.580161,-0.090608,-0.028388,0.146350,0.071072,-0.030284,-0.004583,0.087399,-0.038512,0.016613,-0.038599,0.049747,0.186305,-0.172198,-0.045515,0.050785,0.041889,-0.112849,0.193473,-0.010566,0.044308,-0.118300,0.007117,-0.135687,-0.009441,-0.039465,0.032843,0.080393,-0.035434,0.010352,-0.016680,-0.046252,0.085840,-0.123167,0.064510,-0.023735,-0.025637,-0.027863,0.032156,0.068641,0.027667,0.162729,0.039675,-0.016915,-0.008203,0.048024,0.073343,0.025782,-0.013935,-0.008775,-0.045265,0.008979,-0.100558,0.044074,0.018202,-0.037279,0.062349,0.008014,0.075917,-0.063409,0.015404,-0.091507,-0.079240,-0.033000,-0.019226,-0.103926,0.031514,0.043306,-0.012137,-0.010430,0.035901,-0.013437,-0.042046,-0.064986,0.002947,0.024326,0.085592,-0.008453,0.091087,-0.106852,0.038223,-0.061062,0.027905,0.056421,-0.030501,0.000050,0.051385,-0.087324,-0.024025,0.031626,-0.029461,0.015717,-0.047181,-0.005600,0.049867,0.084412,-0.055460,-0.036620,0.120475,-0.012080,0.006961,-0.079701,0.055655,0.004130,0.013250,0.002392,0.041937,0.028208,-0.037232,0.014886,-0.036905,0.000138,-0.018200,-0.010680,-0.067564,-0.001064,-0.044792,-0.014807,-0.031911,-0.023504,0.070783,0.027626,0.000418,0.043677,-0.030193,-0.034979,0.080093,0.035489,-0.004156,-0.008032,0.039826,-0.037380,0.011931,0.008267,0.000590,0.043862,0.023758,0.038714,0.066128,0.028168,-0.012153,0.005376,0.008085,-0.038933,0.003404,0.003281,-0.004149,-0.025392,0.010434,-0.017613
2,2022-02-24 01:00:00,2,49.2336,28.4486,2.8,-0.3,80.5,0.3,100.0,4.17,0.0,0.0,27.7,10.8,312.0,1023.4,82.5,60.4,5.4,3.0,0.77,2.1,-0.4,89.80,0.0,0.0,0.0,16.6,8.3,289.2,1021.0,97.9,0.0,0.1,0.0,False,False,False,True,False,True,False,False,2022,2,3,1,Vinnytsia,Europe/Kiev,2022-02-24,06:58:49,17:40:52,01:00:00,Вінницька,0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0.0,0.0,2,0.648336,-0.079572,0.178041,0.061854,0.073453,-0.055809,-0.011311,0.047310,0.008354,0.006474,-0.047099,0.020496,0.050190,-0.038573,0.057228,-0.072471,0.045393,-0.116783,0.168249,0.167355,-0.025072,-0.073858,-0.097024,-0.146191,0.027983,0.082989,0.014423,0.058370,-0.033928,0.046265,0.006901,-0.049498,0.126117,-0.089039,-0.006767,-0.031686,-0.010346,0.025637,0.061278,0.162580,-0.028081,0.161291,-0.018217,-0.002657,0.038485,-0.000530,0.044413,0.107176,-0.050721,0.064279,-0.066677,0.016742,-0.050257,0.072549,-0.035201,-0.027279,0.017115,0.043631,0.024660,-0.025841,0.031320,-0.076959,-0.072986,-0.040465,0.003958,-0.022475,0.033208,-0.028056,-0.005499,-0.055998,-0.021882,-0.070462,0.018237,-0.031396,-0.074606,0.072951,0.039997,0.036423,-0.027152,-0.071900,0.026267,-0.046270,-0.017945,0.007933,-0.006203,-0.046099,0.032793,-0.069113,0.020403,0.030783,-0.003787,-0.000490,-0.022951,0.013498,0.009664,-0.007012,-0.016325,-0.005732,0.036069,-0.063906,0.033891,0.010560,-0.104517,-0.022069,0.054322,-0.005460,-0.029093,0.040991,-0.053018,-0.024017,0.050817,-0.003297,-0.020895,-0.053213,-0.028428,0.048231,-0.001221,0.001302,-0.044137,0.015528,-0.012792,-0.012009,-0.008211,0.031114,0.024982,0.003863,-0.032321,0.030920,-0.012845,0.070170,-0.004037,0.014003,0.005577,0.021611,-0.002889,0.034824,0.047164,0.050545,-0.017639,0.029014,-0.030378,-0.027056,0.011464,-0.039759,-0.043514,-0.025605,-0.022484,-0.036224,0.000566,0.005481
3,2022-02-24 01:00:00,2,49.2336,28.4486,2.8,-0.3,80.5,0.3,100.0,4.17,0.0,0.0,27.7,10.8,312.0,1023.4,82.5,60.4,5.4,3.0,0.77,2.1,-0.4,89.80,0.0,0.0,0.0,16.6,8.3,289.2,1021.0,97.9,0.0,0.1,0.0,False,False,False,True,False,True,False,False,2022,2,3,1,Vinnytsia,Europe/Kiev,2022-02-24,06:58:49,17:40:52,01:00:00,Вінницька,0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0.0,0.0,2,0.580161,-0.090608,-0.028388,0.146350,0.071072,-0.030284,-0.004583,0.087399,-0.038512,0.016613,-0.038599,0.049747,0.186305,-0.172198,-0.045515,0.050785,0.041889,-0.112849,0.193473,-0.010566,0.044308,-0.118300,0.007117,-0.135687,-0.009441,-0.039465,0.032843,0.080393,-0.035434,0.010352,-0.016680,-0.046252,0.085840,-0.123167,0.064510,-0.023735,-0.025637,-0.027863,0.032156,0.068641,0.027667,0.162729,0.039675,-0.016915,-0.008203,0.048024,0.073343,0.025782,-0.013935,-0.008775,-0.045265,0.008979,-0.100558,0.044074,0.018202,-0.037279,0.062349,0.008014,0.075917,-0.063409,0.015404,-0.091507,-0.079240,-0.033000,-0.019226,-0.103926,0.031514,0.043306,-0.012137,-0.010430,0.035901,-0.013437,-0.042046,-0.064986,0.002947,0.024326,0.085592,-0.008453,0.091087,-0.106852,0.038223,-0.061062,0.027905,0.056421,-0.030501,0.000050,0.051385,-0.087324,-0.024025,0.031626,-0.029461,0.015717,-0.047181,-0.005600,0.049867,0.084412,-0.055460,-0.036620,0.120475,-0.012080,0.006961,-0.079701,0.055655,0.004130,0.013250,0.002392,0.041937,0.028208,-0.037232,0.014886,-0.036905,0.000138,-0.018200,-0.010680,-0.067564,-0.001064,-0.044792,-0.014807,-0.031911,-0.023504,0.070783,0.027626,0.000418,0.043677,-0.030193,-0.034979,0.080093,0.035489,-0.004156,-0.008032,0.039826,-0.037380,0.011931,0.008267,0.000590,0.043862,0.023758,0.038714,0.066128,0.028168,-0.012153,0.005376,0.008085,-0.038933,0.003404,0.003281,-0.004149,-0.025392,0.010434,-0.017613
4,2022-02-24 02:00:00,2,49.2336,28.4486,2.8,-0.3,80.5,0.3,100.0,4.17,0.0,0.0,27.7,10.8,312.0,1023.4,82.5,60.4,5.4,3.0,0.77,2.0,-0.3,90.44,0.0,0.0,0.0,27.7,7.6,287.6,1021.0,98.2,0.0,0.1,0.0,False,False,False,True,False,True,False,False,2022,2,3,2,Vinnytsia,Europe/Kiev,2022-02-24,06:58:49,17:40:52,02:00:00,Вінницька,0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0.0,0.0,3,0.648336,-0.079572,0.178041,0.061854,0.073453,-0.055809,-0.011311,0.047310,0.008354,0.006474,-0.047099,0.020496,0.050190,-0.038573,0.057228,-0.072471,0.045393,-0.116783,0.168249,0.167355,-0.025072,-0.073858,-0.097024,-0.146191,0.027983,0.082989,0.014423,0.058370,-0.033928,0.046265,0.006901,-0.049498,0.126117,-0.089039,-0.006767,-0.031686,-0.010346,0.025637,0.061278,0.162580,-0.028081,0.161291,-0.018217,-0.002657,0.038485,-0.000530,0.044413,0.107176,-0.050721,0.064279,-0.066677,0.016742,-0.050257,0.072549,-0.035201,-0.027279,0.017115,0.043631,0.024660,-0.025841,0.031320,-0.076959,-0.072986,-0.040465,0.003958,-0.022475,0.033208,-0.028056,-0.005499,-0.055998,-0.021882,-0.070462,0.018237,-0.031396,-0.074606,0.072951,0.039997,0.036423,-0.027152,-0.071900,0.026267,-0.046270,-0.017945,0.007933,-0.006203,-0.046099,0.032793,-0.069113,0.020403,0.030783,-0.003787,-0.000490,-0.022951,0.013498,0.009664,-0.007012,-0.016325,-0.005732,0.036069,-0.063906,0.033891,0.010560,-0.104517,-0.022069,0.054322,-0.005460,-0.029093,0.040991,-0.053018,-0.024017,0.050817,-0.003297,-0.020895,-0.053213,-0.028428,0.048231,-0.001221,0.001302,-0.044137,0.015528,-0.012792,-0.012009,-0.008211,0.031114,0.024982,0.003863,-0.032321,0.030920,-0.012845,0.070170,-0.004037,0.014003,0.005577,0.021611,-0.002889,0.034824,0.047164,0.050545,-0.017639,0.029014,-0.030378,-0.027056,0.011464,-0.039759,-0.043514,-0.025605,-0.022484,-0.036224,0.000566,0.005481
5,2022-02-24 02:00:00,2,49.2336,28.4486,2.8,-0.3,80.5,0.3,100.0,4.17,0.0,0.0,27.7,10.8,312.0,1023.4,82.5,60.4,5.4,3.0,0.77,2.0,-0.3,90.44,0.0,0.0,0.0,27.7,7.6,287.6,1021.0,98.2,0.0,0.1,0.0,False,False,False,True,False,True,False,False,2022,2,3,2,Vinnytsia,Europe/Kiev,2022-02-24,06:58:49,17:40:52,02:00:00,Вінницька,0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0.0,0.0,3,0.580161,-0.090608,-0.028388,0.146350,0.071072,-0.030284,-0.004583,0.087399,-0.038512,0.016613,-0.038599,0.049747,0.186305,-0.172198,-0.045515,0.050785,0.041889,-0.112849,0.193473,-0.010566,0.044308,-0.118300,0.007117,-0.135687,-0.009441,-0.039465,0.032843,0.080393,-0.035434,0.010352,-0.016680,-0.046252,0.085840,-0.123167,0.064510,-0.023735,-0.025637,-0.027863,0.032156,0.068641,0.027667,0.162729,0.039675,-0.016915,-0.008203,0.048024,0.073343,0.025782,-0.013935,-0.008775,-0.045265,0.008979,-0.100558,0.044074,0.018202,-0.037279,0.062349,0.008014,0.075917,-0.063409,0.015404,-0.091507,-0.079240,-0.033000,-0.019226,-0.103926,0.031514,0.043306,-0.012137,-0.010430,0.035901,-0.013437,-0.042046,-0.064986,0.002947,0.024326,0.085592,-0.008453,0.091087,-0.106852,0.038223,-0.061062,0.027905,0.056421,-0.030501,0.000050,0.051385,-0.087324,-0.024025,0.031626,-0.029461,0.015717,-0.047181,-0.005600,0.049867,0.084412,-0.055460,-0.036620,0.120475,-0.012080,0.006961,-0.079701,0.055655,0.004130,0.013250,0.002392,0.041937,0.028208,-0.037232,0.014886,-0.036905,0.000138,-0.018200,-0.010680,-0.067564,-0.001064,-0.044792,-0.014807,-0.031911,-0.023504,0.070783,0.027626,0.000418,0.043677,-0.030193,-0.034979,0.080093,0.035489,-0.004156,-0.008032,0.039826,-0.037380,0.011931,0.008267,0.000590,0.043862,0.023758,0.038714,0.066128,0.028168,-0.012153,0.005376,0.008085,-0.038933,0.003404,0.003281,-0.004149,-0.025392,0.010434,-0.017613
6,2022-02-24 03:00:00,2,49.2336,28.4486,2.8,-0.3,80.5,0.3,100.0,4.17,0.0,0.0,27.7,10.8,312.0,1023.4,82.5,60.4,5.4,3.0,0.77,1.9,-0.3,91.75,0.0,0.0,0.0,15.1,7.2,288.9,1021.0,98.8,0.0,0.1,0.0,False,False,False,True,False,True,False,False,2022,2,3,3,Vinnytsia,Europe/Kiev,2022-02-24,06:58:49,17:40:52,03:00:00,Вінницька,0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0.0,0.0,4,0.648336,-0.079572,0.178041,0.061854,0.073453,-0.055809,-0.011311,0.047310,0.008354,0.006474,-0.047099,0.020496,0.050190,-0.038573,0.057228,-0.072471,0.045393,-0.116783,0.168249,0.167355,-0.025072,-0.073858,-0.097024,-0.146191,0.027983,0.082989,0.014423,0.058370,-0.033928,0.046265,0.006901,-0.049498,0.126117,-0.089039,-0.006767,-0.031686,-0.010346,0.025637,0.061278,0.162580,-0.028081,0.161291,-0.018217,-0.002657,0.038485,-0.000530,0.044413,0.107176,-0.050721,0.064279,-0.066677,0.016742,-0.050257,0.072549,-0.035201,-0.027279,0.017115,0.043631,0.024660,-0.025841,0.031320,-0.076959,-0.072986,-0.040465,0.003958,-0.022475,0.033208,-0.028056,-0.005499,-0.055998,-0.021882,-0.070462,0.018237,-0.031396,-0.074606,0.072951,0.039997,0.036423,-0.027152,-0.071900,0.026267,-0.046270,-0.017945,0.007933,-0.006203,-0.046099,0.032793,-0.069113,0.020403,0.030783,-0.003787,-0.000490,-0.022951,0.013498,0.009664,-0.007012,-0.016325,-0.005732,0.036069,-0.063906,0.033891,0.010560,-0.104517,-0.022069,0.054322,-0.005460,-0.029093,0.040991,-0.053018,-0.024017,0.050817,-0.003297,-0.020895,-0.053213,-0.028428,0.048231,-0.001221,0.001302,-0.044137,0.015528,-0.012792,-0.012009,-0.008211,0.031114,0.024982,0.003863,-0.032321,0.030920,-0.012845,0.070170,-0.004037,0.014003,0.005577,0.021611,-0.002889,0.034824,0.047164,0.050545,-0.017639,0.029014,-0.030378,-0.027056,0.011464,-0.039759,-0.043514,-0.025605,-0.022484,-0.036224,0.000566,0.005481
7,2022-02-24 03:00:00,2,49.2336,28.4486,2.8,-0.3,80.5,0.3,100.0,4.17,0.0,0.0,27.7,10.8,312.0,1023.4,82.5,60.4,5.4,3.0,0.77,1.9,-0.3,91.75,0.0,0.0,0.0,15.1,7.2,288.9,1021.0,98.8,0.0,0.1,0.0,False,False,False,True,False,True,False,False,2022,2,3,3,Vinnytsia,Europe/Kiev,2022-02-24,06:58:49,17:40:52,03:00:00,Вінницька,0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0.0,0.0,4,0.580161,-0.090608,-0.028388,0.146350,0.071072,-0.030284,-0.004583,0.087399,-0.038512,0.016613,-0.038599,0.049747,0.186305,-0.172198,-0.045515,0.050785,0.041889,-0.112849,0.193473,-0.010566,0.044308,-0.118300,0.007117,-0.135687,-0.009441,-0.039465,0.032843,0.080393,-0.035434,0.010352,-0.016680,-0.046252,0.085840,-0.123167,0.064510,-0.023735,-0.025637,-0.027863,0.032156,0.068641,0.027667,0.162729,0.039675,-0.016915,-0.008203,0.048024,0.073343,0.025782,-0.013935,-0.008775,-0.045265,0.008979,-0.100558,0.044074,0.018202,-0.037279,0.062349,0.008014,0.075917,-0.063409,0.015404,-0.091507,-0.079240,-0.033000,-0.019226,-0.103926,0.031514,0.043306,-0.012137,-0.010430,0.035901,-0.013437,-0.042046,-0.064986,0.002947,0.024326,0.085592,-0.008453,0.091087,-0.106852,0.038223,-0.061062,0.027905,0.056421,-0.030501,0.000050,0.051385,-0.087324,-0.024025,0.031626,-0.029461,0.015717,-0.047181,-0.005600,0.049867,0.084412,-0.055460,-0.036620,0.120475,-0.012080,0.006961,-0.079701,0.055655,0.004130,0.013250,0.002392,0.041937,0.028208,-0.037232,0.014886,-0.036905,0.000138,-0.018200,-0.010680,-0.067564,-0.001064,-0.044792,-0.014807,-0.031911,-0.023504,0.070783,0.027626,0.000418,0.043677,-0.030193,-0.034979,0.080093,0.035489,-0.004156,-0.008032,0.039826,-0.037380,0.011931,0.008267,0.000590,0.043862,0.023758,0.038714,0.066128,0.028168,-0.012153,0.005376,0.008085,-0.038933,0.003404,0.003281,-0.004149,-0.025392,0.010434,-0.017613
8,2022-02-24 04:00:00,2,49.2336,28.4486,2.8,-0.3,80.5,0.3,100.0,4.17,0.0,0.0,27.7,10.8,312.0,1023.4,82.5,60.4,5.4,3.0,0.77,1.8,-0.2,92.40,0.0,0.0,0.0,13.7,6.5,290.4,1021.0,100.0,0.0,0.1,0.0,False,False,False,True,False,True,False,False,2022,2,3,4,Vinnytsia,Europe/Kiev,2022-02-24,06:58:49,17:40:52,04:00:00,Вінницька,0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0.0,0.0,5,0.648336,-0.079572,0.178041,0.061854,0.073453,-0.055809,-0.011311,0.047310,0.008354,0.006474,-0.047099,0.020496,0.050190,-0.038573,0.057228,-0.072471,0.045393,-0.116783,0.168249,0.167355,-0.025072,-0.073858,-0.097024,-0.146191,0.027983,0.082989,0.014423,0.058370,-0.033928,0.046265,0.006901,-0.049498,0.126117,-0.089039,-0.006767,-0.031686,-0.010346,0.025637,0.061278,0.162580,-0.028081,0.161291,-0.018217,-0.002657,0.038485,-0.000530,0.044413,0.107176,-0.050721,0.064279,-0.066677,0.016742,-0.050257,0.072549,-0.035201,-0.027279,0.017115,0.043631,0.024660,-0.025841,0.031320,-0.076959,-0.072986,-0.040465,0.003958,-0.022475,0.033208,-0.028056,-0.005499,-0.055998,-0.021882,-0.070462,0.018237,-0.031396,-0.074606,0.072951,0.039997,0.036423,-0.027152,-0.071900,0.026267,-0.046270,-0.017945,0.007933,-0.006203,-0.046099,0.032793,-0.069113,0.020403,0.030783,-0.003787,-0.000490,-0.022951,0.013498,0.009664,-0.007012,-0.016325,-0.005732,0.036069,-0.063906,0.033891,0.010560,-0.104517,-0.022069,0.054322,-0.005460,-0.029093,0.040991,-0.053018,-0.024017,0.050817,-0.003297,-0.020895,-0.053213,-0.028428,0.048231,-0.001221,0.001302,-0.044137,0.015528,-0.012792,-0.012009,-0.008211,0.031114,0.024982,0.003863,-0.032321,0.030920,-0.012845,0.070170,-0.004037,0.014003,0.005577,0.021611,-0.002889,0.034824,0.047164,0.050545,-0.017639,0.029014,-0.030378,-0.027056,0.011464,-0.039759,-0.043514,-0.025605,-0.022484,-0.036224,0.000566,0.005481

In [18]:
df_final.isna().sum()

datetime_hour        0
region_id            0
city_latitude        0
city_longitude       0
day_temp             0
                  ...
isw_topic_145     5760
isw_topic_146     5760
isw_topic_147     5760
isw_topic_148     5760
isw_topic_149     5760
Length: 216, dtype: int64

In [19]:
df_final.fillna(0, inplace=True)

,datetime_hour,region_id,city_latitude,city_longitude,day_temp,day_dew,day_humidity,day_precip,day_precipprob,day_precipcover,day_snow,day_snowdepth,day_windgust,day_windspeed,day_winddir,day_pressure,day_cloudcover,day_solarradiation,day_solarenergy,day_uvindex,day_moonphase,hour_temp,hour_feelslike,hour_humidity,hour_precip,hour_precipprob,hour_snow,hour_windgust,hour_windspeed,hour_winddir,hour_pressure,hour_cloudcover,hour_solarradiation,hour_solarenergy,hour_uvindex,day_conditions_simple_Clear,day_conditions_simple_Cloudy,day_conditions_simple_Rain,day_conditions_simple_Snow,hour_conditions_simple_Clear,hour_conditions_simple_Cloudy,hour_conditions_simple_Rain,hour_conditions_simple_Snow,year,month,day_of_week,hour,city_name,city_timezone,day_datetime,day_sunrise,day_sunset,hour_datetime,region_key,alarm_active,alarm_minutes_in_hour,alarm_lag_1,alarm_lag_3,alarm_lag_6,alarm_lag_12,alarms_in_last_24h,is_weekend,is_night,total_active_alarms_lag1,neighbour_alarms,hours_since_last_alarm,isw_topic_0,isw_topic_1,isw_topic_2,isw_topic_3,isw_topic_4,isw_topic_5,isw_topic_6,isw_topic_7,isw_topic_8,isw_topic_9,isw_topic_10,isw_topic_11,isw_topic_12,isw_topic_13,isw_topic_14,isw_topic_15,isw_topic_16,isw_topic_17,isw_topic_18,isw_topic_19,isw_topic_20,isw_topic_21,isw_topic_22,isw_topic_23,isw_topic_24,isw_topic_25,isw_topic_26,isw_topic_27,isw_topic_28,isw_topic_29,isw_topic_30,isw_topic_31,isw_topic_32,isw_topic_33,isw_topic_34,isw_topic_35,isw_topic_36,isw_topic_37,isw_topic_38,isw_topic_39,isw_topic_40,isw_topic_41,isw_topic_42,isw_topic_43,isw_topic_44,isw_topic_45,isw_topic_46,isw_topic_47,isw_topic_48,isw_topic_49,isw_topic_50,isw_topic_51,isw_topic_52,isw_topic_53,isw_topic_54,isw_topic_55,isw_topic_56,isw_topic_57,isw_topic_58,isw_topic_59,isw_topic_60,isw_topic_61,isw_topic_62,isw_topic_63,isw_topic_64,isw_topic_65,isw_topic_66,isw_topic_67,isw_topic_68,isw_topic_69,isw_topic_70,isw_topic_71,isw_topic_72,isw_topic_73,isw_topic_74,isw_topic_75,isw_topic_76,isw_topic_77,isw_topic_78,isw_topic_79,isw_topic_80,isw_topic_81,isw_topic_82,isw_topic_83,isw_topic_84,isw_topic_85,isw_topic_86,isw_topic_87,isw_topic_88,isw_topic_89,isw_topic_90,isw_topic_91,isw_topic_92,isw_topic_93,isw_topic_94,isw_topic_95,isw_topic_96,isw_topic_97,isw_topic_98,isw_topic_99,isw_topic_100,isw_topic_101,isw_topic_102,isw_topic_103,isw_topic_104,isw_topic_105,isw_topic_106,isw_topic_107,isw_topic_108,isw_topic_109,isw_topic_110,isw_topic_111,isw_topic_112,isw_topic_113,isw_topic_114,isw_topic_115,isw_topic_116,isw_topic_117,isw_topic_118,isw_topic_119,isw_topic_120,isw_topic_121,isw_topic_122,isw_topic_123,isw_topic_124,isw_topic_125,isw_topic_126,isw_topic_127,isw_topic_128,isw_topic_129,isw_topic_130,isw_topic_131,isw_topic_132,isw_topic_133,isw_topic_134,isw_topic_135,isw_topic_136,isw_topic_137,isw_topic_138,isw_topic_139,isw_topic_140,isw_topic_141,isw_topic_142,isw_topic_143,isw_topic_144,isw_topic_145,isw_topic_146,isw_topic_147,isw_topic_148,isw_topic_149
0,2022-02-24 00:00:00,2,49.2336,28.4486,2.8,-0.3,80.5,0.3,100.0,4.17,0.0,0.0,27.7,10.8,312.0,1023.4,82.5,60.4,5.4,3.0,0.77,2.1,-0.5,91.76,0.0,0.0,0.0,16.6,8.6,279.6,1021.0,91.1,0.0,0.1,0.0,False,False,False,True,False,True,False,False,2022,2,3,0,Vinnytsia,Europe/Kiev,2022-02-24,06:58:49,17:40:52,00:00:00,Вінницька,0,0.000000,0.0,0.0,0.0,0.0,0.0,0,1,0.0,0.0,1,0.648336,-0.079572,0.178041,0.061854,0.073453,-0.055809,-0.011311,0.047310,0.008354,0.006474,-0.047099,0.020496,0.050190,-0.038573,0.057228,-0.072471,0.045393,-0.116783,0.168249,0.167355,-0.025072,-0.073858,-0.097024,-0.146191,0.027983,0.082989,0.014423,0.058370,-0.033928,0.046265,0.006901,-0.049498,0.126117,-0.089039,-0.006767,-0.031686,-0.010346,0.025637,0.061278,0.162580,-0.028081,0.161291,-0.018217,-0.002657,0.038485,-0.000530,0.044413,0.107176,-0.050721,0.064279,-0.066677,0.016742,-0.050257,0.072549,-0.035201,-0.027279,0.017115,0.043631,0.024660,-0.025841,0.031320,-0.076959,-0.072986,-0.040465,0.003958,-0.022475,0.033208,-0.028056,-0.005499,-0.055998,-0.021882,-0.070462,0.018237,-0.031396,-0.074606,0.072951,0.039997,0.036423,-0.027152,-0.071900,0.026267,-0.046270,-0.017945,0.007933,-0.006203,-0.046099,0.032793,-0.069113,0.020403,0.030783,-0.003787,-0.000490,-0.022951,0.013498,0.009664,-0.007012,-0.016325,-0.005732,0.036069,-0.063906,0.033891,0.010560,-0.104517,-0.022069,0.054322,-0.005460,-0.029093,0.040991,-0.053018,-0.024017,0.050817,-0.003297,-0.020895,-0.053213,-0.028428,0.048231,-0.001221,0.001302,-0.044137,0.015528,-0.012792,-0.012009,-0.008211,0.031114,0.024982,0.003863,-0.032321,0.030920,-0.012845,0.070170,-0.004037,0.014003,0.005577,0.021611,-0.002889,0.034824,0.047164,0.050545,-0.017639,0.029014,-0.030378,-0.027056,0.011464,-0.039759,-0.043514,-0.025605,-0.022484,-0.036224,0.000566,0.005481
1,2022-02-24 00:00:00,2,49.2336,28.4486,2.8,-0.3,80.5,0.3,100.0,4.17,0.0,0.0,27.7,10.8,312.0,1023.4,82.5,60.4,5.4,3.0,0.77,2.1,-0.5,91.76,0.0,0.0,0.0,16.6,8.6,279.6,1021.0,91.1,0.0,0.1,0.0,False,False,False,True,False,True,False,False,2022,2,3,0,Vinnytsia,Europe/Kiev,2022-02-24,06:58:49,17:40:52,00:00:00,Вінницька,0,0.000000,0.0,0.0,0.0,0.0,0.0,0,1,0.0,0.0,1,0.580161,-0.090608,-0.028388,0.146350,0.071072,-0.030284,-0.004583,0.087399,-0.038512,0.016613,-0.038599,0.049747,0.186305,-0.172198,-0.045515,0.050785,0.041889,-0.112849,0.193473,-0.010566,0.044308,-0.118300,0.007117,-0.135687,-0.009441,-0.039465,0.032843,0.080393,-0.035434,0.010352,-0.016680,-0.046252,0.085840,-0.123167,0.064510,-0.023735,-0.025637,-0.027863,0.032156,0.068641,0.027667,0.162729,0.039675,-0.016915,-0.008203,0.048024,0.073343,0.025782,-0.013935,-0.008775,-0.045265,0.008979,-0.100558,0.044074,0.018202,-0.037279,0.062349,0.008014,0.075917,-0.063409,0.015404,-0.091507,-0.079240,-0.033000,-0.019226,-0.103926,0.031514,0.043306,-0.012137,-0.010430,0.035901,-0.013437,-0.042046,-0.064986,0.002947,0.024326,0.085592,-0.008453,0.091087,-0.106852,0.038223,-0.061062,0.027905,0.056421,-0.030501,0.000050,0.051385,-0.087324,-0.024025,0.031626,-0.029461,0.015717,-0.047181,-0.005600,0.049867,0.084412,-0.055460,-0.036620,0.120475,-0.012080,0.006961,-0.079701,0.055655,0.004130,0.013250,0.002392,0.041937,0.028208,-0.037232,0.014886,-0.036905,0.000138,-0.018200,-0.010680,-0.067564,-0.001064,-0.044792,-0.014807,-0.031911,-0.023504,0.070783,0.027626,0.000418,0.043677,-0.030193,-0.034979,0.080093,0.035489,-0.004156,-0.008032,0.039826,-0.037380,0.011931,0.008267,0.000590,0.043862,0.023758,0.038714,0.066128,0.028168,-0.012153,0.005376,0.008085,-0.038933,0.003404,0.003281,-0.004149,-0.025392,0.010434,-0.017613
2,2022-02-24 01:00:00,2,49.2336,28.4486,2.8,-0.3,80.5,0.3,100.0,4.17,0.0,0.0,27.7,10.8,312.0,1023.4,82.5,60.4,5.4,3.0,0.77,2.1,-0.4,89.80,0.0,0.0,0.0,16.6,8.3,289.2,1021.0,97.9,0.0,0.1,0.0,False,False,False,True,False,True,False,False,2022,2,3,1,Vinnytsia,Europe/Kiev,2022-02-24,06:58:49,17:40:52,01:00:00,Вінницька,0,0.000000,0.0,0.0,0.0,0.0,0.0,0,1,0.0,0.0,2,0.648336,-0.079572,0.178041,0.061854,0.073453,-0.055809,-0.011311,0.047310,0.008354,0.006474,-0.047099,0.020496,0.050190,-0.038573,0.057228,-0.072471,0.045393,-0.116783,0.168249,0.167355,-0.025072,-0.073858,-0.097024,-0.146191,0.027983,0.082989,0.014423,0.058370,-0.033928,0.046265,0.006901,-0.049498,0.126117,-0.089039,-0.006767,-0.031686,-0.010346,0.025637,0.061278,0.162580,-0.028081,0.161291,-0.018217,-0.002657,0.038485,-0.000530,0.044413,0.107176,-0.050721,0.064279,-0.066677,0.016742,-0.050257,0.072549,-0.035201,-0.027279,0.017115,0.043631,0.024660,-0.025841,0.031320,-0.076959,-0.072986,-0.040465,0.003958,-0.022475,0.033208,-0.028056,-0.005499,-0.055998,-0.021882,-0.070462,0.018237,-0.031396,-0.074606,0.072951,0.039997,0.036423,-0.027152,-0.071900,0.026267,-0.046270,-0.017945,0.007933,-0.006203,-0.046099,0.032793,-0.069113,0.020403,0.030783,-0.003787,-0.000490,-0.022951,0.013498,0.009664,-0.007012,-0.016325,-0.005732,0.036069,-0.063906,0.033891,0.010560,-0.104517,-0.022069,0.054322,-0.005460,-0.029093,0.040991,-0.053018,-0.024017,0.050817,-0.003297,-0.020895,-0.053213,-0.028428,0.048231,-0.001221,0.001302,-0.044137,0.015528,-0.012792,-0.012009,-0.008211,0.031114,0.024982,0.003863,-0.032321,0.030920,-0.012845,0.070170,-0.004037,0.014003,0.005577,0.021611,-0.002889,0.034824,0.047164,0.050545,-0.017639,0.029014,-0.030378,-0.027056,0.011464,-0.039759,-0.043514,-0.025605,-0.022484,-0.036224,0.000566,0.005481
3,2022-02-24 01:00:00,2,49.2336,28.4486,2.8,-0.3,80.5,0.3,100.0,4.17,0.0,0.0,27.7,10.8,312.0,1023.4,82.5,60.4,5.4,3.0,0.77,2.1,-0.4,89.80,0.0,0.0,0.0,16.6,8.3,289.2,1021.0,97.9,0.0,0.1,0.0,False,False,False,True,False,True,False,False,2022,2,3,1,Vinnytsia,Europe/Kiev,2022-02-24,06:58:49,17:40:52,01:00:00,Вінницька,0,0.000000,0.0,0.0,0.0,0.0,0.0,0,1,0.0,0.0,2,0.580161,-0.090608,-0.028388,0.146350,0.071072,-0.030284,-0.004583,0.087399,-0.038512,0.016613,-0.038599,0.049747,0.186305,-0.172198,-0.045515,0.050785,0.041889,-0.112849,0.193473,-0.010566,0.044308,-0.118300,0.007117,-0.135687,-0.009441,-0.039465,0.032843,0.080393,-0.035434,0.010352,-0.016680,-0.046252,0.085840,-0.123167,0.064510,-0.023735,-0.025637,-0.027863,0.032156,0.068641,0.027667,0.162729,0.039675,-0.016915,-0.008203,0.048024,0.073343,0.025782,-0.013935,-0.008775,-0.045265,0.008979,-0.100558,0.044074,0.018202,-0.037279,0.062349,0.008014,0.075917,-0.063409,0.015404,-0.091507,-0.079240,-0.033000,-0.019226,-0.103926,0.031514,0.043306,-0.012137,-0.010430,0.035901,-0.013437,-0.042046,-0.064986,0.002947,0.024326,0.085592,-0.008453,0.091087,-0.106852,0.038223,-0.061062,0.027905,0.056421,-0.030501,0.000050,0.051385,-0.087324,-0.024025,0.031626,-0.029461,0.015717,-0.047181,-0.005600,0.049867,0.084412,-0.055460,-0.036620,0.120475,-0.012080,0.006961,-0.079701,0.055655,0.004130,0.013250,0.002392,0.041937,0.028208,-0.037232,0.014886,-0.036905,0.000138,-0.018200,-0.010680,-0.067564,-0.001064,-0.044792,-0.014807,-0.031911,-0.023504,0.070783,0.027626,0.000418,0.043677,-0.030193,-0.034979,0.080093,0.035489,-0.004156,-0.008032,0.039826,-0.037380,0.011931,0.008267,0.000590,0.043862,0.023758,0.038714,0.066128,0.028168,-0.012153,0.005376,0.008085,-0.038933,0.003404,0.003281,-0.004149,-0.025392,0.010434,-0.017613
4,2022-02-24 02:00:00,2,49.2336,28.4486,2.8,-0.3,80.5,0.3,100.0,4.17,0.0,0.0,27.7,10.8,312.0,1023.4,82.5,60.4,5.4,3.0,0.77,2.0,-0.3,90.44,0.0,0.0,0.0,27.7,7.6,287.6,1021.0,98.2,0.0,0.1,0.0,False,False,False,True,False,True,False,False,2022,2,3,2,Vinnytsia,Europe/Kiev,2022-02-24,06:58:49,17:40:52,02:00:00,Вінницька,0,0.000000,0.0,0.0,0.0,0.0,0.0,0,1,0.0,0.0,3,0.648336,-0.079572,0.178041,0.061854,0.073453,-0.055809,-0.011311,0.047310,0.008354,0.006474,-0.047099,0.020496,0.050190,-0.038573,0.057228,-0.072471,0.045393,-0.116783,0.168249,0.167355,-0.025072,-0.073858,-0.097024,-0.146191,0.027983,0.082989,0.014423,0.058370,-0.033928,0.046265,0.006901,-0.049498,0.126117,-0.089039,-0.006767,-0.031686,-0.010346,0.025637,0.061278,0.162580,-0.028081,0.161291,-0.018217,-0.002657,0.038485,-0.000530,0.044413,0.107176,-0.050721,0.064279,-0.066677,0.016742,-0.050257,0.072549,-0.035201,-0.027279,0.017115,0.043631,0.024660,-0.025841,0.031320,-0.076959,-0.072986,-0.040465,0.003958,-0.022475,0.033208,-0.028056,-0.005499,-0.055998,-0.021882,-0.070462,0.018237,-0.031396,-0.074606,0.072951,0.039997,0.036423,-0.027152,-0.071900,0.026267,-0.046270,-0.017945,0.007933,-0.006203,-0.046099,0.032793,-0.069113,0.020403,0.030783,-0.003787,-0.000490,-0.022951,0.013498,0.009664,-0.007012,-0.016325,-0.005732,0.036069,-0.063906,0.033891,0.010560,-0.104517,-0.022069,0.054322,-0.005460,-0.029093,0.040991,-0.053018,-0.024017,0.050817,-0.003297,-0.020895,-0.053213,-0.028428,0.048231,-0.001221,0.001302,-0.044137,0.015528,-0.012792,-0.012009,-0.008211,0.031114,0.024982,0.003863,-0.032321,0.030920,-0.012845,0.070170,-0.004037,0.014003,0.005577,0.021611,-0.002889,0.034824,0.047164,0.050545,-0.017639,0.029014,-0.030378,-0.027056,0.011464,-0.039759,-0.043514,-0.025605,-0.022484,-0.036224,0.000566,0.005481
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
635251,2025-03-01 19:00:00,26,50.4506,30.5243,0.0,-2.6,82.9,0.7,100.0,8.33,1.3,1.0,34.6,15.5,178.1,1026.7,99.5,40.6,3.6,2.0,0.05,-0.1,-3.5,97.13,0.0,0.0,0.0,16.9,10.1,181.6,1027.0,95.6,0.0,0.0,0.0,False,False,False,True,False,True,False,False,2025,3,5,19,Kyiv,Europe/Kiev,2025-03-01,06:41:35,17:39:46,19:00:00,Київ,0,0.000000,0.0,0.0,0.0,0.0,5.0,1,0,11.0,0.0,15,0.741253,0.175928,-0.044270,0.236290,0.000096,-0.082156,-0.069547,0.169634,0.047371,0.108829,-0.111513,0.005588,0.009037,-0.035562,0.049145,0.077242,-0.085251,0.067886,0.052548,-0.120459,0.081966,-0.062164,0.022709,0.023532,-0.002714,0.000626,-0.026931,0.012943,-0.027664,-0.111107,-0.094103,-0.019189,-0.002106,0.023217,0.036788,-0.009149,-0.051459,-0.073844,-0.016720,-0.019477,-0.024286,0.075470,-0.053957,-0.052265,0.022580,-0.016046,-0.047243,0.005718,0.019756,-0.035501,0.025955,0.020804,-0.008431,0.005311,-0.038751,-0.010557,-0.009238,-0.005986,-0.035657,-0.003185,-0.030416,-0.013563,-0.026338,0.069073,-0.003216,0.021366,0.025951,-0.017980,0.006948,0.029034,0.069441,-0.043368,0.028677,0.035237,-0.023784,-0.005083,0.028958,0.012654,0.001550,-0.039223,0.020654,-0.040622,0.014536,0.002429,-0.013533,0.003547,-0.061560,0.020515,-0.017876,0.041345,-0.033319,-0.020192,0.035267,0.011339,-0.088522,0.022461,-0.047734,-0.034346,-0.011346,0.043122,0.001617,-0.023157,-0.018391,-0.006131,0.040270,0.030336,0.007110,0.024232,0.035189,-0.038329,0.020301,0.032434,0.007683,-0.010900,-0.008896,-0.019209,0.007017,0.040898,-0.031859,0.000779,-0.002852,0.028824,0.006013,0.010350,0.013379,-0.027336,-0.003269,0.008264,0.004228,0.022508,-0.012380,0.000627,0.017807,-0.013325,-0.006459,0.021368,-0.027278,-0.008352,0.001816,0.004596,0.019812,-0.012733,-0.001035,-0.001903,0.005062,-0.015576,0.028419,-0.012698,0.016105,-0.007801
635252,2025-03-01 20:00:00,26,50.4506,30.5243,0.0,-2.6,82.9,0.7,100.0,8.33,1.3,1.0,34.6,15.5,178.1,1026.7,99.5,40.6,3.6,2.0,0.05,-0.3,-0.3,92.96,0.4,100.0,0.0,17.6,0.0,189.9,1027.0,100.0,0.0,0.0,0.0,False,False,False,True,False,False,False,True,2025,3,5,20,Kyiv,Europe/Kiev,2025-03-01,06:41:35,17:39:46,20:00:00,Київ,0,0.000000,0.0,0.0,0.0,0.0,5.0,1,0,5.0,0.0,16,0.741253,0.175928,-0.044270,0.236290,0.000096,-0.082156,-0.069547,0.169634,0.047371,0.108829,-0.111513,0.005588,0.009037,-0.035562,0.049145,0.077242,-0.085251,0.067886,0.052548,-0.120459,0.081966,-0.062164,0.022709,0.023532,-0.002714,0.000626,-0.026931,0.012943,-0.027664,-0.111107,-0.094103,-0.019189,-0.002106,0.023217,0.036788,-0.009149,-0.051459,-0.073844,-0.016720,-0.019477,-0.024286,0.075470,-0.053957,-0.052265,0.022580,-0.016046,-0.047243,0.005718,0.019756,-0.035501,0.025955,0.020804,-0.008431,0.005311,-0.038751,-0.010557,-0.009238,-0.005986,-0.035657,-0.003185,-0.030416,-0.013563,-0.026338,0.069073,-0.003216,0.021366,0.025951,-0.017980,0.006948,0.029034,0.069441,-0.043368,0.028677,0.035237,-0.023784,-0.005083,0.028958,0.012654,0.001550,-0.039223,0.020654,-0.040622,0.014536,0.002429,-0.013533,0.003547,-0.061560,0.020515,-0.017876,0.041345,-0.033319,-0.020192,0.035267,0.011339,-0.088522,0.022461,-0.047734,-0.034346,-0.011346,0.043122,0.001617,-0.023157,-0.018391,-0.006131,0.040270,0.030336,0.007110,0.024232,0.035189,-0.038329,0.020301,0.032434,0.007683,-0.010900,-0.008896,-0.019209,0.007017,0.040898,-0.031859,0.000779,-0.002852,0.028824,0.006013,0.010350,0.013379,-0.027336,-0.003269,0.008264,0.004228,0.022508,-0.012380,0.000627,0.017807,-0.013325,-0.006459,0.021368,-0.027278,-0.008352,0.001816,0.004596,0.019812,-0.012733,-0.001035,-0.001903,0.005062,-0.015576,0.028419,-0.012698,0.016105,-0.007801
635253,2025-03-01 21:00:00,26,50.4506,30.5243,0.0,-2.6,82.9,0.7,100.0,8.33,1.3,1.0,34.6,15.5,178.1,1026.7,99.5,40.6,3.6,2.0,0.05,0.0,-3.2,96.43,0.0,0.0,0.0,18.4,9.4,198.3,1027.0,100.0,0.0,0.0,0.0,False,False,False,True,False,True,False,False,2025,3,5,21,Kyiv,Europe/Kiev,2025-03-01,06:41:35,17:39:46,21:00:00,Київ,0,0.000000,0.0,0.0,0.0,0.0,5.0,1,0,9.0,0.0,17,0.741253,0.175928,-0.044270,0.236290,0.000096,-0.082156,-0.069547,0.169634,0.047371,0.108829,-0.111513,0.005588,0.009037,-0.035562,0.049145,0.077242,-0.085251,0.067886,0.052548,-0.120459,0.081966,-0.062164,0.022709,0.023532,-0.002714,0.000626,-0.026931,0.012943,-0.027664,-0.111107,-0.094103,-0.019189,-0.002106,0.023217,0.036788,-0.009149,-0.051459,-0.073844,-0.016720,-0.019477,-0.024286,0.075470,-0.053957,-0.052265,0.022580,-0.016046,-0.047243,0.005718,0.019756,-0.035501,0.025955,0.020804,-0.008431,0.005311,-0.038751,-0.010557,-0.009238,-0.005986,-0.035657,-0.003185,-0.030416,-0.013563,-0.026338,0.069073,-0.003216,0.021366,0.025951,-0.017980,0.006948,0.029034,0.069441,-0.043368,0.028677,0.035237,-0.023784,-0.005083,0.028958,0.012654,0.001550,-0.039223,0.020654,-0.040622,0.014536,0.002429,-0.013533,0.003547,-0.061560,0.020515,-0.017876,0.041345,-0.033319,-0.020192,0.035267,0.011339,-0.088522,0.022461,-0.047734,-0.034346,-0.011346,0.043122,0.001617,-0.023157,-0.018391,-0.006131,0.040270,0.030336,0.007110,0.024232,0.035189,-0.038329,0.020301,0.032434,0.007683,-0.010900,-0.008896,-0.019209,0.007017,0.040898,-0.031859,0.000779,-0.002852,0.028824,0.006013,0.010350,0.013379,-0.027336,-0.003269,0.008264,0.004228,0.022508,-0.012380,0.000627,0.017807,-0.013325,-0.006459,0.021368,-0.027278,-0.008352,0.001816,0.004596,0.019812,-0.012733,-0.001035,-0.001903,0.005062,-0.015576,0.028419,-0.012698,0.016105,-0.007801
635254,2025-03-01 22:00:00,26,50.4506,30.5243,0.0,-2.6,82.9,0.7,100.0,8.33,1.3,1.0,34.6,15.5,178.1,1026.7,99.5,40.6,3.6,2.0,0.05,0.0,-2.9,97.84,0.0,0.0,0.0,16.6,8.3,199.9,1027.0,97.6,0.0,0.0,0.0,False,False,False,True,False,True,False,False,2025,3,5,22,Kyiv,Europe/Kiev,2025-03-01,06:41:35,17:39:46,22:00:00,Київ,1,7.833333,0.0,0.0,0.0,0.0,5.0,1,0,11.0,0.0,18,0.741253,0.175928,-0.044270,0.236290,0.000096,-0.082156,-0.069547,0.169634,0.047371,0.108829,-0.111513,0.005588,0.009037,-0.035562,0.049145,0.077242,-0.085251,0.067886,0.052548,-0.120459,0.081966,-0.062164,0.022709,0.023532,-0.002714,0.000626,-0.026931,0.012943,-0.027664,-0.111107,-0.094103,-0.019189,-0.002106,0.023217,0.036788,-0.009149,-0.051459,-0.073844,-0.016720,-0.019477,-0.024286,0.075470,-0.053957,-0.052265,0.022580,-0.016046,-0.047243,0.005718,0.019756,-0.035501,0.025955,0.020804,-0.008431,0.005311,-0.038751,-0.010557,-0.009238,-0.005986,-0.035657,-0.003185,-0.030416,-0.013563,-0.026338,0.069073,-0.003216,0.021366,0.025951,-0.017980,0.006948,0.029034,0.069441,-0.043368,0.028677,0.035237,-0.023784,-0.005083,0.028958,0.012654,0.001550,-0.039223,0.020654,-0.040622,0.014536,0.002429,-0.013533,0.003547,-0.061560,0.020515,-0.017876,0.041345,-0.033319,-0.020192,0.035267,0.011339,-0.088522,0.022461,-0.047734,-0.034346,-0.011346,0.043122,0.001617,-0.023157,-0.018391,-0.006131,0.040270,0.030336,0.007110,0.024232,0.035189,-0.038329,0.020301,0.032434,0.007683,-0.010900,-0.008896,-0.019209,0.007017,0.040898,-0.031859,0.000779,-0.002852,0.028824,0.006013,0.010350,0.013379,-0.027336,-0.003269,0.008264,0.004228,0.022508,-0.012380,0.000627,0.017807,-0.013325,-0.006459,0.021368,-0.027278,-0.008352,0.001816,0.004596,0.019812,-0.012733,-0.001035,-0.001903,0.005062,-0.015576,0.028419,-0.012698,0.016105,-0.007801

In [20]:
df_final.isna().sum()

datetime_hour     0
region_id         0
city_latitude     0
city_longitude    0
day_temp          0
                 ..
isw_topic_145     0
isw_topic_146     0
isw_topic_147     0
isw_topic_148     0
isw_topic_149     0
Length: 216, dtype: int64

### Feature engineering for isw topics

In [21]:
topic_cols = [c for c in df_final.columns if "isw_topic_" in c]
df_isw_abs = df_final[topic_cols].abs()

df_final['isw_total_intensity'] = df_isw_abs.sum(axis=1)
df_final['isw_topic_std'] = df_isw_abs.std(axis=1)
df_final['isw_topic_max'] = df_isw_abs.max(axis=1)
df_final['isw_topic_mean'] = df_isw_abs.mean(axis=1)

df_final['isw_velocity_24h'] = (
    df_final.groupby('region_id')['isw_total_intensity']
    .diff(24)
    .fillna(0)
)

df_final['isw_intensity_ema'] = (df_final.groupby('region_id')['isw_total_intensity'].transform(lambda x: x.shift(1).ewm(span=24).mean()))

df_final['isw_topic_entropy'] = -(df_isw_abs.div(df_isw_abs.sum(axis=1), axis=0) * np.log(df_isw_abs.div(df_isw_abs.sum(axis=1), axis=0) + 1e-9)).sum(axis=1)

isw_cols = ['isw_velocity_24h', 'isw_intensity_ema', 'isw_topic_entropy']
df_final[isw_cols] = df_final[isw_cols].fillna(0)

C:\Users\Uw11\AppData\Local\Temp\ipykernel_9680\1269306822.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_final['isw_total_intensity'] = df_isw_abs.sum(axis=1)
C:\Users\Uw11\AppData\Local\Temp\ipykernel_9680\1269306822.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_final['isw_topic_std'] = df_isw_abs.std(axis=1)
C:\Users\Uw11\AppData\Local\Temp\ipykernel_9680\1269306822.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_final['isw_topic_max'] = df_isw_abs.max(axis=1)
C:\Users\Uw11\AppData\Local\Temp\ipykernel_9680\1269306822.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_final['isw_topic_mean'] = df_isw_abs.mean(axis=1)
C:\Users\Uw11\AppData\Local\Temp\ipykernel_9680\1269306822.py:9: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_final['isw_velocity_24h'] = (
C:\Users\Uw11\AppData\Local\Temp\ipykernel_9680\1269306822.py:15: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_final['isw_intensity_ema'] = (df_final.groupby('region_id')['isw_total_intensity'].transform(lambda x: x.shift(1).ewm(span=24).mean()))
C:\Users\Uw11\AppData\Local\Temp\ipykernel_9680\1269306822.py:17: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_final['isw_topic_entropy'] = -(df_isw_abs.div(df_isw_abs.sum(axis=1), axis=0) * np.log(df_isw_abs.div(df_isw_abs.sum(axis=1), axis=0) + 1e-9)).sum(axis=1)

In [22]:
df_final.sample(10)

,datetime_hour,region_id,city_latitude,city_longitude,day_temp,day_dew,day_humidity,day_precip,day_precipprob,day_precipcover,day_snow,day_snowdepth,day_windgust,day_windspeed,day_winddir,day_pressure,day_cloudcover,day_solarradiation,day_solarenergy,day_uvindex,day_moonphase,hour_temp,hour_feelslike,hour_humidity,hour_precip,hour_precipprob,hour_snow,hour_windgust,hour_windspeed,hour_winddir,hour_pressure,hour_cloudcover,hour_solarradiation,hour_solarenergy,hour_uvindex,day_conditions_simple_Clear,day_conditions_simple_Cloudy,day_conditions_simple_Rain,day_conditions_simple_Snow,hour_conditions_simple_Clear,hour_conditions_simple_Cloudy,hour_conditions_simple_Rain,hour_conditions_simple_Snow,year,month,day_of_week,hour,city_name,city_timezone,day_datetime,day_sunrise,day_sunset,hour_datetime,region_key,alarm_active,alarm_minutes_in_hour,alarm_lag_1,alarm_lag_3,alarm_lag_6,alarm_lag_12,alarms_in_last_24h,is_weekend,is_night,total_active_alarms_lag1,neighbour_alarms,hours_since_last_alarm,isw_topic_0,isw_topic_1,isw_topic_2,isw_topic_3,isw_topic_4,isw_topic_5,isw_topic_6,isw_topic_7,isw_topic_8,isw_topic_9,isw_topic_10,isw_topic_11,isw_topic_12,isw_topic_13,isw_topic_14,isw_topic_15,isw_topic_16,isw_topic_17,isw_topic_18,isw_topic_19,isw_topic_20,isw_topic_21,isw_topic_22,isw_topic_23,isw_topic_24,isw_topic_25,isw_topic_26,isw_topic_27,isw_topic_28,isw_topic_29,isw_topic_30,isw_topic_31,isw_topic_32,isw_topic_33,isw_topic_34,isw_topic_35,isw_topic_36,isw_topic_37,isw_topic_38,isw_topic_39,isw_topic_40,isw_topic_41,isw_topic_42,isw_topic_43,isw_topic_44,isw_topic_45,isw_topic_46,isw_topic_47,isw_topic_48,isw_topic_49,isw_topic_50,isw_topic_51,isw_topic_52,isw_topic_53,isw_topic_54,isw_topic_55,isw_topic_56,isw_topic_57,isw_topic_58,isw_topic_59,isw_topic_60,isw_topic_61,isw_topic_62,isw_topic_63,isw_topic_64,isw_topic_65,isw_topic_66,isw_topic_67,isw_topic_68,isw_topic_69,isw_topic_70,isw_topic_71,isw_topic_72,isw_topic_73,isw_topic_74,isw_topic_75,isw_topic_76,isw_topic_77,isw_topic_78,isw_topic_79,isw_topic_80,isw_topic_81,isw_topic_82,isw_topic_83,isw_topic_84,isw_topic_85,isw_topic_86,isw_topic_87,isw_topic_88,isw_topic_89,isw_topic_90,isw_topic_91,isw_topic_92,isw_topic_93,isw_topic_94,isw_topic_95,isw_topic_96,isw_topic_97,isw_topic_98,isw_topic_99,isw_topic_100,isw_topic_101,isw_topic_102,isw_topic_103,isw_topic_104,isw_topic_105,isw_topic_106,isw_topic_107,isw_topic_108,isw_topic_109,isw_topic_110,isw_topic_111,isw_topic_112,isw_topic_113,isw_topic_114,isw_topic_115,isw_topic_116,isw_topic_117,isw_topic_118,isw_topic_119,isw_topic_120,isw_topic_121,isw_topic_122,isw_topic_123,isw_topic_124,isw_topic_125,isw_topic_126,isw_topic_127,isw_topic_128,isw_topic_129,isw_topic_130,isw_topic_131,isw_topic_132,isw_topic_133,isw_topic_134,isw_topic_135,isw_topic_136,isw_topic_137,isw_topic_138,isw_topic_139,isw_topic_140,isw_topic_141,isw_topic_142,isw_topic_143,isw_topic_144,isw_topic_145,isw_topic_146,isw_topic_147,isw_topic_148,isw_topic_149,isw_total_intensity,isw_topic_std,isw_topic_max,isw_topic_mean,isw_velocity_24h,isw_intensity_ema,isw_topic_entropy
501585,2025-01-05 18:00:00,21,46.6401,32.6142,-2.9,-7.2,73.1,0.0,0.0,0.00,0.0,0.0,21.2,13.3,226.8,1024.7,40.8,69.6,6.0,3.0,0.20,-2.5,-6.2,71.75,0.0,0.0,0.0,11.5,9.4,160.2,1024.0,0.0,0.0,0.0,0.0,False,True,False,False,True,False,False,False,2025,1,6,18,Kherson,Europe/Kiev,2025-01-05,07:33:46,16:16:36,18:00:00,Херсонська,0,0.0,0.0,0.0,0.0,0.0,3.0,1,0,1.0,0.0,6,0.793526,0.157732,-0.026631,0.011061,0.199061,0.161923,-0.086632,-0.142728,0.131822,-0.070354,-0.016827,-0.001201,-0.096205,0.075964,0.151865,-0.011329,-0.037589,0.011144,-0.005452,0.029509,0.044841,0.008196,-0.035128,0.008659,-0.029047,0.010610,-0.016562,0.018387,0.027200,0.058213,0.004053,0.011613,0.087437,0.018151,0.032665,-0.041993,-0.008453,-0.031692,0.067501,-0.011866,0.012803,-0.018421,-0.011163,0.009858,0.000692,0.006817,-0.018589,-0.020541,-0.021924,-0.026953,-0.003047,0.003924,0.041884,0.009875,-0.001100,0.004278,-0.008789,-0.024669,-0.013187,-0.002893,-0.002529,0.003100,0.002972,-0.004312,0.056106,0.037315,0.004270,-0.006048,-0.031577,-0.009276,0.025841,-0.009345,-0.010775,-0.018082,0.010601,0.025693,0.000684,-0.015986,-0.022320,-0.014209,0.045590,0.004550,-0.027006,0.017751,-0.034614,-0.005892,0.033261,-0.022269,0.006040,0.008352,0.000807,0.011566,-0.032854,0.000599,-0.015823,0.018474,-0.026401,-0.013001,0.016240,0.013808,0.022861,-0.024766,-0.010708,-0.001803,0.013364,0.018252,0.008753,-0.015831,-0.010863,0.022146,0.003295,0.011878,0.005819,0.001989,-0.004566,0.014539,-0.008727,-0.018745,-0.002788,-0.016507,-0.019578,0.014082,0.018911,-0.020144,0.009848,-0.023580,-0.003611,-0.011358,-0.017302,-0.007894,-0.010321,-0.014471,-0.020755,0.007162,0.007245,-0.010943,-0.007896,-0.008402,0.013372,-0.019041,0.004567,-0.043459,-0.000973,-0.006895,-0.019681,-0.021649,-0.007675,0.010592,-0.006962,0.002873,4.347610,0.070785,0.793526,0.028984,-0.336296,4.425545,4.095691
114808,2023-03-02 05:00:00,6,50.2536,28.6654,2.3,-2.0,74.3,0.0,0.0,0.00,0.0,0.0,28.8,14.8,287.9,1022.2,80.2,98.4,8.5,4.0,0.33,0.4,0.4,81.48,0.0,0.0,0.0,19.8,3.6,280.0,1023.2,100.0,0.0,0.0,0.0,False,True,False,False,False,True,False,False,2023,3,3,5,Zhytomyr,Europe/Kiev,2023-03-02,06:47:46,17:48:13,05:00:00,Житомирська,0,0.0,0.0,0.0,0.0,0.0,1.0,0,1,0.0,0.0,9,0.803324,-0.219432,-0.079492,0.091123,0.032156,-0.041607,-0.063748,0.180894,0.007591,0.141927,-0.058370,-0.014103,-0.073642,0.042764,0.004530,0.047177,-0.030340,0.001683,-0.083862,-0.039486,0.000278,-0.038797,0.018297,0.006072,-0.090232,-0.058650,0.006409,-0.054572,0.015310,0.013232,0.021482,-0.030947,-0.025603,0.021907,-0.013904,0.002836,0.067379,-0.050103,-0.020645,0.028896,-0.012250,-0.028067,0.006971,-0.001543,0.021431,0.031867,0.022456,0.006861,-0.044189,0.022256,-0.025234,-0.015981,0.034415,0.006431,0.023558,0.010609,-0.014840,-0.006467,0.028868,-0.023469,0.017533,-0.025723,0.011915,-0.010021,0.020352,0.008023,-0.008922,0.022483,0.003219,0.017522,0.012660,0.019215,-0.023325,-0.011207,0.025836,-0.010616,0.016775,0.014235,-0.027190,-0.002570,-0.023448,-0.022501,-0.009935,0.016257,0.006286,-0.038151,0.030787,-0.021723,-0.016583,-0.014994,-0.006278,-0.006032,0.014268,-0.047490,0.014985,0.000330,0.051620,-0.011931,0.040732,0.003217,0.011345,-0.004818,0.024208,-0.021387,-0.005589,-0.024992,0.009349,-0.013608,-0.028014,-0.039411,-0.016231,-0.003902,-0.026305,-0.014912,0.008128,0.002409,0.007859,0.009323,0.000305,0.006051,-0.040020,0.019997,0.015924,0.011171,-0.006044,-0.007823,-0.004611,0.004912,-0.039061,0.000317,-0.014181,0.007212,0.008493,0.013589,0.008015,-0.048048,0.006819,0.011822,0.005717,0.014277,-0.002985,-0.011244,-0.021284,0.006432,-0.012489,0.034722,-0.010280,-0.025831,-0.018700,-0.007229,4.454843,0.070011,0.803324,0.029699,-0.302375,4.645658,4.198054
218398,2022-11-26 23:00:00,10,50.4506,30.5243,0.9,0.0,93.9,3.5,100.0,66.67,0.5,3.9,26.6,10.8,325.8,1022.5,98.4,2.4,0.0,0.0,0.07,0.9,-2.1,95.07,0.0,0.0,0.0,22.3,9.4,325.4,1026.0,100.0,0.0,0.1,0.0,False,False,False,True,False,True,False,False,2022,11,5,23,Kyiv,Europe/Kiev,2022-11-26,07:29:18,16:00:40,23:00:00,Київська,0,0.0,0.0,0.0,0.0,0.0,0.0,1,1,0.0,0.0,79,0.778421,-0.227892,-0.000885,-0.127423,0.081434,-0.109679,0.080738,-0.077636,0.080139,0.130156,0.060959,0.005800,0.017693,-0.032371,-0.032987,0.092083,-0.046132,-0.006254,0.037463,0.051535,-0.028932,0.016327,0.019916,0.038028,-0.078564,0.027429,0.027769,0.026236,-0.020809,-0.057997,0.010619,0.027309,-0.038299,0.031680,-0.005979,0.015736,0.004247,-0.024164,0.026277,-0.023993,-0.010976,-0.020363,-0.016511,0.000455,-0.042137,0.044445,0.010374,0.008701,0.012143,0.007584,0.005026,-0.057942,-0.004453,-0.029949,0.004905,0.026898,-0.099185,0.017826,-0.062452,-0.059173,0.053321,0.043404,-0.004291,0.056319,0.003741,-0.011766,0.005159,0.017836,-0.015513,-0.031338,-0.026590,-0.004240,0.032865,-0.041865,-0.014982,0.017834,0.004323,0.010579,0.004374,-0.016094,-0.005977,-0.016945,0.000113,0.031585,-0.035931,-0.015649,-0.032549,0.012545,-0.008033,-0.011099,-0.012555,0.001634,-0.019578,0.007534,0.022147,0.015206,0.026488,0.034720,-0.013976,-0.001139,-0.025086,-0.010717,0.023065,-0.026229,-0.007458,0.012467,-0.016704,-0.022100,-0.001852,-0.007869,0.020828,0.033123,0.008577,0.006097,-0.003610,0.033630,0.023399,0.006398,-0.018994,0.006392,0.008635,0.020451,0.009937,-0.005208,-0.013518,0.041045,-0.004593,0.002220,0.005996,0.015427,0.015044,0.018308,-0.007237,0.030953,-0.028818,0.005410,-0.001577,0.023620,0.007647,-0.011029,-0.012103,-0.032960,0.008147,-0.062847,0.002569,0.019451,-0.019595,-0.000184,-0.020783,0.007527,4.688761,0.068162,0.778421,0.031258,-0.171391,4.629875,4.247284
598978,2024-01-18 06:00:00,25,51.4937,31.2944,-1.8,-3.1,91.0,8.0,100.0,8.33,10.1,16.8,58.0,36.0,161.2,1000.7,100.0,17.8,1.5,1.0,0.25,-7.2,-16.5,86.28,0.0,0.0,1.9,58.0,34.6,139.7,1004.0,100.0,0.0,0.0,0.0,False,False,False,True,False,True,False,False,2024,1,3,6,Chernihiv,Europe/Kiev,2024-01-18,07:51:40,16:18:59,06:00:00,Чернігівська,0,0.0,0.0,0.0,0.0,0.0,4.0,0,1,2.0,1.0,17,0.787388,-0.054652,-0.193008,0.085661,0.186053,0.137947,-0.045698,-0.090260,0.069329,-0.060547,-0.023290,-0.001477,0.024200,0.007679,-0.120262,-0.061929,0.053408,0.038091,0.051077,-0.022113,0.022831,-0.063438,0.057171,-0.053481,-0.039120,0.067850,0.014171,0.027243,0.013856,-0.028655,0.015504,-0.021928,0.033332,-0.044135,0.004394,0.006291,-0.053029,0.001332,-0.011408,-0.031034,-0.042889,-0.016576,-0.010917,-0.001792,-0.016197,0.010244,0.021623,-0.023591,-0.023722,-0.032666,-0.018352,0.020457,0.004988,0.004322,0.001928,0.009567,0.025934,-0.024844,0.018942,-0.004750,-0.009244,-0.000995,-0.008158,-0.028782,-0.012728,0.050316,-0.006081,-0.016744,0.007216,-0.025209,0.020244,-0.004148,0.013236,0.012211,0.036929,-0.029317,0.019738,0.028009,-0.037019,0.042430,0.026634,-0.021348,0.050088,0.001820,-0.001928,0.028761,0.030529,-0.018065,0.004229,-0.036319,0.065132,0.001298,0.020988,-0.003460,-0.023179,-0.003463,0.055271,0.028286,-0.007935,0.016746,0.003229,-0.000130,0.021271,-0.015833,0.030530,-0.007540,-0.001717,-0.012597,0.003493,0.010884,0.018401,-0.018159,-0.000965,-0.034790,-0.043353,-0.000927,0.006714,-0.000952,0.026059,0.012820,0.034331,-0.012154,-0.010708,-0.012901,-0.006677,0.008412,-0.033717,-0.028422,-0.013287,0.010540,-0.016952,0.006966,-0.019037,0.012770,0.004518,0.022870,-0.019330,0.020755,-0.002439,0.039302,0.009077,-0.025932,0.023143,0.010658,0.004872,0.017936,-0.027919,-0.013506,0.034585,-0.003883,4.690771,0.068604,0.787388,0.031272,-0.270004,4.841909,4.251367
11067,2023-05-30 05:00:00,2,49.2336,28.4486,17.7,6.7,53.4,0.0,0.0,0.00,0.0,0.0,31.3,13.3,7.3,1016.2,4.8,331.0,28.6,9.0,0.35,9.3,8.9,82.65,0.0,0.0,0.0,11.2,5.0,44.4,1017.0,0.0,0.0,0.0,0.0,True,False,False,False,True,False,False,False,2023,5,1,5,Vinnytsia,Europe/Kiev,2023-05-30,05:07:30,21:00:38,05:00:00,Вінницька,0,0.0,0.0,0.0,0.0,0.0,3.0,0,1,4.0,2.0,16,0.834889,-0.187368,-0.069966,-0.016383,-0.005265,0.020316,0.002313,0.036286,-0.047777,0.050255,0.041790,0.024899,-0.010526,-0.004899,0.028707,0.064974,0.086247,0.081134,0.002803,0.066184,-0.046797,-0.055700,0.082887,-0.009865,0.015062,-0.058567,-0.048873,0.056344,-0.007332,0.015842,0.069722,-0.016270,0.044358,0.041831,0.027013,-0.040027,0.021852,0.020280,0.036573,0.040895,-0.021971,-0.013855,-0.009489,-0.069134,0.011490,-0.010507,-0.011094,0.023665,-0.011363,-0.025865,0.003052,-0.044735,0.033115,-0.059732,-0.001290,0.003039,0.013019,0.019811,-0.057588,0.016755,0.057257,0.022127,-0.003054,-0.026825,0.027139,0.062214,-0.010838,0.017196,0.033236,0.032406,-0.034696,-0.014823,0.021655,-0.034783,-0.002077,0.027765,0.027326,0.011406,0.016284,0.025736,0.002605,0.003931,0.025903,-0.003226,-0.007641,-0.010084,0.029603,-0.013401,-0.036378,0.003485,0.043902,-0.006997,-0.003812,-0.019292,0.022470,-0.010714,-0.020047,-0.027275,-0.005775,-0.010297,-0.012991,-0.012780,0.023125,0.011735,0.021484,-0.002494,0.027007,0.013934,0.007162,-0.005553,0.021129,0.000871,0.004335,0.011124,-0.000317,-0.017075,0.022424,0.018822,-0.007427,0.023760,-0.010820,-0.012250,0.010974,-0.019344,0.009287,0.045190,-0.014729,-0.009722,0.001608,-0.027082,-0.001784,-0.033361,-0.049192,0.002875,0.025708,0.016610,-0.023262,-0.026741,-0.001438,-0.012521,0.008591,-0.008101,0.001730,-0.006942,0.019153,0.009060,0.018710,-0.003765,0.007204,0.003312,4.421934,0.070238,0.834889,0.029480,-0.571926,4.799486,4.239535
331802,2023-10-06 16:00:00,15,46.4725,30.7371,17.3,7.9,57.7,0.3,100.0,4.17,0.0,0.0,45.4,25.6,302.8,1020.8,53.4,148.0,12.8,6.0,0.75,21.5,21.5,34.76,0.0,0.0,0.0,45.0,25.6,323.8,1020.0,9.9,394.6,1.4,4.0,False,False,True,False,True,False,False,False,2023,10,4,16,Odesa,Europe/Kiev,2023-10-06,07:01:35,18:28:17,16:00:00,Одеська,0,0.0,0.0,0.0,0.0,0.0,4.0,0,0,2.0,0.0,12,0.803681,-0.069167,-0.067721,-0.161635,-0.036478,-0.094265,-0.168597,-0.020681,-0.136845,-0.042435,-0.059340,-0.011415,-0.087616,-0.008228,0.087821,-0.108702,0.050775,0.014709,0.011146,-0.050221,0.046456,0.102306,-0.080190,-0.062400,0.020257,-0.016456,0.000511,0.007439,0.002430,-0.078913,0.011228,0.057091,-0.044130,-0.019716,-0.001871,-0.031071,0.002223,0.007002,0.015297,0.011647,0.030377,0.028097,-0.012682,0.017040,0.018937,-0.022116,0.034106,0.000405,-0.001374,-0.024092,0.048396,0.012918,-0.015213,0.012700,-0.003148,-0.015532,-0.014168,-0.038232,-0.014471,0.007548,-0.005597,0.046275,0.003479,-0.004111,-0.017566,-0.021025,-0.012266,0.030431,0.012429,-0.008281,0.018367,-0.019580,-0.012721,0.013256,-0.044918,0.058874,0.014666,0.051076,0.006174,0.025326,0.027614,0.005802,0.041713,0.034991,0.009489,0.009097,-0.034514,-0.006133,-0.016199,0.006867,-0.012132,-0.024335,0.008994,0.000176,0.019952,-0.015666,0.050348,-0.013600,-0.008872,0.022962,0.010342,-0.023259,0.015010,-0.013449,-0.036368,-0.004193,0.009874,0.005103,-0.003666,-0.011491,-0.016622,0.000245,-0.009308,0.027467,0.040795,0.040154,-0.006145,-0.023544,0.008588,-0.026841,0.001950,-0.004698,0.002816,-0.016296,0.012005,0.009178,-0.005683,-0.021352,-0.010745,-0.007262,-0.002664,-0.002030,-0.030730,-0.002232,-0.009300,-0.035578,0.020279,0.003791,-0.012151,0.031652,0.012013,-0.007610,-0.003293,-0.040643,-0.018888,-0.007145,0.024515,-0.014828,0.032965,-0.006255,4.620547,0.069716,0.803681,0.030804,0.129949,4.595811,4.211482
363838,2024-05-25 16:00:00,16,49.5879,34.5517,17.5,-1.1,30.5,0.0,0.0,0.00,0.0,0.0,44.6,22.3,81.7,1026.3,1.7,333.5,28.7,9.0,0.56,23.7,23.7,17.38,0.0,0.0,0.0,40.3,18.0,86.8,1025.0,0.0,705.0,2.5,7.0,True,False,False,False,True,False,False,False,2024,5,5,16,Poltava,Europe/Kiev,2024-05-25,04:45:21,20:33:03,16:00:00,Полтавська,0,0.0,0.0,1.0,0.0,0.0,9.0,1,0,1.0,1.0,1,0.851830,-0.001112,-0.011213,0.065816,-0.048097,-0.007053,0.014401,-0.051840,0.048826,-0.039747,-0.032842,0.038799,0.025811,-0.001836,0.024109,-0.001364,0.141687,0.061148,-0.020571,0.132438,0.030315,-0.043627,-0.055146,-0.014994,0.010074,-0.036006,-0.007490,-0.015006,-0.055606,0.001082,-0.020658,-0.034752,-0.047295,0.044568,-0.032272,0.093054,0.006343,-0.004578,0.009798,-0.044282,0.007785,0.049417,-0.049370,0.015683,0.022774,0.032635,0.003870,-0.022881,-0.032173,0.014663,0.023919,-0.044777,0.024615,0.049754,-0.006434,-0.008595,0.015117,0.055194,-0.056008,0.024339,-0.032394,0.011320,-0.000160,-0.057445,-0.046296,-0.003182,0.003647,-0.011906,-0.009876,-0.014889,0.011357,0.001591,-0.030540,0.047849,-0.024433,0.010215,0.007832,-0.013354,0.010693,-0.043542,0.008552,-0.004476,-0.027141,-0.012487,-0.001889,-0.004530,0.007738,-0.001330,-0.048138,-0.009334,0.033608,0.001085,0.019885,0.005397,-0.006524,0.003763,0.012148,-0.004630,-0.011327,0.009898,0.045142,0.033812,-0.002279,-0.035070,-0.007091,-0.020142,-0.041169,-0.024583,0.005355,-0.004532,0.001059,-0.024358,0.034210,0.011478,0.045571,-0.024156,-0.033612,-0.014831,0.003026,0.012559,-0.037288,0.029713,-0.012677,-0.007618,0.006916,0.003377,0.023804,0.025570,0.028638,0.021608,0.019745,-0.027596,0.010700,-0.007044,-0.008153,-0.005853,-0.013173,0.006679,0.007785,-0.019823,-0.010902,-0.019133,-0.031083,0.001741,0.016533,0.031837,0.011627,-0.035316,-0.011166,0.029368,4.360388,0.071064,0.851830,0.029069,0.080336,4.350615,4.228281
393300,2024-09-27 09:00:00,17,50.6193,26.2513,20.7,12.9,61.3,0.6,100.0,8.33,0.0,0.0,50.4,25.0,204.8,1007.6,84.6,79.9,6.9,3.0,0.82,20.1,20.1,55.35,0.0,0.0,0.0,40.7,21.5,190.0,1005.9,99.8,67.6,0.2,1.0,False,False,True,False,False,True,False,False,2024,9,4,9,Rivne,Europe/Kiev,2024-09-27,07:09:29,19:01:24,09:00:00,Рівненська,0,0.0,0.0,0.0,0.0,0.0,3.0,0,0,1.0,0.0,20,0.829803,0.047829,-0.019874,-0.007677,-0.071266,-0.015918,-0.035848,-0.001454,0.087732,-0.103539,-0.009843,0.037422,0.155549,0.176862,0.077317,0.034745,0.037467,-0.081488,-0.003873,0.041441,0.007118,-0.063486,-0.063760,-0.015576,-0.017344,-0.008646,-0.025732,-0.025554,0.005673,-0.058349,-0.062504,0.020579,0.001714,0.005478,-0.028132,0.011985,0.033480,0.002184,0.007650,0.012404,-0.018245,-0.012245,0.017462,0.028355,-0.005297,0.029243,0.012801,-0.015180,-0.006771,-0.016037,0.017863,-0.021173,0.000462,-0.034735,-0.009788,0.020993,0.012694,0.020511,-0.024162,-0.002205,-0.006013,0.018929,-0.000831,-0.022803,0.008813,-0.003034,-0.010433,-0.027122,-0.025361,0.015848,0.017158,0.006906,0.007807,-0.015794,-0.020282,-0.027121,-0.004082,0.015345,-0.018072,-0.029617,-0.009528,-0.032551,-0.024300,-0.024189,-0.009569,-0.044640,0.028087,0.032580,-0.013557,-0.025755,-0.005211,0.012261,-0.006621,0.017531,-0.030800,-0.025571,0.000613,0.009908,0.029032,0.011927,0.010465,-0.018221,-0.032143,0.012156,-0.049910,0.022775,-0.034192,0.012504,-0.017129,0.030031,0.043566,0.008804,0.010486,-0.001569,0.004578,-0.034056,0.003460,-0.013487,-0.012968,-0.002391,-0.024916,0.014913,0.021236,0.006278,-0.014009,-0.007292,-0.008194,-0.001991,0.007325,0.005442,-0.020114,0.021289,0.000493,0.004918,0.027177,-0.008942,-0.028020,0.033377,0.024322,0.006807,-0.006663,0.008475,-0.018010,0.022373,0.010377,0.001586,0.038983,0.023101,0.016031,0.017589,4.201253,0.070300,0.829803,0.028008,0.060250,4.217745,4.188897
308747,2024-02-25 22:00:00,14,46.9734,31.9852,5.9,1.1,71.9,0.0,0.0,0.00,0.0,0.0,40.0,25.2,116.5,1024.0,96.4,125.1,10.6,5.0,0.53,2.1,-2.4,77.06,0.0,0.0,0.0,33.5,18.0,107.9,1023.0,100.0,0.0,0.0,0.0,False,True,False,False,False,True,False,False,2024,2,6,22,Mykolaiv,Europe/Kiev,2024-02-25,06:40:34,17:30:38,22:00:00,Миколаївська,0,0.0,1.0,1.0,0.0,0.0,13.0,1,0,7.0,2.0,0,0.760788,-0.067296,-0.189149,0.122242,0.050500,-0.001493,-0.019155,0.035911,0.024992,0.005960,-0.054119,0.048990,0.236944,-0.197670,-0.001376,-0.091099,-0.017783,0.054485,0.009725,-0.015959,0.016101,0.045219,0.053540,-0.016663,-0.057857,0.067863,0.030491,-0.017896,0.032576,0.001377,0.067969,0.034075,0.005864,0.011676,-0.028662,-0.047028,-0.041162,0.010523,-0.035663,-0.003300,-0.076825,-0.005182,0.056158,0.039511,-0.013902,0.017805,-0.012995,0.053422,0.008926,-0.005803,0.027273,-0.038243,0.035944,0.037167,0.029308,0.014616,0.002731,-0.012727,-0.017381,0.017380,-0.019131,0.001721,0.006035,-0.017884,0.015877,-0.018429,-0.031109,-0.004814,0.005779,0.013003,0.000842,-0.025612,-0.038395,0.006187,-0.032073,0.035341,-0.029957,-0.027174,0.033834,0.020101,0.018854,-0.001923,-0.028527,0.011272,0.020943,0.014115,-0.012291,0.007122,0.003392,0.056073,-0.044529,-0.032331,0.007604,0.005682,0.044682,-0.015445,0.033502,-0.052705,0.010381,0.015241,0.017325,0.008514,-0.031647,0.005836,0.037119,0.002138,-0.016446,0.009132,0.010240,-0.013814,-0.028872,-0.034033,-0.007603,-0.023827,-0.026101,-0.012325,-0.016052,-0.022932,0.023668,0.022776,0.004773,-0.002551,0.001691,0.022243,0.011190,-0.044953,0.008887,-0.000967,0.030164,0.021859,0.006191,-0.038675,-0.024679,-0.015163,-0.016943,-0.017900,0.007503,0.016549,-0.012054,-0.013752,0.045206,-0.003392,0.005010,-0.005020,-0.010828,0.026161,0.009159,-0.017889,0.004365,-0.023739,4.814204,0.068107,0.760788,0.032095,0.456163,4.761326,4.269576

### TELEGRAM MERGE

In [23]:
df_tg_matrix = pd.read_csv("../data/telegram_processed_svd.csv")

In [24]:
df_tg_matrix.head()

,date,channel,tg_topic_0,tg_topic_1,tg_topic_2,tg_topic_3,tg_topic_4,tg_topic_5,tg_topic_6,tg_topic_7,tg_topic_8,tg_topic_9,tg_topic_10,tg_topic_11,tg_topic_12,tg_topic_13,tg_topic_14,tg_topic_15,tg_topic_16,tg_topic_17,tg_topic_18,tg_topic_19,tg_topic_20,tg_topic_21,tg_topic_22,tg_topic_23,tg_topic_24,tg_topic_25,tg_topic_26,tg_topic_27,tg_topic_28,tg_topic_29,tg_topic_30,tg_topic_31,tg_topic_32,tg_topic_33,tg_topic_34,tg_topic_35,tg_topic_36,tg_topic_37,tg_topic_38,tg_topic_39,tg_topic_40,tg_topic_41,tg_topic_42,tg_topic_43,tg_topic_44,tg_topic_45,tg_topic_46,tg_topic_47,tg_topic_48,tg_topic_49,tg_topic_50,tg_topic_51,tg_topic_52,tg_topic_53,tg_topic_54,tg_topic_55,tg_topic_56,tg_topic_57,tg_topic_58,tg_topic_59,tg_topic_60,tg_topic_61,tg_topic_62,tg_topic_63,tg_topic_64,tg_topic_65,tg_topic_66,tg_topic_67,tg_topic_68,tg_topic_69,tg_topic_70,tg_topic_71,tg_topic_72,tg_topic_73,tg_topic_74,tg_topic_75,tg_topic_76,tg_topic_77,tg_topic_78,tg_topic_79,tg_topic_80,tg_topic_81,tg_topic_82,tg_topic_83,tg_topic_84,tg_topic_85,tg_topic_86,tg_topic_87,tg_topic_88,tg_topic_89,tg_topic_90,tg_topic_91,tg_topic_92,tg_topic_93,tg_topic_94,tg_topic_95,tg_topic_96,tg_topic_97,tg_topic_98,tg_topic_99,tg_topic_100,tg_topic_101,tg_topic_102,tg_topic_103,tg_topic_104,tg_topic_105,tg_topic_106,tg_topic_107,tg_topic_108,tg_topic_109,tg_topic_110,tg_topic_111,tg_topic_112,tg_topic_113,tg_topic_114,tg_topic_115,tg_topic_116,tg_topic_117,tg_topic_118,tg_topic_119,tg_topic_120,tg_topic_121,tg_topic_122,tg_topic_123,tg_topic_124,tg_topic_125,tg_topic_126,tg_topic_127,tg_topic_128,tg_topic_129,tg_topic_130,tg_topic_131,tg_topic_132,tg_topic_133,tg_topic_134,tg_topic_135,tg_topic_136,tg_topic_137,tg_topic_138,tg_topic_139,tg_topic_140,tg_topic_141,tg_topic_142,tg_topic_143,tg_topic_144,tg_topic_145,tg_topic_146,tg_topic_147,tg_topic_148,tg_topic_149,tg_topic_150,tg_topic_151,tg_topic_152,tg_topic_153,tg_topic_154,tg_topic_155,tg_topic_156,tg_topic_157,tg_topic_158,tg_topic_159,tg_topic_160,tg_topic_161,tg_topic_162,tg_topic_163,tg_topic_164,tg_topic_165,tg_topic_166,tg_topic_167,tg_topic_168,tg_topic_169,tg_topic_170,tg_topic_171,tg_topic_172,tg_topic_173,tg_topic_174,tg_topic_175,tg_topic_176,tg_topic_177,tg_topic_178,tg_topic_179,tg_topic_180,tg_topic_181,tg_topic_182,tg_topic_183,tg_topic_184,tg_topic_185,tg_topic_186,tg_topic_187,tg_topic_188,tg_topic_189,tg_topic_190,tg_topic_191,tg_topic_192,tg_topic_193,tg_topic_194,tg_topic_195,tg_topic_196,tg_topic_197,tg_topic_198,tg_topic_199,tg_topic_200,tg_topic_201,tg_topic_202,tg_topic_203,tg_topic_204,tg_topic_205,tg_topic_206,tg_topic_207,tg_topic_208,tg_topic_209,tg_topic_210,tg_topic_211,tg_topic_212,tg_topic_213,tg_topic_214,tg_topic_215,tg_topic_216,tg_topic_217,tg_topic_218,tg_topic_219,tg_topic_220,tg_topic_221,tg_topic_222,tg_topic_223,tg_topic_224,tg_topic_225,tg_topic_226,tg_topic_227,tg_topic_228,tg_topic_229,tg_topic_230,tg_topic_231,tg_topic_232,tg_topic_233,tg_topic_234,tg_topic_235,tg_topic_236,tg_topic_237,tg_topic_238,tg_topic_239,tg_topic_240,tg_topic_241,tg_topic_242,tg_topic_243,tg_topic_244,tg_topic_245,tg_topic_246,tg_topic_247,tg_topic_248,tg_topic_249
0,2026-03-06 13:06:58,DeepStateUA,0.007121,0.000107,0.019843,0.000990,-0.011395,0.032670,-0.050983,0.061080,0.042624,-0.024341,-0.018764,0.023404,-0.017137,-0.358836,0.425288,0.017966,-0.107660,-0.032066,-0.045986,0.118212,0.091172,-0.248637,-0.001069,0.150763,0.030603,-0.074030,0.005803,0.005871,0.034871,0.017239,0.058098,0.029814,-0.010845,0.031486,-0.022705,0.005607,-0.006324,-0.010169,0.024500,-0.015581,-0.012708,0.005139,0.007857,0.016734,-0.040289,-0.019688,-0.026763,0.009381,-0.043500,-0.009525,-0.013075,-0.010473,-0.018150,0.005988,0.032611,0.000850,0.017872,0.020885,0.023899,-0.019290,-0.006676,-0.018478,-0.023263,-0.005497,-0.006460,0.026051,0.004991,0.019687,-0.022244,0.010929,0.007016,-0.067349,-0.035249,-0.005686,0.018747,0.039159,-0.053868,-0.078189,-0.074737,-0.082163,0.020498,0.084336,0.113470,-0.025871,-0.048314,0.096330,0.043779,0.029575,0.019820,0.002819,-0.007308,-0.005234,-0.053796,-0.005893,0.036483,-0.061232,-0.001463,0.048285,-0.017340,0.033961,0.039046,-0.045463,-0.035894,-0.033875,0.041559,-0.021964,-0.005454,-0.020615,0.006442,-0.016322,-0.010443,-0.015532,0.000981,0.002928,-0.010924,-0.004072,-0.007252,-0.020386,0.007354,0.022114,-0.000884,-0.019901,-0.009325,-0.043505,0.008556,-0.016976,0.004765,0.030853,0.012413,0.011307,0.017726,0.010620,-0.013777,-0.037939,-0.003764,0.015808,-0.027407,-0.033773,0.054684,-0.005455,0.077819,0.006894,-0.022642,-0.011036,0.007590,-0.011639,0.036640,-0.020276,0.016764,-0.000467,-0.007996,0.023813,-0.014151,-0.026548,-0.078007,0.014955,0.043507,-0.021709,0.013392,-0.008661,0.012712,0.037409,-0.032628,-0.021403,-0.030711,0.033490,-0.025720,0.008100,-0.011149,-0.002706,0.002765,0.017707,-0.010806,-0.012850,0.007063,0.021780,0.010662,-0.031776,0.011750,0.069730,0.029703,0.012839,-0.031854,0.001635,-0.002149,-0.045445,0.002481,0.021315,0.006077,-0.006012,0.006578,-0.036587,0.009373,-0.025445,-0.019477,-0.011097,0.014675,-0.016785,0.010995,0.002045,-0.004600,-0.008963,0.006641,-0.017489,0.003821,0.005926,0.000537,-0.002830,-0.035321,-0.004957,0.013548,0.015414,0.018981,0.017932,-0.002853,0.007882,0.026621,0.003335,-0.001598,0.011594,-0.016659,0.001508,-0.007204,0.002975,0.001589,0.012191,0.005661,0.006600,-0.027472,0.014275,-0.020139,-0.011419,0.015111,-0.008120,0.001883,-0.011402,0.006871,0.024781,0.019495,0.024153,0.017141,-0.013944,-0.027516,0.034612,-0.032061,-0.051141,-0.004707,-0.003985,-0.052194,-0.026334
1,2026-03-06 12:57:29,DeepStateUA,0.022770,-0.002163,0.041469,0.001527,-0.033584,0.077087,-0.078417,0.091534,0.014917,-0.016270,-0.019775,0.015028,-0.012900,-0.066689,0.049295,-0.031093,0.006109,-0.021357,-0.047947,0.025239,-0.010092,0.063969,0.026579,-0.002938,0.000962,-0.014692,-0.010761,0.001202,-0.015000,-0.005930,-0.010839,0.049023,-0.023754,0.030922,0.000492,-0.009320,-0.015764,0.024560,0.006807,-0.000411,-0.001480,-0.017302,-0.026282,0.007343,0.049168,-0.004316,0.029036,-0.034987,0.034368,-0.046229,-0.012751,0.048371,0.004354,-0.014649,0.034935,-0.016468,-0.013150,0.017354,-0.000886,0.004047,0.036549,-0.017461,0.009667,-0.007887,-0.027599,-0.016937,-0.037606,-0.009493,-0.002735,-0.006034,0.023060,0.028297,0.024781,0.010909,-0.000544,-0.016357,-0.003670,-0.016336,0.002609,0.013846,-0.005648,-0.012539,-0.007839,-0.041249,0.030814,-0.017629,-0.005069,-0.024100,-0.013485,0.010861,-0.015271,-0.006842,-0.013700,0.008861,-0.010810,0.022671,-0.034102,-0.016120,0.001828,0.003954,0.007680,-0.037762,-0.017967,0.016946,0.016302,-0.011406,0.021384,-0.001978,-0.005628,-0.080374,0.039484,0.015890,0.034496,-0.016936,0.004379,-0.005021,0.014321,-0.003484,-0.002882,-0.002483,-0.005047,0.017296,-0.003401,0.009433,-0.001665,0.018296,0.003151,-0.031688,0.003527,0.010405,-0.006932,-0.019232,-0.004084,-0.023476,-0.008857,-0.015648,0.053937,0.034130,-0.026430,0.018625,-0.050338,0.022854,-0.000992,0.001886,-0.013131,0.037482,0.025278,-0.008833,-0.009892,0.015771,-0.019763,-0.015569,-0.015169,0.040201,0.018226,0.018286,-0.011713,-0.000436,0.000451,0.012252,0.007596,-0.000338,0.004704,0.023604,-0.020461,0.016871,0.003246,-0.045373,0.004746,-0.036469,-0.025234,0.030737,-0.000797,0.015820,0.042129,0.010345,0.022695,0.005339,-0.001636,-0.018894,0.026074,-0.054026,-0.057851,0.004372,-0.020828,-0.034435,0.055865,0.016301,0.063019,0.010370,-0.004495,-0.030530,0.018833,-0.013644,0.002207,0.037501,-0.045908,-0.059514,-0.035367,-0.024918,-0.039085,0.035208,0.085963,0.009390,0.079267,0.013885,0.006535,-0.052116,-0.033637,0.008546,-0.019285,0.006149,0.002710,-0.056530,-0.022435,0.020384,-0.013988,-0.005111,-0.015295,-0.097911,-0.042214,0.020642,-0.042973,0.045024,0.005130,-0.022150,0.006530,0.054045,-0.042555,0.006345,-0.035607,-0.006021,0.000036,-0.033672,0.020923,-0.000556,-0.034840,0.034524,0.004798,0.001867,-0.019097,0.025730,0.000530,0.020332,-0.028041,0.001581,0.006948,-0.064965,0.022597,-0.017810
2,2026-03-06 08:32:47,DeepStateUA,0.009647,-0.001083,0.029820,0.004092,-0.021362,0.053647,-0.076998,0.085930,0.011210,-0.020903,-0.051377,0.013232,-0.021159,0.001682,0.049129,-0.010018,-0.014271,-0.012423,-0.010588,0.046603,0.026875,0.002452,0.003347,-0.018525,0.005328,-0.003516,0.003550,0.018054,0.002157,0.012886,0.034851,0.000381,-0.009230,-0.002467,0.002381,0.000435,0.000842,-0.004257,-0.003348,0.009321,-0.005701,-0.004301,-0.016552,-0.001785,0.016005,0.008306,0.000706,-0.004439,-0.004069,-0.017177,-0.017974,-0.000361,-0.033317,-0.032714,0.027864,-0.006006,0.000665,-0.001117,-0.020576,0.002026,0.001386,0.000074,0.000035,0.007953,0.005774,0.005407,-0.005473,0.009134,-0.010858,-0.014439,0.028165,-0.023096,0.014483,0.021402,-0.017701,0.035852,-0.021296,-0.016145,-0.007317,-0.016939,0.014848,-0.006705,-0.047833,-0.002701,0.006144,-0.016566,0.016766,0.017487,0.002922,-0.004175,0.003020,-0.032485,0.001179,0.015611,0.015266,0.023711,0.005134,-0.030744,-0.014357,0.024034,0.016933,-0.044400,0.005215,0.011766,-0.026130,-0.005996,0.011388,-0.012677,-0.016358,-0.020579,-0.003119,-0.003134,0.019595,-0.011791,0.015521,0.022933,0.013426,0.013833,-0.006377,0.006772,-0.023631,0.008806,0.003886,0.014650,-0.029616,0.047030,0.005467,-0.020456,0.018529,-0.009387,0.010160,0.010283,-0.016104,0.038236,-0.028747,0.030649,0.028343,0.020708,0.001123,-0.009186,-0.064016,0.007831,0.005442,0.008333,-0.002820,0.007245,0.037716,-0.034047,0.009513,0.002276,-0.009623,-0.009046,0.023603,-0.009777,-0.047725,0.011991,-0.016423,0.004245,0.039250,0.030454,-0.007661,-0.043307,-0.005340,-0.003352,0.004921,0.010619,0.011745,-0.029661,-0.016769,-0.004054,-0.019134,-0.010521,-0.016018,0.013938,0.061204,0.000223,-0.016080,-0.013129,0.011080,0.025287,0.030597,-0.001902,-0.032930,0.022210,0.024393,-0.023036,0.001308,-0.010151,0.002527,0.003083,0.002821,0.012997,0.008941,-0.011744,0.019257,-0.000326,0.025398,-0.044011,-0.021810,-0.040764,-0.011043,0.008865,-0.020367,-0.005459,0.002685,0.019290,0.025485,-0.019258,-0.011527,-0.015354,-0.003904,0.007485,0.039596,0.030817,-0.034836,0.029725,0.018850,0.009886,0.006251,-0.006886,-0.028339,-0.017251,-0.019577,-0.004734,-0.014053,-0.014076,-0.018760,-0.006640,0.002467,-0.014727,0.015968,-0.020566,-0.000171,-0.020244,0.003823,-0.020505,-0.006361,-0.011117,-0.002427,0.036069,0.025378,-0.003550,-0.043415,-0.007200,-0.009172,0.006124,-0.004550,0.020576,0.010544,0.012825
3,2026-03-05 16:46:58,DeepStateUA,0.006857,0.000279,0.019019,0.000875,-0.011544,0.032104,-0.049929,0.059696,0.042415,-0.023916,-0.020173,0.022363,-0.016425,-0.354007,0.422410,0.017232,-0.106286,-0.032499,-0.045502,0.118053,0.090722,-0.246774,-0.000077,0.150527,0.029981,-0.074173,0.006982,0.007685,0.035762,0.018338,0.059439,0.029451,-0.012747,0.032325,-0.024156,0.006144,-0.004921,-0.007047,0.024916,-0.013464,-0.012810,0.004618,0.006305,0.017777,-0.037226,-0.018749,-0.026076,0.008026,-0.040668,-0.008455,-0.012120,-0.009955,-0.018018,0.006661,0.032070,0.001406,0.015931,0.020066,0.022360,-0.017343,-0.007000,-0.017683,-0.021564,-0.005667,-0.004897,0.022713,0.002352,0.021026,-0.020492,0.010265,0.006341,-0.062306,-0.031869,-0.004833,0.019042,0.034739,-0.048355,-0.072654,-0.066847,-0.074661,0.019525,0.081765,0.106477,-0.025839,-0.046011,0.091824,0.043276,0.026990,0.018548,0.002251,-0.006682,-0.005199,-0.051075,-0.003017,0.029777,-0.054537,-0.002321,0.044861,-0.018019,0.033038,0.036190,-0.042962,-0.033109,-0.031216,0.040022,-0.016626,-0.004321,-0.022597,0.001446,-0.018905,-0.015046,-0.006992,0.004125,0.000550,-0.011207,-0.006348,-0.005325,-0.023457,0.009404,0.021777,-0.001560,-0.021654,-0.010065,-0.041095,0.009058,-0.016847,0.014130,0.030820,0.014433,0.011400,0.017331,0.012039,-0.011976,-0.037318,-0.000059,0.013755,-0.023928,-0.033049,0.051293,-0.004679,0.075124,0.004404,-0.023162,-0.009870,0.008475,-0.011321,0.038668,-0.021760,0.017180,-0.003656,-0.004497,0.024860,-0.010259,-0.023728,-0.073984,0.014863,0.037362,-0.023343,0.010636,-0.008617,0.012118,0.033946,-0.033242,-0.018743,-0.029519,0.034794,-0.025605,0.008930,-0.006082,-0.003809,-0.002692,0.017623,-0.010778,-0.010494,0.004241,0.018071,0.015268,-0.027505,0.007476,0.058355,0.024457,0.010803,-0.030662,-0.001728,-0.001191,-0.040228,0.003914,0.019603,0.006112,-0.006858,0.006677,-0.036682,0.007404,-0.025808,-0.014273,-0.007471,0.014518,-0.012831,0.005292,-0.002303,-0.003711,-0.008705,0.000811,-0.012632,0.003962,0.004388,0.000392,0.002013,-0.028686,-0.003865,0.011868,0.012458,0.016571,0.009521,-0.001085,0.007509,0.021553,0.002596,0.005686,0.003029,-0.016085,0.005070,-0.006296,0.000888,0.002830,0.014467,0.006547,0.000059,-0.020972,0.009385,-0.014722,-0.008414,0.016377,-0.008301,-0.000710,-0.008819,0.006663,0.012456,0.012080,0.020719,0.008728,-0.007502,-0.021433,0.028223,-0.025323,-0.045761,-0.001697,0.002329,-0.042282,-0.017344
4,2026-03-05 15:46:39,DeepStateUA,0.048850,-0.006687,0.076040,-0.003924,-0.027197,0.089562,-0.088811,0.109836,0.052317,-0.025058,0.032393,-0.004227,-0.005032,-0.173462,0.094957,0.012582,-0.022470,-0.000701,-0.014110,-0.004739,-0.012713,0.127035,0.018404,-0.023593,0.003993,0.039285,-0.018524,0.000346,-0.081926,-0.045456,-0.116434,-0.028074,-0.013547,0.024679,0.046939,-0.021634,0.023138,0.009856,-0.025864,-0.041176,-0.000832,-0.024707,0.013634,-0.022765,0.057346,0.020489,0.010217,-0.026627,0.022514,0.022439,0.035388,-0.021224,0.008281,-0.000369,-0.015992,0.012876,-0.018086,-0.005188,-0.021093,0.012907,-0.008576,-0.008820,0.030578,0.014680,0.017475,0.007797,0.004474,-0.006686,0.023422,0.017913,0.009466,-0.011255,-0.006200,0.008317,-0.038521,0.017131,0.046956,0.005528,0.071628,0.044144,-0.006390,0.009272,-0.010302,-0.023798,0.013099,0.004949,0.000502,-0.025377,0.000576,0.005652,0.013762,-0.033165,0.011959,0.032019,-0.010729,0.074746,-0.045156,-0.069856,0.017151,-0.028899,-0.001317,-0.020143,-0.001444,0.077727,0.008474,0.017218,0.063803,0.022661,-0.019578,-0.089309,0.043190,0.054776,0.003839,0.005619,0.042291,-0.040703,0.034216,-0.018434,0.026249,-0.012015,0.004663,0.009540,0.028979,0.022277,0.015843,0.026390,-0.030022,-0.019719,0.008557,-0.006588,-0.012466,-0.013107,0.000680,-0.040800,0.018810,-0.018852,0.015615,-0.026299,-0.013060,-0.022985,-0.019649,0.003882,0.019573,0.020302,-0.053045,-0.013295,-0.013323,0.043432,-0.020309,-0.004050,-0.017728,-0.008395,-0.063169,-0.008017,0.060143,-0.036649,-0.009351,-0.031419,-0.019356,0.002941,0.015680,0.058794,0.034299,0.025507,0.026522,-0.024327,0.001476,-0.008036,-0.008201,0.018152,0.016011,-0.009222,0.020974,0.008694,-0.047264,0.028262,-0.002851,0.009422,-0.012002,0.004519,-0.010160,-0.031831,-0.005528,0.038708,-0.014277,0.009808,0.004059,-0.009500,0.033000,-0.038357,-0.005480,0.016188,-0.012154,-0.003113,0.007213,-0.049557,0.001337,0.025862,0.002217,0.009792,-0.002905,0.012793,-0.039633,-0.014680,0.012541,-0.026685,-0.057037,-0.038288,-0.031196,-0.025930,0.009651,0.004537,0.035687,-0.013257,0.015052,-0.006502,0.018667,-0.013956,0.023991,0.033361,-0.000124,-0.000186,0.012095,0.023317,0.014021,-0.007477,-0.006606,-0.045891,0.004310,-0.008439,0.004574,-0.039585,0.004941,0.010379,-0.002950,-0.053005,0.008541,-0.002762,0.010718,0.035433,0.017978,0.027453,-0.019744,0.008659,0.023139,-0.009485,-0.030263,0.013689,-0.022727,0.006843

In [25]:
df_tg_matrix["datetime_hour"] = pd.to_datetime(df_tg_matrix["date"]).dt.floor("h")

C:\Users\Uw11\AppData\Local\Temp\ipykernel_9680\2851151304.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_tg_matrix["datetime_hour"] = pd.to_datetime(df_tg_matrix["date"]).dt.floor("h")

In [26]:
topic_cols = [c for c in df_tg_matrix.columns if "tg_topic_" in c]

tg_hourly = (
    df_tg_matrix.groupby("datetime_hour")[topic_cols]
    .mean()
    .sort_index()
    .reset_index()
)

C:\Users\Uw11\AppData\Local\Temp\ipykernel_9680\2188712141.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  .reset_index()

In [27]:
df_tg_matrix.head()

,date,channel,tg_topic_0,tg_topic_1,tg_topic_2,tg_topic_3,tg_topic_4,tg_topic_5,tg_topic_6,tg_topic_7,tg_topic_8,tg_topic_9,tg_topic_10,tg_topic_11,tg_topic_12,tg_topic_13,tg_topic_14,tg_topic_15,tg_topic_16,tg_topic_17,tg_topic_18,tg_topic_19,tg_topic_20,tg_topic_21,tg_topic_22,tg_topic_23,tg_topic_24,tg_topic_25,tg_topic_26,tg_topic_27,tg_topic_28,tg_topic_29,tg_topic_30,tg_topic_31,tg_topic_32,tg_topic_33,tg_topic_34,tg_topic_35,tg_topic_36,tg_topic_37,tg_topic_38,tg_topic_39,tg_topic_40,tg_topic_41,tg_topic_42,tg_topic_43,tg_topic_44,tg_topic_45,tg_topic_46,tg_topic_47,tg_topic_48,tg_topic_49,tg_topic_50,tg_topic_51,tg_topic_52,tg_topic_53,tg_topic_54,tg_topic_55,tg_topic_56,tg_topic_57,tg_topic_58,tg_topic_59,tg_topic_60,tg_topic_61,tg_topic_62,tg_topic_63,tg_topic_64,tg_topic_65,tg_topic_66,tg_topic_67,tg_topic_68,tg_topic_69,tg_topic_70,tg_topic_71,tg_topic_72,tg_topic_73,tg_topic_74,tg_topic_75,tg_topic_76,tg_topic_77,tg_topic_78,tg_topic_79,tg_topic_80,tg_topic_81,tg_topic_82,tg_topic_83,tg_topic_84,tg_topic_85,tg_topic_86,tg_topic_87,tg_topic_88,tg_topic_89,tg_topic_90,tg_topic_91,tg_topic_92,tg_topic_93,tg_topic_94,tg_topic_95,tg_topic_96,tg_topic_97,tg_topic_98,tg_topic_99,tg_topic_100,tg_topic_101,tg_topic_102,tg_topic_103,tg_topic_104,tg_topic_105,tg_topic_106,tg_topic_107,tg_topic_108,tg_topic_109,tg_topic_110,tg_topic_111,tg_topic_112,tg_topic_113,tg_topic_114,tg_topic_115,tg_topic_116,tg_topic_117,tg_topic_118,tg_topic_119,tg_topic_120,tg_topic_121,tg_topic_122,tg_topic_123,tg_topic_124,tg_topic_125,tg_topic_126,tg_topic_127,tg_topic_128,tg_topic_129,tg_topic_130,tg_topic_131,tg_topic_132,tg_topic_133,tg_topic_134,tg_topic_135,tg_topic_136,tg_topic_137,tg_topic_138,tg_topic_139,tg_topic_140,tg_topic_141,tg_topic_142,tg_topic_143,tg_topic_144,tg_topic_145,tg_topic_146,tg_topic_147,tg_topic_148,tg_topic_149,tg_topic_150,tg_topic_151,tg_topic_152,tg_topic_153,tg_topic_154,tg_topic_155,tg_topic_156,tg_topic_157,tg_topic_158,tg_topic_159,tg_topic_160,tg_topic_161,tg_topic_162,tg_topic_163,tg_topic_164,tg_topic_165,tg_topic_166,tg_topic_167,tg_topic_168,tg_topic_169,tg_topic_170,tg_topic_171,tg_topic_172,tg_topic_173,tg_topic_174,tg_topic_175,tg_topic_176,tg_topic_177,tg_topic_178,tg_topic_179,tg_topic_180,tg_topic_181,tg_topic_182,tg_topic_183,tg_topic_184,tg_topic_185,tg_topic_186,tg_topic_187,tg_topic_188,tg_topic_189,tg_topic_190,tg_topic_191,tg_topic_192,tg_topic_193,tg_topic_194,tg_topic_195,tg_topic_196,tg_topic_197,tg_topic_198,tg_topic_199,tg_topic_200,tg_topic_201,tg_topic_202,tg_topic_203,tg_topic_204,tg_topic_205,tg_topic_206,tg_topic_207,tg_topic_208,tg_topic_209,tg_topic_210,tg_topic_211,tg_topic_212,tg_topic_213,tg_topic_214,tg_topic_215,tg_topic_216,tg_topic_217,tg_topic_218,tg_topic_219,tg_topic_220,tg_topic_221,tg_topic_222,tg_topic_223,tg_topic_224,tg_topic_225,tg_topic_226,tg_topic_227,tg_topic_228,tg_topic_229,tg_topic_230,tg_topic_231,tg_topic_232,tg_topic_233,tg_topic_234,tg_topic_235,tg_topic_236,tg_topic_237,tg_topic_238,tg_topic_239,tg_topic_240,tg_topic_241,tg_topic_242,tg_topic_243,tg_topic_244,tg_topic_245,tg_topic_246,tg_topic_247,tg_topic_248,tg_topic_249,datetime_hour
0,2026-03-06 13:06:58,DeepStateUA,0.007121,0.000107,0.019843,0.000990,-0.011395,0.032670,-0.050983,0.061080,0.042624,-0.024341,-0.018764,0.023404,-0.017137,-0.358836,0.425288,0.017966,-0.107660,-0.032066,-0.045986,0.118212,0.091172,-0.248637,-0.001069,0.150763,0.030603,-0.074030,0.005803,0.005871,0.034871,0.017239,0.058098,0.029814,-0.010845,0.031486,-0.022705,0.005607,-0.006324,-0.010169,0.024500,-0.015581,-0.012708,0.005139,0.007857,0.016734,-0.040289,-0.019688,-0.026763,0.009381,-0.043500,-0.009525,-0.013075,-0.010473,-0.018150,0.005988,0.032611,0.000850,0.017872,0.020885,0.023899,-0.019290,-0.006676,-0.018478,-0.023263,-0.005497,-0.006460,0.026051,0.004991,0.019687,-0.022244,0.010929,0.007016,-0.067349,-0.035249,-0.005686,0.018747,0.039159,-0.053868,-0.078189,-0.074737,-0.082163,0.020498,0.084336,0.113470,-0.025871,-0.048314,0.096330,0.043779,0.029575,0.019820,0.002819,-0.007308,-0.005234,-0.053796,-0.005893,0.036483,-0.061232,-0.001463,0.048285,-0.017340,0.033961,0.039046,-0.045463,-0.035894,-0.033875,0.041559,-0.021964,-0.005454,-0.020615,0.006442,-0.016322,-0.010443,-0.015532,0.000981,0.002928,-0.010924,-0.004072,-0.007252,-0.020386,0.007354,0.022114,-0.000884,-0.019901,-0.009325,-0.043505,0.008556,-0.016976,0.004765,0.030853,0.012413,0.011307,0.017726,0.010620,-0.013777,-0.037939,-0.003764,0.015808,-0.027407,-0.033773,0.054684,-0.005455,0.077819,0.006894,-0.022642,-0.011036,0.007590,-0.011639,0.036640,-0.020276,0.016764,-0.000467,-0.007996,0.023813,-0.014151,-0.026548,-0.078007,0.014955,0.043507,-0.021709,0.013392,-0.008661,0.012712,0.037409,-0.032628,-0.021403,-0.030711,0.033490,-0.025720,0.008100,-0.011149,-0.002706,0.002765,0.017707,-0.010806,-0.012850,0.007063,0.021780,0.010662,-0.031776,0.011750,0.069730,0.029703,0.012839,-0.031854,0.001635,-0.002149,-0.045445,0.002481,0.021315,0.006077,-0.006012,0.006578,-0.036587,0.009373,-0.025445,-0.019477,-0.011097,0.014675,-0.016785,0.010995,0.002045,-0.004600,-0.008963,0.006641,-0.017489,0.003821,0.005926,0.000537,-0.002830,-0.035321,-0.004957,0.013548,0.015414,0.018981,0.017932,-0.002853,0.007882,0.026621,0.003335,-0.001598,0.011594,-0.016659,0.001508,-0.007204,0.002975,0.001589,0.012191,0.005661,0.006600,-0.027472,0.014275,-0.020139,-0.011419,0.015111,-0.008120,0.001883,-0.011402,0.006871,0.024781,0.019495,0.024153,0.017141,-0.013944,-0.027516,0.034612,-0.032061,-0.051141,-0.004707,-0.003985,-0.052194,-0.026334,2026-03-06 13:00:00
1,2026-03-06 12:57:29,DeepStateUA,0.022770,-0.002163,0.041469,0.001527,-0.033584,0.077087,-0.078417,0.091534,0.014917,-0.016270,-0.019775,0.015028,-0.012900,-0.066689,0.049295,-0.031093,0.006109,-0.021357,-0.047947,0.025239,-0.010092,0.063969,0.026579,-0.002938,0.000962,-0.014692,-0.010761,0.001202,-0.015000,-0.005930,-0.010839,0.049023,-0.023754,0.030922,0.000492,-0.009320,-0.015764,0.024560,0.006807,-0.000411,-0.001480,-0.017302,-0.026282,0.007343,0.049168,-0.004316,0.029036,-0.034987,0.034368,-0.046229,-0.012751,0.048371,0.004354,-0.014649,0.034935,-0.016468,-0.013150,0.017354,-0.000886,0.004047,0.036549,-0.017461,0.009667,-0.007887,-0.027599,-0.016937,-0.037606,-0.009493,-0.002735,-0.006034,0.023060,0.028297,0.024781,0.010909,-0.000544,-0.016357,-0.003670,-0.016336,0.002609,0.013846,-0.005648,-0.012539,-0.007839,-0.041249,0.030814,-0.017629,-0.005069,-0.024100,-0.013485,0.010861,-0.015271,-0.006842,-0.013700,0.008861,-0.010810,0.022671,-0.034102,-0.016120,0.001828,0.003954,0.007680,-0.037762,-0.017967,0.016946,0.016302,-0.011406,0.021384,-0.001978,-0.005628,-0.080374,0.039484,0.015890,0.034496,-0.016936,0.004379,-0.005021,0.014321,-0.003484,-0.002882,-0.002483,-0.005047,0.017296,-0.003401,0.009433,-0.001665,0.018296,0.003151,-0.031688,0.003527,0.010405,-0.006932,-0.019232,-0.004084,-0.023476,-0.008857,-0.015648,0.053937,0.034130,-0.026430,0.018625,-0.050338,0.022854,-0.000992,0.001886,-0.013131,0.037482,0.025278,-0.008833,-0.009892,0.015771,-0.019763,-0.015569,-0.015169,0.040201,0.018226,0.018286,-0.011713,-0.000436,0.000451,0.012252,0.007596,-0.000338,0.004704,0.023604,-0.020461,0.016871,0.003246,-0.045373,0.004746,-0.036469,-0.025234,0.030737,-0.000797,0.015820,0.042129,0.010345,0.022695,0.005339,-0.001636,-0.018894,0.026074,-0.054026,-0.057851,0.004372,-0.020828,-0.034435,0.055865,0.016301,0.063019,0.010370,-0.004495,-0.030530,0.018833,-0.013644,0.002207,0.037501,-0.045908,-0.059514,-0.035367,-0.024918,-0.039085,0.035208,0.085963,0.009390,0.079267,0.013885,0.006535,-0.052116,-0.033637,0.008546,-0.019285,0.006149,0.002710,-0.056530,-0.022435,0.020384,-0.013988,-0.005111,-0.015295,-0.097911,-0.042214,0.020642,-0.042973,0.045024,0.005130,-0.022150,0.006530,0.054045,-0.042555,0.006345,-0.035607,-0.006021,0.000036,-0.033672,0.020923,-0.000556,-0.034840,0.034524,0.004798,0.001867,-0.019097,0.025730,0.000530,0.020332,-0.028041,0.001581,0.006948,-0.064965,0.022597,-0.017810,2026-03-06 12:00:00
2,2026-03-06 08:32:47,DeepStateUA,0.009647,-0.001083,0.029820,0.004092,-0.021362,0.053647,-0.076998,0.085930,0.011210,-0.020903,-0.051377,0.013232,-0.021159,0.001682,0.049129,-0.010018,-0.014271,-0.012423,-0.010588,0.046603,0.026875,0.002452,0.003347,-0.018525,0.005328,-0.003516,0.003550,0.018054,0.002157,0.012886,0.034851,0.000381,-0.009230,-0.002467,0.002381,0.000435,0.000842,-0.004257,-0.003348,0.009321,-0.005701,-0.004301,-0.016552,-0.001785,0.016005,0.008306,0.000706,-0.004439,-0.004069,-0.017177,-0.017974,-0.000361,-0.033317,-0.032714,0.027864,-0.006006,0.000665,-0.001117,-0.020576,0.002026,0.001386,0.000074,0.000035,0.007953,0.005774,0.005407,-0.005473,0.009134,-0.010858,-0.014439,0.028165,-0.023096,0.014483,0.021402,-0.017701,0.035852,-0.021296,-0.016145,-0.007317,-0.016939,0.014848,-0.006705,-0.047833,-0.002701,0.006144,-0.016566,0.016766,0.017487,0.002922,-0.004175,0.003020,-0.032485,0.001179,0.015611,0.015266,0.023711,0.005134,-0.030744,-0.014357,0.024034,0.016933,-0.044400,0.005215,0.011766,-0.026130,-0.005996,0.011388,-0.012677,-0.016358,-0.020579,-0.003119,-0.003134,0.019595,-0.011791,0.015521,0.022933,0.013426,0.013833,-0.006377,0.006772,-0.023631,0.008806,0.003886,0.014650,-0.029616,0.047030,0.005467,-0.020456,0.018529,-0.009387,0.010160,0.010283,-0.016104,0.038236,-0.028747,0.030649,0.028343,0.020708,0.001123,-0.009186,-0.064016,0.007831,0.005442,0.008333,-0.002820,0.007245,0.037716,-0.034047,0.009513,0.002276,-0.009623,-0.009046,0.023603,-0.009777,-0.047725,0.011991,-0.016423,0.004245,0.039250,0.030454,-0.007661,-0.043307,-0.005340,-0.003352,0.004921,0.010619,0.011745,-0.029661,-0.016769,-0.004054,-0.019134,-0.010521,-0.016018,0.013938,0.061204,0.000223,-0.016080,-0.013129,0.011080,0.025287,0.030597,-0.001902,-0.032930,0.022210,0.024393,-0.023036,0.001308,-0.010151,0.002527,0.003083,0.002821,0.012997,0.008941,-0.011744,0.019257,-0.000326,0.025398,-0.044011,-0.021810,-0.040764,-0.011043,0.008865,-0.020367,-0.005459,0.002685,0.019290,0.025485,-0.019258,-0.011527,-0.015354,-0.003904,0.007485,0.039596,0.030817,-0.034836,0.029725,0.018850,0.009886,0.006251,-0.006886,-0.028339,-0.017251,-0.019577,-0.004734,-0.014053,-0.014076,-0.018760,-0.006640,0.002467,-0.014727,0.015968,-0.020566,-0.000171,-0.020244,0.003823,-0.020505,-0.006361,-0.011117,-0.002427,0.036069,0.025378,-0.003550,-0.043415,-0.007200,-0.009172,0.006124,-0.004550,0.020576,0.010544,0.012825,2026-03-06 08:00:00
3,2026-03-05 16:46:58,DeepStateUA,0.006857,0.000279,0.019019,0.000875,-0.011544,0.032104,-0.049929,0.059696,0.042415,-0.023916,-0.020173,0.022363,-0.016425,-0.354007,0.422410,0.017232,-0.106286,-0.032499,-0.045502,0.118053,0.090722,-0.246774,-0.000077,0.150527,0.029981,-0.074173,0.006982,0.007685,0.035762,0.018338,0.059439,0.029451,-0.012747,0.032325,-0.024156,0.006144,-0.004921,-0.007047,0.024916,-0.013464,-0.012810,0.004618,0.006305,0.017777,-0.037226,-0.018749,-0.026076,0.008026,-0.040668,-0.008455,-0.012120,-0.009955,-0.018018,0.006661,0.032070,0.001406,0.015931,0.020066,0.022360,-0.017343,-0.007000,-0.017683,-0.021564,-0.005667,-0.004897,0.022713,0.002352,0.021026,-0.020492,0.010265,0.006341,-0.062306,-0.031869,-0.004833,0.019042,0.034739,-0.048355,-0.072654,-0.066847,-0.074661,0.019525,0.081765,0.106477,-0.025839,-0.046011,0.091824,0.043276,0.026990,0.018548,0.002251,-0.006682,-0.005199,-0.051075,-0.003017,0.029777,-0.054537,-0.002321,0.044861,-0.018019,0.033038,0.036190,-0.042962,-0.033109,-0.031216,0.040022,-0.016626,-0.004321,-0.022597,0.001446,-0.018905,-0.015046,-0.006992,0.004125,0.000550,-0.011207,-0.006348,-0.005325,-0.023457,0.009404,0.021777,-0.001560,-0.021654,-0.010065,-0.041095,0.009058,-0.016847,0.014130,0.030820,0.014433,0.011400,0.017331,0.012039,-0.011976,-0.037318,-0.000059,0.013755,-0.023928,-0.033049,0.051293,-0.004679,0.075124,0.004404,-0.023162,-0.009870,0.008475,-0.011321,0.038668,-0.021760,0.017180,-0.003656,-0.004497,0.024860,-0.010259,-0.023728,-0.073984,0.014863,0.037362,-0.023343,0.010636,-0.008617,0.012118,0.033946,-0.033242,-0.018743,-0.029519,0.034794,-0.025605,0.008930,-0.006082,-0.003809,-0.002692,0.017623,-0.010778,-0.010494,0.004241,0.018071,0.015268,-0.027505,0.007476,0.058355,0.024457,0.010803,-0.030662,-0.001728,-0.001191,-0.040228,0.003914,0.019603,0.006112,-0.006858,0.006677,-0.036682,0.007404,-0.025808,-0.014273,-0.007471,0.014518,-0.012831,0.005292,-0.002303,-0.003711,-0.008705,0.000811,-0.012632,0.003962,0.004388,0.000392,0.002013,-0.028686,-0.003865,0.011868,0.012458,0.016571,0.009521,-0.001085,0.007509,0.021553,0.002596,0.005686,0.003029,-0.016085,0.005070,-0.006296,0.000888,0.002830,0.014467,0.006547,0.000059,-0.020972,0.009385,-0.014722,-0.008414,0.016377,-0.008301,-0.000710,-0.008819,0.006663,0.012456,0.012080,0.020719,0.008728,-0.007502,-0.021433,0.028223,-0.025323,-0.045761,-0.001697,0.002329,-0.042282,-0.017344,2026-03-05 16:00:00
4,2026-03-05 15:46:39,DeepStateUA,0.048850,-0.006687,0.076040,-0.003924,-0.027197,0.089562,-0.088811,0.109836,0.052317,-0.025058,0.032393,-0.004227,-0.005032,-0.173462,0.094957,0.012582,-0.022470,-0.000701,-0.014110,-0.004739,-0.012713,0.127035,0.018404,-0.023593,0.003993,0.039285,-0.018524,0.000346,-0.081926,-0.045456,-0.116434,-0.028074,-0.013547,0.024679,0.046939,-0.021634,0.023138,0.009856,-0.025864,-0.041176,-0.000832,-0.024707,0.013634,-0.022765,0.057346,0.020489,0.010217,-0.026627,0.022514,0.022439,0.035388,-0.021224,0.008281,-0.000369,-0.015992,0.012876,-0.018086,-0.005188,-0.021093,0.012907,-0.008576,-0.008820,0.030578,0.014680,0.017475,0.007797,0.004474,-0.006686,0.023422,0.017913,0.009466,-0.011255,-0.006200,0.008317,-0.038521,0.017131,0.046956,0.005528,0.071628,0.044144,-0.006390,0.009272,-0.010302,-0.023798,0.013099,0.004949,0.000502,-0.025377,0.000576,0.005652,0.013762,-0.033165,0.011959,0.032019,-0.010729,0.074746,-0.045156,-0.069856,0.017151,-0.028899,-0.001317,-0.020143,-0.001444,0.077727,0.008474,0.017218,0.063803,0.022661,-0.019578,-0.089309,0.043190,0.054776,0.003839,0.005619,0.042291,-0.040703,0.034216,-0.018434,0.026249,-0.012015,0.004663,0.009540,0.028979,0.022277,0.015843,0.026390,-0.030022,-0.019719,0.008557,-0.006588,-0.012466,-0.013107,0.000680,-0.040800,0.018810,-0.018852,0.015615,-0.026299,-0.013060,-0.022985,-0.019649,0.003882,0.019573,0.020302,-0.053045,-0.013295,-0.013323,0.043432,-0.020309,-0.004050,-0.017728,-0.008395,-0.063169,-0.008017,0.060143,-0.036649,-0.009351,-0.031419,-0.019356,0.002941,0.015680,0.058794,0.034299,0.025507,0.026522,-0.024327,0.001476,-0.008036,-0.008201,0.018152,0.016011,-0.009222,0.020974,0.008694,-0.047264,0.028262,-0.002851,0.009422,-0.012002,0.004519,-0.010160,-0.031831,-0.005528,0.038708,-0.014277,0.009808,0.004059,-0.009500,0.033000,-0.038357,-0.005480,0.016188,-0.012154,-0.003113,0.007213,-0.049557,0.001337,0.025862,0.002217,0.009792,-0.002905,0.012793,-0.039633,-0.014680,0.012541,-0.026685,-0.057037,-0.038288,-0.031196,-0.025930,0.009651,0.004537,0.035687,-0.013257,0.015052,-0.006502,0.018667,-0.013956,0.023991,0.033361,-0.000124,-0.000186,0.012095,0.023317,0.014021,-0.007477,-0.006606,-0.045891,0.004310,-0.008439,0.004574,-0.039585,0.004941,0.010379,-0.002950,-0.053005,0.008541,-0.002762,0.010718,0.035433,0.017978,0.027453,-0.019744,0.008659,0.023139,-0.009485,-0.030263,0.013689,-0.022727,0.006843,2026-03-05 15:00:00

In [28]:
#tg_hourly["datetime_hour"] = tg_hourly["datetime_hour"] + pd.Timedelta(hours=1)        ТУТ ЗСУВ ТГ НА 1 ГОДИНУ

In [29]:
df_final = df_final.merge(tg_hourly, on="datetime_hour", how="left")

In [30]:
df_final.sample(20)

,datetime_hour,region_id,city_latitude,city_longitude,day_temp,day_dew,day_humidity,day_precip,day_precipprob,day_precipcover,day_snow,day_snowdepth,day_windgust,day_windspeed,day_winddir,day_pressure,day_cloudcover,day_solarradiation,day_solarenergy,day_uvindex,day_moonphase,hour_temp,hour_feelslike,hour_humidity,hour_precip,hour_precipprob,hour_snow,hour_windgust,hour_windspeed,hour_winddir,hour_pressure,hour_cloudcover,hour_solarradiation,hour_solarenergy,hour_uvindex,day_conditions_simple_Clear,day_conditions_simple_Cloudy,day_conditions_simple_Rain,day_conditions_simple_Snow,hour_conditions_simple_Clear,hour_conditions_simple_Cloudy,hour_conditions_simple_Rain,hour_conditions_simple_Snow,year,month,day_of_week,hour,city_name,city_timezone,day_datetime,day_sunrise,day_sunset,hour_datetime,region_key,alarm_active,alarm_minutes_in_hour,alarm_lag_1,alarm_lag_3,alarm_lag_6,alarm_lag_12,alarms_in_last_24h,is_weekend,is_night,total_active_alarms_lag1,neighbour_alarms,hours_since_last_alarm,isw_topic_0,isw_topic_1,isw_topic_2,isw_topic_3,isw_topic_4,isw_topic_5,isw_topic_6,isw_topic_7,isw_topic_8,isw_topic_9,isw_topic_10,isw_topic_11,isw_topic_12,isw_topic_13,isw_topic_14,isw_topic_15,isw_topic_16,isw_topic_17,isw_topic_18,isw_topic_19,isw_topic_20,isw_topic_21,isw_topic_22,isw_topic_23,isw_topic_24,isw_topic_25,isw_topic_26,isw_topic_27,isw_topic_28,isw_topic_29,isw_topic_30,isw_topic_31,isw_topic_32,isw_topic_33,isw_topic_34,isw_topic_35,isw_topic_36,isw_topic_37,isw_topic_38,isw_topic_39,isw_topic_40,isw_topic_41,isw_topic_42,isw_topic_43,isw_topic_44,isw_topic_45,isw_topic_46,isw_topic_47,isw_topic_48,isw_topic_49,isw_topic_50,isw_topic_51,isw_topic_52,isw_topic_53,isw_topic_54,isw_topic_55,isw_topic_56,isw_topic_57,isw_topic_58,isw_topic_59,isw_topic_60,isw_topic_61,isw_topic_62,isw_topic_63,isw_topic_64,isw_topic_65,isw_topic_66,isw_topic_67,isw_topic_68,isw_topic_69,isw_topic_70,isw_topic_71,isw_topic_72,isw_topic_73,isw_topic_74,isw_topic_75,isw_topic_76,isw_topic_77,isw_topic_78,isw_topic_79,isw_topic_80,isw_topic_81,isw_topic_82,isw_topic_83,isw_topic_84,isw_topic_85,isw_topic_86,isw_topic_87,isw_topic_88,isw_topic_89,isw_topic_90,isw_topic_91,isw_topic_92,isw_topic_93,isw_topic_94,isw_topic_95,isw_topic_96,isw_topic_97,isw_topic_98,isw_topic_99,isw_topic_100,isw_topic_101,isw_topic_102,isw_topic_103,isw_topic_104,isw_topic_105,isw_topic_106,isw_topic_107,isw_topic_108,isw_topic_109,isw_topic_110,isw_topic_111,isw_topic_112,isw_topic_113,isw_topic_114,isw_topic_115,isw_topic_116,isw_topic_117,isw_topic_118,isw_topic_119,isw_topic_120,isw_topic_121,isw_topic_122,isw_topic_123,isw_topic_124,isw_topic_125,isw_topic_126,isw_topic_127,isw_topic_128,isw_topic_129,isw_topic_130,isw_topic_131,isw_topic_132,isw_topic_133,isw_topic_134,isw_topic_135,isw_topic_136,isw_topic_137,isw_topic_138,isw_topic_139,isw_topic_140,isw_topic_141,isw_topic_142,isw_topic_143,isw_topic_144,isw_topic_145,isw_topic_146,isw_topic_147,isw_topic_148,isw_topic_149,isw_total_intensity,isw_topic_std,isw_topic_max,isw_topic_mean,isw_velocity_24h,isw_intensity_ema,isw_topic_entropy,tg_topic_0,tg_topic_1,tg_topic_2,tg_topic_3,tg_topic_4,tg_topic_5,tg_topic_6,tg_topic_7,tg_topic_8,tg_topic_9,tg_topic_10,tg_topic_11,tg_topic_12,tg_topic_13,tg_topic_14,tg_topic_15,tg_topic_16,tg_topic_17,tg_topic_18,tg_topic_19,tg_topic_20,tg_topic_21,tg_topic_22,tg_topic_23,tg_topic_24,tg_topic_25,tg_topic_26,tg_topic_27,tg_topic_28,tg_topic_29,tg_topic_30,tg_topic_31,tg_topic_32,tg_topic_33,tg_topic_34,tg_topic_35,tg_topic_36,tg_topic_37,tg_topic_38,tg_topic_39,tg_topic_40,tg_topic_41,tg_topic_42,tg_topic_43,tg_topic_44,tg_topic_45,tg_topic_46,tg_topic_47,tg_topic_48,tg_topic_49,tg_topic_50,tg_topic_51,tg_topic_52,tg_topic_53,tg_topic_54,tg_topic_55,tg_topic_56,tg_topic_57,tg_topic_58,tg_topic_59,tg_topic_60,tg_topic_61,tg_topic_62,tg_topic_63,tg_topic_64,tg_topic_65,tg_topic_66,tg_topic_67,tg_topic_68,tg_topic_69,tg_topic_70,tg_topic_71,tg_topic_72,tg_topic_73,tg_topic_74,tg_topic_75,tg_topic_76,tg_topic_77,tg_topic_78,tg_topic_79,tg_topic_80,tg_topic_81,tg_topic_82,tg_topic_83,tg_topic_84,tg_topic_85,tg_topic_86,tg_topic_87,tg_topic_88,tg_topic_89,tg_topic_90,tg_topic_91,tg_topic_92,tg_topic_93,tg_topic_94,tg_topic_95,tg_topic_96,tg_topic_97,tg_topic_98,tg_topic_99,tg_topic_100,tg_topic_101,tg_topic_102,tg_topic_103,tg_topic_104,tg_topic_105,tg_topic_106,tg_topic_107,tg_topic_108,tg_topic_109,tg_topic_110,tg_topic_111,tg_topic_112,tg_topic_113,tg_topic_114,tg_topic_115,tg_topic_116,tg_topic_117,tg_topic_118,tg_topic_119,tg_topic_120,tg_topic_121,tg_topic_122,tg_topic_123,tg_topic_124,tg_topic_125,tg_topic_126,tg_topic_127,tg_topic_128,tg_topic_129,tg_topic_130,tg_topic_131,tg_topic_132,tg_topic_133,tg_topic_134,tg_topic_135,tg_topic_136,tg_topic_137,tg_topic_138,tg_topic_139,tg_topic_140,tg_topic_141,tg_topic_142,tg_topic_143,tg_topic_144,tg_topic_145,tg_topic_146,tg_topic_147,tg_topic_148,tg_topic_149,tg_topic_150,tg_topic_151,tg_topic_152,tg_topic_153,tg_topic_154,tg_topic_155,tg_topic_156,tg_topic_157,tg_topic_158,tg_topic_159,tg_topic_160,tg_topic_161,tg_topic_162,tg_topic_163,tg_topic_164,tg_topic_165,tg_topic_166,tg_topic_167,tg_topic_168,tg_topic_169,tg_topic_170,tg_topic_171,tg_topic_172,tg_topic_173,tg_topic_174,tg_topic_175,tg_topic_176,tg_topic_177,tg_topic_178,tg_topic_179,tg_topic_180,tg_topic_181,tg_topic_182,tg_topic_183,tg_topic_184,tg_topic_185,tg_topic_186,tg_topic_187,tg_topic_188,tg_topic_189,tg_topic_190,tg_topic_191,tg_topic_192,tg_topic_193,tg_topic_194,tg_topic_195,tg_topic_196,tg_topic_197,tg_topic_198,tg_topic_199,tg_topic_200,tg_topic_201,tg_topic_202,tg_topic_203,tg_topic_204,tg_topic_205,tg_topic_206,tg_topic_207,tg_topic_208,tg_topic_209,tg_topic_210,tg_topic_211,tg_topic_212,tg_topic_213,tg_topic_214,tg_topic_215,tg_topic_216,tg_topic_217,tg_topic_218,tg_topic_219,tg_topic_220,tg_topic_221,tg_topic_222,tg_topic_223,tg_topic_224,tg_topic_225,tg_topic_226,tg_topic_227,tg_topic_228,tg_topic_229,tg_topic_230,tg_topic_231,tg_topic_232,tg_topic_233,tg_topic_234,tg_topic_235,tg_topic_236,tg_topic_237,tg_topic_238,tg_topic_239,tg_topic_240,tg_topic_241,tg_topic_242,tg_topic_243,tg_topic_244,tg_topic_245,tg_topic_246,tg_topic_247,tg_topic_248,tg_topic_249
630466,2024-08-14 10:00:00,26,50.45060,30.52430,18.4,11.3,66.0,0.000,0.0,0.00,0.0,0.0,25.2,10.8,324.0,1018.7,6.5,260.1,22.7,8.0,0.32,16.9,16.9,79.33,0.000,0.0,0.0,23.4,9.7,332.7,1020.0,4.6,497.1,1.8,5.0,True,False,False,False,True,False,False,False,2024,8,2,10,Kyiv,Europe/Kiev,2024-08-14,05:45:19,20:18:47,10:00:00,Київ,0,0.000000,0.0,0.0,0.0,0.0,2.0,0,0,0.0,0.0,8,0.749509,0.044255,-0.013205,-0.042764,-0.199284,0.080607,-0.014024,0.084960,0.274650,-0.183837,0.075777,0.014652,-0.107163,-0.125822,0.030172,-0.037054,-0.007793,-0.029471,-0.001705,0.097654,0.083987,-0.037868,0.028096,0.104114,-0.044579,-0.009504,0.067656,-0.047296,0.098931,0.052353,0.076436,0.001803,0.016558,-0.024363,0.065686,0.012229,-0.008208,-0.012858,-0.012511,-0.007679,0.009661,0.046042,-0.024539,-0.018846,0.032125,-0.001341,0.051314,0.025954,0.070903,-0.000093,-0.045885,0.072565,0.057101,0.032549,0.039621,0.047074,-0.022366,-0.010768,0.022241,-0.027959,-0.026526,0.006269,0.016482,0.006366,0.012777,0.047869,0.020288,-0.021016,0.033053,-0.027628,-0.042692,0.028438,0.019367,0.028522,-0.006111,-0.006172,0.012330,0.001337,-0.012764,-0.026082,-0.009893,-0.006055,0.024881,-0.001526,-0.002622,0.034781,-0.026616,-0.004327,-0.001039,-0.018526,0.010552,-0.022798,-0.002595,-0.010123,0.002588,0.013018,-0.011091,-0.019856,-0.018991,0.011025,-0.000281,0.008367,-0.004560,-0.000305,0.001312,0.013674,0.009486,-0.004159,-0.004727,-0.006872,-0.022212,-0.014079,0.023227,-0.017820,-0.019615,4.127664e-03,-0.023694,0.007165,-0.023440,-0.010539,0.007424,-0.005246,0.007224,-0.011354,0.021997,-0.014262,0.033544,0.000808,0.011336,-0.008563,-0.020059,0.017209,-0.036174,0.000528,-0.024309,0.015243,-0.022272,-0.006551,0.007558,-0.030946,-0.000452,0.004058,-0.025712,0.014124,-0.017867,-0.010808,-0.005132,0.017020,0.023534,0.012731,4.994721,0.069520,0.749509,0.033298,0.301802,4.882061,4.213028,0.288557,0.015600,0.008522,-0.122580,-0.076763,-0.084796,-0.031220,0.055065,-0.038473,-0.067649,0.052553,0.043784,-0.031168,-0.019874,-0.029781,0.015846,0.030401,-0.001711,-0.062649,-0.013458,0.056206,-0.025357,-0.018278,-0.023095,0.011327,0.034799,0.001513,-0.010400,-0.028087,0.046901,0.000527,0.001789,0.026130,-0.031121,0.008247,-0.068835,-0.014501,-0.006406,-0.015034,-0.032760,-0.023470,-0.023265,0.010687,0.035932,0.017956,-0.005547,-0.015238,-0.036193,-0.002383,0.010553,-0.001709,-0.008564,0.016455,0.000187,-0.011118,-0.030069,0.012567,0.001763,-0.002291,-0.006724,-0.006966,-0.005249,-0.002192,0.020613,0.002686,0.018654,0.008749,0.006990,0.000630,0.005121,0.014543,-0.019856,-0.003370,0.004027,-0.018350,0.007247,-0.003094,0.004339,-0.011514,0.006133,-0.019161,-0.022247,0.017082,0.000362,0.005616,-0.016996,0.003559,-0.003107,0.016268,-0.015446,-0.027614,-0.000613,-0.009654,-0.006445,0.012273,-0.010151,-0.027139,-0.002392,0.003090,-0.014294,0.031674,0.023513,0.012264,-0.004751,-0.000851,0.027842,-0.001883,-0.009915,-0.011127,-0.010746,-0.017285,-0.024360,-0.012611,0.008585,0.021183,0.003995,-0.016960,0.004496,-0.031067,0.014623,-0.032159,0.000434,-0.007490,-0.003341,-0.000034,0.018498,-0.005845,0.000658,0.003880,-0.006091,0.012324,0.002619,-0.009817,-0.004322,-0.013481,0.013736,0.034660,-0.000489,0.006323,0.003204,-0.006096,0.006370,-0.006613,0.011974,-0.010802,-0.013339,0.004508,-0.004836,0.002590,-0.018229,-0.005085,0.010781,0.002679,-0.003447,0.000995,0.009669,-0.002306,0.011195,0.002334,-0.005203,0.005355,0.002270,-0.005437,0.001322,0.001176,0.004572,0.012448,0.003752,-0.004987,-0.008771,0.013428,-0.008766,-0.013191,-0.003929,-0.002143,-0.013831,-0.011610,0.007907,0.002821,-0.015477,-0.006117,0.008089,0.013775,0.021251,-0.000918,-0.000307,0.005690,0.006206,0.001532,0.018627,0.006601,-0.004332,-0.004727,0.001231,0.014353,0.013130,-0.006088,-0.006010,0.007588,0.003708,0.011873,0.002135,0.000532,0.002206,-0.002705,0.005039,-0.003523,0.000134,0.002711,0.009183,-0.005701,0.017288,-0.006943,-0.003158,-0.003280,-0.001751,-0.008233,-0.003262,-0.005477,0.004367,0.006172,0.000504,0.008946,0.016044,-0.005599,-0.010165,0.001240,-0.014386,-0.003301,-0.014410,-0.000749,-0.002232,0.000232,0.007093,0.000778,0.006569,0.013345,-0.007627,-0.001648,-0.006604,-0.002340,0.005506,-0.002808,0.007836,0.004033,0.003211,0.006476,-0.003410,-0.001523,-0.001438
592941,2023-05-11 17:00:00,25,51.49370,31.29440,11.5,0.7,49.5,0.800,100.0,12.50,0.0,0.0,30.2,18.0,353.2,1024.6,55.3,258.6,22.3,7.0,0.70,17.5,17.5,36.61,0.000,0.0,0.0,22.0,9.4,5.5,1023.0,60.2,470.5,1.7,5.0,False,False,True,False,False,True,False,False,2023,5,3,17,Chernihiv,Europe/Kiev,2023-05-11,05:09:59,20:33:33,17:00:00,Чернігівська,0,0.000000,0.0,0.0,1.0,0.0,10.0,0,0,2.0,1.0,5,0.754107,-0.255222,-0.094738,-0.008290,0.020274,0.062999,-0.024968,0.086557,-0.136264,0.113538,0.106284,0.021962,-0.049098,-0.003071,0.067646,0.097515,0.124744,0.009234,-0.069873,0.066805,0.074929,0.002251,0.080272,-0.080093,0.023469,0.045944,0.018150,-0.004839,0.005510,-0.005964,0.020804,-0.039084,0.066725,0.028816,-0.028675,-0.024303,0.025624,-0.065761,0.054359,0.025690,-0.060881,-0.033666,-0.031462,0.019170,-0.001340,-0.064013,0.024787,-0.011629,0.052945,-0.028830,0.001303,0.008729,-0.029422,0.009250,-0.002884,-0.024439,-0.014082,0.003038,0.046122,-0.043833,-0.049495,0.044631,-0.009332,-0.019086,-0.091156,-0.053086,-0.010805,-0.013437,0.029145,0.010660,0.039846,-0.034039,-0.024175,0.011345,0.030886,-0.000882,-0.003865,-0.009488,-0.048707,-0.013501,-0.054167,-0.010871,-0.037643,0.033583,0.003650,0.005923,-0.032025,-0.012541,0.002488,-0.006052,-0.009301,-0.027402,-0.003509,0.015539,0.013909,-0.061687,-0.040800,0.017721,-0.020668,0.015726,0.034188,0.024895,-0.003651,-0.004516,-0.014740,-0.031418,0.018941,0.006674,-0.011407,-0.046256,0.007943,0.030459,0.015703,0.044368,-0.005500,1.633853e-04,-0.009842,-0.015122,-0.021265,0.004057,-0.010134,-0.029053,0.032088,-0.015355,-0.006947,-0.020223,0.025120,-0.012430,-0.013494,0.000150,0.035740,0.002148,-0.029235,-0.010959,-0.020841,0.040327,0.029937,-0.034205,0.028010,0.002003,0.013397,0.011245,0.060466,-0.021514,-0.002471,-0.030145,0.029383,0.002093,0.016309,0.035321,5.350895,0.067348,0.754107,0.035673,1.105020,5.133978,4.346238,0.018145,0.002580,0.024293,-0.001496,-0.028403,0.048523,-0.072618,0.084092,0.022692,-0.033299,-0.047503,-0.002538,-0.008448,0.019607,0.006721,-0.031792,0.002325,-0.019187,-0.038413,0.042056,0.002574,0.053271,0.012849,-0.022269,-0.008491,0.002603,-0.008602,0.011442,0.007838,0.015041,0.009178,-0.003501,-0.005454,0.010374,-0.004723,-0.000578,-0.008757,0.006647,-0.006464,0.007982,-0.000245,-0.002161,0.000252,0.003742,0.000566,0.000861,-0.007630,-0.001228,-0.000686,-0.007004,-0.003291,0.001735,-0.006130,0.013293,-0.000087,0.003990,-0.005927,-0.005334,-0.003348,-0.000992,-0.001945,-0.017870,0.006238,-0.022983,-0.002457,0.003413,-0.019677,0.016708,-0.003467,0.003100,0.026652,-0.019145,0.019743,0.025800,0.001524,0.026426,0.002596,0.002754,-0.006778,-0.011540,0.004855,0.001381,-0.020856,-0.014402,0.003203,0.007505,-0.007713,0.002356,0.007274,0.011888,-0.017209,0.011231,-0.018175,0.000895,-0.001211,0.017460,-0.011281,-0.012403,0.000227,0.000117,-0.000451,-0.019114,-0.001674,0.013259,-0.019471,-0.002772,0.000328,0.009853,-0.021877,0.041399,0.019186,-0.013186,-0.016621,-0.030619,0.028827,-0.040316,0.026280,-0.004938,0.001963,-0.013715,0.019960,0.025734,0.034360,0.006992,0.008902,-0.026544,-0.020336,-0.030930,-0.009880,-0.003578,-0.012459,-0.001039,0.012990,-0.032063,0.031246,-0.043145,-0.005636,-0.001295,-0.001483,0.027341,0.024619,0.010508,-0.009167,-0.010218,0.003962,-0.000857,-0.020914,0.029237,0.017528,0.008322,0.023531,0.007784,-0.018910,0.000268,0.013420,-0.025932,-0.021244,-0.027748,-0.024966,-0.005221,-0.032136,0.024843,0.006854,0.030028,-0.011140,-0.026933,0.003492,-0.005199,0.037354,-0.007196,0.035328,-0.018752,0.019433,0.010478,-0.033692,0.003613,0.023421,-0.032430,-0.016437,0.021308,-0.022181,-0.016630,0.034322,0.011381,-0.024213,0.020582,0.007209,-0.000585,-0.034494,-0.008124,0.009246,-0.040476,0.026466,0.010716,0.024684,0.016487,0.051584,-0.017196,-0.028711,-0.003890,-0.007442,-0.026208,0.009604,0.029263,0.043455,0.024095,0.024364,0.021607,-0.004847,0.042111,0.044456,0.012631,-0.009558,0.013263,0.044170,-0.001735,-0.000616,-0.014568,-0.036541,-0.001981,0.004158,-0.024805,0.029344,0.019532,-0.015282,-0.004834,0.001471,-0.013360,-0.004402,0.007997,-0.015645,-0.013250,0.004066,-0.031181,0.021292,0.018150,0.017634,-0.004255,0.038563,0.002899,-0.002123,0.003817,0.005361,0.027180,0.029771,0.001715,-0.004916,0.011219,0.012399,-0.020979
419202,2024-09-03 18:00:00,18,50.90800,34.79720,21.7,8.8,44.3,0.000,0.0,0.00,0.0,0.0,34.9,19.8,66.6,1020.3,87.7,111.0,9.5,4.0,0.00,24.1,24.1,41.18,0.000,0.0,0.0,25.6,7.1,40.0,1020.6,99.7,142.3,0.5,1.0,False,True,False,False,False,True,False,False,2024,9,1,18,Sumy,Europe/Kiev,2024-09-03,05:57:55,19:21:15,18:00:00,Сумська,1,24.866667,1.0,1.0,1.0,1.0,21.0,0,0,5.0,3.0,0,0.809912,0.073285,-0.079578,0.028670,-0.120328,-0.008485,-0.028895,0.004353,0.121206,-0.144167,-0.006592,0.048732,0.160466,0.151950,0.038795,0.089687,0.003073,-0.074817,0.047909,0.056316,0.126310,-0.051195,-0.002868,0.009120,-0.062726,-0.054451,0.045595,-0.070001,0.095038,-0.032931,-0.014295,0.018083,-0.000713,0.016890,-0.013382,-0.010996,0.007575,-0.014775,0.027380,-0.011316,0.038632,-0.003685,0.031856,-0.056754,0.010117,-0.014508,-0.036729,-0.010827,-0.019411,-0.007107,-0.003328,-0.021101,0.052593,-0.016291,-0.013127,-0.001437,-0.028936,-0.000473,-0.012308,0.011090,-0.027741,-0.012496,-0.013659,0.014488,-0.003242,-0.014035,0.033377,-0.028956,-0.018072,-0.009091,0.005052,-0.034558,0.023685,0.005798,-0.033386,-0.016309,-0.004272,-0.000004,-0.000142,-0.014848,0.020033,-0.028015,-0.041623,0.024344,0.004033,0.003829,0.010719,-0.002538,-0.028754,0.010449,0.003737,-0.000674,-0.012995,-0.019202,0.001655,-0.022274,0.034580,-0.010666,-0.039050,0.010119,-0.000635,-0.022376,-0.020734,0.002312,-0.000949,-0.007103,-0.009007,0.003100,-0.029533,0.028354,0.001700,0.001700,-0.005127,-0.009313,0.015276,-1.604816e-02,0.007281,0.015966,0.004642,-0.020661,0.005819,0.004034,-0.015479,0.003827,0.006913,-0.009892,0.004643,0.014153,-0.006230,-0.001177,0.002037,0.012928,-0.001979,-0.014562,0.018658,0.005902,0.040808,-0.014878,0.009186,-0.006917,-0.025069,-0.000540,0.019723,-0.006251,0.006666,-0.017696,-0.018889,-0.001672,-0.002135,-0.001592,4.337736,0.070889,0.809912,0.028918,0.114837,4.326050,4.083196,0.140248,0.079928,0.061080,-0.026778,-0.125196,0.029304,0.023760,-0.041743,-0.077851,-0.112258,0.022844,0.083909,0.113106,0.011510,0.001068,0.017792,0.013875,0.008068,0.007868,0.041509,-0.019152,-0.011098,-0.006783,0.016325,0.053353,0.049670,0.018036,0.027142,-0.009773,-0.015268,-0.023347,-0.007483,0.009295,-0.006938,-0.013194,-0.023116,0.012960,0.026684,-0.000869,-0.029583,-0.003042,0.009831,0.035090,0.021872,0.052078,-0.032714,-0.018584,-0.014936,-0.015222,-0.028292,-0.008144,-0.000237,0.028119,0.009900,0.040065,-0.060896,0.047337,0.055003,0.016779,0.084990,-0.012290,0.042333,-0.067751,-0.062222,0.009910,-0.041571,0.022401,-0.022762,-0.000561,-0.013499,-0.022297,0.016086,0.008759,0.009196,-0.030785,0.000616,0.011241,-0.009106,-0.027455,0.002172,-0.011442,0.012234,-0.010816,0.005029,0.025671,0.005248,-0.004426,-0.011822,0.042456,0.009896,-0.046723,0.007048,-0.020839,-0.019883,-0.008681,0.016936,0.013164,0.000365,-0.000086,-0.005592,0.002966,-0.008560,-0.009932,0.006473,-0.008552,-0.000139,-0.003398,-0.021287,0.002731,-0.003930,-0.016473,-0.015432,-0.011484,0.005080,0.005436,-0.004981,-0.024367,0.000265,-0.006919,0.005974,-0.020761,0.005309,0.002789,0.001663,0.002013,0.005349,0.014577,-0.012115,-0.006023,-0.005808,0.014127,0.009356,0.001472,-0.009967,-0.009303,0.001191,0.024711,-0.010409,-0.030121,0.004788,0.011275,0.001917,-0.003755,0.002197,0.002483,-0.000286,-0.016735,0.001812,0.015241,-0.025870,-0.016839,0.001421,0.022785,0.011370,0.011650,-0.007844,0.008988,-0.001406,-0.010700,-0.004803,-0.018376,0.010199,-0.000206,0.016588,-0.018150,-0.015753,-0.001090,0.021461,-0.015028,0.012226,-0.003158,0.009623,0.016823,-0.004079,0.013293,-0.002533,0.014552,0.008024,-0.000330,0.003563,0.006165,0.015834,-0.030265,0.008603,-0.005699,0.005273,0.012708,0.000660,-0.022408,-0.026618,0.006649,0.000263,-0.005327,-0.009201,0.023652,-0.007211,0.001143,-0.019567,0.009660,-0.001401,0.004988,0.002006,-0.020004,-0.001320,-0.012991,-0.009050,0.014555,-0.018021,-0.004707,0.002025,-0.005013,0.005426,-0.007431,-0.011488,-0.002724,-0.011649,0.001730,0.024909,-0.001752,0.003260,0.019239,0.006501,-0.005530,0.019031,0.002176,0.013152,0.016514,-0.003571,-0.001875,0.020147,-0.010316,0.015433,-0.014279,0.006058,-0.014540,0.000226,-0.006019,0.007181,-0.003514,0.003374,0.001409,-0.005839,0.004034,0.004887,0.004571,0.024010,-0.008874,-0.000579,-0.007347,-0.003493

In [31]:
df_final.shape

(635256, 473)

In [32]:
df_final = df_final.sort_values(["datetime_hour"])

In [33]:
with pd.option_context('display.max_rows', None):
    print(df_final.isnull().sum())

datetime_hour                         0
region_id                             0
city_latitude                         0
city_longitude                        0
day_temp                              0
day_dew                               0
day_humidity                          0
day_precip                            0
day_precipprob                        0
day_precipcover                       0
day_snow                              0
day_snowdepth                         0
day_windgust                          0
day_windspeed                         0
day_winddir                           0
day_pressure                          0
day_cloudcover                        0
day_solarradiation                    0
day_solarenergy                       0
day_uvindex                           0
day_moonphase                         0
hour_temp                             0
hour_feelslike                        0
hour_humidity                         0
hour_precip                           0
hour_precipprob                       0
hour_snow                             0
hour_windgust                         0
hour_windspeed                        0
hour_winddir                          0
hour_pressure                         0
hour_cloudcover                       0
hour_solarradiation                   0
hour_solarenergy                      0
hour_uvindex                          0
day_conditions_simple_Clear           0
day_conditions_simple_Cloudy          0
day_conditions_simple_Rain            0
day_conditions_simple_Snow            0
hour_conditions_simple_Clear          0
hour_conditions_simple_Cloudy         0
hour_conditions_simple_Rain           0
hour_conditions_simple_Snow           0
year                                  0
month                                 0
day_of_week                           0
hour                                  0
city_name                             0
city_timezone                         0
day_datetime                          0
day_sunrise                           0
day_sunset                            0
hour_datetime                         0
region_key                            0
alarm_active                          0
alarm_minutes_in_hour                 0
alarm_lag_1                           0
alarm_lag_3                           0
alarm_lag_6                           0
alarm_lag_12                          0
alarms_in_last_24h                    0
is_weekend                            0
is_night                              0
total_active_alarms_lag1              0
neighbour_alarms                      0
hours_since_last_alarm                0
isw_topic_0                           0
isw_topic_1                           0
isw_topic_2                           0
isw_topic_3                           0
isw_topic_4                           0
isw_topic_5                           0
isw_topic_6                           0
isw_topic_7                           0
isw_topic_8                           0
isw_topic_9                           0
isw_topic_10                          0
isw_topic_11                          0
isw_topic_12                          0
isw_topic_13                          0
isw_topic_14                          0
isw_topic_15                          0
isw_topic_16                          0
isw_topic_17                          0
isw_topic_18                          0
isw_topic_19                          0
isw_topic_20                          0
isw_topic_21                          0
isw_topic_22                          0
isw_topic_23                          0
isw_topic_24                          0
isw_topic_25                          0
isw_topic_26                          0
isw_topic_27                          0
isw_topic_28                          0
isw_topic_29                          0
isw_topic_30                          0
isw_topic_31                          0
isw_topic_32                          0
isw_topic_33                          0
isw_topic_34                          0
isw_topic_35                          0
isw_topic_36                          0
isw_topic_37                          0
isw_topic_38                          0
isw_topic_39                          0
isw_topic_40                          0
isw_topic_41                          0
isw_topic_42                          0
isw_topic_43                          0
isw_topic_44                          0
isw_topic_45                          0
isw_topic_46                          0
isw_topic_47                          0
isw_topic_48                          0
isw_topic_49                          0
isw_topic_50                          0
isw_topic_51                          0
isw_topic_52                          0
isw_topic_53                          0
isw_topic_54                          0
isw_topic_55                          0
isw_topic_56                          0
isw_topic_57                          0
isw_topic_58                          0
isw_topic_59                          0
isw_topic_60                          0
isw_topic_61                          0
isw_topic_62                          0
isw_topic_63                          0
isw_topic_64                          0
isw_topic_65                          0
isw_topic_66                          0
isw_topic_67                          0
isw_topic_68                          0
isw_topic_69                          0
isw_topic_70                          0
isw_topic_71                          0
isw_topic_72                          0
isw_topic_73                          0
isw_topic_74                          0
isw_topic_75                          0
isw_topic_76                          0
isw_topic_77                          0
isw_topic_78                          0
isw_topic_79                          0
isw_topic_80                          0
isw_topic_81                          0
isw_topic_82                          0
isw_topic_83                          0
isw_topic_84                          0
isw_topic_85                          0
isw_topic_86                          0
isw_topic_87                          0
isw_topic_88                          0
isw_topic_89                          0
isw_topic_90                          0
isw_topic_91                          0
isw_topic_92                          0
isw_topic_93                          0
isw_topic_94                          0
isw_topic_95                          0
isw_topic_96                          0
isw_topic_97                          0
isw_topic_98                          0
isw_topic_99                          0
isw_topic_100                         0
isw_topic_101                         0
isw_topic_102                         0
isw_topic_103                         0
isw_topic_104                         0
isw_topic_105                         0
isw_topic_106                         0
isw_topic_107                         0
isw_topic_108                         0
isw_topic_109                         0
isw_topic_110                         0
isw_topic_111                         0
isw_topic_112                         0
isw_topic_113                         0
isw_topic_114                         0
isw_topic_115                         0
isw_topic_116                         0
isw_topic_117                         0
isw_topic_118                         0
isw_topic_119                         0
isw_topic_120                         0
isw_topic_121                         0
isw_topic_122                         0
isw_topic_123                         0
isw_topic_124                         0
isw_topic_125                         0
isw_topic_126                         0
isw_topic_127                         0
isw_topic_128                         0
isw_topic_129                         0
isw_topic_130                         0
isw_topic_131                         0
isw_topic_132                         0
isw_topic_133                         0
isw_topic_134                         0
isw_topic_135                         0
isw_topic_136                         0
isw_topic_137                         0
isw_topic_138                         0
isw_topic_139                         0
isw_topic_140                         0
isw_topic_141                         0
isw_topic_142                         0
isw_topic_143                         0
isw_topic_144                         0
isw_topic_145                         0
isw_topic_146                         0
isw_topic_147                         0
isw_topic_148                         0
isw_topic_149                         0
isw_total_intensity                   0
isw_topic_std                         0
isw_topic_max                         0
isw_topic_mean                        0
isw_velocity_24h                      0
isw_intensity_ema                     0
isw_topic_entropy                     0
tg_topic_0                       121728
tg_topic_1                       121728
tg_topic_2                       121728
tg_topic_3                       121728
tg_topic_4                       121728
tg_topic_5                       121728
tg_topic_6                       121728
tg_topic_7                       121728
tg_topic_8                       121728
tg_topic_9                       121728
tg_topic_10                      121728
tg_topic_11                      121728
tg_topic_12                      121728
tg_topic_13                      121728
tg_topic_14                      121728
tg_topic_15                      121728
tg_topic_16                      121728
tg_topic_17                      121728
tg_topic_18                      121728
tg_topic_19                      121728
tg_topic_20                      121728
tg_topic_21                      121728
tg_topic_22                      121728
tg_topic_23                      121728
tg_topic_24                      121728
tg_topic_25                      121728
tg_topic_26                      121728
tg_topic_27                      121728
tg_topic_28                      121728
tg_topic_29                      121728
tg_topic_30                      121728
tg_topic_31                      121728
tg_topic_32                      121728
tg_topic_33                      121728
tg_topic_34                      121728
tg_topic_35                      121728
tg_topic_36                      121728
tg_topic_37                      121728
tg_topic_38                      121728
tg_topic_39                      121728
tg_topic_40                      121728
tg_topic_41                      121728
tg_topic_42                      121728
tg_topic_43                      121728
tg_topic_44                      121728
tg_topic_45                      121728
tg_topic_46                      121728
tg_topic_47                      121728
tg_topic_48                      121728
tg_topic_49                      121728
tg_topic_50                      121728
tg_topic_51                      121728
tg_topic_52                      121728
tg_topic_53                      121728
tg_topic_54                      121728
tg_topic_55                      121728
tg_topic_56                      121728
tg_topic_57                      121728
tg_topic_58                      121728
tg_topic_59                      121728
tg_topic_60                      121728
tg_topic_61                      121728
tg_topic_62                      121728
tg_topic_63                      121728
tg_topic_64                      121728
tg_topic_65                      121728
tg_topic_66                      121728
tg_topic_67                      121728
tg_topic_68                      121728
tg_topic_69                      121728
tg_topic_70                      121728
tg_topic_71                      121728
tg_topic_72                      121728
tg_topic_73                      121728
tg_topic_74                      121728
tg_topic_75                      121728
tg_topic_76                      121728
tg_topic_77                      121728
tg_topic_78                      121728
tg_topic_79                      121728
tg_topic_80                      121728
tg_topic_81                      121728
tg_topic_82                      121728
tg_topic_83                      121728
tg_topic_84                      121728
tg_topic_85                      121728
tg_topic_86                      121728
tg_topic_87                      121728
tg_topic_88                      121728
tg_topic_89                      121728
tg_topic_90                      121728
tg_topic_91                      121728
tg_topic_92                      121728
tg_topic_93                      121728
tg_topic_94                      121728
tg_topic_95                      121728
tg_topic_96                      121728
tg_topic_97                      121728
tg_topic_98                      121728
tg_topic_99                      121728
tg_topic_100                     121728
tg_topic_101                     121728
tg_topic_102                     121728
tg_topic_103                     121728
tg_topic_104                     121728
tg_topic_105                     121728
tg_topic_106                     121728
tg_topic_107                     121728
tg_topic_108                     121728
tg_topic_109                     121728
tg_topic_110                     121728
tg_topic_111                     121728
tg_topic_112                     121728
tg_topic_113                     121728
tg_topic_114                     121728
tg_topic_115                     121728
tg_topic_116                     121728
tg_topic_117                     121728
tg_topic_118                     121728
tg_topic_119                     121728
tg_topic_120                     121728
tg_topic_121                     121728
tg_topic_122                     121728
tg_topic_123                     121728
tg_topic_124                     121728
tg_topic_125                     121728
tg_topic_126                     121728
tg_topic_127                     121728
tg_topic_128                     121728
tg_topic_129                     121728
tg_topic_130                     121728
tg_topic_131                     121728
tg_topic_132                     121728
tg_topic_133                     121728
tg_topic_134                     121728
tg_topic_135                     121728
tg_topic_136                     121728
tg_topic_137                     121728
tg_topic_138                     121728
tg_topic_139                     121728
tg_topic_140                     121728
tg_topic_141                     121728
tg_topic_142                     121728
tg_topic_143                     121728
tg_topic_144                     121728
tg_topic_145                     121728
tg_topic_146                     121728
tg_topic_147                     121728
tg_topic_148                     121728
tg_topic_149                     121728
tg_topic_150                     121728
tg_topic_151                     121728
tg_topic_152                     121728
tg_topic_153                     121728
tg_topic_154                     121728
tg_topic_155                     121728
tg_topic_156                     121728
tg_topic_157                     121728
tg_topic_158                     121728
tg_topic_159                     121728
tg_topic_160                     121728
tg_topic_161                     121728
tg_topic_162                     121728
tg_topic_163                     121728
tg_topic_164                     121728
tg_topic_165                     121728
tg_topic_166                     121728
tg_topic_167                     121728
tg_topic_168                     121728
tg_topic_169                     121728
tg_topic_170                     121728
tg_topic_171                     121728
tg_topic_172                     121728
tg_topic_173                     121728
tg_topic_174                     121728
tg_topic_175                     121728
tg_topic_176                     121728
tg_topic_177                     121728
tg_topic_178                     121728
tg_topic_179                     121728
tg_topic_180                     121728
tg_topic_181                     121728
tg_topic_182                     121728
tg_topic_183                     121728
tg_topic_184                     121728
tg_topic_185                     121728
tg_topic_186                     121728
tg_topic_187                     121728
tg_topic_188                     121728
tg_topic_189                     121728
tg_topic_190                     121728
tg_topic_191                     121728
tg_topic_192                     121728
tg_topic_193                     121728
tg_topic_194                     121728
tg_topic_195                     121728
tg_topic_196                     121728
tg_topic_197                     121728
tg_topic_198                     121728
tg_topic_199                     121728
tg_topic_200                     121728
tg_topic_201                     121728
tg_topic_202                     121728
tg_topic_203                     121728
tg_topic_204                     121728
tg_topic_205                     121728
tg_topic_206                     121728
tg_topic_207                     121728
tg_topic_208                     121728
tg_topic_209                     121728
tg_topic_210                     121728
tg_topic_211                     121728
tg_topic_212                     121728
tg_topic_213                     121728
tg_topic_214                     121728
tg_topic_215                     121728
tg_topic_216                     121728
tg_topic_217                     121728
tg_topic_218                     121728
tg_topic_219                     121728
tg_topic_220                     121728
tg_topic_221                     121728
tg_topic_222                     121728
tg_topic_223                     121728
tg_topic_224                     121728
tg_topic_225                     121728
tg_topic_226                     121728
tg_topic_227                     121728
tg_topic_228                     121728
tg_topic_229                     121728
tg_topic_230                     121728
tg_topic_231                     121728
tg_topic_232                     121728
tg_topic_233                     121728
tg_topic_234                     121728
tg_topic_235                     121728
tg_topic_236                     121728
tg_topic_237                     121728
tg_topic_238                     121728
tg_topic_239                     121728
tg_topic_240                     121728
tg_topic_241                     121728
tg_topic_242                     121728
tg_topic_243                     121728
tg_topic_244                     121728
tg_topic_245                     121728
tg_topic_246                     121728
tg_topic_247                     121728
tg_topic_248                     121728
tg_topic_249                     121728
dtype: int64

In [34]:
df_final = df_final.fillna(0)

In [35]:
tg_cols = [c for c in df_final.columns if 'tg_topic_' in c]
df_tg_abs = df_final[tg_cols].abs()

df_final['tg_total_intensity'] = df_tg_abs.sum(axis=1)
df_final['tg_topic_std'] = df_tg_abs.std(axis=1)
df_final['tg_topic_max'] = df_tg_abs.max(axis=1)
df_final['tg_topic_entropy'] = -(df_tg_abs.div(df_tg_abs.sum(axis=1), axis=0) * np.log(df_tg_abs.div(df_tg_abs.sum(axis=1), axis=0) + 1e-9)).sum(axis=1)

C:\Users\Uw11\AppData\Local\Temp\ipykernel_9680\409095542.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_final['tg_total_intensity'] = df_tg_abs.sum(axis=1)
C:\Users\Uw11\AppData\Local\Temp\ipykernel_9680\409095542.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_final['tg_topic_std'] = df_tg_abs.std(axis=1)
C:\Users\Uw11\AppData\Local\Temp\ipykernel_9680\409095542.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_final['tg_topic_max'] = df_tg_abs.max(axis=1)
C:\Users\Uw11\AppData\Local\Temp\ipykernel_9680\409095542.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_final['tg_topic_entropy'] = -(df_tg_abs.div(df_tg_abs.sum(axis=1), axis=0) * np.log(df_tg_abs.div(df_tg_abs.sum(axis=1), axis=0) + 1e-9)).sum(axis=1)

In [36]:
df_final['tg_velocity_3h'] = (df_final.groupby('region_id')['tg_total_intensity'].diff(3).fillna(0))
df_final['tg_intensity_ema_6h'] = (df_final.groupby('region_id')['tg_total_intensity'].transform(lambda x: x.ewm(span=6).mean()))
df_final['tg_intensity_zscore'] = (df_final.groupby('region_id')['tg_total_intensity'].transform(lambda x: (x - x.rolling(24, min_periods=1).mean()) / (x.rolling(24, min_periods=1).std() + 1e-9)))

C:\Users\Uw11\AppData\Local\Temp\ipykernel_9680\3857173777.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_final['tg_velocity_3h'] = (df_final.groupby('region_id')['tg_total_intensity'].diff(3).fillna(0))
C:\Users\Uw11\AppData\Local\Temp\ipykernel_9680\3857173777.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_final['tg_intensity_ema_6h'] = (df_final.groupby('region_id')['tg_total_intensity'].transform(lambda x: x.ewm(span=6).mean()))
C:\Users\Uw11\AppData\Local\Temp\ipykernel_9680\3857173777.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_final['tg_intensity_zscore'] = (df_final.groupby('region_id')['tg_total_intensity'].transform(lambda x: (x - x.rolling(24, min_periods=1).mean()) / (x.rolling(24, min_periods=1).std() + 1e-9)))

In [37]:
df_final.sample(20)

,datetime_hour,region_id,city_latitude,city_longitude,day_temp,day_dew,day_humidity,day_precip,day_precipprob,day_precipcover,day_snow,day_snowdepth,day_windgust,day_windspeed,day_winddir,day_pressure,day_cloudcover,day_solarradiation,day_solarenergy,day_uvindex,day_moonphase,hour_temp,hour_feelslike,hour_humidity,hour_precip,hour_precipprob,hour_snow,hour_windgust,hour_windspeed,hour_winddir,hour_pressure,hour_cloudcover,hour_solarradiation,hour_solarenergy,hour_uvindex,day_conditions_simple_Clear,day_conditions_simple_Cloudy,day_conditions_simple_Rain,day_conditions_simple_Snow,hour_conditions_simple_Clear,hour_conditions_simple_Cloudy,hour_conditions_simple_Rain,hour_conditions_simple_Snow,year,month,day_of_week,hour,city_name,city_timezone,day_datetime,day_sunrise,day_sunset,hour_datetime,region_key,alarm_active,alarm_minutes_in_hour,alarm_lag_1,alarm_lag_3,alarm_lag_6,alarm_lag_12,alarms_in_last_24h,is_weekend,is_night,total_active_alarms_lag1,neighbour_alarms,hours_since_last_alarm,isw_topic_0,isw_topic_1,isw_topic_2,isw_topic_3,isw_topic_4,isw_topic_5,isw_topic_6,isw_topic_7,isw_topic_8,isw_topic_9,isw_topic_10,isw_topic_11,isw_topic_12,isw_topic_13,isw_topic_14,isw_topic_15,isw_topic_16,isw_topic_17,isw_topic_18,isw_topic_19,isw_topic_20,isw_topic_21,isw_topic_22,isw_topic_23,isw_topic_24,isw_topic_25,isw_topic_26,isw_topic_27,isw_topic_28,isw_topic_29,isw_topic_30,isw_topic_31,isw_topic_32,isw_topic_33,isw_topic_34,isw_topic_35,isw_topic_36,isw_topic_37,isw_topic_38,isw_topic_39,isw_topic_40,isw_topic_41,isw_topic_42,isw_topic_43,isw_topic_44,isw_topic_45,isw_topic_46,isw_topic_47,isw_topic_48,isw_topic_49,isw_topic_50,isw_topic_51,isw_topic_52,isw_topic_53,isw_topic_54,isw_topic_55,isw_topic_56,isw_topic_57,isw_topic_58,isw_topic_59,isw_topic_60,isw_topic_61,isw_topic_62,isw_topic_63,isw_topic_64,isw_topic_65,isw_topic_66,isw_topic_67,isw_topic_68,isw_topic_69,isw_topic_70,isw_topic_71,isw_topic_72,isw_topic_73,isw_topic_74,isw_topic_75,isw_topic_76,isw_topic_77,isw_topic_78,isw_topic_79,isw_topic_80,isw_topic_81,isw_topic_82,isw_topic_83,isw_topic_84,isw_topic_85,isw_topic_86,isw_topic_87,isw_topic_88,isw_topic_89,isw_topic_90,isw_topic_91,isw_topic_92,isw_topic_93,isw_topic_94,isw_topic_95,isw_topic_96,isw_topic_97,isw_topic_98,isw_topic_99,isw_topic_100,isw_topic_101,isw_topic_102,isw_topic_103,isw_topic_104,isw_topic_105,isw_topic_106,isw_topic_107,isw_topic_108,isw_topic_109,isw_topic_110,isw_topic_111,isw_topic_112,isw_topic_113,isw_topic_114,isw_topic_115,isw_topic_116,isw_topic_117,isw_topic_118,isw_topic_119,isw_topic_120,isw_topic_121,isw_topic_122,isw_topic_123,isw_topic_124,isw_topic_125,isw_topic_126,isw_topic_127,isw_topic_128,isw_topic_129,isw_topic_130,isw_topic_131,isw_topic_132,isw_topic_133,isw_topic_134,isw_topic_135,isw_topic_136,isw_topic_137,isw_topic_138,isw_topic_139,isw_topic_140,isw_topic_141,isw_topic_142,isw_topic_143,isw_topic_144,isw_topic_145,isw_topic_146,isw_topic_147,isw_topic_148,isw_topic_149,isw_total_intensity,isw_topic_std,isw_topic_max,isw_topic_mean,isw_velocity_24h,isw_intensity_ema,isw_topic_entropy,tg_topic_0,tg_topic_1,tg_topic_2,tg_topic_3,tg_topic_4,tg_topic_5,tg_topic_6,tg_topic_7,tg_topic_8,tg_topic_9,tg_topic_10,tg_topic_11,tg_topic_12,tg_topic_13,tg_topic_14,tg_topic_15,tg_topic_16,tg_topic_17,tg_topic_18,tg_topic_19,tg_topic_20,tg_topic_21,tg_topic_22,tg_topic_23,tg_topic_24,tg_topic_25,tg_topic_26,tg_topic_27,tg_topic_28,tg_topic_29,tg_topic_30,tg_topic_31,tg_topic_32,tg_topic_33,tg_topic_34,tg_topic_35,tg_topic_36,tg_topic_37,tg_topic_38,tg_topic_39,tg_topic_40,tg_topic_41,tg_topic_42,tg_topic_43,tg_topic_44,tg_topic_45,tg_topic_46,tg_topic_47,tg_topic_48,tg_topic_49,tg_topic_50,tg_topic_51,tg_topic_52,tg_topic_53,tg_topic_54,tg_topic_55,tg_topic_56,tg_topic_57,tg_topic_58,tg_topic_59,tg_topic_60,tg_topic_61,tg_topic_62,tg_topic_63,tg_topic_64,tg_topic_65,tg_topic_66,tg_topic_67,tg_topic_68,tg_topic_69,tg_topic_70,tg_topic_71,tg_topic_72,tg_topic_73,tg_topic_74,tg_topic_75,tg_topic_76,tg_topic_77,tg_topic_78,tg_topic_79,tg_topic_80,tg_topic_81,tg_topic_82,tg_topic_83,tg_topic_84,tg_topic_85,tg_topic_86,tg_topic_87,tg_topic_88,tg_topic_89,tg_topic_90,tg_topic_91,tg_topic_92,tg_topic_93,tg_topic_94,tg_topic_95,tg_topic_96,tg_topic_97,tg_topic_98,tg_topic_99,tg_topic_100,tg_topic_101,tg_topic_102,tg_topic_103,tg_topic_104,tg_topic_105,tg_topic_106,tg_topic_107,tg_topic_108,tg_topic_109,tg_topic_110,tg_topic_111,tg_topic_112,tg_topic_113,tg_topic_114,tg_topic_115,tg_topic_116,tg_topic_117,tg_topic_118,tg_topic_119,tg_topic_120,tg_topic_121,tg_topic_122,tg_topic_123,tg_topic_124,tg_topic_125,tg_topic_126,tg_topic_127,tg_topic_128,tg_topic_129,tg_topic_130,tg_topic_131,tg_topic_132,tg_topic_133,tg_topic_134,tg_topic_135,tg_topic_136,tg_topic_137,tg_topic_138,tg_topic_139,tg_topic_140,tg_topic_141,tg_topic_142,tg_topic_143,tg_topic_144,tg_topic_145,tg_topic_146,tg_topic_147,tg_topic_148,tg_topic_149,tg_topic_150,tg_topic_151,tg_topic_152,tg_topic_153,tg_topic_154,tg_topic_155,tg_topic_156,tg_topic_157,tg_topic_158,tg_topic_159,tg_topic_160,tg_topic_161,tg_topic_162,tg_topic_163,tg_topic_164,tg_topic_165,tg_topic_166,tg_topic_167,tg_topic_168,tg_topic_169,tg_topic_170,tg_topic_171,tg_topic_172,tg_topic_173,tg_topic_174,tg_topic_175,tg_topic_176,tg_topic_177,tg_topic_178,tg_topic_179,tg_topic_180,tg_topic_181,tg_topic_182,tg_topic_183,tg_topic_184,tg_topic_185,tg_topic_186,tg_topic_187,tg_topic_188,tg_topic_189,tg_topic_190,tg_topic_191,tg_topic_192,tg_topic_193,tg_topic_194,tg_topic_195,tg_topic_196,tg_topic_197,tg_topic_198,tg_topic_199,tg_topic_200,tg_topic_201,tg_topic_202,tg_topic_203,tg_topic_204,tg_topic_205,tg_topic_206,tg_topic_207,tg_topic_208,tg_topic_209,tg_topic_210,tg_topic_211,tg_topic_212,tg_topic_213,tg_topic_214,tg_topic_215,tg_topic_216,tg_topic_217,tg_topic_218,tg_topic_219,tg_topic_220,tg_topic_221,tg_topic_222,tg_topic_223,tg_topic_224,tg_topic_225,tg_topic_226,tg_topic_227,tg_topic_228,tg_topic_229,tg_topic_230,tg_topic_231,tg_topic_232,tg_topic_233,tg_topic_234,tg_topic_235,tg_topic_236,tg_topic_237,tg_topic_238,tg_topic_239,tg_topic_240,tg_topic_241,tg_topic_242,tg_topic_243,tg_topic_244,tg_topic_245,tg_topic_246,tg_topic_247,tg_topic_248,tg_topic_249,tg_total_intensity,tg_topic_std,tg_topic_max,tg_topic_entropy,tg_velocity_3h,tg_intensity_ema_6h,tg_intensity_zscore
462778,2023-08-10 15:00:00,20,50.00420,36.23580,21.4,14.7,67.5,2.600,100.0,20.83,0.0,0.0,39.6,25.2,32.8,1018.9,56.9,209.4,18.0,8.0,0.79,27.0,27.2,47.81,0.0,0.0,0.0,38.2,21.6,20.0,1019.0,85.9,470.5,1.7,5.0,False,False,True,False,False,True,False,False,2023,8,3,15,Kharkiv,Europe/Kiev,2023-08-10,05:16:39,20:03:25,15:00:00,Харківська,1,22.266667,1.0,0.0,0.0,1.0,11.0,0,0,4.0,2.0,0,0.777505,-0.138907,-0.025887,-0.180642,-0.167206,0.131243,-0.027763,0.188815,0.138356,-0.036224,0.144650,0.001299,-0.166310,-0.100288,0.041211,-0.147603,0.020126,0.029465,0.054699,-0.030873,0.018531,-0.037268,0.032543,0.027735,0.035209,0.019666,-0.003414,0.027639,-0.011486,0.021037,-0.022192,0.021060,-0.043080,-0.033426,-0.032601,0.002242,0.021169,0.009479,0.002969,-0.016542,-0.004694,0.004403,-0.011949,-0.008355,0.004402,0.031280,0.030452,0.040013,-0.018539,-0.025904,0.013548,0.021796,-0.008538,-0.008952,0.010219,0.002758,0.024475,0.017862,-0.035621,0.045011,-0.005246,0.012306,0.024421,-0.013303,0.007215,0.026211,0.006931,0.032405,0.000809,0.008211,0.002013,0.014143,0.009842,-0.024386,0.004196,0.030238,-0.000542,-0.013319,-0.003707,-0.016209,-0.007128,0.020699,0.015210,-0.022016,-0.006636,-0.015103,0.001990,-0.016375,-0.035389,-0.012328,-0.018197,0.024767,0.000383,-0.025894,-0.033647,0.008879,0.011223,0.003893,0.003520,-0.004856,0.003529,-0.013998,-0.013283,-0.008557,-0.005869,0.007662,-0.020179,-0.016784,0.004163,0.017251,0.002265,-0.002407,-0.003929,0.060605,-0.007316,0.008230,0.007256,0.021873,0.005986,-0.023567,0.001337,0.008484,0.000120,-0.019374,0.003678,-0.024506,-0.010751,0.011235,-0.005115,0.003576,-0.000356,-0.004393,0.021464,0.017367,0.008300,0.000645,0.018332,0.001557,-0.009836,-0.025147,-0.000308,-0.014010,0.014565,0.001420,0.009733,0.013306,-0.006277,-0.006272,-0.006473,-0.014193,4.437749,0.071397,0.777505,0.029585,-1.055749,4.706257,4.046917,0.008807,-0.002902,0.024016,0.008612,-0.017437,0.038990,-0.052245,0.062293,0.011561,-0.020127,-0.019789,0.010344,-0.004155,-0.006336,-0.030309,0.037013,-0.023512,0.026205,0.049145,-0.039908,-0.014081,-0.022688,0.017500,-0.010067,-0.007168,0.014333,0.012025,0.011649,0.019597,0.041050,0.053861,-0.004572,-0.001886,-0.014566,0.003839,0.058591,-0.015873,0.037336,0.011086,-0.018732,-0.052835,-0.032274,0.025674,-0.004414,0.005787,0.017185,0.041590,-0.034995,0.026539,0.014341,-0.009785,0.011969,0.004421,0.013107,0.032115,0.006341,0.001890,-0.004916,-0.016644,0.003647,-0.004041,-0.000325,0.015452,-0.000915,0.006614,0.001162,0.017431,0.022917,-0.003348,-0.005128,0.005222,-0.004113,-0.002986,0.016041,0.034556,0.006419,-0.009902,0.006140,-0.024544,-0.011305,0.001802,-0.008474,-0.009203,0.000448,-0.004234,0.008821,0.008935,0.011173,-0.003072,-0.015933,-0.015739,0.022288,0.001250,-0.009943,-0.003017,-0.003979,0.032044,0.003294,-0.016011,0.009597,-0.011918,-0.011754,0.021887,0.007886,-0.024698,0.005781,-0.004469,-0.004072,-0.007561,-0.008215,-0.012306,0.012698,0.016923,-0.005588,-0.009195,0.002819,0.009257,0.009428,-0.019742,0.004788,0.007459,-0.001313,-0.014163,0.039272,-0.029795,0.018345,0.005073,-0.004706,-0.006790,-0.011577,-0.014377,0.009482,0.023800,0.030098,-0.026642,0.049560,-0.016728,-0.028682,0.036998,-0.043987,-0.001238,-0.010825,-0.026549,-0.022999,0.015994,0.008938,-0.018612,0.018209,0.017231,0.044242,0.001670,-0.006355,0.008136,0.004458,-0.017094,-0.000971,0.020451,0.003127,-0.011747,-0.028808,0.003247,0.002578,0.015776,-0.005573,-0.023681,-0.005668,-0.005661,0.010855,0.018502,0.006678,0.001953,-0.011768,2.020487e-03,-0.014351,0.001480,-0.007609,-0.003993,0.003887,-0.006435,-0.005258,-0.002384,-0.038489,0.008379,0.010904,0.015100,0.004234,-0.010174,-0.003959,0.023885,0.009265,0.024207,0.002830,-0.030101,0.006802,0.005792,-0.027915,0.030633,0.010779,-0.005911,-0.008721,-0.011941,-0.004115,-0.001920,-0.012756,0.004813,-0.006694,0.007683,-0.022719,-0.006793,0.013905,0.019084,-0.000214,0.023099,-0.018569,0.016576,0.033143,-0.009002,-0.003556,-0.012795,0.034971,-0.016304,-0.005984,0.033741,0.007964,0.020303,0.014180,-0.014253,0.008574,0.022962,-0.022648,-0.010329,0.023056,0.006431,0.003038,0.009532,-0.016121,-0.016689,0.021322,-0.031089,0.008408,-0.002484,-0.038383,0.000107,0.033701,-0.009056,0.031665,-0.000748,-0.004763,0.001037,-0.018979,3.705605,0.012379,0.062293,5.202382,0.178726,3.599273,0.020715
531863,2022-06-06 12:00:00,23,49.44070,32.06370,20.1,10.6,58.1,0.000,0.0,0.00,0.0,0.0,29.9,16.6,24.5,1017.2,23.7,321.2,27.5,9.0,0.22,23.2,23.2,36.72,0.0,0.0,0.0,28.1,15.8,36.6,1018.0,29.3,862.0,3.1,9.0,False,True,False,False,False,True,False,False,2022,6,0,12,Cherkasy,Europe/Kiev,2022-06-06,04:47:25,20:53:56,12:00:00,Черкаська,1,60.000000,1.0,0.0,0.0,0.0,4.0,0,0,12.0,3.0,0,0.666286,-0.204222,0.289810,0.048533,-0.043955,0.077198,0.071817,-0.132420,-0.043867,-0.012734,-0.088759,0.249428,-0.001265,-0.006098,-0.083075,-0.058482,-0.033996,0.025043,-0.091968,-0.125986,0.050422,-0.022644,-0.025620,0.038247,-0.014251,0.043473,0.142305,0.049681,-0.025675,0.012464,0.019193,-0.022003,0.016476,-0.037211,0.014081,-0.017196,-0.003131,-0.002555,0.016763,0.025523,-0.010520,0.025063,0.025766,0.020375,0.074357,-0.063298,-0.040986,0.059821,-0.023711,0.008354,-0.054951,0.010137,0.004268,-0.002935,-0.011030,-0.069976,-0.003747,-0.049369,-0.038968,-0.024828,-0.023944,-0.015682,-0.072222,0.017708,-0.023090,-0.044524,0.036748,-0.038703,0.030357,-0.033075,-0.018126,-0.012939,-0.055204,-0.046808,0.027542,-0.041063,-0.041263,-0.024114,-0.016763,0.006104,-0.015611,-0.030535,-0.049807,-0.005421,0.029391,-0.045268,-0.041321,-0.007576,0.027435,-0.051936,0.034517,-0.035612,-0.016070,0.029720,-0.011334,0.000369,-0.013164,-0.012642,-0.016340,-0.001959,-0.004397,0.001508,0.025774,0.051762,-0.012765,0.009743,0.029409,-0.012951,0.041200,0.001572,-0.000091,0.005873,0.013661,-0.010809,-0.020009,-0.004266,0.012118,0.029545,-0.012526,0.015307,-0.056042,0.003593,-0.020777,0.036580,0.037280,-0.012821,0.005967,0.027399,0.038314,-0.043242,-0.020898,-0.008108,-0.000272,0.029762,0.003108,-0.027321,-0.024709,-0.023074,-0.013671,0.001536,-0.031067,0.006185,-0.008187,-0.064111,0.009537,0.017172,0.019063,-0.007155,-0.011120,0.009536,5.611210,0.065309,0.666286,0.037408,0.781113,5.327591,4.362482,0.013832,-0.001944,0.039638,0.007895,-0.028478,0.069125,-0.101554,0.117221,0.025190,-0.039518,-0.053943,0.005335,-0.015155,0.003209,0.005456,-0.016537,0.001174,-0.013642,-0.012609,0.018161,-0.017185,0.046560,0.005306,-0.050701,-0.014212,0.027838,0.018025,0.014582,0.006699,0.025380,0.048738,-0.005241,0.001275,0.016432,-0.015735,0.001144,0.009966,0.006425,-0.002892,0.005127,-0.000686,0.006614,0.003779,0.010561,-0.001667,-0.001324,-0.004911,-0.007937,0.000654,-0.007467,-0.018746,0.022771,0.000065,-0.007846,0.001013,-0.005472,0.010446,-0.011529,-0.002317,-0.014939,0.023426,-0.014715,-0.010198,-0.008785,-0.012195,-0.016474,-0.020013,-0.018365,0.000016,-0.015520,0.016365,0.009648,0.021630,-0.006836,-0.018417,0.002007,-0.000390,-0.004350,0.015077,0.005382,0.008125,0.011436,0.009334,-0.003359,-0.011316,0.019332,-0.002283,-0.023748,-0.018195,0.008063,0.007456,0.005639,-0.004701,0.016767,0.005396,-0.007945,0.007152,0.001131,-0.007088,-0.002270,0.006393,-0.005915,0.000363,0.041936,-0.008971,-0.000430,0.018721,0.012550,-0.026120,0.059521,-0.012078,-0.008110,-0.005851,-0.044934,0.013427,-0.019890,0.003163,0.010632,-0.003163,-0.020928,0.027271,0.026243,0.022351,0.029977,0.003802,-0.058385,0.013718,-0.010158,-0.000827,-0.005907,-0.028815,0.001264,0.005926,-0.015507,0.007487,0.025062,0.007910,-0.001314,0.010866,-0.024801,-0.024663,0.003296,0.012710,0.007892,-0.006697,-0.025460,-0.008214,-0.010232,-0.014323,-0.036510,0.020001,0.024825,-0.047919,0.025161,0.034171,0.013688,0.003997,0.004188,0.016116,0.003597,0.009800,-0.017424,-0.016432,-0.014697,-0.037487,0.005308,0.003425,-0.008392,-0.016385,-0.005906,-0.016006,0.025121,-3.476568e-03,-0.028182,-0.001131,0.019903,-0.008261,0.023530,0.002830,-0.021126,0.006782,-0.002299,-0.018490,0.018869,0.023893,-0.035514,-0.008191,-0.004208,-0.014287,0.020863,0.011031,-0.020412,0.026841,-0.007285,-0.009804,0.017959,-0.009667,-0.001920,0.005546,0.000430,-0.016443,-0.003437,0.035259,-0.032427,0.020564,-0.006690,0.008724,-0.015430,0.013171,-0.004928,0.026029,0.010920,0.008502,-0.032250,-0.013868,-0.002766,-0.021701,0.013667,0.028030,-0.046257,0.008535,0.009617,-0.032757,-0.004351,-0.016056,0.028817,0.012217,-0.021932,0.016080,-0.007460,-0.000238,0.004696,-0.005396,-0.008948,-0.023696,0.032749,-0.004775,-0.012799,-0.008156,0.006907,-0.003229,-0.014533,0.007690,0.011594,0.008183,0.009661,-0.014985,-0.013506,0.024627,-0.032494,3.801569,0.014821,0.117221,5.152890,0.324338,3.450200,0.462444
109676,2022-07-31 09:00:00,6,50.25360,28.66540,23.0,13.2,55.8,0.000,0.0,0.00,0.0,0.0,40.3,20.9,143.8,1012.5,95.3,98.8,8.6,5.0,0.07,22.7,22.7,58.69,0.0,0.0,0.0,30.2,10.8,140.0,1013.0,100.0,120.0,0.4,1.0,False,True,False,False,False,True,False,False,2022,7,6,9,Zhytomyr,Europe/Kiev,2022-07-31,05:32:04,20:50:34,09:00:00,Житомирська,0,0.000000,0.0,0.0,0.0,0.0,1.0,1,0,1.0,0.0,23,0.735527,-0.196909,0.250230,-0.033559,-0.109231,0.147559,0.081957,-0.111905,-0.012615,0.040132,-0.128833,-0.210844,0.047575,-0.028954,-0.011933,0.015412,-0.067687,0.064041,-0.091705,0.002977,-0.001092,-0.050386,0.025040,-0.087966,0.081171,-0.005205,-0.074750,-0.070596,0.027545,0.004240,0.014254,0.009685,0.021378,0.037002,0.019049,0.001399,-0.011031,0.014583,0.020781,-0.003056,0.024128,-0.000934,-0.000164,-0.017132,-0.055099,0.024231,-0.009253,-0.019397,0.025699,-0.043725,0.010653,0.002555,-0.007374,0.031718,0.031941,-0.008632,0.010309,-0.023235,0.011731,0.021550,-0.019087,-0.005345,0.008696,0.008361,-0.005424,0.013591,-0.043374,-0.048816,0.005376,0.017996,-0.028047,-0.006692,0.025659,-0.022558,0.022694,-0.002711,-0.017404,0.001692,0.018158,-0.022595,-0.008476,0.008255,0.011555,0.026293,-0.005990,0.054788,0.008711,-0.019242,-0.003227,-0.016454,0.001392,0.009901,0.024425,-0.015415,-0.015615,-0.004405,-0.007873,-0.009967,-0.003538,-0.033816,0.036342,-0.006517,-0.026144,-0.009003,0.033432,-0.021131,0.039005,-0.008941,-0.030072,0.020953,0.009500,-0.013601,-0.007916,-0.058173,-0.005783,0.006940,-0.028887,0.008980,-0.000539,-0.020169,0.014815,0.005618,-0.020590,-0.005281,0.011703,0.017384,-0.002281,-0.015603,-0.024328,0.007482,0.030376,0.000203,-0.010903,0.037334,-0.016629,-0.026920,-0.017624,-0.006404,-0.025150,0.011685,-0.039308,-0.016439,0.011356,-0.010074,0.021322,-0.007578,0.018039,-0.025497,0.013682,0.016749,4.863246,0.068738,0.735527,0.032422,-0.506912,5.079576,4.199137,0.021759,-0.009257,0.039106,0.006030,-0.012879,0.056318,-0.083405,0.094476,0.030048,-0.034991,0.132656,-0.140037,0.058229,0.009845,-0.008563,-0.002356,-0.017830,0.002713,0.047463,-0.022883,0.004460,-0.023219,0.011282,-0.035032,-0.011782,0.026472,0.013272,0.038930,0.022763,0.031615,0.063382,-0.002836,-0.011212,0.009977,-0.028269,0.010440,0.015145,0.010024,0.010570,-0.017980,-0.002870,0.006917,-0.013015,0.016852,-0.004872,0.000343,-0.013312,0.001989,-0.008059,-0.003572,-0.017273,-0.001711,-0.002264,0.014200,0.011278,0.012319,0.011515,0.023859,-0.020787,0.017302,-0.029193,-0.028903,0.004606,0.043981,0.027566,-0.003024,-0.010384,0.022774,-0.006333,-0.003926,-0.010970,0.014273,-0.006614,0.003766,0.024132,-0.014415,-0.011983,0.006424,-0.001651,-0.007139,0.025782,0.003427,-0.010649,0.013813,-0.027599,0.015128,0.010897,-0.001576,0.011830,-0.019394,-0.026063,0.019459,-0.029186,-0.006051,0.007884,-0.002468,0.021725,0.005684,0.000838,-0.011298,-0.006951,-0.002240,0.001048,-0.025629,-0.007918,0.003955,-0.013563,-0.022057,0.004136,0.015717,0.031516,-0.065818,0.030964,-0.040390,-0.029019,0.022378,-0.020620,0.002687,0.038678,0.003302,0.032001,0.034137,0.001122,0.040345,0.002378,0.034132,-0.019430,0.003087,-0.005335,-0.020806,-0.012844,-0.000800,0.007481,-0.005041,0.001866,0.006211,0.016897,0.016847,-0.004813,0.001836,-0.011701,0.005024,0.002609,-0.006665,0.012239,-0.010425,-0.012168,0.006623,-0.005550,-0.025804,0.025494,0.002626,-0.026716,0.012949,-0.000888,-0.000412,-0.019868,0.005176,-0.000755,-0.008546,0.011852,-0.014698,-0.014349,-0.009790,0.003372,-0.015190,-0.002212,-0.000500,-0.010718,-0.008440,0.002336,-0.005411,2.396250e-02,-0.007495,0.002687,0.016872,-0.026991,-0.014204,0.010504,0.020806,0.018250,-0.022315,0.008597,0.004201,-0.008547,-0.006052,0.009310,-0.005219,0.011527,-0.001266,0.006693,0.003484,-0.007891,0.001278,-0.003625,-0.010056,-0.006706,-0.000104,-0.005973,-0.007231,0.002853,-0.005015,-0.002035,0.001317,0.005125,-0.004884,-0.001193,0.003162,-0.004207,0.009973,0.004085,0.010388,-0.005498,-0.012659,-0.001899,-0.009431,-0.000141,0.003184,0.005714,-0.006369,0.009300,-0.028454,-0.010350,0.007045,-0.007072,0.003758,-0.018381,0.018293,-0.014836,0.003488,-0.014418,-0.005111,-0.010686,-0.010202,0.011350,0.008298,-0.002229,-0.001267,0.017806,0.003378,-0.009191,0.003441,0.000804,-0.002902,0.004598,-0.016316,-0.003835,0.000644,-0.005715,-0.000984,3.568856,0.017405,0.140037,5.037391,3.568856,2.763382,0.825262

# ТУТ БУДЕ EDA

## Weather, ISW, Telegram shift for further models trainings

In [38]:
df_to_train = df_final.copy()
df_to_train = df_to_train.sort_values(['region_id', 'datetime_hour'])

In [39]:
# delete unnessecary columns
columns_to_delete = ['city_latitude', 'city_longitude', 'day_temp', 'day_dew', 'day_humidity', 'day_precip', 'day_precipprob', 'day_precipcover', 
                     'day_snow', 'day_snowdepth', 'day_windgust', 'day_windspeed', 'day_winddir', 'day_pressure', 'day_cloudcover', 'day_solarradiation',
                     'day_solarenergy', 'day_uvindex', 'day_moonphase', 'day_conditions_simple_Clear', 'day_conditions_simple_Cloudy', 'day_conditions_simple_Rain',
                     'day_conditions_simple_Snow', 'year', 'month', 'hour', 'day_of_week', 'city_timezone', 'day_datetime', 'hour_datetime', 'region_key']
df_to_train = df_to_train.drop(columns=columns_to_delete)

In [40]:
isw_cols = [c for c in df_to_train.columns if 'isw_' in c]
df_to_train[isw_cols] = df_to_train.groupby('region_id')[isw_cols].shift(24).fillna(0)

In [41]:
df_to_train.head()

,datetime_hour,region_id,hour_temp,hour_feelslike,hour_humidity,hour_precip,hour_precipprob,hour_snow,hour_windgust,hour_windspeed,hour_winddir,hour_pressure,hour_cloudcover,hour_solarradiation,hour_solarenergy,hour_uvindex,hour_conditions_simple_Clear,hour_conditions_simple_Cloudy,hour_conditions_simple_Rain,hour_conditions_simple_Snow,city_name,day_sunrise,day_sunset,alarm_active,alarm_minutes_in_hour,alarm_lag_1,alarm_lag_3,alarm_lag_6,alarm_lag_12,alarms_in_last_24h,is_weekend,is_night,total_active_alarms_lag1,neighbour_alarms,hours_since_last_alarm,isw_topic_0,isw_topic_1,isw_topic_2,isw_topic_3,isw_topic_4,isw_topic_5,isw_topic_6,isw_topic_7,isw_topic_8,isw_topic_9,isw_topic_10,isw_topic_11,isw_topic_12,isw_topic_13,isw_topic_14,isw_topic_15,isw_topic_16,isw_topic_17,isw_topic_18,isw_topic_19,isw_topic_20,isw_topic_21,isw_topic_22,isw_topic_23,isw_topic_24,isw_topic_25,isw_topic_26,isw_topic_27,isw_topic_28,isw_topic_29,isw_topic_30,isw_topic_31,isw_topic_32,isw_topic_33,isw_topic_34,isw_topic_35,isw_topic_36,isw_topic_37,isw_topic_38,isw_topic_39,isw_topic_40,isw_topic_41,isw_topic_42,isw_topic_43,isw_topic_44,isw_topic_45,isw_topic_46,isw_topic_47,isw_topic_48,isw_topic_49,isw_topic_50,isw_topic_51,isw_topic_52,isw_topic_53,isw_topic_54,isw_topic_55,isw_topic_56,isw_topic_57,isw_topic_58,isw_topic_59,isw_topic_60,isw_topic_61,isw_topic_62,isw_topic_63,isw_topic_64,isw_topic_65,isw_topic_66,isw_topic_67,isw_topic_68,isw_topic_69,isw_topic_70,isw_topic_71,isw_topic_72,isw_topic_73,isw_topic_74,isw_topic_75,isw_topic_76,isw_topic_77,isw_topic_78,isw_topic_79,isw_topic_80,isw_topic_81,isw_topic_82,isw_topic_83,isw_topic_84,isw_topic_85,isw_topic_86,isw_topic_87,isw_topic_88,isw_topic_89,isw_topic_90,isw_topic_91,isw_topic_92,isw_topic_93,isw_topic_94,isw_topic_95,isw_topic_96,isw_topic_97,isw_topic_98,isw_topic_99,isw_topic_100,isw_topic_101,isw_topic_102,isw_topic_103,isw_topic_104,isw_topic_105,isw_topic_106,isw_topic_107,isw_topic_108,isw_topic_109,isw_topic_110,isw_topic_111,isw_topic_112,isw_topic_113,isw_topic_114,isw_topic_115,isw_topic_116,isw_topic_117,isw_topic_118,isw_topic_119,isw_topic_120,isw_topic_121,isw_topic_122,isw_topic_123,isw_topic_124,isw_topic_125,isw_topic_126,isw_topic_127,isw_topic_128,isw_topic_129,isw_topic_130,isw_topic_131,isw_topic_132,isw_topic_133,isw_topic_134,isw_topic_135,isw_topic_136,isw_topic_137,isw_topic_138,isw_topic_139,isw_topic_140,isw_topic_141,isw_topic_142,isw_topic_143,isw_topic_144,isw_topic_145,isw_topic_146,isw_topic_147,isw_topic_148,isw_topic_149,isw_total_intensity,isw_topic_std,isw_topic_max,isw_topic_mean,isw_velocity_24h,isw_intensity_ema,isw_topic_entropy,tg_topic_0,tg_topic_1,tg_topic_2,tg_topic_3,tg_topic_4,tg_topic_5,tg_topic_6,tg_topic_7,tg_topic_8,tg_topic_9,tg_topic_10,tg_topic_11,tg_topic_12,tg_topic_13,tg_topic_14,tg_topic_15,tg_topic_16,tg_topic_17,tg_topic_18,tg_topic_19,tg_topic_20,tg_topic_21,tg_topic_22,tg_topic_23,tg_topic_24,tg_topic_25,tg_topic_26,tg_topic_27,tg_topic_28,tg_topic_29,tg_topic_30,tg_topic_31,tg_topic_32,tg_topic_33,tg_topic_34,tg_topic_35,tg_topic_36,tg_topic_37,tg_topic_38,tg_topic_39,tg_topic_40,tg_topic_41,tg_topic_42,tg_topic_43,tg_topic_44,tg_topic_45,tg_topic_46,tg_topic_47,tg_topic_48,tg_topic_49,tg_topic_50,tg_topic_51,tg_topic_52,tg_topic_53,tg_topic_54,tg_topic_55,tg_topic_56,tg_topic_57,tg_topic_58,tg_topic_59,tg_topic_60,tg_topic_61,tg_topic_62,tg_topic_63,tg_topic_64,tg_topic_65,tg_topic_66,tg_topic_67,tg_topic_68,tg_topic_69,tg_topic_70,tg_topic_71,tg_topic_72,tg_topic_73,tg_topic_74,tg_topic_75,tg_topic_76,tg_topic_77,tg_topic_78,tg_topic_79,tg_topic_80,tg_topic_81,tg_topic_82,tg_topic_83,tg_topic_84,tg_topic_85,tg_topic_86,tg_topic_87,tg_topic_88,tg_topic_89,tg_topic_90,tg_topic_91,tg_topic_92,tg_topic_93,tg_topic_94,tg_topic_95,tg_topic_96,tg_topic_97,tg_topic_98,tg_topic_99,tg_topic_100,tg_topic_101,tg_topic_102,tg_topic_103,tg_topic_104,tg_topic_105,tg_topic_106,tg_topic_107,tg_topic_108,tg_topic_109,tg_topic_110,tg_topic_111,tg_topic_112,tg_topic_113,tg_topic_114,tg_topic_115,tg_topic_116,tg_topic_117,tg_topic_118,tg_topic_119,tg_topic_120,tg_topic_121,tg_topic_122,tg_topic_123,tg_topic_124,tg_topic_125,tg_topic_126,tg_topic_127,tg_topic_128,tg_topic_129,tg_topic_130,tg_topic_131,tg_topic_132,tg_topic_133,tg_topic_134,tg_topic_135,tg_topic_136,tg_topic_137,tg_topic_138,tg_topic_139,tg_topic_140,tg_topic_141,tg_topic_142,tg_topic_143,tg_topic_144,tg_topic_145,tg_topic_146,tg_topic_147,tg_topic_148,tg_topic_149,tg_topic_150,tg_topic_151,tg_topic_152,tg_topic_153,tg_topic_154,tg_topic_155,tg_topic_156,tg_topic_157,tg_topic_158,tg_topic_159,tg_topic_160,tg_topic_161,tg_topic_162,tg_topic_163,tg_topic_164,tg_topic_165,tg_topic_166,tg_topic_167,tg_topic_168,tg_topic_169,tg_topic_170,tg_topic_171,tg_topic_172,tg_topic_173,tg_topic_174,tg_topic_175,tg_topic_176,tg_topic_177,tg_topic_178,tg_topic_179,tg_topic_180,tg_topic_181,tg_topic_182,tg_topic_183,tg_topic_184,tg_topic_185,tg_topic_186,tg_topic_187,tg_topic_188,tg_topic_189,tg_topic_190,tg_topic_191,tg_topic_192,tg_topic_193,tg_topic_194,tg_topic_195,tg_topic_196,tg_topic_197,tg_topic_198,tg_topic_199,tg_topic_200,tg_topic_201,tg_topic_202,tg_topic_203,tg_topic_204,tg_topic_205,tg_topic_206,tg_topic_207,tg_topic_208,tg_topic_209,tg_topic_210,tg_topic_211,tg_topic_212,tg_topic_213,tg_topic_214,tg_topic_215,tg_topic_216,tg_topic_217,tg_topic_218,tg_topic_219,tg_topic_220,tg_topic_221,tg_topic_222,tg_topic_223,tg_topic_224,tg_topic_225,tg_topic_226,tg_topic_227,tg_topic_228,tg_topic_229,tg_topic_230,tg_topic_231,tg_topic_232,tg_topic_233,tg_topic_234,tg_topic_235,tg_topic_236,tg_topic_237,tg_topic_238,tg_topic_239,tg_topic_240,tg_topic_241,tg_topic_242,tg_topic_243,tg_topic_244,tg_topic_245,tg_topic_246,tg_topic_247,tg_topic_248,tg_topic_249,tg_total_intensity,tg_topic_std,tg_topic_max,tg_topic_entropy,tg_velocity_3h,tg_intensity_ema_6h,tg_intensity_zscore
0,2022-02-24 00:00:00,2,2.1,-0.5,91.76,0.0,0.0,0.0,16.6,8.6,279.6,1021.0,91.1,0.0,0.1,0.0,False,True,False,False,Vinnytsia,06:58:49,17:40:52,0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0.0,0.0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-0.0,0.0,0.0,NaN
1,2022-02-24 00:00:00,2,2.1,-0.5,91.76,0.0,0.0,0.0,16.6,8.6,279.6,1021.0,91.1,0.0,0.1,0.0,False,True,False,False,Vinnytsia,06:58:49,17:40:52,0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0.0,0.0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-0.0,0.0,0.0,0.0
3,2022-02-24 01:00:00,2,2.1,-0.4,89.80,0.0,0.0,0.0,16.6,8.3,289.2,1021.0,97.9,0.0,0.1,0.0,False,True,False,False,Vinnytsia,06:58:49,17:40:52,0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0.0,0.0,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-0.0,0.0,0.0,0.0
2,2022-02-24 01:00:00,2,2.1,-0.4,89.80,0.0,0.0,0.0,16.6,8.3,289.2,1021.0,97.9,0.0,0.1,0.0,False,True,False,False,Vinnytsia,06:58:49,17:40:52,0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0.0,0.0,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-0.0,0.0,0.0,0.0
5,2022-02-24 02:00:00,2,2.0,-0.3,90.44,0.0,0.0,0.0,27.7,7.6,287.6,1021.0,98.2,0.0,0.1,0.0,False,True,False,False,Vinnytsia,06:58:49,17:40:52,0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0.0,0.0,3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-0.0,0.0,0.0,0.0

In [42]:
tg_cols = [c for c in df_to_train.columns if 'tg_' in c]
df_to_train[tg_cols] = df_to_train.groupby('region_id')[tg_cols].shift(1).fillna(0)

In [43]:
df_to_train.head(5)

,datetime_hour,region_id,hour_temp,hour_feelslike,hour_humidity,hour_precip,hour_precipprob,hour_snow,hour_windgust,hour_windspeed,hour_winddir,hour_pressure,hour_cloudcover,hour_solarradiation,hour_solarenergy,hour_uvindex,hour_conditions_simple_Clear,hour_conditions_simple_Cloudy,hour_conditions_simple_Rain,hour_conditions_simple_Snow,city_name,day_sunrise,day_sunset,alarm_active,alarm_minutes_in_hour,alarm_lag_1,alarm_lag_3,alarm_lag_6,alarm_lag_12,alarms_in_last_24h,is_weekend,is_night,total_active_alarms_lag1,neighbour_alarms,hours_since_last_alarm,isw_topic_0,isw_topic_1,isw_topic_2,isw_topic_3,isw_topic_4,isw_topic_5,isw_topic_6,isw_topic_7,isw_topic_8,isw_topic_9,isw_topic_10,isw_topic_11,isw_topic_12,isw_topic_13,isw_topic_14,isw_topic_15,isw_topic_16,isw_topic_17,isw_topic_18,isw_topic_19,isw_topic_20,isw_topic_21,isw_topic_22,isw_topic_23,isw_topic_24,isw_topic_25,isw_topic_26,isw_topic_27,isw_topic_28,isw_topic_29,isw_topic_30,isw_topic_31,isw_topic_32,isw_topic_33,isw_topic_34,isw_topic_35,isw_topic_36,isw_topic_37,isw_topic_38,isw_topic_39,isw_topic_40,isw_topic_41,isw_topic_42,isw_topic_43,isw_topic_44,isw_topic_45,isw_topic_46,isw_topic_47,isw_topic_48,isw_topic_49,isw_topic_50,isw_topic_51,isw_topic_52,isw_topic_53,isw_topic_54,isw_topic_55,isw_topic_56,isw_topic_57,isw_topic_58,isw_topic_59,isw_topic_60,isw_topic_61,isw_topic_62,isw_topic_63,isw_topic_64,isw_topic_65,isw_topic_66,isw_topic_67,isw_topic_68,isw_topic_69,isw_topic_70,isw_topic_71,isw_topic_72,isw_topic_73,isw_topic_74,isw_topic_75,isw_topic_76,isw_topic_77,isw_topic_78,isw_topic_79,isw_topic_80,isw_topic_81,isw_topic_82,isw_topic_83,isw_topic_84,isw_topic_85,isw_topic_86,isw_topic_87,isw_topic_88,isw_topic_89,isw_topic_90,isw_topic_91,isw_topic_92,isw_topic_93,isw_topic_94,isw_topic_95,isw_topic_96,isw_topic_97,isw_topic_98,isw_topic_99,isw_topic_100,isw_topic_101,isw_topic_102,isw_topic_103,isw_topic_104,isw_topic_105,isw_topic_106,isw_topic_107,isw_topic_108,isw_topic_109,isw_topic_110,isw_topic_111,isw_topic_112,isw_topic_113,isw_topic_114,isw_topic_115,isw_topic_116,isw_topic_117,isw_topic_118,isw_topic_119,isw_topic_120,isw_topic_121,isw_topic_122,isw_topic_123,isw_topic_124,isw_topic_125,isw_topic_126,isw_topic_127,isw_topic_128,isw_topic_129,isw_topic_130,isw_topic_131,isw_topic_132,isw_topic_133,isw_topic_134,isw_topic_135,isw_topic_136,isw_topic_137,isw_topic_138,isw_topic_139,isw_topic_140,isw_topic_141,isw_topic_142,isw_topic_143,isw_topic_144,isw_topic_145,isw_topic_146,isw_topic_147,isw_topic_148,isw_topic_149,isw_total_intensity,isw_topic_std,isw_topic_max,isw_topic_mean,isw_velocity_24h,isw_intensity_ema,isw_topic_entropy,tg_topic_0,tg_topic_1,tg_topic_2,tg_topic_3,tg_topic_4,tg_topic_5,tg_topic_6,tg_topic_7,tg_topic_8,tg_topic_9,tg_topic_10,tg_topic_11,tg_topic_12,tg_topic_13,tg_topic_14,tg_topic_15,tg_topic_16,tg_topic_17,tg_topic_18,tg_topic_19,tg_topic_20,tg_topic_21,tg_topic_22,tg_topic_23,tg_topic_24,tg_topic_25,tg_topic_26,tg_topic_27,tg_topic_28,tg_topic_29,tg_topic_30,tg_topic_31,tg_topic_32,tg_topic_33,tg_topic_34,tg_topic_35,tg_topic_36,tg_topic_37,tg_topic_38,tg_topic_39,tg_topic_40,tg_topic_41,tg_topic_42,tg_topic_43,tg_topic_44,tg_topic_45,tg_topic_46,tg_topic_47,tg_topic_48,tg_topic_49,tg_topic_50,tg_topic_51,tg_topic_52,tg_topic_53,tg_topic_54,tg_topic_55,tg_topic_56,tg_topic_57,tg_topic_58,tg_topic_59,tg_topic_60,tg_topic_61,tg_topic_62,tg_topic_63,tg_topic_64,tg_topic_65,tg_topic_66,tg_topic_67,tg_topic_68,tg_topic_69,tg_topic_70,tg_topic_71,tg_topic_72,tg_topic_73,tg_topic_74,tg_topic_75,tg_topic_76,tg_topic_77,tg_topic_78,tg_topic_79,tg_topic_80,tg_topic_81,tg_topic_82,tg_topic_83,tg_topic_84,tg_topic_85,tg_topic_86,tg_topic_87,tg_topic_88,tg_topic_89,tg_topic_90,tg_topic_91,tg_topic_92,tg_topic_93,tg_topic_94,tg_topic_95,tg_topic_96,tg_topic_97,tg_topic_98,tg_topic_99,tg_topic_100,tg_topic_101,tg_topic_102,tg_topic_103,tg_topic_104,tg_topic_105,tg_topic_106,tg_topic_107,tg_topic_108,tg_topic_109,tg_topic_110,tg_topic_111,tg_topic_112,tg_topic_113,tg_topic_114,tg_topic_115,tg_topic_116,tg_topic_117,tg_topic_118,tg_topic_119,tg_topic_120,tg_topic_121,tg_topic_122,tg_topic_123,tg_topic_124,tg_topic_125,tg_topic_126,tg_topic_127,tg_topic_128,tg_topic_129,tg_topic_130,tg_topic_131,tg_topic_132,tg_topic_133,tg_topic_134,tg_topic_135,tg_topic_136,tg_topic_137,tg_topic_138,tg_topic_139,tg_topic_140,tg_topic_141,tg_topic_142,tg_topic_143,tg_topic_144,tg_topic_145,tg_topic_146,tg_topic_147,tg_topic_148,tg_topic_149,tg_topic_150,tg_topic_151,tg_topic_152,tg_topic_153,tg_topic_154,tg_topic_155,tg_topic_156,tg_topic_157,tg_topic_158,tg_topic_159,tg_topic_160,tg_topic_161,tg_topic_162,tg_topic_163,tg_topic_164,tg_topic_165,tg_topic_166,tg_topic_167,tg_topic_168,tg_topic_169,tg_topic_170,tg_topic_171,tg_topic_172,tg_topic_173,tg_topic_174,tg_topic_175,tg_topic_176,tg_topic_177,tg_topic_178,tg_topic_179,tg_topic_180,tg_topic_181,tg_topic_182,tg_topic_183,tg_topic_184,tg_topic_185,tg_topic_186,tg_topic_187,tg_topic_188,tg_topic_189,tg_topic_190,tg_topic_191,tg_topic_192,tg_topic_193,tg_topic_194,tg_topic_195,tg_topic_196,tg_topic_197,tg_topic_198,tg_topic_199,tg_topic_200,tg_topic_201,tg_topic_202,tg_topic_203,tg_topic_204,tg_topic_205,tg_topic_206,tg_topic_207,tg_topic_208,tg_topic_209,tg_topic_210,tg_topic_211,tg_topic_212,tg_topic_213,tg_topic_214,tg_topic_215,tg_topic_216,tg_topic_217,tg_topic_218,tg_topic_219,tg_topic_220,tg_topic_221,tg_topic_222,tg_topic_223,tg_topic_224,tg_topic_225,tg_topic_226,tg_topic_227,tg_topic_228,tg_topic_229,tg_topic_230,tg_topic_231,tg_topic_232,tg_topic_233,tg_topic_234,tg_topic_235,tg_topic_236,tg_topic_237,tg_topic_238,tg_topic_239,tg_topic_240,tg_topic_241,tg_topic_242,tg_topic_243,tg_topic_244,tg_topic_245,tg_topic_246,tg_topic_247,tg_topic_248,tg_topic_249,tg_total_intensity,tg_topic_std,tg_topic_max,tg_topic_entropy,tg_velocity_3h,tg_intensity_ema_6h,tg_intensity_zscore
0,2022-02-24 00:00:00,2,2.1,-0.5,91.76,0.0,0.0,0.0,16.6,8.6,279.6,1021.0,91.1,0.0,0.1,0.0,False,True,False,False,Vinnytsia,06:58:49,17:40:52,0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0.0,0.0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2022-02-24 00:00:00,2,2.1,-0.5,91.76,0.0,0.0,0.0,16.6,8.6,279.6,1021.0,91.1,0.0,0.1,0.0,False,True,False,False,Vinnytsia,06:58:49,17:40:52,0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0.0,0.0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-0.0,0.0,0.0,0.0
3,2022-02-24 01:00:00,2,2.1,-0.4,89.80,0.0,0.0,0.0,16.6,8.3,289.2,1021.0,97.9,0.0,0.1,0.0,False,True,False,False,Vinnytsia,06:58:49,17:40:52,0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0.0,0.0,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-0.0,0.0,0.0,0.0
2,2022-02-24 01:00:00,2,2.1,-0.4,89.80,0.0,0.0,0.0,16.6,8.3,289.2,1021.0,97.9,0.0,0.1,0.0,False,True,False,False,Vinnytsia,06:58:49,17:40:52,0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0.0,0.0,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-0.0,0.0,0.0,0.0
5,2022-02-24 02:00:00,2,2.0,-0.3,90.44,0.0,0.0,0.0,27.7,7.6,287.6,1021.0,98.2,0.0,0.1,0.0,False,True,False,False,Vinnytsia,06:58:49,17:40:52,0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0.0,0.0,3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-0.0,0.0,0.0,0.0

In [44]:
hour_weather_cols = [c for c in df_to_train.columns if c.startswith('hour_')]
for col in hour_weather_cols:
    if df_to_train[col].dtype == bool:
        df_to_train[col] = df_to_train.groupby('region_id')[col].shift(1).fillna(False)
    else:
        df_to_train[col] = df_to_train.groupby('region_id')[col].shift(1).fillna(0)

In [45]:
df_to_train.isna().sum()

datetime_hour          0
region_id              0
hour_temp              0
hour_feelslike         0
hour_humidity          0
                      ..
tg_topic_max           0
tg_topic_entropy       0
tg_velocity_3h         0
tg_intensity_ema_6h    0
tg_intensity_zscore    0
Length: 449, dtype: int64

In [46]:
df_to_train['alarm_minutes_in_hour'] = (df_to_train.groupby('region_id')['alarm_minutes_in_hour'].shift(1).fillna(0))

In [47]:
df_to_train.head()

,datetime_hour,region_id,hour_temp,hour_feelslike,hour_humidity,hour_precip,hour_precipprob,hour_snow,hour_windgust,hour_windspeed,hour_winddir,hour_pressure,hour_cloudcover,hour_solarradiation,hour_solarenergy,hour_uvindex,hour_conditions_simple_Clear,hour_conditions_simple_Cloudy,hour_conditions_simple_Rain,hour_conditions_simple_Snow,city_name,day_sunrise,day_sunset,alarm_active,alarm_minutes_in_hour,alarm_lag_1,alarm_lag_3,alarm_lag_6,alarm_lag_12,alarms_in_last_24h,is_weekend,is_night,total_active_alarms_lag1,neighbour_alarms,hours_since_last_alarm,isw_topic_0,isw_topic_1,isw_topic_2,isw_topic_3,isw_topic_4,isw_topic_5,isw_topic_6,isw_topic_7,isw_topic_8,isw_topic_9,isw_topic_10,isw_topic_11,isw_topic_12,isw_topic_13,isw_topic_14,isw_topic_15,isw_topic_16,isw_topic_17,isw_topic_18,isw_topic_19,isw_topic_20,isw_topic_21,isw_topic_22,isw_topic_23,isw_topic_24,isw_topic_25,isw_topic_26,isw_topic_27,isw_topic_28,isw_topic_29,isw_topic_30,isw_topic_31,isw_topic_32,isw_topic_33,isw_topic_34,isw_topic_35,isw_topic_36,isw_topic_37,isw_topic_38,isw_topic_39,isw_topic_40,isw_topic_41,isw_topic_42,isw_topic_43,isw_topic_44,isw_topic_45,isw_topic_46,isw_topic_47,isw_topic_48,isw_topic_49,isw_topic_50,isw_topic_51,isw_topic_52,isw_topic_53,isw_topic_54,isw_topic_55,isw_topic_56,isw_topic_57,isw_topic_58,isw_topic_59,isw_topic_60,isw_topic_61,isw_topic_62,isw_topic_63,isw_topic_64,isw_topic_65,isw_topic_66,isw_topic_67,isw_topic_68,isw_topic_69,isw_topic_70,isw_topic_71,isw_topic_72,isw_topic_73,isw_topic_74,isw_topic_75,isw_topic_76,isw_topic_77,isw_topic_78,isw_topic_79,isw_topic_80,isw_topic_81,isw_topic_82,isw_topic_83,isw_topic_84,isw_topic_85,isw_topic_86,isw_topic_87,isw_topic_88,isw_topic_89,isw_topic_90,isw_topic_91,isw_topic_92,isw_topic_93,isw_topic_94,isw_topic_95,isw_topic_96,isw_topic_97,isw_topic_98,isw_topic_99,isw_topic_100,isw_topic_101,isw_topic_102,isw_topic_103,isw_topic_104,isw_topic_105,isw_topic_106,isw_topic_107,isw_topic_108,isw_topic_109,isw_topic_110,isw_topic_111,isw_topic_112,isw_topic_113,isw_topic_114,isw_topic_115,isw_topic_116,isw_topic_117,isw_topic_118,isw_topic_119,isw_topic_120,isw_topic_121,isw_topic_122,isw_topic_123,isw_topic_124,isw_topic_125,isw_topic_126,isw_topic_127,isw_topic_128,isw_topic_129,isw_topic_130,isw_topic_131,isw_topic_132,isw_topic_133,isw_topic_134,isw_topic_135,isw_topic_136,isw_topic_137,isw_topic_138,isw_topic_139,isw_topic_140,isw_topic_141,isw_topic_142,isw_topic_143,isw_topic_144,isw_topic_145,isw_topic_146,isw_topic_147,isw_topic_148,isw_topic_149,isw_total_intensity,isw_topic_std,isw_topic_max,isw_topic_mean,isw_velocity_24h,isw_intensity_ema,isw_topic_entropy,tg_topic_0,tg_topic_1,tg_topic_2,tg_topic_3,tg_topic_4,tg_topic_5,tg_topic_6,tg_topic_7,tg_topic_8,tg_topic_9,tg_topic_10,tg_topic_11,tg_topic_12,tg_topic_13,tg_topic_14,tg_topic_15,tg_topic_16,tg_topic_17,tg_topic_18,tg_topic_19,tg_topic_20,tg_topic_21,tg_topic_22,tg_topic_23,tg_topic_24,tg_topic_25,tg_topic_26,tg_topic_27,tg_topic_28,tg_topic_29,tg_topic_30,tg_topic_31,tg_topic_32,tg_topic_33,tg_topic_34,tg_topic_35,tg_topic_36,tg_topic_37,tg_topic_38,tg_topic_39,tg_topic_40,tg_topic_41,tg_topic_42,tg_topic_43,tg_topic_44,tg_topic_45,tg_topic_46,tg_topic_47,tg_topic_48,tg_topic_49,tg_topic_50,tg_topic_51,tg_topic_52,tg_topic_53,tg_topic_54,tg_topic_55,tg_topic_56,tg_topic_57,tg_topic_58,tg_topic_59,tg_topic_60,tg_topic_61,tg_topic_62,tg_topic_63,tg_topic_64,tg_topic_65,tg_topic_66,tg_topic_67,tg_topic_68,tg_topic_69,tg_topic_70,tg_topic_71,tg_topic_72,tg_topic_73,tg_topic_74,tg_topic_75,tg_topic_76,tg_topic_77,tg_topic_78,tg_topic_79,tg_topic_80,tg_topic_81,tg_topic_82,tg_topic_83,tg_topic_84,tg_topic_85,tg_topic_86,tg_topic_87,tg_topic_88,tg_topic_89,tg_topic_90,tg_topic_91,tg_topic_92,tg_topic_93,tg_topic_94,tg_topic_95,tg_topic_96,tg_topic_97,tg_topic_98,tg_topic_99,tg_topic_100,tg_topic_101,tg_topic_102,tg_topic_103,tg_topic_104,tg_topic_105,tg_topic_106,tg_topic_107,tg_topic_108,tg_topic_109,tg_topic_110,tg_topic_111,tg_topic_112,tg_topic_113,tg_topic_114,tg_topic_115,tg_topic_116,tg_topic_117,tg_topic_118,tg_topic_119,tg_topic_120,tg_topic_121,tg_topic_122,tg_topic_123,tg_topic_124,tg_topic_125,tg_topic_126,tg_topic_127,tg_topic_128,tg_topic_129,tg_topic_130,tg_topic_131,tg_topic_132,tg_topic_133,tg_topic_134,tg_topic_135,tg_topic_136,tg_topic_137,tg_topic_138,tg_topic_139,tg_topic_140,tg_topic_141,tg_topic_142,tg_topic_143,tg_topic_144,tg_topic_145,tg_topic_146,tg_topic_147,tg_topic_148,tg_topic_149,tg_topic_150,tg_topic_151,tg_topic_152,tg_topic_153,tg_topic_154,tg_topic_155,tg_topic_156,tg_topic_157,tg_topic_158,tg_topic_159,tg_topic_160,tg_topic_161,tg_topic_162,tg_topic_163,tg_topic_164,tg_topic_165,tg_topic_166,tg_topic_167,tg_topic_168,tg_topic_169,tg_topic_170,tg_topic_171,tg_topic_172,tg_topic_173,tg_topic_174,tg_topic_175,tg_topic_176,tg_topic_177,tg_topic_178,tg_topic_179,tg_topic_180,tg_topic_181,tg_topic_182,tg_topic_183,tg_topic_184,tg_topic_185,tg_topic_186,tg_topic_187,tg_topic_188,tg_topic_189,tg_topic_190,tg_topic_191,tg_topic_192,tg_topic_193,tg_topic_194,tg_topic_195,tg_topic_196,tg_topic_197,tg_topic_198,tg_topic_199,tg_topic_200,tg_topic_201,tg_topic_202,tg_topic_203,tg_topic_204,tg_topic_205,tg_topic_206,tg_topic_207,tg_topic_208,tg_topic_209,tg_topic_210,tg_topic_211,tg_topic_212,tg_topic_213,tg_topic_214,tg_topic_215,tg_topic_216,tg_topic_217,tg_topic_218,tg_topic_219,tg_topic_220,tg_topic_221,tg_topic_222,tg_topic_223,tg_topic_224,tg_topic_225,tg_topic_226,tg_topic_227,tg_topic_228,tg_topic_229,tg_topic_230,tg_topic_231,tg_topic_232,tg_topic_233,tg_topic_234,tg_topic_235,tg_topic_236,tg_topic_237,tg_topic_238,tg_topic_239,tg_topic_240,tg_topic_241,tg_topic_242,tg_topic_243,tg_topic_244,tg_topic_245,tg_topic_246,tg_topic_247,tg_topic_248,tg_topic_249,tg_total_intensity,tg_topic_std,tg_topic_max,tg_topic_entropy,tg_velocity_3h,tg_intensity_ema_6h,tg_intensity_zscore
0,2022-02-24 00:00:00,2,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,False,False,False,False,Vinnytsia,06:58:49,17:40:52,0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0.0,0.0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2022-02-24 00:00:00,2,2.1,-0.5,91.76,0.0,0.0,0.0,16.6,8.6,279.6,1021.0,91.1,0.0,0.1,0.0,False,True,False,False,Vinnytsia,06:58:49,17:40:52,0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0.0,0.0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-0.0,0.0,0.0,0.0
3,2022-02-24 01:00:00,2,2.1,-0.5,91.76,0.0,0.0,0.0,16.6,8.6,279.6,1021.0,91.1,0.0,0.1,0.0,False,True,False,False,Vinnytsia,06:58:49,17:40:52,0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0.0,0.0,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-0.0,0.0,0.0,0.0
2,2022-02-24 01:00:00,2,2.1,-0.4,89.80,0.0,0.0,0.0,16.6,8.3,289.2,1021.0,97.9,0.0,0.1,0.0,False,True,False,False,Vinnytsia,06:58:49,17:40:52,0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0.0,0.0,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-0.0,0.0,0.0,0.0
5,2022-02-24 02:00:00,2,2.1,-0.4,89.80,0.0,0.0,0.0,16.6,8.3,289.2,1021.0,97.9,0.0,0.1,0.0,False,True,False,False,Vinnytsia,06:58:49,17:40:52,0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0.0,0.0,3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-0.0,0.0,0.0,0.0

In [48]:
df_to_train.to_parquet("final_merged_dataset.parquet", index = False, engine = "pyarrow")