# Data merge and feature engineering

In [1]:
%pip install pyarrow

Requirement already satisfied: pyarrow in d:\скаченное\python3.13.1\lib\site-packages (23.0.1)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.3.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import string

import re
import nltk
from nltk.stem import WordNetLemmatizer
from nltk.corpus import stopwords
from sklearn.feature_extraction.text import TfidfVectorizer
from tqdm.notebook import tqdm
from tqdm import tqdm
import pymorphy3
from collections import Counter

import os
from pathlib import Path
import json

In [3]:
df_weather = pd.read_csv("../data/weather_processed.csv")
df_war_events = pd.read_csv("../data/war_events_processed.csv")
df_isw_matrix = pd.read_csv("../data/isw_processed_svd.csv")

In [4]:
pd.set_option('display.max_columns', None)

In [5]:
df_weather['datetime_hour'] = pd.to_datetime(df_weather['datetime_hour'], errors="coerce")
df_war_events['datetime_hour'] = pd.to_datetime(df_war_events['datetime_hour'], errors="coerce")

In [6]:
df_final = pd.merge(
    df_weather, 
    df_war_events[['datetime_hour', 'region_id', 'alarm_active', 'alarm_minutes_in_hour']], 
    on=['datetime_hour', 'region_id'], 
    how='left'
)
df_final.sample(20)

,datetime_hour,region_id,city_latitude,city_longitude,day_temp,day_dew,day_humidity,day_precip,day_precipprob,day_precipcover,day_snow,day_snowdepth,day_windgust,day_windspeed,day_winddir,day_pressure,day_cloudcover,day_solarradiation,day_solarenergy,day_uvindex,day_moonphase,hour_temp,hour_feelslike,hour_humidity,hour_precip,hour_precipprob,hour_snow,hour_windgust,hour_windspeed,hour_winddir,hour_pressure,hour_cloudcover,hour_solarradiation,hour_solarenergy,hour_uvindex,day_conditions_simple_Clear,day_conditions_simple_Cloudy,day_conditions_simple_Rain,day_conditions_simple_Snow,hour_conditions_simple_Clear,hour_conditions_simple_Cloudy,hour_conditions_simple_Rain,hour_conditions_simple_Snow,year,month,day_of_week,hour,city_name,city_timezone,day_datetime,day_sunrise,day_sunset,hour_datetime,region_key,alarm_active,alarm_minutes_in_hour
47823,2022-05-18 01:00:00,18,50.9080,34.7972,10.0,3.7,66.1,2.077,100.0,8.33,0.0,0.0,36.4,21.3,351.2,1013.4,37.7,199.3,17.1,7.0,0.57,7.1,6.3,67.07,0.0,0.0,0.0,11.9,5.4,325.6,1011.0,27.1,0.0,0.1,0.0,False,False,True,False,False,True,False,False,2022,5,2,1,Sumy,Europe/Kiev,2022-05-18,04:47:33,20:27:55,01:00:00,Сумська,0,0.000000
458529,2024-04-30 04:00:00,11,48.5085,32.2656,15.6,4.9,51.5,0.000,0.0,0.00,0.0,0.0,46.4,25.2,53.2,1031.3,7.2,294.5,25.7,8.0,0.73,10.4,10.4,66.36,0.0,0.0,0.0,24.8,13.3,25.7,1032.0,0.0,0.0,0.0,0.0,True,False,False,False,True,False,False,False,2024,4,1,4,Kropyvnytskyi,Europe/Kiev,2024-04-30,05:32:41,20:04:35,04:00:00,Кіровоградська,0,0.000000
417449,2024-02-18 19:00:00,20,50.0042,36.2358,-1.7,-3.3,89.7,3.000,100.0,4.17,1.9,0.6,34.6,18.0,250.2,1023.9,88.5,29.0,2.4,1.0,0.29,0.0,-4.3,92.97,0.0,0.0,0.1,26.6,14.4,350.0,1023.0,88.0,0.0,0.0,0.0,False,False,False,True,False,True,False,False,2024,2,6,19,Kharkiv,Europe/Kiev,2024-02-18,06:41:23,16:57:31,19:00:00,Харківська,0,0.000000
96671,2022-08-10 20:00:00,26,50.4506,30.5243,19.2,14.1,72.2,0.200,100.0,8.33,0.0,0.0,33.1,13.0,9.5,1020.6,99.6,167.9,14.4,7.0,0.41,19.9,19.9,74.81,0.0,0.0,0.0,20.9,8.6,30.3,1020.0,100.0,8.0,0.0,0.0,False,False,True,False,False,True,False,False,2022,8,2,20,Kyiv,Europe/Kiev,2022-08-10,05:38:30,20:27:08,20:00:00,Київ,0,0.000000
236273,2023-04-10 06:00:00,20,50.0042,36.2358,10.1,-0.6,49.3,0.000,0.0,0.00,0.0,0.0,36.0,21.6,50.1,1023.2,42.5,219.6,19.1,7.0,0.65,6.3,6.3,66.41,0.0,0.0,0.0,15.8,0.1,50.0,1024.8,80.0,0.0,0.0,0.0,False,True,False,False,False,True,False,False,2023,4,0,6,Kharkiv,Europe/Kiev,2023-04-10,05:53:30,19:20:30,06:00:00,Харківська,0,0.000000
416157,2024-02-16 13:00:00,24,48.2924,25.9355,1.0,-0.4,91.0,0.000,0.0,0.00,0.0,0.0,25.9,10.6,118.4,1027.7,74.4,93.2,8.0,4.0,0.25,3.0,1.5,85.56,0.0,0.0,0.0,24.8,5.7,130.0,1027.6,51.7,327.6,1.2,3.0,False,True,False,False,False,True,False,False,2024,2,4,13,Chernivtsi,Europe/Kiev,2024-02-16,07:22:45,17:38:46,13:00:00,Чернівецька,0,0.000000
481845,2024-06-09 15:00:00,24,48.2924,25.9355,21.1,15.3,70.8,0.013,100.0,4.17,0.0,0.0,36.7,18.1,176.9,1009.6,74.8,213.4,18.4,6.0,0.09,26.0,26.0,52.57,0.0,0.0,0.0,34.6,7.5,228.0,1007.0,99.4,383.4,1.4,4.0,False,False,True,False,False,True,False,False,2024,6,6,15,Chernivtsi,Europe/Kiev,2024-06-09,05:15:53,21:15:46,15:00:00,Чернівецька,0,0.000000
344640,2023-10-15 10:00:00,2,49.2336,28.4486,11.8,9.6,86.4,6.000,100.0,4.17,0.0,0.0,31.3,15.8,321.2,1009.9,66.9,36.7,3.1,2.0,0.02,12.8,12.8,85.90,0.0,0.0,0.0,18.7,9.0,315.9,1009.0,99.3,150.9,0.5,2.0,False,False,True,False,False,True,False,False,2023,10,6,10,Vinnytsia,Europe/Kiev,2023-10-15,07:26:20,18:17:02,10:00:00,Вінницька,0,0.000000
600021,2024-12-31 19:00:00,24,48.2924,25.9355,2.9,-1.2,76.2,0.000,0.0,0.00,0.0,0.0,19.8,9.8,237.9,1027.6,23.9,58.5,5.1,3.0,0.00,4.6,3.0,70.54,0.0,0.0,0.0,11.5,6.9,257.0,1027.9,0.0,0.0,0.0,0.0,False,True,False,False,True,False,False,False,2024,12,1,19,Chernivtsi,Europe/Kiev,2024-12-31,08:07:28,16:31:41,19:00:00,Чернівецька,0,0.000000
162583,2022-12-03 07:00:00,9,48.9226,24.7147,-0.4,-1.2,94.0,0.000,0.0,0.00,0.0,2.3,29.9,14.0,127.4,1029.1,99.7,45.5,4.0,2.0,0.30,-0.6,-3.5,95.01,0.0,0.0,0.0,16.2,7.9,126.1,1028.0,100.0,0.0,0.1,0.0,False,True,False,False,False,True,False,False,2022,12,5,7,Ivano-Frankivsk,Europe/Kiev,2022-12-03,07:55:50,16:25:45,07:00:00,Івано-Франківська,0,0.000000
39609,2022-05-03 19:00:00,11,48.5085,32.2656,12.8,3.8,57.2,0.000,0.0,0.00,0.0,0.0,14.0,14.4,177.1,1015.9,33.0,162.8,14.0,7.0,0.07,16.9,16.9,45.66,0.0,0.0,0.0,14.0,6.8,183.7,1013.0,40.8,173.0,0.6,2.0,False,True,False,False,False,True,False,False,2022,5,1,19,Kropyvnytskyi,Europe/Kiev,2022-05-03,05:28:32,20:08:07,19:00:00,Кіровоградська,1,59.783333
421858,2024-02-26 11:00:00,13,49.8444,24.0254,9.7,7.2,85.0,0.000,0.0,0.00,0.0,0.0,33.1,19.1,141.8,1011.7,58.7,117.1,10.2,5.0,0.56,10.7,10.7,84.53,0.0,0.0,0.0,30.6,18.0,150.0,1011.4,60.0,305.7,1.1,3.0,False,True,False,False,False,True,False,False,2024,2,0,11,Lviv,Europe/Kiev,2024-02-26,07:14:25,18:00:14,11:00:00,Львівська,0,0.000000
517937,2024-08-11 07:00:00,20,50.0042,36.2358,21.7,12.0,57.3,0.000,0.0,0.00,0.0,0.0,45.4,28.8,276.5,1011.8,29.8,214.0,18.4,6.0,0.23,18.0,18.0,88.10,0.0,0.0,0.0,20.2,10.8,250.0,1013.0,2.6,97.1,0.3,1.0,False,True,False,False,True,False,False,False,2024,8,6,7,Kharkiv,Europe/Kiev,2024-08-11,05:19:15,20:00:17,07:00:00,Харківська,1,53.850000
533724,2024-09-07 17:00:00,15,46.4725,30.7371,21.1,10.2,50.6,0.000,0.0,0.00,0.0,0.0,45.0,28.8,52.0,1020.6,8.5,232.7,19.9,7.0,0.14,25.4,25.4,33.75,0.0,0.0,0.0,39.2,19.8,53.8,1020.0,0.0,419.7,1.5,4.0,True,False,False,False,True,False,False,False,2024,9,5,17,Odesa,Europe/Kiev,2024-09-07,06:25:06,19:24:02,17:00:00,Одеська,0,0.000000
292132,2023-07-16 06:00:00,6,50.2536,28.6654,22.2,15.1,67.2,0.000,0.0,0.00,0.0,0.0,16.6,7.2,185.1,1018.0,36.5,233.7,20.1,7.0,0.95,14.9,14.9,93.74,0.0,0.0,0.0,9.7,0.0,191.4,1018.7,30.0,10.0,0.0,0.0,False,True,False,False,False,True,False,False,2023,7,6,6,Zhytomyr,Europe/Kiev,2023-07-16,05:12:27,21:09:46,06:00:00,Житомирська,0,0.000000
378480,2023-12-13 04:00:00,2,49.2336,28.4486,0.9,0.2,95.0,3.000,100.0,4.17,2.1,2.9,40.7,20.2,157.3,1011.3,98.7,30.1,2.8,2.0,0.00,1.1,-1.9,96.46,0.0,0.0,0.0,18.0,9.4,240.8,1012.0,100.0,0.0,0.0,0.0,False,False,False,True,False,True,False,False,2023,12,2,4,Vinnytsia,Europe/Kiev,2023-12-13,07:52:44,16:07:41,04:00:00,Вінницька,0,0.000000
38932,2022-05-02 15:00:00,6,50.2536,28.6654,12.9,2.1,50.0,0.000,0.0,0.00,0.0,0.0,25.9,13.0,200.9,1019.0,62.7,243.0,20.9,8.0,0.03,19.7,19.7,30.57,0.0,0.0,0.0,20.9,7.2,240.0,1016.8,80.0,673.0,2.4,7.0,False,True,False,False,False,True,False,False,2022,5,0,15,Zhytomyr,Europe/Kiev,2022-05-02,05:39:34,20:26:11,15:00:00,Житомирська,0,0.000000
496557,2024-07-05 04:00:00,24,48.2924,25.9355,19.3,13.0,69.9,0.000,0.0,0.00,0.0,0.0,32.0,17.7,314.6,1012.8,41.1,264.0,22.7,8.0,0.98,13.3,13.3,90.97,0.0,0.0,0.0,14.8,8.6,276.0,1011.3,7.9,0.0,0.0,0.0,False,True,False,False,True,False,False,False,2024,7,4,4,Chernivtsi,Europe/Kiev,2024-07-05,05:22:33,21:19:04,04:00:00,Чернівецька,0,0.000000
284227,2023-07-02 12:00:00,22,49.4168,26.9743,21.9,16.0,71.7,0.100,100.0,4.17,0.0,0.0,32.4,18.0,267.5,1005.8,63.6,283.5,24.7,8.0,0.46,24.9,24.9,60.36,0.0,0.0,0.0,29.2,10.8,330.0,1005.0,60.0,723.8,2.6,7.0,False,False,True,False,False,True,False,False,2023,7,6,12,Khmelnytskyi,Europe/Kiev,2023-07-02,05:10:28,21:21:32,12:00:00,Хмельницька,0,0.000000
488498,2024-06-21 05:00:00,4,48.4753,35.0160,20.2,11.5,59.0,0.000,0.0,0.00,0.0,0.0,49.0,28.8,314.3,1016.6,28.7,265.5,22.8,8.0,0.48,14.9,14.9,78.00,0.0,0.0,0.0,26.6,15.8,305.0,1018.0,0.0,1.7,0.0,0.0,False,True,False,False,True,False,False,False,2024,6,4,5,Dnipro,Europe/Kiev,2024-06-21,04:38:18,20:45:28,05:00:00,Дніпропетровська,0,0.000000

In [7]:
df_final = df_final.sort_values(['region_id', 'datetime_hour'])
df_final.head()

,datetime_hour,region_id,city_latitude,city_longitude,day_temp,day_dew,day_humidity,day_precip,day_precipprob,day_precipcover,day_snow,day_snowdepth,day_windgust,day_windspeed,day_winddir,day_pressure,day_cloudcover,day_solarradiation,day_solarenergy,day_uvindex,day_moonphase,hour_temp,hour_feelslike,hour_humidity,hour_precip,hour_precipprob,hour_snow,hour_windgust,hour_windspeed,hour_winddir,hour_pressure,hour_cloudcover,hour_solarradiation,hour_solarenergy,hour_uvindex,day_conditions_simple_Clear,day_conditions_simple_Cloudy,day_conditions_simple_Rain,day_conditions_simple_Snow,hour_conditions_simple_Clear,hour_conditions_simple_Cloudy,hour_conditions_simple_Rain,hour_conditions_simple_Snow,year,month,day_of_week,hour,city_name,city_timezone,day_datetime,day_sunrise,day_sunset,hour_datetime,region_key,alarm_active,alarm_minutes_in_hour
0,2022-02-24 00:00:00,2,49.2336,28.4486,2.8,-0.3,80.5,0.3,100.0,4.17,0.0,0.0,27.7,10.8,312.0,1023.4,82.5,60.4,5.4,3.0,0.77,2.1,-0.5,91.76,0.0,0.0,0.0,16.6,8.6,279.6,1021.0,91.1,0.0,0.1,0.0,False,False,False,True,False,True,False,False,2022,2,3,0,Vinnytsia,Europe/Kiev,2022-02-24,06:58:49,17:40:52,00:00:00,Вінницька,0,0.0
24,2022-02-24 01:00:00,2,49.2336,28.4486,2.8,-0.3,80.5,0.3,100.0,4.17,0.0,0.0,27.7,10.8,312.0,1023.4,82.5,60.4,5.4,3.0,0.77,2.1,-0.4,89.80,0.0,0.0,0.0,16.6,8.3,289.2,1021.0,97.9,0.0,0.1,0.0,False,False,False,True,False,True,False,False,2022,2,3,1,Vinnytsia,Europe/Kiev,2022-02-24,06:58:49,17:40:52,01:00:00,Вінницька,0,0.0
48,2022-02-24 02:00:00,2,49.2336,28.4486,2.8,-0.3,80.5,0.3,100.0,4.17,0.0,0.0,27.7,10.8,312.0,1023.4,82.5,60.4,5.4,3.0,0.77,2.0,-0.3,90.44,0.0,0.0,0.0,27.7,7.6,287.6,1021.0,98.2,0.0,0.1,0.0,False,False,False,True,False,True,False,False,2022,2,3,2,Vinnytsia,Europe/Kiev,2022-02-24,06:58:49,17:40:52,02:00:00,Вінницька,0,0.0
72,2022-02-24 03:00:00,2,49.2336,28.4486,2.8,-0.3,80.5,0.3,100.0,4.17,0.0,0.0,27.7,10.8,312.0,1023.4,82.5,60.4,5.4,3.0,0.77,1.9,-0.3,91.75,0.0,0.0,0.0,15.1,7.2,288.9,1021.0,98.8,0.0,0.1,0.0,False,False,False,True,False,True,False,False,2022,2,3,3,Vinnytsia,Europe/Kiev,2022-02-24,06:58:49,17:40:52,03:00:00,Вінницька,0,0.0
96,2022-02-24 04:00:00,2,49.2336,28.4486,2.8,-0.3,80.5,0.3,100.0,4.17,0.0,0.0,27.7,10.8,312.0,1023.4,82.5,60.4,5.4,3.0,0.77,1.8,-0.2,92.40,0.0,0.0,0.0,13.7,6.5,290.4,1021.0,100.0,0.0,0.1,0.0,False,False,False,True,False,True,False,False,2022,2,3,4,Vinnytsia,Europe/Kiev,2022-02-24,06:58:49,17:40:52,04:00:00,Вінницька,0,0.0

In [8]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
Index: 634749 entries, 0 to 634748
Data columns (total 56 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   datetime_hour                  634749 non-null  datetime64[ns]
 1   region_id                      634749 non-null  int64
 2   city_latitude                  634749 non-null  float64
 3   city_longitude                 634749 non-null  float64
 4   day_temp                       634749 non-null  float64
 5   day_dew                        634749 non-null  float64
 6   day_humidity                   634749 non-null  float64
 7   day_precip                     634749 non-null  float64
 8   day_precipprob                 634749 non-null  float64
 9   day_precipcover                634749 non-null  float64
 10  day_snow                       634749 non-null  float64
 11  day_snowdepth                  634749 non-null  float64
 12  day_windgust                   634749 non-null  float64
 13  day_windspeed                  634749 non-null  float64
 14  day_winddir                    634749 non-null  float64
 15  day_pressure                   634749 non-null  float64
 16  day_cloudcover                 634749 non-null  float64
 17  day_solarradiation             634749 non-null  float64
 18  day_solarenergy                634749 non-null  float64
 19  day_uvindex                    634749 non-null  float64
 20  day_moonphase                  634749 non-null  float64
 21  hour_temp                      634749 non-null  float64
 22  hour_feelslike                 634749 non-null  float64
 23  hour_humidity                  634749 non-null  float64
 24  hour_precip                    634749 non-null  float64
 25  hour_precipprob                634749 non-null  float64
 26  hour_snow                      634749 non-null  float64
 27  hour_windgust                  634749 non-null  float64
 28  hour_windspeed                 634749 non-null  float64
 29  hour_winddir                   634749 non-null  float64
 30  hour_pressure                  634749 non-null  float64
 31  hour_cloudcover                634749 non-null  float64
 32  hour_solarradiation            634749 non-null  float64
 33  hour_solarenergy               634749 non-null  float64
 34  hour_uvindex                   634749 non-null  float64
 35  day_conditions_simple_Clear    634749 non-null  bool
 36  day_conditions_simple_Cloudy   634749 non-null  bool
 37  day_conditions_simple_Rain     634749 non-null  bool
 38  day_conditions_simple_Snow     634749 non-null  bool
 39  hour_conditions_simple_Clear   634749 non-null  bool
 40  hour_conditions_simple_Cloudy  634749 non-null  bool
 41  hour_conditions_simple_Rain    634749 non-null  bool
 42  hour_conditions_simple_Snow    634749 non-null  bool
 43  year                           634749 non-null  int64
 44  month                          634749 non-null  int64
 45  day_of_week                    634749 non-null  int64
 46  hour                           634749 non-null  int64
 47  city_name                      634749 non-null  object
 48  city_timezone                  634749 non-null  object
 49  day_datetime                   634749 non-null  object
 50  day_sunrise                    634749 non-null  object
 51  day_sunset                     634749 non-null  object
 52  hour_datetime                  634749 non-null  object
 53  region_key                     634749 non-null  object
 54  alarm_active                   634749 non-null  int64
 55  alarm_minutes_in_hour          634749 non-null  float64
dtypes: bool(8), datetime64[ns](1), float64(34), int64(6), object(7)
memory usage: 242.1+ MB

In [9]:
df_final = df_final.sort_values(["region_id", "datetime_hour"])

df_final["alarm_lag_1"] = df_final.groupby("region_id")["alarm_active"].shift(1)
df_final["alarm_lag_3"] = df_final.groupby("region_id")["alarm_active"].shift(3)
df_final["alarm_lag_6"] = df_final.groupby("region_id")["alarm_active"].shift(6)
df_final["alarm_lag_12"] = df_final.groupby("region_id")["alarm_active"].shift(12)
#df_final['alarm_minutes_lag1'] = (df_final.groupby('region_id')['alarm_minutes_in_hour'].shift(1).fillna(0))
#df_final['alarm_minutes_lag3'] = (df_final.groupby('region_id')['alarm_minutes_in_hour'].shift(3).fillna(0))

lag_cols = ["alarm_lag_1","alarm_lag_3","alarm_lag_6","alarm_lag_12"]
df_final[lag_cols] = df_final[lag_cols].fillna(0)

df_final['alarms_in_last_24h'] = (df_final.groupby('region_id')['alarm_active'].transform(lambda x: x.shift(1).rolling(24, min_periods=1).sum()))

df_final['is_weekend'] = df_final['day_of_week'].isin([5, 6]).astype(int)
df_final['is_night'] = ((df_final['hour'] >= 23) | (df_final['hour'] <= 6)).astype(int)

hourly_total = df_final.groupby('datetime_hour')['alarm_active'].sum().shift(1)
df_final['total_active_alarms_lag1'] = df_final['datetime_hour'].map(hourly_total)

df_final.sample(10)

,datetime_hour,region_id,city_latitude,city_longitude,day_temp,day_dew,day_humidity,day_precip,day_precipprob,day_precipcover,day_snow,day_snowdepth,day_windgust,day_windspeed,day_winddir,day_pressure,day_cloudcover,day_solarradiation,day_solarenergy,day_uvindex,day_moonphase,hour_temp,hour_feelslike,hour_humidity,hour_precip,hour_precipprob,hour_snow,hour_windgust,hour_windspeed,hour_winddir,hour_pressure,hour_cloudcover,hour_solarradiation,hour_solarenergy,hour_uvindex,day_conditions_simple_Clear,day_conditions_simple_Cloudy,day_conditions_simple_Rain,day_conditions_simple_Snow,hour_conditions_simple_Clear,hour_conditions_simple_Cloudy,hour_conditions_simple_Rain,hour_conditions_simple_Snow,year,month,day_of_week,hour,city_name,city_timezone,day_datetime,day_sunrise,day_sunset,hour_datetime,region_key,alarm_active,alarm_minutes_in_hour,alarm_lag_1,alarm_lag_3,alarm_lag_6,alarm_lag_12,alarms_in_last_24h,is_weekend,is_night,total_active_alarms_lag1
624957,2025-02-13 02:00:00,24,48.2924,25.9355,-5.2,-7.8,82.9,0.000,0.0,0.00,0.0,0.0,23.0,14.1,137.1,1023.9,50.8,114.3,9.8,5.0,0.53,-10.7,-16.3,95.72,0.000,0.0,0.0,20.9,10.4,104.0,1029.3,4.8,0.0,0.0,0.0,False,True,False,False,True,False,False,False,2025,2,3,2,Chernivtsi,Europe/Kiev,2025-02-13,07:26:34,17:35:09,02:00:00,Чернівецька,0,0.000000,0.0,0.0,0.0,0.0,0.0,0,1,12.0
10002,2022-03-13 08:00:00,21,46.6401,32.6142,-0.4,-7.9,59.4,0.000,0.0,0.00,0.0,0.0,21.6,14.0,117.0,1027.0,78.1,162.5,13.9,5.0,0.34,-3.1,-7.4,64.75,0.000,0.0,0.0,16.6,11.2,110.5,1026.0,78.5,28.0,0.1,0.0,False,True,False,False,False,True,False,False,2022,3,6,8,Kherson,Europe/Kiev,2022-03-13,06:06:42,17:52:12,08:00:00,Херсонська,0,0.000000,0.0,0.0,0.0,0.0,0.0,1,0,8.0
418095,2024-02-19 22:00:00,18,50.9080,34.7972,-2.9,-8.5,66.3,0.000,0.0,0.00,0.0,1.2,25.2,13.7,7.6,1029.5,67.8,103.4,8.9,4.0,0.32,-5.0,-8.3,77.64,0.000,0.0,0.0,14.4,7.2,108.2,1030.0,98.8,0.0,0.0,0.0,False,True,False,False,False,True,False,False,2024,2,0,22,Sumy,Europe/Kiev,2024-02-19,06:47:00,17:03:16,22:00:00,Сумська,0,0.000000,0.0,0.0,0.0,0.0,3.0,0,0,5.0
502817,2024-07-16 01:00:00,20,50.0042,36.2358,28.7,17.3,51.9,0.000,0.0,0.00,0.0,0.0,30.2,14.4,9.8,1014.9,17.4,290.2,24.9,8.0,0.34,25.0,25.0,61.15,0.000,0.0,0.0,14.0,7.2,20.0,1015.0,0.6,0.0,0.0,0.0,True,False,False,False,True,False,False,False,2024,7,1,1,Kharkiv,Europe/Kiev,2024-07-16,04:44:09,20:37:39,01:00:00,Харківська,1,54.966667,1.0,1.0,0.0,1.0,23.0,0,1,7.0
91498,2022-08-01 21:00:00,13,49.8444,24.0254,16.9,14.8,87.4,0.200,100.0,4.17,0.0,0.0,25.6,10.8,284.4,1013.1,95.0,48.6,4.1,1.0,0.11,17.2,17.2,92.07,0.200,100.0,0.0,12.2,0.0,279.5,1014.1,80.0,30.0,0.1,0.0,False,False,True,False,False,False,True,False,2022,8,0,21,Lviv,Europe/Kiev,2022-08-01,05:53:32,21:06:07,21:00:00,Львівська,0,0.000000,0.0,0.0,0.0,0.0,2.0,0,0,0.0
127395,2022-10-03 05:00:00,5,48.0020,37.8145,12.9,7.5,70.7,2.400,100.0,4.17,0.0,0.0,49.3,20.9,245.4,1007.6,64.6,151.3,13.2,6.0,0.24,11.2,11.2,80.12,0.000,0.0,0.0,42.5,20.9,253.3,1003.0,81.1,0.0,0.1,0.0,False,False,True,False,False,True,False,False,2022,10,0,5,Donetsk,Europe/Kiev,2022-10-03,06:30:20,18:04:32,05:00:00,Донецька,1,4.600000,1.0,0.0,0.0,0.0,2.0,0,1,10.0
368837,2023-11-26 10:00:00,7,48.6264,22.2851,-2.0,-6.1,74.2,0.500,100.0,37.50,0.0,1.6,48.6,19.6,330.1,1006.0,66.1,62.0,5.3,3.0,0.47,-1.3,-5.0,69.73,0.124,100.0,0.0,35.3,10.5,340.0,1004.8,57.3,134.2,0.5,1.0,False,False,False,True,False,False,False,True,2023,11,6,10,Uzhgorod,Europe/Uzhgorod,2023-11-26,07:54:51,16:40:55,10:00:00,Закарпатська,0,0.000000,0.0,0.0,0.0,0.0,0.0,1,0,0.0
224507,2023-03-20 19:00:00,14,46.9734,31.9852,6.7,2.5,76.2,0.000,0.0,0.00,0.0,0.0,19.1,10.8,343.5,1019.4,91.2,120.6,10.6,4.0,0.95,6.7,4.9,74.04,0.000,0.0,0.0,10.8,8.6,250.2,1018.0,75.3,0.0,0.0,0.0,False,True,False,False,False,True,False,False,2023,3,0,19,Mykolaiv,Europe/Kiev,2023-03-20,05:55:59,18:04:09,19:00:00,Миколаївська,0,0.000000,0.0,0.0,1.0,0.0,5.0,0,0,0.0
327183,2023-09-15 02:00:00,18,50.9080,34.7972,13.0,9.7,81.0,4.696,100.0,12.50,0.0,0.0,32.8,17.8,106.6,1018.9,79.2,61.4,5.2,3.0,0.00,13.5,13.5,64.78,0.000,0.0,0.0,31.0,17.3,130.3,1017.0,100.0,0.0,0.0,0.0,False,False,True,False,False,True,False,False,2023,9,4,2,Sumy,Europe/Kiev,2023-09-15,06:15:20,18:56:05,02:00:00,Сумська,0,0.000000,0.0,0.0,0.0,1.0,5.0,0,1,0.0
336168,2023-09-30 17:00:00,2,49.2336,28.4486,17.3,8.9,63.6,0.000,0.0,0.00,0.0,0.0,15.5,7.6,223.7,1020.4,7.4,166.7,14.3,6.0,0.53,24.1,24.1,39.29,0.000,0.0,0.0,12.2,5.8,256.2,1018.0,1.5,278.4,1.0,3.0,True,False,False,False,True,False,False,False,2023,9,5,17,Vinnytsia,Europe/Kiev,2023-09-30,07:03:42,18:48:09,17:00:00,Вінницька,0,0.000000,0.0,0.0,0.0,0.0,6.0,1,0,2.0

In [10]:
neighbouring_regions = {
    1: [21],
    2: [6, 10, 11, 15, 22, 23, 24],
    3: [13, 17],
    4: [5, 8, 11, 14, 16, 20, 21],
    5: [4, 8, 12, 20],
    6: [2, 10, 17, 22],
    7: [9, 13],
    8: [4, 5, 21],
    9: [7, 13, 19, 24],
    10: [2, 6, 16, 23, 25],
    11: [2, 4, 14, 15, 16, 23],
    12: [5, 20],
    13: [3, 7, 9, 17, 19],
    14: [4, 11, 15, 21],
    15: [2, 11, 14],
    16: [4, 10, 11, 18, 20, 23, 25],
    17: [3, 6, 13, 19, 22],
    18: [16, 20, 25],
    19: [9, 13, 17, 22, 24],
    20: [4, 5, 12, 16, 18],
    21: [1, 4, 8, 14],
    22: [2, 6, 17, 19, 24],
    23: [2, 10, 11, 16],
    24: [2, 9, 19, 22],
    25: [10, 16, 18], 
    26: [10]
}

alarms_matrix = df_final.pivot_table(
    index='datetime_hour',
    columns='region_id',
    values='alarm_active',
    fill_value=0
)

neighbour_alarm_matrix = pd.DataFrame(index=alarms_matrix.index)

for region, neighbours in neighbouring_regions.items():
    valid_neighbours = [n for n in neighbours if n in alarms_matrix.columns]
    
    if valid_neighbours:
        neighbour_alarm_matrix[region] = alarms_matrix[valid_neighbours].sum(axis=1)
    else:
        neighbour_alarm_matrix[region] = 0

neighbour_alarm_matrix = neighbour_alarm_matrix.shift(1)

neighbour_alarm_long = (neighbour_alarm_matrix.stack().reset_index())

neighbour_alarm_long.columns = ['datetime_hour','region_id','neighbour_alarms']

df_final = df_final.merge(neighbour_alarm_long,on=['datetime_hour', 'region_id'], how='left')

In [11]:
def hours_since_last_alarm(series):
    shifted = series.shift(1).fillna(0)
    result = []
    count = 0
    for val in shifted:
        if val == 1:
            count = 0
        else:
            count += 1
        result.append(count)
    return pd.Series(result, index=series.index)

df_final['hours_since_last_alarm'] = (df_final.groupby('region_id')['alarm_active'].transform(hours_since_last_alarm))

In [12]:
df_final.sample(20)

,datetime_hour,region_id,city_latitude,city_longitude,day_temp,day_dew,day_humidity,day_precip,day_precipprob,day_precipcover,day_snow,day_snowdepth,day_windgust,day_windspeed,day_winddir,day_pressure,day_cloudcover,day_solarradiation,day_solarenergy,day_uvindex,day_moonphase,hour_temp,hour_feelslike,hour_humidity,hour_precip,hour_precipprob,hour_snow,hour_windgust,hour_windspeed,hour_winddir,hour_pressure,hour_cloudcover,hour_solarradiation,hour_solarenergy,hour_uvindex,day_conditions_simple_Clear,day_conditions_simple_Cloudy,day_conditions_simple_Rain,day_conditions_simple_Snow,hour_conditions_simple_Clear,hour_conditions_simple_Cloudy,hour_conditions_simple_Rain,hour_conditions_simple_Snow,year,month,day_of_week,hour,city_name,city_timezone,day_datetime,day_sunrise,day_sunset,hour_datetime,region_key,alarm_active,alarm_minutes_in_hour,alarm_lag_1,alarm_lag_3,alarm_lag_6,alarm_lag_12,alarms_in_last_24h,is_weekend,is_night,total_active_alarms_lag1,neighbour_alarms,hours_since_last_alarm
422026,2025-01-13 16:00:00,18,50.90800,34.79720,-1.1,-2.7,89.1,0.928,100.0,8.33,0.1,0.2,24.8,13.7,309.5,1028.0,75.6,45.1,3.8,2.0,0.48,-0.7,-4.2,81.94,0.0,0.0,0.0,20.5,10.1,305.9,1030.0,82.6,23.0,0.1,0.0,False,False,False,True,False,True,False,False,2025,1,0,16,Sumy,Europe/Kiev,2025-01-13,07:38:44,16:00:52,16:00:00,Сумська,1,60.000000,1.0,1.0,1.0,1.0,21.0,0,0,5.0,2.0,0
242327,2022-08-22 03:00:00,11,48.50850,32.26560,23.1,15.7,64.5,0.100,100.0,4.17,0.0,0.0,34.2,21.6,64.7,1010.5,46.3,268.5,23.3,8.0,0.82,19.4,19.4,82.79,0.0,0.0,0.0,7.9,7.2,20.0,1009.8,30.0,0.0,0.1,0.0,False,False,True,False,False,True,False,False,2022,8,0,3,Kropyvnytskyi,Europe/Kiev,2022-08-22,05:53:52,19:52:58,03:00:00,Кіровоградська,0,0.000000,0.0,0.0,0.0,0.0,3.0,0,1,2.0,1.0,20
343161,2025-02-02 15:00:00,15,46.47250,30.73710,1.4,-1.7,80.9,0.600,100.0,4.17,0.0,0.0,24.8,16.2,298.5,1027.5,53.8,95.5,8.1,4.0,0.14,4.9,3.3,63.26,0.0,0.0,0.0,14.8,6.8,259.1,1027.0,91.1,224.9,0.8,2.0,False,False,False,True,False,True,False,False,2025,2,6,15,Odesa,Europe/Kiev,2025-02-02,07:19:21,17:02:53,15:00:00,Одеська,0,0.000000,0.0,1.0,0.0,1.0,6.0,1,0,2.0,0.0,2
149224,2024-02-01 21:00:00,7,48.62640,22.28510,-0.1,-1.9,87.6,0.286,100.0,12.50,0.4,5.5,39.6,10.8,160.5,1027.4,87.0,25.7,2.2,1.0,0.72,-0.5,-0.5,95.12,0.0,0.0,0.0,10.4,4.7,35.0,1025.0,100.0,0.0,0.0,0.0,False,False,False,True,False,True,False,False,2024,2,3,21,Uzhgorod,Europe/Uzhgorod,2024-02-01,08:01:17,17:28:08,21:00:00,Закарпатська,0,0.000000,0.0,0.0,0.0,0.0,0.0,0,0,4.0,0.0,28
325598,2023-02-01 18:00:00,15,46.47250,30.73710,2.3,-1.5,77.1,0.000,0.0,0.00,0.0,1.4,29.2,18.0,277.7,1011.4,79.3,70.8,6.1,3.0,0.35,3.9,0.2,68.34,0.0,0.0,0.0,25.6,16.2,249.1,1011.0,97.0,0.0,0.0,0.0,False,True,False,False,False,True,False,False,2023,2,2,18,Odesa,Europe/Kiev,2023-02-01,07:21:14,17:00:34,18:00:00,Одеська,0,0.000000,0.0,0.0,0.0,0.0,1.0,0,0,0.0,0.0,6
181203,2024-09-19 09:00:00,8,47.82890,35.16260,17.4,3.1,39.4,0.000,0.0,0.00,0.0,0.0,41.0,25.6,60.8,1022.8,57.3,191.8,16.6,6.0,0.54,15.6,15.6,42.50,0.0,0.0,0.0,34.2,24.1,57.4,1024.0,93.9,248.7,0.9,2.0,False,True,False,False,False,True,False,False,2024,9,3,9,Zaporozhye,Europe/Zaporozhye,2024-09-19,06:22:17,18:42:58,09:00:00,Запорізька,0,0.000000,0.0,0.0,0.0,1.0,4.0,0,0,2.0,0.0,8
335796,2024-04-01 18:00:00,15,46.47250,30.73710,12.5,9.5,82.4,0.000,0.0,0.00,0.0,0.0,32.0,16.2,171.8,1013.4,64.9,219.1,18.9,7.0,0.74,16.0,16.0,67.10,0.0,0.0,0.0,28.4,15.5,159.8,1012.0,89.1,238.6,0.9,2.0,False,True,False,False,False,True,False,False,2024,4,0,18,Odesa,Europe/Kiev,2024-04-01,06:36:03,19:26:28,18:00:00,Одеська,0,0.000000,0.0,0.0,0.0,0.0,0.0,0,0,6.0,0.0,26
266158,2022-05-05 02:00:00,13,49.84440,24.02540,13.0,1.3,47.4,0.000,0.0,0.00,0.0,0.0,28.8,14.4,117.5,1022.3,27.1,291.0,25.3,8.0,0.14,7.9,7.9,63.50,0.0,0.0,0.0,9.4,4.0,64.6,1022.0,0.0,0.0,0.1,0.0,False,True,False,False,True,False,False,False,2022,5,3,2,Lviv,Europe/Kiev,2022-05-05,05:54:12,20:48:04,02:00:00,Львівська,0,0.000000,0.0,0.0,1.0,0.0,3.0,0,1,2.0,0.0,3
444458,2024-07-30 08:00:00,19,49.55270,25.58890,18.1,10.3,61.7,0.000,0.0,0.00,0.0,0.0,58.0,29.9,309.9,1015.2,47.7,178.7,15.5,5.0,0.82,15.3,15.3,68.32,0.0,0.0,0.0,44.6,27.4,311.5,1015.0,28.2,171.2,0.6,2.0,False,True,False,False,False,True,False,False,2024,7,1,8,Ternopil,Europe/Kiev,2024-07-30,05:46:19,21:01:05,08:00:00,Тернопільська,0,0.000000,0.0,0.0,0.0,0.0,0.0,0,0,0.0,0.0,103
178367,2024-05-24 05:00:00,8,47.82890,35.16260,19.7,6.7,44.1,0.000,0.0,0.00,0.0,0.0,44.6,32.0,67.3,1020.2,7.3,297.7,25.8,8.0,0.53,16.4,16.4,58.72,0.0,0.0,0.0,28.4,20.2,66.1,1018.0,0.0,0.1,0.0,0.0,True,False,False,False,True,False,False,False,2024,5,4,5,Zaporozhye,Europe/Zaporozhye,2024-05-24,04:51:02,20:22:13,05:00:00,Запорізька,0,0.000000,0.0,0.0,0.0,0.0,7.0,0,1,0.0,0.0,6
606741,2024-12-27 03:00:00,25,51.49370,31.29440,0.8,0.5,98.0,0.400,100.0,4.17,0.0,0.0,16.6,9.7,342.6,1032.0,100.0,8.0,0.6,0.0,0.89,0.5,-1.1,98.56,0.0,0.0,0.0,9.0,5.0,328.9,1033.0,100.0,0.0,0.0,0.0,False,False,False,True,False,True,False,False,2024,12,4,3,Chernihiv,Europe/Kiev,2024-12-27,08:00:22,15:51:59,03:00:00,Чернігівська,0,0.000000,0.0,0.0,1.0,0.0,6.0,0,1,3.0,2.0,3
406011,2023-03-18 07:00:00,18,50.90800,34.79720,2.7,-3.1,66.7,0.000,0.0,0.00,0.0,0.0,45.0,23.4,54.8,1027.5,45.4,181.1,15.6,6.0,0.88,0.8,-4.0,71.86,0.0,0.0,0.0,32.8,18.4,50.9,1029.0,3.1,55.2,0.2,1.0,False,True,False,False,True,False,False,False,2023,3,5,7,Sumy,Europe/Kiev,2023-03-18,05:49:00,17:49:56,07:00:00,Сумська,0,0.000000,0.0,0.0,0.0,0.0,3.0,1,0,0.0,0.0,19
20149,2024-06-12 16:00:00,2,49.23360,28.44860,18.4,13.6,76.2,16.000,100.0,4.17,0.0,0.0,52.9,25.2,319.2,1011.2,74.2,213.4,18.3,7.0,0.19,21.0,21.0,54.57,0.0,0.0,0.0,40.0,16.2,317.5,1013.0,63.3,692.2,2.5,7.0,False,False,True,False,False,True,False,False,2024,6,2,16,Vinnytsia,Europe/Kiev,2024-06-12,05:00:42,21:12:00,16:00:00,Вінницька,0,0.000000,0.0,0.0,0.0,1.0,6.0,0,0,11.0,3.0,6
134977,2022-06-18 05:00:00,7,48.62636,22.28514,19.1,8.9,55.1,0.035,100.0,4.17,0.0,0.0,19.4,7.9,314.4,1021.2,16.1,297.3,25.7,8.0,0.62,11.4,11.4,81.14,0.0,0.0,0.0,8.3,6.5,341.0,1022.6,0.0,0.0,0.1,0.0,False,False,True,False,True,False,False,False,2022,6,5,5,Uzhgorod,Europe/Uzhgorod,2022-06-18,05:27:58,21:36:11,05:00:00,Закарпатська,0,0.000000,0.0,0.0,0.0,0.0,2.0,1,1,13.0,0.0,18
13274,2023-08-31 04:00:00,2,49.23360,28.44860,20.7,15.5,75.1,0.000,0.0,0.00,0.0,0.0,32.8,18.0,254.7,1009.9,58.1,189.5,16.5,7.0,0.50,16.5,16.5,97.48,0.0,0.0,0.0,15.1,6.1,145.2,1008.0,77.4,0.0,0.0,0.0,False,True,False,False,False,True,False,False,2023,8,3,4,Vinnytsia,Europe/Kiev,2023-08-31,06:20:15,19:52:08,04:00:00,Вінницька,0,0.000000,0.0,0.0,0.0,0.0,2.0,0,1,2.0,0.0,22
169278,2023-05-11 11:00:00,8,47.82890,35.16260,11.7,2.5,56.0,140.000,100.0,4.17,0.0,0.0,25.6,14.4,324.0,1022.1,25.7,259.4,22.4,7.0,0.70,14.0,14.0,42.34,0.0,0.0,0.0,25.6,14.4,338.5,1022.0,35.3,608.6,2.2,6.0,False,False,True,False,False,True,False,False,2023,5,3,11,Zaporozhye,Europe/Zaporozhye,2023-05-11,05:07:14,20:05:11,11:00:00,Запорізька,1,22.033333,1.0,0.0,0.0,1.0,11.0,0,0,5.0,1.0,0
525705,2024-10-17 15:00:00,22,49.41680,26.97430,5.0,1.7,81.2,0.000,0.0,0.00,0.0,0.0,24.8,18.0,32.1,1033.9,42.3,115.2,9.8,5.0,0.50,10.6,10.6,52.95,0.0,0.0,0.0,20.2,10.8,60.0,1033.2,0.4,429.5,1.5,4.0,False,True,False,False,True,False,False,False,2024,10,3,15,Khmelnytskyi,Europe/Kiev,2024-10-17,07:36:48,18:17:13,15:00:00,Хмельницька,0,0.000000,0.0,0.0,0.0,1.0,5.0,0,0,5.0,0.0,9
159047,2022-03-11 02:00:00,8,47.82890,35.16260,-5.2,-10.0,69.1,0.200,100.0,8.33,0.3,0.3,43.2,23.0,24.4,1022.7,86.9,131.8,11.4,4.0,0.28,-8.5,-15.6,72.83,0.0,0.0,0.1,34.2,18.0,26.4,1022.0,91.8,0.0,0.1,0.0,False,False,False,True,False,True,False,False,2022,3,4,2,Zaporozhye,Europe/Zaporozhye,2022-03-11,06:00:58,17:38:39,02:00:00,Запорізька,0,0.000000,0.0,0.0,0.0,0.0,0.0,0,1,1.0,0.0,158
478502,2022-06-05 18:00:00,21,46.64010,32.61420,21.6,12.6,57.2,0.500,100.0,12.50,0.0,0.0,36.0,21.6,349.0,1013.7,71.3,271.5,23.4,9.0,0.18,22.6,22.6,52.86,0.0,0.0,0.0,20.5,13.0,319.7,1013.0,88.7,49.0,0.2,0.0,False,False,True,False,False,True,False,False,2022,6,6,18,Kherson,Europe/Kiev,2022-06-05,04:57:58,20:38:35,18:00:00,Херсонська,0,0.000000,0.0,0.0,0.0,0.0,0.0,1,0,1.0,0.0,1241
372880,2022-06-12 20:00:00,17,50.61927,26.25131,20.5,12.6,63.7,0.000,0.0,0.00,0.0,0.0,31.7,18.0,342.0,1017.2,26.9,247.3,21.4,6.0,0.42,23.7,23.7,41.07,0.0,0.0,0.0,25.2,10.8,344.3,1016.0,37.1,196.0,0.7,2.0,False,True,False,False,False,True,False,False,2022,6,6,20,Rivne,Europe/Kiev,2022-06-12,05:02:38,21:27:26,20:00:00,Рівненська,0,0.000000,0.0,0.0,0.0,0.0,2.0,1,0,0.0,0.0,21

In [13]:
df_isw_matrix.sample(10)

,date,isw_topic_0,isw_topic_1,isw_topic_2,isw_topic_3,isw_topic_4,isw_topic_5,isw_topic_6,isw_topic_7,isw_topic_8,isw_topic_9,isw_topic_10,isw_topic_11,isw_topic_12,isw_topic_13,isw_topic_14,isw_topic_15,isw_topic_16,isw_topic_17,isw_topic_18,isw_topic_19,isw_topic_20,isw_topic_21,isw_topic_22,isw_topic_23,isw_topic_24,isw_topic_25,isw_topic_26,isw_topic_27,isw_topic_28,isw_topic_29,isw_topic_30,isw_topic_31,isw_topic_32,isw_topic_33,isw_topic_34,isw_topic_35,isw_topic_36,isw_topic_37,isw_topic_38,isw_topic_39,isw_topic_40,isw_topic_41,isw_topic_42,isw_topic_43,isw_topic_44,isw_topic_45,isw_topic_46,isw_topic_47,isw_topic_48,isw_topic_49,isw_topic_50,isw_topic_51,isw_topic_52,isw_topic_53,isw_topic_54,isw_topic_55,isw_topic_56,isw_topic_57,isw_topic_58,isw_topic_59,isw_topic_60,isw_topic_61,isw_topic_62,isw_topic_63,isw_topic_64,isw_topic_65,isw_topic_66,isw_topic_67,isw_topic_68,isw_topic_69,isw_topic_70,isw_topic_71,isw_topic_72,isw_topic_73,isw_topic_74,isw_topic_75,isw_topic_76,isw_topic_77,isw_topic_78,isw_topic_79,isw_topic_80,isw_topic_81,isw_topic_82,isw_topic_83,isw_topic_84,isw_topic_85,isw_topic_86,isw_topic_87,isw_topic_88,isw_topic_89,isw_topic_90,isw_topic_91,isw_topic_92,isw_topic_93,isw_topic_94,isw_topic_95,isw_topic_96,isw_topic_97,isw_topic_98,isw_topic_99,isw_topic_100,isw_topic_101,isw_topic_102,isw_topic_103,isw_topic_104,isw_topic_105,isw_topic_106,isw_topic_107,isw_topic_108,isw_topic_109,isw_topic_110,isw_topic_111,isw_topic_112,isw_topic_113,isw_topic_114,isw_topic_115,isw_topic_116,isw_topic_117,isw_topic_118,isw_topic_119,isw_topic_120,isw_topic_121,isw_topic_122,isw_topic_123,isw_topic_124,isw_topic_125,isw_topic_126,isw_topic_127,isw_topic_128,isw_topic_129,isw_topic_130,isw_topic_131,isw_topic_132,isw_topic_133,isw_topic_134,isw_topic_135,isw_topic_136,isw_topic_137,isw_topic_138,isw_topic_139,isw_topic_140,isw_topic_141,isw_topic_142,isw_topic_143,isw_topic_144,isw_topic_145,isw_topic_146,isw_topic_147,isw_topic_148,isw_topic_149
242,2022-10-24,0.731607,-0.201671,-0.010460,-0.224927,-0.012290,-0.175143,-0.247790,-0.070428,-0.181655,-0.108980,-0.117663,-0.018177,-0.089848,-0.101872,-0.028671,0.101958,-0.070993,-0.022994,0.035726,0.083365,0.044793,0.012986,0.044793,-0.006668,0.006325,0.085686,-0.005811,-0.035421,0.013352,-0.024854,0.001578,0.007244,-0.010043,-0.030219,0.014927,0.019798,0.033873,-0.011238,-0.007564,0.031340,-0.013261,-0.000757,-0.023711,-0.003310,-0.024417,-0.007593,0.002816,-0.012254,-0.000622,-0.008384,0.042326,0.009801,-0.004668,0.002790,-0.022808,-0.009900,0.023545,-0.037471,-0.006711,0.007345,0.017326,-0.009699,0.012686,-0.032320,0.012662,0.009835,-0.001949,-0.000395,0.033964,0.006047,-0.022245,0.007089,0.008925,0.022099,-0.024163,0.009547,-0.012934,0.020221,0.011500,0.015924,-0.004467,0.006590,0.032103,0.006470,0.012735,0.024526,-0.004982,0.006805,-0.022113,-0.002502,-0.007553,-0.003264,-0.008843,0.015448,-0.008999,0.001740,0.040646,-0.004407,-0.008246,-0.003869,-0.032755,0.016854,-0.041425,0.004101,0.006265,0.006724,0.032580,-0.001120,0.002710,0.013325,0.055860,-0.037047,-0.009116,0.005087,0.011054,-0.040191,0.003545,0.027615,-0.011223,-0.010391,0.006624,0.018289,-0.030720,-0.001350,0.002498,0.027594,0.021091,-0.002324,0.010911,-0.014818,0.000252,-0.016267,0.018388,-0.014042,0.001017,-0.015215,-0.027786,0.005575,-0.000336,0.008016,-0.004629,0.003489,-0.017812,-0.003941,-0.019399,-0.011303,0.008072,-0.013462,-0.021459,-0.007717
656,2023-12-16,0.798800,-0.096671,-0.133255,-0.050853,0.115531,-0.074566,0.254796,0.078159,-0.063985,-0.150298,-0.046422,-0.017423,-0.038211,0.025566,-0.021589,-0.056077,0.019135,0.061446,0.072636,-0.034789,-0.024598,-0.030755,-0.015307,0.017836,0.022009,0.044216,0.019065,-0.062099,0.025885,0.022227,-0.022448,-0.046203,0.037375,0.010581,0.041893,0.034680,0.008525,-0.006427,-0.024551,-0.008771,0.005040,0.013931,0.032982,-0.063331,-0.020431,-0.008721,-0.010278,0.020146,0.009610,-0.000400,-0.001006,-0.008102,0.006089,-0.052710,-0.016354,-0.006718,-0.032814,-0.007720,0.003637,-0.005453,0.025300,-0.021054,0.014982,0.017252,0.029044,0.049402,0.002127,-0.005396,-0.035557,0.007994,0.009986,-0.018301,0.017588,-0.007183,0.010812,0.016270,-0.043854,-0.017683,0.011697,-0.013241,0.029481,0.010764,-0.017196,-0.021918,-0.022037,-0.018963,0.068747,-0.022435,0.024827,-0.023353,0.011306,-0.012190,-0.021359,0.009125,-0.018689,0.022559,-0.011341,-0.004698,-0.000406,-0.028559,-0.014640,0.013350,0.022057,0.025309,-0.015688,0.006998,0.041536,-0.000513,-0.031534,-0.022255,0.007567,0.018473,0.002453,0.036102,-0.026823,0.002344,-0.062231,0.008785,-0.021923,0.020203,-0.003763,0.011571,-0.005585,0.015931,-0.023076,0.007060,0.017566,0.013585,0.006235,0.018810,0.017779,-0.027538,0.014501,-0.006701,-0.015176,0.014580,-0.001034,0.014029,0.015317,-0.008637,-0.001264,-0.004334,-0.001575,0.008649,-0.015991,0.034514,0.032997,0.008537,0.010336,0.001410
717,2024-02-17,0.794871,-0.067116,-0.083769,0.050971,0.034318,-0.022292,-0.017298,0.013189,0.016411,0.021441,-0.039159,0.029140,0.164238,-0.147717,0.057996,-0.198211,0.011975,0.069373,-0.046055,0.049098,-0.022603,-0.023024,-0.028422,-0.025560,-0.058521,0.118472,-0.026222,-0.066224,0.002762,0.025910,-0.019989,-0.010601,0.035908,0.032402,0.031743,-0.004056,-0.041334,0.051260,-0.012512,0.004429,0.044934,0.028637,0.015771,0.050391,0.031232,0.013079,-0.049885,0.038284,-0.018113,0.012894,0.002379,-0.004390,-0.070403,0.007421,0.020235,0.028294,0.044416,-0.003108,0.037681,0.045621,0.026370,0.051088,-0.068714,-0.011573,-0.015105,-0.049692,-0.022273,-0.054901,0.020828,0.003117,-0.033333,0.027144,-0.035558,0.035675,0.015024,0.002336,-0.061020,-0.081119,0.000938,-0.039385,-0.027559,0.019822,0.027178,-0.039246,-0.011581,0.020107,-0.028986,0.040765,-0.061059,0.046098,0.078880,-0.012929,0.036252,0.037231,0.040705,0.020039,-0.053308,-0.010904,0.013238,-0.019558,0.006326,-0.000774,-0.002341,0.015398,-0.017612,-0.016404,-0.018561,0.027718,0.000303,0.003499,-0.006303,-0.025220,0.032967,-0.024529,0.028614,-0.011569,0.005476,-0.030191,0.006049,-0.006021,0.001050,0.017916,0.030056,-0.034620,-0.001087,-0.010357,-0.011175,0.030858,-0.017676,-0.023221,-0.027511,0.018870,-0.028888,0.008785,0.035897,0.013454,-0.019342,0.032970,-0.048060,-0.005519,-0.019922,-0.018011,0.023092,-0.014184,0.043152,-0.000274,0.025363,0.034930,0.019456,-0.010756
452,2023-05-25,0.691778,-0.227849,-0.150683,0.032431,-0.022179,0.075462,-0.013526,0.080605,-0.114139,0.103146,0.060338,0.067495,-0.075395,-0.008613,0.039753,0.182714,0.181088,-0.036133,-0.115007,0.031294,-0.004473,-0.032478,0.125073,-0.040563,0.028695,-0.047022,0.037273,0.005251,0.008808,0.006480,-0.054188,-0.033026,-0.039301,-0.057318,0.108753,0.027954,0.016086,0.042317,-0.065738,0.021173,-0.025286,-0.006344,-0.065105,0.032817,0.015772,-0.018767,0.010721,0.012484,-0.049607,-0.036938,0.040290,-0.034647,-0.046217,-0.078530,-0.026649,-0.054087,0.068144,-0.074710,-0.004238,0.039350,0.029548,0.010318,0.047284,0.001667,0.037673,0.025262,-0.029148,0.007046,-0.021473,0.011828,-0.005174,-0.043163,0.038195,-0.019002,-0.041970,-0.043135,-0.039251,-0.000804,-0.005525,0.069616,0.015035,0.040067,-0.022002,-0.013594,0.017235,-0.007676,-0.036362,-0.008474,-0.016262,-0.021430,0.005290,-0.002489,0.027623,0.012186,0.017472,-0.035440,-0.009949,0.052265,0.027267,0.073915,-0.013186,0.005328,0.022787,-0.029025,-0.010150,-0.032874,0.017673,0.023818,-0.001446,-0.033276,-0.000717,-0.009766,0.009182,0.004279,0.015609,0.004428,0.041499,0.028235,0.057352,0.009993,0.018816,0.002370,0.002583,0.028538,0.011930,0.018169,-0.006197,0.006489,-0.028935,-0.006708,0.011900,0.031696,0.006287,-0.084822,-0.020182,-0.005413,-0.032515,-0.004171,0.018919,0.007727,0.000671,-0.011495,0.015865,0.011080,-0.015373,-0.033183,0.010756,0.013797,-0.004573,0.015089
539,2023-08-20,0.815820,-0.149614,-0.051068,-0.123843,-0.107609,0.088373,-0.017706,0.143956,0.079143,-0.014859,0.118046,0.004655,-0.131195,-0.050283,0.054200,-0.119223,0.066130,-0.001113,0.036147,-0.030740,0.000894,-0.034411,0.014775,0.051167,0.006238,0.038334,-0.023896,0.045469,-0.028256,-0.034800,-0.016467,0.001664,-0.002179,-0.026299,-0.059208,0.019544,-0.003800,0.001889,-0.002878,-0.014448,0.023678,-0.001216,0.003535,0.000399,0.005628,0.035506,0.004790,0.009656,-0.006681,-0.001653,-0.066299,-0.047856,-0.025857,0.013671,-0.002087,0.012130,-0.017222,0.022367,0.014995,0.006502,-0.036067,0.044745,0.022488,-0.029622,-0.017861,0.076089,-0.008565,0.047372,0.007450,0.017127,0.003128,0.038376,0.026576,-0.013161,-0.028194,-0.008247,-0.004505,-0.022770,0.006897,-0.028756,0.013861,-0.003810,0.003409,-0.016696,-0.000482,-0.007309,0.003357,0.019249,-0.009058,-0.025201,-0.015883,0.018425,0.016718,-0.026101,0.011080,0.054533,0.000648,0.014291,0.037276,-0.018631,0.002174,-0.034411,0.004509,-0.015791,0.006726,-0.030463,-0.053869,-0.001410,0.001096,0.013310,-0.052101,-0.010327,0.021909,-0.004467,-0.001438,0.012745,-0.008997,0.004699,0.035451,0.007374,-0.001643,-0.002729,0.026811,-0.001785,-0.002293,0.007647,-0.005678,0.011698,0.009644,-0.007913,-0.010759,0.022668,-0.012918,-0.006074,-0.011542,0.031550,-0.000319,0.010103,0.004682,0.013564,-0.016933,-0.017782,-0.020663,0.021953,0.004797,-0.009706,0.021590,0.001948,-0.005259,0.004418
1086,2025-02-24,0.769496,0.238352,-0.065305,0.148712,0.034040,-0.000789,-0.007386,0.082998,-0.031604,0.039670,-0.034004,0.065090,0.199851,-0.220763,0.159865,0.018237,-0.054075,0.000330,0.090086,-0.076085,0.039988,0.051998,-0.037534,-0.075427,0.025832,0.002510,0.015175,-0.014594,-0.049662,-0.069598,-0.005333,0.009235,0.005105,0.028575,0.023042,-0.054921,0.004643,-0.049212,-0.009551,0.002368,-0.041214,-0.017506,-0.009698,-0.030589,-0.016931,-0.027847,-0.012920,0.020785,-0.005805,-0.003300,0.015223,-0.023294,0.017944,0.018433,-0.027997,0.020249,-0.008524,0.007571,0.001771,0.037810,-0.038674,0.003626,-0.002904,-0.007109,-0.014617,0.033660,0.011905,0.044787,0.050389,0.005828,-0.022706,-0.027784,-0.001353,0.047316,-0.006794,-0.002897,0.040498,-0.002657,-0.022506,0.000997,-0.005787,-0.005153,0.009007,-0.017175,-0.007483,0.021980,-0.004977,0.025412,-0.000584,-0.003184,-0.019569,0.009181,0.020206,-0.016293,0.011216,-0.004236,0.016150,-0.005117,-0.013303,0.002791,0.002300,0.001422,0.026509,0.003188,-0.017111,0.001036,0.006765,-0.006388,-0.009467,-0.008603,0.012790,0.018457,-0.007023,0.008081,-0.018947,0.001911,0.025028,-0.007633,0.001432,-0.001087,0.036051,-0.006174,0.005411,-0.012131,0.003363,-0.004730,0.041613,0.026006,0.012060,0.011196,-0.019043,0.001248,0.029058,-0.004604,-0.034871,-0.028624,-0.030997,-0.005623,-0.000309,-0.040504,0.015759,0.018472,0.010483,-0.004756,-0.009044,-0.005619,-0.002514,-0.005702,-0.006703,-0.022768
31,2022-03-27,0.590078,-0.168234,0.304144,0.216633,0.097064,-0.178857,-0.107570,0.205829,0.132285,0.118159,-0.192180,-0.040951,-0.113543,0.134809,-0.014039,-0.138407,-0.019988,-0.063989,0.118553,0.121227,-0.037584,0.029566,0.043283,-0.023374,0.084415,-0.008203,0.064201,-0.011823,-0.003674,0.011805,0.104084,0.022062,-0.069460,0.045608,0.032712,-0.032698,0.012295,-0.027695,0.043515,-0.063053,0.020852,-0.058070,0.014874,0.034607,0.012427,0.003012,0.019102,-0.027752,-0.012721,0.032176,0.013146,-0.047666,-0.002897,0.023235,-0.061721,-0.029425,0.000132,0.006811,-0.008762,-0.012195,0.004069,0.016926,-0.003714,-0.002380,0.005152,-0.024948,-0.020645,-0.026220,0.013315,0.004816,0.015912,0.020396,-0.010288,-0.019881,-0.022206,-0.010366,-0.002340,0.009370,0.004728,0.012287,0.008939,0.000763,-0.051712,-0.008189,-0.035364,0.001914,-0.026930,0.007782,0.006736,0.021746,-0.018875,-0.022618,-0.000893,0.029888,-0.027552,0.006840,0.017213,-0.013600,-0.010084,-0.010802,-0.025295,0.002851,0.014389,-0.001733,0.030537,-0.015931,-0.037516,0.014126,-0.036280,-0.025540,0.000222,-0.020977,0.005425,0.045693,-0.008262,0.023955,0.000133,-0.033173,0.004744,-0.028172,-0.028135,-0.001728,-0.020721,-0.055305,-0.027360,-0.029052,-0.024695,0.012121,0.025480,-0.009582,0.020127,-0.007191,0.010776,-0.028950,-0.023617,-0.027901,-0.021454,0.005162,-0.012000,0.022038,0.005640,0.027053,-0.022817,0.014771,0.022325,0.005946,-0.024655,-0.007673,0.012180,-0.019750
1120,2025-03-30,0.728324,0.261766,0.008325,0.238270,-0.027694,-0.127345,-0.091835,0.184100,0.097560,0.131441,-0.140617,-0.040026,-0.145423,0.114257,0.031860,0.078773,-0.120624,0.112946,-0.055431,-0.106433,0.054596,0.037632,-0.012195,0.066635,0.015992,0.018229,-0.008079,-0.036817,-0.046435,-0.060699,-0.049533,0.011146,-0.013835,0.022088,0.017228,0.013742,-0.040721,0.027488,-0.004827,0.003790,-0.003784,0.014201,0.009620,-0.009910,0.006924,0.022957,0.031135,0.014275,-0.005707,0.001986,0.015014,0.021002,0.015793,-0.042140,0.013823,-0.012476,0.016535,0.024896,-0.011922,-0.021167,0.022841,0.015313,-0.011047,-0.016957,0.002549,-0.010132,0.015287,-0.046137,-0.004208,0.010004,0.012599,-0.027423,-0.013008,0.011196,-0.005445,0.018575,0.049960,0.002960,0.026363,-0.019513,-0.017674,-0.028378,-0.005115,-0.002765,0.012389,0.006655,0.023997,-0.018279,0.008046,-0.009900,-0.008126,-0.029607,-0.001745,-0.003170,0.029240,-0.036027,-0.026116,-0.004886,0.020998,0.015885,0.003952,0.012121,0.021259,0.009279,0.007892,-0.034233,0.001826,-0.014656,0.019444,0.007367,0.005056,-0.024959,0.011822,-0.032935,0.022444,-0.002868,0.001891,-0.007182,0.020826,0.014127,0.012030,0.005403,-0.002802,0.000209,0.020082,0.008785,-0.006050,0.009467,-0.001183,0.008128,0.039342,0.012943,0.022644,0.002887,-0.003360,-0.022751,-0.017299,0.006197,0.011170,0.012652,-0.005014,-0.012885,0.008575,0.012059,-0.005601,0.009030,-0.006721,-0.015834,-0.001590,0.001323
662,2023-12-22,0.726462,-0.118911,-0.216582,0.026305,0.105842,-0.009751,0.192663,0.121984,-0.117487,-0.083114,-0.011697,-0.008045,-0.069834,-0.006278,-0.035882,0.024163,0.082748,-0.075310,-0.041216,-0.039806,0.070119,0.051829,0.072629,-0.069214,0.037640,0.114556,0.077702,-0.079484,0.037693,0.001849,-0.011598,-0.029152,-0.017846,-0.021054,0.014225,-0.013978,-0.000915,0.024703,-0.076445,-0.033035,-0.006788,-0.018907,-0.016284,-0.004162,-0.004443,0.000514,0.037886,0.003274,-0.042269,-0.025844,-0.022372,-0.010352,0.019122,-0.048880,-0.050880,-0.005337,-0.041089,0.012461,-0.018007,-0.029162,0.042478,-0.033758,-0.000508,0.003268,0.049133,-0.006586,-0.042446,-0.001136,-0.020999,-0.011179,0.004680,-0.000333,0.003040,-0.006676,0.068727,0.010131,0.019648,-0.038231,-0.027135,0.040339,0.014214,-0.021624,0.043422,0.038941,0.005274,0.028218,0.000288,-0.026863,-0.017645,-0.025171,-0.033701,0.011276,0.008795,-0.005555,0.038225,-0.011430,-0.006286,0.024626,-0.007550,0.007521,-0.038673,0.008500,0.000014,0.051786,-0.017935,0.017492,0.005585,0.007125,0.038825,0.063457,0.024348,0.023621,-0.063128,0.004342,0.002032,0.066474,0.026831,0.028686,-0.017377,-0.039093,-0.028256,-0.014558,0.008929,-0.023288,-0.005117,-0.002441,-0.044794,0.052020,0.009640,-0.053217,-0.017323,0.008222,0.011122,0.001658,-0.018075,0.015293,0.042062,0.008254,-0.006597,0.027586,-0.004724,-0.060414,0.019244,0.030615,-0.063739,0.014884,0.083274,0.010849,0.040246,-0.012457
437,2023-05-10,0.823254,-0.203366,-0.004510,-0.054885,-0.011924,0.029995,-0.022956,0.042064,-0.037316,0.052919,0.033453,0.015564,-0.029227,0.028978,0.098490,-0.019443,0.077786,0.125053,-0.063578,0.088959,0.000425,0.025605,-0.015941,-0.049821,-0.056349,-0.061776,-0.002769,0.017301,-0.002797,0.005505,0.027392,-0.011804,-0.005937,0.068945,0.035636,-0.032448,-0.009089,0.003503,-0.009927,0.018781,0.029590,-0.006601,-0.011017,-0.007929,-0.012495,-0.005820,-0.034147,0.006107,0.001356,0.043445,0.055224,0.009405,-0.019949,-0.006549,-0.028123,-0.022316,0.000422,0.011182,0.003226,0.011441,-0.009997,0.025592,-0.019594,0.005295,-0.015955,0.013533,0.003444,0.005385,-0.029815,0.017452,-0.006806,0.004375,-0.028359,-0.023019,-0.009790,-0.017031,0.032157,-0.000590,0.038231,-0.031088,-0.022666,-0.031473,0.019002,-0.011412,-0.021847,-0.032121,0.001117,-0.013191,-0.021659,-0.015539,0.002266,-0.025284,0.012289,0.037372,0.014655,0.025939,-0.038561,-0.032373,-0.023966,0.018290,-0.031372,-0.033033,-0.015398,-0.025741,0.013853,-0.003916,0.007352,-0.009887,-0.002843,0.019013,-0.026526,-0.010026,0.026172,-0.009231,0.039574,0.041622,0.002082,-0.044028,-0.006464,0.016246,0.025448,0.034190,-0.016449,-0.003356,-0.058479,-0.009187,-0.003248,-0.009568,0.004233,-0.001503,0.035004,-0.005222,-0.014247,0.003273,-0.009825,0.007070,-0.005956,0.013956,-0.049836,-0.012028,0.022943,-0.003648,0.017868,0.012014,0.023575,-0.016446,0.009949,0.021575,-0.024130,-0.013178

In [14]:
#df_isw_matrix["date"] = pd.to_datetime(df_isw_matrix["date"]) + pd.Timedelta(days=1)    ТУТ ЗСУВ ІСВ НА + 1 ДЕНЬ
df_isw_matrix = df_isw_matrix.rename(columns={'date': 'day_datetime'})

In [15]:
df_final['day_datetime'] = pd.to_datetime(df_final['day_datetime']).dt.date
df_isw_matrix['day_datetime'] = pd.to_datetime(df_isw_matrix['day_datetime']).dt.date
df_isw_matrix.fillna(0, inplace=True)
df_isw_matrix.isna().sum()

day_datetime     0
isw_topic_0      0
isw_topic_1      0
isw_topic_2      0
isw_topic_3      0
                ..
isw_topic_145    0
isw_topic_146    0
isw_topic_147    0
isw_topic_148    0
isw_topic_149    0
Length: 151, dtype: int64

In [16]:
df_final = df_final.merge(df_isw_matrix, on="day_datetime", how="left")

In [17]:
df_final.head(10)

,datetime_hour,region_id,city_latitude,city_longitude,day_temp,day_dew,day_humidity,day_precip,day_precipprob,day_precipcover,day_snow,day_snowdepth,day_windgust,day_windspeed,day_winddir,day_pressure,day_cloudcover,day_solarradiation,day_solarenergy,day_uvindex,day_moonphase,hour_temp,hour_feelslike,hour_humidity,hour_precip,hour_precipprob,hour_snow,hour_windgust,hour_windspeed,hour_winddir,hour_pressure,hour_cloudcover,hour_solarradiation,hour_solarenergy,hour_uvindex,day_conditions_simple_Clear,day_conditions_simple_Cloudy,day_conditions_simple_Rain,day_conditions_simple_Snow,hour_conditions_simple_Clear,hour_conditions_simple_Cloudy,hour_conditions_simple_Rain,hour_conditions_simple_Snow,year,month,day_of_week,hour,city_name,city_timezone,day_datetime,day_sunrise,day_sunset,hour_datetime,region_key,alarm_active,alarm_minutes_in_hour,alarm_lag_1,alarm_lag_3,alarm_lag_6,alarm_lag_12,alarms_in_last_24h,is_weekend,is_night,total_active_alarms_lag1,neighbour_alarms,hours_since_last_alarm,isw_topic_0,isw_topic_1,isw_topic_2,isw_topic_3,isw_topic_4,isw_topic_5,isw_topic_6,isw_topic_7,isw_topic_8,isw_topic_9,isw_topic_10,isw_topic_11,isw_topic_12,isw_topic_13,isw_topic_14,isw_topic_15,isw_topic_16,isw_topic_17,isw_topic_18,isw_topic_19,isw_topic_20,isw_topic_21,isw_topic_22,isw_topic_23,isw_topic_24,isw_topic_25,isw_topic_26,isw_topic_27,isw_topic_28,isw_topic_29,isw_topic_30,isw_topic_31,isw_topic_32,isw_topic_33,isw_topic_34,isw_topic_35,isw_topic_36,isw_topic_37,isw_topic_38,isw_topic_39,isw_topic_40,isw_topic_41,isw_topic_42,isw_topic_43,isw_topic_44,isw_topic_45,isw_topic_46,isw_topic_47,isw_topic_48,isw_topic_49,isw_topic_50,isw_topic_51,isw_topic_52,isw_topic_53,isw_topic_54,isw_topic_55,isw_topic_56,isw_topic_57,isw_topic_58,isw_topic_59,isw_topic_60,isw_topic_61,isw_topic_62,isw_topic_63,isw_topic_64,isw_topic_65,isw_topic_66,isw_topic_67,isw_topic_68,isw_topic_69,isw_topic_70,isw_topic_71,isw_topic_72,isw_topic_73,isw_topic_74,isw_topic_75,isw_topic_76,isw_topic_77,isw_topic_78,isw_topic_79,isw_topic_80,isw_topic_81,isw_topic_82,isw_topic_83,isw_topic_84,isw_topic_85,isw_topic_86,isw_topic_87,isw_topic_88,isw_topic_89,isw_topic_90,isw_topic_91,isw_topic_92,isw_topic_93,isw_topic_94,isw_topic_95,isw_topic_96,isw_topic_97,isw_topic_98,isw_topic_99,isw_topic_100,isw_topic_101,isw_topic_102,isw_topic_103,isw_topic_104,isw_topic_105,isw_topic_106,isw_topic_107,isw_topic_108,isw_topic_109,isw_topic_110,isw_topic_111,isw_topic_112,isw_topic_113,isw_topic_114,isw_topic_115,isw_topic_116,isw_topic_117,isw_topic_118,isw_topic_119,isw_topic_120,isw_topic_121,isw_topic_122,isw_topic_123,isw_topic_124,isw_topic_125,isw_topic_126,isw_topic_127,isw_topic_128,isw_topic_129,isw_topic_130,isw_topic_131,isw_topic_132,isw_topic_133,isw_topic_134,isw_topic_135,isw_topic_136,isw_topic_137,isw_topic_138,isw_topic_139,isw_topic_140,isw_topic_141,isw_topic_142,isw_topic_143,isw_topic_144,isw_topic_145,isw_topic_146,isw_topic_147,isw_topic_148,isw_topic_149
0,2022-02-24 00:00:00,2,49.2336,28.4486,2.8,-0.3,80.5,0.3,100.0,4.17,0.0,0.0,27.7,10.8,312.0,1023.4,82.5,60.4,5.4,3.0,0.77,2.1,-0.5,91.76,0.0,0.0,0.0,16.6,8.6,279.6,1021.0,91.1,0.0,0.1,0.0,False,False,False,True,False,True,False,False,2022,2,3,0,Vinnytsia,Europe/Kiev,2022-02-24,06:58:49,17:40:52,00:00:00,Вінницька,0,0.0,0.0,0.0,0.0,0.0,NaN,0,1,NaN,NaN,1,0.674741,-0.094838,0.064071,0.120689,0.07862,-0.044581,-0.007965,0.075727,-0.020062,0.0134,-0.045647,0.038072,0.136361,-0.130969,-0.00347,-0.000044,0.045869,-0.118779,0.193597,0.068622,0.015299,-0.101242,-0.032575,-0.147466,0.007445,0.014106,0.024168,0.068616,-0.038258,0.024172,-0.006262,-0.021652,0.093989,-0.101307,0.039585,-0.028217,-0.01915,-0.008478,-0.028949,0.087036,0.001345,0.164268,0.015164,-0.01357,0.016143,0.024886,0.058269,0.038773,-0.028811,0.040317,-0.056209,0.016928,0.036937,-0.093447,-0.010605,-0.025806,0.038835,0.02343,0.045298,-0.032132,0.015802,0.069239,-0.047025,0.090059,-0.010439,-0.070901,0.038858,0.016694,-0.00945,0.030981,0.010684,-0.036654,-0.005841,-0.033931,0.023448,0.050345,0.054878,0.018441,0.001278,-0.071525,0.056539,-0.061781,0.009646,0.04596,-0.02273,-0.019633,0.014407,0.084057,-0.014263,0.049983,-0.014829,0.005969,-0.028859,0.001031,0.004798,0.055644,-0.043054,-0.001607,-0.008072,0.069868,-0.079296,-0.038375,0.02895,-0.022211,0.027837,-0.014224,0.036279,0.022778,-0.017879,-0.045049,-0.021591,-0.001102,0.006996,-0.050101,-0.049195,0.018187,0.048789,0.010675,0.0093,-0.062543,-0.008429,0.007657,0.000647,0.024386,-0.003121,-0.008551,-0.026046,-0.010398,0.030371,-0.044152,-0.046196,0.043078,0.035404,-0.003596,-0.038555,-0.057543,0.051321,-0.011383,-0.027394,0.0324,-0.027513,-0.001846,0.019531,-0.04306,-0.008246,-0.03657,-0.008913,0.039259,0.006606,-0.000538
1,2022-02-24 01:00:00,2,49.2336,28.4486,2.8,-0.3,80.5,0.3,100.0,4.17,0.0,0.0,27.7,10.8,312.0,1023.4,82.5,60.4,5.4,3.0,0.77,2.1,-0.4,89.80,0.0,0.0,0.0,16.6,8.3,289.2,1021.0,97.9,0.0,0.1,0.0,False,False,False,True,False,True,False,False,2022,2,3,1,Vinnytsia,Europe/Kiev,2022-02-24,06:58:49,17:40:52,01:00:00,Вінницька,0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0.0,0.0,2,0.674741,-0.094838,0.064071,0.120689,0.07862,-0.044581,-0.007965,0.075727,-0.020062,0.0134,-0.045647,0.038072,0.136361,-0.130969,-0.00347,-0.000044,0.045869,-0.118779,0.193597,0.068622,0.015299,-0.101242,-0.032575,-0.147466,0.007445,0.014106,0.024168,0.068616,-0.038258,0.024172,-0.006262,-0.021652,0.093989,-0.101307,0.039585,-0.028217,-0.01915,-0.008478,-0.028949,0.087036,0.001345,0.164268,0.015164,-0.01357,0.016143,0.024886,0.058269,0.038773,-0.028811,0.040317,-0.056209,0.016928,0.036937,-0.093447,-0.010605,-0.025806,0.038835,0.02343,0.045298,-0.032132,0.015802,0.069239,-0.047025,0.090059,-0.010439,-0.070901,0.038858,0.016694,-0.00945,0.030981,0.010684,-0.036654,-0.005841,-0.033931,0.023448,0.050345,0.054878,0.018441,0.001278,-0.071525,0.056539,-0.061781,0.009646,0.04596,-0.02273,-0.019633,0.014407,0.084057,-0.014263,0.049983,-0.014829,0.005969,-0.028859,0.001031,0.004798,0.055644,-0.043054,-0.001607,-0.008072,0.069868,-0.079296,-0.038375,0.02895,-0.022211,0.027837,-0.014224,0.036279,0.022778,-0.017879,-0.045049,-0.021591,-0.001102,0.006996,-0.050101,-0.049195,0.018187,0.048789,0.010675,0.0093,-0.062543,-0.008429,0.007657,0.000647,0.024386,-0.003121,-0.008551,-0.026046,-0.010398,0.030371,-0.044152,-0.046196,0.043078,0.035404,-0.003596,-0.038555,-0.057543,0.051321,-0.011383,-0.027394,0.0324,-0.027513,-0.001846,0.019531,-0.04306,-0.008246,-0.03657,-0.008913,0.039259,0.006606,-0.000538
2,2022-02-24 02:00:00,2,49.2336,28.4486,2.8,-0.3,80.5,0.3,100.0,4.17,0.0,0.0,27.7,10.8,312.0,1023.4,82.5,60.4,5.4,3.0,0.77,2.0,-0.3,90.44,0.0,0.0,0.0,27.7,7.6,287.6,1021.0,98.2,0.0,0.1,0.0,False,False,False,True,False,True,False,False,2022,2,3,2,Vinnytsia,Europe/Kiev,2022-02-24,06:58:49,17:40:52,02:00:00,Вінницька,0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0.0,0.0,3,0.674741,-0.094838,0.064071,0.120689,0.07862,-0.044581,-0.007965,0.075727,-0.020062,0.0134,-0.045647,0.038072,0.136361,-0.130969,-0.00347,-0.000044,0.045869,-0.118779,0.193597,0.068622,0.015299,-0.101242,-0.032575,-0.147466,0.007445,0.014106,0.024168,0.068616,-0.038258,0.024172,-0.006262,-0.021652,0.093989,-0.101307,0.039585,-0.028217,-0.01915,-0.008478,-0.028949,0.087036,0.001345,0.164268,0.015164,-0.01357,0.016143,0.024886,0.058269,0.038773,-0.028811,0.040317,-0.056209,0.016928,0.036937,-0.093447,-0.010605,-0.025806,0.038835,0.02343,0.045298,-0.032132,0.015802,0.069239,-0.047025,0.090059,-0.010439,-0.070901,0.038858,0.016694,-0.00945,0.030981,0.010684,-0.036654,-0.005841,-0.033931,0.023448,0.050345,0.054878,0.018441,0.001278,-0.071525,0.056539,-0.061781,0.009646,0.04596,-0.02273,-0.019633,0.014407,0.084057,-0.014263,0.049983,-0.014829,0.005969,-0.028859,0.001031,0.004798,0.055644,-0.043054,-0.001607,-0.008072,0.069868,-0.079296,-0.038375,0.02895,-0.022211,0.027837,-0.014224,0.036279,0.022778,-0.017879,-0.045049,-0.021591,-0.001102,0.006996,-0.050101,-0.049195,0.018187,0.048789,0.010675,0.0093,-0.062543,-0.008429,0.007657,0.000647,0.024386,-0.003121,-0.008551,-0.026046,-0.010398,0.030371,-0.044152,-0.046196,0.043078,0.035404,-0.003596,-0.038555,-0.057543,0.051321,-0.011383,-0.027394,0.0324,-0.027513,-0.001846,0.019531,-0.04306,-0.008246,-0.03657,-0.008913,0.039259,0.006606,-0.000538
3,2022-02-24 03:00:00,2,49.2336,28.4486,2.8,-0.3,80.5,0.3,100.0,4.17,0.0,0.0,27.7,10.8,312.0,1023.4,82.5,60.4,5.4,3.0,0.77,1.9,-0.3,91.75,0.0,0.0,0.0,15.1,7.2,288.9,1021.0,98.8,0.0,0.1,0.0,False,False,False,True,False,True,False,False,2022,2,3,3,Vinnytsia,Europe/Kiev,2022-02-24,06:58:49,17:40:52,03:00:00,Вінницька,0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0.0,0.0,4,0.674741,-0.094838,0.064071,0.120689,0.07862,-0.044581,-0.007965,0.075727,-0.020062,0.0134,-0.045647,0.038072,0.136361,-0.130969,-0.00347,-0.000044,0.045869,-0.118779,0.193597,0.068622,0.015299,-0.101242,-0.032575,-0.147466,0.007445,0.014106,0.024168,0.068616,-0.038258,0.024172,-0.006262,-0.021652,0.093989,-0.101307,0.039585,-0.028217,-0.01915,-0.008478,-0.028949,0.087036,0.001345,0.164268,0.015164,-0.01357,0.016143,0.024886,0.058269,0.038773,-0.028811,0.040317,-0.056209,0.016928,0.036937,-0.093447,-0.010605,-0.025806,0.038835,0.02343,0.045298,-0.032132,0.015802,0.069239,-0.047025,0.090059,-0.010439,-0.070901,0.038858,0.016694,-0.00945,0.030981,0.010684,-0.036654,-0.005841,-0.033931,0.023448,0.050345,0.054878,0.018441,0.001278,-0.071525,0.056539,-0.061781,0.009646,0.04596,-0.02273,-0.019633,0.014407,0.084057,-0.014263,0.049983,-0.014829,0.005969,-0.028859,0.001031,0.004798,0.055644,-0.043054,-0.001607,-0.008072,0.069868,-0.079296,-0.038375,0.02895,-0.022211,0.027837,-0.014224,0.036279,0.022778,-0.017879,-0.045049,-0.021591,-0.001102,0.006996,-0.050101,-0.049195,0.018187,0.048789,0.010675,0.0093,-0.062543,-0.008429,0.007657,0.000647,0.024386,-0.003121,-0.008551,-0.026046,-0.010398,0.030371,-0.044152,-0.046196,0.043078,0.035404,-0.003596,-0.038555,-0.057543,0.051321,-0.011383,-0.027394,0.0324,-0.027513,-0.001846,0.019531,-0.04306,-0.008246,-0.03657,-0.008913,0.039259,0.006606,-0.000538
4,2022-02-24 04:00:00,2,49.2336,28.4486,2.8,-0.3,80.5,0.3,100.0,4.17,0.0,0.0,27.7,10.8,312.0,1023.4,82.5,60.4,5.4,3.0,0.77,1.8,-0.2,92.40,0.0,0.0,0.0,13.7,6.5,290.4,1021.0,100.0,0.0,0.1,0.0,False,False,False,True,False,True,False,False,2022,2,3,4,Vinnytsia,Europe/Kiev,2022-02-24,06:58:49,17:40:52,04:00:00,Вінницька,0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0.0,0.0,5,0.674741,-0.094838,0.064071,0.120689,0.07862,-0.044581,-0.007965,0.075727,-0.020062,0.0134,-0.045647,0.038072,0.136361,-0.130969,-0.00347,-0.000044,0.045869,-0.118779,0.193597,0.068622,0.015299,-0.101242,-0.032575,-0.147466,0.007445,0.014106,0.024168,0.068616,-0.038258,0.024172,-0.006262,-0.021652,0.093989,-0.101307,0.039585,-0.028217,-0.01915,-0.008478,-0.028949,0.087036,0.001345,0.164268,0.015164,-0.01357,0.016143,0.024886,0.058269,0.038773,-0.028811,0.040317,-0.056209,0.016928,0.036937,-0.093447,-0.010605,-0.025806,0.038835,0.02343,0.045298,-0.032132,0.015802,0.069239,-0.047025,0.090059,-0.010439,-0.070901,0.038858,0.016694,-0.00945,0.030981,0.010684,-0.036654,-0.005841,-0.033931,0.023448,0.050345,0.054878,0.018441,0.001278,-0.071525,0.056539,-0.061781,0.009646,0.04596,-0.02273,-0.019633,0.014407,0.084057,-0.014263,0.049983,-0.014829,0.005969,-0.028859,0.001031,0.004798,0.055644,-0.043054,-0.001607,-0.008072,0.069868,-0.079296,-0.038375,0.02895,-0.022211,0.027837,-0.014224,0.036279,0.022778,-0.017879,-0.045049,-0.021591,-0.001102,0.006996,-0.050101,-0.049195,0.018187,0.048789,0.010675,0.0093,-0.062543,-0.008429,0.007657,0.000647,0.024386,-0.003121,-0.008551,-0.026046,-0.010398,0.030371,-0.044152,-0.046196,0.043078,0.035404,-0.003596,-0.038555,-0.057543,0.051321,-0.011383,-0.027394,0.0324,-0.027513,-0.001846,0.019531,-0.04306,-0.008246,-0.03657,-0.008913,0.039259,0.006606,-0.000538
5,2022-02-24 05:00:00,2,49.2336,28.4486,2.8,-0.3,80.5,0.3,100.0,4.17,0.0,0.0,27.7,10.8,312.0,1023.4,82.5,60.4,5.4,3.0,0.77,2.1,-1.0,90.45,0.0,0.0,0.0,12.6,10.8,300.0,1021.8,100.0,0.0,0.1,0.0,False,False,False,True,False,True,False,False,2022,2,3,5,Vinnytsia,Europe/Kiev,2022-02-24,06:58:49,17:40:52,05:00:00,Вінницька,0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0.0,0.0,6,0.674741,-0.094838,0.064071,0.120689,0.07862,-0.044581,-0.007965,0.075727,-0.020062,0.0134,-0.045647,0.038072,0.136361,-0.130969,-0.00347,-0.000044,0.045869,-0.118779,0.193597,0.068622,0.015299,-0.101242,-0.032575,-0.147466,0.007445,0.014106,0.024168,0.068616,-0.038258,0.024172,-0.006262,-0.021652,0.093989,-0.101307,0.039585,-0.028217,-0.01915,-0.008478,-0.028949,0.087036,0.001345,0.164268,0.015164,-0.01357,0.016143,0.024886,0.058269,0.038773,-0.028811,0.040317,-0.056209,0.016928,0.036937,-0.093447,-0.010605,-0.025806,0.038835,0.02343,0.045298,-0.032132,0.015802,0.069239,-0.047025,0.090059,-0.010439,-0.070901,0.038858,0.016694,-0.00945,0.030981,0.010684,-0.036654,-0.005841,-0.033931,0.023448,0.050345,0.054878,0.018441,0.001278,-0.071525,0.056539,-0.061781,0.009646,0.04596,-0.02273,-0.019633,0.014407,0.084057,-0.014263,0.049983,-0.014829,0.005969,-0.028859,0.001031,0.004798,0.055644,-0.043054,-0.001607,-0.008072,0.069868,-0.079296,-0.038375,0.02895,-0.022211,0.027837,-0.014224,0.036279,0.022778,-0.017879,-0.045049,-0.021591,-0.001102,0.006996,-0.050101,-0.049195,0.018187,0.048789,0.010675,0.0093,-0.062543,-0.008429,0.007657,0.000647,0.024386,-0.003121,-0.008551,-0.026046,-0.010398,0.030371,-0.044152,-0.046196,0.043078,0.035404,-0.003596,-0.038555,-0.057543,0.051321,-0.011383,-0.027394,0.0324,-0.027513,-0.001846,0.019531,-0.04306,-0.008246,-0.03657,-0.008913,0.039259,0.006606,-0.000538
6,2022-02-24 06:00:00,2,49.2336,28.4486,2.8,-0.3,80.5,0.3,100.0,4.17,0.0,0.0,27.7,10.8,312.0,1023.4,82.5,60.4,5.4,3.0,0.77,1.7,0.1,93.07,0.0,0.0,0.0,12.2,5.4,297.1,1022.0,98.0,0.0,0.0,0.0,False,False,False,True,False,True,False,False,2022,2,3,6,Vinnytsia,Europe/Kiev,2022-02-24,06:58:49,17:40:52,06:00:00,Вінницька,0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0.0,0.0,7,0.674741,-0.094838,0.064071,0.120689,0.07862,-0.044581,-0.007965,0.075727,-0.020062,0.0134,-0.045647,0.038072,0.136361,-0.130969,-0.00347,-0.000044,0.045869,-0.118779,0.193597,0.068622,0.015299,-0.101242,-0.032575,-0.147466,0.007445,0.014106,0.024168,0.068616,-0.038258,0.024172,-0.006262,-0.021652,0.093989,-0.101307,0.039585,-0.028217,-0.01915,-0.008478,-0.028949,0.087036,0.001345,0.164268,0.015164,-0.01357,0.016143,0.024886,0.058269,0.038773,-0.028811,0.040317,-0.056209,0.016928,0.036937,-0.093447,-0.010605,-0.025806,0.038835,0.02343,0.045298,-0.032132,0.015802,0.069239,-0.047025,0.090059,-0.010439,-0.070901,0.038858,0.016694,-0.00945,0.030981,0.010684,-0.036654,-0.005841,-0.033931,0.023448,0.050345,0.054878,0.018441,0.001278,-0.071525,0.056539,-0.061781,0.009646,0.04596,-0.02273,-0.019633,0.014407,0.084057,-0.014263,0.049983,-0.014829,0.005969,-0.028859,0.001031,0.004798,0.055644,-0.043054,-0.001607,-0.008072,0.069868,-0.079296,-0.038375,0.02895,-0.022211,0.027837,-0.014224,0.036279,0.022778,-0.017879,-0.045049,-0.021591,-0.001102,0.006996,-0.050101,-0.049195,0.018187,0.048789,0.010675,0.0093,-0.062543,-0.008429,0.007657,0.000647,0.024386,-0.003121,-0.008551,-0.026046,-0.010398,0.030371,-0.044152,-0.046196,0.043078,0.035404,-0.003596,-0.038555,-0.057543,0.051321,-0.011383,-0.027394,0.0324,-0.027513,-0.001846,0.019531,-0.04306,-0.008246,-0.03657,-0.008913,0.039259,0.006606,-0.000538
7,2022-02-24 07:00:00,2,49.2336,28.4486,2.8,-0.3,80.5,0.3,100.0,4.17,0.0,0.0,27.7,10.8,312.0,1023.4,82.5,60.4,5.4,3.0,0.77,1.5,1.5,93.73,0.0,0.0,0.0,10.1,4.3,291.8,1023.0,96.4,0.0,0.1,0.0,False,False,False,True,False,True,False,False,2022,2,3,7,Vinnytsia,Europe/Kiev,2022-02-24,06:58:49,17:40:52,07:00:00,Вінницька,0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,0.0,0.0,8,0.674741,-0.094838,0.064071,0.120689,0.07862,-0.044581,-0.007965,0.075727,-0.020062,0.0134,-0.045647,0.038072,0.136361,-0.130969,-0.00347,-0.000044,0.045869,-0.118779,0.193597,0.068622,0.015299,-0.101242,-0.032575,-0.147466,0.007445,0.014106,0.024168,0.068616,-0.038258,0.024172,-0.006262,-0.021652,0.093989,-0.101307,0.039585,-0.028217,-0.01915,-0.008478,-0.028949,0.087036,0.001345,0.164268,0.015164,-0.01357,0.016143,0.024886,0.058269,0.038773,-0.028811,0.040317,-0.056209,0.016928,0.036937,-0.093447,-0.010605,-0.025806,0.038835,0.02343,0.045298,-0.032132,0.015802,0.069239,-0.047025,0.090059,-0.010439,-0.070901,0.038858,0.016694,-0.00945,0.030981,0.010684,-0.036654,-0.005841,-0.033931,0.023448,0.050345,0.054878,0.018441,0.001278,-0.071525,0.056539,-0.061781,0.009646,0.04596,-0.02273,-0.019633,0.014407,0.084057,-0.014263,0.049983,-0.014829,0.005969,-0.028859,0.001031,0.004798,0.055644,-0.043054,-0.001607,-0.008072,0.069868,-0.079296,-0.038375,0.02895,-0.022211,0.027837,-0.014224,0.036279,0.022778,-0.017879,-0.045049,-0.021591,-0.001102,0.006996,-0.050101,-0.049195,0.018187,0.048789,0.010675,0.0093,-0.062543,-0.008429,0.007657,0.000647,0.024386,-0.003121,-0.008551,-0.026046,-0.010398,0.030371,-0.044152,-0.046196,0.043078,0.035404,-0.003596,-0.038555,-0.057543,0.051321,-0.011383,-0.027394,0.0324,-0.027513,-0.001846,0.019531,-0.04306,-0.008246,-0.03657,-0.008913,0.039259,0.006606,-0.000538
8,2022-02-24 08:00:00,2,49.2336,28.4486,2.8,-0.3,80.5,0.3,100.0,4.17,0.0,0.0,27.7,10.8,312.0,1023.4,82.5,60.4,5.4,3.0,0.77,1.4,-0.9,95.09,0.3,100.0,0.0,16.2,7.2,310.0,1024.0,90.0,100.4,0.4,1.0,False,False,False,True,False,False,False,True,2022,2,3,8,Vinnytsia,Europe/Kiev,2022-02-24,06:58:49,17:40:52,08:00:00,Вінницька,0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,1.0,0.0,9,0.674741,-0.094838,0.064071,0.120689,0.07862,-0.044581,-0.007965,0.075727,-0.020062,0.0134,-0.045647,0.038072,0.136361,-0.130969,-0.00347,-0.000044,0.045869,-0.118779,0.193597,0.068622,0.015299,-0.101242,-0.032575,-0.147466,0.007445,0.014106,0.024168,0.068616,-0.038258,0.024172,-0.006262,-0.021652,0.093989,-0.101307,0.039585,-0.028217,-0.01915,-0.008478,-0.028949,0.087036,0.001345,0.164268,0.015164,-0.01357,0.016143,0.024886,0.058269,0.038773,-0.028811,0.040317,-0.056209,0.016928,0.036937,-0.093447,-0.010605,-0.025806,0.038835,0.02343,0.045298,-0.032132,0.015802,0.069239,-0.047025,0.090059,-0.010439,-0.070901,0.038858,0.016694,-0.00945,0.030981,0.010684,-0.036654,-0.005841,-0.033931,0.023448,0.050345,0.054878,0.018441,0.001278,-0.071525,0.056539,-0.061781,0.009646,0.04596,-0.02273,-0.019633,0.014407,0.084057,-0.014263,0.049983,-0.014829,0.005969,-0.028859,0.001031,0.004798,0.055644,-0.043054,-0.001607,-0.008072,0.069868,-0.079296,-0.038375,0.02895,-0.022211,0.027837,-0.014224,0.036279,0.022778,-0.017879,-0.045049,-0.021591,-0.001102,0.006996,-0.050101,-0.049195,0.018187,0.048789,0.010675,0.0093,-0.062543,-0.008429,0.007657,0.000647,0.024386,-0.003121,-0.008551,-0.026046,-0.010398,0.030371,-0.044152,-0.046196,0.043078,0.035404,-0.003596,-0.038555,-0.057543,0.051321,-0.011383,-0.027394,0.0324,-0.027513,-0.001846,0.019531,-0.04306,-0.008246,-0.03657,-0.008913,0.039259,0.006606,-0.000538

In [18]:
df_final.isna().sum()

datetime_hour        0
region_id            0
city_latitude        0
city_longitude       0
day_temp             0
                  ...
isw_topic_145     5760
isw_topic_146     5760
isw_topic_147     5760
isw_topic_148     5760
isw_topic_149     5760
Length: 216, dtype: int64

In [19]:
df_final.fillna(0, inplace=True)

In [20]:
df_final.isna().sum()

datetime_hour     0
region_id         0
city_latitude     0
city_longitude    0
day_temp          0
                 ..
isw_topic_145     0
isw_topic_146     0
isw_topic_147     0
isw_topic_148     0
isw_topic_149     0
Length: 216, dtype: int64

### Feature engineering for isw topics

In [21]:
topic_cols = [c for c in df_final.columns if "isw_topic_" in c]
df_isw_abs = df_final[topic_cols].abs()

df_final['isw_total_intensity'] = df_isw_abs.sum(axis=1)
df_final['isw_topic_std'] = df_isw_abs.std(axis=1)
df_final['isw_topic_max'] = df_isw_abs.max(axis=1)
df_final['isw_topic_mean'] = df_isw_abs.mean(axis=1)

df_final['isw_velocity_24h'] = (
    df_final.groupby('region_id')['isw_total_intensity']
    .diff(24)
    .fillna(0)
)

df_final['isw_intensity_ema'] = (df_final.groupby('region_id')['isw_total_intensity'].transform(lambda x: x.shift(1).ewm(span=24).mean()))

df_final['isw_topic_entropy'] = -(df_isw_abs.div(df_isw_abs.sum(axis=1), axis=0) * np.log(df_isw_abs.div(df_isw_abs.sum(axis=1), axis=0) + 1e-9)).sum(axis=1)

isw_cols = ['isw_velocity_24h', 'isw_intensity_ema', 'isw_topic_entropy']
df_final[isw_cols] = df_final[isw_cols].fillna(0)

In [22]:
df_final.sample(10)

,datetime_hour,region_id,city_latitude,city_longitude,day_temp,day_dew,day_humidity,day_precip,day_precipprob,day_precipcover,day_snow,day_snowdepth,day_windgust,day_windspeed,day_winddir,day_pressure,day_cloudcover,day_solarradiation,day_solarenergy,day_uvindex,day_moonphase,hour_temp,hour_feelslike,hour_humidity,hour_precip,hour_precipprob,hour_snow,hour_windgust,hour_windspeed,hour_winddir,hour_pressure,hour_cloudcover,hour_solarradiation,hour_solarenergy,hour_uvindex,day_conditions_simple_Clear,day_conditions_simple_Cloudy,day_conditions_simple_Rain,day_conditions_simple_Snow,hour_conditions_simple_Clear,hour_conditions_simple_Cloudy,hour_conditions_simple_Rain,hour_conditions_simple_Snow,year,month,day_of_week,hour,city_name,city_timezone,day_datetime,day_sunrise,day_sunset,hour_datetime,region_key,alarm_active,alarm_minutes_in_hour,alarm_lag_1,alarm_lag_3,alarm_lag_6,alarm_lag_12,alarms_in_last_24h,is_weekend,is_night,total_active_alarms_lag1,neighbour_alarms,hours_since_last_alarm,isw_topic_0,isw_topic_1,isw_topic_2,isw_topic_3,isw_topic_4,isw_topic_5,isw_topic_6,isw_topic_7,isw_topic_8,isw_topic_9,isw_topic_10,isw_topic_11,isw_topic_12,isw_topic_13,isw_topic_14,isw_topic_15,isw_topic_16,isw_topic_17,isw_topic_18,isw_topic_19,isw_topic_20,isw_topic_21,isw_topic_22,isw_topic_23,isw_topic_24,isw_topic_25,isw_topic_26,isw_topic_27,isw_topic_28,isw_topic_29,isw_topic_30,isw_topic_31,isw_topic_32,isw_topic_33,isw_topic_34,isw_topic_35,isw_topic_36,isw_topic_37,isw_topic_38,isw_topic_39,isw_topic_40,isw_topic_41,isw_topic_42,isw_topic_43,isw_topic_44,isw_topic_45,isw_topic_46,isw_topic_47,isw_topic_48,isw_topic_49,isw_topic_50,isw_topic_51,isw_topic_52,isw_topic_53,isw_topic_54,isw_topic_55,isw_topic_56,isw_topic_57,isw_topic_58,isw_topic_59,isw_topic_60,isw_topic_61,isw_topic_62,isw_topic_63,isw_topic_64,isw_topic_65,isw_topic_66,isw_topic_67,isw_topic_68,isw_topic_69,isw_topic_70,isw_topic_71,isw_topic_72,isw_topic_73,isw_topic_74,isw_topic_75,isw_topic_76,isw_topic_77,isw_topic_78,isw_topic_79,isw_topic_80,isw_topic_81,isw_topic_82,isw_topic_83,isw_topic_84,isw_topic_85,isw_topic_86,isw_topic_87,isw_topic_88,isw_topic_89,isw_topic_90,isw_topic_91,isw_topic_92,isw_topic_93,isw_topic_94,isw_topic_95,isw_topic_96,isw_topic_97,isw_topic_98,isw_topic_99,isw_topic_100,isw_topic_101,isw_topic_102,isw_topic_103,isw_topic_104,isw_topic_105,isw_topic_106,isw_topic_107,isw_topic_108,isw_topic_109,isw_topic_110,isw_topic_111,isw_topic_112,isw_topic_113,isw_topic_114,isw_topic_115,isw_topic_116,isw_topic_117,isw_topic_118,isw_topic_119,isw_topic_120,isw_topic_121,isw_topic_122,isw_topic_123,isw_topic_124,isw_topic_125,isw_topic_126,isw_topic_127,isw_topic_128,isw_topic_129,isw_topic_130,isw_topic_131,isw_topic_132,isw_topic_133,isw_topic_134,isw_topic_135,isw_topic_136,isw_topic_137,isw_topic_138,isw_topic_139,isw_topic_140,isw_topic_141,isw_topic_142,isw_topic_143,isw_topic_144,isw_topic_145,isw_topic_146,isw_topic_147,isw_topic_148,isw_topic_149,isw_total_intensity,isw_topic_std,isw_topic_max,isw_topic_mean,isw_velocity_24h,isw_intensity_ema,isw_topic_entropy
73233,2024-06-20 12:00:00,4,48.47530,35.01600,23.5,15.7,64.8,4.0,100.0,4.17,0.0,0.0,59.4,32.0,273.8,1013.8,29.8,267.2,23.1,9.0,0.45,31.2,30.2,33.37,0.0,0.0,0.0,43.2,18.0,230.0,1011.4,30.0,840.9,3.0,8.0,False,False,True,False,False,True,False,False,2024,6,3,12,Dnipro,Europe/Kiev,2024-06-20,04:38:06,20:45:16,12:00:00,Дніпропетровська,0,0.000000,1.0,1.0,1.0,1.0,16.0,0,0,7.0,4.0,0,0.781924,0.003673,-0.121777,0.133436,-0.103326,0.028733,0.071164,-0.076727,-0.039831,0.009987,-0.067451,0.230894,0.005245,-0.024218,-0.150659,0.032677,0.002412,-0.088437,0.079464,0.021469,0.055906,-0.089400,0.008470,-0.026138,0.044901,-0.077218,-0.034957,0.004697,-0.044450,-0.009650,-0.047205,-0.081461,0.031805,0.077347,0.014988,6.351610e-02,0.019505,0.021109,-0.000564,-0.005236,-0.017125,0.029082,-0.046421,0.038323,0.019931,0.017923,-0.062402,0.037689,0.012455,0.040094,-0.006797,-0.048915,-0.031236,-0.009552,0.003454,-0.046366,-0.019667,-0.016434,-0.020673,0.007275,-0.005820,-0.023051,0.040936,-0.017022,0.029128,0.005845,0.013444,-0.019352,0.032613,-0.008461,-0.010770,0.012912,0.029013,0.032479,-0.003776,-0.009401,0.001724,0.023986,0.013319,0.016407,-0.033253,0.029869,-0.020772,-0.002735,-0.018334,-0.047127,0.029030,0.027661,-0.037401,-0.007376,0.023956,-0.026719,0.013238,-0.012964,-0.027414,0.023247,-0.029395,-0.021415,0.020823,0.023107,0.014182,0.017910,-0.003156,0.001918,0.024805,-0.011933,-0.016784,-0.037094,-0.019008,-0.048109,0.022210,0.016186,-0.010441,-0.034775,0.033558,0.035264,-0.016760,-0.015164,0.003845,0.031772,-0.004623,0.001835,0.006091,-0.004135,0.002037,-0.009207,-0.030671,0.017422,0.032758,-0.018927,0.012237,0.034094,-0.005265,0.027209,-0.008634,-0.045915,-0.010195,-0.053530,-0.022272,-0.011860,0.006293,-0.004884,-0.007623,-0.002902,-0.032608,0.007441,-0.019598,0.000555,-0.015989,-0.003678,5.064499,0.068710,0.781924,0.033763,0.256423,4.985320,4.314187
347963,2022-08-15 15:00:00,16,49.58790,34.55170,25.2,14.9,54.1,0.0,0.0,0.00,0.0,0.0,47.5,21.6,60.3,1008.8,91.4,167.3,14.4,8.0,0.58,27.1,27.8,54.69,0.0,0.0,0.0,40.7,10.8,70.0,1009.2,90.0,733.0,2.6,7.0,False,True,False,False,False,True,False,False,2022,8,0,15,Poltava,Europe/Kiev,2022-08-15,05:32:13,19:59:29,15:00:00,Полтавська,0,0.000000,0.0,0.0,0.0,0.0,2.0,0,0,0.0,0.0,20,0.704722,-0.208074,0.196417,-0.073197,-0.093052,0.102865,-0.001354,0.082439,0.178360,-0.127413,0.057681,-0.014374,-0.069999,-0.158090,-0.071652,0.063943,-0.081474,0.007285,-0.066852,-0.032249,-0.099653,0.001244,0.021908,-0.082567,0.070093,-0.015985,-0.082662,-0.089299,0.010274,-0.035376,0.029777,-0.041074,-0.079438,-0.037407,-0.027510,-1.433647e-02,-0.013688,-0.018167,0.004406,-0.024864,-0.009164,-0.041454,-0.009608,-0.002088,0.017936,0.028483,-0.023652,0.022182,-0.026641,-0.026983,0.008899,0.057657,-0.009638,0.015956,0.004156,-0.001313,-0.006508,0.042414,0.035044,-0.036819,-0.013316,-0.013635,-0.046083,-0.005398,-0.007866,-0.010691,0.005687,0.036981,0.037945,-0.023766,0.016272,0.024459,0.002446,0.023106,0.007458,0.025093,0.020467,0.003325,-0.001854,0.065807,0.059970,-0.054273,-0.018297,-0.008151,0.012368,-0.033600,-0.003572,-0.009445,-0.022493,0.012438,0.045761,0.066082,-0.005363,-0.030152,-0.010824,-0.028822,-0.049012,-0.024779,0.033557,0.031566,-0.018406,0.033619,0.043357,0.039431,0.035900,-0.039345,-0.002906,-0.042063,0.006342,-0.025490,-0.004588,-0.080708,-0.004339,0.011230,0.004780,0.008650,0.002515,0.016145,-0.042211,0.028473,0.030299,0.020873,0.038911,0.010478,-0.016105,0.033183,0.011993,0.031910,-0.005054,0.000933,-0.013410,0.017076,0.019191,0.010718,0.030403,0.002890,0.017285,-0.012158,-0.044992,-0.020730,-0.035100,0.031473,0.017622,0.011292,0.044321,0.011155,-0.018642,-0.037873,0.005411,0.037323,5.699296,0.065255,0.704722,0.037995,0.072450,5.646593,4.386204
68099,2023-11-19 13:00:00,4,48.47530,35.01600,1.2,-0.2,90.9,7.0,100.0,4.17,3.5,0.7,51.5,32.4,45.7,1011.5,100.0,20.2,1.6,1.0,0.22,2.7,-2.8,89.84,0.0,0.0,0.0,49.7,27.7,48.4,1010.0,100.0,92.0,0.3,1.0,False,False,False,True,False,True,False,False,2023,11,6,13,Dnipro,Europe/Kiev,2023-11-19,06:53:10,15:56:52,13:00:00,Дніпропетровська,0,0.000000,0.0,0.0,0.0,0.0,4.0,1,0,2.0,1.0,12,0.784126,-0.073201,-0.113016,-0.167109,0.020662,-0.176071,0.100813,-0.120052,0.155610,0.203659,0.088117,-0.008140,0.003150,0.001015,-0.023152,-0.095309,0.068095,0.061787,0.058856,-0.101661,-0.069119,-0.013485,-0.016616,0.021146,0.032456,0.000482,0.023885,-0.062510,0.037184,-0.025902,0.008533,-0.002100,0.007639,0.014834,0.027069,9.874313e-03,0.072014,-0.054518,-0.039926,-0.033472,-0.013089,0.020322,0.031056,-0.010356,-0.024706,0.066311,-0.031915,0.023316,-0.007604,0.000458,-0.025856,0.072562,-0.004148,-0.024221,-0.062618,-0.022353,0.027813,0.018454,0.037091,0.028304,0.068521,-0.040170,0.022035,0.002913,0.014195,0.008224,0.037975,0.015670,0.006386,-0.004064,0.011180,-0.008273,-0.006630,0.045046,0.014524,0.010444,0.004532,-0.011358,-0.007483,0.013947,-0.028980,0.015559,-0.018987,-0.012112,0.008435,0.024186,-0.000135,-0.035821,-0.015254,0.001302,0.022620,-0.014560,-0.007872,-0.017696,0.008923,0.007688,-0.029926,0.033472,0.001791,-0.001127,0.016875,0.006941,0.016202,0.009177,-0.021624,0.004899,0.003622,0.014754,-0.001707,0.006934,0.002561,0.006865,0.029097,-0.027539,-0.028444,-0.014391,-0.001607,-0.008865,-0.013541,0.028181,-0.018164,-0.021358,-0.031197,0.006008,-0.017696,0.008305,-0.001629,-0.005662,-0.003500,-0.001552,0.009012,-0.004707,0.004873,-0.023242,0.004777,-0.006767,0.021544,-0.017498,0.027294,0.010838,0.022335,0.009303,-0.026711,-0.019106,0.022527,0.004677,0.013548,-0.005989,-0.006595,0.005316,4.854485,0.070671,0.784126,0.032363,-0.032579,4.839194,4.181595
83682,2022-08-23 19:00:00,5,48.00200,37.81450,26.8,7.0,29.5,0.0,0.0,0.00,0.0,0.0,60.5,29.2,93.4,1016.3,0.2,275.4,23.6,8.0,0.85,30.2,28.5,23.66,0.0,0.0,0.0,43.2,16.6,86.3,1016.0,0.0,102.0,0.4,1.0,True,False,False,False,True,False,False,False,2022,8,1,19,Donetsk,Europe/Kiev,2022-08-23,05:34:04,19:27:54,19:00:00,Донецька,0,0.000000,0.0,0.0,0.0,1.0,3.0,0,0,0.0,0.0,11,0.780364,-0.229640,0.161838,-0.078490,-0.059563,0.095218,0.006947,0.066313,0.127415,-0.089982,0.038364,-0.014493,-0.035073,-0.136925,-0.070164,0.058729,-0.090876,0.028814,-0.081170,-0.005364,-0.075675,-0.000355,0.013387,-0.065795,0.090049,-0.018453,-0.066136,-0.043001,-0.020776,-0.007800,0.030750,-0.000132,0.032706,-0.048145,-0.026995,1.178272e-02,-0.008006,0.011140,0.002059,-0.020043,0.012621,0.020153,0.028278,-0.025476,0.035845,-0.051347,0.010473,0.012385,-0.019372,0.010683,-0.041808,-0.016081,0.007671,-0.000547,-0.018006,-0.005411,-0.016706,0.024320,-0.036367,-0.014545,0.050040,-0.016077,-0.007720,0.027949,0.014488,-0.006656,-0.029832,0.046988,0.025864,-0.032837,-0.010046,-0.010250,-0.010705,0.011930,0.015026,0.010559,0.002877,0.007294,-0.033618,-0.017244,-0.011194,0.012227,0.002993,-0.007074,-0.014442,0.033162,-0.003724,-0.026332,0.000497,-0.000300,0.006752,0.001909,-0.012410,0.023120,0.006697,-0.052608,0.011367,-0.015794,0.015131,-0.006873,0.045679,-0.000878,0.011591,-0.042149,0.020761,0.030017,0.006076,0.021383,0.002628,0.005954,-0.008101,0.019104,-0.014913,-0.006324,-0.026555,0.018226,0.017911,0.033053,0.000623,0.026888,-0.012900,-0.042988,-0.015929,-0.002599,0.009477,-0.004965,0.005689,0.026647,0.021177,-0.014698,0.013127,-0.025213,0.004379,-0.018495,-0.022365,0.000208,0.013604,-0.000289,-0.022275,0.031497,-0.013251,0.028735,0.024184,-0.013787,0.010962,0.004208,0.003513,-0.008757,-0.014676,-0.002783,4.701810,0.069183,0.780364,0.031345,-0.320268,4.768482,4.208647
198281,2023-08-25 22:00:00,9,48.92260,24.71470,21.9,15.9,71.8,0.0,0.0,0.00,0.0,0.0,19.1,10.4,231.9,1015.0,52.7,227.2,19.7,7.0,0.31,24.1,24.1,70.93,0.0,0.0,0.0,5.0,2.2,251.6,1014.0,19.3,0.0,0.0,0.0,False,True,False,False,True,False,False,False,2023,8,4,22,Ivano-Frankivsk,Europe/Kiev,2023-08-25,06:27:10,20:18:37,22:00:00,Івано-Франківська,1,31.916667,1.0,0.0,0.0,0.0,4.0,0,0,24.0,4.0,0,0.733104,-0.199633,-0.106856,-0.147239,-0.129401,0.134382,-0.035119,0.197682,0.052499,0.017521,0.155805,0.016512,-0.175057,-0.059262,0.066367,-0.060681,0.080376,-0.103842,-0.007848,-0.060503,0.080001,0.021840,0.054611,0.024572,0.084273,0.122957,0.037802,0.014005,0.018959,-0.020436,-0.036605,0.035428,-0.066159,-0.023517,-0.037761,-1.372790e-02,0.046560,0.004413,-0.040941,-0.039955,-0.019952,0.012143,-0.001499,0.022187,0.008824,0.063159,0.040635,0.012382,-0.022316,0.022505,0.072708,-0.001077,0.026142,0.002614,0.009439,0.034172,0.040008,-0.018167,-0.026945,0.016799,-0.013776,-0.019235,0.006750,-0.012755,0.019105,-0.012782,-0.000397,0.015187,-0.016308,0.001258,0.013523,0.015846,-0.014366,-0.037351,0.007491,-0.005028,-0.023598,-0.007198,0.015007,0.007442,0.025358,-0.005549,-0.020877,0.014726,0.005690,-0.019784,0.015583,-0.015246,-0.014299,0.001046,0.001274,-0.025768,0.008289,-0.017887,0.003038,0.015966,0.022401,-0.042095,0.004543,0.023169,-0.005160,-0.022568,0.048605,0.002888,0.026288,-0.007218,0.006405,0.010855,-0.025207,0.016919,-0.013078,-0.031096,0.008749,-0.002125,0.017916,-0.003386,0.016169,-0.010200,-0.002162,-0.002938,-0.007095,-0.010727,0.015743,-0.014112,0.028645,-0.017606,-0.000413,0.010280,0.015917,0.002848,-0.011354,0.001847,-0.015496,-0.009232,0.005211,0.015126,0.020647,0.075087,0.009801,-0.062863,-0.013063,-0.009159,0.038132,-0.045000,-0.000611,-0.002627,-0.021244,-0.014585,-0.011867,0.014363,5.205507,0.068502,0.733104,0.034703,-0.099593,5.222121,4.240773
232845,2024-07-29 03:00:00,10,50.45060,30.52430,20.3,11.7,59.5,1.0,100.0,4.17,0.0,0.0,67.3,33.8,275.2,1010.7,58.4,233.2,20.1,7.0,0.78,20.2,20.2,70.65,0.0,0.0,0.0,57.6,18.0,320.0,1013.6,80.0,0.0,0.0,0.0,False,False,True,False,False,True,False,False,2024,7,0,3,Kyiv,Europe/Kiev,2024-07-29,05:21:50,20:46:08,03:00:00,Київська,0,0.000000,0.0,0.0,0.0,0.0,0.0,0,1,7.0,2.0,43,0.764855,-0.002795,-0.132822,0.077465,-0.179856,0.132012,0.084310,-0.120335,-0.009113,0.067045,-0.140910,-0.246820,0.049470,-0.017700,-0.046153,-0.025590,0.033016,-0.092134,-0.045895,0.026520,-0.032840,0.024395,0.022182,0.063676,0.025626,0.024768,0.023491,0.002358,0.004260,-0.064962,-0.018109,-0.016730,0.009479,-0.014878,-0.019737,-4.175243e-02,-0.011757,-0.026162,0.024460,0.020038,-0.033198,0.010132,0.014678,-0.002441,0.041214,-0.002536,-0.017538,0.036975,0.015861,0.003561,0.044788,-0.003327,0.041261,0.035357,-0.016681,0.017779,0.012498,0.035957,-0.025546,-0.002380,-0.023034,0.056524,0.019914,-0.004271,-0.009169,-0.013380,-0.021821,-0.025139,-0.000668,0.033279,0.040001,-0.026887,0.000950,-0.026079,-0.102484,0.005571,0.028263,0.057699,0.019009,-0.006410,-0.000442,0.030570,0.027130,-0.060861,-0.004691,0.012768,-0.045485,-0.037781,0.006998,0.008889,0.052623,-0.005847,0.000476,0.002679,0.020988,-0.058808,-0.000683,0.001371,0.013208,0.002125,0.004558,0.013964,-0.010749,0.019649,0.015933,-0.008886,0.006268,0.000022,0.024045,0.008623,-0.003506,-0.016608,0.018770,-0.014858,0.006130,0.001641,0.001079,-0.029397,-0.008412,0.000473,0.003441,0.009843,0.007395,0.014070,0.022909,-0.010970,-0.015512,0.003046,-0.023703,0.011311,0.020992,-0.003273,0.031569,-0.027069,0.015813,-0.003045,0.007652,0.036664,0.028686,-0.010005,-0.012748,0.010326,0.009918,-0.002767,0.005441,-0.007337,-0.007699,0.006019,0.044078,0.016592,4.758620,0.069324,0.764855,0.031724,0.504919,4.417587,4.182952
495837,2024-05-28 03:00:00,21,46.64010,32.61420,20.8,11.6,58.0,0.3,100.0,4.17,0.0,0.0,47.5,21.6,81.7,1015.0,79.4,225.9,19.7,7.0,0.67,15.4,15.4,74.54,0.0,0.0,0.0,20.2,7.2,50.0,1016.6,100.0,0.0,0.0,0.0,False,False,True,False,False,True,False,False,2024,5,1,3,Kherson,Europe/Kiev,2024-05-28,05:02:27,20:32:00,03:00:00,Херсонська,1,20.900000,1.0,0.0,0.0,0.0,5.0,0,1,6.0,3.0,0,0.715477,-0.047615,-0.162917,0.130816,-0.059671,0.001929,0.031368,-0.025755,-0.002874,-0.039942,-0.015583,0.044730,0.044228,-0.046267,-0.078965,0.106178,0.191169,0.068379,0.056780,0.073932,0.034090,-0.077422,0.029325,0.016656,0.100416,-0.080795,0.005399,-0.003972,-0.035691,0.048358,-0.007381,-0.010709,-0.029675,0.011792,0.004951,-7.784479e-02,0.004719,-0.040260,0.007944,-0.098841,-0.015358,0.039272,0.025740,-0.051876,0.009744,-0.115931,0.066440,0.049362,0.037725,0.000548,-0.087554,0.032912,-0.043769,0.001583,0.034813,0.081621,-0.033569,0.027890,-0.050270,-0.012274,0.010023,-0.073770,0.060683,0.002183,0.084059,0.026891,-0.013847,-0.060607,0.008695,0.001400,0.030225,0.031970,-0.012570,0.024044,0.034323,0.021359,-0.043290,0.007192,-0.017363,-0.028564,-0.006282,0.015665,-0.058188,0.054683,0.032069,-0.019733,0.052853,-0.012945,-0.019880,0.031009,-0.012995,0.022788,0.052101,0.017678,-0.031674,-0.022736,0.013738,-0.046018,-0.029733,0.043753,0.012668,-0.030669,-0.013589,-0.034083,0.043760,0.042492,0.019535,-0.013311,0.047036,0.018158,-0.062765,-0.056029,-0.010522,-0.064382,0.037196,-0.000813,-0.031947,0.028953,0.038638,0.003017,-0.031604,0.002120,-0.030620,-0.002727,0.008283,0.009020,0.011883,0.061018,-0.012186,-0.006717,-0.019219,-0.027509,-0.037456,0.001238,-0.021409,0.011388,-0.020782,-0.036507,-0.053463,0.034033,-0.045854,-0.028423,-0.046597,-0.036697,0.042298,-0.020941,0.071504,-0.029206,0.008583,-0.027339,6.084834,0.063237,0.715477,0.040566,1.043090,5.202389,4.501459
220984,2023-03-22 20:00:00,10,50.45060,30.52430,9.2,4.8,75.6,0.0,0.0,0.00,0.0,0.0,21.6,10.8,350.9,1016.2,77.0,125.7,10.8,5.0,0.02,9.4,9.4,64.76,0.0,0.0,0.0,10.1,0.0,82.8,1016.8,81.7,0.0,0.0,0.0,False,True,False,False,False,True,False,False,2023,3,2,20,Kyiv,Europe/Kiev,2023-03-22,05:57:12,18:13:33,20:00:00,Київська,0,0.000000,0.0,0.0,0.0,0.0,8.0,0,0,6.0,1.0,8,0.802056,-0.178664,-0.042842,0.099094,0.043268,-0.071824,-0.058606,0.155238,0.032348,0.115999,-0.078090,-0.023474,-0.067687,0.058547,-0.014384,0.009182,-0.020951,0.031470,-0.109891,0.020707,-0.053106,-0.012458,-0.058674,-0.045498,-0.074658,-0.066020,-0.101200,0.008211,-0.033820,-0.042131,0.014562,-0.035922,-0.001232,0.001766,0.024743,8.365439e-03,-0.019218,0.025925,-0.046124,0.008456,0.036485,0.010780,-0.009503,-0.027170,0.018484,-0.024416,-0.004565,0.004461,-0.011248,-0.068181,0.008123,-0.036864,-0.022328,0.013123,-0.006213,0.009566,0.002726,0.041937,0.021410,0.007603,0.057892,0.018245,-0.062162,0.028549,0.021511,-0.017547,0.033701,-0.024337,0.039092,-0.020241,-0.020996,0.058268,-0.015344,-0.008417,0.004860,-0.025091,-0.006518,-0.027033,-0.040286,-0.010649,-0.021902,-0.017521,0.009926,-0.025394,0.016220,0.032925,0.059389,0.010526,0.008622,-0.021376,0.024512,-0.002721,-0.009739,-0.040110,-0.020683,0.009886,0.009689,0.012456,-0.007129,-0.016504,0.017105,-0.048943,0.006140,-0.000815,0.000831,-0.004866,0.014724,0.010994,0.002362,0.001703,-0.011635,0.003377,-0.030903,0.029202,0.023942,-0.063009,-0.000191,0.002754,-0.015998,-0.000773,-0.001195,0.028052,0.026649,0.014590,-0.003386,-0.031515,-0.003456,-0.034881,-0.002954,0.004976,0.003185,0.010286,0.021969,0.001769,0.037409,-0.042057,-0.009214,0.041343,0.018362,-0.043635,-0.003216,-0.019390,0.002027,-0.009129,0.018701,0.032457,0.009141,0.008755,0.005227,0.004708,4.803473,0.069268,0.802056,0.032023,-0.440600,4.885647,4.260166
297468,2022-11-23 16:00:00,14,46.97336,31.98522,4.7,3.3,90.5,1.0,100.0,8.33,0.0,0.0,37.4,18.4,103.2,1012.5,78.6,54.5,4.7,2.0,0.96,7.8,5.4,84.79,0.0,0.0,0.0,27.7,13.0,99.8,1011.0,100.0,21.0,0.1,0.0,False,False,True,False,False,True,False,False,2022,11,2,16,Mykolaiv,Europe/Kiev,2022-11-23,07:06:22,16:10:07,16:00:00,Миколаївська,0,0.000000,1.0,1.0,0.0,0.0,5.0,0,0,24.0,4.0,0,0.810098,-0.200805,0.017439,-0.150582,0.063458,-0.112544,0.062645,-0.072974,0.082168,0.112704,0.048426,0.004333,0.035347,-0.041077,-0.073157,0.089928,-0.081078,0.034880,0.110156,0.070221,0.012277,-0.005342,0.033970,0.056039,-0.041546,0.009491,0.010956,-0.028736,-0.053191,-0.012810,0.015409,0.011443,-0.060288,0.000310,0.006477,1.475020e-07,0.043509,0.026958,0.009103,-0.010912,0.012168,-0.071241,-0.043261,-0.027823,-0.011527,0.053987,-0.038351,0.014126,0.027661,0.035984,0.001639,-0.022299,-0.011899,0.026965,0.010956,0.015409,-0.030731,-0.013394,0.003128,-0.050246,-0.026327,-0.041221,-0.033594,-0.020043,-0.006310,-0.027708,-0.000357,0.023538,-0.000971,0.009158,0.006229,0.013321,-0.031476,-0.029588,-0.001780,0.027302,0.027962,0.014211,-0.029304,0.001902,0.027795,-0.008170,0.003863,0.003323,-0.008949,-0.034749,-0.012936,0.015732,0.030213,-0.001806,0.017981,0.007515,-0.008343,-0.025295,-0.003735,0.007676,-0.023089,0.026540,-0.026926,0.033722,0.016407,0.008367,0.010484,-0.017534,0.025203,-0.014646,-0.029292,0.001931,0.013417,-0.008857,-0.008381,0.004198,0.012003,-0.014612,0.031206,0.017794,0.032232,-0.028833,0.034407,-0.017334,0.014576,0.028083,0.009454,0.002263,-0.028098,-0.013220,-0.010994,0.018946,0.003179,0.005650,0.011660,-0.014270,-0.012259,-0.007562,0.010631,-0.005030,0.010367,-0.004161,0.001883,-0.008591,0.003314,0.013040,-0.004617,-0.004156,-0.004066,-0.009853,0.010117,-0.000763,0.020658,0.015292,4.600130,0.070224,0.810098,0.030668,-0.023934,4.621926,4.206879

### TELEGRAM MERGE

In [23]:
df_tg_matrix = pd.read_csv("../data/telegram_processed_svd.csv")

In [24]:
df_tg_matrix.head()

,date,channel,tg_topic_0,tg_topic_1,tg_topic_2,tg_topic_3,tg_topic_4,tg_topic_5,tg_topic_6,tg_topic_7,tg_topic_8,tg_topic_9,tg_topic_10,tg_topic_11,tg_topic_12,tg_topic_13,tg_topic_14,tg_topic_15,tg_topic_16,tg_topic_17,tg_topic_18,tg_topic_19,tg_topic_20,tg_topic_21,tg_topic_22,tg_topic_23,tg_topic_24,tg_topic_25,tg_topic_26,tg_topic_27,tg_topic_28,tg_topic_29,tg_topic_30,tg_topic_31,tg_topic_32,tg_topic_33,tg_topic_34,tg_topic_35,tg_topic_36,tg_topic_37,tg_topic_38,tg_topic_39,tg_topic_40,tg_topic_41,tg_topic_42,tg_topic_43,tg_topic_44,tg_topic_45,tg_topic_46,tg_topic_47,tg_topic_48,tg_topic_49,tg_topic_50,tg_topic_51,tg_topic_52,tg_topic_53,tg_topic_54,tg_topic_55,tg_topic_56,tg_topic_57,tg_topic_58,tg_topic_59,tg_topic_60,tg_topic_61,tg_topic_62,tg_topic_63,tg_topic_64,tg_topic_65,tg_topic_66,tg_topic_67,tg_topic_68,tg_topic_69,tg_topic_70,tg_topic_71,tg_topic_72,tg_topic_73,tg_topic_74,tg_topic_75,tg_topic_76,tg_topic_77,tg_topic_78,tg_topic_79,tg_topic_80,tg_topic_81,tg_topic_82,tg_topic_83,tg_topic_84,tg_topic_85,tg_topic_86,tg_topic_87,tg_topic_88,tg_topic_89,tg_topic_90,tg_topic_91,tg_topic_92,tg_topic_93,tg_topic_94,tg_topic_95,tg_topic_96,tg_topic_97,tg_topic_98,tg_topic_99,tg_topic_100,tg_topic_101,tg_topic_102,tg_topic_103,tg_topic_104,tg_topic_105,tg_topic_106,tg_topic_107,tg_topic_108,tg_topic_109,tg_topic_110,tg_topic_111,tg_topic_112,tg_topic_113,tg_topic_114,tg_topic_115,tg_topic_116,tg_topic_117,tg_topic_118,tg_topic_119,tg_topic_120,tg_topic_121,tg_topic_122,tg_topic_123,tg_topic_124,tg_topic_125,tg_topic_126,tg_topic_127,tg_topic_128,tg_topic_129,tg_topic_130,tg_topic_131,tg_topic_132,tg_topic_133,tg_topic_134,tg_topic_135,tg_topic_136,tg_topic_137,tg_topic_138,tg_topic_139,tg_topic_140,tg_topic_141,tg_topic_142,tg_topic_143,tg_topic_144,tg_topic_145,tg_topic_146,tg_topic_147,tg_topic_148,tg_topic_149,tg_topic_150,tg_topic_151,tg_topic_152,tg_topic_153,tg_topic_154,tg_topic_155,tg_topic_156,tg_topic_157,tg_topic_158,tg_topic_159,tg_topic_160,tg_topic_161,tg_topic_162,tg_topic_163,tg_topic_164,tg_topic_165,tg_topic_166,tg_topic_167,tg_topic_168,tg_topic_169,tg_topic_170,tg_topic_171,tg_topic_172,tg_topic_173,tg_topic_174,tg_topic_175,tg_topic_176,tg_topic_177,tg_topic_178,tg_topic_179,tg_topic_180,tg_topic_181,tg_topic_182,tg_topic_183,tg_topic_184,tg_topic_185,tg_topic_186,tg_topic_187,tg_topic_188,tg_topic_189,tg_topic_190,tg_topic_191,tg_topic_192,tg_topic_193,tg_topic_194,tg_topic_195,tg_topic_196,tg_topic_197,tg_topic_198,tg_topic_199,tg_topic_200,tg_topic_201,tg_topic_202,tg_topic_203,tg_topic_204,tg_topic_205,tg_topic_206,tg_topic_207,tg_topic_208,tg_topic_209,tg_topic_210,tg_topic_211,tg_topic_212,tg_topic_213,tg_topic_214,tg_topic_215,tg_topic_216,tg_topic_217,tg_topic_218,tg_topic_219,tg_topic_220,tg_topic_221,tg_topic_222,tg_topic_223,tg_topic_224,tg_topic_225,tg_topic_226,tg_topic_227,tg_topic_228,tg_topic_229,tg_topic_230,tg_topic_231,tg_topic_232,tg_topic_233,tg_topic_234,tg_topic_235,tg_topic_236,tg_topic_237,tg_topic_238,tg_topic_239,tg_topic_240,tg_topic_241,tg_topic_242,tg_topic_243,tg_topic_244,tg_topic_245,tg_topic_246,tg_topic_247,tg_topic_248,tg_topic_249
0,2026-03-06 13:06:58,DeepStateUA,0.006988,0.000199,0.019066,0.000954,-0.008572,0.027556,-0.023390,0.082142,0.048557,-0.035442,-0.044857,0.023976,-0.010296,0.314185,0.441313,0.148150,-0.033452,0.013619,-1.517790e-02,0.300137,-0.013806,0.024117,0.032729,-0.075532,-0.055463,0.056108,-0.114965,-0.062816,0.000903,0.040613,0.030642,-0.011243,-0.031933,-0.016561,-0.000002,-0.009349,-0.013026,0.023569,-0.014856,-0.013251,0.003954,0.006923,0.018694,-0.040851,-0.016603,-0.022610,0.020255,-0.044764,-0.014435,-0.000230,-0.005440,-0.015144,0.000328,0.033881,-0.001490,0.004347,0.028966,0.024960,-0.010553,-0.007215,-0.016782,-0.017823,-0.004215,-0.016674,-0.025594,0.012136,0.018104,-0.023220,0.010000,0.012855,-0.056983,-0.036521,-0.008794,-0.007228,-0.026847,-0.062296,0.085056,0.036050,-0.086713,-0.011966,-0.004914,0.141366,-0.055463,-0.088688,0.061813,0.057732,0.016839,-0.002449,0.000986,-0.015949,-0.059070,-0.003215,0.027278,-0.060312,-0.006565,0.040401,-0.027012,0.030306,0.029951,-0.074696,-0.003235,0.014906,0.033469,-0.037257,-0.000254,-0.023586,0.003416,-0.019975,-0.013569,-0.016646,-0.000286,0.008311,-0.014775,-0.005560,-0.015832,-0.004287,-0.005641,0.019341,0.001947,-0.019378,-0.004329,-0.017837,-0.021873,-0.024704,-0.017573,-0.001471,0.055298,-0.001907,-0.015560,0.010959,0.008830,0.013610,-0.038589,0.020823,-0.034751,0.032423,-0.015660,0.027160,0.082206,-0.008323,-0.017703,-0.003846,0.011994,-0.018756,0.032183,0.001488,-0.003756,0.006360,0.029452,0.043348,0.021398,-0.067449,-0.023474,-0.022019,0.022582,0.027935,-0.032891,-0.001852,-0.000252,0.033536,-0.027412,0.039133,-0.011634,-0.036005,-0.007873,0.002068,-0.007386,-0.011691,-0.019126,0.007075,0.013907,0.019937,0.014858,0.020191,-0.025726,0.013726,0.067214,-0.018241,-0.015205,-0.034773,-0.037605,-0.005873,-0.019108,-0.039294,0.006821,-0.001082,0.007128,-0.030109,-0.002517,0.020059,-0.002848,-0.020188,-0.032926,0.020508,-0.008676,-0.005482,0.004211,-0.023763,0.017472,0.002921,-0.007789,-0.011783,0.016696,0.016443,-0.021025,0.001147,-0.001315,-0.018607,-0.003998,-0.010899,0.008551,0.018628,0.011479,0.000386,0.000531,-0.002158,0.010067,-0.002232,0.032518,0.011657,-0.014824,0.011384,-0.015446,-0.008815,-0.010052,0.005703,-0.001860,-0.001866,0.032770,-0.012229,0.004878,0.020139,0.009993,0.017605,0.025128,-0.001467,-0.026995,-0.020391,0.029010,0.040204,-0.025015,-0.009189,0.002957,0.010876,-0.004521,-0.032922,-0.024608,0.001831,0.028593,0.021750
1,2026-03-06 12:57:29,DeepStateUA,0.022407,-0.001962,0.039639,0.001378,-0.027803,0.069329,-0.037687,0.126188,0.023941,-0.028038,-0.035619,0.015229,-0.008888,0.052549,0.052510,-0.028264,-0.017461,-0.048919,-3.464665e-07,-0.004600,0.007378,-0.006132,0.044293,-0.004122,-0.012953,-0.023969,0.033698,0.023532,0.003563,-0.007249,0.049356,-0.024524,-0.027906,0.009350,-0.011559,-0.014335,0.024924,0.011431,-0.000501,0.001054,-0.016655,-0.026000,0.002606,0.049669,-0.012653,0.022710,-0.043217,0.038909,-0.038570,-0.015367,0.052191,0.007416,-0.017443,0.032344,-0.017845,-0.017606,0.016605,-0.004602,0.007640,0.034543,-0.015710,0.016760,0.003032,-0.022000,0.023525,-0.039551,-0.022952,-0.005680,-0.006249,0.026948,0.017350,0.035260,0.004191,-0.003160,0.000994,0.005015,-0.002274,0.005243,0.005334,-0.013808,0.000110,-0.012621,0.017584,-0.008420,-0.008566,-0.044011,-0.008985,0.009480,-0.019268,0.001165,-0.009917,-0.001627,-0.017013,0.029732,-0.029833,-0.013647,0.007678,-0.001438,0.001703,-0.031984,-0.018267,-0.026329,0.011899,-0.021971,0.018629,0.003588,0.005360,-0.087143,0.011639,0.029460,0.038764,-0.016023,0.000354,-0.003981,-0.005368,0.013387,-0.004440,-0.000835,-0.005717,0.014558,-0.008709,0.006656,0.006115,0.017459,-0.006044,-0.022052,-0.020509,0.003933,0.016619,-0.009528,-0.020631,-0.011704,-0.022557,-0.026538,0.056615,-0.025942,-0.008078,-0.000278,-0.052972,0.027300,-0.009044,-0.008969,-0.010954,0.035782,0.031758,-0.015721,0.000368,0.020275,0.011309,-0.016594,0.016283,0.032708,-0.024471,0.013321,-0.003260,0.004796,0.003131,0.006254,-0.008577,-0.001995,-0.014585,-0.015128,-0.026317,-0.022377,-0.006286,-0.042903,0.027544,-0.030118,0.048343,0.012375,-0.013033,0.012912,-0.051105,-0.008472,-0.021120,-0.041249,-0.010107,-0.014900,-0.020264,0.020372,-0.041108,0.055916,0.013361,-0.034614,-0.059933,-0.018446,0.033346,-0.059877,-0.008038,0.015564,-0.006357,0.022688,-0.030337,-0.035111,0.017981,-0.006720,0.033122,-0.085217,0.046451,0.054197,0.068601,-0.022180,0.008875,0.082668,-0.008600,0.008448,-0.028321,-0.026078,0.013132,0.004907,0.013447,0.033821,-0.007054,-0.060050,0.024514,0.009594,-0.081892,0.017465,-0.047235,0.005299,0.068629,0.007046,-0.025149,0.006469,0.030323,-0.050315,0.010203,0.011587,0.026586,0.037392,-0.009938,0.035249,-0.000117,-0.015302,0.000298,-0.033950,0.013220,0.033420,0.008926,0.017554,0.027845,-0.004705,0.021465,-0.012483,-0.023853,-0.001181,-0.009586,-0.020042,-0.016578,0.012830
2,2026-03-06 08:32:47,DeepStateUA,0.009207,-0.000980,0.027773,0.003815,-0.016143,0.044874,-0.036314,0.114619,0.018318,-0.029455,-0.061089,0.011555,-0.017066,-0.012750,0.046438,0.002240,-0.008366,-0.031491,-3.422476e-02,0.021600,0.025354,0.012989,-0.016710,-0.005652,-0.000942,0.004435,-0.026056,-0.002133,0.009171,0.013860,0.001250,-0.008481,0.006147,0.007172,-0.001211,-0.000019,-0.002802,-0.003288,0.009266,-0.004910,-0.003997,-0.016448,-0.001282,0.016932,0.007769,0.000162,-0.003869,-0.003456,-0.021085,0.004213,0.005327,-0.027757,-0.038487,0.028499,-0.006878,0.003909,-0.003040,-0.018648,-0.003556,0.001712,-0.001450,0.004726,-0.007309,0.006115,-0.008207,-0.001980,0.006809,-0.008187,-0.011359,0.031341,-0.017845,0.019875,0.014576,-0.014652,-0.044019,-0.019223,0.017994,-0.000224,-0.022663,0.003561,0.024627,-0.033273,0.008230,0.028736,0.019367,0.013746,-0.002684,-0.001752,0.010491,-0.019671,0.008335,0.004611,0.007200,0.033005,0.006701,-0.031088,-0.000849,0.019676,0.014347,-0.033548,-0.040093,-0.016090,-0.021699,-0.000207,0.008068,-0.010423,-0.007300,-0.024042,0.005014,-0.006404,0.022366,-0.016316,0.022815,0.025305,0.020726,0.012293,0.002634,0.009041,-0.017907,0.009438,-0.010085,0.032145,-0.017487,0.045213,-0.007165,-0.024685,0.001220,0.017807,-0.023695,0.000945,0.011791,0.010850,0.036831,0.004699,0.030134,-0.036768,-0.015027,-0.015130,-0.058561,0.012577,0.007100,0.015908,0.002079,0.004368,0.045626,-0.003953,-0.022526,0.006335,0.010369,-0.001271,-0.010934,-0.049172,-0.023458,0.000341,-0.031367,0.016509,-0.012089,0.039704,-0.009027,-0.043527,0.016736,0.004243,-0.003803,-0.004715,-0.013557,-0.000762,0.030282,0.007177,0.011529,-0.004388,-0.020483,0.022261,-0.054566,0.033860,0.006118,0.005828,0.032058,-0.017984,-0.023836,-0.003558,-0.027382,-0.022436,0.012265,-0.019205,-0.003325,-0.006893,0.007633,-0.004766,0.008148,0.003098,-0.009825,0.023551,-0.010479,0.021995,0.026399,0.011528,-0.026861,-0.016046,-0.006903,0.005188,-0.013524,-0.046201,0.019910,0.007586,0.016840,0.007923,0.001219,-0.012761,0.026745,-0.017222,0.039370,0.025081,0.013642,0.004249,0.010074,0.001067,0.023547,0.001472,0.009214,0.022690,-0.005104,-0.001306,-0.020575,0.019680,0.029585,-0.018227,0.049065,0.001596,-0.006779,0.015124,-0.011910,0.010656,-0.026828,-0.027329,0.024684,0.047435,-0.033182,-0.008409,0.010492,-0.011799,0.010305,-0.002257,0.038329,-0.006852,0.000943,-0.010584,-0.007478,-0.013289,-0.020444,0.037230
3,2026-03-05 16:46:58,DeepStateUA,0.006730,0.000369,0.018262,0.000836,-0.008774,0.027117,-0.022958,0.080319,0.048233,-0.034815,-0.045849,0.022741,-0.009713,0.309643,0.438196,0.146176,-0.033862,0.013238,-1.580278e-02,0.297928,-0.013460,0.024751,0.033260,-0.075030,-0.055840,0.057354,-0.116678,-0.062500,0.000717,0.040400,0.030314,-0.013031,-0.032608,-0.017691,0.000158,-0.008193,-0.009914,0.024541,-0.012840,-0.013137,0.003457,0.005493,0.019286,-0.037760,-0.016446,-0.022256,0.017910,-0.041596,-0.012892,-0.000280,-0.005203,-0.015121,0.001036,0.033322,-0.000906,0.003040,0.027553,0.023324,-0.009145,-0.007351,-0.016474,-0.016809,-0.003330,-0.014597,-0.022927,0.007268,0.018859,-0.021800,0.009131,0.012074,-0.053228,-0.032774,-0.008439,-0.006627,-0.022762,-0.056283,0.078933,0.032017,-0.078149,-0.009691,-0.002644,0.133985,-0.052901,-0.084578,0.060612,0.053594,0.015892,-0.001841,0.001717,-0.015658,-0.055645,-0.001325,0.021126,-0.053717,-0.006974,0.036446,-0.027121,0.029704,0.027952,-0.068233,-0.003599,0.013170,0.034084,-0.030737,0.000881,-0.026277,-0.001736,-0.020846,-0.019346,-0.009823,0.002972,0.006247,-0.014389,-0.006935,-0.018914,-0.002400,-0.005911,0.019147,0.001121,-0.020965,-0.004638,-0.017239,-0.020585,-0.024810,-0.010215,-0.007846,0.055710,0.000031,-0.014512,0.011383,0.009538,0.012128,-0.038329,0.021539,-0.031457,0.033555,-0.014396,0.025844,0.078367,-0.010068,-0.018387,-0.003521,0.012967,-0.017915,0.033516,0.002873,-0.005512,0.002858,0.026889,0.044126,0.018553,-0.066710,-0.023417,-0.020027,0.020845,0.023295,-0.032703,-0.002423,0.000113,0.030762,-0.028151,0.036592,-0.010906,-0.038255,-0.007884,0.000366,-0.009493,-0.011747,-0.012552,0.002861,0.013041,0.016277,0.012649,0.016129,-0.026770,0.009307,0.057962,-0.012966,-0.013863,-0.029381,-0.035827,-0.002517,-0.015274,-0.034535,0.005842,-0.001696,0.003620,-0.027563,-0.000583,0.021418,-0.004244,-0.015328,-0.027039,0.018155,-0.007449,-0.003125,0.001440,-0.021701,0.013112,0.002679,-0.007513,-0.012194,0.014085,0.013777,-0.015106,-0.000613,0.000012,-0.015563,-0.005321,-0.005559,0.005562,0.016872,0.006083,-0.002207,-0.004108,-0.002010,0.009412,0.002042,0.028860,0.015532,-0.011470,0.004811,-0.014625,-0.007261,-0.007659,0.005783,-0.000785,0.001777,0.025645,-0.014319,-0.004701,0.015166,0.010417,0.015061,0.013591,-0.003474,-0.020810,-0.016731,0.013024,0.029357,-0.027499,-0.010470,-0.002663,0.008809,-0.002377,-0.024942,-0.023054,-0.007296,0.018534,0.018426
4,2026-03-05 15:46:39,DeepStateUA,0.048474,-0.006318,0.074492,-0.003676,-0.020838,0.080790,-0.041052,0.150230,0.063555,-0.043206,0.008691,-0.000347,-0.003948,0.152312,0.096820,0.034473,0.000234,-0.012377,4.078870e-03,-0.045798,0.024286,-0.038903,0.063380,0.019504,0.037094,-0.056330,0.129901,0.108323,0.016542,-0.052420,-0.029516,-0.016280,-0.026799,0.036448,-0.006656,0.032468,0.011473,-0.025498,-0.041209,-0.000547,-0.024440,0.013743,-0.021410,0.056264,0.019823,0.005496,-0.032494,0.020598,0.027337,-0.006094,-0.029305,0.002764,0.007007,-0.016470,0.016138,-0.007199,-0.014717,-0.025964,0.005798,-0.008612,-0.007486,0.027008,0.002107,0.023235,-0.010195,0.007027,-0.004510,0.023884,0.018101,0.006018,-0.000848,-0.009528,0.011162,-0.025280,-0.030648,0.056156,-0.012447,-0.049402,0.059022,0.015470,0.015913,-0.005283,0.008671,-0.014688,0.005627,-0.024438,0.010350,0.017736,0.019147,-0.013126,0.023786,0.014656,-0.019442,0.088969,-0.036360,-0.054974,0.038121,-0.035612,-0.005555,0.010935,-0.022885,-0.071534,0.018374,0.004373,0.052751,0.032290,-0.008339,-0.090516,0.018196,0.066381,0.004270,-0.020580,0.047784,-0.030461,-0.041658,0.037566,0.006620,-0.018214,0.002971,0.017014,0.019651,0.020812,0.021123,0.033048,-0.025845,0.007063,-0.015534,0.011495,0.000960,-0.016813,-0.013721,-0.005453,-0.041389,0.000159,0.017728,0.030462,0.017962,-0.032629,-0.013684,0.010937,0.013186,0.023176,-0.056094,-0.011582,-0.021673,-0.004477,0.038870,-0.004558,0.004576,-0.023568,0.044991,0.065428,0.043781,-0.010461,0.009051,-0.048291,-0.023517,-0.011433,0.017929,0.058255,-0.000259,-0.045751,0.007872,0.019385,-0.006916,0.010449,0.015242,0.017788,-0.008952,0.004618,-0.015152,-0.010723,0.049670,-0.007470,-0.000408,-0.003877,-0.019726,-0.004499,-0.017677,0.039586,-0.001441,-0.011096,-0.005770,0.005901,-0.035798,-0.009255,-0.026691,-0.033232,-0.010029,-0.030306,0.015318,0.018775,-0.000740,0.016531,-0.030819,-0.039312,-0.006236,0.025290,0.014651,-0.013704,-0.009411,-0.004784,-0.022150,0.004683,-0.048483,-0.028934,0.037932,-0.031136,0.006823,0.019648,-0.000935,0.014402,0.003778,0.022729,-0.046635,-0.018970,0.012597,0.022199,-0.009682,0.019225,-0.002489,0.022667,0.032180,-0.013274,0.011687,0.013808,0.032914,0.035060,-0.029590,-0.028396,0.020668,-0.013548,0.009654,0.013138,0.004647,0.048754,-0.018448,0.024578,-0.011808,-0.014146,-0.013907,-0.010692,0.031315,0.009080,-0.003524,-0.034707,-0.039795,0.018229,-0.014541,0.038234

In [25]:
df_tg_matrix["datetime_hour"] = pd.to_datetime(df_tg_matrix["date"]).dt.floor("h")

In [26]:
topic_cols = [c for c in df_tg_matrix.columns if "tg_topic_" in c]

tg_hourly = (
    df_tg_matrix.groupby("datetime_hour")[topic_cols]
    .mean()
    .sort_index()
    .reset_index()
)

In [27]:
df_tg_matrix.head()

,date,channel,tg_topic_0,tg_topic_1,tg_topic_2,tg_topic_3,tg_topic_4,tg_topic_5,tg_topic_6,tg_topic_7,tg_topic_8,tg_topic_9,tg_topic_10,tg_topic_11,tg_topic_12,tg_topic_13,tg_topic_14,tg_topic_15,tg_topic_16,tg_topic_17,tg_topic_18,tg_topic_19,tg_topic_20,tg_topic_21,tg_topic_22,tg_topic_23,tg_topic_24,tg_topic_25,tg_topic_26,tg_topic_27,tg_topic_28,tg_topic_29,tg_topic_30,tg_topic_31,tg_topic_32,tg_topic_33,tg_topic_34,tg_topic_35,tg_topic_36,tg_topic_37,tg_topic_38,tg_topic_39,tg_topic_40,tg_topic_41,tg_topic_42,tg_topic_43,tg_topic_44,tg_topic_45,tg_topic_46,tg_topic_47,tg_topic_48,tg_topic_49,tg_topic_50,tg_topic_51,tg_topic_52,tg_topic_53,tg_topic_54,tg_topic_55,tg_topic_56,tg_topic_57,tg_topic_58,tg_topic_59,tg_topic_60,tg_topic_61,tg_topic_62,tg_topic_63,tg_topic_64,tg_topic_65,tg_topic_66,tg_topic_67,tg_topic_68,tg_topic_69,tg_topic_70,tg_topic_71,tg_topic_72,tg_topic_73,tg_topic_74,tg_topic_75,tg_topic_76,tg_topic_77,tg_topic_78,tg_topic_79,tg_topic_80,tg_topic_81,tg_topic_82,tg_topic_83,tg_topic_84,tg_topic_85,tg_topic_86,tg_topic_87,tg_topic_88,tg_topic_89,tg_topic_90,tg_topic_91,tg_topic_92,tg_topic_93,tg_topic_94,tg_topic_95,tg_topic_96,tg_topic_97,tg_topic_98,tg_topic_99,tg_topic_100,tg_topic_101,tg_topic_102,tg_topic_103,tg_topic_104,tg_topic_105,tg_topic_106,tg_topic_107,tg_topic_108,tg_topic_109,tg_topic_110,tg_topic_111,tg_topic_112,tg_topic_113,tg_topic_114,tg_topic_115,tg_topic_116,tg_topic_117,tg_topic_118,tg_topic_119,tg_topic_120,tg_topic_121,tg_topic_122,tg_topic_123,tg_topic_124,tg_topic_125,tg_topic_126,tg_topic_127,tg_topic_128,tg_topic_129,tg_topic_130,tg_topic_131,tg_topic_132,tg_topic_133,tg_topic_134,tg_topic_135,tg_topic_136,tg_topic_137,tg_topic_138,tg_topic_139,tg_topic_140,tg_topic_141,tg_topic_142,tg_topic_143,tg_topic_144,tg_topic_145,tg_topic_146,tg_topic_147,tg_topic_148,tg_topic_149,tg_topic_150,tg_topic_151,tg_topic_152,tg_topic_153,tg_topic_154,tg_topic_155,tg_topic_156,tg_topic_157,tg_topic_158,tg_topic_159,tg_topic_160,tg_topic_161,tg_topic_162,tg_topic_163,tg_topic_164,tg_topic_165,tg_topic_166,tg_topic_167,tg_topic_168,tg_topic_169,tg_topic_170,tg_topic_171,tg_topic_172,tg_topic_173,tg_topic_174,tg_topic_175,tg_topic_176,tg_topic_177,tg_topic_178,tg_topic_179,tg_topic_180,tg_topic_181,tg_topic_182,tg_topic_183,tg_topic_184,tg_topic_185,tg_topic_186,tg_topic_187,tg_topic_188,tg_topic_189,tg_topic_190,tg_topic_191,tg_topic_192,tg_topic_193,tg_topic_194,tg_topic_195,tg_topic_196,tg_topic_197,tg_topic_198,tg_topic_199,tg_topic_200,tg_topic_201,tg_topic_202,tg_topic_203,tg_topic_204,tg_topic_205,tg_topic_206,tg_topic_207,tg_topic_208,tg_topic_209,tg_topic_210,tg_topic_211,tg_topic_212,tg_topic_213,tg_topic_214,tg_topic_215,tg_topic_216,tg_topic_217,tg_topic_218,tg_topic_219,tg_topic_220,tg_topic_221,tg_topic_222,tg_topic_223,tg_topic_224,tg_topic_225,tg_topic_226,tg_topic_227,tg_topic_228,tg_topic_229,tg_topic_230,tg_topic_231,tg_topic_232,tg_topic_233,tg_topic_234,tg_topic_235,tg_topic_236,tg_topic_237,tg_topic_238,tg_topic_239,tg_topic_240,tg_topic_241,tg_topic_242,tg_topic_243,tg_topic_244,tg_topic_245,tg_topic_246,tg_topic_247,tg_topic_248,tg_topic_249,datetime_hour
0,2026-03-06 13:06:58,DeepStateUA,0.006988,0.000199,0.019066,0.000954,-0.008572,0.027556,-0.023390,0.082142,0.048557,-0.035442,-0.044857,0.023976,-0.010296,0.314185,0.441313,0.148150,-0.033452,0.013619,-1.517790e-02,0.300137,-0.013806,0.024117,0.032729,-0.075532,-0.055463,0.056108,-0.114965,-0.062816,0.000903,0.040613,0.030642,-0.011243,-0.031933,-0.016561,-0.000002,-0.009349,-0.013026,0.023569,-0.014856,-0.013251,0.003954,0.006923,0.018694,-0.040851,-0.016603,-0.022610,0.020255,-0.044764,-0.014435,-0.000230,-0.005440,-0.015144,0.000328,0.033881,-0.001490,0.004347,0.028966,0.024960,-0.010553,-0.007215,-0.016782,-0.017823,-0.004215,-0.016674,-0.025594,0.012136,0.018104,-0.023220,0.010000,0.012855,-0.056983,-0.036521,-0.008794,-0.007228,-0.026847,-0.062296,0.085056,0.036050,-0.086713,-0.011966,-0.004914,0.141366,-0.055463,-0.088688,0.061813,0.057732,0.016839,-0.002449,0.000986,-0.015949,-0.059070,-0.003215,0.027278,-0.060312,-0.006565,0.040401,-0.027012,0.030306,0.029951,-0.074696,-0.003235,0.014906,0.033469,-0.037257,-0.000254,-0.023586,0.003416,-0.019975,-0.013569,-0.016646,-0.000286,0.008311,-0.014775,-0.005560,-0.015832,-0.004287,-0.005641,0.019341,0.001947,-0.019378,-0.004329,-0.017837,-0.021873,-0.024704,-0.017573,-0.001471,0.055298,-0.001907,-0.015560,0.010959,0.008830,0.013610,-0.038589,0.020823,-0.034751,0.032423,-0.015660,0.027160,0.082206,-0.008323,-0.017703,-0.003846,0.011994,-0.018756,0.032183,0.001488,-0.003756,0.006360,0.029452,0.043348,0.021398,-0.067449,-0.023474,-0.022019,0.022582,0.027935,-0.032891,-0.001852,-0.000252,0.033536,-0.027412,0.039133,-0.011634,-0.036005,-0.007873,0.002068,-0.007386,-0.011691,-0.019126,0.007075,0.013907,0.019937,0.014858,0.020191,-0.025726,0.013726,0.067214,-0.018241,-0.015205,-0.034773,-0.037605,-0.005873,-0.019108,-0.039294,0.006821,-0.001082,0.007128,-0.030109,-0.002517,0.020059,-0.002848,-0.020188,-0.032926,0.020508,-0.008676,-0.005482,0.004211,-0.023763,0.017472,0.002921,-0.007789,-0.011783,0.016696,0.016443,-0.021025,0.001147,-0.001315,-0.018607,-0.003998,-0.010899,0.008551,0.018628,0.011479,0.000386,0.000531,-0.002158,0.010067,-0.002232,0.032518,0.011657,-0.014824,0.011384,-0.015446,-0.008815,-0.010052,0.005703,-0.001860,-0.001866,0.032770,-0.012229,0.004878,0.020139,0.009993,0.017605,0.025128,-0.001467,-0.026995,-0.020391,0.029010,0.040204,-0.025015,-0.009189,0.002957,0.010876,-0.004521,-0.032922,-0.024608,0.001831,0.028593,0.021750,2026-03-06 13:00:00
1,2026-03-06 12:57:29,DeepStateUA,0.022407,-0.001962,0.039639,0.001378,-0.027803,0.069329,-0.037687,0.126188,0.023941,-0.028038,-0.035619,0.015229,-0.008888,0.052549,0.052510,-0.028264,-0.017461,-0.048919,-3.464665e-07,-0.004600,0.007378,-0.006132,0.044293,-0.004122,-0.012953,-0.023969,0.033698,0.023532,0.003563,-0.007249,0.049356,-0.024524,-0.027906,0.009350,-0.011559,-0.014335,0.024924,0.011431,-0.000501,0.001054,-0.016655,-0.026000,0.002606,0.049669,-0.012653,0.022710,-0.043217,0.038909,-0.038570,-0.015367,0.052191,0.007416,-0.017443,0.032344,-0.017845,-0.017606,0.016605,-0.004602,0.007640,0.034543,-0.015710,0.016760,0.003032,-0.022000,0.023525,-0.039551,-0.022952,-0.005680,-0.006249,0.026948,0.017350,0.035260,0.004191,-0.003160,0.000994,0.005015,-0.002274,0.005243,0.005334,-0.013808,0.000110,-0.012621,0.017584,-0.008420,-0.008566,-0.044011,-0.008985,0.009480,-0.019268,0.001165,-0.009917,-0.001627,-0.017013,0.029732,-0.029833,-0.013647,0.007678,-0.001438,0.001703,-0.031984,-0.018267,-0.026329,0.011899,-0.021971,0.018629,0.003588,0.005360,-0.087143,0.011639,0.029460,0.038764,-0.016023,0.000354,-0.003981,-0.005368,0.013387,-0.004440,-0.000835,-0.005717,0.014558,-0.008709,0.006656,0.006115,0.017459,-0.006044,-0.022052,-0.020509,0.003933,0.016619,-0.009528,-0.020631,-0.011704,-0.022557,-0.026538,0.056615,-0.025942,-0.008078,-0.000278,-0.052972,0.027300,-0.009044,-0.008969,-0.010954,0.035782,0.031758,-0.015721,0.000368,0.020275,0.011309,-0.016594,0.016283,0.032708,-0.024471,0.013321,-0.003260,0.004796,0.003131,0.006254,-0.008577,-0.001995,-0.014585,-0.015128,-0.026317,-0.022377,-0.006286,-0.042903,0.027544,-0.030118,0.048343,0.012375,-0.013033,0.012912,-0.051105,-0.008472,-0.021120,-0.041249,-0.010107,-0.014900,-0.020264,0.020372,-0.041108,0.055916,0.013361,-0.034614,-0.059933,-0.018446,0.033346,-0.059877,-0.008038,0.015564,-0.006357,0.022688,-0.030337,-0.035111,0.017981,-0.006720,0.033122,-0.085217,0.046451,0.054197,0.068601,-0.022180,0.008875,0.082668,-0.008600,0.008448,-0.028321,-0.026078,0.013132,0.004907,0.013447,0.033821,-0.007054,-0.060050,0.024514,0.009594,-0.081892,0.017465,-0.047235,0.005299,0.068629,0.007046,-0.025149,0.006469,0.030323,-0.050315,0.010203,0.011587,0.026586,0.037392,-0.009938,0.035249,-0.000117,-0.015302,0.000298,-0.033950,0.013220,0.033420,0.008926,0.017554,0.027845,-0.004705,0.021465,-0.012483,-0.023853,-0.001181,-0.009586,-0.020042,-0.016578,0.012830,2026-03-06 12:00:00
2,2026-03-06 08:32:47,DeepStateUA,0.009207,-0.000980,0.027773,0.003815,-0.016143,0.044874,-0.036314,0.114619,0.018318,-0.029455,-0.061089,0.011555,-0.017066,-0.012750,0.046438,0.002240,-0.008366,-0.031491,-3.422476e-02,0.021600,0.025354,0.012989,-0.016710,-0.005652,-0.000942,0.004435,-0.026056,-0.002133,0.009171,0.013860,0.001250,-0.008481,0.006147,0.007172,-0.001211,-0.000019,-0.002802,-0.003288,0.009266,-0.004910,-0.003997,-0.016448,-0.001282,0.016932,0.007769,0.000162,-0.003869,-0.003456,-0.021085,0.004213,0.005327,-0.027757,-0.038487,0.028499,-0.006878,0.003909,-0.003040,-0.018648,-0.003556,0.001712,-0.001450,0.004726,-0.007309,0.006115,-0.008207,-0.001980,0.006809,-0.008187,-0.011359,0.031341,-0.017845,0.019875,0.014576,-0.014652,-0.044019,-0.019223,0.017994,-0.000224,-0.022663,0.003561,0.024627,-0.033273,0.008230,0.028736,0.019367,0.013746,-0.002684,-0.001752,0.010491,-0.019671,0.008335,0.004611,0.007200,0.033005,0.006701,-0.031088,-0.000849,0.019676,0.014347,-0.033548,-0.040093,-0.016090,-0.021699,-0.000207,0.008068,-0.010423,-0.007300,-0.024042,0.005014,-0.006404,0.022366,-0.016316,0.022815,0.025305,0.020726,0.012293,0.002634,0.009041,-0.017907,0.009438,-0.010085,0.032145,-0.017487,0.045213,-0.007165,-0.024685,0.001220,0.017807,-0.023695,0.000945,0.011791,0.010850,0.036831,0.004699,0.030134,-0.036768,-0.015027,-0.015130,-0.058561,0.012577,0.007100,0.015908,0.002079,0.004368,0.045626,-0.003953,-0.022526,0.006335,0.010369,-0.001271,-0.010934,-0.049172,-0.023458,0.000341,-0.031367,0.016509,-0.012089,0.039704,-0.009027,-0.043527,0.016736,0.004243,-0.003803,-0.004715,-0.013557,-0.000762,0.030282,0.007177,0.011529,-0.004388,-0.020483,0.022261,-0.054566,0.033860,0.006118,0.005828,0.032058,-0.017984,-0.023836,-0.003558,-0.027382,-0.022436,0.012265,-0.019205,-0.003325,-0.006893,0.007633,-0.004766,0.008148,0.003098,-0.009825,0.023551,-0.010479,0.021995,0.026399,0.011528,-0.026861,-0.016046,-0.006903,0.005188,-0.013524,-0.046201,0.019910,0.007586,0.016840,0.007923,0.001219,-0.012761,0.026745,-0.017222,0.039370,0.025081,0.013642,0.004249,0.010074,0.001067,0.023547,0.001472,0.009214,0.022690,-0.005104,-0.001306,-0.020575,0.019680,0.029585,-0.018227,0.049065,0.001596,-0.006779,0.015124,-0.011910,0.010656,-0.026828,-0.027329,0.024684,0.047435,-0.033182,-0.008409,0.010492,-0.011799,0.010305,-0.002257,0.038329,-0.006852,0.000943,-0.010584,-0.007478,-0.013289,-0.020444,0.037230,2026-03-06 08:00:00
3,2026-03-05 16:46:58,DeepStateUA,0.006730,0.000369,0.018262,0.000836,-0.008774,0.027117,-0.022958,0.080319,0.048233,-0.034815,-0.045849,0.022741,-0.009713,0.309643,0.438196,0.146176,-0.033862,0.013238,-1.580278e-02,0.297928,-0.013460,0.024751,0.033260,-0.075030,-0.055840,0.057354,-0.116678,-0.062500,0.000717,0.040400,0.030314,-0.013031,-0.032608,-0.017691,0.000158,-0.008193,-0.009914,0.024541,-0.012840,-0.013137,0.003457,0.005493,0.019286,-0.037760,-0.016446,-0.022256,0.017910,-0.041596,-0.012892,-0.000280,-0.005203,-0.015121,0.001036,0.033322,-0.000906,0.003040,0.027553,0.023324,-0.009145,-0.007351,-0.016474,-0.016809,-0.003330,-0.014597,-0.022927,0.007268,0.018859,-0.021800,0.009131,0.012074,-0.053228,-0.032774,-0.008439,-0.006627,-0.022762,-0.056283,0.078933,0.032017,-0.078149,-0.009691,-0.002644,0.133985,-0.052901,-0.084578,0.060612,0.053594,0.015892,-0.001841,0.001717,-0.015658,-0.055645,-0.001325,0.021126,-0.053717,-0.006974,0.036446,-0.027121,0.029704,0.027952,-0.068233,-0.003599,0.013170,0.034084,-0.030737,0.000881,-0.026277,-0.001736,-0.020846,-0.019346,-0.009823,0.002972,0.006247,-0.014389,-0.006935,-0.018914,-0.002400,-0.005911,0.019147,0.001121,-0.020965,-0.004638,-0.017239,-0.020585,-0.024810,-0.010215,-0.007846,0.055710,0.000031,-0.014512,0.011383,0.009538,0.012128,-0.038329,0.021539,-0.031457,0.033555,-0.014396,0.025844,0.078367,-0.010068,-0.018387,-0.003521,0.012967,-0.017915,0.033516,0.002873,-0.005512,0.002858,0.026889,0.044126,0.018553,-0.066710,-0.023417,-0.020027,0.020845,0.023295,-0.032703,-0.002423,0.000113,0.030762,-0.028151,0.036592,-0.010906,-0.038255,-0.007884,0.000366,-0.009493,-0.011747,-0.012552,0.002861,0.013041,0.016277,0.012649,0.016129,-0.026770,0.009307,0.057962,-0.012966,-0.013863,-0.029381,-0.035827,-0.002517,-0.015274,-0.034535,0.005842,-0.001696,0.003620,-0.027563,-0.000583,0.021418,-0.004244,-0.015328,-0.027039,0.018155,-0.007449,-0.003125,0.001440,-0.021701,0.013112,0.002679,-0.007513,-0.012194,0.014085,0.013777,-0.015106,-0.000613,0.000012,-0.015563,-0.005321,-0.005559,0.005562,0.016872,0.006083,-0.002207,-0.004108,-0.002010,0.009412,0.002042,0.028860,0.015532,-0.011470,0.004811,-0.014625,-0.007261,-0.007659,0.005783,-0.000785,0.001777,0.025645,-0.014319,-0.004701,0.015166,0.010417,0.015061,0.013591,-0.003474,-0.020810,-0.016731,0.013024,0.029357,-0.027499,-0.010470,-0.002663,0.008809,-0.002377,-0.024942,-0.023054,-0.007296,0.018534,0.018426,2026-03-05 16:00:00
4,2026-03-05 15:46:39,DeepStateUA,0.048474,-0.006318,0.074492,-0.003676,-0.020838,0.080790,-0.041052,0.150230,0.063555,-0.043206,0.008691,-0.000347,-0.003948,0.152312,0.096820,0.034473,0.000234,-0.012377,4.078870e-03,-0.045798,0.024286,-0.038903,0.063380,0.019504,0.037094,-0.056330,0.129901,0.108323,0.016542,-0.052420,-0.029516,-0.016280,-0.026799,0.036448,-0.006656,0.032468,0.011473,-0.025498,-0.041209,-0.000547,-0.024440,0.013743,-0.021410,0.056264,0.019823,0.005496,-0.032494,0.020598,0.027337,-0.006094,-0.029305,0.002764,0.007007,-0.016470,0.016138,-0.007199,-0.014717,-0.025964,0.005798,-0.008612,-0.007486,0.027008,0.002107,0.023235,-0.010195,0.007027,-0.004510,0.023884,0.018101,0.006018,-0.000848,-0.009528,0.011162,-0.025280,-0.030648,0.056156,-0.012447,-0.049402,0.059022,0.015470,0.015913,-0.005283,0.008671,-0.014688,0.005627,-0.024438,0.010350,0.017736,0.019147,-0.013126,0.023786,0.014656,-0.019442,0.088969,-0.036360,-0.054974,0.038121,-0.035612,-0.005555,0.010935,-0.022885,-0.071534,0.018374,0.004373,0.052751,0.032290,-0.008339,-0.090516,0.018196,0.066381,0.004270,-0.020580,0.047784,-0.030461,-0.041658,0.037566,0.006620,-0.018214,0.002971,0.017014,0.019651,0.020812,0.021123,0.033048,-0.025845,0.007063,-0.015534,0.011495,0.000960,-0.016813,-0.013721,-0.005453,-0.041389,0.000159,0.017728,0.030462,0.017962,-0.032629,-0.013684,0.010937,0.013186,0.023176,-0.056094,-0.011582,-0.021673,-0.004477,0.038870,-0.004558,0.004576,-0.023568,0.044991,0.065428,0.043781,-0.010461,0.009051,-0.048291,-0.023517,-0.011433,0.017929,0.058255,-0.000259,-0.045751,0.007872,0.019385,-0.006916,0.010449,0.015242,0.017788,-0.008952,0.004618,-0.015152,-0.010723,0.049670,-0.007470,-0.000408,-0.003877,-0.019726,-0.004499,-0.017677,0.039586,-0.001441,-0.011096,-0.005770,0.005901,-0.035798,-0.009255,-0.026691,-0.033232,-0.010029,-0.030306,0.015318,0.018775,-0.000740,0.016531,-0.030819,-0.039312,-0.006236,0.025290,0.014651,-0.013704,-0.009411,-0.004784,-0.022150,0.004683,-0.048483,-0.028934,0.037932,-0.031136,0.006823,0.019648,-0.000935,0.014402,0.003778,0.022729,-0.046635,-0.018970,0.012597,0.022199,-0.009682,0.019225,-0.002489,0.022667,0.032180,-0.013274,0.011687,0.013808,0.032914,0.035060,-0.029590,-0.028396,0.020668,-0.013548,0.009654,0.013138,0.004647,0.048754,-0.018448,0.024578,-0.011808,-0.014146,-0.013907,-0.010692,0.031315,0.009080,-0.003524,-0.034707,-0.039795,0.018229,-0.014541,0.038234,2026-03-05 15:00:00

In [28]:
#tg_hourly["datetime_hour"] = tg_hourly["datetime_hour"] + pd.Timedelta(hours=1)        ТУТ ЗСУВ ТГ НА 1 ГОДИНУ

In [29]:
df_final = df_final.merge(tg_hourly, on="datetime_hour", how="left")

In [30]:
df_final.sample(20)

,datetime_hour,region_id,city_latitude,city_longitude,day_temp,day_dew,day_humidity,day_precip,day_precipprob,day_precipcover,day_snow,day_snowdepth,day_windgust,day_windspeed,day_winddir,day_pressure,day_cloudcover,day_solarradiation,day_solarenergy,day_uvindex,day_moonphase,hour_temp,hour_feelslike,hour_humidity,hour_precip,hour_precipprob,hour_snow,hour_windgust,hour_windspeed,hour_winddir,hour_pressure,hour_cloudcover,hour_solarradiation,hour_solarenergy,hour_uvindex,day_conditions_simple_Clear,day_conditions_simple_Cloudy,day_conditions_simple_Rain,day_conditions_simple_Snow,hour_conditions_simple_Clear,hour_conditions_simple_Cloudy,hour_conditions_simple_Rain,hour_conditions_simple_Snow,year,month,day_of_week,hour,city_name,city_timezone,day_datetime,day_sunrise,day_sunset,hour_datetime,region_key,alarm_active,alarm_minutes_in_hour,alarm_lag_1,alarm_lag_3,alarm_lag_6,alarm_lag_12,alarms_in_last_24h,is_weekend,is_night,total_active_alarms_lag1,neighbour_alarms,hours_since_last_alarm,isw_topic_0,isw_topic_1,isw_topic_2,isw_topic_3,isw_topic_4,isw_topic_5,isw_topic_6,isw_topic_7,isw_topic_8,isw_topic_9,isw_topic_10,isw_topic_11,isw_topic_12,isw_topic_13,isw_topic_14,isw_topic_15,isw_topic_16,isw_topic_17,isw_topic_18,isw_topic_19,isw_topic_20,isw_topic_21,isw_topic_22,isw_topic_23,isw_topic_24,isw_topic_25,isw_topic_26,isw_topic_27,isw_topic_28,isw_topic_29,isw_topic_30,isw_topic_31,isw_topic_32,isw_topic_33,isw_topic_34,isw_topic_35,isw_topic_36,isw_topic_37,isw_topic_38,isw_topic_39,isw_topic_40,isw_topic_41,isw_topic_42,isw_topic_43,isw_topic_44,isw_topic_45,isw_topic_46,isw_topic_47,isw_topic_48,isw_topic_49,isw_topic_50,isw_topic_51,isw_topic_52,isw_topic_53,isw_topic_54,isw_topic_55,isw_topic_56,isw_topic_57,isw_topic_58,isw_topic_59,isw_topic_60,isw_topic_61,isw_topic_62,isw_topic_63,isw_topic_64,isw_topic_65,isw_topic_66,isw_topic_67,isw_topic_68,isw_topic_69,isw_topic_70,isw_topic_71,isw_topic_72,isw_topic_73,isw_topic_74,isw_topic_75,isw_topic_76,isw_topic_77,isw_topic_78,isw_topic_79,isw_topic_80,isw_topic_81,isw_topic_82,isw_topic_83,isw_topic_84,isw_topic_85,isw_topic_86,isw_topic_87,isw_topic_88,isw_topic_89,isw_topic_90,isw_topic_91,isw_topic_92,isw_topic_93,isw_topic_94,isw_topic_95,isw_topic_96,isw_topic_97,isw_topic_98,isw_topic_99,isw_topic_100,isw_topic_101,isw_topic_102,isw_topic_103,isw_topic_104,isw_topic_105,isw_topic_106,isw_topic_107,isw_topic_108,isw_topic_109,isw_topic_110,isw_topic_111,isw_topic_112,isw_topic_113,isw_topic_114,isw_topic_115,isw_topic_116,isw_topic_117,isw_topic_118,isw_topic_119,isw_topic_120,isw_topic_121,isw_topic_122,isw_topic_123,isw_topic_124,isw_topic_125,isw_topic_126,isw_topic_127,isw_topic_128,isw_topic_129,isw_topic_130,isw_topic_131,isw_topic_132,isw_topic_133,isw_topic_134,isw_topic_135,isw_topic_136,isw_topic_137,isw_topic_138,isw_topic_139,isw_topic_140,isw_topic_141,isw_topic_142,isw_topic_143,isw_topic_144,isw_topic_145,isw_topic_146,isw_topic_147,isw_topic_148,isw_topic_149,isw_total_intensity,isw_topic_std,isw_topic_max,isw_topic_mean,isw_velocity_24h,isw_intensity_ema,isw_topic_entropy,tg_topic_0,tg_topic_1,tg_topic_2,tg_topic_3,tg_topic_4,tg_topic_5,tg_topic_6,tg_topic_7,tg_topic_8,tg_topic_9,tg_topic_10,tg_topic_11,tg_topic_12,tg_topic_13,tg_topic_14,tg_topic_15,tg_topic_16,tg_topic_17,tg_topic_18,tg_topic_19,tg_topic_20,tg_topic_21,tg_topic_22,tg_topic_23,tg_topic_24,tg_topic_25,tg_topic_26,tg_topic_27,tg_topic_28,tg_topic_29,tg_topic_30,tg_topic_31,tg_topic_32,tg_topic_33,tg_topic_34,tg_topic_35,tg_topic_36,tg_topic_37,tg_topic_38,tg_topic_39,tg_topic_40,tg_topic_41,tg_topic_42,tg_topic_43,tg_topic_44,tg_topic_45,tg_topic_46,tg_topic_47,tg_topic_48,tg_topic_49,tg_topic_50,tg_topic_51,tg_topic_52,tg_topic_53,tg_topic_54,tg_topic_55,tg_topic_56,tg_topic_57,tg_topic_58,tg_topic_59,tg_topic_60,tg_topic_61,tg_topic_62,tg_topic_63,tg_topic_64,tg_topic_65,tg_topic_66,tg_topic_67,tg_topic_68,tg_topic_69,tg_topic_70,tg_topic_71,tg_topic_72,tg_topic_73,tg_topic_74,tg_topic_75,tg_topic_76,tg_topic_77,tg_topic_78,tg_topic_79,tg_topic_80,tg_topic_81,tg_topic_82,tg_topic_83,tg_topic_84,tg_topic_85,tg_topic_86,tg_topic_87,tg_topic_88,tg_topic_89,tg_topic_90,tg_topic_91,tg_topic_92,tg_topic_93,tg_topic_94,tg_topic_95,tg_topic_96,tg_topic_97,tg_topic_98,tg_topic_99,tg_topic_100,tg_topic_101,tg_topic_102,tg_topic_103,tg_topic_104,tg_topic_105,tg_topic_106,tg_topic_107,tg_topic_108,tg_topic_109,tg_topic_110,tg_topic_111,tg_topic_112,tg_topic_113,tg_topic_114,tg_topic_115,tg_topic_116,tg_topic_117,tg_topic_118,tg_topic_119,tg_topic_120,tg_topic_121,tg_topic_122,tg_topic_123,tg_topic_124,tg_topic_125,tg_topic_126,tg_topic_127,tg_topic_128,tg_topic_129,tg_topic_130,tg_topic_131,tg_topic_132,tg_topic_133,tg_topic_134,tg_topic_135,tg_topic_136,tg_topic_137,tg_topic_138,tg_topic_139,tg_topic_140,tg_topic_141,tg_topic_142,tg_topic_143,tg_topic_144,tg_topic_145,tg_topic_146,tg_topic_147,tg_topic_148,tg_topic_149,tg_topic_150,tg_topic_151,tg_topic_152,tg_topic_153,tg_topic_154,tg_topic_155,tg_topic_156,tg_topic_157,tg_topic_158,tg_topic_159,tg_topic_160,tg_topic_161,tg_topic_162,tg_topic_163,tg_topic_164,tg_topic_165,tg_topic_166,tg_topic_167,tg_topic_168,tg_topic_169,tg_topic_170,tg_topic_171,tg_topic_172,tg_topic_173,tg_topic_174,tg_topic_175,tg_topic_176,tg_topic_177,tg_topic_178,tg_topic_179,tg_topic_180,tg_topic_181,tg_topic_182,tg_topic_183,tg_topic_184,tg_topic_185,tg_topic_186,tg_topic_187,tg_topic_188,tg_topic_189,tg_topic_190,tg_topic_191,tg_topic_192,tg_topic_193,tg_topic_194,tg_topic_195,tg_topic_196,tg_topic_197,tg_topic_198,tg_topic_199,tg_topic_200,tg_topic_201,tg_topic_202,tg_topic_203,tg_topic_204,tg_topic_205,tg_topic_206,tg_topic_207,tg_topic_208,tg_topic_209,tg_topic_210,tg_topic_211,tg_topic_212,tg_topic_213,tg_topic_214,tg_topic_215,tg_topic_216,tg_topic_217,tg_topic_218,tg_topic_219,tg_topic_220,tg_topic_221,tg_topic_222,tg_topic_223,tg_topic_224,tg_topic_225,tg_topic_226,tg_topic_227,tg_topic_228,tg_topic_229,tg_topic_230,tg_topic_231,tg_topic_232,tg_topic_233,tg_topic_234,tg_topic_235,tg_topic_236,tg_topic_237,tg_topic_238,tg_topic_239,tg_topic_240,tg_topic_241,tg_topic_242,tg_topic_243,tg_topic_244,tg_topic_245,tg_topic_246,tg_topic_247,tg_topic_248,tg_topic_249
241163,2022-07-04 15:00:00,11,48.5085,32.2656,24.6,11.6,47.4,0.000,0.0,0.00,0.0,0.0,11.2,10.8,315.0,1016.5,28.5,343.2,29.6,9.0,0.16,30.9,29.6,29.76,0.00,0.0,0.0,7.9,10.8,360.0,1015.4,8.1,845.0,3.0,8.0,False,True,False,False,True,False,False,False,2022,7,0,15,Kropyvnytskyi,Europe/Kiev,2022-07-04,04:55:06,20:55:20,15:00:00,Кіровоградська,0,0.000000,0.0,0.0,0.0,0.0,5.0,0,0,1.0,0.0,9,0.718522,-0.218250,0.185890,0.014861,-0.080442,0.125194,0.091747,-0.113817,-0.032745,0.034167,-0.134310,-0.181317,0.065708,-0.031923,-0.008929,0.051777,-0.008802,-0.017984,-0.032481,-0.092542,0.044344,-0.081161,-0.111392,0.016035,0.010457,0.016431,0.052485,0.063794,0.031302,-0.015231,0.077580,0.064447,-0.033039,0.057391,0.014409,0.004045,0.049695,-0.039879,-0.028401,-0.022428,0.018271,-0.047720,0.001259,0.005289,-0.064295,0.071443,-0.019068,0.013968,0.027960,0.039390,-0.003695,-0.003916,0.010478,-0.030163,-0.012332,0.044752,0.048974,-0.014478,0.048408,0.055160,0.114244,0.024759,0.102661,-0.027148,0.010859,-0.062119,0.043160,0.018555,0.002355,-0.027595,0.024311,0.021390,0.009081,0.034544,0.009225,-0.001547,0.022192,0.001137,-0.013640,-0.011827,0.021198,-0.007979,0.057318,-0.028145,-0.035109,0.072314,0.034247,0.013066,-0.032987,0.028742,-0.049927,-0.007276,-0.014023,0.021569,-0.062386,0.022029,0.011568,0.044783,0.035105,0.055106,-0.007686,-0.006104,0.014629,0.031363,0.012029,-0.020691,0.018862,0.015094,-0.022676,-0.005577,-0.063287,-0.044447,-0.007206,-0.020879,-0.029354,0.008226,0.004261,0.037089,0.007277,-0.021989,-0.015922,0.008166,-0.031244,-0.019544,0.012197,0.008747,-0.018802,0.005924,-0.001891,0.018535,0.029000,0.001110,0.008148,-0.007306,-0.013557,0.021176,-0.012805,-0.001952,-0.004927,-0.032473,0.005053,0.009049,0.002682,-0.019824,0.008964,0.017903,-0.017359,-0.009158,-0.012388,0.025771,5.693899,0.066374,0.718522,0.037959,0.019824,5.681868,4.375878,0.009169,-0.000245,0.028865,0.004776,-0.007788,0.023428,-0.027402,0.082940,0.010203,-0.033264,-0.043096,0.007079,-0.010258,0.026598,0.071758,0.006198,-0.013591,-0.044628,-0.003427,0.034270,-0.001203,-0.003321,0.008346,0.007723,-0.030349,0.011129,0.001773,0.001762,0.006034,-0.011916,0.000731,-0.010415,0.017548,0.035584,0.039339,-0.034645,0.043556,0.027354,-0.014500,0.037539,0.055589,0.004345,0.039982,0.034542,0.006137,-0.009104,0.003412,0.017865,-0.012772,-0.016242,-0.006954,-0.010026,-0.022997,-0.007804,0.002299,0.003029,0.007071,0.001648,-0.008858,0.006403,-0.011835,0.005370,0.002410,-0.016001,-0.009783,-0.024777,0.006238,-0.008485,-0.001881,0.033560,-0.023145,0.016338,0.007593,-0.000167,-0.026389,-0.012484,0.002426,0.011098,-0.025449,-0.006336,0.000625,0.004079,-0.010635,-0.013395,-0.000093,0.018365,-0.000010,0.004943,0.001002,0.003257,0.001718,0.005948,0.003522,-0.012540,-0.003905,0.009900,-0.011376,0.025058,0.012381,-0.043055,0.002869,0.013578,0.007961,-0.003117,-0.001650,-0.017497,-0.002771,-0.034190,0.005979,0.001818,0.011767,-0.008635,0.016441,-0.019049,-0.020418,0.034308,0.004898,-0.002153,-0.006337,0.011457,0.032206,0.003337,-0.009171,0.013594,-0.012032,0.002419,-0.051761,-0.009023,0.016632,0.010407,-0.018114,-0.035868,-0.007565,-0.036355,0.000532,0.030120,-0.000645,0.028856,0.013805,0.011646,-0.002409,-0.024741,0.001334,0.023247,-0.024773,0.007668,0.026748,0.006122,-0.001622,0.006957,0.014977,0.023644,0.015996,-0.011694,-0.013836,-0.018806,-0.004423,0.008241,-0.026798,0.013335,-0.014190,-0.009812,-0.021145,0.019082,-0.004003,-0.014829,-0.013454,0.021537,-0.017418,0.005048,0.001913,-0.016086,0.013644,0.007002,-0.038422,-0.007286,-0.014608,-0.000832,-0.003660,0.022019,-0.005905,0.002698,-0.019662,0.020064,0.011764,-0.003432,-0.009393,-0.019744,-0.027143,-0.032019,0.016198,0.011328,0.009220,-0.011561,-0.003060,-0.011247,-0.013488,0.023592,-0.016870,-0.025825,-0.022923,-0.005166,0.018418,-0.030888,0.002147,-0.006643,0.009696,-0.012541,-0.004539,0.018141,0.021532,0.015192,0.038077,0.000580,-0.017967,-0.027988,0.042630,-0.003101,-0.002445,0.004723,0.044080,-0.011743,0.018102,-0.019741,-0.013164,-0.009463,0.018936,-0.011863,-0.020090,-0.005087,-0.005291,0.007425,0.025803,0.002778,-0.004073,0.054051,0.020201,0.005195,-0.006851,-0.014434,-0.041841,0.032383,0.029120,-0.004505,-0.003764,0.009271,-0.021815,-0.026695,0.013478,-0.001590
19262,2024-05-06 17:00:00,2,49.2336,28.4486,17.7,7.5,53.0,0.400,100.0,4.17,0.0,0.0,43.6,19.1,231.0,1010.6,81.3,244.1,20.9,7.0,0.94,21.2,21.2,47.81,0.00,0.0,0.0,41.8,17.6,232.8,1009.0,69.9,444.2,1.6,4.0,False,False,True,False,False,True,False,False,2024,5,0,17,Vinnytsia,Europe/Kiev,2024-05-06,05:35:59,20:30:40,17:00:00,Вінницька,0,0.000000,0.0,0.0,0.0,0.0,0.0,0,0,10.0,2.0,49,0.818500,-0.052025,-0.192042,0.132015,-0.037292,-0.021330,0.009147,-0.029553,0.004020,-0.043553,0.026994,0.008552,0.065308,-0.038798,-0.101141,0.034682,0.131600,0.018176,0.010143,0.043151,-0.002151,0.015630,-0.005853,-0.004688,0.048792,-0.030800,0.002553,0.048751,-0.063487,-0.059652,0.005686,-0.006799,0.003249,-0.047878,0.097257,0.040804,0.049636,0.007259,0.016752,-0.015214,0.030949,-0.000062,-0.046958,0.024041,-0.024662,-0.023946,-0.005858,0.034640,0.001063,-0.026149,-0.031563,0.002826,0.004240,0.011978,0.010397,-0.040660,-0.008035,-0.063457,0.000987,0.004215,0.000656,0.015002,0.019303,-0.023184,0.005609,0.003773,-0.015962,-0.008438,-0.041189,-0.019312,0.036320,-0.028066,0.010486,0.007874,-0.002825,0.010512,-0.036811,-0.027800,0.017358,0.012605,0.011782,0.051788,-0.015892,-0.023809,0.013905,-0.043110,0.017533,0.029410,0.004502,-0.019459,0.027383,0.043122,0.028102,0.012539,0.004510,-0.013534,-0.002661,-0.023680,-0.017952,-0.002445,-0.002393,-0.041856,-0.007882,0.019882,0.019322,-0.026449,-0.017162,-0.026670,0.014890,0.034947,0.015894,0.001252,-0.023097,0.000163,-0.035478,-0.003006,-0.010622,0.010511,0.035395,-0.006417,0.007321,-0.030642,0.026675,-0.014622,0.008574,-0.021764,0.016214,0.014534,0.018831,-0.001567,0.023459,0.006743,0.031887,-0.035493,-0.007186,0.011061,0.020700,-0.017398,0.020288,-0.037107,0.013714,0.030237,-0.026371,-0.015489,0.014901,0.013355,0.013834,0.020348,0.023451,0.029652,4.464506,0.069686,0.818500,0.029763,-0.034228,4.472938,4.240392,0.150381,0.225316,-0.081822,0.130805,0.118855,0.075313,-0.014562,0.083196,0.005923,-0.000660,-0.039299,0.002784,-0.005070,-0.056455,-0.009385,-0.007025,-0.003055,0.009229,-0.012029,0.057987,-0.020012,-0.007562,-0.001300,0.003272,0.005433,-0.009430,0.004994,0.005426,-0.010709,-0.005744,0.002297,0.014440,0.013972,0.008372,-0.003799,0.005857,0.008396,-0.003535,0.012588,-0.006463,0.000112,0.007289,0.005778,-0.010171,-0.009152,-0.007966,0.006438,-0.016300,-0.000080,-0.002896,-0.012385,-0.000076,0.015599,-0.006268,-0.008204,-0.002892,0.003190,-0.001569,0.003835,-0.000373,-0.019233,-0.004836,0.004079,-0.002072,0.006435,-0.006071,0.009283,-0.005211,-0.002669,0.006966,-0.001595,-0.003308,0.005209,0.001685,-0.009139,0.005018,-0.009663,0.000533,-0.006051,-0.006218,-0.003440,-0.002842,0.002671,0.005041,-0.000311,0.007615,-0.005667,0.003069,0.009457,0.007006,0.000178,-0.003067,0.001977,0.001160,-0.001053,0.003424,0.004011,-0.008979,-0.004592,0.013568,0.012607,0.006015,0.014270,-0.001412,-0.000975,-0.004124,0.012402,-0.011948,-0.025747,0.011907,-0.001950,0.011181,-0.006850,0.010354,0.005482,-0.006790,0.000999,0.000325,-0.006739,-0.001450,-0.002409,0.000277,0.004278,0.002124,-0.004172,0.004250,-0.015588,0.000953,0.011423,0.007236,0.002867,-0.000036,0.020057,-0.009648,0.003781,-0.020319,0.000081,0.004858,0.010640,0.004528,-0.003680,0.001973,-0.000680,0.000757,0.001265,-0.001350,-0.000420,0.003678,0.004398,-0.005573,-0.008171,0.001004,-0.002975,0.001996,-0.011196,0.008446,0.008779,0.002235,0.012941,-0.004211,0.015629,-0.021646,0.009425,-0.009979,-0.000300,-0.006313,0.012550,-0.010130,0.018076,0.003957,-0.002646,0.001094,0.009962,0.015462,-0.007867,-0.007547,0.018468,-0.008250,-0.007574,-0.003751,-0.012680,0.000762,0.018627,0.004552,-0.002777,0.001327,0.005903,-0.007253,-0.013320,0.002549,-0.001321,-0.010993,-0.001790,-0.000716,0.002319,0.000446,-0.002413,-0.008791,0.008028,0.006569,-0.006948,-0.000243,-0.003935,-0.009058,-0.010617,-0.009392,0.007279,-0.016033,-0.016782,-0.004121,-0.002333,-0.011342,-0.003009,0.005802,-0.007144,0.013237,0.006744,0.013295,0.011604,0.005824,-0.003887,-0.002887,0.000677,0.002099,0.011190,-0.002319,-0.009727,0.010529,0.005049,0.000672,-0.003987,-0.011839,-0.005985,0.003180,-0.008071,-0.007791,-0.005029,-0.003879,-0.005306,0.008991,-0.002187,0.003890,-0.000047,0.001466,-0.002878,-0.000036,-0.000523,-0.004307,0.011064,-0.004843
249903,2023-07-03 20:00:00,11,48.5085,32.2656,22.4,17.2,73.9,3.000,100.0,4.17,0.0,0.0,31.7,18.0,216.4,1010.2,61.7,238.4,20.7,8.0,0.50,20.7,20.7,88.32,0.00,0.0,0.0,16.6,1.8,6.7,1012.0,92.8,71.9,0.3,1.0,False,False,True,False,False,True,False,False,2023,7,0,20,Kropyvnytskyi,Europe/Kiev,2023-07-03,04:54:15,20:55:47,20:00:00,Кіровоградська,0,0.000000,0.0,0.0,0.0,0.0,3.0,0,0,2.0,0.0,16,0.778061,-0.156957,-0.060040,-0.076633,-0.152959,0.144560,0.058420,-0.020705,-0.090325,0.141481,-0.072688,-0.159962,-0.001179,0.037294,0.023041,-0.091952,-0.039071,0.037543,0.098804,0.006260,0.055184,0.027209,0.054890,0.027791,0.001756,-0.079849,-0.008611,0.063767,0.010906,0.034450,-0.052877,-0.003840,0.037465,-0.047342,0.012876,0.012251,-0.007925,0.032496,0.028057,0.010435,0.013652,-0.042226,-0.014485,-0.020272,0.002558,0.015587,0.026525,0.010845,0.020386,-0.018742,-0.036790,-0.027780,0.021312,0.063560,0.007193,0.007146,-0.001075,0.038083,-0.008508,0.009101,0.027860,-0.019108,-0.014273,0.007032,0.033599,0.046586,-0.015932,-0.032489,0.027688,-0.032587,-0.004311,-0.019812,0.034959,0.000648,-0.006058,0.059651,0.032316,-0.019720,-0.005020,0.019457,-0.009500,0.011708,-0.007107,-0.011183,-0.034484,0.008405,0.029341,-0.018314,0.024835,0.038617,-0.070198,0.068598,0.010196,0.023932,-0.019190,-0.014331,-0.036165,-0.003384,-0.034900,-0.021721,-0.000142,0.003200,0.017668,-0.011192,0.009092,0.029230,0.019996,0.016631,-0.012523,0.027118,-0.013112,-0.006027,-0.019074,-0.025012,0.013134,0.010097,0.000166,0.000069,-0.006787,-0.005918,0.053084,-0.017955,0.000042,-0.007449,0.030121,-0.019277,0.016039,-0.018805,-0.023397,0.023238,0.018588,-0.015010,-0.003487,0.017816,0.000852,0.020629,0.006945,-0.006876,-0.030824,-0.020963,-0.018299,-0.001234,0.029448,-0.039027,-0.015352,0.009205,-0.032545,0.031322,0.022331,0.000694,5.016001,0.068337,0.778061,0.033440,0.326927,4.952453,4.293775,0.036933,-0.003706,0.060551,0.000511,-0.030261,0.066894,-0.051566,0.157966,0.013949,-0.026150,0.013036,0.046164,0.022871,0.031010,0.019728,-0.024973,-0.019522,-0.016610,0.024406,-0.068932,-0.020834,-0.012065,0.038957,-0.005587,0.011110,-0.000136,0.028891,0.000724,-0.000649,-0.020688,0.004513,-0.001187,-0.001919,-0.005373,-0.007387,0.016781,0.010324,0.010113,0.000276,-0.008087,-0.008092,-0.025329,0.005877,0.009170,-0.000019,0.000782,-0.022308,0.043522,0.014185,0.021315,0.009495,-0.005801,-0.008391,0.006482,0.019897,-0.005551,0.002695,-0.006867,-0.006747,0.011339,-0.025773,-0.000178,0.005662,-0.006670,0.002097,0.017369,-0.009431,0.003567,0.005547,-0.011213,-0.011170,-0.005618,0.009624,0.012575,-0.029954,0.001641,0.003294,-0.001739,0.037281,0.043913,0.014182,0.019219,-0.014686,-0.028141,-0.021748,0.004150,-0.004983,0.011333,-0.030177,0.012513,-0.027377,0.015575,0.021797,-0.002730,0.008857,-0.010617,-0.020066,0.001876,-0.004801,0.018444,-0.012540,-0.026059,-0.003232,0.007060,0.003838,0.009232,-0.024802,0.011668,0.003816,-0.007141,0.017331,-0.012569,-0.005872,-0.024387,-0.002029,0.000922,-0.013335,0.021882,0.011361,-0.011602,-0.015924,-0.003597,-0.001055,0.005813,0.003347,-0.003047,-0.002852,0.005409,0.016262,-0.006323,-0.022116,-0.014155,-0.042683,0.008431,0.006152,-0.001975,-0.024255,-0.004022,0.053369,0.036998,0.012592,0.017552,-0.020118,-0.000311,-0.026899,0.011729,0.006586,0.022101,0.021693,-0.002526,-0.002410,-0.004274,0.027488,-0.015796,0.016288,-0.015333,0.003960,-0.023208,-0.037292,0.017209,-0.021033,-0.025520,-0.003212,0.008030,0.002383,-0.033113,-0.011964,0.021694,-0.027306,-0.023914,0.004038,-0.015041,0.003576,-0.012755,0.024396,0.016563,-0.034255,0.021628,-0.004955,0.015402,0.014825,0.015543,0.015309,0.008961,-0.004101,-0.024644,0.013734,-0.001876,0.025576,0.004679,0.009520,0.029396,0.007354,-0.032666,0.000746,0.001523,0.009605,0.017894,0.016196,-0.012256,0.027648,-0.006556,0.029270,-0.002186,0.003300,-0.012781,-0.011507,0.002545,0.000829,-0.001556,-0.023083,-0.008143,-0.012992,-0.006442,0.011355,-0.021460,-0.019210,0.012709,-0.013711,0.021963,-0.023518,0.021038,0.027631,-0.005507,-0.032348,-0.017247,0.022036,0.009551,0.002221,0.011930,-0.050398,-0.027018,-0.032739,0.034786,0.000076,-0.026182,0.007099,-0.018572,-0.000484,-0.015243,-0.027532,0.024833,0.011491,0.012709,0.004197,-0.021362,0.015948,-0.007503,0.026600,0.007114

In [31]:
df_final.shape

(634749, 473)

In [32]:
df_final = df_final.sort_values(["datetime_hour"])

In [33]:
with pd.option_context('display.max_rows', None):
    print(df_final.isnull().sum())

datetime_hour                         0
region_id                             0
city_latitude                         0
city_longitude                        0
day_temp                              0
day_dew                               0
day_humidity                          0
day_precip                            0
day_precipprob                        0
day_precipcover                       0
day_snow                              0
day_snowdepth                         0
day_windgust                          0
day_windspeed                         0
day_winddir                           0
day_pressure                          0
day_cloudcover                        0
day_solarradiation                    0
day_solarenergy                       0
day_uvindex                           0
day_moonphase                         0
hour_temp                             0
hour_feelslike                        0
hour_humidity                         0
hour_precip                           0
hour_precipprob                       0
hour_snow                             0
hour_windgust                         0
hour_windspeed                        0
hour_winddir                          0
hour_pressure                         0
hour_cloudcover                       0
hour_solarradiation                   0
hour_solarenergy                      0
hour_uvindex                          0
day_conditions_simple_Clear           0
day_conditions_simple_Cloudy          0
day_conditions_simple_Rain            0
day_conditions_simple_Snow            0
hour_conditions_simple_Clear          0
hour_conditions_simple_Cloudy         0
hour_conditions_simple_Rain           0
hour_conditions_simple_Snow           0
year                                  0
month                                 0
day_of_week                           0
hour                                  0
city_name                             0
city_timezone                         0
day_datetime                          0
day_sunrise                           0
day_sunset                            0
hour_datetime                         0
region_key                            0
alarm_active                          0
alarm_minutes_in_hour                 0
alarm_lag_1                           0
alarm_lag_3                           0
alarm_lag_6                           0
alarm_lag_12                          0
alarms_in_last_24h                    0
is_weekend                            0
is_night                              0
total_active_alarms_lag1              0
neighbour_alarms                      0
hours_since_last_alarm                0
isw_topic_0                           0
isw_topic_1                           0
isw_topic_2                           0
isw_topic_3                           0
isw_topic_4                           0
isw_topic_5                           0
isw_topic_6                           0
isw_topic_7                           0
isw_topic_8                           0
isw_topic_9                           0
isw_topic_10                          0
isw_topic_11                          0
isw_topic_12                          0
isw_topic_13                          0
isw_topic_14                          0
isw_topic_15                          0
isw_topic_16                          0
isw_topic_17                          0
isw_topic_18                          0
isw_topic_19                          0
isw_topic_20                          0
isw_topic_21                          0
isw_topic_22                          0
isw_topic_23                          0
isw_topic_24                          0
isw_topic_25                          0
isw_topic_26                          0
isw_topic_27                          0
isw_topic_28                          0
isw_topic_29                          0
isw_topic_30                          0
isw_topic_31                          0
isw_topic_32                          0
isw_topic_33                          0
isw_topic_34                          0
isw_topic_35                          0
isw_topic_36                          0
isw_topic_37                          0
isw_topic_38                          0
isw_topic_39                          0
isw_topic_40                          0
isw_topic_41                          0
isw_topic_42                          0
isw_topic_43                          0
isw_topic_44                          0
isw_topic_45                          0
isw_topic_46                          0
isw_topic_47                          0
isw_topic_48                          0
isw_topic_49                          0
isw_topic_50                          0
isw_topic_51                          0
isw_topic_52                          0
isw_topic_53                          0
isw_topic_54                          0
isw_topic_55                          0
isw_topic_56                          0
isw_topic_57                          0
isw_topic_58                          0
isw_topic_59                          0
isw_topic_60                          0
isw_topic_61                          0
isw_topic_62                          0
isw_topic_63                          0
isw_topic_64                          0
isw_topic_65                          0
isw_topic_66                          0
isw_topic_67                          0
isw_topic_68                          0
isw_topic_69                          0
isw_topic_70                          0
isw_topic_71                          0
isw_topic_72                          0
isw_topic_73                          0
isw_topic_74                          0
isw_topic_75                          0
isw_topic_76                          0
isw_topic_77                          0
isw_topic_78                          0
isw_topic_79                          0
isw_topic_80                          0
isw_topic_81                          0
isw_topic_82                          0
isw_topic_83                          0
isw_topic_84                          0
isw_topic_85                          0
isw_topic_86                          0
isw_topic_87                          0
isw_topic_88                          0
isw_topic_89                          0
isw_topic_90                          0
isw_topic_91                          0
isw_topic_92                          0
isw_topic_93                          0
isw_topic_94                          0
isw_topic_95                          0
isw_topic_96                          0
isw_topic_97                          0
isw_topic_98                          0
isw_topic_99                          0
isw_topic_100                         0
isw_topic_101                         0
isw_topic_102                         0
isw_topic_103                         0
isw_topic_104                         0
isw_topic_105                         0
isw_topic_106                         0
isw_topic_107                         0
isw_topic_108                         0
isw_topic_109                         0
isw_topic_110                         0
isw_topic_111                         0
isw_topic_112                         0
isw_topic_113                         0
isw_topic_114                         0
isw_topic_115                         0
isw_topic_116                         0
isw_topic_117                         0
isw_topic_118                         0
isw_topic_119                         0
isw_topic_120                         0
isw_topic_121                         0
isw_topic_122                         0
isw_topic_123                         0
isw_topic_124                         0
isw_topic_125                         0
isw_topic_126                         0
isw_topic_127                         0
isw_topic_128                         0
isw_topic_129                         0
isw_topic_130                         0
isw_topic_131                         0
isw_topic_132                         0
isw_topic_133                         0
isw_topic_134                         0
isw_topic_135                         0
isw_topic_136                         0
isw_topic_137                         0
isw_topic_138                         0
isw_topic_139                         0
isw_topic_140                         0
isw_topic_141                         0
isw_topic_142                         0
isw_topic_143                         0
isw_topic_144                         0
isw_topic_145                         0
isw_topic_146                         0
isw_topic_147                         0
isw_topic_148                         0
isw_topic_149                         0
isw_total_intensity                   0
isw_topic_std                         0
isw_topic_max                         0
isw_topic_mean                        0
isw_velocity_24h                      0
isw_intensity_ema                     0
isw_topic_entropy                     0
tg_topic_0                       121631
tg_topic_1                       121631
tg_topic_2                       121631
tg_topic_3                       121631
tg_topic_4                       121631
tg_topic_5                       121631
tg_topic_6                       121631
tg_topic_7                       121631
tg_topic_8                       121631
tg_topic_9                       121631
tg_topic_10                      121631
tg_topic_11                      121631
tg_topic_12                      121631
tg_topic_13                      121631
tg_topic_14                      121631
tg_topic_15                      121631
tg_topic_16                      121631
tg_topic_17                      121631
tg_topic_18                      121631
tg_topic_19                      121631
tg_topic_20                      121631
tg_topic_21                      121631
tg_topic_22                      121631
tg_topic_23                      121631
tg_topic_24                      121631
tg_topic_25                      121631
tg_topic_26                      121631
tg_topic_27                      121631
tg_topic_28                      121631
tg_topic_29                      121631
tg_topic_30                      121631
tg_topic_31                      121631
tg_topic_32                      121631
tg_topic_33                      121631
tg_topic_34                      121631
tg_topic_35                      121631
tg_topic_36                      121631
tg_topic_37                      121631
tg_topic_38                      121631
tg_topic_39                      121631
tg_topic_40                      121631
tg_topic_41                      121631
tg_topic_42                      121631
tg_topic_43                      121631
tg_topic_44                      121631
tg_topic_45                      121631
tg_topic_46                      121631
tg_topic_47                      121631
tg_topic_48                      121631
tg_topic_49                      121631
tg_topic_50                      121631
tg_topic_51                      121631
tg_topic_52                      121631
tg_topic_53                      121631
tg_topic_54                      121631
tg_topic_55                      121631
tg_topic_56                      121631
tg_topic_57                      121631
tg_topic_58                      121631
tg_topic_59                      121631
tg_topic_60                      121631
tg_topic_61                      121631
tg_topic_62                      121631
tg_topic_63                      121631
tg_topic_64                      121631
tg_topic_65                      121631
tg_topic_66                      121631
tg_topic_67                      121631
tg_topic_68                      121631
tg_topic_69                      121631
tg_topic_70                      121631
tg_topic_71                      121631
tg_topic_72                      121631
tg_topic_73                      121631
tg_topic_74                      121631
tg_topic_75                      121631
tg_topic_76                      121631
tg_topic_77                      121631
tg_topic_78                      121631
tg_topic_79                      121631
tg_topic_80                      121631
tg_topic_81                      121631
tg_topic_82                      121631
tg_topic_83                      121631
tg_topic_84                      121631
tg_topic_85                      121631
tg_topic_86                      121631
tg_topic_87                      121631
tg_topic_88                      121631
tg_topic_89                      121631
tg_topic_90                      121631
tg_topic_91                      121631
tg_topic_92                      121631
tg_topic_93                      121631
tg_topic_94                      121631
tg_topic_95                      121631
tg_topic_96                      121631
tg_topic_97                      121631
tg_topic_98                      121631
tg_topic_99                      121631
tg_topic_100                     121631
tg_topic_101                     121631
tg_topic_102                     121631
tg_topic_103                     121631
tg_topic_104                     121631
tg_topic_105                     121631
tg_topic_106                     121631
tg_topic_107                     121631
tg_topic_108                     121631
tg_topic_109                     121631
tg_topic_110                     121631
tg_topic_111                     121631
tg_topic_112                     121631
tg_topic_113                     121631
tg_topic_114                     121631
tg_topic_115                     121631
tg_topic_116                     121631
tg_topic_117                     121631
tg_topic_118                     121631
tg_topic_119                     121631
tg_topic_120                     121631
tg_topic_121                     121631
tg_topic_122                     121631
tg_topic_123                     121631
tg_topic_124                     121631
tg_topic_125                     121631
tg_topic_126                     121631
tg_topic_127                     121631
tg_topic_128                     121631
tg_topic_129                     121631
tg_topic_130                     121631
tg_topic_131                     121631
tg_topic_132                     121631
tg_topic_133                     121631
tg_topic_134                     121631
tg_topic_135                     121631
tg_topic_136                     121631
tg_topic_137                     121631
tg_topic_138                     121631
tg_topic_139                     121631
tg_topic_140                     121631
tg_topic_141                     121631
tg_topic_142                     121631
tg_topic_143                     121631
tg_topic_144                     121631
tg_topic_145                     121631
tg_topic_146                     121631
tg_topic_147                     121631
tg_topic_148                     121631
tg_topic_149                     121631
tg_topic_150                     121631
tg_topic_151                     121631
tg_topic_152                     121631
tg_topic_153                     121631
tg_topic_154                     121631
tg_topic_155                     121631
tg_topic_156                     121631
tg_topic_157                     121631
tg_topic_158                     121631
tg_topic_159                     121631
tg_topic_160                     121631
tg_topic_161                     121631
tg_topic_162                     121631
tg_topic_163                     121631
tg_topic_164                     121631
tg_topic_165                     121631
tg_topic_166                     121631
tg_topic_167                     121631
tg_topic_168                     121631
tg_topic_169                     121631
tg_topic_170                     121631
tg_topic_171                     121631
tg_topic_172                     121631
tg_topic_173                     121631
tg_topic_174                     121631
tg_topic_175                     121631
tg_topic_176                     121631
tg_topic_177                     121631
tg_topic_178                     121631
tg_topic_179                     121631
tg_topic_180                     121631
tg_topic_181                     121631
tg_topic_182                     121631
tg_topic_183                     121631
tg_topic_184                     121631
tg_topic_185                     121631
tg_topic_186                     121631
tg_topic_187                     121631
tg_topic_188                     121631
tg_topic_189                     121631
tg_topic_190                     121631
tg_topic_191                     121631
tg_topic_192                     121631
tg_topic_193                     121631
tg_topic_194                     121631
tg_topic_195                     121631
tg_topic_196                     121631
tg_topic_197                     121631
tg_topic_198                     121631
tg_topic_199                     121631
tg_topic_200                     121631
tg_topic_201                     121631
tg_topic_202                     121631
tg_topic_203                     121631
tg_topic_204                     121631
tg_topic_205                     121631
tg_topic_206                     121631
tg_topic_207                     121631
tg_topic_208                     121631
tg_topic_209                     121631
tg_topic_210                     121631
tg_topic_211                     121631
tg_topic_212                     121631
tg_topic_213                     121631
tg_topic_214                     121631
tg_topic_215                     121631
tg_topic_216                     121631
tg_topic_217                     121631
tg_topic_218                     121631
tg_topic_219                     121631
tg_topic_220                     121631
tg_topic_221                     121631
tg_topic_222                     121631
tg_topic_223                     121631
tg_topic_224                     121631
tg_topic_225                     121631
tg_topic_226                     121631
tg_topic_227                     121631
tg_topic_228                     121631
tg_topic_229                     121631
tg_topic_230                     121631
tg_topic_231                     121631
tg_topic_232                     121631
tg_topic_233                     121631
tg_topic_234                     121631
tg_topic_235                     121631
tg_topic_236                     121631
tg_topic_237                     121631
tg_topic_238                     121631
tg_topic_239                     121631
tg_topic_240                     121631
tg_topic_241                     121631
tg_topic_242                     121631
tg_topic_243                     121631
tg_topic_244                     121631
tg_topic_245                     121631
tg_topic_246                     121631
tg_topic_247                     121631
tg_topic_248                     121631
tg_topic_249                     121631
dtype: int64

In [34]:
df_final = df_final.fillna(0)

In [35]:
tg_cols = [c for c in df_final.columns if 'tg_topic_' in c]
df_tg_abs = df_final[tg_cols].abs()

df_final['tg_total_intensity'] = df_tg_abs.sum(axis=1)
df_final['tg_topic_std'] = df_tg_abs.std(axis=1)
df_final['tg_topic_max'] = df_tg_abs.max(axis=1)
df_final['tg_topic_entropy'] = -(df_tg_abs.div(df_tg_abs.sum(axis=1), axis=0) * np.log(df_tg_abs.div(df_tg_abs.sum(axis=1), axis=0) + 1e-9)).sum(axis=1)

In [36]:
df_final['tg_velocity_3h'] = (df_final.groupby('region_id')['tg_total_intensity'].diff(3).fillna(0))
df_final['tg_intensity_ema_6h'] = (df_final.groupby('region_id')['tg_total_intensity'].transform(lambda x: x.ewm(span=6).mean()))
df_final['tg_intensity_zscore'] = (df_final.groupby('region_id')['tg_total_intensity'].transform(lambda x: (x - x.rolling(24, min_periods=1).mean()) / (x.rolling(24, min_periods=1).std() + 1e-9)))

In [37]:
df_final.sample(20)

,datetime_hour,region_id,city_latitude,city_longitude,day_temp,day_dew,day_humidity,day_precip,day_precipprob,day_precipcover,day_snow,day_snowdepth,day_windgust,day_windspeed,day_winddir,day_pressure,day_cloudcover,day_solarradiation,day_solarenergy,day_uvindex,day_moonphase,hour_temp,hour_feelslike,hour_humidity,hour_precip,hour_precipprob,hour_snow,hour_windgust,hour_windspeed,hour_winddir,hour_pressure,hour_cloudcover,hour_solarradiation,hour_solarenergy,hour_uvindex,day_conditions_simple_Clear,day_conditions_simple_Cloudy,day_conditions_simple_Rain,day_conditions_simple_Snow,hour_conditions_simple_Clear,hour_conditions_simple_Cloudy,hour_conditions_simple_Rain,hour_conditions_simple_Snow,year,month,day_of_week,hour,city_name,city_timezone,day_datetime,day_sunrise,day_sunset,hour_datetime,region_key,alarm_active,alarm_minutes_in_hour,alarm_lag_1,alarm_lag_3,alarm_lag_6,alarm_lag_12,alarms_in_last_24h,is_weekend,is_night,total_active_alarms_lag1,neighbour_alarms,hours_since_last_alarm,isw_topic_0,isw_topic_1,isw_topic_2,isw_topic_3,isw_topic_4,isw_topic_5,isw_topic_6,isw_topic_7,isw_topic_8,isw_topic_9,isw_topic_10,isw_topic_11,isw_topic_12,isw_topic_13,isw_topic_14,isw_topic_15,isw_topic_16,isw_topic_17,isw_topic_18,isw_topic_19,isw_topic_20,isw_topic_21,isw_topic_22,isw_topic_23,isw_topic_24,isw_topic_25,isw_topic_26,isw_topic_27,isw_topic_28,isw_topic_29,isw_topic_30,isw_topic_31,isw_topic_32,isw_topic_33,isw_topic_34,isw_topic_35,isw_topic_36,isw_topic_37,isw_topic_38,isw_topic_39,isw_topic_40,isw_topic_41,isw_topic_42,isw_topic_43,isw_topic_44,isw_topic_45,isw_topic_46,isw_topic_47,isw_topic_48,isw_topic_49,isw_topic_50,isw_topic_51,isw_topic_52,isw_topic_53,isw_topic_54,isw_topic_55,isw_topic_56,isw_topic_57,isw_topic_58,isw_topic_59,isw_topic_60,isw_topic_61,isw_topic_62,isw_topic_63,isw_topic_64,isw_topic_65,isw_topic_66,isw_topic_67,isw_topic_68,isw_topic_69,isw_topic_70,isw_topic_71,isw_topic_72,isw_topic_73,isw_topic_74,isw_topic_75,isw_topic_76,isw_topic_77,isw_topic_78,isw_topic_79,isw_topic_80,isw_topic_81,isw_topic_82,isw_topic_83,isw_topic_84,isw_topic_85,isw_topic_86,isw_topic_87,isw_topic_88,isw_topic_89,isw_topic_90,isw_topic_91,isw_topic_92,isw_topic_93,isw_topic_94,isw_topic_95,isw_topic_96,isw_topic_97,isw_topic_98,isw_topic_99,isw_topic_100,isw_topic_101,isw_topic_102,isw_topic_103,isw_topic_104,isw_topic_105,isw_topic_106,isw_topic_107,isw_topic_108,isw_topic_109,isw_topic_110,isw_topic_111,isw_topic_112,isw_topic_113,isw_topic_114,isw_topic_115,isw_topic_116,isw_topic_117,isw_topic_118,isw_topic_119,isw_topic_120,isw_topic_121,isw_topic_122,isw_topic_123,isw_topic_124,isw_topic_125,isw_topic_126,isw_topic_127,isw_topic_128,isw_topic_129,isw_topic_130,isw_topic_131,isw_topic_132,isw_topic_133,isw_topic_134,isw_topic_135,isw_topic_136,isw_topic_137,isw_topic_138,isw_topic_139,isw_topic_140,isw_topic_141,isw_topic_142,isw_topic_143,isw_topic_144,isw_topic_145,isw_topic_146,isw_topic_147,isw_topic_148,isw_topic_149,isw_total_intensity,isw_topic_std,isw_topic_max,isw_topic_mean,isw_velocity_24h,isw_intensity_ema,isw_topic_entropy,tg_topic_0,tg_topic_1,tg_topic_2,tg_topic_3,tg_topic_4,tg_topic_5,tg_topic_6,tg_topic_7,tg_topic_8,tg_topic_9,tg_topic_10,tg_topic_11,tg_topic_12,tg_topic_13,tg_topic_14,tg_topic_15,tg_topic_16,tg_topic_17,tg_topic_18,tg_topic_19,tg_topic_20,tg_topic_21,tg_topic_22,tg_topic_23,tg_topic_24,tg_topic_25,tg_topic_26,tg_topic_27,tg_topic_28,tg_topic_29,tg_topic_30,tg_topic_31,tg_topic_32,tg_topic_33,tg_topic_34,tg_topic_35,tg_topic_36,tg_topic_37,tg_topic_38,tg_topic_39,tg_topic_40,tg_topic_41,tg_topic_42,tg_topic_43,tg_topic_44,tg_topic_45,tg_topic_46,tg_topic_47,tg_topic_48,tg_topic_49,tg_topic_50,tg_topic_51,tg_topic_52,tg_topic_53,tg_topic_54,tg_topic_55,tg_topic_56,tg_topic_57,tg_topic_58,tg_topic_59,tg_topic_60,tg_topic_61,tg_topic_62,tg_topic_63,tg_topic_64,tg_topic_65,tg_topic_66,tg_topic_67,tg_topic_68,tg_topic_69,tg_topic_70,tg_topic_71,tg_topic_72,tg_topic_73,tg_topic_74,tg_topic_75,tg_topic_76,tg_topic_77,tg_topic_78,tg_topic_79,tg_topic_80,tg_topic_81,tg_topic_82,tg_topic_83,tg_topic_84,tg_topic_85,tg_topic_86,tg_topic_87,tg_topic_88,tg_topic_89,tg_topic_90,tg_topic_91,tg_topic_92,tg_topic_93,tg_topic_94,tg_topic_95,tg_topic_96,tg_topic_97,tg_topic_98,tg_topic_99,tg_topic_100,tg_topic_101,tg_topic_102,tg_topic_103,tg_topic_104,tg_topic_105,tg_topic_106,tg_topic_107,tg_topic_108,tg_topic_109,tg_topic_110,tg_topic_111,tg_topic_112,tg_topic_113,tg_topic_114,tg_topic_115,tg_topic_116,tg_topic_117,tg_topic_118,tg_topic_119,tg_topic_120,tg_topic_121,tg_topic_122,tg_topic_123,tg_topic_124,tg_topic_125,tg_topic_126,tg_topic_127,tg_topic_128,tg_topic_129,tg_topic_130,tg_topic_131,tg_topic_132,tg_topic_133,tg_topic_134,tg_topic_135,tg_topic_136,tg_topic_137,tg_topic_138,tg_topic_139,tg_topic_140,tg_topic_141,tg_topic_142,tg_topic_143,tg_topic_144,tg_topic_145,tg_topic_146,tg_topic_147,tg_topic_148,tg_topic_149,tg_topic_150,tg_topic_151,tg_topic_152,tg_topic_153,tg_topic_154,tg_topic_155,tg_topic_156,tg_topic_157,tg_topic_158,tg_topic_159,tg_topic_160,tg_topic_161,tg_topic_162,tg_topic_163,tg_topic_164,tg_topic_165,tg_topic_166,tg_topic_167,tg_topic_168,tg_topic_169,tg_topic_170,tg_topic_171,tg_topic_172,tg_topic_173,tg_topic_174,tg_topic_175,tg_topic_176,tg_topic_177,tg_topic_178,tg_topic_179,tg_topic_180,tg_topic_181,tg_topic_182,tg_topic_183,tg_topic_184,tg_topic_185,tg_topic_186,tg_topic_187,tg_topic_188,tg_topic_189,tg_topic_190,tg_topic_191,tg_topic_192,tg_topic_193,tg_topic_194,tg_topic_195,tg_topic_196,tg_topic_197,tg_topic_198,tg_topic_199,tg_topic_200,tg_topic_201,tg_topic_202,tg_topic_203,tg_topic_204,tg_topic_205,tg_topic_206,tg_topic_207,tg_topic_208,tg_topic_209,tg_topic_210,tg_topic_211,tg_topic_212,tg_topic_213,tg_topic_214,tg_topic_215,tg_topic_216,tg_topic_217,tg_topic_218,tg_topic_219,tg_topic_220,tg_topic_221,tg_topic_222,tg_topic_223,tg_topic_224,tg_topic_225,tg_topic_226,tg_topic_227,tg_topic_228,tg_topic_229,tg_topic_230,tg_topic_231,tg_topic_232,tg_topic_233,tg_topic_234,tg_topic_235,tg_topic_236,tg_topic_237,tg_topic_238,tg_topic_239,tg_topic_240,tg_topic_241,tg_topic_242,tg_topic_243,tg_topic_244,tg_topic_245,tg_topic_246,tg_topic_247,tg_topic_248,tg_topic_249,tg_total_intensity,tg_topic_std,tg_topic_max,tg_topic_entropy,tg_velocity_3h,tg_intensity_ema_6h,tg_intensity_zscore
100903,2024-08-10 10:00:00,5,48.00200,37.81450,22.7,12.8,57.6,0.0,0.0,0.00,0.0,0.0,27.4,11.5,314.9,1013.4,13.5,232.9,20.3,8.0,0.19,25.0,25.0,47.89,0.0,0.0,0.0,15.8,4.3,324.6,1014.0,2.8,570.3,2.1,6.0,True,False,False,False,True,False,False,False,2024,8,5,10,Donetsk,Europe/Kiev,2024-08-10,05:17:10,19:50:09,10:00:00,Донецька,1,60.000000,1.0,0.0,1.0,1.0,16.0,1,0,6.0,2.0,0,0.778656,0.057104,-0.041531,-0.014969,-0.167454,0.066717,-0.014495,0.101172,0.228252,-0.156633,0.073736,0.017975,-0.121431,-0.102678,0.059007,-0.003968,0.012312,-0.101222,-0.003080,0.054935,0.055476,0.054573,-0.078276,0.084500,-0.064099,-0.077993,0.051501,-0.052371,0.087709,0.016631,0.102628,0.000777,0.039170,-0.064357,0.058425,0.014570,0.006290,-0.027173,-0.030947,0.018322,-0.061517,0.017965,-0.044924,-0.046411,0.006908,0.016207,-0.002747,-0.016152,0.038872,-0.004405,-0.014699,0.020774,-0.019446,-0.039640,-0.026202,-0.012620,0.017852,-0.012730,0.022743,-0.006394,-0.024208,0.039179,-0.015045,-0.026890,-0.013936,-0.023797,-0.017692,-0.004009,0.027696,0.015203,0.001199,0.029835,0.003577,-0.024913,0.006158,-0.009848,-0.014173,-0.021739,0.061797,-0.007358,-0.014709,0.001812,-0.006638,-0.004942,0.000443,0.000445,0.009795,-0.018872,-0.000983,-0.039150,-0.005422,0.015311,0.037667,0.030485,0.012659,0.018500,-0.032455,-0.008006,-0.029481,0.029310,0.020374,0.021189,-0.029361,-0.016713,-0.017050,0.016455,-0.009722,-0.023237,0.022580,0.028150,0.002793,0.002103,-0.029928,-0.025319,0.029328,0.020750,0.012847,0.046610,-0.001114,0.012617,0.017731,-0.017792,-0.004457,-0.027719,-0.014961,-0.005932,-0.015136,-0.002103,0.003585,0.001747,0.009956,-0.009423,0.004598,-0.015110,0.010360,-0.001397,-0.032315,0.013189,-0.016988,0.023738,-0.006305,-0.006636,-0.033601,-0.012893,0.008143,-0.011566,0.002590,-0.010785,0.000867,-0.016232,5.063757,0.069693,0.778656,0.033758,0.774915,4.765412,4.253944,0.200626,0.214942,-0.038456,0.017405,-0.081184,-0.056871,-0.053632,0.104215,-0.023142,-0.073125,-0.002909,0.021227,0.029259,-0.001236,-0.029730,0.027394,0.012062,0.051895,0.022702,0.022455,-0.010619,0.028843,-0.007198,-0.010951,-0.011159,-0.018075,0.002082,-0.006403,0.006907,0.002557,-0.009284,-0.040226,-0.018846,-0.007962,0.008901,-0.006219,-0.003146,-0.000741,0.000931,0.008395,-0.002397,-0.024066,-0.014297,-0.007098,0.008062,0.004372,-0.008986,0.011400,0.005641,-0.007367,0.014356,0.001492,-0.004217,0.000364,-0.006437,-0.019710,-0.016777,-0.004238,-0.003294,-0.002246,0.018309,0.007036,0.005426,-0.000856,-0.007558,0.023166,0.018962,0.000880,0.005312,-0.010807,-0.022410,-0.009370,0.006611,0.007622,0.013513,-0.018918,0.010846,0.011786,-0.011311,-0.003869,0.018285,0.008064,-0.004392,0.016948,0.001962,0.025195,0.019381,0.032969,0.001492,-0.009329,-0.006050,-0.000787,0.000172,0.016989,0.003374,-0.000713,0.010409,-0.001085,-0.002044,-0.006085,0.001860,0.017850,-0.013353,-0.015122,-0.001829,-0.002102,0.009869,0.007428,0.011224,-0.006806,0.000604,0.021987,-0.013774,-0.001799,-0.023463,0.001713,0.008771,-0.001594,0.010762,-0.001473,0.012686,-0.030773,-0.015742,-0.014776,0.036829,0.013561,0.004080,0.008551,0.005881,-0.006875,0.001084,-0.001999,0.002810,0.019290,-0.007683,-0.015940,0.013601,-0.010946,-0.004498,-0.012200,-0.002318,0.013961,-0.002879,-0.016654,0.008551,0.009182,0.007068,0.016769,-0.001759,-0.007394,0.004701,-0.011447,-0.003758,-0.010535,0.009366,-0.020092,-0.018342,0.003394,-0.004123,0.000541,-0.007262,0.002522,0.001686,0.023315,-0.008943,0.000758,0.006677,-0.008651,0.005947,0.006754,-0.021061,0.008918,-0.002139,0.013774,0.003620,0.020044,-0.007099,-0.026343,0.010586,0.009064,0.018837,0.014606,-0.001867,0.023449,0.009004,0.008453,-0.005348,0.000239,-0.023256,0.009877,0.005348,0.000026,0.017705,0.044037,-0.007253,0.024324,-0.038310,-0.015849,-0.000129,-0.018391,-0.014933,0.001783,-0.006052,-0.011954,-0.023453,-0.004723,0.002429,0.004476,-0.017117,-0.019633,0.029929,0.019286,0.021097,0.001550,0.004740,0.008677,-0.014425,0.017174,-0.000104,-0.010294,0.012772,-0.005678,-0.007112,0.003863,0.004518,0.002395,0.008884,0.004670,-0.000627,0.006134,-0.007176,-0.003549,-0.000648,-0.017885,0.006602,0.000974,0.003843,-0.006810,0.000300,0.014460,-0.001251,0.008561,-0.010665,-0.016580,-0.015323,-0.020108,-0.011875,-0.009565,-0.017626,-0.000518,3.393317,0.021678,0.214942,4.923605,-1.450440,4.517197,-0.131639
583476,2022-05-02 16:00:00,25,51.49370,31.29440,11.8,3.4,58.0,0.8,100.0,16.67,0.0,0.0,38.9,16.6,211.7,1019.4,89.6,168.5,14.5,6.0,0.03,16.9,16.9,42.58,0.0,0.0,0.0,33.8,15.5,245.0,1018.0,100.0,454.0,1.6,5.0,False,False,True,False,False,True,False,False,2022,5,0,16,Chernihiv,Europe/Kiev,2022-05-02,05:25:15,20:19:32,16:00:00,Чернігівська,0,0.000000,0.0,0.0,0.0,0.0,0.0,0,0,0.0,0.0,64,0.644091,-0.214388,0.364904,0.139801,0.034561,-0.025649,0.008432,-0.115840,-0.003432,-0.091650,0.035711,0.001189,0.030772,-0.019647,0.049436,0.016042,0.181287,0.033664,-0.027323,-0.076944,-0.005387,0.097601,0.115070,0.093554,0.006702,-0.039411,-0.085815,0.013361,0.045022,-0.048140,-0.068338,0.034777,0.049251,0.057159,0.014451,0.010017,-0.041963,0.053353,-0.026124,-0.010395,-0.028527,0.037895,-0.003877,0.000688,-0.040481,-0.005913,-0.014244,-0.035637,0.026898,-0.029247,0.022658,-0.015327,0.007350,0.011096,-0.004935,-0.003891,0.034734,-0.035445,-0.008239,0.009257,0.002569,-0.030011,0.028364,-0.027998,0.010439,0.015925,-0.039513,-0.034104,0.016624,-0.005567,0.003385,-0.035794,0.016839,-0.043934,-0.010834,-0.023883,0.023890,-0.031016,0.017144,-0.056443,-0.004753,0.060534,0.010095,0.070555,0.010150,0.012389,0.043211,0.006904,-0.015087,-0.011556,0.009485,0.026906,-0.008878,0.059510,-0.041100,0.016678,-0.036461,0.016653,-0.031337,0.046699,-0.032312,-0.026208,0.009095,0.003559,0.003071,0.009923,-0.011478,0.010236,0.024393,-0.079007,-0.000074,0.039105,-0.027146,-0.040172,-0.017827,-0.004784,0.010164,-0.018330,0.009402,-0.025736,-0.004145,0.047678,-0.010886,-0.048586,0.021606,-0.024766,-0.014508,-0.011246,0.005547,0.051329,0.023139,-0.017396,-0.038163,0.005973,-0.008824,-0.019941,0.055889,-0.030223,0.024561,0.025113,0.002620,-0.012629,-0.001171,-0.017922,0.020295,0.001763,0.043568,-0.001257,-0.016754,-0.021561,5.451292,0.065049,0.644091,0.036342,0.280531,5.382265,4.338045,0.004486,-0.000686,0.013536,0.001932,-0.009513,0.027836,-0.020600,0.067160,0.014807,-0.022392,-0.021046,-0.007912,-0.002266,-0.009837,-0.012101,-0.002321,0.004669,-0.007993,-0.012992,-0.020081,0.004552,0.014255,-0.020753,0.006537,0.007634,0.001431,-0.023362,-0.006343,0.003955,0.009344,0.005362,0.002869,-0.002045,-0.006150,0.000164,0.002926,-0.006910,0.008084,-0.011176,0.001069,0.001080,-0.000811,0.007142,0.003184,-0.009528,0.003216,-0.000288,0.009873,0.006193,0.012307,0.002314,0.000361,-0.006102,0.009037,-0.000566,0.002721,0.028621,-0.011095,-0.000836,-0.011036,0.004580,-0.005214,-0.012568,-0.005133,0.014149,0.004346,-0.008195,-0.012249,0.000487,0.018212,-0.004362,0.002156,-0.014594,0.000392,-0.016816,-0.020273,0.022954,0.019181,-0.012223,-0.038389,-0.019113,0.008828,0.007641,-0.013647,-0.004187,-0.018088,-0.017652,-0.010041,0.021147,0.026662,0.085491,-0.003328,-0.026432,-0.032433,0.015550,-0.011229,-0.001189,0.019690,-0.014116,0.071505,0.011060,-0.015859,-0.010062,0.000918,-0.010871,-0.022106,0.002409,-0.064127,0.065315,-0.038386,0.090696,0.023793,-0.029943,-0.054040,-0.015064,0.005280,-0.010890,0.025018,-0.003748,-0.041178,0.018591,-0.051638,-0.011389,-0.023425,-0.004392,-0.002154,0.040461,-0.006399,0.000924,0.024197,-0.006288,-0.015079,-0.040244,-0.014385,-0.003724,0.044384,0.025131,0.011941,0.007727,-0.025636,-0.013490,0.005101,-0.016450,0.001381,0.025032,0.004583,0.001014,-0.038706,-0.009660,0.002756,0.010020,-0.037753,0.011015,-0.009903,-0.015219,-0.015442,0.014473,-0.023801,0.013799,-0.004683,0.004052,-0.020313,0.023477,0.015605,-0.024855,0.008804,-0.011749,0.018664,0.025384,-0.007318,-0.006115,-0.010900,-0.006832,-0.018035,0.040896,-0.012003,-0.018343,0.013222,-0.009302,0.009365,0.000844,-0.034656,0.035145,-0.022663,-0.006048,0.002816,0.022139,0.036234,0.041357,0.002739,0.014644,0.007844,-0.005260,-0.024402,0.014279,-0.006351,-0.020968,0.025839,0.038245,0.020873,0.059061,-0.014471,0.041934,0.001843,0.025004,0.022301,0.003764,0.012467,0.014596,-0.010399,-0.024711,-0.006651,-0.013875,-0.043678,0.038428,0.007582,-0.032081,0.007176,-0.010650,-0.016707,0.008662,-0.018009,-0.003625,0.007933,0.051956,-0.002713,0.016580,-0.014035,-0.008743,0.043195,-0.019204,0.002163,-0.007991,0.053041,0.022509,-0.003084,-0.032575,-0.007178,0.006202,-0.028302,-0.005042,0.009311,-0.014927,0.040908,-0.007229,-0.023265,-0.016645,0.029662,-0.047841,0.030240,4.091715,0.015320,0.090696,5.149121,1.352954,3.245237,0.796280
112875,2022-12-16 07:00:00,6,50.25360,28.66540,0.2,-1.0,92.0,1.1,100.0,16.67,0.0,3.4,33.5,18.7,118.8,1015.5,98.8,3.8,0.3,0.0,0.75,-1.2,-4.3,84.99,0.0,0.0,0.0,18.7,8.3,105.3,1019.0,100.0,0.0,0.1,0.0,False,False,True,False,False,True,False,False,2022,12,4,7,Zhytomyr,Europe/Kiev,2022-12-16,07:59:13,16:02:35,07:00:00,Житомирська,0,0.000000,0.0,0.0,0.0,0.0,0.0,0,0,0.0,0.0,46,0.795350,-0.178362,-0.032170,-0.039466,0.145273,-0.037568,0.208828,0.095865,-0.076194,-0.110484,-0.041710,-0.012769,-0.026336,-0.015670,-0.030605,0.051157,-0.035534,-0.018178,0.099670,0.040762,0.003189,-0.076755,0.026858,-0.044326,-0.063990,-0.005466,0.028349,-0.023707,-0.047941,-0.013554,0.015543,0.028323,-0.050755,-0.000884,0.001089,-0.023632,0.005420,0.058902,0.005380,0.000032,-0.029102,0.036886,-0.002236,-0.051662,0.020569,0.041221,0.002025,-0.020073,0.023901,0.025098,0.057256,-0.017506,0.019903,-0.007782,0.025620,-0.001641,-0.016498,-0.000530,-0.004479,0.007401,-0.037646,0.001777,-0.025597,-0.049820,0.019061,-0.009890,0.038905,0.040482,-0.028846,0.008836,-0.028678,-0.013680,-0.005443,-0.021840,-0.019707,-0.005423,-0.010397,-0.022060,-0.020484,0.005566,0.037351,-0.016203,-0.030425,-0.014115,-0.006747,-0.040327,-0.006817,-0.000237,0.024835,0.008824,-0.017280,-0.002669,-0.011434,-0.032740,0.011084,0.000005,-0.038739,-0.007970,0.004872,0.005985,0.048461,-0.020389,-0.000263,-0.012023,0.007174,0.035240,-0.008641,0.020258,0.003980,-0.009124,-0.001956,-0.028072,-0.005082,-0.037931,-0.021805,-0.015915,0.017109,-0.010056,0.013155,-0.016813,-0.021355,0.039611,-0.008029,-0.029725,0.019380,0.015725,0.003481,0.003334,-0.001090,0.002840,-0.002509,-0.022734,0.028172,-0.014453,0.020187,0.007565,0.004646,0.010098,0.004956,0.007801,-0.002461,-0.012343,-0.010534,-0.012692,-0.034899,0.032550,-0.015043,0.009332,0.006784,0.018911,4.516915,0.069523,0.795350,0.030113,0.247601,4.401954,4.192119,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-0.000000,0.000000,0.360319,-1.220810

# ТУТ БУДЕ EDA

## Weather, ISW, Telegram shift for further models trainings

In [38]:
df_to_train = df_final.copy()
df_to_train = df_to_train.sort_values(['region_id', 'datetime_hour'])

In [40]:
isw_cols = [c for c in df_to_train.columns if 'isw_' in c]
df_to_train[isw_cols] = df_to_train.groupby('region_id')[isw_cols].shift(24).fillna(0)

In [41]:
df_to_train.head()

,datetime_hour,region_id,hour_temp,hour_feelslike,hour_humidity,hour_precip,hour_precipprob,hour_snow,hour_windgust,hour_windspeed,hour_winddir,hour_pressure,hour_cloudcover,hour_solarradiation,hour_solarenergy,hour_uvindex,hour_conditions_simple_Clear,hour_conditions_simple_Cloudy,hour_conditions_simple_Rain,hour_conditions_simple_Snow,city_name,day_sunrise,day_sunset,alarm_active,alarm_minutes_in_hour,alarm_lag_1,alarm_lag_3,alarm_lag_6,alarm_lag_12,alarms_in_last_24h,is_weekend,is_night,total_active_alarms_lag1,neighbour_alarms,hours_since_last_alarm,isw_topic_0,isw_topic_1,isw_topic_2,isw_topic_3,isw_topic_4,isw_topic_5,isw_topic_6,isw_topic_7,isw_topic_8,isw_topic_9,isw_topic_10,isw_topic_11,isw_topic_12,isw_topic_13,isw_topic_14,isw_topic_15,isw_topic_16,isw_topic_17,isw_topic_18,isw_topic_19,isw_topic_20,isw_topic_21,isw_topic_22,isw_topic_23,isw_topic_24,isw_topic_25,isw_topic_26,isw_topic_27,isw_topic_28,isw_topic_29,isw_topic_30,isw_topic_31,isw_topic_32,isw_topic_33,isw_topic_34,isw_topic_35,isw_topic_36,isw_topic_37,isw_topic_38,isw_topic_39,isw_topic_40,isw_topic_41,isw_topic_42,isw_topic_43,isw_topic_44,isw_topic_45,isw_topic_46,isw_topic_47,isw_topic_48,isw_topic_49,isw_topic_50,isw_topic_51,isw_topic_52,isw_topic_53,isw_topic_54,isw_topic_55,isw_topic_56,isw_topic_57,isw_topic_58,isw_topic_59,isw_topic_60,isw_topic_61,isw_topic_62,isw_topic_63,isw_topic_64,isw_topic_65,isw_topic_66,isw_topic_67,isw_topic_68,isw_topic_69,isw_topic_70,isw_topic_71,isw_topic_72,isw_topic_73,isw_topic_74,isw_topic_75,isw_topic_76,isw_topic_77,isw_topic_78,isw_topic_79,isw_topic_80,isw_topic_81,isw_topic_82,isw_topic_83,isw_topic_84,isw_topic_85,isw_topic_86,isw_topic_87,isw_topic_88,isw_topic_89,isw_topic_90,isw_topic_91,isw_topic_92,isw_topic_93,isw_topic_94,isw_topic_95,isw_topic_96,isw_topic_97,isw_topic_98,isw_topic_99,isw_topic_100,isw_topic_101,isw_topic_102,isw_topic_103,isw_topic_104,isw_topic_105,isw_topic_106,isw_topic_107,isw_topic_108,isw_topic_109,isw_topic_110,isw_topic_111,isw_topic_112,isw_topic_113,isw_topic_114,isw_topic_115,isw_topic_116,isw_topic_117,isw_topic_118,isw_topic_119,isw_topic_120,isw_topic_121,isw_topic_122,isw_topic_123,isw_topic_124,isw_topic_125,isw_topic_126,isw_topic_127,isw_topic_128,isw_topic_129,isw_topic_130,isw_topic_131,isw_topic_132,isw_topic_133,isw_topic_134,isw_topic_135,isw_topic_136,isw_topic_137,isw_topic_138,isw_topic_139,isw_topic_140,isw_topic_141,isw_topic_142,isw_topic_143,isw_topic_144,isw_topic_145,isw_topic_146,isw_topic_147,isw_topic_148,isw_topic_149,isw_total_intensity,isw_topic_std,isw_topic_max,isw_topic_mean,isw_velocity_24h,isw_intensity_ema,isw_topic_entropy,tg_topic_0,tg_topic_1,tg_topic_2,tg_topic_3,tg_topic_4,tg_topic_5,tg_topic_6,tg_topic_7,tg_topic_8,tg_topic_9,tg_topic_10,tg_topic_11,tg_topic_12,tg_topic_13,tg_topic_14,tg_topic_15,tg_topic_16,tg_topic_17,tg_topic_18,tg_topic_19,tg_topic_20,tg_topic_21,tg_topic_22,tg_topic_23,tg_topic_24,tg_topic_25,tg_topic_26,tg_topic_27,tg_topic_28,tg_topic_29,tg_topic_30,tg_topic_31,tg_topic_32,tg_topic_33,tg_topic_34,tg_topic_35,tg_topic_36,tg_topic_37,tg_topic_38,tg_topic_39,tg_topic_40,tg_topic_41,tg_topic_42,tg_topic_43,tg_topic_44,tg_topic_45,tg_topic_46,tg_topic_47,tg_topic_48,tg_topic_49,tg_topic_50,tg_topic_51,tg_topic_52,tg_topic_53,tg_topic_54,tg_topic_55,tg_topic_56,tg_topic_57,tg_topic_58,tg_topic_59,tg_topic_60,tg_topic_61,tg_topic_62,tg_topic_63,tg_topic_64,tg_topic_65,tg_topic_66,tg_topic_67,tg_topic_68,tg_topic_69,tg_topic_70,tg_topic_71,tg_topic_72,tg_topic_73,tg_topic_74,tg_topic_75,tg_topic_76,tg_topic_77,tg_topic_78,tg_topic_79,tg_topic_80,tg_topic_81,tg_topic_82,tg_topic_83,tg_topic_84,tg_topic_85,tg_topic_86,tg_topic_87,tg_topic_88,tg_topic_89,tg_topic_90,tg_topic_91,tg_topic_92,tg_topic_93,tg_topic_94,tg_topic_95,tg_topic_96,tg_topic_97,tg_topic_98,tg_topic_99,tg_topic_100,tg_topic_101,tg_topic_102,tg_topic_103,tg_topic_104,tg_topic_105,tg_topic_106,tg_topic_107,tg_topic_108,tg_topic_109,tg_topic_110,tg_topic_111,tg_topic_112,tg_topic_113,tg_topic_114,tg_topic_115,tg_topic_116,tg_topic_117,tg_topic_118,tg_topic_119,tg_topic_120,tg_topic_121,tg_topic_122,tg_topic_123,tg_topic_124,tg_topic_125,tg_topic_126,tg_topic_127,tg_topic_128,tg_topic_129,tg_topic_130,tg_topic_131,tg_topic_132,tg_topic_133,tg_topic_134,tg_topic_135,tg_topic_136,tg_topic_137,tg_topic_138,tg_topic_139,tg_topic_140,tg_topic_141,tg_topic_142,tg_topic_143,tg_topic_144,tg_topic_145,tg_topic_146,tg_topic_147,tg_topic_148,tg_topic_149,tg_topic_150,tg_topic_151,tg_topic_152,tg_topic_153,tg_topic_154,tg_topic_155,tg_topic_156,tg_topic_157,tg_topic_158,tg_topic_159,tg_topic_160,tg_topic_161,tg_topic_162,tg_topic_163,tg_topic_164,tg_topic_165,tg_topic_166,tg_topic_167,tg_topic_168,tg_topic_169,tg_topic_170,tg_topic_171,tg_topic_172,tg_topic_173,tg_topic_174,tg_topic_175,tg_topic_176,tg_topic_177,tg_topic_178,tg_topic_179,tg_topic_180,tg_topic_181,tg_topic_182,tg_topic_183,tg_topic_184,tg_topic_185,tg_topic_186,tg_topic_187,tg_topic_188,tg_topic_189,tg_topic_190,tg_topic_191,tg_topic_192,tg_topic_193,tg_topic_194,tg_topic_195,tg_topic_196,tg_topic_197,tg_topic_198,tg_topic_199,tg_topic_200,tg_topic_201,tg_topic_202,tg_topic_203,tg_topic_204,tg_topic_205,tg_topic_206,tg_topic_207,tg_topic_208,tg_topic_209,tg_topic_210,tg_topic_211,tg_topic_212,tg_topic_213,tg_topic_214,tg_topic_215,tg_topic_216,tg_topic_217,tg_topic_218,tg_topic_219,tg_topic_220,tg_topic_221,tg_topic_222,tg_topic_223,tg_topic_224,tg_topic_225,tg_topic_226,tg_topic_227,tg_topic_228,tg_topic_229,tg_topic_230,tg_topic_231,tg_topic_232,tg_topic_233,tg_topic_234,tg_topic_235,tg_topic_236,tg_topic_237,tg_topic_238,tg_topic_239,tg_topic_240,tg_topic_241,tg_topic_242,tg_topic_243,tg_topic_244,tg_topic_245,tg_topic_246,tg_topic_247,tg_topic_248,tg_topic_249,tg_total_intensity,tg_topic_std,tg_topic_max,tg_topic_entropy,tg_velocity_3h,tg_intensity_ema_6h,tg_intensity_zscore
0,2022-02-24 00:00:00,2,2.1,-0.5,91.76,0.0,0.0,0.0,16.6,8.6,279.6,1021.0,91.1,0.0,0.1,0.0,False,True,False,False,Vinnytsia,06:58:49,17:40:52,0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0.0,0.0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-0.0,0.0,0.0,NaN
1,2022-02-24 01:00:00,2,2.1,-0.4,89.80,0.0,0.0,0.0,16.6,8.3,289.2,1021.0,97.9,0.0,0.1,0.0,False,True,False,False,Vinnytsia,06:58:49,17:40:52,0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0.0,0.0,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-0.0,0.0,0.0,0.0
2,2022-02-24 02:00:00,2,2.0,-0.3,90.44,0.0,0.0,0.0,27.7,7.6,287.6,1021.0,98.2,0.0,0.1,0.0,False,True,False,False,Vinnytsia,06:58:49,17:40:52,0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0.0,0.0,3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-0.0,0.0,0.0,0.0
3,2022-02-24 03:00:00,2,1.9,-0.3,91.75,0.0,0.0,0.0,15.1,7.2,288.9,1021.0,98.8,0.0,0.1,0.0,False,True,False,False,Vinnytsia,06:58:49,17:40:52,0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0.0,0.0,4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-0.0,0.0,0.0,0.0
4,2022-02-24 04:00:00,2,1.8,-0.2,92.40,0.0,0.0,0.0,13.7,6.5,290.4,1021.0,100.0,0.0,0.1,0.0,False,True,False,False,Vinnytsia,06:58:49,17:40:52,0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0.0,0.0,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-0.0,0.0,0.0,0.0

In [42]:
tg_cols = [c for c in df_to_train.columns if 'tg_' in c]
df_to_train[tg_cols] = df_to_train.groupby('region_id')[tg_cols].shift(1).fillna(0)

In [43]:
df_to_train.head(5)

,datetime_hour,region_id,hour_temp,hour_feelslike,hour_humidity,hour_precip,hour_precipprob,hour_snow,hour_windgust,hour_windspeed,hour_winddir,hour_pressure,hour_cloudcover,hour_solarradiation,hour_solarenergy,hour_uvindex,hour_conditions_simple_Clear,hour_conditions_simple_Cloudy,hour_conditions_simple_Rain,hour_conditions_simple_Snow,city_name,day_sunrise,day_sunset,alarm_active,alarm_minutes_in_hour,alarm_lag_1,alarm_lag_3,alarm_lag_6,alarm_lag_12,alarms_in_last_24h,is_weekend,is_night,total_active_alarms_lag1,neighbour_alarms,hours_since_last_alarm,isw_topic_0,isw_topic_1,isw_topic_2,isw_topic_3,isw_topic_4,isw_topic_5,isw_topic_6,isw_topic_7,isw_topic_8,isw_topic_9,isw_topic_10,isw_topic_11,isw_topic_12,isw_topic_13,isw_topic_14,isw_topic_15,isw_topic_16,isw_topic_17,isw_topic_18,isw_topic_19,isw_topic_20,isw_topic_21,isw_topic_22,isw_topic_23,isw_topic_24,isw_topic_25,isw_topic_26,isw_topic_27,isw_topic_28,isw_topic_29,isw_topic_30,isw_topic_31,isw_topic_32,isw_topic_33,isw_topic_34,isw_topic_35,isw_topic_36,isw_topic_37,isw_topic_38,isw_topic_39,isw_topic_40,isw_topic_41,isw_topic_42,isw_topic_43,isw_topic_44,isw_topic_45,isw_topic_46,isw_topic_47,isw_topic_48,isw_topic_49,isw_topic_50,isw_topic_51,isw_topic_52,isw_topic_53,isw_topic_54,isw_topic_55,isw_topic_56,isw_topic_57,isw_topic_58,isw_topic_59,isw_topic_60,isw_topic_61,isw_topic_62,isw_topic_63,isw_topic_64,isw_topic_65,isw_topic_66,isw_topic_67,isw_topic_68,isw_topic_69,isw_topic_70,isw_topic_71,isw_topic_72,isw_topic_73,isw_topic_74,isw_topic_75,isw_topic_76,isw_topic_77,isw_topic_78,isw_topic_79,isw_topic_80,isw_topic_81,isw_topic_82,isw_topic_83,isw_topic_84,isw_topic_85,isw_topic_86,isw_topic_87,isw_topic_88,isw_topic_89,isw_topic_90,isw_topic_91,isw_topic_92,isw_topic_93,isw_topic_94,isw_topic_95,isw_topic_96,isw_topic_97,isw_topic_98,isw_topic_99,isw_topic_100,isw_topic_101,isw_topic_102,isw_topic_103,isw_topic_104,isw_topic_105,isw_topic_106,isw_topic_107,isw_topic_108,isw_topic_109,isw_topic_110,isw_topic_111,isw_topic_112,isw_topic_113,isw_topic_114,isw_topic_115,isw_topic_116,isw_topic_117,isw_topic_118,isw_topic_119,isw_topic_120,isw_topic_121,isw_topic_122,isw_topic_123,isw_topic_124,isw_topic_125,isw_topic_126,isw_topic_127,isw_topic_128,isw_topic_129,isw_topic_130,isw_topic_131,isw_topic_132,isw_topic_133,isw_topic_134,isw_topic_135,isw_topic_136,isw_topic_137,isw_topic_138,isw_topic_139,isw_topic_140,isw_topic_141,isw_topic_142,isw_topic_143,isw_topic_144,isw_topic_145,isw_topic_146,isw_topic_147,isw_topic_148,isw_topic_149,isw_total_intensity,isw_topic_std,isw_topic_max,isw_topic_mean,isw_velocity_24h,isw_intensity_ema,isw_topic_entropy,tg_topic_0,tg_topic_1,tg_topic_2,tg_topic_3,tg_topic_4,tg_topic_5,tg_topic_6,tg_topic_7,tg_topic_8,tg_topic_9,tg_topic_10,tg_topic_11,tg_topic_12,tg_topic_13,tg_topic_14,tg_topic_15,tg_topic_16,tg_topic_17,tg_topic_18,tg_topic_19,tg_topic_20,tg_topic_21,tg_topic_22,tg_topic_23,tg_topic_24,tg_topic_25,tg_topic_26,tg_topic_27,tg_topic_28,tg_topic_29,tg_topic_30,tg_topic_31,tg_topic_32,tg_topic_33,tg_topic_34,tg_topic_35,tg_topic_36,tg_topic_37,tg_topic_38,tg_topic_39,tg_topic_40,tg_topic_41,tg_topic_42,tg_topic_43,tg_topic_44,tg_topic_45,tg_topic_46,tg_topic_47,tg_topic_48,tg_topic_49,tg_topic_50,tg_topic_51,tg_topic_52,tg_topic_53,tg_topic_54,tg_topic_55,tg_topic_56,tg_topic_57,tg_topic_58,tg_topic_59,tg_topic_60,tg_topic_61,tg_topic_62,tg_topic_63,tg_topic_64,tg_topic_65,tg_topic_66,tg_topic_67,tg_topic_68,tg_topic_69,tg_topic_70,tg_topic_71,tg_topic_72,tg_topic_73,tg_topic_74,tg_topic_75,tg_topic_76,tg_topic_77,tg_topic_78,tg_topic_79,tg_topic_80,tg_topic_81,tg_topic_82,tg_topic_83,tg_topic_84,tg_topic_85,tg_topic_86,tg_topic_87,tg_topic_88,tg_topic_89,tg_topic_90,tg_topic_91,tg_topic_92,tg_topic_93,tg_topic_94,tg_topic_95,tg_topic_96,tg_topic_97,tg_topic_98,tg_topic_99,tg_topic_100,tg_topic_101,tg_topic_102,tg_topic_103,tg_topic_104,tg_topic_105,tg_topic_106,tg_topic_107,tg_topic_108,tg_topic_109,tg_topic_110,tg_topic_111,tg_topic_112,tg_topic_113,tg_topic_114,tg_topic_115,tg_topic_116,tg_topic_117,tg_topic_118,tg_topic_119,tg_topic_120,tg_topic_121,tg_topic_122,tg_topic_123,tg_topic_124,tg_topic_125,tg_topic_126,tg_topic_127,tg_topic_128,tg_topic_129,tg_topic_130,tg_topic_131,tg_topic_132,tg_topic_133,tg_topic_134,tg_topic_135,tg_topic_136,tg_topic_137,tg_topic_138,tg_topic_139,tg_topic_140,tg_topic_141,tg_topic_142,tg_topic_143,tg_topic_144,tg_topic_145,tg_topic_146,tg_topic_147,tg_topic_148,tg_topic_149,tg_topic_150,tg_topic_151,tg_topic_152,tg_topic_153,tg_topic_154,tg_topic_155,tg_topic_156,tg_topic_157,tg_topic_158,tg_topic_159,tg_topic_160,tg_topic_161,tg_topic_162,tg_topic_163,tg_topic_164,tg_topic_165,tg_topic_166,tg_topic_167,tg_topic_168,tg_topic_169,tg_topic_170,tg_topic_171,tg_topic_172,tg_topic_173,tg_topic_174,tg_topic_175,tg_topic_176,tg_topic_177,tg_topic_178,tg_topic_179,tg_topic_180,tg_topic_181,tg_topic_182,tg_topic_183,tg_topic_184,tg_topic_185,tg_topic_186,tg_topic_187,tg_topic_188,tg_topic_189,tg_topic_190,tg_topic_191,tg_topic_192,tg_topic_193,tg_topic_194,tg_topic_195,tg_topic_196,tg_topic_197,tg_topic_198,tg_topic_199,tg_topic_200,tg_topic_201,tg_topic_202,tg_topic_203,tg_topic_204,tg_topic_205,tg_topic_206,tg_topic_207,tg_topic_208,tg_topic_209,tg_topic_210,tg_topic_211,tg_topic_212,tg_topic_213,tg_topic_214,tg_topic_215,tg_topic_216,tg_topic_217,tg_topic_218,tg_topic_219,tg_topic_220,tg_topic_221,tg_topic_222,tg_topic_223,tg_topic_224,tg_topic_225,tg_topic_226,tg_topic_227,tg_topic_228,tg_topic_229,tg_topic_230,tg_topic_231,tg_topic_232,tg_topic_233,tg_topic_234,tg_topic_235,tg_topic_236,tg_topic_237,tg_topic_238,tg_topic_239,tg_topic_240,tg_topic_241,tg_topic_242,tg_topic_243,tg_topic_244,tg_topic_245,tg_topic_246,tg_topic_247,tg_topic_248,tg_topic_249,tg_total_intensity,tg_topic_std,tg_topic_max,tg_topic_entropy,tg_velocity_3h,tg_intensity_ema_6h,tg_intensity_zscore
0,2022-02-24 00:00:00,2,2.1,-0.5,91.76,0.0,0.0,0.0,16.6,8.6,279.6,1021.0,91.1,0.0,0.1,0.0,False,True,False,False,Vinnytsia,06:58:49,17:40:52,0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0.0,0.0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2022-02-24 01:00:00,2,2.1,-0.4,89.80,0.0,0.0,0.0,16.6,8.3,289.2,1021.0,97.9,0.0,0.1,0.0,False,True,False,False,Vinnytsia,06:58:49,17:40:52,0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0.0,0.0,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-0.0,0.0,0.0,0.0
2,2022-02-24 02:00:00,2,2.0,-0.3,90.44,0.0,0.0,0.0,27.7,7.6,287.6,1021.0,98.2,0.0,0.1,0.0,False,True,False,False,Vinnytsia,06:58:49,17:40:52,0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0.0,0.0,3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-0.0,0.0,0.0,0.0
3,2022-02-24 03:00:00,2,1.9,-0.3,91.75,0.0,0.0,0.0,15.1,7.2,288.9,1021.0,98.8,0.0,0.1,0.0,False,True,False,False,Vinnytsia,06:58:49,17:40:52,0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0.0,0.0,4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-0.0,0.0,0.0,0.0
4,2022-02-24 04:00:00,2,1.8,-0.2,92.40,0.0,0.0,0.0,13.7,6.5,290.4,1021.0,100.0,0.0,0.1,0.0,False,True,False,False,Vinnytsia,06:58:49,17:40:52,0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0.0,0.0,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-0.0,0.0,0.0,0.0

In [44]:
hour_weather_cols = [c for c in df_to_train.columns if c.startswith('hour_')]
for col in hour_weather_cols:
    if df_to_train[col].dtype == bool:
        df_to_train[col] = df_to_train.groupby('region_id')[col].shift(1).fillna(False)
    else:
        df_to_train[col] = df_to_train.groupby('region_id')[col].shift(1).fillna(0)

C:\Users\vikam\AppData\Local\Temp\ipykernel_23560\2691752085.py:4: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_to_train[col] = df_to_train.groupby('region_id')[col].shift(1).fillna(False)

In [45]:
df_to_train.isna().sum()

datetime_hour          0
region_id              0
hour_temp              0
hour_feelslike         0
hour_humidity          0
                      ..
tg_topic_max           0
tg_topic_entropy       0
tg_velocity_3h         0
tg_intensity_ema_6h    0
tg_intensity_zscore    0
Length: 449, dtype: int64

In [46]:
df_to_train['alarm_minutes_in_hour'] = (df_to_train.groupby('region_id')['alarm_minutes_in_hour'].shift(1).fillna(0))

In [47]:
df_to_train.head()

,datetime_hour,region_id,hour_temp,hour_feelslike,hour_humidity,hour_precip,hour_precipprob,hour_snow,hour_windgust,hour_windspeed,hour_winddir,hour_pressure,hour_cloudcover,hour_solarradiation,hour_solarenergy,hour_uvindex,hour_conditions_simple_Clear,hour_conditions_simple_Cloudy,hour_conditions_simple_Rain,hour_conditions_simple_Snow,city_name,day_sunrise,day_sunset,alarm_active,alarm_minutes_in_hour,alarm_lag_1,alarm_lag_3,alarm_lag_6,alarm_lag_12,alarms_in_last_24h,is_weekend,is_night,total_active_alarms_lag1,neighbour_alarms,hours_since_last_alarm,isw_topic_0,isw_topic_1,isw_topic_2,isw_topic_3,isw_topic_4,isw_topic_5,isw_topic_6,isw_topic_7,isw_topic_8,isw_topic_9,isw_topic_10,isw_topic_11,isw_topic_12,isw_topic_13,isw_topic_14,isw_topic_15,isw_topic_16,isw_topic_17,isw_topic_18,isw_topic_19,isw_topic_20,isw_topic_21,isw_topic_22,isw_topic_23,isw_topic_24,isw_topic_25,isw_topic_26,isw_topic_27,isw_topic_28,isw_topic_29,isw_topic_30,isw_topic_31,isw_topic_32,isw_topic_33,isw_topic_34,isw_topic_35,isw_topic_36,isw_topic_37,isw_topic_38,isw_topic_39,isw_topic_40,isw_topic_41,isw_topic_42,isw_topic_43,isw_topic_44,isw_topic_45,isw_topic_46,isw_topic_47,isw_topic_48,isw_topic_49,isw_topic_50,isw_topic_51,isw_topic_52,isw_topic_53,isw_topic_54,isw_topic_55,isw_topic_56,isw_topic_57,isw_topic_58,isw_topic_59,isw_topic_60,isw_topic_61,isw_topic_62,isw_topic_63,isw_topic_64,isw_topic_65,isw_topic_66,isw_topic_67,isw_topic_68,isw_topic_69,isw_topic_70,isw_topic_71,isw_topic_72,isw_topic_73,isw_topic_74,isw_topic_75,isw_topic_76,isw_topic_77,isw_topic_78,isw_topic_79,isw_topic_80,isw_topic_81,isw_topic_82,isw_topic_83,isw_topic_84,isw_topic_85,isw_topic_86,isw_topic_87,isw_topic_88,isw_topic_89,isw_topic_90,isw_topic_91,isw_topic_92,isw_topic_93,isw_topic_94,isw_topic_95,isw_topic_96,isw_topic_97,isw_topic_98,isw_topic_99,isw_topic_100,isw_topic_101,isw_topic_102,isw_topic_103,isw_topic_104,isw_topic_105,isw_topic_106,isw_topic_107,isw_topic_108,isw_topic_109,isw_topic_110,isw_topic_111,isw_topic_112,isw_topic_113,isw_topic_114,isw_topic_115,isw_topic_116,isw_topic_117,isw_topic_118,isw_topic_119,isw_topic_120,isw_topic_121,isw_topic_122,isw_topic_123,isw_topic_124,isw_topic_125,isw_topic_126,isw_topic_127,isw_topic_128,isw_topic_129,isw_topic_130,isw_topic_131,isw_topic_132,isw_topic_133,isw_topic_134,isw_topic_135,isw_topic_136,isw_topic_137,isw_topic_138,isw_topic_139,isw_topic_140,isw_topic_141,isw_topic_142,isw_topic_143,isw_topic_144,isw_topic_145,isw_topic_146,isw_topic_147,isw_topic_148,isw_topic_149,isw_total_intensity,isw_topic_std,isw_topic_max,isw_topic_mean,isw_velocity_24h,isw_intensity_ema,isw_topic_entropy,tg_topic_0,tg_topic_1,tg_topic_2,tg_topic_3,tg_topic_4,tg_topic_5,tg_topic_6,tg_topic_7,tg_topic_8,tg_topic_9,tg_topic_10,tg_topic_11,tg_topic_12,tg_topic_13,tg_topic_14,tg_topic_15,tg_topic_16,tg_topic_17,tg_topic_18,tg_topic_19,tg_topic_20,tg_topic_21,tg_topic_22,tg_topic_23,tg_topic_24,tg_topic_25,tg_topic_26,tg_topic_27,tg_topic_28,tg_topic_29,tg_topic_30,tg_topic_31,tg_topic_32,tg_topic_33,tg_topic_34,tg_topic_35,tg_topic_36,tg_topic_37,tg_topic_38,tg_topic_39,tg_topic_40,tg_topic_41,tg_topic_42,tg_topic_43,tg_topic_44,tg_topic_45,tg_topic_46,tg_topic_47,tg_topic_48,tg_topic_49,tg_topic_50,tg_topic_51,tg_topic_52,tg_topic_53,tg_topic_54,tg_topic_55,tg_topic_56,tg_topic_57,tg_topic_58,tg_topic_59,tg_topic_60,tg_topic_61,tg_topic_62,tg_topic_63,tg_topic_64,tg_topic_65,tg_topic_66,tg_topic_67,tg_topic_68,tg_topic_69,tg_topic_70,tg_topic_71,tg_topic_72,tg_topic_73,tg_topic_74,tg_topic_75,tg_topic_76,tg_topic_77,tg_topic_78,tg_topic_79,tg_topic_80,tg_topic_81,tg_topic_82,tg_topic_83,tg_topic_84,tg_topic_85,tg_topic_86,tg_topic_87,tg_topic_88,tg_topic_89,tg_topic_90,tg_topic_91,tg_topic_92,tg_topic_93,tg_topic_94,tg_topic_95,tg_topic_96,tg_topic_97,tg_topic_98,tg_topic_99,tg_topic_100,tg_topic_101,tg_topic_102,tg_topic_103,tg_topic_104,tg_topic_105,tg_topic_106,tg_topic_107,tg_topic_108,tg_topic_109,tg_topic_110,tg_topic_111,tg_topic_112,tg_topic_113,tg_topic_114,tg_topic_115,tg_topic_116,tg_topic_117,tg_topic_118,tg_topic_119,tg_topic_120,tg_topic_121,tg_topic_122,tg_topic_123,tg_topic_124,tg_topic_125,tg_topic_126,tg_topic_127,tg_topic_128,tg_topic_129,tg_topic_130,tg_topic_131,tg_topic_132,tg_topic_133,tg_topic_134,tg_topic_135,tg_topic_136,tg_topic_137,tg_topic_138,tg_topic_139,tg_topic_140,tg_topic_141,tg_topic_142,tg_topic_143,tg_topic_144,tg_topic_145,tg_topic_146,tg_topic_147,tg_topic_148,tg_topic_149,tg_topic_150,tg_topic_151,tg_topic_152,tg_topic_153,tg_topic_154,tg_topic_155,tg_topic_156,tg_topic_157,tg_topic_158,tg_topic_159,tg_topic_160,tg_topic_161,tg_topic_162,tg_topic_163,tg_topic_164,tg_topic_165,tg_topic_166,tg_topic_167,tg_topic_168,tg_topic_169,tg_topic_170,tg_topic_171,tg_topic_172,tg_topic_173,tg_topic_174,tg_topic_175,tg_topic_176,tg_topic_177,tg_topic_178,tg_topic_179,tg_topic_180,tg_topic_181,tg_topic_182,tg_topic_183,tg_topic_184,tg_topic_185,tg_topic_186,tg_topic_187,tg_topic_188,tg_topic_189,tg_topic_190,tg_topic_191,tg_topic_192,tg_topic_193,tg_topic_194,tg_topic_195,tg_topic_196,tg_topic_197,tg_topic_198,tg_topic_199,tg_topic_200,tg_topic_201,tg_topic_202,tg_topic_203,tg_topic_204,tg_topic_205,tg_topic_206,tg_topic_207,tg_topic_208,tg_topic_209,tg_topic_210,tg_topic_211,tg_topic_212,tg_topic_213,tg_topic_214,tg_topic_215,tg_topic_216,tg_topic_217,tg_topic_218,tg_topic_219,tg_topic_220,tg_topic_221,tg_topic_222,tg_topic_223,tg_topic_224,tg_topic_225,tg_topic_226,tg_topic_227,tg_topic_228,tg_topic_229,tg_topic_230,tg_topic_231,tg_topic_232,tg_topic_233,tg_topic_234,tg_topic_235,tg_topic_236,tg_topic_237,tg_topic_238,tg_topic_239,tg_topic_240,tg_topic_241,tg_topic_242,tg_topic_243,tg_topic_244,tg_topic_245,tg_topic_246,tg_topic_247,tg_topic_248,tg_topic_249,tg_total_intensity,tg_topic_std,tg_topic_max,tg_topic_entropy,tg_velocity_3h,tg_intensity_ema_6h,tg_intensity_zscore
0,2022-02-24 00:00:00,2,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,False,False,False,False,Vinnytsia,06:58:49,17:40:52,0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0.0,0.0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2022-02-24 01:00:00,2,2.1,-0.5,91.76,0.0,0.0,0.0,16.6,8.6,279.6,1021.0,91.1,0.0,0.1,0.0,False,True,False,False,Vinnytsia,06:58:49,17:40:52,0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0.0,0.0,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-0.0,0.0,0.0,0.0
2,2022-02-24 02:00:00,2,2.1,-0.4,89.80,0.0,0.0,0.0,16.6,8.3,289.2,1021.0,97.9,0.0,0.1,0.0,False,True,False,False,Vinnytsia,06:58:49,17:40:52,0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0.0,0.0,3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-0.0,0.0,0.0,0.0
3,2022-02-24 03:00:00,2,2.0,-0.3,90.44,0.0,0.0,0.0,27.7,7.6,287.6,1021.0,98.2,0.0,0.1,0.0,False,True,False,False,Vinnytsia,06:58:49,17:40:52,0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0.0,0.0,4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-0.0,0.0,0.0,0.0
4,2022-02-24 04:00:00,2,1.9,-0.3,91.75,0.0,0.0,0.0,15.1,7.2,288.9,1021.0,98.8,0.0,0.1,0.0,False,True,False,False,Vinnytsia,06:58:49,17:40:52,0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0.0,0.0,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-0.0,0.0,0.0,0.0

In [48]:
df_to_train.to_parquet("final_merged_dataset.parquet", index = False, engine = "pyarrow")