# Data merge and feature engineering

In [1]:
%pip install pyarrow

Requirement already satisfied: pyarrow in d:\скаченное\python3.13.1\lib\site-packages (23.0.1)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.3.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import string

import re
import nltk
from nltk.stem import WordNetLemmatizer
from nltk.corpus import stopwords
from sklearn.feature_extraction.text import TfidfVectorizer
from tqdm.notebook import tqdm
from tqdm import tqdm
import pymorphy3
from collections import Counter

import os
from pathlib import Path
import json

In [3]:
df_weather = pd.read_csv("../data/weather_processed.csv")
df_war_events = pd.read_csv("../data/war_events_processed.csv")
df_isw_matrix = pd.read_csv("../data/isw_processed_svd.csv")

In [4]:
pd.set_option('display.max_columns', None)

In [5]:
df_weather['datetime_hour'] = pd.to_datetime(df_weather['datetime_hour'], errors="coerce")
df_war_events['datetime_hour'] = pd.to_datetime(df_war_events['datetime_hour'], errors="coerce")

In [6]:
df_final = pd.merge(
    df_weather, 
    df_war_events[['datetime_hour', 'region_id', 'alarm_active', 'alarm_minutes_in_hour']], 
    on=['datetime_hour', 'region_id'], 
    how='left'
)
df_final.sample(20)

,datetime_hour,region_id,city_latitude,city_longitude,day_temp,day_dew,day_humidity,day_precip,day_precipprob,day_precipcover,day_snow,day_snowdepth,day_windgust,day_windspeed,day_winddir,day_pressure,day_cloudcover,day_solarradiation,day_solarenergy,day_uvindex,day_moonphase,hour_temp,hour_feelslike,hour_humidity,hour_precip,hour_precipprob,hour_snow,hour_windgust,hour_windspeed,hour_winddir,hour_pressure,hour_cloudcover,hour_solarradiation,hour_solarenergy,hour_uvindex,day_conditions_simple_Clear,day_conditions_simple_Cloudy,day_conditions_simple_Rain,day_conditions_simple_Snow,hour_conditions_simple_Clear,hour_conditions_simple_Cloudy,hour_conditions_simple_Rain,hour_conditions_simple_Snow,year,month,day_of_week,hour,city_name,city_timezone,day_datetime,day_sunrise,day_sunset,hour_datetime,region_key,alarm_active,alarm_minutes_in_hour
473880,2024-05-26 20:00:00,2,49.23360,28.44860,18.0,4.1,44.7,0.000,0.0,0.00,0.0,0.0,31.0,12.2,68.2,1023.1,18.7,330.9,28.5,9.0,0.60,20.1,20.1,35.09,0.0,0.0,0.0,23.8,10.4,68.3,1022.0,83.7,121.0,0.4,1.0,True,False,False,False,False,True,False,False,2024,5,6,20,Vinnytsia,Europe/Kiev,2024-05-26,05:10:18,20:57:07,20:00:00,Вінницька,0,0.000000
402048,2024-01-23 02:00:00,2,49.23360,28.44860,-1.8,-4.6,81.1,0.100,100.0,4.17,0.0,7.1,44.3,21.6,191.0,1025.7,98.1,39.9,3.4,2.0,0.42,-2.1,-8.2,88.13,0.0,0.0,0.0,44.3,21.6,180.0,1027.1,100.0,0.0,0.0,0.0,False,False,False,True,False,True,False,False,2024,1,1,2,Vinnytsia,Europe/Kiev,2024-01-23,07:49:21,16:47:01,02:00:00,Вінницька,0,0.000000
76112,2022-07-06 04:00:00,10,50.45060,30.52430,26.8,15.6,54.8,8.000,100.0,4.17,0.0,0.0,40.3,16.9,185.6,1011.8,62.7,218.5,18.7,8.0,0.23,22.0,22.0,70.09,0.0,0.0,0.0,11.2,4.0,106.8,1014.0,31.3,0.0,0.1,0.0,False,False,True,False,False,True,False,False,2022,7,2,4,Kyiv,Europe/Kiev,2022-07-06,04:54:19,21:10:38,04:00:00,Київська,0,0.000000
574430,2024-11-17 09:00:00,17,50.61930,26.25130,3.4,0.2,80.3,0.000,0.0,0.00,0.0,0.0,31.7,21.4,230.4,1010.7,33.9,0.0,0.0,0.0,0.55,2.1,-0.1,84.74,0.0,0.0,0.0,12.6,7.2,211.6,1012.0,23.4,5.6,0.1,0.0,False,True,False,False,False,True,False,False,2024,11,6,9,Rivne,Europe/Kiev,2024-11-17,07:33:48,16:25:48,09:00:00,Рівненська,1,23.500000
615111,2025-01-27 00:00:00,18,50.90800,34.79720,4.4,3.6,94.6,0.115,100.0,8.33,0.0,0.0,39.6,23.4,193.8,1020.6,100.0,14.4,1.4,1.0,0.93,3.3,-1.4,95.84,0.0,0.0,0.0,38.2,22.0,189.2,1023.0,100.0,0.0,0.0,0.0,False,False,True,False,False,True,False,False,2025,1,0,0,Sumy,Europe/Kiev,2025-01-27,07:24:12,16:23:41,00:00:00,Сумська,1,60.000000
104596,2022-08-24 15:00:00,6,50.25360,28.66540,23.9,12.3,52.0,0.000,0.0,0.00,0.0,0.0,37.4,19.4,96.4,1018.6,20.7,254.0,21.9,8.0,0.88,31.2,29.5,25.42,0.0,0.0,0.0,36.7,10.8,150.0,1018.1,0.0,711.0,2.6,7.0,False,True,False,False,True,False,False,False,2022,8,2,15,Zhytomyr,Europe/Kiev,2022-08-24,06:07:32,20:06:59,15:00:00,Житомирська,1,13.933333
626308,2025-02-15 11:00:00,6,50.25360,28.66540,-5.8,-9.4,76.9,1.000,100.0,4.17,0.9,1.1,40.3,20.2,320.6,1019.4,83.2,66.4,5.7,3.0,0.59,-5.4,-10.0,62.68,0.0,0.0,0.0,38.2,10.8,340.0,1020.5,40.0,224.7,0.8,2.0,False,False,False,True,False,True,False,False,2025,2,5,11,Zhytomyr,Europe/Kiev,2025-02-15,07:16:18,17:23:29,11:00:00,Житомирська,0,0.000000
551254,2024-10-08 03:00:00,25,51.49370,31.29440,10.6,7.4,81.4,0.100,100.0,4.17,0.0,0.0,52.6,27.4,284.1,1011.5,76.4,57.2,4.9,3.0,0.19,9.2,5.9,92.83,0.0,0.0,0.0,43.9,24.8,281.0,1009.0,100.0,0.0,0.0,0.0,False,False,True,False,False,True,False,False,2024,10,1,3,Chernihiv,Europe/Kiev,2024-10-08,07:07:32,18:16:11,03:00:00,Чернігівська,0,0.000000
523852,2024-08-21 14:00:00,6,50.25360,28.66540,25.3,13.1,53.1,0.000,0.0,0.00,0.0,0.0,18.0,10.1,120.2,1009.5,15.4,244.9,21.0,8.0,0.56,33.7,32.2,26.08,0.0,0.0,0.0,18.0,7.9,128.8,1009.0,1.4,730.4,2.6,7.0,True,False,False,False,True,False,False,False,2024,8,2,14,Zhytomyr,Europe/Kiev,2024-08-21,06:03:49,20:12:02,14:00:00,Житомирська,0,0.000000
447440,2024-04-10 22:00:00,10,50.45060,30.52430,19.0,6.7,47.3,0.000,0.0,0.00,0.0,0.0,27.4,14.4,206.7,1019.3,0.8,239.9,20.8,7.0,0.05,17.4,17.4,59.37,0.0,0.0,0.0,11.5,9.4,175.5,1021.0,0.0,0.0,0.0,0.0,True,False,False,False,True,False,False,False,2024,4,2,22,Kyiv,Europe/Kiev,2024-04-10,06:14:03,19:45:16,22:00:00,Київська,0,0.000000
322316,2023-09-06 15:00:00,23,49.44070,32.06370,19.3,11.3,62.4,0.000,0.0,0.00,0.0,0.0,28.4,13.0,336.9,1022.2,61.5,201.7,17.5,6.0,0.71,24.8,24.8,39.49,0.0,0.0,0.0,27.7,12.6,323.1,1022.0,32.8,548.6,2.0,5.0,False,True,False,False,False,True,False,False,2023,9,2,15,Cherkasy,Europe/Kiev,2023-09-06,06:14:10,19:25:26,15:00:00,Черкаська,0,0.000000
206445,2023-02-17 10:00:00,24,48.29240,25.93550,5.6,-1.4,62.0,0.000,0.0,0.00,0.0,0.0,36.0,17.8,267.0,1020.1,56.2,104.2,9.0,4.0,0.90,4.9,1.8,65.42,0.0,0.0,0.0,21.6,13.7,261.0,1021.5,35.6,228.0,0.8,2.0,False,True,False,False,False,True,False,False,2023,2,4,10,Chernivtsi,Europe/Kiev,2023-02-17,07:20:36,17:40:45,10:00:00,Чернівецька,0,0.000000
225148,2023-03-21 22:00:00,6,50.25360,28.66540,8.3,4.5,78.3,0.900,100.0,16.67,0.0,0.0,26.3,13.3,281.8,1013.8,77.3,141.1,12.1,6.0,0.00,8.6,7.2,89.06,0.0,0.0,0.0,14.0,8.6,324.7,1015.0,31.9,0.0,0.0,0.0,False,False,True,False,False,True,False,False,2023,3,1,22,Zhytomyr,Europe/Kiev,2023-03-21,06:06:52,18:19:20,22:00:00,Житомирська,0,0.000000
351102,2023-10-26 15:00:00,8,47.82890,35.16260,14.3,13.5,94.5,3.700,100.0,37.50,0.0,0.0,48.2,28.8,196.8,1003.3,85.8,29.6,2.3,1.0,0.41,15.7,15.7,91.38,0.1,100.0,0.0,22.7,12.6,261.2,1004.0,96.4,78.2,0.3,1.0,False,False,True,False,False,False,True,False,2023,10,3,15,Zaporozhye,Europe/Zaporozhye,2023-10-26,07:14:01,17:32:00,15:00:00,Запорізька,0,0.000000
20546,2022-03-31 17:00:00,4,48.47530,35.01600,12.4,4.1,59.6,0.000,0.0,0.00,0.0,0.0,59.4,31.8,193.1,1007.2,85.2,172.0,14.8,7.0,0.95,18.6,18.6,37.72,0.0,0.0,0.0,59.4,24.1,204.5,1006.0,100.0,380.0,1.4,4.0,False,True,False,False,False,True,False,False,2022,3,3,17,Dnipro,Europe/Kiev,2022-03-31,06:20:26,19:08:47,17:00:00,Дніпропетровська,1,39.950000
408445,2024-02-03 04:00:00,16,49.58790,34.55170,0.3,-1.1,90.4,4.000,100.0,4.17,2.8,0.3,52.6,31.0,241.7,1008.3,93.7,24.3,2.1,1.0,0.75,-1.0,-5.6,88.89,0.0,0.0,0.0,25.9,14.8,265.1,1014.0,100.0,0.0,0.0,0.0,False,False,False,True,False,True,False,False,2024,2,5,4,Poltava,Europe/Kiev,2024-02-03,07:12:15,16:39:34,04:00:00,Полтавська,0,0.000000
166112,2022-12-09 10:00:00,10,50.45060,30.52430,-0.2,-0.6,97.3,0.100,100.0,4.17,0.0,8.3,20.5,9.0,146.4,1015.6,99.2,10.1,0.9,1.0,0.51,-0.2,-0.2,94.33,0.0,0.0,0.0,10.8,4.7,130.6,1016.0,99.4,80.0,0.3,1.0,False,False,False,True,False,True,False,False,2022,12,4,10,Kyiv,Europe/Kiev,2022-12-09,07:46:11,15:54:04,10:00:00,Київська,0,0.000000
250398,2023-05-04 19:00:00,8,47.82890,35.16260,14.8,7.3,63.5,90.000,100.0,4.17,0.0,0.0,15.5,11.2,213.0,1023.8,45.8,293.4,25.4,9.0,0.46,19.4,19.4,44.80,0.0,0.0,0.0,7.6,4.7,212.0,1021.0,100.0,124.7,0.4,1.0,False,False,True,False,False,True,False,False,2023,5,3,19,Zaporozhye,Europe/Zaporozhye,2023-05-04,05:17:39,19:55:40,19:00:00,Запорізька,0,0.000000
512863,2024-08-02 12:00:00,9,48.92260,24.71470,23.1,16.2,68.3,0.000,0.0,0.00,0.0,0.0,23.0,10.8,103.8,1008.0,78.0,213.6,18.6,6.0,0.93,25.7,25.7,56.46,0.0,0.0,0.0,18.4,7.2,50.0,1008.2,80.0,577.2,2.1,6.0,False,True,False,False,False,True,False,False,2024,8,4,12,Ivano-Frankivsk,Europe/Kiev,2024-08-02,05:56:03,20:57:57,12:00:00,Івано-Франківська,0,0.000000
53237,2022-05-27 11:00:00,7,48.62636,22.28514,17.1,8.5,59.8,0.548,100.0,4.17,0.0,0.0,61.2,23.6,256.8,1015.8,44.6,306.2,26.3,9.0,0.88,19.9,19.9,49.60,0.0,0.0,0.0,12.6,9.0,253.0,1016.9,45.4,669.0,2.4,7.0,False,False,True,False,False,True,False,False,2022,5,4,11,Uzhgorod,Europe/Uzhgorod,2022-05-27,05:37:02,21:19:43,11:00:00,Закарпатська,0,0.000000

In [7]:
df_final = df_final.sort_values(['region_id', 'datetime_hour'])
df_final.head()

,datetime_hour,region_id,city_latitude,city_longitude,day_temp,day_dew,day_humidity,day_precip,day_precipprob,day_precipcover,day_snow,day_snowdepth,day_windgust,day_windspeed,day_winddir,day_pressure,day_cloudcover,day_solarradiation,day_solarenergy,day_uvindex,day_moonphase,hour_temp,hour_feelslike,hour_humidity,hour_precip,hour_precipprob,hour_snow,hour_windgust,hour_windspeed,hour_winddir,hour_pressure,hour_cloudcover,hour_solarradiation,hour_solarenergy,hour_uvindex,day_conditions_simple_Clear,day_conditions_simple_Cloudy,day_conditions_simple_Rain,day_conditions_simple_Snow,hour_conditions_simple_Clear,hour_conditions_simple_Cloudy,hour_conditions_simple_Rain,hour_conditions_simple_Snow,year,month,day_of_week,hour,city_name,city_timezone,day_datetime,day_sunrise,day_sunset,hour_datetime,region_key,alarm_active,alarm_minutes_in_hour
0,2022-02-24 00:00:00,2,49.2336,28.4486,2.8,-0.3,80.5,0.3,100.0,4.17,0.0,0.0,27.7,10.8,312.0,1023.4,82.5,60.4,5.4,3.0,0.77,2.1,-0.5,91.76,0.0,0.0,0.0,16.6,8.6,279.6,1021.0,91.1,0.0,0.1,0.0,False,False,False,True,False,True,False,False,2022,2,3,0,Vinnytsia,Europe/Kiev,2022-02-24,06:58:49,17:40:52,00:00:00,Вінницька,0,0.0
24,2022-02-24 01:00:00,2,49.2336,28.4486,2.8,-0.3,80.5,0.3,100.0,4.17,0.0,0.0,27.7,10.8,312.0,1023.4,82.5,60.4,5.4,3.0,0.77,2.1,-0.4,89.80,0.0,0.0,0.0,16.6,8.3,289.2,1021.0,97.9,0.0,0.1,0.0,False,False,False,True,False,True,False,False,2022,2,3,1,Vinnytsia,Europe/Kiev,2022-02-24,06:58:49,17:40:52,01:00:00,Вінницька,0,0.0
48,2022-02-24 02:00:00,2,49.2336,28.4486,2.8,-0.3,80.5,0.3,100.0,4.17,0.0,0.0,27.7,10.8,312.0,1023.4,82.5,60.4,5.4,3.0,0.77,2.0,-0.3,90.44,0.0,0.0,0.0,27.7,7.6,287.6,1021.0,98.2,0.0,0.1,0.0,False,False,False,True,False,True,False,False,2022,2,3,2,Vinnytsia,Europe/Kiev,2022-02-24,06:58:49,17:40:52,02:00:00,Вінницька,0,0.0
72,2022-02-24 03:00:00,2,49.2336,28.4486,2.8,-0.3,80.5,0.3,100.0,4.17,0.0,0.0,27.7,10.8,312.0,1023.4,82.5,60.4,5.4,3.0,0.77,1.9,-0.3,91.75,0.0,0.0,0.0,15.1,7.2,288.9,1021.0,98.8,0.0,0.1,0.0,False,False,False,True,False,True,False,False,2022,2,3,3,Vinnytsia,Europe/Kiev,2022-02-24,06:58:49,17:40:52,03:00:00,Вінницька,0,0.0
96,2022-02-24 04:00:00,2,49.2336,28.4486,2.8,-0.3,80.5,0.3,100.0,4.17,0.0,0.0,27.7,10.8,312.0,1023.4,82.5,60.4,5.4,3.0,0.77,1.8,-0.2,92.40,0.0,0.0,0.0,13.7,6.5,290.4,1021.0,100.0,0.0,0.1,0.0,False,False,False,True,False,True,False,False,2022,2,3,4,Vinnytsia,Europe/Kiev,2022-02-24,06:58:49,17:40:52,04:00:00,Вінницька,0,0.0

In [8]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
Index: 634680 entries, 0 to 634679
Data columns (total 56 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   datetime_hour                  634680 non-null  datetime64[ns]
 1   region_id                      634680 non-null  int64
 2   city_latitude                  634680 non-null  float64
 3   city_longitude                 634680 non-null  float64
 4   day_temp                       634680 non-null  float64
 5   day_dew                        634680 non-null  float64
 6   day_humidity                   634680 non-null  float64
 7   day_precip                     634680 non-null  float64
 8   day_precipprob                 634680 non-null  float64
 9   day_precipcover                634680 non-null  float64
 10  day_snow                       634680 non-null  float64
 11  day_snowdepth                  634680 non-null  float64
 12  day_windgust                   634680 non-null  float64
 13  day_windspeed                  634680 non-null  float64
 14  day_winddir                    634680 non-null  float64
 15  day_pressure                   634680 non-null  float64
 16  day_cloudcover                 634680 non-null  float64
 17  day_solarradiation             634680 non-null  float64
 18  day_solarenergy                634680 non-null  float64
 19  day_uvindex                    634680 non-null  float64
 20  day_moonphase                  634680 non-null  float64
 21  hour_temp                      634680 non-null  float64
 22  hour_feelslike                 634680 non-null  float64
 23  hour_humidity                  634680 non-null  float64
 24  hour_precip                    634680 non-null  float64
 25  hour_precipprob                634680 non-null  float64
 26  hour_snow                      634680 non-null  float64
 27  hour_windgust                  634680 non-null  float64
 28  hour_windspeed                 634680 non-null  float64
 29  hour_winddir                   634680 non-null  float64
 30  hour_pressure                  634680 non-null  float64
 31  hour_cloudcover                634680 non-null  float64
 32  hour_solarradiation            634680 non-null  float64
 33  hour_solarenergy               634680 non-null  float64
 34  hour_uvindex                   634680 non-null  float64
 35  day_conditions_simple_Clear    634680 non-null  bool
 36  day_conditions_simple_Cloudy   634680 non-null  bool
 37  day_conditions_simple_Rain     634680 non-null  bool
 38  day_conditions_simple_Snow     634680 non-null  bool
 39  hour_conditions_simple_Clear   634680 non-null  bool
 40  hour_conditions_simple_Cloudy  634680 non-null  bool
 41  hour_conditions_simple_Rain    634680 non-null  bool
 42  hour_conditions_simple_Snow    634680 non-null  bool
 43  year                           634680 non-null  int64
 44  month                          634680 non-null  int64
 45  day_of_week                    634680 non-null  int64
 46  hour                           634680 non-null  int64
 47  city_name                      634680 non-null  object
 48  city_timezone                  634680 non-null  object
 49  day_datetime                   634680 non-null  object
 50  day_sunrise                    634680 non-null  object
 51  day_sunset                     634680 non-null  object
 52  hour_datetime                  634680 non-null  object
 53  region_key                     634680 non-null  object
 54  alarm_active                   634680 non-null  int64
 55  alarm_minutes_in_hour          634680 non-null  float64
dtypes: bool(8), datetime64[ns](1), float64(34), int64(6), object(7)
memory usage: 242.1+ MB

In [9]:
df_final = df_final.sort_values(["region_id", "datetime_hour"])

df_final["alarm_lag_1"] = df_final.groupby("region_id")["alarm_active"].shift(1)
df_final["alarm_lag_3"] = df_final.groupby("region_id")["alarm_active"].shift(3)
df_final["alarm_lag_6"] = df_final.groupby("region_id")["alarm_active"].shift(6)
df_final["alarm_lag_12"] = df_final.groupby("region_id")["alarm_active"].shift(12)

lag_cols = ["alarm_lag_1","alarm_lag_3","alarm_lag_6","alarm_lag_12"]
df_final[lag_cols] = df_final[lag_cols].fillna(0)

df_final['alarms_in_last_24h'] = (df_final.groupby('region_id')['alarm_active'].transform(lambda x: x.shift(1).rolling(24, min_periods=1).sum()))

df_final['is_weekend'] = df_final['day_of_week'].isin([5, 6]).astype(int)
df_final['is_night'] = ((df_final['hour'] >= 23) | (df_final['hour'] <= 6)).astype(int)

hourly_total = df_final.groupby('datetime_hour')['alarm_active'].sum().shift(1)
df_final['total_active_alarms_lag1'] = df_final['datetime_hour'].map(hourly_total)

df_final.sample(10)

,datetime_hour,region_id,city_latitude,city_longitude,day_temp,day_dew,day_humidity,day_precip,day_precipprob,day_precipcover,day_snow,day_snowdepth,day_windgust,day_windspeed,day_winddir,day_pressure,day_cloudcover,day_solarradiation,day_solarenergy,day_uvindex,day_moonphase,hour_temp,hour_feelslike,hour_humidity,hour_precip,hour_precipprob,hour_snow,hour_windgust,hour_windspeed,hour_winddir,hour_pressure,hour_cloudcover,hour_solarradiation,hour_solarenergy,hour_uvindex,day_conditions_simple_Clear,day_conditions_simple_Cloudy,day_conditions_simple_Rain,day_conditions_simple_Snow,hour_conditions_simple_Clear,hour_conditions_simple_Cloudy,hour_conditions_simple_Rain,hour_conditions_simple_Snow,year,month,day_of_week,hour,city_name,city_timezone,day_datetime,day_sunrise,day_sunset,hour_datetime,region_key,alarm_active,alarm_minutes_in_hour,alarm_lag_1,alarm_lag_3,alarm_lag_6,alarm_lag_12,alarms_in_last_24h,is_weekend,is_night,total_active_alarms_lag1
135828,2022-10-17 20:00:00,15,46.4725,30.7371,12.5,5.5,63.3,0.000,0.0,0.00,0.0,0.0,23.8,12.2,28.4,1032.9,1.3,153.9,13.3,6.0,0.71,14.4,14.4,56.65,0.0,0.0,0.0,10.4,5.4,16.3,1034.0,0.0,0.0,0.1,0.0,True,False,False,False,True,False,False,False,2022,10,0,20,Odesa,Europe/Kiev,2022-10-17,07:16:52,18:07:17,20:00:00,Одеська,0,0.0,0.0,1.0,1.0,1.0,12.0,0,0,3.0
562855,2024-10-28 07:00:00,9,48.9226,24.7147,9.8,7.1,84.2,0.000,0.0,0.00,0.0,0.0,30.2,18.0,300.8,1025.0,67.8,129.4,11.2,5.0,0.86,12.3,12.3,81.91,0.0,0.0,0.0,28.1,14.0,314.0,1024.0,75.2,5.6,0.1,0.0,False,True,False,False,False,True,False,False,2024,10,0,7,Ivano-Frankivsk,Europe/Kiev,2024-10-28,07:02:21,17:06:46,07:00:00,Івано-Франківська,0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,12.0
214583,2023-03-03 13:00:00,26,50.4506,30.5243,2.2,-1.8,75.4,0.100,100.0,4.17,0.0,0.0,36.7,19.1,267.3,1014.0,85.8,62.4,5.4,3.0,0.37,4.3,0.3,61.73,0.0,0.0,0.0,34.6,19.1,266.0,1012.0,97.4,256.2,0.9,3.0,False,False,True,False,False,True,False,False,2023,3,4,13,Kyiv,Europe/Kiev,2023-03-03,06:38:28,17:42:15,13:00:00,Київ,0,0.0,0.0,1.0,0.0,0.0,4.0,0,0,0.0
238454,2023-04-14 01:00:00,17,50.6193,26.2513,9.3,7.0,86.4,0.007,100.0,8.33,0.0,0.0,40.0,28.5,96.3,1010.4,90.1,118.6,10.4,4.0,0.79,7.7,7.1,93.39,0.0,0.0,0.0,9.4,5.0,100.8,1009.0,22.4,0.0,0.0,0.0,False,False,True,False,False,True,False,False,2023,4,4,1,Rivne,Europe/Kiev,2023-04-14,06:23:58,20:07:51,01:00:00,Рівненська,0,0.0,0.0,0.0,0.0,0.0,2.0,0,1,0.0
358418,2023-11-08 08:00:00,4,48.4753,35.0160,10.3,7.5,83.2,1.000,100.0,4.17,0.0,0.0,46.8,23.4,184.8,1014.7,80.0,33.0,2.8,2.0,0.84,8.2,5.7,78.04,0.0,0.0,0.0,24.5,14.4,190.0,1019.3,90.0,65.4,0.2,1.0,False,False,True,False,False,True,False,False,2023,11,2,8,Dnipro,Europe/Kiev,2023-11-08,06:36:12,16:10:30,08:00:00,Дніпропетровська,0,0.0,0.0,0.0,0.0,0.0,14.0,0,0,0.0
552107,2024-10-09 15:00:00,14,46.9734,31.9852,16.3,12.4,79.6,0.000,0.0,0.00,0.0,0.0,35.6,18.4,171.7,1014.1,48.1,125.6,10.9,4.0,0.22,23.4,23.4,51.69,0.0,0.0,0.0,35.6,10.8,230.0,1012.9,90.0,383.6,1.4,4.0,False,True,False,False,False,True,False,False,2024,10,2,15,Mykolaiv,Europe/Kiev,2024-10-09,07:02:05,18:15:41,15:00:00,Миколаївська,0,0.0,0.0,0.0,0.0,1.0,9.0,0,0,0.0
540295,2024-09-19 03:00:00,9,48.9226,24.7147,15.1,9.4,72.2,0.900,100.0,4.17,0.0,0.0,28.8,14.4,91.5,1025.5,62.4,142.2,12.2,6.0,0.54,13.2,13.2,91.83,0.0,0.0,0.0,21.2,3.6,70.0,1025.4,60.0,0.0,0.0,0.0,False,False,True,False,False,True,False,False,2024,9,3,3,Ivano-Frankivsk,Europe/Kiev,2024-09-19,07:03:47,19:25:00,03:00:00,Івано-Франківська,0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,11.0
482234,2024-06-10 08:00:00,4,48.4753,35.0160,25.8,13.2,49.6,0.000,0.0,0.00,0.0,0.0,37.1,21.6,188.7,1011.0,45.4,292.9,25.4,8.0,0.12,26.4,26.4,50.82,0.0,0.0,0.0,19.8,9.0,168.6,1012.0,95.1,326.2,1.2,3.0,False,True,False,False,False,True,False,False,2024,6,0,8,Dnipro,Europe/Kiev,2024-06-10,04:38:28,20:40:55,08:00:00,Дніпропетровська,0,0.0,0.0,0.0,0.0,0.0,10.0,0,0,0.0
250745,2023-05-05 09:00:00,20,50.0042,36.2358,14.4,6.4,60.0,0.300,100.0,8.33,0.0,0.0,31.3,21.6,358.2,1018.6,84.9,221.2,19.1,7.0,0.50,17.1,17.1,58.34,0.0,0.0,0.0,11.9,0.2,60.0,1019.4,80.0,421.9,1.5,4.0,False,False,True,False,False,True,False,False,2023,5,4,9,Kharkiv,Europe/Kiev,2023-05-05,05:05:19,19:59:20,09:00:00,Харківська,0,0.0,0.0,1.0,0.0,0.0,9.0,0,0,0.0
519611,2024-08-14 05:00:00,14,46.9734,31.9852,22.4,8.5,43.6,0.000,0.0,0.00,0.0,0.0,29.9,14.4,6.3,1017.4,2.9,285.1,24.9,8.0,0.32,15.0,15.0,69.65,0.0,0.0,0.0,17.6,9.4,13.3,1017.0,0.0,0.0,0.0,0.0,True,False,False,False,True,False,False,False,2024,8,2,5,Mykolaiv,Europe/Kiev,2024-08-14,05:48:24,20:04:10,05:00:00,Миколаївська,0,0.0,0.0,1.0,0.0,0.0,7.0,0,1,7.0

In [10]:
neighbouring_regions = {
    1: [21],
    2: [6, 10, 11, 15, 22, 23, 24],
    3: [13, 17],
    4: [5, 8, 11, 14, 16, 20, 21],
    5: [4, 8, 12, 20],
    6: [2, 10, 17, 22],
    7: [9, 13],
    8: [4, 5, 21],
    9: [7, 13, 19, 24],
    10: [2, 6, 16, 23, 25],
    11: [2, 4, 14, 15, 16, 23],
    12: [5, 20],
    13: [3, 7, 9, 17, 19],
    14: [4, 11, 15, 21],
    15: [2, 11, 14],
    16: [4, 10, 11, 18, 20, 23, 25],
    17: [3, 6, 13, 19, 22],
    18: [16, 20, 25],
    19: [9, 13, 17, 22, 24],
    20: [4, 5, 12, 16, 18],
    21: [1, 4, 8, 14],
    22: [2, 6, 17, 19, 24],
    23: [2, 10, 11, 16],
    24: [2, 9, 19, 22],
    25: [10, 16, 18], 
    26: [10]
}

alarms_matrix = df_final.pivot_table(
    index='datetime_hour',
    columns='region_id',
    values='alarm_active',
    fill_value=0
)

neighbour_alarm_matrix = pd.DataFrame(index=alarms_matrix.index)

for region, neighbours in neighbouring_regions.items():
    valid_neighbours = [n for n in neighbours if n in alarms_matrix.columns]
    
    if valid_neighbours:
        neighbour_alarm_matrix[region] = alarms_matrix[valid_neighbours].sum(axis=1)
    else:
        neighbour_alarm_matrix[region] = 0

neighbour_alarm_matrix = neighbour_alarm_matrix.shift(1)

neighbour_alarm_long = (neighbour_alarm_matrix.stack().reset_index())

neighbour_alarm_long.columns = ['datetime_hour','region_id','neighbour_alarms']

df_final = df_final.merge(neighbour_alarm_long,on=['datetime_hour', 'region_id'], how='left')

In [11]:
def calculate_hours_since_last(series):
    series = series.shift(1).fillna(0)
    groups = series.cumsum()
    return series.groupby(groups).cumcount()

df_final['hours_since_last_alarm'] = (df_final.groupby('region_id')['alarm_active'].transform(calculate_hours_since_last))

In [12]:
df_final.sample(20)

,datetime_hour,region_id,city_latitude,city_longitude,day_temp,day_dew,day_humidity,day_precip,day_precipprob,day_precipcover,day_snow,day_snowdepth,day_windgust,day_windspeed,day_winddir,day_pressure,day_cloudcover,day_solarradiation,day_solarenergy,day_uvindex,day_moonphase,hour_temp,hour_feelslike,hour_humidity,hour_precip,hour_precipprob,hour_snow,hour_windgust,hour_windspeed,hour_winddir,hour_pressure,hour_cloudcover,hour_solarradiation,hour_solarenergy,hour_uvindex,day_conditions_simple_Clear,day_conditions_simple_Cloudy,day_conditions_simple_Rain,day_conditions_simple_Snow,hour_conditions_simple_Clear,hour_conditions_simple_Cloudy,hour_conditions_simple_Rain,hour_conditions_simple_Snow,year,month,day_of_week,hour,city_name,city_timezone,day_datetime,day_sunrise,day_sunset,hour_datetime,region_key,alarm_active,alarm_minutes_in_hour,alarm_lag_1,alarm_lag_3,alarm_lag_6,alarm_lag_12,alarms_in_last_24h,is_weekend,is_night,total_active_alarms_lag1,neighbour_alarms,hours_since_last_alarm
22931,2024-10-06 14:00:00,2,49.23360,28.44860,15.3,14.2,93.2,17.300,100.0,8.33,0.0,0.0,26.3,11.5,282.4,1008.4,100.0,39.3,3.5,2.0,0.12,15.6,15.6,89.62,0.000,0.0,0.0,22.7,9.4,279.9,1008.0,100.0,100.6,0.4,1.0,False,False,True,False,False,True,False,False,2024,10,6,14,Vinnytsia,Europe/Kiev,2024-10-06,07:13:47,18:33:53,14:00:00,Вінницька,0,0.000000,0.0,0.0,0.0,1.0,10.0,1,0,2.0,0.0,3
111284,2022-10-11 09:00:00,6,50.25360,28.66540,7.4,2.2,73.5,0.000,0.0,0.00,0.0,0.0,20.2,10.1,210.0,1024.2,27.7,143.4,12.4,5.0,0.51,4.2,4.2,89.96,0.000,0.0,0.0,5.0,0.0,188.6,1025.4,10.0,116.0,0.4,1.0,False,True,False,False,True,False,False,False,2022,10,1,9,Zhytomyr,Europe/Kiev,2022-10-11,07:20:47,18:22:37,09:00:00,Житомирська,1,60.000000,1.0,0.0,0.0,0.0,6.0,0,0,24.0,4.0,0
264886,2022-03-14 04:00:00,13,49.84440,24.02540,1.8,-5.1,62.7,0.000,0.0,0.00,0.0,0.0,28.1,14.4,143.8,1034.5,0.0,191.4,16.5,5.0,0.38,-2.5,-5.1,79.85,0.000,0.0,0.0,14.8,6.5,112.5,1035.0,0.0,0.0,0.1,0.0,True,False,False,False,True,False,False,False,2022,3,0,4,Lviv,Europe/Kiev,2022-03-14,06:40:02,18:27:07,04:00:00,Львівська,1,60.000000,1.0,0.0,0.0,0.0,6.0,0,1,19.0,5.0,0
365452,2024-08-14 22:00:00,16,49.58790,34.55170,18.5,9.6,58.9,0.000,0.0,0.00,0.0,0.0,38.9,18.0,319.1,1016.5,25.5,193.2,16.6,8.0,0.32,19.5,19.5,54.91,0.000,0.0,0.0,12.6,7.6,326.0,1018.0,1.5,0.0,0.0,0.0,False,True,False,False,True,False,False,False,2024,8,2,22,Poltava,Europe/Kiev,2024-08-14,05:31:32,20:00:24,22:00:00,Полтавська,1,0.600000,1.0,1.0,0.0,1.0,14.0,0,0,7.0,4.0,0
232253,2024-07-05 08:00:00,10,50.45060,30.52430,20.8,14.6,70.0,0.700,100.0,12.50,0.0,0.0,39.6,19.4,300.1,1009.7,59.8,270.3,23.5,8.0,0.98,18.7,18.7,86.49,0.100,100.0,0.0,27.0,13.3,294.0,1009.0,82.4,155.5,0.6,2.0,False,False,True,False,False,False,True,False,2024,7,4,8,Kyiv,Europe/Kiev,2024-07-05,04:53:57,21:10:54,08:00:00,Київська,0,0.000000,0.0,0.0,1.0,0.0,6.0,0,0,7.0,3.0,3
121252,2023-11-30 18:00:00,6,50.25360,28.66540,-3.8,-7.4,76.9,0.000,0.0,0.00,0.0,6.2,45.4,22.0,227.8,1011.6,65.4,56.9,4.9,3.0,0.60,-2.1,-7.5,71.83,0.000,0.0,0.0,28.1,17.3,198.4,1012.0,20.8,0.0,0.0,0.0,False,True,False,False,False,True,False,False,2023,11,3,18,Zhytomyr,Europe/Kiev,2023-11-30,07:41:19,16:06:10,18:00:00,Житомирська,0,0.000000,0.0,0.0,0.0,0.0,2.0,0,0,4.0,0.0,12
139667,2022-12-31 03:00:00,7,48.62636,22.28514,6.4,5.6,95.1,1.088,100.0,8.33,0.0,0.4,28.8,10.8,155.6,1025.7,98.0,8.3,0.6,0.0,0.25,5.0,3.3,95.63,0.000,0.0,0.0,17.6,7.2,160.0,1024.6,100.0,0.0,0.1,0.0,False,False,True,False,False,True,False,False,2022,12,5,3,Uzhgorod,Europe/Uzhgorod,2022-12-31,08:23:27,16:44:23,03:00:00,Закарпатська,0,0.000000,0.0,0.0,0.0,0.0,1.0,1,1,1.0,0.0,14
255817,2024-03-07 06:00:00,11,48.50850,32.26560,-0.5,-5.0,72.2,0.000,0.0,0.00,0.0,0.0,29.9,18.0,32.9,1023.8,93.9,81.0,6.9,3.0,0.90,-2.0,-6.6,81.76,0.000,0.0,0.0,26.3,13.7,36.5,1023.0,94.9,0.0,0.0,0.0,False,True,False,False,False,True,False,False,2024,3,3,6,Kropyvnytskyi,Europe/Kiev,2024-03-07,06:19:58,17:44:38,06:00:00,Кіровоградська,0,0.000000,0.0,0.0,0.0,0.0,6.0,0,1,0.0,0.0,12
311313,2024-06-23 21:00:00,14,46.97340,31.98520,25.8,14.7,54.0,0.000,0.0,0.00,0.0,0.0,36.7,19.1,238.9,1010.9,14.8,323.1,28.0,9.0,0.55,26.2,26.2,53.09,0.000,0.0,0.0,23.0,7.2,250.0,1010.2,56.0,18.0,0.1,0.0,True,False,False,False,False,True,False,False,2024,6,6,21,Mykolaiv,Europe/Kiev,2024-06-23,04:57:47,20:51:03,21:00:00,Миколаївська,0,0.000000,1.0,0.0,1.0,0.0,6.0,1,0,4.0,3.0,0
228250,2024-01-20 12:00:00,10,50.45060,30.52430,-1.8,-5.8,74.8,0.800,100.0,16.67,0.0,2.4,35.6,18.0,288.9,1020.2,95.7,32.8,3.0,2.0,0.31,-1.3,-6.5,61.75,0.000,0.0,0.0,34.6,17.3,308.6,1023.0,96.5,135.4,0.5,1.0,False,False,False,True,False,True,False,False,2024,1,5,12,Kyiv,Europe/Kiev,2024-01-20,07:48:35,16:29:29,12:00:00,Київська,1,29.933333,0.0,0.0,0.0,1.0,2.0,1,0,2.0,1.0,10
330751,2023-09-05 21:00:00,15,46.47250,30.73710,23.1,12.8,53.3,0.100,100.0,4.17,0.0,0.0,47.2,27.4,19.6,1018.6,29.9,201.0,17.3,7.0,0.68,24.6,24.6,56.55,0.000,0.0,0.0,36.0,18.0,30.0,1019.2,30.0,0.0,0.0,0.0,False,False,True,False,False,True,False,False,2023,9,1,21,Odesa,Europe/Kiev,2023-09-05,06:21:35,19:29:24,21:00:00,Одеська,0,0.000000,0.0,0.0,0.0,0.0,0.0,0,0,2.0,0.0,30
237691,2025-02-16 22:00:00,10,50.45060,30.52430,-6.8,-11.0,73.2,0.700,100.0,4.17,2.6,4.9,30.2,15.5,286.1,1020.1,61.3,104.6,9.1,4.0,0.62,-9.9,-15.2,85.98,0.000,0.0,0.0,10.1,10.1,184.5,1022.0,97.0,0.0,0.0,0.0,False,False,False,True,False,True,False,False,2025,2,6,22,Kyiv,Europe/Kiev,2025-02-16,07:07:26,17:17:22,22:00:00,Київська,1,27.566667,0.0,0.0,0.0,0.0,7.0,1,0,13.0,4.0,17
179841,2024-07-25 06:00:00,8,47.82890,35.16260,23.5,11.8,49.1,0.000,0.0,0.00,0.0,0.0,23.8,15.1,59.1,1007.0,49.6,256.2,22.1,7.0,0.64,18.0,18.0,64.46,0.000,0.0,0.0,18.7,13.3,38.6,1008.0,0.0,22.8,0.1,0.0,False,True,False,False,True,False,False,False,2024,7,3,6,Zaporozhye,Europe/Zaporozhye,2024-07-25,05:07:47,20:23:23,06:00:00,Запорізька,1,16.950000,1.0,0.0,0.0,1.0,10.0,0,1,7.0,0.0,0
75690,2024-10-01 03:00:00,4,48.47530,35.01600,18.7,4.9,41.5,0.000,0.0,0.00,0.0,0.0,45.4,28.8,93.0,1008.1,15.8,166.5,14.3,6.0,0.95,17.4,17.4,48.40,0.000,0.0,0.0,25.6,10.8,100.0,1007.8,60.0,0.0,0.0,0.0,True,False,False,False,False,True,False,False,2024,10,1,3,Dnipro,Europe/Kiev,2024-10-01,06:39:41,18:18:33,03:00:00,Дніпропетровська,0,0.000000,0.0,0.0,0.0,0.0,7.0,0,1,5.0,2.0,8
338192,2024-07-11 23:00:00,15,46.47250,30.73710,30.9,11.6,33.8,0.000,0.0,0.00,0.0,0.0,37.1,18.0,66.1,1014.8,10.0,325.4,28.1,9.0,0.18,28.0,27.8,42.27,0.000,0.0,0.0,11.5,6.5,298.2,1014.0,2.0,0.0,0.0,0.0,True,False,False,False,True,False,False,False,2024,7,3,23,Odesa,Europe/Kiev,2024-07-11,05:15:56,20:48:59,23:00:00,Одеська,1,17.666667,1.0,0.0,1.0,0.0,9.0,0,1,24.0,3.0,0
36076,2023-04-01 09:00:00,3,50.74690,25.32630,9.0,6.5,84.7,4.467,100.0,8.33,0.0,0.0,29.5,14.0,210.3,999.8,84.9,99.8,8.5,4.0,0.34,7.2,5.9,91.11,1.346,100.0,0.0,20.9,7.2,151.0,999.4,100.0,23.3,0.1,0.0,False,False,True,False,False,False,True,False,2023,4,5,9,Lutsk,Europe/Kiev,2023-04-01,06:55:39,19:50:43,09:00:00,Волинська,0,0.000000,0.0,0.0,0.0,0.0,0.0,1,0,0.0,0.0,43
576967,2024-08-13 01:00:00,24,48.29240,25.93550,21.3,12.0,59.0,0.000,0.0,0.00,0.0,0.0,25.9,14.3,340.5,1014.6,27.0,266.3,23.0,8.0,0.29,18.2,18.2,71.22,0.000,0.0,0.0,11.5,8.3,290.0,1014.9,0.0,0.0,0.0,0.0,False,True,False,False,True,False,False,False,2024,8,1,1,Chernivtsi,Europe/Kiev,2024-08-13,06:08:01,20:33:16,01:00:00,Чернівецька,0,0.000000,0.0,0.0,0.0,0.0,0.0,0,1,13.0,0.0,113
99935,2024-07-01 11:00:00,5,48.00200,37.81450,25.6,12.4,47.3,0.000,0.0,0.00,0.0,0.0,29.2,11.5,65.4,1012.3,10.2,310.3,26.8,8.0,0.84,31.6,30.2,28.41,0.000,0.0,0.0,25.2,8.3,69.4,1013.0,1.6,779.4,2.8,8.0,True,False,False,False,True,False,False,False,2024,7,0,11,Donetsk,Europe/Kiev,2024-07-01,04:33:34,20:31:40,11:00:00,Донецька,1,60.000000,1.0,1.0,1.0,0.0,21.0,0,0,3.0,2.0,0
124232,2024-04-02 23:00:00,6,50.25360,28.66540,16.5,7.6,57.7,2.000,100.0,4.17,0.0,0.0,64.8,30.6,210.0,998.9,64.1,184.9,16.1,7.0,0.75,8.4,4.4,78.07,0.000,0.0,0.0,56.5,30.6,246.7,998.0,100.0,0.0,0.0,0.0,False,False,True,False,False,True,False,False,2024,4,1,23,Zhytomyr,Europe/Kiev,2024-04-02,06:38:56,19:39:42,23:00:00,Житомирська,0,0.000000,0.0,0.0,0.0,0.0,0.0,0,1,2.0,0.0,64
236676,2025-01-05 15:00:00,10,50.45060,30.52430,-3.6,-7.8,73.1,0.000,0.0,0.00,0.0,0.0,42.1,22.7,233.5,1020.5,21.6,51.5,4.3,3.0,0.20,-0.7,-4.9,60.95,0.000,0.0,0.0,28.1,13.0,201.2,1020.0,88.8,113.8,0.4,1.0,False,True,False,False,False,True,False,False,2025,1,6,15,Kyiv,Europe/Kiev,2025-01-05,07:57:52,16:09:15,15:00:00,Київська,0,0.000000,1.0,1.0,0.0,0.0,11.0,1,0,6.0,1.0,0

In [13]:
df_isw_matrix.sample(10)

,date,isw_topic_0,isw_topic_1,isw_topic_2,isw_topic_3,isw_topic_4,isw_topic_5,isw_topic_6,isw_topic_7,isw_topic_8,isw_topic_9,isw_topic_10,isw_topic_11,isw_topic_12,isw_topic_13,isw_topic_14,isw_topic_15,isw_topic_16,isw_topic_17,isw_topic_18,isw_topic_19,isw_topic_20,isw_topic_21,isw_topic_22,isw_topic_23,isw_topic_24,isw_topic_25,isw_topic_26,isw_topic_27,isw_topic_28,isw_topic_29,isw_topic_30,isw_topic_31,isw_topic_32,isw_topic_33,isw_topic_34,isw_topic_35,isw_topic_36,isw_topic_37,isw_topic_38,isw_topic_39,isw_topic_40,isw_topic_41,isw_topic_42,isw_topic_43,isw_topic_44,isw_topic_45,isw_topic_46,isw_topic_47,isw_topic_48,isw_topic_49,isw_topic_50,isw_topic_51,isw_topic_52,isw_topic_53,isw_topic_54,isw_topic_55,isw_topic_56,isw_topic_57,isw_topic_58,isw_topic_59,isw_topic_60,isw_topic_61,isw_topic_62,isw_topic_63,isw_topic_64,isw_topic_65,isw_topic_66,isw_topic_67,isw_topic_68,isw_topic_69,isw_topic_70,isw_topic_71,isw_topic_72,isw_topic_73,isw_topic_74,isw_topic_75,isw_topic_76,isw_topic_77,isw_topic_78,isw_topic_79,isw_topic_80,isw_topic_81,isw_topic_82,isw_topic_83,isw_topic_84,isw_topic_85,isw_topic_86,isw_topic_87,isw_topic_88,isw_topic_89,isw_topic_90,isw_topic_91,isw_topic_92,isw_topic_93,isw_topic_94,isw_topic_95,isw_topic_96,isw_topic_97,isw_topic_98,isw_topic_99,isw_topic_100,isw_topic_101,isw_topic_102,isw_topic_103,isw_topic_104,isw_topic_105,isw_topic_106,isw_topic_107,isw_topic_108,isw_topic_109,isw_topic_110,isw_topic_111,isw_topic_112,isw_topic_113,isw_topic_114,isw_topic_115,isw_topic_116,isw_topic_117,isw_topic_118,isw_topic_119,isw_topic_120,isw_topic_121,isw_topic_122,isw_topic_123,isw_topic_124,isw_topic_125,isw_topic_126,isw_topic_127,isw_topic_128,isw_topic_129,isw_topic_130,isw_topic_131,isw_topic_132,isw_topic_133,isw_topic_134,isw_topic_135,isw_topic_136,isw_topic_137,isw_topic_138,isw_topic_139,isw_topic_140,isw_topic_141,isw_topic_142,isw_topic_143,isw_topic_144,isw_topic_145,isw_topic_146,isw_topic_147,isw_topic_148,isw_topic_149
528,2023-08-09,0.708288,-0.211903,-0.086730,-0.149092,-0.121213,0.150973,-0.031438,0.208107,0.025112,0.037309,0.165840,0.028634,-0.188834,-0.065981,0.060041,-0.054538,0.099998,-0.110803,0.038449,-0.045920,0.141840,0.015058,0.042988,0.004215,0.083478,0.093383,0.014700,-0.003323,-0.018350,0.003488,-0.040702,-0.004049,-0.073432,-0.063260,-0.024153,0.028816,-0.024412,0.050774,0.033323,-0.069316,-0.049126,-0.017278,0.016653,-0.004501,-0.024927,-0.047902,-0.021401,0.023503,-0.028247,-0.012019,-0.033458,-0.045759,-0.005521,-0.004911,0.031088,0.011968,-0.007987,0.036255,0.016708,0.007343,0.010055,0.070523,-0.016265,0.018375,-0.003569,0.034085,0.014384,-0.008675,-0.017706,0.008202,-0.015770,0.055711,-0.029004,-0.006545,-0.030657,0.041676,0.014917,-0.000847,-0.000201,0.004474,-0.009375,0.007897,-0.009739,-0.016868,-0.007504,0.004947,0.022153,0.007445,0.007150,0.038039,-0.000751,0.010839,-0.030582,-0.016455,-0.045452,0.037182,-0.018901,0.041864,0.006250,-0.051237,0.003211,-0.026736,0.000048,-0.014140,0.002200,-0.020378,-0.055255,-0.008109,0.017916,-0.004029,0.025969,0.018326,0.028489,0.000817,-0.033030,-0.018640,0.029765,-0.011588,0.022258,0.012079,-0.020116,0.006592,0.006224,-0.000510,0.004841,0.034687,0.053619,0.008425,-0.047183,0.008075,-0.001763,0.033182,-0.000492,-0.013596,-0.011538,0.032250,-0.007786,-0.005489,-0.023369,0.007861,-0.015272,0.024549,-0.009216,-0.006258,-0.002414,-0.016496,0.043290,0.003357,-0.018537,-0.034981
1209,2025-06-27,0.786359,0.271797,0.035545,0.084521,-0.126942,0.069325,0.053996,-0.048383,-0.102854,0.078990,-0.024602,0.250191,-0.064038,0.036933,-0.062007,0.023902,-0.044686,-0.035940,0.035241,-0.009808,-0.082374,-0.011506,0.033467,-0.031841,-0.048449,0.025298,-0.049090,0.012376,0.038031,0.047115,0.021643,-0.032082,-0.006635,-0.022580,0.002990,-0.005210,0.023248,0.041557,-0.020761,-0.009079,-0.002803,-0.015733,0.028827,-0.001799,-0.023302,-0.025874,0.043065,-0.000529,-0.021737,-0.047330,-0.018417,-0.019992,0.041693,0.019244,-0.031595,0.006256,0.028083,-0.020464,0.011667,-0.012801,-0.064886,-0.012506,0.038612,0.019479,0.024067,0.035845,0.038497,-0.031083,0.015600,0.001268,-0.006000,0.007926,-0.025959,0.014561,-0.004850,0.019313,0.004840,-0.003484,-0.013358,-0.037078,0.013287,-0.006096,0.010642,-0.025391,-0.002539,-0.002577,-0.027164,-0.001258,-0.007307,-0.002818,0.007839,-0.022377,-0.007891,0.027598,0.033647,0.016620,-0.019659,0.004787,0.017375,0.014964,0.018333,-0.000725,-0.008343,0.009740,-0.022310,0.009485,-0.002239,-0.030718,-0.008091,0.001773,-0.014088,-0.023012,0.018340,0.016889,0.006376,-0.019147,0.007305,0.012327,0.003822,0.013594,-0.017576,-0.007294,0.023193,-0.017021,0.015879,-0.036499,-0.002839,-0.010261,0.008168,-0.003286,0.006451,-0.029148,0.001644,-0.012308,-0.019336,0.010008,-0.029939,-0.018857,-0.007276,-0.023616,0.006944,0.008311,0.005239,-0.011113,0.005597,-0.014751,0.018597,-0.009401,0.017946,-0.029099
296,2022-12-18,0.595036,-0.186349,-0.110778,-0.023682,0.124717,0.007519,0.130356,0.127932,-0.130617,0.001375,0.033912,-0.004938,-0.096678,0.008880,0.064888,0.117389,0.073484,-0.222268,-0.029831,0.023595,0.085880,0.002784,-0.006064,-0.060292,-0.006485,0.125733,-0.016165,-0.005734,-0.011647,-0.080179,0.020097,0.016385,-0.033359,-0.097981,-0.007293,-0.002873,-0.047836,0.005110,0.008767,-0.068768,-0.014348,0.076770,0.040853,0.021496,-0.021741,-0.006012,-0.040161,0.000680,0.069872,-0.032232,0.091851,-0.070157,0.004439,-0.018566,0.026636,0.058506,0.004196,-0.009885,-0.018533,0.009780,0.081871,0.051181,-0.002711,-0.036396,-0.001740,-0.003374,0.065533,-0.011020,-0.031994,-0.023395,-0.071209,0.026286,0.006922,-0.004512,-0.035942,0.000058,-0.006283,0.005495,0.041984,0.109990,-0.007375,0.010345,0.030887,0.021436,-0.055979,-0.015618,-0.006929,-0.016254,0.092335,0.031898,0.045853,0.040945,0.026577,0.072533,-0.033673,-0.039402,0.008606,0.071099,0.051777,-0.040004,-0.048687,0.030411,-0.000569,-0.026671,-0.078392,0.018835,-0.076046,-0.058056,-0.002145,-0.010556,-0.063808,0.030192,-0.018210,-0.003505,-0.008024,-0.019126,0.025873,0.091875,0.057609,-0.018662,0.044325,0.025786,0.025749,0.051140,0.005193,0.010979,-0.024738,0.028584,-0.010028,0.068121,-0.065406,0.033896,-0.010728,-0.082056,0.004305,0.037352,0.045305,-0.078410,-0.039636,0.074584,0.083350,-0.044428,0.011391,0.006170,0.009588,-0.012225,-0.058477,0.000317,0.037385,0.042870
812,2024-05-22,0.775662,-0.002424,-0.151920,0.111153,-0.059068,-0.006184,0.024923,-0.051831,0.024773,-0.036331,-0.018013,0.037463,0.043945,-0.024886,-0.013759,0.052852,0.175438,0.074618,-0.051852,0.079847,-0.073549,-0.011400,-0.001745,0.045701,0.082970,-0.046581,0.033425,-0.030383,-0.080264,-0.010439,0.005813,-0.012775,0.035364,-0.043711,0.025131,0.028287,0.035735,-0.030741,-0.017173,-0.017602,-0.007221,-0.033642,0.010754,0.034593,-0.014429,0.031466,0.046941,-0.025614,-0.002341,-0.021614,-0.037766,-0.045356,0.001519,-0.112196,-0.008555,-0.021244,0.009791,0.016191,0.073700,0.012011,-0.041630,-0.035715,-0.013105,-0.000184,-0.007717,-0.016106,-0.007821,0.032656,-0.020975,-0.000926,0.034590,-0.044293,-0.033058,-0.031209,0.013922,-0.002185,-0.007702,0.006359,0.019271,0.026208,0.042526,0.002952,0.008486,0.002611,0.016252,0.030241,0.007588,-0.012311,0.042728,0.001198,-0.001998,0.017215,-0.021997,-0.014898,0.037233,-0.012281,-0.004226,0.023531,0.013356,0.032753,-0.019587,-0.027295,0.021247,-0.017445,-0.000068,0.062606,-0.057726,0.029314,-0.029273,-0.013994,0.002465,-0.027187,-0.001419,0.022369,-0.015598,0.001794,-0.035588,-0.047857,0.029318,0.003109,-0.015219,-0.059916,0.026146,-0.010498,0.006648,-0.017776,0.007915,0.016555,0.023732,-0.003469,-0.010610,0.028261,-0.002604,-0.044334,0.022720,-0.032548,0.024604,0.033168,0.016714,-0.016115,-0.019709,0.034698,0.004183,0.008570,-0.001445,-0.000705,0.006879,0.021836,-0.066026,-0.018670
1094,2025-03-04,0.769796,0.153131,-0.024883,0.226445,-0.004786,-0.088706,-0.061765,0.154646,0.062747,0.092402,-0.117815,-0.007857,-0.038596,0.041653,-0.060571,0.070946,-0.071557,0.058546,0.039706,-0.046035,0.124846,0.017816,-0.009804,-0.021887,-0.038866,-0.003908,-0.017855,0.024314,-0.052120,-0.149494,-0.034573,-0.006292,-0.020372,0.002318,0.040148,-0.009163,-0.009621,-0.064775,-0.027480,-0.041433,0.014301,0.036469,-0.029630,-0.072921,-0.028286,-0.015800,-0.028070,0.031177,0.009008,-0.054503,0.028938,0.019401,0.063635,0.019121,0.008100,0.008387,0.030656,-0.001827,-0.067519,0.022277,-0.016042,0.055979,0.007272,-0.041949,-0.020836,-0.018989,-0.020931,0.026091,-0.019689,-0.033306,0.032671,-0.006097,-0.008370,0.008345,-0.007455,0.020179,0.041367,-0.039267,0.025604,-0.028856,0.000346,0.003405,0.042596,-0.013429,0.005059,-0.013889,-0.052587,-0.022685,0.014649,0.000901,0.029306,-0.008770,-0.008878,-0.026250,-0.041752,-0.003273,-0.016432,-0.016371,0.004053,-0.030745,-0.019061,-0.010610,0.035645,0.021620,0.033518,-0.006394,0.037125,0.028233,-0.024006,0.017438,-0.020267,-0.004297,0.001536,-0.005620,-0.013572,-0.037338,0.012248,-0.016557,0.009503,0.015509,0.006447,0.006454,0.022823,0.007762,-0.031207,-0.004802,0.006279,0.009117,0.021670,-0.006121,-0.023162,0.017894,-0.061486,-0.033742,-0.007350,-0.002133,-0.005775,-0.025626,-0.021853,-0.020002,-0.011154,0.006230,-0.030426,0.003983,0.016502,-0.001726,0.022263,0.008478,-0.007436,-0.022303
249,2022-10-31,0.667562,-0.218897,-0.016566,-0.236182,-0.007896,-0.208093,-0.258897,-0.095804,-0.188256,-0.101306,-0.125722,-0.023048,-0.099343,-0.105931,-0.030473,0.114036,-0.072408,-0.016658,0.022852,0.039825,-0.009557,0.080225,0.039531,0.020144,-0.000430,0.057796,0.082539,0.046452,0.015949,-0.012030,-0.110781,0.005797,0.002614,-0.041236,-0.011295,0.016718,-0.035385,-0.021956,-0.061101,0.009783,-0.013942,0.016985,-0.006924,-0.010596,-0.021027,-0.032205,0.006484,0.036751,-0.003756,-0.019969,-0.022758,-0.008449,-0.003857,0.009968,-0.044852,-0.004444,-0.013814,-0.009993,-0.014012,0.001244,-0.001572,-0.003896,0.003514,0.033743,-0.011291,-0.028370,0.014102,0.018344,0.020146,0.006874,0.004590,-0.021888,0.009738,0.024915,-0.018829,-0.013663,-0.076759,-0.004325,0.058630,-0.033069,-0.006426,-0.015120,0.027872,-0.030712,0.020466,0.045369,0.028851,0.001592,0.012050,-0.052196,-0.025147,0.030469,-0.003041,0.025210,-0.041553,0.010965,0.035424,0.004602,0.001638,-0.032904,-0.019300,-0.012846,-0.002018,0.049640,-0.009647,0.019122,0.016068,0.005917,-0.021430,-0.016059,0.042364,-0.028779,0.015616,-0.036231,0.034204,-0.024053,0.039897,-0.046934,-0.000245,-0.014544,-0.008262,0.009310,-0.034950,0.004151,0.031062,-0.002271,-0.010764,0.008963,0.017851,-0.015712,0.014255,0.027767,0.002336,-0.009302,0.014175,-0.027837,-0.013106,-0.030200,-0.010090,0.008620,-0.004384,0.010040,0.003854,0.004343,0.003270,0.018579,0.000514,-0.025002,0.000496,-0.017727
1298,2025-09-24,0.754601,0.297732,0.093404,-0.120891,-0.041105,0.010775,-0.071351,0.137313,-0.032914,-0.025059,0.058808,0.016746,0.215343,0.197292,-0.090185,0.041695,0.036216,-0.026282,0.010612,-0.043618,0.022959,-0.066788,0.052160,-0.038476,0.001478,0.026550,0.005940,-0.011938,-0.053838,0.025786,-0.031586,-0.016301,0.028643,0.035234,0.020500,0.008627,-0.031547,-0.021315,0.021832,-0.009844,-0.020920,-0.047693,0.013152,-0.016104,-0.010308,0.001154,0.020814,-0.013928,0.032898,0.027179,-0.009225,0.031412,-0.004765,-0.019530,0.031640,-0.040546,0.006217,0.005111,-0.013797,-0.026573,-0.000440,-0.001403,-0.016851,0.012855,0.015427,-0.005919,0.003776,-0.020125,0.000323,-0.034083,-0.014620,0.034089,0.045033,-0.016908,0.043643,-0.012708,-0.033003,0.044166,0.027913,-0.017585,-0.000947,0.022263,0.002961,-0.022912,0.010073,-0.014579,-0.003664,-0.036654,-0.005451,0.018135,0.013479,-0.004589,0.004747,-0.001432,-0.018494,0.011134,-0.015967,0.045791,-0.014262,-0.023654,-0.034420,0.010871,0.024783,0.019939,-0.013738,-0.003582,0.021826,0.004836,-0.013843,0.032697,-0.026636,-0.018168,-0.001407,-0.003563,0.043079,-0.004047,0.001936,0.024458,0.004058,0.025294,0.007617,0.044442,-0.031147,-0.001545,-0.009017,0.000296,-0.012715,-0.002244,0.023915,-0.010384,0.015147,-0.002087,-0.002898,-0.014028,0.005278,0.055497,0.016298,0.020079,0.010879,-0.025868,-0.005522,0.014946,0.044608,-0.004070,0.031989,0.003241,-0.017686,-0.023618,-0.009419,0.013683
20,2022-03-16,0.667431,-0.138932,0.291648,0.225589,0.097596,-0.176840,-0.099146,0.201843,0.116669,0.124865,-0.189029,-0.037059,-0.111875,0.119563,-0.004512,-0.103696,-0.007218,-0.092479,0.085514,0.085195,-0.076971,-0.012568,-0.004017,-0.032162,0.062733,0.018166,0.035447,0.008089,-0.021216,-0.008068,0.029683,-0.029698,-0.005285,-0.019413,0.041325,0.000095,0.013191,0.002503,0.029532,0.017206,0.014475,0.002498,0.019046,-0.025934,-0.011368,-0.006295,-0.009622,0.030728,-0.010092,-0.003030,-0.013573,-0.011077,-0.012711,0.036047,-0.044158,0.009488,-0.000110,-0.017283,-0.017711,-0.018033,-0.001708,-0.018070,0.018531,-0.018619,-0.025066,-0.021069,-0.003492,0.012285,0.003194,0.043886,0.009820,0.008107,0.014243,0.002243,0.034497,-0.013106,-0.003174,0.023783,-0.010745,0.028169,0.006194,0.037698,0.008133,0.000726,-0.013515,0.004517,0.006811,-0.036970,-0.009128,-0.035981,-0.009158,-0.012529,0.011090,-0.027953,-0.007947,-0.016095,0.000858,0.001675,0.012142,0.000490,-0.012117,-0.016955,0.012406,-0.008015,0.002169,0.031563,-0.003653,-0.028369,-0.011763,0.013952,-0.001037,-0.008569,0.003126,-0.013003,-0.009299,-0.023912,-0.030159,0.007868,0.054691,-0.003783,-0.000383,0.002374,0.018463,0.003310,0.016649,0.013739,0.000414,0.009492,0.022687,0.037107,-0.001168,-0.013238,0.006631,0.031918,0.022219,0.027371,-0.028917,0.015902,0.011582,-0.048099,-0.019146,-0.020316,0.009200,-0.005108,0.003880,-0.010764,0.020559,-0.012054,-0.005835,-0.002557
398,2023-04-01,0.774336,-0.208774,-0.080325,0.107606,0.019894,-0.059217,-0.040977,0.048348,-0.076772,0.048786,0.143584,-0.064177,-0.055132,0.046988,0.034394,0.023937,-0.037277,-0.031564,-0.083697,-0.030336,-0.101820,-0.040855,-0.101890,0.015865,-0.070672,-0.085094,-0.070248,0.009614,0.019617,0.011789,0.037520,-0.043106,-0.057421,-0.000542,0.026392,0.012469,-0.011479,0.006105,0.011082,-0.014190,0.024347,-0.014753,0.043338,0.008504,-0.083706,-0.025858,-0.031570,-0.036642,-0.063663,0.006200,0.033213,0.031878,-0.045678,-0.040284,-0.016806,0.024029,0.004037,0.113300,-0.000836,0.020546,0.026431,-0.009590,-0.013071,-0.013641,-0.001302,0.021976,-0.002786,0.022009,0.051393,-0.036317,-0.004540,0.019504,0.005836,-0.016645,0.007633,-0.001178,-0.016246,-0.026424,0.009246,-0.029119,0.085902,0.005766,-0.017314,0.001280,0.008193,0.057360,-0.014444,0.008544,0.040906,-0.032243,0.017320,-0.008721,0.030690,-0.060982,-0.011347,-0.010592,-0.037707,-0.025698,-0.000992,-0.019261,0.005600,-0.025439,0.030327,0.018237,0.007460,0.034750,-0.014492,-0.006437,-0.010557,0.011845,-0.021370,-0.048905,-0.010250,-0.046755,0.005955,0.043559,0.069062,-0.005201,-0.039169,-0.009194,0.007125,0.030687,0.011646,0.007500,-0.016633,0.012106,0.006478,0.008978,0.023660,0.013018,-0.010531,0.027519,0.027175,0.022226,-0.010124,-0.008035,0.003832,-0.000696,0.012166,-0.019860,0.009000,-0.008385,-0.021015,-0.008218,0.011916,0.021847,-0.009153,-0.007771,-0.033963,0.053334
872,2024-07-21,0.735005,0.060618,-0.070507,0.049038,-0.194059,0.118323,0.083209,-0.132798,-0.005045,0.047648,-0.153744,-0.240664,0.055985,-0.001644,-0.019393,-0.053085,0.011176,-0.038935,-0.013153,0.078898,0.012399,0.045249,0.014858,0.052574,0.060182,-0.028280,0.043568,-0.042960,-0.085340,-0.011101,-0.001640,-0.006978,-0.043743,0.032898,0.046734,-0.038965,0.007932,-0.013135,0.019391,-0.045758,0.031822,0.036451,0.026182,-0.020735,0.073163,-0.057577,0.110443,0.104835,0.102861,-0.005403,-0.033818,0.127768,-0.098214,0.010588,0.038124,0.114900,-0.017389,0.037918,0.012900,-0.100857,-0.025193,-0.009718,0.042791,0.003111,0.049593,0.006080,0.022087,-0.034964,0.042327,0.025962,-0.057263,-0.023831,0.000982,0.005994,-0.034457,-0.032876,-0.017395,0.008903,0.008631,0.020337,-0.005042,-0.071141,-0.006186,0.010606,-0.019989,-0.006543,-0.034996,0.020341,0.030363,-0.004215,-0.029191,-0.037241,-0.001220,0.013382,-0.023264,0.017776,-0.024640,-0.000060,0.016225,0.025022,0.018838,-0.006639,-0.007500,-0.006614,-0.013821,-0.006536,0.025179,0.025283,0.006638,-0.017713,-0.025279,-0.019913,-0.004795,0.032519,-0.002385,-0.008316,0.007820,-0.006369,-0.026471,0.003283,0.005860,0.024311,-0.042612,0.011696,-0.040516,-0.000288,0.001423,-0.002552,-0.002641,-0.005369,-0.009466,-0.003681,-0.004816,0.004186,-0.001204,0.010591,0.003289,-0.001401,0.013072,0.014173,0.004047,-0.019367,-0.025803,-0.007666,-0.006570,-0.032702,0.003799,-0.001698,0.007674,-0.011603

In [14]:
df_isw_matrix["date"] = pd.to_datetime(df_isw_matrix["date"]) + pd.Timedelta(days=1)
df_isw_matrix = df_isw_matrix.rename(columns={'date': 'day_datetime'})

In [15]:
df_final['day_datetime'] = pd.to_datetime(df_final['day_datetime']).dt.date
df_isw_matrix['day_datetime'] = pd.to_datetime(df_isw_matrix['day_datetime']).dt.date
df_isw_matrix.fillna(0, inplace=True)
df_isw_matrix.isna().sum()

day_datetime     0
isw_topic_0      0
isw_topic_1      0
isw_topic_2      0
isw_topic_3      0
                ..
isw_topic_145    0
isw_topic_146    0
isw_topic_147    0
isw_topic_148    0
isw_topic_149    0
Length: 151, dtype: int64

In [16]:
df_final = df_final.merge(df_isw_matrix, on="day_datetime", how="left")

In [17]:
df_final.sample(10)

,datetime_hour,region_id,city_latitude,city_longitude,day_temp,day_dew,day_humidity,day_precip,day_precipprob,day_precipcover,day_snow,day_snowdepth,day_windgust,day_windspeed,day_winddir,day_pressure,day_cloudcover,day_solarradiation,day_solarenergy,day_uvindex,day_moonphase,hour_temp,hour_feelslike,hour_humidity,hour_precip,hour_precipprob,hour_snow,hour_windgust,hour_windspeed,hour_winddir,hour_pressure,hour_cloudcover,hour_solarradiation,hour_solarenergy,hour_uvindex,day_conditions_simple_Clear,day_conditions_simple_Cloudy,day_conditions_simple_Rain,day_conditions_simple_Snow,hour_conditions_simple_Clear,hour_conditions_simple_Cloudy,hour_conditions_simple_Rain,hour_conditions_simple_Snow,year,month,day_of_week,hour,city_name,city_timezone,day_datetime,day_sunrise,day_sunset,hour_datetime,region_key,alarm_active,alarm_minutes_in_hour,alarm_lag_1,alarm_lag_3,alarm_lag_6,alarm_lag_12,alarms_in_last_24h,is_weekend,is_night,total_active_alarms_lag1,neighbour_alarms,hours_since_last_alarm,isw_topic_0,isw_topic_1,isw_topic_2,isw_topic_3,isw_topic_4,isw_topic_5,isw_topic_6,isw_topic_7,isw_topic_8,isw_topic_9,isw_topic_10,isw_topic_11,isw_topic_12,isw_topic_13,isw_topic_14,isw_topic_15,isw_topic_16,isw_topic_17,isw_topic_18,isw_topic_19,isw_topic_20,isw_topic_21,isw_topic_22,isw_topic_23,isw_topic_24,isw_topic_25,isw_topic_26,isw_topic_27,isw_topic_28,isw_topic_29,isw_topic_30,isw_topic_31,isw_topic_32,isw_topic_33,isw_topic_34,isw_topic_35,isw_topic_36,isw_topic_37,isw_topic_38,isw_topic_39,isw_topic_40,isw_topic_41,isw_topic_42,isw_topic_43,isw_topic_44,isw_topic_45,isw_topic_46,isw_topic_47,isw_topic_48,isw_topic_49,isw_topic_50,isw_topic_51,isw_topic_52,isw_topic_53,isw_topic_54,isw_topic_55,isw_topic_56,isw_topic_57,isw_topic_58,isw_topic_59,isw_topic_60,isw_topic_61,isw_topic_62,isw_topic_63,isw_topic_64,isw_topic_65,isw_topic_66,isw_topic_67,isw_topic_68,isw_topic_69,isw_topic_70,isw_topic_71,isw_topic_72,isw_topic_73,isw_topic_74,isw_topic_75,isw_topic_76,isw_topic_77,isw_topic_78,isw_topic_79,isw_topic_80,isw_topic_81,isw_topic_82,isw_topic_83,isw_topic_84,isw_topic_85,isw_topic_86,isw_topic_87,isw_topic_88,isw_topic_89,isw_topic_90,isw_topic_91,isw_topic_92,isw_topic_93,isw_topic_94,isw_topic_95,isw_topic_96,isw_topic_97,isw_topic_98,isw_topic_99,isw_topic_100,isw_topic_101,isw_topic_102,isw_topic_103,isw_topic_104,isw_topic_105,isw_topic_106,isw_topic_107,isw_topic_108,isw_topic_109,isw_topic_110,isw_topic_111,isw_topic_112,isw_topic_113,isw_topic_114,isw_topic_115,isw_topic_116,isw_topic_117,isw_topic_118,isw_topic_119,isw_topic_120,isw_topic_121,isw_topic_122,isw_topic_123,isw_topic_124,isw_topic_125,isw_topic_126,isw_topic_127,isw_topic_128,isw_topic_129,isw_topic_130,isw_topic_131,isw_topic_132,isw_topic_133,isw_topic_134,isw_topic_135,isw_topic_136,isw_topic_137,isw_topic_138,isw_topic_139,isw_topic_140,isw_topic_141,isw_topic_142,isw_topic_143,isw_topic_144,isw_topic_145,isw_topic_146,isw_topic_147,isw_topic_148,isw_topic_149
100347,2024-07-18 15:00:00,5,48.0020,37.8145,30.5,15.0,41.4,0.000,0.0,0.00,0.0,0.0,29.9,11.5,27.1,1012.6,16.2,280.2,24.3,7.0,0.40,36.7,35.9,24.70,0.0,0.0,0.0,24.1,8.6,38.1,1012.0,35.2,633.3,2.3,6.0,True,False,False,False,False,True,False,False,2024,7,3,15,Donetsk,Europe/Kiev,2024-07-18,04:48:28,20:21:04,15:00:00,Донецька,1,58.050000,0.0,1.0,1.0,1.0,22.0,0,0,8.0,3.0,2,0.760267,0.015178,-0.078852,0.070842,-0.200958,0.139618,0.109170,-0.137824,-0.018277,0.071013,-0.174145,-0.277872,0.069108,-0.017035,-0.031844,-0.011416,0.013544,-0.077641,0.029381,0.029859,-0.024153,-0.064072,0.043107,0.051210,0.006818,-0.017748,0.046095,-0.043080,-0.023213,0.019518,-0.022270,-0.043839,0.021073,-0.030306,-0.023382,-0.022829,-0.018568,-0.023327,0.043550,0.042733,0.031799,-0.019315,0.033144,0.037504,-0.018285,0.032516,0.025820,0.026405,0.025765,0.007843,0.031287,-0.040047,0.002266,-0.005384,0.016674,-0.014792,-0.006102,0.033531,0.000010,0.006225,-0.058988,0.005989,-0.007321,0.043381,0.013355,-0.019772,0.007989,0.012663,0.023016,0.008733,-0.019718,-0.033472,-0.005265,-0.004797,-0.024429,-0.016490,0.009341,0.032475,-0.003911,-0.001985,-0.006283,0.011884,0.044968,-0.023106,0.033479,-0.034502,0.022280,-0.008883,-0.021168,0.005208,-0.015142,0.021407,-0.031291,0.018271,-0.012634,0.019569,-0.008417,0.009535,0.026579,-0.049404,0.031600,0.010050,0.003327,-0.001128,0.001819,0.027975,0.012465,0.022961,0.001204,0.019869,-0.010559,-0.005000,-0.013347,0.020810,0.024516,0.000962,0.050204,0.015804,0.008061,0.026254,0.006175,0.005093,0.016579,-0.011971,0.009909,0.029889,0.015378,0.004156,0.011920,-0.025162,-0.002540,-0.012257,0.007900,-0.006283,0.019756,-0.000887,0.014252,-0.006109,0.011006,0.001355,0.021520,-0.007592,0.007773,-0.029623,0.007931,-0.015058,0.021870,-0.029457,0.047431,0.019720
480921,2022-09-16 16:00:00,21,46.6401,32.6142,22.4,17.3,74.6,0.000,0.0,0.00,0.0,0.0,32.0,19.8,250.3,1003.8,79.0,147.3,12.7,6.0,0.66,26.3,26.3,56.25,0.0,0.0,0.0,27.4,16.9,262.6,1003.0,58.1,449.0,1.6,4.0,False,True,False,False,False,True,False,False,2022,9,4,16,Kherson,Europe/Kiev,2022-09-16,06:28:17,18:59:51,16:00:00,Херсонська,0,0.000000,0.0,0.0,0.0,0.0,7.0,0,0,8.0,2.0,16,0.790744,-0.217221,0.111295,-0.110102,-0.002999,0.014050,-0.013472,0.019178,0.026810,-0.052872,-0.006572,0.017283,0.129667,0.053816,-0.033937,0.052754,-0.105858,0.075154,0.050780,0.091880,0.043817,0.050260,-0.028314,0.002439,0.055624,0.039025,-0.013427,-0.012881,-0.008841,0.044627,0.004921,-0.051569,0.058775,-0.022005,-0.009152,-0.006425,0.002127,-0.058787,0.005305,-0.009738,0.057923,0.042772,0.019176,-0.028083,0.021845,0.036874,0.091677,-0.050159,-0.001004,0.002658,0.024133,-0.004464,-0.005073,0.006007,-0.013181,-0.051818,-0.010853,-0.002150,0.026956,-0.027846,0.040702,0.031708,0.025439,-0.039668,-0.015382,0.037910,0.034924,0.034797,-0.026363,0.008586,-0.013997,-0.026618,-0.014379,0.004983,-0.001111,-0.056272,0.011137,-0.025090,0.006159,-0.003581,0.001032,0.013256,0.053929,-0.033045,-0.052133,-0.054423,-0.010486,-0.011701,-0.001867,-0.003292,-0.010320,0.054211,-0.018659,-0.000857,0.039492,0.002268,0.000563,-0.000917,0.007764,-0.021586,0.025391,-0.030931,-0.023827,0.004123,-0.036928,-0.038122,-0.005565,-0.019097,0.021348,0.019908,0.008062,-0.017554,-0.034307,0.041417,-0.008190,-0.019425,-0.006241,-0.005605,-0.024545,0.016276,-0.012888,-0.002050,-0.006857,0.003680,0.004825,-0.021199,0.017595,0.040970,-0.007239,0.008229,-0.027613,0.018051,-0.012286,0.005052,-0.013106,-0.007306,-0.010519,-0.001684,0.020572,-0.006147,0.005894,-0.023864,-0.025160,-0.046075,0.001911,-0.013477,-0.022815,0.001615,-0.019131,0.001825
230079,2024-04-05 18:00:00,10,50.4506,30.5243,8.8,2.7,67.8,0.000,0.0,0.00,0.0,0.0,25.9,11.5,148.3,1018.5,46.2,212.1,18.2,7.0,0.88,15.7,15.7,42.23,0.0,0.0,0.0,24.1,3.6,130.0,1017.1,90.0,179.1,0.6,2.0,False,True,False,False,False,True,False,False,2024,4,4,18,Kyiv,Europe/Kiev,2024-04-05,06:24:47,19:37:16,18:00:00,Київська,1,0.983333,1.0,0.0,0.0,0.0,4.0,0,0,24.0,5.0,0,0.749135,-0.057443,-0.187294,0.252398,-0.026612,-0.089545,-0.020075,-0.037091,-0.042714,-0.055792,0.126483,-0.053415,0.052015,-0.016673,-0.163446,-0.006427,0.015976,-0.022585,-0.003512,-0.009837,0.012238,-0.061369,-0.020002,-0.030821,0.022008,0.019931,0.000538,0.050582,0.034964,0.059677,-0.017731,-0.036213,-0.035919,-0.005846,-0.006945,-0.042770,-0.003111,0.020165,0.067258,-0.000690,-0.045020,-0.085357,-0.018724,-0.025464,0.011917,0.032154,0.015957,-0.064880,0.005665,-0.117505,-0.007806,-0.024567,-0.009684,0.021323,-0.034150,0.014908,0.036430,0.028594,0.069330,-0.054766,-0.009116,-0.009079,0.004553,0.081431,0.013586,0.016454,0.041585,0.037435,0.027452,-0.036669,-0.017912,0.012643,-0.018202,-0.063753,0.019698,-0.010160,-0.032193,0.024199,-0.016453,-0.007085,-0.030313,-0.011576,-0.012048,0.023488,0.011376,-0.021535,0.044057,0.015542,-0.025239,0.042370,0.006905,-0.020818,-0.062752,-0.013818,-0.039369,-0.022554,0.025095,-0.043689,-0.026674,0.021987,-0.002129,-0.009736,-0.012883,-0.038415,-0.042841,-0.005705,-0.002941,-0.020317,0.002059,-0.032752,-0.020968,-0.023096,0.015969,-0.025615,-0.008616,0.019851,0.029648,-0.014306,-0.016969,-0.008299,0.021314,0.014023,-0.006755,0.004149,0.001169,0.015657,0.020725,-0.017729,-0.024556,0.038487,0.051818,-0.039529,0.040243,0.026226,-0.005837,0.029036,0.011193,-0.025413,0.013792,0.011311,-0.036618,-0.032111,0.006372,0.018858,-0.002610,-0.008405,-0.011369,-0.028217,-0.029399,-0.002801
506790,2022-08-23 16:00:00,22,49.4168,26.9743,23.3,15.2,61.9,0.000,0.0,0.00,0.0,0.0,25.2,14.4,92.6,1013.5,56.4,243.1,21.1,7.0,0.85,30.0,29.7,40.94,0.0,0.0,0.0,25.2,11.5,120.2,1013.0,33.1,613.0,2.2,6.0,False,True,False,False,False,True,False,False,2022,8,1,16,Khmelnytskyi,Europe/Kiev,2022-08-23,06:14:35,20:14:01,16:00:00,Хмельницька,0,0.000000,0.0,0.0,0.0,0.0,1.0,0,0,3.0,0.0,23,0.737236,-0.238108,0.198573,-0.108697,-0.066683,0.095313,-0.008809,0.075960,0.152731,-0.109914,0.048667,-0.013864,-0.036036,-0.127447,-0.071960,0.044894,-0.130518,0.085745,-0.076556,-0.015275,-0.053492,0.022340,0.058623,-0.070864,0.073896,-0.010371,-0.056665,-0.032150,0.015523,-0.011792,-0.003030,0.017813,-0.018886,0.011573,-0.037192,-0.025105,-0.036887,0.039891,-0.018123,-0.042386,-0.021146,-0.003620,0.006377,-0.005758,0.041534,-0.014094,-0.026793,0.039375,0.027345,-0.038051,-0.029706,0.031204,0.001850,0.012080,0.019024,-0.029222,-0.003541,-0.009705,-0.003862,0.001818,-0.007259,-0.027367,-0.030126,0.015056,-0.014075,-0.011828,-0.019810,0.006557,0.012708,-0.024105,-0.012014,-0.037882,-0.008879,0.022874,0.031484,-0.027978,0.009366,0.030775,0.001292,0.000923,0.017653,0.008888,0.003438,0.018944,-0.022049,-0.007644,0.001401,-0.026108,-0.033714,-0.004996,0.002321,-0.007288,-0.024749,0.063596,-0.014467,-0.070003,0.028190,0.015826,0.042827,-0.001047,0.012469,-0.007366,0.004746,0.022368,0.019970,0.012544,-0.006784,-0.001563,0.014945,-0.058971,-0.007607,-0.056374,-0.000873,-0.019198,-0.003083,0.026570,0.034288,0.019973,-0.006829,-0.003326,-0.019631,-0.010855,-0.010275,-0.007527,-0.009632,-0.013010,0.019897,-0.013811,0.008637,0.006439,-0.009300,0.027147,-0.036113,-0.009432,0.023002,-0.012524,-0.011842,-0.001700,-0.029926,-0.009453,-0.017941,0.036264,0.002997,-0.007563,-0.015735,-0.006191,-0.014491,0.022938,0.000369,0.034389
582393,2022-03-21 03:00:00,25,51.4937,31.2944,4.9,-1.9,63.7,0.000,0.0,0.00,0.0,0.0,29.5,14.8,355.4,1037.7,0.1,174.5,14.9,5.0,0.62,-0.7,-3.2,79.52,0.0,0.0,0.0,11.9,6.8,350.2,1039.0,0.0,0.0,0.1,0.0,True,False,False,False,True,False,False,False,2022,3,0,3,Chernihiv,Europe/Kiev,2022-03-21,05:55:38,18:09:25,03:00:00,Чернігівська,1,60.000000,1.0,1.0,1.0,0.0,13.0,0,1,9.0,1.0,0,0.681949,-0.187891,0.279220,0.164994,0.092560,-0.140303,-0.083584,0.162049,0.099743,0.096641,-0.151596,-0.030718,-0.088110,0.099832,-0.003941,-0.089284,-0.027871,-0.072159,0.074843,0.082536,-0.029845,0.015522,0.031908,-0.008103,0.052886,0.037350,0.029404,-0.022692,-0.055779,-0.030511,0.108776,-0.022537,-0.057658,0.008462,0.041034,-0.013600,-0.012043,-0.019014,0.036140,-0.036987,0.035289,-0.027820,0.018583,0.019222,-0.023197,0.000024,-0.024672,0.000217,0.023531,-0.003348,0.002393,-0.039022,0.001423,0.044854,-0.044475,0.005112,0.015175,-0.042398,-0.044970,-0.044858,-0.020672,-0.011188,0.009788,-0.066730,-0.033975,-0.036263,-0.021586,-0.008517,0.032749,0.075479,0.004853,0.046919,-0.023828,-0.017256,-0.016197,-0.011582,-0.024929,0.022247,0.004526,0.054712,-0.039182,0.048023,-0.003967,-0.031726,-0.079720,-0.000380,0.007420,-0.026989,-0.027253,-0.004699,0.014080,0.025686,-0.031071,0.039953,-0.017170,-0.020216,0.026840,0.013156,0.026736,-0.003572,-0.033409,0.010200,0.009633,0.020164,0.024944,-0.001913,0.003137,0.003557,0.013581,0.005016,0.022452,0.037862,-0.011535,0.000649,-0.036048,0.006710,-0.015335,0.000475,-0.009290,-0.027124,0.009051,0.024458,0.021172,-0.009520,0.021065,-0.001293,0.009399,0.031050,0.021950,0.006884,0.013939,-0.036888,-0.003094,-0.018585,0.016651,-0.003078,0.009457,-0.010666,-0.047453,0.014706,0.001003,0.003972,0.036756,-0.019099,-0.014409,-0.006529,-0.009112,-0.015712,-0.017489,0.001914
380938,2023-05-16 06:00:00,17,50.6193,26.2513,17.4,10.0,62.6,0.804,100.0,4.17,0.0,0.0,32.0,17.7,188.7,1013.0,86.2,189.4,16.3,6.0,0.88,13.1,13.1,80.47,0.0,0.0,0.0,21.6,0.3,145.0,1012.1,90.2,2.0,0.0,0.0,False,False,True,False,False,True,False,False,2023,5,1,6,Rivne,Europe/Kiev,2023-05-16,05:25:57,20:57:47,06:00:00,Рівненська,0,0.000000,0.0,1.0,0.0,0.0,5.0,0,1,3.0,0.0,1,0.729059,-0.263789,-0.084265,-0.034616,0.005943,0.063762,-0.018813,0.093415,-0.119105,0.103957,0.087862,0.028899,-0.052124,0.018485,0.074155,0.099843,0.157990,0.009850,-0.062587,0.073521,0.109903,0.036875,0.079916,-0.020313,0.041381,0.050852,0.045205,0.009318,0.001673,0.013908,0.043354,-0.003193,0.033529,0.044494,-0.008061,-0.049871,0.032698,-0.083823,-0.036118,-0.006260,0.043595,0.026606,-0.001354,0.005281,-0.030687,-0.027443,0.012490,-0.014620,-0.005145,-0.024559,0.091119,0.048132,0.004553,-0.016384,0.004649,-0.042497,-0.055404,-0.014149,-0.035334,-0.045026,-0.028585,-0.025819,0.006578,0.065777,0.026797,-0.036116,-0.014982,0.008224,-0.040224,0.036600,0.063497,0.000626,-0.057667,0.031959,-0.009378,0.007563,-0.002635,0.002814,0.015851,-0.014980,-0.011646,-0.006247,0.009500,-0.009531,0.033441,0.015450,0.012617,-0.064353,-0.002457,0.016243,0.005274,-0.020719,0.003949,0.047914,0.013952,-0.026352,0.039954,-0.019415,0.003279,-0.000127,0.026123,-0.046035,0.022441,0.016426,-0.021818,-0.004067,-0.004909,-0.045302,0.031863,-0.016623,-0.036460,-0.016732,-0.021436,-0.016944,-0.024271,0.020409,-0.002894,0.022697,-0.057342,0.060472,-0.004705,-0.026971,-0.013145,-0.022683,0.007727,-0.019152,0.039073,0.022326,0.007186,-0.018952,0.004459,-0.017686,-0.044893,0.011628,-0.008299,0.005452,0.023571,-0.012338,0.013616,0.055717,-0.021102,-0.034826,0.020111,-0.035236,0.033327,0.044422,0.015623,0.010910,-0.015413,0.007037
254759,2024-01-23 04:00:00,11,48.5085,32.2656,-2.9,-4.7,87.2,0.000,0.0,0.00,0.0,4.2,40.7,28.8,166.4,1030.3,99.6,44.2,3.8,2.0,0.42,-4.3,-10.7,90.64,0.0,0.0,0.0,36.7,19.8,168.8,1032.0,99.6,0.0,0.0,0.0,False,True,False,False,False,True,False,False,2024,1,1,4,Kropyvnytskyi,Europe/Kiev,2024-01-23,07:31:36,16:34:13,04:00:00,Кіровоградська,0,0.000000,1.0,0.0,0.0,1.0,7.0,0,1,6.0,2.0,0,0.755869,-0.072315,-0.246809,0.106416,0.194674,0.164932,-0.086242,-0.110446,0.075670,-0.047364,-0.014283,-0.004304,0.024797,-0.000080,-0.137408,-0.006142,0.053944,0.043950,0.058190,-0.079931,-0.018353,-0.031483,0.045343,-0.002356,0.001384,0.004672,0.058554,-0.021831,0.029362,0.009686,0.007329,-0.013369,0.068545,-0.054700,-0.012872,-0.023626,-0.044869,-0.032570,0.037476,-0.006933,0.032197,-0.023316,-0.030174,-0.004093,-0.003988,0.032900,0.038293,-0.024241,-0.029182,0.015249,-0.026755,0.017437,-0.006461,-0.021032,-0.002846,-0.005221,-0.016101,-0.007301,0.006292,-0.055441,-0.019419,-0.019591,-0.023808,-0.002954,0.012024,-0.002396,0.006077,0.026312,-0.000233,0.029902,0.029857,0.005254,0.007291,0.021407,-0.004172,-0.054754,-0.005643,0.022886,0.012168,0.013245,0.034033,-0.003132,0.046740,0.023665,0.012505,0.001539,0.039282,0.028977,-0.021888,-0.001349,0.015590,0.020197,0.017589,-0.013978,-0.034471,-0.014034,0.049792,-0.012040,-0.008411,-0.009932,-0.006901,-0.032145,-0.023800,-0.003125,0.024423,-0.007273,-0.014742,-0.010811,-0.007061,0.005593,-0.032884,-0.024052,-0.010424,-0.003383,-0.043778,0.050553,0.011735,0.005523,0.011539,-0.029701,0.013814,0.016040,-0.000823,0.012283,0.007049,0.001322,0.023217,-0.003817,-0.044486,0.053608,-0.034215,0.003627,0.006847,0.001735,-0.015917,-0.011525,0.008638,0.001191,0.041425,0.016426,0.011922,0.041585,-0.015292,0.003538,0.000247,0.005326,0.012777,0.006342,-0.022564,-0.005158
498902,2024-10-04 23:00:00,21,46.6401,32.6142,17.8,13.8,79.8,0.300,100.0,4.17,0.0,0.0,37.4,19.4,158.0,1015.9,75.4,109.9,9.4,4.0,0.05,16.6,16.6,88.54,0.0,0.0,0.0,17.3,9.7,159.1,1015.0,99.1,0.0,0.0,0.0,False,False,True,False,False,True,False,False,2024,10,4,23,Kherson,Europe/Kiev,2024-10-04,06:52:31,18:23:06,23:00:00,Херсонська,1,53.416667,1.0,0.0,0.0,0.0,10.0,0,1,12.0,3.0,0,0.818669,0.099127,-0.086063,-0.028884,-0.081270,-0.141600,-0.141522,-0.117094,-0.015544,-0.147051,-0.122416,-0.008494,-0.069838,-0.049605,0.092129,0.040682,0.034888,-0.102460,-0.060821,0.028997,-0.007096,0.036695,-0.109772,0.018105,-0.043781,-0.051766,0.000313,-0.036662,0.058475,-0.033074,0.006262,0.033848,-0.016350,-0.004162,-0.007885,-0.008693,0.014270,-0.001678,-0.039722,-0.019161,-0.021178,-0.033418,-0.015589,-0.035339,0.002807,-0.005806,0.034374,-0.052780,-0.044588,-0.003979,0.003795,-0.016005,-0.011955,0.016022,-0.030395,0.019303,0.029638,-0.009548,-0.044357,-0.005627,0.025204,0.049222,-0.008003,0.020398,-0.027162,-0.007925,0.015591,-0.000179,-0.027887,0.011442,0.003293,-0.023362,0.015261,-0.017054,0.015567,0.003566,0.018475,0.026840,-0.024179,-0.002262,0.025856,0.003994,-0.006222,0.023680,0.016401,0.006524,-0.015424,-0.001033,0.000806,-0.012716,0.002715,0.016025,0.023669,-0.017671,0.014878,-0.029791,-0.021589,0.000051,-0.009999,-0.004009,-0.001314,-0.009036,0.027356,0.001350,0.008592,0.029943,0.003732,0.032846,-0.038671,0.005910,-0.002028,0.025205,-0.009289,-0.004415,-0.010327,-0.004114,-0.016146,0.007278,-0.000180,0.020939,-0.012230,-0.012242,-0.012672,0.000281,0.017347,0.015085,-0.007553,0.006169,0.020864,-0.002524,0.023608,0.003493,-0.018435,-0.014763,-0.007924,0.003990,0.016221,-0.006710,-0.000207,0.019902,0.019649,-0.001233,-0.016619,0.024296,-0.001674,0.010792,0.020563,-0.015180,-0.000425,-0.003524
613569,2022-10-04 07:00:00,26,50.4506,30.5243,8.4,6.2,86.1,7.900,100.0,8.33,0.0,0.0,45.7,19.1,256.9,1009.6,98.1,9.3,0.9,0.0,0.27,7.5,4.8,87.75,0.0,0.0,0.0,36.0,15.1,250.2,1006.0,100.0,0.0,0.1,0.0,False,False,True,False,False,True,False,False,2022,10,1,7,Kyiv,Europe/Kiev,2022-10-04,07:02:26,18:30:04,07:00:00,Київ,0,0.000000,0.0,0.0,0.0,0.0,2.0,0,0,0.0,0.0,22,0.719363,-0.204014,0.008819,-0.218878,-0.008323,-0.130411,-0.187071,-0.068395,-0.124770,-0.115980,-0.102629,-0.005903,-0.010927,-0.081552,-0.078088,0.146895,-0.114094,0.068454,0.077431,0.045532,0.035725,0.107740,-0.010629,0.087263,0.038194,0.016414,0.015906,0.007038,0.004893,0.080502,0.021591,-0.041252,-0.053550,-0.007126,0.016174,-0.050342,-0.025574,-0.009341,-0.026104,-0.008516,0.014918,0.006605,0.001841,0.052598,0.014148,-0.007361,-0.016225,-0.047912,-0.028253,0.001602,-0.030085,0.030782,-0.017928,-0.045076,-0.002205,-0.015065,0.040191,0.019219,0.011977,-0.025463,-0.014422,0.015959,0.009609,0.040870,0.026142,-0.029856,-0.020193,0.010442,-0.003212,0.003296,0.050865,-0.029159,0.016325,0.001161,-0.029349,0.035770,0.029399,0.023528,-0.037106,-0.025997,0.000106,-0.016600,0.016446,-0.047453,0.017480,0.011351,-0.016698,0.029334,0.003135,0.004456,-0.016448,0.046049,0.014515,-0.005230,-0.040393,0.014410,0.022536,0.009402,0.023557,0.000610,0.014080,0.017300,0.002940,0.046960,0.031197,0.021149,-0.022380,-0.006352,-0.023671,-0.003071,-0.023779,-0.008341,-0.008926,0.026919,0.001766,0.022607,-0.034227,0.026028,-0.023944,-0.002999,0.011198,0.005516,-0.010693,0.034514,-0.014051,0.027171,0.002599,0.010255,0.008072,0.004374,-0.038196,0.011860,0.008705,0.011618,-0.033751,-0.006428,0.008047,-0.040640,-0.017538,0.012882,-0.038063,-0.023136,-0.021513,-0.023278,0.016302,0.003653,0.002187,-0.000045,-0.017122,0.024099

In [18]:
df_final.isna().sum()

datetime_hour        0
region_id            0
city_latitude        0
city_longitude       0
day_temp             0
                  ...
isw_topic_145     6336
isw_topic_146     6336
isw_topic_147     6336
isw_topic_148     6336
isw_topic_149     6336
Length: 216, dtype: int64

In [19]:
df_final.fillna(0, inplace=True)

In [20]:
df_final.isna().sum()

datetime_hour     0
region_id         0
city_latitude     0
city_longitude    0
day_temp          0
                 ..
isw_topic_145     0
isw_topic_146     0
isw_topic_147     0
isw_topic_148     0
isw_topic_149     0
Length: 216, dtype: int64

### Feature engineering for isw topics

In [21]:
topic_cols = [c for c in df_final.columns if "isw_topic_" in c]
df_isw_abs = df_final[topic_cols].abs()

df_final['isw_total_intensity'] = df_isw_abs.sum(axis=1)
df_final['isw_topic_std'] = df_isw_abs.std(axis=1)
df_final['isw_topic_max'] = df_isw_abs.max(axis=1)
df_final['isw_topic_mean'] = df_isw_abs.mean(axis=1)

df_final['isw_velocity_24h'] = (
    df_final.groupby('region_id')['isw_total_intensity']
    .diff(24)
    .fillna(0)
)

df_final['isw_intensity_ema'] = (df_final.groupby('region_id')['isw_total_intensity'].transform(lambda x: x.shift(1).ewm(span=24).mean()))

df_final['isw_topic_entropy'] = -(df_isw_abs.div(df_isw_abs.sum(axis=1), axis=0) * np.log(df_isw_abs.div(df_isw_abs.sum(axis=1), axis=0) + 1e-9)).sum(axis=1)

isw_cols = ['isw_velocity_24h', 'isw_intensity_ema', 'isw_topic_entropy']
df_final[isw_cols] = df_final[isw_cols].fillna(0)

In [22]:
df_final.sample(10)

,datetime_hour,region_id,city_latitude,city_longitude,day_temp,day_dew,day_humidity,day_precip,day_precipprob,day_precipcover,day_snow,day_snowdepth,day_windgust,day_windspeed,day_winddir,day_pressure,day_cloudcover,day_solarradiation,day_solarenergy,day_uvindex,day_moonphase,hour_temp,hour_feelslike,hour_humidity,hour_precip,hour_precipprob,hour_snow,hour_windgust,hour_windspeed,hour_winddir,hour_pressure,hour_cloudcover,hour_solarradiation,hour_solarenergy,hour_uvindex,day_conditions_simple_Clear,day_conditions_simple_Cloudy,day_conditions_simple_Rain,day_conditions_simple_Snow,hour_conditions_simple_Clear,hour_conditions_simple_Cloudy,hour_conditions_simple_Rain,hour_conditions_simple_Snow,year,month,day_of_week,hour,city_name,city_timezone,day_datetime,day_sunrise,day_sunset,hour_datetime,region_key,alarm_active,alarm_minutes_in_hour,alarm_lag_1,alarm_lag_3,alarm_lag_6,alarm_lag_12,alarms_in_last_24h,is_weekend,is_night,total_active_alarms_lag1,neighbour_alarms,hours_since_last_alarm,isw_topic_0,isw_topic_1,isw_topic_2,isw_topic_3,isw_topic_4,isw_topic_5,isw_topic_6,isw_topic_7,isw_topic_8,isw_topic_9,isw_topic_10,isw_topic_11,isw_topic_12,isw_topic_13,isw_topic_14,isw_topic_15,isw_topic_16,isw_topic_17,isw_topic_18,isw_topic_19,isw_topic_20,isw_topic_21,isw_topic_22,isw_topic_23,isw_topic_24,isw_topic_25,isw_topic_26,isw_topic_27,isw_topic_28,isw_topic_29,isw_topic_30,isw_topic_31,isw_topic_32,isw_topic_33,isw_topic_34,isw_topic_35,isw_topic_36,isw_topic_37,isw_topic_38,isw_topic_39,isw_topic_40,isw_topic_41,isw_topic_42,isw_topic_43,isw_topic_44,isw_topic_45,isw_topic_46,isw_topic_47,isw_topic_48,isw_topic_49,isw_topic_50,isw_topic_51,isw_topic_52,isw_topic_53,isw_topic_54,isw_topic_55,isw_topic_56,isw_topic_57,isw_topic_58,isw_topic_59,isw_topic_60,isw_topic_61,isw_topic_62,isw_topic_63,isw_topic_64,isw_topic_65,isw_topic_66,isw_topic_67,isw_topic_68,isw_topic_69,isw_topic_70,isw_topic_71,isw_topic_72,isw_topic_73,isw_topic_74,isw_topic_75,isw_topic_76,isw_topic_77,isw_topic_78,isw_topic_79,isw_topic_80,isw_topic_81,isw_topic_82,isw_topic_83,isw_topic_84,isw_topic_85,isw_topic_86,isw_topic_87,isw_topic_88,isw_topic_89,isw_topic_90,isw_topic_91,isw_topic_92,isw_topic_93,isw_topic_94,isw_topic_95,isw_topic_96,isw_topic_97,isw_topic_98,isw_topic_99,isw_topic_100,isw_topic_101,isw_topic_102,isw_topic_103,isw_topic_104,isw_topic_105,isw_topic_106,isw_topic_107,isw_topic_108,isw_topic_109,isw_topic_110,isw_topic_111,isw_topic_112,isw_topic_113,isw_topic_114,isw_topic_115,isw_topic_116,isw_topic_117,isw_topic_118,isw_topic_119,isw_topic_120,isw_topic_121,isw_topic_122,isw_topic_123,isw_topic_124,isw_topic_125,isw_topic_126,isw_topic_127,isw_topic_128,isw_topic_129,isw_topic_130,isw_topic_131,isw_topic_132,isw_topic_133,isw_topic_134,isw_topic_135,isw_topic_136,isw_topic_137,isw_topic_138,isw_topic_139,isw_topic_140,isw_topic_141,isw_topic_142,isw_topic_143,isw_topic_144,isw_topic_145,isw_topic_146,isw_topic_147,isw_topic_148,isw_topic_149,isw_total_intensity,isw_topic_std,isw_topic_max,isw_topic_mean,isw_velocity_24h,isw_intensity_ema,isw_topic_entropy
235691,2024-11-25 14:00:00,10,50.4506,30.5243,-2.8,-4.1,91.0,0.0,0.0,0.00,0.0,3.5,23.0,11.5,148.2,1033.0,72.5,41.5,3.6,2.0,0.81,2.1,2.1,75.38,0.0,0.0,0.0,19.8,3.6,130.0,1032.9,99.2,164.8,0.6,2.0,False,True,False,False,False,True,False,False,2024,11,0,14,Kyiv,Europe/Kiev,2024-11-25,07:28:36,16:01:06,14:00:00,Київська,0,0.0,0.0,0.0,1.0,1.0,17.0,0,0,3.0,0.0,4,0.809575,0.126041,0.006566,-0.052762,-0.010295,-0.148950,0.073070,-0.145940,0.172992,0.089046,0.014239,0.024531,-0.025037,0.030282,0.159686,0.015215,-0.005100,-0.008028,0.000373,-0.007137,0.033925,0.014047,-0.055206,-0.063304,-0.019147,0.026678,-0.046679,0.056787,0.033246,0.035540,-0.053926,0.038427,0.001441,-0.036659,-0.037144,-0.037759,0.008293,0.031385,-0.017946,0.017923,0.001561,-0.007191,0.003230,0.029285,0.008432,-0.035362,0.056134,-0.069675,-0.033101,0.004075,-0.027206,0.037080,-0.040772,0.051121,0.038028,-0.014109,0.003883,-0.000034,-0.015283,0.019460,0.033751,-0.022468,-0.029260,-0.031164,0.023076,-0.043114,-0.002236,0.040027,0.026820,-0.008508,0.016016,-0.047834,0.011573,-0.019893,-0.024359,0.016198,0.003226,0.036050,0.016688,0.032959,0.023702,0.022379,0.008264,0.009212,-0.038188,0.009716,-0.028460,0.026089,-0.022932,0.014152,-0.007247,0.008053,0.035643,-0.032886,-0.044464,-0.002637,0.026189,-0.010418,-0.000109,-0.024825,-0.032683,-0.001784,-0.008991,-0.017171,0.004468,-0.027584,0.008300,-0.059509,-0.009700,-0.013431,-0.000740,-0.008705,0.005241,-0.038167,0.003475,-0.006448,-0.018624,0.021719,0.014247,-0.026399,-0.047978,-0.016405,0.003048,-0.012830,-0.043708,-0.023382,0.001072,0.001918,0.024612,0.012522,-0.020507,0.019994,0.002129,0.003372,0.010724,0.031207,-0.040835,0.006974,0.024372,-0.002542,-0.015593,-0.002290,0.005275,0.005251,-0.013160,0.009243,0.025455,0.017300,0.016119,0.000321,4.753652,0.070145,0.809575,0.031691,0.340705,4.665230,4.245980
500017,2024-11-20 10:00:00,21,46.6401,32.6142,9.3,7.1,86.4,0.2,100.0,8.33,0.0,0.0,43.6,23.8,163.3,1008.0,85.9,38.7,3.2,2.0,0.65,11.5,11.5,81.81,0.0,0.0,0.0,33.1,17.3,150.9,1010.0,100.0,147.4,0.5,1.0,False,False,True,False,False,True,False,False,2024,11,2,10,Kherson,Europe/Kiev,2024-11-20,06:59:21,16:10:47,10:00:00,Херсонська,0,0.0,0.0,0.0,0.0,1.0,5.0,0,0,5.0,1.0,11,0.786305,0.036866,-0.076517,-0.030801,0.005244,-0.165724,0.101613,-0.152019,0.196280,0.107254,0.039135,0.043458,0.041123,-0.024781,-0.012920,0.103018,0.015126,-0.069384,0.086323,0.005620,0.104445,-0.061091,0.058505,-0.087654,0.001205,-0.067864,-0.038357,0.065608,0.047080,-0.039522,-0.027466,0.010448,-0.015074,-0.026158,0.050976,0.033417,0.104281,0.046798,0.017682,0.020355,0.028883,-0.038269,-0.004362,0.109371,0.027782,0.009606,0.001506,-0.007503,0.029348,0.008175,0.006063,-0.016647,-0.040880,-0.002035,0.039792,-0.091773,0.001538,0.010310,-0.032767,-0.028817,0.016348,-0.015213,0.006676,0.006233,-0.006944,0.040426,-0.007862,-0.001676,0.002567,0.043740,0.027277,0.005032,0.020037,0.048086,-0.003101,-0.028184,-0.008069,0.018089,-0.019254,-0.030151,0.017478,-0.004622,-0.021794,-0.026150,-0.015808,-0.008976,-0.012591,0.020582,-0.020072,0.011425,-0.012854,-0.009653,0.019554,-0.021037,0.000707,0.004541,0.017834,0.012341,-0.006492,0.028604,-0.031819,-0.015996,0.000553,0.022928,-0.002262,-0.002410,-0.011736,-0.012823,0.026764,0.003242,-0.009353,-0.021908,0.005336,-0.024033,-0.029418,-0.021825,0.001204,-0.004239,-0.004934,0.000413,-0.003536,0.018524,0.020399,0.014909,-0.006182,-0.039972,0.010848,-0.005227,-0.004333,0.009431,0.012554,-0.014627,-0.028519,-0.002624,-0.021420,0.016190,-0.024281,-0.020626,-0.002390,0.021910,0.014379,0.008067,-0.008697,-0.002483,0.043743,0.016015,0.002690,-0.004778,0.003197,0.015952,4.878701,0.069859,0.786305,0.032525,0.268575,4.749714,4.214343
60185,2022-12-25 00:00:00,4,48.4753,35.0160,3.5,2.4,93.0,1.7,100.0,33.33,0.0,0.0,21.2,9.0,104.2,1018.0,99.9,12.0,0.9,1.0,0.05,3.4,0.9,92.50,0.0,0.0,0.0,21.2,9.0,164.9,1016.0,99.4,0.0,0.1,0.0,False,False,True,False,False,True,False,False,2022,12,6,0,Dnipro,Europe/Kiev,2022-12-25,07:30:44,15:49:17,00:00:00,Дніпропетровська,0,0.0,0.0,0.0,0.0,1.0,4.0,1,1,0.0,0.0,8,0.809566,-0.196409,-0.032233,-0.086326,0.148188,-0.023343,0.189518,0.087118,-0.095699,-0.070627,-0.001373,-0.027606,-0.068135,0.026513,0.036955,0.019697,-0.023050,-0.014448,0.006674,0.042121,-0.025297,-0.048785,0.007854,-0.011332,-0.079996,0.053331,0.007105,-0.038692,-0.072512,-0.006532,0.050626,0.053903,-0.003414,0.054556,-0.032928,0.001202,-0.001257,0.008455,-0.009869,-0.010117,-0.026804,-0.010982,-0.044868,0.008987,0.022074,-0.038432,0.019896,-0.012970,-0.001921,-0.029381,0.019032,-0.035332,0.001614,-0.024054,0.021947,-0.011339,-0.003498,0.014354,0.032977,-0.030724,0.014783,-0.017348,-0.005722,0.025554,-0.002166,0.019098,0.010220,-0.012385,0.001630,-0.045434,-0.015693,-0.018981,-0.017245,0.002024,0.019183,0.012214,0.060423,0.008339,0.001490,0.000935,-0.022649,0.018910,-0.002154,-0.000689,-0.009321,0.015004,0.003453,-0.020068,0.003148,-0.018072,-0.028764,0.004412,-0.014014,-0.015942,-0.046063,0.022907,-0.051029,-0.010090,0.000070,-0.006896,0.036580,-0.024945,0.008543,0.019267,0.001852,0.020767,-0.008728,-0.021478,0.061181,0.001689,0.025912,-0.001722,-0.023965,-0.007190,-0.001642,-0.009544,-0.032375,-0.002604,0.011037,-0.000060,0.003877,-0.016094,0.008854,0.005657,-0.017668,-0.001895,0.007965,0.003111,-0.019711,0.014206,-0.003178,0.037324,0.023011,-0.011486,0.015731,0.016332,-0.024590,0.018844,0.002333,0.010969,0.005062,0.022287,0.009159,-0.025661,-0.002004,0.016753,0.008484,-0.028347,-0.010752,-0.008607,4.340102,0.070615,0.809566,0.028934,-0.799665,5.081725,4.129418
334906,2024-02-26 00:00:00,15,46.4725,30.7371,5.8,2.7,81.0,0.0,0.0,0.00,0.0,0.0,35.6,21.6,95.5,1019.5,92.9,145.0,12.3,6.0,0.56,3.4,-0.9,89.26,0.0,0.0,0.0,34.9,19.1,104.7,1020.0,99.0,0.0,0.0,0.0,False,True,False,False,False,True,False,False,2024,2,0,0,Odesa,Europe/Kiev,2024-02-26,06:43:08,17:37:45,00:00:00,Одеська,0,0.0,0.0,0.0,0.0,0.0,2.0,0,1,5.0,0.0,4,0.760773,-0.067256,-0.188997,0.121738,0.050318,-0.001267,-0.019135,0.034881,0.025635,0.005768,-0.053588,0.044910,0.231335,-0.206929,-0.003113,-0.090229,-0.017065,0.053637,0.010735,-0.015774,0.016651,0.044476,0.055364,-0.014038,-0.059230,0.065754,0.031092,-0.015021,0.033057,0.000781,0.067849,0.034394,-0.000613,0.011667,-0.029810,-0.046274,-0.041204,0.010683,0.035048,-0.011434,0.076755,-0.005346,0.055666,0.039113,-0.015070,0.018960,-0.012855,0.054050,-0.008249,0.013118,0.018093,-0.039517,-0.051138,-0.014548,0.027416,0.014257,0.002409,-0.012516,-0.017175,0.017865,-0.020161,-0.007647,0.019459,0.005348,0.016343,-0.018168,-0.030749,-0.005502,0.005952,-0.016165,-0.000062,-0.028295,-0.035815,0.007900,0.021607,0.046529,-0.024981,-0.021332,0.037632,0.016311,0.009261,0.002727,-0.025799,0.012427,0.020722,0.013047,-0.017719,-0.023363,0.019498,0.049973,-0.041259,-0.034813,0.009571,0.013834,0.048248,0.002906,0.045320,0.026773,0.029584,0.013305,-0.020674,-0.009830,0.007759,0.012591,0.049942,-0.007581,0.021853,-0.021536,-0.006276,-0.003401,0.018280,-0.021686,-0.037870,-0.002579,-0.015130,-0.009613,-0.003233,0.003017,0.000819,-0.020504,0.006679,-0.002466,-0.003387,0.003616,-0.002991,0.000300,0.047629,0.006312,0.018879,-0.032082,0.016931,-0.003202,-0.017296,0.043751,-0.002006,0.020407,-0.021463,0.002420,0.022537,0.054995,0.001826,-0.021785,-0.016975,-0.003058,0.028060,-0.026355,-0.033734,-0.033267,0.003364,-0.003351,4.783046,0.068302,0.760773,0.031887,0.320741,4.566854,4.242886
446406,2024-10-21 09:00:00,19,49.5527,25.5889,6.2,0.4,70.0,0.0,0.0,0.00,0.0,0.0,24.5,14.4,155.0,1033.3,9.8,0.0,0.0,0.0,0.63,2.1,2.1,88.51,0.0,0.0,0.0,7.9,0.0,151.3,1034.7,0.0,5.6,0.1,0.0,True,False,False,False,True,False,False,False,2024,10,0,9,Ternopil,Europe/Kiev,2024-10-21,07:48:55,18:14:46,09:00:00,Тернопільська,0,0.0,0.0,0.0,1.0,0.0,3.0,0,0,3.0,0.0,5,0.762875,0.102930,-0.082707,-0.062777,-0.091772,-0.163366,-0.172125,-0.143999,-0.020873,-0.149444,-0.139778,-0.011650,-0.073180,-0.039831,0.064940,-0.015831,-0.010005,-0.035767,-0.080164,0.019401,-0.015680,-0.031321,0.073128,0.013938,0.027536,0.025261,-0.020230,-0.005788,-0.011371,0.106444,-0.019423,0.156459,-0.117494,-0.010024,-0.008646,0.048681,0.009236,-0.061698,-0.001746,0.032905,0.074266,0.013554,0.054783,-0.033720,0.028952,-0.043678,-0.014137,0.009527,0.028553,0.034086,0.038150,-0.000833,0.037597,0.016371,-0.030717,0.004197,0.044016,-0.013772,0.003469,-0.000976,0.007928,-0.002907,-0.034117,0.076616,0.010983,0.067139,0.043944,-0.002758,-0.050492,0.016775,0.022732,0.033823,0.029951,0.047327,-0.007619,0.004761,0.035889,-0.044021,-0.018537,-0.038957,-0.011705,0.028810,-0.001756,0.009221,-0.073850,0.034647,0.015541,-0.019900,-0.002337,-0.037208,0.040225,0.009354,-0.005526,-0.000652,0.036740,0.015360,-0.033290,-0.005982,0.006305,-0.004344,-0.028249,0.011129,-0.006576,-0.036153,0.038002,-0.014680,-0.021433,-0.008241,-0.008684,-0.006531,0.045406,0.025754,-0.015455,-0.030228,0.014064,-0.002037,-0.006919,0.007845,-0.013324,-0.045500,0.023924,-0.010793,0.034918,0.003319,0.005206,-0.041536,-0.018988,0.015797,-0.007773,-0.010362,-0.001282,-0.015852,-0.009280,-0.029166,-0.017962,0.022837,0.028735,0.004286,0.002748,-0.016911,-0.016050,0.017939,0.008863,-0.005212,0.037589,-0.000604,0.007885,-0.011828,-0.012601,0.012585,5.394845,0.068843,0.762875,0.035966,0.637492,5.108728,4.304729
265989,2022-04-29 04:00:00,13,49.8444,24.0254,10.3,2.6,61.2,0.2,100.0,8.33,0.0,0.0,21.6,8.6,1.4,1026.3,57.5,242.4,20.7,8.0,0.93,6.5,6.5,76.68,0.0,0.0,0.0,3.6,2.5,321.4,1027.0,4.4,0.0,0.1,0.0,False,False,True,False,True,False,False,False,2022,4,4,4,Lviv,Europe/Kiev,2022-04-29,06:04:38,20:38:58,04:00:00,Львівська,0,0.0,0.0,0.0,0.0,0.0,4.0,0,1,0.0,0.0,6,0.641971,-0.204010,0.333254,0.225647,0.051358,-0.089651,-0.020759,-0.117743,-0.072282,-0.102466,0.194635,-0.053511,0.019263,-0.000684,0.007460,-0.072776,0.069582,-0.059744,0.071311,-0.048513,0.025141,0.059167,0.111116,0.032544,-0.020744,-0.035796,-0.151952,-0.074672,-0.012731,0.041625,0.001743,0.059080,-0.025556,-0.009203,0.020695,0.021563,-0.012380,-0.012660,0.018220,0.061412,-0.042660,0.049280,-0.016577,0.014532,-0.022945,-0.017183,0.005625,0.045374,0.009217,-0.013819,-0.007143,0.023363,0.011598,0.063908,-0.010418,-0.005991,-0.017589,0.022440,-0.001104,0.055702,0.035586,0.018726,0.053781,-0.036064,0.003823,-0.030473,0.007635,0.004924,0.016992,-0.018400,0.001857,-0.058583,-0.015016,-0.066507,0.059990,-0.041464,0.009723,0.062784,-0.034643,-0.034350,0.042159,-0.027573,0.020957,0.027587,0.026278,-0.021311,-0.021407,-0.037869,0.008231,-0.010601,0.002736,-0.007306,-0.005233,0.023478,-0.046791,0.004628,0.011653,-0.013125,-0.041179,-0.010222,0.030971,0.009225,0.002979,-0.008102,-0.002180,-0.036666,-0.017917,-0.031946,-0.023488,0.036499,0.019803,0.000930,0.005119,0.007040,-0.049927,0.009601,-0.027538,-0.003233,0.019290,0.026333,-0.014298,0.004852,-0.002802,-0.001794,0.017995,0.024467,-0.009631,0.019683,0.009655,-0.038656,0.028298,0.012071,-0.025372,-0.045723,-0.000674,-0.000158,0.005142,-0.007650,0.008990,-0.022918,-0.003365,0.006133,0.020213,0.001740,-0.013221,-0.006840,-0.021424,0.014804,-0.003940,-0.007439,5.511468,0.066109,0.641971,0.036743,0.047576,5.559984,4.293446
343476,2025-02-17 03:00:00,15,46.4725,30.7371,-2.8,-7.9,68.6,0.0,0.0,0.00,0.0,0.1,19.8,18.0,24.1,1026.1,81.6,110.4,9.6,4.0,0.66,-4.8,-7.8,77.07,0.0,0.0,0.0,10.1,6.5,9.3,1024.0,95.1,0.0,0.0,0.0,False,True,False,False,False,True,False,False,2025,2,0,3,Odesa,Europe/Kiev,2025-02-17,06:57:17,17:25:34,03:00:00,Одеська,0,0.0,0.0,1.0,1.0,0.0,7.0,0,1,12.0,1.0,2,0.790197,0.246565,-0.029359,0.138453,0.019231,0.001491,-0.008794,0.062597,-0.022936,0.031870,-0.017161,0.052476,0.163269,-0.201647,0.173575,0.042099,-0.047136,0.017402,0.056901,-0.052849,0.056697,0.028496,-0.012191,-0.061474,0.012571,-0.021257,0.026625,-0.008212,-0.045117,-0.028511,-0.046906,-0.001194,0.045225,-0.006427,0.020009,-0.038029,-0.017206,-0.051891,-0.001811,0.005010,-0.027240,-0.006076,-0.028097,0.017864,-0.002296,-0.013585,-0.043011,-0.031158,-0.010095,-0.005479,0.023782,0.020666,0.012891,0.006632,-0.029987,0.077684,-0.020781,-0.025689,-0.011657,0.018365,-0.007708,-0.018346,-0.031442,-0.029245,0.027748,0.030557,0.018683,0.001021,0.008382,-0.034541,0.030864,-0.001045,0.001272,-0.010912,-0.001412,-0.032424,0.002806,0.029402,-0.001607,0.020339,0.001917,-0.004801,-0.022487,0.006896,-0.015749,-0.005177,0.000031,-0.003410,0.007183,-0.014905,-0.007261,0.011453,0.011125,0.007712,-0.017566,0.005720,0.004062,0.000870,0.005477,-0.005422,0.012325,0.010781,0.034601,-0.001509,-0.025935,-0.035070,-0.033973,-0.014663,-0.018150,-0.018644,-0.024005,-0.030921,-0.020223,-0.013259,0.002730,-0.032464,-0.004745,0.017898,0.005244,0.022414,0.029099,-0.001425,0.005771,-0.022150,-0.018139,-0.017237,0.008935,-0.018833,0.000128,0.012099,0.003507,0.016427,0.032914,-0.006134,0.008470,0.010573,0.050801,0.012536,0.015519,0.025166,-0.012199,0.021286,0.001192,0.010213,-0.000912,0.005895,0.012320,0.007890,0.027198,0.027675,4.465082,0.071218,0.790197,0.029767,-0.276996,4.706759,4.125255
489983,2023-09-29 07:00:00,21,46.6401,32.6142,21.8,6.3,39.2,0.0,0.0,0.00,0.0,0.0,48.6,28.8,57.0,1019.8,0.8,182.5,15.6,6.0,0.50,15.6,15.6,56.17,0.0,0.0,0.0,27.7,16.6,49.8,1020.0,0.3,0.9,0.0,0.0,True,False,False,False,True,False,False,False,2023,9,4,7,Kherson,Europe/Kiev,2023-09-29,06:44:52,18:34:24,07:00:00,Херсонська,0,0.0,0.0,1.0,0.0,1.0,6.0,0,0,0.0,0.0,2,0.789960,-0.121263,-0.033877,-0.175309,-0.086559,0.011773,-0.068439,0.082953,0.029004,-0.047909,0.041022,0.028792,0.184633,0.273805,0.061864,-0.094992,0.003679,0.055495,0.064215,-0.055402,-0.025033,-0.020482,-0.008320,0.006865,0.025060,0.020195,-0.022112,-0.000704,0.033200,-0.015480,-0.010892,-0.004700,-0.011605,0.071043,0.018043,-0.004563,0.020284,-0.007534,0.013867,0.034729,0.006807,0.008819,-0.007713,0.011043,0.036814,0.031544,0.010041,-0.016463,-0.045096,0.007702,0.006357,0.012429,0.040907,0.010316,0.011365,0.052052,0.013897,-0.038683,-0.007810,0.009707,0.022999,-0.010997,0.011711,-0.001620,0.004322,0.037086,0.001145,-0.009543,-0.008996,0.018899,-0.040333,0.002960,-0.000720,-0.002591,0.005236,-0.013416,0.007812,-0.004205,0.048029,0.004918,0.053216,-0.006689,0.004083,0.004151,0.017735,-0.018994,0.007343,-0.003522,-0.004136,0.005370,-0.009124,-0.041523,-0.019721,-0.003931,-0.034908,0.003393,0.026919,-0.028874,0.012610,0.032625,-0.017370,0.024596,0.005774,0.000103,-0.010710,0.004941,0.007255,-0.000993,0.019126,0.013193,-0.007697,-0.027255,0.004574,0.021961,-0.009851,0.017475,0.002850,-0.008366,0.009755,-0.015687,0.033256,0.005263,-0.017617,0.012518,0.006050,-0.012048,0.020398,0.025047,0.008106,0.012101,-0.000564,-0.006652,0.010468,0.031985,0.011623,-0.007383,0.000241,0.015714,-0.004318,-0.014490,-0.026607,-0.024597,-0.005260,0.009151,0.000485,0.000615,0.001827,0.017342,0.016588,-0.023593,4.279057,0.071281,0.789960,0.028527,-0.164732,4.415175,4.065771
218241,2022-11-29 10:00:00,10,50.4506,30.5243,-0.1,-1.0,93.5,4.1,100.0,70.83,2.7,4.4,28.8,12.6,96.4,1030.7,100.0,17.8,1.5,1.0,0.17,-0.1,-4.0,93.65,0.3,100.0,0.1,28.1,12.2,106.2,1031.0,100.0,47.0,0.2,0.0,False,False,False,True,False,False,False,True,2022,11,1,10,Kyiv,Europe/Kiev,2022-11-29,07:33:38,15:58:24,10:00:00,Київська,0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,1.0,0.0,138,0.736127,-0.225210,-0.012568,-0.205814,0.094267,-0.193928,0.118738,-0.147990,0.172730,0.233521,0.095867,0.001144,0.022297,-0.041450,-0.045616,0.101663,-0.038607,-0.009167,0.010817,-0.009778,-0.049965,0.026813,0.010677,0.003139,-0.068666,-0.005238,0.045665,0.051646,0.024103,-0.032430,-0.047569,0.027233,0.001845,0.024905,0.001264,0.011207,-0.029516,0.015706,0.001551,0.028237,-0.008880,0.019428,-0.009842,0.030523,-0.027403,0.002297,-0.026315,0.010313,0.048285,-0.013382,-0.027255,0.018515,0.030621,-0.001819,-0.029154,0.011866,-0.030284,-0.040788,0.002128,-0.043528,-0.033026,-0.004643,-0.033478,0.004810,0.004023,-0.026824,-0.007077,0.047563,0.004991,0.019352,-0.052544,0.002436,0.003105,-0.016240,-0.021892,0.002865,0.021487,0.026258,0.010108,-0.029033,-0.008456,0.011672,-0.012426,0.039433,0.019431,0.019385,0.004894,-0.004997,-0.004751,-0.010702,-0.012868,-0.001060,0.002335,0.003482,-0.004609,-0.034224,0.007129,-0.013004,0.001599,0.031924,0.039810,-0.034103,-0.024383,0.018580,-0.030378,0.028918,0.011581,-0.017055,-0.024496,-0.027013,0.008361,0.010980,0.016052,-0.016838,0.005537,-0.004917,0.025493,-0.018281,-0.007648,-0.005604,0.006145,-0.001475,0.004620,0.019802,0.027891,-0.009686,-0.009516,-0.014756,-0.009117,-0.020618,0.006807,0.017575,-0.005259,-0.016026,-0.006647,0.006907,-0.007433,-0.024625,-0.004292,0.007167,-0.026714,0.012592,0.016084,-0.000628,0.025755,0.006360,-0.000426,-0.019019,0.001477,-0.003946,4.792829,0.070441,0.736127,0.031952,-1.550613,5.373197,4.122245

### TELEGRAM MERGE

In [23]:
df_tg_matrix = pd.read_csv("../data/telegram_processed_svd.csv")

In [24]:
df_tg_matrix.head()

,date,channel,tg_topic_0,tg_topic_1,tg_topic_2,tg_topic_3,tg_topic_4,tg_topic_5,tg_topic_6,tg_topic_7,tg_topic_8,tg_topic_9,tg_topic_10,tg_topic_11,tg_topic_12,tg_topic_13,tg_topic_14,tg_topic_15,tg_topic_16,tg_topic_17,tg_topic_18,tg_topic_19,tg_topic_20,tg_topic_21,tg_topic_22,tg_topic_23,tg_topic_24,tg_topic_25,tg_topic_26,tg_topic_27,tg_topic_28,tg_topic_29,tg_topic_30,tg_topic_31,tg_topic_32,tg_topic_33,tg_topic_34,tg_topic_35,tg_topic_36,tg_topic_37,tg_topic_38,tg_topic_39,tg_topic_40,tg_topic_41,tg_topic_42,tg_topic_43,tg_topic_44,tg_topic_45,tg_topic_46,tg_topic_47,tg_topic_48,tg_topic_49,tg_topic_50,tg_topic_51,tg_topic_52,tg_topic_53,tg_topic_54,tg_topic_55,tg_topic_56,tg_topic_57,tg_topic_58,tg_topic_59,tg_topic_60,tg_topic_61,tg_topic_62,tg_topic_63,tg_topic_64,tg_topic_65,tg_topic_66,tg_topic_67,tg_topic_68,tg_topic_69,tg_topic_70,tg_topic_71,tg_topic_72,tg_topic_73,tg_topic_74,tg_topic_75,tg_topic_76,tg_topic_77,tg_topic_78,tg_topic_79,tg_topic_80,tg_topic_81,tg_topic_82,tg_topic_83,tg_topic_84,tg_topic_85,tg_topic_86,tg_topic_87,tg_topic_88,tg_topic_89,tg_topic_90,tg_topic_91,tg_topic_92,tg_topic_93,tg_topic_94,tg_topic_95,tg_topic_96,tg_topic_97,tg_topic_98,tg_topic_99,tg_topic_100,tg_topic_101,tg_topic_102,tg_topic_103,tg_topic_104,tg_topic_105,tg_topic_106,tg_topic_107,tg_topic_108,tg_topic_109,tg_topic_110,tg_topic_111,tg_topic_112,tg_topic_113,tg_topic_114,tg_topic_115,tg_topic_116,tg_topic_117,tg_topic_118,tg_topic_119,tg_topic_120,tg_topic_121,tg_topic_122,tg_topic_123,tg_topic_124,tg_topic_125,tg_topic_126,tg_topic_127,tg_topic_128,tg_topic_129,tg_topic_130,tg_topic_131,tg_topic_132,tg_topic_133,tg_topic_134,tg_topic_135,tg_topic_136,tg_topic_137,tg_topic_138,tg_topic_139,tg_topic_140,tg_topic_141,tg_topic_142,tg_topic_143,tg_topic_144,tg_topic_145,tg_topic_146,tg_topic_147,tg_topic_148,tg_topic_149,tg_topic_150,tg_topic_151,tg_topic_152,tg_topic_153,tg_topic_154,tg_topic_155,tg_topic_156,tg_topic_157,tg_topic_158,tg_topic_159,tg_topic_160,tg_topic_161,tg_topic_162,tg_topic_163,tg_topic_164,tg_topic_165,tg_topic_166,tg_topic_167,tg_topic_168,tg_topic_169,tg_topic_170,tg_topic_171,tg_topic_172,tg_topic_173,tg_topic_174,tg_topic_175,tg_topic_176,tg_topic_177,tg_topic_178,tg_topic_179,tg_topic_180,tg_topic_181,tg_topic_182,tg_topic_183,tg_topic_184,tg_topic_185,tg_topic_186,tg_topic_187,tg_topic_188,tg_topic_189,tg_topic_190,tg_topic_191,tg_topic_192,tg_topic_193,tg_topic_194,tg_topic_195,tg_topic_196,tg_topic_197,tg_topic_198,tg_topic_199,tg_topic_200,tg_topic_201,tg_topic_202,tg_topic_203,tg_topic_204,tg_topic_205,tg_topic_206,tg_topic_207,tg_topic_208,tg_topic_209,tg_topic_210,tg_topic_211,tg_topic_212,tg_topic_213,tg_topic_214,tg_topic_215,tg_topic_216,tg_topic_217,tg_topic_218,tg_topic_219,tg_topic_220,tg_topic_221,tg_topic_222,tg_topic_223,tg_topic_224,tg_topic_225,tg_topic_226,tg_topic_227,tg_topic_228,tg_topic_229,tg_topic_230,tg_topic_231,tg_topic_232,tg_topic_233,tg_topic_234,tg_topic_235,tg_topic_236,tg_topic_237,tg_topic_238,tg_topic_239,tg_topic_240,tg_topic_241,tg_topic_242,tg_topic_243,tg_topic_244,tg_topic_245,tg_topic_246,tg_topic_247,tg_topic_248,tg_topic_249
0,2026-03-06 13:06:58,DeepStateUA,0.007121,0.000107,0.019843,0.000991,-0.011395,0.032671,-0.050983,0.061079,0.042624,-0.024342,-0.018764,0.023401,-0.017136,-0.358835,0.425288,0.017963,-0.107665,-0.032070,-0.045988,0.118212,0.091173,-0.248636,-0.001072,0.150764,0.030607,-0.074025,0.005802,0.005872,0.034871,0.017239,0.058098,0.029814,-0.010846,0.031485,-0.022706,0.005607,-0.006324,-0.010169,0.024500,-0.015581,-0.012708,0.005138,0.007857,0.016733,-0.040291,-0.019686,-0.026762,0.009384,-0.043499,-0.009524,-0.013075,-0.010474,-0.018151,0.005990,0.032610,0.000850,0.017870,0.020887,0.023896,-0.019292,-0.006676,-0.018478,-0.023265,-0.005496,-0.006460,0.026051,0.004991,0.019690,-0.022244,0.010931,0.007016,-0.067334,-0.035279,-0.005691,0.018746,0.039153,-0.053869,-0.078182,-0.074734,-0.082173,0.020503,0.084333,0.113472,-0.025870,-0.048315,0.096329,0.043776,0.029577,0.019818,0.002819,-0.007309,-0.005239,-0.053795,-0.005893,0.036485,-0.061233,-0.001457,0.048285,-0.017343,0.033956,0.039048,-0.045469,-0.035886,-0.033876,0.041562,-0.021958,-0.005455,-0.020616,0.006442,-0.016323,-0.010444,-0.015532,0.000982,0.002929,-0.010925,-0.004072,-0.007255,-0.020386,0.007355,0.022113,-0.000886,-0.019903,-0.009321,-0.043504,0.008560,-0.016975,0.004764,0.030854,0.012414,0.011306,0.017728,0.010619,-0.013779,-0.037938,-0.003762,0.015809,-0.027406,-0.033776,0.054686,-0.005475,0.077814,0.006890,-0.022643,-0.011037,0.007590,-0.011639,0.036640,-0.020274,0.016761,-0.000468,-0.007998,0.023813,-0.014156,-0.026536,-0.078013,0.014948,0.043508,-0.021709,0.013392,-0.008663,0.012711,0.037411,-0.032630,-0.021401,-0.030711,0.033489,-0.025717,0.008104,-0.011149,-0.002705,0.002763,0.017706,-0.010806,-0.012854,0.007063,0.021779,0.010665,-0.031774,0.011737,0.069730,0.029707,0.012841,-0.031855,0.001644,-0.002150,-0.045445,0.002484,0.021318,0.006080,-0.006014,0.006577,-0.036585,0.009374,-0.025446,-0.019476,-0.011097,0.014677,-0.016783,0.010994,0.002043,-0.004597,-0.008962,0.006640,-0.017489,0.003821,0.005925,0.000539,-0.002838,-0.035321,-0.004952,0.013549,0.015415,0.018978,0.017934,-0.002851,0.007877,0.026624,0.003337,-0.001597,0.011597,-0.016658,0.001502,-0.007203,0.002978,0.001582,0.012191,0.005657,0.006606,-0.027473,0.014277,-0.020135,-0.011432,0.015100,-0.008126,0.001881,-0.011405,0.006876,0.024785,0.019500,0.024145,0.017144,-0.013950,-0.027494,0.034615,-0.032077,-0.051153,-0.004736,-0.004042,-0.052157,-0.026376
1,2026-03-06 12:57:29,DeepStateUA,0.022770,-0.002163,0.041469,0.001527,-0.033584,0.077088,-0.078418,0.091533,0.014917,-0.016271,-0.019775,0.015027,-0.012900,-0.066689,0.049295,-0.031094,0.006109,-0.021357,-0.047947,0.025239,-0.010092,0.063969,0.026579,-0.002937,0.000963,-0.014692,-0.010761,0.001202,-0.015000,-0.005930,-0.010839,0.049023,-0.023755,0.030922,0.000490,-0.009320,-0.015764,0.024560,0.006806,-0.000411,-0.001480,-0.017301,-0.026283,0.007345,0.049169,-0.004317,0.029033,-0.034991,0.034364,-0.046228,-0.012752,0.048372,0.004352,-0.014647,0.034936,-0.016468,-0.013150,0.017353,-0.000885,0.004048,0.036549,-0.017461,0.009665,-0.007888,-0.027599,-0.016938,-0.037606,-0.009493,-0.002733,-0.006034,0.023059,0.028287,0.024791,0.010914,-0.000543,-0.016357,-0.003671,-0.016336,0.002607,0.013844,-0.005650,-0.012538,-0.007839,-0.041248,0.030817,-0.017629,-0.005068,-0.024102,-0.013482,0.010860,-0.015270,-0.006844,-0.013699,0.008861,-0.010812,0.022667,-0.034105,-0.016120,0.001827,0.003955,0.007681,-0.037766,-0.017956,0.016944,0.016305,-0.011406,0.021384,-0.001979,-0.005628,-0.080375,0.039482,0.015890,0.034496,-0.016937,0.004379,-0.005021,0.014320,-0.003485,-0.002882,-0.002484,-0.005047,0.017295,-0.003404,0.009432,-0.001667,0.018296,0.003153,-0.031687,0.003527,0.010405,-0.006933,-0.019231,-0.004084,-0.023477,-0.008855,-0.015654,0.053936,0.034132,-0.026432,0.018635,-0.050331,0.022857,-0.000991,0.001886,-0.013131,0.037481,0.025280,-0.008834,-0.009892,0.015772,-0.019761,-0.015571,-0.015168,0.040199,0.018232,0.018287,-0.011713,-0.000436,0.000450,0.012252,0.007597,-0.000338,0.004707,0.023601,-0.020464,0.016873,0.003245,-0.045373,0.004742,-0.036469,-0.025238,0.030740,-0.000796,0.015821,0.042126,0.010343,0.022697,0.005340,-0.001634,-0.018898,0.026072,-0.054025,-0.057859,0.004383,-0.020830,-0.034433,0.055865,0.016289,0.063019,0.010373,-0.004503,-0.030526,0.018836,-0.013645,0.002208,0.037503,-0.045901,-0.059515,-0.035371,-0.024916,-0.039117,0.035205,0.085953,0.009392,0.079263,0.013884,0.006546,-0.052122,-0.033630,0.008560,-0.019282,0.006147,0.002711,-0.056533,-0.022431,0.020387,-0.013979,-0.005105,-0.015282,-0.097909,-0.042230,0.020619,-0.042974,0.045041,0.005079,-0.022144,0.006542,0.054048,-0.042548,0.006341,-0.035597,-0.006032,0.000021,-0.033675,0.020931,-0.000564,-0.034844,0.034525,0.004792,0.001869,-0.019095,0.025732,0.000545,0.020312,-0.028054,0.001602,0.006979,-0.064937,0.022653,-0.017796
2,2026-03-06 08:32:47,DeepStateUA,0.009647,-0.001083,0.029820,0.004092,-0.021362,0.053648,-0.076999,0.085929,0.011210,-0.020903,-0.051376,0.013232,-0.021159,0.001682,0.049129,-0.010018,-0.014271,-0.012423,-0.010587,0.046603,0.026875,0.002453,0.003347,-0.018525,0.005328,-0.003516,0.003551,0.018054,0.002158,0.012886,0.034851,0.000381,-0.009229,-0.002467,0.002381,0.000435,0.000842,-0.004257,-0.003347,0.009321,-0.005700,-0.004300,-0.016553,-0.001784,0.016005,0.008306,0.000706,-0.004439,-0.004070,-0.017177,-0.017973,-0.000362,-0.033319,-0.032711,0.027865,-0.006006,0.000665,-0.001118,-0.020575,0.002030,0.001386,0.000074,0.000035,0.007953,0.005773,0.005407,-0.005473,0.009136,-0.010857,-0.014439,0.028165,-0.023102,0.014469,0.021406,-0.017700,0.035850,-0.021301,-0.016144,-0.007317,-0.016941,0.014848,-0.006708,-0.047833,-0.002701,0.006142,-0.016566,0.016765,0.017489,0.002920,-0.004175,0.003020,-0.032485,0.001182,0.015611,0.015266,0.023711,0.005132,-0.030744,-0.014357,0.024033,0.016936,-0.044399,0.005227,0.011765,-0.026128,-0.006000,0.011388,-0.012677,-0.016357,-0.020579,-0.003119,-0.003134,0.019594,-0.011793,0.015522,0.022933,0.013428,0.013832,-0.006376,0.006770,-0.023631,0.008807,0.003886,0.014648,-0.029621,0.047027,0.005468,-0.020455,0.018528,-0.009388,0.010160,0.010282,-0.016103,0.038234,-0.028750,0.030646,0.028346,0.020709,0.001122,-0.009170,-0.064016,0.007833,0.005443,0.008333,-0.002819,0.007244,0.037717,-0.034047,0.009513,0.002275,-0.009622,-0.009045,0.023600,-0.009767,-0.047728,0.011989,-0.016424,0.004241,0.039252,0.030453,-0.007662,-0.043307,-0.005344,-0.003349,0.004918,0.010622,0.011747,-0.029660,-0.016772,-0.004055,-0.019135,-0.010517,-0.016021,0.013939,0.061202,0.000223,-0.016080,-0.013129,0.011073,0.025287,0.030599,-0.001899,-0.032926,0.022217,0.024392,-0.023035,0.001307,-0.010152,0.002524,0.003085,0.002821,0.012997,0.008940,-0.011743,0.019254,-0.000332,0.025401,-0.044007,-0.021811,-0.040766,-0.011047,0.008859,-0.020370,-0.005455,0.002682,0.019287,0.025490,-0.019261,-0.011527,-0.015350,-0.003905,0.007483,0.039590,0.030822,-0.034833,0.029723,0.018858,0.009886,0.006251,-0.006876,-0.028340,-0.017258,-0.019577,-0.004745,-0.014048,-0.014085,-0.018755,-0.006643,0.002466,-0.014730,0.015979,-0.020570,-0.000180,-0.020247,0.003822,-0.020507,-0.006351,-0.011116,-0.002429,0.036064,0.025382,-0.003562,-0.043411,-0.007184,-0.009170,0.006113,-0.004557,0.020586,0.010520,0.012833
3,2026-03-05 16:46:58,DeepStateUA,0.006857,0.000279,0.019019,0.000875,-0.011544,0.032104,-0.049929,0.059695,0.042415,-0.023917,-0.020172,0.022360,-0.016424,-0.354005,0.422411,0.017229,-0.106291,-0.032502,-0.045504,0.118053,0.090724,-0.246773,-0.000080,0.150528,0.029984,-0.074168,0.006981,0.007685,0.035762,0.018339,0.059439,0.029451,-0.012748,0.032324,-0.024158,0.006144,-0.004921,-0.007047,0.024916,-0.013464,-0.012810,0.004617,0.006306,0.017776,-0.037228,-0.018747,-0.026074,0.008028,-0.040668,-0.008453,-0.012120,-0.009957,-0.018019,0.006663,0.032068,0.001405,0.015929,0.020068,0.022358,-0.017345,-0.007000,-0.017683,-0.021565,-0.005666,-0.004898,0.022713,0.002353,0.021029,-0.020492,0.010267,0.006341,-0.062293,-0.031897,-0.004837,0.019041,0.034735,-0.048355,-0.072648,-0.066844,-0.074670,0.019530,0.081762,0.106478,-0.025838,-0.046011,0.091823,0.043274,0.026991,0.018546,0.002251,-0.006683,-0.005203,-0.051075,-0.003016,0.029779,-0.054538,-0.002316,0.044861,-0.018022,0.033034,0.036192,-0.042967,-0.033102,-0.031217,0.040024,-0.016620,-0.004322,-0.022598,0.001446,-0.018905,-0.015046,-0.006993,0.004125,0.000551,-0.011208,-0.006347,-0.005327,-0.023457,0.009405,0.021776,-0.001563,-0.021656,-0.010061,-0.041095,0.009061,-0.016846,0.014129,0.030821,0.014433,0.011398,0.017333,0.012037,-0.011978,-0.037318,-0.000056,0.013756,-0.023927,-0.033052,0.051295,-0.004699,0.075120,0.004400,-0.023162,-0.009870,0.008475,-0.011321,0.038669,-0.021758,0.017178,-0.003656,-0.004499,0.024860,-0.010264,-0.023716,-0.073988,0.014857,0.037362,-0.023343,0.010636,-0.008620,0.012116,0.033947,-0.033244,-0.018742,-0.029519,0.034793,-0.025602,0.008933,-0.006082,-0.003807,-0.002694,0.017622,-0.010777,-0.010497,0.004240,0.018069,0.015271,-0.027503,0.007465,0.058354,0.024459,0.010805,-0.030663,-0.001720,-0.001191,-0.040229,0.003916,0.019605,0.006115,-0.006860,0.006675,-0.036680,0.007406,-0.025808,-0.014272,-0.007470,0.014519,-0.012829,0.005290,-0.002305,-0.003708,-0.008705,0.000810,-0.012632,0.003962,0.004388,0.000393,0.002007,-0.028687,-0.003862,0.011870,0.012459,0.016569,0.009523,-0.001083,0.007506,0.021555,0.002597,0.005688,0.003032,-0.016085,0.005064,-0.006297,0.000892,0.002826,0.014468,0.006542,0.000063,-0.020973,0.009388,-0.014719,-0.008427,0.016369,-0.008306,-0.000711,-0.008819,0.006667,0.012458,0.012085,0.020714,0.008731,-0.007507,-0.021414,0.028226,-0.025335,-0.045774,-0.001725,0.002281,-0.042259,-0.017379
4,2026-03-05 15:46:39,DeepStateUA,0.048850,-0.006687,0.076040,-0.003924,-0.027197,0.089563,-0.088812,0.109835,0.052316,-0.025058,0.032393,-0.004228,-0.005031,-0.173462,0.094957,0.012581,-0.022471,-0.000702,-0.014110,-0.004740,-0.012714,0.127034,0.018405,-0.023593,0.003991,0.039284,-0.018525,0.000346,-0.081926,-0.045458,-0.116433,-0.028074,-0.013547,0.024680,0.046939,-0.021635,0.023137,0.009856,-0.025864,-0.041176,-0.000833,-0.024708,0.013632,-0.022766,0.057347,0.020488,0.010215,-0.026627,0.022513,0.022438,0.035390,-0.021222,0.008282,-0.000370,-0.015991,0.012876,-0.018086,-0.005189,-0.021091,0.012909,-0.008576,-0.008822,0.030579,0.014678,0.017474,0.007798,0.004474,-0.006689,0.023421,0.017912,0.009466,-0.011250,-0.006204,0.008318,-0.038523,0.017134,0.046953,0.005523,0.071625,0.044149,-0.006386,0.009274,-0.010303,-0.023799,0.013101,0.004949,0.000503,-0.025377,0.000579,0.005653,0.013762,-0.033165,0.011962,0.032019,-0.010733,0.074742,-0.045164,-0.069854,0.017152,-0.028895,-0.001318,-0.020144,-0.001435,0.077727,0.008475,0.017214,0.063803,0.022661,-0.019577,-0.089311,0.043187,0.054777,0.003839,0.005617,0.042290,-0.040706,0.034213,-0.018436,0.026248,-0.012017,0.004664,0.009544,0.028976,0.022278,0.015841,0.026391,-0.030021,-0.019719,0.008558,-0.006588,-0.012466,-0.013105,0.000680,-0.040798,0.018813,-0.018854,0.015615,-0.026298,-0.013062,-0.022980,-0.019654,0.003882,0.019574,0.020301,-0.053047,-0.013297,-0.013324,0.043430,-0.020311,-0.004050,-0.017731,-0.008400,-0.063165,-0.008025,0.060144,-0.036648,-0.009352,-0.031417,-0.019358,0.002939,0.015681,0.058795,0.034305,0.025502,0.026523,-0.024327,0.001476,-0.008038,-0.008200,0.018152,0.016015,-0.009222,0.020973,0.008693,-0.047261,0.028264,-0.002850,0.009419,-0.012005,0.004515,-0.010160,-0.031829,-0.005523,0.038707,-0.014279,0.009806,0.004056,-0.009505,0.033001,-0.038354,-0.005477,0.016190,-0.012159,-0.003113,0.007211,-0.049556,0.001332,0.025863,0.002219,0.009790,-0.002899,0.012787,-0.039636,-0.014672,0.012542,-0.026680,-0.057038,-0.038301,-0.031191,-0.025931,0.009650,0.004544,0.035683,-0.013256,0.015054,-0.006507,0.018665,-0.013960,0.023983,0.033370,-0.000121,-0.000184,0.012092,0.023327,0.014000,-0.007482,-0.006610,-0.045891,0.004304,-0.008434,0.004577,-0.039592,0.004910,0.010364,-0.002958,-0.053009,0.008562,-0.002759,0.010717,0.035418,0.017981,0.027449,-0.019751,0.008681,0.023138,-0.009474,-0.030269,0.013652,-0.022735,0.006830

In [25]:
df_tg_matrix["datetime_hour"] = pd.to_datetime(df_tg_matrix["date"]).dt.floor("h")

In [26]:
topic_cols = [c for c in df_tg_matrix.columns if "tg_topic_" in c]

tg_hourly = (
    df_tg_matrix.groupby("datetime_hour")[topic_cols]
    .mean()
    .sort_index()
    .ffill()
    .reset_index()
)

In [27]:
df_tg_matrix.head()

,date,channel,tg_topic_0,tg_topic_1,tg_topic_2,tg_topic_3,tg_topic_4,tg_topic_5,tg_topic_6,tg_topic_7,tg_topic_8,tg_topic_9,tg_topic_10,tg_topic_11,tg_topic_12,tg_topic_13,tg_topic_14,tg_topic_15,tg_topic_16,tg_topic_17,tg_topic_18,tg_topic_19,tg_topic_20,tg_topic_21,tg_topic_22,tg_topic_23,tg_topic_24,tg_topic_25,tg_topic_26,tg_topic_27,tg_topic_28,tg_topic_29,tg_topic_30,tg_topic_31,tg_topic_32,tg_topic_33,tg_topic_34,tg_topic_35,tg_topic_36,tg_topic_37,tg_topic_38,tg_topic_39,tg_topic_40,tg_topic_41,tg_topic_42,tg_topic_43,tg_topic_44,tg_topic_45,tg_topic_46,tg_topic_47,tg_topic_48,tg_topic_49,tg_topic_50,tg_topic_51,tg_topic_52,tg_topic_53,tg_topic_54,tg_topic_55,tg_topic_56,tg_topic_57,tg_topic_58,tg_topic_59,tg_topic_60,tg_topic_61,tg_topic_62,tg_topic_63,tg_topic_64,tg_topic_65,tg_topic_66,tg_topic_67,tg_topic_68,tg_topic_69,tg_topic_70,tg_topic_71,tg_topic_72,tg_topic_73,tg_topic_74,tg_topic_75,tg_topic_76,tg_topic_77,tg_topic_78,tg_topic_79,tg_topic_80,tg_topic_81,tg_topic_82,tg_topic_83,tg_topic_84,tg_topic_85,tg_topic_86,tg_topic_87,tg_topic_88,tg_topic_89,tg_topic_90,tg_topic_91,tg_topic_92,tg_topic_93,tg_topic_94,tg_topic_95,tg_topic_96,tg_topic_97,tg_topic_98,tg_topic_99,tg_topic_100,tg_topic_101,tg_topic_102,tg_topic_103,tg_topic_104,tg_topic_105,tg_topic_106,tg_topic_107,tg_topic_108,tg_topic_109,tg_topic_110,tg_topic_111,tg_topic_112,tg_topic_113,tg_topic_114,tg_topic_115,tg_topic_116,tg_topic_117,tg_topic_118,tg_topic_119,tg_topic_120,tg_topic_121,tg_topic_122,tg_topic_123,tg_topic_124,tg_topic_125,tg_topic_126,tg_topic_127,tg_topic_128,tg_topic_129,tg_topic_130,tg_topic_131,tg_topic_132,tg_topic_133,tg_topic_134,tg_topic_135,tg_topic_136,tg_topic_137,tg_topic_138,tg_topic_139,tg_topic_140,tg_topic_141,tg_topic_142,tg_topic_143,tg_topic_144,tg_topic_145,tg_topic_146,tg_topic_147,tg_topic_148,tg_topic_149,tg_topic_150,tg_topic_151,tg_topic_152,tg_topic_153,tg_topic_154,tg_topic_155,tg_topic_156,tg_topic_157,tg_topic_158,tg_topic_159,tg_topic_160,tg_topic_161,tg_topic_162,tg_topic_163,tg_topic_164,tg_topic_165,tg_topic_166,tg_topic_167,tg_topic_168,tg_topic_169,tg_topic_170,tg_topic_171,tg_topic_172,tg_topic_173,tg_topic_174,tg_topic_175,tg_topic_176,tg_topic_177,tg_topic_178,tg_topic_179,tg_topic_180,tg_topic_181,tg_topic_182,tg_topic_183,tg_topic_184,tg_topic_185,tg_topic_186,tg_topic_187,tg_topic_188,tg_topic_189,tg_topic_190,tg_topic_191,tg_topic_192,tg_topic_193,tg_topic_194,tg_topic_195,tg_topic_196,tg_topic_197,tg_topic_198,tg_topic_199,tg_topic_200,tg_topic_201,tg_topic_202,tg_topic_203,tg_topic_204,tg_topic_205,tg_topic_206,tg_topic_207,tg_topic_208,tg_topic_209,tg_topic_210,tg_topic_211,tg_topic_212,tg_topic_213,tg_topic_214,tg_topic_215,tg_topic_216,tg_topic_217,tg_topic_218,tg_topic_219,tg_topic_220,tg_topic_221,tg_topic_222,tg_topic_223,tg_topic_224,tg_topic_225,tg_topic_226,tg_topic_227,tg_topic_228,tg_topic_229,tg_topic_230,tg_topic_231,tg_topic_232,tg_topic_233,tg_topic_234,tg_topic_235,tg_topic_236,tg_topic_237,tg_topic_238,tg_topic_239,tg_topic_240,tg_topic_241,tg_topic_242,tg_topic_243,tg_topic_244,tg_topic_245,tg_topic_246,tg_topic_247,tg_topic_248,tg_topic_249,datetime_hour
0,2026-03-06 13:06:58,DeepStateUA,0.007121,0.000107,0.019843,0.000991,-0.011395,0.032671,-0.050983,0.061079,0.042624,-0.024342,-0.018764,0.023401,-0.017136,-0.358835,0.425288,0.017963,-0.107665,-0.032070,-0.045988,0.118212,0.091173,-0.248636,-0.001072,0.150764,0.030607,-0.074025,0.005802,0.005872,0.034871,0.017239,0.058098,0.029814,-0.010846,0.031485,-0.022706,0.005607,-0.006324,-0.010169,0.024500,-0.015581,-0.012708,0.005138,0.007857,0.016733,-0.040291,-0.019686,-0.026762,0.009384,-0.043499,-0.009524,-0.013075,-0.010474,-0.018151,0.005990,0.032610,0.000850,0.017870,0.020887,0.023896,-0.019292,-0.006676,-0.018478,-0.023265,-0.005496,-0.006460,0.026051,0.004991,0.019690,-0.022244,0.010931,0.007016,-0.067334,-0.035279,-0.005691,0.018746,0.039153,-0.053869,-0.078182,-0.074734,-0.082173,0.020503,0.084333,0.113472,-0.025870,-0.048315,0.096329,0.043776,0.029577,0.019818,0.002819,-0.007309,-0.005239,-0.053795,-0.005893,0.036485,-0.061233,-0.001457,0.048285,-0.017343,0.033956,0.039048,-0.045469,-0.035886,-0.033876,0.041562,-0.021958,-0.005455,-0.020616,0.006442,-0.016323,-0.010444,-0.015532,0.000982,0.002929,-0.010925,-0.004072,-0.007255,-0.020386,0.007355,0.022113,-0.000886,-0.019903,-0.009321,-0.043504,0.008560,-0.016975,0.004764,0.030854,0.012414,0.011306,0.017728,0.010619,-0.013779,-0.037938,-0.003762,0.015809,-0.027406,-0.033776,0.054686,-0.005475,0.077814,0.006890,-0.022643,-0.011037,0.007590,-0.011639,0.036640,-0.020274,0.016761,-0.000468,-0.007998,0.023813,-0.014156,-0.026536,-0.078013,0.014948,0.043508,-0.021709,0.013392,-0.008663,0.012711,0.037411,-0.032630,-0.021401,-0.030711,0.033489,-0.025717,0.008104,-0.011149,-0.002705,0.002763,0.017706,-0.010806,-0.012854,0.007063,0.021779,0.010665,-0.031774,0.011737,0.069730,0.029707,0.012841,-0.031855,0.001644,-0.002150,-0.045445,0.002484,0.021318,0.006080,-0.006014,0.006577,-0.036585,0.009374,-0.025446,-0.019476,-0.011097,0.014677,-0.016783,0.010994,0.002043,-0.004597,-0.008962,0.006640,-0.017489,0.003821,0.005925,0.000539,-0.002838,-0.035321,-0.004952,0.013549,0.015415,0.018978,0.017934,-0.002851,0.007877,0.026624,0.003337,-0.001597,0.011597,-0.016658,0.001502,-0.007203,0.002978,0.001582,0.012191,0.005657,0.006606,-0.027473,0.014277,-0.020135,-0.011432,0.015100,-0.008126,0.001881,-0.011405,0.006876,0.024785,0.019500,0.024145,0.017144,-0.013950,-0.027494,0.034615,-0.032077,-0.051153,-0.004736,-0.004042,-0.052157,-0.026376,2026-03-06 13:00:00
1,2026-03-06 12:57:29,DeepStateUA,0.022770,-0.002163,0.041469,0.001527,-0.033584,0.077088,-0.078418,0.091533,0.014917,-0.016271,-0.019775,0.015027,-0.012900,-0.066689,0.049295,-0.031094,0.006109,-0.021357,-0.047947,0.025239,-0.010092,0.063969,0.026579,-0.002937,0.000963,-0.014692,-0.010761,0.001202,-0.015000,-0.005930,-0.010839,0.049023,-0.023755,0.030922,0.000490,-0.009320,-0.015764,0.024560,0.006806,-0.000411,-0.001480,-0.017301,-0.026283,0.007345,0.049169,-0.004317,0.029033,-0.034991,0.034364,-0.046228,-0.012752,0.048372,0.004352,-0.014647,0.034936,-0.016468,-0.013150,0.017353,-0.000885,0.004048,0.036549,-0.017461,0.009665,-0.007888,-0.027599,-0.016938,-0.037606,-0.009493,-0.002733,-0.006034,0.023059,0.028287,0.024791,0.010914,-0.000543,-0.016357,-0.003671,-0.016336,0.002607,0.013844,-0.005650,-0.012538,-0.007839,-0.041248,0.030817,-0.017629,-0.005068,-0.024102,-0.013482,0.010860,-0.015270,-0.006844,-0.013699,0.008861,-0.010812,0.022667,-0.034105,-0.016120,0.001827,0.003955,0.007681,-0.037766,-0.017956,0.016944,0.016305,-0.011406,0.021384,-0.001979,-0.005628,-0.080375,0.039482,0.015890,0.034496,-0.016937,0.004379,-0.005021,0.014320,-0.003485,-0.002882,-0.002484,-0.005047,0.017295,-0.003404,0.009432,-0.001667,0.018296,0.003153,-0.031687,0.003527,0.010405,-0.006933,-0.019231,-0.004084,-0.023477,-0.008855,-0.015654,0.053936,0.034132,-0.026432,0.018635,-0.050331,0.022857,-0.000991,0.001886,-0.013131,0.037481,0.025280,-0.008834,-0.009892,0.015772,-0.019761,-0.015571,-0.015168,0.040199,0.018232,0.018287,-0.011713,-0.000436,0.000450,0.012252,0.007597,-0.000338,0.004707,0.023601,-0.020464,0.016873,0.003245,-0.045373,0.004742,-0.036469,-0.025238,0.030740,-0.000796,0.015821,0.042126,0.010343,0.022697,0.005340,-0.001634,-0.018898,0.026072,-0.054025,-0.057859,0.004383,-0.020830,-0.034433,0.055865,0.016289,0.063019,0.010373,-0.004503,-0.030526,0.018836,-0.013645,0.002208,0.037503,-0.045901,-0.059515,-0.035371,-0.024916,-0.039117,0.035205,0.085953,0.009392,0.079263,0.013884,0.006546,-0.052122,-0.033630,0.008560,-0.019282,0.006147,0.002711,-0.056533,-0.022431,0.020387,-0.013979,-0.005105,-0.015282,-0.097909,-0.042230,0.020619,-0.042974,0.045041,0.005079,-0.022144,0.006542,0.054048,-0.042548,0.006341,-0.035597,-0.006032,0.000021,-0.033675,0.020931,-0.000564,-0.034844,0.034525,0.004792,0.001869,-0.019095,0.025732,0.000545,0.020312,-0.028054,0.001602,0.006979,-0.064937,0.022653,-0.017796,2026-03-06 12:00:00
2,2026-03-06 08:32:47,DeepStateUA,0.009647,-0.001083,0.029820,0.004092,-0.021362,0.053648,-0.076999,0.085929,0.011210,-0.020903,-0.051376,0.013232,-0.021159,0.001682,0.049129,-0.010018,-0.014271,-0.012423,-0.010587,0.046603,0.026875,0.002453,0.003347,-0.018525,0.005328,-0.003516,0.003551,0.018054,0.002158,0.012886,0.034851,0.000381,-0.009229,-0.002467,0.002381,0.000435,0.000842,-0.004257,-0.003347,0.009321,-0.005700,-0.004300,-0.016553,-0.001784,0.016005,0.008306,0.000706,-0.004439,-0.004070,-0.017177,-0.017973,-0.000362,-0.033319,-0.032711,0.027865,-0.006006,0.000665,-0.001118,-0.020575,0.002030,0.001386,0.000074,0.000035,0.007953,0.005773,0.005407,-0.005473,0.009136,-0.010857,-0.014439,0.028165,-0.023102,0.014469,0.021406,-0.017700,0.035850,-0.021301,-0.016144,-0.007317,-0.016941,0.014848,-0.006708,-0.047833,-0.002701,0.006142,-0.016566,0.016765,0.017489,0.002920,-0.004175,0.003020,-0.032485,0.001182,0.015611,0.015266,0.023711,0.005132,-0.030744,-0.014357,0.024033,0.016936,-0.044399,0.005227,0.011765,-0.026128,-0.006000,0.011388,-0.012677,-0.016357,-0.020579,-0.003119,-0.003134,0.019594,-0.011793,0.015522,0.022933,0.013428,0.013832,-0.006376,0.006770,-0.023631,0.008807,0.003886,0.014648,-0.029621,0.047027,0.005468,-0.020455,0.018528,-0.009388,0.010160,0.010282,-0.016103,0.038234,-0.028750,0.030646,0.028346,0.020709,0.001122,-0.009170,-0.064016,0.007833,0.005443,0.008333,-0.002819,0.007244,0.037717,-0.034047,0.009513,0.002275,-0.009622,-0.009045,0.023600,-0.009767,-0.047728,0.011989,-0.016424,0.004241,0.039252,0.030453,-0.007662,-0.043307,-0.005344,-0.003349,0.004918,0.010622,0.011747,-0.029660,-0.016772,-0.004055,-0.019135,-0.010517,-0.016021,0.013939,0.061202,0.000223,-0.016080,-0.013129,0.011073,0.025287,0.030599,-0.001899,-0.032926,0.022217,0.024392,-0.023035,0.001307,-0.010152,0.002524,0.003085,0.002821,0.012997,0.008940,-0.011743,0.019254,-0.000332,0.025401,-0.044007,-0.021811,-0.040766,-0.011047,0.008859,-0.020370,-0.005455,0.002682,0.019287,0.025490,-0.019261,-0.011527,-0.015350,-0.003905,0.007483,0.039590,0.030822,-0.034833,0.029723,0.018858,0.009886,0.006251,-0.006876,-0.028340,-0.017258,-0.019577,-0.004745,-0.014048,-0.014085,-0.018755,-0.006643,0.002466,-0.014730,0.015979,-0.020570,-0.000180,-0.020247,0.003822,-0.020507,-0.006351,-0.011116,-0.002429,0.036064,0.025382,-0.003562,-0.043411,-0.007184,-0.009170,0.006113,-0.004557,0.020586,0.010520,0.012833,2026-03-06 08:00:00
3,2026-03-05 16:46:58,DeepStateUA,0.006857,0.000279,0.019019,0.000875,-0.011544,0.032104,-0.049929,0.059695,0.042415,-0.023917,-0.020172,0.022360,-0.016424,-0.354005,0.422411,0.017229,-0.106291,-0.032502,-0.045504,0.118053,0.090724,-0.246773,-0.000080,0.150528,0.029984,-0.074168,0.006981,0.007685,0.035762,0.018339,0.059439,0.029451,-0.012748,0.032324,-0.024158,0.006144,-0.004921,-0.007047,0.024916,-0.013464,-0.012810,0.004617,0.006306,0.017776,-0.037228,-0.018747,-0.026074,0.008028,-0.040668,-0.008453,-0.012120,-0.009957,-0.018019,0.006663,0.032068,0.001405,0.015929,0.020068,0.022358,-0.017345,-0.007000,-0.017683,-0.021565,-0.005666,-0.004898,0.022713,0.002353,0.021029,-0.020492,0.010267,0.006341,-0.062293,-0.031897,-0.004837,0.019041,0.034735,-0.048355,-0.072648,-0.066844,-0.074670,0.019530,0.081762,0.106478,-0.025838,-0.046011,0.091823,0.043274,0.026991,0.018546,0.002251,-0.006683,-0.005203,-0.051075,-0.003016,0.029779,-0.054538,-0.002316,0.044861,-0.018022,0.033034,0.036192,-0.042967,-0.033102,-0.031217,0.040024,-0.016620,-0.004322,-0.022598,0.001446,-0.018905,-0.015046,-0.006993,0.004125,0.000551,-0.011208,-0.006347,-0.005327,-0.023457,0.009405,0.021776,-0.001563,-0.021656,-0.010061,-0.041095,0.009061,-0.016846,0.014129,0.030821,0.014433,0.011398,0.017333,0.012037,-0.011978,-0.037318,-0.000056,0.013756,-0.023927,-0.033052,0.051295,-0.004699,0.075120,0.004400,-0.023162,-0.009870,0.008475,-0.011321,0.038669,-0.021758,0.017178,-0.003656,-0.004499,0.024860,-0.010264,-0.023716,-0.073988,0.014857,0.037362,-0.023343,0.010636,-0.008620,0.012116,0.033947,-0.033244,-0.018742,-0.029519,0.034793,-0.025602,0.008933,-0.006082,-0.003807,-0.002694,0.017622,-0.010777,-0.010497,0.004240,0.018069,0.015271,-0.027503,0.007465,0.058354,0.024459,0.010805,-0.030663,-0.001720,-0.001191,-0.040229,0.003916,0.019605,0.006115,-0.006860,0.006675,-0.036680,0.007406,-0.025808,-0.014272,-0.007470,0.014519,-0.012829,0.005290,-0.002305,-0.003708,-0.008705,0.000810,-0.012632,0.003962,0.004388,0.000393,0.002007,-0.028687,-0.003862,0.011870,0.012459,0.016569,0.009523,-0.001083,0.007506,0.021555,0.002597,0.005688,0.003032,-0.016085,0.005064,-0.006297,0.000892,0.002826,0.014468,0.006542,0.000063,-0.020973,0.009388,-0.014719,-0.008427,0.016369,-0.008306,-0.000711,-0.008819,0.006667,0.012458,0.012085,0.020714,0.008731,-0.007507,-0.021414,0.028226,-0.025335,-0.045774,-0.001725,0.002281,-0.042259,-0.017379,2026-03-05 16:00:00
4,2026-03-05 15:46:39,DeepStateUA,0.048850,-0.006687,0.076040,-0.003924,-0.027197,0.089563,-0.088812,0.109835,0.052316,-0.025058,0.032393,-0.004228,-0.005031,-0.173462,0.094957,0.012581,-0.022471,-0.000702,-0.014110,-0.004740,-0.012714,0.127034,0.018405,-0.023593,0.003991,0.039284,-0.018525,0.000346,-0.081926,-0.045458,-0.116433,-0.028074,-0.013547,0.024680,0.046939,-0.021635,0.023137,0.009856,-0.025864,-0.041176,-0.000833,-0.024708,0.013632,-0.022766,0.057347,0.020488,0.010215,-0.026627,0.022513,0.022438,0.035390,-0.021222,0.008282,-0.000370,-0.015991,0.012876,-0.018086,-0.005189,-0.021091,0.012909,-0.008576,-0.008822,0.030579,0.014678,0.017474,0.007798,0.004474,-0.006689,0.023421,0.017912,0.009466,-0.011250,-0.006204,0.008318,-0.038523,0.017134,0.046953,0.005523,0.071625,0.044149,-0.006386,0.009274,-0.010303,-0.023799,0.013101,0.004949,0.000503,-0.025377,0.000579,0.005653,0.013762,-0.033165,0.011962,0.032019,-0.010733,0.074742,-0.045164,-0.069854,0.017152,-0.028895,-0.001318,-0.020144,-0.001435,0.077727,0.008475,0.017214,0.063803,0.022661,-0.019577,-0.089311,0.043187,0.054777,0.003839,0.005617,0.042290,-0.040706,0.034213,-0.018436,0.026248,-0.012017,0.004664,0.009544,0.028976,0.022278,0.015841,0.026391,-0.030021,-0.019719,0.008558,-0.006588,-0.012466,-0.013105,0.000680,-0.040798,0.018813,-0.018854,0.015615,-0.026298,-0.013062,-0.022980,-0.019654,0.003882,0.019574,0.020301,-0.053047,-0.013297,-0.013324,0.043430,-0.020311,-0.004050,-0.017731,-0.008400,-0.063165,-0.008025,0.060144,-0.036648,-0.009352,-0.031417,-0.019358,0.002939,0.015681,0.058795,0.034305,0.025502,0.026523,-0.024327,0.001476,-0.008038,-0.008200,0.018152,0.016015,-0.009222,0.020973,0.008693,-0.047261,0.028264,-0.002850,0.009419,-0.012005,0.004515,-0.010160,-0.031829,-0.005523,0.038707,-0.014279,0.009806,0.004056,-0.009505,0.033001,-0.038354,-0.005477,0.016190,-0.012159,-0.003113,0.007211,-0.049556,0.001332,0.025863,0.002219,0.009790,-0.002899,0.012787,-0.039636,-0.014672,0.012542,-0.026680,-0.057038,-0.038301,-0.031191,-0.025931,0.009650,0.004544,0.035683,-0.013256,0.015054,-0.006507,0.018665,-0.013960,0.023983,0.033370,-0.000121,-0.000184,0.012092,0.023327,0.014000,-0.007482,-0.006610,-0.045891,0.004304,-0.008434,0.004577,-0.039592,0.004910,0.010364,-0.002958,-0.053009,0.008562,-0.002759,0.010717,0.035418,0.017981,0.027449,-0.019751,0.008681,0.023138,-0.009474,-0.030269,0.013652,-0.022735,0.006830,2026-03-05 15:00:00

In [28]:
tg_hourly["datetime_hour"] = tg_hourly["datetime_hour"] + pd.Timedelta(hours=1)

In [29]:
df_final = df_final.merge(tg_hourly, on="datetime_hour", how="left")

In [30]:
df_final.sample(20)

,datetime_hour,region_id,city_latitude,city_longitude,day_temp,day_dew,day_humidity,day_precip,day_precipprob,day_precipcover,day_snow,day_snowdepth,day_windgust,day_windspeed,day_winddir,day_pressure,day_cloudcover,day_solarradiation,day_solarenergy,day_uvindex,day_moonphase,hour_temp,hour_feelslike,hour_humidity,hour_precip,hour_precipprob,hour_snow,hour_windgust,hour_windspeed,hour_winddir,hour_pressure,hour_cloudcover,hour_solarradiation,hour_solarenergy,hour_uvindex,day_conditions_simple_Clear,day_conditions_simple_Cloudy,day_conditions_simple_Rain,day_conditions_simple_Snow,hour_conditions_simple_Clear,hour_conditions_simple_Cloudy,hour_conditions_simple_Rain,hour_conditions_simple_Snow,year,month,day_of_week,hour,city_name,city_timezone,day_datetime,day_sunrise,day_sunset,hour_datetime,region_key,alarm_active,alarm_minutes_in_hour,alarm_lag_1,alarm_lag_3,alarm_lag_6,alarm_lag_12,alarms_in_last_24h,is_weekend,is_night,total_active_alarms_lag1,neighbour_alarms,hours_since_last_alarm,isw_topic_0,isw_topic_1,isw_topic_2,isw_topic_3,isw_topic_4,isw_topic_5,isw_topic_6,isw_topic_7,isw_topic_8,isw_topic_9,isw_topic_10,isw_topic_11,isw_topic_12,isw_topic_13,isw_topic_14,isw_topic_15,isw_topic_16,isw_topic_17,isw_topic_18,isw_topic_19,isw_topic_20,isw_topic_21,isw_topic_22,isw_topic_23,isw_topic_24,isw_topic_25,isw_topic_26,isw_topic_27,isw_topic_28,isw_topic_29,isw_topic_30,isw_topic_31,isw_topic_32,isw_topic_33,isw_topic_34,isw_topic_35,isw_topic_36,isw_topic_37,isw_topic_38,isw_topic_39,isw_topic_40,isw_topic_41,isw_topic_42,isw_topic_43,isw_topic_44,isw_topic_45,isw_topic_46,isw_topic_47,isw_topic_48,isw_topic_49,isw_topic_50,isw_topic_51,isw_topic_52,isw_topic_53,isw_topic_54,isw_topic_55,isw_topic_56,isw_topic_57,isw_topic_58,isw_topic_59,isw_topic_60,isw_topic_61,isw_topic_62,isw_topic_63,isw_topic_64,isw_topic_65,isw_topic_66,isw_topic_67,isw_topic_68,isw_topic_69,isw_topic_70,isw_topic_71,isw_topic_72,isw_topic_73,isw_topic_74,isw_topic_75,isw_topic_76,isw_topic_77,isw_topic_78,isw_topic_79,isw_topic_80,isw_topic_81,isw_topic_82,isw_topic_83,isw_topic_84,isw_topic_85,isw_topic_86,isw_topic_87,isw_topic_88,isw_topic_89,isw_topic_90,isw_topic_91,isw_topic_92,isw_topic_93,isw_topic_94,isw_topic_95,isw_topic_96,isw_topic_97,isw_topic_98,isw_topic_99,isw_topic_100,isw_topic_101,isw_topic_102,isw_topic_103,isw_topic_104,isw_topic_105,isw_topic_106,isw_topic_107,isw_topic_108,isw_topic_109,isw_topic_110,isw_topic_111,isw_topic_112,isw_topic_113,isw_topic_114,isw_topic_115,isw_topic_116,isw_topic_117,isw_topic_118,isw_topic_119,isw_topic_120,isw_topic_121,isw_topic_122,isw_topic_123,isw_topic_124,isw_topic_125,isw_topic_126,isw_topic_127,isw_topic_128,isw_topic_129,isw_topic_130,isw_topic_131,isw_topic_132,isw_topic_133,isw_topic_134,isw_topic_135,isw_topic_136,isw_topic_137,isw_topic_138,isw_topic_139,isw_topic_140,isw_topic_141,isw_topic_142,isw_topic_143,isw_topic_144,isw_topic_145,isw_topic_146,isw_topic_147,isw_topic_148,isw_topic_149,isw_total_intensity,isw_topic_std,isw_topic_max,isw_topic_mean,isw_velocity_24h,isw_intensity_ema,isw_topic_entropy,tg_topic_0,tg_topic_1,tg_topic_2,tg_topic_3,tg_topic_4,tg_topic_5,tg_topic_6,tg_topic_7,tg_topic_8,tg_topic_9,tg_topic_10,tg_topic_11,tg_topic_12,tg_topic_13,tg_topic_14,tg_topic_15,tg_topic_16,tg_topic_17,tg_topic_18,tg_topic_19,tg_topic_20,tg_topic_21,tg_topic_22,tg_topic_23,tg_topic_24,tg_topic_25,tg_topic_26,tg_topic_27,tg_topic_28,tg_topic_29,tg_topic_30,tg_topic_31,tg_topic_32,tg_topic_33,tg_topic_34,tg_topic_35,tg_topic_36,tg_topic_37,tg_topic_38,tg_topic_39,tg_topic_40,tg_topic_41,tg_topic_42,tg_topic_43,tg_topic_44,tg_topic_45,tg_topic_46,tg_topic_47,tg_topic_48,tg_topic_49,tg_topic_50,tg_topic_51,tg_topic_52,tg_topic_53,tg_topic_54,tg_topic_55,tg_topic_56,tg_topic_57,tg_topic_58,tg_topic_59,tg_topic_60,tg_topic_61,tg_topic_62,tg_topic_63,tg_topic_64,tg_topic_65,tg_topic_66,tg_topic_67,tg_topic_68,tg_topic_69,tg_topic_70,tg_topic_71,tg_topic_72,tg_topic_73,tg_topic_74,tg_topic_75,tg_topic_76,tg_topic_77,tg_topic_78,tg_topic_79,tg_topic_80,tg_topic_81,tg_topic_82,tg_topic_83,tg_topic_84,tg_topic_85,tg_topic_86,tg_topic_87,tg_topic_88,tg_topic_89,tg_topic_90,tg_topic_91,tg_topic_92,tg_topic_93,tg_topic_94,tg_topic_95,tg_topic_96,tg_topic_97,tg_topic_98,tg_topic_99,tg_topic_100,tg_topic_101,tg_topic_102,tg_topic_103,tg_topic_104,tg_topic_105,tg_topic_106,tg_topic_107,tg_topic_108,tg_topic_109,tg_topic_110,tg_topic_111,tg_topic_112,tg_topic_113,tg_topic_114,tg_topic_115,tg_topic_116,tg_topic_117,tg_topic_118,tg_topic_119,tg_topic_120,tg_topic_121,tg_topic_122,tg_topic_123,tg_topic_124,tg_topic_125,tg_topic_126,tg_topic_127,tg_topic_128,tg_topic_129,tg_topic_130,tg_topic_131,tg_topic_132,tg_topic_133,tg_topic_134,tg_topic_135,tg_topic_136,tg_topic_137,tg_topic_138,tg_topic_139,tg_topic_140,tg_topic_141,tg_topic_142,tg_topic_143,tg_topic_144,tg_topic_145,tg_topic_146,tg_topic_147,tg_topic_148,tg_topic_149,tg_topic_150,tg_topic_151,tg_topic_152,tg_topic_153,tg_topic_154,tg_topic_155,tg_topic_156,tg_topic_157,tg_topic_158,tg_topic_159,tg_topic_160,tg_topic_161,tg_topic_162,tg_topic_163,tg_topic_164,tg_topic_165,tg_topic_166,tg_topic_167,tg_topic_168,tg_topic_169,tg_topic_170,tg_topic_171,tg_topic_172,tg_topic_173,tg_topic_174,tg_topic_175,tg_topic_176,tg_topic_177,tg_topic_178,tg_topic_179,tg_topic_180,tg_topic_181,tg_topic_182,tg_topic_183,tg_topic_184,tg_topic_185,tg_topic_186,tg_topic_187,tg_topic_188,tg_topic_189,tg_topic_190,tg_topic_191,tg_topic_192,tg_topic_193,tg_topic_194,tg_topic_195,tg_topic_196,tg_topic_197,tg_topic_198,tg_topic_199,tg_topic_200,tg_topic_201,tg_topic_202,tg_topic_203,tg_topic_204,tg_topic_205,tg_topic_206,tg_topic_207,tg_topic_208,tg_topic_209,tg_topic_210,tg_topic_211,tg_topic_212,tg_topic_213,tg_topic_214,tg_topic_215,tg_topic_216,tg_topic_217,tg_topic_218,tg_topic_219,tg_topic_220,tg_topic_221,tg_topic_222,tg_topic_223,tg_topic_224,tg_topic_225,tg_topic_226,tg_topic_227,tg_topic_228,tg_topic_229,tg_topic_230,tg_topic_231,tg_topic_232,tg_topic_233,tg_topic_234,tg_topic_235,tg_topic_236,tg_topic_237,tg_topic_238,tg_topic_239,tg_topic_240,tg_topic_241,tg_topic_242,tg_topic_243,tg_topic_244,tg_topic_245,tg_topic_246,tg_topic_247,tg_topic_248,tg_topic_249
613445,2022-09-29 03:00:00,26,50.45060,30.52430,12.6,9.5,82.2,0.000,0.0,0.00,0.0,0.0,31.0,13.3,155.2,1008.1,78.5,124.2,10.7,5.0,0.10,9.4,9.4,90.35,0.0,0.0,0.0,11.5,3.6,240.0,1006.7,20.2,0.0,0.1,0.0,False,True,False,False,False,True,False,False,2022,9,3,3,Kyiv,Europe/Kiev,2022-09-29,06:54:37,18:41:04,03:00:00,Київ,0,0.000000,0.0,0.0,0.0,0.0,1.0,0,1,7.0,0.0,8,0.708962,-0.223646,0.041807,-0.126327,-0.013630,0.011461,-0.046282,0.035044,0.022211,-0.094898,0.005000,0.028451,0.229762,0.113041,-0.089822,0.194563,-0.114131,0.039046,0.044743,0.008736,-0.008610,0.140929,-0.022338,0.085891,0.045133,0.018447,0.044735,0.055366,0.029875,0.060403,-0.024991,-0.037458,-0.045550,0.010545,-0.012338,-0.065177,-0.046977,-0.066731,-0.049827,-0.016274,-0.002230,0.065400,0.001589,0.101394,0.017536,0.044161,0.042483,0.013486,-0.044953,-0.007267,-0.050328,0.041789,-0.061302,-0.007732,0.013304,-0.023378,0.033596,0.057118,-0.007241,-0.014432,-0.034734,0.047652,0.018050,-0.010932,0.044051,-0.020965,-0.004506,0.010136,0.021133,0.001420,0.011766,0.033160,0.032102,-0.039365,0.010261,-0.026852,0.026053,-0.016135,-0.030255,-0.015492,0.008255,-0.013556,0.000561,-0.069611,-0.009586,0.014141,0.035949,-0.006784,0.002425,0.011132,-0.000883,0.038038,0.010682,-0.021307,0.002961,0.051219,-0.003972,-0.004408,0.020175,0.008132,-0.005538,0.029094,-0.023950,0.008605,-0.015623,-0.030846,0.026367,-0.035479,-0.043203,-0.006158,-0.016276,-0.008259,0.030374,0.038275,-0.026200,0.000903,-0.020867,-0.000085,-0.007229,0.001015,0.019040,0.017665,0.006710,0.063009,-0.017043,0.012439,0.013277,0.015723,-0.026633,-0.006823,-0.026812,-0.003761,0.021847,0.009278,0.008210,-0.023895,0.010216,-0.015928,-0.021992,-0.006816,-0.047122,-0.032205,0.001320,0.003706,0.016591,-0.023811,0.003720,0.009893,0.011388,0.047584,5.437476,0.066525,0.708962,0.036250,0.265503,5.292752,4.326421,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
390258,2024-06-07 15:00:00,17,50.61930,26.25130,19.1,14.9,78.0,0.395,100.0,4.17,0.0,0.0,38.9,18.0,238.7,1016.2,75.1,198.5,17.2,7.0,0.03,23.7,23.7,59.69,0.0,0.0,0.0,38.5,18.0,260.0,1015.0,90.0,372.0,1.3,4.0,False,False,True,False,False,True,False,False,2024,6,4,15,Rivne,Europe/Kiev,2024-06-07,05:04:12,21:24:16,15:00:00,Рівненська,0,0.000000,0.0,0.0,0.0,1.0,2.0,0,0,6.0,0.0,10,0.756149,0.012099,-0.105112,0.130139,-0.111108,0.055081,0.078600,-0.091731,-0.043876,0.014086,-0.079170,0.264795,-0.011797,0.008675,-0.156030,-0.039616,0.009217,-0.080579,0.040129,0.076458,0.032807,-0.082952,0.020218,-0.013487,0.029705,-0.036406,-0.055041,0.026188,-0.034492,0.007298,-0.039510,-0.025131,-0.017228,0.030278,-0.000495,-0.003754,0.007357,-0.000336,-0.033256,-0.009486,-0.052130,-0.063536,0.032215,0.033579,-0.026276,-0.001211,0.004495,0.002951,0.026879,0.003901,-0.011587,-0.012485,0.022747,-0.021422,0.022759,-0.075439,-0.009490,-0.042598,-0.035800,0.002927,-0.030996,0.003847,0.047734,-0.006784,-0.031448,-0.026988,0.027833,0.010506,0.042837,0.015557,-0.018976,-0.000964,0.044695,-0.013336,0.005962,-0.036364,0.004010,0.003832,0.027109,-0.011078,0.016812,0.013121,-0.011935,0.015699,0.048737,0.005265,0.045857,-0.046005,-0.013794,0.034734,-0.005517,0.001126,-0.008172,-0.053657,-0.010512,-0.023709,0.041328,0.004271,-0.009439,0.003017,0.000444,0.011027,-0.028816,0.015412,0.001559,-0.016321,-0.001259,0.019680,0.011636,-0.002870,-0.002380,-0.002712,0.009061,-0.019849,-0.009835,0.000321,-0.006628,0.019158,-0.073540,-0.010135,-0.014409,0.012663,-0.010192,-0.008207,0.034542,-0.016544,0.027595,-0.013795,-0.026156,0.034427,-0.069713,-0.014277,0.016611,0.008392,0.014765,0.060215,0.011855,-0.001232,-0.006221,0.017701,-0.004741,0.000698,0.001160,-0.002185,-0.020826,0.001912,0.012394,0.005383,-0.028223,0.044567,4.802108,0.068043,0.756149,0.032014,0.312616,4.722129,4.220162,0.267395,-0.168014,-0.035316,0.026590,-0.004497,0.018684,0.022810,0.119542,-0.004028,-0.012593,-0.008563,-0.011964,-0.010398,0.048605,-0.000205,0.080369,0.082995,0.037532,-0.036983,0.057266,-0.010712,-0.058209,0.067151,0.006344,-0.036341,-0.010285,-0.009060,-0.094517,-0.054598,0.003736,0.010735,-0.000755,0.019622,-0.026407,0.000669,0.001828,0.034305,-0.042733,-0.016564,-0.019945,0.014309,0.002394,-0.008100,0.004433,0.026966,-0.023540,-0.009571,0.001152,0.036426,0.023853,0.003523,-0.009666,-0.020996,0.046571,0.008767,0.008907,-0.009458,0.025178,0.021314,-0.009575,-0.027839,-0.004191,0.013619,-0.005413,0.010751,-0.029676,-0.018198,0.011292,-0.027308,-0.004337,-0.012205,-0.016914,0.022213,-0.033083,-0.015173,0.020821,0.001036,-0.002463,-0.006631,0.024966,-0.013803,-0.020975,0.002011,0.005114,0.004662,0.004635,0.014959,0.007256,-0.013814,0.007716,0.004370,0.006876,0.002028,0.023397,-0.013026,-0.046059,-0.025372,0.033919,0.028875,-0.028733,-0.020915,-0.017314,0.024204,-0.011630,0.009858,0.007571,-0.012477,-0.019307,0.013439,-0.003725,-0.006474,0.003221,0.006040,-0.003797,-0.005476,0.009349,-0.006589,-0.006372,-0.013865,0.003687,0.000148,0.004210,-0.000533,0.029430,-0.005400,-0.005604,-0.012295,0.002014,0.022010,0.021854,-0.009430,0.011979,-0.003263,0.019281,-0.001214,0.006940,-0.007728,-0.047489,-0.022898,0.013591,0.012547,0.019351,0.060327,0.025144,0.013237,0.001974,0.037143,0.025407,0.016355,0.000961,0.019984,0.002536,-0.002283,-0.012156,0.016339,0.048644,0.001895,-0.004646,-0.014797,-0.014858,-0.017089,0.002400,0.004351,-0.005031,0.010900,-0.005324,0.000176,0.010398,0.007555,-0.000352,-0.002749,-0.002809,0.002611,-0.008521,-0.006901,0.002898,-0.003784,0.000623,0.006419,-0.001730,0.007205,-0.005981,-0.004009,0.007903,0.008977,0.000160,0.004815,-0.007337,-0.010563,0.006585,0.011074,-0.009155,-0.019282,0.006720,-0.000521,0.007464,-0.006059,-0.004323,0.014182,-0.005650,0.000376,0.001318,-0.002819,0.003500,-0.006178,0.002922,0.007005,0.001610,0.000105,-0.008529,-0.006566,-0.014401,0.000603,-0.008795,-0.007995,-0.004298,0.007449,0.003448,-0.002141,-0.005849,0.006157,0.000176,-0.005955,-0.004857,0.005706,0.002473,0.000512,0.001078,-0.010502,0.004975,-0.005218,-0.003186,-0.001438,-0.007766,0.004524,-0.004477,0.000391,0.001801,-0.011121,0.002431,-0.007561,-0.001630,-0.001545,0.003244,0.002640,0.005070,-0.001055,-0.008769,0.005335,0.004112
466591,2024-02-03 12:00:00,20,50.00420,36.23580,-1.2,-2.7,89.8,3.000,100.0,4.17,1.8,2.3,50.4,21.6,249.2,1004.8,82.8,30.7,2.6,2.0,0.75,0.0,-5.5,86.39,0.0,0.0,0.0,39.6,21.6,250.0,1004.0,88.0,158.8,0.6,2.0,False,False,False,True,False,True,False,False,2024,2,5,12,Kharkiv,Europe/Kiev,2024-02-03,07:06:44,16:31:37,12:00:00,Харківська,1,21.316667,1.0,0.0,1.0,1.0,15.0,1,0,24.0,4.0,0,0.810169,-0.031656,-0.210893,0.117646,0.077905,0.014679,-0.026275,0.005603,0.014858,-0.009708,-0.048416,0.032634,0.181211,-0.178856,-0.007891,-0.044739,0.032428,0.017758,0.008678,-0.036659,-0.027940,0.005046,-0.031281,0.002100,-0.024808,0.083623,-0.004584,-0.000793,0.031576,0.029509,0.028017,0.013000,0.050394,0.026734,0.001564,-0.028757,-0.030638,0.103830,-0.028882,-0.009643,0.032050,-0.018168,-0.029315,-0.012144,0.006457,-0.026811,0.041376,0.025428,-0.054575,0.010427,0.019174,-0.025628,0.008365,-0.009720,0.008659,0.034099,0.062035,-0.015871,-0.008289,-0.015040,0.025673,0.012928,0.008205,-0.055699,-0.043803,0.015676,-0.000849,0.010636,0.005128,-0.010749,-0.012958,0.043027,0.002128,-0.010733,0.015148,0.000946,0.019211,-0.027169,0.015653,-0.018600,-0.029631,-0.012712,0.006218,0.005431,-0.003805,0.005580,0.009343,-0.006236,0.028259,0.015132,0.009174,-0.027835,-0.000454,0.006093,-0.026668,-0.000987,-0.001772,0.022362,-0.002272,-0.006977,-0.005253,0.014912,0.009025,0.005261,0.025519,0.005018,-0.012917,-0.035000,-0.021536,-0.001900,0.016333,0.004937,-0.023613,0.009159,0.015749,-0.030409,0.016703,0.000628,0.016041,0.010495,-0.002018,0.017612,0.016959,0.017420,-0.011259,-0.028129,-0.007130,-0.029181,0.003872,0.014853,0.012358,0.022989,-0.029690,0.002307,0.029822,0.029710,-0.013887,0.019364,0.022643,0.003344,0.007686,0.008430,0.012447,0.027414,0.047415,0.023414,-0.017249,0.009891,-0.008721,0.054226,4.348716,0.070930,0.810169,0.028991,-1.213474,4.761075,4.153619,0.281614,0.431911,-0.148914,0.233774,0.192273,0.156878,-0.039552,0.065903,-0.060449,0.107884,0.001709,-0.007036,0.002199,0.054100,0.031158,0.070830,0.075086,0.013644,-0.035741,0.001734,-0.051601,-0.036535,-0.017983,0.054344,0.000575,0.014916,-0.004797,-0.002105,0.033070,-0.005019,-0.010556,0.009388,0.031415,-0.033522,0.022507,-0.015276,-0.000976,0.001579,-0.027114,0.022827,-0.014221,-0.003886,0.019765,0.002281,-0.014901,-0.018946,-0.021734,0.006024,0.037499,-0.008680,0.036644,-0.019683,-0.004944,-0.032140,0.040293,0.001455,-0.004247,-0.005862,0.031772,-0.007703,0.017629,-0.013943,-0.022355,0.047937,0.007515,-0.015123,0.040945,0.024379,-0.002777,-0.008460,-0.003418,0.010971,-0.023678,0.000314,-0.000611,0.008584,0.023290,0.043174,-0.001744,0.010384,0.010804,-0.003908,-0.002206,0.000298,0.004208,0.001567,-0.002066,-0.007808,-0.006055,0.002067,0.007694,0.001756,-0.001242,-0.006710,0.002422,-0.002203,-0.005087,0.004869,-0.006504,0.005525,0.008590,-0.015430,-0.005633,0.018129,0.010092,0.003180,0.006760,0.005785,-0.026128,-0.005100,-0.001256,-0.004143,-0.021963,0.007683,-0.007727,0.005952,-0.027200,0.001767,-0.012312,0.003933,-0.012897,-0.002797,-0.011575,-0.009930,0.015605,-0.005541,-0.013098,0.003441,-0.004758,-0.007371,0.002284,0.004740,0.008975,-0.006621,0.002517,-0.010044,0.013736,-0.003074,-0.015890,0.021008,0.022286,0.000112,-0.015150,0.000908,0.004676,0.006594,0.010273,0.000768,-0.002925,-0.013583,-0.010783,-0.012981,0.004643,0.002960,0.006162,-0.003567,-0.008298,0.003882,-0.007498,-0.006223,-0.003418,-0.004610,0.005489,-0.002909,0.021537,0.008110,0.018547,-0.010389,-0.007144,-0.020469,0.009968,0.007432,-0.006697,-0.000034,-0.021190,-0.010443,0.008430,-0.017337,-0.000177,-0.002757,-0.002568,-0.001918,0.007739,0.012731,0.006036,-0.007451,0.019059,-0.017719,-0.001225,0.011715,0.000914,-0.006483,0.011006,0.003123,0.014688,0.016898,0.004222,0.009337,0.015093,-0.002325,0.009129,-0.003128,0.026397,-0.000771,0.003201,0.014355,-0.003661,0.016345,-0.024623,0.006487,0.004358,0.000972,-0.012828,-0.006931,-0.010723,0.019857,0.003649,-0.012559,0.006071,-0.004188,0.009705,-0.000008,0.022016,0.000981,0.003404,0.008082,-0.007362,-0.010524,0.028780,0.017768,-0.018107,0.006474,0.001574,0.018469,0.007205,0.007166,-0.019772,0.000332,0.010797,0.009841,-0.017495,-0.025042,-0.029184,-0.026524,0.018977,-0.014461,0.006750,0.000528,-0.001379,-0.004031

In [31]:
df_final.shape

(634680, 473)

In [32]:
df_final = df_final.sort_values(["datetime_hour"])

In [33]:
with pd.option_context('display.max_rows', None):
    print(df_final.isnull().sum())

datetime_hour                         0
region_id                             0
city_latitude                         0
city_longitude                        0
day_temp                              0
day_dew                               0
day_humidity                          0
day_precip                            0
day_precipprob                        0
day_precipcover                       0
day_snow                              0
day_snowdepth                         0
day_windgust                          0
day_windspeed                         0
day_winddir                           0
day_pressure                          0
day_cloudcover                        0
day_solarradiation                    0
day_solarenergy                       0
day_uvindex                           0
day_moonphase                         0
hour_temp                             0
hour_feelslike                        0
hour_humidity                         0
hour_precip                           0
hour_precipprob                       0
hour_snow                             0
hour_windgust                         0
hour_windspeed                        0
hour_winddir                          0
hour_pressure                         0
hour_cloudcover                       0
hour_solarradiation                   0
hour_solarenergy                      0
hour_uvindex                          0
day_conditions_simple_Clear           0
day_conditions_simple_Cloudy          0
day_conditions_simple_Rain            0
day_conditions_simple_Snow            0
hour_conditions_simple_Clear          0
hour_conditions_simple_Cloudy         0
hour_conditions_simple_Rain           0
hour_conditions_simple_Snow           0
year                                  0
month                                 0
day_of_week                           0
hour                                  0
city_name                             0
city_timezone                         0
day_datetime                          0
day_sunrise                           0
day_sunset                            0
hour_datetime                         0
region_key                            0
alarm_active                          0
alarm_minutes_in_hour                 0
alarm_lag_1                           0
alarm_lag_3                           0
alarm_lag_6                           0
alarm_lag_12                          0
alarms_in_last_24h                    0
is_weekend                            0
is_night                              0
total_active_alarms_lag1              0
neighbour_alarms                      0
hours_since_last_alarm                0
isw_topic_0                           0
isw_topic_1                           0
isw_topic_2                           0
isw_topic_3                           0
isw_topic_4                           0
isw_topic_5                           0
isw_topic_6                           0
isw_topic_7                           0
isw_topic_8                           0
isw_topic_9                           0
isw_topic_10                          0
isw_topic_11                          0
isw_topic_12                          0
isw_topic_13                          0
isw_topic_14                          0
isw_topic_15                          0
isw_topic_16                          0
isw_topic_17                          0
isw_topic_18                          0
isw_topic_19                          0
isw_topic_20                          0
isw_topic_21                          0
isw_topic_22                          0
isw_topic_23                          0
isw_topic_24                          0
isw_topic_25                          0
isw_topic_26                          0
isw_topic_27                          0
isw_topic_28                          0
isw_topic_29                          0
isw_topic_30                          0
isw_topic_31                          0
isw_topic_32                          0
isw_topic_33                          0
isw_topic_34                          0
isw_topic_35                          0
isw_topic_36                          0
isw_topic_37                          0
isw_topic_38                          0
isw_topic_39                          0
isw_topic_40                          0
isw_topic_41                          0
isw_topic_42                          0
isw_topic_43                          0
isw_topic_44                          0
isw_topic_45                          0
isw_topic_46                          0
isw_topic_47                          0
isw_topic_48                          0
isw_topic_49                          0
isw_topic_50                          0
isw_topic_51                          0
isw_topic_52                          0
isw_topic_53                          0
isw_topic_54                          0
isw_topic_55                          0
isw_topic_56                          0
isw_topic_57                          0
isw_topic_58                          0
isw_topic_59                          0
isw_topic_60                          0
isw_topic_61                          0
isw_topic_62                          0
isw_topic_63                          0
isw_topic_64                          0
isw_topic_65                          0
isw_topic_66                          0
isw_topic_67                          0
isw_topic_68                          0
isw_topic_69                          0
isw_topic_70                          0
isw_topic_71                          0
isw_topic_72                          0
isw_topic_73                          0
isw_topic_74                          0
isw_topic_75                          0
isw_topic_76                          0
isw_topic_77                          0
isw_topic_78                          0
isw_topic_79                          0
isw_topic_80                          0
isw_topic_81                          0
isw_topic_82                          0
isw_topic_83                          0
isw_topic_84                          0
isw_topic_85                          0
isw_topic_86                          0
isw_topic_87                          0
isw_topic_88                          0
isw_topic_89                          0
isw_topic_90                          0
isw_topic_91                          0
isw_topic_92                          0
isw_topic_93                          0
isw_topic_94                          0
isw_topic_95                          0
isw_topic_96                          0
isw_topic_97                          0
isw_topic_98                          0
isw_topic_99                          0
isw_topic_100                         0
isw_topic_101                         0
isw_topic_102                         0
isw_topic_103                         0
isw_topic_104                         0
isw_topic_105                         0
isw_topic_106                         0
isw_topic_107                         0
isw_topic_108                         0
isw_topic_109                         0
isw_topic_110                         0
isw_topic_111                         0
isw_topic_112                         0
isw_topic_113                         0
isw_topic_114                         0
isw_topic_115                         0
isw_topic_116                         0
isw_topic_117                         0
isw_topic_118                         0
isw_topic_119                         0
isw_topic_120                         0
isw_topic_121                         0
isw_topic_122                         0
isw_topic_123                         0
isw_topic_124                         0
isw_topic_125                         0
isw_topic_126                         0
isw_topic_127                         0
isw_topic_128                         0
isw_topic_129                         0
isw_topic_130                         0
isw_topic_131                         0
isw_topic_132                         0
isw_topic_133                         0
isw_topic_134                         0
isw_topic_135                         0
isw_topic_136                         0
isw_topic_137                         0
isw_topic_138                         0
isw_topic_139                         0
isw_topic_140                         0
isw_topic_141                         0
isw_topic_142                         0
isw_topic_143                         0
isw_topic_144                         0
isw_topic_145                         0
isw_topic_146                         0
isw_topic_147                         0
isw_topic_148                         0
isw_topic_149                         0
isw_total_intensity                   0
isw_topic_std                         0
isw_topic_max                         0
isw_topic_mean                        0
isw_velocity_24h                      0
isw_intensity_ema                     0
isw_topic_entropy                     0
tg_topic_0                       121656
tg_topic_1                       121656
tg_topic_2                       121656
tg_topic_3                       121656
tg_topic_4                       121656
tg_topic_5                       121656
tg_topic_6                       121656
tg_topic_7                       121656
tg_topic_8                       121656
tg_topic_9                       121656
tg_topic_10                      121656
tg_topic_11                      121656
tg_topic_12                      121656
tg_topic_13                      121656
tg_topic_14                      121656
tg_topic_15                      121656
tg_topic_16                      121656
tg_topic_17                      121656
tg_topic_18                      121656
tg_topic_19                      121656
tg_topic_20                      121656
tg_topic_21                      121656
tg_topic_22                      121656
tg_topic_23                      121656
tg_topic_24                      121656
tg_topic_25                      121656
tg_topic_26                      121656
tg_topic_27                      121656
tg_topic_28                      121656
tg_topic_29                      121656
tg_topic_30                      121656
tg_topic_31                      121656
tg_topic_32                      121656
tg_topic_33                      121656
tg_topic_34                      121656
tg_topic_35                      121656
tg_topic_36                      121656
tg_topic_37                      121656
tg_topic_38                      121656
tg_topic_39                      121656
tg_topic_40                      121656
tg_topic_41                      121656
tg_topic_42                      121656
tg_topic_43                      121656
tg_topic_44                      121656
tg_topic_45                      121656
tg_topic_46                      121656
tg_topic_47                      121656
tg_topic_48                      121656
tg_topic_49                      121656
tg_topic_50                      121656
tg_topic_51                      121656
tg_topic_52                      121656
tg_topic_53                      121656
tg_topic_54                      121656
tg_topic_55                      121656
tg_topic_56                      121656
tg_topic_57                      121656
tg_topic_58                      121656
tg_topic_59                      121656
tg_topic_60                      121656
tg_topic_61                      121656
tg_topic_62                      121656
tg_topic_63                      121656
tg_topic_64                      121656
tg_topic_65                      121656
tg_topic_66                      121656
tg_topic_67                      121656
tg_topic_68                      121656
tg_topic_69                      121656
tg_topic_70                      121656
tg_topic_71                      121656
tg_topic_72                      121656
tg_topic_73                      121656
tg_topic_74                      121656
tg_topic_75                      121656
tg_topic_76                      121656
tg_topic_77                      121656
tg_topic_78                      121656
tg_topic_79                      121656
tg_topic_80                      121656
tg_topic_81                      121656
tg_topic_82                      121656
tg_topic_83                      121656
tg_topic_84                      121656
tg_topic_85                      121656
tg_topic_86                      121656
tg_topic_87                      121656
tg_topic_88                      121656
tg_topic_89                      121656
tg_topic_90                      121656
tg_topic_91                      121656
tg_topic_92                      121656
tg_topic_93                      121656
tg_topic_94                      121656
tg_topic_95                      121656
tg_topic_96                      121656
tg_topic_97                      121656
tg_topic_98                      121656
tg_topic_99                      121656
tg_topic_100                     121656
tg_topic_101                     121656
tg_topic_102                     121656
tg_topic_103                     121656
tg_topic_104                     121656
tg_topic_105                     121656
tg_topic_106                     121656
tg_topic_107                     121656
tg_topic_108                     121656
tg_topic_109                     121656
tg_topic_110                     121656
tg_topic_111                     121656
tg_topic_112                     121656
tg_topic_113                     121656
tg_topic_114                     121656
tg_topic_115                     121656
tg_topic_116                     121656
tg_topic_117                     121656
tg_topic_118                     121656
tg_topic_119                     121656
tg_topic_120                     121656
tg_topic_121                     121656
tg_topic_122                     121656
tg_topic_123                     121656
tg_topic_124                     121656
tg_topic_125                     121656
tg_topic_126                     121656
tg_topic_127                     121656
tg_topic_128                     121656
tg_topic_129                     121656
tg_topic_130                     121656
tg_topic_131                     121656
tg_topic_132                     121656
tg_topic_133                     121656
tg_topic_134                     121656
tg_topic_135                     121656
tg_topic_136                     121656
tg_topic_137                     121656
tg_topic_138                     121656
tg_topic_139                     121656
tg_topic_140                     121656
tg_topic_141                     121656
tg_topic_142                     121656
tg_topic_143                     121656
tg_topic_144                     121656
tg_topic_145                     121656
tg_topic_146                     121656
tg_topic_147                     121656
tg_topic_148                     121656
tg_topic_149                     121656
tg_topic_150                     121656
tg_topic_151                     121656
tg_topic_152                     121656
tg_topic_153                     121656
tg_topic_154                     121656
tg_topic_155                     121656
tg_topic_156                     121656
tg_topic_157                     121656
tg_topic_158                     121656
tg_topic_159                     121656
tg_topic_160                     121656
tg_topic_161                     121656
tg_topic_162                     121656
tg_topic_163                     121656
tg_topic_164                     121656
tg_topic_165                     121656
tg_topic_166                     121656
tg_topic_167                     121656
tg_topic_168                     121656
tg_topic_169                     121656
tg_topic_170                     121656
tg_topic_171                     121656
tg_topic_172                     121656
tg_topic_173                     121656
tg_topic_174                     121656
tg_topic_175                     121656
tg_topic_176                     121656
tg_topic_177                     121656
tg_topic_178                     121656
tg_topic_179                     121656
tg_topic_180                     121656
tg_topic_181                     121656
tg_topic_182                     121656
tg_topic_183                     121656
tg_topic_184                     121656
tg_topic_185                     121656
tg_topic_186                     121656
tg_topic_187                     121656
tg_topic_188                     121656
tg_topic_189                     121656
tg_topic_190                     121656
tg_topic_191                     121656
tg_topic_192                     121656
tg_topic_193                     121656
tg_topic_194                     121656
tg_topic_195                     121656
tg_topic_196                     121656
tg_topic_197                     121656
tg_topic_198                     121656
tg_topic_199                     121656
tg_topic_200                     121656
tg_topic_201                     121656
tg_topic_202                     121656
tg_topic_203                     121656
tg_topic_204                     121656
tg_topic_205                     121656
tg_topic_206                     121656
tg_topic_207                     121656
tg_topic_208                     121656
tg_topic_209                     121656
tg_topic_210                     121656
tg_topic_211                     121656
tg_topic_212                     121656
tg_topic_213                     121656
tg_topic_214                     121656
tg_topic_215                     121656
tg_topic_216                     121656
tg_topic_217                     121656
tg_topic_218                     121656
tg_topic_219                     121656
tg_topic_220                     121656
tg_topic_221                     121656
tg_topic_222                     121656
tg_topic_223                     121656
tg_topic_224                     121656
tg_topic_225                     121656
tg_topic_226                     121656
tg_topic_227                     121656
tg_topic_228                     121656
tg_topic_229                     121656
tg_topic_230                     121656
tg_topic_231                     121656
tg_topic_232                     121656
tg_topic_233                     121656
tg_topic_234                     121656
tg_topic_235                     121656
tg_topic_236                     121656
tg_topic_237                     121656
tg_topic_238                     121656
tg_topic_239                     121656
tg_topic_240                     121656
tg_topic_241                     121656
tg_topic_242                     121656
tg_topic_243                     121656
tg_topic_244                     121656
tg_topic_245                     121656
tg_topic_246                     121656
tg_topic_247                     121656
tg_topic_248                     121656
tg_topic_249                     121656
dtype: int64

In [34]:
df_final = df_final.fillna(0)

In [35]:
tg_cols = [c for c in df_final.columns if 'tg_topic_' in c]
df_tg_abs = df_final[tg_cols].abs()

df_final['tg_total_intensity'] = df_tg_abs.sum(axis=1)
df_final['tg_topic_std'] = df_tg_abs.std(axis=1)
df_final['tg_topic_max'] = df_tg_abs.max(axis=1)
df_final['tg_topic_entropy'] = -(df_tg_abs.div(df_tg_abs.sum(axis=1), axis=0) * np.log(df_tg_abs.div(df_tg_abs.sum(axis=1), axis=0) + 1e-9)).sum(axis=1)

In [36]:
df_final.head(20)

,datetime_hour,region_id,city_latitude,city_longitude,day_temp,day_dew,day_humidity,day_precip,day_precipprob,day_precipcover,day_snow,day_snowdepth,day_windgust,day_windspeed,day_winddir,day_pressure,day_cloudcover,day_solarradiation,day_solarenergy,day_uvindex,day_moonphase,hour_temp,hour_feelslike,hour_humidity,hour_precip,hour_precipprob,hour_snow,hour_windgust,hour_windspeed,hour_winddir,hour_pressure,hour_cloudcover,hour_solarradiation,hour_solarenergy,hour_uvindex,day_conditions_simple_Clear,day_conditions_simple_Cloudy,day_conditions_simple_Rain,day_conditions_simple_Snow,hour_conditions_simple_Clear,hour_conditions_simple_Cloudy,hour_conditions_simple_Rain,hour_conditions_simple_Snow,year,month,day_of_week,hour,city_name,city_timezone,day_datetime,day_sunrise,day_sunset,hour_datetime,region_key,alarm_active,alarm_minutes_in_hour,alarm_lag_1,alarm_lag_3,alarm_lag_6,alarm_lag_12,alarms_in_last_24h,is_weekend,is_night,total_active_alarms_lag1,neighbour_alarms,hours_since_last_alarm,isw_topic_0,isw_topic_1,isw_topic_2,isw_topic_3,isw_topic_4,isw_topic_5,isw_topic_6,isw_topic_7,isw_topic_8,isw_topic_9,isw_topic_10,isw_topic_11,isw_topic_12,isw_topic_13,isw_topic_14,isw_topic_15,isw_topic_16,isw_topic_17,isw_topic_18,isw_topic_19,isw_topic_20,isw_topic_21,isw_topic_22,isw_topic_23,isw_topic_24,isw_topic_25,isw_topic_26,isw_topic_27,isw_topic_28,isw_topic_29,isw_topic_30,isw_topic_31,isw_topic_32,isw_topic_33,isw_topic_34,isw_topic_35,isw_topic_36,isw_topic_37,isw_topic_38,isw_topic_39,isw_topic_40,isw_topic_41,isw_topic_42,isw_topic_43,isw_topic_44,isw_topic_45,isw_topic_46,isw_topic_47,isw_topic_48,isw_topic_49,isw_topic_50,isw_topic_51,isw_topic_52,isw_topic_53,isw_topic_54,isw_topic_55,isw_topic_56,isw_topic_57,isw_topic_58,isw_topic_59,isw_topic_60,isw_topic_61,isw_topic_62,isw_topic_63,isw_topic_64,isw_topic_65,isw_topic_66,isw_topic_67,isw_topic_68,isw_topic_69,isw_topic_70,isw_topic_71,isw_topic_72,isw_topic_73,isw_topic_74,isw_topic_75,isw_topic_76,isw_topic_77,isw_topic_78,isw_topic_79,isw_topic_80,isw_topic_81,isw_topic_82,isw_topic_83,isw_topic_84,isw_topic_85,isw_topic_86,isw_topic_87,isw_topic_88,isw_topic_89,isw_topic_90,isw_topic_91,isw_topic_92,isw_topic_93,isw_topic_94,isw_topic_95,isw_topic_96,isw_topic_97,isw_topic_98,isw_topic_99,isw_topic_100,isw_topic_101,isw_topic_102,isw_topic_103,isw_topic_104,isw_topic_105,isw_topic_106,isw_topic_107,isw_topic_108,isw_topic_109,isw_topic_110,isw_topic_111,isw_topic_112,isw_topic_113,isw_topic_114,isw_topic_115,isw_topic_116,isw_topic_117,isw_topic_118,isw_topic_119,isw_topic_120,isw_topic_121,isw_topic_122,isw_topic_123,isw_topic_124,isw_topic_125,isw_topic_126,isw_topic_127,isw_topic_128,isw_topic_129,isw_topic_130,isw_topic_131,isw_topic_132,isw_topic_133,isw_topic_134,isw_topic_135,isw_topic_136,isw_topic_137,isw_topic_138,isw_topic_139,isw_topic_140,isw_topic_141,isw_topic_142,isw_topic_143,isw_topic_144,isw_topic_145,isw_topic_146,isw_topic_147,isw_topic_148,isw_topic_149,isw_total_intensity,isw_topic_std,isw_topic_max,isw_topic_mean,isw_velocity_24h,isw_intensity_ema,isw_topic_entropy,tg_topic_0,tg_topic_1,tg_topic_2,tg_topic_3,tg_topic_4,tg_topic_5,tg_topic_6,tg_topic_7,tg_topic_8,tg_topic_9,tg_topic_10,tg_topic_11,tg_topic_12,tg_topic_13,tg_topic_14,tg_topic_15,tg_topic_16,tg_topic_17,tg_topic_18,tg_topic_19,tg_topic_20,tg_topic_21,tg_topic_22,tg_topic_23,tg_topic_24,tg_topic_25,tg_topic_26,tg_topic_27,tg_topic_28,tg_topic_29,tg_topic_30,tg_topic_31,tg_topic_32,tg_topic_33,tg_topic_34,tg_topic_35,tg_topic_36,tg_topic_37,tg_topic_38,tg_topic_39,tg_topic_40,tg_topic_41,tg_topic_42,tg_topic_43,tg_topic_44,tg_topic_45,tg_topic_46,tg_topic_47,tg_topic_48,tg_topic_49,tg_topic_50,tg_topic_51,tg_topic_52,tg_topic_53,tg_topic_54,tg_topic_55,tg_topic_56,tg_topic_57,tg_topic_58,tg_topic_59,tg_topic_60,tg_topic_61,tg_topic_62,tg_topic_63,tg_topic_64,tg_topic_65,tg_topic_66,tg_topic_67,tg_topic_68,tg_topic_69,tg_topic_70,tg_topic_71,tg_topic_72,tg_topic_73,tg_topic_74,tg_topic_75,tg_topic_76,tg_topic_77,tg_topic_78,tg_topic_79,tg_topic_80,tg_topic_81,tg_topic_82,tg_topic_83,tg_topic_84,tg_topic_85,tg_topic_86,tg_topic_87,tg_topic_88,tg_topic_89,tg_topic_90,tg_topic_91,tg_topic_92,tg_topic_93,tg_topic_94,tg_topic_95,tg_topic_96,tg_topic_97,tg_topic_98,tg_topic_99,tg_topic_100,tg_topic_101,tg_topic_102,tg_topic_103,tg_topic_104,tg_topic_105,tg_topic_106,tg_topic_107,tg_topic_108,tg_topic_109,tg_topic_110,tg_topic_111,tg_topic_112,tg_topic_113,tg_topic_114,tg_topic_115,tg_topic_116,tg_topic_117,tg_topic_118,tg_topic_119,tg_topic_120,tg_topic_121,tg_topic_122,tg_topic_123,tg_topic_124,tg_topic_125,tg_topic_126,tg_topic_127,tg_topic_128,tg_topic_129,tg_topic_130,tg_topic_131,tg_topic_132,tg_topic_133,tg_topic_134,tg_topic_135,tg_topic_136,tg_topic_137,tg_topic_138,tg_topic_139,tg_topic_140,tg_topic_141,tg_topic_142,tg_topic_143,tg_topic_144,tg_topic_145,tg_topic_146,tg_topic_147,tg_topic_148,tg_topic_149,tg_topic_150,tg_topic_151,tg_topic_152,tg_topic_153,tg_topic_154,tg_topic_155,tg_topic_156,tg_topic_157,tg_topic_158,tg_topic_159,tg_topic_160,tg_topic_161,tg_topic_162,tg_topic_163,tg_topic_164,tg_topic_165,tg_topic_166,tg_topic_167,tg_topic_168,tg_topic_169,tg_topic_170,tg_topic_171,tg_topic_172,tg_topic_173,tg_topic_174,tg_topic_175,tg_topic_176,tg_topic_177,tg_topic_178,tg_topic_179,tg_topic_180,tg_topic_181,tg_topic_182,tg_topic_183,tg_topic_184,tg_topic_185,tg_topic_186,tg_topic_187,tg_topic_188,tg_topic_189,tg_topic_190,tg_topic_191,tg_topic_192,tg_topic_193,tg_topic_194,tg_topic_195,tg_topic_196,tg_topic_197,tg_topic_198,tg_topic_199,tg_topic_200,tg_topic_201,tg_topic_202,tg_topic_203,tg_topic_204,tg_topic_205,tg_topic_206,tg_topic_207,tg_topic_208,tg_topic_209,tg_topic_210,tg_topic_211,tg_topic_212,tg_topic_213,tg_topic_214,tg_topic_215,tg_topic_216,tg_topic_217,tg_topic_218,tg_topic_219,tg_topic_220,tg_topic_221,tg_topic_222,tg_topic_223,tg_topic_224,tg_topic_225,tg_topic_226,tg_topic_227,tg_topic_228,tg_topic_229,tg_topic_230,tg_topic_231,tg_topic_232,tg_topic_233,tg_topic_234,tg_topic_235,tg_topic_236,tg_topic_237,tg_topic_238,tg_topic_239,tg_topic_240,tg_topic_241,tg_topic_242,tg_topic_243,tg_topic_244,tg_topic_245,tg_topic_246,tg_topic_247,tg_topic_248,tg_topic_249,tg_total_intensity,tg_topic_std,tg_topic_max,tg_topic_entropy
0,2022-02-24,2,49.23360,28.44860,2.8,-0.3,80.5,0.300,100.0,4.17,0.0,0.0,27.7,10.8,312.0,1023.4,82.5,60.4,5.4,3.0,0.77,2.1,-0.5,91.76,0.0,0.0,0.0,16.6,8.6,279.6,1021.0,91.1,0.0,0.1,0.0,False,False,False,True,False,True,False,False,2022,2,3,0,Vinnytsia,Europe/Kiev,2022-02-24,06:58:49,17:40:52,00:00:00,Вінницька,0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-0.0
581790,2022-02-24,25,51.49370,31.29440,2.4,-0.1,83.8,0.300,100.0,12.50,0.0,0.0,19.8,7.2,195.1,1022.8,95.9,81.5,7.2,3.0,0.77,0.6,-1.8,76.81,0.1,100.0,0.0,12.6,7.2,181.5,1019.0,98.5,0.0,0.1,0.0,False,False,False,True,False,False,False,True,2022,2,3,0,Chernihiv,Europe/Kiev,2022-02-24,06:50:57,17:26:01,00:00:00,Чернігівська,0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-0.0
52890,2022-02-24,4,48.47530,35.01600,3.1,-2.2,70.6,0.000,0.0,0.00,0.0,0.0,28.4,21.6,2.5,1021.9,53.6,148.8,13.1,4.0,0.77,2.0,-1.1,80.51,0.0,0.0,0.0,9.7,10.8,4.0,1019.0,14.1,0.0,0.1,0.0,False,True,False,False,True,False,False,False,2022,2,3,0,Dnipro,Europe/Kiev,2022-02-24,06:31:28,17:15:39,00:00:00,Дніпропетровська,0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-0.0
555345,2022-02-24,24,48.29240,25.93550,3.4,-0.8,74.9,0.008,100.0,8.33,0.0,0.0,28.8,17.9,303.3,1024.3,61.9,59.1,4.1,2.0,0.77,2.5,-1.2,79.03,0.0,0.0,0.0,28.8,14.4,297.0,1023.3,30.0,0.0,0.1,0.0,False,False,False,True,False,True,False,False,2022,2,3,0,Chernivtsi,Europe/Kiev,2022-02-24,07:07:29,17:52:16,00:00:00,Чернівецька,0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-0.0
79335,2022-02-24,5,48.00200,37.81450,3.6,0.7,81.0,1.300,100.0,20.83,0.0,0.0,41.4,14.4,48.6,1021.8,98.6,74.0,6.4,3.0,0.77,3.7,3.7,74.03,0.0,0.0,0.0,8.3,4.7,332.7,1020.0,95.7,0.0,0.1,0.0,False,False,False,True,False,True,False,False,2022,2,3,0,Donetsk,Europe/Kiev,2022-02-24,06:19:37,17:05:06,00:00:00,Донецька,0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-0.0
528900,2022-02-24,23,49.44070,32.06370,1.9,-0.6,83.4,0.000,0.0,0.00,0.0,0.0,14.4,8.3,47.6,1023.2,69.4,47.4,4.4,2.0,0.77,0.9,0.9,75.73,0.0,0.0,0.0,7.2,4.0,132.0,1020.0,89.0,0.0,0.1,0.0,False,True,False,False,False,True,False,False,2022,2,3,0,Cherkasy,Europe/Kiev,2022-02-24,06:44:41,17:26:05,00:00:00,Черкаська,0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0.0,0.0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-0.0

In [38]:
df_final.to_parquet("merged_dataset.parquet", index=False, engine="pyarrow")