# Data merge and feature engineering

In [1]:
%pip install pyarrow

Requirement already satisfied: pyarrow in c:\users\uw11\appdata\local\programs\python\python313\lib\site-packages (23.0.1)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.3.1 -> 26.0.1
[notice] To update, run: C:\Users\Uw11\AppData\Local\Programs\Python\Python313\python.exe -m pip install --upgrade pip

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import string

import re
import nltk
from nltk.stem import WordNetLemmatizer
from nltk.corpus import stopwords
from sklearn.feature_extraction.text import TfidfVectorizer
from tqdm.notebook import tqdm
from tqdm import tqdm
import pymorphy3
from collections import Counter

import os
from pathlib import Path
import json

In [3]:
df_weather = pd.read_csv("../data/weather_processed.csv")
df_war_events = pd.read_csv("../data/war_events_processed.csv")
df_isw_matrix = pd.read_csv("../data/isw_processed_svd.csv")

In [4]:
pd.set_option('display.max_columns', None)

In [5]:
df_weather['datetime_hour'] = pd.to_datetime(df_weather['datetime_hour'], errors="coerce")
df_war_events['datetime_hour'] = pd.to_datetime(df_war_events['datetime_hour'], errors="coerce")

In [6]:
df_final = pd.merge(
    df_weather, 
    df_war_events[['datetime_hour', 'region_id', 'alarm_active', 'alarm_minutes_in_hour']], 
    on=['datetime_hour', 'region_id'], 
    how='left'
)
df_final.sample(20)

,datetime_hour,region_id,city_latitude,city_longitude,day_temp,day_dew,day_humidity,day_precip,day_precipprob,day_precipcover,day_snow,day_snowdepth,day_windgust,day_windspeed,day_winddir,day_pressure,day_cloudcover,day_solarradiation,day_solarenergy,day_uvindex,day_moonphase,hour_temp,hour_feelslike,hour_humidity,hour_precip,hour_precipprob,hour_snow,hour_windgust,hour_windspeed,hour_winddir,hour_pressure,hour_cloudcover,hour_solarradiation,hour_solarenergy,hour_uvindex,day_conditions_simple_Clear,day_conditions_simple_Cloudy,day_conditions_simple_Rain,day_conditions_simple_Snow,hour_conditions_simple_Clear,hour_conditions_simple_Cloudy,hour_conditions_simple_Rain,hour_conditions_simple_Snow,year,month,day_of_week,hour,city_name,city_timezone,day_datetime,day_sunrise,day_sunset,hour_datetime,region_key,alarm_active,alarm_minutes_in_hour
223280,2023-03-18 16:00:00,10,50.45060,30.52430,4.0,0.0,75.9,0.000,0.0,0.00,0.0,0.0,31.3,14.4,66.9,1027.0,78.5,126.9,10.9,4.0,0.88,6.9,4.8,63.73,0.0,0.0,0.0,23.8,10.4,91.3,1027.0,80.4,269.7,1.0,3.0,False,True,False,False,False,True,False,False,2023,3,5,16,Kyiv,Europe/Kiev,2023-03-18,06:06:02,18:07:03,16:00:00,Київська,0,0.000000
181488,2023-01-05 03:00:00,2,49.23360,28.44860,4.0,1.5,83.8,2.600,100.0,8.33,0.0,0.0,41.8,22.7,241.7,1009.2,95.8,6.0,0.5,0.0,0.42,0.6,-3.7,85.19,0.0,0.0,0.0,28.4,15.1,196.9,1016.0,97.3,0.0,0.1,0.0,False,False,True,False,False,True,False,False,2023,1,3,3,Vinnytsia,Europe/Kiev,2023-01-05,08:00:55,16:22:18,03:00:00,Вінницька,0,0.000000
498021,2024-07-07 17:00:00,24,48.29240,25.93550,23.8,15.0,59.7,0.000,0.0,0.00,0.0,0.0,37.4,24.5,134.5,1015.8,32.2,307.9,26.6,9.0,0.05,29.9,29.7,41.19,0.0,0.0,0.0,32.0,15.1,146.0,1014.7,10.0,589.8,2.1,6.0,False,True,False,False,True,False,False,False,2024,7,6,17,Chernivtsi,Europe/Kiev,2024-07-07,05:24:08,21:18:05,17:00:00,Чернівецька,0,0.000000
234206,2023-04-06 16:00:00,17,50.61930,26.25130,4.5,4.0,96.6,11.943,100.0,8.33,0.3,1.1,41.8,25.1,24.1,1011.7,99.6,33.1,2.7,1.0,0.50,7.5,4.4,93.38,0.0,0.0,0.0,30.6,17.6,55.2,1010.0,100.0,63.1,0.2,1.0,False,False,False,True,False,True,False,False,2023,4,3,16,Rivne,Europe/Kiev,2023-04-06,06:41:07,19:54:58,16:00:00,Рівненська,0,0.000000
452402,2024-04-19 13:00:00,4,48.47530,35.01600,10.8,4.0,64.1,0.200,100.0,8.33,0.0,0.0,55.4,32.4,241.2,1007.6,64.9,185.7,16.0,5.0,0.35,13.3,13.3,48.97,0.1,100.0,0.0,51.5,25.2,249.3,1010.0,56.9,524.9,1.9,5.0,False,False,True,False,False,False,True,False,2024,4,4,13,Dnipro,Europe/Kiev,2024-04-19,05:41:31,19:37:29,13:00:00,Дніпропетровська,1,16.333333
604781,2025-01-09 02:00:00,7,48.62640,22.28510,6.4,4.4,87.5,1.996,100.0,66.67,0.0,2.1,41.0,24.1,187.3,1010.5,92.5,6.2,0.6,0.0,0.34,4.8,2.2,89.29,0.0,0.0,0.0,36.0,11.0,211.0,1011.8,89.3,0.0,0.0,0.0,False,False,True,False,False,True,False,False,2025,1,3,2,Uzhgorod,Europe/Uzhgorod,2025-01-09,08:21:35,16:54:56,02:00:00,Закарпатська,0,0.000000
323603,2023-09-08 21:00:00,14,46.97340,31.98520,18.9,4.4,41.9,0.000,0.0,0.00,0.0,0.0,31.7,18.0,24.6,1022.2,0.5,234.4,20.4,7.0,0.78,18.4,18.4,37.40,0.0,0.0,0.0,12.6,7.2,10.0,1019.8,0.0,0.0,0.0,0.0,True,False,False,False,True,False,False,False,2023,9,4,21,Mykolaiv,Europe/Kiev,2023-09-08,06:19:55,19:19:02,21:00:00,Миколаївська,0,0.000000
104917,2022-08-25 04:00:00,16,49.58790,34.55170,24.1,9.5,42.2,0.000,0.0,0.00,0.0,0.0,45.7,25.2,73.5,1017.7,39.0,259.9,22.4,8.0,0.92,17.9,17.9,59.49,0.0,0.0,0.0,16.9,8.3,33.9,1019.0,33.6,0.0,0.1,0.0,False,True,False,False,False,True,False,False,2022,8,3,4,Poltava,Europe/Kiev,2022-08-25,05:46:49,19:40:06,04:00:00,Полтавська,1,46.883333
141744,2022-10-28 03:00:00,2,49.23360,28.44860,10.1,7.8,86.3,0.000,0.0,0.00,0.0,0.0,20.9,9.4,237.1,1028.4,76.9,79.0,6.8,3.0,0.08,6.9,6.9,95.30,0.0,0.0,0.0,4.7,2.9,236.5,1030.0,28.1,0.0,0.1,0.0,False,True,False,False,False,True,False,False,2022,10,4,3,Vinnytsia,Europe/Kiev,2022-10-28,07:47:13,17:52:04,03:00:00,Вінницька,0,0.000000
188419,2023-01-17 03:00:00,22,49.41680,26.97430,3.3,2.0,88.9,0.100,100.0,4.17,0.0,0.0,46.8,36.0,162.8,999.5,70.2,37.3,3.3,2.0,0.83,3.4,3.4,79.14,0.0,0.0,0.0,45.5,36.0,166.9,1000.0,100.0,0.0,0.1,0.0,False,False,True,False,False,True,False,False,2023,1,1,3,Khmelnytskyi,Europe/Kiev,2023-01-17,08:01:16,16:43:24,03:00:00,Хмельницька,0,0.000000
576937,2024-11-21 18:00:00,3,50.74690,25.32630,0.6,-1.8,83.8,0.300,100.0,12.50,0.0,0.0,46.1,23.8,269.0,998.5,65.5,36.9,3.1,2.0,0.68,0.9,-3.7,83.37,0.0,0.0,0.0,32.4,17.3,262.5,1000.0,2.1,0.0,0.0,0.0,False,False,False,True,True,False,False,False,2024,11,3,18,Lutsk,Europe/Kiev,2024-11-21,07:44:25,16:24:30,18:00:00,Волинська,0,0.000000
372388,2023-12-02 14:00:00,6,50.25360,28.66540,-1.1,-1.5,96.7,7.000,100.0,8.33,3.5,10.6,31.7,17.6,91.0,1006.9,100.0,14.4,1.2,1.0,0.66,-0.8,-5.9,95.70,0.0,0.0,0.2,31.3,17.3,89.5,1006.0,100.0,52.6,0.2,1.0,False,False,False,True,False,True,False,False,2023,12,5,14,Zhytomyr,Europe/Kiev,2023-12-02,07:44:01,16:04:59,14:00:00,Житомирська,0,0.000000
268383,2023-06-05 00:00:00,18,50.90800,34.79720,14.0,3.7,54.7,0.000,0.0,0.00,0.0,0.0,28.8,12.6,349.7,1023.0,47.3,212.6,18.5,8.0,0.54,8.8,7.8,78.97,0.0,0.0,0.0,11.9,7.1,360.0,1024.1,21.0,0.0,0.0,0.0,False,True,False,False,False,True,False,False,2023,6,0,0,Sumy,Europe/Kiev,2023-06-05,04:30:00,20:49:09,00:00:00,Сумська,0,0.000000
359136,2023-11-09 14:00:00,2,49.23360,28.44860,6.9,4.6,85.5,0.000,0.0,0.00,0.0,0.0,37.4,18.4,292.5,1018.1,65.3,39.7,3.3,2.0,0.87,10.2,10.2,71.12,0.0,0.0,0.0,34.9,10.8,300.0,1019.3,80.0,121.2,0.4,1.0,False,True,False,False,False,True,False,False,2023,11,3,14,Vinnytsia,Europe/Kiev,2023-11-09,07:06:13,16:33:11,14:00:00,Вінницька,0,0.000000
238402,2023-04-13 23:00:00,13,49.84440,24.02540,9.7,3.8,70.4,0.000,0.0,0.00,0.0,0.0,23.8,13.0,263.7,1006.7,53.9,179.5,15.6,7.0,0.75,7.4,6.1,80.70,0.0,0.0,0.0,12.6,7.2,124.2,1008.0,81.4,0.0,0.0,0.0,False,True,False,False,False,True,False,False,2023,4,3,23,Lviv,Europe/Kiev,2023-04-13,06:36:17,20:13:49,23:00:00,Львівська,0,0.000000
66533,2022-06-19 13:00:00,7,48.62636,22.28514,21.5,11.1,54.9,0.000,0.0,0.00,0.0,0.0,32.4,12.7,175.3,1017.6,4.3,340.2,29.2,9.0,0.65,27.1,26.9,38.39,0.0,0.0,0.0,23.0,12.1,189.0,1017.8,0.0,871.0,3.1,9.0,True,False,False,False,True,False,False,False,2022,6,6,13,Uzhgorod,Europe/Uzhgorod,2022-06-19,05:28:03,21:36:30,13:00:00,Закарпатська,0,0.000000
560095,2024-10-23 12:00:00,9,48.92260,24.71470,8.3,5.4,82.8,0.100,100.0,4.17,0.0,0.0,34.9,14.8,297.3,1032.4,54.6,41.6,3.4,2.0,0.70,12.7,12.7,88.80,0.0,0.0,0.0,29.5,14.4,280.0,1033.3,100.0,117.7,0.4,1.0,False,False,True,False,False,True,False,False,2024,10,2,12,Ivano-Frankivsk,Europe/Kiev,2024-10-23,07:54:27,18:15:40,12:00:00,Івано-Франківська,0,0.000000
64237,2022-06-15 13:00:00,16,49.58790,34.55170,18.6,7.9,51.8,0.600,100.0,4.17,0.0,0.0,35.6,14.8,324.6,1015.5,56.5,302.1,26.3,9.0,0.52,22.2,22.2,36.69,0.0,0.0,0.0,31.0,13.7,313.5,1016.0,65.9,877.0,3.2,9.0,False,False,True,False,False,True,False,False,2022,6,2,13,Poltava,Europe/Kiev,2022-06-15,04:34:13,20:50:35,13:00:00,Полтавська,0,0.000000
103500,2022-08-22 17:00:00,15,46.47250,30.73710,26.2,19.6,68.2,0.000,0.0,0.00,0.0,0.0,27.4,13.7,55.7,1008.1,46.1,263.8,22.8,8.0,0.82,28.4,29.6,57.12,0.0,0.0,0.0,20.5,8.3,101.0,1008.0,51.1,467.0,1.7,5.0,False,True,False,False,False,True,False,False,2022,8,0,17,Odesa,Europe/Kiev,2022-08-22,06:04:03,19:55:05,17:00:00,Одеська,0,0.000000
294369,2023-07-20 03:00:00,11,48.50850,32.26560,20.8,15.7,73.4,2.000,100.0,25.00,0.0,0.0,26.3,21.6,140.4,1008.7,66.6,198.0,17.0,6.0,0.09,18.2,18.2,82.12,0.0,0.0,0.0,12.2,0.0,107.9,1009.5,60.0,0.0,0.0,0.0,False,False,True,False,False,True,False,False,2023,7,3,3,Kropyvnytskyi,Europe/Kiev,2023-07-20,05:10:02,20:43:58,03:00:00,Кіровоградська,1,30.466667

In [7]:
df_final = df_final.sort_values(['region_id', 'datetime_hour'])
df_final.head()

,datetime_hour,region_id,city_latitude,city_longitude,day_temp,day_dew,day_humidity,day_precip,day_precipprob,day_precipcover,day_snow,day_snowdepth,day_windgust,day_windspeed,day_winddir,day_pressure,day_cloudcover,day_solarradiation,day_solarenergy,day_uvindex,day_moonphase,hour_temp,hour_feelslike,hour_humidity,hour_precip,hour_precipprob,hour_snow,hour_windgust,hour_windspeed,hour_winddir,hour_pressure,hour_cloudcover,hour_solarradiation,hour_solarenergy,hour_uvindex,day_conditions_simple_Clear,day_conditions_simple_Cloudy,day_conditions_simple_Rain,day_conditions_simple_Snow,hour_conditions_simple_Clear,hour_conditions_simple_Cloudy,hour_conditions_simple_Rain,hour_conditions_simple_Snow,year,month,day_of_week,hour,city_name,city_timezone,day_datetime,day_sunrise,day_sunset,hour_datetime,region_key,alarm_active,alarm_minutes_in_hour
0,2022-02-24 00:00:00,2,49.2336,28.4486,2.8,-0.3,80.5,0.3,100.0,4.17,0.0,0.0,27.7,10.8,312.0,1023.4,82.5,60.4,5.4,3.0,0.77,2.1,-0.5,91.76,0.0,0.0,0.0,16.6,8.6,279.6,1021.0,91.1,0.0,0.1,0.0,False,False,False,True,False,True,False,False,2022,2,3,0,Vinnytsia,Europe/Kiev,2022-02-24,06:58:49,17:40:52,00:00:00,Вінницька,0,0.0
24,2022-02-24 01:00:00,2,49.2336,28.4486,2.8,-0.3,80.5,0.3,100.0,4.17,0.0,0.0,27.7,10.8,312.0,1023.4,82.5,60.4,5.4,3.0,0.77,2.1,-0.4,89.80,0.0,0.0,0.0,16.6,8.3,289.2,1021.0,97.9,0.0,0.1,0.0,False,False,False,True,False,True,False,False,2022,2,3,1,Vinnytsia,Europe/Kiev,2022-02-24,06:58:49,17:40:52,01:00:00,Вінницька,0,0.0
48,2022-02-24 02:00:00,2,49.2336,28.4486,2.8,-0.3,80.5,0.3,100.0,4.17,0.0,0.0,27.7,10.8,312.0,1023.4,82.5,60.4,5.4,3.0,0.77,2.0,-0.3,90.44,0.0,0.0,0.0,27.7,7.6,287.6,1021.0,98.2,0.0,0.1,0.0,False,False,False,True,False,True,False,False,2022,2,3,2,Vinnytsia,Europe/Kiev,2022-02-24,06:58:49,17:40:52,02:00:00,Вінницька,0,0.0
72,2022-02-24 03:00:00,2,49.2336,28.4486,2.8,-0.3,80.5,0.3,100.0,4.17,0.0,0.0,27.7,10.8,312.0,1023.4,82.5,60.4,5.4,3.0,0.77,1.9,-0.3,91.75,0.0,0.0,0.0,15.1,7.2,288.9,1021.0,98.8,0.0,0.1,0.0,False,False,False,True,False,True,False,False,2022,2,3,3,Vinnytsia,Europe/Kiev,2022-02-24,06:58:49,17:40:52,03:00:00,Вінницька,0,0.0
96,2022-02-24 04:00:00,2,49.2336,28.4486,2.8,-0.3,80.5,0.3,100.0,4.17,0.0,0.0,27.7,10.8,312.0,1023.4,82.5,60.4,5.4,3.0,0.77,1.8,-0.2,92.40,0.0,0.0,0.0,13.7,6.5,290.4,1021.0,100.0,0.0,0.1,0.0,False,False,False,True,False,True,False,False,2022,2,3,4,Vinnytsia,Europe/Kiev,2022-02-24,06:58:49,17:40:52,04:00:00,Вінницька,0,0.0

In [8]:
df_final.info()

<class 'pandas.DataFrame'>
Index: 634680 entries, 0 to 634679
Data columns (total 56 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   datetime_hour                  634680 non-null  datetime64[us]
 1   region_id                      634680 non-null  int64
 2   city_latitude                  634680 non-null  float64
 3   city_longitude                 634680 non-null  float64
 4   day_temp                       634680 non-null  float64
 5   day_dew                        634680 non-null  float64
 6   day_humidity                   634680 non-null  float64
 7   day_precip                     634680 non-null  float64
 8   day_precipprob                 634680 non-null  float64
 9   day_precipcover                634680 non-null  float64
 10  day_snow                       634680 non-null  float64
 11  day_snowdepth                  634680 non-null  float64
 12  day_windgust                   634680 non-null  float64
 13  day_windspeed                  634680 non-null  float64
 14  day_winddir                    634680 non-null  float64
 15  day_pressure                   634680 non-null  float64
 16  day_cloudcover                 634680 non-null  float64
 17  day_solarradiation             634680 non-null  float64
 18  day_solarenergy                634680 non-null  float64
 19  day_uvindex                    634680 non-null  float64
 20  day_moonphase                  634680 non-null  float64
 21  hour_temp                      634680 non-null  float64
 22  hour_feelslike                 634680 non-null  float64
 23  hour_humidity                  634680 non-null  float64
 24  hour_precip                    634680 non-null  float64
 25  hour_precipprob                634680 non-null  float64
 26  hour_snow                      634680 non-null  float64
 27  hour_windgust                  634680 non-null  float64
 28  hour_windspeed                 634680 non-null  float64
 29  hour_winddir                   634680 non-null  float64
 30  hour_pressure                  634680 non-null  float64
 31  hour_cloudcover                634680 non-null  float64
 32  hour_solarradiation            634680 non-null  float64
 33  hour_solarenergy               634680 non-null  float64
 34  hour_uvindex                   634680 non-null  float64
 35  day_conditions_simple_Clear    634680 non-null  bool
 36  day_conditions_simple_Cloudy   634680 non-null  bool
 37  day_conditions_simple_Rain     634680 non-null  bool
 38  day_conditions_simple_Snow     634680 non-null  bool
 39  hour_conditions_simple_Clear   634680 non-null  bool
 40  hour_conditions_simple_Cloudy  634680 non-null  bool
 41  hour_conditions_simple_Rain    634680 non-null  bool
 42  hour_conditions_simple_Snow    634680 non-null  bool
 43  year                           634680 non-null  int64
 44  month                          634680 non-null  int64
 45  day_of_week                    634680 non-null  int64
 46  hour                           634680 non-null  int64
 47  city_name                      634680 non-null  str
 48  city_timezone                  634680 non-null  str
 49  day_datetime                   634680 non-null  str
 50  day_sunrise                    634680 non-null  str
 51  day_sunset                     634680 non-null  str
 52  hour_datetime                  634680 non-null  str
 53  region_key                     634680 non-null  str
 54  alarm_active                   634680 non-null  int64
 55  alarm_minutes_in_hour          634680 non-null  float64
dtypes: bool(8), datetime64[us](1), float64(34), int64(6), str(7)
memory usage: 287.3 MB

In [9]:
df_final = df_final.sort_values(["region_id", "datetime_hour"])

df_final["alarm_lag_1"] = df_final.groupby("region_id")["alarm_active"].shift(1)
df_final["alarm_lag_3"] = df_final.groupby("region_id")["alarm_active"].shift(3)
df_final["alarm_lag_6"] = df_final.groupby("region_id")["alarm_active"].shift(6)
df_final["alarm_lag_12"] = df_final.groupby("region_id")["alarm_active"].shift(12)

lag_cols = ["alarm_lag_1","alarm_lag_3","alarm_lag_6","alarm_lag_12"]
df_final[lag_cols] = df_final[lag_cols].fillna(0)

df_final['alarms_in_last_24h'] = (df_final.groupby('region_id')['alarm_active'].transform(lambda x: x.shift(1).rolling(24, min_periods=1).sum()))

df_final['is_weekend'] = df_final['day_of_week'].isin([5, 6]).astype(int)
df_final['is_night'] = ((df_final['hour'] >= 23) | (df_final['hour'] <= 6)).astype(int)

hourly_total = df_final.groupby('datetime_hour')['alarm_active'].sum().shift(1)
df_final['total_active_alarms_lag1'] = df_final['datetime_hour'].map(hourly_total)

df_final.sample(10)

,datetime_hour,region_id,city_latitude,city_longitude,day_temp,day_dew,day_humidity,day_precip,day_precipprob,day_precipcover,day_snow,day_snowdepth,day_windgust,day_windspeed,day_winddir,day_pressure,day_cloudcover,day_solarradiation,day_solarenergy,day_uvindex,day_moonphase,hour_temp,hour_feelslike,hour_humidity,hour_precip,hour_precipprob,hour_snow,hour_windgust,hour_windspeed,hour_winddir,hour_pressure,hour_cloudcover,hour_solarradiation,hour_solarenergy,hour_uvindex,day_conditions_simple_Clear,day_conditions_simple_Cloudy,day_conditions_simple_Rain,day_conditions_simple_Snow,hour_conditions_simple_Clear,hour_conditions_simple_Cloudy,hour_conditions_simple_Rain,hour_conditions_simple_Snow,year,month,day_of_week,hour,city_name,city_timezone,day_datetime,day_sunrise,day_sunset,hour_datetime,region_key,alarm_active,alarm_minutes_in_hour,alarm_lag_1,alarm_lag_3,alarm_lag_6,alarm_lag_12,alarms_in_last_24h,is_weekend,is_night,total_active_alarms_lag1
196989,2023-02-01 00:00:00,24,48.2924,25.9355,1.6,-2.9,72.9,0.006,100.0,8.33,0.0,0.1,50.4,24.4,269.0,1011.2,75.3,62.4,5.4,3.0,0.35,2.0,-2.0,74.81,0.0,0.0,0.0,30.2,14.8,320.0,1012.0,50.0,0.0,0.0,0.0,False,False,False,True,False,True,False,False,2023,2,2,0,Chernivtsi,Europe/Kiev,2023-02-01,07:45:24,17:14:51,00:00:00,Чернівецька,0,0.000000,0.0,0.0,0.0,1.0,4.0,0,1,1.0
466343,2024-05-13 17:00:00,26,50.4506,30.5243,7.9,1.0,63.5,0.500,100.0,20.83,0.0,0.0,35.3,15.5,31.1,1020.7,68.8,206.9,18.0,6.0,0.17,10.4,10.4,51.02,0.0,0.0,0.0,31.0,14.0,39.2,1020.0,80.5,333.0,1.2,3.0,False,False,True,False,False,True,False,False,2024,5,0,17,Kyiv,Europe/Kiev,2024-05-13,05:12:46,20:36:48,17:00:00,Київ,1,9.233333,1.0,1.0,0.0,0.0,5.0,0,0,24.0
612023,2025-01-21 15:00:00,26,50.4506,30.5243,-0.6,-1.0,96.9,0.000,0.0,0.00,0.1,0.0,30.6,16.9,149.2,1025.8,98.8,22.8,1.9,1.0,0.75,-0.8,-5.1,98.55,0.0,0.0,0.0,26.3,13.3,147.9,1025.0,100.0,58.9,0.2,1.0,False,True,False,False,False,True,False,False,2025,1,1,15,Kyiv,Europe/Kiev,2025-01-21,07:46:47,16:32:19,15:00:00,Київ,0,0.000000,0.0,0.0,0.0,0.0,3.0,0,0,0.0
415410,2024-02-15 06:00:00,21,46.6401,32.6142,6.6,5.1,90.8,3.300,100.0,8.33,0.0,0.0,35.3,21.6,43.1,1019.0,99.7,53.0,4.6,2.0,0.19,7.5,5.1,98.64,0.0,0.0,0.0,22.7,13.0,36.4,1017.0,100.0,0.0,0.0,0.0,False,False,True,False,False,True,False,False,2024,2,3,6,Kherson,Europe/Kiev,2024-02-15,06:54:33,17:13:36,06:00:00,Херсонська,1,60.000000,1.0,0.0,0.0,0.0,5.0,0,1,24.0
482613,2024-06-10 23:00:00,24,48.2924,25.9355,21.2,16.8,77.5,1.156,100.0,8.33,0.0,0.0,38.2,20.7,192.9,1007.4,63.2,248.3,21.4,8.0,0.12,19.2,19.2,86.50,0.0,0.0,0.0,20.9,20.7,256.0,1006.9,88.0,0.0,0.0,0.0,False,False,True,False,False,True,False,False,2024,6,0,23,Chernivtsi,Europe/Kiev,2024-06-10,05:15:37,21:16:25,23:00:00,Чернівецька,0,0.000000,0.0,0.0,0.0,0.0,0.0,0,1,3.0
11862,2022-03-16 14:00:00,8,47.8289,35.1626,-1.0,-7.3,63.5,0.000,0.0,0.00,0.0,0.0,31.3,16.2,13.5,1030.0,43.5,201.3,17.3,6.0,0.45,3.4,3.4,68.74,0.0,0.0,0.0,31.0,16.2,290.0,1027.8,40.0,592.0,2.1,6.0,False,True,False,False,False,True,False,False,2022,3,2,14,Zaporozhye,Europe/Zaporozhye,2022-03-16,05:50:53,17:46:01,14:00:00,Запорізька,0,0.000000,0.0,0.0,0.0,0.0,0.0,0,0,2.0
400293,2024-01-20 00:00:00,24,48.2924,25.9355,-2.1,-5.7,77.0,0.657,100.0,8.33,0.6,3.0,36.0,22.7,300.0,1024.7,37.3,57.2,4.8,3.0,0.31,-2.4,-7.2,95.74,0.0,0.0,0.6,21.6,14.7,315.0,1019.3,25.0,0.0,0.0,0.0,False,False,False,True,False,True,False,False,2024,1,5,0,Chernivtsi,Europe/Kiev,2024-01-20,07:58:59,16:55:46,00:00:00,Чернівецька,0,0.000000,0.0,0.0,0.0,0.0,0.0,1,1,5.0
113841,2022-09-09 16:00:00,11,48.5085,32.2656,14.7,8.5,69.8,1.100,100.0,8.33,0.0,0.0,29.9,21.6,70.0,1020.6,78.9,148.8,12.9,7.0,0.42,20.1,20.1,42.02,0.0,0.0,0.0,25.9,11.9,78.6,1021.0,98.2,43.0,0.2,0.0,False,False,True,False,False,True,False,False,2022,9,4,16,Kropyvnytskyi,Europe/Kiev,2022-09-09,06:18:58,19:16:49,16:00:00,Кіровоградська,0,0.000000,0.0,0.0,0.0,0.0,3.0,0,0,0.0
518272,2024-08-11 21:00:00,19,49.5527,25.5889,21.4,15.7,72.4,0.800,100.0,4.17,0.0,0.0,45.7,21.6,285.0,1018.3,30.9,233.2,20.1,7.0,0.23,21.4,21.4,80.46,0.8,100.0,0.0,26.3,18.0,280.0,1015.8,60.0,8.7,0.0,0.0,False,False,True,False,False,False,True,False,2024,8,6,21,Ternopil,Europe/Kiev,2024-08-11,06:03:11,20:41:32,21:00:00,Тернопільська,0,0.000000,0.0,0.0,0.0,0.0,5.0,1,0,7.0
12124,2022-03-17 01:00:00,6,50.2536,28.6654,-2.5,-10.1,59.2,0.000,0.0,0.00,0.0,0.0,29.2,15.1,54.9,1039.0,16.2,190.0,16.5,5.0,0.48,-4.9,-7.4,74.69,0.0,0.0,0.0,9.4,5.4,77.0,1036.0,0.0,0.0,0.1,0.0,True,False,False,False,True,False,False,False,2022,3,3,1,Zhytomyr,Europe/Kiev,2022-03-17,06:15:06,18:13:17,01:00:00,Житомирська,0,0.000000,0.0,1.0,1.0,0.0,18.0,0,1,1.0

In [10]:
neighbouring_regions = {
    1: [21],
    2: [6, 10, 11, 15, 22, 23, 24],
    3: [13, 17],
    4: [5, 8, 11, 14, 16, 20, 21],
    5: [4, 8, 12, 20],
    6: [2, 10, 17, 22],
    7: [9, 13],
    8: [4, 5, 21],
    9: [7, 13, 19, 24],
    10: [2, 6, 16, 23, 25],
    11: [2, 4, 14, 15, 16, 23],
    12: [5, 20],
    13: [3, 7, 9, 17, 19],
    14: [4, 11, 15, 21],
    15: [2, 11, 14],
    16: [4, 10, 11, 18, 20, 23, 25],
    17: [3, 6, 13, 19, 22],
    18: [16, 20, 25],
    19: [9, 13, 17, 22, 24],
    20: [4, 5, 12, 16, 18],
    21: [1, 4, 8, 14],
    22: [2, 6, 17, 19, 24],
    23: [2, 10, 11, 16],
    24: [2, 9, 19, 22],
    25: [10, 16, 18], 
    26: [10]
}

alarms_matrix = df_final.pivot_table(
    index='datetime_hour',
    columns='region_id',
    values='alarm_active',
    fill_value=0
)

neighbour_alarm_matrix = pd.DataFrame(index=alarms_matrix.index)

for region, neighbours in neighbouring_regions.items():
    valid_neighbours = [n for n in neighbours if n in alarms_matrix.columns]
    
    if valid_neighbours:
        neighbour_alarm_matrix[region] = alarms_matrix[valid_neighbours].sum(axis=1)
    else:
        neighbour_alarm_matrix[region] = 0

neighbour_alarm_matrix = neighbour_alarm_matrix.shift(1)

neighbour_alarm_long = (neighbour_alarm_matrix.stack().reset_index())

neighbour_alarm_long.columns = ['datetime_hour','region_id','neighbour_alarms']

df_final = df_final.merge(neighbour_alarm_long,on=['datetime_hour', 'region_id'], how='left')

In [11]:
def hours_since_last_alarm(series):
    shifted = series.shift(1).fillna(0)
    result = []
    count = 0
    for val in shifted:
        if val == 1:
            count = 0
        else:
            count += 1
        result.append(count)
    return pd.Series(result, index=series.index)

df_final['hours_since_last_alarm'] = (df_final.groupby('region_id')['alarm_active'].transform(hours_since_last_alarm))

In [12]:
df_final.sample(20)

,datetime_hour,region_id,city_latitude,city_longitude,day_temp,day_dew,day_humidity,day_precip,day_precipprob,day_precipcover,day_snow,day_snowdepth,day_windgust,day_windspeed,day_winddir,day_pressure,day_cloudcover,day_solarradiation,day_solarenergy,day_uvindex,day_moonphase,hour_temp,hour_feelslike,hour_humidity,hour_precip,hour_precipprob,hour_snow,hour_windgust,hour_windspeed,hour_winddir,hour_pressure,hour_cloudcover,hour_solarradiation,hour_solarenergy,hour_uvindex,day_conditions_simple_Clear,day_conditions_simple_Cloudy,day_conditions_simple_Rain,day_conditions_simple_Snow,hour_conditions_simple_Clear,hour_conditions_simple_Cloudy,hour_conditions_simple_Rain,hour_conditions_simple_Snow,year,month,day_of_week,hour,city_name,city_timezone,day_datetime,day_sunrise,day_sunset,hour_datetime,region_key,alarm_active,alarm_minutes_in_hour,alarm_lag_1,alarm_lag_3,alarm_lag_6,alarm_lag_12,alarms_in_last_24h,is_weekend,is_night,total_active_alarms_lag1,neighbour_alarms,hours_since_last_alarm
361627,2024-03-08 12:00:00,16,49.5879,34.5517,-0.9,-6.4,67.5,0.000,0.0,0.00,0.0,0.0,23.0,10.8,288.4,1021.3,56.3,88.8,7.6,3.0,0.93,1.7,-0.5,54.50,0.0,0.0,0.0,18.0,7.2,278.8,1022.0,85.9,283.9,1.0,3.0,False,True,False,False,False,True,False,False,2024,3,4,12,Poltava,Europe/Kiev,2024-03-08,06:09:32,17:36:20,12:00:00,Полтавська,0,0.000000,0.0,0.0,0.0,0.0,7.0,0,0,4.0,2.0,3
352600,2023-02-26 08:00:00,16,49.5879,34.5517,3.7,2.0,88.4,1.000,100.0,4.17,0.0,0.1,48.6,25.6,240.3,1008.3,99.0,56.2,4.8,3.0,0.20,2.9,0.9,91.16,0.0,0.0,0.0,14.0,7.2,250.0,1006.2,100.0,29.0,0.1,0.0,False,False,True,False,False,True,False,False,2023,2,6,8,Poltava,Europe/Kiev,2023-02-26,06:31:31,17:18:49,08:00:00,Полтавська,0,0.000000,0.0,0.0,0.0,0.0,3.0,1,0,0.0,0.0,15
148912,2024-01-20 09:00:00,7,48.6264,22.2851,-1.7,-6.6,70.2,0.001,100.0,4.17,0.0,6.4,33.8,10.5,260.7,1027.3,29.2,69.4,6.0,3.0,0.31,-5.8,-5.8,84.82,0.0,0.0,0.0,14.4,4.5,220.0,1027.4,23.5,15.0,0.1,0.0,False,False,False,True,False,True,False,False,2024,1,5,9,Uzhgorod,Europe/Uzhgorod,2024-01-20,08:14:45,17:09:13,09:00:00,Закарпатська,0,0.000000,0.0,0.0,0.0,0.0,0.0,1,0,0.0,0.0,43
355128,2023-06-11 17:00:00,16,49.5879,34.5517,18.2,12.8,71.4,5.900,100.0,16.67,0.0,0.0,52.2,36.0,55.0,1012.3,95.5,201.3,17.5,7.0,0.76,17.0,17.0,88.58,2.1,100.0,0.0,43.6,19.4,57.1,1013.0,100.0,157.7,0.6,2.0,False,False,True,False,False,False,True,False,2023,6,6,17,Poltava,Europe/Kiev,2023-06-11,04:34:58,20:48:13,17:00:00,Полтавська,1,17.433333,0.0,0.0,0.0,0.0,7.0,1,0,2.0,1.0,1
395887,2025-01-28 04:00:00,17,50.6193,26.2513,5.2,3.0,85.9,0.000,0.0,0.00,0.0,0.0,34.9,19.4,163.6,1010.7,81.5,42.8,3.8,2.0,0.96,3.1,-0.8,93.14,0.0,0.0,0.0,30.2,15.8,171.4,1012.0,17.6,0.0,0.0,0.0,False,True,False,False,True,False,False,False,2025,1,1,4,Rivne,Europe/Kiev,2025-01-28,07:56:01,17:00:37,04:00:00,Рівненська,0,0.000000,0.0,0.0,0.0,0.0,1.0,0,1,12.0,0.0,22
597775,2023-12-22 03:00:00,25,51.4937,31.2944,1.3,0.0,91.3,2.000,100.0,4.17,0.2,1.3,43.9,24.1,185.8,986.2,93.4,10.8,0.9,1.0,0.34,1.2,-4.1,85.26,0.0,0.0,0.0,40.7,22.3,179.7,990.0,100.0,0.0,0.0,0.0,False,False,False,True,False,True,False,False,2023,12,4,3,Chernihiv,Europe/Kiev,2023-12-22,07:58:27,15:48:06,03:00:00,Чернігівська,0,0.000000,0.0,1.0,1.0,0.0,5.0,0,1,4.0,0.0,2
511601,2023-03-12 03:00:00,22,49.4168,26.9743,0.4,-3.9,74.4,1.000,100.0,4.17,1.0,1.1,59.0,36.0,291.9,1008.2,61.7,121.9,10.7,5.0,0.67,-0.5,-7.5,92.95,0.0,0.0,0.3,53.3,33.1,309.0,1001.0,100.0,0.0,0.0,0.0,False,False,False,True,False,True,False,False,2023,3,6,3,Khmelnytskyi,Europe/Kiev,2023-03-12,06:32:52,18:11:55,03:00:00,Хмельницька,0,0.000000,0.0,0.0,0.0,0.0,0.0,1,1,0.0,0.0,31
153458,2024-07-27 20:00:00,7,48.6264,22.2851,21.1,12.3,61.1,0.008,100.0,4.17,0.0,0.0,25.9,12.5,189.1,1017.4,25.8,296.2,25.7,8.0,0.71,26.6,26.6,41.62,0.0,0.0,0.0,16.2,12.5,189.0,1016.6,28.4,182.6,0.7,2.0,False,False,True,False,False,True,False,False,2024,7,5,20,Uzhgorod,Europe/Uzhgorod,2024-07-27,05:58:56,21:15:09,20:00:00,Закарпатська,0,0.000000,0.0,0.0,0.0,0.0,0.0,1,0,1.0,0.0,43
573058,2024-03-03 03:00:00,24,48.2924,25.9355,4.6,2.8,87.7,1.766,100.0,16.67,0.0,0.0,32.4,14.1,124.4,1015.0,92.7,47.1,4.0,2.0,0.75,3.2,3.2,93.34,0.0,0.0,0.0,18.7,4.5,104.0,1015.2,88.0,0.0,0.0,0.0,False,False,True,False,False,True,False,False,2024,3,6,3,Chernivtsi,Europe/Kiev,2024-03-03,06:53:03,18:04:00,03:00:00,Чернівецька,0,0.000000,0.0,0.0,0.0,0.0,0.0,1,1,5.0,0.0,122
349826,2022-11-02 18:00:00,16,49.5879,34.5517,6.1,1.9,74.9,0.700,100.0,12.50,0.0,0.0,15.5,6.5,208.2,1016.6,70.9,92.2,8.0,4.0,0.25,7.4,7.4,76.29,0.0,0.0,0.0,7.6,4.0,355.5,1014.0,90.1,0.0,0.1,0.0,False,False,True,False,False,True,False,False,2022,11,2,18,Poltava,Europe/Kiev,2022-11-02,06:31:43,16:18:18,18:00:00,Полтавська,0,0.000000,0.0,0.0,0.0,0.0,10.0,0,0,0.0,0.0,7
205887,2024-07-08 15:00:00,9,48.9226,24.7147,22.8,18.8,79.3,0.700,100.0,4.17,0.0,0.0,23.4,14.4,351.5,1016.7,49.8,252.4,21.8,8.0,0.08,24.9,24.9,78.48,0.0,0.0,0.0,17.3,14.4,290.0,1017.1,80.0,510.2,1.8,5.0,False,False,True,False,False,True,False,False,2024,7,0,15,Ivano-Frankivsk,Europe/Kiev,2024-07-08,05:27:03,21:25:12,15:00:00,Івано-Франківська,0,0.000000,0.0,0.0,1.0,1.0,6.0,0,0,15.0,0.0,3
222256,2023-05-15 18:00:00,10,50.4506,30.5243,19.1,5.8,46.3,0.000,0.0,0.00,0.0,0.0,31.7,14.0,155.9,1017.6,54.5,270.0,23.3,7.0,0.85,24.6,24.6,29.01,0.0,0.0,0.0,25.9,7.2,150.0,1015.3,80.0,219.7,0.8,2.0,False,True,False,False,False,True,False,False,2023,5,0,18,Kyiv,Europe/Kiev,2023-05-15,05:10:57,20:38:34,18:00:00,Київська,0,0.000000,0.0,0.0,0.0,0.0,0.0,0,0,0.0,0.0,36
559642,2022-08-22 02:00:00,24,48.2924,25.9355,22.2,18.0,78.8,9.270,100.0,20.83,0.0,0.0,37.6,17.2,338.4,1010.1,62.5,228.0,19.8,8.0,0.82,19.6,19.6,90.53,0.0,0.0,0.0,16.3,8.7,236.0,1010.1,75.6,0.0,0.1,0.0,False,False,True,False,False,True,False,False,2022,8,0,2,Chernivtsi,Europe/Kiev,2022-08-22,06:19:40,20:17:49,02:00:00,Чернівецька,0,0.000000,0.0,0.0,0.0,0.0,2.0,0,1,2.0,0.0,21
417651,2024-07-17 03:00:00,18,50.9080,34.7972,28.3,18.7,59.9,0.000,0.0,0.00,0.0,0.0,20.2,9.0,16.5,1015.9,9.2,302.1,26.1,8.0,0.37,23.1,23.1,84.99,0.0,0.0,0.0,13.0,3.6,98.0,1015.9,0.1,0.0,0.0,0.0,True,False,False,False,True,False,False,False,2024,7,2,3,Sumy,Europe/Kiev,2024-07-17,04:46:58,20:46:27,03:00:00,Сумська,1,29.050000,0.0,0.0,0.0,0.0,4.0,0,1,10.0,2.0,12
60958,2023-01-26 05:00:00,4,48.4753,35.0160,-3.0,-5.0,87.0,0.000,0.0,0.00,0.0,0.0,11.2,7.2,44.3,1027.9,62.8,50.3,4.3,2.0,0.15,-4.3,-4.3,92.03,0.0,0.0,0.0,7.9,3.6,70.0,1028.9,90.5,0.0,0.0,0.0,False,True,False,False,False,True,False,False,2023,1,3,5,Dnipro,Europe/Kiev,2023-01-26,07:17:02,16:28:22,05:00:00,Дніпропетровська,0,0.000000,0.0,0.0,1.0,0.0,12.0,0,1,2.0,2.0,1
321549,2022-08-18 10:00:00,15,46.4725,30.7371,23.6,20.0,81.2,1.000,100.0,4.17,0.0,0.0,20.9,9.7,340.4,1009.0,63.9,187.9,16.2,8.0,0.68,24.0,24.0,74.09,0.0,0.0,0.0,20.9,9.4,336.4,1009.0,60.1,516.0,1.9,5.0,False,False,True,False,False,True,False,False,2022,8,3,10,Odesa,Europe/Kiev,2022-08-18,05:58:58,20:02:06,10:00:00,Одеська,0,0.000000,0.0,0.0,0.0,0.0,1.0,0,0,3.0,0.0,22
505549,2022-07-02 23:00:00,22,49.4168,26.9743,24.5,14.1,54.5,0.000,0.0,0.00,0.0,0.0,27.7,12.2,110.0,1018.5,66.9,328.8,28.5,8.0,0.09,22.5,22.5,61.76,0.0,0.0,0.0,11.2,4.7,118.4,1020.0,100.0,0.0,0.1,0.0,False,True,False,False,False,True,False,False,2022,7,5,23,Khmelnytskyi,Europe/Kiev,2022-07-02,05:10:37,21:21:27,23:00:00,Хмельницька,0,0.000000,0.0,0.0,0.0,0.0,0.0,1,1,0.0,0.0,130
93259,2023-09-27 06:00:00,5,48.0020,37.8145,18.9,6.4,46.9,0.000,0.0,0.00,0.0,0.0,38.9,17.6,65.1,1024.9,0.0,180.6,15.5,6.0,0.43,13.4,13.4,65.20,0.0,0.0,0.0,19.8,11.5,56.3,1025.0,0.0,0.0,0.0,0.0,True,False,False,False,True,False,False,False,2023,9,2,6,Donetsk,Europe/Kiev,2023-09-27,06:21:36,18:17:22,06:00:00,Донецька,0,0.000000,1.0,1.0,0.0,1.0,13.0,0,1,4.0,1.0,0
499918,2024-11-16 07:00:00,21,46.6401,32.6142,3.6,-0.5,75.6,0.000,0.0,0.00,0.0,0.0,30.6,16.6,314.9,1022.2,76.7,50.6,4.3,2.0,0.52,1.8,-2.3,78.16,0.0,0.0,0.0,28.8,15.5,338.6,1022.0,83.9,0.0,0.0,0.0,False,True,False,False,False,True,False,False,2024,11,5,7,Kherson,Europe/Kiev,2024-11-16,06:53:43,16:14:37,07:00:00,Херсонська,0,0.000000,0.0,0.0,0.0,0.0,6.0,1,0,6.0,0.0,6
541004,2023-07-13 10:00:00,23,49.4407,32.0637,22.6,15.0,63.3,0.200,100.0,8.33,0.0,0.0,36.4,21.2,193.1,1013.0,63.5,229.6,19.8,7.0,0.85,22.4,22.4,54.21,0.0,0.0,0.0,30.6,14.8,206.7,1014.0,42.0,568.2,2.0,6.0,False,False,True,False,False,True,False,False,2023,7,3,10,Cherkasy,Europe/Kiev,2023-07-13,04:59:18,20:55:10,10:00:00,Черкаська,0,0.000000,0.0,0.0,0.0,0.0,4.0,0,0,1.0,0.0,6

In [13]:
df_isw_matrix.sample(10)

,date,isw_topic_0,isw_topic_1,isw_topic_2,isw_topic_3,isw_topic_4,isw_topic_5,isw_topic_6,isw_topic_7,isw_topic_8,isw_topic_9,isw_topic_10,isw_topic_11,isw_topic_12,isw_topic_13,isw_topic_14,isw_topic_15,isw_topic_16,isw_topic_17,isw_topic_18,isw_topic_19,isw_topic_20,isw_topic_21,isw_topic_22,isw_topic_23,isw_topic_24,isw_topic_25,isw_topic_26,isw_topic_27,isw_topic_28,isw_topic_29,isw_topic_30,isw_topic_31,isw_topic_32,isw_topic_33,isw_topic_34,isw_topic_35,isw_topic_36,isw_topic_37,isw_topic_38,isw_topic_39,isw_topic_40,isw_topic_41,isw_topic_42,isw_topic_43,isw_topic_44,isw_topic_45,isw_topic_46,isw_topic_47,isw_topic_48,isw_topic_49,isw_topic_50,isw_topic_51,isw_topic_52,isw_topic_53,isw_topic_54,isw_topic_55,isw_topic_56,isw_topic_57,isw_topic_58,isw_topic_59,isw_topic_60,isw_topic_61,isw_topic_62,isw_topic_63,isw_topic_64,isw_topic_65,isw_topic_66,isw_topic_67,isw_topic_68,isw_topic_69,isw_topic_70,isw_topic_71,isw_topic_72,isw_topic_73,isw_topic_74,isw_topic_75,isw_topic_76,isw_topic_77,isw_topic_78,isw_topic_79,isw_topic_80,isw_topic_81,isw_topic_82,isw_topic_83,isw_topic_84,isw_topic_85,isw_topic_86,isw_topic_87,isw_topic_88,isw_topic_89,isw_topic_90,isw_topic_91,isw_topic_92,isw_topic_93,isw_topic_94,isw_topic_95,isw_topic_96,isw_topic_97,isw_topic_98,isw_topic_99,isw_topic_100,isw_topic_101,isw_topic_102,isw_topic_103,isw_topic_104,isw_topic_105,isw_topic_106,isw_topic_107,isw_topic_108,isw_topic_109,isw_topic_110,isw_topic_111,isw_topic_112,isw_topic_113,isw_topic_114,isw_topic_115,isw_topic_116,isw_topic_117,isw_topic_118,isw_topic_119,isw_topic_120,isw_topic_121,isw_topic_122,isw_topic_123,isw_topic_124,isw_topic_125,isw_topic_126,isw_topic_127,isw_topic_128,isw_topic_129,isw_topic_130,isw_topic_131,isw_topic_132,isw_topic_133,isw_topic_134,isw_topic_135,isw_topic_136,isw_topic_137,isw_topic_138,isw_topic_139,isw_topic_140,isw_topic_141,isw_topic_142,isw_topic_143,isw_topic_144,isw_topic_145,isw_topic_146,isw_topic_147,isw_topic_148,isw_topic_149
476,2023-06-17,0.771852,-0.185982,-0.087620,-0.064521,-0.093318,0.096884,0.025313,0.026478,-0.112319,0.113582,0.027761,0.161396,-0.082255,0.039890,0.008128,-0.085181,-0.038895,0.004820,0.033247,-0.009073,0.085051,0.010810,0.029528,-0.019612,0.029960,-0.062320,0.004967,-0.019809,-0.016240,-0.015038,-0.084560,-0.005676,0.052297,-0.036054,0.012347,0.004358,-0.045601,0.014039,-0.022453,0.018126,-0.036409,-0.037863,-0.066028,-0.093790,0.078159,-0.014084,0.017645,-0.056756,0.029922,-0.027201,0.021642,0.002797,0.055198,-0.024372,-0.030874,0.013387,0.010554,0.047862,0.014339,0.054929,0.002446,0.043620,-0.024838,0.015616,-0.041019,-0.042120,0.011651,-0.052155,-0.013579,0.034463,0.048394,-0.063770,0.043129,-0.009714,-0.020040,0.006054,-0.056869,-0.022954,-0.028101,0.000157,-0.003192,0.000913,-0.014853,-0.016374,0.050575,0.060122,0.009242,-0.030965,0.048860,-0.047804,-0.009138,0.024654,-0.016397,0.035929,-0.005852,0.000161,0.060528,-0.007489,-0.004289,0.013465,0.035507,0.022537,-0.008198,-0.013873,-0.024556,-0.038209,-0.073010,-0.006038,-0.007731,0.027309,-0.006509,-0.010957,0.032716,0.001310,0.004550,-0.029069,0.021539,0.051481,-0.046010,0.002111,0.009508,0.039940,0.024596,0.016278,-0.022953,0.023360,0.037625,0.000632,-0.032786,0.023138,-0.030634,-0.006287,-0.017008,-0.017396,0.009800,0.000658,0.002732,-0.021685,0.009420,0.000091,0.012596,0.000425,-0.014978,-0.015641,-0.013823,0.010228,-0.033134,-0.013788,-0.014273,0.014020
1247,2025-08-03,0.801591,0.282454,0.132537,-0.088477,-0.133454,0.093214,-0.017846,0.132965,0.110878,-0.050596,0.102088,-0.006794,-0.117475,-0.097799,-0.040836,-0.019058,0.012927,0.004710,-0.007879,0.012942,-0.062645,0.012944,0.029404,-0.012616,-0.060775,0.083123,-0.009078,0.034464,-0.032402,0.020468,-0.004073,-0.005226,-0.001602,0.043697,0.018273,-0.006623,0.016680,0.010126,-0.003353,0.012944,-0.005818,0.019297,0.019035,0.014342,0.012017,0.002447,-0.006419,0.004043,-0.017366,0.014667,-0.009565,0.002654,0.017363,0.029377,0.009296,-0.012470,-0.014540,-0.007841,0.016374,-0.006714,0.015724,-0.000538,0.024045,-0.002321,-0.018292,0.019560,0.027814,-0.026373,-0.012385,-0.008990,0.001103,0.014725,-0.008694,0.021443,-0.034159,-0.022489,-0.007462,0.002336,0.021920,-0.023718,-0.014775,0.011735,0.013839,0.006441,-0.010060,0.014383,0.017711,0.005096,0.016188,-0.003110,0.031903,0.010621,-0.008690,0.014039,0.021313,-0.018270,0.001239,0.006914,-0.024393,-0.031398,-0.007233,-0.016806,0.005820,-0.020974,0.000352,0.003556,0.019155,0.013055,-0.017711,0.006408,0.001501,-0.021155,-0.007838,-0.009038,0.011964,-0.029156,-0.005676,-0.009246,-0.001704,0.001570,0.002958,0.005642,-0.021929,0.016184,0.029127,-0.015659,0.010580,-0.014302,0.010095,0.003746,0.002001,0.009376,-0.008345,-0.023300,-0.013723,0.007775,-0.036826,0.009278,0.007818,-0.006626,0.010596,-0.013248,-0.003308,0.001379,0.009370,-0.008679,-0.019821,-0.025114,0.018424,0.002485
1026,2024-12-23,0.794720,0.166379,-0.074132,0.029040,0.100208,-0.085843,0.241527,0.005297,-0.008180,-0.192912,-0.084669,-0.007861,-0.084027,0.021602,0.158793,0.034953,-0.017014,-0.074655,-0.051346,-0.027168,-0.000377,0.067726,-0.014366,-0.082982,0.019896,-0.026459,-0.045002,0.063748,-0.054828,0.073793,0.005525,-0.035685,0.012807,0.002051,-0.015324,0.085014,-0.010134,-0.018149,-0.001446,-0.012799,0.051261,0.032400,-0.020699,0.037856,-0.013698,0.022121,-0.019967,-0.015677,-0.028719,-0.027045,0.022991,-0.000445,0.036144,-0.018851,-0.004456,0.017728,-0.014718,-0.024953,-0.016350,0.021143,0.003710,0.035901,0.016736,-0.013333,-0.003818,-0.030982,-0.010748,-0.022818,-0.056478,0.000378,-0.011814,0.013093,-0.006189,-0.016266,0.017911,0.051200,0.013091,-0.017929,-0.041078,-0.028506,-0.000456,-0.025588,0.002900,-0.009864,0.022689,-0.009705,0.027490,-0.004222,0.028274,-0.019313,-0.003347,-0.007536,0.001257,-0.000153,-0.030415,-0.014206,-0.023565,0.026348,0.018053,0.017251,0.012749,0.005957,-0.026182,-0.004684,0.027136,0.010373,-0.006694,0.036060,-0.011196,0.011025,-0.017885,0.005199,-0.009748,0.010327,-0.002643,0.007358,0.003417,0.023858,-0.009549,-0.016522,-0.007215,0.022892,-0.002923,0.010568,-0.008986,-0.005810,0.002785,0.000374,-0.003235,0.007846,0.006869,0.006990,0.019950,0.018297,-0.017379,0.011908,0.002269,0.001109,-0.003887,0.009412,0.009704,-0.020732,0.015587,0.006863,0.009365,0.007553,-0.011796,0.006340,-0.005371,-0.007873
326,2023-01-18,0.753861,-0.191788,-0.105814,-0.011380,0.268632,0.207352,-0.097987,-0.041178,0.005722,0.014024,0.022851,-0.000415,-0.067743,0.007186,-0.031807,0.133063,-0.013608,-0.072392,0.098358,-0.038261,-0.014183,-0.077555,-0.012574,0.005544,-0.022493,0.043736,0.052146,-0.089374,-0.059155,-0.002919,0.031252,0.064239,-0.015791,0.047654,-0.002486,-0.015907,0.034686,0.046328,-0.034956,-0.027434,0.033863,0.023130,-0.028458,-0.017590,0.078449,0.001919,0.025135,-0.036301,-0.022177,-0.044082,-0.002451,0.007480,-0.022508,0.000774,0.004599,-0.024955,0.018072,-0.020137,-0.011647,0.101846,-0.025327,-0.003088,-0.020889,0.002146,-0.016761,0.034490,0.031782,-0.011158,0.029256,-0.024558,-0.017413,-0.027429,-0.019098,-0.012431,0.004404,-0.015427,-0.042866,0.015414,0.003882,0.035415,-0.015191,-0.043637,0.050701,0.003904,-0.026440,-0.020422,0.039163,-0.020776,0.005334,-0.006784,0.030714,-0.022170,0.017198,-0.024787,0.010723,-0.012575,-0.018312,0.035255,0.002602,-0.000836,0.031629,0.007059,-0.018099,0.002231,0.024437,0.006997,0.017660,0.039503,0.007757,0.004117,-0.001945,0.004132,0.021901,-0.003983,-0.016778,0.002418,0.013407,0.002178,0.025463,0.016451,0.007612,0.007264,0.008108,-0.001520,0.020088,-0.028133,-0.031145,0.002234,0.003897,-0.008245,0.007406,0.013441,0.018471,-0.006946,0.014053,0.004951,-0.001219,0.014869,0.014653,0.017964,0.009520,-0.022894,0.009350,-0.000211,-0.023538,-0.015215,-0.015602,0.027734,0.004420,0.010753
163,2022-08-05,0.764282,-0.217895,0.176382,-0.087230,-0.036731,0.076793,0.011871,0.030564,0.124446,-0.101993,0.024530,-0.010216,-0.003561,-0.121259,-0.091179,0.063528,-0.119619,0.070253,-0.084366,0.008523,-0.036849,-0.010781,0.027906,-0.055185,0.071527,0.028272,-0.043383,-0.009354,-0.031054,-0.011109,0.029434,0.025509,0.057916,-0.012026,-0.041186,0.002588,0.014353,0.014481,0.042560,-0.036726,-0.017404,0.021330,-0.007644,-0.011079,0.014094,-0.032082,0.002299,0.028762,-0.007608,-0.017864,-0.003346,-0.015346,-0.004946,-0.012200,0.014913,-0.018989,0.038780,-0.029713,-0.011714,-0.000700,0.004052,-0.024076,-0.020887,-0.034106,0.047913,0.008830,0.018687,0.025315,-0.017950,0.007226,-0.011734,-0.018808,-0.011940,-0.015823,0.009258,-0.014761,-0.033821,0.029567,0.032860,-0.017004,-0.004968,-0.018358,-0.026997,-0.063184,0.012218,-0.021524,0.002957,0.004624,-0.009982,-0.029018,0.024249,-0.023561,0.006255,-0.018006,0.019480,-0.006173,0.000935,-0.023697,-0.016607,-0.005876,0.004648,0.003603,0.042693,-0.007198,-0.007631,-0.020610,-0.023554,0.030049,0.001701,-0.002564,-0.008767,0.034081,0.003548,0.019770,0.009948,0.003291,-0.027672,-0.023730,-0.027520,-0.003002,-0.019575,0.023423,-0.017992,0.015113,-0.023103,-0.015975,-0.015649,-0.006913,0.034295,-0.009479,-0.001381,0.038252,0.024447,-0.000426,0.013924,0.028535,-0.005039,-0.005971,0.026568,0.026210,-0.026743,0.015567,-0.009306,-0.000408,-0.013338,0.001898,-0.022414,0.000906,0.004300,0.007309
605,2023-10-24,0.776786,-0.066504,-0.116346,-0.183990,-0.059251,-0.158558,-0.176294,-0.059305,-0.115588,-0.062321,-0.089967,-0.030948,-0.085079,-0.028665,0.010437,-0.143418,0.020602,0.107974,0.049430,-0.065133,-0.075135,-0.018176,-0.003981,0.016514,0.041426,-0.000874,0.009061,-0.026225,0.037432,-0.003726,-0.012866,-0.038542,0.028864,-0.007304,-0.001601,-0.036541,0.018295,-0.035704,0.002425,0.008237,0.071268,-0.001855,0.022087,0.002775,-0.001759,-0.049083,-0.007040,0.019528,0.031285,-0.006385,0.007446,-0.012070,0.011796,-0.014816,0.005589,-0.035167,-0.044314,0.031128,0.038297,-0.037054,-0.007179,0.013699,0.009912,-0.006049,-0.011923,-0.008114,0.033164,-0.038059,0.024672,0.021248,0.022901,0.021339,-0.002632,-0.017167,-0.006639,-0.028028,-0.025254,0.021267,0.007768,0.035534,-0.011901,-0.000601,0.009284,0.002696,-0.016371,-0.020381,-0.025636,0.011891,0.007322,0.021010,0.029344,0.013278,-0.008035,0.008338,-0.009896,-0.019501,-0.003283,-0.024240,-0.016831,-0.018354,-0.008654,0.008622,-0.010452,-0.054885,0.028541,0.014149,0.008726,-0.001534,-0.028026,0.022438,-0.007894,0.013898,0.041014,-0.039743,-0.016775,0.049327,0.019045,-0.030818,0.025176,0.013494,-0.027889,-0.000028,0.000776,0.044443,0.038002,0.033269,0.010699,0.013441,-0.005156,-0.013347,-0.010256,-0.010907,0.014421,-0.007035,0.008412,-0.003433,0.025218,-0.030560,0.024576,0.053691,0.011335,-0.020963,-0.005620,0.016724,0.011906,-0.011407,0.015165,-0.007774,-0.009385,-0.047869
1278,2025-09-03,0.831265,0.221099,0.072824,-0.098764,-0.033152,0.026448,-0.037564,0.123513,-0.038259,-0.013505,0.060836,0.032006,0.122233,0.135070,-0.065478,0.065876,0.059303,-0.045891,0.041888,-0.043178,-0.000266,-0.063365,-0.017990,0.013777,0.019275,0.011068,-0.015916,-0.022822,-0.012489,0.036707,0.001548,0.002695,0.011825,0.063511,-0.015087,-0.024761,-0.028129,0.028564,-0.018884,0.001450,-0.002469,0.041854,0.003747,-0.034130,0.002271,0.012036,-0.009796,0.014608,-0.005699,0.043105,0.025571,-0.047309,0.044411,0.005196,-0.002845,0.045396,0.000534,0.009298,0.017573,0.003110,0.003411,0.045560,-0.029049,-0.012737,0.007009,0.007007,-0.014241,0.009015,-0.018633,-0.024114,0.026178,0.011803,0.000700,0.007290,0.022071,-0.040809,-0.057455,-0.002094,-0.011748,-0.028367,-0.033789,-0.012104,-0.004005,-0.001771,-0.007697,-0.001450,-0.007942,-0.004756,-0.023556,0.008870,0.000112,0.002549,0.029598,-0.015181,0.024312,-0.039554,-0.005273,-0.017290,0.013551,-0.023326,-0.013394,0.002101,0.005190,0.004663,0.004234,-0.007291,-0.026371,-0.006283,0.048086,-0.017032,0.007315,0.014187,0.013705,0.011833,-0.026414,0.012754,0.006306,-0.016043,-0.022193,-0.014668,-0.035987,-0.024909,-0.026601,0.003985,-0.017456,0.006214,-0.001116,0.028351,0.014674,0.002013,-0.014526,0.017890,-0.034743,0.043874,0.011425,0.002520,0.003759,-0.001988,0.008406,-0.009980,0.028873,-0.017172,-0.021646,-0.012162,0.033667,0.002775,0.002577,-0.016178,0.001685,-0.021502
952,2024-10-09,0.782921,0.082272,-0.045650,-0.100879,-0.079747,-0.201549,-0.229201,-0.155466,-0.086047,-0.181322,-0.168689,-0.018484,-0.090475,-0.070526,0.072370,0.027649,0.006477,-0.086647,-0.048048,0.024180,0.002537,-0.085448,-0.003785,-0.036321,-0.036191,0.011953,-0.035336,-0.010134,-0.001275,-0.036019,-0.012790,0.012522,0.002886,-0.022684,-0.049969,0.026732,-0.014127,0.019679,-0.014894,0.015251,-0.041044,-0.006701,-0.002914,0.031280,0.000915,0.013923,-0.014845,-0.005471,-0.012165,-0.018029,0.017020,0.021625,-0.031445,-0.013621,-0.024046,0.000294,0.007723,-0.017502,-0.013959,-0.017737,0.016468,0.023984,0.009631,-0.010188,-0.004940,0.026091,-0.008093,0.003463,-0.010956,-0.019978,-0.013566,0.002955,0.018764,0.007428,-0.006107,-0.007791,0.004713,-0.011993,-0.027362,-0.007664,-0.001915,-0.016063,0.015404,0.002808,0.032360,0.029304,0.020087,-0.006904,0.019620,0.011310,0.033612,0.014493,-0.009425,-0.032244,0.001824,-0.006104,-0.029655,0.030312,0.025113,-0.002414,-0.011440,-0.018559,0.019129,-0.023932,-0.038618,-0.003036,-0.009179,-0.016846,0.004461,-0.016985,-0.001554,-0.005544,0.016650,0.011476,-0.001224,-0.008908,0.005517,0.003097,0.017768,-0.008616,-0.007144,-0.015142,0.017200,0.001465,-0.022855,0.013753,0.004487,-0.009838,-0.008848,-0.020121,0.025540,0.002599,0.014751,0.012999,0.001771,-0.028518,0.018173,0.009186,-0.001197,-0.008183,-0.003293,0.016535,-0.032146,0.007796,-0.001123,0.010378,0.005994,0.001970,-0.021984,0.000025
157,2022-07-30,0.726539,-0.218846,0.263573,-0.034923,-0.078865,0.108892,0.064242,-0.098231,0.005888,0.007454,-0.108855,-0.132946,0.058891,-0.021668,-0.018319,0.023939,-0.075197,0.079565,-0.073793,-0.013688,0.028441,-0.025760,-0.010212,-0.073543,0.035998,0.010382,-0.020044,-0.118535,0.051493,0.019636,-0.010110,-0.004970,-0.020912,0.014296,-0.014133,0.045326,0.034381,-0.020776,-0.022415,-0.007666,0.017127,-0.022910,0.028884,-0.063649,-0.047374,0.013514,0.027417,-0.050525,-0.035034,-0.039341,0.046677,0.014929,0.016564,0.078877,0.037161,-0.007679,-0.015243,-0.008696,0.030459,-0.002149,-0.008850,-0.009806,0.017767,-0.002032,0.028049,0.001531,0.025144,-0.052216,-0.008046,0.026758,0.009272,0.014357,-0.015763,-0.074409,0.035894,0.016037,0.021154,0.009620,0.024821,-0.005898,0.000559,0.040297,-0.060449,0.045929,0.013750,0.025601,-0.014770,-0.040097,0.020825,0.009795,-0.001089,0.008801,0.045250,-0.020059,-0.063420,-0.000019,0.007907,0.012406,0.010836,-0.021460,0.050948,0.011769,-0.019244,0.027055,0.017133,-0.042100,0.033199,0.018966,-0.023284,-0.003333,-0.011444,-0.024443,-0.005463,-0.017250,0.003866,-0.015257,0.020468,-0.024410,0.024265,-0.010576,0.014412,-0.009791,0.000319,0.001850,-0.007350,-0.011356,0.043213,0.011588,-0.019819,0.023675,0.047233,0.037345,-0.068160,0.035088,0.036072,-0.046956,0.021690,-0.011463,0.021807,-0.032639,-0.027169,-0.009972,0.005782,0.015046,0.009266,-0.021475,0.023941,-0.015591,0.047441,0.009883
503,2023-07-14,0.790640,-0.201901,-0.067027,-0.101954,-0.120947,0.167597,0.049529,-0.008316,-0.097554,0.144910,-0.054688,-0.192783,-0.023322,0.044187,0.058190,-0.090978,-0.017779,-0.018958,0.046588,-0.007379,0.085998,0.035967,0.026650,0.009627,0.033499,-0.005446,0.020213,0.018311,-0.021251,0.032783,0.029505,0.031902,0.004677,-0.019667,-0.002729,-0.027377,-0.021650,0.011023,-0.014136,-0.029185,0.016211,-0.006309,-0.009728,0.012762,0.009921,-0.003795,-0.006034,0.030886,-0.024696,0.019518,0.016435,-0.013479,0.022817,-0.045929,0.016639,-0.017816,0.022844,-0.015425,-0.012577,0.016283,-0.023835,-0.008073,0.004176,-0.016390,0.029466,-0.000517,0.000615,-0.007972,-0.024569,-0.035656,-0.008559,-0.009006,0.024679,0.000338,-0.031371,-0.011634,0.004764,0.004613,0.042588,-0.015880,0.004608,-0.038735,0.013497,0.012908,-0.017868,-0.018692,-0.016621,0.014419,0.016665,-0.009795,0.054492,0.020895,0.022378,-0.009124,0.025188,0.022263,0.033595,-0.022814,0.007851,0.010774,0.027820,0.001372,-0.014925,-0.019422,-0.031750,0.012324,-0.004790,0.019030,-0.001941,0.008960,-0.016388,0.003672,0.003729,0.028121,0.001374,0.026329,0.021460,0.007858,-0.014557,-0.003833,0.008460,0.004919,-0.017091,-0.012989,0.009445,-0.002678,-0.014877,-0.011945,0.035854,-0.030248,0.001951,0.018354,0.004220,-0.028890,-0.008066,-0.010387,0.009481,-0.002289,-0.012001,-0.022483,-0.019008,-0.019566,0.015172,-0.002262,0.008822,-0.001893,-0.031343,0.001929,0.016000,0.020165

In [14]:
#df_isw_matrix["date"] = pd.to_datetime(df_isw_matrix["date"]) + pd.Timedelta(days=1)    ТУТ ЗСУВ ІСВ НА + 1 ДЕНЬ
df_isw_matrix = df_isw_matrix.rename(columns={'date': 'day_datetime'})

In [15]:
df_final['day_datetime'] = pd.to_datetime(df_final['day_datetime']).dt.date
df_isw_matrix['day_datetime'] = pd.to_datetime(df_isw_matrix['day_datetime']).dt.date
df_isw_matrix.fillna(0, inplace=True)
df_isw_matrix.isna().sum()

day_datetime     0
isw_topic_0      0
isw_topic_1      0
isw_topic_2      0
isw_topic_3      0
                ..
isw_topic_145    0
isw_topic_146    0
isw_topic_147    0
isw_topic_148    0
isw_topic_149    0
Length: 151, dtype: int64

In [16]:
df_final = df_final.merge(df_isw_matrix, on="day_datetime", how="left")

In [38]:
df_final.head(10)

,datetime_hour,region_id,city_latitude,city_longitude,day_temp,day_dew,day_humidity,day_precip,day_precipprob,day_precipcover,day_snow,day_snowdepth,day_windgust,day_windspeed,day_winddir,day_pressure,day_cloudcover,day_solarradiation,day_solarenergy,day_uvindex,day_moonphase,hour_temp,hour_feelslike,hour_humidity,hour_precip,hour_precipprob,hour_snow,hour_windgust,hour_windspeed,hour_winddir,hour_pressure,hour_cloudcover,hour_solarradiation,hour_solarenergy,hour_uvindex,day_conditions_simple_Clear,day_conditions_simple_Cloudy,day_conditions_simple_Rain,day_conditions_simple_Snow,hour_conditions_simple_Clear,hour_conditions_simple_Cloudy,hour_conditions_simple_Rain,hour_conditions_simple_Snow,year,month,day_of_week,hour,city_name,city_timezone,day_datetime,day_sunrise,day_sunset,hour_datetime,region_key,alarm_active,alarm_minutes_in_hour,alarm_lag_1,alarm_lag_3,alarm_lag_6,alarm_lag_12,alarms_in_last_24h,is_weekend,is_night,total_active_alarms_lag1,neighbour_alarms,hours_since_last_alarm,isw_topic_0,isw_topic_1,isw_topic_2,isw_topic_3,isw_topic_4,isw_topic_5,isw_topic_6,isw_topic_7,isw_topic_8,isw_topic_9,isw_topic_10,isw_topic_11,isw_topic_12,isw_topic_13,isw_topic_14,isw_topic_15,isw_topic_16,isw_topic_17,isw_topic_18,isw_topic_19,isw_topic_20,isw_topic_21,isw_topic_22,isw_topic_23,isw_topic_24,isw_topic_25,isw_topic_26,isw_topic_27,isw_topic_28,isw_topic_29,isw_topic_30,isw_topic_31,isw_topic_32,isw_topic_33,isw_topic_34,isw_topic_35,isw_topic_36,isw_topic_37,isw_topic_38,isw_topic_39,isw_topic_40,isw_topic_41,isw_topic_42,isw_topic_43,isw_topic_44,isw_topic_45,isw_topic_46,isw_topic_47,isw_topic_48,isw_topic_49,isw_topic_50,isw_topic_51,isw_topic_52,isw_topic_53,isw_topic_54,isw_topic_55,isw_topic_56,isw_topic_57,isw_topic_58,isw_topic_59,isw_topic_60,isw_topic_61,isw_topic_62,isw_topic_63,isw_topic_64,isw_topic_65,isw_topic_66,isw_topic_67,isw_topic_68,isw_topic_69,isw_topic_70,isw_topic_71,isw_topic_72,isw_topic_73,isw_topic_74,isw_topic_75,isw_topic_76,isw_topic_77,isw_topic_78,isw_topic_79,isw_topic_80,isw_topic_81,isw_topic_82,isw_topic_83,isw_topic_84,isw_topic_85,isw_topic_86,isw_topic_87,isw_topic_88,isw_topic_89,isw_topic_90,isw_topic_91,isw_topic_92,isw_topic_93,isw_topic_94,isw_topic_95,isw_topic_96,isw_topic_97,isw_topic_98,isw_topic_99,isw_topic_100,isw_topic_101,isw_topic_102,isw_topic_103,isw_topic_104,isw_topic_105,isw_topic_106,isw_topic_107,isw_topic_108,isw_topic_109,isw_topic_110,isw_topic_111,isw_topic_112,isw_topic_113,isw_topic_114,isw_topic_115,isw_topic_116,isw_topic_117,isw_topic_118,isw_topic_119,isw_topic_120,isw_topic_121,isw_topic_122,isw_topic_123,isw_topic_124,isw_topic_125,isw_topic_126,isw_topic_127,isw_topic_128,isw_topic_129,isw_topic_130,isw_topic_131,isw_topic_132,isw_topic_133,isw_topic_134,isw_topic_135,isw_topic_136,isw_topic_137,isw_topic_138,isw_topic_139,isw_topic_140,isw_topic_141,isw_topic_142,isw_topic_143,isw_topic_144,isw_topic_145,isw_topic_146,isw_topic_147,isw_topic_148,isw_topic_149,isw_total_intensity,isw_topic_std,isw_topic_max,isw_topic_mean,isw_velocity_24h,isw_intensity_ema,isw_topic_entropy,tg_topic_0,tg_topic_1,tg_topic_2,tg_topic_3,tg_topic_4,tg_topic_5,tg_topic_6,tg_topic_7,tg_topic_8,tg_topic_9,tg_topic_10,tg_topic_11,tg_topic_12,tg_topic_13,tg_topic_14,tg_topic_15,tg_topic_16,tg_topic_17,tg_topic_18,tg_topic_19,tg_topic_20,tg_topic_21,tg_topic_22,tg_topic_23,tg_topic_24,tg_topic_25,tg_topic_26,tg_topic_27,tg_topic_28,tg_topic_29,tg_topic_30,tg_topic_31,tg_topic_32,tg_topic_33,tg_topic_34,tg_topic_35,tg_topic_36,tg_topic_37,tg_topic_38,tg_topic_39,tg_topic_40,tg_topic_41,tg_topic_42,tg_topic_43,tg_topic_44,tg_topic_45,tg_topic_46,tg_topic_47,tg_topic_48,tg_topic_49,tg_topic_50,tg_topic_51,tg_topic_52,tg_topic_53,tg_topic_54,tg_topic_55,tg_topic_56,tg_topic_57,tg_topic_58,tg_topic_59,tg_topic_60,tg_topic_61,tg_topic_62,tg_topic_63,tg_topic_64,tg_topic_65,tg_topic_66,tg_topic_67,tg_topic_68,tg_topic_69,tg_topic_70,tg_topic_71,tg_topic_72,tg_topic_73,tg_topic_74,tg_topic_75,tg_topic_76,tg_topic_77,tg_topic_78,tg_topic_79,tg_topic_80,tg_topic_81,tg_topic_82,tg_topic_83,tg_topic_84,tg_topic_85,tg_topic_86,tg_topic_87,tg_topic_88,tg_topic_89,tg_topic_90,tg_topic_91,tg_topic_92,tg_topic_93,tg_topic_94,tg_topic_95,tg_topic_96,tg_topic_97,tg_topic_98,tg_topic_99,tg_topic_100,tg_topic_101,tg_topic_102,tg_topic_103,tg_topic_104,tg_topic_105,tg_topic_106,tg_topic_107,tg_topic_108,tg_topic_109,tg_topic_110,tg_topic_111,tg_topic_112,tg_topic_113,tg_topic_114,tg_topic_115,tg_topic_116,tg_topic_117,tg_topic_118,tg_topic_119,tg_topic_120,tg_topic_121,tg_topic_122,tg_topic_123,tg_topic_124,tg_topic_125,tg_topic_126,tg_topic_127,tg_topic_128,tg_topic_129,tg_topic_130,tg_topic_131,tg_topic_132,tg_topic_133,tg_topic_134,tg_topic_135,tg_topic_136,tg_topic_137,tg_topic_138,tg_topic_139,tg_topic_140,tg_topic_141,tg_topic_142,tg_topic_143,tg_topic_144,tg_topic_145,tg_topic_146,tg_topic_147,tg_topic_148,tg_topic_149,tg_topic_150,tg_topic_151,tg_topic_152,tg_topic_153,tg_topic_154,tg_topic_155,tg_topic_156,tg_topic_157,tg_topic_158,tg_topic_159,tg_topic_160,tg_topic_161,tg_topic_162,tg_topic_163,tg_topic_164,tg_topic_165,tg_topic_166,tg_topic_167,tg_topic_168,tg_topic_169,tg_topic_170,tg_topic_171,tg_topic_172,tg_topic_173,tg_topic_174,tg_topic_175,tg_topic_176,tg_topic_177,tg_topic_178,tg_topic_179,tg_topic_180,tg_topic_181,tg_topic_182,tg_topic_183,tg_topic_184,tg_topic_185,tg_topic_186,tg_topic_187,tg_topic_188,tg_topic_189,tg_topic_190,tg_topic_191,tg_topic_192,tg_topic_193,tg_topic_194,tg_topic_195,tg_topic_196,tg_topic_197,tg_topic_198,tg_topic_199,tg_topic_200,tg_topic_201,tg_topic_202,tg_topic_203,tg_topic_204,tg_topic_205,tg_topic_206,tg_topic_207,tg_topic_208,tg_topic_209,tg_topic_210,tg_topic_211,tg_topic_212,tg_topic_213,tg_topic_214,tg_topic_215,tg_topic_216,tg_topic_217,tg_topic_218,tg_topic_219,tg_topic_220,tg_topic_221,tg_topic_222,tg_topic_223,tg_topic_224,tg_topic_225,tg_topic_226,tg_topic_227,tg_topic_228,tg_topic_229,tg_topic_230,tg_topic_231,tg_topic_232,tg_topic_233,tg_topic_234,tg_topic_235,tg_topic_236,tg_topic_237,tg_topic_238,tg_topic_239,tg_topic_240,tg_topic_241,tg_topic_242,tg_topic_243,tg_topic_244,tg_topic_245,tg_topic_246,tg_topic_247,tg_topic_248,tg_topic_249,tg_total_intensity,tg_topic_std,tg_topic_max,tg_topic_entropy
0,2022-02-24,2,49.23360,28.44860,2.8,-0.3,80.5,0.3,100.0,4.17,0.0,0.0,27.7,10.8,312.0,1023.4,82.5,60.4,5.4,3.0,0.77,2.1,-0.5,91.76,0.0,0.0,0.0,16.6,8.6,279.6,1021.0,91.1,0.0,0.1,0.0,False,False,False,True,False,True,False,False,2022,2,3,0,Vinnytsia,Europe/Kiev,2022-02-24,06:58:49,17:40:52,00:00:00,Вінницька,0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0.0,0.0,1,0.648336,-0.079572,0.178041,0.061854,0.073453,-0.055809,-0.011311,0.047310,0.008354,0.006474,-0.047099,0.020496,0.050190,-0.038573,0.057228,-0.072471,0.045393,-0.116783,0.168249,0.167355,-0.025072,-0.073858,-0.097024,-0.146191,0.027983,0.082989,0.014423,0.058370,-0.033928,0.046265,0.006901,-0.049498,0.126117,-0.089039,-0.006767,-0.031686,-0.010346,0.025637,0.061278,0.162580,-0.028081,0.161291,-0.018217,-0.002657,0.038485,-0.000530,0.044413,0.107176,-0.050721,0.064279,-0.066677,0.016742,-0.050257,0.072549,-0.035201,-0.027279,0.017115,0.043631,0.024660,-0.025841,0.031320,-0.076959,-0.072986,-0.040465,0.003958,-0.022475,0.033208,-0.028056,-0.005499,-0.055998,-0.021882,-0.070462,0.018237,-0.031396,-0.074606,0.072951,0.039997,0.036423,-0.027152,-0.071900,0.026267,-0.046270,-0.017945,0.007933,-0.006203,-0.046099,0.032793,-0.069113,0.020403,0.030783,-0.003787,-0.000490,-0.022951,0.013498,0.009664,-0.007012,-0.016325,-0.005732,0.036069,-0.063906,0.033891,0.010560,-0.104517,-0.022069,0.054322,-0.005460,-0.029093,0.040991,-0.053018,-0.024017,0.050817,-0.003297,-0.020895,-0.053213,-0.028428,0.048231,-0.001221,0.001302,-0.044137,0.015528,-0.012792,-0.012009,-0.008211,0.031114,0.024982,0.003863,-0.032321,0.030920,-0.012845,0.070170,-0.004037,0.014003,0.005577,0.021611,-0.002889,0.034824,0.047164,0.050545,-0.017639,0.029014,-0.030378,-0.027056,0.011464,-0.039759,-0.043514,-0.025605,-0.022484,-0.036224,0.000566,0.005481,6.699346,0.061318,0.648336,0.044662,0.0,0.000000,4.528176,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-0.0
476443,2022-02-24,21,46.64010,32.61420,5.3,-1.0,65.8,0.0,0.0,0.00,0.0,0.0,28.1,18.4,27.5,1021.5,87.7,135.2,11.8,4.0,0.77,4.9,3.1,67.56,0.0,0.0,0.0,11.2,7.6,29.4,1020.0,100.0,0.0,0.1,0.0,False,True,False,False,False,True,False,False,2022,2,3,0,Kherson,Europe/Kiev,2022-02-24,06:38:31,17:27:46,00:00:00,Херсонська,0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0.0,0.0,1,0.580161,-0.090608,-0.028388,0.146350,0.071072,-0.030284,-0.004583,0.087399,-0.038512,0.016613,-0.038599,0.049747,0.186305,-0.172198,-0.045515,0.050785,0.041889,-0.112849,0.193473,-0.010566,0.044308,-0.118300,0.007117,-0.135687,-0.009441,-0.039465,0.032843,0.080393,-0.035434,0.010352,-0.016680,-0.046252,0.085840,-0.123167,0.064510,-0.023735,-0.025637,-0.027863,0.032156,0.068641,0.027667,0.162729,0.039675,-0.016915,-0.008203,0.048024,0.073343,0.025782,-0.013935,-0.008775,-0.045265,0.008979,-0.100558,0.044074,0.018202,-0.037279,0.062349,0.008014,0.075917,-0.063409,0.015404,-0.091507,-0.079240,-0.033000,-0.019226,-0.103926,0.031514,0.043306,-0.012137,-0.010430,0.035901,-0.013437,-0.042046,-0.064986,0.002947,0.024326,0.085592,-0.008453,0.091087,-0.106852,0.038223,-0.061062,0.027905,0.056421,-0.030501,0.000050,0.051385,-0.087324,-0.024025,0.031626,-0.029461,0.015717,-0.047181,-0.005600,0.049867,0.084412,-0.055460,-0.036620,0.120475,-0.012080,0.006961,-0.079701,0.055655,0.004130,0.013250,0.002392,0.041937,0.028208,-0.037232,0.014886,-0.036905,0.000138,-0.018200,-0.010680,-0.067564,-0.001064,-0.044792,-0.014807,-0.031911,-0.023504,0.070783,0.027626,0.000418,0.043677,-0.030193,-0.034979,0.080093,0.035489,-0.004156,-0.008032,0.039826,-0.037380,0.011931,0.008267,0.000590,0.043862,0.023758,0.038714,0.066128,0.028168,-0.012153,0.005376,0.008085,-0.038933,0.003404,0.003281,-0.004149,-0.025392,0.010434,-0.017613,6.990334,0.058342,0.580161,0.046602,0.0,6.699346,4.547433,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-0.0
132346,2022-02-24,7,48.62636,22.28514,1.8,-1.6,79.9,0.0,0.0,0.00,0.0,7.8,24.1,14.1,142.5,1025.6,48.1,142.7,10.2,4.0,0.77,-1.2,-1.2,91.15,0.0,0.0,0.0,3.6,4.4,100.0,1026.2,55.6,0.0,0.1,0.0,False,True,False,False,False,True,False,False,2022,2,3,0,Uzhgorod,Europe/Uzhgorod,2022-02-24,07:22:33,18:06:25,00:00:00,Закарпатська,0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0.0,0.0,1,0.580161,-0.090608,-0.028388,0.146350,0.071072,-0.030284,-0.004583,0.087399,-0.038512,0.016613,-0.038599,0.049747,0.186305,-0.172198,-0.045515,0.050785,0.041889,-0.112849,0.193473,-0.010566,0.044308,-0.118300,0.007117,-0.135687,-0.009441,-0.039465,0.032843,0.080393,-0.035434,0.010352,-0.016680,-0.046252,0.085840,-0.123167,0.064510,-0.023735,-0.025637,-0.027863,0.032156,0.068641,0.027667,0.162729,0.039675,-0.016915,-0.008203,0.048024,0.073343,0.025782,-0.013935,-0.008775,-0.045265,0.008979,-0.100558,0.044074,0.018202,-0.037279,0.062349,0.008014,0.075917,-0.063409,0.015404,-0.091507,-0.079240,-0.033000,-0.019226,-0.103926,0.031514,0.043306,-0.012137,-0.010430,0.035901,-0.013437,-0.042046,-0.064986,0.002947,0.024326,0.085592,-0.008453,0.091087,-0.106852,0.038223,-0.061062,0.027905,0.056421,-0.030501,0.000050,0.051385,-0.087324,-0.024025,0.031626,-0.029461,0.015717,-0.047181,-0.005600,0.049867,0.084412,-0.055460,-0.036620,0.120475,-0.012080,0.006961,-0.079701,0.055655,0.004130,0.013250,0.002392,0.041937,0.028208,-0.037232,0.014886,-0.036905,0.000138,-0.018200,-0.010680,-0.067564,-0.001064,-0.044792,-0.014807,-0.031911,-0.023504,0.070783,0.027626,0.000418,0.043677,-0.030193,-0.034979,0.080093,0.035489,-0.004156,-0.008032,0.039826,-0.037380,0.011931,0.008267,0.000590,0.043862,0.023758,0.038714,0.066128,0.028168,-0.012153,0.005376,0.008085,-0.038933,0.003404,0.003281,-0.004149,-0.025392,0.010434,-0.017613,6.990334,0.058342,0.580161,0.046602,0.0,6.699346,4.547433,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-0.0
132345,2022-02-24,7,48.62636,22.28514,1.8,-1.6,79.9,0.0,0.0,0.00,0.0,7.8,24.1,14.1,142.5,1025.6,48.1,142.7,10.2,4.0,0.77,-1.2,-1.2,91.15,0.0,0.0,0.0,3.6,4.4,100.0,1026.2,55.6,0.0,0.1,0.0,False,True,False,False,False,True,False,False,2022,2,3,0,Uzhgorod,Europe/Uzhgorod,2022-02-24,07:22:33,18:06:25,00:00:00,Закарпатська,0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0.0,0.0,1,0.648336,-0.079572,0.178041,0.061854,0.073453,-0.055809,-0.011311,0.047310,0.008354,0.006474,-0.047099,0.020496,0.050190,-0.038573,0.057228,-0.072471,0.045393,-0.116783,0.168249,0.167355,-0.025072,-0.073858,-0.097024,-0.146191,0.027983,0.082989,0.014423,0.058370,-0.033928,0.046265,0.006901,-0.049498,0.126117,-0.089039,-0.006767,-0.031686,-0.010346,0.025637,0.061278,0.162580,-0.028081,0.161291,-0.018217,-0.002657,0.038485,-0.000530,0.044413,0.107176,-0.050721,0.064279,-0.066677,0.016742,-0.050257,0.072549,-0.035201,-0.027279,0.017115,0.043631,0.024660,-0.025841,0.031320,-0.076959,-0.072986,-0.040465,0.003958,-0.022475,0.033208,-0.028056,-0.005499,-0.055998,-0.021882,-0.070462,0.018237,-0.031396,-0.074606,0.072951,0.039997,0.036423,-0.027152,-0.071900,0.026267,-0.046270,-0.017945,0.007933,-0.006203,-0.046099,0.032793,-0.069113,0.020403,0.030783,-0.003787,-0.000490,-0.022951,0.013498,0.009664,-0.007012,-0.016325,-0.005732,0.036069,-0.063906,0.033891,0.010560,-0.104517,-0.022069,0.054322,-0.005460,-0.029093,0.040991,-0.053018,-0.024017,0.050817,-0.003297,-0.020895,-0.053213,-0.028428,0.048231,-0.001221,0.001302,-0.044137,0.015528,-0.012792,-0.012009,-0.008211,0.031114,0.024982,0.003863,-0.032321,0.030920,-0.012845,0.070170,-0.004037,0.014003,0.005577,0.021611,-0.002889,0.034824,0.047164,0.050545,-0.017639,0.029014,-0.030378,-0.027056,0.011464,-0.039759,-0.043514,-0.025605,-0.022484,-0.036224,0.000566,0.005481,6.699346,0.061318,0.648336,0.044662,0.0,0.000000,4.528176,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-0.0

In [18]:
df_final.isna().sum()

datetime_hour        0
region_id            0
city_latitude        0
city_longitude       0
day_temp             0
                  ...
isw_topic_145     5760
isw_topic_146     5760
isw_topic_147     5760
isw_topic_148     5760
isw_topic_149     5760
Length: 216, dtype: int64

In [19]:
df_final.fillna(0, inplace=True)

,datetime_hour,region_id,city_latitude,city_longitude,day_temp,day_dew,day_humidity,day_precip,day_precipprob,day_precipcover,day_snow,day_snowdepth,day_windgust,day_windspeed,day_winddir,day_pressure,day_cloudcover,day_solarradiation,day_solarenergy,day_uvindex,day_moonphase,hour_temp,hour_feelslike,hour_humidity,hour_precip,hour_precipprob,hour_snow,hour_windgust,hour_windspeed,hour_winddir,hour_pressure,hour_cloudcover,hour_solarradiation,hour_solarenergy,hour_uvindex,day_conditions_simple_Clear,day_conditions_simple_Cloudy,day_conditions_simple_Rain,day_conditions_simple_Snow,hour_conditions_simple_Clear,hour_conditions_simple_Cloudy,hour_conditions_simple_Rain,hour_conditions_simple_Snow,year,month,day_of_week,hour,city_name,city_timezone,day_datetime,day_sunrise,day_sunset,hour_datetime,region_key,alarm_active,alarm_minutes_in_hour,alarm_lag_1,alarm_lag_3,alarm_lag_6,alarm_lag_12,alarms_in_last_24h,is_weekend,is_night,total_active_alarms_lag1,neighbour_alarms,hours_since_last_alarm,isw_topic_0,isw_topic_1,isw_topic_2,isw_topic_3,isw_topic_4,isw_topic_5,isw_topic_6,isw_topic_7,isw_topic_8,isw_topic_9,isw_topic_10,isw_topic_11,isw_topic_12,isw_topic_13,isw_topic_14,isw_topic_15,isw_topic_16,isw_topic_17,isw_topic_18,isw_topic_19,isw_topic_20,isw_topic_21,isw_topic_22,isw_topic_23,isw_topic_24,isw_topic_25,isw_topic_26,isw_topic_27,isw_topic_28,isw_topic_29,isw_topic_30,isw_topic_31,isw_topic_32,isw_topic_33,isw_topic_34,isw_topic_35,isw_topic_36,isw_topic_37,isw_topic_38,isw_topic_39,isw_topic_40,isw_topic_41,isw_topic_42,isw_topic_43,isw_topic_44,isw_topic_45,isw_topic_46,isw_topic_47,isw_topic_48,isw_topic_49,isw_topic_50,isw_topic_51,isw_topic_52,isw_topic_53,isw_topic_54,isw_topic_55,isw_topic_56,isw_topic_57,isw_topic_58,isw_topic_59,isw_topic_60,isw_topic_61,isw_topic_62,isw_topic_63,isw_topic_64,isw_topic_65,isw_topic_66,isw_topic_67,isw_topic_68,isw_topic_69,isw_topic_70,isw_topic_71,isw_topic_72,isw_topic_73,isw_topic_74,isw_topic_75,isw_topic_76,isw_topic_77,isw_topic_78,isw_topic_79,isw_topic_80,isw_topic_81,isw_topic_82,isw_topic_83,isw_topic_84,isw_topic_85,isw_topic_86,isw_topic_87,isw_topic_88,isw_topic_89,isw_topic_90,isw_topic_91,isw_topic_92,isw_topic_93,isw_topic_94,isw_topic_95,isw_topic_96,isw_topic_97,isw_topic_98,isw_topic_99,isw_topic_100,isw_topic_101,isw_topic_102,isw_topic_103,isw_topic_104,isw_topic_105,isw_topic_106,isw_topic_107,isw_topic_108,isw_topic_109,isw_topic_110,isw_topic_111,isw_topic_112,isw_topic_113,isw_topic_114,isw_topic_115,isw_topic_116,isw_topic_117,isw_topic_118,isw_topic_119,isw_topic_120,isw_topic_121,isw_topic_122,isw_topic_123,isw_topic_124,isw_topic_125,isw_topic_126,isw_topic_127,isw_topic_128,isw_topic_129,isw_topic_130,isw_topic_131,isw_topic_132,isw_topic_133,isw_topic_134,isw_topic_135,isw_topic_136,isw_topic_137,isw_topic_138,isw_topic_139,isw_topic_140,isw_topic_141,isw_topic_142,isw_topic_143,isw_topic_144,isw_topic_145,isw_topic_146,isw_topic_147,isw_topic_148,isw_topic_149
0,2022-02-24 00:00:00,2,49.2336,28.4486,2.8,-0.3,80.5,0.3,100.0,4.17,0.0,0.0,27.7,10.8,312.0,1023.4,82.5,60.4,5.4,3.0,0.77,2.1,-0.5,91.76,0.0,0.0,0.0,16.6,8.6,279.6,1021.0,91.1,0.0,0.1,0.0,False,False,False,True,False,True,False,False,2022,2,3,0,Vinnytsia,Europe/Kiev,2022-02-24,06:58:49,17:40:52,00:00:00,Вінницька,0,0.000000,0.0,0.0,0.0,0.0,0.0,0,1,0.0,0.0,1,0.648336,-0.079572,0.178041,0.061854,0.073453,-0.055809,-0.011311,0.047310,0.008354,0.006474,-0.047099,0.020496,0.050190,-0.038573,0.057228,-0.072471,0.045393,-0.116783,0.168249,0.167355,-0.025072,-0.073858,-0.097024,-0.146191,0.027983,0.082989,0.014423,0.058370,-0.033928,0.046265,0.006901,-0.049498,0.126117,-0.089039,-0.006767,-0.031686,-0.010346,0.025637,0.061278,0.162580,-0.028081,0.161291,-0.018217,-0.002657,0.038485,-0.000530,0.044413,0.107176,-0.050721,0.064279,-0.066677,0.016742,-0.050257,0.072549,-0.035201,-0.027279,0.017115,0.043631,0.024660,-0.025841,0.031320,-0.076959,-0.072986,-0.040465,0.003958,-0.022475,0.033208,-0.028056,-0.005499,-0.055998,-0.021882,-0.070462,0.018237,-0.031396,-0.074606,0.072951,0.039997,0.036423,-0.027152,-0.071900,0.026267,-0.046270,-0.017945,0.007933,-0.006203,-0.046099,0.032793,-0.069113,0.020403,0.030783,-0.003787,-0.000490,-0.022951,0.013498,0.009664,-0.007012,-0.016325,-0.005732,0.036069,-0.063906,0.033891,0.010560,-0.104517,-0.022069,0.054322,-0.005460,-0.029093,0.040991,-0.053018,-0.024017,0.050817,-0.003297,-0.020895,-0.053213,-0.028428,0.048231,-0.001221,0.001302,-0.044137,0.015528,-0.012792,-0.012009,-0.008211,0.031114,0.024982,0.003863,-0.032321,0.030920,-0.012845,0.070170,-0.004037,0.014003,0.005577,0.021611,-0.002889,0.034824,0.047164,0.050545,-0.017639,0.029014,-0.030378,-0.027056,0.011464,-0.039759,-0.043514,-0.025605,-0.022484,-0.036224,0.000566,0.005481
1,2022-02-24 00:00:00,2,49.2336,28.4486,2.8,-0.3,80.5,0.3,100.0,4.17,0.0,0.0,27.7,10.8,312.0,1023.4,82.5,60.4,5.4,3.0,0.77,2.1,-0.5,91.76,0.0,0.0,0.0,16.6,8.6,279.6,1021.0,91.1,0.0,0.1,0.0,False,False,False,True,False,True,False,False,2022,2,3,0,Vinnytsia,Europe/Kiev,2022-02-24,06:58:49,17:40:52,00:00:00,Вінницька,0,0.000000,0.0,0.0,0.0,0.0,0.0,0,1,0.0,0.0,1,0.580161,-0.090608,-0.028388,0.146350,0.071072,-0.030284,-0.004583,0.087399,-0.038512,0.016613,-0.038599,0.049747,0.186305,-0.172198,-0.045515,0.050785,0.041889,-0.112849,0.193473,-0.010566,0.044308,-0.118300,0.007117,-0.135687,-0.009441,-0.039465,0.032843,0.080393,-0.035434,0.010352,-0.016680,-0.046252,0.085840,-0.123167,0.064510,-0.023735,-0.025637,-0.027863,0.032156,0.068641,0.027667,0.162729,0.039675,-0.016915,-0.008203,0.048024,0.073343,0.025782,-0.013935,-0.008775,-0.045265,0.008979,-0.100558,0.044074,0.018202,-0.037279,0.062349,0.008014,0.075917,-0.063409,0.015404,-0.091507,-0.079240,-0.033000,-0.019226,-0.103926,0.031514,0.043306,-0.012137,-0.010430,0.035901,-0.013437,-0.042046,-0.064986,0.002947,0.024326,0.085592,-0.008453,0.091087,-0.106852,0.038223,-0.061062,0.027905,0.056421,-0.030501,0.000050,0.051385,-0.087324,-0.024025,0.031626,-0.029461,0.015717,-0.047181,-0.005600,0.049867,0.084412,-0.055460,-0.036620,0.120475,-0.012080,0.006961,-0.079701,0.055655,0.004130,0.013250,0.002392,0.041937,0.028208,-0.037232,0.014886,-0.036905,0.000138,-0.018200,-0.010680,-0.067564,-0.001064,-0.044792,-0.014807,-0.031911,-0.023504,0.070783,0.027626,0.000418,0.043677,-0.030193,-0.034979,0.080093,0.035489,-0.004156,-0.008032,0.039826,-0.037380,0.011931,0.008267,0.000590,0.043862,0.023758,0.038714,0.066128,0.028168,-0.012153,0.005376,0.008085,-0.038933,0.003404,0.003281,-0.004149,-0.025392,0.010434,-0.017613
2,2022-02-24 01:00:00,2,49.2336,28.4486,2.8,-0.3,80.5,0.3,100.0,4.17,0.0,0.0,27.7,10.8,312.0,1023.4,82.5,60.4,5.4,3.0,0.77,2.1,-0.4,89.80,0.0,0.0,0.0,16.6,8.3,289.2,1021.0,97.9,0.0,0.1,0.0,False,False,False,True,False,True,False,False,2022,2,3,1,Vinnytsia,Europe/Kiev,2022-02-24,06:58:49,17:40:52,01:00:00,Вінницька,0,0.000000,0.0,0.0,0.0,0.0,0.0,0,1,0.0,0.0,2,0.648336,-0.079572,0.178041,0.061854,0.073453,-0.055809,-0.011311,0.047310,0.008354,0.006474,-0.047099,0.020496,0.050190,-0.038573,0.057228,-0.072471,0.045393,-0.116783,0.168249,0.167355,-0.025072,-0.073858,-0.097024,-0.146191,0.027983,0.082989,0.014423,0.058370,-0.033928,0.046265,0.006901,-0.049498,0.126117,-0.089039,-0.006767,-0.031686,-0.010346,0.025637,0.061278,0.162580,-0.028081,0.161291,-0.018217,-0.002657,0.038485,-0.000530,0.044413,0.107176,-0.050721,0.064279,-0.066677,0.016742,-0.050257,0.072549,-0.035201,-0.027279,0.017115,0.043631,0.024660,-0.025841,0.031320,-0.076959,-0.072986,-0.040465,0.003958,-0.022475,0.033208,-0.028056,-0.005499,-0.055998,-0.021882,-0.070462,0.018237,-0.031396,-0.074606,0.072951,0.039997,0.036423,-0.027152,-0.071900,0.026267,-0.046270,-0.017945,0.007933,-0.006203,-0.046099,0.032793,-0.069113,0.020403,0.030783,-0.003787,-0.000490,-0.022951,0.013498,0.009664,-0.007012,-0.016325,-0.005732,0.036069,-0.063906,0.033891,0.010560,-0.104517,-0.022069,0.054322,-0.005460,-0.029093,0.040991,-0.053018,-0.024017,0.050817,-0.003297,-0.020895,-0.053213,-0.028428,0.048231,-0.001221,0.001302,-0.044137,0.015528,-0.012792,-0.012009,-0.008211,0.031114,0.024982,0.003863,-0.032321,0.030920,-0.012845,0.070170,-0.004037,0.014003,0.005577,0.021611,-0.002889,0.034824,0.047164,0.050545,-0.017639,0.029014,-0.030378,-0.027056,0.011464,-0.039759,-0.043514,-0.025605,-0.022484,-0.036224,0.000566,0.005481
3,2022-02-24 01:00:00,2,49.2336,28.4486,2.8,-0.3,80.5,0.3,100.0,4.17,0.0,0.0,27.7,10.8,312.0,1023.4,82.5,60.4,5.4,3.0,0.77,2.1,-0.4,89.80,0.0,0.0,0.0,16.6,8.3,289.2,1021.0,97.9,0.0,0.1,0.0,False,False,False,True,False,True,False,False,2022,2,3,1,Vinnytsia,Europe/Kiev,2022-02-24,06:58:49,17:40:52,01:00:00,Вінницька,0,0.000000,0.0,0.0,0.0,0.0,0.0,0,1,0.0,0.0,2,0.580161,-0.090608,-0.028388,0.146350,0.071072,-0.030284,-0.004583,0.087399,-0.038512,0.016613,-0.038599,0.049747,0.186305,-0.172198,-0.045515,0.050785,0.041889,-0.112849,0.193473,-0.010566,0.044308,-0.118300,0.007117,-0.135687,-0.009441,-0.039465,0.032843,0.080393,-0.035434,0.010352,-0.016680,-0.046252,0.085840,-0.123167,0.064510,-0.023735,-0.025637,-0.027863,0.032156,0.068641,0.027667,0.162729,0.039675,-0.016915,-0.008203,0.048024,0.073343,0.025782,-0.013935,-0.008775,-0.045265,0.008979,-0.100558,0.044074,0.018202,-0.037279,0.062349,0.008014,0.075917,-0.063409,0.015404,-0.091507,-0.079240,-0.033000,-0.019226,-0.103926,0.031514,0.043306,-0.012137,-0.010430,0.035901,-0.013437,-0.042046,-0.064986,0.002947,0.024326,0.085592,-0.008453,0.091087,-0.106852,0.038223,-0.061062,0.027905,0.056421,-0.030501,0.000050,0.051385,-0.087324,-0.024025,0.031626,-0.029461,0.015717,-0.047181,-0.005600,0.049867,0.084412,-0.055460,-0.036620,0.120475,-0.012080,0.006961,-0.079701,0.055655,0.004130,0.013250,0.002392,0.041937,0.028208,-0.037232,0.014886,-0.036905,0.000138,-0.018200,-0.010680,-0.067564,-0.001064,-0.044792,-0.014807,-0.031911,-0.023504,0.070783,0.027626,0.000418,0.043677,-0.030193,-0.034979,0.080093,0.035489,-0.004156,-0.008032,0.039826,-0.037380,0.011931,0.008267,0.000590,0.043862,0.023758,0.038714,0.066128,0.028168,-0.012153,0.005376,0.008085,-0.038933,0.003404,0.003281,-0.004149,-0.025392,0.010434,-0.017613
4,2022-02-24 02:00:00,2,49.2336,28.4486,2.8,-0.3,80.5,0.3,100.0,4.17,0.0,0.0,27.7,10.8,312.0,1023.4,82.5,60.4,5.4,3.0,0.77,2.0,-0.3,90.44,0.0,0.0,0.0,27.7,7.6,287.6,1021.0,98.2,0.0,0.1,0.0,False,False,False,True,False,True,False,False,2022,2,3,2,Vinnytsia,Europe/Kiev,2022-02-24,06:58:49,17:40:52,02:00:00,Вінницька,0,0.000000,0.0,0.0,0.0,0.0,0.0,0,1,0.0,0.0,3,0.648336,-0.079572,0.178041,0.061854,0.073453,-0.055809,-0.011311,0.047310,0.008354,0.006474,-0.047099,0.020496,0.050190,-0.038573,0.057228,-0.072471,0.045393,-0.116783,0.168249,0.167355,-0.025072,-0.073858,-0.097024,-0.146191,0.027983,0.082989,0.014423,0.058370,-0.033928,0.046265,0.006901,-0.049498,0.126117,-0.089039,-0.006767,-0.031686,-0.010346,0.025637,0.061278,0.162580,-0.028081,0.161291,-0.018217,-0.002657,0.038485,-0.000530,0.044413,0.107176,-0.050721,0.064279,-0.066677,0.016742,-0.050257,0.072549,-0.035201,-0.027279,0.017115,0.043631,0.024660,-0.025841,0.031320,-0.076959,-0.072986,-0.040465,0.003958,-0.022475,0.033208,-0.028056,-0.005499,-0.055998,-0.021882,-0.070462,0.018237,-0.031396,-0.074606,0.072951,0.039997,0.036423,-0.027152,-0.071900,0.026267,-0.046270,-0.017945,0.007933,-0.006203,-0.046099,0.032793,-0.069113,0.020403,0.030783,-0.003787,-0.000490,-0.022951,0.013498,0.009664,-0.007012,-0.016325,-0.005732,0.036069,-0.063906,0.033891,0.010560,-0.104517,-0.022069,0.054322,-0.005460,-0.029093,0.040991,-0.053018,-0.024017,0.050817,-0.003297,-0.020895,-0.053213,-0.028428,0.048231,-0.001221,0.001302,-0.044137,0.015528,-0.012792,-0.012009,-0.008211,0.031114,0.024982,0.003863,-0.032321,0.030920,-0.012845,0.070170,-0.004037,0.014003,0.005577,0.021611,-0.002889,0.034824,0.047164,0.050545,-0.017639,0.029014,-0.030378,-0.027056,0.011464,-0.039759,-0.043514,-0.025605,-0.022484,-0.036224,0.000566,0.005481
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
635251,2025-03-01 19:00:00,26,50.4506,30.5243,0.0,-2.6,82.9,0.7,100.0,8.33,1.3,1.0,34.6,15.5,178.1,1026.7,99.5,40.6,3.6,2.0,0.05,-0.1,-3.5,97.13,0.0,0.0,0.0,16.9,10.1,181.6,1027.0,95.6,0.0,0.0,0.0,False,False,False,True,False,True,False,False,2025,3,5,19,Kyiv,Europe/Kiev,2025-03-01,06:41:35,17:39:46,19:00:00,Київ,0,0.000000,0.0,0.0,0.0,0.0,5.0,1,0,11.0,0.0,15,0.741253,0.175928,-0.044270,0.236290,0.000096,-0.082156,-0.069547,0.169634,0.047371,0.108829,-0.111513,0.005588,0.009037,-0.035562,0.049145,0.077242,-0.085251,0.067886,0.052548,-0.120459,0.081966,-0.062164,0.022709,0.023532,-0.002714,0.000626,-0.026931,0.012943,-0.027664,-0.111107,-0.094103,-0.019189,-0.002106,0.023217,0.036788,-0.009149,-0.051459,-0.073844,-0.016720,-0.019477,-0.024286,0.075470,-0.053957,-0.052265,0.022580,-0.016046,-0.047243,0.005718,0.019756,-0.035501,0.025955,0.020804,-0.008431,0.005311,-0.038751,-0.010557,-0.009238,-0.005986,-0.035657,-0.003185,-0.030416,-0.013563,-0.026338,0.069073,-0.003216,0.021366,0.025951,-0.017980,0.006948,0.029034,0.069441,-0.043368,0.028677,0.035237,-0.023784,-0.005083,0.028958,0.012654,0.001550,-0.039223,0.020654,-0.040622,0.014536,0.002429,-0.013533,0.003547,-0.061560,0.020515,-0.017876,0.041345,-0.033319,-0.020192,0.035267,0.011339,-0.088522,0.022461,-0.047734,-0.034346,-0.011346,0.043122,0.001617,-0.023157,-0.018391,-0.006131,0.040270,0.030336,0.007110,0.024232,0.035189,-0.038329,0.020301,0.032434,0.007683,-0.010900,-0.008896,-0.019209,0.007017,0.040898,-0.031859,0.000779,-0.002852,0.028824,0.006013,0.010350,0.013379,-0.027336,-0.003269,0.008264,0.004228,0.022508,-0.012380,0.000627,0.017807,-0.013325,-0.006459,0.021368,-0.027278,-0.008352,0.001816,0.004596,0.019812,-0.012733,-0.001035,-0.001903,0.005062,-0.015576,0.028419,-0.012698,0.016105,-0.007801
635252,2025-03-01 20:00:00,26,50.4506,30.5243,0.0,-2.6,82.9,0.7,100.0,8.33,1.3,1.0,34.6,15.5,178.1,1026.7,99.5,40.6,3.6,2.0,0.05,-0.3,-0.3,92.96,0.4,100.0,0.0,17.6,0.0,189.9,1027.0,100.0,0.0,0.0,0.0,False,False,False,True,False,False,False,True,2025,3,5,20,Kyiv,Europe/Kiev,2025-03-01,06:41:35,17:39:46,20:00:00,Київ,0,0.000000,0.0,0.0,0.0,0.0,5.0,1,0,5.0,0.0,16,0.741253,0.175928,-0.044270,0.236290,0.000096,-0.082156,-0.069547,0.169634,0.047371,0.108829,-0.111513,0.005588,0.009037,-0.035562,0.049145,0.077242,-0.085251,0.067886,0.052548,-0.120459,0.081966,-0.062164,0.022709,0.023532,-0.002714,0.000626,-0.026931,0.012943,-0.027664,-0.111107,-0.094103,-0.019189,-0.002106,0.023217,0.036788,-0.009149,-0.051459,-0.073844,-0.016720,-0.019477,-0.024286,0.075470,-0.053957,-0.052265,0.022580,-0.016046,-0.047243,0.005718,0.019756,-0.035501,0.025955,0.020804,-0.008431,0.005311,-0.038751,-0.010557,-0.009238,-0.005986,-0.035657,-0.003185,-0.030416,-0.013563,-0.026338,0.069073,-0.003216,0.021366,0.025951,-0.017980,0.006948,0.029034,0.069441,-0.043368,0.028677,0.035237,-0.023784,-0.005083,0.028958,0.012654,0.001550,-0.039223,0.020654,-0.040622,0.014536,0.002429,-0.013533,0.003547,-0.061560,0.020515,-0.017876,0.041345,-0.033319,-0.020192,0.035267,0.011339,-0.088522,0.022461,-0.047734,-0.034346,-0.011346,0.043122,0.001617,-0.023157,-0.018391,-0.006131,0.040270,0.030336,0.007110,0.024232,0.035189,-0.038329,0.020301,0.032434,0.007683,-0.010900,-0.008896,-0.019209,0.007017,0.040898,-0.031859,0.000779,-0.002852,0.028824,0.006013,0.010350,0.013379,-0.027336,-0.003269,0.008264,0.004228,0.022508,-0.012380,0.000627,0.017807,-0.013325,-0.006459,0.021368,-0.027278,-0.008352,0.001816,0.004596,0.019812,-0.012733,-0.001035,-0.001903,0.005062,-0.015576,0.028419,-0.012698,0.016105,-0.007801
635253,2025-03-01 21:00:00,26,50.4506,30.5243,0.0,-2.6,82.9,0.7,100.0,8.33,1.3,1.0,34.6,15.5,178.1,1026.7,99.5,40.6,3.6,2.0,0.05,0.0,-3.2,96.43,0.0,0.0,0.0,18.4,9.4,198.3,1027.0,100.0,0.0,0.0,0.0,False,False,False,True,False,True,False,False,2025,3,5,21,Kyiv,Europe/Kiev,2025-03-01,06:41:35,17:39:46,21:00:00,Київ,0,0.000000,0.0,0.0,0.0,0.0,5.0,1,0,9.0,0.0,17,0.741253,0.175928,-0.044270,0.236290,0.000096,-0.082156,-0.069547,0.169634,0.047371,0.108829,-0.111513,0.005588,0.009037,-0.035562,0.049145,0.077242,-0.085251,0.067886,0.052548,-0.120459,0.081966,-0.062164,0.022709,0.023532,-0.002714,0.000626,-0.026931,0.012943,-0.027664,-0.111107,-0.094103,-0.019189,-0.002106,0.023217,0.036788,-0.009149,-0.051459,-0.073844,-0.016720,-0.019477,-0.024286,0.075470,-0.053957,-0.052265,0.022580,-0.016046,-0.047243,0.005718,0.019756,-0.035501,0.025955,0.020804,-0.008431,0.005311,-0.038751,-0.010557,-0.009238,-0.005986,-0.035657,-0.003185,-0.030416,-0.013563,-0.026338,0.069073,-0.003216,0.021366,0.025951,-0.017980,0.006948,0.029034,0.069441,-0.043368,0.028677,0.035237,-0.023784,-0.005083,0.028958,0.012654,0.001550,-0.039223,0.020654,-0.040622,0.014536,0.002429,-0.013533,0.003547,-0.061560,0.020515,-0.017876,0.041345,-0.033319,-0.020192,0.035267,0.011339,-0.088522,0.022461,-0.047734,-0.034346,-0.011346,0.043122,0.001617,-0.023157,-0.018391,-0.006131,0.040270,0.030336,0.007110,0.024232,0.035189,-0.038329,0.020301,0.032434,0.007683,-0.010900,-0.008896,-0.019209,0.007017,0.040898,-0.031859,0.000779,-0.002852,0.028824,0.006013,0.010350,0.013379,-0.027336,-0.003269,0.008264,0.004228,0.022508,-0.012380,0.000627,0.017807,-0.013325,-0.006459,0.021368,-0.027278,-0.008352,0.001816,0.004596,0.019812,-0.012733,-0.001035,-0.001903,0.005062,-0.015576,0.028419,-0.012698,0.016105,-0.007801
635254,2025-03-01 22:00:00,26,50.4506,30.5243,0.0,-2.6,82.9,0.7,100.0,8.33,1.3,1.0,34.6,15.5,178.1,1026.7,99.5,40.6,3.6,2.0,0.05,0.0,-2.9,97.84,0.0,0.0,0.0,16.6,8.3,199.9,1027.0,97.6,0.0,0.0,0.0,False,False,False,True,False,True,False,False,2025,3,5,22,Kyiv,Europe/Kiev,2025-03-01,06:41:35,17:39:46,22:00:00,Київ,1,7.833333,0.0,0.0,0.0,0.0,5.0,1,0,11.0,0.0,18,0.741253,0.175928,-0.044270,0.236290,0.000096,-0.082156,-0.069547,0.169634,0.047371,0.108829,-0.111513,0.005588,0.009037,-0.035562,0.049145,0.077242,-0.085251,0.067886,0.052548,-0.120459,0.081966,-0.062164,0.022709,0.023532,-0.002714,0.000626,-0.026931,0.012943,-0.027664,-0.111107,-0.094103,-0.019189,-0.002106,0.023217,0.036788,-0.009149,-0.051459,-0.073844,-0.016720,-0.019477,-0.024286,0.075470,-0.053957,-0.052265,0.022580,-0.016046,-0.047243,0.005718,0.019756,-0.035501,0.025955,0.020804,-0.008431,0.005311,-0.038751,-0.010557,-0.009238,-0.005986,-0.035657,-0.003185,-0.030416,-0.013563,-0.026338,0.069073,-0.003216,0.021366,0.025951,-0.017980,0.006948,0.029034,0.069441,-0.043368,0.028677,0.035237,-0.023784,-0.005083,0.028958,0.012654,0.001550,-0.039223,0.020654,-0.040622,0.014536,0.002429,-0.013533,0.003547,-0.061560,0.020515,-0.017876,0.041345,-0.033319,-0.020192,0.035267,0.011339,-0.088522,0.022461,-0.047734,-0.034346,-0.011346,0.043122,0.001617,-0.023157,-0.018391,-0.006131,0.040270,0.030336,0.007110,0.024232,0.035189,-0.038329,0.020301,0.032434,0.007683,-0.010900,-0.008896,-0.019209,0.007017,0.040898,-0.031859,0.000779,-0.002852,0.028824,0.006013,0.010350,0.013379,-0.027336,-0.003269,0.008264,0.004228,0.022508,-0.012380,0.000627,0.017807,-0.013325,-0.006459,0.021368,-0.027278,-0.008352,0.001816,0.004596,0.019812,-0.012733,-0.001035,-0.001903,0.005062,-0.015576,0.028419,-0.012698,0.016105,-0.007801

In [20]:
df_final.isna().sum()

datetime_hour     0
region_id         0
city_latitude     0
city_longitude    0
day_temp          0
                 ..
isw_topic_145     0
isw_topic_146     0
isw_topic_147     0
isw_topic_148     0
isw_topic_149     0
Length: 216, dtype: int64

### Feature engineering for isw topics

In [21]:
topic_cols = [c for c in df_final.columns if "isw_topic_" in c]
df_isw_abs = df_final[topic_cols].abs()

df_final['isw_total_intensity'] = df_isw_abs.sum(axis=1)
df_final['isw_topic_std'] = df_isw_abs.std(axis=1)
df_final['isw_topic_max'] = df_isw_abs.max(axis=1)
df_final['isw_topic_mean'] = df_isw_abs.mean(axis=1)

df_final['isw_velocity_24h'] = (
    df_final.groupby('region_id')['isw_total_intensity']
    .diff(24)
    .fillna(0)
)

df_final['isw_intensity_ema'] = (df_final.groupby('region_id')['isw_total_intensity'].transform(lambda x: x.shift(1).ewm(span=24).mean()))

df_final['isw_topic_entropy'] = -(df_isw_abs.div(df_isw_abs.sum(axis=1), axis=0) * np.log(df_isw_abs.div(df_isw_abs.sum(axis=1), axis=0) + 1e-9)).sum(axis=1)

isw_cols = ['isw_velocity_24h', 'isw_intensity_ema', 'isw_topic_entropy']
df_final[isw_cols] = df_final[isw_cols].fillna(0)

C:\Users\Uw11\AppData\Local\Temp\ipykernel_9376\1269306822.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_final['isw_total_intensity'] = df_isw_abs.sum(axis=1)
C:\Users\Uw11\AppData\Local\Temp\ipykernel_9376\1269306822.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_final['isw_topic_std'] = df_isw_abs.std(axis=1)
C:\Users\Uw11\AppData\Local\Temp\ipykernel_9376\1269306822.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_final['isw_topic_max'] = df_isw_abs.max(axis=1)
C:\Users\Uw11\AppData\Local\Temp\ipykernel_9376\1269306822.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_final['isw_topic_mean'] = df_isw_abs.mean(axis=1)
C:\Users\Uw11\AppData\Local\Temp\ipykernel_9376\1269306822.py:9: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_final['isw_velocity_24h'] = (
C:\Users\Uw11\AppData\Local\Temp\ipykernel_9376\1269306822.py:15: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_final['isw_intensity_ema'] = (df_final.groupby('region_id')['isw_total_intensity'].transform(lambda x: x.shift(1).ewm(span=24).mean()))
C:\Users\Uw11\AppData\Local\Temp\ipykernel_9376\1269306822.py:17: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_final['isw_topic_entropy'] = -(df_isw_abs.div(df_isw_abs.sum(axis=1), axis=0) * np.log(df_isw_abs.div(df_isw_abs.sum(axis=1), axis=0) + 1e-9)).sum(axis=1)

In [22]:
df_final.sample(10)

,datetime_hour,region_id,city_latitude,city_longitude,day_temp,day_dew,day_humidity,day_precip,day_precipprob,day_precipcover,day_snow,day_snowdepth,day_windgust,day_windspeed,day_winddir,day_pressure,day_cloudcover,day_solarradiation,day_solarenergy,day_uvindex,day_moonphase,hour_temp,hour_feelslike,hour_humidity,hour_precip,hour_precipprob,hour_snow,hour_windgust,hour_windspeed,hour_winddir,hour_pressure,hour_cloudcover,hour_solarradiation,hour_solarenergy,hour_uvindex,day_conditions_simple_Clear,day_conditions_simple_Cloudy,day_conditions_simple_Rain,day_conditions_simple_Snow,hour_conditions_simple_Clear,hour_conditions_simple_Cloudy,hour_conditions_simple_Rain,hour_conditions_simple_Snow,year,month,day_of_week,hour,city_name,city_timezone,day_datetime,day_sunrise,day_sunset,hour_datetime,region_key,alarm_active,alarm_minutes_in_hour,alarm_lag_1,alarm_lag_3,alarm_lag_6,alarm_lag_12,alarms_in_last_24h,is_weekend,is_night,total_active_alarms_lag1,neighbour_alarms,hours_since_last_alarm,isw_topic_0,isw_topic_1,isw_topic_2,isw_topic_3,isw_topic_4,isw_topic_5,isw_topic_6,isw_topic_7,isw_topic_8,isw_topic_9,isw_topic_10,isw_topic_11,isw_topic_12,isw_topic_13,isw_topic_14,isw_topic_15,isw_topic_16,isw_topic_17,isw_topic_18,isw_topic_19,isw_topic_20,isw_topic_21,isw_topic_22,isw_topic_23,isw_topic_24,isw_topic_25,isw_topic_26,isw_topic_27,isw_topic_28,isw_topic_29,isw_topic_30,isw_topic_31,isw_topic_32,isw_topic_33,isw_topic_34,isw_topic_35,isw_topic_36,isw_topic_37,isw_topic_38,isw_topic_39,isw_topic_40,isw_topic_41,isw_topic_42,isw_topic_43,isw_topic_44,isw_topic_45,isw_topic_46,isw_topic_47,isw_topic_48,isw_topic_49,isw_topic_50,isw_topic_51,isw_topic_52,isw_topic_53,isw_topic_54,isw_topic_55,isw_topic_56,isw_topic_57,isw_topic_58,isw_topic_59,isw_topic_60,isw_topic_61,isw_topic_62,isw_topic_63,isw_topic_64,isw_topic_65,isw_topic_66,isw_topic_67,isw_topic_68,isw_topic_69,isw_topic_70,isw_topic_71,isw_topic_72,isw_topic_73,isw_topic_74,isw_topic_75,isw_topic_76,isw_topic_77,isw_topic_78,isw_topic_79,isw_topic_80,isw_topic_81,isw_topic_82,isw_topic_83,isw_topic_84,isw_topic_85,isw_topic_86,isw_topic_87,isw_topic_88,isw_topic_89,isw_topic_90,isw_topic_91,isw_topic_92,isw_topic_93,isw_topic_94,isw_topic_95,isw_topic_96,isw_topic_97,isw_topic_98,isw_topic_99,isw_topic_100,isw_topic_101,isw_topic_102,isw_topic_103,isw_topic_104,isw_topic_105,isw_topic_106,isw_topic_107,isw_topic_108,isw_topic_109,isw_topic_110,isw_topic_111,isw_topic_112,isw_topic_113,isw_topic_114,isw_topic_115,isw_topic_116,isw_topic_117,isw_topic_118,isw_topic_119,isw_topic_120,isw_topic_121,isw_topic_122,isw_topic_123,isw_topic_124,isw_topic_125,isw_topic_126,isw_topic_127,isw_topic_128,isw_topic_129,isw_topic_130,isw_topic_131,isw_topic_132,isw_topic_133,isw_topic_134,isw_topic_135,isw_topic_136,isw_topic_137,isw_topic_138,isw_topic_139,isw_topic_140,isw_topic_141,isw_topic_142,isw_topic_143,isw_topic_144,isw_topic_145,isw_topic_146,isw_topic_147,isw_topic_148,isw_topic_149,isw_total_intensity,isw_topic_std,isw_topic_max,isw_topic_mean,isw_velocity_24h,isw_intensity_ema,isw_topic_entropy
628096,2024-05-07 16:00:00,26,50.4506,30.5243,14.8,9.7,72.5,0.3,100.0,4.17,0.0,0.0,49.0,25.6,299.2,1008.5,79.8,180.7,15.5,6.0,0.97,18.8,18.8,54.00,0.0,0.0,0.0,46.1,23.8,307.8,1008.0,42.5,427.4,1.5,4.0,False,False,True,False,False,True,False,False,2024,5,1,16,Kyiv,Europe/Kiev,2024-05-07,05:22:06,20:27:52,16:00:00,Київ,0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,1.0,0.0,72,0.760383,-0.115209,-0.216867,0.116622,-0.026353,-0.001564,0.029514,-0.019226,-0.002838,-0.035358,-0.015497,0.022991,0.050022,-0.055749,-0.096895,0.146493,0.152837,0.008929,0.007954,0.006124,-0.047747,-0.032945,0.004861,0.020967,0.082041,-0.075820,-0.008549,0.010871,-0.034577,0.031983,0.001599,0.005368,0.000723,-0.031691,0.006319,0.016787,0.064792,0.045437,0.021521,-0.025317,0.012631,0.015906,-0.005648,-0.011209,0.012172,-0.028425,-0.015082,0.050468,-0.058386,0.015673,-0.013047,-0.043043,-0.000638,0.039013,0.027697,-0.052935,-0.044494,-0.029279,-0.089357,0.014147,0.021755,0.014268,-0.003571,0.054003,0.036114,0.032002,-0.017743,-0.038539,0.014274,0.015597,0.039023,-0.008427,-0.031904,-0.040017,-0.013346,-0.010713,-0.020838,0.012085,0.015380,-0.012106,-0.001752,-0.013224,-0.009221,-0.022696,-0.002323,0.012591,0.006877,-0.005324,0.015160,0.015062,-0.055748,0.009463,-0.012879,-0.033223,0.011967,-0.014699,0.031805,0.014118,-0.011797,0.002365,-0.030427,-0.015311,0.005562,-0.013456,-0.016289,-0.007573,0.005159,0.054593,0.019118,0.023530,0.027860,0.003962,-0.052245,0.019477,-0.002606,-0.022326,0.000935,0.015217,0.003893,0.041568,-0.021028,0.014165,0.019658,0.009556,0.028388,0.031335,-0.025235,-0.000387,-0.018647,0.047973,0.060054,-0.002176,-0.019192,-0.015497,-0.028781,-0.008794,-0.025691,-0.038604,0.011799,-0.027707,0.022037,-0.002904,-0.020024,-0.019555,0.027229,-0.010489,-0.040686,0.038643,0.043441,-0.015113,4.866482,0.066896,0.760383,0.032443,0.456708,4.748980,4.304026
37470,2023-05-27 11:00:00,3,50.7469,25.3263,16.2,7.4,58.3,0.0,0.0,0.00,0.0,0.0,38.5,20.9,353.0,1020.9,22.1,307.6,26.6,8.0,0.25,18.0,18.0,53.79,0.0,0.0,0.0,33.5,15.1,352.2,1022.0,3.8,670.0,2.4,7.0,False,True,False,False,True,False,False,False,2023,5,5,11,Lutsk,Europe/Kiev,2023-05-27,05:15:50,21:16:38,11:00:00,Волинська,0,0.0,0.0,0.0,0.0,0.0,0.0,1,0,1.0,0.0,29,0.786571,-0.236401,-0.060035,-0.005343,-0.003228,0.040632,-0.008143,0.060293,-0.086701,0.073199,0.072501,0.018393,-0.039614,0.011553,0.102219,0.098918,0.190662,0.082747,-0.080191,0.083856,0.014443,0.028632,0.013828,-0.069365,-0.032882,-0.053358,-0.006441,0.008248,0.032069,-0.036374,0.024772,0.000363,-0.011405,0.043271,-0.013419,0.008387,0.031876,-0.070433,0.030765,-0.022410,-0.021859,-0.037929,0.009653,-0.000363,-0.025840,0.036908,-0.029880,0.011287,-0.010684,0.031515,0.009738,0.042943,0.025782,0.036910,-0.058448,-0.011655,-0.005635,-0.014905,-0.007314,-0.061938,0.042006,0.015764,0.007111,-0.049478,0.011370,-0.019349,0.034085,0.051428,-0.021506,0.027629,0.001934,-0.006111,-0.031005,-0.016578,0.013765,0.043570,0.028365,0.026376,0.005577,0.043196,0.008884,0.005863,-0.014451,0.009228,0.027319,0.027210,0.029063,0.000009,-0.009789,-0.031236,-0.010954,-0.011141,0.008398,-0.002592,0.009168,0.009661,-0.015773,0.002817,-0.014408,-0.013995,-0.029909,-0.039872,-0.004453,0.002514,-0.001670,0.046128,-0.007662,0.009634,0.009509,-0.006674,-0.018215,0.025311,0.005538,-0.015301,-0.009109,0.020756,0.011431,0.003827,-0.003347,0.005412,0.010293,-0.011934,0.007835,-0.010433,0.028020,-0.017532,-0.004734,0.004652,-0.004122,-0.035342,0.005739,0.003788,0.002288,-0.012275,-0.012187,-0.012194,-0.010861,-0.013981,-0.016727,-0.008358,0.014437,-0.024329,0.010762,-0.041915,0.020630,-0.030132,0.002301,0.002438,0.007609,0.006869,4.614282,0.069320,0.786571,0.030762,-0.321083,4.776411,4.211656
177990,2024-05-02 03:00:00,8,47.8289,35.1626,18.1,7.1,50.7,0.0,0.0,0.00,0.0,0.0,28.1,16.9,19.0,1013.3,0.0,299.3,25.7,9.0,0.80,12.9,12.9,65.99,0.0,0.0,0.0,21.2,14.4,25.0,1017.0,0.0,0.0,0.0,0.0,True,False,False,False,True,False,False,False,2024,5,3,3,Zaporozhye,Europe/Zaporozhye,2024-05-02,05:19:39,19:53:57,03:00:00,Запорізька,0,0.0,0.0,0.0,1.0,1.0,13.0,0,1,0.0,0.0,3,0.794735,-0.071624,-0.132797,0.135272,-0.040450,-0.016350,0.022038,-0.032611,-0.013320,-0.043444,0.008800,0.032170,0.038801,-0.031041,-0.065104,0.052201,0.172001,0.035596,-0.012310,0.120989,0.044226,-0.020126,-0.039683,0.013752,0.051425,0.005238,-0.012038,0.007328,-0.054156,0.004892,-0.014466,0.012179,-0.058136,0.017958,0.023201,-0.042273,0.017846,0.004211,-0.064294,-0.061102,0.001500,0.025567,-0.016937,0.011868,0.008408,-0.079473,0.048989,0.003794,0.096183,0.012845,-0.051681,0.090004,0.054672,0.035283,0.005517,0.143776,0.027656,-0.016546,-0.030741,-0.043211,0.031853,0.039766,0.028586,0.018876,0.044129,0.012731,0.016450,-0.042827,0.003296,0.008975,0.022492,-0.000721,-0.025272,-0.010726,0.013386,0.029182,-0.017438,-0.026324,-0.024752,0.010201,0.025512,-0.008129,0.018312,-0.001578,0.038956,0.042948,-0.007893,0.006829,0.009135,0.049192,-0.004444,-0.024138,-0.002334,-0.039490,0.026251,-0.003523,0.035265,-0.001996,-0.022839,0.003269,0.037085,0.012528,-0.003244,-0.015484,0.001868,-0.009795,-0.005450,-0.016835,0.028385,-0.014542,0.024210,-0.009206,-0.002522,-0.017639,0.011022,0.015780,0.015545,0.034193,-0.010443,-0.020518,-0.005086,-0.037200,0.009048,0.017201,-0.028562,-0.004500,-0.058890,-0.017469,-0.012748,-0.004831,0.040934,0.010672,-0.010235,0.038972,0.006233,-0.009478,-0.016798,0.009256,0.015688,0.013538,-0.029836,0.004214,-0.008262,0.016109,-0.005081,-0.009207,0.008937,0.023484,-0.024659,0.003139,4.851416,0.068769,0.794735,0.032343,-0.115203,4.932276,4.289671
265796,2022-04-10 03:00:00,13,49.8444,24.0254,4.7,-0.3,72.3,0.0,0.0,0.00,0.0,0.0,32.0,13.3,314.8,1012.7,84.2,161.5,14.0,6.0,0.29,2.6,2.6,97.19,0.0,0.0,0.0,16.2,0.0,273.6,1010.3,60.0,0.0,0.1,0.0,False,True,False,False,False,True,False,False,2022,4,6,3,Lviv,Europe/Kiev,2022-04-10,06:42:00,20:09:31,03:00:00,Львівська,0,0.0,0.0,0.0,0.0,0.0,0.0,1,1,2.0,0.0,42,0.579789,-0.182491,0.367986,0.263701,0.048753,-0.120408,-0.022583,-0.147497,-0.075399,-0.122516,0.235828,-0.074884,0.009483,0.019953,0.019206,-0.125775,0.050856,-0.104043,0.070796,-0.068567,0.001164,0.082938,0.139350,0.097041,-0.039343,-0.025968,-0.091680,-0.053227,-0.017215,-0.025243,0.012713,-0.020271,0.000982,-0.006786,-0.009278,-0.029705,-0.013977,0.009644,-0.005145,-0.022335,-0.011327,-0.004124,-0.031132,0.015483,-0.011586,-0.015814,0.029660,0.017058,-0.004762,0.017482,-0.005198,0.008463,-0.015606,0.010385,0.014824,-0.023875,-0.008291,-0.076428,0.026614,0.048888,0.014680,0.004908,-0.013506,-0.025250,0.016170,0.003387,0.008908,-0.005884,-0.018203,0.015984,-0.003668,0.034128,0.038967,-0.021674,0.008884,0.008422,0.035207,-0.013762,-0.014777,0.001839,0.009192,-0.030204,-0.040175,-0.038483,-0.008099,0.025931,0.028755,0.010353,0.040336,0.012723,-0.004717,-0.019789,0.011717,-0.040138,-0.002525,-0.018699,0.018062,0.031936,-0.001820,0.032310,0.001567,0.022688,-0.032981,-0.005913,-0.019679,0.013441,0.015203,0.026864,0.004503,0.005171,-0.040279,0.001455,0.023399,0.032494,0.003743,0.000415,-0.020418,-0.021095,0.039859,-0.008951,0.011545,0.023052,0.016396,0.016309,-0.004767,0.018869,0.011746,0.016843,0.020851,-0.002414,0.014002,-0.004713,-0.007467,0.017496,-0.019326,-0.004191,-0.009145,-0.021100,0.038522,0.004137,0.002809,-0.042920,0.008130,-0.031919,0.003952,0.032847,0.015527,-0.001337,0.036354,-0.003877,5.348375,0.066052,0.579789,0.035656,-1.328800,6.177716,4.224985
212699,2022-04-03 12:00:00,10,50.4506,30.5243,1.3,-1.1,84.1,1.3,100.0,8.33,0.5,0.1,31.7,13.7,315.9,1002.7,99.0,89.8,7.8,3.0,0.05,1.7,-1.5,87.83,0.0,0.0,0.0,27.0,10.8,350.0,1001.7,100.0,345.0,1.2,3.0,False,False,False,True,False,True,False,False,2022,4,6,12,Kyiv,Europe/Kiev,2022-04-03,06:30:14,19:33:13,12:00:00,Київська,1,2.8,1.0,0.0,1.0,0.0,7.0,1,0,8.0,1.0,0,0.640281,-0.183918,0.299180,0.189085,0.060217,-0.109730,-0.026784,-0.053588,-0.040640,-0.052574,0.124048,-0.049811,-0.004990,0.016089,0.014665,-0.059050,0.030181,-0.116141,0.149160,0.048723,-0.093403,0.067822,-0.004512,0.007478,0.042023,-0.011809,0.127764,0.036029,0.099630,-0.007539,-0.049363,0.024775,0.012713,0.058348,-0.010632,0.020477,-0.074969,-0.039239,0.028090,-0.049340,-0.009046,-0.049528,-0.007578,-0.011935,-0.020404,-0.014676,0.028452,0.004698,0.037369,0.047143,0.033292,-0.040685,0.005275,0.032753,0.025524,-0.008125,-0.030783,-0.024228,0.050225,0.006870,0.017842,0.000682,-0.003056,0.014557,0.061424,0.012871,-0.026549,0.043492,0.011453,0.084403,0.005296,-0.003569,-0.037442,0.053765,0.046560,0.009344,-0.008332,-0.075275,0.027069,-0.046704,-0.009633,-0.001184,0.024179,-0.046445,-0.007453,-0.028514,0.002307,-0.072289,-0.048491,0.022297,0.008978,0.032289,-0.021354,-0.013130,0.028039,-0.049878,0.004793,-0.044769,0.024863,0.027244,0.007279,-0.038589,-0.001529,-0.027364,0.005802,-0.030147,-0.006487,0.093402,-0.022091,0.018807,0.012188,0.009778,0.013885,-0.033540,-0.003591,0.013036,-0.022596,0.034700,0.021740,-0.026814,-0.009019,0.034803,0.045781,-0.005902,-0.039412,0.002010,-0.053372,0.013043,0.021030,0.004567,0.000640,0.010667,0.034199,-0.032755,-0.022675,-0.029464,-0.029046,0.001178,-0.030902,-0.002643,0.012029,-0.003333,-0.045434,0.019698,0.030892,-0.033947,-0.026798,-0.006614,0.008452,-0.027306,5.812188,0.063081,0.640281,0.038748,0.493182,5.619091,4.402494
448546,2025-01-01 13:00:00,19,49.5527,25.5889,3.9,-2.9,62.7,0.0,0.0,0.00,0.0,0.0,46.1,28.8,243.5,1022.2,39.4,51.5,4.4,2.0,0.05,8.7,5.5,51.67,0.0,0.0,0.0,34.6,21.6,243.9,1021.0,8.5,247.1,0.9,2.0,False,True,False,False,True,False,False,False,2025,1,2,13,Ternopil,Europe/Kiev,2025-01-01,08:14:16,16:28:37,13:00:00,Тернопільська,0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,1.0,0.0,27,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-4.117675,1.415923,-0.000000
525281,2024-09-12 05:00:00,22,49.4168,26.9743,18.6,16.5,87.9,8.6,100.0,8.33,0.0,0.0,23.0,10.8,124.6,1007.6,91.7,75.5,6.6,3.0,0.31,17.0,17.0,91.47,0.0,0.0,0.0,12.6,4.7,66.5,1007.0,98.6,0.0,0.0,0.0,False,False,True,False,False,True,False,False,2024,9,3,5,Khmelnytskyi,Europe/Kiev,2024-09-12,06:44:23,19:31:16,05:00:00,Хмельницька,1,38.7,1.0,1.0,0.0,0.0,4.0,0,1,15.0,4.0,0,0.801238,0.033691,-0.042082,-0.021099,-0.117402,-0.006859,-0.045080,0.024867,0.116559,-0.152680,-0.003922,0.055439,0.203650,0.214215,0.037826,0.051309,0.020294,-0.084719,0.034766,0.035561,0.090771,-0.060425,0.008570,-0.005544,-0.022787,-0.037213,0.045517,-0.056605,0.045918,-0.021161,0.015574,0.015178,0.011871,-0.016568,0.006031,0.002013,0.024788,0.010720,0.036172,0.032688,0.003126,-0.029278,-0.000016,0.003493,-0.017471,-0.018790,-0.021516,-0.015344,-0.000229,-0.039568,-0.047659,-0.011856,-0.012421,-0.005697,-0.024935,-0.029420,-0.045407,-0.019704,-0.007229,-0.009953,-0.045547,-0.004124,0.012628,0.016846,0.003390,-0.032317,0.032869,-0.046712,-0.009661,0.010995,-0.011002,-0.020242,0.000819,0.008707,-0.004371,-0.022484,-0.028218,-0.028531,0.005464,0.005890,0.012024,-0.029657,-0.018332,0.014225,-0.013605,0.005651,0.037559,0.013792,0.001101,0.029850,-0.016675,0.020387,0.022610,-0.003481,0.004917,-0.049224,0.002712,-0.012138,-0.001357,0.027624,0.007651,-0.034057,0.005749,-0.036151,-0.005704,0.022071,0.005099,-0.015347,0.009091,-0.003456,0.017364,0.026502,0.002090,0.011636,-0.001854,-0.003666,-0.035690,-0.000975,-0.043950,0.009127,0.002991,0.024375,0.017908,0.008613,-0.022387,-0.003624,-0.013620,0.010438,0.012572,0.004859,-0.006724,-0.005655,0.000470,0.024682,0.003856,-0.008414,0.002703,0.015195,0.030635,0.024937,0.016072,-0.019116,0.009316,-0.005823,-0.003447,-0.018057,-0.001775,-0.001624,-0.015813,-0.010386,4.363540,0.070721,0.801238,0.029090,0.057725,4.370480,4.126445
273703,2023-03-05 14:00:00,13,49.8444,24.0254,-0.4,-6.4,65.2,0.6,100.0,8.33,0.5,0.5,45.7,23.8,282.3,1010.4,55.6,127.6,10.9,5.0,0.43,1.2,-4.0,51.90,0.0,0.0,0.0,45.0,21.6,280.0,1009.8,80.0,350.8,1.3,4.0,False,False,False,True,False,True,False,False,2023,3,6,14,Lviv,Europe/Kiev,2023-03-05,06:59:38,18:12:11,14:00:00,Львівська,0,0.0,0.0,0.0,0.0,0.0,0.0,1,0,0.0,0.0,51,0.746869,-0.206229,0.077302,0.021821,0.072241,-0.007435,-0.040040,0.107073,-0.027548,0.111565,-0.015769,-0.002468,-0.057950,0.037014,0.123495,-0.007205,0.054884,-0.048773,-0.091029,0.030226,0.038284,-0.065134,-0.166121,-0.095082,-0.170621,0.013454,-0.059698,-0.015932,0.030107,0.022263,-0.071226,-0.036284,-0.020088,0.046526,-0.096240,0.047448,0.021390,-0.040492,-0.006058,0.016955,-0.059811,-0.028165,0.028220,0.031508,-0.045340,-0.017763,0.019865,-0.000909,0.038357,0.005468,-0.060286,-0.003472,0.008272,0.005132,-0.011014,0.026902,-0.015470,0.018172,0.067392,-0.091783,0.027986,-0.082060,-0.015192,-0.015257,0.020828,0.002029,-0.000070,-0.021483,-0.006999,-0.002294,0.005627,0.005846,-0.019785,0.014307,0.035648,0.005642,0.050391,0.021890,0.017494,0.039675,-0.019792,0.032261,-0.032944,0.035793,-0.000194,0.038712,-0.016550,0.036910,-0.051826,-0.005785,0.011298,0.020421,0.057945,0.017842,-0.058491,-0.012386,0.057859,-0.013868,-0.025921,0.007988,-0.021964,-0.029124,0.045964,0.012892,-0.025141,-0.047700,-0.047011,0.024416,-0.061503,-0.033769,-0.011113,-0.022342,0.007373,0.033497,0.028511,-0.008552,0.007636,-0.014248,-0.006317,0.014248,-0.017727,-0.006494,0.022396,0.019341,0.014307,0.002893,0.014167,-0.003220,-0.029100,0.001883,-0.013365,0.009045,0.045457,-0.013014,0.030104,0.019349,0.017899,-0.036018,-0.034423,-0.011232,0.003284,0.008275,-0.016002,0.009147,0.043708,0.032361,0.006793,-0.000614,-0.039498,0.009857,5.549225,0.066830,0.746869,0.036995,1.023905,5.262626,4.381971
147075,2023-10-29 20:00:00,7,48.6264,22.2851,11.6,9.0,84.6,0.0,0.0,0.00,0.0,0.0,37.8,14.4,131.9,1013.0,72.7,21.3,1.8,1.0,0.52,16.5,16.5,72.37,0.0,0.0,0.0,32.8,10.8,169.0,1013.5,90.0,0.0,0.0,0.0,False,True,False,False,False,True,False,False,2023,10,6,20,Uzhgorod,Europe/Uzhgorod,2023-10-29,07:11:49,17:16:42,20:00:00,Закарпатська,0,0.0,0.0,0.0,0.0,0.0,0.0,1,0,2.0,0.0,31,0.797116,-0.088335,-0.127378,-0.164924,-0.044102,-0.135815,-0.143400,-0.048275,-0.113123,-0.038697,-0.067157,-0.022831,-0.082719,-0.032518,0.016520,-0.109752,0.064367,0.058151,0.043777,-0.064884,-0.069065,-0.009297,-0.068776,0.030989,0.058358,0.014635,-0.023696,-0.053633,0.016475,-0.019994,0.024161,-0.050809,0.022309,0.005433,0.044692,0.024029,0.010732,-0.033872,-0.040185,0.019885,0.052783,0.035091,0.030668,-0.001393,0.008423,-0.005131,-0.024797,-0.010149,-0.023074,0.021229,0.023148,-0.004382,0.052403,-0.008211,-0.010450,-0.027182,-0.004361,0.007471,0.056927,-0.027005,-0.048547,-0.019350,0.023363,-0.003295,-0.000937,0.035547,0.012031,-0.033729,-0.001505,-0.000392,0.044186,-0.009993,-0.031718,0.032751,0.003568,0.028147,-0.014178,-0.029473,0.015907,-0.038593,-0.000355,-0.019949,-0.008472,-0.014741,0.010380,-0.007146,-0.005699,0.034680,0.011243,-0.017868,-0.023005,-0.005620,0.010678,-0.010994,-0.011001,0.048075,0.008464,0.036578,0.037104,-0.024925,0.004200,-0.016803,-0.007230,0.041626,0.017643,-0.007741,-0.007574,0.028210,-0.021984,0.012410,0.002563,0.021962,-0.007802,-0.001379,0.009310,0.023723,-0.002656,-0.001814,-0.005729,0.030653,-0.027032,-0.011884,0.011807,0.045814,-0.038288,0.004526,-0.021033,0.016975,-0.018331,-0.011590,-0.016084,-0.000275,0.001714,-0.037973,0.016248,0.003543,-0.021161,-0.002745,0.004454,0.019040,0.042023,-0.036064,0.003537,-0.009397,0.000661,-0.028279,-0.018698,0.020167,0.000549,0.022831,4.899057,0.068965,0.797116,0.032660,-0.014734,4.896788,4.280514

### TELEGRAM MERGE

In [23]:
df_tg_matrix = pd.read_csv("../data/telegram_processed_svd.csv")

In [24]:
df_tg_matrix.head()

,date,channel,tg_topic_0,tg_topic_1,tg_topic_2,tg_topic_3,tg_topic_4,tg_topic_5,tg_topic_6,tg_topic_7,tg_topic_8,tg_topic_9,tg_topic_10,tg_topic_11,tg_topic_12,tg_topic_13,tg_topic_14,tg_topic_15,tg_topic_16,tg_topic_17,tg_topic_18,tg_topic_19,tg_topic_20,tg_topic_21,tg_topic_22,tg_topic_23,tg_topic_24,tg_topic_25,tg_topic_26,tg_topic_27,tg_topic_28,tg_topic_29,tg_topic_30,tg_topic_31,tg_topic_32,tg_topic_33,tg_topic_34,tg_topic_35,tg_topic_36,tg_topic_37,tg_topic_38,tg_topic_39,tg_topic_40,tg_topic_41,tg_topic_42,tg_topic_43,tg_topic_44,tg_topic_45,tg_topic_46,tg_topic_47,tg_topic_48,tg_topic_49,tg_topic_50,tg_topic_51,tg_topic_52,tg_topic_53,tg_topic_54,tg_topic_55,tg_topic_56,tg_topic_57,tg_topic_58,tg_topic_59,tg_topic_60,tg_topic_61,tg_topic_62,tg_topic_63,tg_topic_64,tg_topic_65,tg_topic_66,tg_topic_67,tg_topic_68,tg_topic_69,tg_topic_70,tg_topic_71,tg_topic_72,tg_topic_73,tg_topic_74,tg_topic_75,tg_topic_76,tg_topic_77,tg_topic_78,tg_topic_79,tg_topic_80,tg_topic_81,tg_topic_82,tg_topic_83,tg_topic_84,tg_topic_85,tg_topic_86,tg_topic_87,tg_topic_88,tg_topic_89,tg_topic_90,tg_topic_91,tg_topic_92,tg_topic_93,tg_topic_94,tg_topic_95,tg_topic_96,tg_topic_97,tg_topic_98,tg_topic_99,tg_topic_100,tg_topic_101,tg_topic_102,tg_topic_103,tg_topic_104,tg_topic_105,tg_topic_106,tg_topic_107,tg_topic_108,tg_topic_109,tg_topic_110,tg_topic_111,tg_topic_112,tg_topic_113,tg_topic_114,tg_topic_115,tg_topic_116,tg_topic_117,tg_topic_118,tg_topic_119,tg_topic_120,tg_topic_121,tg_topic_122,tg_topic_123,tg_topic_124,tg_topic_125,tg_topic_126,tg_topic_127,tg_topic_128,tg_topic_129,tg_topic_130,tg_topic_131,tg_topic_132,tg_topic_133,tg_topic_134,tg_topic_135,tg_topic_136,tg_topic_137,tg_topic_138,tg_topic_139,tg_topic_140,tg_topic_141,tg_topic_142,tg_topic_143,tg_topic_144,tg_topic_145,tg_topic_146,tg_topic_147,tg_topic_148,tg_topic_149,tg_topic_150,tg_topic_151,tg_topic_152,tg_topic_153,tg_topic_154,tg_topic_155,tg_topic_156,tg_topic_157,tg_topic_158,tg_topic_159,tg_topic_160,tg_topic_161,tg_topic_162,tg_topic_163,tg_topic_164,tg_topic_165,tg_topic_166,tg_topic_167,tg_topic_168,tg_topic_169,tg_topic_170,tg_topic_171,tg_topic_172,tg_topic_173,tg_topic_174,tg_topic_175,tg_topic_176,tg_topic_177,tg_topic_178,tg_topic_179,tg_topic_180,tg_topic_181,tg_topic_182,tg_topic_183,tg_topic_184,tg_topic_185,tg_topic_186,tg_topic_187,tg_topic_188,tg_topic_189,tg_topic_190,tg_topic_191,tg_topic_192,tg_topic_193,tg_topic_194,tg_topic_195,tg_topic_196,tg_topic_197,tg_topic_198,tg_topic_199,tg_topic_200,tg_topic_201,tg_topic_202,tg_topic_203,tg_topic_204,tg_topic_205,tg_topic_206,tg_topic_207,tg_topic_208,tg_topic_209,tg_topic_210,tg_topic_211,tg_topic_212,tg_topic_213,tg_topic_214,tg_topic_215,tg_topic_216,tg_topic_217,tg_topic_218,tg_topic_219,tg_topic_220,tg_topic_221,tg_topic_222,tg_topic_223,tg_topic_224,tg_topic_225,tg_topic_226,tg_topic_227,tg_topic_228,tg_topic_229,tg_topic_230,tg_topic_231,tg_topic_232,tg_topic_233,tg_topic_234,tg_topic_235,tg_topic_236,tg_topic_237,tg_topic_238,tg_topic_239,tg_topic_240,tg_topic_241,tg_topic_242,tg_topic_243,tg_topic_244,tg_topic_245,tg_topic_246,tg_topic_247,tg_topic_248,tg_topic_249
0,2026-03-06 13:06:58,DeepStateUA,0.007121,0.000107,0.019843,0.000990,-0.011395,0.032670,-0.050983,0.061080,0.042624,-0.024341,-0.018764,0.023404,-0.017137,-0.358836,0.425288,0.017966,-0.107660,-0.032066,-0.045986,0.118212,0.091172,-0.248637,-0.001069,0.150763,0.030603,-0.074030,0.005803,0.005871,0.034871,0.017239,0.058098,0.029814,-0.010845,0.031486,-0.022705,0.005607,-0.006324,-0.010169,0.024500,-0.015581,-0.012708,0.005139,0.007857,0.016734,-0.040289,-0.019688,-0.026763,0.009381,-0.043500,-0.009525,-0.013075,-0.010473,-0.018150,0.005988,0.032611,0.000850,0.017872,0.020885,0.023899,-0.019290,-0.006676,-0.018478,-0.023263,-0.005497,-0.006460,0.026051,0.004991,0.019687,-0.022244,0.010929,0.007016,-0.067349,-0.035249,-0.005686,0.018747,0.039159,-0.053868,-0.078189,-0.074737,-0.082163,0.020498,0.084336,0.113470,-0.025871,-0.048314,0.096330,0.043779,0.029575,0.019820,0.002819,-0.007308,-0.005234,-0.053796,-0.005893,0.036483,-0.061232,-0.001463,0.048285,-0.017340,0.033961,0.039046,-0.045463,-0.035894,-0.033875,0.041559,-0.021964,-0.005454,-0.020615,0.006442,-0.016322,-0.010443,-0.015532,0.000981,0.002928,-0.010924,-0.004072,-0.007252,-0.020386,0.007354,0.022114,-0.000884,-0.019901,-0.009325,-0.043505,0.008556,-0.016976,0.004765,0.030853,0.012413,0.011307,0.017726,0.010620,-0.013777,-0.037939,-0.003764,0.015808,-0.027407,-0.033773,0.054684,-0.005455,0.077819,0.006894,-0.022642,-0.011036,0.007590,-0.011639,0.036640,-0.020276,0.016764,-0.000467,-0.007996,0.023813,-0.014151,-0.026548,-0.078007,0.014955,0.043507,-0.021709,0.013392,-0.008661,0.012712,0.037409,-0.032628,-0.021403,-0.030711,0.033490,-0.025720,0.008100,-0.011149,-0.002706,0.002765,0.017707,-0.010806,-0.012850,0.007063,0.021780,0.010662,-0.031776,0.011750,0.069730,0.029703,0.012839,-0.031854,0.001635,-0.002149,-0.045445,0.002481,0.021315,0.006077,-0.006012,0.006578,-0.036587,0.009373,-0.025445,-0.019477,-0.011097,0.014675,-0.016785,0.010995,0.002045,-0.004600,-0.008963,0.006641,-0.017489,0.003821,0.005926,0.000537,-0.002830,-0.035321,-0.004957,0.013548,0.015414,0.018981,0.017932,-0.002853,0.007882,0.026621,0.003335,-0.001598,0.011594,-0.016659,0.001508,-0.007204,0.002975,0.001589,0.012191,0.005661,0.006600,-0.027472,0.014275,-0.020139,-0.011419,0.015111,-0.008120,0.001883,-0.011402,0.006871,0.024781,0.019495,0.024153,0.017141,-0.013944,-0.027516,0.034612,-0.032061,-0.051141,-0.004707,-0.003985,-0.052194,-0.026334
1,2026-03-06 12:57:29,DeepStateUA,0.022770,-0.002163,0.041469,0.001527,-0.033584,0.077087,-0.078417,0.091534,0.014917,-0.016270,-0.019775,0.015028,-0.012900,-0.066689,0.049295,-0.031093,0.006109,-0.021357,-0.047947,0.025239,-0.010092,0.063969,0.026579,-0.002938,0.000962,-0.014692,-0.010761,0.001202,-0.015000,-0.005930,-0.010839,0.049023,-0.023754,0.030922,0.000492,-0.009320,-0.015764,0.024560,0.006807,-0.000411,-0.001480,-0.017302,-0.026282,0.007343,0.049168,-0.004316,0.029036,-0.034987,0.034368,-0.046229,-0.012751,0.048371,0.004354,-0.014649,0.034935,-0.016468,-0.013150,0.017354,-0.000886,0.004047,0.036549,-0.017461,0.009667,-0.007887,-0.027599,-0.016937,-0.037606,-0.009493,-0.002735,-0.006034,0.023060,0.028297,0.024781,0.010909,-0.000544,-0.016357,-0.003670,-0.016336,0.002609,0.013846,-0.005648,-0.012539,-0.007839,-0.041249,0.030814,-0.017629,-0.005069,-0.024100,-0.013485,0.010861,-0.015271,-0.006842,-0.013700,0.008861,-0.010810,0.022671,-0.034102,-0.016120,0.001828,0.003954,0.007680,-0.037762,-0.017967,0.016946,0.016302,-0.011406,0.021384,-0.001978,-0.005628,-0.080374,0.039484,0.015890,0.034496,-0.016936,0.004379,-0.005021,0.014321,-0.003484,-0.002882,-0.002483,-0.005047,0.017296,-0.003401,0.009433,-0.001665,0.018296,0.003151,-0.031688,0.003527,0.010405,-0.006932,-0.019232,-0.004084,-0.023476,-0.008857,-0.015648,0.053937,0.034130,-0.026430,0.018625,-0.050338,0.022854,-0.000992,0.001886,-0.013131,0.037482,0.025278,-0.008833,-0.009892,0.015771,-0.019763,-0.015569,-0.015169,0.040201,0.018226,0.018286,-0.011713,-0.000436,0.000451,0.012252,0.007596,-0.000338,0.004704,0.023604,-0.020461,0.016871,0.003246,-0.045373,0.004746,-0.036469,-0.025234,0.030737,-0.000797,0.015820,0.042129,0.010345,0.022695,0.005339,-0.001636,-0.018894,0.026074,-0.054026,-0.057851,0.004372,-0.020828,-0.034435,0.055865,0.016301,0.063019,0.010370,-0.004495,-0.030530,0.018833,-0.013644,0.002207,0.037501,-0.045908,-0.059514,-0.035367,-0.024918,-0.039085,0.035208,0.085963,0.009390,0.079267,0.013885,0.006535,-0.052116,-0.033637,0.008546,-0.019285,0.006149,0.002710,-0.056530,-0.022435,0.020384,-0.013988,-0.005111,-0.015295,-0.097911,-0.042214,0.020642,-0.042973,0.045024,0.005130,-0.022150,0.006530,0.054045,-0.042555,0.006345,-0.035607,-0.006021,0.000036,-0.033672,0.020923,-0.000556,-0.034840,0.034524,0.004798,0.001867,-0.019097,0.025730,0.000530,0.020332,-0.028041,0.001581,0.006948,-0.064965,0.022597,-0.017810
2,2026-03-06 08:32:47,DeepStateUA,0.009647,-0.001083,0.029820,0.004092,-0.021362,0.053647,-0.076998,0.085930,0.011210,-0.020903,-0.051377,0.013232,-0.021159,0.001682,0.049129,-0.010018,-0.014271,-0.012423,-0.010588,0.046603,0.026875,0.002452,0.003347,-0.018525,0.005328,-0.003516,0.003550,0.018054,0.002157,0.012886,0.034851,0.000381,-0.009230,-0.002467,0.002381,0.000435,0.000842,-0.004257,-0.003348,0.009321,-0.005701,-0.004301,-0.016552,-0.001785,0.016005,0.008306,0.000706,-0.004439,-0.004069,-0.017177,-0.017974,-0.000361,-0.033317,-0.032714,0.027864,-0.006006,0.000665,-0.001117,-0.020576,0.002026,0.001386,0.000074,0.000035,0.007953,0.005774,0.005407,-0.005473,0.009134,-0.010858,-0.014439,0.028165,-0.023096,0.014483,0.021402,-0.017701,0.035852,-0.021296,-0.016145,-0.007317,-0.016939,0.014848,-0.006705,-0.047833,-0.002701,0.006144,-0.016566,0.016766,0.017487,0.002922,-0.004175,0.003020,-0.032485,0.001179,0.015611,0.015266,0.023711,0.005134,-0.030744,-0.014357,0.024034,0.016933,-0.044400,0.005215,0.011766,-0.026130,-0.005996,0.011388,-0.012677,-0.016358,-0.020579,-0.003119,-0.003134,0.019595,-0.011791,0.015521,0.022933,0.013426,0.013833,-0.006377,0.006772,-0.023631,0.008806,0.003886,0.014650,-0.029616,0.047030,0.005467,-0.020456,0.018529,-0.009387,0.010160,0.010283,-0.016104,0.038236,-0.028747,0.030649,0.028343,0.020708,0.001123,-0.009186,-0.064016,0.007831,0.005442,0.008333,-0.002820,0.007245,0.037716,-0.034047,0.009513,0.002276,-0.009623,-0.009046,0.023603,-0.009777,-0.047725,0.011991,-0.016423,0.004245,0.039250,0.030454,-0.007661,-0.043307,-0.005340,-0.003352,0.004921,0.010619,0.011745,-0.029661,-0.016769,-0.004054,-0.019134,-0.010521,-0.016018,0.013938,0.061204,0.000223,-0.016080,-0.013129,0.011080,0.025287,0.030597,-0.001902,-0.032930,0.022210,0.024393,-0.023036,0.001308,-0.010151,0.002527,0.003083,0.002821,0.012997,0.008941,-0.011744,0.019257,-0.000326,0.025398,-0.044011,-0.021810,-0.040764,-0.011043,0.008865,-0.020367,-0.005459,0.002685,0.019290,0.025485,-0.019258,-0.011527,-0.015354,-0.003904,0.007485,0.039596,0.030817,-0.034836,0.029725,0.018850,0.009886,0.006251,-0.006886,-0.028339,-0.017251,-0.019577,-0.004734,-0.014053,-0.014076,-0.018760,-0.006640,0.002467,-0.014727,0.015968,-0.020566,-0.000171,-0.020244,0.003823,-0.020505,-0.006361,-0.011117,-0.002427,0.036069,0.025378,-0.003550,-0.043415,-0.007200,-0.009172,0.006124,-0.004550,0.020576,0.010544,0.012825
3,2026-03-05 16:46:58,DeepStateUA,0.006857,0.000279,0.019019,0.000875,-0.011544,0.032104,-0.049929,0.059696,0.042415,-0.023916,-0.020173,0.022363,-0.016425,-0.354007,0.422410,0.017232,-0.106286,-0.032499,-0.045502,0.118053,0.090722,-0.246774,-0.000077,0.150527,0.029981,-0.074173,0.006982,0.007685,0.035762,0.018338,0.059439,0.029451,-0.012747,0.032325,-0.024156,0.006144,-0.004921,-0.007047,0.024916,-0.013464,-0.012810,0.004618,0.006305,0.017777,-0.037226,-0.018749,-0.026076,0.008026,-0.040668,-0.008455,-0.012120,-0.009955,-0.018018,0.006661,0.032070,0.001406,0.015931,0.020066,0.022360,-0.017343,-0.007000,-0.017683,-0.021564,-0.005667,-0.004897,0.022713,0.002352,0.021026,-0.020492,0.010265,0.006341,-0.062306,-0.031869,-0.004833,0.019042,0.034739,-0.048355,-0.072654,-0.066847,-0.074661,0.019525,0.081765,0.106477,-0.025839,-0.046011,0.091824,0.043276,0.026990,0.018548,0.002251,-0.006682,-0.005199,-0.051075,-0.003017,0.029777,-0.054537,-0.002321,0.044861,-0.018019,0.033038,0.036190,-0.042962,-0.033109,-0.031216,0.040022,-0.016626,-0.004321,-0.022597,0.001446,-0.018905,-0.015046,-0.006992,0.004125,0.000550,-0.011207,-0.006348,-0.005325,-0.023457,0.009404,0.021777,-0.001560,-0.021654,-0.010065,-0.041095,0.009058,-0.016847,0.014130,0.030820,0.014433,0.011400,0.017331,0.012039,-0.011976,-0.037318,-0.000059,0.013755,-0.023928,-0.033049,0.051293,-0.004679,0.075124,0.004404,-0.023162,-0.009870,0.008475,-0.011321,0.038668,-0.021760,0.017180,-0.003656,-0.004497,0.024860,-0.010259,-0.023728,-0.073984,0.014863,0.037362,-0.023343,0.010636,-0.008617,0.012118,0.033946,-0.033242,-0.018743,-0.029519,0.034794,-0.025605,0.008930,-0.006082,-0.003809,-0.002692,0.017623,-0.010778,-0.010494,0.004241,0.018071,0.015268,-0.027505,0.007476,0.058355,0.024457,0.010803,-0.030662,-0.001728,-0.001191,-0.040228,0.003914,0.019603,0.006112,-0.006858,0.006677,-0.036682,0.007404,-0.025808,-0.014273,-0.007471,0.014518,-0.012831,0.005292,-0.002303,-0.003711,-0.008705,0.000811,-0.012632,0.003962,0.004388,0.000392,0.002013,-0.028686,-0.003865,0.011868,0.012458,0.016571,0.009521,-0.001085,0.007509,0.021553,0.002596,0.005686,0.003029,-0.016085,0.005070,-0.006296,0.000888,0.002830,0.014467,0.006547,0.000059,-0.020972,0.009385,-0.014722,-0.008414,0.016377,-0.008301,-0.000710,-0.008819,0.006663,0.012456,0.012080,0.020719,0.008728,-0.007502,-0.021433,0.028223,-0.025323,-0.045761,-0.001697,0.002329,-0.042282,-0.017344
4,2026-03-05 15:46:39,DeepStateUA,0.048850,-0.006687,0.076040,-0.003924,-0.027197,0.089562,-0.088811,0.109836,0.052317,-0.025058,0.032393,-0.004227,-0.005032,-0.173462,0.094957,0.012582,-0.022470,-0.000701,-0.014110,-0.004739,-0.012713,0.127035,0.018404,-0.023593,0.003993,0.039285,-0.018524,0.000346,-0.081926,-0.045456,-0.116434,-0.028074,-0.013547,0.024679,0.046939,-0.021634,0.023138,0.009856,-0.025864,-0.041176,-0.000832,-0.024707,0.013634,-0.022765,0.057346,0.020489,0.010217,-0.026627,0.022514,0.022439,0.035388,-0.021224,0.008281,-0.000369,-0.015992,0.012876,-0.018086,-0.005188,-0.021093,0.012907,-0.008576,-0.008820,0.030578,0.014680,0.017475,0.007797,0.004474,-0.006686,0.023422,0.017913,0.009466,-0.011255,-0.006200,0.008317,-0.038521,0.017131,0.046956,0.005528,0.071628,0.044144,-0.006390,0.009272,-0.010302,-0.023798,0.013099,0.004949,0.000502,-0.025377,0.000576,0.005652,0.013762,-0.033165,0.011959,0.032019,-0.010729,0.074746,-0.045156,-0.069856,0.017151,-0.028899,-0.001317,-0.020143,-0.001444,0.077727,0.008474,0.017218,0.063803,0.022661,-0.019578,-0.089309,0.043190,0.054776,0.003839,0.005619,0.042291,-0.040703,0.034216,-0.018434,0.026249,-0.012015,0.004663,0.009540,0.028979,0.022277,0.015843,0.026390,-0.030022,-0.019719,0.008557,-0.006588,-0.012466,-0.013107,0.000680,-0.040800,0.018810,-0.018852,0.015615,-0.026299,-0.013060,-0.022985,-0.019649,0.003882,0.019573,0.020302,-0.053045,-0.013295,-0.013323,0.043432,-0.020309,-0.004050,-0.017728,-0.008395,-0.063169,-0.008017,0.060143,-0.036649,-0.009351,-0.031419,-0.019356,0.002941,0.015680,0.058794,0.034299,0.025507,0.026522,-0.024327,0.001476,-0.008036,-0.008201,0.018152,0.016011,-0.009222,0.020974,0.008694,-0.047264,0.028262,-0.002851,0.009422,-0.012002,0.004519,-0.010160,-0.031831,-0.005528,0.038708,-0.014277,0.009808,0.004059,-0.009500,0.033000,-0.038357,-0.005480,0.016188,-0.012154,-0.003113,0.007213,-0.049557,0.001337,0.025862,0.002217,0.009792,-0.002905,0.012793,-0.039633,-0.014680,0.012541,-0.026685,-0.057037,-0.038288,-0.031196,-0.025930,0.009651,0.004537,0.035687,-0.013257,0.015052,-0.006502,0.018667,-0.013956,0.023991,0.033361,-0.000124,-0.000186,0.012095,0.023317,0.014021,-0.007477,-0.006606,-0.045891,0.004310,-0.008439,0.004574,-0.039585,0.004941,0.010379,-0.002950,-0.053005,0.008541,-0.002762,0.010718,0.035433,0.017978,0.027453,-0.019744,0.008659,0.023139,-0.009485,-0.030263,0.013689,-0.022727,0.006843

In [25]:
df_tg_matrix["datetime_hour"] = pd.to_datetime(df_tg_matrix["date"]).dt.floor("h")

C:\Users\Uw11\AppData\Local\Temp\ipykernel_9376\2851151304.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_tg_matrix["datetime_hour"] = pd.to_datetime(df_tg_matrix["date"]).dt.floor("h")

In [26]:
topic_cols = [c for c in df_tg_matrix.columns if "tg_topic_" in c]

tg_hourly = (
    df_tg_matrix.groupby("datetime_hour")[topic_cols]
    .mean()
    .sort_index()
    .reset_index()
)

C:\Users\Uw11\AppData\Local\Temp\ipykernel_9376\2188712141.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  .reset_index()

In [27]:
df_tg_matrix.head()

,date,channel,tg_topic_0,tg_topic_1,tg_topic_2,tg_topic_3,tg_topic_4,tg_topic_5,tg_topic_6,tg_topic_7,tg_topic_8,tg_topic_9,tg_topic_10,tg_topic_11,tg_topic_12,tg_topic_13,tg_topic_14,tg_topic_15,tg_topic_16,tg_topic_17,tg_topic_18,tg_topic_19,tg_topic_20,tg_topic_21,tg_topic_22,tg_topic_23,tg_topic_24,tg_topic_25,tg_topic_26,tg_topic_27,tg_topic_28,tg_topic_29,tg_topic_30,tg_topic_31,tg_topic_32,tg_topic_33,tg_topic_34,tg_topic_35,tg_topic_36,tg_topic_37,tg_topic_38,tg_topic_39,tg_topic_40,tg_topic_41,tg_topic_42,tg_topic_43,tg_topic_44,tg_topic_45,tg_topic_46,tg_topic_47,tg_topic_48,tg_topic_49,tg_topic_50,tg_topic_51,tg_topic_52,tg_topic_53,tg_topic_54,tg_topic_55,tg_topic_56,tg_topic_57,tg_topic_58,tg_topic_59,tg_topic_60,tg_topic_61,tg_topic_62,tg_topic_63,tg_topic_64,tg_topic_65,tg_topic_66,tg_topic_67,tg_topic_68,tg_topic_69,tg_topic_70,tg_topic_71,tg_topic_72,tg_topic_73,tg_topic_74,tg_topic_75,tg_topic_76,tg_topic_77,tg_topic_78,tg_topic_79,tg_topic_80,tg_topic_81,tg_topic_82,tg_topic_83,tg_topic_84,tg_topic_85,tg_topic_86,tg_topic_87,tg_topic_88,tg_topic_89,tg_topic_90,tg_topic_91,tg_topic_92,tg_topic_93,tg_topic_94,tg_topic_95,tg_topic_96,tg_topic_97,tg_topic_98,tg_topic_99,tg_topic_100,tg_topic_101,tg_topic_102,tg_topic_103,tg_topic_104,tg_topic_105,tg_topic_106,tg_topic_107,tg_topic_108,tg_topic_109,tg_topic_110,tg_topic_111,tg_topic_112,tg_topic_113,tg_topic_114,tg_topic_115,tg_topic_116,tg_topic_117,tg_topic_118,tg_topic_119,tg_topic_120,tg_topic_121,tg_topic_122,tg_topic_123,tg_topic_124,tg_topic_125,tg_topic_126,tg_topic_127,tg_topic_128,tg_topic_129,tg_topic_130,tg_topic_131,tg_topic_132,tg_topic_133,tg_topic_134,tg_topic_135,tg_topic_136,tg_topic_137,tg_topic_138,tg_topic_139,tg_topic_140,tg_topic_141,tg_topic_142,tg_topic_143,tg_topic_144,tg_topic_145,tg_topic_146,tg_topic_147,tg_topic_148,tg_topic_149,tg_topic_150,tg_topic_151,tg_topic_152,tg_topic_153,tg_topic_154,tg_topic_155,tg_topic_156,tg_topic_157,tg_topic_158,tg_topic_159,tg_topic_160,tg_topic_161,tg_topic_162,tg_topic_163,tg_topic_164,tg_topic_165,tg_topic_166,tg_topic_167,tg_topic_168,tg_topic_169,tg_topic_170,tg_topic_171,tg_topic_172,tg_topic_173,tg_topic_174,tg_topic_175,tg_topic_176,tg_topic_177,tg_topic_178,tg_topic_179,tg_topic_180,tg_topic_181,tg_topic_182,tg_topic_183,tg_topic_184,tg_topic_185,tg_topic_186,tg_topic_187,tg_topic_188,tg_topic_189,tg_topic_190,tg_topic_191,tg_topic_192,tg_topic_193,tg_topic_194,tg_topic_195,tg_topic_196,tg_topic_197,tg_topic_198,tg_topic_199,tg_topic_200,tg_topic_201,tg_topic_202,tg_topic_203,tg_topic_204,tg_topic_205,tg_topic_206,tg_topic_207,tg_topic_208,tg_topic_209,tg_topic_210,tg_topic_211,tg_topic_212,tg_topic_213,tg_topic_214,tg_topic_215,tg_topic_216,tg_topic_217,tg_topic_218,tg_topic_219,tg_topic_220,tg_topic_221,tg_topic_222,tg_topic_223,tg_topic_224,tg_topic_225,tg_topic_226,tg_topic_227,tg_topic_228,tg_topic_229,tg_topic_230,tg_topic_231,tg_topic_232,tg_topic_233,tg_topic_234,tg_topic_235,tg_topic_236,tg_topic_237,tg_topic_238,tg_topic_239,tg_topic_240,tg_topic_241,tg_topic_242,tg_topic_243,tg_topic_244,tg_topic_245,tg_topic_246,tg_topic_247,tg_topic_248,tg_topic_249,datetime_hour
0,2026-03-06 13:06:58,DeepStateUA,0.007121,0.000107,0.019843,0.000990,-0.011395,0.032670,-0.050983,0.061080,0.042624,-0.024341,-0.018764,0.023404,-0.017137,-0.358836,0.425288,0.017966,-0.107660,-0.032066,-0.045986,0.118212,0.091172,-0.248637,-0.001069,0.150763,0.030603,-0.074030,0.005803,0.005871,0.034871,0.017239,0.058098,0.029814,-0.010845,0.031486,-0.022705,0.005607,-0.006324,-0.010169,0.024500,-0.015581,-0.012708,0.005139,0.007857,0.016734,-0.040289,-0.019688,-0.026763,0.009381,-0.043500,-0.009525,-0.013075,-0.010473,-0.018150,0.005988,0.032611,0.000850,0.017872,0.020885,0.023899,-0.019290,-0.006676,-0.018478,-0.023263,-0.005497,-0.006460,0.026051,0.004991,0.019687,-0.022244,0.010929,0.007016,-0.067349,-0.035249,-0.005686,0.018747,0.039159,-0.053868,-0.078189,-0.074737,-0.082163,0.020498,0.084336,0.113470,-0.025871,-0.048314,0.096330,0.043779,0.029575,0.019820,0.002819,-0.007308,-0.005234,-0.053796,-0.005893,0.036483,-0.061232,-0.001463,0.048285,-0.017340,0.033961,0.039046,-0.045463,-0.035894,-0.033875,0.041559,-0.021964,-0.005454,-0.020615,0.006442,-0.016322,-0.010443,-0.015532,0.000981,0.002928,-0.010924,-0.004072,-0.007252,-0.020386,0.007354,0.022114,-0.000884,-0.019901,-0.009325,-0.043505,0.008556,-0.016976,0.004765,0.030853,0.012413,0.011307,0.017726,0.010620,-0.013777,-0.037939,-0.003764,0.015808,-0.027407,-0.033773,0.054684,-0.005455,0.077819,0.006894,-0.022642,-0.011036,0.007590,-0.011639,0.036640,-0.020276,0.016764,-0.000467,-0.007996,0.023813,-0.014151,-0.026548,-0.078007,0.014955,0.043507,-0.021709,0.013392,-0.008661,0.012712,0.037409,-0.032628,-0.021403,-0.030711,0.033490,-0.025720,0.008100,-0.011149,-0.002706,0.002765,0.017707,-0.010806,-0.012850,0.007063,0.021780,0.010662,-0.031776,0.011750,0.069730,0.029703,0.012839,-0.031854,0.001635,-0.002149,-0.045445,0.002481,0.021315,0.006077,-0.006012,0.006578,-0.036587,0.009373,-0.025445,-0.019477,-0.011097,0.014675,-0.016785,0.010995,0.002045,-0.004600,-0.008963,0.006641,-0.017489,0.003821,0.005926,0.000537,-0.002830,-0.035321,-0.004957,0.013548,0.015414,0.018981,0.017932,-0.002853,0.007882,0.026621,0.003335,-0.001598,0.011594,-0.016659,0.001508,-0.007204,0.002975,0.001589,0.012191,0.005661,0.006600,-0.027472,0.014275,-0.020139,-0.011419,0.015111,-0.008120,0.001883,-0.011402,0.006871,0.024781,0.019495,0.024153,0.017141,-0.013944,-0.027516,0.034612,-0.032061,-0.051141,-0.004707,-0.003985,-0.052194,-0.026334,2026-03-06 13:00:00
1,2026-03-06 12:57:29,DeepStateUA,0.022770,-0.002163,0.041469,0.001527,-0.033584,0.077087,-0.078417,0.091534,0.014917,-0.016270,-0.019775,0.015028,-0.012900,-0.066689,0.049295,-0.031093,0.006109,-0.021357,-0.047947,0.025239,-0.010092,0.063969,0.026579,-0.002938,0.000962,-0.014692,-0.010761,0.001202,-0.015000,-0.005930,-0.010839,0.049023,-0.023754,0.030922,0.000492,-0.009320,-0.015764,0.024560,0.006807,-0.000411,-0.001480,-0.017302,-0.026282,0.007343,0.049168,-0.004316,0.029036,-0.034987,0.034368,-0.046229,-0.012751,0.048371,0.004354,-0.014649,0.034935,-0.016468,-0.013150,0.017354,-0.000886,0.004047,0.036549,-0.017461,0.009667,-0.007887,-0.027599,-0.016937,-0.037606,-0.009493,-0.002735,-0.006034,0.023060,0.028297,0.024781,0.010909,-0.000544,-0.016357,-0.003670,-0.016336,0.002609,0.013846,-0.005648,-0.012539,-0.007839,-0.041249,0.030814,-0.017629,-0.005069,-0.024100,-0.013485,0.010861,-0.015271,-0.006842,-0.013700,0.008861,-0.010810,0.022671,-0.034102,-0.016120,0.001828,0.003954,0.007680,-0.037762,-0.017967,0.016946,0.016302,-0.011406,0.021384,-0.001978,-0.005628,-0.080374,0.039484,0.015890,0.034496,-0.016936,0.004379,-0.005021,0.014321,-0.003484,-0.002882,-0.002483,-0.005047,0.017296,-0.003401,0.009433,-0.001665,0.018296,0.003151,-0.031688,0.003527,0.010405,-0.006932,-0.019232,-0.004084,-0.023476,-0.008857,-0.015648,0.053937,0.034130,-0.026430,0.018625,-0.050338,0.022854,-0.000992,0.001886,-0.013131,0.037482,0.025278,-0.008833,-0.009892,0.015771,-0.019763,-0.015569,-0.015169,0.040201,0.018226,0.018286,-0.011713,-0.000436,0.000451,0.012252,0.007596,-0.000338,0.004704,0.023604,-0.020461,0.016871,0.003246,-0.045373,0.004746,-0.036469,-0.025234,0.030737,-0.000797,0.015820,0.042129,0.010345,0.022695,0.005339,-0.001636,-0.018894,0.026074,-0.054026,-0.057851,0.004372,-0.020828,-0.034435,0.055865,0.016301,0.063019,0.010370,-0.004495,-0.030530,0.018833,-0.013644,0.002207,0.037501,-0.045908,-0.059514,-0.035367,-0.024918,-0.039085,0.035208,0.085963,0.009390,0.079267,0.013885,0.006535,-0.052116,-0.033637,0.008546,-0.019285,0.006149,0.002710,-0.056530,-0.022435,0.020384,-0.013988,-0.005111,-0.015295,-0.097911,-0.042214,0.020642,-0.042973,0.045024,0.005130,-0.022150,0.006530,0.054045,-0.042555,0.006345,-0.035607,-0.006021,0.000036,-0.033672,0.020923,-0.000556,-0.034840,0.034524,0.004798,0.001867,-0.019097,0.025730,0.000530,0.020332,-0.028041,0.001581,0.006948,-0.064965,0.022597,-0.017810,2026-03-06 12:00:00
2,2026-03-06 08:32:47,DeepStateUA,0.009647,-0.001083,0.029820,0.004092,-0.021362,0.053647,-0.076998,0.085930,0.011210,-0.020903,-0.051377,0.013232,-0.021159,0.001682,0.049129,-0.010018,-0.014271,-0.012423,-0.010588,0.046603,0.026875,0.002452,0.003347,-0.018525,0.005328,-0.003516,0.003550,0.018054,0.002157,0.012886,0.034851,0.000381,-0.009230,-0.002467,0.002381,0.000435,0.000842,-0.004257,-0.003348,0.009321,-0.005701,-0.004301,-0.016552,-0.001785,0.016005,0.008306,0.000706,-0.004439,-0.004069,-0.017177,-0.017974,-0.000361,-0.033317,-0.032714,0.027864,-0.006006,0.000665,-0.001117,-0.020576,0.002026,0.001386,0.000074,0.000035,0.007953,0.005774,0.005407,-0.005473,0.009134,-0.010858,-0.014439,0.028165,-0.023096,0.014483,0.021402,-0.017701,0.035852,-0.021296,-0.016145,-0.007317,-0.016939,0.014848,-0.006705,-0.047833,-0.002701,0.006144,-0.016566,0.016766,0.017487,0.002922,-0.004175,0.003020,-0.032485,0.001179,0.015611,0.015266,0.023711,0.005134,-0.030744,-0.014357,0.024034,0.016933,-0.044400,0.005215,0.011766,-0.026130,-0.005996,0.011388,-0.012677,-0.016358,-0.020579,-0.003119,-0.003134,0.019595,-0.011791,0.015521,0.022933,0.013426,0.013833,-0.006377,0.006772,-0.023631,0.008806,0.003886,0.014650,-0.029616,0.047030,0.005467,-0.020456,0.018529,-0.009387,0.010160,0.010283,-0.016104,0.038236,-0.028747,0.030649,0.028343,0.020708,0.001123,-0.009186,-0.064016,0.007831,0.005442,0.008333,-0.002820,0.007245,0.037716,-0.034047,0.009513,0.002276,-0.009623,-0.009046,0.023603,-0.009777,-0.047725,0.011991,-0.016423,0.004245,0.039250,0.030454,-0.007661,-0.043307,-0.005340,-0.003352,0.004921,0.010619,0.011745,-0.029661,-0.016769,-0.004054,-0.019134,-0.010521,-0.016018,0.013938,0.061204,0.000223,-0.016080,-0.013129,0.011080,0.025287,0.030597,-0.001902,-0.032930,0.022210,0.024393,-0.023036,0.001308,-0.010151,0.002527,0.003083,0.002821,0.012997,0.008941,-0.011744,0.019257,-0.000326,0.025398,-0.044011,-0.021810,-0.040764,-0.011043,0.008865,-0.020367,-0.005459,0.002685,0.019290,0.025485,-0.019258,-0.011527,-0.015354,-0.003904,0.007485,0.039596,0.030817,-0.034836,0.029725,0.018850,0.009886,0.006251,-0.006886,-0.028339,-0.017251,-0.019577,-0.004734,-0.014053,-0.014076,-0.018760,-0.006640,0.002467,-0.014727,0.015968,-0.020566,-0.000171,-0.020244,0.003823,-0.020505,-0.006361,-0.011117,-0.002427,0.036069,0.025378,-0.003550,-0.043415,-0.007200,-0.009172,0.006124,-0.004550,0.020576,0.010544,0.012825,2026-03-06 08:00:00
3,2026-03-05 16:46:58,DeepStateUA,0.006857,0.000279,0.019019,0.000875,-0.011544,0.032104,-0.049929,0.059696,0.042415,-0.023916,-0.020173,0.022363,-0.016425,-0.354007,0.422410,0.017232,-0.106286,-0.032499,-0.045502,0.118053,0.090722,-0.246774,-0.000077,0.150527,0.029981,-0.074173,0.006982,0.007685,0.035762,0.018338,0.059439,0.029451,-0.012747,0.032325,-0.024156,0.006144,-0.004921,-0.007047,0.024916,-0.013464,-0.012810,0.004618,0.006305,0.017777,-0.037226,-0.018749,-0.026076,0.008026,-0.040668,-0.008455,-0.012120,-0.009955,-0.018018,0.006661,0.032070,0.001406,0.015931,0.020066,0.022360,-0.017343,-0.007000,-0.017683,-0.021564,-0.005667,-0.004897,0.022713,0.002352,0.021026,-0.020492,0.010265,0.006341,-0.062306,-0.031869,-0.004833,0.019042,0.034739,-0.048355,-0.072654,-0.066847,-0.074661,0.019525,0.081765,0.106477,-0.025839,-0.046011,0.091824,0.043276,0.026990,0.018548,0.002251,-0.006682,-0.005199,-0.051075,-0.003017,0.029777,-0.054537,-0.002321,0.044861,-0.018019,0.033038,0.036190,-0.042962,-0.033109,-0.031216,0.040022,-0.016626,-0.004321,-0.022597,0.001446,-0.018905,-0.015046,-0.006992,0.004125,0.000550,-0.011207,-0.006348,-0.005325,-0.023457,0.009404,0.021777,-0.001560,-0.021654,-0.010065,-0.041095,0.009058,-0.016847,0.014130,0.030820,0.014433,0.011400,0.017331,0.012039,-0.011976,-0.037318,-0.000059,0.013755,-0.023928,-0.033049,0.051293,-0.004679,0.075124,0.004404,-0.023162,-0.009870,0.008475,-0.011321,0.038668,-0.021760,0.017180,-0.003656,-0.004497,0.024860,-0.010259,-0.023728,-0.073984,0.014863,0.037362,-0.023343,0.010636,-0.008617,0.012118,0.033946,-0.033242,-0.018743,-0.029519,0.034794,-0.025605,0.008930,-0.006082,-0.003809,-0.002692,0.017623,-0.010778,-0.010494,0.004241,0.018071,0.015268,-0.027505,0.007476,0.058355,0.024457,0.010803,-0.030662,-0.001728,-0.001191,-0.040228,0.003914,0.019603,0.006112,-0.006858,0.006677,-0.036682,0.007404,-0.025808,-0.014273,-0.007471,0.014518,-0.012831,0.005292,-0.002303,-0.003711,-0.008705,0.000811,-0.012632,0.003962,0.004388,0.000392,0.002013,-0.028686,-0.003865,0.011868,0.012458,0.016571,0.009521,-0.001085,0.007509,0.021553,0.002596,0.005686,0.003029,-0.016085,0.005070,-0.006296,0.000888,0.002830,0.014467,0.006547,0.000059,-0.020972,0.009385,-0.014722,-0.008414,0.016377,-0.008301,-0.000710,-0.008819,0.006663,0.012456,0.012080,0.020719,0.008728,-0.007502,-0.021433,0.028223,-0.025323,-0.045761,-0.001697,0.002329,-0.042282,-0.017344,2026-03-05 16:00:00
4,2026-03-05 15:46:39,DeepStateUA,0.048850,-0.006687,0.076040,-0.003924,-0.027197,0.089562,-0.088811,0.109836,0.052317,-0.025058,0.032393,-0.004227,-0.005032,-0.173462,0.094957,0.012582,-0.022470,-0.000701,-0.014110,-0.004739,-0.012713,0.127035,0.018404,-0.023593,0.003993,0.039285,-0.018524,0.000346,-0.081926,-0.045456,-0.116434,-0.028074,-0.013547,0.024679,0.046939,-0.021634,0.023138,0.009856,-0.025864,-0.041176,-0.000832,-0.024707,0.013634,-0.022765,0.057346,0.020489,0.010217,-0.026627,0.022514,0.022439,0.035388,-0.021224,0.008281,-0.000369,-0.015992,0.012876,-0.018086,-0.005188,-0.021093,0.012907,-0.008576,-0.008820,0.030578,0.014680,0.017475,0.007797,0.004474,-0.006686,0.023422,0.017913,0.009466,-0.011255,-0.006200,0.008317,-0.038521,0.017131,0.046956,0.005528,0.071628,0.044144,-0.006390,0.009272,-0.010302,-0.023798,0.013099,0.004949,0.000502,-0.025377,0.000576,0.005652,0.013762,-0.033165,0.011959,0.032019,-0.010729,0.074746,-0.045156,-0.069856,0.017151,-0.028899,-0.001317,-0.020143,-0.001444,0.077727,0.008474,0.017218,0.063803,0.022661,-0.019578,-0.089309,0.043190,0.054776,0.003839,0.005619,0.042291,-0.040703,0.034216,-0.018434,0.026249,-0.012015,0.004663,0.009540,0.028979,0.022277,0.015843,0.026390,-0.030022,-0.019719,0.008557,-0.006588,-0.012466,-0.013107,0.000680,-0.040800,0.018810,-0.018852,0.015615,-0.026299,-0.013060,-0.022985,-0.019649,0.003882,0.019573,0.020302,-0.053045,-0.013295,-0.013323,0.043432,-0.020309,-0.004050,-0.017728,-0.008395,-0.063169,-0.008017,0.060143,-0.036649,-0.009351,-0.031419,-0.019356,0.002941,0.015680,0.058794,0.034299,0.025507,0.026522,-0.024327,0.001476,-0.008036,-0.008201,0.018152,0.016011,-0.009222,0.020974,0.008694,-0.047264,0.028262,-0.002851,0.009422,-0.012002,0.004519,-0.010160,-0.031831,-0.005528,0.038708,-0.014277,0.009808,0.004059,-0.009500,0.033000,-0.038357,-0.005480,0.016188,-0.012154,-0.003113,0.007213,-0.049557,0.001337,0.025862,0.002217,0.009792,-0.002905,0.012793,-0.039633,-0.014680,0.012541,-0.026685,-0.057037,-0.038288,-0.031196,-0.025930,0.009651,0.004537,0.035687,-0.013257,0.015052,-0.006502,0.018667,-0.013956,0.023991,0.033361,-0.000124,-0.000186,0.012095,0.023317,0.014021,-0.007477,-0.006606,-0.045891,0.004310,-0.008439,0.004574,-0.039585,0.004941,0.010379,-0.002950,-0.053005,0.008541,-0.002762,0.010718,0.035433,0.017978,0.027453,-0.019744,0.008659,0.023139,-0.009485,-0.030263,0.013689,-0.022727,0.006843,2026-03-05 15:00:00

In [28]:
#tg_hourly["datetime_hour"] = tg_hourly["datetime_hour"] + pd.Timedelta(hours=1)        ТУТ ЗСУВ ТГ НА 1 ГОДИНУ

In [29]:
df_final = df_final.merge(tg_hourly, on="datetime_hour", how="left")

In [30]:
df_final.sample(20)

,datetime_hour,region_id,city_latitude,city_longitude,day_temp,day_dew,day_humidity,day_precip,day_precipprob,day_precipcover,day_snow,day_snowdepth,day_windgust,day_windspeed,day_winddir,day_pressure,day_cloudcover,day_solarradiation,day_solarenergy,day_uvindex,day_moonphase,hour_temp,hour_feelslike,hour_humidity,hour_precip,hour_precipprob,hour_snow,hour_windgust,hour_windspeed,hour_winddir,hour_pressure,hour_cloudcover,hour_solarradiation,hour_solarenergy,hour_uvindex,day_conditions_simple_Clear,day_conditions_simple_Cloudy,day_conditions_simple_Rain,day_conditions_simple_Snow,hour_conditions_simple_Clear,hour_conditions_simple_Cloudy,hour_conditions_simple_Rain,hour_conditions_simple_Snow,year,month,day_of_week,hour,city_name,city_timezone,day_datetime,day_sunrise,day_sunset,hour_datetime,region_key,alarm_active,alarm_minutes_in_hour,alarm_lag_1,alarm_lag_3,alarm_lag_6,alarm_lag_12,alarms_in_last_24h,is_weekend,is_night,total_active_alarms_lag1,neighbour_alarms,hours_since_last_alarm,isw_topic_0,isw_topic_1,isw_topic_2,isw_topic_3,isw_topic_4,isw_topic_5,isw_topic_6,isw_topic_7,isw_topic_8,isw_topic_9,isw_topic_10,isw_topic_11,isw_topic_12,isw_topic_13,isw_topic_14,isw_topic_15,isw_topic_16,isw_topic_17,isw_topic_18,isw_topic_19,isw_topic_20,isw_topic_21,isw_topic_22,isw_topic_23,isw_topic_24,isw_topic_25,isw_topic_26,isw_topic_27,isw_topic_28,isw_topic_29,isw_topic_30,isw_topic_31,isw_topic_32,isw_topic_33,isw_topic_34,isw_topic_35,isw_topic_36,isw_topic_37,isw_topic_38,isw_topic_39,isw_topic_40,isw_topic_41,isw_topic_42,isw_topic_43,isw_topic_44,isw_topic_45,isw_topic_46,isw_topic_47,isw_topic_48,isw_topic_49,isw_topic_50,isw_topic_51,isw_topic_52,isw_topic_53,isw_topic_54,isw_topic_55,isw_topic_56,isw_topic_57,isw_topic_58,isw_topic_59,isw_topic_60,isw_topic_61,isw_topic_62,isw_topic_63,isw_topic_64,isw_topic_65,isw_topic_66,isw_topic_67,isw_topic_68,isw_topic_69,isw_topic_70,isw_topic_71,isw_topic_72,isw_topic_73,isw_topic_74,isw_topic_75,isw_topic_76,isw_topic_77,isw_topic_78,isw_topic_79,isw_topic_80,isw_topic_81,isw_topic_82,isw_topic_83,isw_topic_84,isw_topic_85,isw_topic_86,isw_topic_87,isw_topic_88,isw_topic_89,isw_topic_90,isw_topic_91,isw_topic_92,isw_topic_93,isw_topic_94,isw_topic_95,isw_topic_96,isw_topic_97,isw_topic_98,isw_topic_99,isw_topic_100,isw_topic_101,isw_topic_102,isw_topic_103,isw_topic_104,isw_topic_105,isw_topic_106,isw_topic_107,isw_topic_108,isw_topic_109,isw_topic_110,isw_topic_111,isw_topic_112,isw_topic_113,isw_topic_114,isw_topic_115,isw_topic_116,isw_topic_117,isw_topic_118,isw_topic_119,isw_topic_120,isw_topic_121,isw_topic_122,isw_topic_123,isw_topic_124,isw_topic_125,isw_topic_126,isw_topic_127,isw_topic_128,isw_topic_129,isw_topic_130,isw_topic_131,isw_topic_132,isw_topic_133,isw_topic_134,isw_topic_135,isw_topic_136,isw_topic_137,isw_topic_138,isw_topic_139,isw_topic_140,isw_topic_141,isw_topic_142,isw_topic_143,isw_topic_144,isw_topic_145,isw_topic_146,isw_topic_147,isw_topic_148,isw_topic_149,isw_total_intensity,isw_topic_std,isw_topic_max,isw_topic_mean,isw_velocity_24h,isw_intensity_ema,isw_topic_entropy,tg_topic_0,tg_topic_1,tg_topic_2,tg_topic_3,tg_topic_4,tg_topic_5,tg_topic_6,tg_topic_7,tg_topic_8,tg_topic_9,tg_topic_10,tg_topic_11,tg_topic_12,tg_topic_13,tg_topic_14,tg_topic_15,tg_topic_16,tg_topic_17,tg_topic_18,tg_topic_19,tg_topic_20,tg_topic_21,tg_topic_22,tg_topic_23,tg_topic_24,tg_topic_25,tg_topic_26,tg_topic_27,tg_topic_28,tg_topic_29,tg_topic_30,tg_topic_31,tg_topic_32,tg_topic_33,tg_topic_34,tg_topic_35,tg_topic_36,tg_topic_37,tg_topic_38,tg_topic_39,tg_topic_40,tg_topic_41,tg_topic_42,tg_topic_43,tg_topic_44,tg_topic_45,tg_topic_46,tg_topic_47,tg_topic_48,tg_topic_49,tg_topic_50,tg_topic_51,tg_topic_52,tg_topic_53,tg_topic_54,tg_topic_55,tg_topic_56,tg_topic_57,tg_topic_58,tg_topic_59,tg_topic_60,tg_topic_61,tg_topic_62,tg_topic_63,tg_topic_64,tg_topic_65,tg_topic_66,tg_topic_67,tg_topic_68,tg_topic_69,tg_topic_70,tg_topic_71,tg_topic_72,tg_topic_73,tg_topic_74,tg_topic_75,tg_topic_76,tg_topic_77,tg_topic_78,tg_topic_79,tg_topic_80,tg_topic_81,tg_topic_82,tg_topic_83,tg_topic_84,tg_topic_85,tg_topic_86,tg_topic_87,tg_topic_88,tg_topic_89,tg_topic_90,tg_topic_91,tg_topic_92,tg_topic_93,tg_topic_94,tg_topic_95,tg_topic_96,tg_topic_97,tg_topic_98,tg_topic_99,tg_topic_100,tg_topic_101,tg_topic_102,tg_topic_103,tg_topic_104,tg_topic_105,tg_topic_106,tg_topic_107,tg_topic_108,tg_topic_109,tg_topic_110,tg_topic_111,tg_topic_112,tg_topic_113,tg_topic_114,tg_topic_115,tg_topic_116,tg_topic_117,tg_topic_118,tg_topic_119,tg_topic_120,tg_topic_121,tg_topic_122,tg_topic_123,tg_topic_124,tg_topic_125,tg_topic_126,tg_topic_127,tg_topic_128,tg_topic_129,tg_topic_130,tg_topic_131,tg_topic_132,tg_topic_133,tg_topic_134,tg_topic_135,tg_topic_136,tg_topic_137,tg_topic_138,tg_topic_139,tg_topic_140,tg_topic_141,tg_topic_142,tg_topic_143,tg_topic_144,tg_topic_145,tg_topic_146,tg_topic_147,tg_topic_148,tg_topic_149,tg_topic_150,tg_topic_151,tg_topic_152,tg_topic_153,tg_topic_154,tg_topic_155,tg_topic_156,tg_topic_157,tg_topic_158,tg_topic_159,tg_topic_160,tg_topic_161,tg_topic_162,tg_topic_163,tg_topic_164,tg_topic_165,tg_topic_166,tg_topic_167,tg_topic_168,tg_topic_169,tg_topic_170,tg_topic_171,tg_topic_172,tg_topic_173,tg_topic_174,tg_topic_175,tg_topic_176,tg_topic_177,tg_topic_178,tg_topic_179,tg_topic_180,tg_topic_181,tg_topic_182,tg_topic_183,tg_topic_184,tg_topic_185,tg_topic_186,tg_topic_187,tg_topic_188,tg_topic_189,tg_topic_190,tg_topic_191,tg_topic_192,tg_topic_193,tg_topic_194,tg_topic_195,tg_topic_196,tg_topic_197,tg_topic_198,tg_topic_199,tg_topic_200,tg_topic_201,tg_topic_202,tg_topic_203,tg_topic_204,tg_topic_205,tg_topic_206,tg_topic_207,tg_topic_208,tg_topic_209,tg_topic_210,tg_topic_211,tg_topic_212,tg_topic_213,tg_topic_214,tg_topic_215,tg_topic_216,tg_topic_217,tg_topic_218,tg_topic_219,tg_topic_220,tg_topic_221,tg_topic_222,tg_topic_223,tg_topic_224,tg_topic_225,tg_topic_226,tg_topic_227,tg_topic_228,tg_topic_229,tg_topic_230,tg_topic_231,tg_topic_232,tg_topic_233,tg_topic_234,tg_topic_235,tg_topic_236,tg_topic_237,tg_topic_238,tg_topic_239,tg_topic_240,tg_topic_241,tg_topic_242,tg_topic_243,tg_topic_244,tg_topic_245,tg_topic_246,tg_topic_247,tg_topic_248,tg_topic_249
356281,2023-07-15 18:00:00,16,49.5879,34.5517,20.8,14.0,68.0,0.000,0.0,0.00,0.0,0.0,44.3,19.4,313.7,1014.0,21.7,272.3,23.4,7.0,0.92,24.7,24.7,42.75,0.0,0.0,0.0,34.9,18.0,320.0,1014.3,60.0,295.0,1.1,3.0,False,True,False,False,False,True,False,False,2023,7,5,18,Poltava,Europe/Kiev,2023-07-15,04:50:47,20:44:11,18:00:00,Полтавська,0,0.000000,0.0,0.0,0.0,0.0,4.0,1,0,2.0,0.0,13,0.772062,-0.171113,-0.086071,-0.081609,-0.090354,0.113084,0.027741,0.007036,-0.087251,0.113515,-0.016905,-0.131115,-0.022200,0.040049,0.067426,-0.083153,0.048106,0.004569,0.048157,-0.008543,0.043054,0.062839,-0.087175,0.052210,0.002381,-0.057600,-0.021832,0.088585,-0.044168,-0.002061,0.050143,0.034571,0.047300,-0.045100,0.003657,0.026353,-0.023537,-0.005956,-0.095934,0.011417,0.022165,-0.020046,-0.024665,-0.017656,-0.064020,-0.055829,-0.001104,0.009210,-0.020118,-0.005540,0.022910,-0.027170,0.031586,-0.006764,-0.000391,-0.049196,0.054042,0.067994,0.026189,-0.085942,-0.035446,0.018216,0.012650,0.036379,0.063864,-0.007810,0.028079,0.093966,-0.018827,-0.024267,-0.022759,0.023421,0.005344,0.022554,-0.088248,-0.012437,0.018056,-0.028602,-0.001549,-0.044636,0.002859,-0.008299,-0.000789,0.064947,-0.001852,0.004450,0.003425,0.026832,0.060557,0.002653,0.042012,0.038401,0.053401,-0.064265,0.002147,-0.013573,0.049609,-0.054311,-0.034198,0.041607,0.006671,0.061560,-0.045889,0.023072,-0.007507,0.035312,0.044885,0.020024,0.013325,0.038506,-0.038656,0.021345,0.030518,0.027707,0.015642,0.048017,0.056943,0.004737,-0.017645,0.010022,-0.003226,-0.008331,0.004854,-0.001223,0.058001,-0.026459,-0.014170,0.013801,-0.010302,0.000520,0.003491,0.030810,0.009986,-0.012795,-0.001136,0.005230,0.001753,0.001203,-0.024435,-0.011923,-0.016141,0.013761,0.014624,0.008811,-0.027784,0.014488,0.008771,-0.007323,-0.005559,-0.011956,5.556618,0.067465,0.772062,0.037044,1.059362,5.388759,4.368265,0.014548,-0.009414,0.018044,0.003542,-0.007932,0.034494,-0.053475,0.058538,0.016514,-0.017675,-0.012828,0.011445,-0.016774,-0.119275,0.152204,-0.008616,-0.043533,-0.016766,-0.027849,0.058990,0.028667,-0.064991,0.016202,0.023051,0.021920,-0.028126,-0.001830,0.013717,-0.003090,-0.000217,0.017289,0.010371,-0.012550,0.003568,0.007395,-0.002431,-0.001127,-0.009575,0.001637,0.001140,0.003868,0.002230,0.009205,-0.000836,-0.003865,0.006886,0.013372,0.004055,0.006111,-0.016465,-0.009892,0.018418,0.011822,0.000124,-0.003378,0.005346,0.003150,0.000549,-0.013576,0.006674,0.002406,-0.003962,0.011355,-0.000042,-0.005660,-0.008786,-0.007418,-0.011940,0.004824,-0.015362,0.019044,0.033814,0.010438,0.013159,0.007602,-0.019141,0.012118,0.057632,-0.012652,0.018120,-0.005634,-0.048055,-0.051909,0.010081,0.020602,-0.038443,-0.031383,0.007443,0.006576,0.009576,-0.005425,-0.008471,0.002672,-0.009662,0.017745,-0.005569,0.002643,-0.000147,0.000376,-0.016483,-0.008590,0.015206,0.009738,0.028789,0.013154,-0.017443,0.010134,0.015381,-0.009516,0.018568,0.043846,-0.010807,-0.000366,0.017793,0.016167,-0.032913,0.003583,0.016862,-0.025498,-0.012858,0.001399,0.014154,0.029025,-0.000392,-0.032527,0.006643,0.002147,-0.013292,-0.013236,-0.006424,-0.003744,0.003184,0.019475,0.013948,-0.005241,-0.053904,0.013279,0.005700,-0.006197,0.013304,-0.004044,0.008011,0.004947,0.002495,-0.008632,0.013675,-0.029791,0.007713,-0.023502,0.005298,0.030281,-0.029166,-0.000472,0.017701,-0.006757,0.012077,0.004945,0.002918,-0.027248,-0.028879,0.006013,-0.026277,-0.018737,-0.008159,-0.028823,-0.057129,-0.004518,0.009038,0.022450,-0.013932,0.019062,-0.009330,0.035161,0.038443,-0.010440,-0.019685,0.017692,-0.002255,-0.008077,-0.045311,-0.037485,-0.002486,0.040622,0.007689,-0.039363,0.009217,-0.028112,0.009923,-0.012477,0.000087,0.015603,-0.047868,0.002423,-0.027595,0.032422,0.026275,0.058404,-0.025843,-0.056050,-0.031569,-0.034014,-0.011204,0.029330,0.019051,0.030169,0.012501,0.050557,0.044423,-0.004349,0.016067,0.007554,0.000177,-0.031880,0.012958,0.015480,-0.000128,-0.028058,0.026563,0.007038,-0.020341,-0.010584,0.003631,-0.019706,-0.003196,0.001037,-0.000205,-0.011130,0.019072,0.002374,0.018784,-0.006206,0.002331,0.021382,0.012360,0.027566,0.020679,-0.011989,-0.012158,0.003231,0.010475,0.047150,-0.003757,0.008367,0.020293,0.004452,0.011171,0.003887,-0.000363,-0.003568,0.014785
190066,2022-09-10 08:00:00,9,48.9226,24.7147,16.0,15.0,94.0,13.000,100.0,8.33,0.0,0.0,35.6,21.6,46.4,1011.8,96.8,48.9,4.3,5.0,0.46,15.6,15.6,96.22,0.0,0.0,0.0,12.6,5.8,98.9,1013.0,100.0,16.0,0.1,0.0,False,False,True,False,False,True,False,False,2022,9,5,8,Ivano-Frankivsk,Europe/Kiev,2022-09-10,06:50:13,19:45:15,08:00:00,Івано-Франківська,0,0.000000,0.0,0.0,0.0,0.0,0.0,1,0,0.0,0.0,60,0.848105,-0.203281,0.140751,-0.107369,0.000305,0.013276,-0.019987,0.015294,0.028938,-0.058313,0.012588,0.018698,0.120572,0.098347,-0.001625,0.046188,-0.064197,0.037110,-0.006112,0.047606,-0.015361,0.009873,-0.035831,0.047712,0.035354,0.068469,-0.049215,-0.043180,-0.026202,0.017068,-0.013658,-0.032052,0.090385,-0.008462,0.002296,0.028542,0.009834,-0.000615,-0.039425,0.015850,-0.053190,0.039373,-0.012168,-0.009795,0.029806,0.028371,0.039662,-0.054295,0.002726,0.027018,0.017565,0.001890,-0.016200,-0.017451,-0.031207,0.010226,0.002938,0.012015,0.013288,0.020361,-0.006810,-0.001893,0.045014,-0.001605,-0.006223,0.024518,-0.024280,0.020642,0.017807,0.044647,-0.000593,0.000918,-0.019982,0.021531,0.054886,-0.016044,0.013799,0.007378,-0.005204,-0.011069,-0.029254,-0.019068,-0.014176,0.026679,-0.015046,0.012546,0.006075,-0.025351,-0.010083,0.001129,0.025638,0.000445,-0.003061,0.009255,0.006441,-0.041605,-0.027029,-0.030123,0.007965,-0.021533,0.007656,0.008931,-0.024572,-0.028503,-0.009345,-0.016286,-0.025037,0.017321,-0.000200,0.008034,-0.002439,-0.001343,-0.013041,-0.008301,0.008877,-0.029788,-0.025464,0.007896,0.000029,-0.000041,0.016376,-0.005619,0.016254,-0.006039,0.009580,0.000778,-0.024145,0.026214,0.021817,-0.024971,-0.004542,-0.003722,-0.001042,-0.006388,0.026116,0.007050,-0.011355,-0.009438,0.003216,-0.011172,0.009688,-0.006755,0.009148,0.006843,0.007792,0.001370,-0.001047,-0.017456,0.007302,-0.015346,4.156617,0.072656,0.848105,0.027711,-0.810698,4.559047,4.087115,0.034233,-0.010113,0.063672,0.011240,-0.019250,0.070495,-0.077750,0.087235,0.013630,-0.019478,0.029663,-0.041511,0.017750,-0.053227,-0.046159,0.063646,-0.028595,0.040654,0.057768,-0.111647,-0.019813,0.038907,0.037303,0.029485,0.034375,-0.020782,0.061475,0.014287,0.062160,0.047870,0.062019,-0.005930,0.032964,0.006074,0.001992,0.015182,0.033282,-0.047372,-0.033199,0.023157,-0.003690,0.009308,0.055596,-0.024352,-0.010900,-0.013371,-0.038735,0.052212,-0.010367,0.038564,-0.017296,-0.008444,-0.033747,-0.004262,-0.072868,-0.020202,-0.013649,-0.043782,0.038604,0.025707,0.014671,0.049482,0.023395,-0.014198,0.008280,-0.039781,-0.006592,0.011771,0.013918,-0.024780,0.031686,0.029727,0.016871,0.012414,0.021722,-0.037248,-0.035225,0.017537,-0.012560,0.022733,0.015304,0.007675,-0.016855,0.015132,-0.022545,0.038775,0.019811,-0.001649,0.016832,-0.015792,0.008095,0.001177,-0.061302,-0.003666,0.006337,0.009145,0.001566,0.015044,0.005311,0.006787,0.006554,-0.037578,-0.014140,-0.009905,-0.008137,0.024803,-0.030029,-0.014171,0.019105,0.015223,-0.023630,-0.021659,0.017626,-0.021031,0.002304,0.001868,-0.006852,-0.005048,0.006476,-0.010762,-0.017890,-0.037729,0.006205,-0.004336,0.009709,-0.005158,0.019599,-0.007289,-0.004817,0.015444,0.009037,0.010689,0.002163,0.016805,-0.009650,-0.014603,0.006030,-0.019610,-0.001767,-0.007817,0.001412,-0.003134,0.024239,0.006245,0.012420,-0.041587,-0.042341,0.002848,-0.024176,0.002081,0.054786,-0.008360,0.041993,-0.024147,-0.010653,0.014419,-0.043227,0.037861,-0.000088,0.001600,0.011002,-0.020424,0.025832,0.045736,-0.014235,0.042463,0.017767,-0.008327,0.002197,0.016605,-0.035070,-0.011343,-0.060903,-0.032463,-0.044469,0.001898,0.025319,0.030124,-0.001694,-0.017137,-0.015881,-0.036127,0.004369,0.010372,0.002392,-0.020536,0.039754,-0.000159,0.003735,-0.019176,-0.007295,0.011673,-0.005915,0.026239,-0.026881,-0.027090,0.014159,-0.008466,-0.029545,-0.002645,0.001733,0.052370,-0.023050,0.046046,-0.021715,-0.014462,0.009411,0.020062,0.019183,-0.014730,0.025817,0.033952,-0.030393,0.009630,0.009301,0.052022,-0.031769,-0.025659,-0.030811,0.031508,0.011089,0.010489,-0.009581,-0.012324,-0.000042,0.009093,0.010243,-0.000061,0.011513,-0.015306,-0.005779,0.056211,0.030829,-0.011266,-0.041362,0.004950,0.017219,0.012868,-0.009186,0.008689,0.018846,0.007328,0.002800,-0.008214,0.020329,-0.028687,0.004968,-0.017303,-0.021553,-0.009110
610785,2022-05-17 07:00:00,26,50.4506,30.5243,13.4,-1.9,36.7,0.000,0.0,0.00,0.0,0.0,51.5,20.9,296.6,1014.2,45.1,305.3,26.3,8.0,0.54,9.7,8.5,47.95,0.0,0.0,0.0,20.9,8.6,264.1,1016.0,62.4,116.0,0.4,1.0,False,True,False,False,False,True,False,False,2022,5,1,7,Kyiv,Europe/Kiev,2022-05-17,05:07:50,20:41:44,07:00:00,Київ,0,0.000000,0.0,1.0,1.0,0.0,8.0,0,0,2.0,0.0,1,0.686528,-0.204537,0.333230,0.077116,0.040664,-0.010572,0.027843,-0.089657,0.003849,-0.068606,-0.016511,0.033790,0.039064,-0.036332,0.023038,0.033892,0.180523,0.058308,-0.010414,-0.070249,0.055417,0.018707,0.068560,0.120998,-0.020966,0.029754,-0.079746,-0.036983,-0.092658,-0.011888,0.027027,-0.053855,0.065140,-0.017869,-0.043115,0.016159,0.078399,0.014620,0.000002,0.025831,-0.038487,-0.042272,0.028309,-0.063375,0.003588,0.010228,-0.059072,-0.031634,0.001968,-0.047464,0.037046,0.050874,0.042492,0.011923,0.091619,0.058923,0.021066,-0.002824,0.021600,-0.004523,-0.004682,-0.020667,0.013695,-0.028758,0.013059,-0.033600,0.050054,0.045142,-0.003205,-0.053538,0.012892,-0.019117,0.057787,-0.021559,-0.014213,0.007740,0.027810,0.045471,-0.011804,0.019304,0.042716,0.042913,0.025348,-0.041033,-0.008871,-0.011613,0.043137,0.028030,0.022704,0.000221,-0.054955,-0.049885,0.006413,-0.028338,0.034324,-0.009980,-0.024101,0.035176,-0.006241,-0.003257,-0.013348,0.005488,-0.007699,-0.004118,-0.034447,0.020888,0.032361,0.019125,0.013826,-0.004886,0.010862,0.050242,-0.008520,0.049452,0.026927,0.013022,0.007522,-0.033008,-0.026845,0.003875,0.016634,-0.012632,0.015491,-0.031557,-0.013536,-0.001709,-0.019249,0.036374,0.014077,0.002840,0.010815,-0.031959,-0.029561,-0.006445,-0.008666,0.032896,0.044913,0.023691,-0.014371,0.014022,0.000457,0.010644,-0.028188,0.020445,0.000297,0.031009,0.012033,0.015465,0.011992,-0.013441,5.526934,0.065627,0.686528,0.036846,1.057674,4.979440,4.377713,0.052637,-0.021655,0.068175,-0.000564,-0.015441,0.086018,-0.092998,0.119968,0.024363,-0.037418,0.089506,0.029170,-0.001920,-0.140913,-0.025070,0.013320,0.047807,0.014081,0.001382,-0.038782,-0.015561,0.091271,-0.041435,-0.067882,-0.026078,0.075304,-0.018371,-0.014301,-0.020731,-0.036069,-0.069113,-0.000797,0.005313,-0.029590,0.033116,-0.016199,-0.009355,-0.044951,-0.006963,-0.009510,0.012406,0.004806,0.056913,-0.020373,-0.006804,-0.001606,0.003765,0.010239,-0.013429,0.014697,-0.005669,-0.018014,-0.006532,0.001099,0.001262,0.011365,0.008269,0.016561,0.003414,-0.003508,-0.010827,0.003062,-0.004744,-0.009375,0.008012,0.004935,0.013300,0.006742,-0.000851,0.000554,-0.016202,-0.000024,-0.024535,-0.013347,0.003925,-0.013959,-0.003182,0.009710,-0.017573,-0.007081,0.000440,-0.010290,-0.002792,0.026899,-0.006944,-0.023104,0.027349,-0.004724,0.006492,0.024234,0.015364,-0.060210,0.008327,0.032422,0.024367,0.017633,-0.023366,-0.044299,0.008172,-0.010767,0.007518,-0.009110,0.022232,0.013745,-0.002826,-0.000979,0.003328,-0.004500,0.035452,-0.026487,-0.002386,0.012262,0.013058,0.017752,-0.035690,0.032675,-0.054425,-0.010366,0.014742,0.001774,0.006029,0.001818,-0.016516,-0.003269,0.001373,-0.006271,0.017743,0.004445,0.007609,0.024159,0.004693,0.002351,0.006881,0.010040,-0.005014,-0.003918,-0.040883,-0.025278,0.027180,0.006176,0.017081,-0.008878,-0.024865,-0.031443,0.037622,0.005741,0.015344,-0.004255,0.004448,-0.006248,0.012535,0.018437,-0.017084,0.014964,-0.014858,-0.002897,0.004856,-0.007614,0.005844,-0.013511,0.000797,0.022341,-0.021474,-0.025820,-0.028847,0.002291,-0.009697,0.022021,-0.009238,0.017149,0.008368,-0.003915,0.006382,-0.029866,-0.037623,-0.010210,-0.001620,0.017319,0.007159,0.000514,0.006220,0.022033,0.002527,0.014212,0.004510,0.007124,0.016198,-0.008521,-0.008073,-0.001556,-0.017881,0.058764,0.016803,-0.013011,0.029959,-0.012573,-0.009732,0.016993,-0.014512,-0.005997,0.027032,0.012893,-0.019855,-0.013726,0.036169,-0.024619,-0.030404,0.001475,0.013039,0.010861,0.011276,-0.022573,-0.000367,-0.016340,0.008050,0.003031,-0.025158,-0.004020,0.031898,-0.023810,-0.003476,-0.014148,-0.017465,0.003325,0.017376,0.017193,-0.018149,-0.007750,-0.022701,-0.024306,0.000428,0.012887,-0.029150,0.017002,0.041523,0.000995,-0.018273,-0.018686,-0.001765,0.013018,-0.004379,0.043786,0.008781,-0.004445,-0.001925,0.001700,0.006334,0.015206,-0.008685,0.006953

In [31]:
df_final.shape

(635256, 473)

In [32]:
df_final = df_final.sort_values(["datetime_hour"])

In [33]:
with pd.option_context('display.max_rows', None):
    print(df_final.isnull().sum())

datetime_hour                         0
region_id                             0
city_latitude                         0
city_longitude                        0
day_temp                              0
day_dew                               0
day_humidity                          0
day_precip                            0
day_precipprob                        0
day_precipcover                       0
day_snow                              0
day_snowdepth                         0
day_windgust                          0
day_windspeed                         0
day_winddir                           0
day_pressure                          0
day_cloudcover                        0
day_solarradiation                    0
day_solarenergy                       0
day_uvindex                           0
day_moonphase                         0
hour_temp                             0
hour_feelslike                        0
hour_humidity                         0
hour_precip                           0
hour_precipprob                       0
hour_snow                             0
hour_windgust                         0
hour_windspeed                        0
hour_winddir                          0
hour_pressure                         0
hour_cloudcover                       0
hour_solarradiation                   0
hour_solarenergy                      0
hour_uvindex                          0
day_conditions_simple_Clear           0
day_conditions_simple_Cloudy          0
day_conditions_simple_Rain            0
day_conditions_simple_Snow            0
hour_conditions_simple_Clear          0
hour_conditions_simple_Cloudy         0
hour_conditions_simple_Rain           0
hour_conditions_simple_Snow           0
year                                  0
month                                 0
day_of_week                           0
hour                                  0
city_name                             0
city_timezone                         0
day_datetime                          0
day_sunrise                           0
day_sunset                            0
hour_datetime                         0
region_key                            0
alarm_active                          0
alarm_minutes_in_hour                 0
alarm_lag_1                           0
alarm_lag_3                           0
alarm_lag_6                           0
alarm_lag_12                          0
alarms_in_last_24h                    0
is_weekend                            0
is_night                              0
total_active_alarms_lag1              0
neighbour_alarms                      0
hours_since_last_alarm                0
isw_topic_0                           0
isw_topic_1                           0
isw_topic_2                           0
isw_topic_3                           0
isw_topic_4                           0
isw_topic_5                           0
isw_topic_6                           0
isw_topic_7                           0
isw_topic_8                           0
isw_topic_9                           0
isw_topic_10                          0
isw_topic_11                          0
isw_topic_12                          0
isw_topic_13                          0
isw_topic_14                          0
isw_topic_15                          0
isw_topic_16                          0
isw_topic_17                          0
isw_topic_18                          0
isw_topic_19                          0
isw_topic_20                          0
isw_topic_21                          0
isw_topic_22                          0
isw_topic_23                          0
isw_topic_24                          0
isw_topic_25                          0
isw_topic_26                          0
isw_topic_27                          0
isw_topic_28                          0
isw_topic_29                          0
isw_topic_30                          0
isw_topic_31                          0
isw_topic_32                          0
isw_topic_33                          0
isw_topic_34                          0
isw_topic_35                          0
isw_topic_36                          0
isw_topic_37                          0
isw_topic_38                          0
isw_topic_39                          0
isw_topic_40                          0
isw_topic_41                          0
isw_topic_42                          0
isw_topic_43                          0
isw_topic_44                          0
isw_topic_45                          0
isw_topic_46                          0
isw_topic_47                          0
isw_topic_48                          0
isw_topic_49                          0
isw_topic_50                          0
isw_topic_51                          0
isw_topic_52                          0
isw_topic_53                          0
isw_topic_54                          0
isw_topic_55                          0
isw_topic_56                          0
isw_topic_57                          0
isw_topic_58                          0
isw_topic_59                          0
isw_topic_60                          0
isw_topic_61                          0
isw_topic_62                          0
isw_topic_63                          0
isw_topic_64                          0
isw_topic_65                          0
isw_topic_66                          0
isw_topic_67                          0
isw_topic_68                          0
isw_topic_69                          0
isw_topic_70                          0
isw_topic_71                          0
isw_topic_72                          0
isw_topic_73                          0
isw_topic_74                          0
isw_topic_75                          0
isw_topic_76                          0
isw_topic_77                          0
isw_topic_78                          0
isw_topic_79                          0
isw_topic_80                          0
isw_topic_81                          0
isw_topic_82                          0
isw_topic_83                          0
isw_topic_84                          0
isw_topic_85                          0
isw_topic_86                          0
isw_topic_87                          0
isw_topic_88                          0
isw_topic_89                          0
isw_topic_90                          0
isw_topic_91                          0
isw_topic_92                          0
isw_topic_93                          0
isw_topic_94                          0
isw_topic_95                          0
isw_topic_96                          0
isw_topic_97                          0
isw_topic_98                          0
isw_topic_99                          0
isw_topic_100                         0
isw_topic_101                         0
isw_topic_102                         0
isw_topic_103                         0
isw_topic_104                         0
isw_topic_105                         0
isw_topic_106                         0
isw_topic_107                         0
isw_topic_108                         0
isw_topic_109                         0
isw_topic_110                         0
isw_topic_111                         0
isw_topic_112                         0
isw_topic_113                         0
isw_topic_114                         0
isw_topic_115                         0
isw_topic_116                         0
isw_topic_117                         0
isw_topic_118                         0
isw_topic_119                         0
isw_topic_120                         0
isw_topic_121                         0
isw_topic_122                         0
isw_topic_123                         0
isw_topic_124                         0
isw_topic_125                         0
isw_topic_126                         0
isw_topic_127                         0
isw_topic_128                         0
isw_topic_129                         0
isw_topic_130                         0
isw_topic_131                         0
isw_topic_132                         0
isw_topic_133                         0
isw_topic_134                         0
isw_topic_135                         0
isw_topic_136                         0
isw_topic_137                         0
isw_topic_138                         0
isw_topic_139                         0
isw_topic_140                         0
isw_topic_141                         0
isw_topic_142                         0
isw_topic_143                         0
isw_topic_144                         0
isw_topic_145                         0
isw_topic_146                         0
isw_topic_147                         0
isw_topic_148                         0
isw_topic_149                         0
isw_total_intensity                   0
isw_topic_std                         0
isw_topic_max                         0
isw_topic_mean                        0
isw_velocity_24h                      0
isw_intensity_ema                     0
isw_topic_entropy                     0
tg_topic_0                       121728
tg_topic_1                       121728
tg_topic_2                       121728
tg_topic_3                       121728
tg_topic_4                       121728
tg_topic_5                       121728
tg_topic_6                       121728
tg_topic_7                       121728
tg_topic_8                       121728
tg_topic_9                       121728
tg_topic_10                      121728
tg_topic_11                      121728
tg_topic_12                      121728
tg_topic_13                      121728
tg_topic_14                      121728
tg_topic_15                      121728
tg_topic_16                      121728
tg_topic_17                      121728
tg_topic_18                      121728
tg_topic_19                      121728
tg_topic_20                      121728
tg_topic_21                      121728
tg_topic_22                      121728
tg_topic_23                      121728
tg_topic_24                      121728
tg_topic_25                      121728
tg_topic_26                      121728
tg_topic_27                      121728
tg_topic_28                      121728
tg_topic_29                      121728
tg_topic_30                      121728
tg_topic_31                      121728
tg_topic_32                      121728
tg_topic_33                      121728
tg_topic_34                      121728
tg_topic_35                      121728
tg_topic_36                      121728
tg_topic_37                      121728
tg_topic_38                      121728
tg_topic_39                      121728
tg_topic_40                      121728
tg_topic_41                      121728
tg_topic_42                      121728
tg_topic_43                      121728
tg_topic_44                      121728
tg_topic_45                      121728
tg_topic_46                      121728
tg_topic_47                      121728
tg_topic_48                      121728
tg_topic_49                      121728
tg_topic_50                      121728
tg_topic_51                      121728
tg_topic_52                      121728
tg_topic_53                      121728
tg_topic_54                      121728
tg_topic_55                      121728
tg_topic_56                      121728
tg_topic_57                      121728
tg_topic_58                      121728
tg_topic_59                      121728
tg_topic_60                      121728
tg_topic_61                      121728
tg_topic_62                      121728
tg_topic_63                      121728
tg_topic_64                      121728
tg_topic_65                      121728
tg_topic_66                      121728
tg_topic_67                      121728
tg_topic_68                      121728
tg_topic_69                      121728
tg_topic_70                      121728
tg_topic_71                      121728
tg_topic_72                      121728
tg_topic_73                      121728
tg_topic_74                      121728
tg_topic_75                      121728
tg_topic_76                      121728
tg_topic_77                      121728
tg_topic_78                      121728
tg_topic_79                      121728
tg_topic_80                      121728
tg_topic_81                      121728
tg_topic_82                      121728
tg_topic_83                      121728
tg_topic_84                      121728
tg_topic_85                      121728
tg_topic_86                      121728
tg_topic_87                      121728
tg_topic_88                      121728
tg_topic_89                      121728
tg_topic_90                      121728
tg_topic_91                      121728
tg_topic_92                      121728
tg_topic_93                      121728
tg_topic_94                      121728
tg_topic_95                      121728
tg_topic_96                      121728
tg_topic_97                      121728
tg_topic_98                      121728
tg_topic_99                      121728
tg_topic_100                     121728
tg_topic_101                     121728
tg_topic_102                     121728
tg_topic_103                     121728
tg_topic_104                     121728
tg_topic_105                     121728
tg_topic_106                     121728
tg_topic_107                     121728
tg_topic_108                     121728
tg_topic_109                     121728
tg_topic_110                     121728
tg_topic_111                     121728
tg_topic_112                     121728
tg_topic_113                     121728
tg_topic_114                     121728
tg_topic_115                     121728
tg_topic_116                     121728
tg_topic_117                     121728
tg_topic_118                     121728
tg_topic_119                     121728
tg_topic_120                     121728
tg_topic_121                     121728
tg_topic_122                     121728
tg_topic_123                     121728
tg_topic_124                     121728
tg_topic_125                     121728
tg_topic_126                     121728
tg_topic_127                     121728
tg_topic_128                     121728
tg_topic_129                     121728
tg_topic_130                     121728
tg_topic_131                     121728
tg_topic_132                     121728
tg_topic_133                     121728
tg_topic_134                     121728
tg_topic_135                     121728
tg_topic_136                     121728
tg_topic_137                     121728
tg_topic_138                     121728
tg_topic_139                     121728
tg_topic_140                     121728
tg_topic_141                     121728
tg_topic_142                     121728
tg_topic_143                     121728
tg_topic_144                     121728
tg_topic_145                     121728
tg_topic_146                     121728
tg_topic_147                     121728
tg_topic_148                     121728
tg_topic_149                     121728
tg_topic_150                     121728
tg_topic_151                     121728
tg_topic_152                     121728
tg_topic_153                     121728
tg_topic_154                     121728
tg_topic_155                     121728
tg_topic_156                     121728
tg_topic_157                     121728
tg_topic_158                     121728
tg_topic_159                     121728
tg_topic_160                     121728
tg_topic_161                     121728
tg_topic_162                     121728
tg_topic_163                     121728
tg_topic_164                     121728
tg_topic_165                     121728
tg_topic_166                     121728
tg_topic_167                     121728
tg_topic_168                     121728
tg_topic_169                     121728
tg_topic_170                     121728
tg_topic_171                     121728
tg_topic_172                     121728
tg_topic_173                     121728
tg_topic_174                     121728
tg_topic_175                     121728
tg_topic_176                     121728
tg_topic_177                     121728
tg_topic_178                     121728
tg_topic_179                     121728
tg_topic_180                     121728
tg_topic_181                     121728
tg_topic_182                     121728
tg_topic_183                     121728
tg_topic_184                     121728
tg_topic_185                     121728
tg_topic_186                     121728
tg_topic_187                     121728
tg_topic_188                     121728
tg_topic_189                     121728
tg_topic_190                     121728
tg_topic_191                     121728
tg_topic_192                     121728
tg_topic_193                     121728
tg_topic_194                     121728
tg_topic_195                     121728
tg_topic_196                     121728
tg_topic_197                     121728
tg_topic_198                     121728
tg_topic_199                     121728
tg_topic_200                     121728
tg_topic_201                     121728
tg_topic_202                     121728
tg_topic_203                     121728
tg_topic_204                     121728
tg_topic_205                     121728
tg_topic_206                     121728
tg_topic_207                     121728
tg_topic_208                     121728
tg_topic_209                     121728
tg_topic_210                     121728
tg_topic_211                     121728
tg_topic_212                     121728
tg_topic_213                     121728
tg_topic_214                     121728
tg_topic_215                     121728
tg_topic_216                     121728
tg_topic_217                     121728
tg_topic_218                     121728
tg_topic_219                     121728
tg_topic_220                     121728
tg_topic_221                     121728
tg_topic_222                     121728
tg_topic_223                     121728
tg_topic_224                     121728
tg_topic_225                     121728
tg_topic_226                     121728
tg_topic_227                     121728
tg_topic_228                     121728
tg_topic_229                     121728
tg_topic_230                     121728
tg_topic_231                     121728
tg_topic_232                     121728
tg_topic_233                     121728
tg_topic_234                     121728
tg_topic_235                     121728
tg_topic_236                     121728
tg_topic_237                     121728
tg_topic_238                     121728
tg_topic_239                     121728
tg_topic_240                     121728
tg_topic_241                     121728
tg_topic_242                     121728
tg_topic_243                     121728
tg_topic_244                     121728
tg_topic_245                     121728
tg_topic_246                     121728
tg_topic_247                     121728
tg_topic_248                     121728
tg_topic_249                     121728
dtype: int64

In [34]:
df_final = df_final.fillna(0)

In [35]:
tg_cols = [c for c in df_final.columns if 'tg_topic_' in c]
df_tg_abs = df_final[tg_cols].abs()

df_final['tg_total_intensity'] = df_tg_abs.sum(axis=1)
df_final['tg_topic_std'] = df_tg_abs.std(axis=1)
df_final['tg_topic_max'] = df_tg_abs.max(axis=1)
df_final['tg_topic_entropy'] = -(df_tg_abs.div(df_tg_abs.sum(axis=1), axis=0) * np.log(df_tg_abs.div(df_tg_abs.sum(axis=1), axis=0) + 1e-9)).sum(axis=1)

C:\Users\Uw11\AppData\Local\Temp\ipykernel_9376\409095542.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_final['tg_total_intensity'] = df_tg_abs.sum(axis=1)
C:\Users\Uw11\AppData\Local\Temp\ipykernel_9376\409095542.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_final['tg_topic_std'] = df_tg_abs.std(axis=1)
C:\Users\Uw11\AppData\Local\Temp\ipykernel_9376\409095542.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_final['tg_topic_max'] = df_tg_abs.max(axis=1)
C:\Users\Uw11\AppData\Local\Temp\ipykernel_9376\409095542.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_final['tg_topic_entropy'] = -(df_tg_abs.div(df_tg_abs.sum(axis=1), axis=0) * np.log(df_tg_abs.div(df_tg_abs.sum(axis=1), axis=0) + 1e-9)).sum(axis=1)

In [36]:
df_final.head(20)

,datetime_hour,region_id,city_latitude,city_longitude,day_temp,day_dew,day_humidity,day_precip,day_precipprob,day_precipcover,day_snow,day_snowdepth,day_windgust,day_windspeed,day_winddir,day_pressure,day_cloudcover,day_solarradiation,day_solarenergy,day_uvindex,day_moonphase,hour_temp,hour_feelslike,hour_humidity,hour_precip,hour_precipprob,hour_snow,hour_windgust,hour_windspeed,hour_winddir,hour_pressure,hour_cloudcover,hour_solarradiation,hour_solarenergy,hour_uvindex,day_conditions_simple_Clear,day_conditions_simple_Cloudy,day_conditions_simple_Rain,day_conditions_simple_Snow,hour_conditions_simple_Clear,hour_conditions_simple_Cloudy,hour_conditions_simple_Rain,hour_conditions_simple_Snow,year,month,day_of_week,hour,city_name,city_timezone,day_datetime,day_sunrise,day_sunset,hour_datetime,region_key,alarm_active,alarm_minutes_in_hour,alarm_lag_1,alarm_lag_3,alarm_lag_6,alarm_lag_12,alarms_in_last_24h,is_weekend,is_night,total_active_alarms_lag1,neighbour_alarms,hours_since_last_alarm,isw_topic_0,isw_topic_1,isw_topic_2,isw_topic_3,isw_topic_4,isw_topic_5,isw_topic_6,isw_topic_7,isw_topic_8,isw_topic_9,isw_topic_10,isw_topic_11,isw_topic_12,isw_topic_13,isw_topic_14,isw_topic_15,isw_topic_16,isw_topic_17,isw_topic_18,isw_topic_19,isw_topic_20,isw_topic_21,isw_topic_22,isw_topic_23,isw_topic_24,isw_topic_25,isw_topic_26,isw_topic_27,isw_topic_28,isw_topic_29,isw_topic_30,isw_topic_31,isw_topic_32,isw_topic_33,isw_topic_34,isw_topic_35,isw_topic_36,isw_topic_37,isw_topic_38,isw_topic_39,isw_topic_40,isw_topic_41,isw_topic_42,isw_topic_43,isw_topic_44,isw_topic_45,isw_topic_46,isw_topic_47,isw_topic_48,isw_topic_49,isw_topic_50,isw_topic_51,isw_topic_52,isw_topic_53,isw_topic_54,isw_topic_55,isw_topic_56,isw_topic_57,isw_topic_58,isw_topic_59,isw_topic_60,isw_topic_61,isw_topic_62,isw_topic_63,isw_topic_64,isw_topic_65,isw_topic_66,isw_topic_67,isw_topic_68,isw_topic_69,isw_topic_70,isw_topic_71,isw_topic_72,isw_topic_73,isw_topic_74,isw_topic_75,isw_topic_76,isw_topic_77,isw_topic_78,isw_topic_79,isw_topic_80,isw_topic_81,isw_topic_82,isw_topic_83,isw_topic_84,isw_topic_85,isw_topic_86,isw_topic_87,isw_topic_88,isw_topic_89,isw_topic_90,isw_topic_91,isw_topic_92,isw_topic_93,isw_topic_94,isw_topic_95,isw_topic_96,isw_topic_97,isw_topic_98,isw_topic_99,isw_topic_100,isw_topic_101,isw_topic_102,isw_topic_103,isw_topic_104,isw_topic_105,isw_topic_106,isw_topic_107,isw_topic_108,isw_topic_109,isw_topic_110,isw_topic_111,isw_topic_112,isw_topic_113,isw_topic_114,isw_topic_115,isw_topic_116,isw_topic_117,isw_topic_118,isw_topic_119,isw_topic_120,isw_topic_121,isw_topic_122,isw_topic_123,isw_topic_124,isw_topic_125,isw_topic_126,isw_topic_127,isw_topic_128,isw_topic_129,isw_topic_130,isw_topic_131,isw_topic_132,isw_topic_133,isw_topic_134,isw_topic_135,isw_topic_136,isw_topic_137,isw_topic_138,isw_topic_139,isw_topic_140,isw_topic_141,isw_topic_142,isw_topic_143,isw_topic_144,isw_topic_145,isw_topic_146,isw_topic_147,isw_topic_148,isw_topic_149,isw_total_intensity,isw_topic_std,isw_topic_max,isw_topic_mean,isw_velocity_24h,isw_intensity_ema,isw_topic_entropy,tg_topic_0,tg_topic_1,tg_topic_2,tg_topic_3,tg_topic_4,tg_topic_5,tg_topic_6,tg_topic_7,tg_topic_8,tg_topic_9,tg_topic_10,tg_topic_11,tg_topic_12,tg_topic_13,tg_topic_14,tg_topic_15,tg_topic_16,tg_topic_17,tg_topic_18,tg_topic_19,tg_topic_20,tg_topic_21,tg_topic_22,tg_topic_23,tg_topic_24,tg_topic_25,tg_topic_26,tg_topic_27,tg_topic_28,tg_topic_29,tg_topic_30,tg_topic_31,tg_topic_32,tg_topic_33,tg_topic_34,tg_topic_35,tg_topic_36,tg_topic_37,tg_topic_38,tg_topic_39,tg_topic_40,tg_topic_41,tg_topic_42,tg_topic_43,tg_topic_44,tg_topic_45,tg_topic_46,tg_topic_47,tg_topic_48,tg_topic_49,tg_topic_50,tg_topic_51,tg_topic_52,tg_topic_53,tg_topic_54,tg_topic_55,tg_topic_56,tg_topic_57,tg_topic_58,tg_topic_59,tg_topic_60,tg_topic_61,tg_topic_62,tg_topic_63,tg_topic_64,tg_topic_65,tg_topic_66,tg_topic_67,tg_topic_68,tg_topic_69,tg_topic_70,tg_topic_71,tg_topic_72,tg_topic_73,tg_topic_74,tg_topic_75,tg_topic_76,tg_topic_77,tg_topic_78,tg_topic_79,tg_topic_80,tg_topic_81,tg_topic_82,tg_topic_83,tg_topic_84,tg_topic_85,tg_topic_86,tg_topic_87,tg_topic_88,tg_topic_89,tg_topic_90,tg_topic_91,tg_topic_92,tg_topic_93,tg_topic_94,tg_topic_95,tg_topic_96,tg_topic_97,tg_topic_98,tg_topic_99,tg_topic_100,tg_topic_101,tg_topic_102,tg_topic_103,tg_topic_104,tg_topic_105,tg_topic_106,tg_topic_107,tg_topic_108,tg_topic_109,tg_topic_110,tg_topic_111,tg_topic_112,tg_topic_113,tg_topic_114,tg_topic_115,tg_topic_116,tg_topic_117,tg_topic_118,tg_topic_119,tg_topic_120,tg_topic_121,tg_topic_122,tg_topic_123,tg_topic_124,tg_topic_125,tg_topic_126,tg_topic_127,tg_topic_128,tg_topic_129,tg_topic_130,tg_topic_131,tg_topic_132,tg_topic_133,tg_topic_134,tg_topic_135,tg_topic_136,tg_topic_137,tg_topic_138,tg_topic_139,tg_topic_140,tg_topic_141,tg_topic_142,tg_topic_143,tg_topic_144,tg_topic_145,tg_topic_146,tg_topic_147,tg_topic_148,tg_topic_149,tg_topic_150,tg_topic_151,tg_topic_152,tg_topic_153,tg_topic_154,tg_topic_155,tg_topic_156,tg_topic_157,tg_topic_158,tg_topic_159,tg_topic_160,tg_topic_161,tg_topic_162,tg_topic_163,tg_topic_164,tg_topic_165,tg_topic_166,tg_topic_167,tg_topic_168,tg_topic_169,tg_topic_170,tg_topic_171,tg_topic_172,tg_topic_173,tg_topic_174,tg_topic_175,tg_topic_176,tg_topic_177,tg_topic_178,tg_topic_179,tg_topic_180,tg_topic_181,tg_topic_182,tg_topic_183,tg_topic_184,tg_topic_185,tg_topic_186,tg_topic_187,tg_topic_188,tg_topic_189,tg_topic_190,tg_topic_191,tg_topic_192,tg_topic_193,tg_topic_194,tg_topic_195,tg_topic_196,tg_topic_197,tg_topic_198,tg_topic_199,tg_topic_200,tg_topic_201,tg_topic_202,tg_topic_203,tg_topic_204,tg_topic_205,tg_topic_206,tg_topic_207,tg_topic_208,tg_topic_209,tg_topic_210,tg_topic_211,tg_topic_212,tg_topic_213,tg_topic_214,tg_topic_215,tg_topic_216,tg_topic_217,tg_topic_218,tg_topic_219,tg_topic_220,tg_topic_221,tg_topic_222,tg_topic_223,tg_topic_224,tg_topic_225,tg_topic_226,tg_topic_227,tg_topic_228,tg_topic_229,tg_topic_230,tg_topic_231,tg_topic_232,tg_topic_233,tg_topic_234,tg_topic_235,tg_topic_236,tg_topic_237,tg_topic_238,tg_topic_239,tg_topic_240,tg_topic_241,tg_topic_242,tg_topic_243,tg_topic_244,tg_topic_245,tg_topic_246,tg_topic_247,tg_topic_248,tg_topic_249,tg_total_intensity,tg_topic_std,tg_topic_max,tg_topic_entropy
0,2022-02-24,2,49.23360,28.44860,2.8,-0.3,80.5,0.300,100.0,4.17,0.0,0.0,27.7,10.8,312.0,1023.4,82.5,60.4,5.4,3.0,0.77,2.1,-0.5,91.76,0.0,0.0,0.0,16.6,8.6,279.6,1021.0,91.1,0.0,0.1,0.0,False,False,False,True,False,True,False,False,2022,2,3,0,Vinnytsia,Europe/Kiev,2022-02-24,06:58:49,17:40:52,00:00:00,Вінницька,0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0.0,0.0,1,0.648336,-0.079572,0.178041,0.061854,0.073453,-0.055809,-0.011311,0.047310,0.008354,0.006474,-0.047099,0.020496,0.050190,-0.038573,0.057228,-0.072471,0.045393,-0.116783,0.168249,0.167355,-0.025072,-0.073858,-0.097024,-0.146191,0.027983,0.082989,0.014423,0.058370,-0.033928,0.046265,0.006901,-0.049498,0.126117,-0.089039,-0.006767,-0.031686,-0.010346,0.025637,0.061278,0.162580,-0.028081,0.161291,-0.018217,-0.002657,0.038485,-0.000530,0.044413,0.107176,-0.050721,0.064279,-0.066677,0.016742,-0.050257,0.072549,-0.035201,-0.027279,0.017115,0.043631,0.024660,-0.025841,0.031320,-0.076959,-0.072986,-0.040465,0.003958,-0.022475,0.033208,-0.028056,-0.005499,-0.055998,-0.021882,-0.070462,0.018237,-0.031396,-0.074606,0.072951,0.039997,0.036423,-0.027152,-0.071900,0.026267,-0.046270,-0.017945,0.007933,-0.006203,-0.046099,0.032793,-0.069113,0.020403,0.030783,-0.003787,-0.000490,-0.022951,0.013498,0.009664,-0.007012,-0.016325,-0.005732,0.036069,-0.063906,0.033891,0.010560,-0.104517,-0.022069,0.054322,-0.005460,-0.029093,0.040991,-0.053018,-0.024017,0.050817,-0.003297,-0.020895,-0.053213,-0.028428,0.048231,-0.001221,0.001302,-0.044137,0.015528,-0.012792,-0.012009,-0.008211,0.031114,0.024982,0.003863,-0.032321,0.030920,-0.012845,0.070170,-0.004037,0.014003,0.005577,0.021611,-0.002889,0.034824,0.047164,0.050545,-0.017639,0.029014,-0.030378,-0.027056,0.011464,-0.039759,-0.043514,-0.025605,-0.022484,-0.036224,0.000566,0.005481,6.699346,0.061318,0.648336,0.044662,0.0,0.000000,4.528176,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-0.0
476443,2022-02-24,21,46.64010,32.61420,5.3,-1.0,65.8,0.000,0.0,0.00,0.0,0.0,28.1,18.4,27.5,1021.5,87.7,135.2,11.8,4.0,0.77,4.9,3.1,67.56,0.0,0.0,0.0,11.2,7.6,29.4,1020.0,100.0,0.0,0.1,0.0,False,True,False,False,False,True,False,False,2022,2,3,0,Kherson,Europe/Kiev,2022-02-24,06:38:31,17:27:46,00:00:00,Херсонська,0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0.0,0.0,1,0.580161,-0.090608,-0.028388,0.146350,0.071072,-0.030284,-0.004583,0.087399,-0.038512,0.016613,-0.038599,0.049747,0.186305,-0.172198,-0.045515,0.050785,0.041889,-0.112849,0.193473,-0.010566,0.044308,-0.118300,0.007117,-0.135687,-0.009441,-0.039465,0.032843,0.080393,-0.035434,0.010352,-0.016680,-0.046252,0.085840,-0.123167,0.064510,-0.023735,-0.025637,-0.027863,0.032156,0.068641,0.027667,0.162729,0.039675,-0.016915,-0.008203,0.048024,0.073343,0.025782,-0.013935,-0.008775,-0.045265,0.008979,-0.100558,0.044074,0.018202,-0.037279,0.062349,0.008014,0.075917,-0.063409,0.015404,-0.091507,-0.079240,-0.033000,-0.019226,-0.103926,0.031514,0.043306,-0.012137,-0.010430,0.035901,-0.013437,-0.042046,-0.064986,0.002947,0.024326,0.085592,-0.008453,0.091087,-0.106852,0.038223,-0.061062,0.027905,0.056421,-0.030501,0.000050,0.051385,-0.087324,-0.024025,0.031626,-0.029461,0.015717,-0.047181,-0.005600,0.049867,0.084412,-0.055460,-0.036620,0.120475,-0.012080,0.006961,-0.079701,0.055655,0.004130,0.013250,0.002392,0.041937,0.028208,-0.037232,0.014886,-0.036905,0.000138,-0.018200,-0.010680,-0.067564,-0.001064,-0.044792,-0.014807,-0.031911,-0.023504,0.070783,0.027626,0.000418,0.043677,-0.030193,-0.034979,0.080093,0.035489,-0.004156,-0.008032,0.039826,-0.037380,0.011931,0.008267,0.000590,0.043862,0.023758,0.038714,0.066128,0.028168,-0.012153,0.005376,0.008085,-0.038933,0.003404,0.003281,-0.004149,-0.025392,0.010434,-0.017613,6.990334,0.058342,0.580161,0.046602,0.0,6.699346,4.547433,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-0.0
132346,2022-02-24,7,48.62636,22.28514,1.8,-1.6,79.9,0.000,0.0,0.00,0.0,7.8,24.1,14.1,142.5,1025.6,48.1,142.7,10.2,4.0,0.77,-1.2,-1.2,91.15,0.0,0.0,0.0,3.6,4.4,100.0,1026.2,55.6,0.0,0.1,0.0,False,True,False,False,False,True,False,False,2022,2,3,0,Uzhgorod,Europe/Uzhgorod,2022-02-24,07:22:33,18:06:25,00:00:00,Закарпатська,0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0.0,0.0,1,0.580161,-0.090608,-0.028388,0.146350,0.071072,-0.030284,-0.004583,0.087399,-0.038512,0.016613,-0.038599,0.049747,0.186305,-0.172198,-0.045515,0.050785,0.041889,-0.112849,0.193473,-0.010566,0.044308,-0.118300,0.007117,-0.135687,-0.009441,-0.039465,0.032843,0.080393,-0.035434,0.010352,-0.016680,-0.046252,0.085840,-0.123167,0.064510,-0.023735,-0.025637,-0.027863,0.032156,0.068641,0.027667,0.162729,0.039675,-0.016915,-0.008203,0.048024,0.073343,0.025782,-0.013935,-0.008775,-0.045265,0.008979,-0.100558,0.044074,0.018202,-0.037279,0.062349,0.008014,0.075917,-0.063409,0.015404,-0.091507,-0.079240,-0.033000,-0.019226,-0.103926,0.031514,0.043306,-0.012137,-0.010430,0.035901,-0.013437,-0.042046,-0.064986,0.002947,0.024326,0.085592,-0.008453,0.091087,-0.106852,0.038223,-0.061062,0.027905,0.056421,-0.030501,0.000050,0.051385,-0.087324,-0.024025,0.031626,-0.029461,0.015717,-0.047181,-0.005600,0.049867,0.084412,-0.055460,-0.036620,0.120475,-0.012080,0.006961,-0.079701,0.055655,0.004130,0.013250,0.002392,0.041937,0.028208,-0.037232,0.014886,-0.036905,0.000138,-0.018200,-0.010680,-0.067564,-0.001064,-0.044792,-0.014807,-0.031911,-0.023504,0.070783,0.027626,0.000418,0.043677,-0.030193,-0.034979,0.080093,0.035489,-0.004156,-0.008032,0.039826,-0.037380,0.011931,0.008267,0.000590,0.043862,0.023758,0.038714,0.066128,0.028168,-0.012153,0.005376,0.008085,-0.038933,0.003404,0.003281,-0.004149,-0.025392,0.010434,-0.017613,6.990334,0.058342,0.580161,0.046602,0.0,6.699346,4.547433,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-0.0
132345,2022-02-24,7,48.62636,22.28514,1.8,-1.6,79.9,0.000,0.0,0.00,0.0,7.8,24.1,14.1,142.5,1025.6,48.1,142.7,10.2,4.0,0.77,-1.2,-1.2,91.15,0.0,0.0,0.0,3.6,4.4,100.0,1026.2,55.6,0.0,0.1,0.0,False,True,False,False,False,True,False,False,2022,2,3,0,Uzhgorod,Europe/Uzhgorod,2022-02-24,07:22:33,18:06:25,00:00:00,Закарпатська,0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0.0,0.0,1,0.648336,-0.079572,0.178041,0.061854,0.073453,-0.055809,-0.011311,0.047310,0.008354,0.006474,-0.047099,0.020496,0.050190,-0.038573,0.057228,-0.072471,0.045393,-0.116783,0.168249,0.167355,-0.025072,-0.073858,-0.097024,-0.146191,0.027983,0.082989,0.014423,0.058370,-0.033928,0.046265,0.006901,-0.049498,0.126117,-0.089039,-0.006767,-0.031686,-0.010346,0.025637,0.061278,0.162580,-0.028081,0.161291,-0.018217,-0.002657,0.038485,-0.000530,0.044413,0.107176,-0.050721,0.064279,-0.066677,0.016742,-0.050257,0.072549,-0.035201,-0.027279,0.017115,0.043631,0.024660,-0.025841,0.031320,-0.076959,-0.072986,-0.040465,0.003958,-0.022475,0.033208,-0.028056,-0.005499,-0.055998,-0.021882,-0.070462,0.018237,-0.031396,-0.074606,0.072951,0.039997,0.036423,-0.027152,-0.071900,0.026267,-0.046270,-0.017945,0.007933,-0.006203,-0.046099,0.032793,-0.069113,0.020403,0.030783,-0.003787,-0.000490,-0.022951,0.013498,0.009664,-0.007012,-0.016325,-0.005732,0.036069,-0.063906,0.033891,0.010560,-0.104517,-0.022069,0.054322,-0.005460,-0.029093,0.040991,-0.053018,-0.024017,0.050817,-0.003297,-0.020895,-0.053213,-0.028428,0.048231,-0.001221,0.001302,-0.044137,0.015528,-0.012792,-0.012009,-0.008211,0.031114,0.024982,0.003863,-0.032321,0.030920,-0.012845,0.070170,-0.004037,0.014003,0.005577,0.021611,-0.002889,0.034824,0.047164,0.050545,-0.017639,0.029014,-0.030378,-0.027056,0.011464,-0.039759,-0.043514,-0.025605,-0.022484,-0.036224,0.000566,0.005481,6.699346,0.061318,0.648336,0.044662,0.0,0.000000,4.528176,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-0.0

In [37]:
df_final.to_parquet("merged_dataset.parquet", index=False, engine="pyarrow")