# Data merge and feature engineering

In [1]:
%pip install pyarrow

Requirement already satisfied: pyarrow in c:\users\uw11\appdata\local\programs\python\python313\lib\site-packages (23.0.1)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.3.1 -> 26.0.1
[notice] To update, run: C:\Users\Uw11\AppData\Local\Programs\Python\Python313\python.exe -m pip install --upgrade pip

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import string

import re
import nltk
from nltk.stem import WordNetLemmatizer
from nltk.corpus import stopwords
from sklearn.feature_extraction.text import TfidfVectorizer
from tqdm.notebook import tqdm
from tqdm import tqdm
import pymorphy3
from collections import Counter

import os
from pathlib import Path
import json

In [3]:
df_weather = pd.read_csv("../data/weather_processed.csv")
df_war_events = pd.read_csv("../data/war_events_processed.csv")
df_isw_matrix = pd.read_csv("../data/isw_processed_svd.csv")

In [4]:
pd.set_option('display.max_columns', None)

In [5]:
df_weather['datetime_hour'] = pd.to_datetime(df_weather['datetime_hour'], errors="coerce")
df_war_events['datetime_hour'] = pd.to_datetime(df_war_events['datetime_hour'], errors="coerce")

In [6]:
df_final = pd.merge(
    df_weather, 
    df_war_events[['datetime_hour', 'region_id', 'alarm_active', 'alarm_minutes_in_hour']], 
    on=['datetime_hour', 'region_id'], 
    how='left'
)
df_final.sample(20)

,datetime_hour,region_id,city_latitude,city_longitude,day_temp,day_dew,day_humidity,day_precip,day_precipprob,day_precipcover,day_snow,day_snowdepth,day_windgust,day_windspeed,day_winddir,day_pressure,day_cloudcover,day_solarradiation,day_solarenergy,day_uvindex,day_moonphase,hour_temp,hour_feelslike,hour_humidity,hour_precip,hour_precipprob,hour_snow,hour_windgust,hour_windspeed,hour_winddir,hour_pressure,hour_cloudcover,hour_solarradiation,hour_solarenergy,hour_uvindex,day_conditions_simple_Clear,day_conditions_simple_Cloudy,day_conditions_simple_Rain,day_conditions_simple_Snow,hour_conditions_simple_Clear,hour_conditions_simple_Cloudy,hour_conditions_simple_Rain,hour_conditions_simple_Snow,year,month,day_of_week,hour,city_name,city_timezone,day_datetime,day_sunrise,day_sunset,hour_datetime,region_key,alarm_active,alarm_minutes_in_hour
257587,2023-05-17 06:00:00,22,49.4168,26.9743,17.3,8.7,57.6,0.200,100.0,8.33,0.0,0.0,38.9,20.5,152.7,1014.9,92.7,173.9,15.1,6.0,0.92,14.8,14.8,60.37,0.0,0.0,0.0,32.4,16.9,150.8,1014.0,100.0,3.3,0.0,0.0,False,False,True,False,False,True,False,False,2023,5,2,6,Khmelnytskyi,Europe/Kiev,2023-05-17,05:26:22,20:51:34,06:00:00,Хмельницька,0,0.0
124498,2022-09-28 04:00:00,13,49.8444,24.0254,11.6,8.1,80.9,4.200,100.0,8.33,0.0,0.0,37.8,16.2,252.7,1001.4,63.7,113.0,9.7,6.0,0.07,10.4,10.4,92.89,0.0,0.0,0.0,10.1,4.3,168.9,999.0,93.5,0.0,0.1,0.0,False,False,True,False,False,True,False,False,2022,9,2,4,Lviv,Europe/Kiev,2022-09-28,07:18:56,19:09:24,04:00:00,Львівська,0,0.0
34915,2022-04-25 15:00:00,22,49.4168,26.9743,13.7,8.1,70.6,7.000,100.0,8.33,0.0,0.0,29.9,14.4,185.1,1006.9,88.0,181.9,15.9,8.0,0.80,18.6,18.6,43.36,0.0,0.0,0.0,19.8,3.6,130.0,1005.1,90.0,771.0,2.8,8.0,False,False,True,False,False,True,False,False,2022,4,0,15,Khmelnytskyi,Europe/Kiev,2022-04-25,06:01:17,20:19:56,15:00:00,Хмельницька,0,0.0
181585,2023-01-05 07:00:00,3,50.7469,25.3263,6.5,4.0,84.4,7.124,100.0,8.33,0.0,0.0,53.6,35.8,255.4,1006.1,99.5,5.6,0.5,0.0,0.42,7.2,3.1,81.24,0.0,0.0,0.0,51.5,27.0,244.9,1006.0,100.0,0.0,0.1,0.0,False,False,True,False,False,True,False,False,2023,1,3,7,Lutsk,Europe/Kiev,2023-01-05,08:20:08,16:28:05,07:00:00,Волинська,0,0.0
534965,2024-09-09 21:00:00,7,48.6264,22.2851,19.6,8.7,51.7,2.148,100.0,20.83,0.0,0.0,42.1,17.9,88.7,1009.3,68.5,177.5,15.3,6.0,0.21,20.8,20.8,59.44,0.0,0.0,0.0,16.6,0.0,319.0,1005.7,100.0,0.0,0.0,0.0,False,False,True,False,False,True,False,False,2024,9,0,21,Uzhgorod,Europe/Uzhgorod,2024-09-09,06:59:34,19:55:44,21:00:00,Закарпатська,0,0.0
215099,2023-03-04 11:00:00,14,46.9734,31.9852,4.1,-0.3,75.5,0.000,0.0,0.00,0.0,0.0,44.6,23.4,234.9,1011.6,26.6,164.1,14.2,6.0,0.40,6.7,4.5,56.67,0.0,0.0,0.0,35.3,10.8,220.0,1014.0,50.0,530.5,1.9,5.0,False,True,False,False,False,True,False,False,2023,3,5,11,Mykolaiv,Europe/Kiev,2023-03-04,06:27:11,17:41:19,11:00:00,Миколаївська,0,0.0
101090,2022-08-18 13:00:00,4,48.4753,35.0160,24.0,19.0,75.0,0.500,100.0,12.50,0.0,0.0,20.5,14.4,257.8,1008.7,39.2,191.5,16.5,8.0,0.68,28.6,29.1,50.42,0.1,100.0,0.0,20.2,7.2,244.9,1008.0,58.0,770.0,2.8,8.0,False,False,True,False,False,False,True,False,2022,8,3,13,Dnipro,Europe/Kiev,2022-08-18,05:37:22,19:49:23,13:00:00,Дніпропетровська,0,0.0
208808,2023-02-21 13:00:00,10,50.4506,30.5243,3.8,1.1,82.6,9.000,100.0,8.33,0.3,0.9,73.4,33.5,288.2,996.0,78.9,76.2,6.6,3.0,0.04,5.6,0.9,73.84,0.0,0.0,0.0,68.8,29.2,286.9,994.0,99.2,338.8,1.2,3.0,False,False,False,True,False,True,False,False,2023,2,1,13,Kyiv,Europe/Kiev,2023-02-21,06:58:49,17:25:09,13:00:00,Київська,0,0.0
217922,2023-03-09 09:00:00,4,48.4753,35.0160,9.9,4.9,73.9,0.500,100.0,8.33,0.0,0.0,39.6,25.2,197.8,1003.8,61.6,138.1,12.0,6.0,0.57,5.0,1.0,97.93,0.0,0.0,0.0,35.6,19.8,192.7,1005.0,100.0,131.7,0.5,1.0,False,False,True,False,False,True,False,False,2023,3,3,9,Dnipro,Europe/Kiev,2023-03-09,06:06:26,17:35:32,09:00:00,Дніпропетровська,0,0.0
417228,2024-02-18 10:00:00,15,46.4725,30.7371,3.1,1.7,90.7,0.600,100.0,12.50,0.0,0.0,30.6,17.6,305.5,1028.0,96.2,39.3,3.5,2.0,0.29,3.8,0.9,90.57,0.0,0.0,0.0,22.0,11.2,263.8,1028.0,100.0,173.7,0.6,2.0,False,False,True,False,False,True,False,False,2024,2,6,10,Odesa,Europe/Kiev,2024-02-18,06:56:53,17:25:55,10:00:00,Одеська,0,0.0
284134,2023-07-02 08:00:00,25,51.4937,31.2944,21.6,17.4,78.4,0.300,100.0,4.17,0.0,0.0,45.0,18.0,239.2,1004.8,55.6,246.8,21.4,7.0,0.46,21.8,21.8,76.56,0.0,0.0,0.0,18.0,7.2,230.9,1005.0,19.8,252.3,0.9,3.0,False,False,True,False,True,False,False,False,2023,7,6,8,Chernihiv,Europe/Kiev,2023-07-02,04:42:30,21:14:54,08:00:00,Чернігівська,1,10.6
61495,2022-06-10 19:00:00,9,48.9226,24.7147,20.7,14.0,67.3,1.400,100.0,16.67,0.0,0.0,45.4,22.0,314.6,1013.2,72.7,258.6,22.4,8.0,0.35,24.1,24.1,67.03,0.4,100.0,0.0,37.1,9.0,308.1,1013.0,94.4,126.0,0.5,1.0,False,False,True,False,False,False,True,False,2022,6,4,19,Ivano-Frankivsk,Europe/Kiev,2022-06-10,05:17:42,21:23:52,19:00:00,Івано-Франківська,0,0.0
127231,2022-10-02 22:00:00,9,48.9226,24.7147,12.4,9.2,81.0,14.000,100.0,8.33,0.0,0.0,72.0,26.3,291.7,1010.4,79.3,94.3,8.0,5.0,0.20,10.3,10.3,79.45,0.0,0.0,0.0,24.1,11.9,277.1,1012.0,61.8,0.0,0.1,0.0,False,False,True,False,False,True,False,False,2022,10,6,22,Ivano-Frankivsk,Europe/Kiev,2022-10-02,07:21:48,18:58:27,22:00:00,Івано-Франківська,0,0.0
40630,2022-05-05 13:00:00,25,51.4937,31.2944,8.1,-3.6,45.8,0.000,0.0,0.00,0.0,0.0,25.2,14.4,58.2,1025.9,17.2,305.1,26.4,8.0,0.14,12.1,12.1,30.38,0.0,0.0,0.0,23.8,11.2,63.5,1027.0,0.0,848.0,3.1,8.0,True,False,False,False,True,False,False,False,2022,5,3,13,Chernihiv,Europe/Kiev,2022-05-05,05:19:47,20:24:24,13:00:00,Чернігівська,0,0.0
291741,2023-07-15 13:00:00,24,48.2924,25.9355,22.7,13.7,61.0,0.000,0.0,0.00,0.0,0.0,21.6,13.7,338.0,1019.0,18.0,309.1,26.9,9.0,0.92,26.7,26.7,41.49,0.0,0.0,0.0,14.4,5.6,125.0,1019.4,20.4,787.1,2.8,8.0,True,False,False,False,False,True,False,False,2023,7,5,13,Chernivtsi,Europe/Kiev,2023-07-15,05:30:50,21:13:06,13:00:00,Чернівецька,0,0.0
186978,2023-01-14 15:00:00,21,46.6401,32.6142,-0.8,-2.8,84.0,0.000,0.0,0.00,0.0,0.0,22.3,13.7,67.2,1022.7,73.4,76.5,6.6,4.0,0.73,0.0,0.0,71.58,0.0,0.0,0.0,20.5,11.9,64.4,1022.0,25.9,202.0,0.7,2.0,False,True,False,False,False,True,False,False,2023,1,5,15,Kherson,Europe/Kiev,2023-01-14,07:30:36,16:26:45,15:00:00,Херсонська,1,60.0
120471,2022-09-21 04:00:00,18,50.9080,34.7972,10.6,8.0,84.9,3.605,100.0,8.33,0.0,0.0,29.9,14.1,147.3,1010.9,74.6,100.6,8.5,5.0,0.83,9.9,9.2,94.77,0.0,0.0,0.0,13.3,6.5,73.2,1011.0,87.6,0.0,0.1,0.0,False,False,True,False,False,True,False,False,2022,9,2,4,Sumy,Europe/Kiev,2022-09-21,06:25:03,18:41:56,04:00:00,Сумська,0,0.0
617424,2025-01-31 01:00:00,2,49.2336,28.4486,5.9,5.3,96.0,0.400,100.0,12.50,0.0,0.0,34.2,15.1,180.3,1024.5,99.7,23.8,1.9,1.0,0.07,4.9,2.5,98.61,0.1,100.0,0.0,20.2,10.1,162.8,1025.0,99.0,0.0,0.0,0.0,False,False,True,False,False,False,True,False,2025,1,4,1,Vinnytsia,Europe/Kiev,2025-01-31,07:38:46,17:01:17,01:00:00,Вінницька,0,0.0
443165,2024-04-03 12:00:00,7,48.6264,22.2851,10.1,3.8,69.6,0.124,100.0,16.67,0.0,0.0,53.6,19.6,220.8,1011.0,51.8,187.1,16.1,6.0,0.81,13.3,13.3,69.28,0.0,0.0,0.0,25.2,10.8,140.0,1012.1,30.0,530.7,1.9,5.0,False,False,True,False,False,True,False,False,2024,4,2,12,Uzhgorod,Europe/Uzhgorod,2024-04-03,07:03:54,20:05:07,12:00:00,Закарпатська,0,0.0
596191,2024-12-25 04:00:00,9,48.9226,24.7147,-0.2,-1.8,89.3,0.400,100.0,4.17,1.3,2.0,27.7,14.4,341.4,1034.9,91.7,26.2,2.3,1.0,0.82,0.2,-3.4,90.30,0.0,0.0,0.1,19.8,11.2,336.7,1031.0,99.7,0.0,0.0,0.0,False,False,False,True,False,True,False,False,2024,12,2,4,Ivano-Frankivsk,Europe/Kiev,2024-12-25,08:14:05,16:28:55,04:00:00,Івано-Франківська,0,0.0

In [7]:
df_final = df_final.sort_values(['region_id', 'datetime_hour'])
df_final.head()

,datetime_hour,region_id,city_latitude,city_longitude,day_temp,day_dew,day_humidity,day_precip,day_precipprob,day_precipcover,day_snow,day_snowdepth,day_windgust,day_windspeed,day_winddir,day_pressure,day_cloudcover,day_solarradiation,day_solarenergy,day_uvindex,day_moonphase,hour_temp,hour_feelslike,hour_humidity,hour_precip,hour_precipprob,hour_snow,hour_windgust,hour_windspeed,hour_winddir,hour_pressure,hour_cloudcover,hour_solarradiation,hour_solarenergy,hour_uvindex,day_conditions_simple_Clear,day_conditions_simple_Cloudy,day_conditions_simple_Rain,day_conditions_simple_Snow,hour_conditions_simple_Clear,hour_conditions_simple_Cloudy,hour_conditions_simple_Rain,hour_conditions_simple_Snow,year,month,day_of_week,hour,city_name,city_timezone,day_datetime,day_sunrise,day_sunset,hour_datetime,region_key,alarm_active,alarm_minutes_in_hour
0,2022-02-24 00:00:00,2,49.2336,28.4486,2.8,-0.3,80.5,0.3,100.0,4.17,0.0,0.0,27.7,10.8,312.0,1023.4,82.5,60.4,5.4,3.0,0.77,2.1,-0.5,91.76,0.0,0.0,0.0,16.6,8.6,279.6,1021.0,91.1,0.0,0.1,0.0,False,False,False,True,False,True,False,False,2022,2,3,0,Vinnytsia,Europe/Kiev,2022-02-24,06:58:49,17:40:52,00:00:00,Вінницька,0,0.0
24,2022-02-24 01:00:00,2,49.2336,28.4486,2.8,-0.3,80.5,0.3,100.0,4.17,0.0,0.0,27.7,10.8,312.0,1023.4,82.5,60.4,5.4,3.0,0.77,2.1,-0.4,89.80,0.0,0.0,0.0,16.6,8.3,289.2,1021.0,97.9,0.0,0.1,0.0,False,False,False,True,False,True,False,False,2022,2,3,1,Vinnytsia,Europe/Kiev,2022-02-24,06:58:49,17:40:52,01:00:00,Вінницька,0,0.0
48,2022-02-24 02:00:00,2,49.2336,28.4486,2.8,-0.3,80.5,0.3,100.0,4.17,0.0,0.0,27.7,10.8,312.0,1023.4,82.5,60.4,5.4,3.0,0.77,2.0,-0.3,90.44,0.0,0.0,0.0,27.7,7.6,287.6,1021.0,98.2,0.0,0.1,0.0,False,False,False,True,False,True,False,False,2022,2,3,2,Vinnytsia,Europe/Kiev,2022-02-24,06:58:49,17:40:52,02:00:00,Вінницька,0,0.0
72,2022-02-24 03:00:00,2,49.2336,28.4486,2.8,-0.3,80.5,0.3,100.0,4.17,0.0,0.0,27.7,10.8,312.0,1023.4,82.5,60.4,5.4,3.0,0.77,1.9,-0.3,91.75,0.0,0.0,0.0,15.1,7.2,288.9,1021.0,98.8,0.0,0.1,0.0,False,False,False,True,False,True,False,False,2022,2,3,3,Vinnytsia,Europe/Kiev,2022-02-24,06:58:49,17:40:52,03:00:00,Вінницька,0,0.0
96,2022-02-24 04:00:00,2,49.2336,28.4486,2.8,-0.3,80.5,0.3,100.0,4.17,0.0,0.0,27.7,10.8,312.0,1023.4,82.5,60.4,5.4,3.0,0.77,1.8,-0.2,92.40,0.0,0.0,0.0,13.7,6.5,290.4,1021.0,100.0,0.0,0.1,0.0,False,False,False,True,False,True,False,False,2022,2,3,4,Vinnytsia,Europe/Kiev,2022-02-24,06:58:49,17:40:52,04:00:00,Вінницька,0,0.0

In [8]:
df_final.info()

<class 'pandas.DataFrame'>
Index: 634680 entries, 0 to 634679
Data columns (total 56 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   datetime_hour                  634680 non-null  datetime64[us]
 1   region_id                      634680 non-null  int64
 2   city_latitude                  634680 non-null  float64
 3   city_longitude                 634680 non-null  float64
 4   day_temp                       634680 non-null  float64
 5   day_dew                        634680 non-null  float64
 6   day_humidity                   634680 non-null  float64
 7   day_precip                     634680 non-null  float64
 8   day_precipprob                 634680 non-null  float64
 9   day_precipcover                634680 non-null  float64
 10  day_snow                       634680 non-null  float64
 11  day_snowdepth                  634680 non-null  float64
 12  day_windgust                   634680 non-null  float64
 13  day_windspeed                  634680 non-null  float64
 14  day_winddir                    634680 non-null  float64
 15  day_pressure                   634680 non-null  float64
 16  day_cloudcover                 634680 non-null  float64
 17  day_solarradiation             634680 non-null  float64
 18  day_solarenergy                634680 non-null  float64
 19  day_uvindex                    634680 non-null  float64
 20  day_moonphase                  634680 non-null  float64
 21  hour_temp                      634680 non-null  float64
 22  hour_feelslike                 634680 non-null  float64
 23  hour_humidity                  634680 non-null  float64
 24  hour_precip                    634680 non-null  float64
 25  hour_precipprob                634680 non-null  float64
 26  hour_snow                      634680 non-null  float64
 27  hour_windgust                  634680 non-null  float64
 28  hour_windspeed                 634680 non-null  float64
 29  hour_winddir                   634680 non-null  float64
 30  hour_pressure                  634680 non-null  float64
 31  hour_cloudcover                634680 non-null  float64
 32  hour_solarradiation            634680 non-null  float64
 33  hour_solarenergy               634680 non-null  float64
 34  hour_uvindex                   634680 non-null  float64
 35  day_conditions_simple_Clear    634680 non-null  bool
 36  day_conditions_simple_Cloudy   634680 non-null  bool
 37  day_conditions_simple_Rain     634680 non-null  bool
 38  day_conditions_simple_Snow     634680 non-null  bool
 39  hour_conditions_simple_Clear   634680 non-null  bool
 40  hour_conditions_simple_Cloudy  634680 non-null  bool
 41  hour_conditions_simple_Rain    634680 non-null  bool
 42  hour_conditions_simple_Snow    634680 non-null  bool
 43  year                           634680 non-null  int64
 44  month                          634680 non-null  int64
 45  day_of_week                    634680 non-null  int64
 46  hour                           634680 non-null  int64
 47  city_name                      634680 non-null  str
 48  city_timezone                  634680 non-null  str
 49  day_datetime                   634680 non-null  str
 50  day_sunrise                    634680 non-null  str
 51  day_sunset                     634680 non-null  str
 52  hour_datetime                  634680 non-null  str
 53  region_key                     634680 non-null  str
 54  alarm_active                   634680 non-null  int64
 55  alarm_minutes_in_hour          634680 non-null  float64
dtypes: bool(8), datetime64[us](1), float64(34), int64(6), str(7)
memory usage: 287.3 MB

In [9]:
df_final = df_final.sort_values(["region_id", "datetime_hour"])

df_final["alarm_lag_1"] = df_final.groupby("region_id")["alarm_active"].shift(1)
df_final["alarm_lag_3"] = df_final.groupby("region_id")["alarm_active"].shift(3)
df_final["alarm_lag_6"] = df_final.groupby("region_id")["alarm_active"].shift(6)
df_final["alarm_lag_12"] = df_final.groupby("region_id")["alarm_active"].shift(12)
#df_final['alarm_minutes_lag1'] = (df_final.groupby('region_id')['alarm_minutes_in_hour'].shift(1).fillna(0))
#df_final['alarm_minutes_lag3'] = (df_final.groupby('region_id')['alarm_minutes_in_hour'].shift(3).fillna(0))

lag_cols = ["alarm_lag_1","alarm_lag_3","alarm_lag_6","alarm_lag_12"]
df_final[lag_cols] = df_final[lag_cols].fillna(0)

df_final['alarms_in_last_24h'] = (df_final.groupby('region_id')['alarm_active'].transform(lambda x: x.shift(1).rolling(24, min_periods=1).sum()))

df_final['is_weekend'] = df_final['day_of_week'].isin([5, 6]).astype(int)
df_final['is_night'] = ((df_final['hour'] >= 23) | (df_final['hour'] <= 6)).astype(int)

hourly_total = df_final.groupby('datetime_hour')['alarm_active'].sum().shift(1)
df_final['total_active_alarms_lag1'] = df_final['datetime_hour'].map(hourly_total)

df_final.sample(10)

,datetime_hour,region_id,city_latitude,city_longitude,day_temp,day_dew,day_humidity,day_precip,day_precipprob,day_precipcover,day_snow,day_snowdepth,day_windgust,day_windspeed,day_winddir,day_pressure,day_cloudcover,day_solarradiation,day_solarenergy,day_uvindex,day_moonphase,hour_temp,hour_feelslike,hour_humidity,hour_precip,hour_precipprob,hour_snow,hour_windgust,hour_windspeed,hour_winddir,hour_pressure,hour_cloudcover,hour_solarradiation,hour_solarenergy,hour_uvindex,day_conditions_simple_Clear,day_conditions_simple_Cloudy,day_conditions_simple_Rain,day_conditions_simple_Snow,hour_conditions_simple_Clear,hour_conditions_simple_Cloudy,hour_conditions_simple_Rain,hour_conditions_simple_Snow,year,month,day_of_week,hour,city_name,city_timezone,day_datetime,day_sunrise,day_sunset,hour_datetime,region_key,alarm_active,alarm_minutes_in_hour,alarm_lag_1,alarm_lag_3,alarm_lag_6,alarm_lag_12,alarms_in_last_24h,is_weekend,is_night,total_active_alarms_lag1
259282,2023-05-20 05:00:00,13,49.8444,24.0254,17.2,11.7,73.2,0.100,100.0,4.17,0.0,0.0,33.1,15.5,68.6,1024.3,47.0,254.6,22.1,7.0,0.02,12.0,12.0,96.12,0.0,0.0,0.0,13.0,5.8,32.4,1025.0,73.2,0.0,0.0,0.0,False,False,True,False,False,True,False,False,2023,5,5,5,Lviv,Europe/Kiev,2023-05-20,05:32:42,21:09:03,05:00:00,Львівська,0,0.000000,0.0,0.0,0.0,0.0,1.0,1,1,3.0
473668,2024-05-26 11:00:00,6,50.2536,28.6654,17.7,4.1,45.7,0.000,0.0,0.00,0.0,0.0,29.5,11.9,75.8,1023.5,29.6,327.0,28.3,9.0,0.60,23.3,23.3,26.70,0.0,0.0,0.0,22.3,9.4,66.3,1024.0,0.0,737.4,2.7,7.0,False,True,False,False,True,False,False,False,2024,5,6,11,Zhytomyr,Europe/Kiev,2024-05-26,05:04:59,21:00:44,11:00:00,Житомирська,0,0.000000,1.0,0.0,1.0,0.0,7.0,1,0,24.0
472583,2024-05-24 13:00:00,26,50.4506,30.5243,20.8,10.6,54.6,0.400,100.0,4.17,0.0,0.0,43.9,18.7,94.2,1023.2,32.9,293.2,25.1,8.0,0.53,26.1,26.1,37.54,0.0,0.0,0.0,43.9,15.8,97.9,1024.0,14.0,837.1,3.0,8.0,False,False,True,False,True,False,False,False,2024,5,4,13,Kyiv,Europe/Kiev,2024-05-24,04:58:43,20:51:45,13:00:00,Київ,1,22.933333,0.0,0.0,0.0,0.0,2.0,0,0,6.0
275329,2023-06-17 02:00:00,3,50.7469,25.3263,18.5,16.7,89.5,9.774,100.0,8.33,0.0,0.0,22.7,13.3,180.8,1010.7,98.4,141.5,12.2,4.0,0.97,16.8,16.8,98.11,0.0,0.0,0.0,15.5,13.3,123.5,1010.0,99.9,0.0,0.0,0.0,False,False,True,False,False,True,False,False,2023,6,5,2,Lutsk,Europe/Kiev,2023-06-17,05:05:06,21:34:16,02:00:00,Волинська,0,0.000000,0.0,0.0,0.0,0.0,2.0,1,1,1.0
540548,2024-09-19 13:00:00,23,49.4407,32.0637,16.7,3.2,44.3,0.000,0.0,0.00,0.0,0.0,38.9,16.9,64.2,1026.0,30.6,198.3,17.1,7.0,0.54,23.3,23.3,21.08,0.0,0.0,0.0,38.2,16.6,76.3,1027.0,37.7,654.7,2.4,7.0,False,True,False,False,False,True,False,False,2024,9,3,13,Cherkasy,Europe/Kiev,2024-09-19,06:34:12,18:55:47,13:00:00,Черкаська,0,0.000000,0.0,0.0,0.0,1.0,5.0,0,0,8.0
109509,2022-09-02 03:00:00,24,48.2924,25.9355,13.9,12.2,89.8,16.042,100.0,41.67,0.0,0.0,21.7,10.9,143.5,1021.0,99.0,27.0,2.3,1.0,0.19,14.8,14.8,86.86,0.0,0.0,0.0,12.7,3.8,336.0,1019.4,100.0,0.0,0.1,0.0,False,False,True,False,False,True,False,False,2022,9,4,3,Chernivtsi,Europe/Kiev,2022-09-02,06:34:51,19:56:14,03:00:00,Чернівецька,0,0.000000,0.0,0.0,0.0,0.0,0.0,0,1,5.0
281806,2023-06-28 07:00:00,25,51.4937,31.2944,16.3,12.3,78.9,11.000,100.0,8.33,0.0,0.0,63.0,28.4,243.5,1005.0,81.3,227.7,19.8,7.0,0.33,14.0,14.0,97.44,0.0,0.0,0.0,14.4,10.1,211.8,1004.0,100.0,20.1,0.1,0.0,False,False,True,False,False,True,False,False,2023,6,2,7,Chernihiv,Europe/Kiev,2023-06-28,04:40:02,21:15:55,07:00:00,Чернігівська,0,0.000000,0.0,0.0,0.0,0.0,2.0,0,0,0.0
322113,2023-09-06 07:00:00,11,48.5085,32.2656,19.5,10.6,60.5,0.000,0.0,0.00,0.0,0.0,31.0,21.6,353.1,1021.7,35.4,221.3,19.2,7.0,0.71,14.2,14.2,78.42,0.0,0.0,0.0,20.9,12.2,353.3,1023.0,12.8,18.2,0.1,0.0,False,True,False,False,True,False,False,False,2023,9,2,7,Kropyvnytskyi,Europe/Kiev,2023-09-06,06:14:27,19:23:33,07:00:00,Кіровоградська,0,0.000000,1.0,1.0,0.0,1.0,5.0,0,0,24.0
356554,2023-11-05 02:00:00,13,49.8444,24.0254,9.1,6.0,81.1,3.000,100.0,4.17,0.0,0.0,57.2,25.2,177.2,993.7,74.0,26.0,2.2,1.0,0.75,6.7,5.3,88.29,0.0,0.0,0.0,16.9,7.2,220.0,996.3,8.8,0.0,0.0,0.0,False,False,True,False,True,False,False,False,2023,11,6,2,Lviv,Europe/Kiev,2023-11-05,07:19:06,16:55:12,02:00:00,Львівська,0,0.000000,0.0,0.0,0.0,1.0,4.0,1,1,2.0
597456,2024-12-27 09:00:00,2,49.2336,28.4486,-0.1,-0.6,96.7,1.300,100.0,8.33,0.2,0.0,27.0,12.6,349.6,1032.9,100.0,5.8,0.4,0.0,0.89,-0.7,-4.4,100.00,0.0,0.0,0.0,20.9,10.8,353.6,1033.0,100.0,2.5,0.0,0.0,False,False,False,True,False,True,False,False,2024,12,4,9,Vinnytsia,Europe/Kiev,2024-12-27,08:01:02,16:14:05,09:00:00,Вінницька,0,0.000000,0.0,0.0,0.0,0.0,0.0,0,0,0.0

In [10]:
neighbouring_regions = {
    1: [21],
    2: [6, 10, 11, 15, 22, 23, 24],
    3: [13, 17],
    4: [5, 8, 11, 14, 16, 20, 21],
    5: [4, 8, 12, 20],
    6: [2, 10, 17, 22],
    7: [9, 13],
    8: [4, 5, 21],
    9: [7, 13, 19, 24],
    10: [2, 6, 16, 23, 25],
    11: [2, 4, 14, 15, 16, 23],
    12: [5, 20],
    13: [3, 7, 9, 17, 19],
    14: [4, 11, 15, 21],
    15: [2, 11, 14],
    16: [4, 10, 11, 18, 20, 23, 25],
    17: [3, 6, 13, 19, 22],
    18: [16, 20, 25],
    19: [9, 13, 17, 22, 24],
    20: [4, 5, 12, 16, 18],
    21: [1, 4, 8, 14],
    22: [2, 6, 17, 19, 24],
    23: [2, 10, 11, 16],
    24: [2, 9, 19, 22],
    25: [10, 16, 18], 
    26: [10]
}

alarms_matrix = df_final.pivot_table(
    index='datetime_hour',
    columns='region_id',
    values='alarm_active',
    fill_value=0
)

neighbour_alarm_matrix = pd.DataFrame(index=alarms_matrix.index)

for region, neighbours in neighbouring_regions.items():
    valid_neighbours = [n for n in neighbours if n in alarms_matrix.columns]
    
    if valid_neighbours:
        neighbour_alarm_matrix[region] = alarms_matrix[valid_neighbours].sum(axis=1)
    else:
        neighbour_alarm_matrix[region] = 0

neighbour_alarm_matrix = neighbour_alarm_matrix.shift(1)

neighbour_alarm_long = (neighbour_alarm_matrix.stack().reset_index())

neighbour_alarm_long.columns = ['datetime_hour','region_id','neighbour_alarms']

df_final = df_final.merge(neighbour_alarm_long,on=['datetime_hour', 'region_id'], how='left')

In [11]:
def hours_since_last_alarm(series):
    shifted = series.shift(1).fillna(0)
    result = []
    count = 0
    for val in shifted:
        if val == 1:
            count = 0
        else:
            count += 1
        result.append(count)
    return pd.Series(result, index=series.index)

df_final['hours_since_last_alarm'] = (df_final.groupby('region_id')['alarm_active'].transform(hours_since_last_alarm))

In [12]:
df_final.sample(20)

,datetime_hour,region_id,city_latitude,city_longitude,day_temp,day_dew,day_humidity,day_precip,day_precipprob,day_precipcover,day_snow,day_snowdepth,day_windgust,day_windspeed,day_winddir,day_pressure,day_cloudcover,day_solarradiation,day_solarenergy,day_uvindex,day_moonphase,hour_temp,hour_feelslike,hour_humidity,hour_precip,hour_precipprob,hour_snow,hour_windgust,hour_windspeed,hour_winddir,hour_pressure,hour_cloudcover,hour_solarradiation,hour_solarenergy,hour_uvindex,day_conditions_simple_Clear,day_conditions_simple_Cloudy,day_conditions_simple_Rain,day_conditions_simple_Snow,hour_conditions_simple_Clear,hour_conditions_simple_Cloudy,hour_conditions_simple_Rain,hour_conditions_simple_Snow,year,month,day_of_week,hour,city_name,city_timezone,day_datetime,day_sunrise,day_sunset,hour_datetime,region_key,alarm_active,alarm_minutes_in_hour,alarm_lag_1,alarm_lag_3,alarm_lag_6,alarm_lag_12,alarms_in_last_24h,is_weekend,is_night,total_active_alarms_lag1,neighbour_alarms,hours_since_last_alarm
281586,2024-02-08 02:00:00,13,49.8444,24.0254,0.8,0.3,96.0,8.000,100.0,8.33,2.3,0.5,35.3,17.6,240.6,1006.1,100.0,19.8,1.7,1.0,0.95,1.4,-3.2,93.73,0.0,0.0,0.0,33.5,17.6,290.3,1005.0,100.0,0.0,0.0,0.0,False,False,False,True,False,True,False,False,2024,2,3,2,Lviv,Europe/Kiev,2024-02-08,07:47:18,17:29:34,02:00:00,Львівська,0,0.0,0.0,0.0,0.0,0.0,4.0,0,1,6.0,0.0,17
213460,2022-05-14 05:00:00,10,50.4506,30.5243,15.5,6.7,57.2,0.100,100.0,4.17,0.0,0.0,45.0,16.6,297.9,1011.5,82.2,197.2,16.7,8.0,0.44,12.5,12.5,77.64,0.0,0.0,0.0,17.3,5.8,233.0,1011.0,76.1,0.0,0.1,0.0,False,False,True,False,False,True,False,False,2022,5,5,5,Kyiv,Europe/Kiev,2022-05-14,05:12:02,20:37:28,05:00:00,Київська,0,0.0,0.0,0.0,0.0,0.0,3.0,1,1,0.0,0.0,6
120096,2023-10-13 14:00:00,6,50.2536,28.6654,14.2,9.9,76.9,4.000,100.0,4.17,0.0,0.0,28.8,13.0,281.8,1017.8,60.5,111.4,9.6,4.0,0.96,18.0,18.0,52.35,0.0,0.0,0.0,25.2,12.6,295.3,1019.0,4.2,438.2,1.6,4.0,False,False,True,False,True,False,False,False,2023,10,4,14,Zhytomyr,Europe/Kiev,2023-10-13,07:23:36,18:18:56,14:00:00,Житомирська,0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,3.0,0.0,178
166926,2023-02-03 01:00:00,8,47.8289,35.1626,0.9,-0.7,89.4,0.400,100.0,16.67,0.0,1.3,26.3,16.2,167.6,1014.5,70.7,82.1,7.0,4.0,0.42,0.4,-3.9,92.32,0.0,0.0,0.0,22.3,14.8,183.5,1015.0,100.0,0.0,0.0,0.0,False,False,False,True,False,True,False,False,2023,2,4,1,Zaporozhye,Europe/Zaporozhye,2023-02-03,07:04:34,16:42:22,01:00:00,Запорізька,0,0.0,0.0,0.0,0.0,1.0,3.0,0,1,0.0,0.0,11
388238,2024-03-15 10:00:00,17,50.6193,26.2513,3.3,0.6,83.8,0.000,0.0,0.00,0.0,0.0,25.2,10.8,154.0,1020.0,52.2,144.7,12.4,5.0,0.17,5.5,4.0,79.29,0.0,0.0,0.0,17.3,6.8,120.6,1021.0,45.2,331.7,1.2,3.0,False,True,False,False,False,True,False,False,2024,3,4,10,Rivne,Europe/Kiev,2024-03-15,06:28:05,18:20:30,10:00:00,Рівненська,0,0.0,0.0,0.0,0.0,0.0,2.0,0,0,3.0,0.0,20
225224,2023-09-16 10:00:00,10,50.4506,30.5243,16.8,13.2,80.8,0.800,100.0,4.17,0.0,0.0,23.0,11.9,48.0,1025.8,88.3,95.3,8.1,3.0,0.05,15.0,15.0,84.45,0.0,0.0,0.0,18.7,8.3,61.6,1026.0,90.6,132.9,0.5,1.0,False,False,True,False,False,True,False,False,2023,9,5,10,Kyiv,Europe/Kiev,2023-09-16,06:34:17,19:10:38,10:00:00,Київська,0,0.0,0.0,0.0,0.0,0.0,0.0,1,0,3.0,0.0,150
495719,2024-05-25 08:00:00,21,46.6401,32.6142,19.6,3.5,36.6,0.000,0.0,0.00,0.0,0.0,52.2,25.9,62.6,1021.0,2.1,332.3,28.6,9.0,0.56,18.7,18.7,34.93,0.0,0.0,0.0,40.3,22.3,59.2,1022.0,0.0,313.2,1.1,3.0,True,False,False,False,True,False,False,False,2024,5,5,8,Kherson,Europe/Kiev,2024-05-25,05:04:50,20:28:57,08:00:00,Херсонська,0,0.0,0.0,0.0,0.0,1.0,8.0,1,0,0.0,0.0,6
422316,2025-01-27 12:00:00,18,50.9080,34.7972,4.4,3.6,94.6,0.115,100.0,8.33,0.0,0.0,39.6,23.4,193.8,1020.6,100.0,14.4,1.4,1.0,0.93,5.1,1.5,93.25,0.0,0.0,0.0,34.2,16.9,206.2,1021.0,100.0,69.8,0.3,1.0,False,False,True,False,False,True,False,False,2025,1,0,12,Sumy,Europe/Kiev,2025-01-27,07:24:12,16:23:41,12:00:00,Сумська,1,60.0,1.0,1.0,0.0,1.0,20.0,0,0,2.0,0.0,0
465793,2024-01-01 06:00:00,20,50.0042,36.2358,1.0,-1.2,85.4,0.300,100.0,12.50,0.0,0.0,37.1,18.0,212.7,1014.0,87.8,30.8,2.7,2.0,0.67,0.0,-4.3,86.39,0.0,0.0,0.0,26.3,14.4,260.0,1015.0,96.7,0.0,0.0,0.0,False,False,False,True,False,True,False,False,2024,1,0,6,Kharkiv,Europe/Kiev,2024-01-01,07:33:45,15:43:12,06:00:00,Харківська,0,0.0,0.0,0.0,1.0,1.0,16.0,0,1,4.0,0.0,5
103671,2024-12-04 03:00:00,5,48.0020,37.8145,-0.1,-1.4,91.2,0.000,0.0,0.00,0.0,0.0,27.0,12.2,90.3,1025.6,95.8,23.3,1.9,1.0,0.11,-0.3,-3.6,93.64,0.0,0.0,0.0,18.0,9.7,79.9,1025.0,95.4,0.0,0.0,0.0,False,True,False,False,False,True,False,False,2024,12,2,3,Donetsk,Europe/Kiev,2024-12-04,07:01:32,15:36:31,03:00:00,Донецька,0,0.0,0.0,1.0,1.0,0.0,12.0,0,1,11.0,0.0,2
177549,2024-04-20 18:00:00,8,47.8289,35.1626,12.4,4.9,62.2,1.300,100.0,25.00,0.0,0.0,44.3,28.8,56.2,1011.9,52.8,198.3,17.2,7.0,0.38,16.0,16.0,51.11,0.0,0.0,0.0,44.3,23.4,62.4,1008.0,89.9,96.5,0.3,1.0,False,False,True,False,False,True,False,False,2024,4,5,18,Zaporozhye,Europe/Zaporozhye,2024-04-20,05:40:22,19:37:02,18:00:00,Запорізька,0,0.0,0.0,0.0,1.0,1.0,12.0,1,0,6.0,2.0,1
345445,2022-05-04 05:00:00,16,49.5879,34.5517,13.5,4.5,55.7,0.200,100.0,8.33,0.0,0.0,34.9,16.6,261.6,1013.0,65.2,196.0,16.9,8.0,0.10,7.8,6.6,70.15,0.0,0.0,0.0,14.8,7.2,201.1,1013.0,74.8,0.0,0.1,0.0,False,False,True,False,False,True,False,False,2022,5,2,5,Poltava,Europe/Kiev,2022-05-04,05:14:36,20:03:37,05:00:00,Полтавська,0,0.0,0.0,0.0,1.0,0.0,9.0,0,1,0.0,0.0,3
524998,2024-09-20 10:00:00,22,49.4168,26.9743,14.4,5.5,58.4,0.000,0.0,0.00,0.0,0.0,28.4,14.4,37.2,1027.0,16.4,191.9,16.6,6.0,0.58,10.7,10.7,68.31,0.0,0.0,0.0,20.5,9.7,43.1,1028.0,0.0,348.3,1.3,3.0,True,False,False,False,True,False,False,False,2024,9,4,10,Khmelnytskyi,Europe/Kiev,2024-09-20,06:56:03,19:13:57,10:00:00,Хмельницька,0,0.0,0.0,0.0,1.0,0.0,6.0,0,0,8.0,0.0,3
84892,2022-10-13 14:00:00,5,48.0020,37.8145,8.2,3.0,71.4,0.000,0.0,0.00,0.0,0.0,28.8,13.3,321.4,1023.3,39.2,133.9,11.7,5.0,0.57,12.9,12.9,54.32,0.0,0.0,0.0,26.6,12.2,330.9,1022.0,55.6,497.0,1.8,5.0,False,True,False,False,False,True,False,False,2022,10,3,14,Donetsk,Europe/Kiev,2022-10-13,06:44:41,17:44:36,14:00:00,Донецька,0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,4.0,2.0,24
434940,2023-07-01 14:00:00,19,49.5527,25.5889,21.3,15.7,72.0,2.000,100.0,4.17,0.0,0.0,35.3,14.4,248.3,1007.9,79.7,250.6,21.6,8.0,0.43,25.8,25.8,56.13,0.0,0.0,0.0,34.9,8.3,255.3,1008.0,76.7,760.6,2.7,8.0,False,False,True,False,False,True,False,False,2023,7,5,14,Ternopil,Europe/Kiev,2023-07-01,05:14:43,21:28:01,14:00:00,Тернопільська,0,0.0,0.0,0.0,0.0,0.0,0.0,1,0,2.0,0.0,177
511230,2023-02-24 16:00:00,22,49.4168,26.9743,2.6,0.1,83.9,0.100,100.0,4.17,0.0,0.1,40.0,25.2,183.5,1010.4,94.2,86.2,7.5,4.0,0.14,6.1,3.1,76.61,0.1,100.0,0.0,32.0,14.4,186.4,1007.0,99.6,128.4,0.5,1.0,False,False,True,False,False,False,True,False,2023,2,4,16,Khmelnytskyi,Europe/Kiev,2023-02-24,07:05:27,17:46:07,16:00:00,Хмельницька,0,0.0,0.0,0.0,0.0,0.0,0.0,0,0,10.0,2.0,52
517496,2023-11-12 19:00:00,22,49.4168,26.9743,5.6,3.8,88.4,0.100,100.0,4.17,0.0,0.0,50.0,28.8,288.5,1001.6,96.3,18.5,1.6,1.0,0.97,5.9,1.8,84.57,0.0,0.0,0.0,42.5,23.0,282.7,1007.0,100.0,0.0,0.0,0.0,False,False,True,False,False,True,False,False,2023,11,6,19,Khmelnytskyi,Europe/Kiev,2023-11-12,07:17:30,16:34:20,19:00:00,Хмельницька,0,0.0,0.0,0.0,0.0,0.0,0.0,1,0,1.0,0.0,27
353439,2023-04-02 08:00:00,16,49.5879,34.5517,8.4,2.6,68.6,0.900,100.0,12.50,0.0,0.0,42.8,21.6,136.8,1009.5,99.1,104.3,8.7,4.0,0.38,6.9,3.9,72.51,0.0,0.0,0.0,32.4,15.8,137.6,1009.0,100.0,63.9,0.2,1.0,False,False,True,False,False,True,False,False,2023,4,6,8,Poltava,Europe/Kiev,2023-04-02,06:17:40,19:14:17,08:00:00,Полтавська,0,0.0,0.0,0.0,0.0,0.0,1.0,1,0,0.0,0.0,3
275995,2023-06-20 03:00:00,13,49.8444,24.0254,19.1,14.6,78.2,0.200,100.0,8.33,0.0,0.0,20.2,8.3,288.1,1017.2,58.7,255.6,21.9,7.0,0.07,11.6,11.6,100.00,0.0,0.0,0.0,4.3,0.0,243.9,1017.9,43.4,0.0,0.0,0.0,False,False,True,False,False,True,False,False,2023,6,1,3,Lviv,Europe/Kiev,2023-06-20,05:15:13,21:35:45,03:00:00,Львівська,0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,16.0,0.0,86
587923,2022-11-06 14:00:00,25,51.4937,31.2944,3.1,0.9,86.1,0.500,100.0,16.67,0.0,0.0,32.4,17.3,149.8,1025.9,99.1,43.0,3.6,2.0,0.39,4.5,0.7,80.87,0.0,0.0,0.0,31.0,17.3,162.7,1027.0,100.0,116.0,0.4,1.0,False,False,True,False,False,True,False,False,2022,11,6,14,Chernihiv,Europe/Kiev,2022-11-06,06:56:48,16:19:23,14:00:00,Чернігівська,0,0.0,0.0,0.0,0.0,0.0,0.0,1,0,0.0,0.0,27

In [13]:
df_isw_matrix.sample(10)

,date,isw_topic_0,isw_topic_1,isw_topic_2,isw_topic_3,isw_topic_4,isw_topic_5,isw_topic_6,isw_topic_7,isw_topic_8,isw_topic_9,isw_topic_10,isw_topic_11,isw_topic_12,isw_topic_13,isw_topic_14,isw_topic_15,isw_topic_16,isw_topic_17,isw_topic_18,isw_topic_19,isw_topic_20,isw_topic_21,isw_topic_22,isw_topic_23,isw_topic_24,isw_topic_25,isw_topic_26,isw_topic_27,isw_topic_28,isw_topic_29,isw_topic_30,isw_topic_31,isw_topic_32,isw_topic_33,isw_topic_34,isw_topic_35,isw_topic_36,isw_topic_37,isw_topic_38,isw_topic_39,isw_topic_40,isw_topic_41,isw_topic_42,isw_topic_43,isw_topic_44,isw_topic_45,isw_topic_46,isw_topic_47,isw_topic_48,isw_topic_49,isw_topic_50,isw_topic_51,isw_topic_52,isw_topic_53,isw_topic_54,isw_topic_55,isw_topic_56,isw_topic_57,isw_topic_58,isw_topic_59,isw_topic_60,isw_topic_61,isw_topic_62,isw_topic_63,isw_topic_64,isw_topic_65,isw_topic_66,isw_topic_67,isw_topic_68,isw_topic_69,isw_topic_70,isw_topic_71,isw_topic_72,isw_topic_73,isw_topic_74,isw_topic_75,isw_topic_76,isw_topic_77,isw_topic_78,isw_topic_79,isw_topic_80,isw_topic_81,isw_topic_82,isw_topic_83,isw_topic_84,isw_topic_85,isw_topic_86,isw_topic_87,isw_topic_88,isw_topic_89,isw_topic_90,isw_topic_91,isw_topic_92,isw_topic_93,isw_topic_94,isw_topic_95,isw_topic_96,isw_topic_97,isw_topic_98,isw_topic_99,isw_topic_100,isw_topic_101,isw_topic_102,isw_topic_103,isw_topic_104,isw_topic_105,isw_topic_106,isw_topic_107,isw_topic_108,isw_topic_109,isw_topic_110,isw_topic_111,isw_topic_112,isw_topic_113,isw_topic_114,isw_topic_115,isw_topic_116,isw_topic_117,isw_topic_118,isw_topic_119,isw_topic_120,isw_topic_121,isw_topic_122,isw_topic_123,isw_topic_124,isw_topic_125,isw_topic_126,isw_topic_127,isw_topic_128,isw_topic_129,isw_topic_130,isw_topic_131,isw_topic_132,isw_topic_133,isw_topic_134,isw_topic_135,isw_topic_136,isw_topic_137,isw_topic_138,isw_topic_139,isw_topic_140,isw_topic_141,isw_topic_142,isw_topic_143,isw_topic_144,isw_topic_145,isw_topic_146,isw_topic_147,isw_topic_148,isw_topic_149
165,2022-08-07,0.704463,-0.223520,0.217479,-0.064640,-0.076640,0.113478,-0.001755,0.068555,0.155479,-0.129257,0.047586,-0.005814,-0.029551,-0.163066,-0.092632,0.078703,-0.084993,0.042595,-0.109730,-0.040833,-0.022201,0.070454,0.002449,-0.139510,0.077842,-0.050667,-0.071332,-0.033498,-0.007079,-0.063468,0.018467,0.032779,-0.021615,-0.022973,0.000698,0.010115,0.004603,0.014994,-0.032008,-0.020954,0.007831,0.000542,0.033269,0.000414,0.047826,-0.028002,-0.027318,0.030428,0.012277,-0.054936,0.014533,0.047379,0.003866,0.000253,-0.004247,-0.034601,0.004392,-0.021009,0.002891,0.015253,-0.032777,0.003372,-0.019544,0.001574,0.045949,-0.011345,-0.008872,-0.016711,-0.043395,0.008829,0.007191,-0.041674,-0.009121,-0.003429,-0.030518,0.024193,-0.042378,0.039976,-0.018245,-0.003833,-0.017614,-0.008889,-0.054812,0.018619,0.000525,0.027568,-0.001807,-0.011538,-0.027853,0.036587,0.020848,-0.034160,0.008828,-0.022065,-0.018241,0.003424,-0.006993,-0.007278,0.041904,0.004164,0.026395,-0.001777,0.024665,0.010205,0.021680,-0.037459,-0.018406,-0.033702,0.010960,0.031496,0.018253,0.030395,0.011274,-0.014571,-0.018441,0.023158,-0.011148,-0.017726,0.021447,-0.010866,-0.007156,-0.005360,0.020055,-0.010297,-0.004697,0.028017,0.008439,-0.001740,0.016943,0.027491,-0.010272,0.012294,-0.054201,-0.025263,-0.019919,0.021211,-0.021132,-0.034642,-0.020175,0.013086,0.019968,-0.027974,-0.003742,-0.035248,0.012605,-0.006451,0.014536,-0.035769,0.005223,-0.040830
474,2023-06-15,0.810533,-0.199448,0.022822,-0.067516,-0.089837,0.080004,0.032868,-0.023151,-0.074613,0.078943,-0.017435,0.229366,-0.060342,0.068703,0.001954,-0.126380,-0.090490,0.059556,0.031597,0.058231,0.019373,0.020109,0.000108,-0.026535,-0.041180,-0.076606,-0.039198,0.012435,0.030682,0.024514,-0.003271,-0.003149,0.016733,0.027025,0.028908,0.005084,-0.031863,-0.012771,-0.019409,-0.006814,-0.017268,-0.050022,-0.008876,-0.024673,0.062032,-0.013703,0.038274,0.004608,0.001375,0.044383,0.002159,0.017072,-0.026321,-0.020086,0.003281,0.027738,0.029937,0.028155,-0.038356,0.013348,0.049159,0.010045,-0.041175,0.014683,-0.013003,-0.035480,-0.018952,0.002764,-0.043683,-0.017869,-0.016586,-0.018022,-0.004274,0.004277,0.008083,0.005801,-0.017740,-0.015020,0.001087,0.025460,0.013896,0.001513,-0.001293,-0.006596,0.005469,-0.008097,0.029983,0.013183,0.011908,-0.003278,0.003760,0.009252,-0.020770,-0.017116,0.009764,-0.000195,0.007263,-0.009526,0.000781,-0.004334,-0.032238,0.014082,0.001602,-0.010125,-0.005481,0.015830,0.001390,-0.000164,-0.007190,-0.021810,-0.011074,-0.000960,0.006595,0.010073,-0.003868,0.001098,0.000300,-0.025902,-0.001679,-0.002726,-0.005428,0.010618,0.011914,0.016823,0.007831,0.002906,-0.012450,0.016090,0.016005,-0.006492,-0.001967,-0.001462,0.004447,0.019266,0.022537,0.003945,-0.017092,0.013424,0.017047,0.004890,-0.011783,0.003686,0.004675,-0.007546,0.017302,0.002864,0.028387,0.008757,-0.005009,0.008585
808,2024-05-17,0.865578,-0.012507,0.000173,0.060099,-0.044996,-0.006514,0.012328,-0.044896,0.041722,-0.043861,-0.017753,0.032950,0.018499,0.010682,0.043200,-0.004636,0.151570,0.086585,-0.017034,0.147593,0.025830,-0.081423,-0.046079,0.042316,-0.002536,-0.005481,-0.021573,-0.044339,-0.044626,0.039360,-0.022805,0.010434,-0.053094,0.051456,0.014292,0.005322,-0.013209,0.016001,0.026590,-0.044683,-0.010508,0.043423,-0.007881,-0.025435,-0.021101,-0.010086,-0.004313,0.000939,-0.017974,0.042516,-0.009919,-0.040480,-0.020818,0.049965,0.028642,-0.017991,0.051643,-0.020575,-0.077393,0.001620,-0.015602,0.003684,-0.003943,-0.061746,-0.070888,0.029194,-0.016634,0.007887,-0.003775,0.020962,0.001837,-0.020329,0.001382,0.013832,-0.028164,-0.004323,-0.003131,0.000681,-0.004097,0.009214,0.021941,-0.015677,0.016290,0.028036,-0.017239,-0.019214,0.030957,-0.000346,-0.036048,0.014134,0.031672,0.039955,0.002458,0.012979,0.034655,-0.016153,0.027927,-0.012264,0.000727,0.010069,0.013269,-0.003620,-0.006229,-0.036523,-0.033470,-0.021747,-0.024152,-0.024990,0.024982,0.015348,-0.000699,0.001650,-0.005168,0.014382,-0.014478,-0.017694,-0.015596,-0.031460,-0.014320,0.008328,-0.019396,0.022612,-0.021023,0.020705,0.004537,-0.005925,0.002445,0.018615,-0.011344,-0.000920,0.012612,-0.006888,0.022882,-0.000174,0.003554,0.018499,0.000891,-0.028000,-0.012816,-0.009952,-0.000294,0.016147,0.002052,0.009686,0.025761,0.004142,-0.023334,-0.014405,0.007958,-0.003729
1175,2025-05-23,0.795642,0.252889,0.047400,0.060681,-0.070844,0.018672,0.012368,-0.006796,-0.042717,0.038685,0.029723,0.037586,-0.052855,0.030890,0.113995,0.166076,0.159439,0.230696,0.026073,0.052372,-0.091660,0.015271,0.031458,0.005623,0.035523,0.045273,-0.007224,0.001223,0.041080,0.002226,0.044103,0.024673,-0.002551,-0.043124,-0.051572,-0.045199,0.018560,-0.019738,-0.059839,-0.004233,-0.025232,0.002476,-0.008869,-0.028723,-0.013137,-0.003879,-0.018517,0.034242,0.009571,0.029074,0.018423,-0.071197,-0.004299,-0.004741,0.011024,0.012773,0.003241,0.007170,0.038608,0.017992,-0.000715,-0.024413,0.002802,-0.025972,0.030971,-0.025089,-0.007980,-0.071506,0.003090,-0.048417,0.012896,-0.040319,0.035339,-0.000820,0.028589,-0.022168,-0.004920,0.007205,-0.017576,0.039084,-0.006257,0.026627,0.033085,-0.001502,0.015579,-0.011481,-0.014334,0.010027,-0.010027,-0.001745,0.023677,-0.021956,-0.013424,0.004257,-0.022900,0.019294,0.003232,0.031574,0.019660,0.026440,-0.013198,0.011026,-0.009160,-0.010128,0.002342,-0.020274,-0.007357,-0.003745,0.011324,0.020095,-0.015070,0.020432,0.020201,0.014837,-0.032682,0.010288,-0.000243,0.018008,0.010015,-0.001390,-0.009604,0.007552,0.014140,0.010608,-0.032694,-0.017471,0.006486,0.006783,-0.012627,-0.002343,-0.006854,-0.004885,0.005148,0.016168,0.010261,-0.004897,-0.001492,0.010410,-0.005717,-0.011406,0.023920,-0.006051,0.014166,0.001925,-0.003376,-0.041472,0.011488,-0.004763,0.018315,-0.000238
953,2024-10-10,0.801100,0.088167,-0.051510,-0.102172,-0.083927,-0.182445,-0.198593,-0.134963,-0.065516,-0.176778,-0.154452,-0.009452,-0.062440,-0.050888,0.060292,-0.006285,0.000765,-0.039699,-0.039067,0.055121,0.028953,-0.064276,0.038182,-0.017737,-0.017990,0.022045,-0.015341,-0.010748,0.021807,-0.049762,0.000085,0.037905,-0.012395,0.002655,-0.013203,-0.033888,-0.016761,0.037828,0.025364,0.031692,-0.030780,-0.027014,0.043531,0.015745,0.003122,-0.007766,-0.021836,-0.015325,-0.012288,-0.009433,-0.008976,0.010264,-0.025409,-0.039860,-0.018030,-0.016294,-0.037193,-0.036854,-0.003360,-0.012143,-0.025849,0.005039,0.031060,-0.010017,0.007156,0.001595,0.038637,-0.008956,-0.014692,-0.020740,-0.022396,-0.002562,0.013501,0.013342,0.003145,-0.019073,-0.004966,-0.023505,-0.024782,-0.002667,0.020330,0.010100,-0.008932,0.021996,0.004709,0.025501,-0.004232,-0.006975,0.000799,-0.004759,0.002740,0.053597,0.006400,-0.001546,-0.006682,-0.028823,0.004041,-0.000009,-0.012971,-0.010535,0.009126,-0.036662,0.011592,-0.012508,0.010895,0.016229,0.018630,-0.010877,-0.017143,-0.046795,0.003526,-0.002585,-0.010332,0.009664,-0.012475,-0.025899,-0.015068,-0.003575,-0.017999,0.019312,0.004594,0.041374,0.014991,-0.005675,0.001482,-0.011207,0.007131,-0.018873,0.000003,-0.025888,-0.002184,0.010818,0.001191,-0.021998,-0.019512,0.010761,-0.005301,-0.005263,0.037325,0.017664,0.003640,-0.011051,0.026766,-0.000274,0.005041,-0.001151,0.014904,-0.009576,0.007589,0.003641
785,2024-04-24,0.750535,-0.039913,-0.165240,0.215387,-0.051086,-0.084001,-0.022609,-0.107049,-0.057095,-0.075973,0.199270,-0.056485,0.040673,-0.013284,-0.113588,-0.082497,-0.024027,-0.017412,-0.066069,0.074575,-0.006970,0.008145,-0.014860,0.021133,0.063428,0.003703,0.019658,0.025906,-0.083498,0.049622,-0.034259,0.080931,-0.042933,-0.013743,0.017140,0.059271,0.059810,-0.087028,0.041917,-0.004461,-0.013696,0.063697,0.055237,-0.006545,-0.011477,0.003739,-0.041012,-0.056698,-0.034618,-0.024236,-0.043350,-0.034938,-0.018176,0.005681,-0.018035,0.021017,-0.041693,-0.012078,0.029344,-0.003017,0.087352,-0.001312,-0.047256,0.071944,0.030000,0.033219,0.008668,0.030769,-0.028726,-0.013252,0.005430,0.024331,0.095917,0.010137,-0.015272,-0.017139,0.073539,-0.049271,0.012110,0.008791,-0.014679,0.018400,0.008359,-0.013723,-0.039594,0.033819,-0.009732,0.000738,0.013670,-0.043137,-0.001747,-0.059263,0.029348,0.011279,-0.004018,-0.046413,0.004054,-0.015271,0.005707,0.027699,0.050593,0.024892,-0.011660,-0.025787,0.047166,0.000203,0.028173,-0.038748,-0.001735,0.013132,-0.003934,-0.013289,-0.027173,-0.010775,0.002755,-0.007022,-0.011128,0.014749,0.001309,0.016710,0.013486,0.015313,0.030853,-0.027954,0.006406,0.016549,-0.030718,0.001442,-0.001932,0.004277,-0.022055,0.021045,0.034287,-0.011886,0.071613,-0.001675,0.027247,-0.004797,0.012427,0.015227,0.007712,0.017387,0.026644,-0.040382,0.008838,-0.010730,0.015323,0.023258,-0.004474,-0.013093
1252,2025-08-08,0.749001,0.250064,0.126926,0.004545,-0.108641,0.081016,-0.000009,0.134338,0.061879,-0.038984,0.097253,-0.014112,-0.082886,-0.119698,-0.066783,0.084416,0.027821,-0.006749,0.071911,-0.066521,0.034057,-0.002010,-0.079232,-0.040972,-0.037309,0.026774,0.042655,-0.050336,-0.017905,0.036184,-0.098536,-0.022036,-0.033087,0.049679,-0.056172,-0.021011,-0.066606,0.026875,0.011962,0.073020,0.008001,-0.009136,0.010105,0.007304,0.010934,-0.043560,-0.042221,-0.038414,-0.053729,0.033723,0.022015,0.023908,0.026388,-0.020281,-0.009551,0.048303,0.023519,-0.064128,-0.016420,0.013269,0.037580,0.031313,0.045570,0.018168,0.058914,-0.001102,-0.027933,-0.028166,0.003298,0.012839,0.042399,0.004261,-0.038935,0.012165,0.009557,0.036904,-0.029564,0.047025,-0.029281,0.031508,0.017348,0.027618,-0.057079,0.013688,-0.004139,0.042238,-0.025919,0.011743,0.015740,-0.034644,0.008920,0.001951,0.005648,0.012590,0.060539,-0.053425,-0.030651,0.006778,0.005836,-0.005254,-0.041529,0.053590,-0.018813,0.028581,-0.005970,0.020797,0.023196,-0.056349,-0.082966,0.014312,0.001229,-0.069972,-0.013480,0.002586,0.035816,0.007389,0.061720,0.020130,0.056012,0.013153,-0.015391,0.005494,0.028220,-0.017320,0.004844,-0.034058,-0.017400,0.032001,-0.003565,0.003401,0.022323,0.006339,-0.008930,-0.006208,0.007875,0.066328,0.004402,-0.003993,0.015399,-0.006968,-0.012119,-0.060964,-0.036923,-0.019171,-0.018363,0.024968,0.030686,-0.049424,0.013249,0.010558
30,2022-03-25,0.654775,-0.174111,0.292342,0.194825,0.102245,-0.153423,-0.071405,0.146295,0.088441,0.068738,-0.146196,-0.025090,-0.063012,0.075078,-0.038158,-0.123965,0.027142,-0.093032,0.179389,0.082778,-0.011046,0.039100,0.063068,-0.047679,0.069094,-0.006411,0.054217,0.003224,-0.018998,-0.013975,0.093441,0.019499,-0.022875,0.056670,0.030250,-0.049167,0.013839,-0.041666,-0.032376,-0.025718,-0.020023,-0.039463,0.023803,0.017393,0.011027,-0.006907,0.010259,-0.001857,-0.006971,0.000264,-0.004210,-0.052853,0.028702,-0.030029,-0.062560,-0.032674,-0.025933,-0.005557,-0.000393,-0.041446,-0.018233,0.008125,-0.014559,-0.022276,-0.007209,-0.014794,-0.003915,-0.000058,0.031565,-0.001659,0.022062,0.062853,-0.029950,0.012009,-0.008388,0.000541,-0.037655,-0.015582,0.022239,0.051986,-0.002545,-0.005952,-0.049488,-0.057107,-0.037701,0.003516,0.006122,-0.014748,0.008128,0.014362,-0.022202,-0.021689,0.010416,-0.035115,-0.005675,0.023627,0.011328,0.044046,0.012036,-0.013037,0.013513,-0.000291,0.015068,0.065085,0.009298,0.023519,0.021983,-0.011265,-0.017275,-0.002366,0.011296,-0.022986,0.005338,0.020499,-0.001232,-0.039885,-0.035749,0.029492,0.000047,0.006374,-0.005379,-0.003064,-0.043545,-0.004256,-0.011474,0.005912,0.023656,0.029667,-0.004364,0.004096,-0.011101,0.016551,-0.024786,0.018463,0.037096,0.030544,0.028704,-0.019913,-0.018543,0.000254,0.015523,-0.041838,0.010369,0.005125,-0.004531,-0.022019,-0.008533,-0.011516,0.007411,0.010178
226,2022-10-07,0.773741,-0.217762,0.000045,-0.171250,0.006793,-0.097477,-0.132658,-0.046756,-0.109732,-0.072881,-0.070263,-0.007836,-0.029268,-0.077931,-0.042421,0.168413,-0.100942,-0.000857,0.064515,0.052352,0.007833,0.066916,-0.026941,0.100282,0.027192,0.064845,-0.030678,-0.045793,-0.050260,0.049828,0.029709,-0.037997,-0.077153,-0.024365,0.032879,-0.007899,0.015385,-0.005172,-0.016583,0.035365,0.002368,-0.032119,-0.047177,-0.035545,-0.003596,0.037212,-0.015528,0.023517,-0.060349,0.008216,0.005723,0.029332,-0.010346,-0.000987,0.025957,0.033397,0.014379,-0.013982,-0.015369,0.014901,-0.054825,0.024000,0.013978,0.005131,-0.002371,-0.023887,-0.019629,0.007375,-0.013199,-0.011726,0.041228,-0.026769,0.010890,-0.010903,0.021367,0.058860,0.012673,0.002575,-0.027535,-0.003493,-0.010490,-0.019654,-0.002879,0.018270,-0.006768,0.019021,-0.005958,-0.005147,-0.037033,0.010498,0.032554,-0.012187,-0.014718,0.026797,-0.008183,-0.012208,0.024725,-0.006424,-0.007536,-0.002212,-0.009679,-0.004562,-0.012066,0.025785,-0.007316,0.017498,0.015480,-0.028076,0.010246,0.012088,-0.017468,0.007055,-0.005598,0.015237,-0.021561,0.000288,-0.001242,0.004124,-0.021388,0.005382,-0.051641,0.001671,0.015026,0.015135,-0.005163,-0.007524,0.006293,-0.000328,0.001197,0.020066,0.015216,0.033155,0.009313,0.009055,0.046383,-0.007160,-0.013793,0.016460,-0.004733,0.006313,-0.009570,-0.006203,-0.007766,-0.017782,-0.024371,-0.006259,-0.013081,-0.002669,0.010989,0.017989
916,2024-09-02,0.822465,0.038477,-0.105279,-0.005117,-0.106249,-0.001082,-0.021460,0.003912,0.096406,-0.133662,-0.001441,0.041217,0.166294,0.181653,0.037794,0.076332,-0.004432,-0.093349,-0.046549,-0.002016,-0.028116,-0.005033,0.006037,0.018224,0.023986,-0.056481,0.041986,-0.058133,-0.017856,-0.045065,0.003282,0.024688,0.008610,0.000723,0.012267,-0.009153,0.035944,0.066579,0.020166,0.012318,-0.005037,-0.040870,-0.005184,-0.008606,0.013610,-0.032082,-0.025316,0.003173,-0.059858,-0.034044,-0.013216,-0.021860,0.001925,-0.006473,-0.038014,0.011587,-0.046301,0.044209,-0.036784,0.010573,0.027464,-0.013588,0.013294,0.022836,0.049670,-0.033387,0.033541,-0.022234,-0.044649,0.008321,-0.019841,0.005093,-0.017629,0.016386,-0.016952,0.006783,-0.014624,-0.005514,-0.000187,-0.007388,-0.007242,-0.011318,-0.004663,0.018342,-0.001436,0.015138,0.022302,-0.013230,0.000328,-0.005262,0.023108,-0.012272,-0.005351,-0.015758,0.037759,0.010378,0.026104,0.003607,-0.006945,-0.016169,-0.002563,-0.019022,-0.017234,-0.015124,0.006685,-0.009730,-0.000231,0.018282,-0.004271,-0.011032,0.020197,0.016185,0.001126,0.027618,-0.036083,-0.012745,-0.035807,-0.003346,-0.012208,0.019326,-0.010544,-0.003527,0.007256,0.021327,-0.028216,-0.006746,0.011190,-0.001381,-0.030461,0.023534,-0.017194,-0.004468,0.003946,-0.015811,0.012910,-0.006952,0.023444,-0.022819,0.008752,0.019098,0.017636,-0.002936,-0.004125,-0.005930,0.009939,-0.007566,0.012147,-0.000646,-0.006580,-0.012356

In [14]:
#df_isw_matrix["date"] = pd.to_datetime(df_isw_matrix["date"]) + pd.Timedelta(days=1)    ТУТ ЗСУВ ІСВ НА + 1 ДЕНЬ
df_isw_matrix = df_isw_matrix.rename(columns={'date': 'day_datetime'})

In [15]:
df_final['day_datetime'] = pd.to_datetime(df_final['day_datetime']).dt.date
df_isw_matrix['day_datetime'] = pd.to_datetime(df_isw_matrix['day_datetime']).dt.date
df_isw_matrix.fillna(0, inplace=True)
df_isw_matrix.isna().sum()

day_datetime     0
isw_topic_0      0
isw_topic_1      0
isw_topic_2      0
isw_topic_3      0
                ..
isw_topic_145    0
isw_topic_146    0
isw_topic_147    0
isw_topic_148    0
isw_topic_149    0
Length: 151, dtype: int64

In [16]:
df_final = df_final.merge(df_isw_matrix, on="day_datetime", how="left")

In [17]:
df_final.head(10)

,datetime_hour,region_id,city_latitude,city_longitude,day_temp,day_dew,day_humidity,day_precip,day_precipprob,day_precipcover,day_snow,day_snowdepth,day_windgust,day_windspeed,day_winddir,day_pressure,day_cloudcover,day_solarradiation,day_solarenergy,day_uvindex,day_moonphase,hour_temp,hour_feelslike,hour_humidity,hour_precip,hour_precipprob,hour_snow,hour_windgust,hour_windspeed,hour_winddir,hour_pressure,hour_cloudcover,hour_solarradiation,hour_solarenergy,hour_uvindex,day_conditions_simple_Clear,day_conditions_simple_Cloudy,day_conditions_simple_Rain,day_conditions_simple_Snow,hour_conditions_simple_Clear,hour_conditions_simple_Cloudy,hour_conditions_simple_Rain,hour_conditions_simple_Snow,year,month,day_of_week,hour,city_name,city_timezone,day_datetime,day_sunrise,day_sunset,hour_datetime,region_key,alarm_active,alarm_minutes_in_hour,alarm_lag_1,alarm_lag_3,alarm_lag_6,alarm_lag_12,alarms_in_last_24h,is_weekend,is_night,total_active_alarms_lag1,neighbour_alarms,hours_since_last_alarm,isw_topic_0,isw_topic_1,isw_topic_2,isw_topic_3,isw_topic_4,isw_topic_5,isw_topic_6,isw_topic_7,isw_topic_8,isw_topic_9,isw_topic_10,isw_topic_11,isw_topic_12,isw_topic_13,isw_topic_14,isw_topic_15,isw_topic_16,isw_topic_17,isw_topic_18,isw_topic_19,isw_topic_20,isw_topic_21,isw_topic_22,isw_topic_23,isw_topic_24,isw_topic_25,isw_topic_26,isw_topic_27,isw_topic_28,isw_topic_29,isw_topic_30,isw_topic_31,isw_topic_32,isw_topic_33,isw_topic_34,isw_topic_35,isw_topic_36,isw_topic_37,isw_topic_38,isw_topic_39,isw_topic_40,isw_topic_41,isw_topic_42,isw_topic_43,isw_topic_44,isw_topic_45,isw_topic_46,isw_topic_47,isw_topic_48,isw_topic_49,isw_topic_50,isw_topic_51,isw_topic_52,isw_topic_53,isw_topic_54,isw_topic_55,isw_topic_56,isw_topic_57,isw_topic_58,isw_topic_59,isw_topic_60,isw_topic_61,isw_topic_62,isw_topic_63,isw_topic_64,isw_topic_65,isw_topic_66,isw_topic_67,isw_topic_68,isw_topic_69,isw_topic_70,isw_topic_71,isw_topic_72,isw_topic_73,isw_topic_74,isw_topic_75,isw_topic_76,isw_topic_77,isw_topic_78,isw_topic_79,isw_topic_80,isw_topic_81,isw_topic_82,isw_topic_83,isw_topic_84,isw_topic_85,isw_topic_86,isw_topic_87,isw_topic_88,isw_topic_89,isw_topic_90,isw_topic_91,isw_topic_92,isw_topic_93,isw_topic_94,isw_topic_95,isw_topic_96,isw_topic_97,isw_topic_98,isw_topic_99,isw_topic_100,isw_topic_101,isw_topic_102,isw_topic_103,isw_topic_104,isw_topic_105,isw_topic_106,isw_topic_107,isw_topic_108,isw_topic_109,isw_topic_110,isw_topic_111,isw_topic_112,isw_topic_113,isw_topic_114,isw_topic_115,isw_topic_116,isw_topic_117,isw_topic_118,isw_topic_119,isw_topic_120,isw_topic_121,isw_topic_122,isw_topic_123,isw_topic_124,isw_topic_125,isw_topic_126,isw_topic_127,isw_topic_128,isw_topic_129,isw_topic_130,isw_topic_131,isw_topic_132,isw_topic_133,isw_topic_134,isw_topic_135,isw_topic_136,isw_topic_137,isw_topic_138,isw_topic_139,isw_topic_140,isw_topic_141,isw_topic_142,isw_topic_143,isw_topic_144,isw_topic_145,isw_topic_146,isw_topic_147,isw_topic_148,isw_topic_149
0,2022-02-24 00:00:00,2,49.2336,28.4486,2.8,-0.3,80.5,0.3,100.0,4.17,0.0,0.0,27.7,10.8,312.0,1023.4,82.5,60.4,5.4,3.0,0.77,2.1,-0.5,91.76,0.0,0.0,0.0,16.6,8.6,279.6,1021.0,91.1,0.0,0.1,0.0,False,False,False,True,False,True,False,False,2022,2,3,0,Vinnytsia,Europe/Kiev,2022-02-24,06:58:49,17:40:52,00:00:00,Вінницька,0,0.0,0.0,0.0,0.0,0.0,NaN,0,1,NaN,NaN,1,0.648336,-0.079572,0.178041,0.061854,0.073453,-0.055809,-0.011311,0.047310,0.008354,0.006474,-0.047099,0.020496,0.050190,-0.038573,0.057228,-0.072471,0.045393,-0.116783,0.168249,0.167355,-0.025072,-0.073858,-0.097024,-0.146191,0.027983,0.082989,0.014423,0.058370,-0.033928,0.046265,0.006901,-0.049498,0.126117,-0.089039,-0.006767,-0.031686,-0.010346,0.025637,0.061278,0.162580,-0.028081,0.161291,-0.018217,-0.002657,0.038485,-0.000530,0.044413,0.107176,-0.050721,0.064279,-0.066677,0.016742,-0.050257,0.072549,-0.035201,-0.027279,0.017115,0.043631,0.024660,-0.025841,0.031320,-0.076959,-0.072986,-0.040465,0.003958,-0.022475,0.033208,-0.028056,-0.005499,-0.055998,-0.021882,-0.070462,0.018237,-0.031396,-0.074606,0.072951,0.039997,0.036423,-0.027152,-0.071900,0.026267,-0.046270,-0.017945,0.007933,-0.006203,-0.046099,0.032793,-0.069113,0.020403,0.030783,-0.003787,-0.000490,-0.022951,0.013498,0.009664,-0.007012,-0.016325,-0.005732,0.036069,-0.063906,0.033891,0.010560,-0.104517,-0.022069,0.054322,-0.005460,-0.029093,0.040991,-0.053018,-0.024017,0.050817,-0.003297,-0.020895,-0.053213,-0.028428,0.048231,-0.001221,0.001302,-0.044137,0.015528,-0.012792,-0.012009,-0.008211,0.031114,0.024982,0.003863,-0.032321,0.030920,-0.012845,0.070170,-0.004037,0.014003,0.005577,0.021611,-0.002889,0.034824,0.047164,0.050545,-0.017639,0.029014,-0.030378,-0.027056,0.011464,-0.039759,-0.043514,-0.025605,-0.022484,-0.036224,0.000566,0.005481
1,2022-02-24 00:00:00,2,49.2336,28.4486,2.8,-0.3,80.5,0.3,100.0,4.17,0.0,0.0,27.7,10.8,312.0,1023.4,82.5,60.4,5.4,3.0,0.77,2.1,-0.5,91.76,0.0,0.0,0.0,16.6,8.6,279.6,1021.0,91.1,0.0,0.1,0.0,False,False,False,True,False,True,False,False,2022,2,3,0,Vinnytsia,Europe/Kiev,2022-02-24,06:58:49,17:40:52,00:00:00,Вінницька,0,0.0,0.0,0.0,0.0,0.0,NaN,0,1,NaN,NaN,1,0.580161,-0.090608,-0.028388,0.146350,0.071072,-0.030284,-0.004583,0.087399,-0.038512,0.016613,-0.038599,0.049747,0.186305,-0.172198,-0.045515,0.050785,0.041889,-0.112849,0.193473,-0.010566,0.044308,-0.118300,0.007117,-0.135687,-0.009441,-0.039465,0.032843,0.080393,-0.035434,0.010352,-0.016680,-0.046252,0.085840,-0.123167,0.064510,-0.023735,-0.025637,-0.027863,0.032156,0.068641,0.027667,0.162729,0.039675,-0.016915,-0.008203,0.048024,0.073343,0.025782,-0.013935,-0.008775,-0.045265,0.008979,-0.100558,0.044074,0.018202,-0.037279,0.062349,0.008014,0.075917,-0.063409,0.015404,-0.091507,-0.079240,-0.033000,-0.019226,-0.103926,0.031514,0.043306,-0.012137,-0.010430,0.035901,-0.013437,-0.042046,-0.064986,0.002947,0.024326,0.085592,-0.008453,0.091087,-0.106852,0.038223,-0.061062,0.027905,0.056421,-0.030501,0.000050,0.051385,-0.087324,-0.024025,0.031626,-0.029461,0.015717,-0.047181,-0.005600,0.049867,0.084412,-0.055460,-0.036620,0.120475,-0.012080,0.006961,-0.079701,0.055655,0.004130,0.013250,0.002392,0.041937,0.028208,-0.037232,0.014886,-0.036905,0.000138,-0.018200,-0.010680,-0.067564,-0.001064,-0.044792,-0.014807,-0.031911,-0.023504,0.070783,0.027626,0.000418,0.043677,-0.030193,-0.034979,0.080093,0.035489,-0.004156,-0.008032,0.039826,-0.037380,0.011931,0.008267,0.000590,0.043862,0.023758,0.038714,0.066128,0.028168,-0.012153,0.005376,0.008085,-0.038933,0.003404,0.003281,-0.004149,-0.025392,0.010434,-0.017613
2,2022-02-24 01:00:00,2,49.2336,28.4486,2.8,-0.3,80.5,0.3,100.0,4.17,0.0,0.0,27.7,10.8,312.0,1023.4,82.5,60.4,5.4,3.0,0.77,2.1,-0.4,89.80,0.0,0.0,0.0,16.6,8.3,289.2,1021.0,97.9,0.0,0.1,0.0,False,False,False,True,False,True,False,False,2022,2,3,1,Vinnytsia,Europe/Kiev,2022-02-24,06:58:49,17:40:52,01:00:00,Вінницька,0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0.0,0.0,2,0.648336,-0.079572,0.178041,0.061854,0.073453,-0.055809,-0.011311,0.047310,0.008354,0.006474,-0.047099,0.020496,0.050190,-0.038573,0.057228,-0.072471,0.045393,-0.116783,0.168249,0.167355,-0.025072,-0.073858,-0.097024,-0.146191,0.027983,0.082989,0.014423,0.058370,-0.033928,0.046265,0.006901,-0.049498,0.126117,-0.089039,-0.006767,-0.031686,-0.010346,0.025637,0.061278,0.162580,-0.028081,0.161291,-0.018217,-0.002657,0.038485,-0.000530,0.044413,0.107176,-0.050721,0.064279,-0.066677,0.016742,-0.050257,0.072549,-0.035201,-0.027279,0.017115,0.043631,0.024660,-0.025841,0.031320,-0.076959,-0.072986,-0.040465,0.003958,-0.022475,0.033208,-0.028056,-0.005499,-0.055998,-0.021882,-0.070462,0.018237,-0.031396,-0.074606,0.072951,0.039997,0.036423,-0.027152,-0.071900,0.026267,-0.046270,-0.017945,0.007933,-0.006203,-0.046099,0.032793,-0.069113,0.020403,0.030783,-0.003787,-0.000490,-0.022951,0.013498,0.009664,-0.007012,-0.016325,-0.005732,0.036069,-0.063906,0.033891,0.010560,-0.104517,-0.022069,0.054322,-0.005460,-0.029093,0.040991,-0.053018,-0.024017,0.050817,-0.003297,-0.020895,-0.053213,-0.028428,0.048231,-0.001221,0.001302,-0.044137,0.015528,-0.012792,-0.012009,-0.008211,0.031114,0.024982,0.003863,-0.032321,0.030920,-0.012845,0.070170,-0.004037,0.014003,0.005577,0.021611,-0.002889,0.034824,0.047164,0.050545,-0.017639,0.029014,-0.030378,-0.027056,0.011464,-0.039759,-0.043514,-0.025605,-0.022484,-0.036224,0.000566,0.005481
3,2022-02-24 01:00:00,2,49.2336,28.4486,2.8,-0.3,80.5,0.3,100.0,4.17,0.0,0.0,27.7,10.8,312.0,1023.4,82.5,60.4,5.4,3.0,0.77,2.1,-0.4,89.80,0.0,0.0,0.0,16.6,8.3,289.2,1021.0,97.9,0.0,0.1,0.0,False,False,False,True,False,True,False,False,2022,2,3,1,Vinnytsia,Europe/Kiev,2022-02-24,06:58:49,17:40:52,01:00:00,Вінницька,0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0.0,0.0,2,0.580161,-0.090608,-0.028388,0.146350,0.071072,-0.030284,-0.004583,0.087399,-0.038512,0.016613,-0.038599,0.049747,0.186305,-0.172198,-0.045515,0.050785,0.041889,-0.112849,0.193473,-0.010566,0.044308,-0.118300,0.007117,-0.135687,-0.009441,-0.039465,0.032843,0.080393,-0.035434,0.010352,-0.016680,-0.046252,0.085840,-0.123167,0.064510,-0.023735,-0.025637,-0.027863,0.032156,0.068641,0.027667,0.162729,0.039675,-0.016915,-0.008203,0.048024,0.073343,0.025782,-0.013935,-0.008775,-0.045265,0.008979,-0.100558,0.044074,0.018202,-0.037279,0.062349,0.008014,0.075917,-0.063409,0.015404,-0.091507,-0.079240,-0.033000,-0.019226,-0.103926,0.031514,0.043306,-0.012137,-0.010430,0.035901,-0.013437,-0.042046,-0.064986,0.002947,0.024326,0.085592,-0.008453,0.091087,-0.106852,0.038223,-0.061062,0.027905,0.056421,-0.030501,0.000050,0.051385,-0.087324,-0.024025,0.031626,-0.029461,0.015717,-0.047181,-0.005600,0.049867,0.084412,-0.055460,-0.036620,0.120475,-0.012080,0.006961,-0.079701,0.055655,0.004130,0.013250,0.002392,0.041937,0.028208,-0.037232,0.014886,-0.036905,0.000138,-0.018200,-0.010680,-0.067564,-0.001064,-0.044792,-0.014807,-0.031911,-0.023504,0.070783,0.027626,0.000418,0.043677,-0.030193,-0.034979,0.080093,0.035489,-0.004156,-0.008032,0.039826,-0.037380,0.011931,0.008267,0.000590,0.043862,0.023758,0.038714,0.066128,0.028168,-0.012153,0.005376,0.008085,-0.038933,0.003404,0.003281,-0.004149,-0.025392,0.010434,-0.017613
4,2022-02-24 02:00:00,2,49.2336,28.4486,2.8,-0.3,80.5,0.3,100.0,4.17,0.0,0.0,27.7,10.8,312.0,1023.4,82.5,60.4,5.4,3.0,0.77,2.0,-0.3,90.44,0.0,0.0,0.0,27.7,7.6,287.6,1021.0,98.2,0.0,0.1,0.0,False,False,False,True,False,True,False,False,2022,2,3,2,Vinnytsia,Europe/Kiev,2022-02-24,06:58:49,17:40:52,02:00:00,Вінницька,0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0.0,0.0,3,0.648336,-0.079572,0.178041,0.061854,0.073453,-0.055809,-0.011311,0.047310,0.008354,0.006474,-0.047099,0.020496,0.050190,-0.038573,0.057228,-0.072471,0.045393,-0.116783,0.168249,0.167355,-0.025072,-0.073858,-0.097024,-0.146191,0.027983,0.082989,0.014423,0.058370,-0.033928,0.046265,0.006901,-0.049498,0.126117,-0.089039,-0.006767,-0.031686,-0.010346,0.025637,0.061278,0.162580,-0.028081,0.161291,-0.018217,-0.002657,0.038485,-0.000530,0.044413,0.107176,-0.050721,0.064279,-0.066677,0.016742,-0.050257,0.072549,-0.035201,-0.027279,0.017115,0.043631,0.024660,-0.025841,0.031320,-0.076959,-0.072986,-0.040465,0.003958,-0.022475,0.033208,-0.028056,-0.005499,-0.055998,-0.021882,-0.070462,0.018237,-0.031396,-0.074606,0.072951,0.039997,0.036423,-0.027152,-0.071900,0.026267,-0.046270,-0.017945,0.007933,-0.006203,-0.046099,0.032793,-0.069113,0.020403,0.030783,-0.003787,-0.000490,-0.022951,0.013498,0.009664,-0.007012,-0.016325,-0.005732,0.036069,-0.063906,0.033891,0.010560,-0.104517,-0.022069,0.054322,-0.005460,-0.029093,0.040991,-0.053018,-0.024017,0.050817,-0.003297,-0.020895,-0.053213,-0.028428,0.048231,-0.001221,0.001302,-0.044137,0.015528,-0.012792,-0.012009,-0.008211,0.031114,0.024982,0.003863,-0.032321,0.030920,-0.012845,0.070170,-0.004037,0.014003,0.005577,0.021611,-0.002889,0.034824,0.047164,0.050545,-0.017639,0.029014,-0.030378,-0.027056,0.011464,-0.039759,-0.043514,-0.025605,-0.022484,-0.036224,0.000566,0.005481
5,2022-02-24 02:00:00,2,49.2336,28.4486,2.8,-0.3,80.5,0.3,100.0,4.17,0.0,0.0,27.7,10.8,312.0,1023.4,82.5,60.4,5.4,3.0,0.77,2.0,-0.3,90.44,0.0,0.0,0.0,27.7,7.6,287.6,1021.0,98.2,0.0,0.1,0.0,False,False,False,True,False,True,False,False,2022,2,3,2,Vinnytsia,Europe/Kiev,2022-02-24,06:58:49,17:40:52,02:00:00,Вінницька,0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0.0,0.0,3,0.580161,-0.090608,-0.028388,0.146350,0.071072,-0.030284,-0.004583,0.087399,-0.038512,0.016613,-0.038599,0.049747,0.186305,-0.172198,-0.045515,0.050785,0.041889,-0.112849,0.193473,-0.010566,0.044308,-0.118300,0.007117,-0.135687,-0.009441,-0.039465,0.032843,0.080393,-0.035434,0.010352,-0.016680,-0.046252,0.085840,-0.123167,0.064510,-0.023735,-0.025637,-0.027863,0.032156,0.068641,0.027667,0.162729,0.039675,-0.016915,-0.008203,0.048024,0.073343,0.025782,-0.013935,-0.008775,-0.045265,0.008979,-0.100558,0.044074,0.018202,-0.037279,0.062349,0.008014,0.075917,-0.063409,0.015404,-0.091507,-0.079240,-0.033000,-0.019226,-0.103926,0.031514,0.043306,-0.012137,-0.010430,0.035901,-0.013437,-0.042046,-0.064986,0.002947,0.024326,0.085592,-0.008453,0.091087,-0.106852,0.038223,-0.061062,0.027905,0.056421,-0.030501,0.000050,0.051385,-0.087324,-0.024025,0.031626,-0.029461,0.015717,-0.047181,-0.005600,0.049867,0.084412,-0.055460,-0.036620,0.120475,-0.012080,0.006961,-0.079701,0.055655,0.004130,0.013250,0.002392,0.041937,0.028208,-0.037232,0.014886,-0.036905,0.000138,-0.018200,-0.010680,-0.067564,-0.001064,-0.044792,-0.014807,-0.031911,-0.023504,0.070783,0.027626,0.000418,0.043677,-0.030193,-0.034979,0.080093,0.035489,-0.004156,-0.008032,0.039826,-0.037380,0.011931,0.008267,0.000590,0.043862,0.023758,0.038714,0.066128,0.028168,-0.012153,0.005376,0.008085,-0.038933,0.003404,0.003281,-0.004149,-0.025392,0.010434,-0.017613
6,2022-02-24 03:00:00,2,49.2336,28.4486,2.8,-0.3,80.5,0.3,100.0,4.17,0.0,0.0,27.7,10.8,312.0,1023.4,82.5,60.4,5.4,3.0,0.77,1.9,-0.3,91.75,0.0,0.0,0.0,15.1,7.2,288.9,1021.0,98.8,0.0,0.1,0.0,False,False,False,True,False,True,False,False,2022,2,3,3,Vinnytsia,Europe/Kiev,2022-02-24,06:58:49,17:40:52,03:00:00,Вінницька,0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0.0,0.0,4,0.648336,-0.079572,0.178041,0.061854,0.073453,-0.055809,-0.011311,0.047310,0.008354,0.006474,-0.047099,0.020496,0.050190,-0.038573,0.057228,-0.072471,0.045393,-0.116783,0.168249,0.167355,-0.025072,-0.073858,-0.097024,-0.146191,0.027983,0.082989,0.014423,0.058370,-0.033928,0.046265,0.006901,-0.049498,0.126117,-0.089039,-0.006767,-0.031686,-0.010346,0.025637,0.061278,0.162580,-0.028081,0.161291,-0.018217,-0.002657,0.038485,-0.000530,0.044413,0.107176,-0.050721,0.064279,-0.066677,0.016742,-0.050257,0.072549,-0.035201,-0.027279,0.017115,0.043631,0.024660,-0.025841,0.031320,-0.076959,-0.072986,-0.040465,0.003958,-0.022475,0.033208,-0.028056,-0.005499,-0.055998,-0.021882,-0.070462,0.018237,-0.031396,-0.074606,0.072951,0.039997,0.036423,-0.027152,-0.071900,0.026267,-0.046270,-0.017945,0.007933,-0.006203,-0.046099,0.032793,-0.069113,0.020403,0.030783,-0.003787,-0.000490,-0.022951,0.013498,0.009664,-0.007012,-0.016325,-0.005732,0.036069,-0.063906,0.033891,0.010560,-0.104517,-0.022069,0.054322,-0.005460,-0.029093,0.040991,-0.053018,-0.024017,0.050817,-0.003297,-0.020895,-0.053213,-0.028428,0.048231,-0.001221,0.001302,-0.044137,0.015528,-0.012792,-0.012009,-0.008211,0.031114,0.024982,0.003863,-0.032321,0.030920,-0.012845,0.070170,-0.004037,0.014003,0.005577,0.021611,-0.002889,0.034824,0.047164,0.050545,-0.017639,0.029014,-0.030378,-0.027056,0.011464,-0.039759,-0.043514,-0.025605,-0.022484,-0.036224,0.000566,0.005481
7,2022-02-24 03:00:00,2,49.2336,28.4486,2.8,-0.3,80.5,0.3,100.0,4.17,0.0,0.0,27.7,10.8,312.0,1023.4,82.5,60.4,5.4,3.0,0.77,1.9,-0.3,91.75,0.0,0.0,0.0,15.1,7.2,288.9,1021.0,98.8,0.0,0.1,0.0,False,False,False,True,False,True,False,False,2022,2,3,3,Vinnytsia,Europe/Kiev,2022-02-24,06:58:49,17:40:52,03:00:00,Вінницька,0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0.0,0.0,4,0.580161,-0.090608,-0.028388,0.146350,0.071072,-0.030284,-0.004583,0.087399,-0.038512,0.016613,-0.038599,0.049747,0.186305,-0.172198,-0.045515,0.050785,0.041889,-0.112849,0.193473,-0.010566,0.044308,-0.118300,0.007117,-0.135687,-0.009441,-0.039465,0.032843,0.080393,-0.035434,0.010352,-0.016680,-0.046252,0.085840,-0.123167,0.064510,-0.023735,-0.025637,-0.027863,0.032156,0.068641,0.027667,0.162729,0.039675,-0.016915,-0.008203,0.048024,0.073343,0.025782,-0.013935,-0.008775,-0.045265,0.008979,-0.100558,0.044074,0.018202,-0.037279,0.062349,0.008014,0.075917,-0.063409,0.015404,-0.091507,-0.079240,-0.033000,-0.019226,-0.103926,0.031514,0.043306,-0.012137,-0.010430,0.035901,-0.013437,-0.042046,-0.064986,0.002947,0.024326,0.085592,-0.008453,0.091087,-0.106852,0.038223,-0.061062,0.027905,0.056421,-0.030501,0.000050,0.051385,-0.087324,-0.024025,0.031626,-0.029461,0.015717,-0.047181,-0.005600,0.049867,0.084412,-0.055460,-0.036620,0.120475,-0.012080,0.006961,-0.079701,0.055655,0.004130,0.013250,0.002392,0.041937,0.028208,-0.037232,0.014886,-0.036905,0.000138,-0.018200,-0.010680,-0.067564,-0.001064,-0.044792,-0.014807,-0.031911,-0.023504,0.070783,0.027626,0.000418,0.043677,-0.030193,-0.034979,0.080093,0.035489,-0.004156,-0.008032,0.039826,-0.037380,0.011931,0.008267,0.000590,0.043862,0.023758,0.038714,0.066128,0.028168,-0.012153,0.005376,0.008085,-0.038933,0.003404,0.003281,-0.004149,-0.025392,0.010434,-0.017613
8,2022-02-24 04:00:00,2,49.2336,28.4486,2.8,-0.3,80.5,0.3,100.0,4.17,0.0,0.0,27.7,10.8,312.0,1023.4,82.5,60.4,5.4,3.0,0.77,1.8,-0.2,92.40,0.0,0.0,0.0,13.7,6.5,290.4,1021.0,100.0,0.0,0.1,0.0,False,False,False,True,False,True,False,False,2022,2,3,4,Vinnytsia,Europe/Kiev,2022-02-24,06:58:49,17:40:52,04:00:00,Вінницька,0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0.0,0.0,5,0.648336,-0.079572,0.178041,0.061854,0.073453,-0.055809,-0.011311,0.047310,0.008354,0.006474,-0.047099,0.020496,0.050190,-0.038573,0.057228,-0.072471,0.045393,-0.116783,0.168249,0.167355,-0.025072,-0.073858,-0.097024,-0.146191,0.027983,0.082989,0.014423,0.058370,-0.033928,0.046265,0.006901,-0.049498,0.126117,-0.089039,-0.006767,-0.031686,-0.010346,0.025637,0.061278,0.162580,-0.028081,0.161291,-0.018217,-0.002657,0.038485,-0.000530,0.044413,0.107176,-0.050721,0.064279,-0.066677,0.016742,-0.050257,0.072549,-0.035201,-0.027279,0.017115,0.043631,0.024660,-0.025841,0.031320,-0.076959,-0.072986,-0.040465,0.003958,-0.022475,0.033208,-0.028056,-0.005499,-0.055998,-0.021882,-0.070462,0.018237,-0.031396,-0.074606,0.072951,0.039997,0.036423,-0.027152,-0.071900,0.026267,-0.046270,-0.017945,0.007933,-0.006203,-0.046099,0.032793,-0.069113,0.020403,0.030783,-0.003787,-0.000490,-0.022951,0.013498,0.009664,-0.007012,-0.016325,-0.005732,0.036069,-0.063906,0.033891,0.010560,-0.104517,-0.022069,0.054322,-0.005460,-0.029093,0.040991,-0.053018,-0.024017,0.050817,-0.003297,-0.020895,-0.053213,-0.028428,0.048231,-0.001221,0.001302,-0.044137,0.015528,-0.012792,-0.012009,-0.008211,0.031114,0.024982,0.003863,-0.032321,0.030920,-0.012845,0.070170,-0.004037,0.014003,0.005577,0.021611,-0.002889,0.034824,0.047164,0.050545,-0.017639,0.029014,-0.030378,-0.027056,0.011464,-0.039759,-0.043514,-0.025605,-0.022484,-0.036224,0.000566,0.005481

In [18]:
df_final.isna().sum()

datetime_hour        0
region_id            0
city_latitude        0
city_longitude       0
day_temp             0
                  ...
isw_topic_145     5760
isw_topic_146     5760
isw_topic_147     5760
isw_topic_148     5760
isw_topic_149     5760
Length: 216, dtype: int64

In [19]:
df_final.fillna(0, inplace=True)

,datetime_hour,region_id,city_latitude,city_longitude,day_temp,day_dew,day_humidity,day_precip,day_precipprob,day_precipcover,day_snow,day_snowdepth,day_windgust,day_windspeed,day_winddir,day_pressure,day_cloudcover,day_solarradiation,day_solarenergy,day_uvindex,day_moonphase,hour_temp,hour_feelslike,hour_humidity,hour_precip,hour_precipprob,hour_snow,hour_windgust,hour_windspeed,hour_winddir,hour_pressure,hour_cloudcover,hour_solarradiation,hour_solarenergy,hour_uvindex,day_conditions_simple_Clear,day_conditions_simple_Cloudy,day_conditions_simple_Rain,day_conditions_simple_Snow,hour_conditions_simple_Clear,hour_conditions_simple_Cloudy,hour_conditions_simple_Rain,hour_conditions_simple_Snow,year,month,day_of_week,hour,city_name,city_timezone,day_datetime,day_sunrise,day_sunset,hour_datetime,region_key,alarm_active,alarm_minutes_in_hour,alarm_lag_1,alarm_lag_3,alarm_lag_6,alarm_lag_12,alarms_in_last_24h,is_weekend,is_night,total_active_alarms_lag1,neighbour_alarms,hours_since_last_alarm,isw_topic_0,isw_topic_1,isw_topic_2,isw_topic_3,isw_topic_4,isw_topic_5,isw_topic_6,isw_topic_7,isw_topic_8,isw_topic_9,isw_topic_10,isw_topic_11,isw_topic_12,isw_topic_13,isw_topic_14,isw_topic_15,isw_topic_16,isw_topic_17,isw_topic_18,isw_topic_19,isw_topic_20,isw_topic_21,isw_topic_22,isw_topic_23,isw_topic_24,isw_topic_25,isw_topic_26,isw_topic_27,isw_topic_28,isw_topic_29,isw_topic_30,isw_topic_31,isw_topic_32,isw_topic_33,isw_topic_34,isw_topic_35,isw_topic_36,isw_topic_37,isw_topic_38,isw_topic_39,isw_topic_40,isw_topic_41,isw_topic_42,isw_topic_43,isw_topic_44,isw_topic_45,isw_topic_46,isw_topic_47,isw_topic_48,isw_topic_49,isw_topic_50,isw_topic_51,isw_topic_52,isw_topic_53,isw_topic_54,isw_topic_55,isw_topic_56,isw_topic_57,isw_topic_58,isw_topic_59,isw_topic_60,isw_topic_61,isw_topic_62,isw_topic_63,isw_topic_64,isw_topic_65,isw_topic_66,isw_topic_67,isw_topic_68,isw_topic_69,isw_topic_70,isw_topic_71,isw_topic_72,isw_topic_73,isw_topic_74,isw_topic_75,isw_topic_76,isw_topic_77,isw_topic_78,isw_topic_79,isw_topic_80,isw_topic_81,isw_topic_82,isw_topic_83,isw_topic_84,isw_topic_85,isw_topic_86,isw_topic_87,isw_topic_88,isw_topic_89,isw_topic_90,isw_topic_91,isw_topic_92,isw_topic_93,isw_topic_94,isw_topic_95,isw_topic_96,isw_topic_97,isw_topic_98,isw_topic_99,isw_topic_100,isw_topic_101,isw_topic_102,isw_topic_103,isw_topic_104,isw_topic_105,isw_topic_106,isw_topic_107,isw_topic_108,isw_topic_109,isw_topic_110,isw_topic_111,isw_topic_112,isw_topic_113,isw_topic_114,isw_topic_115,isw_topic_116,isw_topic_117,isw_topic_118,isw_topic_119,isw_topic_120,isw_topic_121,isw_topic_122,isw_topic_123,isw_topic_124,isw_topic_125,isw_topic_126,isw_topic_127,isw_topic_128,isw_topic_129,isw_topic_130,isw_topic_131,isw_topic_132,isw_topic_133,isw_topic_134,isw_topic_135,isw_topic_136,isw_topic_137,isw_topic_138,isw_topic_139,isw_topic_140,isw_topic_141,isw_topic_142,isw_topic_143,isw_topic_144,isw_topic_145,isw_topic_146,isw_topic_147,isw_topic_148,isw_topic_149
0,2022-02-24 00:00:00,2,49.2336,28.4486,2.8,-0.3,80.5,0.3,100.0,4.17,0.0,0.0,27.7,10.8,312.0,1023.4,82.5,60.4,5.4,3.0,0.77,2.1,-0.5,91.76,0.0,0.0,0.0,16.6,8.6,279.6,1021.0,91.1,0.0,0.1,0.0,False,False,False,True,False,True,False,False,2022,2,3,0,Vinnytsia,Europe/Kiev,2022-02-24,06:58:49,17:40:52,00:00:00,Вінницька,0,0.000000,0.0,0.0,0.0,0.0,0.0,0,1,0.0,0.0,1,0.648336,-0.079572,0.178041,0.061854,0.073453,-0.055809,-0.011311,0.047310,0.008354,0.006474,-0.047099,0.020496,0.050190,-0.038573,0.057228,-0.072471,0.045393,-0.116783,0.168249,0.167355,-0.025072,-0.073858,-0.097024,-0.146191,0.027983,0.082989,0.014423,0.058370,-0.033928,0.046265,0.006901,-0.049498,0.126117,-0.089039,-0.006767,-0.031686,-0.010346,0.025637,0.061278,0.162580,-0.028081,0.161291,-0.018217,-0.002657,0.038485,-0.000530,0.044413,0.107176,-0.050721,0.064279,-0.066677,0.016742,-0.050257,0.072549,-0.035201,-0.027279,0.017115,0.043631,0.024660,-0.025841,0.031320,-0.076959,-0.072986,-0.040465,0.003958,-0.022475,0.033208,-0.028056,-0.005499,-0.055998,-0.021882,-0.070462,0.018237,-0.031396,-0.074606,0.072951,0.039997,0.036423,-0.027152,-0.071900,0.026267,-0.046270,-0.017945,0.007933,-0.006203,-0.046099,0.032793,-0.069113,0.020403,0.030783,-0.003787,-0.000490,-0.022951,0.013498,0.009664,-0.007012,-0.016325,-0.005732,0.036069,-0.063906,0.033891,0.010560,-0.104517,-0.022069,0.054322,-0.005460,-0.029093,0.040991,-0.053018,-0.024017,0.050817,-0.003297,-0.020895,-0.053213,-0.028428,0.048231,-0.001221,0.001302,-0.044137,0.015528,-0.012792,-0.012009,-0.008211,0.031114,0.024982,0.003863,-0.032321,0.030920,-0.012845,0.070170,-0.004037,0.014003,0.005577,0.021611,-0.002889,0.034824,0.047164,0.050545,-0.017639,0.029014,-0.030378,-0.027056,0.011464,-0.039759,-0.043514,-0.025605,-0.022484,-0.036224,0.000566,0.005481
1,2022-02-24 00:00:00,2,49.2336,28.4486,2.8,-0.3,80.5,0.3,100.0,4.17,0.0,0.0,27.7,10.8,312.0,1023.4,82.5,60.4,5.4,3.0,0.77,2.1,-0.5,91.76,0.0,0.0,0.0,16.6,8.6,279.6,1021.0,91.1,0.0,0.1,0.0,False,False,False,True,False,True,False,False,2022,2,3,0,Vinnytsia,Europe/Kiev,2022-02-24,06:58:49,17:40:52,00:00:00,Вінницька,0,0.000000,0.0,0.0,0.0,0.0,0.0,0,1,0.0,0.0,1,0.580161,-0.090608,-0.028388,0.146350,0.071072,-0.030284,-0.004583,0.087399,-0.038512,0.016613,-0.038599,0.049747,0.186305,-0.172198,-0.045515,0.050785,0.041889,-0.112849,0.193473,-0.010566,0.044308,-0.118300,0.007117,-0.135687,-0.009441,-0.039465,0.032843,0.080393,-0.035434,0.010352,-0.016680,-0.046252,0.085840,-0.123167,0.064510,-0.023735,-0.025637,-0.027863,0.032156,0.068641,0.027667,0.162729,0.039675,-0.016915,-0.008203,0.048024,0.073343,0.025782,-0.013935,-0.008775,-0.045265,0.008979,-0.100558,0.044074,0.018202,-0.037279,0.062349,0.008014,0.075917,-0.063409,0.015404,-0.091507,-0.079240,-0.033000,-0.019226,-0.103926,0.031514,0.043306,-0.012137,-0.010430,0.035901,-0.013437,-0.042046,-0.064986,0.002947,0.024326,0.085592,-0.008453,0.091087,-0.106852,0.038223,-0.061062,0.027905,0.056421,-0.030501,0.000050,0.051385,-0.087324,-0.024025,0.031626,-0.029461,0.015717,-0.047181,-0.005600,0.049867,0.084412,-0.055460,-0.036620,0.120475,-0.012080,0.006961,-0.079701,0.055655,0.004130,0.013250,0.002392,0.041937,0.028208,-0.037232,0.014886,-0.036905,0.000138,-0.018200,-0.010680,-0.067564,-0.001064,-0.044792,-0.014807,-0.031911,-0.023504,0.070783,0.027626,0.000418,0.043677,-0.030193,-0.034979,0.080093,0.035489,-0.004156,-0.008032,0.039826,-0.037380,0.011931,0.008267,0.000590,0.043862,0.023758,0.038714,0.066128,0.028168,-0.012153,0.005376,0.008085,-0.038933,0.003404,0.003281,-0.004149,-0.025392,0.010434,-0.017613
2,2022-02-24 01:00:00,2,49.2336,28.4486,2.8,-0.3,80.5,0.3,100.0,4.17,0.0,0.0,27.7,10.8,312.0,1023.4,82.5,60.4,5.4,3.0,0.77,2.1,-0.4,89.80,0.0,0.0,0.0,16.6,8.3,289.2,1021.0,97.9,0.0,0.1,0.0,False,False,False,True,False,True,False,False,2022,2,3,1,Vinnytsia,Europe/Kiev,2022-02-24,06:58:49,17:40:52,01:00:00,Вінницька,0,0.000000,0.0,0.0,0.0,0.0,0.0,0,1,0.0,0.0,2,0.648336,-0.079572,0.178041,0.061854,0.073453,-0.055809,-0.011311,0.047310,0.008354,0.006474,-0.047099,0.020496,0.050190,-0.038573,0.057228,-0.072471,0.045393,-0.116783,0.168249,0.167355,-0.025072,-0.073858,-0.097024,-0.146191,0.027983,0.082989,0.014423,0.058370,-0.033928,0.046265,0.006901,-0.049498,0.126117,-0.089039,-0.006767,-0.031686,-0.010346,0.025637,0.061278,0.162580,-0.028081,0.161291,-0.018217,-0.002657,0.038485,-0.000530,0.044413,0.107176,-0.050721,0.064279,-0.066677,0.016742,-0.050257,0.072549,-0.035201,-0.027279,0.017115,0.043631,0.024660,-0.025841,0.031320,-0.076959,-0.072986,-0.040465,0.003958,-0.022475,0.033208,-0.028056,-0.005499,-0.055998,-0.021882,-0.070462,0.018237,-0.031396,-0.074606,0.072951,0.039997,0.036423,-0.027152,-0.071900,0.026267,-0.046270,-0.017945,0.007933,-0.006203,-0.046099,0.032793,-0.069113,0.020403,0.030783,-0.003787,-0.000490,-0.022951,0.013498,0.009664,-0.007012,-0.016325,-0.005732,0.036069,-0.063906,0.033891,0.010560,-0.104517,-0.022069,0.054322,-0.005460,-0.029093,0.040991,-0.053018,-0.024017,0.050817,-0.003297,-0.020895,-0.053213,-0.028428,0.048231,-0.001221,0.001302,-0.044137,0.015528,-0.012792,-0.012009,-0.008211,0.031114,0.024982,0.003863,-0.032321,0.030920,-0.012845,0.070170,-0.004037,0.014003,0.005577,0.021611,-0.002889,0.034824,0.047164,0.050545,-0.017639,0.029014,-0.030378,-0.027056,0.011464,-0.039759,-0.043514,-0.025605,-0.022484,-0.036224,0.000566,0.005481
3,2022-02-24 01:00:00,2,49.2336,28.4486,2.8,-0.3,80.5,0.3,100.0,4.17,0.0,0.0,27.7,10.8,312.0,1023.4,82.5,60.4,5.4,3.0,0.77,2.1,-0.4,89.80,0.0,0.0,0.0,16.6,8.3,289.2,1021.0,97.9,0.0,0.1,0.0,False,False,False,True,False,True,False,False,2022,2,3,1,Vinnytsia,Europe/Kiev,2022-02-24,06:58:49,17:40:52,01:00:00,Вінницька,0,0.000000,0.0,0.0,0.0,0.0,0.0,0,1,0.0,0.0,2,0.580161,-0.090608,-0.028388,0.146350,0.071072,-0.030284,-0.004583,0.087399,-0.038512,0.016613,-0.038599,0.049747,0.186305,-0.172198,-0.045515,0.050785,0.041889,-0.112849,0.193473,-0.010566,0.044308,-0.118300,0.007117,-0.135687,-0.009441,-0.039465,0.032843,0.080393,-0.035434,0.010352,-0.016680,-0.046252,0.085840,-0.123167,0.064510,-0.023735,-0.025637,-0.027863,0.032156,0.068641,0.027667,0.162729,0.039675,-0.016915,-0.008203,0.048024,0.073343,0.025782,-0.013935,-0.008775,-0.045265,0.008979,-0.100558,0.044074,0.018202,-0.037279,0.062349,0.008014,0.075917,-0.063409,0.015404,-0.091507,-0.079240,-0.033000,-0.019226,-0.103926,0.031514,0.043306,-0.012137,-0.010430,0.035901,-0.013437,-0.042046,-0.064986,0.002947,0.024326,0.085592,-0.008453,0.091087,-0.106852,0.038223,-0.061062,0.027905,0.056421,-0.030501,0.000050,0.051385,-0.087324,-0.024025,0.031626,-0.029461,0.015717,-0.047181,-0.005600,0.049867,0.084412,-0.055460,-0.036620,0.120475,-0.012080,0.006961,-0.079701,0.055655,0.004130,0.013250,0.002392,0.041937,0.028208,-0.037232,0.014886,-0.036905,0.000138,-0.018200,-0.010680,-0.067564,-0.001064,-0.044792,-0.014807,-0.031911,-0.023504,0.070783,0.027626,0.000418,0.043677,-0.030193,-0.034979,0.080093,0.035489,-0.004156,-0.008032,0.039826,-0.037380,0.011931,0.008267,0.000590,0.043862,0.023758,0.038714,0.066128,0.028168,-0.012153,0.005376,0.008085,-0.038933,0.003404,0.003281,-0.004149,-0.025392,0.010434,-0.017613
4,2022-02-24 02:00:00,2,49.2336,28.4486,2.8,-0.3,80.5,0.3,100.0,4.17,0.0,0.0,27.7,10.8,312.0,1023.4,82.5,60.4,5.4,3.0,0.77,2.0,-0.3,90.44,0.0,0.0,0.0,27.7,7.6,287.6,1021.0,98.2,0.0,0.1,0.0,False,False,False,True,False,True,False,False,2022,2,3,2,Vinnytsia,Europe/Kiev,2022-02-24,06:58:49,17:40:52,02:00:00,Вінницька,0,0.000000,0.0,0.0,0.0,0.0,0.0,0,1,0.0,0.0,3,0.648336,-0.079572,0.178041,0.061854,0.073453,-0.055809,-0.011311,0.047310,0.008354,0.006474,-0.047099,0.020496,0.050190,-0.038573,0.057228,-0.072471,0.045393,-0.116783,0.168249,0.167355,-0.025072,-0.073858,-0.097024,-0.146191,0.027983,0.082989,0.014423,0.058370,-0.033928,0.046265,0.006901,-0.049498,0.126117,-0.089039,-0.006767,-0.031686,-0.010346,0.025637,0.061278,0.162580,-0.028081,0.161291,-0.018217,-0.002657,0.038485,-0.000530,0.044413,0.107176,-0.050721,0.064279,-0.066677,0.016742,-0.050257,0.072549,-0.035201,-0.027279,0.017115,0.043631,0.024660,-0.025841,0.031320,-0.076959,-0.072986,-0.040465,0.003958,-0.022475,0.033208,-0.028056,-0.005499,-0.055998,-0.021882,-0.070462,0.018237,-0.031396,-0.074606,0.072951,0.039997,0.036423,-0.027152,-0.071900,0.026267,-0.046270,-0.017945,0.007933,-0.006203,-0.046099,0.032793,-0.069113,0.020403,0.030783,-0.003787,-0.000490,-0.022951,0.013498,0.009664,-0.007012,-0.016325,-0.005732,0.036069,-0.063906,0.033891,0.010560,-0.104517,-0.022069,0.054322,-0.005460,-0.029093,0.040991,-0.053018,-0.024017,0.050817,-0.003297,-0.020895,-0.053213,-0.028428,0.048231,-0.001221,0.001302,-0.044137,0.015528,-0.012792,-0.012009,-0.008211,0.031114,0.024982,0.003863,-0.032321,0.030920,-0.012845,0.070170,-0.004037,0.014003,0.005577,0.021611,-0.002889,0.034824,0.047164,0.050545,-0.017639,0.029014,-0.030378,-0.027056,0.011464,-0.039759,-0.043514,-0.025605,-0.022484,-0.036224,0.000566,0.005481
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
635251,2025-03-01 19:00:00,26,50.4506,30.5243,0.0,-2.6,82.9,0.7,100.0,8.33,1.3,1.0,34.6,15.5,178.1,1026.7,99.5,40.6,3.6,2.0,0.05,-0.1,-3.5,97.13,0.0,0.0,0.0,16.9,10.1,181.6,1027.0,95.6,0.0,0.0,0.0,False,False,False,True,False,True,False,False,2025,3,5,19,Kyiv,Europe/Kiev,2025-03-01,06:41:35,17:39:46,19:00:00,Київ,0,0.000000,0.0,0.0,0.0,0.0,5.0,1,0,11.0,0.0,15,0.741253,0.175928,-0.044270,0.236290,0.000096,-0.082156,-0.069547,0.169634,0.047371,0.108829,-0.111513,0.005588,0.009037,-0.035562,0.049145,0.077242,-0.085251,0.067886,0.052548,-0.120459,0.081966,-0.062164,0.022709,0.023532,-0.002714,0.000626,-0.026931,0.012943,-0.027664,-0.111107,-0.094103,-0.019189,-0.002106,0.023217,0.036788,-0.009149,-0.051459,-0.073844,-0.016720,-0.019477,-0.024286,0.075470,-0.053957,-0.052265,0.022580,-0.016046,-0.047243,0.005718,0.019756,-0.035501,0.025955,0.020804,-0.008431,0.005311,-0.038751,-0.010557,-0.009238,-0.005986,-0.035657,-0.003185,-0.030416,-0.013563,-0.026338,0.069073,-0.003216,0.021366,0.025951,-0.017980,0.006948,0.029034,0.069441,-0.043368,0.028677,0.035237,-0.023784,-0.005083,0.028958,0.012654,0.001550,-0.039223,0.020654,-0.040622,0.014536,0.002429,-0.013533,0.003547,-0.061560,0.020515,-0.017876,0.041345,-0.033319,-0.020192,0.035267,0.011339,-0.088522,0.022461,-0.047734,-0.034346,-0.011346,0.043122,0.001617,-0.023157,-0.018391,-0.006131,0.040270,0.030336,0.007110,0.024232,0.035189,-0.038329,0.020301,0.032434,0.007683,-0.010900,-0.008896,-0.019209,0.007017,0.040898,-0.031859,0.000779,-0.002852,0.028824,0.006013,0.010350,0.013379,-0.027336,-0.003269,0.008264,0.004228,0.022508,-0.012380,0.000627,0.017807,-0.013325,-0.006459,0.021368,-0.027278,-0.008352,0.001816,0.004596,0.019812,-0.012733,-0.001035,-0.001903,0.005062,-0.015576,0.028419,-0.012698,0.016105,-0.007801
635252,2025-03-01 20:00:00,26,50.4506,30.5243,0.0,-2.6,82.9,0.7,100.0,8.33,1.3,1.0,34.6,15.5,178.1,1026.7,99.5,40.6,3.6,2.0,0.05,-0.3,-0.3,92.96,0.4,100.0,0.0,17.6,0.0,189.9,1027.0,100.0,0.0,0.0,0.0,False,False,False,True,False,False,False,True,2025,3,5,20,Kyiv,Europe/Kiev,2025-03-01,06:41:35,17:39:46,20:00:00,Київ,0,0.000000,0.0,0.0,0.0,0.0,5.0,1,0,5.0,0.0,16,0.741253,0.175928,-0.044270,0.236290,0.000096,-0.082156,-0.069547,0.169634,0.047371,0.108829,-0.111513,0.005588,0.009037,-0.035562,0.049145,0.077242,-0.085251,0.067886,0.052548,-0.120459,0.081966,-0.062164,0.022709,0.023532,-0.002714,0.000626,-0.026931,0.012943,-0.027664,-0.111107,-0.094103,-0.019189,-0.002106,0.023217,0.036788,-0.009149,-0.051459,-0.073844,-0.016720,-0.019477,-0.024286,0.075470,-0.053957,-0.052265,0.022580,-0.016046,-0.047243,0.005718,0.019756,-0.035501,0.025955,0.020804,-0.008431,0.005311,-0.038751,-0.010557,-0.009238,-0.005986,-0.035657,-0.003185,-0.030416,-0.013563,-0.026338,0.069073,-0.003216,0.021366,0.025951,-0.017980,0.006948,0.029034,0.069441,-0.043368,0.028677,0.035237,-0.023784,-0.005083,0.028958,0.012654,0.001550,-0.039223,0.020654,-0.040622,0.014536,0.002429,-0.013533,0.003547,-0.061560,0.020515,-0.017876,0.041345,-0.033319,-0.020192,0.035267,0.011339,-0.088522,0.022461,-0.047734,-0.034346,-0.011346,0.043122,0.001617,-0.023157,-0.018391,-0.006131,0.040270,0.030336,0.007110,0.024232,0.035189,-0.038329,0.020301,0.032434,0.007683,-0.010900,-0.008896,-0.019209,0.007017,0.040898,-0.031859,0.000779,-0.002852,0.028824,0.006013,0.010350,0.013379,-0.027336,-0.003269,0.008264,0.004228,0.022508,-0.012380,0.000627,0.017807,-0.013325,-0.006459,0.021368,-0.027278,-0.008352,0.001816,0.004596,0.019812,-0.012733,-0.001035,-0.001903,0.005062,-0.015576,0.028419,-0.012698,0.016105,-0.007801
635253,2025-03-01 21:00:00,26,50.4506,30.5243,0.0,-2.6,82.9,0.7,100.0,8.33,1.3,1.0,34.6,15.5,178.1,1026.7,99.5,40.6,3.6,2.0,0.05,0.0,-3.2,96.43,0.0,0.0,0.0,18.4,9.4,198.3,1027.0,100.0,0.0,0.0,0.0,False,False,False,True,False,True,False,False,2025,3,5,21,Kyiv,Europe/Kiev,2025-03-01,06:41:35,17:39:46,21:00:00,Київ,0,0.000000,0.0,0.0,0.0,0.0,5.0,1,0,9.0,0.0,17,0.741253,0.175928,-0.044270,0.236290,0.000096,-0.082156,-0.069547,0.169634,0.047371,0.108829,-0.111513,0.005588,0.009037,-0.035562,0.049145,0.077242,-0.085251,0.067886,0.052548,-0.120459,0.081966,-0.062164,0.022709,0.023532,-0.002714,0.000626,-0.026931,0.012943,-0.027664,-0.111107,-0.094103,-0.019189,-0.002106,0.023217,0.036788,-0.009149,-0.051459,-0.073844,-0.016720,-0.019477,-0.024286,0.075470,-0.053957,-0.052265,0.022580,-0.016046,-0.047243,0.005718,0.019756,-0.035501,0.025955,0.020804,-0.008431,0.005311,-0.038751,-0.010557,-0.009238,-0.005986,-0.035657,-0.003185,-0.030416,-0.013563,-0.026338,0.069073,-0.003216,0.021366,0.025951,-0.017980,0.006948,0.029034,0.069441,-0.043368,0.028677,0.035237,-0.023784,-0.005083,0.028958,0.012654,0.001550,-0.039223,0.020654,-0.040622,0.014536,0.002429,-0.013533,0.003547,-0.061560,0.020515,-0.017876,0.041345,-0.033319,-0.020192,0.035267,0.011339,-0.088522,0.022461,-0.047734,-0.034346,-0.011346,0.043122,0.001617,-0.023157,-0.018391,-0.006131,0.040270,0.030336,0.007110,0.024232,0.035189,-0.038329,0.020301,0.032434,0.007683,-0.010900,-0.008896,-0.019209,0.007017,0.040898,-0.031859,0.000779,-0.002852,0.028824,0.006013,0.010350,0.013379,-0.027336,-0.003269,0.008264,0.004228,0.022508,-0.012380,0.000627,0.017807,-0.013325,-0.006459,0.021368,-0.027278,-0.008352,0.001816,0.004596,0.019812,-0.012733,-0.001035,-0.001903,0.005062,-0.015576,0.028419,-0.012698,0.016105,-0.007801
635254,2025-03-01 22:00:00,26,50.4506,30.5243,0.0,-2.6,82.9,0.7,100.0,8.33,1.3,1.0,34.6,15.5,178.1,1026.7,99.5,40.6,3.6,2.0,0.05,0.0,-2.9,97.84,0.0,0.0,0.0,16.6,8.3,199.9,1027.0,97.6,0.0,0.0,0.0,False,False,False,True,False,True,False,False,2025,3,5,22,Kyiv,Europe/Kiev,2025-03-01,06:41:35,17:39:46,22:00:00,Київ,1,7.833333,0.0,0.0,0.0,0.0,5.0,1,0,11.0,0.0,18,0.741253,0.175928,-0.044270,0.236290,0.000096,-0.082156,-0.069547,0.169634,0.047371,0.108829,-0.111513,0.005588,0.009037,-0.035562,0.049145,0.077242,-0.085251,0.067886,0.052548,-0.120459,0.081966,-0.062164,0.022709,0.023532,-0.002714,0.000626,-0.026931,0.012943,-0.027664,-0.111107,-0.094103,-0.019189,-0.002106,0.023217,0.036788,-0.009149,-0.051459,-0.073844,-0.016720,-0.019477,-0.024286,0.075470,-0.053957,-0.052265,0.022580,-0.016046,-0.047243,0.005718,0.019756,-0.035501,0.025955,0.020804,-0.008431,0.005311,-0.038751,-0.010557,-0.009238,-0.005986,-0.035657,-0.003185,-0.030416,-0.013563,-0.026338,0.069073,-0.003216,0.021366,0.025951,-0.017980,0.006948,0.029034,0.069441,-0.043368,0.028677,0.035237,-0.023784,-0.005083,0.028958,0.012654,0.001550,-0.039223,0.020654,-0.040622,0.014536,0.002429,-0.013533,0.003547,-0.061560,0.020515,-0.017876,0.041345,-0.033319,-0.020192,0.035267,0.011339,-0.088522,0.022461,-0.047734,-0.034346,-0.011346,0.043122,0.001617,-0.023157,-0.018391,-0.006131,0.040270,0.030336,0.007110,0.024232,0.035189,-0.038329,0.020301,0.032434,0.007683,-0.010900,-0.008896,-0.019209,0.007017,0.040898,-0.031859,0.000779,-0.002852,0.028824,0.006013,0.010350,0.013379,-0.027336,-0.003269,0.008264,0.004228,0.022508,-0.012380,0.000627,0.017807,-0.013325,-0.006459,0.021368,-0.027278,-0.008352,0.001816,0.004596,0.019812,-0.012733,-0.001035,-0.001903,0.005062,-0.015576,0.028419,-0.012698,0.016105,-0.007801

In [20]:
df_final.isna().sum()

datetime_hour     0
region_id         0
city_latitude     0
city_longitude    0
day_temp          0
                 ..
isw_topic_145     0
isw_topic_146     0
isw_topic_147     0
isw_topic_148     0
isw_topic_149     0
Length: 216, dtype: int64

### Feature engineering for isw topics

In [21]:
topic_cols = [c for c in df_final.columns if "isw_topic_" in c]
df_isw_abs = df_final[topic_cols].abs()

df_final['isw_total_intensity'] = df_isw_abs.sum(axis=1)
df_final['isw_topic_std'] = df_isw_abs.std(axis=1)
df_final['isw_topic_max'] = df_isw_abs.max(axis=1)
df_final['isw_topic_mean'] = df_isw_abs.mean(axis=1)

df_final['isw_velocity_24h'] = (
    df_final.groupby('region_id')['isw_total_intensity']
    .diff(24)
    .fillna(0)
)

df_final['isw_intensity_ema'] = (df_final.groupby('region_id')['isw_total_intensity'].transform(lambda x: x.shift(1).ewm(span=24).mean()))

df_final['isw_topic_entropy'] = -(df_isw_abs.div(df_isw_abs.sum(axis=1), axis=0) * np.log(df_isw_abs.div(df_isw_abs.sum(axis=1), axis=0) + 1e-9)).sum(axis=1)

isw_cols = ['isw_velocity_24h', 'isw_intensity_ema', 'isw_topic_entropy']
df_final[isw_cols] = df_final[isw_cols].fillna(0)

C:\Users\Uw11\AppData\Local\Temp\ipykernel_24900\1269306822.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_final['isw_total_intensity'] = df_isw_abs.sum(axis=1)
C:\Users\Uw11\AppData\Local\Temp\ipykernel_24900\1269306822.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_final['isw_topic_std'] = df_isw_abs.std(axis=1)
C:\Users\Uw11\AppData\Local\Temp\ipykernel_24900\1269306822.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_final['isw_topic_max'] = df_isw_abs.max(axis=1)
C:\Users\Uw11\AppData\Local\Temp\ipykernel_24900\1269306822.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_final['isw_topic_mean'] = df_isw_abs.mean(axis=1)
C:\Users\Uw11\AppData\Local\Temp\ipykernel_24900\1269306822.py:9: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_final['isw_velocity_24h'] = (
C:\Users\Uw11\AppData\Local\Temp\ipykernel_24900\1269306822.py:15: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_final['isw_intensity_ema'] = (df_final.groupby('region_id')['isw_total_intensity'].transform(lambda x: x.shift(1).ewm(span=24).mean()))
C:\Users\Uw11\AppData\Local\Temp\ipykernel_24900\1269306822.py:17: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_final['isw_topic_entropy'] = -(df_isw_abs.div(df_isw_abs.sum(axis=1), axis=0) * np.log(df_isw_abs.div(df_isw_abs.sum(axis=1), axis=0) + 1e-9)).sum(axis=1)

In [22]:
df_final.sample(10)

,datetime_hour,region_id,city_latitude,city_longitude,day_temp,day_dew,day_humidity,day_precip,day_precipprob,day_precipcover,day_snow,day_snowdepth,day_windgust,day_windspeed,day_winddir,day_pressure,day_cloudcover,day_solarradiation,day_solarenergy,day_uvindex,day_moonphase,hour_temp,hour_feelslike,hour_humidity,hour_precip,hour_precipprob,hour_snow,hour_windgust,hour_windspeed,hour_winddir,hour_pressure,hour_cloudcover,hour_solarradiation,hour_solarenergy,hour_uvindex,day_conditions_simple_Clear,day_conditions_simple_Cloudy,day_conditions_simple_Rain,day_conditions_simple_Snow,hour_conditions_simple_Clear,hour_conditions_simple_Cloudy,hour_conditions_simple_Rain,hour_conditions_simple_Snow,year,month,day_of_week,hour,city_name,city_timezone,day_datetime,day_sunrise,day_sunset,hour_datetime,region_key,alarm_active,alarm_minutes_in_hour,alarm_lag_1,alarm_lag_3,alarm_lag_6,alarm_lag_12,alarms_in_last_24h,is_weekend,is_night,total_active_alarms_lag1,neighbour_alarms,hours_since_last_alarm,isw_topic_0,isw_topic_1,isw_topic_2,isw_topic_3,isw_topic_4,isw_topic_5,isw_topic_6,isw_topic_7,isw_topic_8,isw_topic_9,isw_topic_10,isw_topic_11,isw_topic_12,isw_topic_13,isw_topic_14,isw_topic_15,isw_topic_16,isw_topic_17,isw_topic_18,isw_topic_19,isw_topic_20,isw_topic_21,isw_topic_22,isw_topic_23,isw_topic_24,isw_topic_25,isw_topic_26,isw_topic_27,isw_topic_28,isw_topic_29,isw_topic_30,isw_topic_31,isw_topic_32,isw_topic_33,isw_topic_34,isw_topic_35,isw_topic_36,isw_topic_37,isw_topic_38,isw_topic_39,isw_topic_40,isw_topic_41,isw_topic_42,isw_topic_43,isw_topic_44,isw_topic_45,isw_topic_46,isw_topic_47,isw_topic_48,isw_topic_49,isw_topic_50,isw_topic_51,isw_topic_52,isw_topic_53,isw_topic_54,isw_topic_55,isw_topic_56,isw_topic_57,isw_topic_58,isw_topic_59,isw_topic_60,isw_topic_61,isw_topic_62,isw_topic_63,isw_topic_64,isw_topic_65,isw_topic_66,isw_topic_67,isw_topic_68,isw_topic_69,isw_topic_70,isw_topic_71,isw_topic_72,isw_topic_73,isw_topic_74,isw_topic_75,isw_topic_76,isw_topic_77,isw_topic_78,isw_topic_79,isw_topic_80,isw_topic_81,isw_topic_82,isw_topic_83,isw_topic_84,isw_topic_85,isw_topic_86,isw_topic_87,isw_topic_88,isw_topic_89,isw_topic_90,isw_topic_91,isw_topic_92,isw_topic_93,isw_topic_94,isw_topic_95,isw_topic_96,isw_topic_97,isw_topic_98,isw_topic_99,isw_topic_100,isw_topic_101,isw_topic_102,isw_topic_103,isw_topic_104,isw_topic_105,isw_topic_106,isw_topic_107,isw_topic_108,isw_topic_109,isw_topic_110,isw_topic_111,isw_topic_112,isw_topic_113,isw_topic_114,isw_topic_115,isw_topic_116,isw_topic_117,isw_topic_118,isw_topic_119,isw_topic_120,isw_topic_121,isw_topic_122,isw_topic_123,isw_topic_124,isw_topic_125,isw_topic_126,isw_topic_127,isw_topic_128,isw_topic_129,isw_topic_130,isw_topic_131,isw_topic_132,isw_topic_133,isw_topic_134,isw_topic_135,isw_topic_136,isw_topic_137,isw_topic_138,isw_topic_139,isw_topic_140,isw_topic_141,isw_topic_142,isw_topic_143,isw_topic_144,isw_topic_145,isw_topic_146,isw_topic_147,isw_topic_148,isw_topic_149,isw_total_intensity,isw_topic_std,isw_topic_max,isw_topic_mean,isw_velocity_24h,isw_intensity_ema,isw_topic_entropy
137083,2022-09-08 11:00:00,7,48.62636,22.28514,20.6,14.2,68.9,0.008,100.0,4.17,0.0,0.0,46.8,13.7,82.9,1014.9,61.9,189.5,16.3,7.0,0.39,21.2,21.2,65.53,0.0,0.0,0.0,33.8,7.9,99.0,1015.8,34.8,479.0,1.7,5.0,False,False,True,False,False,True,False,False,2022,9,3,11,Uzhgorod,Europe/Uzhgorod,2022-09-08,06:57:24,19:58:53,11:00:00,Закарпатська,0,0.000000,0.0,0.0,0.0,0.0,1.0,0,0,1.0,0.0,15,0.809727,-0.221686,0.154321,-0.152486,-0.026332,0.033961,-0.024565,0.017441,0.050666,-0.078529,0.006984,0.021928,0.136802,0.103640,-0.019146,0.023123,-0.107389,0.093725,0.009609,0.081766,0.043083,0.031293,0.021245,0.035246,0.074513,0.036859,-0.032635,-0.058497,-0.031134,0.022858,0.021038,-0.008669,0.061904,0.029781,0.008352,0.020688,0.033577,-0.001511,-0.064946,-0.022478,-0.019356,0.050694,0.044830,-0.009204,0.044311,0.011212,0.028720,-0.065306,-0.018759,-0.006198,0.033734,-0.000747,-0.013840,-0.018094,-0.014747,-0.020506,-0.006377,0.005557,-0.000510,0.019161,-0.011773,-0.011051,0.046577,-0.013420,0.021674,-0.011831,-0.010184,0.008106,0.014128,0.015176,-0.001383,0.034163,0.014256,0.013199,0.021116,-0.023380,0.022612,0.031429,0.004963,-0.020145,-0.006294,-0.032454,-0.025692,0.027241,0.005017,0.024288,0.000185,-0.036477,-0.012974,-0.018154,0.046846,-0.010663,-0.009528,0.033723,-0.017434,-0.026389,-0.015990,-0.034642,0.007448,-0.020569,0.040204,-0.010404,0.019293,-0.013367,0.014978,-0.013082,-0.011297,0.003227,0.015709,0.014384,-0.004665,-0.006957,0.018993,-0.020930,-0.015539,-0.030707,-0.013111,-0.028245,0.001257,-0.012338,0.029159,-0.017628,0.011318,-0.005836,0.032706,0.001101,0.003919,0.012172,0.001409,0.008284,0.005327,0.033514,-0.008125,-0.006797,0.011093,0.003152,-0.013543,-0.025030,-0.013862,-0.015163,0.004058,-0.010371,-0.001876,0.005934,-0.008725,0.008884,0.011059,-0.033109,-0.005954,0.008220,4.694585,0.071032,0.809727,0.031297,-0.594817,4.919791,4.220282
169315,2023-05-06 15:00:00,8,47.82890,35.16260,13.8,7.1,65.6,0.000,0.0,0.00,0.0,0.0,42.1,28.1,10.7,1017.6,4.2,291.0,25.2,8.0,0.52,16.8,16.8,47.90,0.0,0.0,0.0,39.2,22.7,12.5,1018.0,16.4,753.0,2.7,8.0,True,False,False,False,True,False,False,False,2023,5,5,15,Zaporozhye,Europe/Zaporozhye,2023-05-06,05:14:33,19:58:25,15:00:00,Запорізька,1,14.016667,0.0,0.0,0.0,0.0,11.0,1,0,0.0,0.0,3,0.717364,-0.294832,-0.082737,-0.064299,0.006840,0.069226,-0.038052,0.077039,-0.126986,0.121897,0.121127,0.010327,-0.091706,0.030862,0.138625,0.082903,0.119836,0.031325,-0.146646,0.060462,0.043232,0.017620,0.051228,-0.037010,-0.026117,0.053480,0.034033,-0.029550,0.078923,-0.001004,-0.019550,-0.024562,-0.005730,0.076124,0.026630,0.022707,-0.008485,-0.084556,0.004698,0.071542,0.009384,-0.029779,-0.095424,0.024654,0.058847,-0.016028,0.052350,0.024515,-0.069782,-0.000509,-0.033429,0.014580,-0.054636,0.001128,0.048141,0.008483,-0.014933,0.002276,-0.042538,0.027264,-0.004005,-0.014916,-0.068620,-0.000083,0.019079,-0.010407,-0.004620,0.019412,-0.032645,-0.000090,-0.028143,0.049935,-0.038137,0.001819,0.021161,-0.089756,0.021241,-0.011127,0.026208,-0.005881,-0.006799,-0.045016,-0.015161,0.003621,0.044314,0.016590,0.004760,-0.038240,0.015755,-0.000583,-0.025465,0.000500,-0.024161,0.002295,0.016989,-0.010990,-0.005208,-0.018269,0.042257,0.022153,0.024065,0.013378,-0.024670,-0.023768,-0.010057,-0.001864,-0.019133,0.008160,0.016679,0.008573,0.007171,0.016448,0.024077,0.025053,0.027474,-0.046615,0.013109,-0.028065,0.006621,0.018446,0.009011,-0.015203,-0.006510,-0.032586,-0.002361,-0.003081,0.022730,0.039471,-0.025273,0.015238,-0.013876,-0.026791,-0.016319,0.018862,0.011813,-0.009581,-0.001367,0.000094,-0.018921,0.021736,-0.015065,0.013553,0.005125,0.006149,-0.008081,-0.006116,0.019727,0.004067,0.019488,0.034044,5.410629,0.067152,0.717364,0.036071,0.371628,5.277665,4.305526
429917,2022-11-17 06:00:00,19,49.55270,25.58890,0.2,-0.6,94.6,10.100,100.0,83.33,3.3,0.9,37.4,19.1,55.8,1005.6,99.6,13.3,1.2,1.0,0.76,0.1,-4.6,96.43,0.9,100.0,0.1,30.2,16.6,57.0,1005.0,100.0,0.0,0.1,0.0,False,False,False,True,False,False,False,True,2022,11,3,6,Ternopil,Europe/Kiev,2022-11-17,07:31:51,16:32:49,06:00:00,Тернопільська,0,0.000000,0.0,0.0,0.0,0.0,2.0,0,1,0.0,0.0,19,0.790524,-0.236351,0.038822,-0.184692,0.053981,-0.107013,0.070043,-0.089230,0.122951,0.123162,0.057960,0.006859,0.032142,-0.026587,-0.044243,0.064012,-0.107794,0.078330,0.077645,0.089696,-0.002354,0.039216,0.029261,0.049934,-0.081797,0.018009,0.056406,-0.002052,-0.018391,-0.001095,-0.017795,0.021020,-0.046157,0.012069,-0.005767,0.022875,-0.002413,0.030273,0.004181,-0.010245,0.034263,0.006209,-0.008424,-0.062112,-0.037586,-0.001749,0.019720,-0.001304,-0.013136,0.018858,0.027527,-0.010058,0.024860,0.003819,-0.022533,-0.024200,-0.015074,0.005672,-0.042533,0.018550,0.007845,0.006859,0.000104,0.050444,-0.005094,-0.004887,0.025464,0.012184,-0.014345,-0.032730,-0.021034,0.004000,-0.012774,-0.024881,0.007006,0.008245,-0.030070,0.005967,0.007769,-0.029073,0.020768,0.015368,0.016222,-0.024446,-0.011429,0.000932,-0.017152,-0.016036,0.036015,-0.000445,0.016174,0.027389,-0.024030,-0.017160,-0.004677,0.015263,-0.012381,0.012771,0.021048,-0.008989,-0.013322,-0.008167,-0.003697,-0.022842,0.014663,-0.004436,-0.019479,0.042419,-0.016348,0.005581,0.019603,-0.005290,0.029752,-0.008219,-0.006481,-0.002072,-0.015029,-0.006045,0.015794,-0.008096,0.054101,0.019239,0.009110,-0.009317,-0.036818,-0.006945,-0.031305,0.014975,-0.019179,-0.008190,0.006960,-0.001721,0.004180,-0.000088,-0.010633,0.004156,0.017646,-0.009879,0.013642,-0.010367,0.011233,0.018283,0.014312,-0.022187,0.004538,0.004246,0.021880,0.006528,-0.004394,0.016653,4.581045,0.070424,0.790524,0.030540,-0.190309,4.702131,4.160466
478167,2022-05-05 22:00:00,21,46.64010,32.61420,14.0,3.7,50.0,0.000,0.0,0.00,0.0,0.0,39.2,25.2,14.4,1018.8,54.0,316.2,27.4,9.0,0.14,12.9,12.9,55.87,0.0,0.0,0.0,18.0,12.2,28.4,1023.0,1.0,0.0,0.1,0.0,False,True,False,False,True,False,False,False,2022,5,3,22,Kherson,Europe/Kiev,2022-05-05,05:29:12,20:04:13,22:00:00,Херсонська,0,0.000000,0.0,0.0,0.0,0.0,0.0,0,0,23.0,3.0,501,0.698928,-0.180449,0.408709,0.067851,0.035430,-0.010995,0.006828,-0.058885,0.005956,-0.054664,-0.016070,0.030191,0.018237,0.003243,0.070361,-0.033981,0.187188,0.084429,0.065581,0.037487,0.100862,0.015990,0.080366,0.017125,-0.038992,-0.023157,-0.071235,-0.068776,-0.042034,0.031081,0.004267,0.010777,-0.012384,0.004325,-0.009397,-0.022633,-0.013352,-0.019557,-0.012450,-0.015276,0.028602,0.042741,0.006695,0.027180,-0.010559,0.021891,-0.001435,-0.046027,-0.033045,-0.022402,0.015294,0.015769,-0.051958,-0.004337,0.024955,0.000599,0.016759,0.063946,-0.013741,-0.047321,0.020441,-0.008538,0.028933,-0.037535,-0.030562,0.022306,-0.009652,-0.012581,-0.004550,-0.015892,0.020770,-0.015658,-0.012365,0.081598,-0.025285,0.025977,-0.040489,0.027552,-0.008394,0.035882,-0.003442,-0.027892,-0.016869,-0.006462,0.038477,-0.013698,-0.042056,-0.033363,-0.007931,0.022770,-0.011851,0.000998,0.025363,0.017550,-0.014775,-0.003458,-0.018168,0.009095,-0.012699,0.015371,-0.007987,-0.010755,0.047086,0.024304,-0.005187,0.009829,0.014578,0.015076,-0.023932,0.013349,0.041368,-0.001581,0.011591,0.003130,0.033482,-0.002203,0.016960,-0.034629,0.035640,-0.002170,-0.005559,0.015055,-0.022850,-0.025247,-0.026510,-0.061018,0.012799,-0.002909,-0.033363,-0.018722,-0.000437,0.061350,-0.019322,0.007774,0.019998,-0.013848,0.019242,-0.022290,0.004527,0.015196,-0.020381,0.015853,0.020856,0.028867,-0.030662,-0.014837,-0.008525,-0.010871,0.009360,-0.019324,4.954395,0.068408,0.698928,0.033029,0.396955,4.911342,4.267120
606545,2024-11-28 14:00:00,25,51.49370,31.29440,0.2,-0.6,94.2,0.000,0.0,0.00,0.0,3.1,26.6,14.4,208.5,1025.1,99.9,20.2,1.7,1.0,0.91,1.4,1.4,91.71,0.0,0.0,0.0,16.9,0.0,191.1,1025.1,100.0,69.8,0.3,1.0,False,True,False,False,False,True,False,False,2024,11,3,14,Chernihiv,Europe/Kiev,2024-11-28,07:34:23,15:51:09,14:00:00,Чернігівська,1,60.000000,1.0,0.0,1.0,1.0,13.0,0,0,8.0,2.0,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-3.971563,1.240265,-0.000000
335982,2024-03-28 20:00:00,15,46.47250,30.73710,10.5,6.8,78.0,0.000,0.0,0.00,0.0,0.0,55.8,31.7,162.8,1010.3,76.3,195.8,17.0,6.0,0.61,11.5,11.5,78.01,0.0,0.0,0.0,42.5,23.0,203.3,1008.0,100.0,0.0,0.0,0.0,False,True,False,False,False,True,False,False,2024,3,3,20,Odesa,Europe/Kiev,2024-03-28,05:43:50,18:21:03,20:00:00,Одеська,0,0.000000,0.0,0.0,0.0,1.0,8.0,0,0,0.0,0.0,1,0.788825,-0.072465,-0.135768,0.200234,0.013042,-0.072620,-0.033024,0.080229,0.050240,0.024655,-0.089637,0.001140,0.023091,-0.003932,-0.161587,0.007208,0.062176,-0.020182,-0.015832,0.021951,0.077790,-0.053176,-0.030816,-0.030175,-0.046262,0.064809,-0.064688,0.077393,0.048263,-0.007086,-0.027382,-0.026362,0.016309,0.035355,-0.091256,-0.078582,0.064823,-0.000359,-0.069408,0.042074,0.123931,0.011262,-0.050791,-0.012443,-0.005923,0.026834,0.016405,-0.037692,0.047771,-0.048164,-0.009835,-0.015654,0.001114,0.004160,-0.051110,0.012390,-0.013731,-0.036170,0.003383,0.000400,0.023234,0.005122,0.009317,-0.018748,0.009827,0.018057,-0.014589,0.031479,0.024883,-0.036196,0.002878,-0.062335,-0.006517,-0.012648,0.006700,0.001115,-0.018124,-0.024310,0.006649,0.010535,-0.017209,-0.012930,0.012508,-0.009917,-0.018909,0.006471,0.007714,-0.009065,-0.031285,0.023164,0.061089,-0.008878,-0.007484,0.006637,0.014437,0.042773,0.002106,-0.017690,0.007076,0.001560,-0.012304,-0.036095,-0.013534,0.023503,-0.028716,-0.022357,0.021226,0.003503,0.022910,-0.004968,0.034970,0.034553,-0.000416,0.020938,0.022070,-0.013222,-0.022579,-0.004925,-0.047164,-0.002429,-0.004991,0.003999,0.027189,-0.002345,0.010915,0.004836,0.000479,-0.027007,-0.021384,0.003056,-0.015728,0.003256,0.008390,-0.008696,0.034424,0.017398,-0.014229,-0.018561,0.003247,0.000223,0.010010,-0.005654,0.002606,-0.027959,-0.029914,0.010410,-0.042293,-0.008072,0.010675,-0.016547,4.808404,0.069221,0.788825,0.032056,-1.008871,5.015604,4.231083
515159,2023-07-18 10:00:00,22,49.41680,26.97430,22.1,16.2,71.7,0.500,100.0,4.17,0.0,0.0,43.2,25.2,318.7,1014.7,54.6,235.2,20.3,7.0,0.02,19.9,19.9,95.74,0.0,0.0,0.0,31.0,15.5,311.1,1015.0,60.7,323.0,1.2,3.0,False,False,True,False,False,True,False,False,2023,7,1,10,Khmelnytskyi,Europe/Kiev,2023-07-18,05:25:11,21:10:53,10:00:00,Хмельницька,0,0.000000,0.0,0.0,0.0,0.0,0.0,0,0,1.0,0.0,86,0.792668,-0.182554,-0.030400,-0.108020,-0.105798,0.115278,0.033752,0.001579,-0.072375,0.121130,-0.035502,-0.150337,-0.020331,0.049461,0.077137,-0.118415,-0.014778,0.030402,0.030627,-0.009522,0.013978,-0.028686,-0.006649,0.008905,-0.015429,-0.081790,-0.010833,0.072676,-0.039036,0.029044,-0.006628,0.024653,0.031249,-0.065504,-0.022925,-0.023583,-0.031433,0.031706,-0.024128,0.005107,0.030549,0.001202,-0.007803,-0.023715,-0.033674,0.016402,-0.003787,0.033735,-0.054901,-0.009945,-0.031503,-0.019089,0.022569,-0.012549,0.024900,0.005500,-0.042447,0.038334,-0.024134,0.022099,-0.035867,0.014538,-0.021270,-0.008447,0.027412,0.033173,-0.062385,0.004502,-0.041176,0.027872,-0.021059,0.040174,-0.002491,0.049714,-0.003698,-0.097931,0.059115,0.031493,0.014827,0.010612,-0.002535,0.007173,-0.025628,0.029600,-0.009721,0.009306,-0.021254,0.008401,0.038401,0.019195,0.048432,-0.017495,0.067119,-0.028503,0.054160,0.010815,0.034651,-0.017114,-0.014243,0.039493,0.002472,-0.026524,-0.058112,0.020860,-0.030412,0.009953,0.007279,0.045714,0.041055,0.005604,0.012361,0.009773,-0.009494,0.035536,0.016323,-0.004792,0.050607,0.003961,-0.039823,0.018729,0.043749,-0.008891,-0.010292,0.002770,0.014780,0.036125,0.038839,0.032874,-0.028700,0.001448,0.008845,-0.012174,-0.024882,-0.024128,0.000239,0.014465,-0.022075,0.030653,-0.008696,-0.003858,-0.030382,0.016695,0.012141,-0.030006,-0.022247,0.008927,0.028843,0.014956,0.014887,0.010025,5.250817,0.068657,0.792668,0.035005,-0.159954,5.311210,4.365041
134325,2022-05-16 13:00:00,7,48.62636,22.28514,16.3,6.1,54.1,0.000,0.0,0.00,0.0,0.0,21.6,9.3,346.1,1019.1,47.5,302.9,26.0,9.0,0.51,21.4,21.4,35.77,0.0,0.0,0.0,18.0,7.2,347.0,1019.5,40.0,844.0,3.0,8.0,False,True,False,False,False,True,False,False,2022,5,0,13,Uzhgorod,Europe/Uzhgorod,2022-05-16,05:48:59,21:06:23,13:00:00,Закарпатська,0,0.000000,0.0,0.0,0.0,0.0,0.0,0,0,6.0,0.0,31,0.736935,-0.237892,0.337988,0.063697,0.028898,-0.001414,0.021813,-0.094280,0.015657,-0.075757,-0.022547,0.034695,0.041240,-0.028148,0.034446,0.041960,0.163247,0.092861,-0.043468,-0.041343,0.047234,0.053435,0.047684,0.107602,-0.024078,-0.006461,-0.001828,0.026189,-0.015052,-0.003121,-0.022805,-0.034862,0.028163,0.025384,-0.009993,0.024102,0.029922,0.011970,0.020373,-0.010532,0.013615,-0.018986,0.041672,-0.025039,0.003954,0.011063,-0.036360,-0.030601,-0.032425,-0.010611,-0.000451,0.000253,0.008601,0.017192,0.041425,0.007269,0.006476,-0.012176,0.001140,-0.052614,-0.001527,-0.009002,-0.021040,-0.044020,-0.002442,-0.040736,0.014693,0.028279,0.003636,-0.033887,0.009657,0.012490,0.032232,0.055501,-0.002414,0.029571,-0.001982,0.003962,-0.009774,0.032605,0.033267,0.016313,-0.018593,-0.008123,-0.000772,-0.019950,-0.005098,-0.037644,-0.003417,0.016683,-0.039623,-0.012459,0.034352,-0.013635,0.001770,-0.003739,-0.031951,-0.002814,0.016408,-0.026700,-0.000580,-0.006144,-0.013664,-0.008089,0.009713,-0.014975,0.009663,0.027766,-0.037868,0.006753,-0.009360,0.000556,0.018722,0.000760,-0.007092,-0.034366,-0.015939,-0.006348,0.008404,-0.004969,0.027610,0.035181,-0.021942,0.000007,0.003114,-0.000244,0.006450,-0.019610,0.023851,0.009881,-0.012855,0.019969,-0.021598,0.039416,0.017971,-0.004156,0.019166,0.000017,-0.023514,-0.006731,0.006240,0.002779,-0.004732,0.016039,0.016221,0.012576,0.013390,0.014107,0.012890,-0.001514,4.469259,0.069515,0.736935,0.029795,-0.579951,4.660015,4.124621
608907,2022-02-28 00:00:00,26,50.45060,30.52430,-0.7,-6.9,64.4,0.000,0.0,0.00,0.0,0.0,39.2,17.3,16.1,1032.5,57.9,136.4,12.1,4.0,0.90,-1.2,-3.3,73.11,0.0,0.0,0.0,13.7,5.8,25.5,1033.0,0.0,0.0,0.1,0.0,False,True,False,False,True,False,False,False,2022,2,0,0,Kyiv,Europe/Kiev,2022-02-28,06:44:12,17:37:34,00:00:00,Київ,1,23.250000,1.0,1.0,1.0,0.0,7.0,0,1,6.0,0.0,0,0.658182,-0.083476,0.210413,0.123701,0.128039,-0.052661,-0.036711,0.116411,-0.018182,0.064033,-0.068725,0.058917,0.219618,-0.216717,0.190733,-0.124702,0.001308,-0.110761,0.144719,0.126454,-0.067033,-0.088167,-0.008720,-0.099063,0.003548,0.070589,-0.010141,0.035961,-0.018439,0.008922,-0.010335,-0.014091,0.095744,-0.064864,-0.005396,-0.023768,0.000540,0.030188,0.020888,0.095186,0.008415,0.098179,0.005603,0.020865,0.028498,0.010728,-0.001640,0.079629,-0.008840,-0.002019,-0.056807,0.033482,-0.031377,0.024563,0.008903,0.014949,0.020816,0.007946,-0.009088,-0.013615,0.028867,-0.064712,-0.009287,-0.028995,-0.001593,-0.033006,0.010110,-0.009815,-0.019675,-0.044106,-0.007732,-0.043496,0.045137,-0.016668,-0.055026,0.029324,0.036182,-0.016954,-0.011506,-0.023797,0.005538,0.004830,-0.003345,0.030728,0.032616,-0.019564,-0.000268,-0.007104,0.016893,-0.004107,-0.023713,-0.032961,-0.027921,0.027084,0.010352,0.008830,-0.017471,-0.008653,-0.020782,-0.009317,0.007200,0.003505,-0.027939,-0.042652,-0.030441,-0.007496,-0.005585,0.000636,-0.015329,0.019081,0.025532,0.008503,0.055324,-0.001692,-0.000192,0.009109,0.023690,0.001084,0.013576,0.014186,0.017194,0.010609,0.022678,0.021968,-0.000048,0.016576,-0.021697,-0.013515,-0.019140,-0.000627,-0.019198,-0.007717,-0.017842,-0.004014,0.004443,-0.018841,-0.025425,0.003876,0.007702,-0.022794,-0.003470,0.015435,0.001268,-0.002248,0.019134,0.013219,-0.001470,0.022917,-0.027148,-0.000046,5.555093,0.066481,0.658182,0.037034,0.027058,5.602500,4.246084

### TELEGRAM MERGE

In [23]:
df_tg_matrix = pd.read_csv("../data/telegram_processed_svd.csv")

In [24]:
df_tg_matrix.head()

,date,channel,tg_topic_0,tg_topic_1,tg_topic_2,tg_topic_3,tg_topic_4,tg_topic_5,tg_topic_6,tg_topic_7,tg_topic_8,tg_topic_9,tg_topic_10,tg_topic_11,tg_topic_12,tg_topic_13,tg_topic_14,tg_topic_15,tg_topic_16,tg_topic_17,tg_topic_18,tg_topic_19,tg_topic_20,tg_topic_21,tg_topic_22,tg_topic_23,tg_topic_24,tg_topic_25,tg_topic_26,tg_topic_27,tg_topic_28,tg_topic_29,tg_topic_30,tg_topic_31,tg_topic_32,tg_topic_33,tg_topic_34,tg_topic_35,tg_topic_36,tg_topic_37,tg_topic_38,tg_topic_39,tg_topic_40,tg_topic_41,tg_topic_42,tg_topic_43,tg_topic_44,tg_topic_45,tg_topic_46,tg_topic_47,tg_topic_48,tg_topic_49,tg_topic_50,tg_topic_51,tg_topic_52,tg_topic_53,tg_topic_54,tg_topic_55,tg_topic_56,tg_topic_57,tg_topic_58,tg_topic_59,tg_topic_60,tg_topic_61,tg_topic_62,tg_topic_63,tg_topic_64,tg_topic_65,tg_topic_66,tg_topic_67,tg_topic_68,tg_topic_69,tg_topic_70,tg_topic_71,tg_topic_72,tg_topic_73,tg_topic_74,tg_topic_75,tg_topic_76,tg_topic_77,tg_topic_78,tg_topic_79,tg_topic_80,tg_topic_81,tg_topic_82,tg_topic_83,tg_topic_84,tg_topic_85,tg_topic_86,tg_topic_87,tg_topic_88,tg_topic_89,tg_topic_90,tg_topic_91,tg_topic_92,tg_topic_93,tg_topic_94,tg_topic_95,tg_topic_96,tg_topic_97,tg_topic_98,tg_topic_99,tg_topic_100,tg_topic_101,tg_topic_102,tg_topic_103,tg_topic_104,tg_topic_105,tg_topic_106,tg_topic_107,tg_topic_108,tg_topic_109,tg_topic_110,tg_topic_111,tg_topic_112,tg_topic_113,tg_topic_114,tg_topic_115,tg_topic_116,tg_topic_117,tg_topic_118,tg_topic_119,tg_topic_120,tg_topic_121,tg_topic_122,tg_topic_123,tg_topic_124,tg_topic_125,tg_topic_126,tg_topic_127,tg_topic_128,tg_topic_129,tg_topic_130,tg_topic_131,tg_topic_132,tg_topic_133,tg_topic_134,tg_topic_135,tg_topic_136,tg_topic_137,tg_topic_138,tg_topic_139,tg_topic_140,tg_topic_141,tg_topic_142,tg_topic_143,tg_topic_144,tg_topic_145,tg_topic_146,tg_topic_147,tg_topic_148,tg_topic_149,tg_topic_150,tg_topic_151,tg_topic_152,tg_topic_153,tg_topic_154,tg_topic_155,tg_topic_156,tg_topic_157,tg_topic_158,tg_topic_159,tg_topic_160,tg_topic_161,tg_topic_162,tg_topic_163,tg_topic_164,tg_topic_165,tg_topic_166,tg_topic_167,tg_topic_168,tg_topic_169,tg_topic_170,tg_topic_171,tg_topic_172,tg_topic_173,tg_topic_174,tg_topic_175,tg_topic_176,tg_topic_177,tg_topic_178,tg_topic_179,tg_topic_180,tg_topic_181,tg_topic_182,tg_topic_183,tg_topic_184,tg_topic_185,tg_topic_186,tg_topic_187,tg_topic_188,tg_topic_189,tg_topic_190,tg_topic_191,tg_topic_192,tg_topic_193,tg_topic_194,tg_topic_195,tg_topic_196,tg_topic_197,tg_topic_198,tg_topic_199,tg_topic_200,tg_topic_201,tg_topic_202,tg_topic_203,tg_topic_204,tg_topic_205,tg_topic_206,tg_topic_207,tg_topic_208,tg_topic_209,tg_topic_210,tg_topic_211,tg_topic_212,tg_topic_213,tg_topic_214,tg_topic_215,tg_topic_216,tg_topic_217,tg_topic_218,tg_topic_219,tg_topic_220,tg_topic_221,tg_topic_222,tg_topic_223,tg_topic_224,tg_topic_225,tg_topic_226,tg_topic_227,tg_topic_228,tg_topic_229,tg_topic_230,tg_topic_231,tg_topic_232,tg_topic_233,tg_topic_234,tg_topic_235,tg_topic_236,tg_topic_237,tg_topic_238,tg_topic_239,tg_topic_240,tg_topic_241,tg_topic_242,tg_topic_243,tg_topic_244,tg_topic_245,tg_topic_246,tg_topic_247,tg_topic_248,tg_topic_249
0,2026-03-06 13:06:58,DeepStateUA,0.007121,0.000107,0.019843,0.000990,-0.011395,0.032670,-0.050983,0.061080,0.042624,-0.024341,-0.018764,0.023404,-0.017137,-0.358836,0.425288,0.017966,-0.107660,-0.032066,-0.045986,0.118212,0.091172,-0.248637,-0.001069,0.150763,0.030603,-0.074030,0.005803,0.005871,0.034871,0.017239,0.058098,0.029814,-0.010845,0.031486,-0.022705,0.005607,-0.006324,-0.010169,0.024500,-0.015581,-0.012708,0.005139,0.007857,0.016734,-0.040289,-0.019688,-0.026763,0.009381,-0.043500,-0.009525,-0.013075,-0.010473,-0.018150,0.005988,0.032611,0.000850,0.017872,0.020885,0.023899,-0.019290,-0.006676,-0.018478,-0.023263,-0.005497,-0.006460,0.026051,0.004991,0.019687,-0.022244,0.010929,0.007016,-0.067349,-0.035249,-0.005686,0.018747,0.039159,-0.053868,-0.078189,-0.074737,-0.082163,0.020498,0.084336,0.113470,-0.025871,-0.048314,0.096330,0.043779,0.029575,0.019820,0.002819,-0.007308,-0.005234,-0.053796,-0.005893,0.036483,-0.061232,-0.001463,0.048285,-0.017340,0.033961,0.039046,-0.045463,-0.035894,-0.033875,0.041559,-0.021964,-0.005454,-0.020615,0.006442,-0.016322,-0.010443,-0.015532,0.000981,0.002928,-0.010924,-0.004072,-0.007252,-0.020386,0.007354,0.022114,-0.000884,-0.019901,-0.009325,-0.043505,0.008556,-0.016976,0.004765,0.030853,0.012413,0.011307,0.017726,0.010620,-0.013777,-0.037939,-0.003764,0.015808,-0.027407,-0.033773,0.054684,-0.005455,0.077819,0.006894,-0.022642,-0.011036,0.007590,-0.011639,0.036640,-0.020276,0.016764,-0.000467,-0.007996,0.023813,-0.014151,-0.026548,-0.078007,0.014955,0.043507,-0.021709,0.013392,-0.008661,0.012712,0.037409,-0.032628,-0.021403,-0.030711,0.033490,-0.025720,0.008100,-0.011149,-0.002706,0.002765,0.017707,-0.010806,-0.012850,0.007063,0.021780,0.010662,-0.031776,0.011750,0.069730,0.029703,0.012839,-0.031854,0.001635,-0.002149,-0.045445,0.002481,0.021315,0.006077,-0.006012,0.006578,-0.036587,0.009373,-0.025445,-0.019477,-0.011097,0.014675,-0.016785,0.010995,0.002045,-0.004600,-0.008963,0.006641,-0.017489,0.003821,0.005926,0.000537,-0.002830,-0.035321,-0.004957,0.013548,0.015414,0.018981,0.017932,-0.002853,0.007882,0.026621,0.003335,-0.001598,0.011594,-0.016659,0.001508,-0.007204,0.002975,0.001589,0.012191,0.005661,0.006600,-0.027472,0.014275,-0.020139,-0.011419,0.015111,-0.008120,0.001883,-0.011402,0.006871,0.024781,0.019495,0.024153,0.017141,-0.013944,-0.027516,0.034612,-0.032061,-0.051141,-0.004707,-0.003985,-0.052194,-0.026334
1,2026-03-06 12:57:29,DeepStateUA,0.022770,-0.002163,0.041469,0.001527,-0.033584,0.077087,-0.078417,0.091534,0.014917,-0.016270,-0.019775,0.015028,-0.012900,-0.066689,0.049295,-0.031093,0.006109,-0.021357,-0.047947,0.025239,-0.010092,0.063969,0.026579,-0.002938,0.000962,-0.014692,-0.010761,0.001202,-0.015000,-0.005930,-0.010839,0.049023,-0.023754,0.030922,0.000492,-0.009320,-0.015764,0.024560,0.006807,-0.000411,-0.001480,-0.017302,-0.026282,0.007343,0.049168,-0.004316,0.029036,-0.034987,0.034368,-0.046229,-0.012751,0.048371,0.004354,-0.014649,0.034935,-0.016468,-0.013150,0.017354,-0.000886,0.004047,0.036549,-0.017461,0.009667,-0.007887,-0.027599,-0.016937,-0.037606,-0.009493,-0.002735,-0.006034,0.023060,0.028297,0.024781,0.010909,-0.000544,-0.016357,-0.003670,-0.016336,0.002609,0.013846,-0.005648,-0.012539,-0.007839,-0.041249,0.030814,-0.017629,-0.005069,-0.024100,-0.013485,0.010861,-0.015271,-0.006842,-0.013700,0.008861,-0.010810,0.022671,-0.034102,-0.016120,0.001828,0.003954,0.007680,-0.037762,-0.017967,0.016946,0.016302,-0.011406,0.021384,-0.001978,-0.005628,-0.080374,0.039484,0.015890,0.034496,-0.016936,0.004379,-0.005021,0.014321,-0.003484,-0.002882,-0.002483,-0.005047,0.017296,-0.003401,0.009433,-0.001665,0.018296,0.003151,-0.031688,0.003527,0.010405,-0.006932,-0.019232,-0.004084,-0.023476,-0.008857,-0.015648,0.053937,0.034130,-0.026430,0.018625,-0.050338,0.022854,-0.000992,0.001886,-0.013131,0.037482,0.025278,-0.008833,-0.009892,0.015771,-0.019763,-0.015569,-0.015169,0.040201,0.018226,0.018286,-0.011713,-0.000436,0.000451,0.012252,0.007596,-0.000338,0.004704,0.023604,-0.020461,0.016871,0.003246,-0.045373,0.004746,-0.036469,-0.025234,0.030737,-0.000797,0.015820,0.042129,0.010345,0.022695,0.005339,-0.001636,-0.018894,0.026074,-0.054026,-0.057851,0.004372,-0.020828,-0.034435,0.055865,0.016301,0.063019,0.010370,-0.004495,-0.030530,0.018833,-0.013644,0.002207,0.037501,-0.045908,-0.059514,-0.035367,-0.024918,-0.039085,0.035208,0.085963,0.009390,0.079267,0.013885,0.006535,-0.052116,-0.033637,0.008546,-0.019285,0.006149,0.002710,-0.056530,-0.022435,0.020384,-0.013988,-0.005111,-0.015295,-0.097911,-0.042214,0.020642,-0.042973,0.045024,0.005130,-0.022150,0.006530,0.054045,-0.042555,0.006345,-0.035607,-0.006021,0.000036,-0.033672,0.020923,-0.000556,-0.034840,0.034524,0.004798,0.001867,-0.019097,0.025730,0.000530,0.020332,-0.028041,0.001581,0.006948,-0.064965,0.022597,-0.017810
2,2026-03-06 08:32:47,DeepStateUA,0.009647,-0.001083,0.029820,0.004092,-0.021362,0.053647,-0.076998,0.085930,0.011210,-0.020903,-0.051377,0.013232,-0.021159,0.001682,0.049129,-0.010018,-0.014271,-0.012423,-0.010588,0.046603,0.026875,0.002452,0.003347,-0.018525,0.005328,-0.003516,0.003550,0.018054,0.002157,0.012886,0.034851,0.000381,-0.009230,-0.002467,0.002381,0.000435,0.000842,-0.004257,-0.003348,0.009321,-0.005701,-0.004301,-0.016552,-0.001785,0.016005,0.008306,0.000706,-0.004439,-0.004069,-0.017177,-0.017974,-0.000361,-0.033317,-0.032714,0.027864,-0.006006,0.000665,-0.001117,-0.020576,0.002026,0.001386,0.000074,0.000035,0.007953,0.005774,0.005407,-0.005473,0.009134,-0.010858,-0.014439,0.028165,-0.023096,0.014483,0.021402,-0.017701,0.035852,-0.021296,-0.016145,-0.007317,-0.016939,0.014848,-0.006705,-0.047833,-0.002701,0.006144,-0.016566,0.016766,0.017487,0.002922,-0.004175,0.003020,-0.032485,0.001179,0.015611,0.015266,0.023711,0.005134,-0.030744,-0.014357,0.024034,0.016933,-0.044400,0.005215,0.011766,-0.026130,-0.005996,0.011388,-0.012677,-0.016358,-0.020579,-0.003119,-0.003134,0.019595,-0.011791,0.015521,0.022933,0.013426,0.013833,-0.006377,0.006772,-0.023631,0.008806,0.003886,0.014650,-0.029616,0.047030,0.005467,-0.020456,0.018529,-0.009387,0.010160,0.010283,-0.016104,0.038236,-0.028747,0.030649,0.028343,0.020708,0.001123,-0.009186,-0.064016,0.007831,0.005442,0.008333,-0.002820,0.007245,0.037716,-0.034047,0.009513,0.002276,-0.009623,-0.009046,0.023603,-0.009777,-0.047725,0.011991,-0.016423,0.004245,0.039250,0.030454,-0.007661,-0.043307,-0.005340,-0.003352,0.004921,0.010619,0.011745,-0.029661,-0.016769,-0.004054,-0.019134,-0.010521,-0.016018,0.013938,0.061204,0.000223,-0.016080,-0.013129,0.011080,0.025287,0.030597,-0.001902,-0.032930,0.022210,0.024393,-0.023036,0.001308,-0.010151,0.002527,0.003083,0.002821,0.012997,0.008941,-0.011744,0.019257,-0.000326,0.025398,-0.044011,-0.021810,-0.040764,-0.011043,0.008865,-0.020367,-0.005459,0.002685,0.019290,0.025485,-0.019258,-0.011527,-0.015354,-0.003904,0.007485,0.039596,0.030817,-0.034836,0.029725,0.018850,0.009886,0.006251,-0.006886,-0.028339,-0.017251,-0.019577,-0.004734,-0.014053,-0.014076,-0.018760,-0.006640,0.002467,-0.014727,0.015968,-0.020566,-0.000171,-0.020244,0.003823,-0.020505,-0.006361,-0.011117,-0.002427,0.036069,0.025378,-0.003550,-0.043415,-0.007200,-0.009172,0.006124,-0.004550,0.020576,0.010544,0.012825
3,2026-03-05 16:46:58,DeepStateUA,0.006857,0.000279,0.019019,0.000875,-0.011544,0.032104,-0.049929,0.059696,0.042415,-0.023916,-0.020173,0.022363,-0.016425,-0.354007,0.422410,0.017232,-0.106286,-0.032499,-0.045502,0.118053,0.090722,-0.246774,-0.000077,0.150527,0.029981,-0.074173,0.006982,0.007685,0.035762,0.018338,0.059439,0.029451,-0.012747,0.032325,-0.024156,0.006144,-0.004921,-0.007047,0.024916,-0.013464,-0.012810,0.004618,0.006305,0.017777,-0.037226,-0.018749,-0.026076,0.008026,-0.040668,-0.008455,-0.012120,-0.009955,-0.018018,0.006661,0.032070,0.001406,0.015931,0.020066,0.022360,-0.017343,-0.007000,-0.017683,-0.021564,-0.005667,-0.004897,0.022713,0.002352,0.021026,-0.020492,0.010265,0.006341,-0.062306,-0.031869,-0.004833,0.019042,0.034739,-0.048355,-0.072654,-0.066847,-0.074661,0.019525,0.081765,0.106477,-0.025839,-0.046011,0.091824,0.043276,0.026990,0.018548,0.002251,-0.006682,-0.005199,-0.051075,-0.003017,0.029777,-0.054537,-0.002321,0.044861,-0.018019,0.033038,0.036190,-0.042962,-0.033109,-0.031216,0.040022,-0.016626,-0.004321,-0.022597,0.001446,-0.018905,-0.015046,-0.006992,0.004125,0.000550,-0.011207,-0.006348,-0.005325,-0.023457,0.009404,0.021777,-0.001560,-0.021654,-0.010065,-0.041095,0.009058,-0.016847,0.014130,0.030820,0.014433,0.011400,0.017331,0.012039,-0.011976,-0.037318,-0.000059,0.013755,-0.023928,-0.033049,0.051293,-0.004679,0.075124,0.004404,-0.023162,-0.009870,0.008475,-0.011321,0.038668,-0.021760,0.017180,-0.003656,-0.004497,0.024860,-0.010259,-0.023728,-0.073984,0.014863,0.037362,-0.023343,0.010636,-0.008617,0.012118,0.033946,-0.033242,-0.018743,-0.029519,0.034794,-0.025605,0.008930,-0.006082,-0.003809,-0.002692,0.017623,-0.010778,-0.010494,0.004241,0.018071,0.015268,-0.027505,0.007476,0.058355,0.024457,0.010803,-0.030662,-0.001728,-0.001191,-0.040228,0.003914,0.019603,0.006112,-0.006858,0.006677,-0.036682,0.007404,-0.025808,-0.014273,-0.007471,0.014518,-0.012831,0.005292,-0.002303,-0.003711,-0.008705,0.000811,-0.012632,0.003962,0.004388,0.000392,0.002013,-0.028686,-0.003865,0.011868,0.012458,0.016571,0.009521,-0.001085,0.007509,0.021553,0.002596,0.005686,0.003029,-0.016085,0.005070,-0.006296,0.000888,0.002830,0.014467,0.006547,0.000059,-0.020972,0.009385,-0.014722,-0.008414,0.016377,-0.008301,-0.000710,-0.008819,0.006663,0.012456,0.012080,0.020719,0.008728,-0.007502,-0.021433,0.028223,-0.025323,-0.045761,-0.001697,0.002329,-0.042282,-0.017344
4,2026-03-05 15:46:39,DeepStateUA,0.048850,-0.006687,0.076040,-0.003924,-0.027197,0.089562,-0.088811,0.109836,0.052317,-0.025058,0.032393,-0.004227,-0.005032,-0.173462,0.094957,0.012582,-0.022470,-0.000701,-0.014110,-0.004739,-0.012713,0.127035,0.018404,-0.023593,0.003993,0.039285,-0.018524,0.000346,-0.081926,-0.045456,-0.116434,-0.028074,-0.013547,0.024679,0.046939,-0.021634,0.023138,0.009856,-0.025864,-0.041176,-0.000832,-0.024707,0.013634,-0.022765,0.057346,0.020489,0.010217,-0.026627,0.022514,0.022439,0.035388,-0.021224,0.008281,-0.000369,-0.015992,0.012876,-0.018086,-0.005188,-0.021093,0.012907,-0.008576,-0.008820,0.030578,0.014680,0.017475,0.007797,0.004474,-0.006686,0.023422,0.017913,0.009466,-0.011255,-0.006200,0.008317,-0.038521,0.017131,0.046956,0.005528,0.071628,0.044144,-0.006390,0.009272,-0.010302,-0.023798,0.013099,0.004949,0.000502,-0.025377,0.000576,0.005652,0.013762,-0.033165,0.011959,0.032019,-0.010729,0.074746,-0.045156,-0.069856,0.017151,-0.028899,-0.001317,-0.020143,-0.001444,0.077727,0.008474,0.017218,0.063803,0.022661,-0.019578,-0.089309,0.043190,0.054776,0.003839,0.005619,0.042291,-0.040703,0.034216,-0.018434,0.026249,-0.012015,0.004663,0.009540,0.028979,0.022277,0.015843,0.026390,-0.030022,-0.019719,0.008557,-0.006588,-0.012466,-0.013107,0.000680,-0.040800,0.018810,-0.018852,0.015615,-0.026299,-0.013060,-0.022985,-0.019649,0.003882,0.019573,0.020302,-0.053045,-0.013295,-0.013323,0.043432,-0.020309,-0.004050,-0.017728,-0.008395,-0.063169,-0.008017,0.060143,-0.036649,-0.009351,-0.031419,-0.019356,0.002941,0.015680,0.058794,0.034299,0.025507,0.026522,-0.024327,0.001476,-0.008036,-0.008201,0.018152,0.016011,-0.009222,0.020974,0.008694,-0.047264,0.028262,-0.002851,0.009422,-0.012002,0.004519,-0.010160,-0.031831,-0.005528,0.038708,-0.014277,0.009808,0.004059,-0.009500,0.033000,-0.038357,-0.005480,0.016188,-0.012154,-0.003113,0.007213,-0.049557,0.001337,0.025862,0.002217,0.009792,-0.002905,0.012793,-0.039633,-0.014680,0.012541,-0.026685,-0.057037,-0.038288,-0.031196,-0.025930,0.009651,0.004537,0.035687,-0.013257,0.015052,-0.006502,0.018667,-0.013956,0.023991,0.033361,-0.000124,-0.000186,0.012095,0.023317,0.014021,-0.007477,-0.006606,-0.045891,0.004310,-0.008439,0.004574,-0.039585,0.004941,0.010379,-0.002950,-0.053005,0.008541,-0.002762,0.010718,0.035433,0.017978,0.027453,-0.019744,0.008659,0.023139,-0.009485,-0.030263,0.013689,-0.022727,0.006843

In [25]:
df_tg_matrix["datetime_hour"] = pd.to_datetime(df_tg_matrix["date"]).dt.floor("h")

C:\Users\Uw11\AppData\Local\Temp\ipykernel_24900\2851151304.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_tg_matrix["datetime_hour"] = pd.to_datetime(df_tg_matrix["date"]).dt.floor("h")

In [26]:
topic_cols = [c for c in df_tg_matrix.columns if "tg_topic_" in c]

tg_hourly = (
    df_tg_matrix.groupby("datetime_hour")[topic_cols]
    .mean()
    .sort_index()
    .reset_index()
)

C:\Users\Uw11\AppData\Local\Temp\ipykernel_24900\2188712141.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  .reset_index()

In [27]:
df_tg_matrix.head()

,date,channel,tg_topic_0,tg_topic_1,tg_topic_2,tg_topic_3,tg_topic_4,tg_topic_5,tg_topic_6,tg_topic_7,tg_topic_8,tg_topic_9,tg_topic_10,tg_topic_11,tg_topic_12,tg_topic_13,tg_topic_14,tg_topic_15,tg_topic_16,tg_topic_17,tg_topic_18,tg_topic_19,tg_topic_20,tg_topic_21,tg_topic_22,tg_topic_23,tg_topic_24,tg_topic_25,tg_topic_26,tg_topic_27,tg_topic_28,tg_topic_29,tg_topic_30,tg_topic_31,tg_topic_32,tg_topic_33,tg_topic_34,tg_topic_35,tg_topic_36,tg_topic_37,tg_topic_38,tg_topic_39,tg_topic_40,tg_topic_41,tg_topic_42,tg_topic_43,tg_topic_44,tg_topic_45,tg_topic_46,tg_topic_47,tg_topic_48,tg_topic_49,tg_topic_50,tg_topic_51,tg_topic_52,tg_topic_53,tg_topic_54,tg_topic_55,tg_topic_56,tg_topic_57,tg_topic_58,tg_topic_59,tg_topic_60,tg_topic_61,tg_topic_62,tg_topic_63,tg_topic_64,tg_topic_65,tg_topic_66,tg_topic_67,tg_topic_68,tg_topic_69,tg_topic_70,tg_topic_71,tg_topic_72,tg_topic_73,tg_topic_74,tg_topic_75,tg_topic_76,tg_topic_77,tg_topic_78,tg_topic_79,tg_topic_80,tg_topic_81,tg_topic_82,tg_topic_83,tg_topic_84,tg_topic_85,tg_topic_86,tg_topic_87,tg_topic_88,tg_topic_89,tg_topic_90,tg_topic_91,tg_topic_92,tg_topic_93,tg_topic_94,tg_topic_95,tg_topic_96,tg_topic_97,tg_topic_98,tg_topic_99,tg_topic_100,tg_topic_101,tg_topic_102,tg_topic_103,tg_topic_104,tg_topic_105,tg_topic_106,tg_topic_107,tg_topic_108,tg_topic_109,tg_topic_110,tg_topic_111,tg_topic_112,tg_topic_113,tg_topic_114,tg_topic_115,tg_topic_116,tg_topic_117,tg_topic_118,tg_topic_119,tg_topic_120,tg_topic_121,tg_topic_122,tg_topic_123,tg_topic_124,tg_topic_125,tg_topic_126,tg_topic_127,tg_topic_128,tg_topic_129,tg_topic_130,tg_topic_131,tg_topic_132,tg_topic_133,tg_topic_134,tg_topic_135,tg_topic_136,tg_topic_137,tg_topic_138,tg_topic_139,tg_topic_140,tg_topic_141,tg_topic_142,tg_topic_143,tg_topic_144,tg_topic_145,tg_topic_146,tg_topic_147,tg_topic_148,tg_topic_149,tg_topic_150,tg_topic_151,tg_topic_152,tg_topic_153,tg_topic_154,tg_topic_155,tg_topic_156,tg_topic_157,tg_topic_158,tg_topic_159,tg_topic_160,tg_topic_161,tg_topic_162,tg_topic_163,tg_topic_164,tg_topic_165,tg_topic_166,tg_topic_167,tg_topic_168,tg_topic_169,tg_topic_170,tg_topic_171,tg_topic_172,tg_topic_173,tg_topic_174,tg_topic_175,tg_topic_176,tg_topic_177,tg_topic_178,tg_topic_179,tg_topic_180,tg_topic_181,tg_topic_182,tg_topic_183,tg_topic_184,tg_topic_185,tg_topic_186,tg_topic_187,tg_topic_188,tg_topic_189,tg_topic_190,tg_topic_191,tg_topic_192,tg_topic_193,tg_topic_194,tg_topic_195,tg_topic_196,tg_topic_197,tg_topic_198,tg_topic_199,tg_topic_200,tg_topic_201,tg_topic_202,tg_topic_203,tg_topic_204,tg_topic_205,tg_topic_206,tg_topic_207,tg_topic_208,tg_topic_209,tg_topic_210,tg_topic_211,tg_topic_212,tg_topic_213,tg_topic_214,tg_topic_215,tg_topic_216,tg_topic_217,tg_topic_218,tg_topic_219,tg_topic_220,tg_topic_221,tg_topic_222,tg_topic_223,tg_topic_224,tg_topic_225,tg_topic_226,tg_topic_227,tg_topic_228,tg_topic_229,tg_topic_230,tg_topic_231,tg_topic_232,tg_topic_233,tg_topic_234,tg_topic_235,tg_topic_236,tg_topic_237,tg_topic_238,tg_topic_239,tg_topic_240,tg_topic_241,tg_topic_242,tg_topic_243,tg_topic_244,tg_topic_245,tg_topic_246,tg_topic_247,tg_topic_248,tg_topic_249,datetime_hour
0,2026-03-06 13:06:58,DeepStateUA,0.007121,0.000107,0.019843,0.000990,-0.011395,0.032670,-0.050983,0.061080,0.042624,-0.024341,-0.018764,0.023404,-0.017137,-0.358836,0.425288,0.017966,-0.107660,-0.032066,-0.045986,0.118212,0.091172,-0.248637,-0.001069,0.150763,0.030603,-0.074030,0.005803,0.005871,0.034871,0.017239,0.058098,0.029814,-0.010845,0.031486,-0.022705,0.005607,-0.006324,-0.010169,0.024500,-0.015581,-0.012708,0.005139,0.007857,0.016734,-0.040289,-0.019688,-0.026763,0.009381,-0.043500,-0.009525,-0.013075,-0.010473,-0.018150,0.005988,0.032611,0.000850,0.017872,0.020885,0.023899,-0.019290,-0.006676,-0.018478,-0.023263,-0.005497,-0.006460,0.026051,0.004991,0.019687,-0.022244,0.010929,0.007016,-0.067349,-0.035249,-0.005686,0.018747,0.039159,-0.053868,-0.078189,-0.074737,-0.082163,0.020498,0.084336,0.113470,-0.025871,-0.048314,0.096330,0.043779,0.029575,0.019820,0.002819,-0.007308,-0.005234,-0.053796,-0.005893,0.036483,-0.061232,-0.001463,0.048285,-0.017340,0.033961,0.039046,-0.045463,-0.035894,-0.033875,0.041559,-0.021964,-0.005454,-0.020615,0.006442,-0.016322,-0.010443,-0.015532,0.000981,0.002928,-0.010924,-0.004072,-0.007252,-0.020386,0.007354,0.022114,-0.000884,-0.019901,-0.009325,-0.043505,0.008556,-0.016976,0.004765,0.030853,0.012413,0.011307,0.017726,0.010620,-0.013777,-0.037939,-0.003764,0.015808,-0.027407,-0.033773,0.054684,-0.005455,0.077819,0.006894,-0.022642,-0.011036,0.007590,-0.011639,0.036640,-0.020276,0.016764,-0.000467,-0.007996,0.023813,-0.014151,-0.026548,-0.078007,0.014955,0.043507,-0.021709,0.013392,-0.008661,0.012712,0.037409,-0.032628,-0.021403,-0.030711,0.033490,-0.025720,0.008100,-0.011149,-0.002706,0.002765,0.017707,-0.010806,-0.012850,0.007063,0.021780,0.010662,-0.031776,0.011750,0.069730,0.029703,0.012839,-0.031854,0.001635,-0.002149,-0.045445,0.002481,0.021315,0.006077,-0.006012,0.006578,-0.036587,0.009373,-0.025445,-0.019477,-0.011097,0.014675,-0.016785,0.010995,0.002045,-0.004600,-0.008963,0.006641,-0.017489,0.003821,0.005926,0.000537,-0.002830,-0.035321,-0.004957,0.013548,0.015414,0.018981,0.017932,-0.002853,0.007882,0.026621,0.003335,-0.001598,0.011594,-0.016659,0.001508,-0.007204,0.002975,0.001589,0.012191,0.005661,0.006600,-0.027472,0.014275,-0.020139,-0.011419,0.015111,-0.008120,0.001883,-0.011402,0.006871,0.024781,0.019495,0.024153,0.017141,-0.013944,-0.027516,0.034612,-0.032061,-0.051141,-0.004707,-0.003985,-0.052194,-0.026334,2026-03-06 13:00:00
1,2026-03-06 12:57:29,DeepStateUA,0.022770,-0.002163,0.041469,0.001527,-0.033584,0.077087,-0.078417,0.091534,0.014917,-0.016270,-0.019775,0.015028,-0.012900,-0.066689,0.049295,-0.031093,0.006109,-0.021357,-0.047947,0.025239,-0.010092,0.063969,0.026579,-0.002938,0.000962,-0.014692,-0.010761,0.001202,-0.015000,-0.005930,-0.010839,0.049023,-0.023754,0.030922,0.000492,-0.009320,-0.015764,0.024560,0.006807,-0.000411,-0.001480,-0.017302,-0.026282,0.007343,0.049168,-0.004316,0.029036,-0.034987,0.034368,-0.046229,-0.012751,0.048371,0.004354,-0.014649,0.034935,-0.016468,-0.013150,0.017354,-0.000886,0.004047,0.036549,-0.017461,0.009667,-0.007887,-0.027599,-0.016937,-0.037606,-0.009493,-0.002735,-0.006034,0.023060,0.028297,0.024781,0.010909,-0.000544,-0.016357,-0.003670,-0.016336,0.002609,0.013846,-0.005648,-0.012539,-0.007839,-0.041249,0.030814,-0.017629,-0.005069,-0.024100,-0.013485,0.010861,-0.015271,-0.006842,-0.013700,0.008861,-0.010810,0.022671,-0.034102,-0.016120,0.001828,0.003954,0.007680,-0.037762,-0.017967,0.016946,0.016302,-0.011406,0.021384,-0.001978,-0.005628,-0.080374,0.039484,0.015890,0.034496,-0.016936,0.004379,-0.005021,0.014321,-0.003484,-0.002882,-0.002483,-0.005047,0.017296,-0.003401,0.009433,-0.001665,0.018296,0.003151,-0.031688,0.003527,0.010405,-0.006932,-0.019232,-0.004084,-0.023476,-0.008857,-0.015648,0.053937,0.034130,-0.026430,0.018625,-0.050338,0.022854,-0.000992,0.001886,-0.013131,0.037482,0.025278,-0.008833,-0.009892,0.015771,-0.019763,-0.015569,-0.015169,0.040201,0.018226,0.018286,-0.011713,-0.000436,0.000451,0.012252,0.007596,-0.000338,0.004704,0.023604,-0.020461,0.016871,0.003246,-0.045373,0.004746,-0.036469,-0.025234,0.030737,-0.000797,0.015820,0.042129,0.010345,0.022695,0.005339,-0.001636,-0.018894,0.026074,-0.054026,-0.057851,0.004372,-0.020828,-0.034435,0.055865,0.016301,0.063019,0.010370,-0.004495,-0.030530,0.018833,-0.013644,0.002207,0.037501,-0.045908,-0.059514,-0.035367,-0.024918,-0.039085,0.035208,0.085963,0.009390,0.079267,0.013885,0.006535,-0.052116,-0.033637,0.008546,-0.019285,0.006149,0.002710,-0.056530,-0.022435,0.020384,-0.013988,-0.005111,-0.015295,-0.097911,-0.042214,0.020642,-0.042973,0.045024,0.005130,-0.022150,0.006530,0.054045,-0.042555,0.006345,-0.035607,-0.006021,0.000036,-0.033672,0.020923,-0.000556,-0.034840,0.034524,0.004798,0.001867,-0.019097,0.025730,0.000530,0.020332,-0.028041,0.001581,0.006948,-0.064965,0.022597,-0.017810,2026-03-06 12:00:00
2,2026-03-06 08:32:47,DeepStateUA,0.009647,-0.001083,0.029820,0.004092,-0.021362,0.053647,-0.076998,0.085930,0.011210,-0.020903,-0.051377,0.013232,-0.021159,0.001682,0.049129,-0.010018,-0.014271,-0.012423,-0.010588,0.046603,0.026875,0.002452,0.003347,-0.018525,0.005328,-0.003516,0.003550,0.018054,0.002157,0.012886,0.034851,0.000381,-0.009230,-0.002467,0.002381,0.000435,0.000842,-0.004257,-0.003348,0.009321,-0.005701,-0.004301,-0.016552,-0.001785,0.016005,0.008306,0.000706,-0.004439,-0.004069,-0.017177,-0.017974,-0.000361,-0.033317,-0.032714,0.027864,-0.006006,0.000665,-0.001117,-0.020576,0.002026,0.001386,0.000074,0.000035,0.007953,0.005774,0.005407,-0.005473,0.009134,-0.010858,-0.014439,0.028165,-0.023096,0.014483,0.021402,-0.017701,0.035852,-0.021296,-0.016145,-0.007317,-0.016939,0.014848,-0.006705,-0.047833,-0.002701,0.006144,-0.016566,0.016766,0.017487,0.002922,-0.004175,0.003020,-0.032485,0.001179,0.015611,0.015266,0.023711,0.005134,-0.030744,-0.014357,0.024034,0.016933,-0.044400,0.005215,0.011766,-0.026130,-0.005996,0.011388,-0.012677,-0.016358,-0.020579,-0.003119,-0.003134,0.019595,-0.011791,0.015521,0.022933,0.013426,0.013833,-0.006377,0.006772,-0.023631,0.008806,0.003886,0.014650,-0.029616,0.047030,0.005467,-0.020456,0.018529,-0.009387,0.010160,0.010283,-0.016104,0.038236,-0.028747,0.030649,0.028343,0.020708,0.001123,-0.009186,-0.064016,0.007831,0.005442,0.008333,-0.002820,0.007245,0.037716,-0.034047,0.009513,0.002276,-0.009623,-0.009046,0.023603,-0.009777,-0.047725,0.011991,-0.016423,0.004245,0.039250,0.030454,-0.007661,-0.043307,-0.005340,-0.003352,0.004921,0.010619,0.011745,-0.029661,-0.016769,-0.004054,-0.019134,-0.010521,-0.016018,0.013938,0.061204,0.000223,-0.016080,-0.013129,0.011080,0.025287,0.030597,-0.001902,-0.032930,0.022210,0.024393,-0.023036,0.001308,-0.010151,0.002527,0.003083,0.002821,0.012997,0.008941,-0.011744,0.019257,-0.000326,0.025398,-0.044011,-0.021810,-0.040764,-0.011043,0.008865,-0.020367,-0.005459,0.002685,0.019290,0.025485,-0.019258,-0.011527,-0.015354,-0.003904,0.007485,0.039596,0.030817,-0.034836,0.029725,0.018850,0.009886,0.006251,-0.006886,-0.028339,-0.017251,-0.019577,-0.004734,-0.014053,-0.014076,-0.018760,-0.006640,0.002467,-0.014727,0.015968,-0.020566,-0.000171,-0.020244,0.003823,-0.020505,-0.006361,-0.011117,-0.002427,0.036069,0.025378,-0.003550,-0.043415,-0.007200,-0.009172,0.006124,-0.004550,0.020576,0.010544,0.012825,2026-03-06 08:00:00
3,2026-03-05 16:46:58,DeepStateUA,0.006857,0.000279,0.019019,0.000875,-0.011544,0.032104,-0.049929,0.059696,0.042415,-0.023916,-0.020173,0.022363,-0.016425,-0.354007,0.422410,0.017232,-0.106286,-0.032499,-0.045502,0.118053,0.090722,-0.246774,-0.000077,0.150527,0.029981,-0.074173,0.006982,0.007685,0.035762,0.018338,0.059439,0.029451,-0.012747,0.032325,-0.024156,0.006144,-0.004921,-0.007047,0.024916,-0.013464,-0.012810,0.004618,0.006305,0.017777,-0.037226,-0.018749,-0.026076,0.008026,-0.040668,-0.008455,-0.012120,-0.009955,-0.018018,0.006661,0.032070,0.001406,0.015931,0.020066,0.022360,-0.017343,-0.007000,-0.017683,-0.021564,-0.005667,-0.004897,0.022713,0.002352,0.021026,-0.020492,0.010265,0.006341,-0.062306,-0.031869,-0.004833,0.019042,0.034739,-0.048355,-0.072654,-0.066847,-0.074661,0.019525,0.081765,0.106477,-0.025839,-0.046011,0.091824,0.043276,0.026990,0.018548,0.002251,-0.006682,-0.005199,-0.051075,-0.003017,0.029777,-0.054537,-0.002321,0.044861,-0.018019,0.033038,0.036190,-0.042962,-0.033109,-0.031216,0.040022,-0.016626,-0.004321,-0.022597,0.001446,-0.018905,-0.015046,-0.006992,0.004125,0.000550,-0.011207,-0.006348,-0.005325,-0.023457,0.009404,0.021777,-0.001560,-0.021654,-0.010065,-0.041095,0.009058,-0.016847,0.014130,0.030820,0.014433,0.011400,0.017331,0.012039,-0.011976,-0.037318,-0.000059,0.013755,-0.023928,-0.033049,0.051293,-0.004679,0.075124,0.004404,-0.023162,-0.009870,0.008475,-0.011321,0.038668,-0.021760,0.017180,-0.003656,-0.004497,0.024860,-0.010259,-0.023728,-0.073984,0.014863,0.037362,-0.023343,0.010636,-0.008617,0.012118,0.033946,-0.033242,-0.018743,-0.029519,0.034794,-0.025605,0.008930,-0.006082,-0.003809,-0.002692,0.017623,-0.010778,-0.010494,0.004241,0.018071,0.015268,-0.027505,0.007476,0.058355,0.024457,0.010803,-0.030662,-0.001728,-0.001191,-0.040228,0.003914,0.019603,0.006112,-0.006858,0.006677,-0.036682,0.007404,-0.025808,-0.014273,-0.007471,0.014518,-0.012831,0.005292,-0.002303,-0.003711,-0.008705,0.000811,-0.012632,0.003962,0.004388,0.000392,0.002013,-0.028686,-0.003865,0.011868,0.012458,0.016571,0.009521,-0.001085,0.007509,0.021553,0.002596,0.005686,0.003029,-0.016085,0.005070,-0.006296,0.000888,0.002830,0.014467,0.006547,0.000059,-0.020972,0.009385,-0.014722,-0.008414,0.016377,-0.008301,-0.000710,-0.008819,0.006663,0.012456,0.012080,0.020719,0.008728,-0.007502,-0.021433,0.028223,-0.025323,-0.045761,-0.001697,0.002329,-0.042282,-0.017344,2026-03-05 16:00:00
4,2026-03-05 15:46:39,DeepStateUA,0.048850,-0.006687,0.076040,-0.003924,-0.027197,0.089562,-0.088811,0.109836,0.052317,-0.025058,0.032393,-0.004227,-0.005032,-0.173462,0.094957,0.012582,-0.022470,-0.000701,-0.014110,-0.004739,-0.012713,0.127035,0.018404,-0.023593,0.003993,0.039285,-0.018524,0.000346,-0.081926,-0.045456,-0.116434,-0.028074,-0.013547,0.024679,0.046939,-0.021634,0.023138,0.009856,-0.025864,-0.041176,-0.000832,-0.024707,0.013634,-0.022765,0.057346,0.020489,0.010217,-0.026627,0.022514,0.022439,0.035388,-0.021224,0.008281,-0.000369,-0.015992,0.012876,-0.018086,-0.005188,-0.021093,0.012907,-0.008576,-0.008820,0.030578,0.014680,0.017475,0.007797,0.004474,-0.006686,0.023422,0.017913,0.009466,-0.011255,-0.006200,0.008317,-0.038521,0.017131,0.046956,0.005528,0.071628,0.044144,-0.006390,0.009272,-0.010302,-0.023798,0.013099,0.004949,0.000502,-0.025377,0.000576,0.005652,0.013762,-0.033165,0.011959,0.032019,-0.010729,0.074746,-0.045156,-0.069856,0.017151,-0.028899,-0.001317,-0.020143,-0.001444,0.077727,0.008474,0.017218,0.063803,0.022661,-0.019578,-0.089309,0.043190,0.054776,0.003839,0.005619,0.042291,-0.040703,0.034216,-0.018434,0.026249,-0.012015,0.004663,0.009540,0.028979,0.022277,0.015843,0.026390,-0.030022,-0.019719,0.008557,-0.006588,-0.012466,-0.013107,0.000680,-0.040800,0.018810,-0.018852,0.015615,-0.026299,-0.013060,-0.022985,-0.019649,0.003882,0.019573,0.020302,-0.053045,-0.013295,-0.013323,0.043432,-0.020309,-0.004050,-0.017728,-0.008395,-0.063169,-0.008017,0.060143,-0.036649,-0.009351,-0.031419,-0.019356,0.002941,0.015680,0.058794,0.034299,0.025507,0.026522,-0.024327,0.001476,-0.008036,-0.008201,0.018152,0.016011,-0.009222,0.020974,0.008694,-0.047264,0.028262,-0.002851,0.009422,-0.012002,0.004519,-0.010160,-0.031831,-0.005528,0.038708,-0.014277,0.009808,0.004059,-0.009500,0.033000,-0.038357,-0.005480,0.016188,-0.012154,-0.003113,0.007213,-0.049557,0.001337,0.025862,0.002217,0.009792,-0.002905,0.012793,-0.039633,-0.014680,0.012541,-0.026685,-0.057037,-0.038288,-0.031196,-0.025930,0.009651,0.004537,0.035687,-0.013257,0.015052,-0.006502,0.018667,-0.013956,0.023991,0.033361,-0.000124,-0.000186,0.012095,0.023317,0.014021,-0.007477,-0.006606,-0.045891,0.004310,-0.008439,0.004574,-0.039585,0.004941,0.010379,-0.002950,-0.053005,0.008541,-0.002762,0.010718,0.035433,0.017978,0.027453,-0.019744,0.008659,0.023139,-0.009485,-0.030263,0.013689,-0.022727,0.006843,2026-03-05 15:00:00

In [28]:
#tg_hourly["datetime_hour"] = tg_hourly["datetime_hour"] + pd.Timedelta(hours=1)        ТУТ ЗСУВ ТГ НА 1 ГОДИНУ

In [29]:
df_final = df_final.merge(tg_hourly, on="datetime_hour", how="left")

In [30]:
df_final.sample(20)

,datetime_hour,region_id,city_latitude,city_longitude,day_temp,day_dew,day_humidity,day_precip,day_precipprob,day_precipcover,day_snow,day_snowdepth,day_windgust,day_windspeed,day_winddir,day_pressure,day_cloudcover,day_solarradiation,day_solarenergy,day_uvindex,day_moonphase,hour_temp,hour_feelslike,hour_humidity,hour_precip,hour_precipprob,hour_snow,hour_windgust,hour_windspeed,hour_winddir,hour_pressure,hour_cloudcover,hour_solarradiation,hour_solarenergy,hour_uvindex,day_conditions_simple_Clear,day_conditions_simple_Cloudy,day_conditions_simple_Rain,day_conditions_simple_Snow,hour_conditions_simple_Clear,hour_conditions_simple_Cloudy,hour_conditions_simple_Rain,hour_conditions_simple_Snow,year,month,day_of_week,hour,city_name,city_timezone,day_datetime,day_sunrise,day_sunset,hour_datetime,region_key,alarm_active,alarm_minutes_in_hour,alarm_lag_1,alarm_lag_3,alarm_lag_6,alarm_lag_12,alarms_in_last_24h,is_weekend,is_night,total_active_alarms_lag1,neighbour_alarms,hours_since_last_alarm,isw_topic_0,isw_topic_1,isw_topic_2,isw_topic_3,isw_topic_4,isw_topic_5,isw_topic_6,isw_topic_7,isw_topic_8,isw_topic_9,isw_topic_10,isw_topic_11,isw_topic_12,isw_topic_13,isw_topic_14,isw_topic_15,isw_topic_16,isw_topic_17,isw_topic_18,isw_topic_19,isw_topic_20,isw_topic_21,isw_topic_22,isw_topic_23,isw_topic_24,isw_topic_25,isw_topic_26,isw_topic_27,isw_topic_28,isw_topic_29,isw_topic_30,isw_topic_31,isw_topic_32,isw_topic_33,isw_topic_34,isw_topic_35,isw_topic_36,isw_topic_37,isw_topic_38,isw_topic_39,isw_topic_40,isw_topic_41,isw_topic_42,isw_topic_43,isw_topic_44,isw_topic_45,isw_topic_46,isw_topic_47,isw_topic_48,isw_topic_49,isw_topic_50,isw_topic_51,isw_topic_52,isw_topic_53,isw_topic_54,isw_topic_55,isw_topic_56,isw_topic_57,isw_topic_58,isw_topic_59,isw_topic_60,isw_topic_61,isw_topic_62,isw_topic_63,isw_topic_64,isw_topic_65,isw_topic_66,isw_topic_67,isw_topic_68,isw_topic_69,isw_topic_70,isw_topic_71,isw_topic_72,isw_topic_73,isw_topic_74,isw_topic_75,isw_topic_76,isw_topic_77,isw_topic_78,isw_topic_79,isw_topic_80,isw_topic_81,isw_topic_82,isw_topic_83,isw_topic_84,isw_topic_85,isw_topic_86,isw_topic_87,isw_topic_88,isw_topic_89,isw_topic_90,isw_topic_91,isw_topic_92,isw_topic_93,isw_topic_94,isw_topic_95,isw_topic_96,isw_topic_97,isw_topic_98,isw_topic_99,isw_topic_100,isw_topic_101,isw_topic_102,isw_topic_103,isw_topic_104,isw_topic_105,isw_topic_106,isw_topic_107,isw_topic_108,isw_topic_109,isw_topic_110,isw_topic_111,isw_topic_112,isw_topic_113,isw_topic_114,isw_topic_115,isw_topic_116,isw_topic_117,isw_topic_118,isw_topic_119,isw_topic_120,isw_topic_121,isw_topic_122,isw_topic_123,isw_topic_124,isw_topic_125,isw_topic_126,isw_topic_127,isw_topic_128,isw_topic_129,isw_topic_130,isw_topic_131,isw_topic_132,isw_topic_133,isw_topic_134,isw_topic_135,isw_topic_136,isw_topic_137,isw_topic_138,isw_topic_139,isw_topic_140,isw_topic_141,isw_topic_142,isw_topic_143,isw_topic_144,isw_topic_145,isw_topic_146,isw_topic_147,isw_topic_148,isw_topic_149,isw_total_intensity,isw_topic_std,isw_topic_max,isw_topic_mean,isw_velocity_24h,isw_intensity_ema,isw_topic_entropy,tg_topic_0,tg_topic_1,tg_topic_2,tg_topic_3,tg_topic_4,tg_topic_5,tg_topic_6,tg_topic_7,tg_topic_8,tg_topic_9,tg_topic_10,tg_topic_11,tg_topic_12,tg_topic_13,tg_topic_14,tg_topic_15,tg_topic_16,tg_topic_17,tg_topic_18,tg_topic_19,tg_topic_20,tg_topic_21,tg_topic_22,tg_topic_23,tg_topic_24,tg_topic_25,tg_topic_26,tg_topic_27,tg_topic_28,tg_topic_29,tg_topic_30,tg_topic_31,tg_topic_32,tg_topic_33,tg_topic_34,tg_topic_35,tg_topic_36,tg_topic_37,tg_topic_38,tg_topic_39,tg_topic_40,tg_topic_41,tg_topic_42,tg_topic_43,tg_topic_44,tg_topic_45,tg_topic_46,tg_topic_47,tg_topic_48,tg_topic_49,tg_topic_50,tg_topic_51,tg_topic_52,tg_topic_53,tg_topic_54,tg_topic_55,tg_topic_56,tg_topic_57,tg_topic_58,tg_topic_59,tg_topic_60,tg_topic_61,tg_topic_62,tg_topic_63,tg_topic_64,tg_topic_65,tg_topic_66,tg_topic_67,tg_topic_68,tg_topic_69,tg_topic_70,tg_topic_71,tg_topic_72,tg_topic_73,tg_topic_74,tg_topic_75,tg_topic_76,tg_topic_77,tg_topic_78,tg_topic_79,tg_topic_80,tg_topic_81,tg_topic_82,tg_topic_83,tg_topic_84,tg_topic_85,tg_topic_86,tg_topic_87,tg_topic_88,tg_topic_89,tg_topic_90,tg_topic_91,tg_topic_92,tg_topic_93,tg_topic_94,tg_topic_95,tg_topic_96,tg_topic_97,tg_topic_98,tg_topic_99,tg_topic_100,tg_topic_101,tg_topic_102,tg_topic_103,tg_topic_104,tg_topic_105,tg_topic_106,tg_topic_107,tg_topic_108,tg_topic_109,tg_topic_110,tg_topic_111,tg_topic_112,tg_topic_113,tg_topic_114,tg_topic_115,tg_topic_116,tg_topic_117,tg_topic_118,tg_topic_119,tg_topic_120,tg_topic_121,tg_topic_122,tg_topic_123,tg_topic_124,tg_topic_125,tg_topic_126,tg_topic_127,tg_topic_128,tg_topic_129,tg_topic_130,tg_topic_131,tg_topic_132,tg_topic_133,tg_topic_134,tg_topic_135,tg_topic_136,tg_topic_137,tg_topic_138,tg_topic_139,tg_topic_140,tg_topic_141,tg_topic_142,tg_topic_143,tg_topic_144,tg_topic_145,tg_topic_146,tg_topic_147,tg_topic_148,tg_topic_149,tg_topic_150,tg_topic_151,tg_topic_152,tg_topic_153,tg_topic_154,tg_topic_155,tg_topic_156,tg_topic_157,tg_topic_158,tg_topic_159,tg_topic_160,tg_topic_161,tg_topic_162,tg_topic_163,tg_topic_164,tg_topic_165,tg_topic_166,tg_topic_167,tg_topic_168,tg_topic_169,tg_topic_170,tg_topic_171,tg_topic_172,tg_topic_173,tg_topic_174,tg_topic_175,tg_topic_176,tg_topic_177,tg_topic_178,tg_topic_179,tg_topic_180,tg_topic_181,tg_topic_182,tg_topic_183,tg_topic_184,tg_topic_185,tg_topic_186,tg_topic_187,tg_topic_188,tg_topic_189,tg_topic_190,tg_topic_191,tg_topic_192,tg_topic_193,tg_topic_194,tg_topic_195,tg_topic_196,tg_topic_197,tg_topic_198,tg_topic_199,tg_topic_200,tg_topic_201,tg_topic_202,tg_topic_203,tg_topic_204,tg_topic_205,tg_topic_206,tg_topic_207,tg_topic_208,tg_topic_209,tg_topic_210,tg_topic_211,tg_topic_212,tg_topic_213,tg_topic_214,tg_topic_215,tg_topic_216,tg_topic_217,tg_topic_218,tg_topic_219,tg_topic_220,tg_topic_221,tg_topic_222,tg_topic_223,tg_topic_224,tg_topic_225,tg_topic_226,tg_topic_227,tg_topic_228,tg_topic_229,tg_topic_230,tg_topic_231,tg_topic_232,tg_topic_233,tg_topic_234,tg_topic_235,tg_topic_236,tg_topic_237,tg_topic_238,tg_topic_239,tg_topic_240,tg_topic_241,tg_topic_242,tg_topic_243,tg_topic_244,tg_topic_245,tg_topic_246,tg_topic_247,tg_topic_248,tg_topic_249
243064,2022-09-12 20:00:00,11,48.50850,32.26560,13.6,12.2,92.0,3.500,100.0,20.83,0.0,0.0,24.1,18.0,294.1,1007.8,92.6,117.2,10.2,5.0,0.53,13.4,13.4,88.86,0.0,0.0,0.0,10.8,3.6,294.4,1008.0,73.7,0.0,0.1,0.0,False,False,True,False,False,True,False,False,2022,9,0,20,Kropyvnytskyi,Europe/Kiev,2022-09-12,06:23:09,19:10:32,20:00:00,Кіровоградська,0,0.000000,0.0,0.0,0.0,0.0,3.0,0,0,0.0,0.0,14,0.722567,-0.237187,0.142536,-0.129786,-0.013644,0.022875,-0.030947,0.014368,0.042024,-0.085822,0.002900,0.036138,0.176150,0.100158,-0.042746,0.114024,-0.130405,0.111836,0.053612,0.105586,0.083667,0.127156,-0.020567,0.032638,-0.026512,0.000810,0.045202,0.022044,0.066682,0.036028,-0.123175,-0.015384,0.036527,0.007314,0.019705,0.038988,0.001229,-0.012393,-0.048537,-0.027871,0.021424,0.066585,0.047073,0.058934,-0.026282,-0.034710,0.045914,-0.012279,-0.050970,0.068656,0.025252,-0.003868,-0.000658,0.014945,-0.053254,0.000116,0.045528,0.002090,-0.033025,0.032233,0.009121,0.001595,0.023466,-0.015156,0.011376,-0.001287,-0.007557,0.007390,0.019237,-0.009697,0.021228,0.015959,0.002884,-0.027827,0.000585,0.037097,-0.006172,-0.014435,-0.055912,-0.001816,0.016661,-0.030478,0.011284,-0.003828,-0.019138,0.003705,0.019091,-0.010366,0.031359,0.013142,-0.028592,0.018489,0.022979,0.016223,-0.012023,0.025425,-0.009437,0.004658,-0.045062,0.019485,-0.001526,-0.002335,-0.010714,-0.043968,0.025808,0.010079,-0.001030,-0.009518,-0.009729,-0.003306,0.019401,0.029032,-0.023590,0.000933,-0.038510,-0.021634,0.016597,-0.029054,0.016664,-0.025761,0.004116,-0.009703,0.019853,-0.037786,0.028323,-0.017254,-0.050420,0.026477,-0.040521,0.016251,0.033809,-0.040269,-0.020287,-0.004161,0.018765,0.046424,0.008660,-0.022087,-0.021452,-0.040838,0.004160,0.034454,-0.009007,0.008089,0.006917,0.010979,0.018967,0.008170,0.008573,0.001002,5.359717,0.066816,0.722567,0.035731,0.270773,5.287546,4.307745,0.006929,-0.000315,0.020365,0.002671,-0.019975,0.045990,-0.068473,0.076356,0.012196,-0.025027,-0.057541,0.008093,-0.015031,0.038392,0.009875,-0.038792,0.010375,-0.025692,-0.041745,0.051352,0.005792,0.044047,-0.003154,-0.028885,-0.004077,-0.000271,0.005880,0.003771,0.002517,0.012313,0.015092,-0.002242,-0.004143,0.006037,-0.007003,0.004930,0.004481,0.001914,0.002261,-0.000612,0.001006,0.006120,0.010128,0.008580,-0.017481,-0.007536,-0.003120,-0.000311,0.007879,-0.002336,0.009290,-0.003898,-0.003026,-0.011981,0.008365,-0.007785,-0.000989,-0.007773,-0.000036,-0.006279,0.014348,0.000380,-0.008253,-0.008530,0.002440,-0.008965,-0.013989,-0.002238,-0.005862,-0.003216,0.004728,-0.003624,0.009481,0.000839,0.000784,-0.000392,-0.007907,-0.006278,-0.012908,-0.018293,-0.003516,-0.000149,-0.002192,0.006450,-0.004707,0.002110,0.008297,-0.004117,-0.000653,-0.000255,0.003828,-0.012317,-0.000651,0.006722,0.006714,-0.008509,0.014849,0.003870,-0.002236,0.009949,0.000578,0.006220,0.000125,-0.010347,-0.017327,0.007800,-0.020214,-0.017534,-0.008066,0.018829,-0.008955,0.003100,0.001544,-0.015830,0.020985,-0.021504,0.031009,-0.006556,0.013585,-0.006004,0.006738,0.017396,0.036898,0.010654,-0.002842,-0.006843,-0.004843,-0.024374,0.001946,-0.000285,-0.003989,0.001041,-0.005559,0.003745,0.008875,-0.002721,0.000033,-0.000769,0.010296,-0.006456,-0.010109,0.006544,0.000613,-0.000419,-0.001194,-0.009679,0.001394,0.012078,-0.006299,0.009373,0.000640,0.004272,-0.020994,0.010335,0.001830,-0.001743,-0.010010,-0.006888,0.014806,0.027715,-0.022446,0.013842,-0.005088,0.000027,-0.003344,0.002842,-0.013661,0.004431,0.017545,-0.002862,-0.005005,0.021103,0.017547,-0.007996,0.018222,0.023140,-0.018217,-0.009065,-0.010615,0.011249,6.193775e-03,-2.077406e-03,-0.003370,-0.009924,-0.005586,0.025590,0.003214,0.000942,0.022109,-0.003112,-0.008278,0.009780,-0.017810,0.027290,0.009137,0.008422,0.016731,0.001077,-0.009311,0.029488,0.010210,-0.029530,-0.013012,-0.002407,-0.007541,-0.015871,-0.004703,0.027033,-0.002509,0.015792,-0.011552,0.007334,0.002394,-0.010772,-0.006181,-0.015822,-0.026824,0.002656,-0.010939,0.000440,0.016183,0.006126,0.028630,-0.015007,-0.026008,-0.005196,0.006914,0.012578,-0.003518,0.005153,-0.010940,0.005347,-0.012001,0.003254,0.003226,-0.018845,0.002268,0.003475,-0.004168,0.016068,-0.019669,-0.006542,-0.005483,-0.013545,-0.019309,0.026611,0.001578,-0.011012,-0.012765,-0.016683
72803,2024-05-30 20:00:00,4,48.47530,35.01600,18.4,12.6,72.4,0.400,100.0,4.17,0.0,0.0,32.0,15.1,178.5,1012.4,77.8,268.1,23.1,8.0,0.75,18.7,18.7,64.62,0.0,0.0,0.0,13.3,5.8,198.8,1012.0,100.0,58.7,0.2,1.0,False,False,True,False,False,True,False,False,2024,5,3,20,Dnipro,Europe/Kiev,2024-05-30,04:43:57,20:31:50,20:00:00,Дніпропетровська,1,4.933333,0.0,0.0,1.0,0.0,10.0,0,0,1.0,1.0,5,0.806011,0.000292,-0.135718,0.136213,-0.053678,-0.001551,0.019858,-0.060323,0.023970,-0.052357,-0.022007,0.040094,0.044123,-0.027425,-0.043855,0.078534,0.199286,0.041345,-0.027828,0.100711,-0.027292,-0.026799,0.000137,-0.028343,0.030290,-0.035855,-0.055011,0.020686,-0.066762,0.013361,-0.015396,0.038837,-0.061011,-0.052712,0.015592,0.087209,-0.016714,-0.051646,0.039801,0.000052,0.002829,0.027294,0.007469,-0.043493,-0.010727,0.000536,-0.019862,-0.033735,-0.004637,0.015393,-0.027656,-0.036205,-0.038947,-0.013834,0.018518,-0.100667,0.006536,0.002664,-0.037289,0.002258,-0.024799,0.028828,0.011185,-0.020765,-0.081670,0.027486,-0.005935,0.012761,-0.018552,-0.003449,0.007143,0.039248,-0.045758,0.005466,-0.009972,0.038516,0.046643,0.006217,-0.005808,-0.045566,0.011722,-0.031739,0.013268,-0.006251,-0.040291,0.026767,0.009441,-0.015399,0.004438,-0.004095,-0.009225,0.006585,-0.001404,0.022347,0.021163,0.010546,0.031721,0.003624,0.017011,-0.021819,0.005967,0.005682,0.016338,-0.030919,-0.027535,-0.032791,0.015605,0.012462,-0.038330,0.037555,-0.000963,0.012354,0.013899,0.008049,0.014880,-0.015652,-0.007698,0.017745,0.041972,-0.000210,-0.051772,0.045136,-0.000040,0.010448,0.037547,0.029836,0.046591,-0.009637,-0.000941,0.000821,0.027217,-0.036581,0.026144,-0.008942,-0.000267,0.018720,-0.010821,0.023443,0.029402,-0.016023,0.008932,-0.037868,0.017074,-0.003020,-0.005060,-0.008704,-0.002250,0.015346,-0.008125,-0.006572,4.743740,0.069430,0.806011,0.031625,-0.081706,4.784669,4.256025,0.060287,-0.010721,0.089104,-0.002742,-0.017258,0.067862,-0.036150,0.061211,-0.012188,-0.035357,-0.020086,0.006484,0.004511,-0.052954,-0.039096,0.006816,0.075751,-0.008183,-0.009086,0.047626,0.056861,0.084223,0.025986,0.059361,0.014305,0.017541,-0.039850,0.050857,-0.024841,0.002428,0.020221,0.017047,0.041672,-0.078630,-0.008360,-0.047494,-0.041928,0.053360,-0.008098,-0.006128,0.011305,0.003544,-0.033618,0.021932,-0.002554,-0.005211,-0.038162,-0.016037,0.032835,0.007916,-0.006215,0.057814,-0.000537,0.030537,0.042234,-0.009286,-0.007376,-0.033365,0.017620,-0.011351,0.026216,0.002969,-0.000192,0.004902,-0.000583,0.001111,-0.028623,-0.038385,-0.019333,-0.016392,-0.022082,0.018899,-0.000167,0.005768,0.010987,-0.016400,-0.006830,-0.006517,0.011484,-0.014504,-0.008166,-0.016684,0.052873,-0.015628,0.003201,-0.016878,-0.018874,-0.002715,-0.001544,-0.013286,-0.022289,0.009612,-0.005600,0.017431,-0.001247,-0.019027,0.054986,0.007224,-0.019521,0.036195,0.029429,-0.016895,0.023646,0.019153,0.006839,-0.020063,-0.024724,0.005323,0.016682,-0.007611,-0.016719,0.005038,-0.021660,-0.003896,-0.020178,-0.016351,0.032327,-0.003082,0.024499,0.002169,0.009005,0.013368,0.001397,-0.042599,0.039685,0.005316,0.025735,-0.007946,-0.013277,-0.005427,0.002335,-0.002897,0.025833,-0.017078,0.021410,0.012480,-0.021255,0.000638,-0.035814,-0.037254,0.008370,0.008565,0.021053,0.011627,0.008427,-0.025650,-0.003514,0.012118,0.000807,0.004199,-0.024359,0.010201,-0.027814,0.012990,0.019658,-0.012101,-0.025548,-0.000658,-0.010837,-0.008608,-0.010843,0.029773,0.013968,0.002690,0.018757,-0.008010,-0.002782,-0.021275,-0.007673,0.001943,0.001840,-0.011139,0.021083,0.004003,0.012300,0.001477,-0.010056,-0.010019,0.005893,0.003632,6.020704e-03,-3.636986e-02,0.016792,0.002361,-0.021343,0.005363,0.026433,0.022571,0.014332,-0.000109,0.006637,-0.016767,-0.020116,0.019223,0.002133,-0.032766,0.010304,0.007418,-0.005919,0.001067,0.001829,-0.012758,-0.004070,0.009665,-0.020827,-0.015498,0.001297,0.007073,-0.010435,0.011532,-0.008663,0.002333,0.016065,-0.016530,-0.004627,0.000757,-0.017828,-0.003316,0.017335,0.018714,0.011541,-0.025310,0.017279,0.009112,0.004829,-0.006182,0.006763,-0.014172,-0.022416,0.000925,-0.021093,0.003254,-0.007640,-0.001984,0.012611,0.005411,-0.009671,-0.006242,-0.007389,0.010109,0.007815,-0.006559,0.002975,-0.012534,-0.005364,0.006329,0.026755,0.012061,0.002962,0.006416
489435,2023-08-18 11:00:00,21,46.64010,32.61420,26.1,15.3,54.3,0.000,0.0,0.00,0.0,0.0,36.0,18.0,36.8,1018.0,15.4,271.4,23.5,8.0,0.07,30.4,29.9,38.75,0.0,0.0,0.0,34.6,16.6,54.8,1018.0,0.0,652.6,2.3,7.0,True,False,False,False,True,False,False,False,2023,8,4,11,Kherson,Europe/Kiev,2023-08-18,05:50:48,19:55:23,11:00:00,Херсонська,0,0.000000,0.0,0.0,0.0,1.0,7.0,0,0,2.0,1.0,11,0.792229,-0.155609,-0.050891,-0.134323,-0.147059,0.102280,-0.018508,0.151997,0.146244,-0.070303,0.114076,-0.001984,-0.119086,-0.094422,-0.003480,-0.114265,0.037209,0.049766,0.056688,-0.077392,-0.022948,-0.033323,-0.015362,0.062963,0.024513,-0.012185,-0.002811,0.070226,0.008904,0.014437,-0.021942,0.051353,-0.020388,-0.017133,-0.040917,-0.000437,0.043428,0.003739,-0.004210,-0.021351,-0.016546,0.000138,-0.021394,-0.000862,0.008470,0.001621,0.024409,0.023150,-0.023717,-0.041703,0.005117,0.018760,-0.040169,-0.010524,0.037917,0.020514,-0.007007,0.010771,-0.048954,0.025494,-0.015487,-0.035430,0.002251,-0.005524,-0.014687,-0.014755,-0.008120,0.013704,-0.005737,0.012029,0.018743,0.029086,-0.004436,-0.013079,0.032479,-0.039180,-0.030292,0.006497,-0.023022,0.006543,0.013747,0.016828,-0.020763,0.016425,0.003538,-0.006810,0.013783,-0.014870,-0.007806,0.034070,-0.000768,-0.003746,0.001185,0.022962,0.004743,-0.015018,0.015682,-0.000953,0.002457,-0.004625,0.003218,-0.009673,-0.003653,0.011865,0.012205,0.004856,-0.028745,-0.017859,0.009168,0.004217,0.018400,-0.002411,-0.013731,0.009000,-0.011935,0.037827,-0.006671,-0.004093,0.012062,0.012666,0.002062,-0.024594,0.015076,-0.004810,0.006965,0.003933,-0.012714,0.044435,0.005349,-0.011492,-0.007815,-0.007638,0.044806,0.005397,-0.007935,-0.003944,-0.023221,0.000838,0.018992,-0.031632,-0.014463,-0.006950,-0.019120,0.011050,0.023140,-0.000467,-0.007746,0.033968,-0.006249,0.008505,4.519040,0.070357,0.792229,0.030127,0.049529,4.519419,4.118684,0.039194,0.004754,0.055854,-0.005525,-0.060669,0.143352,0.000444,0.002292,-0.009083,-0.087453,-0.022678,0.005126,-0.016728,0.018915,0.018605,-0.025152,-0.023865,-0.014816,-0.040261,0.051953,0.013123,0.044059,0.022087,0.013328,0.004627,-0.013034,-0.037084,0.023759,0.008233,0.014821,0.020535,-0.008665,-0.002736,0.028885,0.042566,-0.004861,0.054012,0.011972,-0.020178,0.003579,-0.010689,0.008615,0.009074,0.011666,-0.006309,0.003476,-0.020372,-0.003306,-0.011102,0.025551,0.008407,-0.011232,-0.000180,0.029396,-0.012552,-0.011052,-0.005489,-0.003176,-0.002375,-0.004559,-0.003731,-0.029392,0.000405,-0.005695,0.004530,-0.000582,-0.022398,0.018817,-0.014761,-0.001101,0.021345,-0.009326,0.008198,0.013332,-0.022420,0.026426,0.010431,0.001135,0.003622,-0.008222,0.001042,0.004454,-0.015124,-0.016420,0.008384,0.001361,-0.014588,0.002713,-0.000197,0.018093,-0.003132,-0.001163,-0.002260,0.005282,-0.002921,0.011423,-0.004932,-0.001127,0.001410,0.000180,0.000063,-0.004694,-0.006107,0.002580,0.002255,0.000565,0.001455,-0.000898,-0.007071,0.003150,0.015785,-0.010310,0.003699,-0.006346,0.016688,-0.008942,0.011529,0.006050,-0.006550,-0.006556,0.002680,0.011824,0.018101,0.003708,-0.006726,0.003365,-0.001559,-0.007664,-0.003756,0.000396,-0.001273,-0.002193,0.005928,-0.012728,0.003549,-0.009800,0.003112,-0.018873,-0.000425,-0.004400,-0.008076,-0.011544,-0.006608,0.000230,-0.001776,-0.011823,0.001893,0.021229,0.010032,0.005049,0.018543,-0.009297,-0.015546,-0.017350,-0.011892,-0.022221,-0.005153,-0.021017,-0.022345,-0.001373,-0.019428,0.013594,-0.001356,0.009785,-0.018786,-0.028185,0.004113,0.014852,0.030937,0.012973,0.028225,-0.046583,-0.014237,0.011816,0.005631,-0.003009,-0.008511,-0.003952,-0.026150,0.007945,-4.499442e-03,-1.823212e-02,0.023390,0.057563,-0.032785,0.051135,0.011528,-0.019116,0.013902,-0.022907,-0.035311,-0.000955,0.032698,-0.011541,0.004131,-0.021228,0.003950,-0.005083,-0.013909,0.023739,-0.015191,-0.010192,0.025547,-0.010547,0.029328,0.007464,0.011388,0.013301,-0.006250,0.004437,0.007612,-0.025664,-0.011107,-0.004608,0.002026,-0.012864,0.010721,0.023781,-0.013522,0.000889,-0.017291,-0.024049,0.005615,0.006622,-0.006604,-0.022065,0.002806,-0.024589,-0.014839,0.006147,-0.004456,-0.019429,0.002516,0.016791,0.003331,0.003464,-0.010673,-0.008597,-0.027850,-0.002194,-0.010999,0.014992,0.005473,-0.002363,0.001340,-0.002218,0.002962,-0.010620,0.000617,-0.014171

In [31]:
df_final.shape

(635256, 473)

In [32]:
df_final = df_final.sort_values(["datetime_hour"])

In [33]:
with pd.option_context('display.max_rows', None):
    print(df_final.isnull().sum())

datetime_hour                         0
region_id                             0
city_latitude                         0
city_longitude                        0
day_temp                              0
day_dew                               0
day_humidity                          0
day_precip                            0
day_precipprob                        0
day_precipcover                       0
day_snow                              0
day_snowdepth                         0
day_windgust                          0
day_windspeed                         0
day_winddir                           0
day_pressure                          0
day_cloudcover                        0
day_solarradiation                    0
day_solarenergy                       0
day_uvindex                           0
day_moonphase                         0
hour_temp                             0
hour_feelslike                        0
hour_humidity                         0
hour_precip                           0
hour_precipprob                       0
hour_snow                             0
hour_windgust                         0
hour_windspeed                        0
hour_winddir                          0
hour_pressure                         0
hour_cloudcover                       0
hour_solarradiation                   0
hour_solarenergy                      0
hour_uvindex                          0
day_conditions_simple_Clear           0
day_conditions_simple_Cloudy          0
day_conditions_simple_Rain            0
day_conditions_simple_Snow            0
hour_conditions_simple_Clear          0
hour_conditions_simple_Cloudy         0
hour_conditions_simple_Rain           0
hour_conditions_simple_Snow           0
year                                  0
month                                 0
day_of_week                           0
hour                                  0
city_name                             0
city_timezone                         0
day_datetime                          0
day_sunrise                           0
day_sunset                            0
hour_datetime                         0
region_key                            0
alarm_active                          0
alarm_minutes_in_hour                 0
alarm_lag_1                           0
alarm_lag_3                           0
alarm_lag_6                           0
alarm_lag_12                          0
alarms_in_last_24h                    0
is_weekend                            0
is_night                              0
total_active_alarms_lag1              0
neighbour_alarms                      0
hours_since_last_alarm                0
isw_topic_0                           0
isw_topic_1                           0
isw_topic_2                           0
isw_topic_3                           0
isw_topic_4                           0
isw_topic_5                           0
isw_topic_6                           0
isw_topic_7                           0
isw_topic_8                           0
isw_topic_9                           0
isw_topic_10                          0
isw_topic_11                          0
isw_topic_12                          0
isw_topic_13                          0
isw_topic_14                          0
isw_topic_15                          0
isw_topic_16                          0
isw_topic_17                          0
isw_topic_18                          0
isw_topic_19                          0
isw_topic_20                          0
isw_topic_21                          0
isw_topic_22                          0
isw_topic_23                          0
isw_topic_24                          0
isw_topic_25                          0
isw_topic_26                          0
isw_topic_27                          0
isw_topic_28                          0
isw_topic_29                          0
isw_topic_30                          0
isw_topic_31                          0
isw_topic_32                          0
isw_topic_33                          0
isw_topic_34                          0
isw_topic_35                          0
isw_topic_36                          0
isw_topic_37                          0
isw_topic_38                          0
isw_topic_39                          0
isw_topic_40                          0
isw_topic_41                          0
isw_topic_42                          0
isw_topic_43                          0
isw_topic_44                          0
isw_topic_45                          0
isw_topic_46                          0
isw_topic_47                          0
isw_topic_48                          0
isw_topic_49                          0
isw_topic_50                          0
isw_topic_51                          0
isw_topic_52                          0
isw_topic_53                          0
isw_topic_54                          0
isw_topic_55                          0
isw_topic_56                          0
isw_topic_57                          0
isw_topic_58                          0
isw_topic_59                          0
isw_topic_60                          0
isw_topic_61                          0
isw_topic_62                          0
isw_topic_63                          0
isw_topic_64                          0
isw_topic_65                          0
isw_topic_66                          0
isw_topic_67                          0
isw_topic_68                          0
isw_topic_69                          0
isw_topic_70                          0
isw_topic_71                          0
isw_topic_72                          0
isw_topic_73                          0
isw_topic_74                          0
isw_topic_75                          0
isw_topic_76                          0
isw_topic_77                          0
isw_topic_78                          0
isw_topic_79                          0
isw_topic_80                          0
isw_topic_81                          0
isw_topic_82                          0
isw_topic_83                          0
isw_topic_84                          0
isw_topic_85                          0
isw_topic_86                          0
isw_topic_87                          0
isw_topic_88                          0
isw_topic_89                          0
isw_topic_90                          0
isw_topic_91                          0
isw_topic_92                          0
isw_topic_93                          0
isw_topic_94                          0
isw_topic_95                          0
isw_topic_96                          0
isw_topic_97                          0
isw_topic_98                          0
isw_topic_99                          0
isw_topic_100                         0
isw_topic_101                         0
isw_topic_102                         0
isw_topic_103                         0
isw_topic_104                         0
isw_topic_105                         0
isw_topic_106                         0
isw_topic_107                         0
isw_topic_108                         0
isw_topic_109                         0
isw_topic_110                         0
isw_topic_111                         0
isw_topic_112                         0
isw_topic_113                         0
isw_topic_114                         0
isw_topic_115                         0
isw_topic_116                         0
isw_topic_117                         0
isw_topic_118                         0
isw_topic_119                         0
isw_topic_120                         0
isw_topic_121                         0
isw_topic_122                         0
isw_topic_123                         0
isw_topic_124                         0
isw_topic_125                         0
isw_topic_126                         0
isw_topic_127                         0
isw_topic_128                         0
isw_topic_129                         0
isw_topic_130                         0
isw_topic_131                         0
isw_topic_132                         0
isw_topic_133                         0
isw_topic_134                         0
isw_topic_135                         0
isw_topic_136                         0
isw_topic_137                         0
isw_topic_138                         0
isw_topic_139                         0
isw_topic_140                         0
isw_topic_141                         0
isw_topic_142                         0
isw_topic_143                         0
isw_topic_144                         0
isw_topic_145                         0
isw_topic_146                         0
isw_topic_147                         0
isw_topic_148                         0
isw_topic_149                         0
isw_total_intensity                   0
isw_topic_std                         0
isw_topic_max                         0
isw_topic_mean                        0
isw_velocity_24h                      0
isw_intensity_ema                     0
isw_topic_entropy                     0
tg_topic_0                       121728
tg_topic_1                       121728
tg_topic_2                       121728
tg_topic_3                       121728
tg_topic_4                       121728
tg_topic_5                       121728
tg_topic_6                       121728
tg_topic_7                       121728
tg_topic_8                       121728
tg_topic_9                       121728
tg_topic_10                      121728
tg_topic_11                      121728
tg_topic_12                      121728
tg_topic_13                      121728
tg_topic_14                      121728
tg_topic_15                      121728
tg_topic_16                      121728
tg_topic_17                      121728
tg_topic_18                      121728
tg_topic_19                      121728
tg_topic_20                      121728
tg_topic_21                      121728
tg_topic_22                      121728
tg_topic_23                      121728
tg_topic_24                      121728
tg_topic_25                      121728
tg_topic_26                      121728
tg_topic_27                      121728
tg_topic_28                      121728
tg_topic_29                      121728
tg_topic_30                      121728
tg_topic_31                      121728
tg_topic_32                      121728
tg_topic_33                      121728
tg_topic_34                      121728
tg_topic_35                      121728
tg_topic_36                      121728
tg_topic_37                      121728
tg_topic_38                      121728
tg_topic_39                      121728
tg_topic_40                      121728
tg_topic_41                      121728
tg_topic_42                      121728
tg_topic_43                      121728
tg_topic_44                      121728
tg_topic_45                      121728
tg_topic_46                      121728
tg_topic_47                      121728
tg_topic_48                      121728
tg_topic_49                      121728
tg_topic_50                      121728
tg_topic_51                      121728
tg_topic_52                      121728
tg_topic_53                      121728
tg_topic_54                      121728
tg_topic_55                      121728
tg_topic_56                      121728
tg_topic_57                      121728
tg_topic_58                      121728
tg_topic_59                      121728
tg_topic_60                      121728
tg_topic_61                      121728
tg_topic_62                      121728
tg_topic_63                      121728
tg_topic_64                      121728
tg_topic_65                      121728
tg_topic_66                      121728
tg_topic_67                      121728
tg_topic_68                      121728
tg_topic_69                      121728
tg_topic_70                      121728
tg_topic_71                      121728
tg_topic_72                      121728
tg_topic_73                      121728
tg_topic_74                      121728
tg_topic_75                      121728
tg_topic_76                      121728
tg_topic_77                      121728
tg_topic_78                      121728
tg_topic_79                      121728
tg_topic_80                      121728
tg_topic_81                      121728
tg_topic_82                      121728
tg_topic_83                      121728
tg_topic_84                      121728
tg_topic_85                      121728
tg_topic_86                      121728
tg_topic_87                      121728
tg_topic_88                      121728
tg_topic_89                      121728
tg_topic_90                      121728
tg_topic_91                      121728
tg_topic_92                      121728
tg_topic_93                      121728
tg_topic_94                      121728
tg_topic_95                      121728
tg_topic_96                      121728
tg_topic_97                      121728
tg_topic_98                      121728
tg_topic_99                      121728
tg_topic_100                     121728
tg_topic_101                     121728
tg_topic_102                     121728
tg_topic_103                     121728
tg_topic_104                     121728
tg_topic_105                     121728
tg_topic_106                     121728
tg_topic_107                     121728
tg_topic_108                     121728
tg_topic_109                     121728
tg_topic_110                     121728
tg_topic_111                     121728
tg_topic_112                     121728
tg_topic_113                     121728
tg_topic_114                     121728
tg_topic_115                     121728
tg_topic_116                     121728
tg_topic_117                     121728
tg_topic_118                     121728
tg_topic_119                     121728
tg_topic_120                     121728
tg_topic_121                     121728
tg_topic_122                     121728
tg_topic_123                     121728
tg_topic_124                     121728
tg_topic_125                     121728
tg_topic_126                     121728
tg_topic_127                     121728
tg_topic_128                     121728
tg_topic_129                     121728
tg_topic_130                     121728
tg_topic_131                     121728
tg_topic_132                     121728
tg_topic_133                     121728
tg_topic_134                     121728
tg_topic_135                     121728
tg_topic_136                     121728
tg_topic_137                     121728
tg_topic_138                     121728
tg_topic_139                     121728
tg_topic_140                     121728
tg_topic_141                     121728
tg_topic_142                     121728
tg_topic_143                     121728
tg_topic_144                     121728
tg_topic_145                     121728
tg_topic_146                     121728
tg_topic_147                     121728
tg_topic_148                     121728
tg_topic_149                     121728
tg_topic_150                     121728
tg_topic_151                     121728
tg_topic_152                     121728
tg_topic_153                     121728
tg_topic_154                     121728
tg_topic_155                     121728
tg_topic_156                     121728
tg_topic_157                     121728
tg_topic_158                     121728
tg_topic_159                     121728
tg_topic_160                     121728
tg_topic_161                     121728
tg_topic_162                     121728
tg_topic_163                     121728
tg_topic_164                     121728
tg_topic_165                     121728
tg_topic_166                     121728
tg_topic_167                     121728
tg_topic_168                     121728
tg_topic_169                     121728
tg_topic_170                     121728
tg_topic_171                     121728
tg_topic_172                     121728
tg_topic_173                     121728
tg_topic_174                     121728
tg_topic_175                     121728
tg_topic_176                     121728
tg_topic_177                     121728
tg_topic_178                     121728
tg_topic_179                     121728
tg_topic_180                     121728
tg_topic_181                     121728
tg_topic_182                     121728
tg_topic_183                     121728
tg_topic_184                     121728
tg_topic_185                     121728
tg_topic_186                     121728
tg_topic_187                     121728
tg_topic_188                     121728
tg_topic_189                     121728
tg_topic_190                     121728
tg_topic_191                     121728
tg_topic_192                     121728
tg_topic_193                     121728
tg_topic_194                     121728
tg_topic_195                     121728
tg_topic_196                     121728
tg_topic_197                     121728
tg_topic_198                     121728
tg_topic_199                     121728
tg_topic_200                     121728
tg_topic_201                     121728
tg_topic_202                     121728
tg_topic_203                     121728
tg_topic_204                     121728
tg_topic_205                     121728
tg_topic_206                     121728
tg_topic_207                     121728
tg_topic_208                     121728
tg_topic_209                     121728
tg_topic_210                     121728
tg_topic_211                     121728
tg_topic_212                     121728
tg_topic_213                     121728
tg_topic_214                     121728
tg_topic_215                     121728
tg_topic_216                     121728
tg_topic_217                     121728
tg_topic_218                     121728
tg_topic_219                     121728
tg_topic_220                     121728
tg_topic_221                     121728
tg_topic_222                     121728
tg_topic_223                     121728
tg_topic_224                     121728
tg_topic_225                     121728
tg_topic_226                     121728
tg_topic_227                     121728
tg_topic_228                     121728
tg_topic_229                     121728
tg_topic_230                     121728
tg_topic_231                     121728
tg_topic_232                     121728
tg_topic_233                     121728
tg_topic_234                     121728
tg_topic_235                     121728
tg_topic_236                     121728
tg_topic_237                     121728
tg_topic_238                     121728
tg_topic_239                     121728
tg_topic_240                     121728
tg_topic_241                     121728
tg_topic_242                     121728
tg_topic_243                     121728
tg_topic_244                     121728
tg_topic_245                     121728
tg_topic_246                     121728
tg_topic_247                     121728
tg_topic_248                     121728
tg_topic_249                     121728
dtype: int64

In [34]:
df_final = df_final.fillna(0)

In [35]:
tg_cols = [c for c in df_final.columns if 'tg_topic_' in c]
df_tg_abs = df_final[tg_cols].abs()

df_final['tg_total_intensity'] = df_tg_abs.sum(axis=1)
df_final['tg_topic_std'] = df_tg_abs.std(axis=1)
df_final['tg_topic_max'] = df_tg_abs.max(axis=1)
df_final['tg_topic_entropy'] = -(df_tg_abs.div(df_tg_abs.sum(axis=1), axis=0) * np.log(df_tg_abs.div(df_tg_abs.sum(axis=1), axis=0) + 1e-9)).sum(axis=1)

C:\Users\Uw11\AppData\Local\Temp\ipykernel_24900\409095542.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_final['tg_total_intensity'] = df_tg_abs.sum(axis=1)
C:\Users\Uw11\AppData\Local\Temp\ipykernel_24900\409095542.py:5: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_final['tg_topic_std'] = df_tg_abs.std(axis=1)
C:\Users\Uw11\AppData\Local\Temp\ipykernel_24900\409095542.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_final['tg_topic_max'] = df_tg_abs.max(axis=1)
C:\Users\Uw11\AppData\Local\Temp\ipykernel_24900\409095542.py:7: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_final['tg_topic_entropy'] = -(df_tg_abs.div(df_tg_abs.sum(axis=1), axis=0) * np.log(df_tg_abs.div(df_tg_abs.sum(axis=1), axis=0) + 1e-9)).sum(axis=1)

In [36]:
df_final['tg_velocity_3h'] = (df_final.groupby('region_id')['tg_total_intensity'].diff(3).fillna(0))
df_final['tg_intensity_ema_6h'] = (df_final.groupby('region_id')['tg_total_intensity'].transform(lambda x: x.ewm(span=6).mean()))
df_final['tg_intensity_zscore'] = (df_final.groupby('region_id')['tg_total_intensity'].transform(lambda x: (x - x.rolling(24, min_periods=1).mean()) / (x.rolling(24, min_periods=1).std() + 1e-9)))

C:\Users\Uw11\AppData\Local\Temp\ipykernel_24900\3857173777.py:1: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_final['tg_velocity_3h'] = (df_final.groupby('region_id')['tg_total_intensity'].diff(3).fillna(0))
C:\Users\Uw11\AppData\Local\Temp\ipykernel_24900\3857173777.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_final['tg_intensity_ema_6h'] = (df_final.groupby('region_id')['tg_total_intensity'].transform(lambda x: x.ewm(span=6).mean()))
C:\Users\Uw11\AppData\Local\Temp\ipykernel_24900\3857173777.py:3: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df_final['tg_intensity_zscore'] = (df_final.groupby('region_id')['tg_total_intensity'].transform(lambda x: (x - x.rolling(24, min_periods=1).mean()) / (x.rolling(24, min_periods=1).std() + 1e-9)))

In [37]:
df_final.sample(20)

,datetime_hour,region_id,city_latitude,city_longitude,day_temp,day_dew,day_humidity,day_precip,day_precipprob,day_precipcover,day_snow,day_snowdepth,day_windgust,day_windspeed,day_winddir,day_pressure,day_cloudcover,day_solarradiation,day_solarenergy,day_uvindex,day_moonphase,hour_temp,hour_feelslike,hour_humidity,hour_precip,hour_precipprob,hour_snow,hour_windgust,hour_windspeed,hour_winddir,hour_pressure,hour_cloudcover,hour_solarradiation,hour_solarenergy,hour_uvindex,day_conditions_simple_Clear,day_conditions_simple_Cloudy,day_conditions_simple_Rain,day_conditions_simple_Snow,hour_conditions_simple_Clear,hour_conditions_simple_Cloudy,hour_conditions_simple_Rain,hour_conditions_simple_Snow,year,month,day_of_week,hour,city_name,city_timezone,day_datetime,day_sunrise,day_sunset,hour_datetime,region_key,alarm_active,alarm_minutes_in_hour,alarm_lag_1,alarm_lag_3,alarm_lag_6,alarm_lag_12,alarms_in_last_24h,is_weekend,is_night,total_active_alarms_lag1,neighbour_alarms,hours_since_last_alarm,isw_topic_0,isw_topic_1,isw_topic_2,isw_topic_3,isw_topic_4,isw_topic_5,isw_topic_6,isw_topic_7,isw_topic_8,isw_topic_9,isw_topic_10,isw_topic_11,isw_topic_12,isw_topic_13,isw_topic_14,isw_topic_15,isw_topic_16,isw_topic_17,isw_topic_18,isw_topic_19,isw_topic_20,isw_topic_21,isw_topic_22,isw_topic_23,isw_topic_24,isw_topic_25,isw_topic_26,isw_topic_27,isw_topic_28,isw_topic_29,isw_topic_30,isw_topic_31,isw_topic_32,isw_topic_33,isw_topic_34,isw_topic_35,isw_topic_36,isw_topic_37,isw_topic_38,isw_topic_39,isw_topic_40,isw_topic_41,isw_topic_42,isw_topic_43,isw_topic_44,isw_topic_45,isw_topic_46,isw_topic_47,isw_topic_48,isw_topic_49,isw_topic_50,isw_topic_51,isw_topic_52,isw_topic_53,isw_topic_54,isw_topic_55,isw_topic_56,isw_topic_57,isw_topic_58,isw_topic_59,isw_topic_60,isw_topic_61,isw_topic_62,isw_topic_63,isw_topic_64,isw_topic_65,isw_topic_66,isw_topic_67,isw_topic_68,isw_topic_69,isw_topic_70,isw_topic_71,isw_topic_72,isw_topic_73,isw_topic_74,isw_topic_75,isw_topic_76,isw_topic_77,isw_topic_78,isw_topic_79,isw_topic_80,isw_topic_81,isw_topic_82,isw_topic_83,isw_topic_84,isw_topic_85,isw_topic_86,isw_topic_87,isw_topic_88,isw_topic_89,isw_topic_90,isw_topic_91,isw_topic_92,isw_topic_93,isw_topic_94,isw_topic_95,isw_topic_96,isw_topic_97,isw_topic_98,isw_topic_99,isw_topic_100,isw_topic_101,isw_topic_102,isw_topic_103,isw_topic_104,isw_topic_105,isw_topic_106,isw_topic_107,isw_topic_108,isw_topic_109,isw_topic_110,isw_topic_111,isw_topic_112,isw_topic_113,isw_topic_114,isw_topic_115,isw_topic_116,isw_topic_117,isw_topic_118,isw_topic_119,isw_topic_120,isw_topic_121,isw_topic_122,isw_topic_123,isw_topic_124,isw_topic_125,isw_topic_126,isw_topic_127,isw_topic_128,isw_topic_129,isw_topic_130,isw_topic_131,isw_topic_132,isw_topic_133,isw_topic_134,isw_topic_135,isw_topic_136,isw_topic_137,isw_topic_138,isw_topic_139,isw_topic_140,isw_topic_141,isw_topic_142,isw_topic_143,isw_topic_144,isw_topic_145,isw_topic_146,isw_topic_147,isw_topic_148,isw_topic_149,isw_total_intensity,isw_topic_std,isw_topic_max,isw_topic_mean,isw_velocity_24h,isw_intensity_ema,isw_topic_entropy,tg_topic_0,tg_topic_1,tg_topic_2,tg_topic_3,tg_topic_4,tg_topic_5,tg_topic_6,tg_topic_7,tg_topic_8,tg_topic_9,tg_topic_10,tg_topic_11,tg_topic_12,tg_topic_13,tg_topic_14,tg_topic_15,tg_topic_16,tg_topic_17,tg_topic_18,tg_topic_19,tg_topic_20,tg_topic_21,tg_topic_22,tg_topic_23,tg_topic_24,tg_topic_25,tg_topic_26,tg_topic_27,tg_topic_28,tg_topic_29,tg_topic_30,tg_topic_31,tg_topic_32,tg_topic_33,tg_topic_34,tg_topic_35,tg_topic_36,tg_topic_37,tg_topic_38,tg_topic_39,tg_topic_40,tg_topic_41,tg_topic_42,tg_topic_43,tg_topic_44,tg_topic_45,tg_topic_46,tg_topic_47,tg_topic_48,tg_topic_49,tg_topic_50,tg_topic_51,tg_topic_52,tg_topic_53,tg_topic_54,tg_topic_55,tg_topic_56,tg_topic_57,tg_topic_58,tg_topic_59,tg_topic_60,tg_topic_61,tg_topic_62,tg_topic_63,tg_topic_64,tg_topic_65,tg_topic_66,tg_topic_67,tg_topic_68,tg_topic_69,tg_topic_70,tg_topic_71,tg_topic_72,tg_topic_73,tg_topic_74,tg_topic_75,tg_topic_76,tg_topic_77,tg_topic_78,tg_topic_79,tg_topic_80,tg_topic_81,tg_topic_82,tg_topic_83,tg_topic_84,tg_topic_85,tg_topic_86,tg_topic_87,tg_topic_88,tg_topic_89,tg_topic_90,tg_topic_91,tg_topic_92,tg_topic_93,tg_topic_94,tg_topic_95,tg_topic_96,tg_topic_97,tg_topic_98,tg_topic_99,tg_topic_100,tg_topic_101,tg_topic_102,tg_topic_103,tg_topic_104,tg_topic_105,tg_topic_106,tg_topic_107,tg_topic_108,tg_topic_109,tg_topic_110,tg_topic_111,tg_topic_112,tg_topic_113,tg_topic_114,tg_topic_115,tg_topic_116,tg_topic_117,tg_topic_118,tg_topic_119,tg_topic_120,tg_topic_121,tg_topic_122,tg_topic_123,tg_topic_124,tg_topic_125,tg_topic_126,tg_topic_127,tg_topic_128,tg_topic_129,tg_topic_130,tg_topic_131,tg_topic_132,tg_topic_133,tg_topic_134,tg_topic_135,tg_topic_136,tg_topic_137,tg_topic_138,tg_topic_139,tg_topic_140,tg_topic_141,tg_topic_142,tg_topic_143,tg_topic_144,tg_topic_145,tg_topic_146,tg_topic_147,tg_topic_148,tg_topic_149,tg_topic_150,tg_topic_151,tg_topic_152,tg_topic_153,tg_topic_154,tg_topic_155,tg_topic_156,tg_topic_157,tg_topic_158,tg_topic_159,tg_topic_160,tg_topic_161,tg_topic_162,tg_topic_163,tg_topic_164,tg_topic_165,tg_topic_166,tg_topic_167,tg_topic_168,tg_topic_169,tg_topic_170,tg_topic_171,tg_topic_172,tg_topic_173,tg_topic_174,tg_topic_175,tg_topic_176,tg_topic_177,tg_topic_178,tg_topic_179,tg_topic_180,tg_topic_181,tg_topic_182,tg_topic_183,tg_topic_184,tg_topic_185,tg_topic_186,tg_topic_187,tg_topic_188,tg_topic_189,tg_topic_190,tg_topic_191,tg_topic_192,tg_topic_193,tg_topic_194,tg_topic_195,tg_topic_196,tg_topic_197,tg_topic_198,tg_topic_199,tg_topic_200,tg_topic_201,tg_topic_202,tg_topic_203,tg_topic_204,tg_topic_205,tg_topic_206,tg_topic_207,tg_topic_208,tg_topic_209,tg_topic_210,tg_topic_211,tg_topic_212,tg_topic_213,tg_topic_214,tg_topic_215,tg_topic_216,tg_topic_217,tg_topic_218,tg_topic_219,tg_topic_220,tg_topic_221,tg_topic_222,tg_topic_223,tg_topic_224,tg_topic_225,tg_topic_226,tg_topic_227,tg_topic_228,tg_topic_229,tg_topic_230,tg_topic_231,tg_topic_232,tg_topic_233,tg_topic_234,tg_topic_235,tg_topic_236,tg_topic_237,tg_topic_238,tg_topic_239,tg_topic_240,tg_topic_241,tg_topic_242,tg_topic_243,tg_topic_244,tg_topic_245,tg_topic_246,tg_topic_247,tg_topic_248,tg_topic_249,tg_total_intensity,tg_topic_std,tg_topic_max,tg_topic_entropy,tg_velocity_3h,tg_intensity_ema_6h,tg_intensity_zscore
491449,2023-11-10 09:00:00,21,46.6401,32.6142,7.8,3.5,76.5,0.000,0.0,0.00,0.0,0.0,33.1,17.6,137.3,1022.9,46.2,89.6,7.5,4.0,0.90,7.6,5.9,88.37,0.0,0.0,0.0,18.7,9.0,139.0,1025.0,7.7,161.0,0.6,2.0,False,True,False,False,True,False,False,False,2023,11,4,9,Kherson,Europe/Kiev,2023-11-10,06:43:55,16:22:22,09:00:00,Херсонська,1,5.616667,0.0,0.0,0.0,0.0,12.0,0,0,0.0,0.0,4,0.813576,-0.092036,-0.069499,-0.167533,0.052409,-0.191215,0.124650,-0.098120,0.146826,0.173100,0.068307,0.009558,0.002339,0.003878,-0.048154,-0.089817,0.029564,0.045882,0.090224,-0.048833,0.006089,-0.045790,0.017544,0.004800,-0.000861,0.036398,-0.026528,-0.030213,0.015006,-0.000245,0.040525,-0.006903,-0.002448,0.012563,0.039286,-0.007838,0.014406,-0.008643,0.024025,-0.007271,0.026751,0.034666,0.045977,-0.001744,-0.014100,-0.034595,-0.039396,-0.000487,0.032011,0.002700,0.045847,0.022880,-0.003491,0.013785,0.009657,0.005390,0.021417,-0.037022,0.010572,-0.028799,-0.011011,0.003292,-0.017373,-0.040190,0.011976,-0.001438,-0.011662,-0.007087,-0.009760,0.034577,-0.020178,0.034514,0.018397,0.000296,-0.016076,0.010117,-0.019430,-0.008622,0.005659,0.014554,-0.009565,-0.010351,-0.015134,0.008298,-0.022865,0.000980,0.021763,0.038986,0.023116,0.008330,0.000645,-0.010214,-0.002977,-0.008649,0.000804,0.003866,0.009875,0.006763,-0.008852,-0.008697,-0.002282,0.017326,-0.002775,0.002939,-0.004216,0.006772,-0.022699,0.029349,0.004346,-0.009200,-0.005062,-0.012077,-0.004101,0.004326,-0.026856,-0.016202,0.018758,-0.008544,0.027991,0.018377,-0.012559,-0.014011,0.009255,0.014691,-0.025272,-0.010920,-0.010689,-0.004264,0.012207,0.018553,-0.020462,0.013231,-0.001907,0.004118,-0.016583,0.012211,-0.021101,-0.006496,0.002055,-0.003613,-0.022653,-0.003913,-0.004060,-0.004756,0.007874,0.003319,-0.005926,-0.021337,-0.007045,-0.000519,4.220922,0.072030,0.813576,0.028139,-0.296457,4.350173,4.033315,0.054703,0.007227,0.063162,-0.013897,-0.083665,0.195942,0.055748,-0.051882,-0.037516,-0.123371,0.020928,0.017146,-0.015926,-0.017308,0.002849,-0.008809,-0.002969,-0.002171,0.007551,0.000292,0.005392,0.028735,0.010590,-0.004947,-0.017850,0.020730,-0.021272,0.037367,0.011239,0.002961,-0.003690,-0.018141,0.002503,-0.007103,-0.000970,-0.017495,-0.030801,-0.002986,0.000101,0.003399,0.005679,-0.000027,-0.004433,-0.001335,0.012641,-0.027716,0.018259,-0.009469,-0.011734,-0.015423,0.000240,0.015487,0.022872,0.022529,0.003907,-0.037127,-0.012180,0.036003,0.009169,0.024051,0.011644,0.005857,-0.002687,-0.001558,-0.034188,-0.015417,0.013881,-0.001821,-0.015718,0.000769,-0.002849,0.010656,-0.002229,-0.005018,-0.007639,0.025866,0.000514,0.000761,-0.007039,-0.001257,0.005262,-0.001287,-0.007306,-0.000051,0.012144,0.008032,-0.001109,0.014962,-0.014087,-0.000846,0.003432,0.004537,-0.015407,-0.012291,0.008552,-0.004277,0.011705,0.015792,0.005123,-0.000253,0.005734,-0.003567,-0.003615,-0.007206,-0.006774,-0.007204,-0.002528,0.000065,0.004827,0.009168,0.006870,-0.023077,0.000311,0.013296,0.015231,0.006948,0.023074,0.008207,0.003055,-0.007103,-0.012456,0.005034,0.012997,-0.002624,-0.001374,0.003770,-0.011328,0.014067,-0.032946,-0.004194,-0.008685,-0.029224,0.006923,-0.000216,-0.019695,0.015034,0.021510,0.002780,0.002812,-0.003084,-0.017909,0.009708,0.005260,-0.002063,0.017863,-0.004296,0.005736,-0.001357,0.003482,0.006186,0.006411,-0.011291,-0.000841,0.006490,-0.009833,-0.002761,0.008871,-0.000100,0.000600,0.007236,0.002744,-0.011590,0.001187,-0.010219,-0.010031,0.005311,-0.001751,0.013157,0.005373,0.008556,-0.006213,-0.000484,-0.015413,-0.006076,0.011588,0.001343,-0.008437,0.000863,-0.006062,-0.005235,0.003948,-0.010094,0.013251,0.019023,0.001694,0.018432,0.006814,-0.010987,0.005274,-0.005845,-0.009508,0.003448,-0.001062,0.000755,0.000622,-0.011103,0.005780,-0.009116,-0.008836,-0.001467,0.006593,-0.000978,-0.001167,0.003736,0.008409,-0.003224,0.007253,-0.006209,-0.001652,0.002163,0.004986,-0.000201,0.009419,-0.005067,-0.001450,0.006242,0.007265,-0.001907,-0.003376,0.002702,-0.005445,-0.019017,0.000646,0.001182,-0.002127,0.008296,0.020039,-0.008500,0.011103,-0.005956,-0.004314,0.005429,0.003530,0.002750,-0.007357,0.000736,-0.010946,0.001298,-0.011703,-0.003251,-0.001675,0.000676,0.008482,0.009412,-0.004697,-0.004639,0.004240,-0.005490,-0.007064,-0.010979,2.686006,0.017551,0.195942,4.886210,2.686006,2.281056,-0.244619
555638,2025-02-21 05:00:00,23,49.4407,32.0637,-5.7,-10.8,67.8,0.000,0.0,0.00,0.0,2.4,34.9,16.2,19.5,1040.0,92.1,90.0,7.9,3.0,0.79,-6.6,-12.2,78.60,0.0,0.0,0.0,25.6,13.3,15.7,1038.0,97.2,0.0,0.0,0.0,False,True,False,False,False,True,False,False,2025,2,4,5,Cherkasy,Europe/Kiev,2025-02-21,06:49:57,17:21:36,05:00:00,Черкаська,0,0.000000,0.0,0.0,0.0,0.0,0.0,0,1,13.0,3.0,39,0.788585,0.222172,-0.069352,0.099549,0.045733,0.003824,-0.016716,0.024035,0.005606,0.032479,-0.040601,0.060809,0.159484,-0.188355,0.255158,-0.020000,-0.095971,-0.017121,0.003852,-0.049385,-0.004684,0.112727,-0.040034,-0.017730,0.017994,-0.005672,-0.026318,0.027931,-0.041583,-0.040793,0.007741,0.024483,0.030937,0.001551,0.034758,-0.036305,0.005202,-0.031109,-0.001824,0.006622,0.023781,-0.021917,-0.009580,-0.043213,0.020444,0.000983,-0.006086,0.022541,0.009327,-0.019068,0.032393,-0.010744,0.004250,0.019032,-0.014115,0.004687,0.000999,-0.043400,-0.020558,0.005526,-0.008314,0.004588,0.010937,0.025771,0.001637,0.000166,-0.020647,0.010291,0.040771,-0.018289,0.013913,-0.005171,-0.003442,-0.005356,0.031633,0.018998,-0.001116,-0.009761,0.015481,0.019739,-0.007777,-0.027260,-0.017284,-0.002982,-0.038213,0.010430,-0.011017,0.015130,0.000949,0.006112,-0.020238,-0.005457,0.018137,0.016676,-0.035725,0.005471,0.021872,0.012895,-0.019572,-0.001115,0.006329,0.004374,0.018032,-0.001663,-0.028757,0.005619,-0.001358,0.000712,0.000278,0.030837,0.002802,0.005622,-0.020705,-0.001868,0.004240,0.025533,0.017304,-0.010670,-0.010111,-0.004592,0.001101,0.008812,-0.012713,0.015706,-0.018817,0.013959,-0.007252,0.006091,0.012156,-0.002316,0.024992,-0.011680,0.003069,0.017082,-0.008796,-0.015319,-0.034519,-0.004644,0.001671,0.026637,0.015172,-0.012196,-0.026167,-0.013975,0.011735,0.021360,-0.030164,-0.012213,-0.005661,0.011317,4.216456,0.072004,0.788585,0.028110,-1.060399,4.871815,4.024214,0.428514,0.413083,0.095681,0.120427,0.106238,0.042769,0.066368,-0.080831,0.308096,0.102189,-0.029683,-0.009876,0.023467,0.054404,0.021358,-0.016406,0.041168,-0.019896,-0.000613,-0.008321,-0.018406,-0.014954,0.007488,-0.007042,-0.003911,-0.012656,-0.005089,0.016288,-0.014334,0.015239,0.053749,-0.005238,-0.082858,0.036262,0.034584,0.013169,-0.077973,-0.087749,0.001930,-0.044454,0.014328,-0.004200,0.076702,-0.028565,-0.016172,-0.027532,0.021039,0.064456,0.105247,-0.041132,-0.040631,0.048275,-0.015346,0.037624,0.002882,0.060239,0.021674,-0.003142,0.019293,0.039953,-0.048699,-0.005643,0.053303,-0.027581,-0.004326,0.103480,-0.006099,-0.027594,-0.008664,0.021838,0.028583,-0.010610,-0.023194,-0.008747,-0.028847,-0.012420,0.017852,-0.004061,-0.002424,-0.027044,0.054600,0.027055,0.005494,0.017550,-0.000809,-0.014572,-0.003830,0.019939,-0.005931,0.033593,0.072789,-0.040047,0.004346,-0.022906,-0.043555,0.055088,0.066739,0.069009,0.069612,-0.040300,0.030342,-0.011923,-0.066404,0.050343,-0.044081,0.053225,0.012466,-0.043972,0.026509,-0.006752,-0.022470,-0.034232,-0.019495,-0.005205,0.074926,-0.020465,-0.045071,-0.019062,-0.035537,0.021229,-0.023744,0.038809,0.004387,-0.028176,0.044458,0.049653,0.028947,-0.010976,-0.034203,0.001371,-0.002710,-0.021218,0.041336,-0.037514,0.020583,-0.000576,-0.011457,-0.014284,0.007517,-0.014652,-0.027254,-0.004438,-0.000764,-0.000711,0.043231,-0.026191,-0.039005,-0.027204,0.032068,-0.007707,-0.000323,-0.047376,0.003763,0.011657,0.000392,0.022944,0.020558,-0.014738,-0.006106,0.007293,-0.014011,0.005506,0.036737,-0.018323,-0.021152,-0.009834,-0.025973,-0.026095,-0.021542,0.020057,0.008354,-0.014298,-0.006807,0.002616,0.007062,0.000905,0.011720,0.031718,0.007130,0.029292,-0.007533,-0.017446,0.019161,-0.016117,0.011360,-0.015764,-0.002954,0.019949,-0.013618,0.017927,0.006958,-0.003750,-0.015041,0.014084,-0.001845,0.036397,-0.003198,0.015637,-0.020803,-0.012339,-0.021599,0.014619,-0.023764,0.010946,-0.018811,0.005412,-0.003638,-0.012365,0.027625,-0.009525,0.006492,-0.011923,0.024955,0.000577,-0.003287,-0.023464,-0.010336,-0.022696,-0.001056,-0.007077,-0.013540,-0.019460,0.008598,-0.001253,-0.008407,-0.017610,0.000999,-0.001236,-0.015560,0.008780,-0.002562,-0.027121,-0.015365,0.010920,0.002694,-0.014542,-0.019236,0.017120,-0.009578,-0.013262,-0.009577,0.001122,-0.013565,-0.016191,0.000275,-0.004691,-0.010770,-0.011297,-0.018832,0.015877,6.975179,0.045548,0.428514,4.904481,-1.894556,6.281034,1.266996
589657,2022-12-25 20:00:00,25,51.4937,31.2944,0.8,0.3,96.3,0.000,0.0,0.00,0.0,4.0,20.2,11.5,36.0,1021.1,99.3,17.8,1.5,1.0,0.05,0.0,-2.8,92.97,0.0,0.0,0.0,14.8,7.9,34.7,1025.0,97.2,0.0,0.1,0.0,False,True,False,False,False,True,False,False,2022,12,6,20,Chernihiv,Europe/Kiev,2022-12-25,07:59:45,15:50:03,20:00:00,Чернігівська,0,0.000000,0.0,0.0,1.0,0.0,7.0,1,0,0.0,0.0,3,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-4.414697,0.846805,-0.000000,0.009325,0.000961,0.023581,0.000814,-0.028886,0.056139,-0.074183,0.080031,0.003591,-0.002932,-0.065193,0.009911,-0.017449,0.039617,0.019434,-0.043761,0.008679,-0.029424,-0.043933,0.050217,-0.002931,0.038217,-0.005145,-0.030799,-0.005113,0.005569,0.002813,0.005291,0.012364,0.022211,0.031773,0.000023,0.005983,0.001515,-0.012077,0.008651,0.011188,0.002248,-0.004975,0.005245,-0.003464,0.006669,0.003425,0.009656,-0.016785,-0.000857,-0.005713,0.004381,0.002614,0.003687,-0.001660,-0.000631,-0.005917,-0.004685,0.007192,0.002245,0.007311,-0.009138,0.009281,-0.011643,0.014874,-0.002801,-0.017591,0.014680,-0.004282,-0.011815,-0.013509,-0.021138,0.003519,-0.005555,0.006746,0.009934,0.006421,-0.010651,-0.035607,0.004509,0.011386,-0.007235,0.012838,0.004578,0.003581,0.000118,0.005606,-0.001296,-0.000795,-0.002849,-0.005531,-0.008521,0.004599,0.011915,0.000109,-0.006816,-0.001807,0.007190,0.015431,-0.014997,0.013035,0.003174,-0.015715,0.016019,0.013516,-0.013435,0.008246,-0.008723,-0.029353,-0.004801,-0.007128,-0.007357,0.018179,-0.007776,-0.015078,0.012394,-0.001370,0.022466,-0.017683,0.011933,-0.019670,-0.020015,0.028117,0.003654,-0.015222,0.009651,0.004368,-0.016052,0.030643,0.001576,-0.018884,-0.021662,-0.000712,0.034692,0.011576,-0.008379,-0.010381,0.009527,-0.018850,0.012506,-0.009856,0.008172,-0.014636,0.001109,-0.005527,-0.006170,-0.000639,0.003262,0.002096,-0.000154,-0.001487,-0.008376,0.019474,0.002417,-0.012141,-0.002412,0.008650,-0.022701,-0.008963,-0.007184,0.013779,-0.016953,-0.008106,-0.004913,-0.002694,0.017793,0.009846,0.007951,0.011763,0.008388,0.000310,-0.009554,0.001400,-0.004295,-0.007106,0.011011,0.005335,0.012284,0.005673,0.005681,0.006653,0.008171,-0.003514,-0.003527,-0.007926,0.006849,0.004863,-0.004235,0.002562,0.023546,0.008458,-0.013355,-0.010015,-0.000487,-0.004074,-0.007476,0.001687,0.014044,-0.003803,0.012644,-0.005087,-0.007718,0.002624,-0.010209,0.010028,-0.001305,0.008405,-0.011493,0.002623,0.007286,-0.000508,-0.005930,-0.005052,0.007927,0.002133,-0.006963,-0.001971,0.020674,-0.002223,0.002516,0.000332,-0.000374,-0.015665,0.000879,-0.008318,-0.003540,0.007011,0.004166,-0.003569,0.013710,-0.011826,0.003339,-0.000129,-0.000248,-0.003889,-0.023406,-0.005712,-0.004322,-0.006008,-0.005628,0.010391,-0.017108,0.024550,-0.002076,-0.000419,-0.009166,-0.013513,-0.000003,-0.015110,-0.009553,-0.011552,0.012994,-0.002028,-0.016724,2.641578,0.011445,0.080031,5.092770,-0.649825,2.318246,0.439004

In [38]:
df_final.to_parquet("merged_dataset.parquet", index=False, engine="pyarrow")

# ТУТ БУДЕ EDA

## Weather, ISW, Telegram shift for further models trainings

In [39]:
df_to_train = df_final.copy()
df_to_train = df_to_train.sort_values(['region_id', 'datetime_hour'])

In [40]:
# delete unnessecary columns
columns_to_delete = ['city_latitude', 'city_longitude', 'day_temp', 'day_dew', 'day_humidity', 'day_precip', 'day_precipprob', 'day_precipcover', 
                     'day_snow', 'day_snowdepth', 'day_windgust', 'day_windspeed', 'day_winddir', 'day_pressure', 'day_cloudcover', 'day_solarradiation',
                     'day_solarenergy', 'day_uvindex', 'day_moonphase', 'day_conditions_simple_Clear', 'day_conditions_simple_Cloudy', 'day_conditions_simple_Rain',
                     'day_conditions_simple_Snow', 'year', 'month', 'hour', 'day_of_week', 'city_timezone', 'day_datetime', 'hour_datetime', 'region_key']
df_to_train = df_to_train.drop(columns=columns_to_delete)

In [41]:
isw_cols = [c for c in df_to_train.columns if 'isw_' in c]
df_to_train[isw_cols] = df_to_train.groupby('region_id')[isw_cols].shift(24).fillna(0)

In [42]:
df_to_train.head()

,datetime_hour,region_id,hour_temp,hour_feelslike,hour_humidity,hour_precip,hour_precipprob,hour_snow,hour_windgust,hour_windspeed,hour_winddir,hour_pressure,hour_cloudcover,hour_solarradiation,hour_solarenergy,hour_uvindex,hour_conditions_simple_Clear,hour_conditions_simple_Cloudy,hour_conditions_simple_Rain,hour_conditions_simple_Snow,city_name,day_sunrise,day_sunset,alarm_active,alarm_minutes_in_hour,alarm_lag_1,alarm_lag_3,alarm_lag_6,alarm_lag_12,alarms_in_last_24h,is_weekend,is_night,total_active_alarms_lag1,neighbour_alarms,hours_since_last_alarm,isw_topic_0,isw_topic_1,isw_topic_2,isw_topic_3,isw_topic_4,isw_topic_5,isw_topic_6,isw_topic_7,isw_topic_8,isw_topic_9,isw_topic_10,isw_topic_11,isw_topic_12,isw_topic_13,isw_topic_14,isw_topic_15,isw_topic_16,isw_topic_17,isw_topic_18,isw_topic_19,isw_topic_20,isw_topic_21,isw_topic_22,isw_topic_23,isw_topic_24,isw_topic_25,isw_topic_26,isw_topic_27,isw_topic_28,isw_topic_29,isw_topic_30,isw_topic_31,isw_topic_32,isw_topic_33,isw_topic_34,isw_topic_35,isw_topic_36,isw_topic_37,isw_topic_38,isw_topic_39,isw_topic_40,isw_topic_41,isw_topic_42,isw_topic_43,isw_topic_44,isw_topic_45,isw_topic_46,isw_topic_47,isw_topic_48,isw_topic_49,isw_topic_50,isw_topic_51,isw_topic_52,isw_topic_53,isw_topic_54,isw_topic_55,isw_topic_56,isw_topic_57,isw_topic_58,isw_topic_59,isw_topic_60,isw_topic_61,isw_topic_62,isw_topic_63,isw_topic_64,isw_topic_65,isw_topic_66,isw_topic_67,isw_topic_68,isw_topic_69,isw_topic_70,isw_topic_71,isw_topic_72,isw_topic_73,isw_topic_74,isw_topic_75,isw_topic_76,isw_topic_77,isw_topic_78,isw_topic_79,isw_topic_80,isw_topic_81,isw_topic_82,isw_topic_83,isw_topic_84,isw_topic_85,isw_topic_86,isw_topic_87,isw_topic_88,isw_topic_89,isw_topic_90,isw_topic_91,isw_topic_92,isw_topic_93,isw_topic_94,isw_topic_95,isw_topic_96,isw_topic_97,isw_topic_98,isw_topic_99,isw_topic_100,isw_topic_101,isw_topic_102,isw_topic_103,isw_topic_104,isw_topic_105,isw_topic_106,isw_topic_107,isw_topic_108,isw_topic_109,isw_topic_110,isw_topic_111,isw_topic_112,isw_topic_113,isw_topic_114,isw_topic_115,isw_topic_116,isw_topic_117,isw_topic_118,isw_topic_119,isw_topic_120,isw_topic_121,isw_topic_122,isw_topic_123,isw_topic_124,isw_topic_125,isw_topic_126,isw_topic_127,isw_topic_128,isw_topic_129,isw_topic_130,isw_topic_131,isw_topic_132,isw_topic_133,isw_topic_134,isw_topic_135,isw_topic_136,isw_topic_137,isw_topic_138,isw_topic_139,isw_topic_140,isw_topic_141,isw_topic_142,isw_topic_143,isw_topic_144,isw_topic_145,isw_topic_146,isw_topic_147,isw_topic_148,isw_topic_149,isw_total_intensity,isw_topic_std,isw_topic_max,isw_topic_mean,isw_velocity_24h,isw_intensity_ema,isw_topic_entropy,tg_topic_0,tg_topic_1,tg_topic_2,tg_topic_3,tg_topic_4,tg_topic_5,tg_topic_6,tg_topic_7,tg_topic_8,tg_topic_9,tg_topic_10,tg_topic_11,tg_topic_12,tg_topic_13,tg_topic_14,tg_topic_15,tg_topic_16,tg_topic_17,tg_topic_18,tg_topic_19,tg_topic_20,tg_topic_21,tg_topic_22,tg_topic_23,tg_topic_24,tg_topic_25,tg_topic_26,tg_topic_27,tg_topic_28,tg_topic_29,tg_topic_30,tg_topic_31,tg_topic_32,tg_topic_33,tg_topic_34,tg_topic_35,tg_topic_36,tg_topic_37,tg_topic_38,tg_topic_39,tg_topic_40,tg_topic_41,tg_topic_42,tg_topic_43,tg_topic_44,tg_topic_45,tg_topic_46,tg_topic_47,tg_topic_48,tg_topic_49,tg_topic_50,tg_topic_51,tg_topic_52,tg_topic_53,tg_topic_54,tg_topic_55,tg_topic_56,tg_topic_57,tg_topic_58,tg_topic_59,tg_topic_60,tg_topic_61,tg_topic_62,tg_topic_63,tg_topic_64,tg_topic_65,tg_topic_66,tg_topic_67,tg_topic_68,tg_topic_69,tg_topic_70,tg_topic_71,tg_topic_72,tg_topic_73,tg_topic_74,tg_topic_75,tg_topic_76,tg_topic_77,tg_topic_78,tg_topic_79,tg_topic_80,tg_topic_81,tg_topic_82,tg_topic_83,tg_topic_84,tg_topic_85,tg_topic_86,tg_topic_87,tg_topic_88,tg_topic_89,tg_topic_90,tg_topic_91,tg_topic_92,tg_topic_93,tg_topic_94,tg_topic_95,tg_topic_96,tg_topic_97,tg_topic_98,tg_topic_99,tg_topic_100,tg_topic_101,tg_topic_102,tg_topic_103,tg_topic_104,tg_topic_105,tg_topic_106,tg_topic_107,tg_topic_108,tg_topic_109,tg_topic_110,tg_topic_111,tg_topic_112,tg_topic_113,tg_topic_114,tg_topic_115,tg_topic_116,tg_topic_117,tg_topic_118,tg_topic_119,tg_topic_120,tg_topic_121,tg_topic_122,tg_topic_123,tg_topic_124,tg_topic_125,tg_topic_126,tg_topic_127,tg_topic_128,tg_topic_129,tg_topic_130,tg_topic_131,tg_topic_132,tg_topic_133,tg_topic_134,tg_topic_135,tg_topic_136,tg_topic_137,tg_topic_138,tg_topic_139,tg_topic_140,tg_topic_141,tg_topic_142,tg_topic_143,tg_topic_144,tg_topic_145,tg_topic_146,tg_topic_147,tg_topic_148,tg_topic_149,tg_topic_150,tg_topic_151,tg_topic_152,tg_topic_153,tg_topic_154,tg_topic_155,tg_topic_156,tg_topic_157,tg_topic_158,tg_topic_159,tg_topic_160,tg_topic_161,tg_topic_162,tg_topic_163,tg_topic_164,tg_topic_165,tg_topic_166,tg_topic_167,tg_topic_168,tg_topic_169,tg_topic_170,tg_topic_171,tg_topic_172,tg_topic_173,tg_topic_174,tg_topic_175,tg_topic_176,tg_topic_177,tg_topic_178,tg_topic_179,tg_topic_180,tg_topic_181,tg_topic_182,tg_topic_183,tg_topic_184,tg_topic_185,tg_topic_186,tg_topic_187,tg_topic_188,tg_topic_189,tg_topic_190,tg_topic_191,tg_topic_192,tg_topic_193,tg_topic_194,tg_topic_195,tg_topic_196,tg_topic_197,tg_topic_198,tg_topic_199,tg_topic_200,tg_topic_201,tg_topic_202,tg_topic_203,tg_topic_204,tg_topic_205,tg_topic_206,tg_topic_207,tg_topic_208,tg_topic_209,tg_topic_210,tg_topic_211,tg_topic_212,tg_topic_213,tg_topic_214,tg_topic_215,tg_topic_216,tg_topic_217,tg_topic_218,tg_topic_219,tg_topic_220,tg_topic_221,tg_topic_222,tg_topic_223,tg_topic_224,tg_topic_225,tg_topic_226,tg_topic_227,tg_topic_228,tg_topic_229,tg_topic_230,tg_topic_231,tg_topic_232,tg_topic_233,tg_topic_234,tg_topic_235,tg_topic_236,tg_topic_237,tg_topic_238,tg_topic_239,tg_topic_240,tg_topic_241,tg_topic_242,tg_topic_243,tg_topic_244,tg_topic_245,tg_topic_246,tg_topic_247,tg_topic_248,tg_topic_249,tg_total_intensity,tg_topic_std,tg_topic_max,tg_topic_entropy,tg_velocity_3h,tg_intensity_ema_6h,tg_intensity_zscore
0,2022-02-24 00:00:00,2,2.1,-0.5,91.76,0.0,0.0,0.0,16.6,8.6,279.6,1021.0,91.1,0.0,0.1,0.0,False,True,False,False,Vinnytsia,06:58:49,17:40:52,0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0.0,0.0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-0.0,0.0,0.0,NaN
1,2022-02-24 00:00:00,2,2.1,-0.5,91.76,0.0,0.0,0.0,16.6,8.6,279.6,1021.0,91.1,0.0,0.1,0.0,False,True,False,False,Vinnytsia,06:58:49,17:40:52,0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0.0,0.0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-0.0,0.0,0.0,0.0
3,2022-02-24 01:00:00,2,2.1,-0.4,89.80,0.0,0.0,0.0,16.6,8.3,289.2,1021.0,97.9,0.0,0.1,0.0,False,True,False,False,Vinnytsia,06:58:49,17:40:52,0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0.0,0.0,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-0.0,0.0,0.0,0.0
2,2022-02-24 01:00:00,2,2.1,-0.4,89.80,0.0,0.0,0.0,16.6,8.3,289.2,1021.0,97.9,0.0,0.1,0.0,False,True,False,False,Vinnytsia,06:58:49,17:40:52,0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0.0,0.0,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-0.0,0.0,0.0,0.0
5,2022-02-24 02:00:00,2,2.0,-0.3,90.44,0.0,0.0,0.0,27.7,7.6,287.6,1021.0,98.2,0.0,0.1,0.0,False,True,False,False,Vinnytsia,06:58:49,17:40:52,0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0.0,0.0,3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-0.0,0.0,0.0,0.0

In [43]:
tg_cols = [c for c in df_to_train.columns if 'tg_' in c]
df_to_train[tg_cols] = df_to_train.groupby('region_id')[tg_cols].shift(1).fillna(0)

In [44]:
hour_weather_cols = [c for c in df_to_train.columns if c.startswith('hour_')]
df_to_train[hour_weather_cols] = (df_to_train.groupby('region_id')[hour_weather_cols].shift(1))
df_to_train[hour_weather_cols] = (df_to_train.groupby('region_id')[hour_weather_cols].transform(lambda x: x.bfill()))

In [45]:
df_to_train['alarm_minutes_in_hour'] = (df_to_train.groupby('region_id')['alarm_minutes_in_hour'].shift(1).fillna(0))

In [46]:
df_to_train.head()

,datetime_hour,region_id,hour_temp,hour_feelslike,hour_humidity,hour_precip,hour_precipprob,hour_snow,hour_windgust,hour_windspeed,hour_winddir,hour_pressure,hour_cloudcover,hour_solarradiation,hour_solarenergy,hour_uvindex,hour_conditions_simple_Clear,hour_conditions_simple_Cloudy,hour_conditions_simple_Rain,hour_conditions_simple_Snow,city_name,day_sunrise,day_sunset,alarm_active,alarm_minutes_in_hour,alarm_lag_1,alarm_lag_3,alarm_lag_6,alarm_lag_12,alarms_in_last_24h,is_weekend,is_night,total_active_alarms_lag1,neighbour_alarms,hours_since_last_alarm,isw_topic_0,isw_topic_1,isw_topic_2,isw_topic_3,isw_topic_4,isw_topic_5,isw_topic_6,isw_topic_7,isw_topic_8,isw_topic_9,isw_topic_10,isw_topic_11,isw_topic_12,isw_topic_13,isw_topic_14,isw_topic_15,isw_topic_16,isw_topic_17,isw_topic_18,isw_topic_19,isw_topic_20,isw_topic_21,isw_topic_22,isw_topic_23,isw_topic_24,isw_topic_25,isw_topic_26,isw_topic_27,isw_topic_28,isw_topic_29,isw_topic_30,isw_topic_31,isw_topic_32,isw_topic_33,isw_topic_34,isw_topic_35,isw_topic_36,isw_topic_37,isw_topic_38,isw_topic_39,isw_topic_40,isw_topic_41,isw_topic_42,isw_topic_43,isw_topic_44,isw_topic_45,isw_topic_46,isw_topic_47,isw_topic_48,isw_topic_49,isw_topic_50,isw_topic_51,isw_topic_52,isw_topic_53,isw_topic_54,isw_topic_55,isw_topic_56,isw_topic_57,isw_topic_58,isw_topic_59,isw_topic_60,isw_topic_61,isw_topic_62,isw_topic_63,isw_topic_64,isw_topic_65,isw_topic_66,isw_topic_67,isw_topic_68,isw_topic_69,isw_topic_70,isw_topic_71,isw_topic_72,isw_topic_73,isw_topic_74,isw_topic_75,isw_topic_76,isw_topic_77,isw_topic_78,isw_topic_79,isw_topic_80,isw_topic_81,isw_topic_82,isw_topic_83,isw_topic_84,isw_topic_85,isw_topic_86,isw_topic_87,isw_topic_88,isw_topic_89,isw_topic_90,isw_topic_91,isw_topic_92,isw_topic_93,isw_topic_94,isw_topic_95,isw_topic_96,isw_topic_97,isw_topic_98,isw_topic_99,isw_topic_100,isw_topic_101,isw_topic_102,isw_topic_103,isw_topic_104,isw_topic_105,isw_topic_106,isw_topic_107,isw_topic_108,isw_topic_109,isw_topic_110,isw_topic_111,isw_topic_112,isw_topic_113,isw_topic_114,isw_topic_115,isw_topic_116,isw_topic_117,isw_topic_118,isw_topic_119,isw_topic_120,isw_topic_121,isw_topic_122,isw_topic_123,isw_topic_124,isw_topic_125,isw_topic_126,isw_topic_127,isw_topic_128,isw_topic_129,isw_topic_130,isw_topic_131,isw_topic_132,isw_topic_133,isw_topic_134,isw_topic_135,isw_topic_136,isw_topic_137,isw_topic_138,isw_topic_139,isw_topic_140,isw_topic_141,isw_topic_142,isw_topic_143,isw_topic_144,isw_topic_145,isw_topic_146,isw_topic_147,isw_topic_148,isw_topic_149,isw_total_intensity,isw_topic_std,isw_topic_max,isw_topic_mean,isw_velocity_24h,isw_intensity_ema,isw_topic_entropy,tg_topic_0,tg_topic_1,tg_topic_2,tg_topic_3,tg_topic_4,tg_topic_5,tg_topic_6,tg_topic_7,tg_topic_8,tg_topic_9,tg_topic_10,tg_topic_11,tg_topic_12,tg_topic_13,tg_topic_14,tg_topic_15,tg_topic_16,tg_topic_17,tg_topic_18,tg_topic_19,tg_topic_20,tg_topic_21,tg_topic_22,tg_topic_23,tg_topic_24,tg_topic_25,tg_topic_26,tg_topic_27,tg_topic_28,tg_topic_29,tg_topic_30,tg_topic_31,tg_topic_32,tg_topic_33,tg_topic_34,tg_topic_35,tg_topic_36,tg_topic_37,tg_topic_38,tg_topic_39,tg_topic_40,tg_topic_41,tg_topic_42,tg_topic_43,tg_topic_44,tg_topic_45,tg_topic_46,tg_topic_47,tg_topic_48,tg_topic_49,tg_topic_50,tg_topic_51,tg_topic_52,tg_topic_53,tg_topic_54,tg_topic_55,tg_topic_56,tg_topic_57,tg_topic_58,tg_topic_59,tg_topic_60,tg_topic_61,tg_topic_62,tg_topic_63,tg_topic_64,tg_topic_65,tg_topic_66,tg_topic_67,tg_topic_68,tg_topic_69,tg_topic_70,tg_topic_71,tg_topic_72,tg_topic_73,tg_topic_74,tg_topic_75,tg_topic_76,tg_topic_77,tg_topic_78,tg_topic_79,tg_topic_80,tg_topic_81,tg_topic_82,tg_topic_83,tg_topic_84,tg_topic_85,tg_topic_86,tg_topic_87,tg_topic_88,tg_topic_89,tg_topic_90,tg_topic_91,tg_topic_92,tg_topic_93,tg_topic_94,tg_topic_95,tg_topic_96,tg_topic_97,tg_topic_98,tg_topic_99,tg_topic_100,tg_topic_101,tg_topic_102,tg_topic_103,tg_topic_104,tg_topic_105,tg_topic_106,tg_topic_107,tg_topic_108,tg_topic_109,tg_topic_110,tg_topic_111,tg_topic_112,tg_topic_113,tg_topic_114,tg_topic_115,tg_topic_116,tg_topic_117,tg_topic_118,tg_topic_119,tg_topic_120,tg_topic_121,tg_topic_122,tg_topic_123,tg_topic_124,tg_topic_125,tg_topic_126,tg_topic_127,tg_topic_128,tg_topic_129,tg_topic_130,tg_topic_131,tg_topic_132,tg_topic_133,tg_topic_134,tg_topic_135,tg_topic_136,tg_topic_137,tg_topic_138,tg_topic_139,tg_topic_140,tg_topic_141,tg_topic_142,tg_topic_143,tg_topic_144,tg_topic_145,tg_topic_146,tg_topic_147,tg_topic_148,tg_topic_149,tg_topic_150,tg_topic_151,tg_topic_152,tg_topic_153,tg_topic_154,tg_topic_155,tg_topic_156,tg_topic_157,tg_topic_158,tg_topic_159,tg_topic_160,tg_topic_161,tg_topic_162,tg_topic_163,tg_topic_164,tg_topic_165,tg_topic_166,tg_topic_167,tg_topic_168,tg_topic_169,tg_topic_170,tg_topic_171,tg_topic_172,tg_topic_173,tg_topic_174,tg_topic_175,tg_topic_176,tg_topic_177,tg_topic_178,tg_topic_179,tg_topic_180,tg_topic_181,tg_topic_182,tg_topic_183,tg_topic_184,tg_topic_185,tg_topic_186,tg_topic_187,tg_topic_188,tg_topic_189,tg_topic_190,tg_topic_191,tg_topic_192,tg_topic_193,tg_topic_194,tg_topic_195,tg_topic_196,tg_topic_197,tg_topic_198,tg_topic_199,tg_topic_200,tg_topic_201,tg_topic_202,tg_topic_203,tg_topic_204,tg_topic_205,tg_topic_206,tg_topic_207,tg_topic_208,tg_topic_209,tg_topic_210,tg_topic_211,tg_topic_212,tg_topic_213,tg_topic_214,tg_topic_215,tg_topic_216,tg_topic_217,tg_topic_218,tg_topic_219,tg_topic_220,tg_topic_221,tg_topic_222,tg_topic_223,tg_topic_224,tg_topic_225,tg_topic_226,tg_topic_227,tg_topic_228,tg_topic_229,tg_topic_230,tg_topic_231,tg_topic_232,tg_topic_233,tg_topic_234,tg_topic_235,tg_topic_236,tg_topic_237,tg_topic_238,tg_topic_239,tg_topic_240,tg_topic_241,tg_topic_242,tg_topic_243,tg_topic_244,tg_topic_245,tg_topic_246,tg_topic_247,tg_topic_248,tg_topic_249,tg_total_intensity,tg_topic_std,tg_topic_max,tg_topic_entropy,tg_velocity_3h,tg_intensity_ema_6h,tg_intensity_zscore
0,2022-02-24 00:00:00,2,2.1,-0.5,91.76,0.0,0.0,0.0,16.6,8.6,279.6,1021.0,91.1,0.0,0.1,0.0,False,True,False,False,Vinnytsia,06:58:49,17:40:52,0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0.0,0.0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2022-02-24 00:00:00,2,2.1,-0.5,91.76,0.0,0.0,0.0,16.6,8.6,279.6,1021.0,91.1,0.0,0.1,0.0,False,True,False,False,Vinnytsia,06:58:49,17:40:52,0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0.0,0.0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-0.0,0.0,0.0,0.0
3,2022-02-24 01:00:00,2,2.1,-0.5,91.76,0.0,0.0,0.0,16.6,8.6,279.6,1021.0,91.1,0.0,0.1,0.0,False,True,False,False,Vinnytsia,06:58:49,17:40:52,0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0.0,0.0,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-0.0,0.0,0.0,0.0
2,2022-02-24 01:00:00,2,2.1,-0.4,89.80,0.0,0.0,0.0,16.6,8.3,289.2,1021.0,97.9,0.0,0.1,0.0,False,True,False,False,Vinnytsia,06:58:49,17:40:52,0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0.0,0.0,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-0.0,0.0,0.0,0.0
5,2022-02-24 02:00:00,2,2.1,-0.4,89.80,0.0,0.0,0.0,16.6,8.3,289.2,1021.0,97.9,0.0,0.1,0.0,False,True,False,False,Vinnytsia,06:58:49,17:40:52,0,0.0,0.0,0.0,0.0,0.0,0.0,0,1,0.0,0.0,3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-0.0,0.0,0.0,0.0