# Predicting war events

## I. Importing essential libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import os
from pathlib import Path
import json

## II. Importing

### ISW

In [2]:
json_path_isw = Path("../data/isw_reports.json")

with open(json_path_isw, "r", encoding="utf-8") as f:
    data = json.load(f)

df_isw_raw = pd.DataFrame(data)

print(type(df_isw_raw))

<class 'pandas.core.frame.DataFrame'>

## III. EDA

### ISW

In [3]:
df_isw_raw.shape

(1439, 4)

In [4]:
df_isw_raw.head()

,date,title,url,text
0,2022-02-25,Russia-Ukraine Warning Update: Russian Offensi...,https://understandingwar.org/research/russia-u...,Previous\nNext\nRussia-Ukraine Warning Update:...
1,2022-02-26,Russia-Ukraine Warning Update: Russian Offensi...,https://understandingwar.org/research/russia-u...,Previous\nNext\nRussia-Ukraine Warning Update:...
2,2022-02-27,Russia-Ukraine Warning Update: Russian Offensi...,https://understandingwar.org/research/russia-u...,Previous\nNext\nRussia-Ukraine Warning Update:...
3,2022-02-28,"Russian Offensive Campaign Assessment, Februar...",https://understandingwar.org/research/russia-u...,Previous\nNext\nRussian Offensive Campaign Ass...
4,2022-03-01,"Russian Offensive Campaign Assessment, March 1...",https://understandingwar.org/research/russia-u...,Previous\nNext\nRussian Offensive Campaign Ass...

In [5]:
df_isw_raw.sample(5)

,date,title,url,text
1398,2026-01-20,"Russian Offensive Campaign Assessment, January...",https://understandingwar.org/research/russia-u...,Previous\nNext\nRussian Offensive Campaign Ass...
871,2024-08-02,"Russian Offensive Campaign Assessment, August ...",https://understandingwar.org/research/russia-u...,Previous\nNext\nRussian Offensive Campaign Ass...
415,2023-04-28,"Russian Offensive Campaign Assessment, April 2...",https://understandingwar.org/research/russia-u...,Previous\nNext\nRussian Offensive Campaign Ass...
43,2022-04-14,"Russian Offensive Campaign Assessment, April 1...",https://understandingwar.org/research/russia-u...,Previous\nNext\nRussian Offensive Campaign Ass...
1281,2025-09-21,"Russian Offensive Campaign Assessment, Septemb...",https://understandingwar.org/research/russia-u...,Previous\nNext\nRussian Offensive Campaign Ass...

In [6]:
df_isw_raw.describe()

,date,title,url,text
count,1439,1439,1439,1439
unique,1439,1439,1439,1439
top,2026-03-01,"Russian Offensive Campaign Assessment, March 1...",https://understandingwar.org/research/russia-u...,Previous\nNext\nRussian Offensive Campaign Ass...
freq,1,1,1,1

In [7]:
df_isw_raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1439 entries, 0 to 1438
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1439 non-null   object
 1   title   1439 non-null   object
 2   url     1439 non-null   object
 3   text    1439 non-null   object
dtypes: object(4)
memory usage: 45.1+ KB

The dataset contains 1439 rows and 4 columns. 
All values are unique.  
All columns currently have the `object` data type. 
No missing values were found

In [8]:
df_isw = df_isw_raw.copy()

In [9]:
df_isw["date"] = pd.to_datetime(df_isw["date"], errors="coerce")
print("Invalid dates:", df_isw["date"].isna().sum())
print(df_isw["date"].dtype)

Invalid dates: 0
datetime64[ns]

In [10]:
print("Duplicate dates:", df_isw["date"].duplicated().sum())

Duplicate dates: 0

In [11]:
all_dates = pd.date_range("2022-02-24", "2026-03-01")
existing_dates = pd.DatetimeIndex(df_isw["date"])
missing_dates = all_dates.difference(existing_dates)

print("Missing dates:", len(missing_dates))
print(missing_dates)

Missing dates: 28
DatetimeIndex(['2022-02-24', '2022-03-16', '2022-03-18', '2022-03-29',
               '2022-04-01', '2022-04-11', '2022-05-14', '2022-06-23',
               '2022-10-28', '2022-11-24', '2022-12-25', '2023-01-01',
               '2023-03-19', '2023-07-08', '2023-07-27', '2023-11-23',
               '2023-12-25', '2024-01-01', '2024-01-05', '2024-10-08',
               '2024-11-28', '2024-12-25', '2025-01-01', '2025-09-07',
               '2025-10-31', '2025-11-27', '2025-12-25', '2026-01-01'],
              dtype='datetime64[ns]', freq=None)

In [12]:
outside_range = df_isw[(df_isw["date"] < "2022-02-24") | (df_isw["date"] > "2026-03-01")]
print(outside_range)

Empty DataFrame
Columns: [date, title, url, text]
Index: []

In [13]:
def clean_isw_text(text):
    text = str(text)
    text = text.replace("Previous\nNext", "")
    text = text.replace("\n", " ")
    return text

df_isw["text_clean"] = df_isw["text"].apply(clean_isw_text)

In [14]:
print("=== RAW TEXT:")
print(df_isw.loc[0, "text"])

print("\n" + "="*100 + "\n")

print("=== CLEAN TEXT:")
print(df_isw.loc[0, "text_clean"])

=== RAW TEXT:
Previous
Next
Russia-Ukraine Warning Update: Russian Offensive Campaign Assessment, February 25, 2022
Mason Clark, George Barros, and Kateryna Stepanenko
February 25, 3:00 pm EST
Russian forces entered major Ukrainian cities—including Kyiv and Kherson—for the first time on February 25.
Russian forces’ main axes of advance focused on Kyiv (successfully isolating the city on both banks of the Dnipro River). Russian military operations along Ukraine’s northern border have been less well-planned, organized, and conducted than those emanating from Crimea. They have also been less successful so far. The divergence in performance likely arises in part from differences in the composition and organization of the Russian ground forces elements in the Western Military District and Belarus (to Ukraine’s north) and Southern Military District and Black Sea Fleet (to its south and east), as ISW has previously observed.
[1]
Determined and well-organized Ukrainian resistance around Kyiv and Kharkiv has also played an important role in preventing the Russian military from advancing with the speed and success for which it had reportedly planned.
[2]
The Russian military has deployed additional forces to southeastern Belarus, likely beyond those Moscow had planned to use against Ukraine, to offset these problems and challenges. Russian forces remain much larger and more capable than Ukraine’s conventional military, however. Russia will likely defeat Ukrainian regular military forces and secure their territorial objectives at some point in the coming days or weeks if Putin is determined to do so and willing to pay the cost in blood and treasure.
Key Takeaways
Russian forces entered the outskirts of Kyiv on the west bank of the Dnipro on February 25. Russian sabotage groups in civilian clothes are reportedly active in downtown Kyiv.
Russian forces have so far failed to enter Kyiv’s eastern outskirts. Ukrainian forces have successfully slowed Russian troops, which have temporarily abandoned the failed attempt to take the city of Chernihiv and are instead bypassing it.
Elements of the Russian 76th VDV (Airborne) division have concentrated in southeastern Belarus likely for use along the Chernihiv-bypass axis toward Kyiv in the next 24 hours.
Russian forces will likely envelop Kharkhiv in the next 24 hours after failing to enter the city through frontal assaults on February 24.
Russian forces have achieved little success on frontal assaults or envelopments against Ukrainian forces in Donbas but may not have intended to do more than pin Ukrainian forces in the east.
North of Crimea, Russian forces fully captured Kherson and are likely on the verge of seizing Melitopol in the east. Unconfirmed reports indicate that Russian forces had bypassed Kherson earlier and headed directly for Mykolaiv and Odessa.
Russian forces may be assembling in Stolin, Belarus, to open a new line of advance against Rivne in western Ukraine.
Russian forces carried out additional air and missile strikes on Kyiv and other major cities around 3:00 am local time on February 25.
ISW cannot confirm the frequency and targets of overnight Russian strikes at this time. The Ukrainian General Staff reported that Russian forces are increasingly targeting civil infrastructure and residential buildings “to intimidate the population of Ukraine.”
[3]
Russian forces continue to refrain from using the likely full scale of Russian air and missile capabilities, likely seeking to limit the negative imagery of heavy Ukrainian civilian casualties. However, Russian forces will likely increase their use of bombardments in coming days to overcome heavier-than-anticipated Ukrainian resistance.
Russian ground forces are advancing on four primary axes, discussed in turn below:
Belarus/Kyiv;
Kharkiv;
Donbas; and
Crimea-Kherson.
1)     Belarus/Kyiv axis: Russian forces entered the outskirts of Kyiv on the west bank of the Dnipro on February 25. Russian forces have so far failed to enter Kyiv’s eastern outskirts. They have abandoned for now the failed attempt to take the city of Chernihiv and are instead bypassing it.  Elements of the 76thVDV (Airborne) division have concentrated in southeastern Belarus likely for use along the Chernihiv-bypass axis toward Kyiv in the next 24 hours.
Russian forces entered the northwest Kyiv suburb of Obolon, on the western bank of the Dnipro River, as of 11:00 am local time.
[4]
The Ukrainian General Staff asked residents of Obolon to shelter in place and make Molotov cocktails the morning of February 25.
[5]
The Russian Ministry of Defense claimed at 3:30 pm local time on February 25 that Russian forces had isolated Kyiv from the west.
[6]
Russian forces bypassed the city of Chernihiv on the eastern approach to Kyiv after being halted by Ukrainian forces much of February 24-25.
[7]
The UK Defense Ministry reported at 6:00 pm local time that Russian forces opened a “new route” to Kyiv after failing to capture Chernihiv.
[8]
Russian forces have not yet entered Kyiv’s eastern outskirts.
The Ukrainian general staff reported Russian VDV (airborne) troops redeployed from Belarus to the
east
bank of the Dnipro River due to damage to the Hostomel military airport on the western bank, now in Russian hands after Ukrainian forces withdrew sometime early on February 25.
[9]
Russian forces failed to secure Hostomel airport by air assault and appear to have taken it only when mechanized units from Belarus arrived.  Ukrainian defenders appear to have damaged the runway enough to make it unusable, preventing Russian forces from airlifting troops directly onto Kyiv’s western flank and causing Russian forces to reprioritize the eastern axis of advance.
Russian reconnaissance and sabotage units, many reportedly operating in civilian clothes or captured Ukrainian uniforms, are reportedly active in central Kyiv. A Ukrainian Deputy Defense Minister reported Russian forces seized two Ukrainian trucks to break through Ukrainian lines into central Kyiv around noon local time.
[10]
The Ukrainian General Staff warned at 5:00 pm local time that Russian units in civilian clothes are operating in several unspecified Ukrainian cities.
[11]
President Zelensky, his Chief of Staff, and Prime Minister Shmyhal released a video from downtown Kyiv at 8:00 pm local time on February 25 stating “we are all here, defending our independence.”
[12]
The Ukrainian military reported it redeployed unspecified units to assist in the defense of Kyiv.
[13]
ISW cannot currently confirm the extent of Ukrainian preparations to conduct urban fighting in Kyiv.
2)     Kharkiv axis: Russian forces will likely envelop Kharkiv in the next 24 hours after failing to enter the city through frontal assaults on February 24. Russian forces are now advancing on a broad front along the northeastern Ukrainian border as of February 25.
Kharkiv civil authorities reported Russian forces entering the outskirts of Kharkiv from several directions at 9:00 pm local time.
[14]
Elements of Russia’s 25th Separate Guards Motor Rifle Brigade, part of the 6th Combined Arms Army and permanently deployed near St Petersburg, are confirmed to be active in Kharkiv.
[15]
Russian forces have reportedly crossed the northeastern Ukrainian border at several other points both west of Kharkiv, including Okhtyrka and Sumy.
[16]
Russian forces are likely advancing toward Kyiv on a broad front and may seek to envelop and isolate Kharkiv.
3)     Donbas axis: Russian forces have achieved little success on the frontal assaults or the envelopment but may not have intended to do more than pin Ukrainian forces in the east.  The Russians have not weighted their ground offensive efforts toward breaking through Ukrainian defensive positions on the line of contact, taking Mariupol from the east, or driving rapidly through Luhansk Oblast to the north. Ukrainian forces remain largely in their original defensive positions in the east. The Russians may be content to leave them there while concentrating on capturing Kyiv and imposing a new government on Ukraine. They may alternatively seek to envelop and destroy Ukrainian forces at and near the line of contact at a later date.
Russian forces have been unable to continue an enveloping maneuver through Donetsk Oblast as of 4:00 pm local time February 25.
[17]
They have not apparently reinforced their efforts to do so, however, suggesting that they may not be very determined to make rapid progress on this axis as long as Ukrainian forces remain in defensive positions.  Ukrainian forces report undergoing continuous shelling.
Ukrainian forces claim to continue to hold the entire line of contact in Donetsk and Luhansk as of 1pm local time February 25.
[18]
Russian forces are likely conducting a frontal assault on Mariupol from the northeast. The mayor of Mariupol claimed Ukrainian forces destroyed twenty-two Russian tanks advancing from Pavlopil at 4:00 pm local time on February 25.
[19]
Russian sources reported shelling Mariupol with MLRS systems at 7:00 pm local time on February 25.
[20]
4)
Crimea axis: Russian forces fully captured Kherson and are likely on the verge of seizing Melitopol in the east. Unconfirmed reports indicate that Russian forces had bypassed Kherson earlier and headed directly for Mykolaiv and Odessa.
Russian forces reportedly captured Kherson at 6:00 pm local time on February 25.
[21]
Elements of the Russian 42nd Motor Rifle Division of the 58th Combined Arms Army and unknown VDV (Airborne) elements are confirmed to be active in Kherson.
[22]
Russian forces are advancing west of Kherson and reportedly bypassed it early February 25 before its capture by follow-on Russian forces later in the day. Ukrainian forces destroyed at least one bridge over the Dnipro to slow Russian forces.
[23]
The Ukrainian Ministry of Defense reported Russian forces are advancing on Mykolaiv.
[24]
ISW cannot confirm the current depth of Russian advances.
Russian forces may have captured Melitopol, east of Crimea, late on February 25. Ukrainian forces reported defending the city at 10:00 am local time February 25.
[25]
Russian forces claimed to have captured the city as of 6:00 pm local time.
[26]
The Ukrainian General Staff reported that Russia is deploying second echelon troops to Kherson on February 25. If confirmed, this is the first Russian deployment of second-line troops into Ukrainian territory.
[27]
ISW cannot confirm any Russian amphibious landings as of 3:00 pm EST. Several Western sources misreported a quote from an anonymous US official that there are indications of Russia’s capability to conduct an amphibious assault west of Mariupol with thousands of troops as meaning a landing had already occurred.
[28]
Russia may wait until forces from Crimea have fully secured crossings over the Dnipro River or gotten closer to Odesa before attempting to seize Odesa by air and sea.
Immediate items to watch
Social media users observed a Russian armored column assembling in Stolin, Belarus, on February 25.
[29]
These forces could potentially conduct a new line of advance against Rivne in western Ukraine.
Russian Naval Infantry have not yet conducted amphibious landings but retain the capability to do so against the Odesa or the Azov Sea coasts or both.
Russian forces continue to refrain from using their likely full spectrum of air and missile capabilities. The Ukrainian air force also remains active. Russian operations will likely steadily wear down Ukrainian air capabilities and eventually take the Ukrainian air force out of the fight.
Russian forces have not yet attempted the decapitation strike several analysts and outlets have forecasted and may attempt to do so in the near future.
Russia has sufficient conventional military power to reinforce each of its current axes of advance and overpower the conventional Ukrainian forces defending them.
[1]
https://understandingwar.org/backgrounder/putin%E2%80%99s-likely-course-action-ukraine-updated-course-action-assessment
; https://understandingwar.org/report/putins-likely-courses-action-ukraine-part-2.
[2]
https://twitter.com/b_judah/status/1497023156409700355?s=20&t=Yt–CdSsmBHsHAroR7Dd8g
;
https://twitter.com/DefenceHQ/status/1497206130820407299?s=20&t=Yt–CdSsmBHsHAroR7Dd8g
; https://twitter.com/DefenceHQ/status/1497015621082624003?s=20&t=Yt–CdSsmBHsHAroR7Dd8g
[3]
https://www.facebook.com/GeneralStaff.ua/posts/258795543100198
.
[4]
https://twitter.com/BabakTaghvaee/status/1497213543837544449; https://twitter.com/RALee85/status/1497141937035489283.
[5]
https://www.facebook.com/GeneralStaff.ua/posts/258784753101277.
[6]
https://www.militarynews dot ru/story.asp?rid=1&nid=568376&lang=RU
[7]
https://www.facebook.com/GeneralStaff.ua/posts/258795543100198
; https://www.facebook.com/CinCAFU/posts/255380563424103.
[8]
https://twitter.com/cfmalloy/status/1497279955767488512?s=20&t=uaBHm3j28_KNZ3oArU9ixA.
[9]
https://www.facebook.com/GeneralStaff.ua/posts/258795543100198.
[10]
https://twitter.com/antiputler_news/status/1497104623798304770.
[11]
https://www.facebook.com/GeneralStaff.ua/posts/258997149746704.
[12]
https://twitter.com/PaulSonne/status/1497270954321489920?s=20&t=uaBHm3j28_KNZ3oArU9ixA.
[13]
https://www.facebook.com/watch/?v=702750714218225.
[14]
https://www.rbc dot ua/ukr/styler/situatsiya-harkove-pryamo-seychas-proishodit-1645692584.html
[15]
https://twitter.com/CITeam_ru/status/1496895748394336259?s=20&t=PQu08CRF5nurw66tFc-orA.
[16]
https://www.zsu.gov dot ua/new_page/6217e45a4909af00130a405a.
[17]
https://www.facebook.com/GeneralStaff.ua/posts/258795543100198.
[18]
https://www.facebook.com/GeneralStaff.ua/posts/258943416418744; https://www.facebook.com/GeneralStaff.ua/posts/258943416418744.
[19]
https://twitter.com/BackAndAlive/status/1497204751502614531?s=20&t=KCi4mM6difJZ2Hr23OcXsA.
[20]
https://twitter.com/michaelh992/status/1497249328217395200?s=20&t=kjW399ml6Db66SQmmYg68g.
[21]
https://twitter.com/BackAndAlive/status/1497240248081948692
; https://www.zsu.gov dot ua/new_page/6217e45a4909af00130a405a.
[22]
https://twitter.com/Osinttechnical/status/1497108874461016066
; https://twitter.com/CITeam_ru/status/1497166561186099227.
[23]
https://www.zsu.gov dot ua/new_page/6218981f4909af0013119d07;
[24]
https://www.zsu.gov dot ua/new_page/6217e45a4909af00130a405a.
[25]
https://www.facebook.com/GeneralStaff.ua/posts/258795543100198.
[26]
https://twitter.com/IntelCrab/status/1497243193271857155
; https://topwar dot ru/192752-svodka-o-sobytijah-na-ukraine-po-sostojaniju-na-vecher-25-fevralja.html; https://twitter.com/RALee85/status/1497138209251155969; https://twitter.com/RALee85/status/1497135346387148820.
[27]
https://www.facebook.com/GeneralStaff.ua/posts/258943416418744.
[28]
https://twitter.com/phildstewart/status/1497244545247059993?s=20&t=ZuNbHx_g_ryMKIEYHYkbBQ.
[29]
https://twitter.com/konrad_muzyka/status/1497115295512776711; https://twitter.com/MotolkoHelp/status/1497108720953835543.
Previous
Next

====================================================================================================

=== CLEAN TEXT:

In [15]:
df_isw["text"] = df_isw["text_clean"]
df_isw = df_isw.drop(columns=["text_clean"])

In [16]:
df_isw.head()

,date,title,url,text
0,2022-02-25,Russia-Ukraine Warning Update: Russian Offensi...,https://understandingwar.org/research/russia-u...,Russia-Ukraine Warning Update: Russian Offens...
1,2022-02-26,Russia-Ukraine Warning Update: Russian Offensi...,https://understandingwar.org/research/russia-u...,Russia-Ukraine Warning Update: Russian Offens...
2,2022-02-27,Russia-Ukraine Warning Update: Russian Offensi...,https://understandingwar.org/research/russia-u...,Russia-Ukraine Warning Update: Russian Offens...
3,2022-02-28,"Russian Offensive Campaign Assessment, Februar...",https://understandingwar.org/research/russia-u...,"Russian Offensive Campaign Assessment, Februa..."
4,2022-03-01,"Russian Offensive Campaign Assessment, March 1...",https://understandingwar.org/research/russia-u...,"Russian Offensive Campaign Assessment, March ..."

## IV. Prepare data